### ISSUE TITLE
RemoteService invoke very fast,the remoteServer register point has a warn,what wrong is it?

### ISSUE THREAD

**Issue by wilesun** [redisson/redisson#1000]
I do a RemoteService invoke test,it report a warn,then the remote client wait timeout.what wrong is it?

```code
2017-08-11 15:43:40,699 [redisson-3-2] WARN  [io.netty.util.concurrent.DefaultPromise] - An exception was thrown by org.redisson.command.CommandAsyncService$13.operationComplete()
java.lang.NullPointerException: null
	at org.redisson.command.CommandAsyncService$13.operationComplete(CommandAsyncService.java:707) ~[redisson-3.5.0.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.DefaultPromise.cancel(DefaultPromise.java:315) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:228) [redisson-3.5.0.jar:?]
	at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:287) [redisson-3.5.0.jar:?]
	at org.redisson.RedissonRemoteService.access$400(RedissonRemoteService.java:59) [redisson-3.5.0.jar:?]
	at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:239) [redisson-3.5.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by mrniko** [comment]
Is there any code example how to reproduce it?

**Comment by drejc** [comment]
I'm seeing the same behaviour when running 30 tasks at once on a MASTER/SLAVE setup.
```
WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.command.CommandAsyncService$14.operationComplete()
java.lang.NullPointerException: null
	at org.redisson.command.CommandAsyncService$14.operationComplete(CommandAsyncService.java:751)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.cancel(DefaultPromise.java:315)
	at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:228)
	at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:287)
	at org.redisson.RedissonRemoteService.access$400(RedissonRemoteService.java:59)
	at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

It happens when a task successfully finishes and returns it's result. 
The tasks are invoked like this:
`List<Future<String>> futures = executorService.invokeAll(tasks);`

The task executor is created like this:
```
RedissonNodeConfig nodeConfig = new RedissonNodeConfig(redissonClient.getConfig());
		nodeConfig.setExecutorServiceWorkers(Collections.singletonMap(RedisCleaner.TASK_EXECUTOR, 50)); // 50 task executor per node

RedissonNode node = RedissonNode.create(nodeConfig);
node.start();

executorService = redisson.getExecutorService(TASK_EXECUTOR);
```

**Comment by mrniko** [comment]
@drejc What is the Redisson version you use?

**Comment by drejc** [comment]
We are using the latest version: 3.5.4

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/99d515c19be42eca71b31e469ac13edcf633c396

**Comment by drejc** [comment]
Cool ... what's the plan for the next release?

**Comment by mrniko** [comment]
@drejc a week or so
