### ISSUE TITLE
Config.fromJSON thow an exception

### ISSUE THREAD

**Issue by battlesteed** [redisson/redisson#1016]
the redisson version is 3.5.0,
follow is the StackTrace

java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.setFilterProvider(Lcom/fasterxml/jackson/databind/ser/FilterProvider;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at org.redisson.config.ConfigSupport.createMapper(ConfigSupport.java:281)
	at org.redisson.config.ConfigSupport.<init>(ConfigSupport.java:124)
	at org.redisson.config.Config.fromJSON(Config.java:639)
	at org.redisson.config.Config.fromJSON(Config.java:651)
	at steed.util.redis.RedissonUtil.<clinit>(RedissonUtil.java:18)
	at steed.test.redis.TestRedisson.testDataCacheUtil(TestRedisson.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

my config code is this:

     Config.fromJSON(new File(PathUtil.praseRelativePath("properties/redisson.json")));

the follow is a part of maven downed redisson source code

      mapper.addMixIn(MasterSlaveServersConfig.class, MasterSlaveServersConfigMixIn.class);
      FilterProvider filterProvider = new SimpleFilterProvider().addFilter("classFilter", SimpleBeanPropertyFilter.filterOutAllExcept());
      mapper.setFilterProvider(filterProvider);//this line throw the exception

then i copy this code to eclipse ,and eclipse report an Compile error like follow:
    ` The method setFilterProvider(FilterProvider) is undefined for the type ObjectMapper`

so I think there is some problem in the jar of 3.5.0 version

**Comment by battlesteed** [comment]
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://127.0.0.1:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":10,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoring":false,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
   	"class":"org.redisson.codec.KryoCode.class"
   },
   "useLinuxNativeEpoll":false
}

**Comment by battlesteed** [comment]
Above is my config file

**Comment by battlesteed** [comment]
I want to describe the problem more clearer by using picture,but it seems the China network can not upload picture to github,sorry

**Comment by mrniko** [comment]
Hi! Please check your classpath for correct Jackson lib version. It should be 2.7+ Or it could be a interference  of two different Jackson versions in classpath.

**Comment by battlesteed** [comment]
thank you,the problem was resolved. follow is my maven code,hope it is helpful for someone who encounter the same problem.

`<dependency>
	   <groupId>com.fasterxml.jackson.core</groupId>
	   <artifactId>jackson-core</artifactId>
	   <version>2.7.9</version>
	</dependency>
	 <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>2.7.9</version>
         <exclusions>
		   <exclusion>
	        <groupId>com.fasterxml.jackson.core</groupId>
	        <artifactId>jackson-core</artifactId>
	      </exclusion>
		   <exclusion>
		   <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
	      </exclusion>
	   </exclusions>
      </dependency>
       <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>2.7.9</version>
      </dependency>
	
	<dependency>
	   <groupId>org.redisson</groupId>
	   <artifactId>redisson</artifactId>
	   <version>3.5.0</version>
	   <exclusions>
		   <exclusion>
	        <groupId>com.fasterxml.jackson.core</groupId>
	        <artifactId>jackson-core</artifactId>
	      </exclusion>
		   <exclusion>
	        <groupId>com.fasterxml.jackson.core</groupId>
	        <artifactId>jackson-databind</artifactId>
	      </exclusion>
	   </exclusions>
	</dependency>  `
