### ISSUE TITLE
class 'LoadBalancerManager' in  version 2.10.1  may cause the NullpointException in method 'returnConnection'

### ISSUE THREAD

**Issue by bryan31** [redisson/redisson#1031]
i updated the version to 2.10.1 in my project.
when i use **redissonClient.getBucket("thekey").isExists()**,some exception happen:
`java.lang.NullPointerException
	at org.redisson.connection.pool.ConnectionPool.returnConnection(ConnectionPool.java:441)
	at org.redisson.connection.pool.SlaveConnectionPool.returnConnection(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.returnConnection(LoadBalancerManager.java:210)
	at org.redisson.connection.MasterSlaveEntry.releaseRead(MasterSlaveEntry.java:459)
	at org.redisson.connection.MasterSlaveConnectionManager.releaseRead(MasterSlaveConnectionManager.java:770)
	at org.redisson.command.CommandAsyncService$14.operationComplete(CommandAsyncService.java:732)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:65)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:322)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:261)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:103)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)`

i found the code in class LoadBalancerManager

```java
   public void returnConnection(RedisConnection connection) {
        ClientConnectionsEntry entry = ip2Entry.get(connection.getRedisClient().getAddr().getAddress().getHostAddress());
        slaveConnectionPool.returnConnection(entry, connection);
    }
```
the code **connection.getRedisClient().getAddr().getAddress().getHostAddress()** returns ip address, but the map **ip2Entry** need the key: ip + port。so null is returned

**Comment by mrniko** [comment]
It's a bug! Thanks for report

**Comment by mrniko** [comment]
Fixed

**Comment by mrniko** [comment]
Please rollback to 2.10.0/3.5.0 for now. While I'm finishing work on next version
