### ISSUE TITLE
Redisson 3.5.1 NullPointerException in Sentinel mode - Not working at all

### ISSUE THREAD

**Issue by abel98** [redisson/redisson#1052]
We just upgraded our redisson library from 3.3.2 to 3.5.1. Our application has no problems when run in a single Redis server mode or with 3.3.2, but when we run it in a sentinel mode with 3.5.1 it does not work at all, constantly generating error messages. Our sentinel cluster consists of 3 servers (master and 2 slaves) and 5 sentinel clients. Redis version :3.2.8. Here is example of error log
```
49022 13 Sep 2017 22:09:53 +0000 [qtp786041152-21] INFO  org.redisson.Version - Redisson 3.5.1
49241 13 Sep 2017 22:09:54 +0000 [qtp786041152-21] INFO  o.r.c.SentinelConnectionManager - master: redis://172.30.1.87:6379 added
49251 13 Sep 2017 22:09:54 +0000 [qtp786041152-21] INFO  o.r.c.SentinelConnectionManager - slave: redis://172.30.0.8:6379 added
49251 13 Sep 2017 22:09:54 +0000 [qtp786041152-21] INFO  o.r.c.SentinelConnectionManager - slave: redis://172.30.1.206:6379 added
49292 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-4] INFO  o.r.c.pool.SlaveConnectionPool - 10 connections initialized for /172.30.0.8:6379
49292 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-3] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for /172.30.1.206:6379
49292 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-3] INFO  o.r.c.pool.SlaveConnectionPool - 10 connections initialized for /172.30.1.206:6379
49292 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-3] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for /172.30.0.8:6379
49300 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-3] INFO  o.r.c.pool.MasterConnectionPool - 10 connections initialized for /172.30.1.87:6379
49313 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-1] INFO  o.r.c.SentinelConnectionManager - sentinel: 172.30.0.8:26379 added
49316 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-3] INFO  o.r.c.SentinelConnectionManager - sentinel: 172.30.1.206:26379 added
49840 13 Sep 2017 22:09:54 +0000 [redisson-netty-1-3] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.command.CommandAsyncService$14.operationComplete()
java.lang.NullPointerException: null
        at org.redisson.connection.pool.ConnectionPool.returnConnection(ConnectionPool.java:441)
        at org.redisson.connection.pool.SlaveConnectionPool.returnConnection(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.returnConnection(LoadBalancerManager.java:210)
        at org.redisson.connection.MasterSlaveEntry.releaseRead(MasterSlaveEntry.java:459)
        at org.redisson.connection.MasterSlaveConnectionManager.releaseRead(MasterSlaveConnectionManager.java:770)
        at org.redisson.command.CommandAsyncService$14.operationComplete(CommandAsyncService.java:732)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:78)
        at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:322)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:253)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:103)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)

```
Here is our Sentinel info
```
# Server
redis_version:3.2.8
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:79ea7151812d6ea4
redis_mode:sentinel
os:Linux 4.4.51-40.58.amzn1.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.8.3
process_id:27343
run_id:c42dedde7048b62d9163b65b330834e01cda4231
tcp_port:26379
uptime_in_seconds:14205790
uptime_in_days:164
hz:18
lru_clock:12177654
executable:/usr/local/bin/redis-server
config_file:/etc/redis/sentinel.conf

# Clients
connected_clients:5
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# CPU
used_cpu_sys:15195.70
used_cpu_user:11351.15
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Stats
total_connections_received:21
total_commands_processed:66455494
instantaneous_ops_per_sec:4
total_net_input_bytes:3763710843
total_net_output_bytes:398315069
instantaneous_input_kbps:0.30
instantaneous_output_kbps:0.03
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0

# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=xxxxxx,status=ok,address=172.30.1.87:6379,slaves=2,sentinels=6
```

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1031

Please update to latest version
