### ISSUE TITLE
[Redisson 3.5.3] MR Collator Nullpoint Error

### ISSUE THREAD

**Issue by Godson2017** [redisson/redisson#1053]
Classes:
1、Main:
		RedissonClient redisson = Redisson.create(config);
		RMap<String, String> map = redisson.getMap("wordsMap");
		map.put("line1", "Alice was beginning to get very tired");
		map.put("line2", "of sitting by her sister on the bank and");
		map.put("line3", "of having nothing to do once or twice she");
		map.put("line4", "had peeped into the book her sister was reading");
		map.put("line5", "but it had no pictures or conversations in it");
		map.put("line6", "and what is the use of a book");
		map.put("line7", "thought Alice without pictures or conversation");
		RMapReduce<String, String, String, Integer> mapReduce = map.<String, Integer>mapReduce().mapper(new WordMapper()).reducer(new WordReducer()).timeout(60, TimeUnit.MINUTES);
		// count occurrences of words
		Map<String, Integer> mapToNumber = mapReduce.execute();
		System.out.println("mapToNumber=" + mapToNumber);		
               // count total words amount
		Integer totalWordsAmount = mapReduce.execute(new WordCollator());
		System.out.println("totalWordsAmount=" + totalWordsAmount);

2、public class WordCollator implements RCollator<String, Integer, Integer> {
    public Integer collate(Map<String, Integer> resultMap) {
        int result = 0;
        for (Integer count : resultMap.values()) {
            result += count;
        }
        return result;
    }   
}
3、WordMapper：    
public void map(String key, String value, RCollector<String, Integer> collector) {
        String[] words = value.split("[^a-zA-Z]");
        for (String word : words) {
            collector.emit(word, 1);
        }
    }
4、WordReducer：
	public Integer reduce(String reducedKey, Iterator<Integer> values) {
        int sum = 0;
        while (values.hasNext()) {
           Integer i = (Integer) values.next();
           sum += i;
        }
        return sum;
	}

Result as following: mapReduce.execute(new WordCollator()) is error.
[main] INFO org.redisson.Version - Redisson 3.5.3
[redisson-netty-1-5] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for /11.1.1.1:7379
[redisson-netty-1-6] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /11.1.1.1:7379
mapToNumber={sitting=1, Alice=2, beginning=1, by=1, to=2, was=2, her=2, and=2, tired=1, the=3, had=2, sister=2, once=1, peeped=1, bank=1, reading=1, into=1, she=1, but=1, no=1, pictures=2, it=2, thought=1, conversations=1, what=1, without=1, in=1, conversation=1, use=1, a=1, get=1, very=1, of=3, on=1, having=1, nothing=1, do=1, or=3, twice=1, book=2, is=1}
Exception in thread "main" org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:322)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165)
	at org.redisson.mapreduce.MapReduceExecutor.execute(MapReduceExecutor.java:156)
	at org.redisson.mapreduce.RedissonMapReduce.execute(RedissonMapReduce.java:38)
	at org.redisson.example.mr.Test.main(Test.java:34)
Caused by: java.lang.IllegalArgumentException: java.lang.NullPointerException
	at .executeCallable(TasksRunnerService.java:183)
	at .executeCallable(TasksRunnerService.java:163)
	at .invoke0(Native Method)
	at .invoke(NativeMethodAccessorImpl.java:62)
	at .invoke(DelegatingMethodAccessorImpl.java:43)
	at .invoke(Method.java:498)
	at .invokeMethod(RedissonRemoteService.java:276)
	at .access$400(RedissonRemoteService.java:59)
	at .run(RedissonRemoteService.java:239)
	at .call(Executors.java:511)
	at .run(FutureTask.java:266)
	at .runWorker(ThreadPoolExecutor.java:1142)
	at .run(ThreadPoolExecutor.java:617)
	at .run(DefaultThreadFactory.java:138)
	at .run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at .executeCollator(CoordinatorTask.java:147)
	at .call(CoordinatorTask.java:129)
	at .executeCallable(TasksRunnerService.java:176)
	... 14 more

**Comment by Godson2017** [comment]
@mrniko If use MR to compute, is there any test data for reference？Thank you!

**Comment by mrniko** [comment]
Fixed
