### ISSUE TITLE
Use map,when some value be null,can't get from redis server,and can't set to redis server too

### ISSUE THREAD

**Issue by zxj19951029** [redisson/redisson#1060]
Because map use the jaskson codec,it seem can't resove empty value.But redis server support it.
How can i do this?

也就是说，缓存map的时候，不能有相应的空值，所以我之前使用jedis客户端存进去的值，部分为Null的会取不出来，

Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'language': was expecting ('true', 'false' or 'null')
 at [Source: io.netty.buffer.ByteBufInputStream@535b8c24; line: 1, column: 17]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3464)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2628)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:854)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:748)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:87)

**Comment by mrniko** [comment]
Could you share your code?

**Comment by jackygurui** [comment]
Can you share your data in redis too?

**Comment by zxj19951029** [comment]
@jackygurui 
![tim 20170918225741](https://user-images.githubusercontent.com/18377791/30548539-01fd0f56-9cc5-11e7-8817-1bf4dae4cd84.png)

like it

**Comment by jackygurui** [comment]
@zxj19951029 I see, thanks for the screenshot.

By the default Jackson configuration, it requires the content to be a `VALID` JSON format, that means a string needs to be quoted with `"`, so in your case if you can change the empty string in to `""`, it would be OK.

Alternatively, you can use tell Redisson to use StringCodec like you did with Jedis. So that Jackson won't be trying to deserialise an illegal JSON string and throws an error again.

**Comment by mrniko** [comment]
Or you could try any other [available codec](https://github.com/redisson/redisson/wiki/4.-data-serialization)

**Comment by zxj19951029** [comment]
Okey! thanks for your answer! I will try it.

Another irrelevant little problem,Does the deveploment team have chinese,i see the chineses document!
very thank you very much for this document!

**Comment by jackygurui** [comment]
@zxj19951029 我以为我的头像已经很明显了。

**Comment by zxj19951029** [comment]
![image](https://user-images.githubusercontent.com/18377791/30550128-20a99ee8-9cc9-11e7-9131-2132005add99.png)

真没注意到
