### ISSUE TITLE
Use host alias throw Exception when alias contain ‘_’

### ISSUE THREAD

**Issue by vickze** [redisson/redisson#1066]
My host alias is redis_db, test found that contain ‘_’  will throw this Exception.

Caused by: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'address' threw exception; nested exception is java.lang.IllegalArgumentException: Malformed IPv6 address at index 9: redis://[redis_db]:6379
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:108)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:62)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1490)
	... 38 more

**Comment by vickze** [comment]
![fc 8h twprn _03z mtzb](https://user-images.githubusercontent.com/19652735/30643314-f71f9428-9e40-11e7-923a-d69b7d85a6ac.png)
