### ISSUE TITLE
redisson throw exception 'Exception in thread "redisson-3-10" java.lang.ArrayIndexOutOfBoundsException: 1'

### ISSUE THREAD

**Issue by welove312** [redisson/redisson#1069]
redisson running on tomcat.The program is working.redisson throw exception few minutes,
`Exception in thread "redisson-3-10" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:259)
	at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:50)
	at org.redisson.PubSubPatternMessageListener.onPatternMessage(PubSubPatternMessageListener.java:80)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:86)
	at org.redisson.client.handler.CommandDecoder$1.run(CommandDecoder.java:368)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jackygurui** [comment]
Which version of Redisson are you using?

**Comment by welove312** [comment]
The version of Resisson is 2.8.1

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/df7de8b4320684cad65aa4fea8920434148b5027
