### ISSUE TITLE
Upgrade from 3.4.2 to 3.5.3

### ISSUE THREAD

**Issue by sheldon-sminq** [redisson/redisson#1079]
We have been using Redisson successfully for the past few months, since our version was pretty old we just tried and upgrade to the latest version today.

With version 3.4.2 we used  SnappyCodec as follows

```
SnappyCodec snappyCodec = new SnappyCodec(new StringCodec());
  Config config = new Config();
 config.useSingleServer().setAddress(DynamicApplicationConfig.getStringProperty("REDIS_SERVER","localhost")+":6379");
  config.setCodec(snappyCodec);
  redissonClient = Redisson.create(config);
```

This setup fails with the new 3.5.3 version

```
`org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:322)
 at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165) at org.redisson.RedissonObject.get(RedissonObject.java:72) 
at org.redisson.RedissonMap.get(RedissonMap.java:251)`
```

Example client usage

```
String key = namespace + ":" + id;
                RMap<String, Object> cachedMap = redissonClient.getMap(cacheGroup);
                ObjectWriter writer = mapper.writer();
                cachedMap.fastPutAsync(key, writer.writeValueAsString(data));
```

With so many release since 3.4.2, many other codecs have been added. We store JSON string so which is the best codec to use for this case?.

**Comment by mrniko** [comment]
Sorry, I didn't get what exactly the problem is?

Your code could be rewritten as follow:
```java
// uses StringCodec for key and JacksonJsonCodec for value
Codec codec = new CompositeCodec(new StringCodec(), new JacksonJsonCodec());
RMap<String, Object> cachedMap = redissonClient.getMap(cacheGroup, codec);
// you shouldn't serialize data manually anymore
cachedMap.fastPutAsync(key, data);
```

**Comment by sheldon-sminq** [comment]
There is some conversion issue when using the SnappyCodec in the newer version 3.5.3

```
RMap<String, Object> cachedMap = redissonClient.getMap(cacheGroup,codec);
```
fails with the this exception

```
Unexpected exception while processing command
stacktrace:at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:322)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165)
	at org.redisson.RedissonObject.get(RedissonObject.java:72)
	at org.redisson.RedissonMap.get(RedissonMap.java:251)
```

Will try the changes you have recommended.

**Comment by mrniko** [comment]
`SnappyCodec` now uses internal netty's implementation without external lib. I think you're getting this problem since it's not compatible with previous version used by Redisson.

**Comment by sheldon-sminq** [comment]
Thanks for the details, was just trying out the changes you recommended.

```
RMap<String, Object> cachedMap = redissonClient.getMap(cacheGroup,codec);
        return cachedMap.get(key);
```
How does the deserialisation work for the get? does it return the data as string how do i convert the returned value to my object? the following exception is thrown now.

```
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:322)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165)
	at org.redisson.RedissonObject.get(RedissonObject.java:72)
	at org.redisson.RedissonMap.get(RedissonMap.java:251)
	at com.sminq.kernel.clients.cache.DistributedRedisMapClient.getObjectFromCacheMap(DistributedRedisMapClient.java:68)
	at com.sminq.kernel.processor.queue.QueuePool.getFromPool(QueuePool.java:84)
	at com.sminq.kernel.processor.queue.QueueManager.getQueue(QueueManager.java:50)
	at com.sminq.kernel.processor.queue.event.subscriber.QueueLiveFeedEventHandler.onEvent(QueueLiveFeedEventHandler.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@class' that is to contain type id  (for class java.lang.Object)
 at [Source: io.netty.buffer.ByteBufInputStream@7ebb9143; line: 1, column: 73503]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1061)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:147)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:87)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:259)
```

**Comment by mrniko** [comment]
> How does the deserialisation work for the get? 

JacksonJsonCodec will be used for it. Your trace shows that you need to pass custom ObjectMapper object to it.

**Comment by sheldon-sminq** [comment]
Thanks for that info, the problem we now have we cannot easily switch to the JacksonJsonCodec as all our redis data is compressed using SnappyCodec and the deserialization fails with errors related to utf8

```
 Invalid UTF-8 middle byte 0x22
!  at [Source: io.netty.buffer.ByteBufInputStream@4d7a50c9; line: 1, column: 5]
! at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
! at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
! at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3482)
! at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeCharForError(UTF8StreamJsonParser.java:3228)
! at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3454)
! at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2624)
! at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:854)
```

Will do some more research on the SnappyCodec changes, thanks for all the help.

**Comment by brijnkh** [comment]
@sheldon-sminq  could you find any solution with utf-8?
