### ISSUE TITLE
MasterConnectionPool no available Redis entries.

### ISSUE THREAD

**Issue by tianyangyang427** [redisson/redisson#1092]
org.redisson.client.RedisConnectionException: MasterConnectionPool no available Redis entries.  Hosts disconnected due to `failedAttempts` limit reac
hed: [/192.168.10.109:6459]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:196) ~[redisson-2.9.3.jar:?]
        at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:31) ~[redisson-2.9.3.jar:?]
        at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:409) ~[redisson-2.9.3.jar:?]
        at org.redisson.connection.SingleEntry.connectionReadOp(SingleEntry.java:45) ~[redisson-2.9.3.jar:?]
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:745) ~[redisson-2.9.3.jar:?]
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:500) ~[redisson-2.9.3.jar:?]
        at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:551) ~[redisson-2.9.3.jar:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663) ~[netty-common-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738) ~[netty-common-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466) ~[netty-common-4.1.11.Final.jar:4.1.11.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_60]

**Comment by mrniko** [comment]
This issue fixed in https://github.com/redisson/redisson/pull/1078 Please try 2.10.4 release.
