### ISSUE TITLE
Redisson Client cannot link properly after the master - slave relationship changes

### ISSUE THREAD

**Issue by tianyangyang427** [redisson/redisson#1093]
Redis cluster, when the master-slave relationship changes, the Redisson Client links to the original master node and cannot link the changed master node, resulting in no data write.

WARN io.netty.util.concurrent.DefaultPromise: An exception was thrown by org.redisson.command.CommandAsyncService$9.operationComplete()
org.redisson.client.RedisNodeNotFoundException: Node: /192.168.16.118:10377 

 for slot: 5997 hasn't been discovered yet
        at org.redisson.connection.MasterSlaveConnectionManager.getEntry(MasterSlaveConnectionManager.java:684) ~[redisson-2.9.1.jar:?]
        at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:674) ~[redisson-2.9.1.jar:?]
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:503) ~[redisson-2.9.1.jar:?]
        at org.redisson.command.CommandAsyncService.checkAttemptFuture(CommandAsyncService.java:751) ~[redisson-2.9.1.jar:?]
        at org.redisson.command.CommandAsyncService.access$300(CommandAsyncService.java:80) ~[redisson-2.9.1.jar:?]
        at org.redisson.command.CommandAsyncService$9.operationComplete(CommandAsyncService.java:610) ~[redisson-2.9.1.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) [netty-common-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500) [netty-common-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479) [netty-common-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) [netty-common-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122) [netty-common-4.1.8.Final.jar:4.1.8.Final]
at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:75) [redisson-2.9.1.jar:?]
        at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:78) [redisson-2.9.1.jar:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:247) [redisson-2.9.1.jar:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127) [redisson-2.9.1.jar:?]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367) [netty-codec-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-common-4.1.8.Final.jar:4.1.8.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

**Comment by mrniko** [comment]
Fixed in this commit https://github.com/redisson/redisson/commit/c7f327d95d1ba62012679d3bc1b26eb5f3808e73 for 2.10.4 version
