### ISSUE TITLE
redisson not handling failover in sentinel mode

### ISSUE THREAD

**Issue by Rowen123** [redisson/redisson#1095]
Hello, i'm new to redisson and using version 2.10.4. Assume that i have a master node M1 and a slave node R1. 3 sentinels are connected to M1 namely, S1,S2,S3. I have connected Redisson to the 3 sentinels and started inserting data. Following is my code:

```
static RMap<Object, String> map = null;
		static String resp = null;
		Config config = new Config();
		config.useSentinelServers().setMasterName("mymaster")
									.addSentinelAddress("redis://0.0.0.82:5001")
									.addSentinelAddress("redis://0.0.0.82:5002")
									.addSentinelAddress("redis://0.0.0.35:5003")
									.setIdleConnectionTimeout(10000)
									.setPingTimeout(1000)
									.setConnectTimeout(10000)
									.setTimeout(20000)
									.setRetryAttempts(3)
									.setRetryInterval(1500)
									.setReconnectionTimeout(3000)
									.setFailedAttempts(3)
									.setSlaveConnectionMinimumIdleSize(20)
									.setSlaveConnectionPoolSize(64)
									.setMasterConnectionMinimumIdleSize(20)
									.setMasterConnectionPoolSize(64)
									.setDatabase(0);
		RedissonClient redisson = Redisson.create(config);
		map = redisson.getMap("My-Map");
		map.clear();
		for(int i=0;i<1000000;i++) {
			resp = map.put("key"+i,"value"+i);
			System.out.println(resp+" for key "+"key"+i);
		}
		redisson.shutdown();
```

In the middle of insertion, i kill M1, so insertion interrupted. So the sentinels make R1 as the new master. Redisson identifies that R1 has been made the new master, but it doesn't continue inserting the data to the new master rather it throws a server response timeout exception.
Following is the stacktrace:

```
[main] INFO org.redisson.Version - Redisson 2.10.4
[main] INFO org.redisson.connection.SentinelConnectionManager - master: redis://0.0.0.35:6385 added
[main] INFO org.redisson.connection.SentinelConnectionManager - slave: redis://0.0.0.82:6382 added
[redisson-netty-1-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 20 connections initialized for /0.0.0.82:6382
[redisson-netty-1-5] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /0.0.0.82:6382
[redisson-netty-1-4] INFO org.redisson.connection.pool.MasterConnectionPool - 20 connections initialized for /0.0.0.35:6385
[redisson-netty-1-7] INFO org.redisson.connection.SentinelConnectionManager - sentinel: 0.0.0.82:5001 added
[redisson-netty-1-2] INFO org.redisson.connection.SentinelConnectionManager - sentinel: 0.0.0.82:5002 added
[redisson-netty-1-3] INFO org.redisson.connection.SentinelConnectionManager - sentinel: 0.0.0.35:5003 added
null
null
null
null
null
null
null
[redisson-3-3] INFO org.redisson.connection.MasterSlaveEntry - master /0.0.0.82:6382 excluded from slaves
[redisson-3-3] INFO org.redisson.connection.SentinelConnectionManager - slave: 0.0.0.35:6385 has up
[redisson-3-5] INFO org.redisson.connection.MasterSlaveEntry - master /0.0.0.82:6382 excluded from slaves
[redisson-3-5] INFO org.redisson.connection.SentinelConnectionManager - slave: 0.0.0.35:6385 has up
[redisson-3-4] INFO org.redisson.connection.MasterSlaveEntry - master /0.0.0.82:6382 excluded from slaves
[redisson-3-4] INFO org.redisson.connection.SentinelConnectionManager - slave: 0.0.0.35:6385 has up
[redisson-netty-1-7] INFO org.redisson.connection.pool.MasterConnectionPool - 20 connections initialized for /0.0.0.82:6382
[redisson-netty-1-7] INFO org.redisson.connection.MasterSlaveEntry - master /0.0.0.35:6385 has changed to redis://0.0.0.82:6382
Exception in thread "main" org.redisson.client.RedisTimeoutException: Redis server response timeout (20000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, My-Map, PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 12, cap: 256)] channel: [id: 0x6ffe7551, L:0.0.0.0/0.0.0.0:59826 ! R:/0.0.0.35:6385]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:696)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Unknown Source)
```
My question is whether this is some configuration issue from my side or does redisson not support failover?

**Comment by mrniko** [comment]
You should adjust`retryAttempts` and `retryInterval` parameters to not lost your writes during failover process.

**Comment by Rowen123** [comment]
@mrniko I put `retryAttempts=10` and `retryInterval=1000`. The stacktrace after slave becoming master is as follows:
```
key key10467
Exception in thread "main" org.redisson.client.RedisTimeoutException: Redis server response timeout (5000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, My-Map, PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 12, cap: 256)] channel: [id: 0x0224321b, L:0.0.0.0/0.0.0.0:54705 ! R:/10.0.0.35:6385]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:696)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Unknown Source)
[redisson-3-7] INFO org.redisson.connection.SentinelConnectionManager - slave: 10.0.0.35:6385 has up
[redisson-netty-1-8] INFO org.redisson.connection.pool.MasterConnectionPool - 20 connections initialized for /10.0.0.82:6382
[redisson-netty-1-8] INFO org.redisson.connection.MasterSlaveEntry - master /10.0.0.35:6385 has changed to redis://10.0.0.82:6382
[redisson-3-3] INFO org.redisson.connection.MasterSlaveEntry - master /10.0.0.82:6382 excluded from slaves
[redisson-3-3] INFO org.redisson.connection.SentinelConnectionManager - slave: 10.0.0.35:6385 has up
[redisson-3-3] INFO org.redisson.connection.MasterSlaveEntry - master /10.0.0.82:6382 excluded from slaves
[redisson-3-3] INFO org.redisson.connection.SentinelConnectionManager - slave: 10.0.0.35:6385 has up
```
After this further writes is not happening. Execution just stays like this. Hope u were able to understand what i'm saying

**Comment by mrniko** [comment]
I understand. I think 10 seconds is not enough for failover in your case since according to logs
`[redisson-netty-1-8] INFO org.redisson.connection.MasterSlaveEntry - master`
Happens long after 10 seconds you defined for retry policy.

**Comment by Rowen123** [comment]
>  I think 10 seconds is not enough for failover in your case
Trying with `retryAttempts=2` and `retryInterval=60000`. Screenshot of stacktrace is as below:
![netty](https://user-images.githubusercontent.com/32266495/31497186-e02a5964-af7b-11e7-92b9-a7a604a5b241.PNG)

Execution has been like this for the past 15min.

**Comment by Rowen123** [comment]
@mrniko what i do not understand is why the execution is not stopping.  After identifying that `the master has changed`  the execution just continues on indefinitely without continuing with the writes. Are u able to reproduce this same issue with the code that i've provided?

**Comment by Rowen123** [comment]
@mrniko I finally  got the issue, here. I was using version 2.10.4 till now. when i upgraded redisson version to 3.5.4, failover was happening in the correct way.
