### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type

### ISSUE THREAD

**Issue by okwei2000** [redisson/redisson#1102]
Using the latest 3.5.4 version and Java 8. getting the error when deserialize the json to Java objects.

``
Oct 16, 2017 11:53:09 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jersey-serlvet] in context with path [/] threw exception [org.redisson.client.RedisException: Unexpected exception while processing command] with root cause
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.google.maps.model.LatLng]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1397] (through reference chain: com.google.maps.model.GeocodingResult["geometry"]->com.google.maps.model.Geometry["bounds"]->com.google.maps.model.Bounds["northeast"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:256)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1134)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:168)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1021)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:493)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
``

For my own classes, I could implement a default constructor to workaround the issue, but not on other classes that I dont have access to

**Comment by jackygurui** [comment]
Error message `No suitable constructor found for type [simple type, class com.google.maps.model.LatLng]` has suggested this is a Jackson related issue. 

You can either choose a different encoder/decoder such as FST codec or customise the object mapper to support the additional types

**Comment by okwei2000** [comment]
Thanks @jackygurui . You are saying this library is not working out of the box? it includes jackson 2.7.9, and it's not working.  Is there any workaround to still use Jackson as the codec, like how I can customize the object mapper?

**Comment by jackygurui** [comment]
Jackson can't serialise every object out of box for some objects that lacks of the default constructor, it requires additional annotation directives or additional mixins to make them work. 

please refer to this SO Q&A for the class in question.
