### ISSUE TITLE
Handle server down with singleServer mode

### ISSUE THREAD

**Issue by okwei2000** [redisson/redisson#1118]
Using singleServer mode without slave. 

```
        Config config = new Config();
        config.useSingleServer().setAddress(redisServer1);
        client = Redisson.create(config);
        ....
        RBucket<Object> bucket = client.getBucket("TestKey");
        bucket.get();
```

now, when the Redis server is down, an exception will be throw:
```
org.redisson.client.RedisConnectionException: MasterConnectionPool no available Redis entries
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:196)
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:31)
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:419)
	at org.redisson.connection.SingleEntry.connectionReadOp(SingleEntry.java:45)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:752)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:504)
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:585)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:745)
```

I'd like to handle this in our app, but it looks like the getBucket() or get() is an async call, so the function doesnt throw the exception, I look through the docs, and found nothing to configure Redission to work in synchronized mode. Is  synchronous mode supported by Redission or is there a different way to handle this?

**Comment by okwei2000** [comment]
OK, got it solve. the Exception can be caught on the `bucket.get();` call, although there's no exceptions defined on the `get()` call.

**Comment by jackygurui** [comment]
Just to clarify, `getBucket()` creates a handler to operate on the redis the string type. This method doesn't react to Redis and therefore there will not be any connection related exception thrown at there.

On contrary `get()` is a ***blocking*** method that ultimately executes the `GET` command to the key. Internally, calling thread to this method gets parked while the action is executed as an async action by an executor thread, when the result comes back and successfully decoded by an executor thread, the original calling thread would then been woken up and given to the result. If there were any exception, they will be passed back to the original calling thread.
