### ISSUE TITLE
Seeing lots of redisson errors - RedisTimeoutException and RedisConnectionException

### ISSUE THREAD

**Issue by yspotts** [redisson/redisson#1122]
Hi. I am using redisson 3.5.4. 

I am using redisson for task service management. However, I am seeing a bunch of redis errors - not for every call, but for enough calls to where I am concerned. Here is a sample:

```
 RedisTimeoutException occurred when processing request: [GET] /tasks/74618b07-dbce-4c06-93e9-8720b59d56f9
Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 3, ns:redisson-task:results, redisson__timeout__set:{ns:redisson-task:results}, redisson__idle__set:{ns:redisson-task:results}, 1509457132711, 74618b07-dbce-4c06-93e9-8720b59d56f9] channel: [id: 0xa8085706, L:/10.10.41.230:57794 - R:non-prod-cache-dev.dkmn9o.0001.use1.cache.amazonaws.com/10.10.41.103:6379]. Stacktrace follows:
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 3, ns:redisson-task:results, redisson__timeout__set:{ns:redisson-task:results}, redisson__idle__set:{ns:redisson-task:results}, 1509457132711, 74618b07-dbce-4c06-93e9-8720b59d56f9] channel: [id: 0xa8085706, L:/10.10.41.230:57794 - R:non-prod-cache-dev.dkmn9o.0001.use1.cache.amazonaws.com/10.10.41.103:6379]
        at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:647)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:661)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:736)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:464)
        at java.lang.Thread.run(Thread.java:748)
```

and a different error:

```
RedisConnectionException occurred when processing request: [GET] /tasks/3b28ac7f-8ca2-45ab-b3c7-a422798ed7b7
RedisConnection@1674996143 [redisClient=[addr=non-prod-cache-dev.dkmn9o.0001.use1.cache.amazonaws.com/10.10.41.103:6379], channel=[id: 0x0248d945, L:0.0.0.0/0.0.0.0:57512]] is not active!. Stacktrace follows:
org.redisson.client.RedisConnectionException: RedisConnection@1674996143 [redisClient=[addr=non-prod-cache-dev.dkmn9o.0001.use1.cache.amazonaws.com/10.10.41.103:6379], channel=[id: 0x0248d945, L:0.0.0.0/0.0.0.0:57512]] is not active!
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:314)
        at org.redisson.connection.pool.ConnectionPool.connectTo(ConnectionPool.java:251)
        at org.redisson.connection.pool.ConnectionPool.access$300(ConnectionPool.java:53)
        at org.redisson.connection.pool.ConnectionPool$3.run(ConnectionPool.java:216)
        at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:76)
        at org.redisson.connection.ClientConnectionsEntry.acquireConnection(ClientConnectionsEntry.java:114)
        at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:154)
        at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:226)
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:168)
        at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:31)
        at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:409)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:677)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:503)
        at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:552)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:661)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:736)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:464)
        at java.lang.Thread.run(Thread.java:748)
```

I am also seeing some `RemoteServiceAckTimeException: No ACK response after 5000ms for request: RemoteServiceRequest`.

Here is my configuration:

```
redisson {
    config {
        singleServerConfig {
            idleConnectionTimeout = 10000
            pingTimeout = 1000
            connectTimeout = 10000
            timeout = 3000
            retryAttempts = 3
            retryInterval = 1500
            reconnectionTimeout = 3000
            failedAttempts = 3
            password = null
            subscriptionsPerConnection = 5
            clientName = null
            address = 'redis://127.0.0.1:6379'
            subscriptionConnectionMinimumIdleSize = 1
            subscriptionConnectionPoolSize = 50
            connectionMinimumIdleSize = 10
            connectionPoolSize = 64
            database = 0
            dnsMonitoring = false
            dnsMonitoringInterval = 5000
        }
        threads = 0
        nettyThreads = 0
        codec = null
        useLinuxNativeEpoll = false
    }
}
```

Is there any config setting I could change to help with this? Am I doing something wrong?

thanks!

**Comment by somendraraj** [comment]
# **I am also getting same error related like this**
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EXISTS) with params: [redis.lock] channel: [id: 0x74131d2d, L:/x.x.x.x:xxxx - R:/127.0.0.1:6379]
        at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:698)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jackygurui** [comment]
`RedisTimeoutException` happens when Redisson had ALREADY sent the command to the redis server and it has failed to respond within the given time limit. 

`RemoteServiceAckTimeException` is an exception describing the similar scenario but specifically indicate it is not getting acknowledgement from the receiving end.

For both situations, it is advised to re-adjust timeout and retry parameters or implement some resend strategy in some use cases.

**Comment by mumutu66** [comment]
got same issue just update client to 3.6.2 on redis 3.0 formally is 3.2.0  with same configuration  
timeout is 10000ms retry interval is 1500ms ..but didn't figure it out why    
we will take time to make it clear

**Comment by mrniko** [comment]
Hi! Please update to 3.6.5 version it contains fix for RedisTimeoutException problem - https://github.com/redisson/redisson/issues/1377

**Comment by mumutu66** [comment]
Great!  it's just the problem  thanks a lot!
