### ISSUE TITLE
reactor/fn/Supplier : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by manojcv** [redisson/redisson#1139]
I am Using Java 1.6 and the Redisson 2.10.1

and i am using the RedissonReactiveClient  as shown in the blow sample code 

 Config config = Config.fromJSON(new File("src/main/resources/WEB-INF/SentinelServersConfig.json")
 RedissonReactiveClient redisson = Redisson.createReactive(config);
 RMapCacheReactive<String, String> mapCachemain = redisson.getMapCache("sessionloopmain");
 mapCachemain.putIfAbsent("1234" , "manoj", 30 , TimeUnit.SECONDS);

when i run the code  I am getting the below Error
java.lang.UnsupportedClassVersionError: reactor/fn/Supplier : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.redisson.RedissonReactive.<init>(RedissonReactive.java:106)
	at org.redisson.Redisson.createReactive(Redisson.java:182)

**Comment by mrniko** [comment]
Sorry, ReactiveClient requires JDK 7+. I'll cover it in wiki

**Comment by manojcv** [comment]
Thank you
