### ISSUE TITLE
Redis timeout exceptions when trying to submit tasks on a now executor

### ISSUE THREAD

**Issue by prashantochatterjee** [redisson/redisson#1141]
I have a redisson configuration with a single worker executors for various schedules - 1min, 5min, 1hour, ... 24hours. When each of these ticker-tasks are invoked I have a set of devices on which I need to run diagnostics. Each device will have a task that will be slotted in various schedules and these tasks for all the devices that belong to a schedule need to be invoked at that particular time.

The device tasks are put in a 'now' executor. So on every schedule invocation, there are a lot of tasks that are submitted on the now-executor. 

I am using Redisson version 3.3.1 and my key settings are:
timeout - 180000 ms (3 mins)
retryInterval - 60000 ms (1 min)
connectionPoolSize - 1100

Maximum workers in now-executor - 1000.

1) I am observing sporadic RedisTimeoutException when submitting tasks to the now executor:
`org.redisson.client.RedisTimeoutException: Command execution timeout for command: (EVAL) with params: [if redis.call('exists', KEYS[2]) == 0 then redis.call('rpush', KEYS[3], ARGV[1]); redis.call('incr',..., 3, {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_now:org.redisson.executor.Rem..., {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_now:org.redisson.executor.Rem..., {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_now:org.redisson.executor.Rem..., [123, 34, 64, 99, 108, 97, 115, 115, 34, 58, ...]]
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:538) ~[redisson-3.3.1.jar!/:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:625) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:700) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:428) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
`
 ------------------------------------------------------------------------------------------------------------------------------------------
2) I am also getting sporadic timeouts on the ticker tasks - 1min, 3min etc.
`
2017-11-09 10:10:00,437 [pool-1-thread-1] ERROR [o.r.QueueTransferTask] - Command execution timeout for command: (EVAL) with params: [local expiredTaskIds = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #ex..., 3, {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_every_3_minutes:org.redisson...., {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_every_3_minutes:org.redisson...., {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_every_3_minutes:org.redisson...., 1510221960038, 100]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (EVAL) with params: [local expiredTaskIds = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #ex..., 3, {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_every_3_minutes:org.redisson...., {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_every_3_minutes:org.redisson...., {f4242397-122e-410a-ba32-f455ef71bbdf_device.manager.task.schedule.sys_every_3_minutes:org.redisson...., 1510221960038, 100]
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:538) ~[redisson-3.3.1.jar!/:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:625) [netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:700) [netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:428) [netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
`

I have two instances running that feed off the Redis cache. These errors are sporadic in  nature. Appreciate any help in understanding the root cause of these timeouts.

**Comment by mrniko** [comment]
Hi!

I think your issue related to this one https://github.com/redisson/redisson/issues/1087. Please try to use Redisson 3.5.5.

**Comment by prashantochatterjee** [comment]
Worked perfectly after upgrading to Redisson 3.5.5. Thank you for the direction.
