### ISSUE TITLE
redisson3.4.4+spring4.1.6项目启动提示错误。

### ISSUE THREAD

**Issue by rendongjing** [redisson/redisson#1154]
redssion 配置 
<redisson:client>
	    <redisson:master-slave-servers master-address="redis://127.0.0.1:16379" password="123">
	        <redisson:slave-address value="redis://127.0.0.1:16380"/>
	        <redisson:slave-address value="redis://127.0.0.1:16381"/>
	    </redisson:master-slave-servers>
</redisson:client>

项目启动后一直报
十一月 21, 2017 10:39:40 上午 org.redisson.client.handler.CommandsQueue exceptionCaught
严重: Exception occured. Channel: [id: 0x36a1b44e, L:/127.0.0.1:6539 - R:/127.0.0.1:16380]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:366)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

不知道是怎么回事。希望能处理下。 万分感谢！！！

**Comment by rendongjing** [comment]
redis版本 3.0.503

**Comment by rendongjing** [comment]
问题解决  升级本地redis版本到最新3.2.1解决问题。
