### ISSUE TITLE
The question of the version

### ISSUE THREAD

**Issue by heatgemini** [redisson/redisson#1155]
When I used high version(org.redisson:redisson:3.5.3)，The error is as follows.
But, when I used low version(org.redisson:redisson:2.2.17), my project is started normal with tomcat 8.0.14.
My project is used gradle 4.0, I want to use the high version, please tell me how to do?

2017-11-21 16:57:57.807||WARN -[Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.xxx.common.utils.SpringUtils#0' defined in ServletContext resource [/WEB-INF/classes/spring/spring-servlet.xml]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalCacheAdvisor': Cannot resolve reference to bean 'org.springframework.cache.annotation.AnnotationCacheOperationSource#0' while setting bean property 'cacheOperationSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.AnnotationCacheOperationSource#0': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalJCacheAdvisor': Cannot resolve reference to bean 'org.springframework.cache.jcache.interceptor.DefaultJCacheOperationSource#0' while setting bean property 'cacheOperationSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.jcache.interceptor.DefaultJCacheOperationSource#0': Cannot resolve reference to bean 'cacheManager' while setting bean property 'cacheManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheManager' defined in ServletContext resource [/WEB-INF/classes/spring/spring-servlet.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException]-[o.s.w.c.s.XmlWebApplicationContext]-[localhost-startStop-1]
2017-11-21 16:57:57.822||ERROR-[Context initialization failed]-[o.s.web.servlet.DispatcherServlet]-[localhost-startStop-1]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.xxx.common.utils.SpringUtils#0' defined in ServletContext resource [/WEB-INF/classes/spring/spring-servlet.xml]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalCacheAdvisor': Cannot resolve reference to bean 'org.springframework.cache.annotation.AnnotationCacheOperationSource#0' while setting bean property 'cacheOperationSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.AnnotationCacheOperationSource#0': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalJCacheAdvisor': Cannot resolve reference to bean 'org.springframework.cache.jcache.interceptor.DefaultJCacheOperationSource#0' while setting bean property 'cacheOperationSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.jcache.interceptor.DefaultJCacheOperationSource#0': Cannot resolve reference to bean 'cacheManager' while setting bean property 'cacheManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheManager' defined in ServletContext resource [/WEB-INF/classes/spring/spring-servlet.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:479) ~[AbstractAutowireCapableBeanFactory.class:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[AbstractBeanFactory$1.class:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[DefaultSingletonBeanRegistry.class:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[AbstractBeanFactory.class:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[AbstractBeanFactory.class:4.3.6.RELEASE]

**Comment by jackygurui** [comment]
The cause of the error is:
```
Error creating bean with name 'cacheManager' defined in ServletContext resource [/WEB-INF/classes/spring/spring-servlet.xml]: Invocation of init method failed;
```
Please check your xml definition.

**Comment by heatgemini** [comment]
I saw the error, but I don't update spring-servlet.xml when I use 2.2.17 or 3.5.3.
I just updated the version and some import package in java code.
This spring-servlet.xml contains the following code
`<bean id="cacheManager" class="com.suixingpay.common.cache.RedisCacheManager" init-method="parseCacheExpires">
	<constructor-arg ref="redisTemplate" />
</bean>`
I think that cacheManager  because that is in conflict with the redisson high version.

**Comment by jackygurui** [comment]
Based on the XML code you shared, I cannot tell what the problem is since the piece of code in question is not supplied by Redisson. 

I am afraid you will have to debug this one out yourself unless you are able to share the code of your own `RedisCacheManager`
