### ISSUE TITLE
spring boot health check redis is down

### ISSUE THREAD

**Issue by zhanghaichang** [redisson/redisson#1176]
2017-12-04 17:59:01.118  WARN 2872 --- [nio-9090-exec-1] o.s.b.a.health.RedisHealthIndicator      : Health check failed
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:204)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:348)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:129)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:92)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:79)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194)
	... 119 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect

**Comment by jackygurui** [comment]
I think this issue can be quite easily fixed by changed to use Redisson instead, right? @mrniko  😃

**Comment by hjhhjhhjh** [comment]
这个问题也是绝了

**Comment by mrniko** [comment]
@jackygurui :D

**Comment by zhanghaichang** [comment]
@mrniko  hi, how about fix it?

**Comment by mrniko** [comment]
@zhanghaichang I'm sorry but I don't support Jedis integration with Spring Boot

**Comment by pratikshah1701** [comment]
I am which redission redisson-spring-boot-starter : 3.9.1, on application startup I see this error. pls help

**Comment by mrniko** [comment]
@pratikshah1701 

Please try 3.10.0 version. It contains fix that allow to start without lettuce or jedis drivers.

**Comment by mrniko** [comment]
@pratikshah1701 

You're welcome!
