### ISSUE TITLE
redisson work with a cluster with no full coverage slots

### ISSUE THREAD

**Issue by JackEggie** [redisson/redisson#1182]
你好，

我将redis cluster的参数**cluster-require-full-coverage**设置为了no，以让集群在挂掉部分节点的时候仍然可以提供服务。但是一旦16384个slot没有全部被覆盖，redisson在初始化的时候会报如下错误，请问如何解决：

org.redisson.client.RedisConnectionException: Not all slots are covered! Only 10923 slots are avaliable. Failed masters according to cluster status: [/127.0.0.1:8800]
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:146)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:237)
	at org.redisson.Redisson.<init>(Redisson.java:117)
	at org.redisson.Redisson.create(Redisson.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 42 more
Caused by: com.eif.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:8800
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
	at com.eif.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347)
	at com.eif.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at com.eif.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at com.eif.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at com.eif.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at com.eif.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at com.eif.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at com.eif.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:722)

**Comment by gauravs140689** [comment]
Hi, 

I am also getting the same issue while accessing the _redis_ cluster.

java.lang.RuntimeException: org.redisson.client.RedisConnectionException: Not all slots are covered! Only 14044 slots are avaliable...


Could you please confirm if this issue is already addressed?

**Comment by mrniko** [comment]
@gauravs140689 

Check your Redis cluster config it doesn't cover all slots.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2284
