### ISSUE TITLE
redisson 3.5.5 RScheduledExecutorService

### ISSUE THREAD

**Issue by liuzhongkai** [redisson/redisson#1183]
You can't find a class using the Lambda creation task

java.lang.NullPointerException
	at java.io.FilterInputStream.available(FilterInputStream.java:168)
	at org.redisson.RedissonExecutorService.getClassBody(RedissonExecutorService.java:326)
	at org.redisson.RedissonExecutorService.scheduleAsync(RedissonExecutorService.java:734)
	at org.redisson.RedissonExecutorService.schedule(RedissonExecutorService.java:726)
	at org.redisson.RedissonExecutorService.schedule(RedissonExecutorService.java:87)

**Comment by mrniko** [comment]
Please share code how to reproduce that

**Comment by archmisha** [comment]
This happens to me as well on latest redisson version 3.8.1

Happens when runnable is anonioums class:
`redissonClient.getExecutorService(name).scheduleWithFixedDelay(() -> do something, 1, 1, TimeUnit.SECONDS)`

**Comment by mrniko** [comment]
Done

**Comment by mrniko** [comment]
Done
