### ISSUE TITLE
DNSMonitor fails on bootstrap with custom event loop

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#1188]
redisson 3.5.6 fails on bootstrap when using custom event loop.

```java
    private RedissonClient createRedissonClient(int database) {
        Config config = new Config();
        if (redisNodes.indexOf(',') > -1) {
            ReplicatedServersConfig clusterConfig = config.useReplicatedServers();
            clusterConfig.setScanInterval(3000);
            clusterConfig.setDatabase(database);
            clusterConfig.setTcpNoDelay(true);
            clusterConfig.setKeepAlive(true);
            for (String addr : StringUtils.tokenizeToStringArray(redisNodes, ",", true, true)) {
                clusterConfig.addNodeAddress(addSchema(addr));
            }
            clusterConfig.setTimeout(8000);
            if (database == redisGameDatabase) {
                clusterConfig.setReadMode(ReadMode.MASTER); // consistency is crucial
            } else {
                clusterConfig.setReadMode(ReadMode.MASTER_SLAVE); // consider setting SLAVE when we have multiple slaves
            }
        } else {
            SingleServerConfig singleServerConfig = config.useSingleServer();
            singleServerConfig.setDatabase(database);
            singleServerConfig.setTimeout(8000);
            singleServerConfig.setTcpNoDelay(true);
            singleServerConfig.setKeepAlive(true);
            singleServerConfig.setAddress(addSchema(redisNodes));
        }
        config.setCodec(new SnappyCodec());
        config.setThreads(redisEventLoop.getThreadPoolSize());
        config.setEventLoopGroup(redisEventLoop.getWorkerGroup());
        config.setUseLinuxNativeEpoll(redisEventLoop.isNativeEpoll());

        return Redisson.create(config);
    }
```

```
Caused by: java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:162) ~[netty-transport-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.AbstractNioChannel.eventLoop(AbstractNioChannel.java:119) ~[netty-transport-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.AbstractNioChannel.eventLoop(AbstractNioChannel.java:49) ~[netty-transport-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:316) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:295) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:791) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolverContext.internalResolve(DnsNameResolverContext.java:200) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolverContext.doSearchDomainQuery(DnsNameResolverContext.java:189) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolverContext.resolve(DnsNameResolverContext.java:136) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:657) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:594) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:527) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63) ~[netty-resolver-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51) ~[netty-resolver-dns-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57) ~[netty-resolver-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32) ~[netty-resolver-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108) ~[netty-resolver-4.1.18.Final.jar:4.1.18.Final]
	at org.redisson.connection.DNSMonitor.<init>(DNSMonitor.java:65) ~[redisson-3.5.6.jar:?]
	at org.redisson.connection.MasterSlaveConnectionManager.initSingleEntry(MasterSlaveConnectionManager.java:288) ~[redisson-3.5.6.jar:?]
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:165) ~[redisson-3.5.6.jar:?]
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:32) ~[redisson-3.5.6.jar:?]
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:231) ~[redisson-3.5.6.jar:?]
	at org.redisson.Redisson.<init>(Redisson.java:117) ~[redisson-3.5.6.jar:?]
	at org.redisson.Redisson.create(Redisson.java:156) ~[redisson-3.5.6.jar:?]
```

**Comment by mrniko** [comment]
Could you share the code of your custom eventLoopGroup supplied to Redisson?

**Comment by johnou** [comment]
@mrniko sure, it's a singleton injected into the RedissonClientFactory.

```java
@Component
class RedisEventLoop {

    private static final Logger logger = LogManager.getLogger(RedisEventLoop.class);

    private boolean epollEnabled;

    private int parallelism = 16;

    private EventLoopGroup workerGroup;
    private boolean isNativeEpoll;

    @PostConstruct
    public void initialize() {
        if (isEpollEnabledAndAvailable()) {
            isNativeEpoll = true;
            workerGroup = new EpollEventLoopGroup(parallelism, new NonBlockingIOThreadFactory("Redisson-Epoll"));
            logger.info("Epoll initialized!");
        } else {
            workerGroup = new NioEventLoopGroup(parallelism, new NonBlockingIOThreadFactory("Redisson-Nio"));
            logger.info("Nio initialized!");
        }
    }

    EventLoopGroup getWorkerGroup() {
        return workerGroup;
    }

    boolean isNativeEpoll() {
        return isNativeEpoll;
    }

    int getThreadPoolSize() {
        return parallelism;
    }

    private boolean isEpollEnabledAndAvailable() {
        if (!epollEnabled) {
            return false;
        }
        if (!Epoll.isAvailable()) {
            logger.warn("Failed to init Epoll, falling back to Nio", Epoll.unavailabilityCause());
            return false;
        }
        return true;
    }

    @PreDestroy
    public void shutdown() throws InterruptedException {
        logger.info("Shutting down worker group!");
        workerGroup.shutdownGracefully(2, 15, TimeUnit.SECONDS).await();
    }
}
```

**Comment by mrniko** [comment]
This issue reproduced with epoll enabled setting only

**Comment by mrniko** [comment]
Fixed! Please check it too

**Comment by johnou** [comment]
change looks good to me, I will test it in a canary build this week.
