### ISSUE TITLE
关闭web容器后,在比较短的时间内重启容器时,初始化客户端报空指异常

### ISSUE THREAD

**Issue by pso2yui** [redisson/redisson#1208]
大神,又来麻烦您了.eclipse源码跟不进去,希望能解答下这个如何处理.   

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getRedissonConfig' defined in class path resource [com/jiangnanciqi/manage/reading/configset/RedissonCluster.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'getRedissonConfig' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	... 50 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'getRedissonConfig' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 62 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.redisson.cluster.ClusterConnectionManager.connect(ClusterConnectionManager.java:176)
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:91)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:237)
	at org.redisson.Redisson.<init>(Redisson.java:117)
	at org.redisson.Redisson.create(Redisson.java:156)
	at com.jiangnanciqi.manage.reading.configset.RedissonCluster.getRedissonConfig(RedissonCluster.java:40)
	at com.jiangnanciqi.manage.reading.configset.RedissonCluster$$EnhancerBySpringCGLIB$$ad4e34e6.CGLIB$getRedissonConfig$0(<generated>)
	at com.jiangnanciqi.manage.reading.configset.RedissonCluster$$EnhancerBySpringCGLIB$$ad4e34e6$$FastClassBySpringCGLIB$$102e7cd2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.jiangnanciqi.manage.reading.configset.RedissonCluster$$EnhancerBySpringCGLIB$$ad4e34e6.getRedissonConfig(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 63 common frames omitted
```

个人感觉是不是资源没有被释放的原因呢?   

redisson客户端配置如下:   

![image](https://user-images.githubusercontent.com/23494400/34342216-80dad176-e9e3-11e7-9e94-8c4c9407b57e.png)

**Comment by mrniko** [comment]
One of defined nodeaddress is null
