### ISSUE TITLE
.setDnsMonitoringInterval(-1) doesn't actually seem to be disabling DNS Monitoring

### ISSUE THREAD

**Issue by daniel9x** [redisson/redisson#1221]
I'm using 3.5.7 and am getting intermittent "Unable to resolve" DNSMonitor exceptions, using AWS ElasticCache Cluster. Here's my createConfig() code:

`protected org.redisson.config.Config createConfig() {

   org.redisson.config.Config config = new org.redisson.config.Config();

    List<String> prefixedServers = new ArrayList<>();

    for (HostAndPort server : servers) prefixedServers.add("redis://" + server.toString());

    config.useReplicatedServers()
            .setDnsMonitoringIterval(-1)
            .addNodeAddress(
                    prefixedServers.toArray(new String[prefixedServers.size()]));
    return config;
  }`

I'm still getting the UnknownHostExceptions from DNSMonitor which suggests the monitoring is not being disabled. Is this a bug or am I missing something?

Just an additional FYI, this is my initialization block: 

`private synchronized void initialize(){
    if(!initialized){
      Logger.debug(LOG_INITIALIZING_CACHE.getValue());
      org.redisson.config.Config config = createConfig();
      redisson = Redisson.create(config);
      initialized = true;
    } else {
      Logger.debug(LOG_CACHE_ALREADY_INITIALIZED.getValue());
    }
  }`

**Comment by mrniko** [comment]
Could you please share your code and stacktrace?

**Comment by daniel9x** [comment]
Sure. This is my entire SimpleCache and AWSUtil class: 

```
import com.amazonaws.services.elasticache.model.ReplicationGroup;
import com.elemica.apollo.utilities.AWSRedisCacheUtil;
import com.google.common.net.HostAndPort;
import com.typesafe.config.Config;
import org.jooq.lambda.Seq;
import org.redisson.Redisson;
import org.redisson.api.RedissonClient;
import play.Logger;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;

import static com.elemica.apollo.utilities.RiskConstant.*;

@Singleton
public class SimpleCacheImpl implements SimpleCache {

  private Boolean initialized = false;

  private Config configuration;

  private RedissonClient redisson = null;

  @Inject
  public SimpleCacheImpl(Config configuration) {
    this.configuration = configuration;
    AWSRedisCacheUtil awsRedisCacheUtil = new AWSRedisCacheUtil();

    ReplicationGroup replicationGroup = awsRedisCacheUtil.describeElastiCacheReplicationGroup(this.configuration.getString(CACHE_GROUP_ID.getValue()), this.configuration.getString(CACHE_REGION.getValue()));

    if (replicationGroup != null) {
      setHostAndPorts(awsRedisCacheUtil.getHostAndPorts(replicationGroup));
    }
  }

  private synchronized void initialize(){
    if(!initialized){
      Logger.debug(LOG_INITIALIZING_CACHE.getValue());
      org.redisson.config.Config config = createConfig();
      redisson = Redisson.create(config);
      initialized = true;
    } else {
      Logger.debug(LOG_CACHE_ALREADY_INITIALIZED.getValue());
    }
  }

  protected List<HostAndPort> servers;

  protected void setHostAndPorts(List<HostAndPort> servers){
    this.servers = servers;
  }

  protected org.redisson.config.Config createConfig() {
    org.redisson.config.Config config = new org.redisson.config.Config();

    List<String> prefixedServers = new ArrayList<>();

    for (HostAndPort server : servers) prefixedServers.add("redis://" + server.toString());

    config.useReplicatedServers()
            .setDnsMonitoringInterval(-1)
            .addNodeAddress(
                    prefixedServers.toArray(new String[prefixedServers.size()]));
    return config;
  }


  public Object get(String key) {
    initialize();
    return redisson.getBucket(key).get();
  }

  @Override
  public Object getOrElse(String key, Callable<Object> methodToExecute) {
    if (get(key) != null) {
      Logger.info(LOG_USING_CACHED_INSTANCE.getValue() + key);
      return get(key);
    } else {
      Logger.info(LOG_KEY_NOT_FOUND_IN_CACHE.getValue() + key);
      try {
        Object methodResult = methodToExecute.call();
        set(key, methodResult);
        return methodResult;
      } catch (Exception e) {
        Logger.error(LOG_ERROR_CALLING_FUNCTION.getValue(), e);
        e.printStackTrace();
        return null;
      }
    }
  }


  @Override
  public void set(String key, Object value) {
    initialize();
    Logger.info("Setting " + key + " to " + value);
    redisson.getBucket(key).set(value, 5, TimeUnit.MINUTES);
  }

}

```

```
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.services.elasticache.AmazonElastiCache;
import com.amazonaws.services.elasticache.AmazonElastiCacheClientBuilder;
import com.amazonaws.services.elasticache.model.DescribeReplicationGroupsRequest;
import com.amazonaws.services.elasticache.model.DescribeReplicationGroupsResult;
import com.amazonaws.services.elasticache.model.Endpoint;
import com.amazonaws.services.elasticache.model.ReplicationGroup;
import com.google.common.net.HostAndPort;
import org.apache.commons.lang3.StringUtils;
import org.jooq.lambda.Seq;
import play.Logger;

import java.util.List;

import static com.elemica.apollo.utilities.RiskConstant.*;

public class AWSRedisCacheUtil {

  public ReplicationGroup describeElastiCacheReplicationGroup(final String replicationGroupId, final String regionName) {
    final AmazonElastiCache elasticCacheClient = AmazonElastiCacheClientBuilder
            .standard()
            .withCredentials(new DefaultAWSCredentialsProviderChain())
            .withRegion(regionName)
            .build();

    final DescribeReplicationGroupsRequest request = new DescribeReplicationGroupsRequest().withReplicationGroupId(replicationGroupId);

    try {
      final DescribeReplicationGroupsResult describeReplicationGroupsResult = elasticCacheClient.describeReplicationGroups(request);

      List<ReplicationGroup> list = describeReplicationGroupsResult.getReplicationGroups();
      if (list != null && list.size() > 0) {
        return list.get(0);
      }

      throw new RuntimeException(LOG_MULTIPLE_REPLICATION_GROUPS.getValue() + replicationGroupId);
    } catch (Exception e) {
      Logger.error(LOG_ERROR_CONNECTING_TO_CACHE.getValue(), e);
      return null;
    }
  }

  public List<HostAndPort> getHostAndPorts(final ReplicationGroup replicationGroup) {
    final List<HostAndPort> hostAndPorts = Seq.seq(replicationGroup.getNodeGroups()).flatMap(nodeGroup -> {
      final Endpoint primaryEndpoint = nodeGroup.getPrimaryEndpoint();
      HostAndPort hostAndPort = fromEndPoint(primaryEndpoint); // this is the primary, so we filter the primary out below.
      return Seq.of(hostAndPort)
              .concat(nodeGroup.getNodeGroupMembers().stream()
                      .filter(member -> !StringUtils.equalsIgnoreCase(PRIMARY.getValue(), member.getCurrentRole())) // add the read replicas (non-primary)
                      .map(member -> fromEndPoint(member.getReadEndpoint()))
              );
    }).toList();

    Logger.info(LOG_SUCCESSFULLY_CONNECTED_TO_CACHE.getValue());

    return hostAndPorts;
  }

  private static HostAndPort fromEndPoint(Endpoint endpoint) {
    return HostAndPort.fromParts(endpoint.getAddress(), endpoint.getPort());
  }
}
```



These are the stacktraces I receive preiodically:

```
[error] application - No token present in request:
[error] o.r.c.DNSMonitor - Unable to resolve cfr1xov4lh2uk4ae-002.qeh5fx.0001.euw1.cache.amazonaws.com
java.net.UnknownHostException: failed to resolve 'cfr1xov4lh2uk4ae-002.qeh5fx.0001.euw1.cache.amazonaws.com' after 3 queries 
	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:701)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:643)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:292)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:282)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:620)
	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:327)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
```

**Comment by mrniko** [comment]
Thanks for report! Fixed

**Comment by daniel9x** [comment]
Awesome thanks! Looks like there was a 3.5.7 release for this, but I'm a little confused as to where I can pull it down from. According to https://mvnrepository.com/artifact/org.redisson/redisson 3.5.7 was release back in December, and in fact that's the one my current project is using.

**Comment by mrniko** [comment]
@daniel9x it's planned for 2.10.8 / 3.5.8 versions release.
