### ISSUE TITLE
InstantiationException when getting priorityQueue

### ISSUE THREAD

**Issue by welovelain** [redisson/redisson#1225]
The code
```
public void test1() {
    RPriorityQueue<TrackMessage> trackQueue = redisson.getPriorityQueue("123");
    trackQueue.trySetComparator(new Comparator<TrackMessage>() {
        @Override
        public int compare(TrackMessage t1, TrackMessage t2) {
            return (int)(t1.getServerTime() - t2.getServerTime());
        }
    });
}

public void test2() {
  RPriorityQueue<TrackMessage> t2 = redisson.getPriorityQueue("123");
}

// TESTCODE:
test1();
test2(); // throws next stack trace:
Caused by: java.lang.IllegalStateException: java.lang.InstantiationException: com.zeppelinen.carsharing.dataprocessor.controller.TestController$1
	at org.redisson.RedissonPriorityQueue.loadComparator(RedissonPriorityQueue.java:140) ~[redisson-3.5.6.jar:na]
	at org.redisson.RedissonPriorityQueue.<init>(RedissonPriorityQueue.java:108) ~[redisson-3.5.6.jar:na]
	at org.redisson.Redisson.getPriorityQueue(Redisson.java:635) ~[redisson-3.5.6.jar:na]
	at com.zeppelinen.carsharing.dataprocessor.controller.TestController.test2(TestController.java:126) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:777) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) ~[spring-webmvc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	... 48 common frames omitted
Caused by: java.lang.InstantiationException: com.zeppelinen.carsharing.dataprocessor.controller.TestController$1
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_151]
	at org.redisson.RedissonPriorityQueue.loadComparator(RedissonPriorityQueue.java:135) ~[redisson-3.5.6.jar:na]
	... 64 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.zeppelinen.carsharing.dataprocessor.controller.TestController$1.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_151]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_151]
	... 65 common frames omitted
```

Is that because comparator is anonymous?

**Comment by jackygurui** [comment]
> Is that because comparator is anonymous?
Yes, it is.
