### ISSUE TITLE
io.netty.resolver.dns.DnsNameResolver#doResolveCached race condition java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pohlmarcus** [redisson/redisson#1243]
It's an known bug in io.netty 4.1.19.Final and fixed in 4.1.20.Final
https://github.com/netty/netty/issues/7583

Sometimes my AWS Lambdas fail by creation of the redisson client.

Index: 0, Size: 0: java.lang.IndexOutOfBoundsException
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at io.netty.resolver.dns.DnsNameResolver.doResolveCached(DnsNameResolver.java:613)
at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:593)
at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:527)
at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
at org.redisson.client.RedisClient.resolveAddr(RedisClient.java:170)
at org.redisson.connection.MasterSlaveEntry.addSlave(MasterSlaveEntry.java:382)
at org.redisson.connection.MasterSlaveEntry.addSlave(MasterSlaveEntry.java:416)
at org.redisson.connection.MasterSlaveEntry.initSlaveBalancer(MasterSlaveEntry.java:103)
at org.redisson.connection.MasterSlaveConnectionManager.createMasterSlaveEntry(MasterSlaveConnectionManager.java:303)
at org.redisson.connection.MasterSlaveConnectionManager.initSingleEntry(MasterSlaveConnectionManager.java:280)
at org.redisson.connection.ReplicatedConnectionManager.<init>(ReplicatedConnectionManager.java:105)
at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:242)
at org.redisson.Redisson.<init>(Redisson.java:115)
at org.redisson.Redisson.create(Redisson.java:153)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by mrniko** [comment]
Thanks! I know about that

**Comment by wenxzhen** [comment]
@mrniko any idea on how to avoid the issue?
