### ISSUE TITLE
RedisTimeoutException: Unable to send command: (ZADD) with params: ...... after 3 retry attempts

### ISSUE THREAD

**Issue by yingbo-wu** [redisson/redisson#1250]
org.redisson.client.RedisTimeoutException: Unable to send command: (ZADD) with params: [me:5a6080dabf0d120011b9f6d9:campaign_log, 3045976628944469, {"id":null,"tenantId":1,"campaignId":"5a6080dabf0d120011b9f6d9","nodeId":"node_5a3b57e169d7b15fd3538...]after 3 retry attempts
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:542)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:748)

高并发场景下持续发生这个异常

**Comment by jackygurui** [comment]
造成这个原因是因为现有连接数量用不过来了，解决方法有三：
1）增加最大连接数
2）增加重试次数和重试间隔时间
3）换用企业版的高速引擎

**Comment by wxdh1987** [comment]
@jackygurui issue里面有很多关于RedisTimeoutException的问题，有些可能是高并发，但有些是在并发量很小的情况下就会发生，你提供的方案是1、增加连接数2、增加重试次数和时间，我想这个解决方案治标不治本。是否RedisConnectionManager有问题，获取的redis connection是失效的连接。总之就是pool里面的connection失效后无感知

**Comment by jackygurui** [comment]
每个连接都有WatchDog在看管，失效的连接会自动重连的。
