### ISSUE TITLE
Redisson expiration event - deserialization issue

### ISSUE THREAD

**Issue by xipo** [redisson/redisson#1262]
I use Redisson (sentinel mode), and everything was working fine until I added an EntryExpiredListener. 
After adding the listener I started getting the following errors

```
[CommandAsyncService] - acquired connection for command (EVAL) and params [if redis.call('setnx', KEYS[6], ARGV[4]) == 0 then return 0;end;redis.call('expire', KEYS[6], ARGV[3]); local expiredKeys1 = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); for i, key in ipairs(expiredKeys1) do local v = redis.call('hget', KEYS[1], key); if v ~= false then local t, val = struct.unpack('dLc0', v); local msg = struct.pack('Lc0Lc0', string.len(key), key, string.len(val), val); local listeners = redis.call('publish', KEYS[4], msg); if (listeners == 0) then break;end; end;end;if #expiredKeys1 > 0 then redis.call('zrem', KEYS[4], unpack(expiredKeys1)); redis.call('zrem', KEYS[3], unpack(expiredKeys1)); redis.call('zrem', KEYS[2], unpack(expiredKeys1)); redis.call('hdel', KEYS[1], unpack(expiredKeys1)); end; local expiredKeys2 = redis.call('zrangebyscore', KEYS[3], 0, ARGV[1], 'limit', 0, ARGV[2]); for i, key in ipairs(expiredKeys2) do local v = redis.call('hget', KEYS[1], key); if v ~= false then local t, val = struct.unpack('dLc0', v); local msg = struct.pack('Lc0Lc0', string.len(key), key, string.len(val), val); local listeners = redis.call('publish', KEYS[4], msg); if (listeners == 0) then break;end; end;end;if #expiredKeys2 > 0 then redis.call('zrem', KEYS[4], unpack(expiredKeys2)); redis.call('zrem', KEYS[3], unpack(expiredKeys2)); redis.call('zrem', KEYS[2], unpack(expiredKeys2)); redis.call('hdel', KEYS[1], unpack(expiredKeys2)); end; return #expiredKeys1 + #expiredKeys2;, 6, <MAP_CACHE_NAME>, redisson__timeout__set:{<MAP_CACHE_NAME>}, redisson__idle__set:{<MAP_CACHE_NAME>}, redisson_map_cache_expired:{<MAP_CACHE_NAME>}, redisson__map_cache__last_access__set:{<MAP_CACHE_NAME>}, redisson__execute_task_once_latch:{<MAP_CACHE_NAME>}, 1516811165744, 100, 33, 1] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@50487e86] using node /<NODE_HOST_AND_PORT>... RedisConnection@795684401 [redisClient=[addr=redis://<NODE_HOST_AND_PORT>], channel=[id: <channelId>, L:/... - R:/<NODE_HOST_AND_PORT>]]

[CommandAsyncService] - connection released for command (EVAL) and params [if redis.call('setnx', KEYS[6], ARGV[4]) == 0 then return 0;end;redis.call('expire', KEYS[6], ARGV[3]); local expiredKeys1 = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); for i, key in ipairs(expiredKeys1) do local v = redis.call('hget', KEYS[1], key); if v ~= false then local t, val = struct.unpack('dLc0', v); local msg = struct.pack('Lc0Lc0', string.len(key), key, string.len(val), val); local listeners = redis.call('publish', KEYS[4], msg); if (listeners == 0) then break;end; end;end;if #expiredKeys1 > 0 then redis.call('zrem', KEYS[4], unpack(expiredKeys1)); redis.call('zrem', KEYS[3], unpack(expiredKeys1)); redis.call('zrem', KEYS[2], unpack(expiredKeys1)); redis.call('hdel', KEYS[1], unpack(expiredKeys1)); end; local expiredKeys2 = redis.call('zrangebyscore', KEYS[3], 0, ARGV[1], 'limit', 0, ARGV[2]); for i, key in ipairs(expiredKeys2) do local v = redis.call('hget', KEYS[1], key); if v ~= false then local t, val = struct.unpack('dLc0', v); local msg = struct.pack('Lc0Lc0', string.len(key), key, string.len(val), val); local listeners = redis.call('publish', KEYS[4], msg); if (listeners == 0) then break;end; end;end;if #expiredKeys2 > 0 then redis.call('zrem', KEYS[4], unpack(expiredKeys2)); redis.call('zrem', KEYS[3], unpack(expiredKeys2)); redis.call('zrem', KEYS[2], unpack(expiredKeys2)); redis.call('hdel', KEYS[1], unpack(expiredKeys2)); end; return #expiredKeys1 + #expiredKeys2;, 6, <MAP_CACHE_NAME>, redisson__timeout__set:{<MAP_CACHE_NAME>}, redisson__idle__set:{<MAP_CACHE_NAME>}, redisson_map_cache_expired:{<MAP_CACHE_NAME>}, redisson__map_cache__last_access__set:{<MAP_CACHE_NAME>}, redisson__execute_task_once_latch:{<MAP_CACHE_NAME>}, 1516811165744, 100, 33, 1] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@50487e86] using connection RedisConnection@795684401 [redisClient=[addr=redis://<NODE_HOST_AND_PORT>], channel=[id: <channelId>, L:/... - R:/<NODE_HOST_AND_PORT>]]

DefaultChannelPipeline] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('b' (code 98)): Expected space separating root-level values
 at [Source: io.netty.buffer.ByteBufInputStream@5b82e39; line: 1, column: 3]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('b' (code 98)): Expected space separating root-level values
 at [Source: io.netty.buffer.ByteBufInputStream@5b82e39; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:466)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyRootSpace(UTF8StreamJsonParser.java:1657)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1394)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:852)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:748)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
        at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:87)
        at org.redisson.codec.MapCacheEventCodec.decode(MapCacheEventCodec.java:102)
        at org.redisson.codec.MapCacheEventCodec.access$100(MapCacheEventCodec.java:35)
        at org.redisson.codec.MapCacheEventCodec$1.decode(MapCacheEventCodec.java:44)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:257)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:287)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:276)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:93)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        ... 28 more
```

Any hints?

Client Factory

```
public final class RedissonSentinelClientFactory {

	private static final String SEPARATOR = ",";

	private RedissonSentinelClientFactory() {
		throw new UnsupportedOperationException("Cannot instantiate");
	}

	public static RedissonClient create(String masterName, String hostsAndPorts, String password, int database) {
		if (database < 0) {
			log.error("Database provided is {}", database);
			throw new IllegalArgumentException("Database index cannot be less than 0");
		}

		String[] hostsAndPortsArr = splitHostsAndPorts(hostsAndPorts);
		log.info("Initializing redis sentinel configuration {master: {}, hosts/ports: {}, database: {} }", masterName, hostsAndPortsArr,
				database);

		Config config = new Config();
		config.useSentinelServers()
				.setMasterName(masterName)
				.addSentinelAddress(hostsAndPortsArr)
				.setDatabase(database)
				.setPassword(password);

		return Redisson.create(config);
	}

	private static String[] splitHostsAndPorts(String input) {
		return Arrays.stream(input.split(SEPARATOR))
				.map(RedissonSentinelClientFactory::appendPrefix)
				.toArray(String[]::new);
	}

	private static String appendPrefix(String hostAndPort) {
		return "redis://" + hostAndPort;
	}
}
```

Usage

```
	public RedisService(String name, RedissonClient client, long expiration, long lockTimeout) {
		this.key = name + "-key";
		this.mapCache = client.getMapCache(name);
		this.updateLock = client.getLock(name + "-lock");
		this.fundsExpiration = expiration;
		this.lockTimeout = lockTimeout;
	}
      // ....
        public void addExpiredListener(BiConsumer<String, List<Product>> consumer) {
		LOGGER.info("Registering listener for expired entries");
		this.mapCache.addListener((EntryExpiredListener<String, List<Product>>) event -> {
			String eventKey = event.getKey();
			if (eventKey.equals(key)) {
				consumer.accept(event.getKey(), event.getValue());
			}
		});
	}


       // in some other class in the code. 
       // handleExpire() just re-fetches the data from an external service and saves them back again
       this.redisService.addExpiredListener((key, value) -> this.handleExpire());
```

**Comment by mrniko** [comment]
Which OS type do you use to run application with Redisson?

**Comment by xipo** [comment]
Its SunOS

**Comment by mrniko** [comment]
Please provide code example to reproduce that

**Comment by xipo** [comment]
@mrniko code example added in initial comment

**Comment by mrniko** [comment]
Sorry, but I'm unable to reproduce it with code you provided
