### ISSUE TITLE
Slow gets from redisson in CommandServiceAsyncGet

### ISSUE THREAD

**Issue by PC-AKumar** [redisson/redisson#1273]
Hi,

We are using redisson-client with cluster mode enabled with elasticache. These are the configurations for 2 separate clusters,

```
{
  "clusterServersConfig": {
    "idleConnectionTimeout": 60000,
    "pingTimeout": 1000,
    "connectTimeout": 10000,
    "timeout": 5000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "reconnectionTimeout": 3000,
    "failedAttempts": 3,
    "subscriptionsPerConnection": 5,
    "clientName": "RegularCluster",
    "sslEnableEndpointIdentification": true,
    "sslProvider": "JDK",
    "pingConnectionInterval": 0,
    "keepAlive": false,
    "tcpNoDelay": false,
    "loadBalancer": {
      "class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveConnectionMinimumIdleSize": 50,
    "slaveConnectionPoolSize": 150,
    "masterConnectionMinimumIdleSize": 50,
    "masterConnectionPoolSize": 150,
    "readMode": "MASTER",
    "subscriptionMode": "SLAVE",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "dnsMonitoringInterval": 5000,
    "nodeAddresses": [
      "redis://elastic-cache-config-end-point:6379"
    ],
    "scanInterval": 5000,
    "slaveSubscriptionConnectionPoolSize": 50,
    "slaveSubscriptionConnectionMinimumIdleSize": 1
  },
  "threads": 25,
  "nettyThreads": 50,
  "codec": {
    "class": "org.redisson.codec.SnappyCodec"
  },
  "referenceCodecProvider": {
    "class": "org.redisson.codec.DefaultReferenceCodecProvider"
  },
  "referenceEnabled": true,
  "transportMode": "NIO",
  "lockWatchdogTimeout": 30000,
  "keepPubSubOrder": true,
  "useLinuxNativeEpoll": false
}
```
```
{
  "clusterServersConfig": {
    "idleConnectionTimeout": 60000,
    "pingTimeout": 1000,
    "connectTimeout": 10000,
    "timeout": 5000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "reconnectionTimeout": 3000,
    "failedAttempts": 3,
    "subscriptionsPerConnection": 5,
    "clientName": "HighAvailCluster",
    "sslEnableEndpointIdentification": true,
    "sslProvider": "JDK",
    "pingConnectionInterval": 0,
    "keepAlive": false,
    "tcpNoDelay": false,
    "loadBalancer": {
      "class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveConnectionMinimumIdleSize": 50,
    "slaveConnectionPoolSize": 150,
    "masterConnectionMinimumIdleSize": 50,
    "masterConnectionPoolSize": 150,
    "readMode": "MASTER",
    "subscriptionMode": "SLAVE",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "dnsMonitoringInterval": 5000,
    "nodeAddresses": [
      "redis://elastic-cache-config-end-point:6379"
    ],
    "scanInterval": 5000,
    "slaveSubscriptionConnectionPoolSize": 50,
    "slaveSubscriptionConnectionMinimumIdleSize": 1
  },
  "threads": 25,
  "nettyThreads": 50,
  "codec": {
    "class": "org.redisson.codec.SnappyCodec"
  },
  "referenceCodecProvider": {
    "class": "org.redisson.codec.DefaultReferenceCodecProvider"
  },
  "referenceEnabled": true,
  "transportMode": "NIO",
  "lockWatchdogTimeout": 30000,
  "keepPubSubOrder": true,
  "useLinuxNativeEpoll": false
}

```

We see a degraded performance on all our apis and the bottle-neck seems to be from redisson. We are using spring caching and noticed that all the keys with a particular cacheName are being stored in a single shard instead of being distributed. How do we solve for actually distributing this across different shards?

We are contemplating switching to redisson.pro if it's going to help. But does the configuration look good and will redisson.pro help with the issues?

Please find attached screenshots that is showing the bottle-neck
![image](https://user-images.githubusercontent.com/19846443/35650902-98a3d476-0692-11e8-849f-967206de5ed6.png)
![image](https://user-images.githubusercontent.com/19846443/35650918-a8b213d2-0692-11e8-9bee-ab4b77b74d16.png)

**Comment by jackygurui** [comment]
> All the keys with a particular cacheName are being stored in a single shard instead of being distributed. How do we solve for actually distributing this across different shards?

Redis cluster key level sharding works by taking the crc16 value of the key name and then mod it with 16384 to determine the slot number for this key, each redis node is then responsible for arrange of the slots. If this default method created an uneven distribution, you could use [key hash tags](https://redis.io/topics/cluster-spec#keys-hash-tags) method to help with the way a slot is calculated. 

> We are contemplating switching to redisson.pro if it's going to help.

If the performance degradation was very severe at in a highly contended period, then PRO would definitely help. 

> Please find attached screenshots that is showing the bottle-neck

It's hard to say where exactly the bottle neck is from the images you sent. What you are seeing is your thread has invoked a redisson method and then the thread gets parked up for sometime. Since redisson manages a lot of work before a command is dispatched and also after a result is returned all on a different thread than the one you originally invoked. There are a number of factor that can affect the overall performance. Just to name a few (it's not a definitive list): on redisson side, there are command encoding, command queuing, connection acquiring, result parsing result decoding, etc; on Redis side, there are command queuing, command executing and result dispatching, of course network round trip is also a big factor in this. All of those times and delays are hidden behind the `LockSupport.park` line. So it would really help if you can show us how other threads are doing at the same time, redisson's netty threads in particular. 

And the most important thing, please state the version of redisson you are using. Thanks.

**Comment by PC-AKumar** [comment]
Updated my comment to have more specifics about the redis we are using.
Does the configuration look alright? Do we need more netty threads? What is a good configuration for netty threads?
I see all of them in RUNNABLE state
Snippet of the netty threads ,
```
"redisson-netty-4-36" #165 prio=5 os_prio=0 tid=0x00007ff43021b000 nid=0x5623 runnable [0x00007ff3f9b9e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(Unknown Source)
	at sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	- locked <0x00000007440d1c98> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000007441471c8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007440d1bf0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)

"redisson-netty-4-35" #164 prio=5 os_prio=0 tid=0x00007ff430219000 nid=0x5622 runnable [0x00007ff3f9c9f000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(Unknown Source)
	at sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	- locked <0x0000000743eb2d58> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000743f3d118> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000743eb2cb0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by PC-AKumar** [comment]
Another issue I am facing as we moved to redisson pro trial version is,
using redisson-all 3.6.0 again
```
WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.command.CommandAsyncService$9.operationComplete()
java.lang.NullPointerException: channel
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
	at io.netty.channel.DefaultChannelPromise.<init>(DefaultChannelPromise.java:53)
	at org.redisson.connection.t.b.send(ac:148)
	at org.redisson.command.CommandAsyncService$9.operationComplete(oj:389)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:123)
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:41)
	at org.redisson.command.CommandAsyncService.async(oj:503)
	at org.redisson.command.CommandAsyncService.evalAsync(oj:599)
	at org.redisson.command.CommandAsyncService.evalWriteAsync(oj:307)
	at org.redisson.RedissonMapCache.getOperationAsync(wf:288)
	at org.redisson.RedissonMap.getAsync(ko:800)
	at org.redisson.RedissonMap.get(ko:409)
	at org.redisson.spring.cache.RedissonCache.get(RedissonCache.java:73)
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:71)
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:536)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:502)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:388)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:326)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.safepage.user.data.impl.UserFeatureTypeMapDaoImpl$$EnhancerBySpringCGLIB$$8924d657.getUserFeatureTypeByUserId(<generated>)
	.
.
.
.
```

**Comment by mrniko** [comment]
@PC-AKumar 

> I see all of them in RUNNABLE state

It's expected behaviour, this is the way how netty epoll is working.
Basically default threads amount is enough for most cases.

**Comment by PC-AKumar** [comment]
@jackygurui  The slow down at redisson layer is very evident, causes high CPU on our instances and slowdowns in the api layer as well. Here are a few other screenshots.

@mrniko I have tried using redisson pro in LOWER_LATENCY mode, with above config and no luck here as well. Still, see the same issue with `LockSupport.park`
In some cases, `LockSupport.park` is holding the service for 1 minute(distributed across multiple method calls)

![image](https://user-images.githubusercontent.com/19846443/35699637-8622d6e0-0745-11e8-91a0-112367bef893.png)


![image](https://user-images.githubusercontent.com/19846443/35699709-b35434ec-0745-11e8-8828-c251a50d057d.png)

**Comment by PC-AKumar** [comment]
@mrniko I used RedissonClusteredSpringCacheManager, but it appears the keys are mostly still going to 1 shard(the second one is the read replica)

![image](https://user-images.githubusercontent.com/19846443/35700550-24db1296-0748-11e8-8d92-4102aea74f29.png)

**Comment by mrniko** [comment]
@PC-AKumar 

> The slow down at redisson layer is very evident, causes high CPU on our instances and slowdowns in the api layer as well. Here are a few other screenshots.
FYI, I didn't see this issue when we used jedis-client

Could you check Redis load at those moments? I think network and/or Redis setup is the bottleneck in your case. I would recommend to try more performant Redis setup.

**Comment by PC-AKumar** [comment]
@mrniko CPU usage on elasticache cluster with 6 nodes(cache.r3.large | 2 core| 13.5 gb, with 1 slave replica each) didn't exceed 35%. Checked this usual-suspect as well.

What seems to be helping right now is going back to performance HIGHER_THROUGHPUT performance mode and increasing the master connection pool size to 300 with minimum idle and max idle at 60. The Lock support blocking has reduced but we still see it frequently.

I liked the near cache concept of `org.redisson.spring.cache.RedissonSpringLocalCachedCacheManager` but I am unsure if it will support clustered sharding. If it does this will add a significant performance boost for us.

**Comment by mrniko** [comment]
@PC-AKumar 

> What seems to be helping right now is going back to performance HIGHER_THROUGHPUT performance mode and increasing the master connection pool size to 300 with minimum idle and max idle at 60

What is the average size of objects you're stored into spring cache?

> I liked the near cache concept of org.redisson.spring.cache.RedissonSpringLocalCachedCacheManager but I am unsure if it will support clustered sharding. If it does this will add a significant performance boost for us.

I have just released `3.6.0-3` version it contains `org.redisson.spring.cache.RedissonSpringClusteredLocalCachedCacheManager` class. It supports local cache and works in cluster.

**Comment by PC-AKumar** [comment]
@mrniko We store roughly 17kb on an average, median will probably around 50

Thanks for the update with near cache, will try it out.
