### ISSUE TITLE
NPE with redisson pro

### ISSUE THREAD

**Issue by PC-AKumar** [redisson/redisson#1274]
I am using redisson pro trial version(3.6.0) in cluster config with elasticache(redis=3.2.6), I see NPE in get and evict operations using spring cache framework. I don't see this issue with the community version(3.6.0) and same configuration

It basically just gives this error and hangs. I think the exception is being swallowed by DefaultPromise
```
WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.command.CommandAsyncService$9.operationComplete()
java.lang.NullPointerException: channel
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
	at io.netty.channel.DefaultChannelPromise.<init>(DefaultChannelPromise.java:53)
	at org.redisson.connection.t.b.send(ac:148)
	at org.redisson.command.CommandAsyncService$9.operationComplete(oj:389)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:123)
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:41)
	at org.redisson.command.CommandAsyncService.async(oj:503)
	at org.redisson.command.CommandAsyncService.evalAsync(oj:599)
	at org.redisson.command.CommandAsyncService.evalWriteAsync(oj:307)
	at org.redisson.RedissonMapCache.getOperationAsync(wf:288)
	at org.redisson.RedissonMap.getAsync(ko:800)
	at org.redisson.RedissonMap.get(ko:409)
	at org.redisson.spring.cache.RedissonCache.get(RedissonCache.java:73)
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:71)
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:536)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:502)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:388)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:326)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.safepage.user.data.impl.UserFeatureTypeMapDaoImpl$$EnhancerBySpringCGLIB$$8924d657.getUserFeatureTypeByUserId(<generated>)
```

**Comment by mrniko** [comment]
Fixed in `3.6.0-1` version. As workaround you can also switch back to netty `4.1.20.Final`.
