### ISSUE TITLE
Error while creating bean of RScheduledExecutorService

### ISSUE THREAD

**Issue by shinigamiryuk** [redisson/redisson#1301]
I am trying to create a singleton bean of RScheduledExecutorService in Spring 4. I have not yet autowired this bean anywhere. I am always ending up with error. I am working with Redisson 2.11. 

Unable to find any kind of solution or any instances of problem with anyone else here. Is this a bug ? 
Since it is a JsonMappingException I also tried using different codes but nothing helped. 

`SEVERE: StandardWrapper.Throwable
java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.springframework.scheduling.concurrent.ReschedulingRunnable["cancelled"])
	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:317)
	at org.redisson.RedissonExecutorService.scheduleAsync(RedissonExecutorService.java:741)
	at org.redisson.RedissonExecutorService.schedule(RedissonExecutorService.java:700)
	at org.redisson.RedissonExecutorService.schedule(RedissonExecutorService.java:92)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.schedule(ReschedulingRunnable.java:73)
	at org.springframework.scheduling.concurrent.ConcurrentTaskScheduler.schedule(ConcurrentTaskScheduler.java:170)
	at org.springframework.scheduling.config.ScheduledTaskRegistrar.scheduleTasks(ScheduledTaskRegistrar.java:306)
	at org.springframework.scheduling.config.ScheduledTaskRegistrar.afterPropertiesSet(ScheduledTaskRegistrar.java:284)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.finishRegistration(ScheduledAnnotationBeanPostProcessor.java:208)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:162)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:85)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:664)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:536)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:490)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)`

**Comment by mrniko** [comment]
Please share the code to reproduce this problem

**Comment by shinigamiryuk** [comment]
@mrniko it seems like a code issue from our end. I was using EnableScheduling annotation on ApplicationConfig file while creating beans. When removed it was working normally. You can reject this issue as it was not an issue in the first place.
