### ISSUE TITLE
"Unable to init enough connections" when ConnectionMinimumIdleSize is high

### ISSUE THREAD

**Issue by maltalex** [redisson/redisson#1315]
We're having trouble spinning up redisson (3.6.1) when the minimum number of connections is high.

Steps to reproduce:

1. Run a local redis server. We used the official docker image:

`docker container run -d --name redis -p 6379:6379 redis`

2. Try to create a redisson client with a high number of idle connections, short retry interval and some client name:

```
public static void main(String[] args) {
    Config config = new Config();
    config.useSingleServer()
            .setAddress("redis://127.0.0.1:6379")
            .setClientName("client")
            .setConnectionMinimumIdleSize(1000)
            .setConnectionPoolSize(2000)
            .setRetryInterval(100);
    RedissonClient client = Redisson.create(config);
    System.out.println("Done!");
}
```

More often than not, we're getting the following exception after a few seconds, with a varying number if successful connections:

```
Exception in thread "main" org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 440 from 1000 were initialized. Redis server: /127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:138)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:512)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:425)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:307)
	at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:54)
	at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:277)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:512)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:505)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:484)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:425)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
	at org.redisson.client.RedisClient$2$1$1$1.run(RedisClient.java:215)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for /127.0.0.1:6379
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	... 6 more
```

**Comment by jackygurui** [comment]
You can try a higher value for the `connectTimeout` parameter, the default value is 10000.

Out of my curiosity, why do you need so many connections? Is it a just test or there is a particular reason?

**Comment by maltalex** [comment]
@jackygurui Aren't connection timeouts per-connection? Also, the repro code throws an exception after less than 10 seconds on my machine, so I don't think that's it.
I know 1K connections is a bit over the top. It's a number I used for the reproduction, not for actual usage.

**Comment by jackygurui** [comment]
Sorry, you're right. 

Try adjust `retryInterval` & `retryAttempts` instead.

**Comment by maltalex** [comment]
@jackygurui I'll try, but why should that work? Retries affect what happens after a failure, here it seems that redisson gives up on the initial connection too soon.

**Comment by jackygurui** [comment]
The problem you are having is caused by redisson is unable to execute a command that's required as part of the connection initialisation process. In your case, I think it is most likely to be the command setting the client name. By changing the two configs I mentioned, you will have better chance of success.

**Comment by maltalex** [comment]
Thanks. I'll try it out. 
But just to be clear, I'd like to know though whether this behavior is considered normal for redisson, even if tweaking the configuration reduces the chance of it happening.

**Comment by jackygurui** [comment]
> I'd like to know though whether this behavior is considered normal for redisson

If I understood correctly that "this behaviour" you are referring to the fact that a command is executed after connection is established, then the answer is yes.

**Comment by maltalex** [comment]
No, I was asking whether the exception thrown after `Redisson.create()` is considered normal. I realize that the situation can be improved by using fewer connections, more retries, and avoiding `setClientName()`, but these are workarounds, not solutions.

**Comment by jackygurui** [comment]
In general, exception thrown after `Redisson.create()` is considered NOT normal. However the problem you are observing was due to the fact that your initial connection size is far larger than what it is considered to be normal hence you need to adjust other settings to accordingly.

**Comment by jackygurui** [comment]
> I suspect that the same can occur if there are fewer connections, but the redis instance is far away, or slow to respond, or connected through a congested network or something similar. Is my understanding correct?

Absolutely, which is why you need to override the default settings to adapt your environment.

**Comment by jackygurui** [comment]
> Anyway, it's completely up to you guys to decide whether this is something you want to fix. We appreciate the work that's been put into redisson.

Your support is much appreciated. If you have any better idea and/or advice please by all means let us know.
