### ISSUE TITLE
Jcache - getAndRemove method is throwing an NPE

### ISSUE THREAD

**Issue by dfortier-jive** [redisson/redisson#1327]
We configured a Redisson cached based on Jcr-107. Most operations are working fine but the getAndRemove implementation is throwing a null pointer exception. When removing the key with cache.remove("key"); instead, it works fine. We could do it in two operations but it will lose the free Atomicity.
Unfortunately, I'm not fluent in the LUA scripting used in order to propose a solution at the moment

```
javax.cache.CacheException: org.redisson.client.RedisException: Unexpected exception while processing command

	at org.redisson.jcache.JCache.evalWrite(JCache.java:342)
	at org.redisson.jcache.JCache.getAndRemoveValue(JCache.java:1445)
	at org.redisson.jcache.JCache.getAndRemove(JCache.java:1521)
	at com.jive.jci.cache.redisson.RedissonDefaultResourceIT.getAndRemoveTest(RedissonDefaultResourceIT.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:338)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:169)
	at org.redisson.RedissonObject.get(RedissonObject.java:74)
	at org.redisson.jcache.JCache.evalWrite(JCache.java:340)
	... 27 more
Caused by: java.lang.NullPointerException
	at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:401)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:345)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:329)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Code that show the issue:
``` java
    String host = REDIS.getContainerIpAddress();
    int port = REDIS.getMappedPort(6379);
    MutableConfiguration<String, String> jcacheConfig = new MutableConfiguration<>();

    Config redissonConfig = new Config();
    redissonConfig.setCodec(new JsonJacksonCodec());

    redissonConfig.useSingleServer()
        .setAddress("redis://" + host + ":" + port);

    Configuration<String, String> jConfig = RedissonConfiguration.fromConfig(
        redissonConfig, jcacheConfig);


    CacheManager manager = Caching.getCachingProvider("org.redisson.jcache.JCachingProvider")
        .getCacheManager();

    try (Cache<String, String> cache = manager.createCache("strings", jConfig);)
    {
      cache.put("key", "value");
      String result = cache.getAndRemove("key");

      Assert.assertEquals("value", result);
      Assert.assertNull(cache.get("key"));

      cache.put("key", "value");
      cache.remove("key");
      Assert.assertNull(cache.get("key"));
    }
```

Dependencies:
Redisson: 3.6.1
Redis: Vanilla docker image version 4.0.8
JDK: 1.8.0_151

```[INFO] com.jive.jci:jci-cache:jar:5.1.8-SNAPSHOT
[INFO] +- org.ehcache:ehcache:jar:3.4.0:compile
[INFO] +- org.cache2k:cache2k-all:jar:1.0.1.Final:compile
[INFO] +- org.cache2k:cache2k-api:jar:1.0.1.Final:provided
[INFO] +- org.redisson:redisson:jar:3.6.1:provided
[INFO] |  +- io.netty:netty-common:jar:4.1.21.Final:provided
[INFO] |  +- io.netty:netty-codec:jar:4.1.21.Final:provided
[INFO] |  +- io.netty:netty-buffer:jar:4.1.21.Final:provided
[INFO] |  +- io.netty:netty-transport:jar:4.1.21.Final:provided
[INFO] |  |  \- io.netty:netty-resolver:jar:4.1.21.Final:provided
[INFO] |  +- io.netty:netty-resolver-dns:jar:4.1.21.Final:provided
[INFO] |  |  \- io.netty:netty-codec-dns:jar:4.1.21.Final:provided
[INFO] |  +- io.netty:netty-handler:jar:4.1.21.Final:provided
[INFO] |  +- io.projectreactor:reactor-core:jar:3.1.1.RELEASE:provided
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.1:provided
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.1:provided
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.18:provided
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.1:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.7.10:provided
[INFO] |  \- org.jodd:jodd-bean:jar:3.7.1:provided
[INFO] |     \- org.jodd:jodd-core:jar:3.7.1:provided
[INFO] +- javax.cache:cache-api:jar:1.0.0:compile
[INFO] +- org.projectlombok:lombok:jar:1.16.18:provided
[INFO] +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.25:runtime
[INFO] +- org.slf4j:jul-to-slf4j:jar:1.7.25:runtime
[INFO] \- org.slf4j:log4j-over-slf4j:jar:1.7.25:runtime```

**Comment by mrniko** [comment]
Fixed! Thanks for report!
