### ISSUE TITLE
Unable to connect AWS elastic Cahce over SSL in Cluster mode

### ISSUE THREAD

**Issue by jayarampradhan** [redisson/redisson#1334]
I am using lib version: 3.6.2
When trying to connect AWS Elastic cache(i.e `rediss://clustercfg.xxx-test-sample.ttt.usw2.cache.amazonaws.com:6379`) over `ssl` in `cluster` mode getting below exception:
```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
                at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1529)
                at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
                at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
                at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
                at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
                at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292)
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1257)
                at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
                at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1203)
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
                ... 16 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
                at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
                at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
                at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:330)
                at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
                at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
                at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
                at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
                at sun.security.ssl.Handshaker$1.run(Handshaker.java:992)
                at sun.security.ssl.Handshaker$1.run(Handshaker.java:989)
                at java.security.AccessController.doPrivileged(Native Method)
                at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467)
                at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1417)
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1325)
                ... 20 common frames omitted
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 10.82.141.245 found
                at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:168)
                at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
                at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
                at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
                at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
                at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
                at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1601)
```

Not sure whats going wrong here, as per documents AWS manages the SSL certs so ideally this exception shouldn't have arrises.
I see this was closed as part of the issue #1135 . How ever single server mode with SSL is working fine. Could you please help me on this?

**Comment by mrniko** [comment]
Could you share your Redisson configuration?

**Comment by jayarampradhan** [comment]
Here is the configuration:
```java
public RedissonClient redissonClient() {
        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.useClusterServers();
        clusterServersConfig.addNodeAddress("rediss://clustercfg.xxx-test-sample.ttt.usw2.cache.amazonaws.com:6379");
        if (getRedisProperties().getPassword() != null) {
            clusterServersConfig.setPassword(getRedisProperties().getPassword());
        }

        clusterServersConfig.setConnectTimeout(1000);
        clusterServersConfig.setMasterConnectionPoolSize(50);
        clusterServersConfig.setMasterConnectionMinimumIdleSize(0);
        clusterServersConfig.setRetryInterval(500);
        clusterServersConfig.setReconnectionTimeout(1000);
        clusterServersConfig.setSubscriptionConnectionMinimumIdleSize(0);
        clusterServersConfig.setSlaveConnectionMinimumIdleSize(0);
       //Tried with OPENSSL as well with default JDK
        if (getRedissonProperties().getRedisson().isUseOpenSSL()) {
            clusterServersConfig.setSslProvider(SslProvider.OPENSSL);
        }
       return Redisson.create(config);
}
```

**Comment by mrniko** [comment]
It seems related to this one https://github.com/redisson/redisson/issues/1296

**Comment by mrniko** [comment]
Fixed
