### ISSUE TITLE
Deserializing Nested RMap throws NotSerializableException 

### ISSUE THREAD

**Issue by kaniska** [redisson/redisson#1335]
I am using **org.redisson.codec.SerializationCodec** and   **redisson 3.6.0**
I have **a child Rmap inside a parent Rmap**. 
Facing an Exception while fetching the stored Rmap 
- java.io.NotSerializableException: org.redisson.RedissonReference

**Is Rmap serializable ?**  
**How can I use a codec for fetching (get) and storing (put) Rmap from inside a parent Rmap ?**

/////////////////  
// onetime-initialization
RMap<String,Map<String,Long> parentMap = redisson.getMap("parentMap");
/////////////

if(parentMap.containsKey("child") == null) { 
 parentMap.put("child",redisson.getMapCache("childMapCache"));  
}
RMap childCache = parentMap.get("child");
childCache.put("test1", 1000));

///////////////////////////////////

**as long as I don't restart the application , it works fine**
**upon subsequent restart, it fails in the step -> parentMap.get("child");**  

[ERROR] Exception : Unexpected exception while processing command
org.redisson.client.RedisException: Unexpected exception while processing command
        at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:322) ~[stormjar.jar:?]
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165) ~[stormjar.jar:?]
        at org.redisson.RedissonObject.get(RedissonObject.java:69) ~[stormjar.jar:?]
        at org.redisson.RedissonMap.put(RedissonMap.java:191) ~[stormjar.jar:?]

////////
Caused by: java.io.NotSerializableException: org.redisson.RedissonReference
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[?:1.8.0_72]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_72]
        at org.redisson.codec.SerializationCodec$2.encode(SerializationCodec.java:64) ~[stormjar.jar:?]
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:103) ~[stormjar.jar:?]
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:45) ~[stormjar.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[stormjar.jar:?]
////////////

**Comment by jackygurui** [comment]
This should have been fixe since version 3.4.3. See https://github.com/redisson/redisson/commit/2c4761f1b5d3e5d6de5fdd710009965b2cc393ce 

Can you double check your classpath and see if there are any conflicts?
