### ISSUE TITLE
ERR Error running script (call to f_8770695dc269722cd5368a1e08ca936b4ccbb0b7): @user_script:1: user_script:1: bad argument #2 to 'unpack'

### ISSUE THREAD

**Issue by kumar-pratyaksh** [redisson/redisson#1339]
Getting error when calling readAllKeySet() operation.

org.redisson.client.RedisException: ERR Error running script (call to f_8770695dc269722cd5368a1e08ca936b4ccbb0b7): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x0f03b43a, L:/192.168.1.66:57481 - R:/192.168.1.159:6379] command: (EVAL), params: [local s = redis.call('hgetall', KEYS[1]); local maxSize = tonumber(redis.call('hget', KEYS[5], 'max-..., 5, userDataCache, redisson__timeout__set:{userDataCache}, redisson__idle__set:{userDataCache}, redisson__map_cache__last_access__set:{userDataCache}, {userDataCache}:redisson_options, 1521112711284]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:241)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
This error means that objects of different types share same key name.

**Comment by kumar-pratyaksh** [comment]
<img width="1680" alt="screen shot 2018-03-15 at 5 27 12 pm" src="https://user-images.githubusercontent.com/25146461/37461929-23132788-2876-11e8-9c89-9d4b072e16ac.png">
This is the screenshot of the current redis data.
We are trying to remove keys with a specific pattern which is in the begining of each key.
For example: 86BAE1CC0850E1FA06BE180E53194E79*
we tried using readAllKeys function but it gave the exception.
And the keySet function is returning empty array.
Do you have a solution for this or any alternate approach. Please help.

**Comment by mrniko** [comment]
Could you provide code example to reproduce the problem?

**Comment by kumar-pratyaksh** [comment]
This problem was occurring when we were trying to manually delete keys from redis with a specific pattern.
Basically all the keys that we were making had session ids in the beginning and the data in the keys was session specific,  so on session end we had to delete the data from redis. But as you can see from the picture posted in above comment that the data differed in content for each key.
But now we have set ttl and idle time so it should't be a problem anymore. BTW we are using spring data caching with redisson client.

**Comment by mrniko** [comment]
Redisson Spring data caching consists of multiple objects. I strongly recommended to remove data only through Redisson methods belong to corresponding object.

**Comment by kumar-pratyaksh** [comment]
We are doing it now. Thanks
