### ISSUE TITLE
Can't execute SENTINEL commands on /

### ISSUE THREAD

**Issue by wq163** [redisson/redisson#1351]
redisson throw follow exception, while start app everytime.

redisson version:  3.6.3
redis version:4.0.8

18:56:00.262 [nioEventLoopGroup-2-1] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@752529858 [redisClient=[addr=redis://172.16.4.115:6379], channel=[id: 0x8e14d761, L:/172.16.4.109:61553 - R:/172.16.4.115:6379]]
18:56:00.262 [nioEventLoopGroup-2-1] INFO org.redisson.connection.pool.MasterConnectionPool - 32 connections initialized for /172.16.4.115:6379
18:56:05.779 [nioEventLoopGroup-2-1] ERROR org.redisson.connection.SentinelConnectionManager - Can't execute SENTINEL commands on /172.16.4.115:26379
org.redisson.client.RedisTimeoutException: Command execution timeout for /172.16.4.115:26379
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by langyan1022** [comment]
请问你解决了没

**Comment by jackygurui** [comment]
Please see [FAQ](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it) regarding RedisTimeoutException
