### ISSUE TITLE
单机升级集群出现的问题

### ISSUE THREAD

**Issue by JanChao** [redisson/redisson#1355]
项目使用redisson的单机模式，现在要升级为集群模式，搭建好redis服务后启动项目出现如下错误：

```
2018-03-23 15:22:25,978 [main] INFO  org.nutz.log.Log$info.call(?:?)
 --- Redis Server:192.168.28.60:6379,192.168.28.60:6380,192.168.28.60:6381
2018-03-23 15:22:25,979 [main] INFO  org.nutz.log.Log$info.call(?:?)
 --- Redis Server:192.168.28.60:6379
2018-03-23 15:22:25,992 [main] INFO  org.nutz.log.Log$info.call(?:?)
 --- Redis Server:192.168.28.60:6380
2018-03-23 15:22:25,993 [main] INFO  org.nutz.log.Log$info.call(?:?)
 --- Redis Server:192.168.28.60:6381
2018-03-23 15:24:49,894 [main] WARN  org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:94)
 --- port out of range:-1
2018-03-23 15:26:10,913 [main] WARN  org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:94)
 --- port out of range:-1
2018-03-23 15:26:19,812 [main] ERROR org.nutz.log.Log$error$0.call(?:?)
 --- Can't connect to servers!
org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:100)
	at org.redisson.Redisson.<init>(Redisson.java:108)
	at org.redisson.Redisson.create(Redisson.java:158)
	at com.asiainfo.mm.biz.util.RedissonUtil.create(RedissonUtil.groovy:17)
	at com.asiainfo.mm.biz.util.RedissonUtil$create.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.asiainfo.mm.MvcSetup.init(MvcSetup.groovy:61)
	at org.nutz.mvc.impl.NutLoading.evalSetup(NutLoading.java:256)
	at org.nutz.mvc.impl.NutLoading.load(NutLoading.java:115)
	at org.nutz.mvc.ActionHandler.<init>(ActionHandler.java:19)
	at org.nutz.mvc.NutFilter.init(NutFilter.java:78)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:137)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:831)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:300)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1341)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1334)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:744)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:281)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:154)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:357)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
	at org.eclipse.jetty.server.Server.doStart(Server.java:324)
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:68)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:564)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:360)
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

```

程序代码为如下：
```
log.info("初始化Redis Client")

                Config redisConfig = new Config()
                def serverConfig = redisConfig.useClusterServers()

                String hosts = DictItemUtil.REDIS_CONFIG.value()

                log.info("Redis Server:" + hosts)
                for (String host : hosts.split(",")) {
                    log.info("Redis Server:" + host)
                    serverConfig.addNodeAddress(host)
                }
//                def serverConfig = redisConfig.useSingleServer()
//
//                String hosts = DictItemUtil.REDIS_CONFIG.value()

//                serverConfig.setAddress("192.168.28.60:6379")

                RedissonUtil.create(redisConfig)
```
单机模式使用192.168.28.60:6379可以成功，现在使用 集群addNodeAddress增加三台实例（192.168.28.60:6379  192.168.28.60:6380  192.168.28.60:6381）时就出现如上错误，字面理解是端口有问题，但是6379 这样的端口应该没问题吧，请大神赐教

**Comment by jackygurui** [comment]
应该是地址格式的问题。正确的地址格式是`redis://192.168.28.60:6379`，如果是SSL连接请使用`rediss://192.168.28.60:6379`

**Comment by JanChao** [comment]
多谢！现在已经解决了，存在两个问题一个是地址格式错误，另外一个是redis集群没配置正确。
另外项目使用的redisson版本很旧了（2.2.10），换成新版后没问题了。
