### ISSUE TITLE
哪个codec支持LocalDateTime/LocalDate？

### ISSUE THREAD

**Issue by gaecfov** [redisson/redisson#1358]
哪个codec支持LocalDateTime/LocalDate？
有如何自定义Codec的文档吗？

**Comment by jackygurui** [comment]
FstCodec和SerializationCodec支持，以Jackson为基础的Codec需要额外的配置才支持。

自定义Codec可以参看[Codec接口](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/client/codec/Codec.java)，也可以用[复合Codec](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/codec/CompositeCodec.java)实现。

**Comment by gaecfov** [comment]
谢谢回复，我使用了JsonJacksonMapCodec，增加了jackson-datatype-jsr310的依赖，但是Deserializer的时候依然异常了，不过JSON数据已经是正常的了，请问还有什么地方需要配置吗？
```
public class JsonCodec extends JsonJacksonMapCodec {
    public JsonCodec() {
        super(String.class, LocalDateTime.class);
    }

    @Override
    protected void init(ObjectMapper objectMapper) {
        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        objectMapper.registerModule(new JavaTimeModule());
        super.init(objectMapper);
    }
}
```
```
2018-03-25 11:20:15.820 ERROR 10764 --- [isson-netty-1-8] o.r.client.handler.CommandDecoder        : Unable to decode data. channel: [id: 0x280a20d9, L:/127.0.0.1:56123 - R:localhost/127.0.0.1:6379] message: $60
{"shopCode":"test_cache_1","time":"2018-03-25T11:20:02.266"}


com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected VALUE_STRING: Expected array or string.
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1507) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:141) ~[jackson-datatype-jsr310-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:39) ~[jackson-datatype-jsr310-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058) ~[jackson-databind-2.9.4.jar:2.9.4]
	at org.redisson.client.codec.JsonJacksonMapCodec$2.decode(JsonJacksonMapCodec.java:68) ~[redisson-3.6.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:309) ~[redisson-3.6.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:109) ~[redisson-3.6.3.jar:na]
```

**Comment by beykery** [comment]
怎么关了？怎么解决的？

**Comment by npe2023** [comment]
同问啊，怎么处理啊，redisson网上资料真的少。
