### ISSUE TITLE
IllegalStateException: availableProcessors is already set to [8], rejecting [8]

### ISSUE THREAD

**Issue by ptahchiev** [redisson/redisson#1359]
Hello,

i'm using embedded elasticsearch in my application with EHCache and it all works fine. Now I want to configure redisson and I get this exception during startup:
````
Caused by: java.lang.IllegalStateException: availableProcessors is already set to [8], rejecting [8]
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
	at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
	at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:85)
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.<init>(Netty4HttpServerTransport.java:219)
	at org.elasticsearch.transport.Netty4Plugin.lambda$getHttpTransports$1(Netty4Plugin.java:105)
	at org.elasticsearch.node.Node.<init>(Node.java:438)
	at com.nemesis.platform.module.search.elasticsearch.config.ElasticsearchAutoConfiguration$1.<init>(ElasticsearchAutoConfiguration.java:129)
````
Looks like redisson has already initialized a netty runtime and elasticsearch is trying to do the same so it blows with this error.

**Comment by ptahchiev** [comment]
Ignore this issue - it seems like it's an issue with elasticsearch.

**Comment by nkalra0123** [comment]
@ptahchiev I am also getting same issue, How did you solve this issue?
