### ISSUE TITLE
Java 10 support

### ISSUE THREAD

**Issue by l0co** [redisson/redisson#1367]
Java 10 looks currently not supported because `highMask` and `lowMask` private methods are removed from `URI` class what is referenced [here](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/ConfigSupport.java#L129-L130).

```
Caused by: java.io.IOException: java.lang.NoSuchMethodException: java.net.URI.lowMask(java.lang.String)
	at org.redisson.config.ConfigSupport.patchUriField(ConfigSupport.java:147)
	at org.redisson.config.ConfigSupport.patchUriObject(ConfigSupport.java:127)
	at org.redisson.config.ConfigSupport.toJSON(ConfigSupport.java:183)
	at org.redisson.config.Config.toJSON(Config.java:659)
	at org.hibernate.cache.redis.client.RedisClient.<init>(RedisClient.java:62)
	at org.hibernate.cache.redis.client.RedisClient.<init>(RedisClient.java:57)
	at io.luna.lib.postgres.LunaRedisRegionFactory.createRedisClient(LunaRedisRegionFactory.java:49)
	at org.hibernate.cache.redis.hibernate52.SingletonRedisRegionFactory.start(SingletonRedisRegionFactory.java:55)
	... 40 common frames omitted
Caused by: java.lang.NoSuchMethodException: java.net.URI.lowMask(java.lang.String)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2434)
	at org.redisson.config.ConfigSupport.patchUriField(ConfigSupport.java:134)
	... 47 common frames omitted
```

**Comment by l0co** [comment]
Of course removed without fixing [this)(https://stackoverflow.com/questions/28568188/java-net-uri-get-host-with-underscores/28568433)

**Comment by mrniko** [comment]
It's a known bug. I haven't test Redisson with JDK 10 yet.

**Comment by l0co** [comment]
All tests of my system passed right now after this fix, I use redisson a lot. So maybe this is the only thing required to be fixed. You can quick-fix this by wrapping it in `NoSuchMethodException` try..catch and ignore patching with warning.

**Comment by mrniko** [comment]
Good point

**Comment by mrniko** [comment]
Fixed
