### ISSUE TITLE
[CRITICAL] Redisson cluster sync failed

### ISSUE THREAD

**Issue by yandooo** [redisson/redisson#1378]
In cluster mode when master goes down and slave becomes a master, Redisson picks up new master but failes to sync slaves. Cluster nodes synchronisation crashes (never scheduled again) with `IllegalArgumentException` while processing slave nodes.

Redis cluster setup:
 - 3 masters
- 3 slaves

Relevant stacktrace:

```

April 6th 2018, 12:58:39.000 | java.lang.IllegalStateException: Can't find redis://10.3.0.74:6379 in slaves!
-- | --

  | April 6th 2018, 12:58:39.000 | at org.redisson.connection.balancer.LoadBalancerManager.unfreeze(LoadBalancerManager.java:120) ~[redisson-3.6.4.jar!/:na]

  | April 6th 2018, 12:58:39.000 | at org.redisson.connection.MasterSlaveEntry.slaveUp(MasterSlaveEntry.java:383) ~[redisson-3.6.4.jar!/:na]

  | April 6th 2018, 12:58:39.000 | at org.redisson.cluster.ClusterConnectionManager.upDownSlaves(ClusterConnectionManager.java:439) ~[redisson-3.6.4.jar!/:na]

  | April 6th 2018, 12:58:39.000 | at org.redisson.cluster.ClusterConnectionManager.checkSlaveNodesChange(ClusterConnectionManager.java:426) ~[redisson-3.6.4.jar!/:na]

  | April 6th 2018, 12:58:39.000 | at org.redisson.cluster.ClusterConnectionManager.access$1400(ClusterConnectionManager.java:74) ~[redisson-3.6.4.jar!/:na]

  | April 6th 2018, 12:58:39.000 | at org.redisson.cluster.ClusterConnectionManager$4.operationComplete(ClusterConnectionManager.java:401) ~[redisson-3.6.4.jar!/:na]

  | April 6th 2018, 12:58:39.000 | at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]

  | April 6th 2018, 12:58:39.000 | at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) [netty-common-4.1.22.Final.jar!/:4.1.22.Final]

  | April 6th 2018, 12:58:39.000 | 2018-04-06 11:58:39.248 DEBUG 1 --- [isson-netty-1-1] o.r.cluster.ClusterConnectionManager     : cluster nodes state from /10.3.0.33:6379:

```

Code path which fails with `IllegalArgumentException` (**please note it's 3.0.0 branch**):

https://github.com/redisson/redisson/blob/3.0.0/redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java#L401

`scheduleClusterChangeCheck(cfg, null);` is never executed thus Redisson stops sync cluster state. Any subsequent cluster change leads to a service outage.

**Comment by yandooo** [comment]
@mrniko it's quite critical issue at the moment. Any chance you can have a look? Thanks.

**Comment by mrniko** [comment]
Fixed
