### ISSUE TITLE
RMI starts to lose ability to send commands

### ISSUE THREAD

**Issue by bhoover10001** [redisson/redisson#1384]
We are using Redisson 3.6.4 and publishing several hundred RMIs at a time.  After a few minutes, we start seeing these errors, and they start to build up over time, until no RMIs are being processed at all.

We are on a clustered AWS Redis server

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@7fac4f35], connection: [id: 0xb6a1891b, L:/10.98.84.55:58609 - R:/10.98.81.47:6379], command: (HGET), command params: [{redisson_rs:com.davisnet.weatherlink.commons.service.remoteservices.StationDataServiceIf}:tasks, PooledUnsafeDirectByteBuf(ridx: 0, widx: 32, cap: 256)] after 3 retry attempts
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663) [1 skipped]
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
[1 skipped]

**Comment by bhoover10001** [comment]
That fixed the problem.  Thanks for the quick help!
