### ISSUE TITLE
Can't update cluster state

### ISSUE THREAD

**Issue by 921vikram** [redisson/redisson#1397]
Hi,

I am getting below error message when one for the node goes down from the cluster (3 node master/slave cluster).  version of redisson (2.7.4). 

Message                            | function                | Classname  
Can't update cluster state | checkClusterState | org.redisson.cluster.ClusterConnectionManager

Above message is keeps on coming. And on subsequent call to redisson leads to below exception.

Caused by: java.lang.NullPointerException 
at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:733) [redisson-2.7.4.jar:] 
at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:501) [redisson-2.7.4.jar:] 
at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:335) [redisson-2.7.4.jar:] 
at org.redisson.RedissonMap.containsKeyAsync(RedissonMap.java:135) [redisson-2.7.4.jar:] 
at org.redisson.RedissonMap.containsKey(RedissonMap.java:126) [redisson-2.7.4.jar:] 

Please help me on this. I found one of the related issue https://github.com/redisson/redisson/issues/1366

Thanks
Vikram

**Comment by mrniko** [comment]
Did you try latest version? I fixed a few bugs in MasterSlaveConnectionManager object since 2.7.4 version

**Comment by 921vikram** [comment]
Hi,

I have updated the resisson library to 2.11.5. So After one node fail over we are not seeing above issue. but getting following error. We are not seeing any functionality issue. But wanted to understand the what is the problem now.

JBWEB000236: Servlet.service() for servlet Resteasy threw exception: org.jboss.resteasy.spi.UnhandledException: org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts: [jcs-ha-test-demo-ip2.englab.juniper.net/10.213.13.162:6379] Hosts disconnected due to errors during `failedSlaveCheckInterval`: [jcs-ha-test-demo-ip1.englab.juniper.net/10.213.13.161:6380]
	at org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:369) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:237) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:213) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:598) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:565) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:130) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.20.Final-redhat-1.jar:]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.17.Final-redhat-4.jar:7.5.17.Final-redhat-4]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.17.Final-redhat-4.jar:7.5.17.Final-redhat-4]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.17.Final-redhat-4.jar:7.5.17.Final-redhat-4]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:151) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:656) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.24.Final-redhat-1.jar:]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.7.0_151]
Caused by: org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts: [jcs-ha-test-demo-ip2.englab.juniper.net/10.213.13.162:6379] Hosts disconnected due to errors during `failedSlaveCheckInterval`: [jcs-ha-test-demo-ip1.englab.juniper.net/10.213.13.161:6380]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:197) [redisson-2.11.5.jar:]
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30) [redisson-2.11.5.jar:]
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:240) [redisson-2.11.5.jar:]
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:502) [redisson-2.11.5.jar:]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:595) [redisson-2.11.5.jar:]
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:497) [redisson-2.11.5.jar:]
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:589) [redisson-2.11.5.jar:]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) [netty-common-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) [netty-common-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) [netty-common-4.1.23.Final.jar:4.1.23.Final]
	... 1 more

**Comment by mrniko** [comment]
Good to see that Juniper also uses it. This error says that `jcs-ha-test-demo-ip1.englab.juniper.net` host has been disconnected, because of errors during time interval defined by `Config.failedSlaveCheckInterval`. Please ensure this host is alive. Could you also share your config?

**Comment by 921vikram** [comment]
Hi,

We are getting error in reading data after one of the node goes down from the cluster. We are querying for a key "domainNameCache". 

Expected behavior- Client should fetch the value from other node if record is moved.  We are using Redisson client version 2.11.5 

Exception-
Caused by: org.redisson.client.RedisTimeoutException: Redis server response timeout (10000 ms) occured for command: (HEXISTS) with params: [domainNameCache, PooledUnsafeDirectByteBuf(ridx: 0, widx: 39, cap: 256)] channel: [id: 0xa48e335b, L:/172.16.93.8:39959 - R:jcs-ha-test-demo-ip1.englab.juniper.net/10.213.13.161:6380]"}


Redisson CLI output-

127.0.0.1:6379> keys *
1) "XXX_default-project"
2) "dXXXXXXXe"
3) "AXXXXEN"
4) "DistributedXXXXXCache"
5) "Tenant_15XXXX_15"
6) "FMXXXXXac-9e36-82f516777c0d::site"
7) "csXXXXX6"


127.0.0.1:6380> keys *
1) "FMXXXXXe797c::site"
2) "FMXXXXla_profile"
3) "FMXXXXinks"
4) "FMXXXXnks"
5) "domainNameCache"


127.0.0.1:6380> dump "domainNameCache"
(error) MOVED 9259 10.213.13.162:6379
127.0.0.1:6380> exit

127.0.0.1:6379> cluster nodes
e54de2e1d87b2a2921524c4a10e78f5663ffc91c 10.213.13.162:6379 master - 0 1524654147400 8 connected 5461-10922
32457dad80e0a203264045ffc615dd5256d04978 10.213.13.162:6380 slave 638b198bf6943f28e86bdaf23f2ff6d9276a2ede 0 1524654148401 3 connected
1a6387a7a2b33ac08e25527af55b59fa91e6399e 10.213.13.161:6380 slave e54de2e1d87b2a2921524c4a10e78f5663ffc91c 0 1524654147899 8 connected
638b198bf6943f28e86bdaf23f2ff6d9276a2ede 10.213.13.163:6379 master - 0 1524654149402 3 connected 10923-16383
586b0af5604fd68aeb7fe47a07b6f2299ed4adfb 10.213.13.163:6380 slave 19c85e4327a2c95dfb5c167ab737c631ce78da3b 0 1524654148401 10 connected
19c85e4327a2c95dfb5c167ab737c631ce78da3b 10.213.13.161:6379 myself,master - 0 0 10 connected 0-5460

Thanks
Vikram

**Comment by mrniko** [comment]
Could you share Redisson config?

**Comment by mrniko** [comment]
Redisson correctly handles MOVED response. Here is the test https://github.com/redisson/redisson/blob/6247ba52c66354aa79448890a0b1889922a07dcb/redisson/src/test/java/org/redisson/RedissonTest.java#L644. In your case `10.213.13.162:6380` didn't response in time and already became up when you connected to it by redis-cli.
