### ISSUE TITLE
ConcurrentModificationException - Pub/Sub using SerializationCodec, redisson 3.6.5

### ISSUE THREAD

**Issue by mmatosevic** [redisson/redisson#1408]
I have noticed occasional ConcurrentModificationException while using RedissonTopic.publishAsync. We are using it in multi threaded context, but I think this method is supposed to be thread-safe, right?

Stack trace:
`java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[na:1.8.0_60]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[na:1.8.0_60]
	at java.util.HashSet.writeObject(HashSet.java:286) ~[na:1.8.0_60]
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_60]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_60]
	at org.redisson.codec.SerializationCodec$2.encode(SerializationCodec.java:67) ~[redisson-3.6.5.jar:na]
	at org.redisson.RedissonTopic.encode(RedissonTopic.java:91) ~[redisson-3.6.5.jar:na]
	at org.redisson.RedissonTopic.publishAsync(RedissonTopic.java:79) ~[redisson-3.6.5.jar:na]`

We have noticed this error after upgrading from redisson 3.6.1 to 3.6.5.
This is using Redis server in sentinel mode with one master and one slave. Redis info:
`# Server
redis_version:4.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:f1060815dd32471a
redis_mode:standalone
os:Linux 3.10.0-514.26.2.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.9.2
process_id:1
run_id:afea5f69992d74d8d72affc9eaa3318f368db37a
tcp_port:6379
uptime_in_seconds:2492215
uptime_in_days:28
hz:10
lru_clock:14698389
`

This issue occurs rarely, under moderate load 50 - 100 messages/s.
Could you please check what might be the cause of this, and is there any work-around available.
Thank you!

**Comment by mrniko** [comment]
According to stacktrace this bug arise during encoding process by SerializationCodec. HashSet used in object was changed by another thread during its serialization. That causes ConcurrentModificationException since as we know HashSet si not thread-safe. Please review your application code.

**Comment by mmatosevic** [comment]
Thank you for your quick response. We did have some major refactoring on our application code, it's possible we introduced some issue there. I will review everything again. Since we recently updated redisson lib, this made me jump to conclusion it's related.

Thank you! :)
