### ISSUE TITLE
Tomcat Session replication inconsistences

### ISSUE THREAD

**Issue by akrepon** [redisson/redisson#1414]
Hi,

I have a tomcat cluster with 2 servers, both having the Redisson Session manager for non-sticky session replication. Whenever a request is served for the first time by a server, a new session is created with session attributes. Next time if the second server receives a request with same session id, it should create a session in memory and fetch the attributes from Redis. Sometimes it does fetch all the attributes and sometimes it does not. This random behaviour is really getting annoying. 

I've tried to use REDIS as the read mode instead of MEMORY. But the application gave me some problems(IllegalMonitorStateException). That's why I was not able to test it.

After looking at the code, I've seen one problem. If we are using the MEMORY read mode and all instances have the same session with all the attributes; whenever an instance updates an attribute it will be persisted on Redis but the other instances won't check this update if they already have a value stored in memory for that session. This is obviously discouraging. 

I am wrong about my findings? And how can I solve my problem?

Thanks in advance.

**Comment by akrepon** [comment]
I am using v3.6.5. The error happens when the application tries to access a session atrribute:

`javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.IllegalMonitorStateException
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:383) ~[vaadin-server-8.1.5.jar:8.1.5]
        at info.magnolia.ui.admincentral.AdmincentralVaadinServlet.service(AdmincentralVaadinServlet.java:141) [magnolia-ui-admincentral-5.6.4.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at info.magnolia.cms.filters.ServletDispatchingFilter.doFilter(ServletDispatchingFilter.java:148) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.CompositeFilter.doFilter(CompositeFilter.java:65) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.virtualuri.VirtualUriFilter.doFilter(VirtualUriFilter.java:98) [magnolia-virtual-uri-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.module.cache.executor.Bypass.processCacheRequest(Bypass.java:58) [magnolia-cache-core-5.6.1.jar:?]
        at info.magnolia.module.cache.executor.CompositeExecutor.processCacheRequest(CompositeExecutor.java:67) [magnolia-cache-core-5.6.1.jar:?]
        at info.magnolia.module.cache.filter.CacheFilter.doFilter(CacheFilter.java:220) [magnolia-cache-core-5.6.1.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.i18n.I18nContentSupportFilter.doFilter(I18nContentSupportFilter.java:89) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.RangeSupportFilter.doFilter(RangeSupportFilter.java:77) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at com.electrabel.ms.website.magnolia.filters.RootRedirectFilter.doFilter(RootRedirectFilter.java:65) [magnolia-engie-extra-1.0.0.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.security.BaseSecurityFilter.doFilter(BaseSecurityFilter.java:57) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.security.SecurityCallbackFilter.doFilter(SecurityCallbackFilter.java:84) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.OncePerRequestAbstractMgnlFilter.doFilter(OncePerRequestAbstractMgnlFilter.java:59) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.security.LogoutFilter.doFilter(LogoutFilter.java:94) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.OncePerRequestAbstractMgnlFilter.doFilter(OncePerRequestAbstractMgnlFilter.java:59) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.module.site.filters.SiteMergeFilter.doFilter(SiteMergeFilter.java:119) [magnolia-site-1.2.2.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.multisite.filters.MultiSiteFilter.doFilter(MultiSiteFilter.java:120) [magnolia-module-multisite-1.3.3.jar:?]
        at com.electrabel.ms.website.magnolia.multisite.filter.EngieMultiSiteFilter.doFilter(EngieMultiSiteFilter.java:61) [magnolia-engie-extra-1.0.0.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MultiChannelFilter.doFilter(MultiChannelFilter.java:83) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.module.cache.filter.GZipFilter.doFilter(GZipFilter.java:73) [magnolia-cache-core-5.6.1.jar:?]
        at info.magnolia.cms.filters.OncePerRequestAbstractMgnlFilter.doFilter(OncePerRequestAbstractMgnlFilter.java:59) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.security.auth.login.LoginFilter.doFilter(LoginFilter.java:127) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.enterprise.registration.RegistrationFilter.doFilter(RegistrationFilter.java:64) [magnolia-module-enterprise-5.6.5.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.UnicodeNormalizationFilter.doFilter(UnicodeNormalizationFilter.java:89) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.personalization.preview.filter.PreviewFilter.doFilter(PreviewFilter.java:92) [magnolia-personalization-preview-app-1.5.2.jar:?]
        at info.magnolia.cms.filters.OncePerRequestAbstractMgnlFilter.doFilter(OncePerRequestAbstractMgnlFilter.java:59) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.ContentTypeFilter.doFilter(ContentTypeFilter.java:155) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.ContextFilter.doFilter(ContextFilter.java:128) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.CompositeFilter.doFilter(CompositeFilter.java:65) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.SafeDestroyMgnlFilterWrapper.doFilter(SafeDestroyMgnlFilterWrapper.java:107) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlFilterDispatcher.doDispatch(MgnlFilterDispatcher.java:67) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlMainFilter.doFilter(MgnlMainFilter.java:110) [magnolia-core-5.6.4.jar:?]
        at info.magnolia.cms.filters.MgnlMainFilter.doFilter(MgnlMainFilter.java:96) [magnolia-core-5.6.4.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.6]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.6]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.6]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494) [catalina.jar:9.0.6]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [catalina.jar:9.0.6]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651) [catalina.jar:9.0.6]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.6]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:9.0.6]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.6]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:407) [tomcat-coyote.jar:9.0.6]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.6]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754) [tomcat-coyote.jar:9.0.6]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376) [tomcat-coyote.jar:9.0.6]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.vaadin.server.ServiceException: java.lang.IllegalMonitorStateException
        at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1620) ~[vaadin-server-8.1.5.jar:8.1.5]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1580) ~[vaadin-server-8.1.5.jar:8.1.5]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381) ~[vaadin-server-8.1.5.jar:8.1.5]
        ... 104 more
Caused by: java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151) ~[?:1.8.0_151]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261) ~[?:1.8.0_151]
        at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457) ~[?:1.8.0_151]
        at com.vaadin.server.VaadinService.unlockSession(VaadinService.java:707) ~[vaadin-server-8.1.5.jar:8.1.5]
        at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:726) ~[vaadin-server-8.1.5.jar:8.1.5]
        at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:581) ~[vaadin-server-8.1.5.jar:8.1.5]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1562) ~[vaadin-server-8.1.5.jar:8.1.5]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381) ~[vaadin-server-8.1.5.jar:8.1.5]
        ... 104 more
`

**Comment by mrniko** [comment]
IllegalMonitorStateException arise in Vaadin framework. Can't help here. As for session replication stored in MEMORY, I have fixed it. Thanks for report!

**Comment by akrepon** [comment]
@mrniko ,

 I've found out the source of the problem in Vaadin. Actually it's a general problem for objects being serialized with transient fields.

In our case, Vaadin was creating a ReentrantLock with thread information being a transient field. So there's a piece of code that checks tries to unlock the lock. While doing this it checks the current thread to the one stored in ReentrantLock. 

Now, before your fix it was working in version 3.6.5 with Memory mode due to the fact that this Lock was always fetched from the memory instead of Redis. So, it kept the this transient field as a result. But there we had the problem of sessions not being synchronized between different nodes. So in order to solve this problem you added a topic for listening to the changes, which was working really well. 

But, as I noticed while debugging your new implementation was self-updating the attribute in memory after calling the HttpSession.setAttribute method. Because of this the attribute in the memory with the transient fields was overwritten and the transient fields were lost which led to the problem above.

In order to solve this problem, I added a check in RedissonSessionManager, so that whenever an AttributeMessage is captured by the topic, the changes are only applied in local memory if the changes are from a different node than the current tomcat instance. This way I was able to avoid attributes being overwritten by the topic whenever HttpSession.setAttribute is called by the same tomcat node. This seems to be working. If you want I can do a PR of my change?

What do you think?

**Comment by mrniko** [comment]
@akrepon 

> In order to solve this problem, I added a check in RedissonSessionManager, so that whenever an AttributeMessage is captured by the topic, the changes are only applied in local memory if the changes are from a different node than the current tomcat instance. This way I was able to avoid attributes being overwritten by the topic whenever HttpSession.setAttribute is called by the same tomcat node. This seems to be working. If you want I can do a PR of my change?

Sure, please apply it for all tomcats

**Comment by akrepon** [comment]
I've created a new fork with the fix
