### ISSUE TITLE
sentinel switch-master no work

### ISSUE THREAD

**Issue by lansuiyun** [redisson/redisson#1424]
Hi,I have a Redis setup with 2 nodes (master, slave) and 1 sentinels .
redis version is windows 3.2.100 .
redisson version is 3.6.5.
When master is failover，redisson can not failover to new master automatic.
my code:
```
Config config = new Config();
        config.useSentinelServers()
            .setMasterName("master")
            .addSentinelAddress("redis://192.168.11.216:6679")
            .setReadMode(ReadMode.MASTER_SLAVE)
            .setSubscriptionMode(SubscriptionMode.SLAVE);
        System.out.println(config.toJSON());
        RedissonClient client = Redisson.create(config);
        ExecutorService service = Executors.newFixedThreadPool(1);
        service.submit(() -> {
            for (; ; ) {
                try {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    RBucket<String> a = client.getBucket("a");
                    String format = sdf.format(new Date());
                    String value = "sss：" + format;
                    a.set(value);
                    System.out.println("master: " + value + " @Time:" + format);
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
```

log:
```
2018-05-02 22:01:59,563 DEBUG pool-1-thread-1 [ConnectionWatchdog.java:109] - reconnecting RedisConnection@616184970 [redisClient=[addr=redis://192.168.11.216:6479], channel=[id: 0xd95e42c4, L:/192.168.11.216:55079 ! R:/192.168.11.216:6479]] to /192.168.11.216:6479 
2018-05-02 22:01:59,564 DEBUG pool-1-thread-1 [ConnectionWatchdog.java:109] - reconnecting RedisConnection@112185329 [redisClient=[addr=redis://192.168.11.216:6479], channel=[id: 0xe3d09124, L:/192.168.11.216:55082 ! R:/192.168.11.216:6479]] to /192.168.11.216:6479 
2018-05-02 22:02:00,062 DEBUG pool-1-thread-1 [CommandAsyncService.java:797] - connection released for command (SET) and params [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@34f50df2] using connection RedisConnection@1318095909 [redisClient=[addr=redis://192.168.11.216:6479], channel=[id: 0x15a974e7, L:/192.168.11.216:55077 ! R:/192.168.11.216:6479]]
2018-05-02 22:02:00,062 DEBUG pool-1-thread-1 [CommandAsyncService.java:585] - attempt 2 for command (SET) and params [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)]
2018-05-02 22:02:00,062 DEBUG pool-1-thread-1 [CommandAsyncService.java:628] - acquired connection for command (SET) and params [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@34f50df2] using node /192.168.11.216:6479... RedisConnection@1751114064 [redisClient=[addr=redis://192.168.11.216:6479], channel=[id: 0x37e1902f, L:/192.168.11.216:55074 ! R:/192.168.11.216:6479]]
2018-05-02 22:02:01,662 DEBUG pool-1-thread-1 [CommandAsyncService.java:797] - connection released for command (SET) and params [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@34f50df2] using connection RedisConnection@1751114064 [redisClient=[addr=redis://192.168.11.216:6479], channel=[id: 0x37e1902f, L:/192.168.11.216:55074 ! R:/192.168.11.216:6479]]
2018-05-02 22:02:01,662 DEBUG pool-1-thread-1 [CommandAsyncService.java:585] - attempt 3 for command (SET) and params [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)]
2018-05-02 22:02:01,662 DEBUG pool-1-thread-1 [CommandAsyncService.java:628] - acquired connection for command (SET) and params [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@34f50df2] using node /192.168.11.216:6479... RedisConnection@2062359937 [redisClient=[addr=redis://192.168.11.216:6479], channel=[id: 0x1658e94c, L:/192.168.11.216:55081 ! R:/192.168.11.216:6479]]
2018-05-02 22:02:01,663 DEBUG redisson-netty-1-5 [CommandAsyncService.java:797] - connection released for command (SET) and params [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@34f50df2] using connection RedisConnection@2062359937 [redisClient=[addr=redis://192.168.11.216:6479], channel=[id: 0x1658e94c, L:/192.168.11.216:55081 ! R:/192.168.11.216:6479]]
org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@34f50df2], connection: [id: 0x1658e94c, L:/192.168.11.216:55081 ! R:/192.168.11.216:6479], command: (SET), params: [a, PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256)]
	at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:675)
	at org.redisson.command.CommandAsyncService.access$100(CommandAsyncService.java:84)
```

sentinel log:
```
[16612] 02 May 21:59:26.623 # +sdown master master 192.168.11.216 6479
[16612] 02 May 21:59:26.623 # +odown master master 192.168.11.216 6479 #quorum 1/1
[16612] 02 May 21:59:26.623 # +new-epoch 50
[16612] 02 May 21:59:26.623 # +try-failover master master 192.168.11.216 6479
[16612] 02 May 21:59:26.626 # +vote-for-leader 9c69c98a184dc560fd72fe710241d18f3afd0406 50
[16612] 02 May 21:59:26.626 # +elected-leader master master 192.168.11.216 6479
[16612] 02 May 21:59:26.626 # +failover-state-select-slave master master 192.168.11.216 6479
[16612] 02 May 21:59:26.692 # +selected-slave slave 192.168.11.216:6579 192.168.11.216 6579 @ master 192.168.11.216 6479

[16612] 02 May 21:59:26.692 * +failover-state-send-slaveof-noone slave 192.168.11.216:6579 192.168.11.216 6579 @ master 192.168.11.216 6479
[16612] 02 May 21:59:26.744 * +failover-state-wait-promotion slave 192.168.11.216:6579 192.168.11.216 6579 @ master 192.168.11.216 6479
[16612] 02 May 21:59:27.692 # +promoted-slave slave 192.168.11.216:6579 192.168.11.216 6579 @ master 192.168.11.216 6479

[16612] 02 May 21:59:27.692 # +failover-state-reconf-slaves master master 192.168.11.216 6479
[16612] 02 May 21:59:27.742 # +failover-end master master 192.168.11.216 6479
[16612] 02 May 21:59:27.742 # +switch-master master 192.168.11.216 6479 192.168.11.216 6579
[16612] 02 May 21:59:27.742 * +slave slave 192.168.11.216:6479 192.168.11.216 6479 @ master 192.168.11.216 6579
[16612] 02 May 21:59:32.771 # +sdown slave 192.168.11.216:6479 192.168.11.216 6479 @ master 192.168.11.216 6579
```
Is that my code's error or redission's bug?

--- update 
I find out the reason.
In SentinelConnectionManager's Constructor, loop all sentinelAddress using SENTINELS command to find all sentinels. If there is only one sentinel, `List<Map<String, String>> sentinelSentinels = connection.sync(StringCodec.INSTANCE, RedisCommands.SENTINEL_SENTINELS, cfg.getMasterName());` ,the code result will be empty.

**Comment by mrniko** [comment]
Redis returns empty result if there is only one Sentinel. At least two sentinels are required for proper work of Redis cluster.

```
14:10:33 [redisson-netty-1-3] TRACE org.redisson.client.handler.CommandEncoder - channel: [id: 0xb8323302, L:/127.0.0.1:32188 - R:127.0.0.1/127.0.0.1:26379] message: *3
$8
SENTINEL
$9
SENTINELS
$8
mymaster

14:10:33 [redisson-netty-1-3] TRACE org.redisson.client.handler.CommandDecoder - channel: [id: 0xb8323302, L:/127.0.0.1:32188 - R:127.0.0.1/127.0.0.1:26379] message: *0
```
