### ISSUE TITLE
ClassCastException when receiving messages of different types

### ISSUE THREAD

**Issue by robinbraemer** [redisson/redisson#1429]
Hello,

I need to be able to publish different types of messages through a single channel.

I try to explain my senario with an example.

App X publishes messages of type String and Integer to one channel.
App 1 catches the Integer objects and App 2 only wants the Strings from the channel.

```java
// App 1
RTopic<Integer> topicApp1 = redis.getTopic( "channel" );
topicApp1.addListener( ( channel, msg ) -> System.out.println( msg ) );
// App 2
RTopic<String> topicApp2 = redis.getTopic( "channel" );
topicApp2.addListener( ( channel, msg ) -> System.out.println( msg ) );

// App X
redis.getTopic( "channel" ).publish( 43 );
redis.getTopic( "channel" ).publish( "Test" );
```

The unchecked casts are blocking me to do that.
https://github.com/redisson/redisson/blob/dfa3b4c2dd112e68256d20227747ac534a582c5f/redisson/src/main/java/org/redisson/PubSubMessageListener.java#L76
https://github.com/redisson/redisson/blob/dfa3b4c2dd112e68256d20227747ac534a582c5f/redisson/src/main/java/org/redisson/PubSubMessageListener.java#L84

output
```
Exception in thread "redisson-3-13" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
43
	at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:76)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:81)
	at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "redisson-3-15" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

	at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:76)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:81)
	at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

Thanks for helping me...

**Comment by RoboFlax** [comment]
The only plausible solution I came up with that I add a listerner for `Object` and then internally check the message via `instanceof`.

**Comment by mykolap** [comment]
I have a lot of class cast exceptions both with tomcat8 and tomcat9 redisson
11:32:50.028 [redisson-netty-1-7] DEBUG org.redisson.command.CommandAsyncService - connection released for command (HSET) and params [redisson:tomcat_session:697C00097E753D657E26AFE36116A935, PooledUnsafeDirectByteBuf(ridx: 0, widx: 21, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 7, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=10, freeConnectionsCounter=64, freezed=false, freezeReason=null, client=[addr=redis://mparedis:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@2072562081 [redisClient=[addr=redis://mparedis:6379], channel=[id: 0x5ec86634, L:/172.16.24.5:49100 - R:mparedis/172.16.24.4:6379]]
11:32:50.028 [http-nio2-8080-exec-1] DEBUG org.redisson.command.CommandAsyncService - acquired connection for command (PUBLISH) and params [redisson:tomcat_session_updates:/mpa, PooledUnsafeDirectByteBuf(ridx: 0, widx: 103, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=9, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://mparedis:6379], nodeType=MASTER, firstFail=0]]] using node mparedis/172.16.24.4:6379... RedisConnection@259558797 [redisClient=[addr=redis://mparedis:6379], channel=[id: 0xdd3cfbcc, L:/172.16.24.5:49122 - R:mparedis/172.16.24.4:6379]]
11:32:50.029 [redisson-netty-1-8] DEBUG org.redisson.command.CommandAsyncService - connection released for command (PUBLISH) and params [redisson:tomcat_session_updates:/mpa, PooledUnsafeDirectByteBuf(ridx: 0, widx: 103, cap: 256)] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=10, freeConnectionsCounter=64, freezed=false, freezeReason=null, client=[addr=redis://mparedis:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@259558797 [redisClient=[addr=redis://mparedis:6379], channel=[id: 0xdd3cfbcc, L:/172.16.24.5:49122 - R:mparedis/172.16.24.4:6379]]
Exception in thread "redisson-3-79" java.lang.ClassCastException: org.redisson.tomcat.AttributeUpdateMessage cannot be cast to org.redisson.tomcat.AttributeMessage
	at org.redisson.tomcat.RedissonSessionManager$1.onMessage(RedissonSessionManager.java:200)
	at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:77)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:77)
	at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by mrniko** [comment]
@mykolap 

fixed in https://github.com/redisson/redisson/pull/1639

**Comment by mrniko** [comment]
@robinbraemer 

Fixed in https://github.com/redisson/redisson/issues/731
