### ISSUE TITLE
NoClassDefFoundError when using FstCodec 

### ISSUE THREAD

**Issue by lying1234** [redisson/redisson#1439]
I'm using redisson tomcat session manager 3.7.0, and tried to set codec with FstCodec, but got error during tomcat startup. Did I miss anything? :

org.apache.catalina.LifecycleException: Failed to start component [org.redisson.tomcat.RedissonSessionManager[/sb]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5499)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Lorg/nustaq/serialization/FSTConfiguration;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredFields(Class.java:1916)
        at com.fasterxml.jackson.databind.util.ClassUtil.getDeclaredFields(ClassUtil.java:822)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:817)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveFields(AnnotatedClass.java:581)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:353)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:350)
.....
Caused by: java.lang.ClassNotFoundException: org.nustaq.serialization.FSTConfiguration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 51 more

**Comment by lying1234** [comment]
Doesn't redisson-all include FST library? or I need to import it into app level?

**Comment by hans123456** [comment]
@lying1234 you need to import the FST library.

**Comment by lying1234** [comment]
Yes, I figured that out. Thanks. Just wonder why you don't include it into redisson-all package. I used your redisson session manager, which requires FST lib under tomcat lib instead of app lib, so I couldn't simply add fst into our pom file.
