### ISSUE TITLE
redssion shiro jackson problem

### ISSUE THREAD

**Issue by dy-chen** [redisson/redisson#1465]
hi：
    i have a problem when i use redssion manager session and shiro save data.problem description is under:
    if i want to change the jackson,how i can do?

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid type id 'org.apache.shiro.subject.SimplePrincipalCollection' (for id type 'Id.class'): no such class found (through reference chain: org.redisson.tomcat.AttributeUpdateMessage["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:379)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1514)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:89)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:330)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:372)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:111)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 28 more

**Comment by dy-chen** [comment]
redssion version redisson-all-3.7.0.jar、redisson-tomcat-8-3.7.0.jar

**Comment by DALDEI** [comment]
I suspect that the shiro jar file is not in the classpath in the context of the netty thread handling the decoding.

**Comment by mrniko** [comment]
use FstCodec
