### ISSUE TITLE
Subscribe timeout

### ISSUE THREAD

**Issue by welovelain** [redisson/redisson#1466]
﻿### Expected behavior
No exceptions
### Actual behavior
```
Subscribe timeout: (41000ms)org.redisson.client.RedisTimeoutException: Subscribe timeout: (41000ms)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:130)
	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:122)
	at org.redisson.RedissonLock.lock(RedissonLock.java:100)
	at com.zeppelinen.carsharing.dataprocessor.registry.manager.locker.RegistryLocker.lock(RegistryLocker.java:39)
	at com.zeppelinen.carsharing.dataprocessor.registry.manager.lifecycle.LifeCycleManager.getRentIdAttachedToCar(LifeCycleManager.java:195)
	at com.zeppelinen.carsharing.dataprocessor.workunit.core.carserver.service.impl.TrackMessageProcessorImpl.processTrackMessage(TrackMessageProcessorImpl.java:60)
	at com.zeppelinen.carsharing.dataprocessor.workunit.periphery.io.carserver.listener.TrackMessageListener.receiveTrackData(TrackMessageListener.java:55)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:51)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:182)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:120)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1414)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1337)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:785)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:769)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1010)
	at java.lang.Thread.run(Thread.java:748)
```
### Redis version
4.0.6

# Redis Replication

role:slave
master_host:10.233.80.95
master_port:6379
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0
slave_repl_offset:4327166295
slave_priority:100
slave_read_only:1
connected_slaves:0
master_replid:610cea4395c4ccb2f4d42620e5b40be23f42a28f
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:4327166295
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:4326117720
repl_backlog_histlen:1048576

### Redisson version
3.7.0
### Redisson configuration
Sentinel configuration.
setRetryAttempts  (7)
setRetryInterval (3000 ms)
setSubscriptionConnectionPoolSize (200)
setSubscriptionConnectionMinimumIdleSize (10)
setSlaveConnectionPoolSize(200)
setMasterConnectionPoolSize(200)
other: default

Why is I keep getting these subscribe timeouts? After restarting service it works allright for, like, 24 hours, then I get a lot of subscribe errors. I have a pretty big connection pool, so I don't see why I keep getting it.

I mostly receive this error with RLock, which I use to synchronize. Should I tune my configuration somehow?

**Comment by jackygurui** [comment]
You can increase `subscriptionConnectionMinimumIdleSize` and `retryAttempts`

**Comment by welovelain** [comment]
It's already increased, though, I'll try to increase it even more. Should I increase subscriptionsPerConnection as well?

**Comment by jackygurui** [comment]
Sure

**Comment by welovelain** [comment]
REDISSON_RETRY_ATTEMPTS = 15;
REDISSON_RETRY_INTERVALS = 3000; // 3 seconds
 REDISSON_SUBSCRIPTION_CONNECTION_POOL_SIZE = 200; // default 50
REDISSON_SUBSCRIPTION_CONNECTION_MIN_IDLE_SIZE = 50; // default 1
REDISSON_SUBSCRIPTIONS_PER_CONNECTION_SIZE = 20; // default 5
 REDISSON_SLAVE_CONNECTION_POOL_SIZE = 200; // default 64
REDISSON_MASTER_CONNECTION_POOL_SIZE = 200; // default 32;
TIMEOUT = 20_000;

I tried this configuration, and it worked longer, then earlier, but still, in the end I received a lot of "Subscribe timeout"

> 2018-06-05 09:07:38.755  WARN 7 --- [isson-netty-1-7] o.r.c.SentinelConnectionManager          : Skipped slave up 10.233.80.124:6379 for master redis://10.233.80.95:6379 differs from current redis://10.233.80.124:6379
> 2018-06-05 09:07:38.756  WARN 7 --- [isson-netty-1-7] o.r.c.SentinelConnectionManager          : slave: 10.233.80.124:6379 has down
> 2018-06-05 09:07:38.757  INFO 7 --- [isson-netty-1-1] o.r.c.pool.MasterConnectionPool          : 32 connections initialized for 10.233.80.124/10.233.80.124:6379
> 2018-06-05 09:07:38.758  INFO 7 --- [isson-netty-1-6] o.r.c.pool.MasterPubSubConnectionPool    : 50 connections initialized for 10.233.80.124/10.233.80.124:6379
> 2018-06-05 09:07:38.767  INFO 7 --- [isson-netty-1-6] o.redisson.connection.MasterSlaveEntry   : master 10.233.80.95/10.233.80.95:6379 has changed to 10.233.80.124/10.233.80.124:6379
> 2018-06-05 09:07:39.758  WARN 7 --- [isson-netty-1-7] o.r.c.SentinelConnectionManager          : Skipped slave up 10.233.80.124:6379 for master redis://10.233.80.95:6379 differs from current redis://10.233.80.124:6379
> 2018-06-05 09:07:40.760  WARN 7 --- [isson-netty-1-7] o.r.c.SentinelConnectionManager          : Skipped slave up 10.233.80.124:6379 for master redis://10.233.80.95:6379 differs from current redis://10.233.80.124:6379
> 2018-06-05 09:07:51.783  INFO 7 --- [isson-netty-1-7] o.r.c.SentinelConnectionManager          : slave: 10.233.80.95:6379 has up
> 2018-06-05 09:08:43.760 ERROR 7 --- [cTaskExecutor-2] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:20:58.601 ERROR 7 --- [cTaskExecutor-2] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:21:00.200 ERROR 7 --- [cTaskExecutor-1] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:21:00.493 ERROR 7 --- [cTaskExecutor-3] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:25:15.560 ERROR 7 --- [cTaskExecutor-6] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:25:15.562 ERROR 7 --- [cTaskExecutor-1] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:26:20.591 ERROR 7 --- [cTaskExecutor-6] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:29:06.507 ERROR 7 --- [cTaskExecutor-6] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:29:06.511 ERROR 7 --- [cTaskExecutor-3] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:30:11.598 ERROR 7 --- [cTaskExecutor-6] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:32:48.185 ERROR 7 --- [cTaskExecutor-6] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:32:48.197 ERROR 7 --- [cTaskExecutor-3] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:33:53.196 ERROR 7 --- [cTaskExecutor-7] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:33:53.291 ERROR 7 --- [cTaskExecutor-3] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:36:49.869 ERROR 7 --- [cTaskExecutor-8] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:36:49.869 ERROR 7 --- [TaskExecutor-11] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:36:49.869 ERROR 7 --- [cTaskExecutor-9] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)
> 2018-06-05 09:36:49.894 ERROR 7 --- [TaskExecutor-12] c.z.c.r.p.i.l.TrackMessageListener       : Subscribe timeout: (65000ms)


This is my code:

```
public void processTrackMessage(TrackMessage tm) {
        String imei = tm.getImei();
        RLock carLock = redisson.getLock(CAR_LOCK_KEY_PREFIX + imei);
        carLock.lock(20, TimeUnit.SECONDS);

        try {
           // business logic
        } finally {
            carLock.unlock();
        }

    }

```

It's like RedissonLock doesn't release subscription connection or something

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1717
