### ISSUE TITLE
Occasional  ERROR:Search domain query failed.  

### ISSUE THREAD

**Issue by ChaselCho** [redisson/redisson#1486]
### Expected behavior
项目能够顺利启动。
### Actual behavior
偶尔会抛出Search domain query failed.异常信息导致项目启动不了
Steps to reproduce or test case
项目采用的spring boot1.5.3。
### Redis version
redis 4.0.2
### Redisson version
Redisson 3.6.5
Redisson configuration
```
application.yml
redisson:
  address: redis://www.chasel.com:6279
  timeout: 3000
  connectionPoolSize: 64
  connectionMinimumIdleSize: 10
  reconnectionTimeout: 3000
  threads: 10
  codec: org.redisson.codec.JsonJacksonCodec
  nettyThreads: 10
  transportMode: NIO
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  database: 0
Java Code
public class RedissonConfig {

	private String address;
	private int connectionMinimumIdleSize;
	private int idleConnectionTimeout;
	private int pingTimeout;
	private int connectTimeout;
	private int timeout;
	private int reconnectionTimeout;
	private int connectionPoolSize;
	private int database;
	private int threads; // 当前处理核数量 * 2
	private int nettyThreads;
	private String codec;
	@ConditionalOnProperty(name = "redisson.address")
	@Bean(destroyMethod = "shutdown")
	RedissonClient redisson() throws Exception {
		Config config = new Config();
		config.useSingleServer().setAddress(address)
				.setConnectionMinimumIdleSize(connectionMinimumIdleSize).setIdleConnectionTimeout(idleConnectionTimeout)
				.setPingTimeout(pingTimeout).setConnectTimeout(connectTimeout).setTimeout(timeout)
				.setConnectionPoolSize(connectionPoolSize).setDatabase(database)
				;
		config.setThreads(threads);
		config.setTransportMode(TransportMode.NIO);
		config.setNettyThreads(nettyThreads);
		// SingleServerConfig singleServerConfig =
		// config.useSingleServer().setAddress();
		// Config config = Config.fromJSON(new
		// ClassPathResource(RedisContants.RedissonConstants.REDISSON_JSON_CONFIG_FILE_NAME).getFile());
		return Redisson.create(config);
	}

	@ConditionalOnProperty(name = "redisson.address")
	@Bean
	RedissonReactiveClient RedissonReactive() throws IOException {
		Config config = new Config();
		config.useSingleServer().setAddress(address)
				.setConnectionMinimumIdleSize(connectionMinimumIdleSize).setIdleConnectionTimeout(idleConnectionTimeout)
				.setPingTimeout(pingTimeout).setConnectTimeout(connectTimeout).setTimeout(timeout)
				.setConnectionPoolSize(connectionPoolSize).setDatabase(database)
				;
		config.setThreads(threads);
		config.setTransportMode(TransportMode.NIO);
		config.setNettyThreads(nettyThreads);
		return Redisson.createReactive(config);
	}
```
### Excpetion:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redissonUtil': Unsatisfied dependency expressed through method 'setRedissonReactiveClient' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RedissonReactive' defined in class path resource [com/sst/common/config/RedissonConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonReactiveClient]: Factory method 'RedissonReactive' threw exception; nested exception is io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'www.chasel.com' failed to resolve 'www.chasel.com' after 2 queries 
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:667)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.sst.AdminApiApplication.main(AdminApiApplication.java:13)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RedissonReactive' defined in class path resource [com/sst/common/config/RedissonConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonReactiveClient]: Factory method 'RedissonReactive' threw exception; nested exception is io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'www.chasel.com' failed to resolve 'www.chasel.com' after 2 queries 
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:659)
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonReactiveClient]: Factory method 'RedissonReactive' threw exception; nested exception is io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'www.chasel.com' failed to resolve 'www.chasel.com' after 2 queries 
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 31 common frames omitted
Caused by: io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'www.chasel.com' failed to resolve 'www.chasel.com' after 2 queries 
	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:728)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:670)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:306)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:295)
	at io.netty.resolver.dns.DnsNameResolverContext.access$700(DnsNameResolverContext.java:60)
	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:346)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:223)
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:162)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.3.0.28:53] query timed out after 5000 milliseconds (no stack trace available)
```

**Comment by jackygurui** [comment]
能否请按照模板把运行环境和配置发出来呢？

**Comment by ChaselCho** [comment]
@jackygurui Modify according to the issue template finish .

**Comment by mrniko** [comment]
`[/10.3.0.28:53] query timed out after 5000 milliseconds (no stack trace available)`

Means that DNS by address 10.3.0.28 doesn't work

**Comment by ChaselCho** [comment]
@mrniko Do you have any solution?

**Comment by mrniko** [comment]
Change your system's DNS to working one

**Comment by dragon9783** [comment]
i have same issue, but it can resolv dns in shell, and `nc -w1 -z dnsdomain port` work well

**Comment by dragon9783** [comment]
Redis version
redis 4.0.2

Redisson version
Redisson 3.5.5

application.yaml
redis:
  host: redis://redis:6379

@Bean
    public RedissonClient getRedissonClient() {
        Config config = new Config();
        config.useSingleServer().setAddress(this.getRedisHost());
        return Redisson.create(config);
    }
    
    @Bean
    public RedissonReactiveClient getRedissonReactiveClient() {
        Config redissonConfig = new Config().setNettyThreads(2).setThreads(2);
        redissonConfig.useSingleServer().setAddress(this.getRedisHost());
        return Redisson.createReactive(redissonConfig);
    }

**Comment by mrniko** [comment]
Please update to Redisson 3.7.0+ it contains bug fix https://github.com/redisson/redisson/commit/5a000bedbb150a1ea070fdfccfa025c2da258c67

**Comment by x0a1b** [comment]
I have version 3.8.1 I still these errors happening 
```
io.netty.resolver.dns.SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.amazonaws.com' failed to resolve 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.amazonaws.com' after 2 queries 
    at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:816)
    at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:777)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:310)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:299)
    at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62)
    at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:356)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
    at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216)
    at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43)
    at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:166)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```

I am not sure if the fix actually fixed the issue. I don't expect AWS infra to be flaky on DNS entries.

**Comment by mrniko** [comment]
related to https://github.com/netty/netty/issues/8261

**Comment by mrniko** [comment]
Done! Implemented workaround on Redisson side.

**Comment by smigfu** [comment]
I am still seeing the error after upgrading to 3.8.2. The service is running in AWS. Did the workaround work for others who were seeing this issue before?

**Comment by j-be** [comment]
No, we are seeing this issue to on OpenShift runnig:
* Redis 3.2.4 in standalone mode
* redisson-all-3.8.2.jar
* redisson-tomcat-9-3.8.2.jar

**Comment by j-be** [comment]
The problem seems to go away when upgrading to latest netty `4.1.31.Final`.
I used:
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
and now it works like a charm.

**Comment by jackygurui** [comment]
@j-be Thanks for the confirmation. I wondered that this morning when reading the netty `4.1.31.Final` release note.

**Comment by hlms** [comment]
netty 4.1.31.Final didn't fix the issue...
```
ERROR - Unable to resolve <host> io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: '<host>' failed to resolve '<host>' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:806) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:322) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:379) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:166) [netty-resolver-dns-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466) [netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_60]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.0.0.2:53] query timed out after 5000 milliseconds (no stack trace available)
```

**Comment by jackygurui** [comment]
@hlms I think the exception is trying to tell you `<host>` is not a valid hostname.

**Comment by hlms** [comment]
@jackygurui 

It is valid one. I restarted the tomcat, and it worked. But, in another machine, restarting tomcat does not fix the issue.

**Comment by hlms** [comment]
@jackygurui 
I have replaced the real value with a placeholder before pasting here.
Regret for leaving it unclear. :)

**Comment by jackygurui** [comment]
@hlms My apologies for not clarify it first.

**Comment by mrniko** [comment]
Fixed

**Comment by hlms** [comment]
@mrniko ,
Thanks for fixing this.

We attempted to workaround this by setting [dnsMonitoringInterval](https://github.com/redisson/redisson/wiki/2.-Configuration#dnsmonitoringinterval) to -1.
`
config.useSingleServer().setDnsMonitoringInterval(-1);
`
and surprisingly, it seems to work.

However, JAVA_HOME\jre\lib\security\java.security had the following parameters:
```
# caching forever
networkaddress.cache.ttl=-1  

# 10 seconds.
networkaddress.cache.negative.ttl=10 
```

Do you think it is a legitimate workaround?

**Comment by mrniko** [comment]
@hlms 

I don't think this would take effect since Redisson uses netty based DNS resolver for all hosts not only for monitoring.
