### ISSUE TITLE
Warn:"Invocation of destroy method 'close' failed on bean with name 'jCacheCacheManager'"

### ISSUE THREAD

**Issue by meixiaoxi110** [redisson/redisson#1489]
﻿### Expected behavior
I imported Redission in spring boot using distributedLock,but the log always show this WARN 
### Actual behavior
collection-web 2018-06-13 20:50:24.428 WARN  --- [Thread-7] org.springframework.beans.factory.support.DisposableBeanAdapter Line:371 - Invocation of destroy method 'close' failed on bean with name 'jCacheCacheManager'
java.lang.NullPointerException: null
	at org.redisson.jcache.JCacheManager.close(JCacheManager.java:368)
	at org.redisson.jcache.JCachingProvider.close(JCachingProvider.java:183)
	at org.redisson.jcache.JCacheManager.close(JCacheManager.java:360)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:364)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:287)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:230)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1030)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1006)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:958)
	at org.springframework.boot.actuate.endpoint.ShutdownEndpoint$1.run(ShutdownEndpoint.java:74)
	at java.lang.Thread.run(Thread.java:745)

### Redisson version
3.7.0
### Redisson configuration
this is my configuration class:
/**
     *
     * @return
     */
    @Bean
    RedissonClient redissonClient() {
        List<String> nodeList = redisClusterConfigProperties.getNodes();
        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.useClusterServers();
        for (String node : nodeList) {
            clusterServersConfig = config.useClusterServers().addNodeAddress("redis://" + node);
        }
        clusterServersConfig.setScanInterval(2000);
        return Redisson.create(config);
    }

    @Bean
    CacheManager cacheManager(RedissonClient redissonClient) {
        Map<String, CacheConfig> config = new HashMap<>();
        config.put("testMap", new CacheConfig(24*60*1000, 12*60*1000));
        return new RedissonSpringCacheManager(redissonClient, config);
    }

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by meixiaoxi110** [comment]
Hello! Which version fixed this Bug?And I can use which version?

**Comment by jackygurui** [comment]
2.12.2/3.7.2

**Comment by meixiaoxi110** [comment]
Hi! The Redession,so good to use.And I suggest, you can put redission in spring boot starter!

**Comment by jackygurui** [comment]
Thank you. @mrniko is already working on that.
