### ISSUE TITLE
Redisson not executing jobs requiring external dependencies?

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1491]
I have one RunnableTask which makes a HTTP request and hence needs a dependency of HTTP client. This job looks like this.
```java
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;

public class RunnableTask implements Runnable {
    private int job_no;
    RunnableTask(int job_no) {
        this.job_no = job_no;
    }
    public RunnableTask() {}
    public void run() {
        try {
            System.out.println(Unirest.get("http://192.168.1.108:3000").asString().getBody() + " " + job_no);
        } catch (UnirestException e) {
            e.printStackTrace();
        }
    }
}
```
Now I am scheduling some jobs using this code.

```java
public class Main {
    private final static int NO_OF_JOBS = 10;
    static int i = 1;
    public static void main(String[] args) {
        //initUnirest();
        Config config = new Config();
        config.useClusterServers()
                .addNodeAddress("http://127.0.0.1:7000", "http://127.0.0.1:7001", "http://127.0.0.1:7002");
        RedissonClient redisson = Redisson.create(config);

//Block-1
       /* RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setThreads(100);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("d1", 1));
        RedissonNode.create(nodeConfig).start();
*/
        RExecutorService e = redisson.getExecutorService("d1");
        //redisson.getExecutorService("d1").registerWorkers(10, Executors.newFixedThreadPool(10));
        for (int j = 0; j < NO_OF_JOBS; j++) {
            Calendar calendar = Calendar.getInstance();
            int hour = calendar.get(Calendar.HOUR_OF_DAY);
            int minute = calendar.get(Calendar.MINUTE) + 1;
            //System.out.println("hour, minute" + hour + ", " + minute);
            RExecutorFuture r = (RExecutorFuture) ((RScheduledExecutorService) e).schedule(new RunnableTask(j + 1), CronSchedule.dailyAtHourAndMinute(hour, minute));
            //System.out.println(r.getTaskId());
        }
    }
}
```
After this I launched a RedissonNode in standalone mode. Now when the time for the execution of this jobs come, I am getting following error.

```
[redisson-3-30] ERROR org.redisson.RedissonRemoteService - Can't execute: RemoteServiceRequest [requestId=01ff7d044609fe82f2a85d5eb665839f45, methodName=schedule, signatures=[[java.lang.String, [B, [B, long, java.lang.String, java.lang.String, java.lang.String]], args=[com.webengage.MRunnableTask, [B@3f8166bd, [B@7a83ef29, 1529334600000, 0 40 20 ? * *, cf987ea1-4e2b-4335-93f1-02baaccfca19, 01ff7d044609fe82f2a85d5eb665839f45], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1529334573532]
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:347)
	at org.redisson.RedissonRemoteService.access$400(RedissonRemoteService.java:66)
	at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/mashape/unirest/http/exceptions/UnirestException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.fasterxml.jackson.databind.type.TypeFactory.classForName(TypeFactory.java:278)
	at com.fasterxml.jackson.databind.type.TypeFactory.findClass(TypeFactory.java:258)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:68)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:51)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:158)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:106)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:92)
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:246)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:268)
	at org.redisson.executor.TasksRunnerService.schedule(TasksRunnerService.java:126)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.mashape.unirest.http.exceptions.UnirestException
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```
But when I uncomment the part of code described below, i.e., I launch the RedissonNodes from the same process and not in standalone mode, jobs get executed successfully.
```java
RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setThreads(100);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("d1", 1));
        RedissonNode.create(nodeConfig).start();
```
@mrniko @jackygurui 
Anyone please explain why this is happening and resolution for this issue.

### Redis version
4.0.9
### Redisson version
3.7.2

**Comment by jackygurui** [comment]
You can supply additional jars via command line.

**Comment by 029vaibhav** [comment]
I am also facing the same error. Mine is not even an external dependency. Its the initialization of class within the code

**Comment by ns-qasim** [comment]
Facing same `NoClassDefFoundError` error on initialization of internal class inside run method, although variables from interfaces are working fine.

@mrniko Kindly assist.

**Comment by mrniko** [comment]
@ns-qasim 

Did you try to set `useThreadClassLoader = false`
