### ISSUE TITLE
3.7.2 SingleServer 配置问题

### ISSUE THREAD

**Issue by huigesv123** [redisson/redisson#1514]
`Exception in thread "main" java.lang.NoSuchMethodError: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace(Ljava/lang/CharSequence;I)I
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parse(UnixResolverDnsServerAddressStreamProvider.java:171)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:90)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:124)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:66)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:32)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:195)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:158)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:34)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:192)
	at org.redisson.Redisson.<init>(Redisson.java:121)
	at org.redisson.Redisson.create(Redisson.java:158)
	at com.vanwardsmart.tools.RedisTool.init(RedisTool.java:53)
	at com.vanwardsmart.cloud.SmartServer.main(SmartServer.java:49)`

设置了断点调试，发觉redission会读取/etc/resolv.conf文件，大概就说格式错误吧

可是这些地址格式是系统自动生成的，怎么回事

**Comment by jackygurui** [comment]
检查一下你项目的依赖，排除其他低版本netty再试试

**Comment by jackygurui** [comment]
有其他项目也在使用netty吗？如果没有的话就去掉直接依赖。

**Comment by huigesv123** [comment]
@jackygurui 有啊，不能去掉，而且不能随便升版本

**Comment by jackygurui** [comment]
那就没办法了啊，你只有降低redisson的版本了

**Comment by huigesv123** [comment]
@jackygurui 那好吧，只能用回3.2.x了

**Comment by zhuyeqing5828** [comment]
建议开发者不要使用Netty内部的工具类io.netty.util.internal.StringUtil [http://javadox.com/io.netty/netty-common/4.0.23.Final/io/netty/util/internal/package-summary.html](NettyLJavaDoc链接)
