### ISSUE TITLE
CustomObjectInputStream doesnt work for proxied classes

### ISSUE THREAD

**Issue by heikih** [redisson/redisson#1518]
﻿### Expected behavior
Classloader passed into CustomObjectInputStream is not used to load proxied classes.
In my case redisson cant deserialize org.springframework.security.oauth2.client.token.AccessTokenRequest class
### Actual behavior
Following exception is thrown during class loading:
Caused by: java.lang.ClassNotFoundException: org.springframework.security.oauth2.client.token.AccessTokenRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveProxyClass(ObjectInputStream.java:698)
	at java.io.ObjectInputStream.readProxyDesc(ObjectInputStream.java:1559)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1515)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)

### Redis version
4.x

### Redisson version
3.6.5

**Comment by mrniko** [comment]
Fixed! Thanks for report
