### ISSUE TITLE
Using Redis Transaction MULTI crashes in java.lang.NumberFormatException: For input string: "QUEUED"

### ISSUE THREAD

**Issue by adrianiacobghiula** [redisson/redisson#1522]
﻿### Expected behavior
no expcetion
### Actual behavior
java.lang.NumberFormatException: For input string: "QUEUED"
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:343)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:170)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:361)
	at org.redisson.RedissonBatch.execute(RedissonBatch.java:267)
	at som.executors.basic.RedissonTest.transactionTest(RedissonTest.java:38)
Caused by: java.lang.NumberFormatException: For input string: "QUEUED"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.redisson.client.protocol.convertor.DoubleReplayConvertor.convert(DoubleReplayConvertor.java:25)
	at org.redisson.client.protocol.convertor.DoubleNullSafeReplayConvertor.convert(DoubleNullSafeReplayConvertor.java:27)
	at org.redisson.client.protocol.convertor.DoubleNullSafeReplayConvertor.convert(DoubleNullSafeReplayConvertor.java:23)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:434)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:295)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:229)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:135)

### Steps to reproduce or test case
        RBatch batch = redissonClient.createBatch(BatchOptions.defaults().executionMode(BatchOptions.ExecutionMode.REDIS_WRITE_ATOMIC));

        batch.getScoredSortedSet("myZKey").addScoreAsync("abc", 1d);

        batch.execute();

### Redis version
redis_version:4.0.7

### Redisson version
Redisson 3.7.2

### Redisson configuration
        Config config = new Config();
        config.setCodec(new StringCodec());
        config.useSingleServer()
                .setAddress("redis://localhost:6379")
                .setConnectionMinimumIdleSize(1)
                .setConnectionPoolSize(1);

        RedissonClient redissonClient = Redisson.create(config);

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by mrniko** [comment]
Fixed. Test got improved
