### ISSUE TITLE
Redisson Not able to serialize and deserialize external objects?

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1528]
@mrniko @jackygurui 
Job class
```java
public class HttpJob implements Runnable {

    HttpClient client;

    public HttpJob() {

    }

    public HttpJob(HttpClient client) {
        this.client = client;
    }

    @Override
    public void run() {

        String url = "http://localhost:3000";
        HttpGet request = new HttpGet(url);

        HttpResponse response = null;
        try {
            response = client.execute(request);
            System.out.println("Response Code : " + response.getStatusLine().getStatusCode());
            System.out.println(response.getStatusLine());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
I am running Redisson Nodes in standalone mode, at the time of execution of this job, I am getting following error.

```
[redisson-3-23] ERROR org.redisson.RedissonRemoteService - Can't execute: RemoteServiceRequest [requestId=010acb018185e3786b777fe305e192b32f, methodName=schedule, signatures=[[java.lang.String, [B, [B, long, java.lang.String, java.lang.String, java.lang.String]], args=[com.webengage.HttpJob, [B@1742e1f, [B@395ed74f, 1530533820000, 0 47 17 2 JUL ? 2018, 15728f50-6654-4c4e-b45a-39ccf60fa8f3, 010acb018185e3786b777fe305e192b32f], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1530533769834]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:347)
	at org.redisson.RedissonRemoteService.access$400(RedissonRemoteService.java:66)
	at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:281)
	at org.redisson.executor.TasksRunnerService.schedule(TasksRunnerService.java:130)
	... 13 more
Caused by: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:256)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:274)
	... 14 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.apache.http.impl.client.InternalHttpClient]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: io.netty.buffer.ByteBufInputStream@63e0c28d; line: 1, column: 103] (through reference chain: HttpJob["client"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:256)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1134)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:168)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:493)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:92)
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:252)
	... 15 more
```

How can I inject such dependencies in redisson, I think this use case is quite natural, and should be definitely be accommodated.

**Comment by jackygurui** [comment]
Please see [FAQ](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-comfasterxmljacksondatabindjsonmappingexception-during-deserialization-process-can-you-fix-it) for recommendations.

**Comment by arpit728** [comment]
@jackygurui 

Yes it is quite obvious that HttpClient or DAO objects is not something that anyone would want to serialize or deserialize. 

The point of creating issue was that, I couldn't figure out any way to achieve this i.e, injecting external objects in job class. I want to know how this can be achieved.

Can you please help me out with this?

**Comment by arpit728** [comment]
But that way I will not be able to reuse the same HttpClient, and creating new HttpClient for every job will cause serious performance  bottleneck in my case no. of jobs would go in millions.

**Comment by jackygurui** [comment]
The way you are trying to do now is to serialise the instance and deserialise it again which would give you N + 1 instance, where N is the number of jobs you are executing and 1 being the source.

Have you tried the to initialise the instance statically in a different class?

**Comment by arpit728** [comment]
No, I didn't.

**Comment by l0co** [comment]
For all kinds of serializers and deserializers it would be useful to have an option in redisson to check automatically if the object can be deserialized just after serialization. I know this influences performance, but it would be useful as an option in development mode, which would be disabled on production. Currently for all kinds of serializers you will know there's something wrong with your class only if you deserialize it and you can miss it if your tests cover only serialization part.
