### ISSUE TITLE
Scheduled task not working

### ISSUE THREAD

**Issue by tobiastimm** [redisson/redisson#1536]
﻿### Expected behavior
I want to create a simple scheduled task with redisson & kotlin.

My Task:

```
class IncrementRunnableTask(private var counterName: String) : Runnable {

    @RInject
    lateinit var redisson: RedissonClient

    override fun run() {
        redisson.getAtomicLong(counterName).incrementAndGet()
    }

}
```

My Test:

```
    @Autowired
    lateinit var redissonClient: RedissonClient

    private lateinit var node: RedissonNode

    @Before
    fun setup() {
        val nodeConfig = RedissonNodeConfig(this.redissonClient.config)
        nodeConfig.executorServiceWorkers = Collections.singletonMap("test", 1)
        node = RedissonNode.create(nodeConfig);
        node.start()
    }

    @After
    fun after() {
        node.shutdown();
    }

    @Test
    @Throws(Exception::class)
    fun testRedisson() {
        val executor = redissonClient.getExecutorService("test", ExecutorOptions.defaults().taskRetryInterval(10, TimeUnit.SECONDS))
        val f = executor.schedule(IncrementRunnableTask("counter"), 1, TimeUnit.SECONDS)
        f.get()
        assertThat(redissonClient.getAtomicLong("counter").get()).isEqualTo(1)
    }

```

### Actual behavior

I get an exception everytime

```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:347) [redisson-3.7.3.jar:na]
	at org.redisson.RedissonRemoteService.access$400(RedissonRemoteService.java:66) [redisson-3.7.3.jar:na]
	at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:312) [redisson-3.7.3.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:281) ~[redisson-3.7.3.jar:na]
	at org.redisson.executor.TasksRunnerService.scheduleRunnable(TasksRunnerService.java:174) ~[redisson-3.7.3.jar:na]
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:256) ~[redisson-3.7.3.jar:na]
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:274) ~[redisson-3.7.3.jar:na]
	... 15 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class java.lang.Object]: missing type id property '@class'
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 25]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:1638) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1217) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:300) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:164) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:105) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:193) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:712) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070) ~[jackson-databind-2.9.6.jar:2.9.6]
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:92) ~[redisson-3.7.3.jar:na]
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:252) ~[redisson-3.7.3.jar:na]
	... 16 common frames omitted

```
### Redis version
4.0.10
### Redisson version
3.7.3
### Redisson configuration
```
    fun redissonClient(): RedissonClient {
        return Redisson.create()
    }
```

**Comment by Aqu1nt** [comment]
If i rememer correctly jackson doesn't add the `@class` field when serializing a `final` class.
Since Kotlin classes are always final by default you could try to define your `IncrementRunnableTask ` class as `open` and check if the serialization / deserialization process is working that way.

Only reference i found: [https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization#11-global-default-typing](url)
