### ISSUE TITLE
Redisson stops executing commands found during tests with RBoundedBlockingQueue

### ISSUE THREAD

**Issue by vgpetrov** [redisson/redisson#1539]
﻿### Expected behavior
Probably throwing an alert message or slow down but not stuck in infinite cycle.

### Actual behavior
Stops executing commands

**A lot of exceptions logged**
`Exception in thread "pool-12-thread-3" org.redisson.client.RedisTimeoutException: Redis server response timeout (1000 ms) occured for command: (LLEN) with params: [purchase_queue_ravil2] channel: [id: 0x9a34862a, L:/192.168.50.135:57482 - R:/192.168.50.167:6380]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:690)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-10-thread-3" Exception in thread "pool-12-thread-4" Exception in thread "pool-10-thread-6" Exception in thread "pool-10-thread-2" Exception in thread "pool-10-thread-1" Exception in thread "pool-10-thread-4" Exception in thread "pool-11-thread-1" Exception in thread "pool-12-thread-2" Exception in thread "pool-10-thread-7" Exception in thread "pool-12-thread-1" Exception in thread "pool-10-thread-8" Exception in thread "pool-10-thread-5" org.redisson.client.RedisTimeoutException: Redis server response timeout (1000 ms) occured for command: (LLEN) with params: [purchase_queue_ravil2] channel: [id: 0xc7338ee0, L:/192.168.50.135:57485 - R:/192.168.50.167:6380]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:690)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:745)
org.redisson.client.RedisTimeoutException: Redis server response timeout (1000 ms) occured for command: (EVAL) with params: [local value = redis.call('get', KEYS[1]); assert(value ~= false, 'Capacity of queue ' .. KEYS[1] .. ..., 2, redisson_bqs:{purchase_queue_ravil2}, purchase_queue_ravil2, 1, PooledUnsafeDirectByteBuf(ridx: 0, widx: 303, cap: 512)] channel: [id: 0xf5b3b299, L:/192.168.50.135:57496 - R:/192.168.50.167:6380]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:690)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:745)
org.redisson.client.RedisTimeoutException: Redis server response timeout (1000 ms) occured for command: (EVAL) with params: [local value = redis.call('get', KEYS[1]); assert(value ~= false, 'Capacity of queue ' .. KEYS[1] .. ..., 2, redisson_bqs:{purchase_queue_ravil2}, purchase_queue_ravil2, 1, PooledUnsafeDirectByteBuf(ridx: 0, widx: 303, cap: 512)] channel: [id: 0x099dd057, L:/192.168.50.135:57495 - R:/192.168.50.167:6380]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:690)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:745)`

**Thread dump**
`"redisson-netty-1-8" #25 prio=5 os_prio=31 tid=0x00007fc41d599800 nid=0x6503 runnable [0x0000700004eed000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00000007404cc4f8> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000074050c1c8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007404cc458> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"redisson-netty-1-7" #24 prio=5 os_prio=31 tid=0x00007fc41c3b3000 nid=0x6303 runnable [0x0000700004dea000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x000000074050c428> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000074050c440> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000074050c3d8> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"redisson-netty-1-6" #23 prio=5 os_prio=31 tid=0x00007fc41c1b1800 nid=0x6103 runnable [0x0000700004ce7000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00000007404c5098> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000007404783d8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007404c4ff8> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"redisson-netty-1-5" #22 prio=5 os_prio=31 tid=0x00007fc41c4f9800 nid=0x5f03 runnable [0x0000700004be4000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000740478638> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x0000000740478650> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007404785e8> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"redisson-netty-1-4" #21 prio=5 os_prio=31 tid=0x00007fc41df13000 nid=0x5d03 runnable [0x0000700004ae1000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00000007405da7d0> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000007405da7e8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007405da780> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"redisson-netty-1-3" #20 prio=5 os_prio=31 tid=0x00007fc41deba800 nid=0x5b03 runnable [0x00007000049de000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x000000074064b300> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000074064b318> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000074064b2b0> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"redisson-netty-1-2" #19 prio=5 os_prio=31 tid=0x00007fc41d1a3800 nid=0x5903 runnable [0x00007000048db000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x000000074051aee8> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000007406a6880> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000740515e38> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"redisson-netty-1-1" #17 prio=5 os_prio=31 tid=0x00007fc41d9a3000 nid=0x1107 runnable [0x0000700003213000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x000000074058dbb8> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000007406a6bd8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000074058daa8> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None`

### Steps to reproduce or test case
1. Make a slow docker image for redis 4.0.10 docker run -p 6380:6379 -m 100m --cpus=".5" redis:latest
2. Write junit test for RBoundedBlockingQueue and run them from remote instance.

> Test example below

    public static final int TIMEOUT = 1000;
    public static final int ATTEMPTS = 1;

    private static final RedissonClient redissonClient = RedissonClientFactory
        .getRedissonClient(TIMEOUT, ATTEMPTS);

    private static final String QUEUE_NAME = "queue_test";
    private static final RBoundedBlockingQueue<Runnable> queue = redissonClient.getBoundedBlockingQueue(QUEUE_NAME);

    static class TaskWrite implements Runnable {

        Integer id;

        public TaskWrite(Integer id) {
            this.id = id;
        }

        @Override
        public void run() {
            while (true) {
                SomeTask someTask = new SomeTask("1", "2", id, "3",
                    Collections.emptyMap(), Collections.emptyMap());
                queue.offer(someTask);
            }
        }
    }

    static class TaskRead implements Runnable {

        @Override
        public void run() {
            while (true) {
                queue.poll();
            }
        }
    }

    static class TaskLLen implements Runnable {

        @Override
        public void run() {
            int i = 0;
            while (true) {
                int size = queue.size();
                if (i % 250 == 0) {
                    System.out.println(queue.size());
                    i = 0;
                }
                i++;
            }
        }
    }

    @Test
    public void test() throws InterruptedException {

        System.out.println("Remaining capacity: " + queue.remainingCapacity());
        System.out.println("Try set capacity: " + queue.trySetCapacity(5));

        ExecutorService writer = Executors.newFixedThreadPool(8);
        writer.execute(new TaskWrite(1));
        writer.execute(new TaskWrite(1));
        writer.execute(new TaskWrite(1));
        writer.execute(new TaskWrite(1));
        writer.execute(new TaskWrite(1));
        writer.execute(new TaskWrite(1));
        writer.execute(new TaskWrite(1));
        writer.execute(new TaskWrite(1));

        ExecutorService reader = Executors.newFixedThreadPool(1);
        reader.execute(new TaskRead());

        ExecutorService llen = Executors.newFixedThreadPool(4);
        llen.execute(new TaskLLen());
        llen.execute(new TaskLLen());
        llen.execute(new TaskLLen());
        llen.execute(new TaskLLen());

        Thread.sleep(1000000);
    }

### Redis version
Redis 4.0.10

### Redisson version
Redisson 3.7.3

### Redisson configuration

> {
    "singleServerConfig": {
        "idleConnectionTimeout": 10000,
        "pingTimeout": 1000,
        "connectTimeout": 1000,
        "timeout": 1000,
        "retryAttempts": 1,
        "retryInterval": 1500,
        "subscriptionsPerConnection": 5,
        "sslEnableEndpointIdentification": true,
        "sslProvider": "JDK",
        "pingConnectionInterval": 10000,
        "keepAlive": true,
        "tcpNoDelay": false,
        "address": "redis://192.168.50.167:6380",
        "subscriptionConnectionMinimumIdleSize": 1,
        "subscriptionConnectionPoolSize": 50,
        "connectionMinimumIdleSize": 32,
        "connectionPoolSize": 64,
        "database": 0,
        "dnsMonitoringInterval": 5000
    },
    "threads": 0,
    "nettyThreads": 0,
    "codec": {
        "class": "org.redisson.codec.JsonJacksonCodec"
    },
    "referenceCodecProvider": {
        "class": "org.redisson.codec.DefaultReferenceCodecProvider"
    },
    "referenceEnabled": true,
    "transportMode": "NIO",
    "lockWatchdogTimeout": 30000,
    "keepPubSubOrder": true,
    "addressResolverGroupFactory": {
        "class": "org.redisson.connection.DnsAddressResolverGroupFactory"
    },
    "useLinuxNativeEpoll": false
}

**Comment by mrniko** [comment]
Unable to reproduce it with your testcase and --cpus=".05" param for docker.
But if I set --cpus=".01", I see lot of `Redis server response timeout` which means Redis doesn't have enough resources to process command in time.

Where is the stuck thread in your thread dump?

**Comment by vgpetrov** [comment]
@mrniko thanks for your answer, thinking that it could be failed ThreadPool. I'm closing it.
