### ISSUE TITLE
Connecting to AWS ElastiCache Redis in cluster mode behind NAT

### ISSUE THREAD

**Issue by soheil-jazayeri** [redisson/redisson#1549]
﻿### Expected behavior
I want to be able to use Redisson when Redis Cluster is behind NAT. I can think of following solutions:

1. Disable auto discovery and use ElastiCache Management Nodes for all request (prefered approach recommendation in [aws doc](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html)).
2. Disabling auto discovery by manually registering all nodes in Redisson. 
3. Provide customer provide DNS mapping

I am using AWS ElastiCache Redis in cluster mode where AWS creates a management endpoint for whole cluster and separate endpoint for each master node. My whole cluster is behind NAT, so when Redisson tries to discover all the nodes in the cluster it find their local IP not the NAT IP, as a result it fails to connect to clustered nodes.

### Actual behavior
Redisson discovers all the nodes in the clusters and tries to connect to them. However it fails because those IP/endpoints are behind NAT.

### Steps to reproduce or test case
Create an AWS ElastiCache Redis stack in cluster mode. Create a NAT on top of it and try to connect to the NATed cluster.

### Redis version
3.2.10

### Redisson version
3.6.5

### Redisson configuration
```code
        config.useReplicatedServers().addNodeAddress("Cluster Management Endpoint)
            .setConnectTimeout(500)
            .setMasterConnectionPoolSize(20)
            .setReadMode(ReadMode.MASTER);
```

**Comment by jackygurui** [comment]
Based on the redis document, NAT is currently not supported in cluster mode.

https://redis.io/topics/cluster-tutorial#redis-cluster-and-docker

**Comment by soheil-jazayeri** [comment]
Correct, but we can get around it if Redisson uses configuration endpoint instead of discover nodes automatically. 

Just to clarify nodes in the cluster can talk with each other since they are in same private network. Problem is to client (Redisson) has to connect to cluster thru NAT.

**Comment by mrniko** [comment]
> This should be kind of similar to "readMode" property for replication which client can set to "MASTER" so Redisson sends both read and write commands to master node instead of slaves.

You could use singeServer configuration in this case.

**Comment by soheil-jazayeri** [comment]
I have tried singleService without any luck, it seems Redisson still try to discover nodes:
`	org.redisson.client.RedisNodeNotFoundException: Node: /172.31.2.201:6379 for slot: 15144 hasn't been discovered yet
	at org.redisson.connection.MasterSlaveConnectionManager.getEntry(MasterSlaveConnectionManager.java:684) ~[Redisson-3.x.jar:?]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:674) ~[Redisson-3.x.jar:?]
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:503) ~[Redisson-3.x.jar:?]
	at org.redisson.command.CommandAsyncService.checkAttemptFuture(CommandAsyncService.java:751) ~[Redisson-3.x.jar:?]
	at org.redisson.command.CommandAsyncService.access$300(CommandAsyncService.java:80) ~[Redisson-3.x.jar:?]
	at org.redisson.command.CommandAsyncService$9.operationComplete(CommandAsyncService.java:610) ~[Redisson-3.x.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [netty-all-4.1.jar:4.1.27.Final]
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:98) [Redisson-3.x.jar:?]
	at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:78) [Redisson-3.x.jar:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:247) [Redisson-3.x.jar:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127) [Redisson-3.x.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]`

where `172.31.2.201` is the private ip address of one of master nodes in my cluster. here is my config:

`config.useSingleServer().setAddress("vpce-065af066e58fe0622-x6la1usx.vpce-svc-0ba3f0308bdbb9e32.us-west-2.vpce.amazonaws.com:6379")
            .setConnectTimeout(connectionTimeout)
            .setIdleConnectionTimeout(connectionIdleTimeout)
            .setDnsMonitoring(false);`

while redis benchmarking still works:

`./redis-benchmark -h vpce-065af066e58fe0622-x6la1usx.vpce-svc-0ba3f0308bdbb9e32.us-west-2.vpce.amazonaws.com -p 6379 -t set
====== SET ======
  100000 requests completed in 2.77 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

0.00% <= 1 milliseconds
98.47% <= 2 milliseconds
99.46% <= 3 milliseconds
99.73% <= 4 milliseconds
99.84% <= 5 milliseconds
99.86% <= 6 milliseconds
99.88% <= 7 milliseconds
99.91% <= 8 milliseconds
99.95% <= 11 milliseconds
99.96% <= 12 milliseconds
100.00% <= 13 milliseconds
100.00% <= 202 milliseconds
100.00% <= 207 milliseconds
36114.12 requests per second`

I've also tried registering all master nodes in useClusterServers, however it failed with following error:
`1) Error injecting constructor, org.redisson.client.RedisException: Multiple masters detected
  at com.amazon.alexa.presence.datastore.persistence.repository.redis.RedisStateRepository.<init>(RedisStateRepository.java:49)
  at com.amazon.alexa.presence.datastore.service.guice.PersistenceModule.configure(PersistenceModule.java:30) (via modules: com.amazon.alexa.presence.datastore.service.guice.ServiceModule -> com.amazon.alexa.presence.datastore.service.guice.PersistenceModule)
  while locating com.amazon.alexa.presence.datastore.persistence.repository.redis.RedisStateRepository
  while locating com.amazon.alexa.presence.datastore.persistence.repository.StateRepository
    for parameter 0 at com.amazon.alexa.presence.datastore.service.controller.v1.StateController.<init>(StateController.java:41)
  while locating com.amazon.alexa.presence.datastore.service.controller.v1.StateController

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:?]
	at org.jboss.resteasy.plugins.guice.GuiceResourceFactory.createResource(GuiceResourceFactory.java:35) ~[resteasy-guice-3.0.10.Final.jar:?]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236) ~[resteasy-jaxrs-3.0.10.Final.jar:?]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) ~[resteasy-jaxrs-3.0.10.Final.jar:?]
	... 25 more
Caused by: org.redisson.client.RedisException: Multiple masters detected
	at org.redisson.connection.ReplicatedConnectionManager.<init>(ReplicatedConnectionManager.java:86) ~[Redisson-3.x.jar:?]
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:267) ~[Redisson-3.x.jar:?]
	at org.redisson.Redisson.<init>(Redisson.java:115) ~[Redisson-3.x.jar:?]
	at org.redisson.Redisson.create(Redisson.java:154) ~[Redisson-3.x.jar:?]
	at com.amazon.alexa.presence.datastore.persistence.repository.redis.RedisRepository.<init>(RedisRepository.java:19) ~[AlexaPresenceDataStorePersistence-1.0.jar:?]
	at com.amazon.alexa.presence.datastore.persistence.repository.redis.RedisStateRepository.<init>(RedisStateRepository.java:49) ~[AlexaPresenceDataStorePersistence-1.0.jar:?]
	at com.amazon.alexa.presence.datastore.persistence.repository.redis.RedisStateRepository$$EnhancerByGuice$$6259de33.<init>(<generated>) ~[guice-4.0.jar:?]
	at com.amazon.alexa.presence.datastore.persistence.repository.redis.RedisStateRepository$$EnhancerByGuice$$6259de33$$FastClassByGuice$$df254dd.newInstance(<generated>) ~[guice-4.0.jar:?]
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ProxyFactory$ProxyConstructor.newInstance(ProxyFactory.java:266) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) ~[guice-4.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.0.jar:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) ~[guice-4.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-4.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) ~[guice-4.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012) ~[guice-4.0.jar:?]
	at org.jboss.resteasy.plugins.guice.GuiceResourceFactory.createResource(GuiceResourceFactory.java:35) ~[resteasy-guice-3.0.10.Final.jar:?]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236) ~[resteasy-jaxrs-3.0.10.Final.jar:?]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) ~[resteasy-jaxrs-3.0.10.Final.jar:?]
	... 25 more`

**Comment by mrniko** [comment]
Done. `Config.natMap` setting added.

**Comment by sailsgo** [comment]
@soheil-jazayeri  I also encountered the same problem,How do you solve this issue?
thanks
