### ISSUE TITLE
"RedisConnectionException: SlaveConnectionPool no available Redis entries" even when slave is reachable and connections established.

### ISSUE THREAD

**Issue by amarbsjnpr** [redisson/redisson#1569]
### Expected behavior
Since slave connections are present, connection exception should not occur

### Actual behavior

In our redis cluster of 3 nodes, redisson client is failing with following exception:
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts: [/172.16.62.5:6379] Hosts disconnected due to errors during `failedSlaveCheckInterval`: [/172.16.62.4:6380]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:197) [redisson-2.11.5.jar:]
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30) [redisson-2.11.5.jar:]
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:240) [redisson-2.11.5.jar:]
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:502) [redisson-2.11.5.jar:]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:595) [redisson-2.11.5.jar:]
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:497) [redisson-2.11.5.jar:]
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:589) [redisson-2.11.5.jar:]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) [netty-common-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) [netty-common-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) [netty-common-4.1.23.Final.jar:4.1.23.Final]

However, the client host does have connections:
root@csp:/# netstat -an | grep 172.16.62.4:6380 | wc -l
29

All the 29 above connections are in ESTABLISHED state.

### Steps to reproduce or test case

1) Setup a 3-node master/slave cluster with sharding. 
2) Start redisson client.
3) Ensure that there is no cluster state change.
4) After sometime client fails with above error on read operation.

### Redis version
3.2.5

### Redisson version
2.11.5 (using java 7)

### Redisson configuration
Using programmatic ClusterServersConfig
timeout = 10s
retryAttempts = 5
retryInterval = 30s
all the other values are defaults.

### Other observations:
1) Typically, we see the following log when slave connection-pool is populated on client startup:

July 30th 2018, 22:33:32.567	org.redisson.connection.pool.SlaveConnectionPool	operationComplete	32 connections initialized for /172.16.62.3:6380

But, for the failed slave (172.16.62.4), during client startup, the above log never came.

2) The number of idle connections for failed slave was less than slaveConnectionMinimumIdleSize. It was 29 instead of 32.

3) Couldn't find any io.netty or org.redisson error logs indicating connection issues for either the master (172.16.62.5:6379) or the slave (172.16.62.4:6380)

### Attachments:

1) redis-debug-logs - org.redisson debug logs from client start till failure. All debug logs except the cluster-scan logs which are highly frequent (printed every second).
2) server-info - output of redis-cli "INFO" command for each server.
3) cluster-info - output of redis-cli "CLUSTER INFO" command
4) cluster-nodes - output of redis-cli "CLUSTER NODES" command

[cluster-info.txt](https://github.com/redisson/redisson/files/2244167/cluster-info.txt)
[cluster-nodes.txt](https://github.com/redisson/redisson/files/2244168/cluster-nodes.txt)
[redis-debug-logs.txt](https://github.com/redisson/redisson/files/2244176/redis-debug-logs.txt)
[server-info-172.16.62.4.txt](https://github.com/redisson/redisson/files/2244206/server-info-172.16.62.4.txt)
[server-info-172.16.62.5.txt](https://github.com/redisson/redisson/files/2244207/server-info-172.16.62.5.txt)
[server-info-172.16.62.3.txt](https://github.com/redisson/redisson/files/2244208/server-info-172.16.62.3.txt)

**Comment by amarbsjnpr** [comment]
Hello,
Request for any update on this.

**Comment by mrniko** [comment]
Unable to reproduce the issue
