### ISSUE TITLE
Spring session integration error

### ISSUE THREAD

**Issue by bsandhu** [redisson/redisson#1570]
### Expected behavior
Spring Session should be able to serialize/deserialize the Spring session > security context via Redisson as [documented](https://github.com/redisson/redisson/wiki/14.-Integration%20with%20frameworks#146-spring-session)

### Actual behavior
Spring `SecurityContextImpl` fails to deserialize when its put in a Redisson map.
It deserializes _ok_ in a regular HashMap, leading to the conclusion that this might be a Redisson issue. 

### Steps to reproduce or test case
The test case demonstrates the problem by replicating the behavior of the `RedissonSessionRepository::load()` method

- springSecurityCtxWithoutRedis - passes
- springSecurityCtxWithRedis - fails, with the following exception:

```
ERROR 2018-07-31 23:46:56,306 [,] CommandDecoder.decodeCommand(132) : Unable to decode data. channel: [id: 0xc3f4f62d, L:/172.19.0.2:59869 - R:nydevelop1.biometric.software/10.20.8.4:6379] message: $420
{"@class":"org.springframework.security.core.context.SecurityContextImpl","authentication":{"@class":"org.springframework.security.authentication.UsernamePasswordAuthenticationToken","authenticated":true,"authorities":["java.util.Collections$UnmodifiableRandomAccessList",[{"@class":"org.springframework.security.core.authority.SimpleGrantedAuthority","authority":"ADMIN"}]],"credentials":"foo","principal":"PRINCIPAL"}}

com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@class' that is to contain type id  (for class com.fasterxml.jackson.databind.JsonNode)
 at [Source: io.netty.buffer.ByteBufInputStream@81fb03e; line: 1, column: 419] (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1389) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1210) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:165) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:105) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:182) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeWithType(JsonNodeDeserializer.java:151) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserializeWithType(JsonNodeDeserializer.java:15) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2223) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at org.springframework.security.jackson2.UsernamePasswordAuthenticationTokenDeserializer.deserialize(UsernamePasswordAuthenticationTokenDeserializer.java:61) ~[spring-security-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.security.jackson2.UsernamePasswordAuthenticationTokenDeserializer.deserialize(UsernamePasswordAuthenticationTokenDeserializer.java:47) ~[spring-security-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:502) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:111) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:182) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:553) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924) ~[jackson-databind-2.8.11.1.jar:2.8.11.1]
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:92) ~[redisson-3.7.5.jar:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:347) ~[redisson-3.7.5.jar:?]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:128) [redisson-3.7.5.jar:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108) [redisson-3.7.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-codec-4.1.27.Final.jar:4.1.27.Final]
```

```
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Before;
import org.junit.Test;
import org.redisson.Redisson;
import org.redisson.api.RedissonClient;
import org.redisson.codec.JsonJacksonCodec;
import org.redisson.config.Config;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextImpl;
import org.springframework.security.jackson2.SecurityJackson2Modules;

import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class JacksonTest {

    private ObjectMapper objectMapper;
    private SecurityContextImpl sc;

    @Before
    public void setupMapper() {
        objectMapper = new ObjectMapper()
                .registerModules(SecurityJackson2Modules.getModules(this.getClass().getClassLoader()));

        sc = new SecurityContextImpl();
        sc.setAuthentication(new UsernamePasswordAuthenticationToken(
                "Principal",
                "foo",
                Arrays.asList(new SimpleGrantedAuthority("ADMIN"))
        ));
    }

   @Test
    public void springSecurityCtxWithRedis() throws IOException {
        Config config = Config.fromJSON("{" +
                "\"singleServerConfig\" :{" +
                "\"password\": \"iAmRedis1#$!\", " +
                "\"address\" : \"redis://nydevelop1.biometric.software:6379\"" +
                "}" +
                "}");
        config.setCodec(new JsonJacksonCodec(objectMapper));
        RedissonClient conn = Redisson.create(config);

        Map<String, Object> map = conn.getMap("TEST");

        // FAILS here
        map.put("TEST_CTX", sc);
        map.get("TEXT_CTX");
    }

    @Test
    public void springSecurityCtxWithoutRedis() throws IOException {
        Map<String, Object> map = new HashMap<>();
        map.put("TEST_CTX", sc);
        String asJson = objectMapper.writeValueAsString(map);
        System.out.println(asJson);

        // PASSES
        Object value = objectMapper.readValue(asJson, Object.class);
        System.out.println(value);
    }
}
```

### Redis version
3.2.11

### Redisson version
3.7.5
Spring Session: 2.0.5.RELEASE

### Redisson configuration
singleServerConfig (see test)

**Comment by bsandhu** [comment]
More info:
In Redis the test data looks like this:

```{
	"@class": "org.springframework.security.core.context.SecurityContextImpl",
	"authentication": {
		"@class": "org.springframework.security.authentication.UsernamePasswordAuthenticationToken",
		"authenticated": true,
		"authorities": [
			"java.util.Collections$UnmodifiableRandomAccessList",
			[
				{
					"@class": "org.springframework.security.core.authority.SimpleGrantedAuthority",
					"authority": "ADMIN"
				}
			]
		],
		"credentials": "foo",
		"principal": "HYPR"
	}
}```

**Comment by mrniko** [comment]
Try to extend `JsonJacksonCodec` and override `initTypeInclusion` method into empty one.

**Comment by bsandhu** [comment]
I did some digging. It looks like its a conflict between:
Spring Security > `SecurityJackson2Modules > WhitelistTypeIdResolver`
and
Redisson > `JsonJacksonCode > TypeResolverBuilder`

The Spring stuff is pkg protected, so I went with using Redisson Jackson codec setup as the base and 
resolving the default constructor errors on my own. 
 
```
    @Bean
    @Qualifier(REDIS_CACHE_CLIENT)
    fun jacksonObjectMapperRedis(): ObjectMapper {
        val objectMapper = ObjectMapper()
        // This should work, doesn't
        // objectMapper.registerModules(SecurityJackson2Modules.getModules(this.getClass().getClassLoader()));
       // Use what we can, from Spring
       objectMapper.registerModule(WebJackson2Module())
        objectMapper.registerModule(KotlinModule())
        objectMapper.registerModule(SpringSecurityModules())

        return objectMapper
    }
}

/** ****************************************************************************** */

class SpringSecurityModules : SimpleModule(SpringSecurityModules::class.java.name, Version(1, 0, 0, null, null, null)) {

    override fun setupModule(context: Module.SetupContext) {
        context.setMixInAnnotations(UsernamePasswordAuthenticationToken::class.java, UsernamePasswordAuthenticationTokenMixin::class.java)
        context.setMixInAnnotations(SimpleGrantedAuthority::class.java, SimpleGrantedAuthorityMixin::class.java)
        context.setMixInAnnotations(BadCredentialsException::class.java, BadCredentialsExceptionMixin::class.java)
        context.setMixInAnnotations(Collections.unmodifiableList(ArrayList<Any>()).javaClass, ListMixin::class.java)

        context.setMixInAnnotations(ResponseEntity::class.java, ResponseEntityMixin::class.java)
        context.setMixInAnnotations(DeviceRegistrationRequestResponse::class.java, DeviceRegistrationRequestResponseMixin::class.java)
    }
}

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "@class")
abstract class UsernamePasswordAuthenticationTokenMixin
@JsonCreator constructor(
    @JsonProperty("principal") principal: Any,
    @JsonProperty("credentials") credentials: Any,
    @JsonProperty("authorities") authorities: Collection<GrantedAuthority>) {

    @JsonIgnore
    abstract fun setAuthenticated(authenticated: Boolean)
}

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "@class")
abstract class BadCredentialsExceptionMixin {
    @JsonCreator constructor(@JsonProperty("msg") msg: String)
}

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "@class")
class ListMixin {
    @JsonCreator constructor(@JsonProperty("list") list: List<*>)
}

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "@class")
abstract class SimpleGrantedAuthorityMixin {
    @JsonCreator constructor(@JsonProperty("role") role: String)
}
```
