### ISSUE TITLE
Redisson stand alone giving classNotFoundException 

### ISSUE THREAD

**Issue by pushparajxa** [redisson/redisson#1580]
### Expected behavior
When we try to run java -cp core-1.0-SNAPSHOT.jar -jar redisson-all-3.7.3.jar single.json, classNotFoundException should not occur

### Actual behavior
we get classNotFound Exception

main] ERROR org.redisson.RedissonNode - Can't parse json config single_initializer.json
com.fasterxml.jackson.databind.JsonMappingException: Invalid type id 'com.rivigo.zoom.kairos.timer.KairosRedissonNodeInitializer' (for id type 'Id.class'): no such class found (through reference chain: org.redisson.config.RedissonNodeConfig["redissonNodeInitializer"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:379)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1514)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2691)
	at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:135)
	at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:130)
	at org.redisson.config.RedissonNodeConfig.fromJSON(RedissonNodeConfig.java:110)
	at org.redisson.RedissonNode.main(RedissonNode.java:92)
Caused by: java.lang.IllegalArgumentException: Invalid type id 'com.rivigo.zoom.kairos.timer.KairosRedissonNodeInitializer' (for id type 'Id.class'): no such class found
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:79)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:51)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:158)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:106)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:493)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	... 7 more
### Redisson configuration
single.json has following configutation
{
   "singleServerConfig":{
      "address": "redis://127.0.0.1:6379"
   },
   "threads":2,
   "executorServiceWorkers": {"cpbsummary_worker":2},
   "redissonNodeInitializer": {"class":"com.rivigo.zoom.kairos.timer.KairosRedissonNodeInitializer.java"}
}

**Comment by mrniko** [comment]
Did you resolve this issue?

**Comment by pushparajxa** [comment]
We resolved this.
