### ISSUE TITLE
Can't write command batch to channel: [id: 0x61e3267f, L:/xxxxxxxx:xxx ! R:xxxxxx/xxxxxx:6379].

### ISSUE THREAD

**Issue by fl061157** [redisson/redisson#1581]
Can't write command batch to channel: [id: 0x61e3267f, L:/xxxxxxxx:xxx ! R:xxxxxx/xxxxxx:6379].

If redis block for some times. then redis recover. 
but redisson still use broken connection.
I found the tcp.socket not exists , bu we use it .
 why we not close it in   CommandBatchService.checkWriteFuture

**Comment by mrniko** [comment]
Could you provide some test case to reproduce that? Thanks!

**Comment by fl061157** [comment]
@mrniko  ， I think I already know the reason ,   In  Redisson  Config , i add PingHandler ,     but  when the channel inactive and the redis block 。  Then  the ConnectionWatchdog.reconnect   can't reconnect , and retrun 。 because RedisConnectionHandler.channelActive   not receive the redis response command .  so i remove the config of pingHandler

**Comment by mrniko** [comment]
Please share Redisson configuration

**Comment by tech-tao** [comment]
@mrniko I got the same error but I don't see PingHandler in config, How did you resolve this?

**Comment by CHANGEX929** [comment]
> @mrniko I got the same error but I don't see PingHandler in config, How did you resolve this?

Hi，Have you fixed this problem？I got the same error too！

**Comment by mrniko** [comment]
@CHANGEX929 

Which Redisson version do you use? Please share Redisson configuration. Have you set password setting?

**Comment by CHANGEX929** [comment]
> @CHANGEX929
> 
> Which Redisson version do you use? Please share Redisson configuration. Have you set password setting?

Thanks for your reply !!
My Redisson version is 3.11.0(redisson-spring-boot-starter)，and my configuration is default . Have no password setting.
Unfortunately,I don't know why the error happened, it happened sometimes.

**Comment by mrniko** [comment]
@CHANGEX929 

Could you share full stacktrace?

**Comment by CHANGEX929** [comment]
> @ CHANGEX929
> 
> 您可以共享完整的堆栈跟踪信息吗？

ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.connection.RedisPipelineException: Pipeline contained one or more invalid commands; nested exception is org.redisson.client.WriteRedisConnectionException: Can't write command batch to channel: [id: 0x0c0ec9b7, L:/192.168.0.4:56342 - R:192.168.0.7/192.168.0.7:6379]] with root cause
java.lang.NullPointerException: null
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:131)
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:100)
        at org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:52)
        at org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:32)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
        at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:106)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1031)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:310)
        at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:132)
        at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)


> @CHANGEX929
> 
> Could you share full stacktrace?

ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.connection.RedisPipelineException: Pipeline contained one or more invalid commands; nested exception is org.redisson.client.WriteRedisConnectionException: Can't write command batch to channel: [id: 0x0c0ec9b7, L:/192.168.0.4:56342 - R:192.168.0.7/192.168.0.7:6379]] with root cause
java.lang.NullPointerException: null
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:131)
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:100)
        at org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:52)
        at org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:32)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
        at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:106)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1031)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:310)
        at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:132)
        at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by CHANGEX929** [comment]
> @CHANGEX929
> 
> Could you share full stacktrace?

ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.connection.RedisPipelineException: Pipeline contained one or more invalid commands; nested exception is org.redisson.client.WriteRedisConnectionException: Can't write command batch to channel: [id: 0x0c0ec9b7, L:/192.168.0.4:56342 - R:192.168.0.7/192.168.0.7:6379]] with root cause
java.lang.NullPointerException: null
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:131)
        at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:100)
        at org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:52)
        at org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:32)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
        at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:106)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1031)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:310)
        at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:132)
        at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
@CHANGEX929 

This issue related to redisson object defined with `null` name. Please check it

**Comment by CHANGEX929** [comment]
> @CHANGEX929
> 
> Could you share full stacktrace?

I using spring security oauth2.0,it's tokenstore using RedisConnectionFactory, this exception throw when i using tokenstore to remove token. I have no idea to check .... But thanks for your help!

**Comment by mrniko** [comment]
@CHANGEX929 

Could you spot which opertion does it use in this case?

**Comment by fl061157** [comment]
if you set interval time you will use ping Handler.   password are same with PingHandler. if connection is create ，it will execute these command ，if fail，it close The connection。




| |
方亮
|
|
邮箱：18625154592@163.com
|

签名由 网易邮箱大师 定制

On 12/19/2019 18:38, CHANGEX wrote:

@mrniko I got the same error but I don't see PingHandler in config, How did you resolve this?

Hi，Have you fixed this problem？I got the same error too！

**Comment by CHANGEX929** [comment]
> @CHANGEX929
> 
> Could you spot which opertion does it use in this case?

I use org.springframework.security.oauth2.provider.token.TokenStore.removeAccessToken, the exception happend sometimes

**Comment by CHANGEX929** [comment]
> @CHANGEX929
> 
> Could you spot which opertion does it use in this case?

And the TokenStore using RedissonConnectionFactory to operat Redis

**Comment by CHANGEX929** [comment]
> @CHANGEX929
> 
> Could you spot which opertion does it use in this case?

Thanks for your help,I think I can't describe the phenomenon clearly. Thank you very much!

**Comment by fl061157** [comment]
i am using phone to answer you.code not in my phone. I just rewrite sentinelManagerConfig . It like watchdog .  


| |
方亮
|
|
邮箱：18625154592@163.com
|

签名由 网易邮箱大师 定制

On 12/19/2019 21:06, CHANGEX wrote:

@CHANGEX929

Could you spot which opertion does it use in this case?

Thanks for your help,I think I can't describe the phenomenon clearly. Thank you very much!

**Comment by CHANGEX929** [comment]
> i am using phone to answer you.code not in my phone. I just rewrite sentinelManagerConfig . It like watchdog . | | 方亮 | | 邮箱：18625154592@163.com | 签名由 网易邮箱大师 定制 On 12/19/2019 21:06, CHANGEX wrote: @CHANGEX929 Could you spot which opertion does it use in this case? Thanks for your help,I think I can't describe the phenomenon clearly. Thank you very much! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks!! I will try it tommorow!

**Comment by syschen** [comment]
兄弟，我好像跟你遇到一模一样的问题了，我这边也是用TokenStore删除token时，偶尔会报这个
能分享一下怎么解决的吗？

**Comment by syschen** [comment]
> > i am using phone to answer you.code not in my phone. I just rewrite sentinelManagerConfig . It like watchdog . | | 方亮 | | 邮箱：[18625154592@163.com](mailto:18625154592@163.com) | 签名由 网易邮箱大师 定制 On 12/19/2019 21:06, CHANGEX wrote: @CHANGEX929 Could you spot which opertion does it use in this case? Thanks for your help,I think I can't describe the phenomenon clearly. Thank you very much! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> thanks!! I will try it tommorow!

兄弟，我好像跟你遇到一模一样的问题了，我这边也是用TokenStore删除token时，偶尔会报这个
能分享一下怎么解决的吗？

**Comment by CHANGEX929** [comment]
> > > i am using phone to answer you.code not in my phone. I just rewrite sentinelManagerConfig . It like watchdog . | | 方亮 | | 邮箱：[18625154592@163.com](mailto:18625154592@163.com) | 签名由 网易邮箱大师 定制 On 12/19/2019 21:06, CHANGEX wrote: @CHANGEX929 Could you spot which opertion does it use in this case? Thanks for your help,I think I can't describe the phenomenon clearly. Thank you very much! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > thanks!! I will try it tommorow!
> 
> 兄弟，我好像跟你遇到一模一样的问题了，我这边也是用TokenStore删除token时，偶尔会报这个
> 能分享一下怎么解决的吗？

这个问题我最后也没有解决，搁置了。。。
