### ISSUE TITLE
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder

### ISSUE THREAD

**Issue by Lennyss** [redisson/redisson#1586]
### Expected behavior
set value: "avaible" to key: "test"
### Actual behavior
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/jsontype/TypeResolverBuilder
at org.redisson.config.Config.(Config.java:110) ~[?:?]
at org.redisson.Redisson.(Redisson.java:120) ~[?:?]
at org.redisson.Redisson.create(Redisson.java:159) ~[?:?]
...
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_141]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paperspigot-1.8.8-R0.1-SNAPSHOT-remapped.jar:git-PaperSpigot-unknown]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paperspigot-1.8.8-R0.1-SNAPSHOT-remapped.jar:git-PaperSpigot-unknown]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
at org.redisson.config.Config.(Config.java:110) ~[?:?]
at org.redisson.Redisson.(Redisson.java:120) ~[?:?]
at org.redisson.Redisson.create(Redisson.java:159) ~[?:?]
### Steps to reproduce or test case
invoke code:
    Config config = new Config();
            config.useSingleServer().setAddress("redis://"+host+":6349");
            RedissonClient a = Redisson.create(config);
            a.getBucket("Test").set("avaible");
### Redis version
redis_version:4.0.9

### Redisson version
3.7.5
### Redisson configuration
Default

pom:
        <dependency>
            <groupId>org.redisson</groupId>
            <scope>compile</scope>
            <artifactId>redisson</artifactId>
            <version>3.7.5</version>
        </dependency>

after built project and run on vps(java 1.8) error appear, in intellij everythink work

**Comment by mrniko** [comment]
Check your classpath for jackson lib presence
