### ISSUE TITLE
Non Sticky Session with tomcat 8: Session loaded in second node triggers new session event(tellnew)

### ISSUE THREAD

**Issue by jmuthu** [redisson/redisson#1595]
We are using Tomcat 8 session replication and some attributes are set in session listeners whenever a new session event is created. Configuration details are given below. 

When a request for a session (created in node 1 goes to node 2) is loaded from redis cache, we are getting the following error as one of the listeners is setting an attribute and the Session's isValid attribute is false at the time.

Expected behavior is that for sessions loaded from redis cache, "session created" event (tellNew) should not be triggered. 

A probable solution would be to disable notification when setting the session id (ie) setId(id, false) in  RedissonSessionManager.findSession function. 

16-Aug-2018 20:25:46.314 SEVERE [ajp-nio-8010-exec-3] org.apache.catalina.session.StandardSession.tellNew Session event listener threw exception
 java.lang.IllegalStateException: setAttribute: Session [CED5C6D89DC87D28A6842EAC52631D26] has already been invalidated
        at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1450)
        at org.redisson.tomcat.RedissonSession.setAttribute(RedissonSession.java:184)
        at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1415)
        at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:137)
        at **org.eclipse.birt.report.listener.ViewerHttpSessionListener.sessionCreated(ViewerHttpSessionListener.java:41)**
        at org.apache.catalina.session.StandardSession.tellNew(StandardSession.java:396)
        at org.apache.catalina.session.StandardSession.setId(StandardSession.java:368)
        at org.redisson.tomcat.RedissonSession.setId(RedissonSession.java:72)
        at org.apache.catalina.session.StandardSession.setId(StandardSession.java:349)
        at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:159)
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2977)
        at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2695)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:466)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
### Steps to reproduce or test case
Configure a cluster of tomcat 8 servers using redisson/redis managers.  Configure the load balancer for non sticky sessions. 
Have a HttpSessionListener configured to set some attribute on sessionCreated event. 
public class ViewerHttpSessionListener implements HttpSessionListener
{
       public void sessionCreated( HttpSessionEvent event )
	{
		// Create Tasks map
		HttpSession session = event.getSession( );
		session.setAttribute( "TASKS", new HashMap( ) );
	}
        public void sessionDestroyed( HttpSessionEvent event )
	{
	}
}
Add this listener to the application's web.xml 
<listener>
		<listener-class>org.eclipse.birt.report.listener.ViewerHttpSessionListener</listener-class>
</listener>

Start the loadbalancer and all tomcat nodes. Login to the application and browse through the application.The above error will be logged in the log files for the node that is trying to load the session from the redis cache. 

### Redis version
4.0.11
### Redisson version
3.7.5
#### redisson.yaml
singleServerConfig:
  address: "redis://192.168.8.224:6379"
codec: !<org.redisson.codec.SerializationCodec> {}

#### context.xml
<Manager className="org.redisson.tomcat.RedissonSessionManager"
          configPath="${catalina.base}/conf/redisson.yaml" readMode="REDIS" updateMode="DEFAULT"/>

**Comment by Maks5299** [comment]
Hi, I have the same issue, but I use claster

**Comment by mrniko** [comment]
This issue was fixed in 3.10.4 version https://github.com/redisson/redisson/issues/1558

Could you try it and give your feedback?

**Comment by Maks5299** [comment]
Hello @mrniko ! We got this problem in 3.10.5 version.

**Comment by mrniko** [comment]
@Maks5299 

Hi! Did you update redisson-tomcat as well?

**Comment by Maks5299** [comment]
@mrniko yep, we downloaded redisson-tomcat-8-3.10.5.jar and located it in $CATALINA_HOME/lib folder.

**Comment by mrniko** [comment]
Could you describe your test scenario?

**Comment by Maks5299** [comment]
Ok, I have a first node for managers and a second for clients. And on the first node I need to listen to the client session state(create/destroy) and make some actions with it.
Now we are switching to Redis, and this does not work on our test servers. But it worked before.

**Comment by mrniko** [comment]
Could you clarify worked before which version?

**Comment by Maks5299** [comment]
We didn't use redisson then. We used tomcat clastering. Here is a part of our past config:
~~~xml
 <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster" channelSendOptions="8" channelStartOptions="3">
        <Manager className="org.apache.catalina.ha.session.DeltaManager"
                 expireSessionsOnShutdown="false"
                 notifyListenersOnReplication="true"
                 stateTransferTimeout="1200"
                 sendAllSessions="true"
                 sendAllSessionsSize="5000"
                 sendAllSessionsWaitTime="2000"
                 notifySessionListenersOnReplication="true"/>

        <Channel className="org.apache.catalina.tribes.group.GroupChannel">

          <Receiver className="org.apache.catalina.tribes.transport.nio.NioReceiver"
                    address="node1"
                    port="4110"
                    autoBind="9"
                    selectorTimeout="5000"
                    maxThreads="6"/>

          <Sender timeout="120000"  className="org.apache.catalina.tribes.transport.ReplicationTransmitter">
          <Transport className="org.apache.catalina.tribes.transport.nio.PooledParallelSender"/>
          </Sender>
          <Interceptor className="org.apache.catalina.tribes.group.interceptors.TcpPingInterceptor"/>
          <Interceptor className="org.apache.catalina.tribes.group.interceptors.TcpFailureDetector"/>
          <Interceptor className="org.apache.catalina.tribes.group.interceptors.MessageDispatch15Interceptor"/>

          <Interceptor className="org.apache.catalina.tribes.group.interceptors.StaticMembershipInterceptor">
                <Member className="org.apache.catalina.tribes.membership.StaticMember"
                  port="4110"
                  host="node2"
                  domain="delta-static"
                  uniqueId="{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}"
                />
          </Interceptor>

        </Channel>
        <Valve className="org.apache.catalina.ha.tcp.ReplicationValve" filter=""/>
        <Valve className="org.apache.catalina.ha.session.JvmRouteBinderValve"/>

        <ClusterListener className="org.apache.catalina.ha.session.ClusterSessionListener"/>
</Cluster>
~~~

**Comment by mrniko** [comment]
Fixed! New `broadcastSessionEvents` setting introduced. 

@Maks5299 
Please try follow updated tomcat module and set `broadcastSessionEvents = true`
[redisson-tomcat-8-3.10.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3021267/redisson-tomcat-8-3.10.6-SNAPSHOT.jar.zip)
