### ISSUE TITLE
RedisConnectionException thrown if client-name is set and retry-attempts is zero

### ISSUE THREAD

**Issue by jeiroa** [redisson/redisson#1611]
### Expected behavior
Redisson should start properly when _client-name_ property is set and _retry-attempts_ property is zero in a single-server configuration.

Redisson starts properly if _retry-attempts_ is set to 1.

### Actual behavior
The following exception is thrown and the server does not start:
```
org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:137)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:83)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:299)
	at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:53)
	at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:264)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:83)
	at org.redisson.client.RedisClient$2$1$1$1.run(RedisClient.java:240)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLIENT SETNAME), command params: [test-redisson-cli], Redis client: [addr=redis://127.0.0.1:6379]
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:213)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
```
### Steps to reproduce or test case
1.- set client-name="test-redisson-cli" and retry-attempts="0" in the configuration file.
2.- Start Redisson

Please check the configuration used below.

### Redis version
3.2.12

### Redisson version
2.12.5

### Redisson configuration
Spring XML format:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:redisson="http://redisson.org/schema/redisson"
	xsi:schemaLocation="
		http://www.springframework.org/schema/beans
			http://www.springframework.org/schema/beans/spring-beans.xsd
		http://redisson.org/schema/redisson
			http://redisson.org/schema/redisson/redisson.xsd
	" default-lazy-init="false">

  <bean id="redissonNioEventLoopGroup" class="io.netty.channel.nio.NioEventLoopGroup" />

  <redisson:client
    id="redissonClient"
    threads="8"
    netty-threads="8" 
    event-loop-group-ref="redissonNioEventLoopGroup">
    <redisson:single-server 
      client-name="test-redisson-cli"
      address="redis://127.0.0.1:6379"
      connect-timeout="10000"
      timeout="10000"
      retry-attempts="0"
      retry-interval="1500"
      subscription-connection-minimum-idle-size="1"
      subscription-connection-pool-size="50"
      connection-minimum-idle-size="32"
      connection-pool-size="64"
      idle-connection-timeout="10000"
      database="0" />
  </redisson:client>
</beans>
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
