### ISSUE TITLE
Redisson Sentinel not executing scheduled task on Master-Slave Failover

### ISSUE THREAD

**Issue by mohitsinghcse** [redisson/redisson#1622]
I am running Redis in Sentinel Mode with 5 Sentinel, 1 Master and 2 Slaves. I am scheduling a task with Redisson. It is executing the scheduled tasks normally but if i bring down the Master and a new master is elected by the sentinels, redisson doesn't execute the previously scheduled task. Newly scheduled tasks are getting executed.

```
RedissonTest.createRedissonNode();
            RScheduledExecutorService scheduledExecutorService = redissonClient.getExecutorService("dialer_manager_worker");
             scheduledExecutorService.schedule(new CallableTask(i), i+1, TimeUnit.MINUTES);
```
**Observation:** The previously scheduled tasks are getting executed on restarting redisson node.

### Expected behavior
Redisson Node should execute the previously scheduled task after master-slave failover

### Actual behavior
Redisson Node doesn't execute the previously scheduled task after master-slave failover.

### Steps to reproduce or test case

1. Submit scheduled task to redisson
2. Shutdown Redis Master
3. After sentinels have elected new master, wait for redisson to execute the previously executed task.

### Redis version
4.0.11

### Redisson version
3.7.5

### Redisson configuration
```
RedissonNodeConfig nodeConfig = new RedissonNodeConfig();
        SentinelServersConfig sentinelServersConfig = nodeConfig.useSentinelServers();
        sentinelServersConfig.setMasterName("master01")
                .addSentinelAddress("redis://192.168.2.132:26379", "redis://192.168.2.132:26380", "redis://192.168.2.132:26381")
                .addSentinelAddress("redis://192.168.2.130:26379", "redis://192.168.2.130:26380");
        nodeConfig.setRedissonNodeInitializer(new UbonaRedissonNodeinitializer());
        Map<String, Integer> workers = new HashMap<>();
        workers.put("dialer_manager_worker", 5);
        nodeConfig.setExecutorServiceWorkers(workers);
```

**Comment by mohitsinghcse** [comment]
**Update**

When the redis instance comes back up as SLAVE instance, Redisson Remote Service is still saving stale state and considering it as Master. Below is the exception stack trace to confirm:

ERROR org.redisson.RedissonRemoteService - Can't process the remote service request.
org.redisson.client.RedisException: READONLY You can't write against a read only slave.. channel: [id: 0x10a01586, L:/192.168.2.82:58007 - R:192.168.2.130/192.168.2.130:6379] command: (BLPOP), params: [{redisson_mapreduce:org.redisson.executor.RemoteExecutorService}, 0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:333)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:128)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
does this happen on Redisson Node or application with RedissonClient instance?

**Comment by mohitsinghcse** [comment]
It is happening on an Embedded Radisson Node.

**Comment by mrniko** [comment]
> Redisson Remote Service is still saving stale state and considering it as Master

Fixed

**Comment by mrniko** [comment]
Could you assist and recheck the issue "Redisson Node doesn't execute the previously scheduled task after master-slave failover"  ?

**Comment by mrniko** [comment]
Redisson node failover test passed. Fixed.
