### ISSUE TITLE
Spring boot fail to start when I use redisson-spring-boot-starter

### ISSUE THREAD

**Issue by DevWantJustHaveFun** [redisson/redisson#1640]
I have tried to use redisson-spring-boot-starter in this sample project :
https://github.com/DevWantJustHaveFun/spring-boot-session-redisson/tree/redisson-spring-boot-start-dependency

But unfortunately it doesn't work, I get this error at startup:
```
2018-09-14 17:10:05.426 ERROR 16816 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.devwantjusthavefun.springbootsessionredisson.SpringBootSessionRedissonApplication]; nested exception is java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.MetricRepositoryAutoConfiguration$LegacyMetricRepositoryConfiguration
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:646) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.lambda$processDeferredImportSelectors$2(ConfigurationClassParser.java:566) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
        at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:563) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:271) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:91) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at com.devwantjusthavefun.springbootsessionredisson.SpringBootSessionRedissonApplication.main(SpringBootSessionRedissonApplication.java:11) [main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.4.RELEASE.jar:2.0.4.RELEASE]
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.MetricRepositoryAutoConfiguration$LegacyMetricRepositoryConfiguration
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64) ~[spring-boot-autoconfigure-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:221) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:362) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:265) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:636) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
        ... 22 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.boot.system.JavaVersion
        at org.springframework.boot.autoconfigure.condition.OnJavaCondition.getMatchOutcome(OnJavaCondition.java:48) ~[spring-boot-autoconfigure-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.0.4.RELEASE.jar:2.0.4.RELEASE]
        ... 28 common frames omitted

```

### Redis version
redis 3.2.9

### Redisson version
redisson 3.8.0

**Comment by mrniko** [comment]
I added spring.factories and spring.provides files into Spring Boot Start module. Absence of which could affect Redisson application based on Spring Boot. Could you try 3.8.1 version?

**Comment by DevWantJustHaveFun** [comment]
Same error with 3.8.1

**Comment by mykolap** [comment]
https://mvnrepository.com/artifact/org.redisson/redisson-spring-boot-starter/3.8.1
this artifact has dependency redisson-spring-data-18, that depends on spring boot 1.5, and this dependency is not optional

Maybe my fix can help you:
compile 'org.springframework.session:spring-session-data-redis'
compile "org.redisson:redisson-spring-data-20:${redissonVersion}"
compile: "org.redisson", name: "redisson-spring-boot-starter", version: "${redissonVersion}", transitive: false

**Comment by DevWantJustHaveFun** [comment]
@mykolap, thanks! this work around fix my issue, I have updated the sample

@mrniko, the addition of the "redisson-spring-boot-starter" with some out of the box auto-configuration is a cool idea but in the other hand we get many unnecessary dependency 
like spring-data-redis, spring-data-keyvalue, oxm, lettuce etc...
```
org.springframework.boot:spring-boot-starter-data-redis:2.0.4.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:2.0.4.RELEASE (*)
|    +--- org.springframework.data:spring-data-redis:2.0.9.RELEASE
|    |    +--- org.springframework.data:spring-data-keyvalue:2.0.9.RELEASE
|    |    |    +--- org.springframework.data:spring-data-commons:2.0.9.RELEASE
|    |    |    |    +--- org.springframework:spring-core:5.0.8.RELEASE (*)
|    |    |    |    +--- org.springframework:spring-beans:5.0.8.RELEASE (*)
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    |    +--- org.springframework:spring-context:5.0.8.RELEASE (*)
|    |    |    +--- org.springframework:spring-tx:5.0.8.RELEASE
|    |    |    |    +--- org.springframework:spring-beans:5.0.8.RELEASE (*)
|    |    |    |    \--- org.springframework:spring-core:5.0.8.RELEASE (*)
|    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.springframework:spring-tx:5.0.8.RELEASE (*)
|    |    +--- org.springframework:spring-oxm:5.0.8.RELEASE
|    |    |    +--- org.springframework:spring-beans:5.0.8.RELEASE (*)
|    |    |    \--- org.springframework:spring-core:5.0.8.RELEASE (*)
|    |    +--- org.springframework:spring-aop:5.0.8.RELEASE (*)
|    |    +--- org.springframework:spring-context-support:5.0.8.RELEASE
|    |    |    +--- org.springframework:spring-beans:5.0.8.RELEASE (*)
|    |    |    +--- org.springframework:spring-context:5.0.8.RELEASE (*)
|    |    |    \--- org.springframework:spring-core:5.0.8.RELEASE (*)
|    |    \--- org.slf4j:slf4j-api:1.7.25
|    \--- io.lettuce:lettuce-core:5.0.4.RELEASE
|         +--- io.projectreactor:reactor-core:3.1.6.RELEASE -> 3.1.7.RELEASE
|         |    \--- org.reactivestreams:reactive-streams:1.0.2
|         +--- io.netty:netty-common:4.1.24.Final -> 4.1.29.Final
|         +--- io.netty:netty-transport:4.1.24.Final -> 4.1.29.Final
|         |    +--- io.netty:netty-buffer:4.1.29.Final
|         |    |    \--- io.netty:netty-common:4.1.29.Final
|         |    \--- io.netty:netty-resolver:4.1.29.Final
|         |         \--- io.netty:netty-common:4.1.29.Final
|         \--- io.netty:netty-handler:4.1.24.Final -> 4.1.29.Final
|              +--- io.netty:netty-buffer:4.1.29.Final (*)
|              +--- io.netty:netty-transport:4.1.29.Final (*)
|              \--- io.netty:netty-codec:4.1.29.Final
|                   \--- io.netty:netty-transport:4.1.29.Final (*)
```

and dependencies increase for the same result  => https://github.com/DevWantJustHaveFun/spring-boot-session-redisson/pull/2/files

can you avoid that ?

**Comment by mrniko** [comment]
Libs updated to redisson-spring-data-20 and spring-boot-starter:2.0.5
