### ISSUE TITLE
[Scala] Unable to store objects that hold complex datatypes (that are not one of the dataypes of Redis)

### ISSUE THREAD

**Issue by jubins** [redisson/redisson#1641]
#### Expected behavior
Saving objects that hold String, Int, or methods within them does not work.

#### Actual behavior
I am trying to perform simple set and get operation on objects and following the Redisson [Object Holder](https://github.com/redisson/redisson/wiki/6.-distributed-objects#61-object-holder) example (similar to the way we do using redis-cli: `redis.set('mykey', 'myvalue')`). Simple examples like storing Int, Str key-values work fine, but setting class objects that have methods within them is not working. For example `redis.set('mykey', mymlengine)` does not work. mymlengine is .scala file that holds several methods (Please look at examples below that will help replicate). Could please help with this?

#### Steps to reproduce or test case
```
Scala Code:
def redisSetGet[T](key: String, value: T): T ={
    val config = new Config
    config.useSingleServer.setAddress("redis://localhost:6379")
    config.setCodec(new JsonJacksonCodec())
    val client = Redisson.create(config)
    println("Connected to Redis Server" + client)
    // Simple Object Get-Set
    var bucket_any :RBucket[T] = client.getBucket(key)
    bucket_any.set(value)
    println("Success: Value set on Redis server.")
    val valGot : T = bucket_any.get()
    println("Success: Value get on Redis server. valGot")
    valGot
  }

TEST CASE0: Saving String (one of the primitive datatypes Redis supports) <PASS>
redisSetGet("1", "222")

TEST CASE1: Saving object that holds string <FAIL>
redisSetGet("1", SObject[String]("81"))
ConsoleLog:
(Exception: ,org.redisson.client.RedisException: Unexpected exception while processing command)
om.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `SObject` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 21]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com

TEST CASE2: Saving class <FAIL>
final class SentenceDetector(modelFile:String) extends Serializable {
  import opennlp.tools.sentdetect.SentenceDetectorME
  val sdetector = try{
    val modelIn = new FileInputStream(modelFile)
    val model = new SentenceModel(modelIn)
    new SentenceDetectorME(model)
  }catch {
    case ex:Exception => throw ex
  }
  def sentDetect(s:String):Array[String] = {
    sdetector.sentDetect(s)
  }
}
val sd :SentenceDetector = new SentenceDetector("en-sent.bin")
val sd2 = redisSetGet("1", sd)
val sents2 = sd2.sentDetect("This is the sent 2. second sent 2")
println(sents2.toList)

Console Log:
8115 [redisson-netty-1-2] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0x364b40a9, L:/127.0.0.1:53460 - R:localhost/127.0.0.1:6379] message: $340
{"bitmap$0":false,"logger":{"underlying":{"@class":"org.slf4j.impl.SimpleLogger","debugEnabled":false,"errorEnabled":true,"infoEnabled":true,"name":"com.converseon.transformers.ItemTransformerCascade","traceEnabled":false,"warnEnabled":true}},"transformers":{"@class":"scala.collection.immutable.Nil$","empty":true,"traversableAgain":true}}

com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class java.lang.Object]: missing type id property '@class'
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 340]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:1638)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1217)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:300)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:164)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:105)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:193)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:712)

(Exception: ,org.redisson.client.RedisException: Unexpected exception while processing command)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```

#### Configuration
Redis server v=4.0.9 
Redisson client v=3.8.1
JDK version = 1.8
Code written in Scala (Scala version = 2.11.12)
OS: Linux Ubuntu 18.04

**Comment by jubins** [comment]
@mrniko can you please help on this?

**Comment by mrniko** [comment]
Basically this is encoder problem, not Redisson itself. I guess there are should be some solution regarding jackson and scala integration. Have you evaluated that question?
