### ISSUE TITLE
DNSNameResolver warnings in log using AWS Elasticache

### ISSUE THREAD

**Issue by gopkumar** [redisson/redisson#1646]
I see this warning with stack trace below in  our application log when using redisson version 3.8.1 going against AWS Elasticache 3.2.6.  Wondering what is the cause of this? We are using netty 4.1.29.Final

2018-09-24 19:19:17,885 WARN  [redisson-netty-1-43]  io.netty.resolver.dns.DnsNameResolver  - [id: 0xfe9383cc, L:/0.0.0.0:48778] Unexpected exception: 
io.netty.handler.codec.CorruptedFrameException: not a response
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.newResponse(DatagramDnsResponseDecoder.java:84)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:57)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:33)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Expected behavior
No warnings or exceptions
### Actual behavior
See above warning
### Steps to reproduce or test case
No particular steps to reproduce happens in normal course of execution
### Redis version
AWS Elasticache 3.2.6
### Redisson version
3.8.1
### Redisson configuration
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 60000
  retryAttempts: 10
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 4
  slaveConnectionPoolSize: 4
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 100
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 4
  dnsMonitoringInterval: 5000
  nodeAddresses:
  - "redis://xxxxxxxxxxxxxxx.cache.amazonaws.com:6379"
  scanInterval: 1000
  slaveSubscriptionConnectionPoolSize: 4
  slaveSubscriptionConnectionMinimumIdleSize: 1
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
referenceCodecProvider: !<org.redisson.codec.DefaultReferenceCodecProvider> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
keepPubSubOrder: true
addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}
useLinuxNativeEpoll: false

**Comment by mrniko** [comment]
It might be related to https://github.com/netty/netty/issues/8261

**Comment by normanmaurer** [comment]
@gopkumar @mrniko how often this happens ? Seems like we did not receive something we can parse

**Comment by mrniko** [comment]
Confirmed! Netty's bug https://github.com/netty/netty/issues/8261#issuecomment-427350547

**Comment by mrniko** [comment]
Done! Implemented workaround on Redisson side.

**Comment by x0a1b** [comment]
What version do we expect these changes to be published? I think this can be a minor release it badly effects production servers.

**Comment by mrniko** [comment]
@x0a1b fixed in 3.8.2 version

**Comment by mrniko** [comment]
Fixed
