### ISSUE TITLE
Unable to use anonymous runnable with scheduler

### ISSUE THREAD

**Issue by archmisha** [redisson/redisson#1656]
### Expected behavior
When submitting runnable as anonymous class we fail on NPE in getClassBody method
### Actual behavior
```
Caused by: java.lang.NullPointerException
	at java.io.FilterInputStream.available(FilterInputStream.java:167) ~[?:?]
	at org.redisson.RedissonExecutorService.getClassBody(RedissonExecutorService.java:387) ~[redisson-3.8.1.jar:?]
	at org.redisson.RedissonExecutorService.scheduleWithFixedDelayAsync(RedissonExecutorService.java:899) ~[redisson-3.8.1.jar:?]
	at org.redisson.RedissonExecutorService.scheduleWithFixedDelay(RedissonExecutorService.java:889) ~[redisson-3.8.1.jar:?]
```
### Steps to reproduce or test case
`redissonClient.getExecutorService(name).scheduleWithFixedDelay(() -> do something, 1, 1, TimeUnit.SECONDS)`
### Redisson version
3.8.1

**Comment by mrniko** [comment]
Done

**Comment by mrniko** [comment]
Done. Since the new version to run lambda cast it with additional bound like this: 

```java
redisson.getExecutorService("test").scheduleWithFixedDelay((Runnable & Serializable)() -> System.out.println("123"), 1, 1, TimeUnit.SECONDS);
```
