### ISSUE TITLE
is not active! error while using pingConnectionInterval flag

### ISSUE THREAD

**Issue by archmisha** [redisson/redisson#1664]
Since started to use the parameter pingConnectionInterval after a while the service being up we start getting the following errors on all redis operations:
`RedisConnection@1983198386 [redisClient=[addr=redis://100.65.5.107:6379], channel=[id: 0x66c3b445, L:/172.17.0.6:58200 ! R:100.65.5.107/100.65.5.107:6379]] is not active!
org.redisson.client.RedisConnectionException: RedisConnection@1983198386 [redisClient=[addr=redis://100.65.5.107:6379], channel=[id: 0x66c3b445, L:/172.17.0.6:58200 ! R:100.65.5.107/100.65.5.107:6379]] is not active!
at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:323) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.pool.ConnectionPool.connectTo(ConnectionPool.java:253) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.pool.ConnectionPool.access$300(ConnectionPool.java:53) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.pool.ConnectionPool$3.run(ConnectionPool.java:214) ~[redisson-3.8.1.jar:?]
at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:142) ~[redisson-3.8.1.jar:?]
at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:125) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.ClientConnectionsEntry.acquireConnection(ClientConnectionsEntry.java:134) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:161) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:224) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:41) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:450) ~[redisson-3.8.1.jar:?]
at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:543) ~[redisson-3.8.1.jar:?]
at org.redisson.command.CommandAsyncService.getConnection(CommandAsyncService.java:681) ~[redisson-3.8.1.jar:?]
at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:536) ~[redisson-3.8.1.jar:?]
at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:625) ~[redisson-3.8.1.jar:?]
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
at java.lang.Thread.run(Thread.java:844) [?:?]
`
Eventually leading to messages of the type:
`o.r.c.p.SlaveConnectionPool - slave 100.65.5.222/100.65.5.222:6379 has been disconnected after 60000 ms interval since moment of the first failed connection`

The only way to resolve this is to restart the server.
Redis at this time is fully functional as all other servers are working fine

### Steps to reproduce or test case
Our redisson configuration:
Sentinel cluster with 4 nodes
masterConnectionPoolMinSize=16
masterConnectionPoolMaxSize=64
slaveConnectionPoolMinSize=16
slaveConnectionPoolMaxSize=64
timeout=3000
keepAlive=false
idleConnectionTimeout=10000
connectTimeout=10000
pingConnectionInterval=1000
pingTimeout=1000

### Redis version
3.0.7
### Redisson version
3.8.1

**Comment by archmisha** [comment]
Today we had the same exception in production without the usage of the pingConnectionInterval flag
So seems the issue is not directly related to that flag.
What is more important to this case that this time our servers were up and running without restart for a longer period of time that usually

**Comment by archmisha** [comment]
Thanks!
Which version number is it going to be in?

**Comment by mrniko** [comment]
2.14.0 / 3.9.0

**Comment by liyong6351** [comment]
@archmisha Hello, my friend, I have ever happend to get the Exception, but when I restart the redis and redisson then the exception disappeared,Now I want to reappear the exception，but find it's hard to do.so I asked u for advise how to reappeared the exception？

**Comment by MR-gwh** [comment]
> @archmisha Hello, my friend, I have ever happend to get the Exception, but when I restart the redis and redisson then the exception disappeared,Now I want to reappear the exception，but find it's hard to do.so I asked u for advise how to reappeared the exception？

hello,can you reappear now?I have the same exception
