### ISSUE TITLE
RBlockingQueue doesn't retrieve element

### ISSUE THREAD

**Issue by vestverg** [redisson/redisson#1665]
### Expected behavior
.takeAsync().whenComplete will retrivehead of the qeueu and evaluate it
### Actual behavior
we are not retrieve element from qeueu, but in redis I can see them.
But if offer from same service it's work
### Steps to reproduce or test case
I have two microservices frirst retrive elements with RedissonQueueBundle<V>
Second just offer element directly
queue.offer(someObject)
```java
//wrapper for RQueue to make operation over it
public class RedissonQueueBundle<V> implements QueueBundle<V> {
    private RQueue<V> rQueue;
    private final Set<Consumer<V>> handlers;
    private final ScheduledExecutorService executorService;
    private final String queueName;
    private RDelayedQueue<V> rDelayedQueue;

    public RedissonQueueBundle(RedissonClient redissonClient, String queueName, ScheduledExecutorService executorService) {
        this.rQueue = redissonClient.<V>getBlockingQueue(queueName);
        this.handlers = ConcurrentHashMap.newKeySet();
        this.executorService = executorService;
        this.queueName = queueName;
        this.rDelayedQueue = redissonClient.getDelayedQueue(rQueue);
    }


    @PostConstruct
    public void init() {
        executorService.submit(this::fetch);
    }

    @Override
    public void offer(V element) {
        rQueue.offer(element);
    }
    /**
     * Inserts element into this queue with
     * specified transfer delay to destination queue.
     *
     * @param element  the element to add
     * @param delay    for transition
     * @param timeUnit for delay
     */

    @Override
    public void offer(final V element, final long delay, final TimeUnit timeUnit) {
        LOGGER.info("Offer value {} with delay {} {}", element, delay, timeUnit);
        rDelayedQueue.offer(element, delay, timeUnit);
    }

    @Override
    public void register(Consumer<V> handler) {
        if (handler == null){
            return;
        }
        LOGGER.info("Registering handler {}", handler.getClass().getCanonicalName());
        handlers.add(handler);
    }

    public boolean removeIf(Predicate<? super V> filter) {
        return rDelayedQueue.removeIf(filter);
    }

    private void handle(V val) {
        LOGGER.info("Got value {} from {} for {} consumers", val, queueName, handlers.size());
        if (val != null) {
            handlers.forEach(handler -> handler.accept(val));
        }
    }

    private void fetch() {
        if (!handlers.isEmpty()) {
            ((RBlockingQueue<V>) rQueue).takeAsync().whenComplete((val, ex) -> {
                try {
                    if (ex == null) {
                        this.handle(val);
                        executorService.execute(this::fetch);
                    } else {
                        LOGGER.warn("", ex);
                    }
                } catch (Exception exx) {
                    LOGGER.error("", exx);
                }
            });
        } else {
            LOGGER.warn("Handlers set for queue {} is empty", queueName);
            executorService.schedule(this::fetch, 1, TimeUnit.SECONDS);
        }
    }

}

```
### Redis version
3.0.3
### Redisson version
3.5.0
### Redisson configuration
```java
@Configuration
public class RedissonConfiguration {
    private static final int MAX_CONNECTION_RETRY = 5;
    private final Config config = new Config();
    private final String connectionDescription;

    RedissonConfiguration() {

        String master = null;
        Set<String> sentinels = null;
        try {
            master = PropertiesRetriever.getRedisMaster();
            sentinels = PropertiesRetriever.getRedisSentinels();
        } catch (MissingResourceException ex) { /*_*/ }

        ObjectMapper objectMapper = new JacksonObjectMappers().getDefaultObjectMapper();
        config.setCodec(new JsonJacksonCodec(objectMapper));
        if (sentinels != null && !sentinels.isEmpty() && StringUtils.isNotBlank(master) && !"disabled".equalsIgnoreCase(master)) {
            String[] addresses = sentinels.stream().map(sentinel -> "redis://" + sentinel).toArray(String[]::new);
            config.useSentinelServers()
                    .setMasterName(master)
                    .setDatabase(PropertiesRetriever.getRedisDBData())
                    .setMasterConnectionMinimumIdleSize(5)
                    .setSlaveConnectionMinimumIdleSize(5)
                    .addSentinelAddress(addresses);
            connectionDescription = "Sentinels " + master + "/" + Arrays.asList(addresses);
        } else {
            String redisAddress = PropertiesRetriever.getRedisDataHost() + ":" + PropertiesRetriever.getRedisDataPort();
            config.useSingleServer()
                    .setAddress(redisAddress)
                    .setDatabase(PropertiesRetriever.getRedisDBData());
            connectionDescription = redisAddress;
        }
    }

    @Bean
    public RedissonClient redissonClient() {
        RuntimeException reThrow = null;
        for (int i = 0; i < MAX_CONNECTION_RETRY; i++) {
            try {
                return Redisson.create(config);
            } catch (RedisConnectionException ex) {
                LOGGER.warn("Retry {} of {} FAIL", i + 1, MAX_CONNECTION_RETRY);
                              reThrow = ex;
            }
        }
        LOGGER.error("", reThrow);
        throw reThrow;
    }
}
```

**Comment by vestverg** [comment]
I have figured out why it's not working.

The problem that two classes(queue elements) with the same name in different packages. So when we receive new element from the queue it's trying to create an object based on @class field, but in current service, this is class not exist and fail silently with writing WARN log. It's will be useful to ignore @class field or omit it, and deserialize with the target class with a generic parameter of the created queue or change level from WARN to ERROR when we can't deserialize an object.

**Comment by vestverg** [comment]
I can't provide at the moment test code, but if it helps stack trace
```
com.loyaltyplant.server.services.register.entities.ChangeAccountEvent' as a subtype of [simple type, class java.lang.Object]: no such class found
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 11]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1628)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1186)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:51)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:42)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:193)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:712)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:77)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:259)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:289)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:278)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:103)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by mrniko** [comment]
I suggest you to use jackson annotations to map object hierarhy properly in Jackson. More info here https://www.baeldung.com/jackson-inheritance

As option you could switch to FstCodec which is default by now.
