### ISSUE TITLE
Deadlock while obtaining lock

### ISSUE THREAD

**Issue by Sairamiv** [redisson/redisson#1667]
Thread gets stuck while obtaining lock. 

prio=5 os_prio=0 tid=0x00007fa1201d1000 nid=0x7f5a in Object.wait() [0x00007fa0bedd3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
	- locked <0x00000006052c40b0> (a io.netty.util.concurrent.DefaultPromise)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:218)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:32)
	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:112)
	at org.redisson.RedissonLock.lock(RedissonLock.java:86)

The same lock name was likely concurrently obtained and held by another thread possibly on another jvm, and then released.

Observed intermittently.

Redisson Version used : 3.4.3

**Comment by mrniko** [comment]
Is there any way to reproduce this?

Here is my concurrency test
https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/RedissonLockHeavyTest.java

**Comment by Sairamiv** [comment]
Couldn't reproduce but observed the above situation when we got below exception, checked the memory utilization of reddis server, but memory utilization was normal.

org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [api] in context with path [] threw exception [Request processing failed; nested exception is org.redisson.client.RedisConnectionException: Can't aquire connection from pool! [[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=239, freeConnectionsCounter=246, freezed=true, freezeReason=RECONNECT, client=x, nodeType=MASTER, failedAttempts=6]]] with root cause
org.redisson.client.RedisConnectionException: Can't aquire connection from pool! [[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=239, freeConnectionsCounter=246, freezed=true, freezeReason=RECONNECT, client=x, nodeType=MASTER, failedAttempts=6]]
        at org.redisson.misc.ConnectionPool.get(ConnectionPool.java:124)
        at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:184)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:563)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:352)
        at org.redisson.command.CommandAsyncService$5.run(CommandAsyncService.java:401)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
Could you share your code with lock object usage?
