### ISSUE TITLE
NPE in CommandDecoder

### ISSUE THREAD

**Issue by lbernollin** [redisson/redisson#1677]
### Expected behavior
It should get the entry save into Reddis
### Actual behavior
I got the following exception :
`2018-10-15 14:11:24,121 ERROR [stderr] (redisson-3-6) Exception in thread "redisson-3-6" org.redisson.client.RedisException: Unexpected exception while processing command
2018-10-15 14:11:24,121 ERROR [stderr] (redisson-3-6)   at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:378)
2018-10-15 14:11:24,121 ERROR [stderr] (redisson-3-6)   at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:182)
2018-10-15 14:11:24,121 ERROR [stderr] (redisson-3-6)   at org.redisson.RedissonObject.get(RedissonObject.java:76)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at org.redisson.RedissonMap.readAllEntrySet(RedissonMap.java:430)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at org.redisson.spring.session.RedissonSessionRepository$RedissonSession.load(RedissonSessionRepository.java:97)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:264)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:53)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at org.redisson.PubSubPatternMessageListener.onPatternMessage(PubSubPatternMessageListener.java:81)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:83)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:183)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2018-10-15 14:11:24,122 ERROR [stderr] (redisson-3-6)   at java.lang.Thread.run(Thread.java:748)
2018-10-15 14:11:24,136 ERROR [stderr] (redisson-3-6) Caused by: java.lang.NullPointerException
2018-10-15 14:11:24,136 ERROR [stderr] (redisson-3-6)   at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:476)
2018-10-15 14:11:24,136 ERROR [stderr] (redisson-3-6)   at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:348)
2018-10-15 14:11:24,136 ERROR [stderr] (redisson-3-6)   at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:128)
2018-10-15 14:11:24,136 ERROR [stderr] (redisson-3-6)   at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018-10-15 14:11:24,137 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018-10-15 14:11:24,138 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018-10-15 14:11:24,139 ERROR [stderr] (redisson-3-6)   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
2018-10-15 14:11:24,139 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018-10-15 14:11:24,139 ERROR [stderr] (redisson-3-6)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018-10-15 14:11:24,139 ERROR [stderr] (redisson-3-6)   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
2018-10-15 14:11:24,139 ERROR [stderr] (redisson-3-6)   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2018-10-15 14:11:24,140 ERROR [stderr] (redisson-3-6)   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
2018-10-15 14:11:24,140 ERROR [stderr] (redisson-3-6)   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
2018-10-15 14:11:24,140 ERROR [stderr] (redisson-3-6)   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
2018-10-15 14:11:24,140 ERROR [stderr] (redisson-3-6)   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
2018-10-15 14:11:24,140 ERROR [stderr] (redisson-3-6)   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
2018-10-15 14:11:24,140 ERROR [stderr] (redisson-3-6)   ... 2 more`

### Steps to reproduce or test case
It is very hard to reproduce. It does not appears each time. I only got this error during a load test. It is very random.
We are in Spring 5 with spring-session-core in 2.0.5.RELEASE.
Redis is used to store the httpSession data.
Here is the redis data :
` 1) "\"passwordLess\""
 2) "\"true\""
 3) "\"SPRING_SECURITY_CONTEXT\""
 4) "{\"@class\":\"org.springframework.security.core.context.SecurityContextImpl\",\"authentication\":{\"@class\":\"ctx.security.CustomUsernamePasswordAuthenticationToken\",\"authenticated\":true,\"details\":{\"@class\":\"org.springframework.security.web.authentication.WebAuthenticationDetails\",\"remoteAddress\":\"88.190.12.13\",\"sessionId\":\"d6266c39-ac4d-4a2b-b3b5-995f1c341b58\"},\"principal\":{\"@class\":\"ctx.security.model.OnAirUserSecurity\",\"email\":\"9612472228_72@mailinator.com\",\"grantedAuths\":[\"java.util.ArrayList\",[{\"@class\":\"org.springframework.security.core.authority.SimpleGrantedAuthority\",\"authority\":\"ROLE_USER\"}]],\"id\":23178686,\"password\":\"$2a$10$iK2ijRQvMMxOXrzVAtLOQelepT1.ry.FE7n8jxO4D7xMkkurHibBO\"}}}"
 5) "\"session:maxInactiveInterval\""
 6) "[\"java.lang.Long\",1800]"
 7) "\"session:creationTime\""
 8) "[\"java.lang.Long\",1539612489361]"
 9) "\"passenger_context\""
10) "{\"@class\":\"ctx.model.PassengerContext\",\"carrierCode\":\"TEST\",\"deviceIp\":\"10.0.0.0\",\"email\":\"1539612472228_72@mailinator.com\",\"flightId\":1926722,\"locale\":\"en\",\"platform\":\"EKPAC\",\"sessionId\":\"d6266c39-ac4d-4a2b-b3b5-995f1c341b58\",\"theme\":\"TEST\",\"userAgent\":\"Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0\",\"userId\":23178686,\"vesselCode\":\"TEST4\"}"
11) "\"selected_product\""
12) "{\"@class\":\"ice.client.backend.dto.resource.ProductResource\",\"allFlight\":true,\"byteUsageLimit\":26214400,\"carrier\":\"TEST\",\"createdAt\":\"2018-10-12T07:57:51.743871Z\",\"disabled\":false,\"discountable\":true,\"displayOrder\":0,\"displayedByteUsageLimit\":26214400,\"hideFromMenu\":false,\"id\":628,\"initial\":true,\"isAllFlight\":true,\"isInitial\":true,\"isRenewal\":true,\"links\":[\"java.util.ArrayList\",[{\"@class\":\"org.springframework.hateoas.Link\",\"href\":\"http://ppe-core-vip-001.pod.sitaonair.aero/ice-back-end/api/v1/products/LT_TEST_FL_25MB_FREE\",\"rel\":\"self\"}]],\"maxLifeTime\":90,\"meteringType\":\"FLIGHT_LIMITED_VOLUME\",\"pausable\":true,\"price\":0.0,\"productCode\":\"LT_TEST_FL_25MB_FREE\",\"productTranslations\":[\"java.util.ArrayList\",[]],\"productType\":\"REGULAR\",\"renewal\":true,\"speedLimit\":\"ILLIMITED\",\"timeUsageLimit\":0,\"updatedAt\":\"2018-10-12T07:57:51.743871Z\",\"upgradable\":false}"
13) "\"captcha\""
14) "\"false\""
15) "\"org.springframework.security.web.csrf.HttpSessionCsrfTokenRepository.CSRF_TOKEN\""
16) "{\"@class\":\"org.springframework.security.web.csrf.DefaultCsrfToken\",\"headerName\":\"X-CSRF-TOKEN\",\"parameterName\":\"_csrf\",\"token\":\"3e3c0d98-3e0a-428e-897a-7078f4bbc949\"}"
17) "\"session:lastAccessedTime\""
18) "[\"java.lang.Long\",1539612775785]"
`

i also got NPE with this message 
`[2018-10-15 12:17:25,026] [ERROR] [o.r.c.h.CommandDecoder] - Unable to decode data. channel: [id: 0x746bf880, L:/127.17.0.5:44662 - R:88.101.47.45/88.101.47.44:6399] message: *8$26"session:lastAccessedTime"$32["java.lang.Long",1539605843679]$22"session:creationTime"$32["java.lang.Long",1539605843676]$19"passenger_context"$272{"@class":"aero.onair.ctx.model.PassengerContext","carrierCode":"PAL","deviceIp":"10.0.0.17","flightId":1926263,"locale":"en","platform":"EKPAC","theme":"PAL","userAgent":"Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0","userId":0,"vesselCode":"PAL14"}$29"session:maxInactiveInterval"$23["java.lang.Long",1800]*0*0
java.lang.NullPointerException: null
`
### Redisson version
3.8.2. It is also appear with the 3.7.5
### Redisson configuration
`
@Configuration
@EnableRedissonHttpSession
public class RedissonConfig implements BeanClassLoaderAware
{
    @Autowired
    private ConfigurationWrapper configuration;

    private static final int CONNECTION_TIMEOUT = 3000;
    private static final int TIMEOUT = 10000;
    private static final int THREAD_NUMBER = 4;

    private ClassLoader loader;

    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient()
    {
         return Redisson.create(sentinelServers());
    }

    private Config baseConfig()
    {
        return new Config()
                .setNettyThreads(THREAD_NUMBER)
                .setThreads(THREAD_NUMBER)
                .setCodec(new JsonJacksonCodec(mapper()));
    }

    private Config sentinelServers()
    {
        final Config config = baseConfig();
        config.useSentinelServers()
                .setConnectTimeout(CONNECTION_TIMEOUT)
                .setTimeout(TIMEOUT)
                .addSentinelAddress(split(configuration.getAddresses(), ", "))
                .setMasterName(configuration.getMasterName())
                .setPassword(configuration.getPassword());
        return config;
    }

    @Override
    public void setBeanClassLoader(final ClassLoader classLoader)
    {
        this.loader = classLoader;
    }

    private ObjectMapper mapper()
    {
        final ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        mapper.registerModules(SecurityJackson2Modules.getModules(this.loader));
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
        mapper.setSerializationInclusion(Include.NON_NULL);
        mapper.addMixIn(Throwable.class, JsonJacksonCodec.ThrowableMixIn.class);
        mapper.findAndRegisterModules();
        return mapper;
    }
}
`

**Comment by lying1234** [comment]
We had the similar NPE issue on CommandDecoder. We're using Redisson 3.6.5.

Caused by: java.lang.NullPointerException
        at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:421)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:315)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        ... 28 more

**Comment by mrniko** [comment]
@lbernollin 

Could you show full NPE stacktrace?

**Comment by mrniko** [comment]
Fixed! Thanks for report
