### ISSUE TITLE
RedisException caused by NPE

### ISSUE THREAD

**Issue by lying1234** [redisson/redisson#1681]
We are using redisson session manager in our application, and got RedisException sometimes due to NPE. 
### Expected behavior
No exception should be thrown.
### Actual behavior
Error found randomly, and no more information where NPE was from.
Stack trace:
Unexpected exception while processing command org.redisson.client.RedisException: Unexpected exception while processing command
        at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:339)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:170)
        at org.redisson.RedissonObject.get(RedissonObject.java:74)
        at org.redisson.RedissonMap.readAllMap(RedissonMap.java:405)
        at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:131)
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2913)
        at org.apache.catalina.connector.Request.getSession(Request.java:2310)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
        at org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper.saveContext(HttpSessionSecurityContextRepository.java:332)
        at org.springframework.security.web.context.SaveContextOnUpdateOrErrorResponseWrapper.onResponseCommitted(SaveContextOnUpdateOrErrorResponseWrapper.java:85)
        at org.springframework.security.web.context.OnCommittedResponseWrapper.doOnResponseCommitted(OnCommittedResponseWrapper.java:208)
        at org.springframework.security.web.context.OnCommittedResponseWrapper.sendRedirect(OnCommittedResponseWrapper.java:114)
        at org.apache.struts2.dispatcher.ServletRedirectResult.sendRedirect(ServletRedirectResult.java:257)
        at org.apache.struts2.dispatcher.ServletRedirectResult.doExecute(ServletRedirectResult.java:229)
        at org.apache.struts2.dispatcher.StrutsResultSupport.execute(StrutsResultSupport.java:193)
        at org.apache.struts2.dispatcher.ServletRedirectResult.execute(ServletRedirectResult.java:164)
.....
.....
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.ajp.AjpNioProcessor.process(AjpNioProcessor.java:175)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException

### Steps to reproduce or test case
Sometimes error will be found when running:
request.getSession(false);
after the session was removed by:
request.getSession(true).invalidate();

### Redis version
4.0.6
### Redisson version
3.6.5
### Redisson configuration
{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":6000,
      "retryAttempts":6,
      "retryInterval":3000,
      "failedSlaveReconnectionInterval":3000,
      "failedSlaveCheckInterval":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "slaveConnectionMinimumIdleSize":10,
      "slaveConnectionPoolSize":610,
      "masterConnectionMinimumIdleSize":10,
      "masterConnectionPoolSize":610,
      "readMode":"SLAVE",
      "subscriptionMode":"SLAVE",
      "nodeAddresses":[
        "redis://RedisServer1:6379",
        "redis://RedisServer2:6379",
        "redis://RedisServer3:6379",
        "redis://RedisServer4:6379",
        "redis://RedisServer5:6379", 
        "redis://RedisServer6:6379" 
      ],
      "scanInterval":1000
   },
   "threads":0,
   "nettyThreads": 0,
   "codec":!<org.redisson.codec.FstCodec> {},
   "useLinuxNativeEpoll":false
}

**Comment by lying1234** [comment]
Also, some errors shows:
Caused by: java.lang.NullPointerException
        at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:421)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:315)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

**Comment by lying1234** [comment]
NPE was thrown because both decoder and parts are null in selectDecoder. Code is not so robust to take care of this case. We're not sure why getReplayDecoder() returns null. Can anybody help? 

protected Decoder<Object> selectDecoder(CommandData<Object, Object> data, List<Object> parts) {
        .....
        Decoder<Object> decoder = data.getCommand().getReplayDecoder();
        .....
        if (decoder == null) {
            if (data.getCommand().getOutParamType() == ValueType.MAP) {
                if (parts.size() % 2 != 0) {
                    decoder = data.getCodec().getMapValueDecoder();
                } else {
                    decoder = data.getCodec().getMapKeyDecoder();
                }
            } ....
            .......
        }
        return decoder;
    }
