### ISSUE TITLE
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。

### ISSUE THREAD

**Issue by hulvyou** [redisson/redisson#1682]
<dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson-spring-boot-starter</artifactId>
      <version>3.8.2</version>
    </dependency>
spring:
  redis:
    database: 0
    timeout: 60000
    sentinel:
      master: redisMaster
      nodes: 
        - 10.250.100.211:27000
        - 10.250.100.211:27001
        - 10.250.100.211:27002
2018-10-18 19:22:36.396 [redisson-netty-4-3] ERROR org.redisson.client.handler.CommandsQueue - Exception occured. Channel: [id: 0xdea6dc47, L:/10.250.100.101:57379 - R:10.250.100.211/10.250.100.211:7001]
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
sos !!!
Why is there such an error?

**Comment by jackygurui** [comment]
这不是一个客户端的问题。

**Comment by linmengmeng-1314** [comment]
留名，第一次用redisson，也遇到这个异常了，搜了半天没找到解决办法
