### ISSUE TITLE
Slowness in using Redisson Session Manager. Same is working much faster with Oracle Coherence session manager.

### ISSUE THREAD

**Issue by srkrmandal** [redisson/redisson#1689]
Currently we are doing a load test of around 600 users hitting the application every 10 minutes for two hours. There we can see around 1095 threads created at any point of time and at most of the time there are 919 threads being runnable state acquiring 60 % CPU utilization and there are 152 threads waiting on condition. And all the waiting threads are waiting on at sun.nio.ch.EPollArrayWrapper.epollWait. the exception is given below in full detail.  Total CPU utilization is around 90 percent which is a concern.

We are using Redisson Session Manager Open source version 3.8.0 with redis server 3.2.  
Also, tomcat version 8.5.31 is used with JDK 1.8.161

### Expected behavior
Same modules when deployed in weblogic server along with coherence session manager is performing much faster and CPU utlization is around 45 percent.

### Actual behavior

When same modules are deployed in tomcat along with redisson session manager there are 90 percent CPU utilization and waiting threads on redisson netty

Waiting threads because of below reason::

We are having 85%  (all redisson-netty) threads at runnable status. And, it is taking more than 60% of CPU cycle time (as per Newrelic thread profiler) on tomcat. It doesn’t seem to be caused by any application code.
 
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
- locked [0x00000007187d7be8] (a io.netty.channel.nio.SelectedSelectionKeySet)
- locked [0x00000007187d7c78] (a java.util.Collections$UnmodifiableSet)
- locked [0x000000071868fb00] (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:737)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:392)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(Redefined)
at java.lang.Thread.run(Thread.java:748)

----------------------------------------
Findings
1> there are no latency observed in Redis server which is more than 10 ms
2> showlog command shows only 10 commands took more than 10 and less than 30 ms timeframe

---------------------------------------
### Redis version 
3.2

### Redisson version
3.8.0

### Redisson configuration
In apache tomcat server ( 3.5.1) There are 16 modules deployed. All the modules share the same session 
and session manger is set at each module context level but all the sessionmanager share the same sesison cookie via JSESSIONID object and same sharedsessionpath.
{
   "sentinelServersConfig":{
      "idleConnectionTimeout":60000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":10000,
      "retryAttempts":3,
      "retryInterval":2000,
      "failedSlaveReconnectionInterval":3000,
      "failedSlaveCheckInterval":60000,
      "password":null,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "slaveConnectionMinimumIdleSize":32,
      "slaveConnectionPoolSize":100,
      "masterConnectionMinimumIdleSize":32,
      "masterConnectionPoolSize":100,
      "readMode":"MASTER_SLAVE",
      "sentinelAddresses":[
         "redis://10.54.24.XXX:26379",
         "redis://10.54.24.ZZZ:26379",
         "redis://10.54.24.YYY:26379"
      ],
      "masterName":"mymaster",
      "database":0
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
   "class":"org.redisson.codec.SerializationCodec"
   }
}

**Comment by srkrmandal** [comment]
Also, We had observed that max latency from redis is in microseconds (10 - 100 microseconds) however at tomcat side we are seeing 10-12 ms being the total response time for each session.setattribute and getAttribute call. Since there are lot of session modifications done in a single transaction, the overall time taken for a complete transaction at tomcat level is more than 5 seconds.  Here is the latest configurations we have tried which gave us better response times however that is still not in proper range.


{
"sentinelServersConfig":{
"idleConnectionTimeout":60000,
"pingTimeout":1000,
"connectTimeout":5000,
"timeout":1000,
"retryAttempts":1,
"retryInterval":2000,
"failedSlaveReconnectionInterval":5000,
"failedSlaveCheckInterval":60000,
"password":null,
"clientName":null,
"loadBalancer":{
"class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
},
"slaveConnectionMinimumIdleSize":16,
"slaveConnectionPoolSize":16,
"masterConnectionMinimumIdleSize":16,
"masterConnectionPoolSize":16,
"readMode":"SLAVE",
"sentinelAddresses":[
"redis://10.54.24.XXX:26379",
"redis://10.54.24.ZZZ:26379",
"redis://10.54.24.YYY:26379"
],
"masterName":"mymaster",
"database":0
},
"threads":3,
"nettyThreads":3,
"codec":{
"class":"org.redisson.codec.SerializationCodec"
}
}

**Comment by srkrmandal** [comment]
we are observing slowness in session.getAttribute invocation through Redisson Open Source Client.

**Error Log observed:** 
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:161)
at org.redisson.RedissonObject.get(RedissonObject.java:76)
at org.redisson.RedissonMap.get(RedissonMap.java:249)
at org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:77)
at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:103)
at com.rci.web.common.util.SessionKeysUtils.getCustomerBean(SessionKeysUtils.java:47) 


If redis is returning data in micro seconds, then why are we observing 10-12 milliseconds (at times even 100 ms) response time at tomcat jvm level using redisson.

Please let us know any twig in any of the parameters in redission_config.json file as attached above.
