### ISSUE TITLE
Command execution timeout for redisson on lambda with aws elasticache

### ISSUE THREAD

**Issue by matteoluzzi** [redisson/redisson#1694]
I am running redisson in AWS Lambda functions connecting to a Elasticache redis cluster. The worflow of each lambda consist in 3 batch requests on average (2 read and 1 write).
### Expected behavior
No command execution timeout errors
### Actual behavior
Every once in a while redisson returns command execution timeout while fetching the cluster status through the command `CLUSTER_NODES`. Stacktrace is:
```
   ERROR ClusterConnectionManager:383 - Can't execute CLUSTER_NODES with /10.108.113.3:6379
   org.redisson.client.RedisTimeoutException: Command execution timeout for /10.108.113.3:6379
   at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212) [redisson-3.6.5.jar:?]
   at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.22.Final.jar:4.1.22.Final]
   at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-common-4.1.22.Final.jar:4.1.22.Final]
   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.22.Final.jar:4.1.22.Final]
   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.22.Final.jar:4.1.22.Final]
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.22.Final.jar:4.1.22.Final]
   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.22.Final.jar:4.1.22.Final]
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.22.Final.jar:4.1.22.Final]
   at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

   WARN CommandDecoder:392 - response has been skipped due to timeout! channel: [id: 0x33ab875c, L:/169.254.76.21:40804 - R:/10.108.113.3:6379], command: (CLUSTER NODES), params: [], result: [ClusterNodeInfo [nodeId=2593fecf77f003f46743b1acc1cd08b136bbc04a, address=redis://10.108.37.191:6379, flags=[MASTER], slaveOf=null, slotRanges=[[0-3276]]], ClusterNodeInfo [nodeId=1a9e1046]
```
Worth mentioning that this happens with few concurrent execution at the time and I cannot understand why this is happening. 

### Redis version
3.2.10, cluster mode (5 shards)
### Redisson version
3.6.5
### Redisson configuration
Default cluster configuration apart for:
* transportMode=NIO
* readMode=MASTER_SLAVE
* retryAttempts=1

**Comment by FranckyBoyX** [comment]
We're having the exact same issue using Elasticache with Redis 5.0.0.

Cluster made, 2 replicas, 2 shards.

It also happens on other commands like locking.
@matteoluzzi have you found a solution yet ?
