### ISSUE TITLE
RedisException: ERR max number of clients reached. channel:

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1708]
```java
ERROR [2018-10-27 18:08:43,504] [redisson-netty-4-1] ClusterConnectionManager: Can't add slave: redis://100.101.26.91:6379
! org.redisson.client.RedisException: ERR max number of clients reached. channel: [id: 0x03f718df, L:/100.111.217.190:53733 - R:100.101.26.91/100.101.26.91:6379] command: (READONLY), params: []
! at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:331) ~[app.jar:1.0.25]
! at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:128) ~[app.jar:1.0.25]
! at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108) ~[app.jar:1.0.25]
! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[app.jar:1.0.25]
! at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[app.jar:1.0.25]
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[app.jar:1.0.25]
! at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[app.jar:1.0.25]
! at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[app.jar:1.0.25]
! at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[app.jar:1.0.25]
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[app.jar:1.0.25]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[app.jar:1.0.25]
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[app.jar:1.0.25]
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[app.jar:1.0.25]
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [app.jar:1.0.25]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [app.jar:1.0.25]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [app.jar:1.0.25]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [app.jar:1.0.25]
! ... 3 common frames omitted
! Causing: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 100.101.26.91/100.101.26.91:6379
! at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:138) ~[app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [app.jar:1.0.25]
! at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:83) [app.jar:1.0.25]
! at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:301) [app.jar:1.0.25]
! at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:54) [app.jar:1.0.25]
! at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:266) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [app.jar:1.0.25]
! at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [app.jar:1.0.25]
! at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:83) [app.jar:1.0.25]
! at org.redisson.client.RedisClient$2$1$1$1.run(RedisClient.java:240) [app.jar:1.0.25]
! at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [app.jar:1.0.25]
! at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [app.jar:1.0.25]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [app.jar:1.0.25]
! at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [app.jar:1.0.25]
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [app.jar:1.0.25]
! at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]```

I have been using redisson in my application, since last couple of weeks, I have been getting this error. Kindly help me root cause this issue.

**Comment by mrniko** [comment]
Check `maxclients` setting in redis.conf and amount of total connections to this node

**Comment by arpit728** [comment]
I have not provided value for `maxClients`  default is being used which I guess is 10000. 
`connected_clients:72`

**Comment by arpit728** [comment]
@mrniko 
As discussed on gitter, I have updated to the latest version of Redisson, but this issue still persists. I think [this](https://github.com/redisson/redisson/issues/1623) is the different issue.
