### ISSUE TITLE
Exception occurred when redis cluster master-slave failover

### ISSUE THREAD

**Issue by JunjianS** [redisson/redisson#1718]
redis version : 3.2.1
redisson: 3.5.4
jdk:1.8
redis cluster : 3 master, 3 slave

Below exception occurred until application restarts when redis cluster master-slave failover .

[ERROR] 2018-11-03 17:30:21.445 [http-nio-8080-exec-33] AppController: In getAddress Exception
org.redisson.client.RedisConnectionException: Can't aquire connection to [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@794138c3, freeConnectionsAmount=0, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@6b32b3e8, freezed=true, freezeReason=MANAGER, client=[addr=/172.1.1.:16379], nodeType=SLAVE, failedAttempts=2]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:206)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.getConnection(LoadBalancerManager.java:197)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:433)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:744)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:504)
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:585)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by JunjianS** [comment]
could anybody please take a look at this issue ?

**Comment by mrniko** [comment]
Have you solved the issue?
