### ISSUE TITLE
RedisResponseTimeoutException at getLockedLock for read operation in "replicatedServersConfig"

### ISSUE THREAD

**Issue by stkggit** [redisson/redisson#1723]
Hi,
 I'm using jcache  implementation and using AWS Redis servers in "replicatedServersConfig", i'm getting response time out exception at "getLockedLock" method. raised another [issue ](https://github.com/redisson/redisson/issues/1722) related to jcache.

Please do the needful.

javax.cache.CacheException: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (5000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, {test_ApplicationFormat}:WSFHEHaApjlCL5QG/Ng/dg:key, 30000, a225e312-e347-40ad-8c37-d4c0d9ef9800:120] channel: [id: 0x2519e10d, L:/172.17.0.3:49640 - R:***.**.cache.amazonaws.com/10.0.0.181:6379]
	at org.redisson.jcache.JCache.getLockedLock(JCache.java:746)
	at org.redisson.jcache.JCache.get(JCache.java:177)
	at CacheRedisCacheRedissonImpl.get(CacheRedisCacheRedissonImpl.java:57)
	at ApplicationFormatServiceImpl.getApplicationFormatCache(ApplicationFormatServiceImpl.java:500)
	at ApplicationFormatServiceImpl.getApplicationFormatCache(ApplicationFormatServiceImpl.java:309)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy102.getApplicationFormatCache(Unknown Source)
	at controllers.CCPlayUtils.getApplicationFormatCache(CCPlayUtils.java:102)
	at controllers.CCPlayApplication.getResponseAsJson(CCPlayApplication.java:127)
	at controllers.CCLocaleController$1.call(CCLocaleController.java:30)
	at controllers.CCPlayUtils$1.apply(CCPlayUtils.java:974)
	at controllers.CCPlayUtils$1.apply(CCPlayUtils.java:964)
	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:34)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (5000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, {test_ApplicationFormat}:WSFHEHaApjlCL5QG/Ng/dg:key, 30000, a225e312-e347-40ad-8c37-d4c0d9ef9800:120] channel: [id: 0x2519e10d, L:/172.17.0.3:49640 - R:*.*.0001.use1.cache.amazonaws.com/10.0.0.181:6379]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:752)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)
	at java.lang.Thread.run(Thread.java:745)

Thanks,

**Comment by stkggit** [comment]
Using Redisson 2.13.2 version

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1722
