### ISSUE TITLE
Local embedded redis stopped working with 3.9.0

### ISSUE THREAD

**Issue by slisaasquatch** [redisson/redisson#1729]
### Expected behavior
Redisson should be able to connect to local redis running on port 6614.

### Actual behavior
Redisson won't start and throws this error:
```
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6614
        at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:160)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:327)
        at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:53)
        at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:291)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
        at org.redisson.client.RedisClient$2$1$2.run(RedisClient.java:250)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: failed to create a new resolver
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
        at org.redisson.connection.dns.MultiDnsAddressResolverGroup.getResolver(MultiDnsAddressResolverGroup.java:65)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        ... 6 common frames omitted
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioDatagramChannel
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
        at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
        at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:394)
        at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        ... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor36.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
        ... 28 common frames omitted
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:88)
        at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:116)
        ... 32 common frames omitted
Caused by: java.net.SocketException: maximum number of DatagramSockets reached
        at sun.net.ResourceManager.beforeUdpCreate(ResourceManager.java:73)
        at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:111)
        at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:42)
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:86)
        ... 33 common frames omitted
```

### Redis version
2.8.19

### Redisson version
3.9.0

### Redisson configuration
```java
		final org.redisson.config.Config rConfig = new org.redisson.config.Config()
				.setTransportMode(TransportMode.NIO);
		rConfig.useSingleServer()
				.setAddress("redis://localhost:6614")
				.setPassword(password);
```

So a few things to note.

I'm only having this issue with 3.9.0. 3.8.2 works just fine.

I tried replacing the address with "redis://127.0.0.1:6614", and I got the same error:
```
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6614
        at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:160)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:327)
        at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:53)
        at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:291)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
        at org.redisson.client.RedisClient$2$1$2.run(RedisClient.java:250)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: failed to create a new resolver
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
        at org.redisson.connection.dns.MultiDnsAddressResolverGroup.getResolver(MultiDnsAddressResolverGroup.java:65)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        ... 6 common frames omitted
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioDatagramChannel
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
        at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
        at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:394)
        at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        ... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
        ... 28 common frames omitted
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:88)
        at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:116)
        ... 32 common frames omitted
Caused by: java.net.SocketException: maximum number of DatagramSockets reached
        at sun.net.ResourceManager.beforeUdpCreate(ResourceManager.java:73)
        at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:111)
        at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:42)
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:86)
        ... 33 common frames omitted
```

I also tried removing the "redis://" part and only include "localhost:6614" or "127.0.0.1:6614", and I got a completely different error, which is:
```
Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: [localhost]:6614
        at java.net.URI.create(URI.java:852)
        at org.redisson.misc.URIBuilder.create(URIBuilder.java:39)
        at org.redisson.config.SingleServerConfig.setAddress(SingleServerConfig.java:119)
```
and 
```
Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:6614
        at java.net.URI.create(URI.java:852)
        at org.redisson.misc.URIBuilder.create(URIBuilder.java:31)
        at org.redisson.config.SingleServerConfig.setAddress(SingleServerConfig.java:119)
```

**Comment by jackygurui** [comment]
I think the last block of `Caused by` should have explained it itself:

```
Caused by: java.net.SocketException: maximum number of DatagramSockets reached
```

**Comment by slisaasquatch** [comment]
> I think the last block of `Caused by` should have explained it itself:
> 
> ```
> Caused by: java.net.SocketException: maximum number of DatagramSockets reached
> ```

So can you please explain to me why this is only happening with 3.9.0? As soon as I downgrade to 3.8.2, everything works just fine.

**Comment by mrniko** [comment]
Fixed! Could anyone try it and give feedback (3.0.0 branch)?

**Comment by slisaasquatch** [comment]
> Fixed! Could anyone try it and give feedback (3.0.0 branch)?

Hi, looks like the issue is still happening for me with 3.9.1. I created a [new ticket](https://github.com/redisson/redisson/issues/1750) for it.

@Flo354 Can you please give 3.9.1 a try and see if you have the same issue?
