### ISSUE TITLE
in MASTER_SLAVE readMode ,when master down,and read will be slow...

### ISSUE THREAD

**Issue by violetgo** [redisson/redisson#1746]
In MASTER_SLAVE read mode, when redis master node closes, read will slow down. Is this a bug?

Here are my operations：

I started three redis server processes, (6379, 7379, 7380), 6379 as master and 7379, 7380 as slave.
Then I started three Sentinel processes (26379, 26380, 26381) to monitor the redis cluster.
Then I started redisson client by this config:

`
Config config = new Config();
        config.setTransportMode(TransportMode.NIO);
        config.useSentinelServers()
                .setReadMode(ReadMode.MASTER_SLAVE)
                .setMasterName("mymaster")
                .addSentinelAddress("redis://127.0.0.1:26379", "redis://127.0.0.1:26380", "redis://127.0.0.1:26381");
`

Then I read and write randomly to redis cluster：

`
RedissonClient redisson = Redisson.create(config);
        for (; ; ) {
            try {
                RBucket<Object> test = redisson.getBucket("test");
                if (System.currentTimeMillis() % 5 == 0) {
                    test.set(System.currentTimeMillis()+"");
                }

                System.out.println(test.get());
                
                Thread.sleep(50);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
`
Then every 50 milliseconds I can get a result.

But when I kill redis master node (6379), the get command of redisson will become very slow, which is jstack information.

`
192 "main" #1 prio=5 os_prio=31 tid=0x00007febfc00c000 nid=0x1703 waiting on condition [0x0000700000218000]
193    java.lang.Thread.State: WAITING (parking)
194     at sun.misc.Unsafe.park(Native Method)
195     - parking to wait for  <0x000000076c40ab30> (a java.util.concurrent.CountDownLatch$Sync)
196     at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
197     at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
198     at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
199     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
200     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
201     at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:182)
202     at org.redisson.RedissonObject.get(RedissonObject.java:76)
203     at org.redisson.RedissonBucket.get(RedissonBucket.java:97)
204     at com.xxxx.main(RedisExpandClient.java:2135)
205     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
206     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
207     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
208     at java.lang.reflect.Method.invoke(Method.java:498)
209     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
`

### Redis version

redis-server --version
Redis server v=4.0.11 sha=00000000:0 malloc=libc bits=64 build=a57766d459574c0a

### Redisson version
<dependency>
   <groupId>org.redisson</groupId>
   <artifactId>redisson</artifactId>
   <version>3.9.0</version>
</dependency>

**Comment by violetgo** [comment]
@mrniko restart slave node has same problem~
