### ISSUE TITLE
RDelayedQueue 运行一段时间后不再transfer到Destination Queue，必须得重启才行

### ISSUE THREAD

**Issue by RogerFang** [redisson/redisson#1754]
`<!--`
Please consider to take commercial 24x7 support included in PRO version https://redisson.pro
-->
RDelayedQueue在应用启动一段时间后，不再transfer队列中到期的元素到Destination Queue，必须得重启才行呀。
### Expected behavior
重连后应该会继续Transfer才对
### Actual behavior
可以正常获取RDelayedQueue中的元素个数，但是没有进行Transfer

### Redisson version
3.9.0
### Redisson configuration

@jackygurui 麻烦帮忙看看，几天了都没有解决。

**Comment by jackygurui** [comment]
您能提供一个重现吗？主要是“一段时间”这个概念有一点抽象。能够重现出来的话就好解决一些。

**Comment by RogerFang** [comment]
```
2018-11-27 17:47:10,160[CommandAsyncService.java:977][DEBUG][org.redisson.command.CommandAsyncService] - connection released for command (LLEN) and params [redisson_delay_queue:{test-node-1}] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=3, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=31, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1744259190 [redisClient=[addr=redis://10.160.247.183:6001], channel=[id: 0x61a8b5f4]]
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (6000 ms) occured for command: (LLEN) with params: [redisson_delay_queue:{test-node-1}] channel: [id: 0x61a8b5f4]
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:884) ~[redisson-3.9.0.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

```
运行一段时间后也会出现这种超时现象，只有重启才能解决，这个是必现的问题，不知道怎么解决呢？
@jackygurui

**Comment by guosavage** [comment]
我遇到了同样的问题，但是时间比较长才会出现，也会出现这样的错误。
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (6000 ms)

**Comment by jackygurui** [comment]
@RogerFang @guosavage 你们可以尝试修改一下pingConnectionInterval这个参数

**Comment by guosavage** [comment]
如果 设置了pingConnectionTinterval 会遇到如下的错误。
`2019-01-05 14:08:15.911 ERROR 3536 --- [isson-netty-1-2] o.r.cluster.ClusterConnectionManager     : Can't execute CLUSTER_INFO for 55.12.196.18/55.12.196.18:6379

org.redisson.client.WriteRedisConnectionException: Channel has been closed! Can't write command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5a08631a(incomplete)], command=(CLUSTER INFO), params=[], codec=null] to channel: [id: 0x3fd82d0c, L:0.0.0.0/0.0.0.0:16070 ! R:55.12.196.18/55.12.196.18:6379]
	at org.redisson.client.handler.CommandsQueue.channelInactive(CommandsQueue.java:83) ~[redisson-3.8.2.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at org.redisson.client.handler.ConnectionWatchdog.channelInactive(ConnectionWatchdog.java:84) [redisson-3.8.2.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]`

**Comment by RogerFang** [comment]
> @RogerFang @guosavage 你们可以尝试修改一下pingConnectionInterval这个参数

是的，之前是通过尝试这个参数开启后才解决的。

**Comment by guosavage** [comment]
> > @RogerFang @guosavage 你们可以尝试修改一下pingConnectionInterval这个参数
> 
> 是的，之前是通过尝试这个参数开启后才解决的。

你是修改这个参数到什么值解决的呢？我开启了这个以后 就会报channel has been closed。目前还没解决

**Comment by floor23** [comment]
你好，我也遇到了这个问题。应该是必现的一个问题。
运行大概两三天会出现延时队列元素丢失的问题。
队列创建代码：
 ```java
private static RBlockingQueue<Long> taskQueue = RedissonHelper.redisson.getBlockingQueue("WX_DELAYED_TASK_QUEUE");
private static RDelayedQueue<Long> delayedTaskQueue = RedissonHelper.redisson.getDelayedQueue(taskQueue);
 ```
入队列代码：
 ```java
delayedTaskQueue.offer(one, delayTime, TimeUnit.MILLISECONDS);
 ```
获取元素的代码：
 ```java
while (true) {
try {
    printQueue("before execute");
    execute(taskQueue.take());
    printQueue("after execute");
    } catch (Exception e) {
    log.error("由任务队列获取任务失败", e);
    }
}
 ```
printQueue代码：
 ```java
public static void printQueue(String hint) {
        log.info("taskTrace start: " + hint);
        delayedTaskQueue.readAll().forEach(one -> log.info(String.format("taskTrace: delayedTaskQueue 内容: %s", one)));
        log.info("taskTrace end: " + hint);
    }
```
在服务器运行一段时间后发现任务执行失败，查看日志发现delayedTaskQueue中的元素都不见了，日志如下：
```log
15:38:43,424  INFO TaskService:969 - taskTrace start: Thread pool check
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097757933673955328
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097758524814962690
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097458667441139716
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097692298050850818
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098112565378068482
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098113151238463493
15:38:43,426  INFO TaskService:971 - taskTrace remainTimeToLive: -2
15:38:43,426  INFO TaskService:972 - taskTrace end: Thread pool check
15:43:42,450  INFO TaskService:969 - taskTrace start: Thread pool check
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097757933673955328
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097758524814962690
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097458667441139716
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097692298050850818
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098112565378068482
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098113151238463493
15:43:42,452  INFO TaskService:971 - taskTrace remainTimeToLive: -2
15:43:42,452  INFO TaskService:972 - taskTrace end: Thread pool check
15:48:41,483  INFO TaskService:969 - taskTrace start: Thread pool check
15:48:41,483  INFO TaskService:971 - taskTrace remainTimeToLive: -1
15:48:41,483  INFO TaskService:972 - taskTrace end: Thread pool check
15:53:40,507  INFO TaskService:969 - taskTrace start: Thread pool check
15:53:40,507  INFO TaskService:971 - taskTrace remainTimeToLive: -1
15:53:40,507  INFO TaskService:972 - taskTrace end: Thread pool check
15:58:39,533  INFO TaskService:969 - taskTrace start: Thread pool check
15:58:39,534  INFO TaskService:971 - taskTrace remainTimeToLive: -1
15:58:39,534  INFO TaskService:972 - taskTrace end: Thread pool check
```

这个问题在我这边是必现的。如果需要配合，我这边可以随时复现。谢谢。

**Comment by ieven** [comment]
我也遇上了同样的问题，版本是3.9.1。两天左右以后必出现，而且只有在延迟队列>=2个的时候才会出现。

**Comment by ieven** [comment]
设置pingConnectionInterval以后也无法解决这个问题，请问您是怎么解决的

**Comment by fanaj** [comment]
> 设置pingConnectionInterval以后也无法解决这个问题，请问您是怎么解决的
请问你这个问题现在解决了吗?是怎么解决的.

**Comment by chengduHebiao** [comment]
any suggestion? 是在高版本中意见修复了吗

**Comment by ieven** [comment]
高版本已经修复。低版本设置了pingConnectionInterval以后会出现部分延迟消息丢失的情况。

**Comment by 843257317** [comment]
> 高版本已经修复。低版本设置了pingConnectionInterval以后会出现部分延迟消息丢失的情况。

请问java7对应修复的版本是哪个

**Comment by 843257317** [comment]
> 高版本已经修复。低版本设置了pingConnectionInterval以后会出现部分延迟消息丢失的情况。

请问有对应修复的2.x版本的具体的版本号吗，看了release记录没找到很具体的

**Comment by ieven** [comment]
版本号时间有点儿久记不清了。最新版本是没有这个问题的。

**Comment by dwyane3011** [comment]
me too

**Comment by WingGao** [comment]
3.16.3 还有
