### ISSUE TITLE
ByteArrayCodec does not work with RedissonSession

### ISSUE THREAD

**Issue by BigMichi1** [redisson/redisson#1757]
### Expected behavior
having this config for the redissonclient and using @EnableRedissonHttpSession should not fail with ClassCastException

        final Config config = new Config();
        config.setCodec(new ByteArrayCodec());
        return Redisson.create(config);

### Actual behavior

using above configuration and RedissonSession we get a ClassCastException

    Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to [B
    		at org.redisson.client.codec.ByteArrayCodec$1.encode(ByteArrayCodec.java:39)
    		at org.redisson.RedissonObject.encodeMapKey(RedissonObject.java:265)
    		at org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:396)
    		at org.redisson.RedissonMap.putAllAsync(RedissonMap.java:338)
    		at org.redisson.RedissonMap.putAll(RedissonMap.java:269)
    		at org.redisson.spring.session.RedissonSessionRepository$RedissonSession.<init>(RedissonSessionRepository.java:69)
    		at org.redisson.spring.session.RedissonSessionRepository.createSession(RedissonSessionRepository.java:293)
    		at org.redisson.spring.session.RedissonSessionRepository.createSession(RedissonSessionRepository.java:51)
    		at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:373)
    		at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:217)
    		at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:270)

### Steps to reproduce or test case

follow https://github.com/redisson/redisson/wiki/14.-Integration%20with%20frameworks#146-spring-session but also add ByteArrayCodec as the default codec

### Redis version

3.2.6

### Redisson version

2.14.1

### Redisson configuration

        final Config config = new Config();
        config.setCodec(new ByteArrayCodec());
        return Redisson.create(config);

**Comment by mrniko** [comment]
Usage of ByteArrayCodec assumes that only object with byte array type are stored. Spring Session uses String in some cases, so it doesn't fit for this case. I would recommend you to try FST binary codec instead
