### ISSUE TITLE
Unexpected ClosedChannelException during operation

### ISSUE THREAD

**Issue by Katikatikou** [redisson/redisson#1769]
This error occurs regularly (about every 3-5 minutes), I’ve noticed that when it happens the freeSubscribeConnectionsAmount  is 0, could it be related to that?

### Actual behavior
org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=47, freeConnectionsAmount=16, freeConnectionsCounter=112, freezed=false, freezeReason=null, client=[addr=redis://master.ip:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@213381393 [redisClient=[addr=redis://master.ip:6379], channel=[id: 0x377886d2, L:/client.ip:53212 ! R:master.ip/master.ip:6379]], command: (PUBLISH), command params: [Channel-Name:TEST:heartbeat, *****************] after 3 retry attempts
                at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:837) ~[redisson-3.9.1.jar:?]
                at org.redisson.command.CommandAsyncService.access$200(CommandAsyncService.java:92) ~[redisson-3.9.1.jar:?]
                at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:794) ~[redisson-3.9.1.jar:?]
                at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:791) ~[redisson-3.9.1.jar:?]
                at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.nio.channels.ClosedChannelException
                at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]

### Redis version
3.2.12, 1 master, 2 slaves & 3 sentinels

### Redisson version
3.9.1

### Redisson configuration
sentinelServers.setPassword(*****);
sentinelServers.setSlaveConnectionPoolSize(128);
sentinelServers.setMasterConnectionPoolSize(128);
(everything else uses the default values)

**Comment by jackygurui** [comment]
Please consider increase the pubsub conneciton pool size

**Comment by zzhgithub** [comment]
@jackygurui  I'm sorry to disturb you.

can you tell me why the problem happen 。and if i increase the pubsub conneciton pool size,Can the problem be fixed forever  Or just extend the time of error reporting.

by the way here is my config . it's that be allright??  
```java
 Config config = new Config();
        config.setThreads(16);
        config.setTransportMode(TransportMode.NIO);
        config.setNettyThreads(64);

        config.useSingleServer()
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setSubscriptionConnectionPoolSize(100)
                .setTcpNoDelay(true)
                .setKeepAlive(true)
                .setPingConnectionInterval(60)
                .setAddress(redisUri);
```

**Comment by jackygurui** [comment]
The size of the pool is entirely depending on your usage. There are two parameters essentially determins how many topics can be subscribed at most at any time. `subscriptionConnectionPoolSize` and `subscriptionsPerConnection` the product of the two number is effectively the upper limit. When  usage exceeds the limit, you will start experencing this problem. 

It is adviced to make an educated guess of potential usage to start with, and always review and re-tune the configuration periodically in production.

**Comment by zzhgithub** [comment]
@jackygurui  thx it helps me a lot.
