### ISSUE TITLE
Reddison tomcat session manager - unhandled exception

### ISSUE THREAD

**Issue by skybber** [redisson/redisson#1773]
We're using : Tomcat8.5

When develop it might happen, that serialized session is not able to deserialize due modification in Class
(add/remove fields), in such cases redisson throws java.lang.ClassCastException, it's quite OK. But session manager doesn't catch it in findSession() method: 

2018.12.04 10:53:12     com.mailprofiler.app.xcampaign.appl.webfilters.Logout   doFilter()      java.lang.Long cannot be cast to java.util.Map
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Map
        at org.redisson.RedissonMap.readAllMap(RedissonMap.java:501)
        at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:148)
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2977)
        at org.apache.catalina.connector.Request.getSession(Request.java:2434)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231)

would be better if it catch it and return no-session.

**Comment by mrniko** [comment]
Done
