### ISSUE TITLE
Parse URI error,  Illegal character in authority at index 8

### ISSUE THREAD

**Issue by oudezhi** [redisson/redisson#1781]
Hello ，I got a error when starting up the application.

     [ERROR] org.springframework.web.context.ContextLoader:initWebApplicationContext:351 - Context initialization failed 
     org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.redisson.spring.misc.BeanMethodInvoker#0': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Illegal character in authority at index 8: redis://fkredis0engine2s.dsjfeideedba.com:29200 
     
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at com.feidee.risk.base.web.AdminContextListener.contextInitialized(AdminContextListener.java:13) ~[classes/:1.0]

     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4861) ~[catalina.jar:8.0.50]

     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322) ~[catalina.jar:8.0.50]

     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) ~[catalina.jar:8.0.50]

     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753) ~[catalina.jar:8.0.50]

     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729) ~[catalina.jar:8.0.50]

     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) ~[catalina.jar:8.0.50]

     at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:974) ~[catalina.jar:8.0.50]

     at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850) ~[catalina.jar:8.0.50]

     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]

     at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]

     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]

     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]

     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

     Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 8: redis://fkredis0engine2s.dsjfeideedba.com:29200

     at java.net.URI.create(URI.java:852) ~[?:1.8.0_51]

     at org.redisson.misc.URIBuilder.create(URIBuilder.java:31) ~[redisson-3.7.5.jar:?]

     at org.redisson.config.SentinelServersConfig.addSentinelAddress(SentinelServersConfig.java:77) ~[redisson-3.7.5.jar:?]

     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]

     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]

     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]

     at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]

     at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.redisson.spring.misc.BeanMethodInvoker.afterPropertiesSet(BeanMethodInvoker.java:33) ~[redisson-3.7.5.jar:?]

          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: redis://fkredis0engine2s.dsjfeideedba.com:29200

     at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_51]

     at java.net.URI$Parser.parseAuthority(URI.java:3186) ~[?:1.8.0_51]

     at java.net.URI$Parser.parseHierarchical(URI.java:3097) ~[?:1.8.0_51]

     at java.net.URI$Parser.parse(URI.java:3053) ~[?:1.8.0_51]

     at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_51]

     at java.net.URI.create(URI.java:850) ~[?:1.8.0_51]

     at org.redisson.misc.URIBuilder.create(URIBuilder.java:31) ~[redisson-3.7.5.jar:?]

     at org.redisson.config.SentinelServersConfig.addSentinelAddress(SentinelServersConfig.java:77) ~[redisson-3.7.5.jar:?]

     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]

     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]

     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]

     at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]

at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]

     at org.redisson.spring.misc.BeanMethodInvoker.afterPropertiesSet(BeanMethodInvoker.java:33) ~[redisson-3.7.5.jar:?]

**Comment by mrniko** [comment]
Unable to reproduce it with 3.9.1 version
