### ISSUE TITLE
RMap.getAll   throw ClassCastException

### ISSUE THREAD

**Issue by LG772EF** [redisson/redisson#1798]
### Actual behavior
exception
java.lang.ClassCastException: java.util.HashMap cannot be cast to org.redisson.RedissonMap
	at org.redisson.transaction.BaseTransactionalMap.getAllOperationAsync(BaseTransactionalMap.java:702)
	at org.redisson.transaction.RedissonTransactionalMap.getAllOperationAsync(RedissonTransactionalMap.java:203)
	at org.redisson.RedissonMap.getAllAsync(RedissonMap.java:202)
	at org.redisson.RedissonMap.getAll(RedissonMap.java:193)

### reason
BaseTransactionalMap.java
protected RFuture<Map<K, V>> getAllOperationAsync(Set<K> keys) {
      final Map<K, V> map = new HashMap();
      ...
     // 此处map是hashMap，强转异常  -- redission 3.8.0,  line:646
     RFuture<Map<K, V>> future = ((RedissonMap)map).getAllOperationAsync(keysToLoad);

}

### Redisson version
3.8.0

**Comment by mrniko** [comment]
Fixed! Thanks for report
