### ISSUE TITLE
Fallback on DB if Redis cache fails to handle requests

### ISSUE THREAD

**Issue by wmaozhi** [redisson/redisson#1800]
### Actual behavior
org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=19, freeConnectionsCounter=99, freezed=false, freezeReason=null, client=[addr=redis://xxx:8547], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@71309928 [redisClient=[addr=redis://xxx:8547], channel=[id: 0x5acfe8a4, L:/xxx1:59042 ! R:xxx/xxx:8547]], command: (EXISTS), command params: [2430000015871226] after 3 retry attempts]

	at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:837)
	at org.redisson.command.CommandAsyncService.access$200(CommandAsyncService.java:92)
	at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:794)
	at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:791)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

 
### Redisson version
     3.9.0
### Redisson configuration
  <redisson:client id="redissonClient">
        <redisson:single-server
             address="redis://${redis.jedisConnectionFactory.hostName}:${redis.jedisConnectionFactory.port}"
                password="${redis.jedisConnectionFactory.password}"
                retry-attempts="${redisson.retry-attempts}"
                retry-interval="${redisson.retry-interval}"
                connection-minimum-idle-size="${redisson.connection-minimum-idle-size}"
                connection-pool-size="${redisson.connection-pool-size}"
                ping-timeout="${redisson.ping-timeout}"
                timeout="${redisson.timeout}"
                idle-connection-timeout="${redisson.idle-connection-timeout}"
                connect-timeout="${redisson.connect-timeout}"
                failed-slave-reconnection-interval=""
                database="${redis.session.dbIndex}"/>

redisson.retry-attempts=10
redisson.retry-interval=1500
redisson.connection-minimum-idle-size=20
redisson.connection-pool-size=100
redisson.ping-timeout=1000
redisson.timeout=3000
redisson.idle-connection-timeout=10000
redisson.connect-timeout=10000
    </redisson:client>

**Comment by jackygurui** [comment]
能不能把完整的报错发一下？

**Comment by wmaozhi** [comment]
Caused by: java.nio.channels.ClosedChannelException  这个错误如何解决？

**Comment by animator013** [comment]
have the same problem when redis server shuts down and application is still alive. Also when using hibernate 2nd level cache i get no session found and application is in unusable state. Is it possible to revert to no caching (hitting db) when redis is down ?

**Comment by mahesh-ogale** [comment]
It would be great to get the functionality of falling back on DB in case Redis is down.

**Comment by blackstorm** [comment]
same error on version 3.9.1

**Comment by mrniko** [comment]
Done. Use `hibernate.cache.redisson.fallback=true" setting

**Comment by cybercooll** [comment]
I tried 3.12.2 with fallback set to true.
How is it suppose to behave if I akill redis before startup or while application is running ?
At startup: I get a `RedisConnectionException : Can't connect to servers` which prevents the application from starting by crashing the build of EntityManagerFactory.
While running: I get an endless looping just after the sql statement:
`org.redisson.hibernate.RedissonStorage: Unable to write command into connection!
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection!  after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:271) ` 
Seems like I get the results from database, but then it tries to cache the results and fails in a loop.

Tried with both singleServerConfig and clusterServerConfig.

Is there something more to do ?

**Comment by mrniko** [comment]
at the moment it works only if Redis beacame unavailable during application work.

**Comment by mrniko** [comment]
> I get an endless looping just after the sql statement:
org.redisson.hibernate.RedissonStorage: Unable to write command into connection! org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! after 3 retry attempts at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:271)
Seems like I get the results from database, but then it tries to cache the results and fails in a loop.

Unable to reproduce this part. Errors are only reported in log, but not thrown to user.

**Comment by cybercooll** [comment]
You're right, it works but it is very slow due to  retryAttempts/retryInterval that "lock" each statement until all attemps fail.
I use this conf:
idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
If I use the following configuration, it's more usable:
  idleConnectionTimeout: 1000
  connectTimeout: 1000
  timeout: 3000
  retryAttempts: 2
  retryInterval: 500

**Comment by anthonyrichir** [comment]
Hello,

Any reason why this fallback wasn't released on redisson-hibernate-52 ?

**Comment by ashishsahuGitHub** [comment]
Hi,
I'm also getting this error very frequently  org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:500:queue:0, freeConnectionsAmount=973, freeConnectionsCounter=value:4974:queue:0, freezed=false, freezeReason=null, client=[addr=redis://10.26.6.190:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1857244849 [redisClient=[addr=redis://10.26.6.133:6379], channel=[id: 0x8e212358, L:0.0.0.0/0.0.0.0:43288], command=null], command: (HGET), command params: [tenantDataBaseMap, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 256)] after 3 retry attempts
        at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:873)
        at org.redisson.command.CommandAsyncService.access$000(CommandAsyncService.java:97)
        at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:792)
        at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:789)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)




I am using redisson-all-3.10.4
Below is configuration 

"sentinelServersConfig":{
      "idleConnectionTimeout":5000,
      "connectTimeout":8000,
      "timeout":5000,
      "retryAttempts":3,
      "retryInterval":1500,
      "failedSlaveReconnectionInterval":3000,
      "failedSlaveCheckInterval":60000,
      "password":null,
      "subscriptionsPerConnection":10,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "subscriptionConnectionMinimumIdleSize":100,
      "subscriptionConnectionPoolSize":500,
      "slaveConnectionMinimumIdleSize":1000,
      "slaveConnectionPoolSize":5000,
      "masterConnectionMinimumIdleSize":1000,
      "masterConnectionPoolSize":5000,
      "readMode":"SLAVE",
      "subscriptionMode":"SLAVE",
      "sentinelAddresses":["redis://10.57.6.133:26371","redis://10.57.6.80:26371","redis://10.26.4.205:26371"],
      "masterName":"master01",
      "database":0
   },
   "threads":16,
   "nettyThreads":32,
   "codec":{
      "class":"org.redisson.codec.FstCodec"
   },
   "transportMode":"NIO" 

Help me to solve this issue.

**Comment by mrniko** [comment]
@ashishsahuGitHub 

> `Caused by: java.nio.channels.ClosedChannelException`

define `pingConnectionInterval` setting

**Comment by ashishsahuGitHub** [comment]
Hi @mrniko ,
Can you please me to explain this closedchannelexception ?
What pingConnectionInterval  parameter gonna help here ?

**Comment by mrniko** [comment]
@ashishsahuGitHub 

It will help to keep connection in "connected" state. Just try

**Comment by ashishsahuGitHub** [comment]
@mrniko Okay , I will try this, what will the value of this parameter ?

**Comment by mrniko** [comment]
It pings connection and reconnects it when it fails to response

**Comment by ashishsahuGitHub** [comment]
I have given the value as below 
`"pingConnectionInterval":1000`

is this ideal value for this ?

**Comment by ashishsahuGitHub** [comment]
Hi @mrniko ,

Now i am getting below error.

[] [] [] []  [2020-05-08 12:47:15,149] [redisson-netty-1-19] [ERROR] [org.redisson.connection.SentinelConnectionManager:acce
pt:304] - Can't execute SENTINEL commands on X.Y.Z.T/X.Y.Z.N:2679
 [] [] [] []  org.redisson.client.WriteRedisConnectionException: Channel has been closed! Can't write command: (SENTINEL SLAVES), params: [master01] to channel: [id: 0xb7ed9c79, L:0.0.0.0/0.0.0.0:58460 ! R:X.Y.Z.T/X.Y.Z.N:2679]
        at org.redisson.client.handler.CommandsQueue.channelInactive(CommandsQueue.java:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at org.redisson.client.handler.ConnectionWatchdog.channelInactive(ConnectionWatchdog.java:82)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Suggest me solution for this.

**Comment by xercasy** [comment]
@cybercooll Dit you find the solution ?I also have a loop

**Comment by mrniko** [comment]
@cybercooll 

> it works but it is very slow due to retryAttempts/retryInterval that "lock" each statement until all attemps fail.

Fixed

**Comment by karlssone** [comment]
> at the moment it works only if Redis beacame unavailable during application work.

Do you have any plans to make it work if Redis is not available during startup?

**Comment by mrniko** [comment]
@karlssone 

Did you try to set `lazyInitialization=true` ?

**Comment by karlssone** [comment]
@mrniko 
That doesn't sound like a solution for me. I would like my applikation to be able to run even if Redis is unavailable for a long time.
