### ISSUE TITLE
NPE in CommandPubSubDecoder

### ISSUE THREAD

**Issue by hedroid** [redisson/redisson#1802]
Caused by: java.lang.NullPointerException
at org.redisson.client.handler.CommandPubSubDecoder.selectDecoder(CommandPubSubDecoder.java:246)
~[redisson-3.9.1.jar:?]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:351) ~[redisson-3.9.1.jar:?]
at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:413) ~[redisson-3.9.1.jar:?] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378) ~[redisson-3.9.1.jar:?]
at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:78)
~[redisson-3.9.1.jar:?]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108) ~[redisson-3.9.1.jar:?]
### Expected behavior
在使用多线程调用RLock的时候，时不时出现这个npe.
单线程跑，暂时未发现
  RLock lock = redisson.getLock("MATCH_QUEUE_LOCK");
        if (lock.tryLock(10, 10, TimeUnit.SECONDS)) {
            try {
          .....
            } finally {
                lock.unlock();
            }
        } else {
            return playerPairs;
        }

### Redis version
3.2
### Redisson version
3.9.1
### Redisson configuration
{
  "singleServerConfig": {
    "idleConnectionTimeout": 10000,
    "pingTimeout": 1000,
    "connectTimeout": 10000,
    "pingConnectionInterval":10000,
    "keepAlive":true,
    "timeout": 3000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "password": null,
    "subscriptionsPerConnection": 5,
    "clientName": null,
    "address": "redis://192.168.1.138:6379",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "connectionMinimumIdleSize": 32,
    "connectionPoolSize": 64,
    "database": 1
  },
  "threads": 5,
  "nettyThreads": 5,
  "codec": {
    "class": "org.redisson.codec.JsonJacksonCodec"
  },
  "transportMode": "NIO"
}

**Comment by mrniko** [comment]
set `pingConnectionInterval` = 0 as workaround

**Comment by mrniko** [comment]
please recheck it against 3.10.0 version. It contains decoding bug fix caused by `pingConnectionInterval` setting
