### ISSUE TITLE
Redisson exception message include password as plain text which is insecure when print in log

### ISSUE THREAD

**Issue by empty117** [redisson/redisson#1820]
### Expected behavior

Exception stack/message print password as ******:
Caused by: org.redisson.client.RedisException: ERR invalid password. channel: [id: 0xb92cdd41, L:/2a00:8a00:4000:20c:0:0:87:2fb:34496 - R:2a00:8a00:4000:20c::87:2fb/2a00:8a00:4000:20c:0:0:87:2fb:6379] command: (AUTH), params: [ ***** ]

### Actual behavior
Exception stack/message print password as plain text which is insecure:

org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 2a00:8a00:4000:20c::87:2fb/2a00:8a00:4000:20c:0:0:87:2fb:6379
	at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:138) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[?:?]
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108) ~[?:?]
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:301) ~[?:?]
	at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:54) ~[?:?]
	at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:266) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[?:?]
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108) ~[?:?]
	at org.redisson.client.RedisClient$2$1$1$1.run(RedisClient.java:240) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[?:?]
	at io

Caused by: org.redisson.client.RedisException: ERR invalid password. channel: [id: 0xb92cdd41, L:/2a00:8a00:4000:20c:0:0:87:2fb:34496 - R:2a00:8a00:4000:20c::87:2fb/2a00:8a00:4000:20c:0:0:87:2fb:6379] command: (AUTH), params: [**abcde**]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:314) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:124) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[?:?]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]

### Steps to reproduce or test case
Configure wrong password in redisson("abcde") when connect redis("abcd")
### Redis version
any
### Redisson version
3.7.0
### Redisson configuration
sentinel

**Comment by empty117** [comment]
@mrniko  Could you help to check this issue?
