### ISSUE TITLE
Command execution timeout for command: (INFO REPLICATION)

### ISSUE THREAD

**Issue by julialiu15** [redisson/redisson#1825]
### Steps to reproduce or test case
We're using 1 node in ElasticCache with the following config:
```
        ReplicatedServersConfig serversConfig = config.useReplicatedServers()
                .setRetryInterval(15000)
                .setRetryAttempts(2);
```
Already checked the network latency, CPU, memory, everything seems to be normal when the exception happens.

### Redis version
4.0.10

### Redisson version
3.8.2

This happens around once a day or less, pretty consistently, usually during midnight when system is idle. Seems to be related to reconnection / retry strategy, already tried to bump up `retryInterval` and `retryAttempts` following the suggestion in https://github.com/redisson/redisson/issues/576.
Full stack trace:
```
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (INFO REPLICATION), command params: [], Redis client: [addr=http://****cache.amazonaws.com:6379]
    at org.redisson.client.RedisConnection$2.run(RedisConnection.java:214)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```
Any inputs are welcome, thank you!

**Comment by mrniko** [comment]
Also please check memory usage on Redis this could be the cause

**Comment by julialiu15** [comment]
Thank you for the reply. Ass mentioned in the post, checked on network/memory/CPU usage, everything looks normal, generally below 5%.

**Comment by mrniko** [comment]
wrong address is used `http://****cache.amazonaws.com` but `redis://****cache.amazonaws.com` should be used instead

**Comment by julialiu15** [comment]
Posting my solution here incase someone run into the same issue. Bumping up timeout and connectTimeout in BaseConfig remits the issue for now. Address(starting with `redis://` or `http://`) doesn't matter here, could be required in higher versions of Redisson.
