### ISSUE TITLE
NPE after upgrade to 3.10.0

### ISSUE THREAD

**Issue by archmisha** [redisson/redisson#1830]
```
Caused by: java.lang.NullPointerException
at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357) ~[fst-2.56.jar:?]
at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.56.jar:?]
at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.56.jar:?]
at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.56.jar:?]
at org.redisson.codec.FstCodec$1.decode(FstCodec.java:70) ~[redisson-3.10.0.jar:?]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:330) ~[redisson-3.10.0.jar:?]
at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:130) ~[redisson-3.10.0.jar:?]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110) ~[redisson-3.10.0.jar:?]
```

### Redis version
3.0.7

### Redisson version
3.10.0

### Redisson configuration
Our redisson configuration:
Sentinel cluster with 4 nodes
masterConnectionPoolMinSize=16
masterConnectionPoolMaxSize=64
slaveConnectionPoolMinSize=16
slaveConnectionPoolMaxSize=64
timeout=3000
keepAlive=false
idleConnectionTimeout=10000
connectTimeout=10000
pingConnectionInterval=0
pingTimeout=1000
with password auth

**Comment by mrniko** [comment]
Hi,

Please define codec explicitly, since default codec has been changed to `FSTCodec`.

**Comment by archmisha** [comment]
Thanks. Can you share what was the default code before, that I need to use now?

**Comment by mrniko** [comment]
it was `org.redisson.codec.JsonJacksonCodec`

**Comment by mrniko** [comment]
In case you have this issue with empty Redis database please provide test case to reproduce that.
