### ISSUE TITLE
LRUCacheMap ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jchobantonov** [redisson/redisson#1836]
java.lang.ArrayIndexOutOfBoundsException
        at java.util.ArrayList.elementData(ArrayList.java:433)
        at java.util.ArrayList.get(ArrayList.java:446)
        at org.redisson.cache.LRUCacheMap.getQueue(LRUCacheMap.java:57)
        at org.redisson.cache.LRUCacheMap.onValueCreate(LRUCacheMap.java:52)
        at org.redisson.cache.AbstractCacheMap.put(AbstractCacheMap.java:190)
        at org.redisson.cache.AbstractCacheMap.put(AbstractCacheMap.java:179)
        at org.redisson.liveobject.misc.ClassUtils.isAnnotationPresent(ClassUtils.java:137)
        at org.redisson.misc.RedissonObjectFactory.toReference(RedissonObjectFactory.java:166)
        at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:273)
        at org.redisson.RedissonMap.fastPutOperationAsync(RedissonMap.java:1052)
        at org.redisson.RedissonMap.fastPutAsync(RedissonMap.java:1037)
        at org.redisson.RedissonMap.fastPut(RedissonMap.java:1057)
        at org.redisson.tomcat.RedissonSession.fastPut(RedissonSession.java:153)
        at org.redisson.tomcat.RedissonSession.setAttribute(RedissonSession.java:200)
        at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1415)
        at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:137)

### Expected behavior
No ArrayIndexOutOfBoundsException

### Actual behavior
Throwing ArrayIndexOutOfBoundsException when setting object into HTTP session using setAttribute

### Steps to reproduce or test case
Configure Tomcat 8.5 server with redisson-tomcat-8-2.15.0.jar and redisson-all-2.15.0.jar - try to set object into http session using setAttribute

### Redis version
Redis server v=3.0.504 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=a4f7a6e86f2d60b3

### Redisson version
redisson-all-2.15.0

### Redisson configuration

singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by jchobantonov** [comment]
Thank you!

**Comment by jchobantonov** [comment]
After rebuilding with the fix you did I'm getting this exception now:
@mrniko 

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -2
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:399)
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:408)
        at org.redisson.cache.LRUCacheMap.getQueue(LRUCacheMap.java:57)
        at org.redisson.cache.LRUCacheMap.onValueCreate(LRUCacheMap.java:52)
        at org.redisson.cache.AbstractCacheMap.put(AbstractCacheMap.java:190)
        at org.redisson.cache.AbstractCacheMap.put(AbstractCacheMap.java:179)
        at org.redisson.liveobject.misc.ClassUtils.isAnnotationPresent(ClassUtils.java:137)
        at org.redisson.liveobject.core.RedissonObjectBuilder.toReference(RedissonObjectBuilder.java:258)
        at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:272)
        at org.redisson.RedissonMap.fastPutOperationAsync(RedissonMap.java:1052)
        at org.redisson.RedissonMap.fastPutAsync(RedissonMap.java:1037)
        at org.redisson.RedissonMap.fastPut(RedissonMap.java:1057)
        at org.redisson.tomcat.RedissonSession.fastPut(RedissonSession.java:153)
        at org.redisson.tomcat.RedissonSession.setAttribute(RedissonSession.java:200)
        at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1415)
        at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:137)

**Comment by jchobantonov** [comment]
@mrniko the method getQueue should be like this:

    private Collection<CachedValue<K, V>> getQueue(CachedValue<K, V> value) {
        return queues.get(Math.abs(value.hashCode() % queues.size()));
    }

e.g we need Math.abs as value.hashCode() could be negative

**Comment by mrniko** [comment]
@jchobantonov Right!

Fixed
