### ISSUE TITLE
Unable to decode data & NPE

### ISSUE THREAD

**Issue by Skycat** [redisson/redisson#1838]
### Actual behavior
```
01/05 14:22:37.435 ERROR [redisson-netty-2-2] (CommandPubSubDecoder.java:81) - Unable to decode data. channel: [id: 0xa570f102, L:/172.18.5.20:55662 - R:10.0.2.10/10.0.2.10:6379] message: *3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0
*3
$7
message
$48
redisson_lock__channel:{lock:friend:68719477182}
$1
0

java.lang.NullPointerException: null
        at org.redisson.client.handler.CommandPubSubDecoder.selectDecoder(CommandPubSubDecoder.java:245) ~[redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:329) [redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:380) [redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:343) [redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:77) ~[redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110) [redisson-3.10.0.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
01/05 14:22:37.435  WARN [redisson-netty-2-2] (Slf4JLogger.java:151) - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NullPointerException: null
        at org.redisson.client.handler.CommandPubSubDecoder.selectDecoder(CommandPubSubDecoder.java:245) ~[redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:329) ~[redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:380) ~[redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:343) ~[redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:77) ~[redisson-3.10.0.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110) ~[redisson-3.10.0.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        ... 28 common frames omitted
```
### Steps to reproduce or test case
```
        RLock lock1 = redissonClient.getLock(LockName.friend(playerId));
        List<Long> success = new ArrayList<>();
        for (long friendId : friendIds) {
            RLock lock2 = redissonClient.getLock(LockName.friend(friendId));
            RLock[] locks = sort(lock1, lock2);
            RedissonMultiLock lock = new RedissonMultiLock(locks);
            try {
            if (!lock.tryLock(config.getRedissonLockWait(), config.getRedissonLockRelease(), TimeUnit.SECONDS)) {
                throw new Exception("lock failed", e);
            }
        } catch (Exception e) {
            throw new Exception("lock failed", e);
        }

            try {
                // do something...
            } finally {
                lock.unlock();
            }
        }
```
the code run in high concurrent environment appear so many of the exception
### Redis version
4.0
### Redisson version
3.10.0
### Redisson configuration
```
<bean id="redissonCodec" class="org.redisson.codec.JsonJacksonCodec" />
<redisson:client id="gameRedisson" codec-ref="redissonCodec">
    <redisson:single-server address="${redis.host1}" password="${redis.password}" />
</redisson:client>
```

**Comment by mrniko** [comment]
Could you share values for getRedissonLockWait getRedissonLockRelease params?

**Comment by Skycat** [comment]
> 
> 
> Could you share values for `friendIds`, `getRedissonLockWait` and `getRedissonLockRelease` params?
> 
> Which Redis hosting do you use?

the friendIds such as 68719477182, 68719477183, 68719477185... and so on

getRedissonLockWait = 3

getRedissonLockRelease = 6

Redis hosting is tencent cloud service, the documents link: [https://intl.cloud.tencent.com/document/product/239/18336](https://intl.cloud.tencent.com/document/product/239/18336)

thx for you replay!

**Comment by mrniko** [comment]
Fixed! Please give it a try
