### ISSUE TITLE
NPE at startUp onMessage

### ISSUE THREAD

**Issue by lbernollin** [redisson/redisson#1841]
### Actual behavior
`Exception in thread "redisson-3-1" java.lang.NullPointerException
        at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:251)
        at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:52)
        at org.redisson.PubSubPatternMessageListener.onPatternMessage(PubSubPatternMessageListener.java:82)
        at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:84)
        at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:186)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)`
### Steps to reproduce or test case
I got this issue at my application startup. It is not happens at each startup
### Redis version
4.0.11
### Redisson version
3.10.0
### Redisson configuration
`@configuration
@EnableRedissonHttpSession
public class RedissonConfig implements BeanClassLoaderAware
{
@Autowired
private RedisProperties redisProperties;

private static final int CONNECTION_TIMEOUT = 3000;
private static final int TIMEOUT = 10000;
private static final int THREAD_NUMBER = 4;

private ClassLoader loader;

@Bean(destroyMethod = "shutdown")
public RedissonClient redissonClient()
{
    return Redisson.create(sentinelServers());
}

private Config baseConfig()
{
    return new Config()
            .setNettyThreads(THREAD_NUMBER)
            .setThreads(THREAD_NUMBER)
            .setCodec(new JsonJacksonCodec(mapper()));
}

private Config sentinelServers()
{
    final Config config = baseConfig();
    config.useSentinelServers()
            .setConnectTimeout(CONNECTION_TIMEOUT)
            .setTimeout(TIMEOUT)
            .addSentinelAddress(split(redisProperties.getAddresses(), ", "))
            .setMasterName(redisProperties.getMasterName())
            .setPassword(redisProperties.getPassword())
           .setDatabase(redisProperties.getDatabase());
    return config;
}

@Override
public void setBeanClassLoader(final ClassLoader classLoader)
{
    this.loader = classLoader;
}

private ObjectMapper mapper()
{
    final ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new JavaTimeModule());
    mapper.registerModules(SecurityJackson2Modules.getModules(this.loader));
    mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
    mapper.setSerializationInclusion(Include.NON_NULL);
    mapper.addMixIn(Throwable.class, JsonJacksonCodec.ThrowableMixIn.class);
    mapper.findAndRegisterModules();
    return mapper;
}
}
`

**Comment by mrniko** [comment]
Unable to reproduce it. Can you debug it and trace at which field NPE arise?

**Comment by lbernollin** [comment]
I didn't manage to reproduce for now. I will let you know when i will have more data.
