### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Subscribe timeout: (7500ms)

### ISSUE THREAD

**Issue by archmisha** [redisson/redisson#1847]
### Expected behavior
`java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Subscribe timeout: (7500ms)
at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:197) ~[redisson-3.10.0.jar:?]
at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:206) ~[redisson-3.10.0.jar:?]
at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:159) ~[redisson-3.10.0.jar:?]
at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:149) ~[redisson-3.10.0.jar:?]
at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:136) ~[redisson-3.10.0.jar:?]
at org.redisson.RedissonLock.lock(RedissonLock.java:118) ~[redisson-3.10.0.jar:?]
Caused by: org.redisson.client.RedisTimeoutException: Subscribe timeout: (7500ms)
at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:160) ~[redisson-3.10.0.jar:?]
... 23 more`

### Redis version
3.0.7

### Redisson version
3.9.0

### Redisson configuration
Our redisson configuration:
Sentinel cluster with 4 nodes
masterConnectionPoolMinSize=16
masterConnectionPoolMaxSize=64
slaveConnectionPoolMinSize=16
slaveConnectionPoolMaxSize=64
timeout=3000
keepAlive=false
idleConnectionTimeout=10000
connectTimeout=10000
pingConnectionInterval=0
pingTimeout=1000
with password auth

**Comment by mrniko** [comment]
increase `subscriptionsPerConnection` and/or `subscriptionConnectionPoolSize` params

**Comment by archmisha** [comment]
Hi,
The defaults are subscriptionsPerConnection=5 and subscriptionConnectionPoolSize=50
Does it mean in reality we have 5*50=250 subscriptions?
What are subscriptions used for?
Since i don't understand how we can even reach this high number for performing locking operation. (does it affect only locking?)
Can you shed some additional information please.

**Comment by mrniko** [comment]
it affects all objects that use PubSub, like RLock, RPermitExpirableSemaphore, RSemaphore

**Comment by archmisha** [comment]
Thanks,
Does it makes sense to double subscriptionsPerConnection from 5 to 10 in order to not increase amount of connections?
BTW does it makes sense 250 is too low?

**Comment by mrniko** [comment]
I would recommend first to try to increase `subscriptionsPerConnection` parameter.

> BTW does it makes sense 250 is too low?

Depends on locks amount and threads amount use them.

**Comment by NeoZephyr** [comment]
> I would recommend first to try to increase `subscriptionsPerConnection` parameter.
> 
> > BTW does it makes sense 250 is too low?
> 
> Depends on locks amount and threads amount use them.

Can these two parameters be set very large? How do they relate to the count of locks and threads, and what kind of relationship do they have? Let's say I start 20 threads and each thread requests 5 read/write locks and lock

**Comment by sampopes** [comment]
Some light here would definitely help. There is nothing on internet explaining it.(Even SO is out of answers)
