### ISSUE TITLE
Getting Redisson is shutdown

### ISSUE THREAD

**Issue by jchobantonov** [redisson/redisson#1872]
### Expected behavior
Not throwing RedissonShutdownException

### Actual behavior
Throwing RedissonShutdownException

### Steps to reproduce or test case
One of our WAR did not start and I thing this have something to do with RedissonShutdownException

### Redisson version
redisson-tomcat-8-2.15.1-SNAPSHOT.jar
redisson-all-2.15.1-SNAPSHOT.jar
Tomcat 8.5.35

### Redisson configuration

    <Manager className="org.redisson.tomcat.JndiRedissonSessionManager" jndiName="session/redisson"  readMode="REDIS"
		 updateMode="DEFAULT"/>

**Comment by jchobantonov** [comment]
One of our web application did not get started because of internal issue that we have but other web applications did started up - I'm able to access them via web interface but as soon as we hit the http session we are getting this exception:

```
org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:683)
	at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:662)
	at org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:427)
	at org.redisson.RedissonMap.putAllAsync(RedissonMap.java:365)
	at org.redisson.RedissonMap.putAll(RedissonMap.java:296)
	at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:306)
	at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:284)
	at org.redisson.tomcat.RedissonSessionManager.add(RedissonSessionManager.java:203)
	at org.apache.catalina.session.StandardSession.setId(StandardSession.java:365)
	at org.apache.catalina.session.StandardSession.setId(StandardSession.java:349)
	at org.redisson.tomcat.RedissonSessionManager.createSession(RedissonSessionManager.java:126)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3075)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2729)
	at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:236)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
	at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
	at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
	at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
	at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
	at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:811)
```

Redis server is working on localhost and I can connect to it using RedisDesktopManager app. - There is no exception during startup from redisson

Probably because the one of our web application did not start up Tomcat is trying to shutdown the session manager and from there we are closing global JNDI redisson client?
@mrniko

**Comment by jchobantonov** [comment]
in RedissonSessionManager do:

```
    @Override
    protected void stopInternal() throws LifecycleException {
        super.stopInternal();
        
        setState(LifecycleState.STOPPING);
        
        try {
        	shutdownRedisson();
        } catch (Exception e) {
            throw new LifecycleException(e);
        }
        
    }
    
    protected void shutdownRedisson() {
        if (redisson != null) {
            redisson.shutdown();
        }
    }
```

and in JndiRedissonSessionManager do:
```
    @Override
    protected void shutdownRedisson() {
    	//do not shutdown shared JNDI redisson client
    }
```

**Comment by jchobantonov** [comment]
@mrniko ^

**Comment by jchobantonov** [comment]
You should close JNDI RedissonClient by using closeMethod in Resource configuration:
```
    <Resource 
	    name="session/redisson"
	    auth="Container"
	    factory="org.redisson.JndiRedissonFactory"
	    configPath="${catalina.home}/conf/redisson.yaml"
	    closeMethod="shutdown"
	/>
```
so that once the JNDI is unbound then to shutdown redisson - you could update your documentation so others will not forget to add the closeMethod to properly close the JNDI resource

Also could you implement java.lang.AutoCloseable interface for RedissonClient like that:
```
public class RedisClient implements AutoCloseable {
    @Override
    public void close() {
    	shutdown();
    }
}
```

then closeMethod configuration could become closeMethod="close" (as it is with DBCP BasicDataSource)

@mrniko ^

**Comment by mrniko** [comment]
Thanks for pointing out! I updated Tomcat documentation.

**Comment by jchobantonov** [comment]
@mrniko  but you did not update RedissonSessionManager and JndiRedissonSessionManager to master - so the manager is still going to shutdown the JNDI RedissonClient if the RedossonSessionManager of at least one of the web app shutdown - which is incorrect

See https://github.com/redisson/redisson/issues/1872#issuecomment-455787344

**Comment by mrniko** [comment]
Sorry, my mistake

**Comment by mrniko** [comment]
I applied your fix. Thank you!
