### ISSUE TITLE
RBatch bug when redis sentinel slave restart

### ISSUE THREAD

**Issue by linmingchang** [redisson/redisson#1887]
### Expected behavior
use Rbatch to perform LRANGE requests

### Actual behavior
I use redis sentinel mode. 
When using Rbatch to perform LRANGE requests. If the redis slave  restart at this time, the redisson client will replay the LRANGE request until the program is restarted.

### Steps to reproduce or test case

1. use Rbatch to perform LRANGE requests（Keep request pressure）
2. restart redis slave（sentinel mode）

### Redis version 
4.0.9

### Redisson version
3.5.7

### Redisson configuration
```properties
/redisson/order=codec=org.redisson.client.codec.StringCodec
/redisson/order=database=0
/redisson/order=masterAddress=192.168.0.x:6384
/redisson/order=masterName=pre_order
/redisson/order=password=xxx
/redisson/order=sentinelAddresses[0]=192.168.0.x:26379
/redisson/order=sentinelAddresses[1]=192.168.0.x:26379
/redisson/order=sentinelAddresses[2]=192.168.0.x:26379
/redisson/order=slaveAddress=192.168.0.xx:6384
/redisson=codec=org.redisson.client.codec.StringCodec
/redisson=database=0
/redisson=masterAddress=192.168.0.x:6316
/redisson=masterName=pre
/redisson=password=xxxx
/redisson=sentinelAddresses[0]=192.168.0.x:26379
/redisson=sentinelAddresses[1]=192.168.0.x:26379
/redisson=sentinelAddresses[2]=192.168.0.xx:26379
/redisson=slaveAddress=192.168.0.xx:6316
```

**Comment by linmingchang** [comment]
similar issue：
[1012](https://github.com/redisson/redisson/issues/1012)

**Comment by linmingchang** [comment]
> @linmingchang
> 
> I think similar to this one #1567. Checked it with the latest version and unable reproduce

ok. i will try it later

**Comment by linmingchang** [comment]
> @linmingchang
> 
> I think similar to this one #1567. Checked it with the latest version and unable reproduce

ok. i will try it later

**Comment by linmingchang** [comment]
@mrniko 
I tried the 3.10.1 version and the problem still exists.

my test code
```java
@RestController
@RequestMapping
@Slf4j
public class RedissonTestController {

    private RedissonClient redissonClient;

    @PostConstruct
    public void init(){
        Config config = new Config();
        config.setCodec(new StringCodec());
        config.setReferenceEnabled(false);
        config.useSentinelServers()
                .setMasterName("pre")
                .addSentinelAddress("redis://192.168.0.10:26379","redis://192.168.0.11:26379","redis://192.168.0.12:26379")
                .setPassword("123456")
                .setDatabase(0);
        redissonClient = Redisson.create(config);
    }


    @PostMapping("/redisson")
    public Map test() {

        List<String> keys = new ArrayList<>();
        keys.add("key1");
        keys.add("key2");
        keys.add("key3");
        keys.add("key4");
        keys.add("key5");
        keys.add("key6");
        keys.add("key7");
        keys.add("key8");
        keys.add("key9");
        keys.add("key10");

        Map<String, List<String>> result = listAll(keys,String.class);

        Map<String, Object> rtnMap = new HashMap<>();
        rtnMap.put("errcode", 0);
        rtnMap.put("result", result.size());
        rtnMap.put("errmsg", "OK");
        return rtnMap;
    }

    public <V> Map<String, List<V>> listAll(List<String> keys, Class<V> clazz) {
        keys = keys.stream().distinct().collect(Collectors.toList());
        RBatch batch = redissonClient.createBatch();
        List<RFuture<List<V>>> resultFutures = new ArrayList<>();
        for (String key : keys) {
            RListAsync<V> list = batch.getList(key);
            RFuture<List<V>> val = list.readAllAsync();
            resultFutures.add(val);
        }
        batch.execute();
        Map<String, List<V>> result = new HashMap<>();
        int index = 0;
        for (RFuture<List<V>> val : resultFutures) {
            result.put(keys.get(index++), val.getNow().stream().map(v -> JSON.parseObject(v.toString(), clazz)).collect(Collectors.toList()));
        }
        return result;
    }

}
```

**Comment by linmingchang** [comment]
![image](https://user-images.githubusercontent.com/18035905/51781687-17ff7600-2157-11e9-8caa-4ec4dc0f7e81.png)

**Comment by linmingchang** [comment]
logs:
```
org.redisson.client.WriteRedisConnectionException: Can't write command batch to channel: [id: 0xf3aaa04d, L:0.0.0.0/0.0.0.0:36131 ! R:192.168.0.12/192.168.0.12:6316]
	at org.redisson.command.CommandBatchService.checkWriteFuture(CommandBatchService.java:815) ~[redisson-3.10.1.jar!/:na]
	at org.redisson.command.CommandBatchService.access$900(CommandBatchService.java:75) ~[redisson-3.10.1.jar!/:na]
	at org.redisson.command.CommandBatchService$13.operationComplete(CommandBatchService.java:900) ~[redisson-3.10.1.jar!/:na]
	at org.redisson.command.CommandBatchService$13.operationComplete(CommandBatchService.java:897) ~[redisson-3.10.1.jar!/:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:991) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:873) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1365) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1127) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1174) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1098) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[netty-all-4.1.33.Final.jar!/:4.1.33.Final]

2019-01-26 10:29:32.191  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:32.207  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : slave: 192.168.0.12:6316 has down
2019-01-26 10:29:33.209  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:34.210  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:35.212  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:36.213  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:37.215  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:38.216  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:39.218  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
2019-01-26 10:29:40.220  WARN 9724 --- [isson-netty-1-5] o.r.c.SentinelConnectionManager          : Skipped slave up 192.168.0.12:6316 for master redis://192.168.0.10:6316 differs from current redis://192.168.0.11:6316
```

**Comment by mrniko** [comment]
How many slaves do you have and requests per seconds before failover?

**Comment by mrniko** [comment]
Explained in https://github.com/redisson/redisson/issues/1567#issuecomment-459736719

**Comment by linmingchang** [comment]
On version 3.10.2, this issue has been fixed
