### ISSUE TITLE
Huge log messages

### ISSUE THREAD

**Issue by valodzka** [redisson/redisson#1889]
Issue similar to #1035 (redisson 3.10.1), probably introduced in commit 60352b8490220cfeecc99ca51d73b867f563838c (or may be f0953279b4da70b7d26defdb009758d45ac25711).

Recieve big message, get timeout, **tens megabytes** log message:

       CommandDecoder:  Unable to decode data. reply <lot of binary data> channel: [id: 0xa7e47d53....], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@7df03a9c(failure: java.util.concurrent.CancellationException)], command=(HMGET), params=[n-notifications-m, PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), ...], codec=org.redisson.codec.CompositeCodec@9dfefa0d]                                                                                                        
       java.util.concurrent.CancellationException: null
        at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2396)                                                      
        at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:239)                                                                                
        at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:941)                                                                     
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)                                                               
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)                                                
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)                                                                      
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mrniko** [comment]
Fixed! Thanks for report
