### ISSUE TITLE
Unable to decode data.

### ISSUE THREAD

**Issue by hlms** [redisson/redisson#1899]
### Expected behavior
No exception

### Actual behavior
```
2019-02-04 04:27:24,749-0800 [toe=009i5jwyj7erbk] [redisson-netty-1-2] ERROR - Unable to decode data. reply: *124
$4114
....
....
, channel: [id: 0xf3f268b3, L:/10.1.1.1:40115 - R:my.server.1/10.1.2.2:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@12ec0a16(failure: java.util.concurrent.CancellationException)], command=(HMGET), params=[mykey, param2, ...], codec=org.redisson.codec.CompositeCodec@d2717648] java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263) ~[?:1.8.0_181]
	at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:239) ~[redisson-3.10.1.jar:?]
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:941) ~[redisson-3.10.1.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

### Steps to reproduce or test case
I don't have exact steps. but I have the following information:
It was working earlier with redisson 2.14.1 with Oracle java 7.
It is broken with redisson 3.10.1 with OpenJdk java 8.

### Redis version
4.0.11

### Redisson version
3.10.1

### Redisson configuration
 ```
      {
      	"replicatedServersConfig": {
      		"idleConnectionTimeout": 10000,
      		"pingTimeout": 1000,
      		"connectTimeout": 10000,
      		"timeout": 10000,
      		"retryAttempts": 3,
      		"retryInterval": 1500,
      		"subscriptionsPerConnection": 5,
      		"sslEnableEndpointIdentification": true,
      		"sslProvider": "JDK",
      		"pingConnectionInterval": 0,
      		"keepAlive": false,
      		"tcpNoDelay": false,
      		"loadBalancer": {
      			"class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
      		},
      		"slaveConnectionMinimumIdleSize": 32,
      		"slaveConnectionPoolSize": 64,
      		"failedSlaveReconnectionInterval": 3000,
      		"failedSlaveCheckInterval": 180000,
      		"masterConnectionMinimumIdleSize": 32,
      		"masterConnectionPoolSize": 64,
      		"readMode": "MASTER_SLAVE",
      		"subscriptionMode": "MASTER",
      		"subscriptionConnectionMinimumIdleSize": 1,
      		"subscriptionConnectionPoolSize": 50,
      		"dnsMonitoringInterval": 5000,
      		"nodeAddresses": [
      			"redis://my.server.1:6379",
      			"redis://my.server.2:6379"
      		],
      		"scanInterval": 2000,
      		"database": 0,
      		"slaveSubscriptionConnectionPoolSize": 50,
      		"slaveSubscriptionConnectionMinimumIdleSize": 1
      	},
      	"threads": 0,
      	"nettyThreads": 0,
      	"referenceCodecProvider": {
      		"class": "org.redisson.codec.DefaultReferenceCodecProvider"
      	},
      	"referenceEnabled": true,
      	"transportMode": "NIO",
      	"lockWatchdogTimeout": 30000,
      	"keepPubSubOrder": true,
      	"useScriptCache": false,
      	"addressResolverGroupFactory": {
      		"class": "org.redisson.connection.DnsAddressResolverGroupFactory"
      	},
      	"useLinuxNativeEpoll": false
      }
```

How to fix this?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1893

**Comment by mrniko** [comment]
@hlms 

Already published

**Comment by hlms** [comment]
> @hlms
> 
> Already published

Thank you :)

**Comment by hlms** [comment]
@mrniko ,
Attempted to upgrade redisson client, and bumped into this issue: https://github.com/redisson/redisson/issues/1908.
