### ISSUE TITLE
Why the redis cluster port [nodeAddresses] in redission.yaml file should be slave(non-master) node port?

### ISSUE THREAD

**Issue by alexanderlc6** [redisson/redisson#1904]
### Expected behavior
Both master or slave port can be configured at the config item [nodeAddresses].

### Actual behavior
Should be slave(non-master) node port, but why? When I configure master node port, below exception stack block always appears, output the message saying that the configured master node port cannot be connected.

### Steps to reproduce or test case
1) Redis server installation version is 5.0.3, start the cluster mode with command:
./create-cluster start
(3 master 3 slave nodes are now **running**..)

2)Check if all redis slots have been covered or not:
./redis-cli --cluster check localhost:30001

Command output log(everything is ok):
>>> Performing Cluster Check (using node localhost:30001)
M: b76aae890a6726bf30e579d80112a11d7d21b857 localhost:**30001**
   slots:[0-5460] (5461 slots) master
   1 additional replica(s)
M: db3f19ac2c5fbae73812dfb77ddeecfb83962ed1 129.211.101.192:**30002**
   slots:[5461-10922] (5462 slots) master
   1 additional replica(s)
S: 3ead9fddc90a907baecc2401b63887aad9924223 129.211.101.192:**30006**
   slots: (0 slots) slave
   replicates db3f19ac2c5fbae73812dfb77ddeecfb83962ed1
S: 96789232ea1d4e913e4a00b86fbe4638d2d9375e 129.211.101.192:**30005**
   slots: (0 slots) slave
   replicates b76aae890a6726bf30e579d80112a11d7d21b857
S: b9d6332b52a488e462d6c17ddfac13f499011ab7 129.211.101.192:**30004**
   slots: (0 slots) slave
   replicates 63ab0571c2df794a6c4c45f13917e59c9952cf1a
M: 63ab0571c2df794a6c4c45f13917e59c9952cf1a 129.211.101.192:**30003**
   slots:[10923-16383] (5461 slots) master
   1 additional replica(s)
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.

3)Configure the redission.yaml file:
clusterServersConfig:
  ...
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  - "redis://10.19.131.180:30001"  #30001 is master node port of redis cluster
(Though use another 2 master node port: 30002 and 30003, same exception result as below).

4)Run my Springboot service(from main() in Application), exception then occured:
2019-02-11 16:51:26 [redisson-netty-1-5] INFO  o.r.c.p.MasterPubSubConnectionPool:168 - 1 connections initialized for 129.211.101.192/129.211.101.192:30002
2019-02-11 16:51:26 [redisson-netty-1-3] INFO  o.r.c.pool.MasterConnectionPool:168 - 5 connections initialized for 129.211.101.192/129.211.101.192:30003
2019-02-11 16:51:26 [redisson-netty-1-8] INFO  o.r.cluster.ClusterConnectionManager:268 - master: redis://129.211.101.192:30003 added for slot ranges: [[10923-16383]]
2019-02-11 16:51:26 [redisson-netty-1-8] INFO  o.r.c.p.MasterPubSubConnectionPool:168 - 1 connections initialized for 129.211.101.192/129.211.101.192:30003
2019-02-11 16:51:26 [redisson-netty-1-5] INFO  o.r.cluster.ClusterConnectionManager:268 - master: redis://129.211.101.192:30002 added for slot ranges: [[5461-10922]]
2019-02-11 16:51:26 [redisson-netty-1-5] INFO  o.r.c.pool.MasterConnectionPool:168 - 5 connections initialized for 129.211.101.192/129.211.101.192:30002
2019-02-11 16:51:36 [redisson-netty-1-1] ERROR o.r.cluster.ClusterConnectionManager:203 - **Can't connect to master: redis://172.17.16.9:30001 with slot ranges: [[0-5460]]**
2019-02-11 16:51:36 [main] ERROR o.h.c.r.client.RedisClientFactory:50 - Fail to create RedisClient.
org.redisson.client.RedisConnectionException: **Not all slots are covered! Only 10923 slots are avaliable**
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:168)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:198)
	at org.redisson.Redisson.<init>(Redisson.java:123)
	at org.redisson.Redisson.create(Redisson.java:162)
	at org.hibernate.cache.redis.client.RedisClientFactory.createRedisClient(RedisClientFactory.java:47)
	at org.hibernate.cache.redis.client.RedisClientFactory.createRedisClient(RedisClientFactory.java:64)
	at org.hibernate.cache.redis.client.RedisClientFactory.createRedisClient(RedisClientFactory.java:83)
	at org.hibernate.cache.redis.hibernate52.AbstractRedisRegionFactory.createRedisClient(AbstractRedisRegionFactory.java:65)
	at org.hibernate.cache.redis.hibernate52.RedisRegionFactory.start(RedisRegionFactory.java:48)
	at org.hibernate.cache.spi.RegionFactory.start(RegionFactory.java:63)
	at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:71)
	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:28)
	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:20)
	at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:59)
...
	at com.sp.Application.main(Application.java:37)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: 172.17.16.9/172.17.16.9:30001
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-02-11 16:51:36 [main] ERROR o.h.c.r.h.RedisRegionFactory:53 - Fail to start RedisRegionFactory.
java.lang.RuntimeException: org.redisson.client.RedisConnectionException: Not all slots are covered! Only 10923 slots are avaliable
	at org.hibernate.cache.redis.client.RedisClientFactory.createRedisClient(RedisClientFactory.java:51)
	at org.hibernate.cache.redis.client.RedisClientFactory.createRedisClient(RedisClientFactory.java:64)
	at org.hibernate.cache.redis.client.RedisClientFactory.createRedisClient(RedisClientFactory.java:83)
...

When I try to configure the port with slave port(30004,30005 or 30006), however, it worked well:
2019-02-11 17:35:59 [redisson-netty-1-1] INFO  o.r.c.pool.MasterConnectionPool:168 - 5 connections initialized for 129.211.101.192/129.211.101.192:30001
2019-02-11 17:36:09 [main] INFO  o.h.c.r.h.RedisRegionFactory:51 - **RedisRegionFactory is started.**
2019-02-11 17:36:09 [main] INFO  o.h.cache.spi.UpdateTimestampsCache:48 - HHH000250: Starting update timestamps cache at region: hibernate.org.hibernate.cache.spi.UpdateTimestampsCache
2019-02-11 17:36:09 [main] INFO  o.h.c.internal.StandardQueryCache:81 - HHH000248: Starting query cache at region: org.hibernate.cache.internal.StandardQueryCache

I'm curious about how this happened, since all slots have been already checked to be covered and the log says all nodes have had been connected before the exception message printed out. Hope someone can help to analyze this issue and discuss with me, thanks a lot!

### Redis version
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>3.9.1</version>
            </dependency>

### Redisson version
            <dependency>
                <groupId>com.github.debop</groupId>
                <artifactId>hibernate-redis</artifactId>
                <version>2.4.0</version>   
            </dependency>

### Redisson configuration
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 5
  slaveConnectionPoolSize: 128
  masterConnectionMinimumIdleSize: 5
  masterConnectionPoolSize: 128
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  - "redis://xxx.xxx.1x1.1xx:30004"    #Changed to slave node port, exception disappeared,**WHY**?
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.SnappyCodec> {}

**Comment by jackygurui** [comment]
> Performing Cluster Check (using node localhost:30001)
> M: b76aae890a6726bf30e579d80112a11d7d21b857 localhost:**30001**
> slots:[0-5460] (5461 slots) master
> 1 additional replica(s)
> M: db3f19ac2c5fbae73812dfb77ddeecfb83962ed1 129.211.101.192:**30002**
> slots:[5461-10922] (5462 slots) master
> 1 additional replica(s)
> S: 3ead9fddc90a907baecc2401b63887aad9924223 129.211.101.192:**30006**
> slots: (0 slots) slave
> replicates db3f19ac2c5fbae73812dfb77ddeecfb83962ed1
> S: 96789232ea1d4e913e4a00b86fbe4638d2d9375e 129.211.101.192:**30005**
> slots: (0 slots) slave
> replicates b76aae890a6726bf30e579d80112a11d7d21b857
> S: b9d6332b52a488e462d6c17ddfac13f499011ab7 129.211.101.192:**30004**
> slots: (0 slots) slave
> replicates 63ab0571c2df794a6c4c45f13917e59c9952cf1a
> M: 63ab0571c2df794a6c4c45f13917e59c9952cf1a 129.211.101.192:**30003**
> slots:[10923-16383] (5461 slots) master
> 1 additional replica(s)
> [OK] All nodes agree about slots configuration.
> Check for open slots...
> Check slots coverage...
> [OK] All 16384 slots covered.

It looks like one of the master is broadcasting its service on a different subnet to the rest of the nodes.

**Comment by alexanderlc6** [comment]
> > Performing Cluster Check (using node localhost:30001)
> > M: b76aae890a6726bf30e579d80112a11d7d21b857 localhost:**30001**
> > slots:[0-5460] (5461 slots) master
> > 1 additional replica(s)
> > M: db3f19ac2c5fbae73812dfb77ddeecfb83962ed1 129.211.101.192:**30002**
> > slots:[5461-10922] (5462 slots) master
> > 1 additional replica(s)
> > S: 3ead9fddc90a907baecc2401b63887aad9924223 129.211.101.192:**30006**
> > slots: (0 slots) slave
> > replicates db3f19ac2c5fbae73812dfb77ddeecfb83962ed1
> > S: 96789232ea1d4e913e4a00b86fbe4638d2d9375e 129.211.101.192:**30005**
> > slots: (0 slots) slave
> > replicates b76aae890a6726bf30e579d80112a11d7d21b857
> > S: b9d6332b52a488e462d6c17ddfac13f499011ab7 129.211.101.192:**30004**
> > slots: (0 slots) slave
> > replicates 63ab0571c2df794a6c4c45f13917e59c9952cf1a
> > M: 63ab0571c2df794a6c4c45f13917e59c9952cf1a 129.211.101.192:**30003**
> > slots:[10923-16383] (5461 slots) master
> > 1 additional replica(s)
> > [OK] All nodes agree about slots configuration.
> > Check for open slots...
> > Check slots coverage...
> > [OK] All 16384 slots covered.
> 
> It looks like one of the master is broadcasting its service on a different subnet to the rest of the nodes.

Thanks,but how do you figure out this point mind? I guess the service should be the inner redission netty component service, or may be health check by socket,right?However, why this affect the configuration of redis port in yaml file?
