### ISSUE TITLE
2.14.1 works fine vs 2.15.1 giving RedisResponseTimeoutException

### ISSUE THREAD

**Issue by hlms** [redisson/redisson#1908]
### Expected behavior
Should work fine

### Actual behavior
RedisResponseTimeoutException

3.10.2:
```
2019-02-08 02:11:00,670-0800 [toe=0012bpqw2iqela] [Pool Worker - 18] ERROR - org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. Command: (HMGET), params: [key-in-redis, PooledUnsafeDirectByteBuf(ridx: 0, widx: 92, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 98, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 74, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 99, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 105, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 54, cap: 256), ...], channel: [id: 0xb1175b78, L:/10.1.10.17:9350 - R:my.server.1.com/10.1.2.7:6379] org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. Command: (HMGET), params: [key-in-redis, PooledUnsafeDirectByteBuf(ridx: 0, widx: 92, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 98, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 74, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 99, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 105, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 54, cap: 256), ...], channel: [id: 0xb1175b78, L:/10.1.10.17:9350 - R:my.server.1.com/10.1.2.7:6379]
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:960) ~[redisson-3.10.2.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
```

2.15.2:	
```
2019-02-12 00:14:31,505-0800 [toe=000tq6l5rb3ifx] [Pool Worker - 18] ERROR - org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. Command: (HMGET), params: [key-in-redis, PooledUnsafeDirectByteBuf(ridx: 0, widx: 92, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 98, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 74, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 99, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 105, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 54, cap: 256), ...], channel: [id: 0xdcc6a81d, L:/10.1.10.17:49323 - R:my.server.1.com/10.1.2.7:6379] org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. Command: (HMGET), params: [key-in-redis, PooledUnsafeDirectByteBuf(ridx: 0, widx: 92, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 98, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 74, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 99, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 105, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 54, cap: 256), ...], channel: [id: 0xdcc6a81d, L:/10.1.10.17:49323 - R:my.server.1.com/10.1.2.7:6379]
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:960) ~[redisson-2.15.2.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
```
	
2.15.1:
```
2019-02-12 01:56:50,618-0800 [toe=00081ibjglswzd] [Pool Worker - 18] ERROR - org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. Command: (HMGET), params: [key-in-redis, get-values-requested, ...], channel: [id: 0x0fb8c255, L:/10.1.10.17:64746 - R:my.server.1.com/10.1.2.7:6379] org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. Command: (HMGET), params: [key-in-redis, get-values-requested, ...], channel: [id: 0x0fb8c255, L:/10.1.10.17:64746 - R:my.server.1.com/10.1.2.7:6379]
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:959) ~[redisson-2.15.1.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
```

### Steps to reproduce or test case
I have no exact steps. But, my code works fine with 2.14.1. With 2.15.1, 2.15.2, 3.10.2, it always fails.

### Redis version
4.0.11

### Redisson version
3.10.2

### Redisson configuration for 2.14.1:
```
{
     	"replicatedServersConfig": {
     		"idleConnectionTimeout": 10000,
     		"pingTimeout": 1000,
     		"connectTimeout": 10000,
     		"timeout": 10000,
     		"retryAttempts": 3,
     		"retryInterval": 1500,
     		"subscriptionsPerConnection": 5,
     		"sslEnableEndpointIdentification": true,
     		"sslProvider": "JDK",
     		"pingConnectionInterval": 0,
     		"keepAlive": false,
     		"tcpNoDelay": false,
     		"loadBalancer": {
     			"class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
     		},
     		"slaveConnectionMinimumIdleSize": 32,
     		"slaveConnectionPoolSize": 64,
     		"failedSlaveReconnectionInterval": 3000,
     		"failedSlaveCheckInterval": 180000,
     		"masterConnectionMinimumIdleSize": 32,
     		"masterConnectionPoolSize": 64,
     		"readMode": "MASTER_SLAVE",
     		"subscriptionMode": "MASTER",
     		"subscriptionConnectionMinimumIdleSize": 1,
     		"subscriptionConnectionPoolSize": 50,
     		"dnsMonitoringInterval": 5000,
     		"nodeAddresses": [
     			"redis://my.server.1:6379",
     			"redis://my.server.2:6379"
     		],
     		"scanInterval": 2000,
     		"database": 0,
     		"slaveSubscriptionConnectionPoolSize": 50,
     		"slaveSubscriptionConnectionMinimumIdleSize": 1
     	},
     	"threads": 0,
     	"nettyThreads": 0,
     	"referenceCodecProvider": {
     		"class": "org.redisson.codec.DefaultReferenceCodecProvider"
     	},
     	"referenceEnabled": true,
     	"transportMode": "NIO",
     	"lockWatchdogTimeout": 30000,
     	"keepPubSubOrder": true,
     	"useScriptCache": false,
     	"addressResolverGroupFactory": {
     		"class": "org.redisson.connection.DnsAddressResolverGroupFactory"
     	},
     	"useLinuxNativeEpoll": false
}
```

**Comment by mrniko** [comment]
Is that the same for 2.15.0 / 3.10.0 as well ?
Only for HMGET command?
Could you provide test case?

**Comment by mrniko** [comment]
Default codec has been changed to FSTCodec since 2.15.0 / 3.10.0 version. Try to use `org.redisson.codec.JsonJacksonCodec` for your case

**Comment by hlms** [comment]
Yes, the problem occurs for HMGET command for 2.15.0 and 3.10.0 .

For 3.10.2, I've collected debug logs for redisson: [cleaned-up-log.txt](https://github.com/redisson/redisson/files/2859845/cleaned-up-log.txt)

I guess the problem occurs after this line:

```
2019-02-12 23:06:31,137-0800 [toe=001urprlk4g0cv] [redisson-netty-1-23] WARN  - response has been skipped due to timeout! channel: [id: 0xab19aebc, L:/10.1.10.17:31630 - R:primary.server.com/10.1.2.7:6379], command: (HMGET), params: [my_key_in_redis_keypart1:keypart2_type2, PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 43, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 92, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 104, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 39, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 101, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 91, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 54, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), ...], result: {around_20k_characters_text_removed_by_me}
```
Note that there was a large text (~20k characters) in the place of around_20k_characters_text_removed_by_me above.

**Comment by mrniko** [comment]
Try to switch back to `org.redisson.codec.JsonJacksonCodec` codec. Or set nettyThreads to 32 as this is default value now.

**Comment by hlms** [comment]
1. The configuration I provided earlier was read in 2.14.1.
1. We have `new CompositeCodec(new StringCodec(), new LZ4Codec(),  new SerializationCodec());`. It was same earlier also.

**Comment by hlms** [comment]
@mrniko ,
Configuration dumped by 3.10.2:
```json
{
	"replicatedServersConfig": {
		"idleConnectionTimeout": 10000,
		"pingTimeout": 1000,
		"connectTimeout": 10000,
		"timeout": 10000,
		"retryAttempts": 3,
		"retryInterval": 1500,
		"password": "password",
		"subscriptionsPerConnection": 5,
		"sslEnableEndpointIdentification": true,
		"sslProvider": "JDK",
		"pingConnectionInterval": 0,
		"keepAlive": false,
		"tcpNoDelay": false,
		"loadBalancer": {
			"class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
		},
		"slaveConnectionMinimumIdleSize": 32,
		"slaveConnectionPoolSize": 64,
		"failedSlaveReconnectionInterval": 3000,
		"failedSlaveCheckInterval": 180000,
		"masterConnectionMinimumIdleSize": 32,
		"masterConnectionPoolSize": 64,
		"readMode": "MASTER_SLAVE",
		"subscriptionMode": "MASTER",
		"subscriptionConnectionMinimumIdleSize": 1,
		"subscriptionConnectionPoolSize": 50,
		"dnsMonitoringInterval": 5000,
		"nodeAddresses": [
			"rediss://my.server.1:6379",
			"rediss://my.server.2:6379"
		],
		"scanInterval": 2000,
		"database": 0,
		"slaveSubscriptionConnectionPoolSize": 50,
		"slaveSubscriptionConnectionMinimumIdleSize": 1
	},
	"threads": 16,
	"nettyThreads": 32,
	"referenceEnabled": true,
	"transportMode": "NIO",
	"lockWatchdogTimeout": 30000,
	"keepPubSubOrder": true,
	"decodeInExecutor": false,
	"useScriptCache": false,
	"addressResolverGroupFactory": {
		"class": "org.redisson.connection.DnsAddressResolverGroupFactory"
	}
}
```

nettyThreads is already 32.

**Comment by mrniko** [comment]
Could you try to change netty version to 4.1.31.Final?

**Comment by hlms** [comment]
> Could you try to change netty version to 4.1.31.Final?

Redisson 2.14.1 uses netty version 4.1.31.Final. And my test runs successfully with 2.14.1.
Are you suggesting some other mix and match of libraries?

**Comment by mrniko** [comment]
@hlms 

Yes, could you try Redisson 3.10.0 and Netty 4.1.31.Final?

**Comment by hlms** [comment]
Tried using redisson 3.10.0 and netty 4.1.31.Final.

Got "Unable to decode data." error as mentioned in https://github.com/redisson/redisson/issues/1899.

### List of jars used
redisson-3.10.0.jar
netty-buffer-4.1.31.Final.jar
netty-codec-4.1.31.Final.jar
netty-codec-dns-4.1.31.Final.jar
netty-codec-http-4.1.28.Final.jar
netty-common-4.1.31.Final.jar
netty-handler-4.1.31.Final.jar
netty-resolver-4.1.31.Final.jar
netty-resolver-dns-4.1.31.Final.jar
netty-transport-4.1.31.Final.jar
netty-transport-native-epoll-4.1.28.Final-linux-x86_64.jar
netty-transport-native-kqueue-4.1.28.Final-osx-x86_64.jar
netty-transport-native-unix-common-4.1.28.Final.jar

**Comment by mrniko** [comment]
Could you try 3.10.2 with 4.1.31.Final then?

Also please replace libs with 4.1.28.Final to 4.1.31.Final

**Comment by hlms** [comment]
redisson 3.10.2 with netty 4.1.31.Final...
```
2019-02-13 21:47:21,646-0800 [toe=000makoutv6qtu] [Pool Worker - 18] ERROR - org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=32, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://my.server.1.com:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@10054256 [redisClient=[addr=rediss://my.server.2.com:6379], channel=[id: 0x99fd6d46, L:/10.1.10.17:20516 - R:my.server.2.com/10.1.2.16:6379]], current command in queue: null, command: (HMGET), command params: [kp1:kp21, SimpleLeakAwareByteBuf(PooledUnsafeDirectByteBuf(ridx: 0, widx: 92, cap: 512)), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 98, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 74, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 99, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 105, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 54, cap: 256), ...] after 3 retry attempts org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=32, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://my.server.1.com:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@10054256 [redisClient=[addr=rediss://my.server.2.com:6379], channel=[id: 0x99fd6d46, L:/10.1.10.17:20516 - R:my.server.2.com/10.1.2.16:6379]], current command in queue: null, command: (HMGET), command params: [kp1:kp21, SimpleLeakAwareByteBuf(PooledUnsafeDirectByteBuf(ridx: 0, widx: 92, cap: 512)), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 98, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 74, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 99, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 105, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 54, cap: 256), ...] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:734) ~[redisson-3.10.2.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
```

**Comment by mrniko** [comment]
@hlms 

Thanks for your feedback. I'll investigate this issue

**Comment by mrniko** [comment]
I made a build with some improvements. Could you give it a try and give your feedback? 
[redisson-3.10.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/2874490/redisson-3.10.3-SNAPSHOT.jar.zip)

**Comment by hlms** [comment]
For now, we have reverted to 2.14.1.
Will let you know once I get chance to test with this jar.

**Comment by mrniko** [comment]
Fixed
