### ISSUE TITLE
RedissonNamespaceHandlerSupport fail to load at Tomcat startup

### ISSUE THREAD

**Issue by marcobrizi** [redisson/redisson#1920]
The scenario is a Spring based application deployed on top of Tomcat 8 configured to use the RedissonSessionManager. 

At startup, Spring initialization try to discover on classloader the namespace handlers including the org.redisson.spring.support.RedissonNamespaceHandlerSupport provided with the reddisson-all.jar library.

At this point the init of this handler fails with a NoClassDefFoundError probably because the Tomcat classloader cannot see Spring dependencies that are loaded by webapp classloader.

Unfortunately, after this WARN, the RedissonSessionManager doesn't work properly and new sessions are not stored on Redis.

Here the complete stacktrace:
`
15-Feb-2019 15.48.23 [Appalti]|WARN |Ignoring namespace handler [org.redisson.spring.support.RedissonNamespaceHandlerSupport]: problem with handler class file or dependent class
java.lang.NoClassDefFoundError: org/springframework/beans/factory/xml/NamespaceHandlerSupport
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1315)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1163)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:201)
	at org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.initHandlerMappings(DefaultNamespaceHandlerResolver.java:117)
	at org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.<init>(DefaultNamespaceHandlerResolver.java:96)
	at org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.<init>(DefaultNamespaceHandlerResolver.java:82)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.createDefaultNamespaceHandlerResolver(XmlBeanDefinitionReader.java:488)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.createReaderContext(XmlBeanDefinitionReader.java:477)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:458)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:353)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:280)
	at org.springframework.jdbc.support.SQLErrorCodesFactory.<init>(SQLErrorCodesFactory.java:112)
	at org.springframework.jdbc.support.SQLErrorCodesFactory.<clinit>(SQLErrorCodesFactory.java:70)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:133)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:98)
	at org.springframework.jdbc.support.JdbcAccessor.getExceptionTranslator(JdbcAccessor.java:99)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:553)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:587)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:616)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:624)
	at it.eldasoft.gene.db.dao.jdbc.SqlDaoJdbc.getVectorQuery(SqlDaoJdbc.java:603)
	at it.eldasoft.gene.bl.SqlManager.getVector(SqlManager.java:184)
	at it.eldasoft.gene.bl.SqlManager.isTable(SqlManager.java:433)
	at it.eldasoft.gene.bl.SqlManager$$FastClassByCGLIB$$9be41d47.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:695)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:144)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:107)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:630)
	at it.eldasoft.gene.bl.SqlManager$$EnhancerByCGLIB$$bf7df9b3.isTable(<generated>)
	at it.eldasoft.gene.bl.SqlManager.setUserStoriaModifiche(SqlManager.java:477)
	at it.eldasoft.gene.commons.web.spring.DataSourceTransactionManagerBase.doBegin(DataSourceTransactionManagerBase.java:65)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:350)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:102)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:630)
	at it.eldasoft.gene.bl.admin.AccountManager$$EnhancerByCGLIB$$bf386373.updateLogins(<generated>)
	at it.eldasoft.gene.commons.web.struts.GeneStartupPlugIn.initConfigurabile(GeneStartupPlugIn.java:94)
	at it.eldasoft.gene.commons.web.struts.PlugInBase.initApplicazione(PlugInBase.java:257)
	at it.eldasoft.gene.commons.web.struts.PlugInBase.init(PlugInBase.java:177)
	at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:871)
	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:359)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1199)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1143)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1032)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5035)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5345)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1795)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.xml.NamespaceHandlerSupport
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 75 more
`
After some tests, we try to solve this problem by removing the following files from redisson-all-3.10.2.jar:
- META-INF/spring.factories
- META-INF/spring.handlers
- META-INF/spring.schemas
- META-INF/spring.tooling

so there is no need of Sprint integration in our case.

There is any solution/configuration we can adopt to avoid this error and keep the original library?

**Comment by mrniko** [comment]
Fixed. Thanks for report
