### ISSUE TITLE
SENTINEL_SENTINELS can not get anything, why?

### ISSUE THREAD

**Issue by HendSame** [redisson/redisson#1945]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'getRedission' threw exception; nested exception is org.redisson.client.RedisConnectionException: At least two sentinels should be defined in Redis configuration! SENTINEL SENTINELS command returns empty result!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
	... 95 common frames omitted
Caused by: org.redisson.client.RedisConnectionException: At least two sentinels should be defined in Redis configuration! SENTINEL SENTINELS command returns empty result!
	at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:159)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:231)
	at org.redisson.Redisson.<init>(Redisson.java:121)
	at org.redisson.Redisson.create(Redisson.java:164)
	at com.hikvision.hosp.ham.main.cfg.RedissonConfig.getRedission(RedissonConfig.java:79)
	at com.hikvision.hosp.ham.main.cfg.RedissonConfig$$EnhancerBySpringCGLIB$$8aeaf904.CGLIB$getRedission$1(<generated>)
	at com.hikvision.hosp.ham.main.cfg.RedissonConfig$$EnhancerBySpringCGLIB$$8aeaf904$$FastClassBySpringCGLIB$$c419b4b8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
	at com.hikvision.hosp.ham.main.cfg.RedissonConfig$$EnhancerBySpringCGLIB$$8aeaf904.getRedission(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 96 common frames omitted

when run this code :
List<Map<String, String>> sentinelSentinels = connection.sync(StringCodec.INSTANCE, RedisCommands.SENTINEL_SENTINELS, cfg.getMasterName());

sentinelSentinels size  is 0

Why?

### Redis version
4.0.2
### Redisson version
3.10.2
### Redisson configuration
![image](https://user-images.githubusercontent.com/9264192/53619565-ae2d2d00-3c2a-11e9-9eb4-c077ef3edab3.png)

![image](https://user-images.githubusercontent.com/9264192/53619608-d9178100-3c2a-11e9-91ec-67e234a5de85.png)

![image](https://user-images.githubusercontent.com/9264192/53619420-5098e080-3c2a-11e9-90fb-19609bc2224f.png)

config.useSentinelServers()
                    .setPassword(redisProperties.getPassword())
                    .setMasterName(sentinel.getMaster())
                    .addSentinelAddress("redis://10.13.69.153:26379,redis://10.33.43.37:26379")
                    .setReadMode(ReadMode.MASTER_SLAVE)
                    .setDnsMonitoringInterval(5000)
                    .setSubscriptionConnectionMinimumIdleSize(1)
                    .setSubscriptionConnectionPoolSize(50)
                    .setTimeout(3000)
                    .setConnectTimeout(10000)
                    .setIdleConnectionTimeout(10000);

**Comment by mrniko** [comment]
You need to check result of `SENTINEL SENTINELS` command

**Comment by HendSame** [comment]
@mrniko 
![image](https://user-images.githubusercontent.com/9264192/53621451-8ab9b080-3c31-11e9-94d6-b3aa029df0fb.png)
....
It is empty!

I have made the wrong configuration?
Configure the following:

![image](https://user-images.githubusercontent.com/9264192/53621520-bc327c00-3c31-11e9-99b1-748d8c3fe28d.png)

sentinel.conf
`port 26379
sentinel myid f4fd51fce9bceef34d4c579f90259268759088e8
daemonize yes
protected-mode no
logfile "./sentinel_log.log"
dir "/middleware/redis"
sentinel monitor mymaster 10.14.69.153 6379 2
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 3
sentinel current-epoch 3
`

**Comment by HendSame** [comment]
![image](https://user-images.githubusercontent.com/9264192/53622040-7b3b6700-3c33-11e9-9159-ed4e9caa40a3.png)

**Comment by HendSame** [comment]
I've solved the problem!
@mrniko thanks!

by:
sentinel.conf 
add this line :
sentinel auth-pass <master name> <password>
