### ISSUE TITLE
RedissonLock在腾讯云集群版redis加/解锁报错: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context

### ISSUE THREAD

**Issue by chuangzai** [redisson/redisson#1957]
### Redis version
redis-4.0 Tencent Cloud Cluster (腾讯云集群版)

### Redisson version
3.10.0-3.10.3

### Redisson configuration
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://10.1.1.16:6379")
                .setTimeout(3000)
                .setPassword(password);

1、腾讯云集群版对外只有一个代理IP，没有具体的子节点ip，Redisson无法配置成cluster模式，目前本地只能配置成单机模式，有没有针对腾讯云集群版方面的配置介绍？
2、使用RedissonLock 进行tryLock 或 unLock操作时，经常会出现 org.redisson.client.RedisException: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context错误。不知道有没有碰到过类似的问题可以借鉴？ (非必现，运行一段时间后会出来)

lock.tryLock场景：
org.redisson.client.RedisException: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context. channel: [id: 0xaeff9cd8, L:/172.16.0.184:60030 - R:10.1.1.16/10.1.1.16:6379] command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, redis_lock:order_center:order:update:lock:11031138634123182082, 60000, a1f84934-abba-4bf9-b076-107ef093ebf6:96]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:314)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:130)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

lock.unlock()场景：
org.redisson.client.RedisException: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context. channel: [id: 0x12f793e3, L:/172.16.0.184:60042 - R:10.1.1.16/10.1.1.16:6379] command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('publish', KEYS[2], ARGV[1]); return 1; end;..., 2, redis_lock:order_center:order:update:lock:11031138634123182082, redisson_lock__channel:{redis_lock:order_center:order:update:lock:11031138634123182082}, 0, 60000, a1f84934-abba-4bf9-b076-107ef093ebf6:124]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:314)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:130)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)  ... ...

**Comment by mrniko** [comment]
I'm afraid this question is to Tencent Cloud Cluster support team. Original version of Redis doesn't have such restriction.

**Comment by feixuwu** [comment]
there's a proxy in front of tencent cloud redis cluster, the early version of the proxy have very limit support for subscribe/unsubscribe,  the current version online have fixed the bug.

腾讯云集群版 proxy对subscribe/unsubscribe的支持有bug, 升级到最新的proxy就解决了，可以找客服升级下proxy。

**Comment by Skycat** [comment]
> there's a proxy in front of tencent cloud redis cluster, the early version of the proxy have very limit support for subscribe/unsubscribe, the current version online have fixed the bug.
> 
> 腾讯云集群版 proxy对subscribe/unsubscribe的支持有bug, 升级到最新的proxy就解决了，可以找客服升级下proxy。

Yes, we had the same problem with Tencent Cloud redis earlier, which was solved by upgrading proxy.

是的，我们早前使用腾讯云redis也遇到了相同的问题，也是反馈到客服升级proxy解决的。

**Comment by jackygurui** [comment]
@feixuwu It has been a great pleasure to work with Redis team at Tencent Cloud. 非常感谢腾讯云Redis团队的努力。

@Skycat Thanks for confirming the resolution from Tencent Cloud is effective. 感谢您再次确认。
