### ISSUE TITLE
RedissonClient shutdown() error

### ISSUE THREAD

**Issue by wshcdr** [redisson/redisson#1965]
### Expected behavior
shutdown successfully
### Actual behavior
There are errors on Eclipse console ,sort of

[redisson-netty-4-6] ERROR org.redisson.client.handler.CommandsQueue - Exception occured. Channel: [id: 0xd0d91ecc, L:/192.168.0.147:60301 - R:192.168.0.144/192.168.0.144:6379]
java.io.IOException: The remote host forcibly shuts down an existing connection。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
19:10:05.060 [redisson-netty-4-8] ERROR org.redisson.client.handler.CommandsQueue - Exception occured. Channel: [id: 0xf56a3ced, L:/192.168.0.147:60316 - R:192.168.0.144/192.168.0.144:6379]
java.io.IOException: The remote host forcibly shuts down an existing connection。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)

### Steps to reproduce or test case
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.redisson.Redisson;
import org.redisson.api.RList;
import org.redisson.api.RedissonClient;

public class ListExamples {

    public static void main(String[] args) {
        // connects to 127.0.0.1:6379 by default
        RedissonClient redisson = Redisson.create();
        redisson.shutdown();
    }
    
}
### Redis version
redis-64.3.0.503  windows
### Redisson version
3.10.1

**Comment by mrniko** [comment]
Could you try Redis-x64-3.2.100 version or linux version?

**Comment by wshcdr** [comment]
Thank you mrniko! I've tried Redis-x64-3.2.100 , and Eclipse reports the same errors on console.

**Comment by mrniko** [comment]
Unable to reproduce it on windows 10

**Comment by s-limi** [comment]
I have the same problem. Could you tell me how you solved it?
Thanks

**Comment by wshcdr** [comment]
> I have the same problem. Could you tell me how you solved it?
> Thanks

That's strange,  I still have the problem in my codes...

**Comment by jackygurui** [comment]
As the error `java.io.IOException: The remote host forcibly shuts down an existing connection` suggests, this is an issue caused by the remote host. Client side has only reported the problem. It cannot solve this issue from client side alone.
