### ISSUE TITLE
ClassCastException in Netty/Redisson when executing RMapCache.valueSize(...)

### ISSUE THREAD

**Issue by kschroiff** [redisson/redisson#1969]
We are using an AWS ElastiCache Redis 4.0.10 cluster with Redisson 3.10.3 and following a

cache.valueSize(id);

where cache is a RMapCache we can spot the following in our logs:

reply: ReplayingDecoderByteBuf(ridx=2111, widx=3072), command: (HSTRLEN), params: [xxxxx, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256)]: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long

T

```
09 Mar 2019 06:00:31.152aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
09 Mar 2019 06:00:31.152aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
09 Mar 2019 06:00:31.152aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at java.lang.Thread.run(Thread.java:748) [:1.8.0_131]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at org.redisson.client.protocol.convertor.IntegerReplayConvertor.convert(IntegerReplayConvertor.java:39) [redisson-3.10.3.jar:]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at org.redisson.client.protocol.convertor.IntegerReplayConvertor.convert(IntegerReplayConvertor.java:23) [redisson-3.10.3.jar:]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:434) [redisson-3.10.3.jar:]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370) [redisson-3.10.3.jar:]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:201) [redisson-3.10.3.jar:]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:143) [redisson-3.10.3.jar:]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122) [redisson-3.10.3.jar:]
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
09 Mar 2019 06:00:31.153aws-beta_JBoss[aws-beta-app-02] at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
```

### Redis version

4.0.10

### Redisson version

3.10.3

### Redisson configuration

Cluster-Mode

**Comment by mrniko** [comment]
Could you provide some test code to reproduce that?

**Comment by kschroiff** [comment]
As mentioned in #1968 we faced some issues regarding a growing cache - so in order to determine the root cause (which in theory could be related to the size of the cache entries) I did the following on our test system.

cache.put(id, val, timeToLive, timeToLiveUnit, timeToIdle, timeToIdleUnit);
immediately followed by
log ... cache..valueSize(id)

The value is a Base64-encoded string (based on a serialized object).

FWIW, I can also spot that this happens with Set.size() as well. The Set contains strings (emails) - see below.

It feels as if this is a timing issue ... or in other words - this doesn't always happen ...

```
11 Mar 2019 17:58:00.353aws-beta_JBoss[aws-beta-master-01] 2019-03-11_06:58:00,258 ERROR [stderr] (GlobalScheduler_Worker-9) org.redisson.client.RedisException: Unexpected exception while processing command
11 Mar 2019 17:58:00.353aws-beta_JBoss[aws-beta-master-01] 2019-03-11_06:58:00,258 ERROR [stderr] (GlobalScheduler_Worker-9) at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:400)
11 Mar 2019 17:58:00.353aws-beta_JBoss[aws-beta-master-01] 2019-03-11_06:58:00,259 ERROR [stderr] (GlobalScheduler_Worker-9) at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:204)
11 Mar 2019 17:58:00.353aws-beta_JBoss[aws-beta-master-01] 2019-03-11_06:58:00,259 ERROR [stderr] (GlobalScheduler_Worker-9) at org.redisson.RedissonObject.get(RedissonObject.java:85)
11 Mar 2019 17:58:00.353aws-beta_JBoss[aws-beta-master-01] 2019-03-11_06:58:00,259 ERROR [stderr] (GlobalScheduler_Worker-9) at org.redisson.RedissonSet.size(RedissonSet.java:76)
....
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] 2019-03-11_06:58:00,257 WARN [io.netty.channel.DefaultChannelPipeline] (redisson-netty-1-15) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: io.netty.handler.codec.DecoderException: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
....
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] at java.lang.Thread.run(Thread.java:748) [:1.8.0_131]
11 Mar 2019 17:58:00.377aws-beta_JBoss[aws-beta-master-01] Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
```

**Comment by mrniko** [comment]
Tried to reproduce with code below, no luck:

```java
        RMapCache<String, String> map = redisson.getMapCache("test");
        CountDownLatch l = new CountDownLatch(1000);
        String key = RandomString.make(1000);
        for (int i = 0; i < 10000; i++) {
            Thread t = new Thread(() -> {
                map.valueSize(key);
                map.put(key, RandomString.make(100), 2, TimeUnit.SECONDS);
                l.countDown();
            });
            
            t.start();
        }
        
        l.await();
```

**Comment by kschroiff** [comment]
@mrniko Can it be that this relates to https://github.com/redisson/redisson/issues/1938?

We have data - written with 3.9 - in the cache.

So according to the ticket, 3.10 is incompatible with 3.9, correct?

**Comment by mrniko** [comment]
@kschroiff 

Since 3.10 version FstCodec is default codec, but you can still use JsonJacksonCodec. Just define it in your configuration explicitly.
