### ISSUE TITLE
Security Breach - password passed in exceptions

### ISSUE THREAD

**Issue by gilshidlansikgong** [redisson/redisson#1976]
### Expected behavior
When an exception is thrown upon the AUTH command the exception contains the actual password as a param. This happens because LogHelper.toString called by RedisConnection.async nowadays accepts a "Object..." all the time, and LogHelper redacts the password only when a single object of the type CommandData is passed.

### Actual behavior
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), command params: [**our actual password**], Redis client: [addr=rediss://server:6379]
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:214)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	... 6 common frames omitted

### Redisson version
3.10.4

**Comment by mrniko** [comment]
Fixed! Thanks for report
