### ISSUE TITLE
分布式锁lock.lock();时异常

### ISSUE THREAD

**Issue by networksatyr** [redisson/redisson#1984]
RLock lock = redisson.getLock("anyLock");

lock.lock();时异常

只有获取锁的时候异常，其它的集合类操作都没有问题。

### Actual behavior
 ERR Error running script (call to f_9401052d872adfd0179ef8c8e8c028512707629a): @user_script:1: @user_script: 1: Unknown Redis command called from Lua script . channel: [id: 0xa5ae7592, L:/192.168.1.110:61979 - R:188.188.2.195/188.188.2.195:6379] command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, api:match:lock:robotMoneyReturn, 30000, 9734124f-2104-4554-8a0f-235d3f60912f:71]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:201)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:143)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
### Redis version
redis_version:5.0.3
### Redisson version
3.10.4
### Redisson configuration
#redis
spring.redis.host=188.188.2.195
spring.redis.port=6379
spring.redis.password=12345678

**Comment by mrniko** [comment]
Which Redis hosting do you use?

**Comment by networksatyr** [comment]
Company internal test server
Single Redis node mode

info
"# Server
redis_version:5.0.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4a761c97fea30462
redis_mode:standalone
os:Linux 3.10.0-957.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:7339
run_id:368ad362f8cfed5c08d7181fe86a1b35543df6d2
tcp_port:6379
uptime_in_seconds:6152619
uptime_in_days:71
hz:10
configured_hz:10
lru_clock:9057898
executable:/home/dev/app/redis/bin/redis-server
config_file:/home/dev/app/redis/6379/redis_6379.conf

**Comment by mrniko** [comment]
Unable to reproduce it with Redis 5.0.3. Please check your Redis implementation

**Comment by Qunar-wyq** [comment]
遇到同样的问题，怎么解决的？
