### ISSUE TITLE
java.lang.NoClassDefFoundError: org/hibernate/cache/spi/support/DomainDataRegionImpl

### ISSUE THREAD

**Issue by tufgupmi** [redisson/redisson#1991]
### Expected behavior

No error

### Actual behavior

When starting hiberate-redisson53 with hibernate-core-5.3.2.FINAL i got this error

java.lang.NoClassDefFoundError: org/hibernate/cache/spi/support/DomainDataRegionImpl
        at org.redisson.hibernate.RedissonRegionFactory.buildDomainDataRegion(RedissonRegionFactory.java:178)
        at org.hibernate.cache.internal.EnabledCaching.prime(EnabledCaching.java:108)
        at org.hibernate.metamodel.internal.MetamodelImpl.primeSecondLevelCacheRegions(MetamodelImpl.java:304)
        at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:133)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:295)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
        at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:96)
        at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFact

**Comment by mrniko** [comment]
I'm afraid 5.3.0, 5.3.1 and 5.3.2 versions aren't supported due to lack of some functionality. 

Thanks for pointing out! Documentation has been updated.
