### ISSUE TITLE
Error: java.lang.NoSuchFieldError: INSTANCE on start

### ISSUE THREAD

**Issue by tufgupmi** [redisson/redisson#1994]
Hello

I have changed to hibernate-5,2,2,Final and redisson-hibernate-52

```
 <dependency>
          <groupId>org.redisson</groupId>
          <artifactId>redisson-hibernate-52</artifactId>
         <version>3.10.4</version>
 </dependency>

```
And i'm getting this error on start up
```

INFO  [2019-03-19 11:04:35,236] [redisson-netty-1-14] [] [MasterConnectionPool] 5 connections initialized for srvaxivln213/10.216.0.213:6379
java.lang.NoSuchFieldError: INSTANCE
        at org.redisson.hibernate.RedissonRegionFactory.start(RedissonRegionFactory.java:97)
        at org.hibernate.cache.spi.RegionFactory.start(RegionFactory.java:63)
        at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:71)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:28)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:20)
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:55)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:257)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:231)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:238)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:490)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:710)
        at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:96)
        at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:49)
        at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:39)
        at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:62)
        at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:15)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:93)
        at com.triggle.middleware.user.UserApplication.main(UserApplication.java:17)


```

**Comment by mrniko** [comment]
It's bug, as workaround please try hibernate 5.2.5 version.

**Comment by mrniko** [comment]
Fixed!
