### ISSUE TITLE
Pub/sub subscriptions lost on master failover

### ISSUE THREAD

**Issue by adrian-baker** [redisson/redisson#2007]
When a primary node fails over, redisson appears to detect this and correctly pick up the new primary. However, after this point, pub/sub subscriptions no longer work.

This occurred in our production env when AWS Elasticache triggered a failover by itself. I was able to reproduce using https://aws.amazon.com/blogs/database/testing-automatic-failover-to-a-read-replica-on-amazon-elasticache-for-redis/ .

Here's a log from the client during the failover:
```
2019-03-23 16:05:00.900 ERROR [redisson-netty-6-18]  org.redisson.cluster.ClusterConnectionManager - Can't update cluster state
io.netty.channel.ConnectTimeoutException: connection timed out: 10.101.59.175/10.101.59.175:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-03-23 16:05:15.927 ERROR [redisson-netty-6-23]  org.redisson.cluster.ClusterConnectionManager - Can't update cluster state
io.netty.channel.ConnectTimeoutException: connection timed out: 10.101.59.175/10.101.59.175:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-03-23 16:05:21.005 INFO  [redisson-netty-6-19]  org.redisson.connection.MasterSlaveEntry - master 10.101.63.131/10.101.63.131:6379 used as slave
2019-03-23 16:05:21.046 INFO  [redisson-netty-6-19]  org.redisson.cluster.ClusterConnectionManager - slave redis://10.101.63.131:6379 removed for slot ranges: [[0-16383]]
2019-03-23 16:05:21.053 INFO  [redisson-netty-6-5]  org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 10.101.63.131/10.101.63.131:6379
2019-03-23 16:05:21.099 ERROR [redisson-netty-6-19]  org.redisson.cluster.ClusterConnectionManager - cluster_state:fail for 10.101.63.131/10.101.63.131:6379
2019-03-23 16:05:21.115 INFO  [redisson-netty-6-3]  org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 10.101.63.131/10.101.63.131:6379
2019-03-23 16:05:21.140 INFO  [redisson-netty-6-30]  org.redisson.connection.MasterSlaveEntry - master 10.101.59.175/10.101.59.175:6379 has changed to 10.101.63.131/10.101.63.131:6379
2019-03-23 16:05:21.140 INFO  [redisson-netty-6-30]  org.redisson.connection.pool.MasterConnectionPool - 32 connections initialized for 10.101.63.131/10.101.63.131:6379
2019-03-23 16:05:21.155 INFO  [redisson-netty-6-31]  org.redisson.connection.pool.SlaveConnectionPool - 32 connections initialized for 10.101.63.131/10.101.63.131:6379
```

### Redis version
5.0.0, AWS Elasticache Cluster

### Redisson version
3.10.5

### Redisson configuration
ClusterServersConfig

**Comment by mrniko** [comment]
Redisson has a test for this case:

https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/RedissonTopicTest.java#L689

Could you provide your test code?

**Comment by adrian-baker** [comment]
We're using `org.redisson.config.Config#useClusterServers` with an AWS Elasticache configured using Redis Cluster. The test you link is using `org.redisson.config.Config#useSentinelServers`, with Redis Sentinel (I don't believe AWS Elasticache supports Redis Sentinel).

Did you mean to link to https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/RedissonTopicTest.java#L845 ? 

I'll experiment with that test to see if I can reproduce the issue without a remote Elasticache instance.

**Comment by mrniko** [comment]
@adrian-baker 

Sorry, my mistake. The link you provided is correct. Waiting for you feedback

**Comment by adrian-baker** [comment]
I'm still working on getting the stock Redisson tests to run, however differences I notice between the test and our environment:
- we're using the default `SubscriptionMode.MASTER` setting, the test uses `SubscriptionMode.SLAVE`.
- the test stops a slave node, whereas we experienced a master failover, where a slave takes over the master role.

**Comment by mrniko** [comment]
I have added test for your case. It passes:

https://github.com/redisson/redisson/blob/356fd9bc1333e297354387b91d7bf7fc79c8eb00/redisson/src/test/java/org/redisson/RedissonTopicTest.java#L915

**Comment by shailender-bathula** [comment]
@mrniko this is @adrian-baker 's colleague.

#2009 has the unit test which describes our redis cluster setup and topic subscriptions. As you can see, the bug seems to be with re-subscribing pattern topic listeners.

The unit test does not pass always:
* because the way I am failing over the cluster doesn't seem to trigger these lines in the logging always:
```
org.redisson.connection.MasterSlaveEntry - master 127.0.0.1/127.0.0.1:36613 has changed to 127.0.0.1/127.0.0.1:41399
org.redisson.cluster.ClusterConnectionManager - cluster_state:fail for 127.0.0.1/127.0.0.1:41399
org.redisson.pubsub.PublishSubscribeService - resubscribed listeners for '__keyspace*__:i*' channel-pattern to '[addr=redis://127.0.0.1:41399]'
```
* Is it because we are using a redis cluster with just a single master and slave? There seems to be some Redis documentation about a minimal cluster requiring 3 masters and 3 slaves. That minimum number is not enforced by Redis or by Elasticache. As you can see in Adrian's initial logging in the issue, Elasticache did failover with a single master and slave node.
* Does Redisson have any issues handling failover of a cluster with just a single master and slave?

Thanks

**Comment by shailender-bathula** [comment]
> The unit test does not pass always:
I tested using Redis 5.0.4.

**Comment by mrniko** [comment]
@shailender-bathula 

Thanks for the contribution! I'm strongly recommend to use at least 3 masters, since less amount causes some issues during failover.

Redisson failover handling doesn't depend on amount of masters in cluster.

**Comment by adrian-baker** [comment]
>I'm strongly recommend to use at least 3 masters, since less amount causes some issues during failover.

What sort of issues? Is this your recommendation for any Redis cluster, or a Redisson specific recommendation/requirement?

**Comment by mrniko** [comment]
@adrian-baker 

I tested failover with 2 master nodes and 2 slaves per master about year ago. Whole cluster nodes starts to throw CLUSTERDOWN error during single master failover, but this not happenning with 3 master nodes.

**Comment by mrniko** [comment]
I discovered another bug - in cluster mode pattern topic can't catch all keyspace events, but only for one master node in cluster

**Comment by shailender-bathula** [comment]
Yes, noticed that when trying my unit test with recommended 6 node cluster. It seems to be a known feature of redis cluster. Please see antirez/redis/issues/2541 for the suggested fix the clients are meant to implement.

**Comment by shailender-bathula** [comment]
@mrniko FYI - we checked with AWS support on how Elasticache supports a 1 master + 1 slave scenario when Redis recommends 3 masters + 3 slaves minimum. They do that using an external health check monitoring process. If the monitoring process detects the only master has failed, then it repairs the cluster by promoting the slave as the new master, adding a new node as the slave and replicating it from the new master. Whereas, from my understanding a 3 master + 3 slave configuration can repair itself by promoting the slave of the failed master as the new master (i.e. without an external health check process).

Even though the latest `redis-cli` enforces a minimum number of nodes, it is possible to create a cluster using any number of masters and slave using the CLUSTER group commands. See http://pingredis.blogspot.com/2016/09/redis-cluster-how-to-create-cluster.html which explains how to create a cluster using individual commands.

**Comment by mrniko** [comment]
@shailender-bathula 

Thanks for the information, anyway 3 nodes has better stability in case of failover than 2 or 1. https://github.com/redisson/redisson/issues/2007#issuecomment-477043138

**Comment by mrniko** [comment]
> in cluster mode pattern topic can't catch all keyspace events, but only for one master node in cluster

Fixed in https://github.com/redisson/redisson/issues/2237
