### ISSUE TITLE
o.redisson.client.handler.CommandsQueue  : Exception occured. Channel:

### ISSUE THREAD

**Issue by wad12302** [redisson/redisson#2013]
2019-03-28 00:47:14.367  INFO 45088 --- [           main] org.redisson.Version                     : Redisson 3.10.5
2019-03-28 00:47:14.641  INFO 45088 --- [           main] o.r.c.SentinelConnectionManager          : master: redis://127.0.0.1:6380 added
2019-03-28 00:47:14.644  INFO 45088 --- [           main] o.r.c.SentinelConnectionManager          : slave: redis://127.0.0.1:6381 added
2019-03-28 00:47:14.644  INFO 45088 --- [           main] o.r.c.SentinelConnectionManager          : slave: redis://127.0.0.1:6382 added
2019-03-28 00:47:14.646  INFO 45088 --- [           main] o.r.c.SentinelConnectionManager          : sentinel: redis://127.0.0.1:26382 added
2019-03-28 00:47:14.647  INFO 45088 --- [           main] o.r.c.SentinelConnectionManager          : sentinel: redis://127.0.0.1:26381 added
2019-03-28 00:47:14.679  INFO 45088 --- [sson-netty-4-13] o.r.connection.pool.SlaveConnectionPool  : 10 connections initialized for 127.0.0.1/127.0.0.1:6381
2019-03-28 00:47:14.681 ERROR 45088 --- [isson-netty-4-3] o.redisson.client.handler.CommandsQueue  : Exception occured. Channel: [id: 0xb5ffdd00, L:/127.0.0.1:58815 - R:127.0.0.1/127.0.0.1:26380]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_181]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_181]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_181]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_181]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

2019-03-28 00:47:14.683  INFO 45088 --- [isson-netty-4-3] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for 127.0.0.1/127.0.0.1:6382
2019-03-28 00:47:14.685  INFO 45088 --- [isson-netty-4-6] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for 127.0.0.1/127.0.0.1:6381
2019-03-28 00:47:14.692  INFO 45088 --- [isson-netty-4-8] o.r.connection.pool.SlaveConnectionPool  : 10 connections initialized for 127.0.0.1/127.0.0.1:6382
2019-03-28 00:47:14.700  INFO 45088 --- [sson-netty-4-10] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 127.0.0.1/127.0.0.1:6380
2019-03-28 00:47:14.701  INFO 45088 --- [isson-netty-4-9] o.r.c.pool.MasterConnectionPool          : 10 connections initialized for 127.0.0.1/127.0.0.1:6380
2019-03-28 00:47:15.062  INFO 45088 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'

### Redis version
 Redis version 3.2.100
spring.boot.version>2.1.3.RELEASE
### Redisson version
3.10.5
### Redisson configuration
sentinelServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 3
  password: 
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 32
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 32
  readMode: "SLAVE"
  sentinelAddresses:
  - "redis://127.0.0.1:26380"
  - "redis://127.0.0.1:26381"
  - "redis://127.0.0.1:26382"
  masterName: "mymaster"
  database: 1
  #dnsMonitoring: false
  dnsMonitoringInterval: -1
threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"

**Comment by wad12302** [comment]
spring boot 2.1.3 
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.10.5</version>
		</dependency>
哨兵模式，始终报错，到底是什么原因，
单实例没问题
如果使用：redisson-spring-boot-starter 也有问题

**Comment by jackygurui** [comment]
`远程主机强迫关闭了一个现有的连接。`这个跟客户的的关系不大吧？

**Comment by wad12302** [comment]
> `远程主机强迫关闭了一个现有的连接。`这个跟客户的的关系不大吧？

这个是使用哨兵模式就报这个错，使用单机模式没问题，所以不知道是不是 指令有问题进行检测

**Comment by jackygurui** [comment]
运行哨兵模式的单元测试没有这个问题。

**Comment by wad12302** [comment]
> 运行哨兵模式的单元测试没有这个问题。

那真不知道有什么问题了

**Comment by wad12302** [comment]
> 运行哨兵模式的单元测试没有这个问题。

有没有demo，代码，我拉下来试试

**Comment by jackygurui** [comment]
https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/RedissonTest.java#L832

**Comment by tom055** [comment]
@wad12302  我也是这个问题，哨兵模式每次Redisson.create的时候就是报这个问题 问下你解决了吗？

**Comment by jackygurui** [comment]
@tom055 你用redis-cli连一下试试先。

**Comment by tom055** [comment]
@jackygurui  可以了 是我redis的版本问题 用的是3.0.5的版本 老版本中在sentinel.conf配置文件中没有 关闭保护模式的参数 还是非常感谢

**Comment by Jonnyleezh** [comment]
@tom055 我用的3.2得redis还是一样,你现在用的是3.0.5版本,然后关闭保护模式的参数是吗?

**Comment by tom055** [comment]
@Jonnyleezh 哨兵一定一定要弄3台centos电脑，同台windows或者centos电脑docker出3个redis 3个sentinel都是不行的

**Comment by Jonnyleezh** [comment]
@tom055 关键是这个项目里配的是单机,看前面的comment说单机应该是没问题的.所以报这个我也是有点晕~

**Comment by tom055** [comment]
@Jonnyleezh 哨兵单机的我试了从win到linux都不行 弄3台linux就可以了

**Comment by Jonnyleezh** [comment]
这样子啊,也是一直报这个问题是吗?

**Comment by tom055** [comment]
@Jonnyleezh 不会了
