### ISSUE TITLE
redis server response timeout (3000ms) occured for command

### ISSUE THREAD

**Issue by chyangxi** [redisson/redisson#2022]
exception：
2019-03-27-11:59:46 [pool-4-thread-2] ERROR c.i.c.p.n.n.u.ImportUtil - 更新导入接口详情表出错，出错原因：
Redis server response timeout (3000 ms) occured for command: (GET) with params: [99999999999999_20190327001PigcGuaracctbsinfsgmt_P] channel: [id: 0x533ebf98, L:/127.0.0.1:56650 - R:127.0.0.1/127.0.0.1:6379]
2019-03-27-11:59:49 [pool-4-thread-2] ERROR c.i.c.p.n.n.u.ImportUtil - 更新导入接口详情表出错，出错原因：Redis server response timeout (3000 ms) occured for command: (GET) with params: [99999999999999_20190327001PigcGuaracctbsinfsgmt_P] channel: [id: 0x0559f2c4, L:/127.0.0.1:56638 - R:127.0.0.1/127.0.0.1:6379]
2019-03-27-11:59:49 [pool-4-thread-2] ERROR c.i.c.p.n.n.i.ImportServiceImpl - pig---error:{}
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured for command: (GET) with params: [99999999999999_20190327001PigcGuaracctbsinfsgmt_P] channel: [id: 0x0559f2c4, L:/127.0.0.1:56638 - R:127.0.0.1/127.0.0.1:6379]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:752) ~[redisson-3.8.2.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2019-03-27-11:59:51 [http-nio-8080-exec-2] ERROR c.i.c.c.a.filter.Authorization - isUrlInList:org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=31, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@278152080 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x9d5e6eae, L:/127.0.0.1:56640 - R:127.0.0.1/127.0.0.1:6379]], command: (LINDEX), command params: [k_d_a, 2] after 3 retry attempts
2019-03-27-11:59:58 [http-nio-8080-exec-2] ERROR c.i.c.c.a.filter.Authorization - error:org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=31, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@57801302 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x5786d31c, L:/127.0.0.1:56652 - R:127.0.0.1/127.0.0.1:6379]], command: (EVAL), command params: [local key = KEYS[1] local obj = ARGV[1] local items = redis.call('lrange', key, 0, -1) for i=1,#item..., 1, 57258884-c583-4969-9a32-186880898c88k_i_l, PooledUnsafeDirectByteBuf(ridx: 0, widx: 29, cap: 256)] after 3 retry attempts
2019-03-27-12:00:04 [redisson-netty-1-14] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x0559f2c4, L:/127.0.0.1:56638 - R:127.0.0.1/127.0.0.1:6379], command: (GET), params: [99999999999999_20190327001PigcGuaracctbsinfsgmt_P], result: com.icfcc.credit.common.interfaceimport.entity.PsgImportsDetailSerialize@31275b42
2019-03-27-12:00:04 [redisson-netty-1-1] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x533ebf98, L:/127.0.0.1:56650 - R:127.0.0.1/127.0.0.1:6379], command: (GET), params: [99999999999999_20190327001PigcGuaracctbsinfsgmt_P], result: com.icfcc.credit.common.interfaceimport.entity.PsgImportsDetailSerialize@3ecb0ae3
2019-03-27-12:01:14 [pool-4-thread-5] INFO  c.i.c.p.n.m.i.bImportServiceImpl - B data import end
2019-03-27-12:01:37 [pool-4-thread-5] INFO  c.i.c.p.n.m.i.cImportServiceImpl - C data import start,count=500000

This paper：
I tried many way, but there has been no redis overtime this solution. Hope to get a great god for help, thank you.
### Redis version
redis-windows -x64-3.2.1
### Redisson version
two version :2.8.2 or 3.8.2
### Redisson configuration
new Config().userSingleServer().setAdddress("redis://127.0.0.1:6379");

**Comment by mrniko** [comment]
Try follow values for `nettyThreads` setting: 32,64,128 and increase connection pool

**Comment by wujilai** [comment]
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (EVAL), params: [local s = redis.call('hgetall', KEYS[1]); local result = {}; local maxSize = tonumber(redis.call('hg..., 5, onlineUserCache, redisson__timeout__set:{onlineUserCache}, redisson__idle__set:{onlineUserCache}, redisson__map_cache__last_access__set:{onlineUserCache}, {onlineUserCache}:redisson_options, 1560498015304], channel: [id: 0xa205d196, ...............
  at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:960)
  at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
  at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
  at java.lang.Thread.run(Thread.java:748)

question:
when i get allvalue of a key, occured RedisResponseTimeoutException,why?  the numbers of the values is 10000 or more .

**Comment by mrniko** [comment]
@wujilai 

Did you try to increase connections amount as well?
