### ISSUE TITLE
hadoop - yarn application failed due to Error: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace with redisson-3.10.5

### ISSUE THREAD

**Issue by bhaskarroy19** [redisson/redisson#2031]
### Expected behavior
Hadoop yarn application should run successfully
### Actual behavior
2019-04-07 23:15:58 INFO  [THREAD ID=LTM-worker-thd-128] Job:1406 - Task Id : attempt_1554192178061_15274_m_000003_2, Status : FAILED
@400000005caa37602da1dca4 Error: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace(Ljava/lang/CharSequence;I)I
@400000005caa37602da1e474 Container killed by the ApplicationMaster.
@400000005caa37602da1e474 Container killed on request. Exit code is 143
@400000005caa37602da1e85c Container exited with a non-zero exit code 143
### Redis version
redis-3.*
### Redisson version
3.10.5
### Redisson configuration
programatic configuration with sentinel servers

**Comment by jackygurui** [comment]
Is there a netty dependency conflict? Can you paste the full stack trace?

**Comment by bhaskarroy19** [comment]
yes, it looks like that. I tried different netty version. But it happening the same thing. 
Netty used: netty-3.6.2.Final.jar with netty-buffer:4.1.34-final and other netty dependency of redisson-3.10.5.  
we have netty-3.6.2.Final dependency for HDFS.

**Comment by bhaskarroy19** [comment]
Stack trace only showing this much

**Comment by bhaskarroy19** [comment]
Please help here.

**Comment by mrniko** [comment]
@bhaskarroy19 

I'm afraid it's not possible to use different netty libs in the same classpath

**Comment by bhaskarroy19** [comment]
I re-test using netty-all-4.0.23.Final.jar along with netty-buffer:4.1.34-final and other netty dependency of redisson-3.10.5.


But, still getting the same exception:

2019-04-08 14:17:28,557 FATAL [IPC Server handler 2 on 44233] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Task: attempt_1554192178061_16504_m_000009_0 - exited : io.netty.util.internal.StringUtil.indexOfNonWhiteSpace(Ljava/lang/CharSequence;I)I
2019-04-08 14:17:28,557 INFO [IPC Server handler 2 on 44233] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Diagnostics report from attempt_1554192178061_16504_m_000009_0: Error: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace(Ljava/lang/CharSequence;I)I

**Comment by jackygurui** [comment]
@bhaskarroy19 I am afraid you cannot pick and mix the netty dependencies. If I am correct, I think the full message of the error is NoSuchMethodException. This is simply means wrong version of libs are used.

**Comment by bhaskarroy19** [comment]
Yes, you are right, it throwing NoSuchMethodException. Here the complete stack trace:
***********************************************
2019-04-08 17:11:42,286 WARN [main] org.apache.hadoop.metrics2.impl.MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-maptask.properties,hadoop-metrics2.properties
2019-04-08 17:11:42,354 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled snapshot period at 10 second(s).
2019-04-08 17:11:42,354 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system started
2019-04-08 17:11:42,356 INFO [main] org.apache.hadoop.mapred.YarnChild: Executing with tokens:
2019-04-08 17:11:42,356 INFO [main] org.apache.hadoop.mapred.YarnChild: Kind: mapreduce.job, Service: job_1554192178061_16663, Ident: (org.apache.hadoop.mapreduce.security.token.JobTokenIdentifier@20bd8be5)
2019-04-08 17:11:42,571 INFO [main] org.apache.hadoop.mapred.YarnChild: Sleeping for 0ms before retrying again. Got null now.
2019-04-08 17:11:42,841 INFO [main] org.apache.hadoop.mapred.YarnChild: mapreduce.cluster.local.dir for child: /mnt/data/hadoop/yarn/local/usercache/fk-logsvc-writer/appcache/application_1554192178061_16663
2019-04-08 17:11:43,140 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
2019-04-08 17:11:43,612 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: File Output Committer Algorithm version is 1
2019-04-08 17:11:43,623 INFO [main] org.apache.hadoop.mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
2019-04-08 17:11:43,843 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: hdfs://nn-ha/v_raw/5/by-consumed-at-time/20190407H20M50/test-log-writer-tmp-ad9-1119215-6fc7737f-569d-4a2f-b25e-fd967b9007b3:0+5602756
2019-04-08 17:11:44,719 INFO [main] org.apache.hadoop.mapred.MapTask: (EQUATOR) 0 kvi 483131388(1932525552)
2019-04-08 17:11:44,720 INFO [main] org.apache.hadoop.mapred.MapTask: mapreduce.task.io.sort.mb: 1843
2019-04-08 17:11:44,720 INFO [main] org.apache.hadoop.mapred.MapTask: soft limit at 1352767872
2019-04-08 17:11:44,720 INFO [main] org.apache.hadoop.mapred.MapTask: bufstart = 0; bufvoid = 1932525568
2019-04-08 17:11:44,720 INFO [main] org.apache.hadoop.mapred.MapTask: kvstart = 483131388; length = 120782848
2019-04-08 17:11:44,727 INFO [main] org.apache.hadoop.mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
2019-04-08 17:11:44,753 INFO [main] org.apache.hadoop.io.compress.zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
2019-04-08 17:11:44,754 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.deflate]
2019-04-08 17:11:44,758 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.deflate]
2019-04-08 17:11:44,759 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.deflate]
2019-04-08 17:11:44,759 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.deflate]
2019-04-08 17:11:44,819 INFO [main] fk.logsvc.writer.record.filepartitioner.LogFilePartitioner: ************** LogFilepartitioner getInstance started ****************
2019-04-08 17:11:44,819 INFO [main] fk.logsvc.writer.record.filepartitioner.LogFilePartitioner: ************** redisdestfilepartitioner called from logfilepartitioner ****************
2019-04-08 17:11:44,831 INFO [main] fk.logsvc.writer.record.filepartitioner.RedisDestFilePartitioner: ************** Redisson instance creation started ****************
2019-04-08 17:11:44,831 INFO [main] fk.logsvc.writer.record.filepartitioner.RedisDestFilePartitioner: ************** redisson config : ****************
2019-04-08 17:11:44,831 INFO [main] fk.logsvc.writer.record.filepartitioner.RedisDestFilePartitioner: org.redisson.config.Config@74a9c4b0
2019-04-08 17:11:45,177 INFO [main] org.redisson.Version: Redisson 3.10.5
2019-04-08 17:11:45,295 INFO [main] org.apache.hadoop.mapred.MapTask: Starting flush of map output
2019-04-08 17:11:45,308 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new compressor [.snappy]
2019-04-08 17:11:45,351 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.NoSuchMethodError: io.netty.util.internal.StringUtil.indexOfNonWhiteSpace(Ljava/lang/CharSequence;I)I
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parse(UnixResolverDnsServerAddressStreamProvider.java:175)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:94)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:128)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:70)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$1.provider(DnsServerAddressStreamProviders.java:57)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$1.<init>(DnsServerAddressStreamProviders.java:36)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:34)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:204)
	at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:79)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:232)
	at org.redisson.Redisson.<init>(Redisson.java:118)
	at org.redisson.Redisson.create(Redisson.java:157)
	at fk.logsvc.writer.record.filepartitioner.RedisDestFilePartitioner.<init>(RedisDestFilePartitioner.java:49)
	at fk.logsvc.writer.record.filepartitioner.LogFilePartitioner.getInstance(LogFilePartitioner.java:76)
	at fk.logsvc.mr.HiveDataFileMapRunner.setup(HiveDataFileMapRunner.java:130)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
*****************************************************************************

I am using follwing dependency as per [https://mvnrepository.com/artifact/org.redisson/redisson/3.10.5](url)

netty-buffer-4.1.34.Final.jar
netty-codec-4.1.34.Final.jar
netty-codec-dns-4.1.34.Final.jar
netty-common-4.1.34.Final.jar
netty-handler-4.1.34.Final.jar
netty-resolver-4.1.34.Final.jar
netty-resolver-dns-4.1.34.Final.jar
netty-transport-4.1.34.Final.jar


When I ran my unit test, it ran successfully. But when I am running the whole process then I am getting this exception.

**Comment by jackygurui** [comment]
I think somewhere it is picking the wrong netty version. Have you tried to declare netty explicitly?

**Comment by bhaskarroy19** [comment]
yes, I found a conflict is there. Our node manager has its own version of neety-3.6.2. So it is getting conflicted with it. I am trying to override it with new version.  Will update after resolving this.

**Comment by mrniko** [comment]
I think this is the same problem as https://github.com/redisson/redisson/issues/2003
