### ISSUE TITLE
WriteRedisConnectionException HANDLING

### ISSUE THREAD

**Issue by roborobo2** [redisson/redisson#2042]
### Expected behavior
handle org.redisson.client.WriteRedisConnectionException for example same way as others in spring CacheErrorHandler

### Actual behavior
I try sentinel, master-slave and also single server redisson config. In each configuration is problem when cached method **with** sync=true and connection to redis server is broken or redis server is down.

`
org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:100:queue:0, freeConnectionsAmount=31, freeConnectionsCounter=value:255:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1737055972 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x4aa21a8b, L:0.0.0.0/0.0.0.0:58873], command=null], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, migrationDispatcher, redisson__timeout__set:{migrationDispatcher}, redisson__idle__set:{migrationDispatcher}, redisson__map_cache__last_access__set:{migrationDispatcher}, {migrationDispatcher}:redisson_options, 1555312017905, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256)] after 1 retry attempts
	at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:873) ~[redisson-3.10.5.jar:?]
	at org.redisson.command.CommandAsyncService.access$000(CommandAsyncService.java:97) ~[redisson-3.10.5.jar:?]
	at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:792) ~[redisson-3.10.5.jar:?]
	at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:789) ~[redisson-3.10.5.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1018) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:874) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1365) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1091) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1062) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.netty.channel.ExtendedClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]`

IF WE USE method **without** SYNC=true then exception is similar but is HANDLED by org.springframework.cache.interceptor.CacheErrorHandler and is behavior OK

`org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:100:queue:0, freeConnectionsAmount=31, freeConnectionsCounter=value:255:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1737055972 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x4aa21a8b, L:0.0.0.0/0.0.0.0:58873], command=null], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, migrationDispatcher, redisson__timeout__set:{migrationDispatcher}, redisson__idle__set:{migrationDispatcher}, redisson__map_cache__last_access__set:{migrationDispatcher}, {migrationDispatcher}:redisson_options, 1555312017905, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256)] after 1 retry attempts
	at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:873) ~[redisson-3.10.5.jar:?]
	at org.redisson.command.CommandAsyncService.access$000(CommandAsyncService.java:97) ~[redisson-3.10.5.jar:?]
	at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:792) ~[redisson-3.10.5.jar:?]
	at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:789) ~[redisson-3.10.5.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1018) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:874) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1365) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1091) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1062) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.netty.channel.ExtendedClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	
	`

### Steps to reproduce or test case
Start app for example with SingleServer config and method with spring annotation

### Redis version
4.0.12

### Redisson version
3.10.5

### Redisson configuration

compile("org.redisson:redisson-spring-data-21:3.10.5")
/////////
@Bean
        public RedissonClient redissonSingleServerClient() {
                Config config = new Config();
                config.useSingleServer()
                        .setAddress("redis://127.0.0.1:6379")
                        .setRetryInterval(RETRY_INTERVAL)
                        .setRetryAttempts(RETRY_ATTEMPTS)
                        .setConnectionPoolSize(CONNECTION_POOL_SIZE)
                        .setSubscriptionConnectionPoolSize(SUBSCRIPTION_POOL_SIZE);
                return Redisson.create(config);
        }

**Comment by mrniko** [comment]
CacheErrorHandler is not used by Spring to catch RuntimeExceptions in `sync = true` mode.

You can reproduce this with ConcurrentMapCacheManager:

```java
        @Bean
        CacheManager cacheManager() {
            return new ConcurrentMapCacheManager() {
                @Override
                protected Cache createConcurrentMapCache(String name) {
                    return new ConcurrentMapCache(name, new ConcurrentHashMap(256), this.isAllowNullValues()) {
                        @Override
                        public <T> T get(Object key, Callable<T> valueLoader) {
                            throw new IllegalStateException();
                        }
                    };
                }
            };
        }

```
