### ISSUE TITLE
Possibility of broken connections on the pool

### ISSUE THREAD

**Issue by kringol** [redisson/redisson#2043]
### Expected behavior
When using a fixed connection pool of min=64 and max=64 to every node (masters and slaves) on cluster config. Redisson is able to open a healthy connection pool of 64 to each of the nodes
### Actual behavior
It seems that on some cases when our app container (dockerized app) starts there might be some network/warm up issues (also seen by getting a few CLUSTER_NODES and CLUSTER_INFO timeouts during startup) leads to some connections on the pool to be broken. No issue is easily observed at low traffic after but after increasing a bit the load, it seems some requests to those instances (we deployed 20 instances and 2 ended up like this) fail with timeouts. This doesn't seem to happen to instances that started and opened all the connections properly at startup but seems this faulty startup instances remain in a broken state and do not recover and/or re-create those broken connections.

On any case, as said, this only happens on those cases during startup. So that's our primary hypothesis. If any logic can be put into place to deal with potential broken connections on the pool or some monitoring of the pool we can enable or some config we could do differently. Please advice

example timeout:
```rapid.shaded.org.redisson.client.RedisTimeoutException: Unable to send batch after 4 retry attempts
	at rapid.shaded.org.redisson.command.CommandBatchService$3.run(CommandBatchService.java:675)
	at rapid.shaded.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at rapid.shaded.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
```

### Steps to reproduce or test case
Trying to isolate an easy way to reproduce it at the moemnt

### Redis version
3.2.8

### Redisson version
3.10.4

### Redisson configuration
```"clusterServersConfig": {
                            "connectTimeout": 10000,
                            "timeout": 100,
                            "retryInterval": 50,
                            "retryAttempts": 4,
                            "masterConnectionMinimumIdleSize": 64,
                            "masterConnectionPoolSize": 64,
                            "slaveConnectionMinimumIdleSize": 64,
                            "slaveConnectionPoolSize": 64,
                            "keepAlive": true,
                            "tcpNoDelay": true,
                            "readMode": "MASTER_SLAVE",
                            "nodeAddresses": [
                                "redis://redis001.prod.local:6329",
                                "redis://redis001.prod.local:6339",
                                "redis://redis001.prod.local:6349",
                                "redis://redis002.prod.local:6329",
                                "redis://redis002.prod.local:6339",
                                "redis://redis002.prod.local:6349",
                                "redis://redis003.prod.local:6329",
                                "redis://redis003.prod.local:6339",
                                "redis://redis003.prod.local:6349",
                                "redis://redis004.prod.local:6329",
                                "redis://redis004.prod.local:6339",
                                "redis://redis004.prod.local:6349",
                                "redis://redis005.prod.local:6329",
                                "redis://redis005.prod.local:6339",
                                "redis://redis005.prod.local:6349",
                                "redis://redis006.prod.local:6329",
                                "redis://redis006.prod.local:6339",
                                "redis://redis006.prod.local:6349"
                            ]
                        },
                        "useLinuxNativeEpoll": true
```

**Comment by mrniko** [comment]
Did you try to set `pingConnectionInterval` setting? This would help to avoid broken connections by using redis PING command. Broken connection get reconnected if Redis fail to response.

**Comment by kringol** [comment]
That looks promising, i didn't notice it was disabled by default. Thanks for the suggestion.
We will try that and come back

**Comment by kringol** [comment]
We've been trying the setting, but we have been facing issues when enabling it
Basically it seems that if the PING command fails during startup (sometimes the containers are slow on network, etc during startup) it just stops the whole process and thus leaves me with a dead app
We need a way to make sure that the redis starts properly and remains working. It can throw warnings about connections dying or similar. But it has to start and if a connection misbehaves, it has to be replaced, but it shouldn't stop it from working

### Redis version
3.2.8

### Redisson version
3.10.4

### Redisson configuration
```"clusterServersConfig": {
                            "connectTimeout": 10000,
                            "timeout": 100,
                            "retryInterval": 50,
                            "retryAttempts": 4,
                            "masterConnectionMinimumIdleSize": 64,
                            "masterConnectionPoolSize": 64,
                            "slaveConnectionMinimumIdleSize": 64,
                            "slaveConnectionPoolSize": 64,
                            "keepAlive": true,
                            "tcpNoDelay": true,
                            "readMode": "MASTER_SLAVE",
                            "pingConnectionInterval": 10000,
                            "nodeAddresses": [
                                "redis://redis001.prod.local:6329",
                                "redis://redis001.prod.local:6339",
                                "redis://redis001.prod.local:6349",
                                "redis://redis002.prod.local:6329",
                                "redis://redis002.prod.local:6339",
                                "redis://redis002.prod.local:6349",
                                "redis://redis003.prod.local:6329",
                                "redis://redis003.prod.local:6339",
                                "redis://redis003.prod.local:6349",
                                "redis://redis004.prod.local:6329",
                                "redis://redis004.prod.local:6339",
                                "redis://redis004.prod.local:6349",
                                "redis://redis005.prod.local:6329",
                                "redis://redis005.prod.local:6339",
                                "redis://redis005.prod.local:6349",
                                "redis://redis006.prod.local:6329",
                                "redis://redis006.prod.local:6339",
                                "redis://redis006.prod.local:6349"
                            ]
                        },
                        "useLinuxNativeEpoll": true
```

but we get the following issue 
```
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
    at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:163)
    at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:235)
    at org.redisson.Redisson.<init>(Redisson.java:118)
    at org.redisson.Redisson.create(Redisson.java:157)
    ... 81 more
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 19 from 64 were initialized. Redis server: 100.79.8.64/100.79.8.64:6329
    at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:160)
    at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
    at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
    at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:330)
    at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:296)
    at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
    at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
    at org.redisson.client.RedisClient$2$1.run(RedisClient.java:236)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), command params: [], Redis client: [addr=redis://100.79.8.64:6329]
    at org.redisson.client.RedisConnection$1.run(RedisConnection.java:209)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    ... 6 more
```

**Comment by kringol** [comment]
Hi @mrniko 
I fear it might not just a dead connection, i've just observed that when this issue happens (happens every few days randomly on one of our app instances) the whole redisson is plain dead, every single command it takes after we get the first timeout error fails the same way. 
We mostly call redis using RBatch commands (with a few get commands inside) 
There is no other log besides the first timeout
```
Caused by: org.redisson.client.RedisTimeoutException: Unable to send batch after 4 retry attempts
	at org.redisson.command.CommandBatchService$3.run(CommandBatchService.java:675)
```

**Comment by mrniko** [comment]
@kringol 

Could you provide some test code to reproduce this case?

**Comment by kringol** [comment]
Hi @mrniko 
Nothing would make me happier that having an easy way to reproduce this issue mechanically and easily. But it happens randomly, sometimes on the same day we deploy the app on 1 of the 20-30 servers, but sometimes it happens after 1 week and under no observable similitudes that might trigger it from external. 
We do see this happening only this app that has high traffic and 99.9% is only reading from redis. And it performs the reads via an RBatch with at most 45 GET commands inside, we haven't seen this issue so far on other apps not using RBatch, but maybe it just because of lower traffic. We also use KRYO serialization and LZ4 compression. This app has been like this for around 2years and this only started happening during the past 6 months i believe after some version upgrades but i can't exactly pinpoint from which version.
In the next release we will try with the latest version of redisson as well.

**Comment by kringol** [comment]
If there is anyway to expose some metrics about the connection pool or threads or similar via JMX we can track those to see if there is any observable condition when this happens or is about to happen

**Comment by mrniko** [comment]
Did you try to increase nettyThreads setting ? Since LZ4 compression is a time consuming operation this might give effect. https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by kringol** [comment]
We can try, but it doesn't seem to be the root issue since we stress tested the app with much higher load scenarios than the real production one and it doesn't explain why it doesn't recover at all when this error happens, even if the traffic drops to 0 and then we continue, the app is already broken on redis, and i can only fix it by restarting the app or creating a new redisson client instance and killing the dead one.

**Comment by mrniko** [comment]
Since you're experience timeout with batch, could you share your code which executes batch?

**Comment by kringol** [comment]
Sure
It is something like this at the moment

```
    public CompletionStage<Map<String, V>> doGetAllAsync(@NotNull Set<String> keys) {
        final RedissonClient client = getClient();
        final RBatch batch = client.createBatch();

        for (String key : keys) {
            batch.<V> getBucket(key).getAsync();
        }
        return batch.executeAsync().thenApply(objects -> {
            final Iterator<?> iterator = objects.getResponses().iterator();
            Map<String, V> result = new HashMap<>();
            for (String key : keys) {
                final Object value = iterator.next();
                if (value != null) {
                    result.put(key, uncheckedCast(value));
                }
            }
            return result;
        });
    }
```

Reason why we are also using RBatch to make a bunch of GET calls is that MGET did not support handling the CROSSSLOT behavior on cluster mode. And as a plus RBatch allows us to set a different timeout than the one on the client config (which we usually set a bit higher for init commands being slow during startup like CLUSTER_INFO, CLUSTER_NODES)

**Comment by kringol** [comment]
We just run some tests with redis 5.0.4 (before we had 3.x) and redisson 3.10.4.
And sadly the issue remains when using RBatch, and so far we have found no way to easily reproduce it or narrow down the cause. But it's happening to more and more services using it on our company. And so far our only solution is to restart the containers which displayed the issue, as it does not recover. 
It all starts with this timeout, and basically, all requests timeout like that from that moment on
```2019-11-08 00:55:22.109 +0000 WARN [pool-1-thread-1] [AbstractCache.java:1222] - Error retrieving from cache. Skipping cache and loading directly from the source. Cache keys: [JP:202154, JP:202929, JP:204860]
java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Unable to send batch after 4 retry attempts
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:97)
	at org.redisson.command.CommandBatchService.lambda$executeAsync$4(CommandBatchService.java:545)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.command.CommandBatchService.handle(CommandBatchService.java:884)
	at org.redisson.command.CommandBatchService.lambda$execute$7(CommandBatchService.java:764)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.command.CommandBatchService$3.run(CommandBatchService.java:677)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.redisson.client.RedisTimeoutException: Unable to send batch after 4 retry attempts
	at org.redisson.command.CommandBatchService$3.run(CommandBatchService.java:675)
	... 4 common frames omitted
```

We are also going to try a long running test with redisson 3.11.1 and redis 5.0.4 as well
Will keep updating if we find something new =\

**Comment by mrniko** [comment]
@kringol 

The problem is that connection is acquired but sent command wasn't written into Redis channel. Did you try to increase `nettyThreads` setting and/or `retryInterval`

**Comment by mrniko** [comment]
> We have been using redisson for the past 2 years and many versions. And i don't remember having this issue on older versions.

You were right. That's a regression since 2.3.0 version.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2587
