### ISSUE TITLE
UpdateValve is executed outside application classloader

### ISSUE THREAD

**Issue by jchobantonov** [redisson/redisson#2047]
### Expected behavior
UpdateValve should execute 
manager.store(request.getSession(false))
inside application classloader
### Actual behavior
UpdateValve executes 
manager.store(request.getSession(false))
without application classloader which could lead to ClassNotFoundException

### Redisson version
3.10.7-SNAPSHOT

**Comment by jchobantonov** [comment]
@mrniko the code for the UpdateValve and any valves that supports tomcat redisson session save should be called with application classloader otherwise ClassNotFoundException could occur - although this is quite strange to have ClassNotFoundException been thrown when we store session attributes as the object is already been created in memory ClassNotFoundException could happen when during serialization someone calls Class.forName in order to persist properly the object - once such case is captured in following exception:

```
java.lang.ClassNotFoundException: org.richfaces.function.RichFunction
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:365)
        at org.apache.el.util.ReflectionUtil.forName(ReflectionUtil.java:65)
        at org.apache.el.lang.FunctionMapperImpl$Function.getMethod(FunctionMapperImpl.java:158)
        at org.apache.el.lang.FunctionMapperImpl$Function.writeExternal(FunctionMapperImpl.java:125)
        at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1526)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1424)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at org.apache.el.lang.FunctionMapperImpl.writeExternal(FunctionMapperImpl.java:75)
        at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1526)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at org.apache.el.ValueExpressionImpl.writeExternal(ValueExpressionImpl.java:272)
        at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1526)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at com.sun.facelets.el.TagValueExpression.writeExternal(TagValueExpression.java:128)
        at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1526)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at java.util.HashMap.internalWriteEntries(HashMap.java:1801)
        at java.util.HashMap.writeObject(HashMap.java:1374)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at java.util.ArrayList.writeObject(ArrayList.java:777)
        at sun.reflect.GeneratedMethodAccessor479.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at java.util.ArrayList.writeObject(ArrayList.java:777)
        at sun.reflect.GeneratedMethodAccessor479.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at java.util.ArrayList.writeObject(ArrayList.java:777)
        at sun.reflect.GeneratedMethodAccessor479.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1431)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1205)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1615)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1576)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:344)
        at java.util.HashMap.writeObject(HashMap.java:1374)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:344)
        at java.util.HashMap.writeObject(HashMap.java:1374)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1615)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:458)
        at org.ajax4jsf.application.AjaxStateHolder.writeObject(AjaxStateHolder.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1200)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1563)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1499)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1209)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:365)
        at org.redisson.codec.SerializationCodec$2.encode(SerializationCodec.java:67)
        at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:278)
        at org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:424)
        at org.redisson.RedissonMap.putAllAsync(RedissonMap.java:365)
        at org.redisson.RedissonMap.putAll(RedissonMap.java:296)
        at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:347)
        at org.redisson.tomcat.RedissonSession.saveRequestSessionAttributeCache(RedissonSession.java:111)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:52)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.redisson.tomcat.RequestSessionAttributeCacheValve.invoke(RequestSessionAttributeCacheValve.java:45)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:811)
```

Here is the code right now for UpdateValve:
```
    @Override
    public void invoke(Request request, Response response) throws IOException, ServletException {
        try {
            getNext().invoke(request, response);
        } finally {
           manager.store(request.getSession(false));
        }
    }

```

And here is what I'm suggesting :

```
    @Override
    public void invoke(Request request, Response response) throws IOException, ServletException {
        try {
            getNext().invoke(request, response);
        } finally {
			final ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
			try {
				ClassLoader applicationClassLoader = request.getContext().getLoader().getClassLoader();
				Thread.currentThread().setContextClassLoader(applicationClassLoader);
				manager.store(request.getSession(false));
			} finally {
				Thread.currentThread().setContextClassLoader(classLoader);
			}
        }
    }
```

**Comment by jchobantonov** [comment]
Also in RedissonSessionManager
probably this code
```
        final ClassLoader applicationClassLoader;
        if (Thread.currentThread().getContextClassLoader() != null) {
            applicationClassLoader = Thread.currentThread().getContextClassLoader();
        } else {
            applicationClassLoader = getClass().getClassLoader();
        }
```
could become this as well:

```
        final ClassLoader applicationClassLoader;
	if (getContext().getLoader().getClassLoader() != null) {
            applicationClassLoader = getContext().getLoader().getClassLoader();
        } else if (Thread.currentThread().getContextClassLoader() != null) {
            applicationClassLoader = Thread.currentThread().getContextClassLoader();
        } else {
            applicationClassLoader = getClass().getClassLoader();
        }
```

e.g try to use getContext().getLoader().getClassLoader() first

@mrniko ^

**Comment by mrniko** [comment]
Thanks for pointing out. Could you suggest PR?

**Comment by jchobantonov** [comment]
PR: https://github.com/redisson/redisson/pull/2053
