### ISSUE TITLE
Redisson 3.10.6 with liferay 7.1 tomcat 9 and redis 5.0.4

### ISSUE THREAD

**Issue by jonnylove** [redisson/redisson#2063]
### Expected behavior
No exception
### Actual behavior
On liferay / tomcat start i see this error:
[redisson-netty-1-23] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0x7fd12bdb, L:/127.0.0.1:50454 - R:127.0.0.1/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=162, widx=162), command: (HGET), params: [redisson:tomcat_session:163C090D93D292EE5B8CBBF4535DE140, PooledUnsafeDirectByteBuf(ridx: 0, widx: 18, cap: 256)]
java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:com.liferay.portal.model.impl.PortalPreferencesImpl loader:org.eclipse.osgi.internal.loader.EquinoxClassLoader@633328d3[classic-theme:2.0.24(id=1008)]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
        at org.redisson.codec.FstCodec$1.decode(FstCodec.java:164)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:364)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:199)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:139)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
.........

### Steps to reproduce or test case
-Install vanilla version of Liferay 7.1 with openjdk 8 or 11: https://dev.liferay.com/discover/deployment/-/knowledge_base/7-1/preparing-for-install
No needs of extra configs
-Follow the instructions on site: https://github.com/redisson/redisson/tree/master/redisson-tomcat

### Redis version
5.0.4
### Redisson version
3.10.6
### Redisson configuration
---
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

**Comment by jonnylove** [comment]
Does somebody use redisson with liferay dxp, it is supported?

**Comment by mrniko** [comment]
Probably related to this issue https://github.com/redisson/redisson/issues/2071

Please find updated modules below:

[redisson-tomcat-9-3.10.7-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3119984/redisson-tomcat-9-3.10.7-SNAPSHOT.jar.zip)
[redisson-tomcat-8-3.10.7-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3119986/redisson-tomcat-8-3.10.7-SNAPSHOT.jar.zip)
[redisson-all-3.10.7-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3119988/redisson-all-3.10.7-SNAPSHOT.jar.zip)

**Comment by jonnylove** [comment]
Probably related to this issue #2071

Please find updated modules below:

redisson-tomcat-9-3.10.7-SNAPSHOT.jar.zip
redisson-tomcat-8-3.10.7-SNAPSHOT.jar.zip
redisson-all-3.10.7-SNAPSHOT.jar.zip

I test with the snapshot 3.10.7 ... i have the same error...

**Comment by mrniko** [comment]
@jonnylove 

I rushed a bit. It's not merged yet. Here is the fork with fix of #2071 https://github.com/jchobantonov/redisson

**Comment by jonnylove** [comment]
Hi,

Thanks  for your help

I build de fork and test it ... but i still have de same behaviour/error ... i think that the source of the issue 2063  is not the same of the issue 2071.

Do you know if reddisson have been already use by Liferay?

**Comment by mrniko** [comment]
Have solved the issue?

**Comment by epalazuelosb** [comment]
> Hi,
> 
> Thanks for your help
> 
> I build de fork and test it ... but i still have de same behaviour/error ... i think that the source of the issue 2063 is not the same of the issue 2071.
> 
> Do you know if reddisson have been already use by Liferay?

Did you solved the issue?

**Comment by sam701** [comment]
@mrniko I have the same error but with redisson 3.13.1 and tomcat 8. Is redisson supposed to work with osgi out of the box or it must be additionally configured to be aware of?

**Comment by mrniko** [comment]
@sam701 
Redisson is OSGI compatible. Let me know if you have any issue with it or something is missed.

**Comment by sam701** [comment]
I had exactly the same error `org.redisson.client.handler.CommandDecoder`. Then I tried to implement my own codec with this constructor
```java
    public LiferayMarshallingCodec() {
        super(com.liferay.portal.kernel.util.PortalClassLoaderUtil.getClassLoader());
    }
```
It worked. But then I ended up specifying `useThreadClassLoader: false` in my `redisson.yml` so I do not need to compile my own java code.
