### ISSUE TITLE
"Unable to send command" from time to time

### ISSUE THREAD

**Issue by jackmalkovick** [redisson/redisson#2089]
Hello,

I'm using for tests Redis 4.x version on a single master node with a Redission java client.
I'm making concurrent hget requests trough getMap().get() from about 20 threads.
nettyThreads is configured to 100 
<redisson:client netty-threads="100"> ...

If works fine, I just sometimes I get an error like this:

Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, 
freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=27, freeConnectionsCounter=value:59:queue:0, freezed=false, freezeReason=null, client=[addr=redis://xxx:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1935367643 [redisClient=[addr=redis://xxx:6379], channel=[id: 0x58c3b08b, L:/xxx:42475 - R:xxx/xxx:6379], command=null], current command in queue: null, command: (HGET), params: [multi-index, PooledUnsafeDirectByteBuf(ridx: 0, widx: 11, cap: 256)] after 3 retry attempts
        at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
Did try to set `pingConnectionInterval` setting to keep connection alive?

**Comment by zzhgithub** [comment]
Hi! And I got the same problem .here is my config of Redisson.
```
Config config = new Config();
        config.setThreads(16);
        config.setTransportMode(TransportMode.NIO);
        config.setNettyThreads(64);
        config.useSingleServer()
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setTcpNoDelay(true)
                .setKeepAlive(true)
                .setPingConnectionInterval(60)
                .setAddress(redisUri);
```
how can i to fix it ? I had used `setPingConnectionInterval`
thx!

**Comment by mrniko** [comment]
@zzhgithub 

set `connectionMinimumIdleSize` = `connectionPoolSize` = `64`
set `subscriptionConnectionPoolSize` = `subscriptionConnectionMinimumIdleSize` = 50

Also could you share your exception?

**Comment by zzhgithub** [comment]
@mrniko  
something news !  my project run all night ,and that problem never happen again. thank you very very much!!!!
lol!

**Comment by mrniko** [comment]
@zzhgithub 

Good! Thanks for your feedback

**Comment by zzhgithub** [comment]
@mrniko OMG! I meet the same problem again 。
i use the v3.10.5.And here is my exception
```
Exception in thread "EventConsume-ELE_REG_ADMIN_EVENT" org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=50, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=61, freeConnectionsCounter=value:61:queue:0, freezed=false, freezeReason=null, client=[addr=redis://r-uf67d9deea701164.redis.rds.aliyuncs.com:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1062633067 [redisClient=[addr=redis://r-uf67d9deea701164.redis.rds.aliyuncs.com:6379], channel=[id: 0x49bd1c05, L:/10.50.0.8:41186 ! R:r-uf67d9deea701164.redis.rds.aliyuncs.com/172.16.0.145:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5fb4151a(failure: java.util.concurrent.CancellationException)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (LINDEX), params: [ele.reg.admin.message, 0] after 3 retry attempts
	at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:873)
	at org.redisson.command.CommandAsyncService.access$000(CommandAsyncService.java:97)
	at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:792)
	at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:789)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at org.redisson.client.handler.CommandsQueue.channelInactive(CommandsQueue.java:92)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at org.redisson.client.handler.ConnectionWatchdog.channelInactive(ConnectionWatchdog.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:826)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.WriteRedisConnectionException: Channel has been closed! Can't write command: (LINDEX), params: [ele.reg.admin.message, 0] to channel: [id: 0x49bd1c05, L:/10.50.0.8:41186 ! R:r-uf67d9deea701164.redis.rds.aliyuncs.com/172.16.0.145:6379]
	at org.redisson.client.handler.CommandsQueue.channelInactive(CommandsQueue.java:94)
```
Help me please.
i try it
```
set connectionMinimumIdleSize = connectionPoolSize = 64
set subscriptionConnectionPoolSize = subscriptionConnectionMinimumIdleSize = 50
```
it works a day .now the error comes again.

**Comment by mrniko** [comment]
@zzhgithub 

root cause of exception is `Channel has been closed! Can't write command` please check your network.

**Comment by zzhgithub** [comment]
@mrniko  you mean I really lost connect to the Redis server?
but it seems impossble. 
My idea is that redisson can be reconnected senselessly after the break. Like some kind of watchdog。

In fact. I use redisson to be a  queue. can you check my project?  and sorry i am working in ChongQing/China  I promisee i will upload my project at  tonight.

**Comment by zzhgithub** [comment]
@mrniko  
sorry , I find that I can put my code on github now. and should I set `tcp-keepalive` in redis?
