### ISSUE TITLE
ERROR Exception occured. Channel: [id: 0xc8423c0e, L:/192.168.144.77:56588 - R:192.168.119.10/192.168.119.10:9001] | CommandsQueue.exceptionCaught(153)

### ISSUE THREAD

**Issue by jikuanyu** [redisson/redisson#2094]
### Actual behavior
Running for a while will happen。

2019-05-07 12:25:16,383 ERROR Exception occured. Channel: [id: 0x4d9736e1, L:/192.168.144.77:56563 - R:192.168.119.10/192.168.119.10:9001] | CommandsQueue.exceptionCaught(153)
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[zzent]2019-05-07 12:25:16,383 ERROR Exception occured. Channel: [id: 0x37894027, L:/192.168.144.77:56580 - R:192.168.119.10/192.168.119.10:9001] | CommandsQueue.exceptionCaught(153)
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[zzent]2019-05-07 12:25:16,388 ERROR Exception occured. Channel: [id: 0xc39786f5, L:/192.168.144.77:56574 - R:192.168.119.10/192.168.119.10:9001] | CommandsQueue.exceptionCaught(153)
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (30000 ms) occured after 5 retry attempts. Command: (HGET), params: [KS_MP_CACHE, PooledUnsafeDirectByteBuf(ridx: 0, widx: 12, cap: 256)], channel: [id: 0xc779d9ef, L:/192.168.144.77:49987 - R:192.168.119.10/192.168.119.10:9001]
### Redis version
Redis server v=5.0.4 
### Redisson version
redisson 2.15.2
### Redisson configuration
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":30000,
      "retryAttempts":5,
      "retryInterval":1000,
      "reconnectionTimeout":30000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://192.168.119.10:9001",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":11
    },
   "threads":16,
   "nettyThreads":32,
   "codec":{
      "class":"org.redisson.codec.FstCodec"
   },
   "transportMode":"NIO"
}

jdk1.7,apache-tomcat-7.0.94

codes/**
 * redis缓存单例实例管理。
 * @author yujikuan
 *
 */
public class RedissonManager {
	
	private static Logger log=Logger.getLogger(RedissonManager.class);
	private static class SingletonHolder {
       private static final RedissonManager INSTANCE = new RedissonManager();
      }
	
	public static final RedissonManager getInstance() {
           return SingletonHolder.INSTANCE;
     }
   private RedissonClient redisson =null;
   
  
   private RedissonManager()
    {
	   try {
		ChangeRedissionAddress.cfgRedisson();
	} catch (ChangeFileException e2) {
		log.error(e2);
	}
    	
    	String redissonCofigFilePath="";
    	try {
			redissonCofigFilePath=RedissonManager.class.getClassLoader().getResource("redisson-config.json").toURI().getPath();
		} catch (URISyntaxException e1) {
			log.error(e1);
		}
    	
      Config config=null;
		try {
			config = Config.fromJSON(new File(redissonCofigFilePath));
		} catch (IOException e) {
			log.error(e);
		}
		
    	 redisson = Redisson.create(config);
    	 localmaps=new ConcurrentHashMap<String,RLocalCachedMap<Object, Object>>();
     }
  private  Map<String,RLocalCachedMap<Object, Object>> localmaps=null;
  
  private  LocalCachedMapOptions<Object, Object>  options=LocalCachedMapOptions.defaults(); 
   
   public <K, V> RLocalCachedMap<K, V> getDefaultRLocalCached(String mapKey)
   {
	   RLocalCachedMap<K, V> cachedMap=null;
	   if(localmaps.get(mapKey)==null)
	   {
	      cachedMap= (RLocalCachedMap<K, V>) redisson.getLocalCachedMap(mapKey,options);
	      localmaps.put(mapKey, (RLocalCachedMap<Object, Object>) cachedMap);
	   }else
	   {
		   cachedMap=(RLocalCachedMap<K, V>) localmaps.get(mapKey); 
	   }   
	   return cachedMap;
   }
   
   public void clear(String mapKey)
   {
	 
	   if(localmaps.get(mapKey)!=null)
	   {
		   localmaps.get(mapKey).clearLocalCache();
	   }
	   
	   //redisson.getLocalCachedMap(mapKey, options)
   }
   
   public <K, V> RLocalCachedMap<K, V> getDefaultRLocalCachedS()
   {
	   LocalCachedMapOptions<K, V> options=LocalCachedMapOptions.defaults();
	  return redisson.getLocalCachedMap("myMapx",options);
   }
   
  public RedissonClient getRedissonClient()
   {
	   return redisson;
   }
   public void shutDown()
   {
	  
	   if(redisson!=null)
	   {
		  redisson.shutdown();
		 log.info("redsson shutdown");
	  }
   }

}

**Comment by jackygurui** [comment]
`远程主机强迫关闭了一个现有的连接。`这个报错是由于服务端把连接异常断开了。请先检查服务端的情况。

**Comment by jikuanyu** [comment]
thanks,  我在日志中仅仅看到这些警告。我先调整这些试试。
1906:M 27 Apr 2019 01:00:52.091 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1906:M 27 Apr 2019 01:00:52.091 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

**Comment by jackygurui** [comment]
通常跟防火墙有关
