### ISSUE TITLE
redissonClient.getKeys().deleteByPatternAsync

### ISSUE THREAD

**Issue by laomolaomo** [redisson/redisson#2108]
### Redisson configuration  config.useSingleServer().setAddress("redis://" +redisProperties.getHost() + ":" + redisProperties.getPort()); config.setEventLoopGroup(new NioEventLoopGroup());

[2019-05-15 10:48:08 ERROR] [nioEventLoopGroup-2-8] [CommandDecoder.java:134] - Unable to decode data. reply: *2
$4
6672
*0
, channel: [id: 0x9e3649f8, L:/172.23.193.131:53309 - R:192.168.240.121/192.168.240.121:8379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@ef9691d(failure: java.util.concurrent.CancellationException)], command=(SCAN), params=[0, MATCH, gift:goodsList:215:*, COUNT, 100], codec=org.redisson.client.codec.StringCodec]
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:239)
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:887)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
Timeout has occured becuse you stopped command execution at breakpoint.
