### ISSUE TITLE
Fails to store Tomcat 8 Session in Redis 

### ISSUE THREAD

**Issue by gbarsky** [redisson/redisson#2110]
### Expected behavior
Hi, 
I am using "AFTER_REQUEST" update mode in Redisson Session Manager configuration to ensure that mutable session attributes are in sync with the session stored in Redis 
But it fails with this exception : 
Caused by: java.lang.RuntimeException: Class org.apache.catalina.session.StandardSessionFacade does not implement Serializable or externalizable
This is my configuration:

    <ResourceLink name="bean/redisson"
                  global="bean/redisson"
		  type="org.redisson.api.RedissonClient" />

     <Manager className="org.redisson.tomcat.JndiRedissonSessionManager"
         readMode="REDIS"
         updateMode="AFTER_REQUEST"
         jndiName="bean/redisson" />
        
Please advise what is wrong ?
### Redisson version

I am running Tomcat 8.0.14 version and Redisson Tomcat jar - redisson-tomcat-8-3.10.6.jar

**Comment by mrniko** [comment]
Could you provide full stacktrace?

**Comment by gbarsky** [comment]
May 15, 2019 11:40:13 AM org.apache.coyote.http11.AbstractHttp11Processor process
SEVERE: Error processing request
java.lang.IllegalArgumentException: java.io.IOException: java.lang.RuntimeException: Class org.apache.catalina.session.StandardSessionFacade does not implement Serializable or externalizable
	at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:330)
	at org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:403)
	at org.redisson.RedissonMap.putAllAsync(RedissonMap.java:344)
	at org.redisson.RedissonMap.putAll(RedissonMap.java:281)
	at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:310)
	at org.redisson.tomcat.RedissonSessionManager.store(RedissonSessionManager.java:339)
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:46)
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:44)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: java.lang.RuntimeException: Class org.apache.catalina.session.StandardSessionFacade does not implement Serializable or externalizable
	at org.redisson.codec.FstCodec$2.encode(FstCodec.java:191)
	at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:328)
	... 17 more
Caused by: java.lang.RuntimeException: Class org.apache.catalina.session.StandardSessionFacade does not implement Serializable or externalizable
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:144)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:369)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectFields(FSTObjectOutput.java:664)
	at org.nustaq.serialization.FSTObjectOutput.defaultWriteObject(FSTObjectOutput.java:546)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:458)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:204)
	at org.redisson.codec.FstCodec$2.encode(FstCodec.java:183)

**Comment by jchobantonov** [comment]
@gbarsky are you trying to store the actual http session into it's attributes?
Something like : 
HttpSession session = request.getSession();
session.setAttribute("someattr", session);

Or probably an object that do have reference to the HttpSession and it is tried to be stored as attribute like:
class MyObject {
  HttpSession session;
}

HttpSession session = request.getSession();
MyObject obj = new MyObject();
obj.session = session;
session.setAttribute("someattr", obj);

as org.apache.catalina.session.StandardSessionFacade indeed do not implement Serializable and it is the class used to give you the HttpSession when asked from the web app

**Comment by gbarsky** [comment]
Thank you. Yes, it seems to be the case. We store session as one of the attributes in the object which is stored in the session by itself

**Comment by mrniko** [comment]
@gbarsky 

Have you resovled the issue?
