### ISSUE TITLE
Redis connection fails to re-establish

### ISSUE THREAD

**Issue by romanblachman** [redisson/redisson#2115]
### Expected behavior
Redisson in single server mode should reconnect after the connection is unavailable for some time.

### Actual behavior
Redisson fails to re-establish a connection to the Redis server.

### Steps to reproduce or test case
Hard to reproduce.

### Redis version
4.0.1

### Redisson version
3.5.0

### Redisson configuration
`        Config config = new Config();
        config.useSingleServer()
              .setAddress(serverAddress.toString())
              .setRetryAttempts(retryAttempts)
              .setRetryInterval(retryInterval);
`

At some point, when Redis is needed, an error is reported when trying to 

`java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: MasterConnectionPool no available Redis entries.  Disconnected hosts: [localhost/127.0.0.1:6378]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1284)
	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1270)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:97)
	at org.redisson.command.CommandAsyncService.checkAttemptFuture(CommandAsyncService.java:804)
	at org.redisson.command.CommandAsyncService.access$300(CommandAsyncService.java:79)
	at org.redisson.command.CommandAsyncService$9.operationComplete(CommandAsyncService.java:609)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:98)
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:539)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisConnectionException: MasterConnectionPool no available Redis entries.  Disconnected hosts: [localhost/127.0.0.1:6378]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:196)
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:31)
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:409)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:708)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:502)
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:551)
	... 4 common frames omitted`

Debug logs when the connection is unavailable, and redisson is trying to reconnect:

`2019-05-16 13:01:06,518 DEBUG 2920 [ool-41-thread-1] o.r.client.handler.ConnectionWatchdog    : reconnecting RedisConnection@1311315531 [redisClient=[addr=localhost/127.0.0.1:6378], channel=[id: 0x0e9a8682, L:0.0.0.0/0.0.0.0:64139]] to localhost/127.0.0.1:6378 
2019-05-16 13:01:06,519 DEBUG 2920 [isson-netty-1-6] o.r.client.handler.ConnectionWatchdog    : RedisConnection@1311315531 [redisClient=[addr=localhost/127.0.0.1:6378], channel=[id: 0x0e9a8682, L:0.0.0.0/0.0.0.0:64139]] connected to localhost/127.0.0.1:6378, command: null
2019-05-16 13:01:06,695 DEBUG 2920 [ool-54-thread-1] o.r.client.handler.ConnectionWatchdog    : reconnecting RedisConnection@1621118964 [redisClient=[addr=localhost/127.0.0.1:6378], channel=[id: 0x312d8beb, L:0.0.0.0/0.0.0.0:64141]] to localhost/127.0.0.1:6378 
2019-05-16 13:01:06,695 DEBUG 2920 [isson-netty-5-3] o.r.client.handler.ConnectionWatchdog    : RedisConnection@1621118964 [redisClient=[addr=localhost/127.0.0.1:6378], channel=[id: 0x312d8beb, L:0.0.0.0/0.0.0.0:64141]] connected to localhost/127.0.0.1:6378, command: null
2019-05-16 13:01:06,845 DEBUG 2920 [ool-54-thread-1] o.r.client.handler.ConnectionWatchdog    : reconnecting RedisConnection@452093370 [redisClient=[addr=localhost/127.0.0.1:6378], channel=[id: 0x5168a7f1, L:0.0.0.0/0.0.0.0:64143]] to localhost/127.0.0.1:6378 
2019-05-16 13:01:06,845 DEBUG 2920 [isson-netty-5-4] o.r.client.handler.ConnectionWatchdog    : RedisConnection@452093370 [redisClient=[addr=localhost/127.0.0.1:6378], channel=[id: 0x5168a7f1, L:0.0.0.0/0.0.0.0:64143]] connected to localhost/127.0.0.1:6378, command: null`

**Comment by jackygurui** [comment]
Have you tried with later versions?

**Comment by romanblachman** [comment]
Not yet, but I plan to. I'm just curious if it can be explained by the following issues:
https://github.com/redisson/redisson/issues/1610
https://github.com/redisson/redisson/issues/1691
https://github.com/redisson/redisson/issues/1632

The issue is very hard to reproduce, as redission client **sometimes** gets into a state where it fails to re-establish the connection. In fact, I'm unable to reproduce in our development environment as it happens only in production deployment. The only thing that resolves is restarting the process, and then the redisson client connects successfully.

**Comment by romanblachman** [comment]
Notice that it says "reconnecting" and then "connected to" but then goes back again to "reconnecting".

**Comment by mrniko** [comment]
@romanblachman 

> Notice that it says "reconnecting" and then "connected to" but then goes back again to "reconnecting".

Please try it with latest version and give your feedback.
