### ISSUE TITLE
RedissonClient CreateError  in my Production Environment

### ISSUE THREAD

**Issue by Linzol** [redisson/redisson#2133]
### Expected behavior
Development environment ,it run ok ,i use it well。
development-right-log
		[INFO] 29 16:11:13 [main] - Redisson 3.10.7
		[INFO] 29 16:11:13 [main] - redis://127.0.0.1:6379 is the master
		[WARN] 29 16:11:13 [main] - ReadMode = SLAVE, but slave nodes are not found! Please specify all nodes in replicated mode.
		[INFO] 29 16:11:13 [redisson-netty-4-7] - 32 connections initialized for 127.0.0.1/127.0.0.1:6379
		[INFO] 29 16:11:13 [redisson-netty-4-5] - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
		[INFO] 29 16:11:13 [redisson-netty-4-9] - 32 connections initialized for 127.0.0.1/127.0.0.1:6379
		[INFO] 29 16:11:13 [redisson-netty-4-11] - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
		[INFO] 29 16:11:14 [main] - Redisson 3.10.7
		[INFO] 29 16:11:14 [main] - redis://127.0.0.1:6379 is the master
		[WARN] 29 16:11:14 [main] - ReadMode = SLAVE, but slave nodes are not found! Please specify all nodes in replicated mode.
		[INFO] 29 16:11:14 [redisson-netty-6-18] - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
		[INFO] 29 16:11:14 [redisson-netty-6-6] - 32 connections initialized for 127.0.0.1/127.0.0.1:6379
		[INFO] 29 16:11:14 [redisson-netty-6-10] - 32 connections initialized for 127.0.0.1/127.0.0.1:6379
		[INFO] 29 16:11:14 [redisson-netty-6-11] - 1 connections initialized for 127.0.0.1/127.0.0.1:6379

development-redis-version		

	    Redis 2.8.2101 (00000000/0) 64 bit

development-redisson-version:
	<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.10.7</version>
        </dependency>
        
development-redisson-conf:
    @Bean
    public RedissonClient redisson() throws IOException {
	Config config = new Config();
        config.useReplicatedServers()
                .setScanInterval(2000) // 主节点变化扫描间隔时间
                .addNodeAddress("redis://127.0.0.1:6379")
                .setPassword("123456");
	return Redisson.create(config);
    }

### Actual behavior
       in my Production Environment it didnt work ,and throw those Exception.
Production-error-log
       Redisson 3.10.7
		org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'roomUtil': Unsatisfied dependency expressed through field 'redisson'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisson' defined in com.App: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is java.lang.NullPointerException: Name is null
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)
			at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1336)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
			at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
			at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
			at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
			at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
			at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
			at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
			at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
			at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
			at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
			at com.App.main(App.java:53)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
			at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
		Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisson' defined in com.App: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is java.lang.NullPointerException: Name is null
			at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
			at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
			at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
			at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
			at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
			at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:581)
			... 25 more
		Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is java.lang.NullPointerException: Name is null
			at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
			at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
			... 37 more
		Caused by: java.lang.NullPointerException: Name is null
			at java.lang.Enum.valueOf(Enum.java:236)
			at org.redisson.connection.ReplicatedConnectionManager$Role.valueOf(ReplicatedConnectionManager.java:60)
			at org.redisson.connection.ReplicatedConnectionManager.<init>(ReplicatedConnectionManager.java:79)
			at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:238)
			at org.redisson.Redisson.<init>(Redisson.java:119)
			at org.redisson.Redisson.create(Redisson.java:159)
			at com.App.redisson(App.java:146)
			at com.App$$EnhancerBySpringCGLIB$$e3868ddc.CGLIB$redisson$3(<generated>)
			at com.App$$EnhancerBySpringCGLIB$$e3868ddc$$FastClassBySpringCGLIB$$1f9713c.invoke(<generated>)
			at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
			at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
			at com.App$$EnhancerBySpringCGLIB$$e3868ddc.redisson(<generated>)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
			... 38 more            
Production-redis-version
		Redis 4.0 (Alibaba Cloud Cluster Edition)

Production-redisson-version:
	<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.10.7</version>
        </dependency>
        
Production-redisson-conf:
    @Bean
    public RedissonClient redisson() throws IOException {
	Config config = new Config();
        config.useReplicatedServers()
                .setScanInterval(2000) // 主节点变化扫描间隔时间
                .addNodeAddress("redis://127.0.0.1:6379")
                .setPassword("123456");
	return Redisson.create(config);
    }

### Steps to reproduce or test case
  public class App{
      public static void main(String[] args) {
        SpringApplication.run(App.Class，args)
      }
  }

### Redis version
  development-redis-version		
	    Redis 2.8.2101 (00000000/0) 64 bit

  Production-redis-version
		Redis 4.0 (Alibaba Cloud Cluster Edition)

### Redisson version
         <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.10.7</version>
        </dependency>

### Redisson configuration
    @Bean
    public RedissonClient redisson() throws IOException {
				Config config = new Config();
        config.useReplicatedServers()
                .setScanInterval(2000) // 主节点变化扫描间隔时间
                .addNodeAddress("redis://127.0.0.1:6379")
                .setPassword("123456");
				return Redisson.create(config);
    }

**Comment by mrniko** [comment]
you have wrong Redis configuration because INFO REPLICATION command doesn't return "role" field
