### ISSUE TITLE
[HELP]Default configuration hasn't been specified!

### ISSUE THREAD

**Issue by tain198127** [redisson/redisson#2141]
### Expected behavior
startup
### Actual behavior
get error 
`
Caused by: java.lang.IllegalStateException: Default configuration hasn't been specified!
	at org.redisson.jcache.JCacheManager.createCache(JCacheManager.java:118)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration.jCacheCacheManager(JCacheCacheConfiguration.java:101)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$$EnhancerBySpringCGLIB$$a6ce7558.CGLIB$jCacheCacheManager$1(<generated>)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$$EnhancerBySpringCGLIB$$a6ce7558$$FastClassBySpringCGLIB$$3ebd8bcd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$$EnhancerBySpringCGLIB$$a6ce7558.jCacheCacheManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
`
### Steps to reproduce or test case
1. use redisson with springboot 
2. use `spring.cache.chach-name=default` in application.properties

### Redis version
server :2.6.9
### Redisson version
3.7.5
### Redisson configuration
`
Config config = new Config();
config.setTransportMode(TransportMode.NIO);
config.useSingleServer().setAddress("redis://"+this.redisProperties.getHost()+":"+this.redisProperties.getPort());
config.useSingleServer().setPassword(this.redisProperties.getPassword());
config.useSingleServer().setTimeout(this.redisProperties.getTimeout());
`

**Comment by mrniko** [comment]
You need to place config file in root of classpath with name `redisson-jcache.json` or `redisson-jcache.yaml`
