### ISSUE TITLE
CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by nickletgo** [redisson/redisson#2145]
We have a testing redis cluster environment with only **1 master and 1 slave**. When using redisson client with RedissonBinaryStream to write byte array to redis server, we encountered the exception logged below. 
 
### Expected behavior
Successfully write and read from Redis Cluster using RedissonBinaryStream implementation

### Actual behavior
Seeing exception:

```
Exception in thread "main" org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x6264422d, L:/<hide ip>:61627 - R:/<hide ip>:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@5ebfe264[Not completed], command=(EVAL), params=[local parts = redis.call('get', KEYS[2]); local lastPartName = KEYS[1];if parts ~= false then lastPa..., 2, stream-test, stream-test:parts], codec=org.redisson.client.codec.ByteArrayCodec@16e94982]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:267)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Redis version
3.2.8
### Redisson version
3.4.1

### Redisson configuration
```
 String redisClusterEntryEndpoint = bcConfig.getEndpoint();
        Config config = new Config();
        config.useClusterServers().addNodeAddress(redisClusterEntryEndpoint);
        return Redisson.create(config);
```
```
OutputStream os = redissonClient.getBinaryStream(key).getOutputStream();
os.write(bytes);
```

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version.

**Comment by nickletgo** [comment]
Hi @mrniko 

I setup a redis cluster with one master node in latest version and still seeing the issue. Do you suggest using the latest Redisson build?

Redis version
--------------------
5.0.5

**Comment by mrniko** [comment]
Sorry, I meant the latest Redisson version - 3.11.0

**Comment by mrniko** [comment]
Also please note, that minimal recommended amount of masters in Redis Cluster is 3

**Comment by nickletgo** [comment]
Sure, we only use this single node cluster for connectivity testing with Redisson client and will add more nodes later.

We will try to use the latest version and check again. Since you can't reproduce it with latest version, I will just close this issue and will open a new one if the issue persists. 

Thanks a lot for your help!

**Comment by ouyangshixiong** [comment]
I reproduce the bug during test. 
redis version : 4.0.14
redisson version: 3.11.2
Use many rlo objects.
![bug](https://user-images.githubusercontent.com/2086862/74494613-73da9f80-4f10-11ea-9a38-1fa3957b103e.jpg)
@nickletgo

**Comment by mrniko** [comment]
@ouyangshixiong 

This issue was fixed in https://github.com/redisson/redisson/commit/4a1681629df1058abe8931fe5ec8243711e5d58f
