### ISSUE TITLE
redisson fails to connect to slave node

### ISSUE THREAD

**Issue by EldarZ** [redisson/redisson#2146]
redisson fails to connect to slave node. 

### Expected behavior
successful connection.
### Actual behavior
> Can't add slave: rediss://[ip]:[port]",mhash="6ff2ffa1",exc="org.redisson.client.RedisConnectionException: Unable to connect to Redis server: [ip1]/[ip2]:[port]
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:160)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:330)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:296)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:245)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.nio.AbstractNioChannel.doClose()(Unknown Source)

### Redis version
3.2.7
### Redisson version
3.10.7
### Redisson configuration

> {
  "clusterServersConfig" : {
    "idleConnectionTimeout" : 10000,
    "pingTimeout" : 1000,
    "connectTimeout" : 10000,
    "timeout" : 3000,
    "retryAttempts" : 3,
    "retryInterval" : 3500,
    "password" : "1",
    "subscriptionsPerConnection" : 15,
    "sslEnableEndpointIdentification" : true,
    "sslProvider" : "JDK",
    "pingConnectionInterval" : 0,
    "keepAlive" : false,
    "tcpNoDelay" : false,
    "loadBalancer" : {
      "class" : "org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveConnectionMinimumIdleSize" : 10,
    "slaveConnectionPoolSize" : 35,
    "failedSlaveReconnectionInterval" : 3000,
    "failedSlaveCheckInterval" : 60000,
    "masterConnectionMinimumIdleSize" : 10,
    "masterConnectionPoolSize" : 35,
    "readMode" : "MASTER",
    "subscriptionMode" : "MASTER",
    "subscriptionConnectionMinimumIdleSize" : 1,
    "subscriptionConnectionPoolSize" : 30,
    "dnsMonitoringInterval" : 5000,
    "natMap" : { },
    "nodeAddresses" : [ "rediss://[ip]:[port]" ],
    "scanInterval" : 10000,
    "slaveSubscriptionConnectionPoolSize" : 30,
    "slaveSubscriptionConnectionMinimumIdleSize" : 1
  },
  "threads" : 0,
  "nettyThreads" : 0,
  "codec" : {
    "class" : "org.redisson.codec.JsonJacksonCodec"
  },
  "referenceEnabled" : true,
  "transportMode" : "NIO",
  "lockWatchdogTimeout" : 30000,
  "keepPubSubOrder" : true,
  "decodeInExecutor" : false,
  "useScriptCache" : false,
  "minCleanUpDelay" : 5,
  "maxCleanUpDelay" : 1800,
  "addressResolverGroupFactory" : {
    "class" : "org.redisson.connection.RoundRobinDnsAddressResolverGroupFactory"
  }
}

**Comment by mrniko** [comment]
From stacktrace we can see that the reason is:

> Caused by: java.nio.channels.ClosedChannelException

Please check your network
