### ISSUE TITLE
Redisson throws NPE when host name contains underscore in it

### ISSUE THREAD

**Issue by nikolajovickg** [redisson/redisson#2150]
Redisson version 3.10.7
Linked with https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6587184

Problem is in RedisClient.java,  line 172:
```java
        byte[] addr = NetUtil.createByteArrayFromIpAddressString(uri.getHost());
```
`uri.getHost()` is returning null, so validation of address inside netty is throwing NPE when it tries to get length of the string that is null.

I'm providing the stack trace:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 42 more
Caused by: java.lang.NullPointerException
	at io.netty.util.NetUtil.isValidIpV4Address(NetUtil.java:648)
	at io.netty.util.NetUtil.createByteArrayFromIpAddressString(NetUtil.java:368)
	at org.redisson.client.RedisClient.resolveAddr(RedisClient.java:172)
	at org.redisson.connection.MasterSlaveEntry.setupMasterEntry(MasterSlaveEntry.java:123)
	at org.redisson.connection.MasterSlaveEntry.setupMasterEntry(MasterSlaveEntry.java:118)
	at org.redisson.connection.MasterSlaveConnectionManager.initSingleEntry(MasterSlaveConnectionManager.java:345)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:163)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:34)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:229)
	at org.redisson.Redisson.<init>(Redisson.java:119)
	at org.redisson.Redisson.create(Redisson.java:159)
	at net.icpweb.messaging.broker.configuration.MessagingAutoConfiguration.redissonClient(MessagingAutoConfiguration.java:114)
	at net.icpweb.messaging.broker.configuration.MessagingAutoConfiguration$$EnhancerBySpringCGLIB$$30111eb4.CGLIB$redissonClient$1(<generated>)
	at net.icpweb.messaging.broker.configuration.MessagingAutoConfiguration$$EnhancerBySpringCGLIB$$30111eb4$$FastClassBySpringCGLIB$$ba41b375.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at net.icpweb.messaging.broker.configuration.MessagingAutoConfiguration$$EnhancerBySpringCGLIB$$30111eb4.redissonClient(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 43 more

```

Configuration is YAML based:
```
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
  address: "redis_test:3809"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
keepPubSubOrder: true
decodeInExecutor: false
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
