### ISSUE TITLE
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. 

### ISSUE THREAD

**Issue by double2Liang** [redisson/redisson#2199]
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts. Command: (EXISTS), params: [claim_task_concurrent_lock_7b34232d-9721-11e9-a8da-680715517318], channel: [id: 0x59bfd9e4, L:/192.168.10.241:53028 - R:10.65.255.121/10.65.255.121:6379]
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:934)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

config:
redission:3.11.0

{"addressResolverGroupFactory":{},"clusterConfig":false,"codec":{"mapKeyDecoder":{},"mapKeyEncoder":{},"mapValueDecoder":{"$ref":"$.codec.mapKeyDecoder"},"mapValueEncoder":{"$ref":"$.codec.mapKeyEncoder"},"valueDecoder":{"$ref":"$.codec.mapKeyDecoder"},"valueEncoder":{"$ref":"$.codec.mapKeyEncoder"}},"decodeInExecutor":false,"keepPubSubOrder":true,"lockWatchdogTimeout":30000,"maxCleanUpDelay":1800,"minCleanUpDelay":5,"nettyThreads":32,"referenceEnabled":true,"sentinelConfig":false,"threads":16,"transportMode":"NIO","useScriptCache":false}

不懂为啥过段时间就会出现问题 不稳定 求指导

**Comment by mrniko** [comment]
Please refer this topic https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by double2Liang** [comment]
RLock rLock = redissonUtils.getLock(RedisKey);
            try {
                boolean result = rLock.tryLock(0, 10, TimeUnit.SECONDS);
              //do something
}

**Comment by double2Liang** [comment]
> Please refer this topic https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

it doesn't work

**Comment by mrniko** [comment]
which values did you try? Also check your network

**Comment by double2Liang** [comment]
@mrniko  i just try set nettyThreads ,thanks i will do more try

**Comment by double2Liang** [comment]
@mrniko redisson nettyThreads is affected by redis connectionpool size? my test redis max connectionpool size is 200 .

**Comment by double2Liang** [comment]
java.lang.UnsupportedOperationException

**Comment by mrniko** [comment]
nettyThreads value depends on connection pool and average data deserialzation time.

**Comment by double2Liang** [comment]
@mrniko  Thank you for your patient answer. but i debuged found  exception is UnsupportedOperationException

**Comment by mrniko** [comment]
Could you share more detail about this error? full stacktrace?

**Comment by gx304419380** [comment]
> Could you share more detail about this error? full stacktrace?

I alse got the same exception:
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured for command: (HEXISTS) with params: [CLUSTER_LEADER, 7f9806ab-c1f1-43e5-b49a-a936c529cd56:1448] channel: [id: 0x80af8437, L:/10.19.131.236:59965 - R:10.19.131.236/10.19.131.236:7019]
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:882)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

my redisson config is:
Config config = new Config();
        config.setNettyThreads(32)
                .useSingleServer()
                .setConnectTimeout(60000)
                .setTimeout(60000)
                .setRetryAttempts(10)
                .setAddress("redis://" + ip + ":" + port)
                .setPassword(password);

**Comment by mrniko** [comment]
@gx304419380 

Sorry, I don't see UnsupportedOperationException in your stacktrace

**Comment by double2Liang** [comment]
[2019-07-02 15:40:54.865 DEBUG] [http-nio-8090-exec-35] {org.redisson.command.CommandAsyncService:1235}-acquired connection for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, claim_task_concurrent_lock_81dc72f6-9c9c-11e9-b1ec-2c337a5facf3, 9000, bbd95452-1d12-4bfe-a7c3-31232ac77263:141] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=4, freeConnectionsCounter=value:19:queue:0, freezed=false, freezeReason=null, client=[addr=redis://10.65.255.121:6379], nodeType=MASTER, firstFail=0]]] using node 10.65.255.121/10.65.255.121:6379... RedisConnection@1583660889 [redisClient=[addr=redis://10.65.255.121:6379], channel=[id: 0xff35a8bc, L:/172.18.1.74:50486 - R:10.65.255.121/10.65.255.121:6379], currentCommand=null]
[2019-07-02 15:40:57.475 DEBUG] [HikariPool-1 housekeeper] {com.zaxxer.hikari.pool.HikariPool:411}-HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
[2019-07-02 15:41:04.923 DEBUG] [pool-1-thread-1] {org.redisson.command.CommandAsyncService:1008}-connection released for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, claim_task_concurrent_lock_81dc72f6-9c9c-11e9-b1ec-2c337a5facf3, 9000, bbd95452-1d12-4bfe-a7c3-31232ac77263:141] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=5, freeConnectionsCounter=value:20:queue:0, freezed=false, freezeReason=null, client=[addr=redis://10.65.255.121:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1583660889 [redisClient=[addr=redis://10.65.255.121:6379], channel=[id: 0xff35a8bc, L:/172.18.1.74:50486 - R:10.65.255.121/10.65.25

**Comment by honestAnt** [comment]
网络有断开会出现这个问题、（比如mac电脑的sleep后，出去吃个饭（30分钟左右）再开机就会出现）

**Comment by double2Liang** [comment]
@honestAnt  感谢提供场景，但是我没有这种操作  一直没有排查到问题所在  = 。= 然后过段时间又自己好了 怀疑是测试环境问题   = = 很尴尬

**Comment by honestAnt** [comment]
我这边能复现，但是没有较好的解决方案；只能调整那个watchtimeout（调大点）参数，感觉不是很好的实践

**Comment by double2Liang** [comment]
@honestAnt  我也是很纳闷  买办法只能找了替代方案 这个不稳定 不敢线上用啊

**Comment by jackygurui** [comment]
`Redis server response timeout` 表示命令发送出去了，没收到回复。如果解码的时候没出现问题的话，基本跟客户端没关系了。请检查服务端和网络上的问题。

**Comment by iwin4aids** [comment]
我有同样的问题

**Comment by arturgspb** [comment]
@double2Liang @honestAnt @jackygurui  @iwin4aids 

Было бы хорошо, если бы вы писали на английском языке, тогда Google помогал бы найти ответы на схожие вопросы большему количеству людей. Спасибо!

**Comment by pluone** [comment]
我也遇到了这个问题，并且定位了问题。
我的情况是这样的，redis开启了密码认证，并且我的客户端处于NAT环境中，中间有一个路由器。
如果你也是这种情况，那么大概率是因为你服务器上的TCP连接已经关闭了，而本地的状态还是正常状态。
可以通过设置config.setPingConnectionInterval来临时解决一下
具体可以参考我的分析文章https://plu.one/%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91/2020/07/01/redisson-RedisResponseTimeoutException/
