### ISSUE TITLE
Can't execute SENTINELS commands, only happens to the last sentinel server

### ISSUE THREAD

**Issue by piketrcechillas** [redisson/redisson#2201]
I'm using Redis with 1 master and 2 slaves, watched over by 3 sentinels on 3 ports 8359, 8360 and 8361 from a single node. When executing through redisson the program works perfectly fine except that every now and then it spews out this error:

```
[redisson-netty-4-5] ERROR org.redisson.connection.SentinelConnectionManager - Can't execute SENTINEL commands on 10.60.xxx.xxx/10.60.xxxx.xxxx:8361
org.redisson.client.RedisTimeoutException: Command execution timeout for  10.60.xxx.xxx/10.60.xxxx.xxxx:8361
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```
This doesn't really affect anything so far, the sentinels still send data properly to the clients but I have ever wondered what might be the cause of this? It only happens to the last port 8361, the two other ports are unaffected albeit on the same node.

**Comment by mrniko** [comment]
Have you checked your network?

**Comment by mingjia-vip** [comment]
How to solve? I had the same problem

**Comment by kumarkeshav021** [comment]
i also have same problem

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3404
