### ISSUE TITLE
org.redisson.client.RedisTimeoutException:

### ISSUE THREAD

**Issue by asdxiaoqex** [redisson/redisson#2205]
org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=6, freeConnectionsCounter=value:60:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1208139997 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0x0eaaac69, L:/192.168.0.8:53949 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3f5f6794(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3f5f6794(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd], command: (HGETALL), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)
2019-07-01 15:59:46.919  WARN 24032 --- [nio-8099-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=6, freeConnectionsCounter=value:60:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1208139997 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0x0eaaac69, L:/192.168.0.8:53949 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3f5f6794(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3f5f6794(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd], command: (HGETALL), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8] after 3 retry attempts]
2019-07-01 15:59:46.975 ERROR 24032 --- [nio-8099-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=6, freeConnectionsCounter=value:60:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1734246104 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0xc32936dc, L:/192.168.0.8:53945 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3217bd72(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3217bd72(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd], command: (PEXPIRE), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8, 1800000] after 3 retry attempts] with root cause

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=6, freeConnectionsCounter=value:60:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1734246104 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0xc32936dc, L:/192.168.0.8:53945 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3217bd72(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3217bd72(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@750413cd], command: (PEXPIRE), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8, 1800000] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715) ~[redisson-3.10.6.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

/error
2019-07-01 15:59:47.044 ERROR 24032 --- [nio-8099-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=7, freeConnectionsCounter=value:61:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1015602425 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0xc72413df, L:/192.168.0.8:53943 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@34c86c4d(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@34c86c4d(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7], command: (PEXPIRE), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8, 1800000] after 3 retry attempts] with root cause

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=7, freeConnectionsCounter=value:61:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1015602425 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0xc72413df, L:/192.168.0.8:53943 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@34c86c4d(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@34c86c4d(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7], command: (PEXPIRE), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8, 1800000] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715) ~[redisson-3.10.6.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

/error
2019-07-01 15:59:49.488 ERROR 24032 --- [nio-8099-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=6, freeConnectionsCounter=value:60:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1540626475 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0x8cc95170, L:/192.168.0.8:53948 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3b3e743e(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3b3e743e(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7], command: (PEXPIRE), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8, 1800000] after 3 retry attempts] with root cause

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:19:queue:0, freeConnectionsAmount=6, freeConnectionsCounter=value:60:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.0.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1540626475 [redisClient=[addr=redis://192.168.0.250:6379], channel=[id: 0x8cc95170, L:/192.168.0.8:53948 - R:192.168.0.250/192.168.0.250:6379], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3b3e743e(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3b3e743e(failure: java.util.concurrent.CancellationException)], command=(HGETALL), params=[spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8], codec=org.redisson.codec.CompositeCodec@b330f7e7], command: (PEXPIRE), params: [spring:session:5a1e8cc5-a7eb-47ba-9b29-e73e8d4f36c8, 1800000] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715) ~[redisson-3.10.6.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

/error

**Comment by mrniko** [comment]
Please refer this section https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it
