### ISSUE TITLE
3.11.1 无法解析 Host

### ISSUE THREAD

**Issue by huodon** [redisson/redisson#2211]
### Expected behavior

3.11. 0 版本: 

```
16:42:01.132 [main] DEBUG org.redisson.connection.DNSMonitor - DNS monitoring enabled; Current masters: {redis://:sa@192.168.1.175:6381/9=192.168.1.175/192.168.1.175:6381}, slaves: {}
```

### Actual behavior
3.11.1 版本: 
```
16:43:44.537 [redisson-netty-2-2] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: redisson-netty-2-2
Exception in thread "main" java.net.UnknownHostException: failed to resolve '192.168.1.175]' after 6 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:901)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:860)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:328)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:515)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:63)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:372)

```

### Redisson version

3.11.1

### Redisson configuration

```kotlin
    val url = "redis://:sa@192.168.1.175:6381/9"
    val config = Config()
    config.useSingleServer().setAddress(url)
    val redisson = Redisson.create(config)
```

**Comment by mrniko** [comment]
`redis://:sa@192.168.1.175:6381/9` - this is a wrong format of url you use

**Comment by huodon** [comment]
这是标准的 redis URL Schema 语法. 
错的为什么3.11. 0版本能正常解析?

**Comment by mrniko** [comment]
Sorry, I meant format of Redisson url

**Comment by huodon** [comment]
感谢回复 @mrniko  , 不过不是很理解为什么对标准的 Redis URL 解析放弃支持.

**Comment by jackygurui** [comment]
我猜想你说的标准的 Redis URL 解析指的是[IANA的Redis URI方案](https://www.iana.org/assignments/uri-schemes/prov/redis)。首先该方案从提出至今仍然是临时方案，非正式方案。其次该方案基于URI的格式标准并不适用与现有用户的使用习惯，比如URI标准规定主机名中不能含有下划线“_”，但实际使用当中，不少用户仍然在采用。鉴于这些因素，并没有采用这样的方案。如果你有更好的理由或方案，能够平衡以上的问题，可以跟@mrniko 提出。
