### ISSUE TITLE
CommandBatchService Execute Error

### ISSUE THREAD

**Issue by liubaochuan** [redisson/redisson#2212]
### Actual behavior
Caused by: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:400) ~[redisson-3.10.6.jar!/:?]
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:204) ~[redisson-3.10.6.jar!/:?]
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:360) ~[redisson-3.10.6.jar!/:?]
	at org.redisson.spring.data.connection.RedissonConnection.exec(RedissonConnection.java:1597) ~[redisson-spring-data-21-3.10.6.jar!/:?]
	... 143 more
Caused by: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854) ~[?:1.8.0_65]
	at org.redisson.command.CommandBatchService$1.lambda$run$2(CommandBatchService.java:471) ~[redisson-3.10.6.jar!/:?]
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) ~[redisson-3.10.6.jar!/:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[netty-all-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476) ~[netty-all-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[netty-all-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[netty-all-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529) ~[netty-all-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101) ~[netty-all-4.1.34.Final.jar!/:4.1.34.Final]

### Steps to reproduce or test case
Test code(Under the multithread test):
List<Object> txResults = redisTemplate.execute(new SessionCallback<List<Object>>() {
                @Override
                public List<Object> execute(RedisOperations operations) throws DataAccessException {
                    try {
                        operations.watch(key);
                        SeqInfo seqInfo = SeqInfo.fromString(String.valueOf(operations.opsForValue().get(key)));
                        if (oldSeq.equals(seqInfo)) {
                            operations.multi();
                            operations.opsForValue().get(key);
                            operations.opsForValue().set(key, newSeq.toString());
                            return operations.exec();
                        } else {
                            return null;
                        }
                    } catch (Exception e) {
                        log.error(e.getMessage(), e);
                        return null;
                    } finally {
                        operations.unwatch();
                    }
                }
            });

### 
singleServerConfig

**Comment by mrniko** [comment]
Fixed! Thanks for report
