### ISSUE TITLE
o.redisson.client.handler.CommandsQueue  : Exception occured. Channel: [id: 0xc1433690, L:/127.0.0.1:58792 - R:127.0.0.1/127.0.0.1:6380]

### ISSUE THREAD

**Issue by acelance** [redisson/redisson#2227]
Dear sirs, When I just start a simple Demo with Redisson and SpringBoot v2.1.6.RELEASE according to the example of redisson with springboot In GitHub ( where is refence: https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#149-spring-boot-starter), But I run a unit test In my project@SpringBootTest, The test result is OK but throw java.io.IOException below, my redis server is a single localhost not remote or Cluster;
What's The problem of this configuration ,Please help me;
### Expected behavior
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_73]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_73]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_73]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_73]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_73]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125) ~[netty-buffer-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
### Steps to reproduce or test case
@RunWith(SpringRunner.class)
@SpringBootTest
public class PayTypeServiceTest {

    @Autowired
    private PayTypeService payTypeService;
    @Autowired
    private PayTypeDao payTypeDao;
    @Autowired
    private PayTypeRedisOps payTypeRedisOps;

    @Test
    public void getPayTypeByIdTest () {
        PayType payType1 = payTypeService.getPayTypeById("04");
        System.out.println(JSON.toJSONString(payType1));
    }
}
### Redis version
Redis for Windows Redis3.2.100
### Redisson version
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson-spring-boot-starter</artifactId>
	<version>3.11.0</version>
</dependency>
### Redisson configuration
@Configuration
public class RedissonConfigure {
    @Bean(value = "redissonClient")
    public RedissonClient createRedissonClient (@Value("${spring.redis.redisson.address}") String address,
                                                @Value("${spring.redis.redisson.database}") Integer database) {
        Config config = new Config();
        config.useSingleServer()
                .setAddress(address) // redis://127.0.0.1:6380
                .setDatabase(database); // 1
        return Redisson.create(config);
    }
}

**Comment by jackygurui** [comment]
`远程主机强迫关闭了一个现有的连接。`这跟客户端没什么关系。可能是服务端关闭得太早了。

**Comment by acelance** [comment]
> `远程主机强迫关闭了一个现有的连接。`这跟客户端没什么关系。可能是服务端关闭得太早了。

但是我在使用原生Spring的RedisCacheManager时却没有这样的问题,将redssion暂时注释,重新用回Spring的RedisCacheManager也是OK,就是整合redisson之后就出现这种情况了

**Comment by jackygurui** [comment]
你的服务端是什么时候关闭的？

**Comment by TrickyFatty** [comment]
服务端指什么，redis-server吗？

**Comment by TrickyFatty** [comment]
> 你的服务端是什么时候关闭的？

服务端指redis-server吗

**Comment by jackygurui** [comment]
对
