### ISSUE TITLE
Cann't find yaml config file in Springboot when config is not in classpath

### ISSUE THREAD

**Issue by yuanpli** [redisson/redisson#2229]
### Actual behavior

Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/opt/oss/xxx-telcocloudapp/conf/redisson.yaml]
        at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:158) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.R
ELEASE]
        at org.redisson.spring.starter.RedissonAutoConfiguration.getConfigStream(RedissonAutoConfiguration.java:181) ~[redisson-spring-boot-starter-3.11.1.jar:3
.11.1]
        at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:113) ~[redisson-spring-boot-starter-3.11.1.jar:3.11.1]
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$724061cb.CGLIB$redisson$2(<generated>) ~[redisson-spring-boot-starter-3
.11.1.jar:3.11.1]
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$724061cb$$FastClassBySpringCGLIB$$cc2c344d.invoke(<generated>) ~[rediss
on-spring-boot-starter-3.11.1.jar:3.11.1]

### Redisson version
3.11.1
### Redisson configuration
spring.redis.redisson.config=/opt/oss/xxx-telcocloudapp/conf/redisson.yaml

**Comment by mrniko** [comment]
Use "file:///" prefix. Example:

file:///opt/oss/xxx-telcocloudapp/conf/redisson.yaml

**Comment by yuanpli** [comment]
Thanks for your information! It is better to update the wiki to indicate that how to config for this case.

**Comment by LongCodeShort** [comment]
good
