### ISSUE TITLE
Redisson issue on Spark

### ISSUE THREAD

**Issue by mccstan** [redisson/redisson#2253]
### Expected behavior
Successfully write and read data from Redis Cluster throught Redisson inside an appache Spark App.
Thanks for your Help !
### Actual behavior
Failing  with this stack trace when trying to write about  more than 20 items
Everything is OK when limited to about 10 items
```log
19/08/05 20:50:19 WARN TaskSetManager: Lost task 3.0 in stage 0.0 (TID 3, localhost, executor driver): org.redisson.client.RedisConnectionException: Not all slots are covered! Only 10922 slots are avaliable
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:174)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200)
	at org.redisson.Redisson.<init>(Redisson.java:120)
	at org.redisson.Redisson.create(Redisson.java:160)
	at redis.cache.RedisClient$class.getRedissonClusterClient(RedisClient.scala:75)
	at redis.cache.RedisCacheRepository$.getRedissonClusterClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$.redisClient(RedisCacheRepository.scala:24)
	at redis.cache.RedisClient$class.withRedissonClusterClient(RedisClient.scala:99)
	at redis.cache.RedisCacheRepository$.withRedissonClusterClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisClient$class.set(RedisClient.scala:31)
	at redis.cache.RedisCacheRepository$.set(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$$anonfun$setStock$1.apply(RedisCacheRepository.scala:102)
	at redis.cache.RedisCacheRepository$$anonfun$setStock$1.apply(RedisCacheRepository.scala:101)
	at redis.cache.RedisClient$class.withClient(RedisClient.scala:92)
	at redis.cache.RedisCacheRepository$.withClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$.setStock(RedisCacheRepository.scala:101)
	at redis.RedissonTest$$anonfun$3$$anonfun$apply$1.apply(RedissonTest.scala:154)
	at redis.RedissonTest$$anonfun$3$$anonfun$apply$1.apply(RedissonTest.scala:152)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at redis.RedissonTest$$anonfun$3.apply(RedissonTest.scala:152)
	at redis.RedissonTest$$anonfun$3.apply(RedissonTest.scala:152)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 1 of 24 were initialized. Redis server: 127.0.0.1/127.0.0.1:7001
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:160)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:330)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:296)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:245)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Connection reset by peer: 127.0.0.1/127.0.0.1:7001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	... 4 more
Caused by: java.net.SocketException: Connection reset by peer
	... 12 more

19/08/05 20:50:19 INFO ClusterConnectionManager: Redis cluster nodes configuration got from localhost/127.0.0.1:7000:
63a394a484f7ac9e10803c18fc9fec009128f581 127.0.0.1:7000@17000 myself,master - 0 1565031017000 1 connected 0-5460
93aba15e82195d5c7c636a1072b4a073ee2a21a5 127.0.0.1:7002@17002 master - 0 1565031019000 3 connected 10923-16383
506e6ff5d4a86c1bc3111a1982bf9c750deb3e72 127.0.0.1:7001@17001 master - 0 1565031019729 2 connected 5461-10922

19/08/05 20:50:19 ERROR TaskSetManager: Task 3 in stage 0.0 failed 1 times; aborting job
19/08/05 20:50:19 WARN TaskSetManager: Lost task 4.0 in stage 0.0 (TID 4, localhost, executor driver): org.redisson.client.RedisConnectionException: Not all slots are covered! Only 10923 slots are avaliable
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:174)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200)
	at org.redisson.Redisson.<init>(Redisson.java:120)
	at org.redisson.Redisson.create(Redisson.java:160)
	at redis.cache.RedisClient$class.getRedissonClusterClient(RedisClient.scala:75)
	at redis.cache.RedisCacheRepository$.getRedissonClusterClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$.redisClient(RedisCacheRepository.scala:24)
	at redis.cache.RedisClient$class.withRedissonClusterClient(RedisClient.scala:99)
	at redis.cache.RedisCacheRepository$.withRedissonClusterClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisClient$class.set(RedisClient.scala:31)
	at redis.cache.RedisCacheRepository$.set(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$$anonfun$setStock$1.apply(RedisCacheRepository.scala:102)
	at redis.cache.RedisCacheRepository$$anonfun$setStock$1.apply(RedisCacheRepository.scala:101)
	at redis.cache.RedisClient$class.withClient(RedisClient.scala:92)
	at redis.cache.RedisCacheRepository$.withClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$.setStock(RedisCacheRepository.scala:101)
	at redis.RedissonTest$$anonfun$3$$anonfun$apply$1.apply(RedissonTest.scala:154)
	at redis.RedissonTest$$anonfun$3$$anonfun$apply$1.apply(RedissonTest.scala:152)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at redis.RedissonTest$$anonfun$3.apply(RedissonTest.scala:152)
	at redis.RedissonTest$$anonfun$3.apply(RedissonTest.scala:152)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 13 of 24 were initialized. Redis server: 127.0.0.1/127.0.0.1:7002
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:160)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:330)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:296)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:245)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Connection reset by peer: 127.0.0.1/127.0.0.1:7002
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	... 4 more
Caused by: java.net.SocketException: Connection reset by peer
	... 12 more

19/08/05 20:50:20 INFO ClusterConnectionManager: Redis cluster nodes configuration got from localhost/127.0.0.1:7000:
63a394a484f7ac9e10803c18fc9fec009128f581 127.0.0.1:7000@17000 myself,master - 0 1565031017000 1 connected 0-5460
93aba15e82195d5c7c636a1072b4a073ee2a21a5 127.0.0.1:7002@17002 master - 0 1565031019000 3 connected 10923-16383
506e6ff5d4a86c1bc3111a1982bf9c750deb3e72 127.0.0.1:7001@17001 master - 0 1565031019729 2 connected 5461-10922

19/08/05 20:50:20 WARN TaskSetManager: Lost task 6.0 in stage 0.0 (TID 6, localhost, executor driver): org.redisson.client.RedisConnectionException: Not all slots are covered! Only 5461 slots are avaliable
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:174)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200)
	at org.redisson.Redisson.<init>(Redisson.java:120)
	at org.redisson.Redisson.create(Redisson.java:160)
	at redis.cache.RedisClient$class.getRedissonClusterClient(RedisClient.scala:75)
	at redis.cache.RedisCacheRepository$.getRedissonClusterClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$.redisClient(RedisCacheRepository.scala:24)
	at redis.cache.RedisClient$class.withRedissonClusterClient(RedisClient.scala:99)
	at redis.cache.RedisCacheRepository$.withRedissonClusterClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisClient$class.set(RedisClient.scala:31)
	at redis.cache.RedisCacheRepository$.set(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$$anonfun$setStock$1.apply(RedisCacheRepository.scala:102)
	at redis.cache.RedisCacheRepository$$anonfun$setStock$1.apply(RedisCacheRepository.scala:101)
	at redis.cache.RedisClient$class.withClient(RedisClient.scala:92)
	at redis.cache.RedisCacheRepository$.withClient(RedisCacheRepository.scala:10)
	at redis.cache.RedisCacheRepository$.setStock(RedisCacheRepository.scala:101)
	at redis.RedissonTest$$anonfun$3$$anonfun$apply$1.apply(RedissonTest.scala:154)
	at redis.RedissonTest$$anonfun$3$$anonfun$apply$1.apply(RedissonTest.scala:152)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at redis.RedissonTest$$anonfun$3.apply(RedissonTest.scala:152)
	at redis.RedissonTest$$anonfun$3.apply(RedissonTest.scala:152)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``

### Steps to reproduce or test case
Instantiate a Spark Session
parralelize a collection aabout 1000 items
Write scala/java object into Redis via Redisson with a Singleton object

### Redis version
5.0

### Redisson version
3.11.1

### Redisson configuration
``` scala   
val nodes = List("redis://127.0.0.1:7000", "redis://127.0.0.1:7001", "redis://127.0.0.1:7001")

  val config : Config = new Config()
  nodes.foldLeft(config.useClusterServers().setScanInterval(2000)){
    (baseConf, node) => baseConf.addNodeAddress(node)
  }

  var redisson: RedissonClient = Redisson.create(config)
`

Thanks for your help

**Comment by jackygurui** [comment]
`Connection reset by peer: 127.0.0.1/127.0.0.1:7002`根据错误信息提示，请检查集群节点的运行情况。
