### ISSUE TITLE
客户端超时过长问题咨询

### ISSUE THREAD

**Issue by loy1991** [redisson/redisson#2258]
### DESCRIPTION
<b>客户端经过6分钟才超时，期间一直hang。触发条件未知，只能看到以下异常</b>
### ERROR LOG
```shell
[ERROR][2019-08-09T00:03:29.501+0800][ContractRedisCache.getCachedContracts:83]lamborghini_am||traceid=0a5416245d4c47c000003c9163151d51||spanid=00a8114c243cf6b0||缓存读取失败,缓存跪了
org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=30, freeConnectionsCounter=value:62:queue:0, freezed=false, freezeReason=null, client=[addr=redis://100.69.239.73:3000], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@666666508 [redisClient=[addr=redis://100.69.239.73:3000], channel=[id: 0x8d869393, L:/10.169.155.17:45671 - R:100.69.239.73/100.69.239.73:3000], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@567360b7(failure: java.util.concurrent.CancellationException)], command=(MGET), params=[lamborghini:discount:storeId:5001525163030230770, lamborghini:discount:storeId:-1], codec=org.redisson.codec.CompositeCodec@a41c515d]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@567360b7(failure: java.util.concurrent.CancellationException)], command=(MGET), params=[lamborghini:discount:storeId:5001525163030230770, lamborghini:discount:storeId:-1], codec=org.redisson.codec.CompositeCodec@a41c515d], command: (EVAL), params: [local expireHead = redis.call('zrange', KEYS[2], 0, 0, 'withscores'); local currentTime = tonumber(t..., 5, lamborghini:contract:store, redisson__timeout__set:{lamborghini:contract:store}, redisson__idle__set:{lamborghini:contract:store}, redisson__map_cache__last_access__set:{lamborghini:contract:store}, {lamborghini:contract:store}:redisson_options, 1565280203140, PooledUnsafeDirectByteBuf(ridx: 0, widx: 28, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 28, cap: 256), ...] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:745)
```
### Redis version
3.2
### Redisson version
3.10.6
### Redisson configuration
``` java
RedissonServiceFactory codisServiceFactory = new RedissonServiceFactory();
        codisServiceFactory.setVip(host + ":" + port + "");
        codisServiceFactory.setLogOpen(true);
        codisServiceFactory.setLogPrintTimeThreshold(5L);
        codisServiceFactory.setCodec(new org.redisson.codec.SerializationCodec());
        try {
            codisServiceFactory.init();
        } catch (Exception e) {
            codisServiceFactory.stop();
        }
        return codisServiceFactory.getRedissonClient();
```

**Comment by jackygurui** [comment]
`RedissonServiceFactory`不是Redisson提供的类，不好判断是否是配置上造成的问题啊。

**Comment by loy1991** [comment]
不好意思，写错了。我这里把系统里的配置方式，以及用到的方法。给一个测试用例:

```java
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import org.junit.Test;
import org.redisson.Redisson;
import org.redisson.api.RBucket;
import org.redisson.api.RBuckets;
import org.redisson.api.RedissonClient;
import org.redisson.client.codec.Codec;
import org.redisson.codec.JsonJacksonCodec;
import org.redisson.config.Config;
import org.redisson.config.SingleServerConfig;
import org.redisson.config.TransportMode;


import io.netty.channel.EventLoopGroup;

/**
 * @author didi
 * @since 2019-08-16 17:18
 */
public class RedissonTest {

    private static final String ADDRESS_PRE = "redis://";
    private String vip = "127.0.0.1:6379";

    private Codec codec = JsonJacksonCodec.INSTANCE;
    private Integer threads = 8;
    private Integer nettyThreads = 8;
    private ExecutorService executor = null;
    private EventLoopGroup eventLoopGroup = null;
    private TransportMode transportMode = TransportMode.NIO;
    private Integer lockWatchdogTimeout = 30000;
    private Boolean keepPubSubOrder = true;
    // 发布和订阅连接的最小空闲连接数。Redisson内部经常通过发布和订阅来实现许多功能，长期保持一定数量的发布订阅连接是必须的。
    private Integer subscriptionConnectionMinimumIdleSize = 1;
    // 发布和订阅连接池最大容量。连接池的连接数量自动弹性伸缩
    private Integer subscriptionConnectionPoolSize = 50;
    // 单个连接最大订阅数量
    private Integer subscriptionsPerConnection = 5;
    // 最小空闲连接数。长期保持一定数量的连接有利于提高瞬时写入反应速度
    private Integer connectionMinimumIdleSize = 32;
    // 连接池最大容量。连接池的连接数量自动弹性伸缩
    private Integer connectionPoolSize = 64;
    // 连接空闲超时，单位：毫秒。如果当前连接池里的连接数量超过了最小空闲连接数，而同时有连接空闲时间超过了该数值，
    // 那么这些连接将会自动被关闭，并从连接池里去掉。
    private Integer idleConnectionTimeout = 10000;
    // DNS监测时间间隔，单位：毫秒
    private Long dnsMonitoringInterval = 5000L;
    // ping超时
    private Integer pingTimeout = 1000;
    // 连接超时，单位：毫秒。同节点建立连接时的等待超时
    private Integer connectTimeout = 10000;
    // 命令等待超时，单位：毫秒。等待节点回复命令的时间。该时间从命令发送成功时开始计时
    private Integer timeout = 3000;
    // 命令失败重试次数。如果尝试达到 retryAttempts（命令失败重试次数） 仍然不能将命令发送至某个指定的节点时，将抛出错误。
    // 如果尝试在此限制之内发送成功，则开始启用 timeout（命令等待超时） 计时。
    private Integer retryAttempts = 3;
    // 命令重试发送时间间隔，单位：毫秒。在一条命令发送失败以后，等待重试发送的时间间隔
    // 若配置retryAttempts=0，参数不生效
    private Integer retryInterval = 1500;
    // 密码。用于节点身份验证的密码
    private String password = null;
    // 客户端名称。在Redis节点里显示的客户端名称
    private String clientName = null;
    // 数据库编号。尝试连接的数据库编号
    private Integer database = 0;

    @Test
    public void test() {
        Config config = initConfig();
        Redisson redisson = (Redisson)Redisson.create(config);
        RedissonClient redissonClient = redisson;

        // 批量读
        RBuckets rBuckets = redissonClient.getBuckets();
        Map<String, List<String>> queryMap = rBuckets.get("1", "2", "3");
        System.out.println(queryMap);

        // 分批写
        Map<String, List<String>> updateMap = Maps.newHashMap();
        updateMap.put("1", Lists.newArrayList("A", "B", "C"));
        updateMap.put("2", Lists.newArrayList("D","E","F"));
        updateMap.put("3", Lists.newArrayList("G","H","I"));
        updateMap.forEach((key, value) -> {
            RBucket<List<String>> rBucket = redissonClient.getBucket(key);
            rBucket.set(value, 10, TimeUnit.MINUTES);
        });

    }

    /**
     * 初始化客户端
     *
     * @return
     */
    private Config initConfig() {
        Config config = new Config();
        config.setCodec(codec);
        config.setThreads(threads);
        config.setNettyThreads(nettyThreads);
        config.setExecutor(executor);
        config.setEventLoopGroup(eventLoopGroup);
        config.setTransportMode(transportMode);
        config.setLockWatchdogTimeout(lockWatchdogTimeout);
        config.setKeepPubSubOrder(keepPubSubOrder);
        String redisAddr = ADDRESS_PRE + vip;
        SingleServerConfig singleServerConfig = config.useSingleServer();
        singleServerConfig.setAddress(redisAddr);
        singleServerConfig.setSubscriptionConnectionMinimumIdleSize(subscriptionConnectionMinimumIdleSize);
        singleServerConfig.setSubscriptionConnectionPoolSize(subscriptionConnectionPoolSize);
        singleServerConfig.setSubscriptionsPerConnection(subscriptionsPerConnection);
        singleServerConfig.setConnectionMinimumIdleSize(connectionMinimumIdleSize);
        singleServerConfig.setConnectionPoolSize(connectionPoolSize);
        singleServerConfig.setIdleConnectionTimeout(idleConnectionTimeout);
        singleServerConfig.setDnsMonitoringInterval(dnsMonitoringInterval);
        singleServerConfig.setPingTimeout(pingTimeout);
        singleServerConfig.setConnectTimeout(connectTimeout);
        singleServerConfig.setTimeout(timeout);
        singleServerConfig.setRetryAttempts(retryAttempts);
        singleServerConfig.setRetryInterval(retryInterval);
        singleServerConfig.setPassword(password);
        singleServerConfig.setClientName(clientName);
        singleServerConfig.setDatabase(database);
        return config;
    }
}
```
