### ISSUE TITLE
从3.8.2升级到3.11.2后，所有缓存的对象序列化都失败了

### ISSUE THREAD

**Issue by romever** [redisson/redisson#2262]
### Expected behavior
稳定从3.8.2升级到3.11.2版本
### Actual behavior
升级后缓存中对象序列化失败
### Steps to reproduce or test case
只修改了版本号，没有其他修改
### Redisson version
3.11.2
### Redisson configuration
`@Value("${spring.redis.cluster.nodes:}")
    private String clusterNodes;
    @Value("${spring.redis.host:}")
    private String host;
    @Value("${spring.redis.port:0}")
    private int port;
    @Value("${spring.redis.password:}")
    private String password;

    @Value("${application.env}")
    private String env;

    public Config config() {
        Config config = new Config();
        if (env.equalsIgnoreCase("local")) {
            config.setTransportMode(TransportMode.KQUEUE);
        } else {
            config.setTransportMode(TransportMode.EPOLL);
        }
        config.setThreads(4);
        if (Strings.isNotBlank(host)) {
            if (port == 0) {
                port = 6379;
            }
            SingleServerConfig singleServerConfig = config.useSingleServer().setAddress("redis://" + host + ":" + port);
            if (StringUtils.isNoneBlank(password)) {
                singleServerConfig.setPassword(password);
            }

        } else if (Strings.isNotBlank(clusterNodes)) {
            ClusterServersConfig clusterServersConfig = config.useClusterServers();

            String[] strings = clusterNodes.split(",");
            for (String s : strings) {
                clusterServersConfig.setScanInterval(2000) // 集群状态扫描间隔时间，单位是毫秒
                        .addNodeAddress("redis://" + s);
            }

        }

        return config;

    }

    @Bean
    public RedissonClient redissonClient() {
        RedissonClient redisson = Redisson.create(config());
        return redisson;

    }`

`[redisson-netty-2-9] 12:08:11.671 ERROR o.r.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0xa7cd9836, L:/10.234.230.36:56001 - R:wallet-dev-08.sinnet.huobiidc.com/172.18.1.85:6379], reply: ReplayingDecoderByteBuf(ridx=3751, widx=3751), command: (GET), params: [market:bc:exchange:info]
java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:242)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:551)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:399)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:195)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:269)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
	... 34 common frames omitted`

**Comment by jackygurui** [comment]
把codec换成JsonJacksonCodec试试？

**Comment by romever** [comment]
> 把codec换成JsonJacksonCodec试试？

确实可以，谢谢
