### ISSUE TITLE
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。

### ISSUE THREAD

**Issue by Tout-An** [redisson/redisson#2266]

**Comment by Tout-An** [comment]
[2019-08-20 10:52:33.279]  INFO [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.redis.redisson-org.redisson.spring.starter.RedissonProperties' of type [org.redisson.spring.starter.RedissonProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[2019-08-20 10:52:33.287]  INFO [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.redis-org.springframework.boot.autoconfigure.data.redis.RedisProperties' of type [org.springframework.boot.autoconfigure.data.redis.RedisProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[2019-08-20 10:52:33.291]  INFO [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.redisson.spring.starter.RedissonAutoConfiguration' of type [org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$b2fea732] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[2019-08-20 10:52:33.521]  INFO [           main] org.redisson.Version                     : Redisson 3.11.2
[2019-08-20 10:52:34.666] ERROR [sson-netty-2-27] o.redisson.client.handler.CommandsQueue  : Exception occured. Channel: [id: 0xada7832b, L:/192.168.0.230:54436 - R:test.tembin.com/192.168.0.223:6379]

java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jackygurui** [comment]
`你的主机中的软件中止了一个已建立的连接。`这不是客户端的问题。

**Comment by ynfatal** [comment]
一千并发去加锁，我也出现了这样的问题。
![image](https://user-images.githubusercontent.com/40764140/63909079-0adf9800-ca54-11e9-9a82-dfd33c79cf71.png)
