### ISSUE TITLE
org.redisson.client.RedisConnectionClosedException: Command (EVAL), .... succesfully sent, but channel [..] has been closed

### ISSUE THREAD

**Issue by Johor03** [redisson/redisson#2268]
### Expected behavior
I have three reids nodes, and I have configured three sentinel, now Redis fairLock for redisson, and I tried the following exception multiple times. Redis port my telnet communication is normal.

### Steps to reproduce or test case

org.redisson.client.RedisConnectionClosedException: Command (EVAL), params: [while true do local firstThreadId2 = redis.call('lindex', KEYS[2], 0);if firstThreadId2 == false the..., 3, test0120190820, redisson_lock_queue:{test0120190820}, redisson_lock_timeout:{test0120190820}, 5000, c44bace4-3e9a-4d84-bdcf-3838bb382958:35, 1566291309268, 1566291304268] succesfully sent, but channel [id: 0xf4e7c971, L:0.0.0.0/0.0.0.0:57898 ! R:10.0.10.113/10.0.10.113:7000] has been closed!
	at org.redisson.client.handler.CommandsQueue.channelInactive(CommandsQueue.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at org.redisson.client.handler.ConnectionWatchdog.channelInactive(ConnectionWatchdog.java:84)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Redis version
4.0.11
### Redisson version
3.9.1
### Redisson configuration

Spring config

```java
@Data
@Configuration
@ConfigurationProperties(prefix = "redisson.sentinel", ignoreUnknownFields = false)
public class RedissonConfiguration {

    private String masterName;

    private Integer database;

    private String [] node;

    private String password;

    @Bean
    public RedissonClient createRedissson(){
        Config config = new Config();
        config.setTransportMode(TransportMode.NIO);
        config.useSentinelServers().setMasterName(masterName)
                .addSentinelAddress(node)
                .setDatabase(database)
                .setPassword(password);
        return Redisson.create(config);
    }

}
```
```yaml
redisson:
  sentinel:
    masterName: mymaster
    database: 1
    password: password
    node:
      - redis://10.0.10.111:27000
      - redis://10.0.10.112:27000
      - redis://10.0.10.113:27000
```

**Comment by mrniko** [comment]
Redis connection is closed for some reason. Try to set pingConnectionInterval = 60000

**Comment by Johor03** [comment]
> Redis connection is closed for some reason. Try to set pingConnectionInterval = 60000

Thank you, I configured  this parameter and I have not reproduced the exception.

**Comment by mrniko** [comment]
Great! I'm closing this.
