### ISSUE TITLE
RedissonFairLock deadlock

### ISSUE THREAD

**Issue by haiS8dn** [redisson/redisson#2278]
Seems related to the change on https://github.com/redisson/redisson/issues/2099.
We have tried to upgrade to 3.11.2 from 3.10.7 and this behavior started occurring.

### Expected behavior
The FairLock acquired on high load system without lease time defined. 

### Actual behavior
Redisson does not handle the case of Fair lock without lease time (on high load).
when many different threads are asking for the same lock key the client is stuck and no thread acquires the lock.

### Steps to reproduce or test case
`        

        ExecutorService executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                1000L, TimeUnit.MILLISECONDS,
                new SynchronousQueue<Runnable>());
        RedissonClient client = Redisson.create();
        IntStream.rangeClosed(0, 300).boxed().forEach(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) {
                executorService.submit(new Runnable() {
                    @Override
                    public void run() {
                        ConnectionManager connectionManager = Redisson.class.cast(client).getConnectionManager();
                        try {
                            Field field = MasterSlaveConnectionManager.class.getDeclaredField("id");
                            field.setAccessible(true);
                            field.set(connectionManager, UUID.randomUUID());
                        } catch (NoSuchFieldException | IllegalAccessException e) {
                            e.printStackTrace();
                        }
                        RLock lock1 = client.getFairLock("fair:lock");
                        try {
                            lock1.lock();
                            Thread.sleep(50);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        } finally {
                            lock1.unlock();
                            System.out.println("done = " + integer);
                        }
                    }
                });
            }
        });
        Thread.sleep(150000);`
### Redis version
3.27 and 2.8
### Redisson version
3.11.2
### Redisson configuration
defaults

**Comment by wangbo911** [comment]
It's a question of your usage，you can try this:
//
lock.lock(2,TimeUnit.SECONDS);
lock.unlock();
//

**Comment by mrniko** [comment]
The code is stuck at `UUID.randomUUID`

**Comment by mrniko** [comment]
There is an error in your test. You should create Redisson client instead of modifying ConnectionManager object.

Here is the correct version of test and it passes:

```java
            ExecutorService executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE,
            1000L, TimeUnit.MILLISECONDS,
            new SynchronousQueue<Runnable>());
    IntStream.rangeClosed(0, 300).boxed().forEach(new Consumer<Integer>() {
        @Override
        public void accept(Integer integer) {
            executorService.submit(new Runnable() {
                @Override
                public void run() {
                    RedissonClient r = Redisson.create(redisson.getConfig());
                    RLock lock1 = r.getFairLock("fair:lock");
                    try {
                        lock1.lock();
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    } finally {
                        lock1.unlock();
                        System.out.println("done = " + integer);
                    }
                }
            });
        }
    });
    executorService.shutdown();
    assertThat(executorService.awaitTermination(60, TimeUnit.SECONDS)).isTrue();

```

**Comment by haiS8dn** [comment]
@mrniko - 
When I'm running your test flow - no lock is acquired.
You cannot open 300 netty clients.
The refection set used to manipulate the lock mechanism which taking the field for thread identification.
Maybe we have different  OS (I'm using MacOs).
this case is upgrade blocker.

That's the stacktraces - 
`"pool-1-thread-295" #355 prio=5 os_prio=31 tid=0x00007fcf0fad8000 nid=0x2cf03 in Object.wait() [0x000070001e6cb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076dad3e48> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at java.lang.Object.wait(Object.java:460)
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:604)
	- locked <0x000000076dad3e48> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:277)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:139)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:167)
	at org.redisson.RedissonLock.lock(RedissonLock.java:183)
	at org.redisson.RedissonLock.lock(RedissonLock.java:148)
	at redtest.LoadTest$1$1.run(LoadTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-294" #354 prio=5 os_prio=31 tid=0x00007fcf0eb39000 nid=0x32603 in Object.wait() [0x000070001e5c8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076dac82e8> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at java.lang.Object.wait(Object.java:460)
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:604)
	- locked <0x000000076dac82e8> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:277)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:139)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:167)
	at org.redisson.RedissonLock.lock(RedissonLock.java:183)
	at org.redisson.RedissonLock.lock(RedissonLock.java:148)
	at redtest.LoadTest$1$1.run(LoadTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-293" #353 prio=5 os_prio=31 tid=0x00007fcf0f340000 nid=0x32803 in Object.wait() [0x000070001e4c5000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076dabc7d8> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at java.lang.Object.wait(Object.java:460)
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:604)
	- locked <0x000000076dabc7d8> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:277)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:139)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:167)
	at org.redisson.RedissonLock.lock(RedissonLock.java:183)
	at org.redisson.RedissonLock.lock(RedissonLock.java:148)
	at redtest.LoadTest$1$1.run(LoadTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-292" #352 prio=5 os_prio=31 tid=0x00007fcf0eb32800 nid=0x32a03 in Object.wait() [0x000070001e3c2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076dab0ca0> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at java.lang.Object.wait(Object.java:460)
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:604)
	- locked <0x000000076dab0ca0> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:277)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:139)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:167)
	at org.redisson.RedissonLock.lock(RedissonLock.java:183)
	at org.redisson.RedissonLock.lock(RedissonLock.java:148)
	at redtest.LoadTest$1$1.run(LoadTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-291" #351 prio=5 os_prio=31 tid=0x00007fcf0fad7800 nid=0x32c03 in Object.wait() [0x000070001e2bf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076da6b0f0> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at java.lang.Object.wait(Object.java:460)
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:604)
	- locked <0x000000076da6b0f0> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:277)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:139)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:167)
	at org.redisson.RedissonLock.lock(RedissonLock.java:183)
	at org.redisson.RedissonLock.lock(RedissonLock.java:148)
	at redtest.LoadTest$1$1.run(LoadTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-290" #350 prio=5 os_prio=31 tid=0x00007fcf0fad6800 nid=0x2ce03 in Object.wait() [0x000070001e1bc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076da5f5b8> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at java.lang.Object.wait(Object.java:460)
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:604)
	- locked <0x000000076da5f5b8> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:277)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:139)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:167)
	at org.redisson.RedissonLock.lock(RedissonLock.java:183)
	at org.redisson.RedissonLock.lock(RedissonLock.java:148)
	at redtest.LoadTest$1$1.run(LoadTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by mrniko** [comment]
@haiS8dn 

I refactored it with shared eventLoopGroup:

```java
        ExecutorService executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE,
            1000L, TimeUnit.MILLISECONDS,
            new SynchronousQueue<Runnable>());

        Config config = BaseTest.createConfig();
        NioEventLoopGroup group = new NioEventLoopGroup(config.getNettyThreads(), new DefaultThreadFactory("redisson-netty"));
        config.setEventLoopGroup(group);

        IntStream.rangeClosed(0, 300).boxed().forEach(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) {
                executorService.submit(new Runnable() {
                    @Override
                    public void run() {
                        RedissonClient r = Redisson.create(config);
                        RLock lock1 = r.getFairLock("fair:lock");
                        try {
                            lock1.lock();
                            Thread.sleep(50);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        } finally {
                            lock1.unlock();
                            System.out.println("done = " + integer);
                        }
                    }
                });
            }
        });
        executorService.shutdown();
        assertThat(executorService.awaitTermination(60, TimeUnit.SECONDS)).isTrue();
    }
```

Could you give it a try?
