### ISSUE TITLE
redisson如何连接阿里云redis集群? 使用云托管模式

### ISSUE THREAD

**Issue by wangzeyan999** [redisson/redisson#2282]
### Expected behavior
连接成功,并正常使用
### Actual behavior
使用单Redis节点模式连接正常,操作不正常
使用云托管模式连接错误, 
```
Exception in thread "main" java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source)
	at org.redisson.connection.ReplicatedConnectionManager$Role.valueOf(ReplicatedConnectionManager.java:60)
	at org.redisson.connection.ReplicatedConnectionManager.<init>(ReplicatedConnectionManager.java:80)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:203)
	at org.redisson.Redisson.<init>(Redisson.java:120)
	at org.redisson.Redisson.create(Redisson.java:160)
	at com.bizvane.openapi.gateway.Application.main(Application.java:28)
```

源码:  `org.redisson.connection.ReplicatedConnectionManager` 80行中
```
Role role = Role.valueOf(connection.sync(RedisCommands.INFO_REPLICATION).get(ROLE_KEY));
```
`connection.sync(RedisCommands.INFO_REPLICATION)` 执行的返回结果中并没有 `role`字段

### Steps to reproduce or test case
```
public static void main(String[] args) throws IOException {
		Config config = Config.fromYAML(new ClassPathResource("redisson.yaml").getInputStream());
		RedissonClient redisson = Redisson.create(config);
	}
```

### Redis version 
4.0
### Redisson version 
3.11.2
### Redisson configuration
```
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"

replicatedServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  database: 4
  password: "password"
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: "MASTER_SLAVE"
  nodeAddresses:
  - "redis://aliyunredis:6379"
  scanInterval: 1000
  
```

**Comment by jackygurui** [comment]
阿里云环境请使用单机配置。

**Comment by syschen** [comment]
> 阿里云环境请使用单机配置。

你好，请问阿里云环境只能使用单机配置吗？我们使用的是master-slaver遇到了
跟[#2493](https://github.com/redisson/redisson/issues/2493)和[#1581](https://github.com/redisson/redisson/issues/1581)表象一样的错

版本：3.11.5
