### ISSUE TITLE
redis cluster: RedisConnectionException: Not all slots are covered

### ISSUE THREAD

**Issue by iengchen** [redisson/redisson#2284]
### environment
- redisson 3.11.2
- redis cluster: based on redis 5.0.5。redis cluster is in Aliyun Cloud ECS, all instances(6,includes 3 master and 3 slave) is in one host,public ip is 149.129.48.110,private ip is 172.16.30.41。

### test
I test in redis cluster based on redis 4.0.3 and redis 5.0.5, the error is same。redis.conf:
```
port 8001
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
protected-mode no
```

nodes.conf of 8001:
```
288fef1bebe084a187b7a5db58b4021ce82f2106 149.129.48.110:8003@18003 master - 0 1567133263504 3 connected 10923-16383
8cffc074adb4059fa5a29410f4a4aa785ce02a54 172.16.30.41:8001@18001 myself,master - 0 1567133264000 1 connected 0-5460
6f297f9e9494494c12c5a7fa8a6bc7fd414eaaa1 149.129.48.110:8006@18006 slave 8cffc074adb4059fa5a29410f4a4aa785ce02a54 0 1567133264407 6 connected
ed3d6b84dbf52e2b2a3f21f7e86d1765fda5c7fc 149.129.48.110:8005@18005 slave 288fef1bebe084a187b7a5db58b4021ce82f2106 0 1567133263504 5 connected
8a1a817d67fb2c6f3e42f462e0e17114c00374c7 149.129.48.110:8002@18002 master - 0 1567133265409 2 connected 5461-10922
153110415bcf5f468924ba1d9ea23333d15aaeea 149.129.48.110:8004@18004 slave 8a1a817d67fb2c6f3e42f462e0e17114c00374c7 0 1567133263906 4 connected
vars currentEpoch 6 lastVoteEpoch 0
```

### analysis
I guess the error is beacuse redisson use one of my configuration node(8001) to connnet to redis cluster,and then execute`cluster nodes`command on that node(8001) to get other nodes,not direct use the nodes in configuration。But the node(8001) where `cluster nodes` is executed always return  private ip(172.16.30.41) while other node's ip is public ip(149.129.48.110),just the same as nodes.conf of 8001.

### error
redisson log:
```
2019-08-30 10:55:48 main INFO [org.redisson.cluster.ClusterConnectionManager] [127] Redis cluster nodes configuration got from 149.129.48.110/149.129.48.110:8001:
288fef1bebe084a187b7a5db58b4021ce82f2106 149.129.48.110:8003@18003 master - 0 1567133748082 3 connected 10923-16383
8cffc074adb4059fa5a29410f4a4aa785ce02a54 172.16.30.41:8001@18001 myself,master - 0 1567133747000 1 connected 0-5460
6f297f9e9494494c12c5a7fa8a6bc7fd414eaaa1 149.129.48.110:8006@18006 slave 8cffc074adb4059fa5a29410f4a4aa785ce02a54 0 1567133747982 6 connected
ed3d6b84dbf52e2b2a3f21f7e86d1765fda5c7fc 149.129.48.110:8005@18005 slave 288fef1bebe084a187b7a5db58b4021ce82f2106 0 1567133747000 5 connected
8a1a817d67fb2c6f3e42f462e0e17114c00374c7 149.129.48.110:8002@18002 master - 0 1567133746479 2 connected 5461-10922
153110415bcf5f468924ba1d9ea23333d15aaeea 149.129.48.110:8004@18004 slave 8a1a817d67fb2c6f3e42f462e0e17114c00374c7 0 1567133747481 4 connected

2019-08-30 10:55:48 redisson-netty-2-6 INFO [org.redisson.cluster.ClusterConnectionManager] [245] slaves: [redis://149.129.48.110:8004] added for slot ranges: [[5461-10922]]
2019-08-30 10:55:48 redisson-netty-2-7 INFO [org.redisson.cluster.ClusterConnectionManager] [245] slaves: [redis://149.129.48.110:8005] added for slot ranges: [[10923-16383]]
2019-08-30 10:55:48 redisson-netty-2-26 INFO [org.redisson.cluster.ClusterConnectionManager] [266] master: redis://149.129.48.110:8003 added for slot ranges: [[10923-16383]]
2019-08-30 10:55:48 redisson-netty-2-2 INFO [org.redisson.cluster.ClusterConnectionManager] [266] master: redis://149.129.48.110:8002 added for slot ranges: [[5461-10922]]
2019-08-30 10:55:48 redisson-netty-2-26 INFO [org.redisson.connection.pool.MasterConnectionPool] [168] 24 connections initialized for 149.129.48.110/149.129.48.110:8003
2019-08-30 10:55:48 redisson-netty-2-2 INFO [org.redisson.connection.pool.MasterConnectionPool] [168] 24 connections initialized for 149.129.48.110/149.129.48.110:8002
2019-08-30 10:55:48 redisson-netty-2-12 INFO [org.redisson.connection.pool.PubSubConnectionPool] [168] 1 connections initialized for 149.129.48.110/149.129.48.110:8004
2019-08-30 10:55:48 redisson-netty-2-9 INFO [org.redisson.connection.pool.PubSubConnectionPool] [168] 1 connections initialized for 149.129.48.110/149.129.48.110:8005
2019-08-30 10:55:48 redisson-netty-2-10 INFO [org.redisson.connection.pool.SlaveConnectionPool] [168] 24 connections initialized for 149.129.48.110/149.129.48.110:8004
2019-08-30 10:55:48 redisson-netty-2-11 INFO [org.redisson.connection.pool.SlaveConnectionPool] [168] 24 connections initialized for 149.129.48.110/149.129.48.110:8005
2019-08-30 10:55:58 redisson-netty-2-12 ERROR [org.redisson.cluster.ClusterConnectionManager] [207] Can't connect to master: redis://172.16.30.41:8001 with slot ranges: [[0-5460]]

java.lang.ExceptionInInitializerError
	at com.ms.redisdemo.redisson.StringTest.<init>(StringTest.java:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:226)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.redisson.client.RedisConnectionException: Not all slots are covered! Only 10923 slots are avaliable
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:174)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200)
	at org.redisson.Redisson.<init>(Redisson.java:120)
	at org.redisson.Redisson.create(Redisson.java:160)
	at com.ms.redisdemo.redisson.RedissonClusterUtil.createClient(RedissonClusterUtil.java:51)
	at com.ms.redisdemo.redisson.RedissonClusterUtil.<clinit>(RedissonClusterUtil.java:39)
	... 26 more
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: 172.16.30.41/172.16.30.41:8001
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by mrniko** [comment]
> But the node(8001) where cluster nodes is executed always return private ip(172.16.30.41) while other node's ip is public ip(149.129.48.110),just the same as nodes.conf of 8001.

Please check your network

**Comment by iengchen** [comment]
> > But the node(8001) where cluster nodes is executed always return private ip(172.16.30.41) while other node's ip is public ip(149.129.48.110),just the same as nodes.conf of 8001.
> 
> Please check your network

My network is fine.Because when I use JedisCluster to connect redis cluster,store data and get data,all things go well,there is nothing wrong

**Comment by mrniko** [comment]
You need to correct ip address in cluster - 172.16.30.41 to 149.129.48.110

**Comment by iengchen** [comment]
> You need to correct ip address in cluster - 172.16.30.41

I create cluster use public ip address: 
```
./redis-cli --cluster create  149.129.48.110:8001 149.129.48.110:8002 149.129.48.110:8003 149.129.48.110:8004 149.129.48.110:8005 149.129.48.110:8006  --cluster-replicas 1
```

Redisson will choose one ip address in configuration nodes to connect cluster,then fetch cluster nodes。The problem is,the node connected to always return private ip.For example,if redisson connect to 8001,then return ip address is:
```
288fef1bebe084a187b7a5db58b4021ce82f2106 47.98.122.112:8003@18003 master - 0 1567297563304 3 connected 10923-16383
8cffc074adb4059fa5a29410f4a4aa785ce02a54 172.16.30.41:8001@18001 myself,master - 0 1567297562000 1 connected 0-5460
6f297f9e9494494c12c5a7fa8a6bc7fd414eaaa1 47.98.122.112:8006@18006 slave 8cffc074adb4059fa5a29410f4a4aa785ce02a54 0 1567297563000 6 connected
ed3d6b84dbf52e2b2a3f21f7e86d1765fda5c7fc 47.98.122.112:8005@18005 slave 288fef1bebe084a187b7a5db58b4021ce82f2106 0 1567297563806 5 connected
8a1a817d67fb2c6f3e42f462e0e17114c00374c7 47.98.122.112:8002@18002 master - 0 1567297562301 2 connected 5461-10922
153110415bcf5f468924ba1d9ea23333d15aaeea 47.98.122.112:8004@18004 slave 8a1a817d67fb2c6f3e42f462e0e17114c00374c7 0 1567297563000 4 connected
```
you see,only 8001 is private ip。If redisson choose 8002,then return ip address is:
```
6f297f9e9494494c12c5a7fa8a6bc7fd414eaaa1 47.98.122.112:8006@18006 slave 8cffc074adb4059fa5a29410f4a4aa785ce02a54 0 1567297668643 6 connected
8a1a817d67fb2c6f3e42f462e0e17114c00374c7 172.16.30.41:8002@18002 myself,master - 0 1567297668000 2 connected 5461-10922
ed3d6b84dbf52e2b2a3f21f7e86d1765fda5c7fc 47.98.122.112:8005@18005 slave 288fef1bebe084a187b7a5db58b4021ce82f2106 0 1567297669644 5 connected
8cffc074adb4059fa5a29410f4a4aa785ce02a54 47.98.122.112:8001@18001 master - 0 1567297669544 1 connected 0-5460
288fef1bebe084a187b7a5db58b4021ce82f2106 47.98.122.112:8003@18003 master - 0 1567297669000 3 connected 10923-16383
153110415bcf5f468924ba1d9ea23333d15aaeea 47.98.122.112:8004@18004 slave 8a1a817d67fb2c6f3e42f462e0e17114c00374c7 0 1567297669000 4 connected
```
Now only 8002 is private ip.

Conclusion: At application startup,the node  redisson connected to  should use the ip address in my configuration(149.129.48.110),because return ip of it is always private ip(172.16.30.41),redisson can't rely on the return ip of this node。While the nodes not used by redisson to connect to cluster at startup can use the return ip(because they are public ip)

**Comment by iengchen** [comment]
> Use nat mapping to resolve it
> 
> https://github.com/redisson/redisson/wiki/2.-Configuration#natmap

It does not work.I set nat mapping as below:
```
ClusterServersConfig clusterServersConfig = config.useClusterServers();

HashMap<String,String> natMap = new HashMap<>();
natMap.put("172.16.30.41","149.129.48.110");
clusterServersConfig.setNatMap(natMap);
```

**Comment by alexanderlc6** [comment]
@iengchen What's the result of your issue?Resolved by set the nat mapping?I met the same issue with you, I don't know how the return IP can be the inner IP of Tecent Cloud Node IP, how to solve this problem?

**Comment by iengchen** [comment]
> @iengchen What's the result of your issue?Resolved by set the nat mapping?I met the same issue with you, I don't know how the return IP can be the inner IP of Tecent Cloud Node IP, how to solve this problem?

I can't solve this problem.The only solution is using  jedis instead of redisson

**Comment by mrniko** [comment]
@iengchen 

I'll introduce an option so client can ignore this check and start.

**Comment by mrniko** [comment]
`checkSlotsCoverage` setting added. It's value `false` by default.
