### ISSUE TITLE
DNS resolve error

### ISSUE THREAD

**Issue by damoyang** [redisson/redisson#2295]
### Expected behavior
I used redisson master/slave mode and get dns resolve error.
I init the client as followed:
public class RedissonCluster {
    List\<RedisPair\> redises;
    List\<RedissonClient\> redisClients;
    BatchOptions batchOptions;
    public RedissonCluster(List<RedisPair> redises) {
        this.redises = redises;
        redisClients = new ArrayList<>(redises.size());
        redises.forEach(redisPair -> {
            Config config = new Config();
            config.setAddressResolverGroupFactory(new DnsAddressResolverGroupFactory());
            config.useMasterSlaveServers().setMasterAddress(redisPair.master).addSlaveAddress(redisPair.slave);
            config.setCodec(StringCodec.INSTANCE);
            RedissonClient redisClient = Redisson.create(config);
            redisClients.add(redisClient);
        });
        batchOptions = BatchOptions.defaults().executionMode(ExecutionMode.IN_MEMORY)
                .responseTimeout(1, TimeUnit.SECONDS).retryInterval(1, TimeUnit.SECONDS).retryAttempts(2);
    }
the DnsAddressResolverGroupFactory is implemented as followed:
public class DnsAddressResolverGroupFactory implements AddressResolverGroupFactory {
    @Override
    public DnsAddressResolverGroup create(Class<? extends DatagramChannel> channelType,
                                          DnsServerAddressStreamProvider nameServerProvider) {
        DnsAddressResolverGroup group = new DnsAddressResolverGroup(new DnsNameResolverBuilder()
                .channelType(NioDatagramChannel.class)
                .nameServerProvider(DnsServerAddressStreamProviders.platformDefault())
                .resolvedAddressTypes(ResolvedAddressTypes.IPV4_ONLY));
        return group;
    }
}
I have 4 master/slave redis nodes(rs1,rs2,rs3,rs4). I found that the program failed 4 times and after that the program successed! The dns resolve failing was from rs1 to rs4 and I guess because I set different DnsAddressResolverGroupFactory instance for each redisson client config, so each redisson client failed one time.
### Actual behavior
Here is the error:
Caused by: java.net.UnknownHostException: failed to resolve 'rs1.hebe.grid.xxx.com.cn' after 2 queries 
	at shaded.io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925)
	at shaded.io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884)
	at shaded.io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356)
	at shaded.io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64)
	at shaded.io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at shaded.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
	at shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
	at shaded.io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:228)
	at shaded.io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42)
	at shaded.io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
	at shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
### Redis version
2.4.20.23
### Redisson version
3.11.2
I want to know why this happened and how to make the program work success at the first run time.

**Comment by mrniko** [comment]
Check dns servers it uses
