### ISSUE TITLE
Redisson netty thread consumes ~100% CPU with RedisTimeoutException

### ISSUE THREAD

**Issue by suhaspb** [redisson/redisson#2299]
Hi, 

**The issue being faced is that redisson netty thread consumes ~100% CPU and when a redis operation is performed we get RedisTimeoutException.**

In the current set up, 
3 redis sentinels and 3 redis servers
2 pods with our application that uses redisson client.

Out of the 2 pods only one pod seems to have this issue.
The pattern of the issue is that it runs with .1% CPU utilisation for few days and,
suddenly there is increase in CPU usage which hits 100%. Once it reached 100% all redis operation fail with RedisTimeoutException.
The CPU utilisation drops down back to .1% if the pod is restarted and the issue doesnt appear for few days.
If the pod is not restarted CPU utilisation continues to be at 100% throughout.

**This is happening irrespective of the load even for as low as 1 request per minute.**

The exception being faced post high CPU usage is 
**org.redisson.client.RedisTimeoutException:** Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=31, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://X.X.X.X:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@391497724 [redisClient=[addr=redis://X.X.X.X:6379], channel=[id: 0x9a7e9a0c, L:/X.X.X.X:52226 - R:X.X.X.X/X.X.X.X:6379], command=null], current command in queue: null, command: (GET), params: [YYYYYY] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:745) 

On analysing the top threads for CPU utilisation for pid 

> **top -H -p <pid>** 

PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
**78 root 20 0 26.439g 1.730g 28888 R 99.3 2.8 11392:52 java**
102 root 20 0 26.439g 1.730g 28888 S 0.7 2.8 74:22.42 java
509 root 20 0 26.439g 1.730g 28888 S 0.7 2.8 116:44.13 java
7 root 20 0 26.439g 1.730g 28888 S 0.0 2.8 0:00.00 java
8 root 20 0 26.439g 1.730g 28888 S 0.0 2.8 0:07.37 java

pid 78 corresponds to hex 4E
Analysing thread dump for the process we have : 

The thread 78 with high CPU usage corresponds to one of redisson-netty threads.
**"redisson-netty-2-26" #59 prio=5 os_prio=0 tid=0x00007fe515245000 nid=0x4e runnable [0x00007fe4c19f6000]
java.lang.Thread.State: RUNNABLE**
at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:381)
at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:104)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1127)
at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1174)
at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1098)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

### Expected behavior
Redisson netty threads should not consumer 100% CPU, even if it does should release it eventually.
And we should not be having RedisTimeoutException.

### Actual behavior
100% CPU utilisation followed by  RedisTimeoutException

### Steps to reproduce or test case
Random

### Redis version
4.0.8

### Redisson version
3.10.7

### Redisson configuration

config.setNettyThreads(0) //16 core machine so 32 netty threads
        .setDecodeInExecutor(true)
        .useSentinelServers()
        .setMasterName("master")
        .addSentinelAddress(<Address>)
        .setReadMode("MASTER")
        .setMasterConnectionMinimumIdleSize(32)
        .setMasterConnectionPoolSize(128)
        .setIdleConnectionTimeout(10000)
        .setConnectTimeout(20000)
        .setTimeout(10000)
        .setRetryAttempts(3)
        .setRetryInterval(1500)

**Comment by mrniko** [comment]
Did you try to follow these steps https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by suhaspb** [comment]
@mrniko
As per the guide lines - There are three main reasons: Please find inline comments
1. All netty threads are busy, leading to delays in both Redis response decoding and sending commands to Redis
>> All 32 netty threads are RUNNABLE and one of then is consuming 100% CPU. The load we have is hardly 1 request per minute. Hence how does increasing netty threads help?
2. All connections are busy
>> We have 31 free connections as per the exception
org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, **freeConnectionsAmount=31**, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://X.X.X.X:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@391497724 [redisClient=[addr=redis://X.X.X.X:6379], channel=[id: 0x9a7e9a0c, L:/X.X.X.X:52226 - R:X.X.X.X/X.X.X.X:6379], command=null], current command in queue: null, command: (GET), params: [YYYYYY] after 3 retry attempts

3. Redis server takes too long to respond the request.
>> The same command executed from redis server gets executed within milliseconds

The issue we are facing is that one of the netty thread is unable to release CPU (seems like a background process that is not releasing CPU), hence how does increasing netty threads from 32 to 64 or even higher value help? We can see 31 free connections hence how does increasing connection pool size help us to reduce the CPU usage.

Also we would like to bring the attention back to the fact that the load we are running is very low. And with the same configuration another pod seems to be working.

**Comment by mrniko** [comment]
Is there any test case to reproduce it?

**Comment by suhaspb** [comment]
@mrniko
The issue is seen all of sudden and continues throughout till restart. Hence, there is no specific code to reproduce this. 

Please provide any recommendation/suggestions if you have to overcome this issue, such as enabling pingConnectionInterval or changing TransportMode from NIO to EPOLL

**Comment by mrniko** [comment]
what is the netty version you have in classpath?

**Comment by suhaspb** [comment]
netty-all 4.1.38.Final
netty-resolver-dns 4.1.34.final
netty-codec-dns 4.1.34.Final

**Comment by suhaspb** [comment]
Additional info from pom.xml:

<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson</artifactId>
    <version>3.10.7</version>
    <exclusions>
        <exclusion>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-all</artifactId>
	<version>4.1.38.Final</version>
</dependency>

**Comment by suhaspb** [comment]
Additional info from pom :
\<dependency\>
    \<groupId\>org.redisson\</groupId\>
    \<artifactId\>redisson\</artifactId\>
    \<version\>3.10.7\</version\>
    \<exclusions\>
        \<exclusion\>
            \<groupId\>com.fasterxml.jackson.core\</groupId\>
            \<artifactId\>jackson-databind\</artifactId\>
        \</exclusion\>
        \<exclusion\>
            \<groupId\>com.fasterxml.jackson.core\</groupId\>
            \<artifactId\>jackson-core\</artifactId\>
        \</exclusion\>
        \<exclusion\>
            \<groupId\>io.netty\</groupId\>
            \<artifactId\>netty-common\</artifactId\>
        \</exclusion\>
        \<exclusion\>
            \<groupId\>io.netty\</groupId\>
            \<artifactId\>netty-codec\</artifactId\>
        \</exclusion\>
        \<exclusion\>
            \<groupId\>io.netty\</groupId\>
            \<artifactId\>netty-transport\</artifactId\>
        \</exclusion\>
        \<exclusion\>
            \<groupId\>io.netty\</groupId\>
            \<artifactId\>netty-buffer\</artifactId\>
        \</exclusion\>
        \<exclusion\>
            \<groupId\>io.netty\</groupId\>
            \<artifactId\>netty-handler\</artifactId\>
        \</exclusion\>
    \</exclusions\>
\</dependency\>
\<dependency\>
	\<groupId\>io.netty\</groupId\>
	\<artifactId\>netty-all\</artifactId\>
	\<version\>4.1.38.Final\</version\>
\</dependency\>

**Comment by arunbenoyv** [comment]
This is the pattern we are observing : 

<img width="1125" alt="Screenshot 2019-09-04 at 2 00 01 PM" src="https://user-images.githubusercontent.com/51450075/64404881-fbd39800-d09a-11e9-905a-52fb8ac2f70a.png">

**Comment by mrniko** [comment]
I would recommend you to exclude netty-all from dependencies and remain rest with the same version.

**Comment by mrniko** [comment]
According to this part of dump:

java.lang.Thread.State: RUNNABLE
at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:381)
at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:104)
a

You encounter commands spike. Can you set logging level to `TRACE` for `org.redisson` and share output?

**Comment by arunbenoyv** [comment]
<img width="533" alt="Screenshot 2019-09-09 at 3 09 07 PM" src="https://user-images.githubusercontent.com/51450075/64520430-ce455380-d313-11e9-8d26-274b4d807ba4.png">

In the last 30 days max commands executed observed is 12 per second

**Comment by mrniko** [comment]
You encounter commands spike. Can you set logging level to TRACE for org.redisson and share output?

**Comment by arunbenoyv** [comment]
Currently we are trying to re-produce the issue by enabling trace logs, but post restart the component stabilises and its not observed for long periods of time.

**Comment by suhaspb** [comment]
@mrniko
Since the issue is random, Let us now if you have any suggestions to simulate the issue or workaround if any.

**Comment by suhaspb** [comment]
@mrniko
The issue is reproduced with TRACE logs enabled. Can you let us know is there any specific logs which you want to check?

**Comment by mrniko** [comment]
After which command did it happen?

**Comment by lemonguge** [comment]
I have also had such problems, a lot of RedisTimeoutException and CPU 100%.

**Comment by lemonguge** [comment]
```java

"redisson-netty-2-10" #251 prio=5 os_prio=0 tid=0x00002aaad881d000 nid=0x4835 runnable [0x00000000496b3000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:275)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006f0c33738> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006f0c33768> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006f098dd68> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:786)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:434)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:882)

"redisson-netty-2-9" #250 prio=5 os_prio=0 tid=0x00002aaad8a40000 nid=0x4834 runnable [0x00000000495b2000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:275)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006f23564c8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006f23564f8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006f1fd6568> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:786)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:434)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:882)

"redisson-netty-2-8" #249 prio=5 os_prio=0 tid=0x00002aaad80c4800 nid=0x4833 runnable [0x00000000494b1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:275)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006f22e9c48> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006f22e9c78> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006f2780080> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:786)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:434)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:882)
```

**Comment by arunbenoyv** [comment]
@mrniko : In one of the cases that was recently observed, it started with 

[redisson-netty-2-7] org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL SENTINELS), params: [AAA], Redis client: [addr=redis://Y.Y.Y.Y:P]
	at org.redisson.client.RedisConnection$1.run(RedisConnection.java:209)

Sometimes it starts with SET,  GET, HMGET etc as well. 

Here if you see [redisson-netty-2-7] is where error occurred but,
as per thread analysis the thread consuming 100% CPU is [redisson-netty-2-20] though.

>>>>> Thread in which first error occurred redisson-netty-2-7
"redisson-netty-2-7" #42 prio=5 os_prio=0 tid=0x00007f62f521b000 nid=0x58 runnable [0x00007f620017f000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c1e4a5c8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006c1e4a5b8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c1e4a570> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:786)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:434)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

>>>>> Thread consuming 100% CPU is redisson-netty-2-20
"redisson-netty-2-20" #61 prio=5 os_prio=0 tid=0x00007f62f523b000 nid=0x6b runnable [0x00007f617baf9000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:381)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:104)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1127)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1174)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1098)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

Would changing Transport mode to epoll or defining redis.ping.connection.interval help? Could this be due to stale connections?

**Comment by mrniko** [comment]
@
I never faced such issue. You can try to set pingConnectionInterval

**Comment by mrniko** [comment]
I see in all cases thread RUNNING at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:381)

here is the source code for this method:

```java
    public E peek() {
        E[] buffer = this.consumerBuffer;
        long index = this.consumerIndex;
        long mask = this.consumerMask;
        long offset = LinkedArrayQueueUtil.modifiedCalcElementOffset(index, mask);
        Object e = UnsafeRefArrayAccess.lvElement(buffer, offset);
        if (e == null && index != this.lvProducerIndex()) {
            do {
                e = UnsafeRefArrayAccess.lvElement(buffer, offset);
            } while(e == null);
        }

        return e == JUMP ? this.newBufferPeek(this.getNextBuffer(buffer, mask), index) : e;
    }
```

It contains loop. Unfortunately, de-compiled version of this class doesn't contain line 381 at all. So I suggest the problem could be in internal do ... while loop. I can try to switch to a standard ConcurrentLinkedQueue object.

**Comment by johnou** [comment]
@mrniko maybe you ran into this? https://github.com/netty/netty/pull/9579

**Comment by mrniko** [comment]
@johnou 

Yes, you're right. Thanks for pointing out!

**Comment by mrniko** [comment]
Fixed

**Comment by arunbenoyv** [comment]
@mrniko : By when can we expect 3.11.5 release?

**Comment by mrniko** [comment]
@arunbenoyv 

At the end of this month

**Comment by deepak-t-n** [comment]
I am also facing this problem in production. May I know any specific date you have in mind? Does this issue exists in the paid version - Redission.Pro as well?

**Comment by mrniko** [comment]
@deepak-t-n 

Redisson PRO users affected this issue got hot fix version.

**Comment by jagan-autonomic** [comment]
I have faced this a couple of times in production. I am assuming 3.11.5 release will have the fix for this. Any date for that release?

**Comment by DIL8654** [comment]
I am using this spring-boot-starter dependency. But I am still getting this issue. It causes to restart the service. Any idea?

`[INFO] \- org.redisson:redisson-spring-boot-starter:jar:3.13.1:compile
[INFO]    +- org.redisson:redisson:jar:3.13.1:compile
[INFO]    |  +- io.netty:netty-codec:jar:4.1.52.Final:compile
[INFO]    |  +- io.netty:netty-buffer:jar:4.1.52.Final:compile
[INFO]    |  +- io.netty:netty-resolver-dns:jar:4.1.52.Final:compile
[INFO]    |  |  \- io.netty:netty-codec-dns:jar:4.1.52.Final:compile
[INFO]    |  +- javax.cache:cache-api:jar:1.1.1:compile
[INFO]    |  +- io.reactivex.rxjava2:rxjava:jar:2.2.19:compile
[INFO]    |  +- org.jboss.marshalling:jboss-marshalling-river:jar:2.0.9.Final:compile
[INFO]    |  |  \- org.jboss.marshalling:jboss-marshalling:jar:2.0.9.Final:compile
[INFO]    |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.11.2:compile
[INFO]    |  \- org.jodd:jodd-bean:jar:5.0.13:compile
[INFO]    |     \- org.jodd:jodd-core:jar:5.0.13:compile
[INFO]    \- org.redisson:redisson-spring-data-22:jar:3.13.1:compile
`

**Comment by smjt-h** [comment]
I am facing the same issue with version 4.1.86 as well, its causing restart to the service, Any idea 
`org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@451631109`

**Comment by shehanck** [comment]
@mrniko I'm facing this issue with Java 1.6 and Redisson 2.12.0. Considering upgrading Java as a limitation, is there a way to fix this issue? Thanks in advance!

**Comment by mrniko** [comment]
@smjt-h 

Did you try to increase `nettyThreads` as suggested in the message?
