### ISSUE TITLE
threads blocked waiting on CountDownLatch

### ISSUE THREAD

**Issue by ilyusha** [redisson/redisson#2304]
Hello,

We are facing an an issue where some threads get blocked indefinitely waiting on the CountDownLatch in `CommandAsyncService.get()`. Relevant section of the thread dump:
```
- waiting on java.util.concurrent.CountDownLatch$Sync@1f2311a9
at java.util.concurrent.locks.LockSupport.park(LockSupport.java: at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:186)
...
```
The reason for why the requests aren't able to complete isn't relevant here (we are deploying redis in kubernetes, and are working through various upgrade/failure scenarios that currently can result in severed connections). However, it's strange to me that the `CommandAsyncService.get()` method doesn't respect timeout configuration, and simply calls `l.await()`.
Is there any way around this? Please let me know if I am misunderstanding the situation.

### Expected behavior
`CommandAsyncService.get()` should throw an exception if the future is unable to complete within a timeout.

### Actual behavior
Many threads are hanging indefinitely in the `CommandAsyncService.get()` method.

### Redis version
5.0.5

### Redisson version
3.10.7

### Redisson configuration
nettyThreads=16
masterConnectionPoolSize=200
masterConnectionMinimumIdleSize=100
subscriptionConnectionPoolSize=200
subscriptionConnectionMinimumIdleSize=100
subscriptionsPerConnection=10
connectionTimeout=10000
retryInterval=3000
retryAttempts=10
keepAlive=true
tcpNoDelay=true
clusterScanInterval=2000
pingConnectionInterval=10000

**Comment by Lovesmoring** [comment]
We are also using redis inside k8s. And we are using one specific ClusterIP. 
Get org.redisson.client.RedisTimeoutException after running a while.
It's possible that our cluster may have some network glitch sometime, and then one after one all nettyThreads get busy(?).

Are you using RBlockingQueue? In my case i used RBlockingQueue.take().

**Comment by ilyusha** [comment]
@Lovesmoring We are not using RBlockingQueue in our application, but we are seeing this issue with RMap, RBucket, and executing Lua scripts.

RedisTimeoutException is what I would expect in my scenario - instead we are seeing threads waiting indefinitely.

**Comment by Lovesmoring** [comment]
> @Lovesmoring We are not using RBlockingQueue in our application, but we are seeing this issue with RMap, RBucket, and executing Lua scripts.
> 
> RedisTimeoutException is what I would expect in my scenario - instead we are seeing threads waiting indefinitely.

Alright. I see RedisTimeoutException when accessing RBucket too.
My point is that if some threads are waiting indefinitely, they are wasting resources and never come back, which may result in RedisTimeoutException eventually(when all threads are gone). But this is my assumption.

**Comment by thefoolwhocodes** [comment]
> RedisTimeoutException

@Lovesmoring RedisTimeoutException is not seen with the Redisson version 3.10.7. Looks to us like an issue with Redisson client.

**Comment by mrniko** [comment]
as for RedisTimeoutException please follow this guide https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by thefoolwhocodes** [comment]
Hi folks,
The issue related to the ticket is that RedisTimeoutException is **not** raised and CommandAsyncService.get() does not respect timeout configuration.

**Comment by mrniko** [comment]
@ilyusha 

Could you provide full thread dump?

**Comment by thefoolwhocodes** [comment]
@mrniko check this

> /service/soap
> Transaction type: Web
> Transaction name: /service/soap
> Duration: 13,100,174.0 milliseconds
> CPU time: 8.6 milliseconds
> "qtp653880197-1071299" #1071299
>    java.lang.Thread.State: WAITING
>         at jdk.internal.misc.Unsafe.park(Native Method)
>         - waiting on java.util.concurrent.CountDownLatch$Sync@6a1f3ce3
>         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
>         at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
>         at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:186)
>         at org.redisson.command.CommandSyncService.evalWrite(CommandSyncService.java:70)
>         at com.zimbra.cs.mailbox.redis.lock.RedisLock.execute(RedisLock.java:183)
>         at com.zimbra.cs.mailbox.redis.lock.RedisReadLock.tryAcquire(RedisReadLock.java:107)
>         at com.zimbra.cs.mailbox.redis.lock.RedisLock.lock(RedisLock.java:155)
>         at com.zimbra.cs.mailbox.redis.lock.RedisLock.lock(RedisLock.java:122)
>         at com.zimbra.cs.mailbox.DistributedMailboxLockFactory$DistributedMailboxLock.acquireRedisLock(DistributedMailboxLockFactory.java:448)
>         at com.zimbra.cs.mailbox.DistributedMailboxLockFactory$DistributedMailboxLock.lock(DistributedMailboxLockFactory.java:395)
>         - locked on com.zimbra.cs.mailbox.DistributedMailboxLockFactory$DistributedMailboxLock@48fdc21e
>         at com.zimbra.cs.mailbox.Mailbox$MailboxTransaction.<init>(Mailbox.java:9927)
>         at com.zimbra.cs.mailbox.Mailbox$MailboxTransaction.<init>(Mailbox.java:9910)
>         at com.zimbra.cs.mailbox.Mailbox.mailboxReadTransaction(Mailbox.java:9882)
>         at com.zimbra.cs.mailbox.Mailbox.getItemById(Mailbox.java:2554)
>         at com.zimbra.cs.mailbox.Mailbox.getItemById(Mailbox.java:2549)
>         at com.zimbra.cs.mailbox.Mailbox.getFolderById(Mailbox.java:3715)
>         at com.zimbra.cs.mailbox.Mailbox.getFolderByPath(Mailbox.java:3787)
>         at com.zimbra.cs.mailbox.MailSender.getSentFolderId(MailSender.java:302)
>         at com.zimbra.cs.mailbox.MailSender.sendMimeMessage(MailSender.java:615)
>         at com.zimbra.cs.mailbox.MailSender.sendMimeMessage(MailSender.java:488)
>         at com.zimbra.cs.mailbox.MailSender.sendMimeMessage(MailSender.java:430)
>         at com.zimbra.cs.service.mail.SendMsg.doSendMessage(SendMsg.java:258)
>         at com.zimbra.cs.service.mail.SendMsg.handle(SendMsg.java:182)
>         at com.zimbra.cs.service.mail.SendMsg.handle(SendMsg.java:108)
>         at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:664)
>         at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:509)
>         at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:296)
>         at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:307)
>         at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:216)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
>         at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:211)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
>         at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:169)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:125)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
>         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
>         at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
>         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
>         at org.eclipse.jetty.server.Server.handle(Server.java:517)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
>         at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
>         at java.lang.Thread.run(Thread.java:834)

**Comment by mrniko** [comment]
@thefoolwhocodes

Sorry, I meant full dump. It allows me to see which netty thread in blocked and cause block for another waiting thread.

**Comment by thefoolwhocodes** [comment]
[Threads.txt](https://github.com/redisson/redisson/files/3583233/Threads.txt)
Done @mrniko

**Comment by mrniko** [comment]
@thefoolwhocodes 

Thanks for the shared dump!
Is there any stepts to reproduce the issue?

**Comment by thefoolwhocodes** [comment]
@mrniko
Please find the steps that i used to simulate the same in **dev** environment. 
1.Have a cluster setup.
	We have 6 node Redis cluster with 3 masters and 3 slaves.
2.Keep the application (that uses Redisson client) busy enough.
3.Kill one of the masters (Redis masters).

Note:
The issue occurred in a **pre-production** environment.

**Comment by thefoolwhocodes** [comment]
Exception1:
```
[redisson-netty-2-10] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$438/0x000000080025fc40.operationComplete()
[redisson-netty-2-1] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$438/0x000000080025fc40.operationComplete()
[redisson-netty-2-12] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$438/0x000000080025fc40.operationComplete()
[redisson-netty-2-8] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$438/0x000000080025fc40.operationComplete()
[redisson-netty-2-15] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$438/0x000000080025fc40.operationComplete()
[redisson-netty-2-7] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$438/0x000000080025fc40.operationComplete()
[redisson-netty-2-11] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$438/0x000000080025fc40.operationComplete()
java.lang.IllegalStateException: cannot be started once stopped
	at io.netty.util.HashedWheelTimer.start(HashedWheelTimer.java:338)
	at io.netty.util.HashedWheelTimer.newTimeout(HashedWheelTimer.java:417)
	at org.redisson.client.handler.PingConnectionHandler.sendPing(PingConnectionHandler.java:66)
	at org.redisson.client.handler.PingConnectionHandler.lambda$channelActive$0(PingConnectionHandler.java:56)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.client.handler.BaseConnectionHandler.lambda$channelActive$1(BaseConnectionHandler.java:113)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:444)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:439)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:324)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:200)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:140)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:115)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mrniko** [comment]
Now I see the cause - io.netty.util.HashedWheelTimer has been stopped for some reason. It's resposible for all command timeouts.

**Comment by mrniko** [comment]
Could you create a memory dump when this error arise again? So we could check how many HashedWheelTimer instanes does JVM have.

**Comment by thefoolwhocodes** [comment]
> Now I see the cause - io.netty.util.HashedWheelTimer has been stopped for some reason. It's resposible for all command timeouts. It's stopped only during Redisson shutdown. Did you call it?

Yeah, we call at the scenarios when there is a state change in Redis servers.

**Comment by thefoolwhocodes** [comment]
> Could you create a memory dump when this error arise again? So we could check how many HashedWheelTimer instanes does JVM have.

Yeah sure.

**Comment by mrniko** [comment]
I did some changes to fix this issue. Please try attached version below:

[redisson-3.11.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3583782/redisson-3.11.4-SNAPSHOT.jar.zip)

**Comment by thefoolwhocodes** [comment]
@mrniko 
That''s wonderful.
Does it include https://github.com/redisson/redisson/issues/2306 too as i want to test the same in single pass.

**Comment by mrniko** [comment]
@thefoolwhocodes 

Indeed

**Comment by thefoolwhocodes** [comment]
@mrniko i could still see the issue
the stack trace is bit different and do not land at _CountDownLatch_ but creates similar issue at a different flow using _RedissonPromise_

```
/service/soap
Transaction type: Web
Transaction name: /service/soap
Duration: 2,375,482.7 milliseconds
CPU time: 16.3 milliseconds
"qtp1034584766-2136" #2136
   java.lang.Thread.State: WAITING
        at java.lang.Object.wait(Native Method)
        - waiting on io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise@371ad9af
        at java.lang.Object.wait(Object.java:328)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:232)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:134)
```

**Comment by mrniko** [comment]
@thefoolwhocodes 

after Redisson shutdown?

**Comment by thefoolwhocodes** [comment]
Simulation steps are same.
Yeah. I could upload the complete thread dump.

**Comment by thefoolwhocodes** [comment]
[Thread_dump_After_patch.txt](https://github.com/redisson/redisson/files/3590630/Thread_dump_After_patch.txt)

**Comment by mrniko** [comment]
Are there any exceptions this time?

**Comment by thefoolwhocodes** [comment]
I could not find the exception mentioned above.

**Comment by mrniko** [comment]
@thefoolwhocodes 

could you set `pingConnectionInterval = 0` and try again?

**Comment by thefoolwhocodes** [comment]
Sure @mrniko

**Comment by thefoolwhocodes** [comment]
@mrniko after setting pingConnectionInterval = 0 (default) + plus the above patch
I am not seeing any BLOCKED threads or WAITING threads for very longer duration.

**Comment by thefoolwhocodes** [comment]
@mrniko things looks ok here, but for a complete validation, i need https://github.com/redisson/redisson/issues/2306 too with this patch.
I am hitting the mentioned issue https://github.com/redisson/redisson/issues/2306 with this jar.
Thanks in advance.

**Comment by mrniko** [comment]
@ilyusha 

Could you try this snapshot and give your feedback?

[redisson-3.11.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3616767/redisson-3.11.4-SNAPSHOT.jar.zip)

**Comment by ilyusha** [comment]
@mrniko We are still doing some testing of the jar you provided. I'll let you know if there are any issues with it.

Thanks!

**Comment by mrniko** [comment]
Fixed! Please reopen it. If you encounter this issue again.
