### ISSUE TITLE
Jackson mapping for Config raising java.lang.reflect.InaccessibleObjectException with Java 11

### ISSUE THREAD

**Issue by mcanalesmayo** [redisson/redisson#2305]
### Expected behavior
Reading properties from a config file and mapping them with `com.fasterxml.jackson.databind.ObjectMapper.convertValue()` to a Redisson `Config` to be working fine.

### Actual behavior
It seems like with Java 9 module system using reflection is not as safe as before. We are running Java 11 and the following exception is raised when using `com.fasterxml.jackson.databind.ObjectMapper.convertValue()` to create a Redisson `Config` from a `Map` (properties loaded from a config file).
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final boolean java.lang.module.ModuleDescriptor.open accessible: module java.base does not "opens java.lang.module" to unnamed module @5c83ae01
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:891)
at com.fasterxml.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:102)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:484)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:350)
at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:245)
at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:467)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:467)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.resolve(SuperSonicBeanDeserializer.java:79)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:467)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.resolve(SuperSonicBeanDeserializer.java:79)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:467)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.resolve(SuperSonicBeanDeserializer.java:79)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4190)
at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3743)
at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
```
The exception is raised when trying to create a `ClassLoader` (which is needed in the Redisson `Codec`) via reflection.

I would like to know if there's any other way to easily create a Redisson `Config` based on a config file without having to hardcode every property.

If you have something in mind which can be implemented here to avoid this kind of issues we are more than happy to contribute a PR.

### Steps to reproduce or test case
We still can't reproduce this with a clear example, in some of our Java 11 apps we can convert to a Redisson `Config`, but in other ones the above exception is raised. So we are still trying to figure out how we can reproduce this consistently.

That said, the piece of code is something like this:
```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

Map<String, Object> config = loadConfigFile();
Config redissonCfg = objectMapper.convertValue(config, Config.class);
```

### Redis version
N/A

### Redisson version
3.11.0

### Jackson version
com.fasterxml.jackson.core : jackson-databind : 2.9.9

### Redisson configuration
N/A

**Comment by mrniko** [comment]
> If you have something in mind which can be implemented here to avoid this kind of issues we are more than happy to contribute a PR.

That would be great if we could use https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/ for json config parsing instead of jackson and https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.25/ for yaml config

**Comment by mcanalesmayo** [comment]
Thanks for your quick response.

Those libraries also use reflection, so I'm afraid that we would get the same resulting exception. Moreover we are using HOCON config files. We are looking for a way to transform a `Map` into a `Config` without using reflection or hardcoding every property.

**Comment by avillev** [comment]
We had the same issue in our project. My feeling is that since the bean rapid.shaded.org.redisson.config.Config does not have traditional setters, Jackson will try to reach the fields directly and fail at that point because of the new java rules.

**Comment by mrniko** [comment]
you need to add config mixin to get it work.

```java
mapper.addMixIn(Config.class, ConfigMixIn.class);
```
