### ISSUE TITLE
Graceful handling of failures for Redisson Tomcat Session Manager

### ISSUE THREAD

**Issue by howarddsouzaw** [redisson/redisson#2314]
I am using Redisson's Tomcat9 session manager going against Azure Redis Cache
with readMode=MEMORY and updateMode=DEFAULT .
This is mainly for session failover in case a server fails. Sessions are sticky, and so during normal operation, all session reads should be local within Tomcat.

Occasionally all of our Tomcat instances experience Netty timeout errors and requests to Redis fail.  This causes a complete failure of the application, as sessions are unavailable. This failure seems unnecessary, since the session data is available in local Tomcat memory and is not dependent on Redis (except in the case of failover)

Is there any way to get Redisson session manager to circuit break if calls to Redis fail or time out, and fall back to using session data from local memory ? The exception is below. Any help would be appreciated. Thanks!

Sep 05, 2019 1:09:58 AM org.redisson.tomcat.RedissonSessionManager findSession
SEVERE: Can't read session object by id: 36D02EC9371A380BBA8A8A6C7BAC6C37
org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=9, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://sessions-redis.redis.cache.windows.net:6380], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@310983480 [redisClient=[addr=rediss://sessions-redis.redis.cache.windows.net:6380], channel=[id: 0x51576dba, L:/10.23.152.48:49800 - R:sessions-redis.redis.cache.windows.net/137.116.35.20:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3f0a0e71(failure: java.util.concurrent.CancellationException)], command=(PUBLISH), params=[p-bs:redisson:tomcat_session_updates:/auth, PooledUnsafeDirectByteBuf(freed)], codec=org.redisson.client.codec.StringCodec]], command: (HMGET), params: [p-bs:redisson:tomcat_session:36D02EC9371A380BBA8A8A6C7BAC6C37, PooledUnsafeDirectByteBuf(ridx: 0, widx: 24, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 13, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 24, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 15, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 20, cap: 256)] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:714)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

 
### Expected behavior
Redisson Session Manager should fail gracefully and fall back to local memory if Redis calls fail, and Tomcat requests should succeed

### Actual behavior
All Tomcat requests that use the http session data fail

### Steps to reproduce or test case
Issue is intermittent, but occurs when calls to Netty time out 

### Redis version
Azure Cache for Redis

### Redisson version
3.11.0

### Redisson configuration

singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  clientName: null
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 35000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
If you look at https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java#L177

Redisson tries to load session from Redis only if it couldn't be found locally.
To overcome this issue set `broadcastSessionEvents=true` for RedissonSessionManager.

**Comment by howarddsouzaw** [comment]
Thank you, I will try that.

**Comment by mabombo** [comment]
Hi we have the same problem when we start tomcat the first time. If Redis for some reason is not available, the session manager fail. The session follback in MEMORY seems not work and the application id down. Or better, i think the session manager must works only in memory if Redis is not available.
The configuration is the same above. We use Redisson 3.11.4
Below the logs:

[localhost-startStop-1] WARN org.redisson.connection.SentinelConnectionManager - Can't connect to sentinel server. Unable to connect to: redis://rfs-bea-redis:26379
Oct 09, 2019 8:35:39 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [org.redisson.tomcat.RedissonSessionManager[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5730)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2038)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: org.redisson.client.RedisConnectionException: Unable to connect to Redis sentinel servers: redis://rfs-bea-redis:26379, 
        at org.redisson.tomcat.RedissonSessionManager.buildClient(RedissonSessionManager.java:356)
        at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:239)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 12 more
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis sentinel servers: redis://rfs-bea-redis:26379, 
        at org.redisson.connection.SentinelConnectionManager.checkAuth(SentinelConnectionManager.java:235)
        at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:104)
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:197)
        at org.redisson.Redisson.<init>(Redisson.java:120)
        at org.redisson.Redisson.create(Redisson.java:160)
        at org.redisson.tomcat.RedissonSessionManager.buildClient(RedissonSessionManager.java:354)
        ... 14 more

**Comment by mabombo** [comment]
I have used the config you have suggested. broadcastSessionEvents=true.

**Comment by mabombo** [comment]
To reproduce the problem start tomcat with Redis Down.

**Comment by mabombo** [comment]
The problem is the **session manager**, it doesn't start if Redis is Down

**Comment by mrniko** [comment]
Duplicated with https://github.com/redisson/redisson/issues/1651

**Comment by adbhutrai** [comment]
we are using Redisson's Tomcat10 session manager going against Azure Redis Cache with folliwng configuration. Our aplication is based on Spring MVC.

**Redisson version:**
**3.35.0**

**Redisson configuration:**
{
    "singleServerConfig": {
        "idleConnectionTimeout": 10000,
        "connectTimeout": 10000,
        "timeout": 3000,
        "retryAttempts": 3,
        "retryInterval": 1500,
        "subscriptionsPerConnection": 5,
        "clientName": null,
        "address": "rediss://:******************************@server.server.net:6380",
        "subscriptionConnectionMinimumIdleSize": 1,
        "subscriptionConnectionPoolSize": 50,
        "connectionMinimumIdleSize": 10,
        "connectionPoolSize": 64,
        "database": 0,
        "dnsMonitoringInterval": 5000
    },
    "threads": 0,
    "nettyThreads": 0,
    "lazyInitialization": true,
    codec: !<org.redisson.codec.SerializationCodec> {}
}


Tomcat redisson session manager config:


<Manager className="org.redisson.tomcat.RedissonSessionManager"
            configPath="${catalina.base}/redisson.conf"
            readMode="MEMORY"
            broadcastSessionEvents="true"
            updateMode="AFTER_REQUEST"/>
			

Here is the stack trace of the logs. Thanks
24-Sep-2024 15:55:41.879 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal The session manager failed to start
        org.apache.catalina.LifecycleException: Failed to start component [RedissonSessionManager[StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:402)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:179)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4441)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:599)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:571)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:654)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:969)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:771)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:423)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1629)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:109)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:385)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:332)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:776)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:874)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:757)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:569)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
        Caused by: org.redisson.client.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: down-test.redis.cache.windows.net/1.1.1.1:6380
                at org.redisson.connection.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:228)
                at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:188)
                at org.redisson.connection.MasterSlaveConnectionManager.lazyConnect(MasterSlaveConnectionManager.java:172)
                at org.redisson.connection.MasterSlaveConnectionManager.getEntry(MasterSlaveConnectionManager.java:466)
                at org.redisson.connection.MasterSlaveConnectionManager.getWriteEntry(MasterSlaveConnectionManager.java:473)
                at org.redisson.pubsub.PublishSubscribeService.getEntry(PublishSubscribeService.java:582)
                at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:381)
                at org.redisson.RedissonTopic.addListenerAsync(RedissonTopic.java:127)
                at org.redisson.RedissonTopic.addListenerAsync(RedissonTopic.java:123)
                at org.redisson.RedissonTopic.addListener(RedissonTopic.java:110)
                at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:350)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                ... 40 more
        Caused by: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: down-test.redis.cache.windows.net/1.1.1.1:6380
                at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
                at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
                at org.redisson.connection.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:223)
                ... 51 more
        Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: down-test.redis.cache.windows.net/1.1.1.1:6380
                at org.redisson.connection.ConnectionsHolder.lambda$createConnection$2(ConnectionsHolder.java:165)
                at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
                at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
                at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
                at org.redisson.connection.ConnectionsHolder.lambda$createConnection$5(ConnectionsHolder.java:179)
                at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
                at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
                at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
                at org.redisson.client.RedisClient$1$2.run(RedisClient.java:304)
                at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:840)
        Caused by: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: down-test.redis.cache.windows.net/1.1.1.1:6380
                at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
                at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
                at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)
                ... 11 more
        Caused by: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: down-test.redis.cache.windows.net/1.1.1.1:6380
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
                at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
                at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
                ... 8 more
24-Sep-2024 15:55:41.879 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
