### ISSUE TITLE
DNS issues occuring sometimes with Elasticache

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#2316]
Hello,

We are running in to DNS resolution failures sometimes. 

`DatagramDnsResponse(from: /10.0.0.2:53, to: /0:0:0:0:0:0:0:0:53018, 52723, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. IN A)
	DefaultDnsRawRecord(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. 15 IN A 4B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
2019-09-11 06:50:21,154-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [58273: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com. IN A)
2019-09-11 06:50:21,155-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [31257: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com. IN AAAA)
2019-09-11 06:50:21,155-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [54664: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. IN A)
2019-09-11 06:50:22,881-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [32392: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. IN AAAA)
2019-09-11 06:50:40,212-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-35] ERROR - Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com:6379] org.redisson.client.RedisTimeoutException: Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com:6379]
	at org.redisson.client.RedisConnection$1.run(RedisConnection.java:209) [redisson-3.10.7.jar:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

2019-09-11 06:50:37,598-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] ERROR - Unable to resolve useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com' failed to resolve 'useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.0.0.2:53] query timed out after 5000 milliseconds (no stack trace available)

2019-09-11 06:51:13,388-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] ERROR - Unable to resolve useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com' failed to resolve 'useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.35.Final.jar:4.1.35.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.0.0.2:53] query timed out after 5000 milliseconds (no stack trace available)`

 
The redisson configuration details are as below

Redisson Version : 3.10.7

Redis Server : Elasticache

Redisson Configuration

Server Mode: Replication
Threads: 32
Netty Threads : 64
decodeInExecutor:false
timeout : 10 seconds
pingInterval : 60 seconds

Can you please look in to this. This is happening intermittently(nearly 50% of times)

**Comment by mrniko** [comment]
Please make sure you have the same version in your classpath for all netty dependencies. Update it to 4.1.37.Final since it has some fixes for DNS handler.

**Comment by mrniko** [comment]
> Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.0.0.2:53] query timed out after 5000 milliseconds (no stack trace available)`

Please check that 10.0.0.2 is working

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1625
