### ISSUE TITLE
After restarted a slave node of cluster, redisson could not recover from "RedisConnection is not active" exception

### ISSUE THREAD

**Issue by ChePeatio** [redisson/redisson#2333]
### Expected behavior
The redisson should reconnect and query without exceptions, after the slave restarted.

### Actual behavior
After the slave node restarted successfully, the server using redisson v2.13.1 printed logs like `ClusterConnectionManager.java:245 | - slaves: [redis://x.x.x.x:x] added for slot ranges:[[x-x]] `, and I took it as redisson had reconnected to the slave node. However, when the server queried data in this node, there were expections:
```
org.redisson.client.RedisConnectionException: RedisConnection@xxxx [redisClient=[addr=redis://x.x.x.x:x], channel=[id: xxxx, L:x.x.x.x/x.x.x.x:xxxx]] is not active!
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:323)
	at org.redisson.connection.pool.ConnectionPool.connectTo(ConnectionPool.java:253)
	at org.redisson.connection.pool.ConnectionPool.access$300(ConnectionPool.java:53)
	at org.redisson.connection.pool.ConnectionPool$3.run(ConnectionPool.java:214)
	at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:142)
	at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:125)
	at org.redisson.connection.ClientConnectionsEntry.acquireConnection(ClientConnectionsEntry.java:134)
	at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:161)
	at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:224)
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:172)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:244)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:457)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:576)
	at org.redisson.command.CommandAsyncService.getConnection(CommandAsyncService.java:679)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:536)
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:625)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)
	at java.lang.Thread.run(Thread.java:748)
```
By contrast, the servers using redisson v3.7.3 recovered as expected.

### Steps to reproduce or test case
The redis cluster are composed of 3 masters with 3 slaves. 
I did `cluster failover` on the slave, after the master and slave switched successfully, i did `shutdown` and restarted the server. After the operations, the redisson threw exceptions when queried the restarted redis node, and could not recovered automatically in half an hour.

### Redis version
3.2.9

### Redisson version
Exception version：2.13.1
Right version：3.7.3

### Redisson configuration
We are using recommend parameters in redisson wiki, here are 2 key parameters：
```
{
  "clusterServerConfig": {
    "idleConnectionTimeout": 10000,
    ...,
    "readMode": "SLAVE",
    ...
  }
}
```

### Other problems
After master-slave switch and restart slave node, I found all redisson(v2.13.1 and v3.7.3) connections increased significantly(almost twice as normal connections), and `config timeout set xxx` was useless. When i restarted the servers, the redisson connections were back to normal. So is there a reason that redisson do no release idle connections for a long time?

**Comment by mrniko** [comment]
Please try to reproduce it with the latest version
