### ISSUE TITLE
DNSMonitor UnknownHostException with Azure Redis Cache

### ISSUE THREAD

**Issue by ijmac3** [redisson/redisson#2347]
While looking through the server logs of our application running on Microsoft Azure, I came across the UnknownHostException below. It seems to occur on average once or twice a day. 

```
<04:58:48> [ERROR] [DNSMonitor] Unable to resolve app.redis.cache.windows.net
java.net.UnknownHostException: failed to resolve 'app.redis.cache.windows.net'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:228) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177) [netty-resolver-dns-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:134) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [netty-transport-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.41.Final.jar:4.1.41.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/127.0.0.11:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
```

I found [this issue](https://github.com/redisson/redisson/issues/2316) which discusses a similar problem, but I am still seeing the error after upgrading to the latest version of Redisson.

### Redis version
3.2.7
### Redisson version
3.11.4
### Redisson configuration
```java
config.useSingleServer()
    .setAddress(PROTOCOL + HOST_PORT)
    .setPassword(PASSWORD)
    .setConnectTimeout(15000)
    .setConnectionMinimumIdleSize(32)
    .setConnectionPoolSize(32)
    .setRetryAttempts(3)
    .setRetryInterval(1500);
```

Any assistance would be much appreciated. 
Thanks.

**Comment by robsonkades** [comment]
I have the same problem.

**Comment by mrniko** [comment]
> [/127.0.0.11:53] query via UDP timed out after 5000 milliseconds

Please check your dns settings

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1625
