### ISSUE TITLE
Redis hostname gets a `]` at the end

### ISSUE THREAD

**Issue by jkutner** [redisson/redisson#2370]
### Expected behavior

Connects to Redis on AWS

### Actual behavior

Netty throws an exception trying to resolve the hostname:

```
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'ec2-54-234-206-155.compute-1.amazonaws.com]' failed to resolve 'ec2-54-234-206-155.compute-1.amazonaws.com].ec2.internal' after 3 queries
```

Somehow, there is a `]` added to the hostname (`ec2-54-234-206-155.compute-1.amazonaws.com]`), even though my `redisson.json` does not contain one.

### Steps to reproduce or test case

Click this button to deploy the repro example for free on Heroku:

[![Deploy to Heroku](https://www.herokucdn.com/deploy/button.png)](https://dashboard.heroku.com/new?&template=https%3A%2F%2Fgithub.com%2Fjkutner%2Fwebapp-runner-redis-example)

Then view the logs (you may need to restart the app if you want to view the logs in the browser because it crashes).

Or you may run this [sample app](https://github.com/jkutner/webapp-runner-redis-example) with a command like: 

```
$ java -jar webapp-runner.jar --session-store redis --session-store-pool-size 5 target/heroku-redisson-test.war
```

### Redis version

5.0

### Redisson version

3.11.4 (appeared in 3.11.01 and possibly earlier but not before 3.10.0)

### Redisson configuration

```json
{"singleServerConfig":{"idleConnectionTimeout":10000,"pingTimeout":1000,"connectTimeout":10000,"timeout":5000,"retryAttempts":3,"retryInterval":1500,"password":"pb9e2626905755078bb5c0fa4d482a19e5871b66645aac0c8650794d3c6e742f2","subscriptionsPerConnection":5,"sslEnableEndpointIdentification":true,"sslProvider":"JDK","
pingConnectionInterval":0,"keepAlive":false,"tcpNoDelay":false,"address":"redis://<redacted>:<redacted>@ec2-54-234-206-155.compute-1.amazonaws.com:15319","subscriptionConnectionMinimumIdleSize":1,"subscriptionConnectionPoolSize":50,"connectionMinimumIdleSize":5,"connectionPoolSize":5,"database":0,"dnsMonitoringInterval
":5000},"threads":16,"nettyThreads":32,"codec":{"class":"org.redisson.codec.FstCodec"},"referenceEnabled":true,"transportMode":"NIO","lockWatchdogTimeout":30000,"keepPubSubOrder":true,"decodeInExecutor":false,"useScriptCache":false,"minCleanUpDelay":5,"maxCleanUpDelay":1800,"addressResolverGroupFactory":{"class":"org.redisson.connection.DnsAddressResolverGroupFa
ctory"}}
```

### Other information

Tomcat 8.5.47

The source code for the [webapp-runner code that sets up Redisson can be found on Github](https://github.com/jsimone/webapp-runner/blob/master/redis/src/main/java/webapp/runner/launch/RedisSessionStore.java).

Full error:

```
SEVERE: The session manager failed to start
org.apache.catalina.LifecycleException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'ec2-34-226-17-251.compute-1.amazonaws.com]' failed to resolve 'ec2-34-226-17-251.compute-1.amazonaws.com].ec2.internal' after 3 queries
	at org.redisson.tomcat.RedissonSessionManager.buildClient(RedissonSessionManager.java:354)
	at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:237)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5182)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'ec2-34-226-17-251.compute-1.amazonaws.com]' failed to resolve 'ec2-34-226-17-251.compute-1.amazonaws.com].ec2.internal' after 3 queries
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:543)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:64)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:400)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:204)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:196)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Comment by mrniko** [comment]
Could you please set logging level `TRACE` for `org.redisson` package and share the output for this case?

**Comment by jkutner** [comment]
@mrniko sure. can you tell me how to configure that?

**Comment by mrniko** [comment]
that depends on logging lib you use

**Comment by jkutner** [comment]
Here's the raw logs. I need to take close look at it myself:
https://gist.github.com/jkutner/4197f08d24f042ba114453b84160af2c

**Comment by jkutner** [comment]
Nothing sticks out to me in those trace logs. The first reference I see has the `]`:

```
2019-10-19T16:05:15.370079+00:00 app[web.1]: [redisson-netty-2-2] DEBUG io.netty.resolver.dns.DnsQueryContext - [id: 0x1ffd6912] WRITE: UDP, [46640: /172.16.0.23:53], DefaultDnsQuestion(ec2-34-226-17-251.compute-1.amazonaws.com]. IN A)
```

**Comment by jkutner** [comment]
I'm starting to work through the debugger and I can see that at the moment the `Redisson` object is created, the config has the correct value

![redisson](https://user-images.githubusercontent.com/1589/67151376-16e51a80-f28b-11e9-8ec2-8b242910e2f1.png)

**Comment by jkutner** [comment]
I've found where the stray `]` is introduced, but I don't understand the correct way to fix this. It seems the `RedisURL` is adding brackets around the `<user>:<password>@<host>`, but `uri.getHost()` is then returning `<host>]`.

What is the purpose of those brackets? Can we `getHost` without them?

![redisson](https://user-images.githubusercontent.com/1589/67153734-1e6ce980-f2b4-11e9-8b64-9ffe5cec4d2f.png)

**Comment by mrniko** [comment]
braces are used for IPv6 formatting. The workaround for this bug is to omit <redacted>:<redacted>@ in url

**Comment by mrniko** [comment]
Fixed

**Comment by jkutner** [comment]
@mrniko the `user:password@` is a legal part of the URL. If I submit a patch that correctly moves the braces will you accept it?

**Comment by jkutner** [comment]
@mrniko oh! i just noticed your commit. thanks!
