### ISSUE TITLE
Unable to Create Redisson Session 

### ISSUE THREAD

**Issue by gbarsky** [redisson/redisson#2372]
### Expected behavior
Session object is stored in Redis
### Actual behavior
Getting the following error trying to enable session replication via Redisson:
21-Oct-2019 14:15:42.488 SEVERE [http-nio2-8086-exec-9] org.apache.coyote.http11.Http11Processor.service Error processing request
 java.lang.ClassCastException: org.apache.catalina.session.StandardManager cannot be cast to org.redisson.tomcat.RedissonSessionManager
        at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:55)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1735)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1069)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$3.completed(Nio2Endpoint.java:575)
        at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$3.completed(Nio2Endpoint.java:553)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
        at sun.nio.ch.Invoker$2.run(Invoker.java:218)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
### Steps to reproduce or test case
Tomcat Version 8.0.14
### Redisson version
redisson-tomcat-8-3.11.5
### Redisson configuration
singleServerConfig:
  address: "redis://${REDIS_HOST}:${REDIS_PORT}"

**Comment by gbarsky** [comment]
Please advise what am I doing wrong ?

**Comment by gbarsky** [comment]
Ignore it  . We figured out our problem

**Comment by Pino92** [comment]
@gbarsky Could you please tell me what was the cause of this issue? I'm facing the same

**Comment by gbarsky** [comment]
In our case the issue was that we defined RedissonSessionManager in context.xml in server level, but it conflicted with context.xml under webapp . Once we commented <Manager ...> directive for application context.xml - it solved the issue
