### ISSUE TITLE
org.redisson.client.RedisException: Unexpected exception while processing command

### ISSUE THREAD

**Issue by junchenbb0430** [redisson/redisson#2374]
### Expected behavior
   集合比对，求差集
### Actual behavior
  Caused by: java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:164)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:364)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:408)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:373)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:199)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:139)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)

### Steps to reproduce or test case
public Set<String> sdiffSet(String setSourceKey, String setDestKey) {
		RSet<String> sourceSet = redissonClient.getSet(setSourceKey);
		 
		return sourceSet.readDiff(setDestKey);
	}
### Redis version
3.10.5
### Redisson configuration
redis.pool.lock.waitTime=30000
redis.pool.lock.leaseTime=10000
redis.pool.cache.hostPrefix=redis://
redis.pool.cache.servers=redis1:7000,redis2:7000,redis3:7000,redis1:7001,redis2:7001,redis3:7001
redis.pool.cache.password=xxxxxx

redis.pool.cache.lockWatchTime=20

redis.pool.cache.cluserMaxAttempts=20

**Comment by mrniko** [comment]
Unable to reproduce this. Could you provide complete test code with data?
