### ISSUE TITLE
使用VIP的两Redis,VIP切换后,不会进行TCP断线重连

### ISSUE THREAD

**Issue by Icemap** [redisson/redisson#2379]
### Expected behavior
- 在VIP切换后，服务正常运行，可以进行Redisson在Redis上的读写
- 或在多次尝试失败后丢弃该TCP连接，进行TCP断线重连

### Actual behavior
- 超时

### Steps to reproduce or test case
- 搭建两Redis单点服务器
- 服务器配置VIP，提供统一出口
- Redisson通过VIP访问Redis
- 正常读写
- VIP切换
- 超时

### Redis version
- 4.0.6

### Redisson version
- 3.11.5

### Redisson configuration
- Class: SingleServerConfig
- Address: redis://192.168.1.30:6379
- 其中Address为VIP

### Consider
- 是否支持VIP模式，或是否支持TCP断线重连？
- 若无该模式，如使用useCustomServers()方式是否能解决该问题？

### Error Log
~~~
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (EVAL), params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, test-map, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 5, cap: 256)], channel: [id: 0xf04f767c, L:/10.237.147.15:54352 - R:192.168.1.30/192.168.1.30:6379]
	at org.redisson.command.RedisExecutor$3.run(RedisExecutor.java:338) ~[redisson-3.11.5.jar:3.11.5]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
~~~

**Comment by mrniko** [comment]
You need to define `pingConnectionInterval` param

https://github.com/redisson/redisson/wiki/2.-Configuration#pingconnectioninterval
