### ISSUE TITLE
Running into RedisTimeoutException. Need help to figure out

### ISSUE THREAD

**Issue by emtiazahmed** [redisson/redisson#2383]
### Expected behavior
few Timeout Exceptions
### Actual behavior
A lot of timeout exceptions and Can't add slave exceptions
### Steps to reproduce or test case
intermittent
### Redis version
Azure Redis Cache with 5 shards
4.0.14, 3.2.7
### Redisson version
3.11.4
### Redisson configuration
Default clustered config with the following overrides:
REDIS_ENABLED | true 
REDIS_KEEP_ALIVE | true 
REDIS_THREADS | 512 
REDIS_NETTY_THREADS | 1024 
REDIS_MASTER_CONNECTION_MINIMUM_IDLE_SIZE | 5 
REDIS_MASTER_CONNECTION_POOL_SIZE | 10 
REDIS_SLAVE_CONNECTION_MINIMUM_IDLE_SIZE | 5 
REDIS_SLAVE_CONNECTION_POOL_SIZE | 10
REDIS_TIMEOUT | 1000
REDIS_RETRY_INTERVAL | 500 
REDIS_TCP_NO_DELAY | true

I see following exceptions in the log:

`
exception: { [-]
     class: org.redisson.client.RedisConnectionException
     thrownfrom: unknown
   }
   level: ERROR
   logger_name: org.redisson.cluster.ClusterConnectionManager
   message: Can't add slave: rediss://<some-ip>:15002
   process: 6523
   stack_trace: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (READONLY), params: [], Redis client: [addr=rediss://<some-ip>:15002]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	... 2 common frames omitted
Wrapped by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: <some-ip>/<some-ip>:15002
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:160)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:330)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:296)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.client.RedisClient$2$1.run(RedisClient.java:240)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at i.n.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

stack_trace: org.redisson.client.RedisTimeoutException: Unable to get connection! Try to increase 'nettyThreads' and/or connection pool size settingsNode source: NodeSource [slot=15393, addr=redis://<some-ip>:15007, redisClient=null, redirect=MOVED, entry=null], command: (PSETEX), params: [some key, 3600000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 457, cap: 512)] after 0 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:209)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

 level: ERROR
   logger_name: org.redisson.cluster.ClusterConnectionManager
   message: Can't add master: rediss://<some-ip>:15007 for slot ranges: [[15019-15564], [12288-13652], [4096-5461]]
   process: 6574
   thread_name: redisson-netty-2-718
   timestamp: 2019-10-29 22:32:15.592

`

My logs are flooded with these exceptions and when I login to Azure portal, I see the CPU metric for Redis spiked to 100%. Any help is appreciated.

**Comment by mrniko** [comment]
Could you set logging level to `DEBUG` for `org.redisson` package and share the output when this issue happens? For some reason azure reports empty host or Redisson can't parse it. I need to figure out this with logs.

**Comment by emtiazahmed** [comment]
We've also seen these issues come up when Azure redis shard goes down and a new one comes up. Redisson does not seem to detect and starts failing until we restart the application.

**Comment by mrniko** [comment]
@emtiazahmed 

Could you also do these steps? https://github.com/redisson/redisson/issues/2383#issuecomment-547773073

**Comment by mrniko** [comment]
config looks right. I need the logs

**Comment by emtiazahmed** [comment]
exception: { [-]
     class: org.redisson.client.RedisException
     thrownfrom: unknown
   }
   level: ERROR
   logger_name: org.redisson.cluster.ClusterConnectionManager
   message: Can't update cluster state
   process: 5160
   stack_trace: org.redisson.client.RedisException: ERR invalid password. channel: [id: 0xd4d0e38e, L:/<some-ip>:43846 - R:<some-ip>/<some-ip>:6380] command: (AUTH), params: (password masked)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:371)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at i.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at i.n.c.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at i.n.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by emtiazahmed** [comment]
@mrniko I am trying to get another instance of redis provisioned to reproduce the issue and provide you with the logs, in the meanwhile, I got this response from microsoft:

> Our engineering team looked at the infra logs and they have seen a host update on the infrastructure hosting Shard 1 which caused a failover. Connections would have experienced a network blip during this time. Host OS update is similar to patching event explanation about it can be found here https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-failover

There seems to be an issue with Redisson client unable to detect when a shard goes down or a new one comes to replace it. We eventually have to restart our application to resolve such issues. 

Have you guys tested this scenario?

**Comment by mrniko** [comment]
> There seems to be an issue with Redisson client unable to detect when a shard goes down or a new one comes to replace it

This covered by tests in RedissonTest class. In your case Azure doesn't report hosts for slave and master, so Redisson unable to reconnect to it. This is why I asked to share cluster status logs available in DEBUG logging mode.

**Comment by emtiazahmed** [comment]
@mrniko I've shared the logs with you. You might have gotten an invite.

**Comment by mrniko** [comment]
@emtiazahmed 

org.redisson.client.RedisConnectionException: Not all slots are covered! Only 13107 slots are avaliable. Failed masters according to cluster status: [rediss://10.19.89.214:15001]

In Azure cluster info I see that 10.19.89.214:15001 node marked as failed

**Comment by emtiazahmed** [comment]
Any suggestions how we can recover from it?

**Comment by mrniko** [comment]
resolved in #2284
