### ISSUE TITLE
java.lang.NumberFormatException when ZRangeByScore query with -Infinity Double value

### ISSUE THREAD

**Issue by ashish2350** [redisson/redisson#2396]
### Expected behavior
No Exception must be thrown

### Actual behavior
2019-11-06 17:22:50:476*[ERROR]*scheduled-task-pool-2*o.s.s.s.TaskUtils$LoggingErrorHandler*handleError*Unexpected error occurred in scheduled task.
java.lang.NumberFormatException: null
	at java.math.BigDecimal.<init>(BigDecimal.java:497)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:809)
	at java.math.BigDecimal.valueOf(BigDecimal.java:1277)
	at org.redisson.spring.data.connection.RedissonConnection.value(RedissonConnection.java:1089)
	at org.redisson.spring.data.connection.RedissonConnection.zRangeByScore(RedissonConnection.java:1370)
	at org.redisson.spring.data.connection.RedissonConnection.zRangeByScore(RedissonConnection.java:1098)
	at org.springframework.data.redis.core.DefaultZSetOperations.lambda$rangeByScore$10(DefaultZSetOperations.java:197)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:225)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:185)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultZSetOperations.rangeByScore(DefaultZSetOperations.java:197)

### Steps to reproduce or test case
Try using RedissonConnectionFactory with RedisTemplate and call the method template.opsForZSet().rangeByScore(id, min, max); with min value as Double.NEGATIVE_INFINITY

### Redis version
4.0.9

### Redisson version
3.11.5

### Redisson configuration
Default Configuration on localhost

**Comment by mrniko** [comment]
Fixed! Thanks for report
