### ISSUE TITLE
IBM liberty Codec Error when trying to get session data from redis

### ISSUE THREAD

**Issue by vsrisubhash** [redisson/redisson#2406]
### Expected behavior
Configured session management in IBM liberty below is the configuration inside liberty server.xml, below I also attached teh redis-jcache.yml configuration.  I was expecting the session data to be stored in redis and get back the session whenever needed based on user activity. However I see redis throwing error during decode the data from redis.

<server>
    
    <featureManager>
        <feature>webProfile-8.0</feature>
		<feature>sessionCache-1.0</feature>
    </featureManager>
	
	
	
	<httpSessionCache libraryRef="JCacheLib" uri="file:D:/IBM/redis/wlp/usr/shared/resources/redis-jcache.yml"/>
	<library id="JCacheLib">
	   <fileset dir="${shared.resource.dir}" includes="redisson-all-3.10.7.jar"/> 
	</library>
	
 </server>

### Actual behavior

Once the application started I'm seeing the below error. This is even before  any user activity logged into the application.

[11/9/19 16:20:50:915 EST] 0000002e com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator          I SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at D:\IBM\redis\wlp\usr\servers\acServer\logs\state\plugin-cfg.xml.
[11/9/19 16:20:53:527 EST] 0000003a SystemErr                                                    R [redisson-netty-2-8] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0xf3683f34, L:/10.66.34.226:56737 - R:redishost/redisIP:redisport], reply: ReplayingDecoderByteBuf(ridx=30, widx=2390), command: (HSCAN), params: [com.ibm.ws.session.meta.default_host%2Fappname%2Fappname-web, 0, COUNT, 50]
[11/9/19 16:20:53:537 EST] 0000003a SystemErr                                                    R java.io.StreamCorruptedException: invalid stream header: 222E696E
[11/9/19 16:20:53:538 EST] 0000003a SystemErr                                                    R 	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
[11/9/19 16:20:53:539 EST] 0000003a SystemErr                                                    R 	at java.io.ObjectInputStream.<init>(Unknown Source)
[11/9/19 16:20:53:540 EST] 0000003a SystemErr                                                    R 	at org.redisson.codec.CustomObjectInputStream.<init>(CustomObjectInputStream.java:36)
[11/9/19 16:20:53:541 EST] 0000003a SystemErr                                                    R 	at org.redisson.codec.SerializationCodec$1.decode(SerializationCodec.java:51)
[11/9/19 16:20:53:542 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378)
[11/9/19 16:20:53:542 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:422)
[11/9/19 16:20:53:542 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
[11/9/19 16:20:53:543 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:422)
[11/9/19 16:20:53:547 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
[11/9/19 16:20:53:549 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209)
[11/9/19 16:20:53:549 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147)
[11/9/19 16:20:53:549 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
[11/9/19 16:20:53:549 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
[11/9/19 16:20:53:550 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
[11/9/19 16:20:53:550 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
[11/9/19 16:20:53:550 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[11/9/19 16:20:53:551 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[11/9/19 16:20:53:551 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[11/9/19 16:20:53:551 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
[11/9/19 16:20:53:551 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
[11/9/19 16:20:53:552 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
[11/9/19 16:20:53:552 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
[11/9/19 16:20:53:552 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
[11/9/19 16:20:53:553 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
[11/9/19 16:20:53:553 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[11/9/19 16:20:53:553 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[11/9/19 16:20:53:554 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[11/9/19 16:20:53:554 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[11/9/19 16:20:53:555 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[11/9/19 16:20:53:555 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[11/9/19 16:20:53:555 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[11/9/19 16:20:53:555 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[11/9/19 16:20:53:559 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[11/9/19 16:20:53:560 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[11/9/19 16:20:53:560 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[11/9/19 16:20:53:560 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[11/9/19 16:20:53:561 EST] 0000003a SystemErr                                                    R 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
[11/9/19 16:20:53:561 EST] 0000003a SystemErr                                                    R 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11/9/19 16:20:53:561 EST] 0000003a SystemErr                                                    R 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[11/9/19 16:20:53:562 EST] 0000003a SystemErr                                                    R 	at java.lang.Thread.run(Unknown Source)
[11/9/19 16:20:53:563 EST] 0000003a SystemErr                                                    R [redisson-netty-2-8] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[11/9/19 16:20:53:616 EST] 0000003a SystemErr                                                    R io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid stream header: 222E696E
[11/9/19 16:20:53:617 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
[11/9/19 16:20:53:617 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
[11/9/19 16:20:53:618 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[11/9/19 16:20:53:618 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[11/9/19 16:20:53:619 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[11/9/19 16:20:53:619 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
[11/9/19 16:20:53:622 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
[11/9/19 16:20:53:622 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
[11/9/19 16:20:53:622 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
[11/9/19 16:20:53:623 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
[11/9/19 16:20:53:623 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
[11/9/19 16:20:53:627 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[11/9/19 16:20:53:630 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[11/9/19 16:20:53:631 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[11/9/19 16:20:53:631 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[11/9/19 16:20:53:632 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[11/9/19 16:20:53:632 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[11/9/19 16:20:53:632 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[11/9/19 16:20:53:633 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[11/9/19 16:20:53:633 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[11/9/19 16:20:53:633 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[11/9/19 16:20:53:634 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[11/9/19 16:20:53:634 EST] 0000003a SystemErr                                                    R 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[11/9/19 16:20:53:635 EST] 0000003a SystemErr                                                    R 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
[11/9/19 16:20:53:635 EST] 0000003a SystemErr                                                    R 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11/9/19 16:20:53:639 EST] 0000003a SystemErr                                                    R 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[11/9/19 16:20:53:639 EST] 0000003a SystemErr                                                    R 	at java.lang.Thread.run(Unknown Source)
[11/9/19 16:20:53:639 EST] 0000003a SystemErr                                                    R Caused by: java.io.StreamCorruptedException: invalid stream header: 222E696E
[11/9/19 16:20:53:640 EST] 0000003a SystemErr                                                    R 	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
[11/9/19 16:20:53:640 EST] 0000003a SystemErr                                                    R 	at java.io.ObjectInputStream.<init>(Unknown Source)
[11/9/19 16:20:53:645 EST] 0000003a SystemErr                                                    R 	at org.redisson.codec.CustomObjectInputStream.<init>(CustomObjectInputStream.java:36)
[11/9/19 16:20:53:645 EST] 0000003a SystemErr                                                    R 	at org.redisson.codec.SerializationCodec$1.decode(SerializationCodec.java:51)
[11/9/19 16:20:53:646 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378)
[11/9/19 16:20:53:646 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:422)
[11/9/19 16:20:53:649 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
[11/9/19 16:20:53:650 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:422)
[11/9/19 16:20:53:651 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
[11/9/19 16:20:53:651 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209)
[11/9/19 16:20:53:657 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147)
[11/9/19 16:20:53:657 EST] 0000003a SystemErr                                                    R 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
[11/9/19 16:20:53:660 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
[11/9/19 16:20:53:661 EST] 0000003a SystemErr                                                    R 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
[11/9/19 16:20:53:661 EST] 0000003a SystemErr                                                    R 	... 26 more
[11/9/19 16:20:53:687 EST] 00000026 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "javax.cache.CacheException: org.redisson.client.RedisException: Unexpected exception while processing command com.ibm.ws.session.store.cache.CacheHashMap 367" at ffdc_19.11.09_16.20.53.0.log
[11/9/19 16:20:53:687 EST] 00000026 com.ibm.ws.session.store.cache.CacheHashMap                  E SESN0306E: An exception occurred when invalidating a session in the cache. The exception is: javax.cache.CacheException: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.jcache.JCache.scanIterator(JCache.java:2845)
	at org.redisson.jcache.JCache$10.iterator(JCache.java:3201)
	at org.redisson.BaseIterator.hasNext(BaseIterator.java:54)
	at com.ibm.ws.session.store.cache.CacheHashMap.doInvalidations(CacheHashMap.java:288)
	at com.ibm.ws.session.store.cache.CacheHashMap.performInvalidation(CacheHashMap.java:961)
	at com.ibm.ws.session.store.common.BackedStore.runInvalidation(BackedStore.java:130)
	at com.ibm.ws.session.SessionInvalidatorWithThreadPool$InvalidationTask.run(SessionInvalidatorWithThreadPool.java:70)
	at com.ibm.ws.threading.internal.SchedulingRunnableFixedHelper.run(SchedulingRunnableFixedHelper.java:272)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:232)

### Steps to reproduce or test case
Configure the features mentioned in server.xml  in open liberty 18.0.0.4 and configure redis configurations mentioned below.
 
### Redis version
5.0.0
### Redisson version
I tried both 3.11.5 / 3.10.7
### Redisson configuration
singleServerConfig:
  address: rediss://redishost:port
  clientName: appname
  password: null
codec: !<org.redisson.codec.SerializationCodec> {}

**Comment by mrniko** [comment]
Are you sure map with this name `com.ibm.ws.session.meta.default_host%2Fappname%2Fappname-web` stores values encoded by SerializationCodec?
