### ISSUE TITLE
Unable to decode data NPE

### ISSUE THREAD

**Issue by lidengke** [redisson/redisson#2419]
17:43:04.526 ERROR [redisson-3-6] org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0xaf08e3fd, L:/127.0.0.1:64741 ! R:127.0.0.1/127.0.0.1:6379], reply: PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 5), command: (BLPOP), params: [task_queue7, 1]
java.lang.NullPointerException: null
	at org.redisson.client.handler.CommandDecoder.sendNext(CommandDecoder.java:241)
	at org.redisson.client.handler.CommandDecoder.sendNext(CommandDecoder.java:154)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
	at org.redisson.client.handler.CommandDecoder.lambda$decode$0(CommandDecoder.java:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Redis version
Redis-x64-3.2.100
### Redisson version
3.11.4
### Redisson configuration
   baseConfig.useSingleServer()
                .setConnectionPoolSize(64)
                .setIdleConnectionTimeout(3 * 60 * 1000)
                .setKeepAlive(true)
                .setPingConnectionInterval(3000)
                .setSubscriptionConnectionMinimumIdleSize(5)
                .setAddress("redis://127.0.0.1:6379")
                .setTcpNoDelay(true)
                .setRetryAttempts(3)
                .setRetryInterval(1000)
                .setConnectTimeout(6000);

**Comment by mrniko** [comment]
Please provide code example to reproduce

**Comment by ehontoria** [comment]
Also running into this problem. 
```
java.lang.NullPointerException: null
	at org.redisson.client.handler.CommandDecoder.sendNext(CommandDecoder.java:241)
	at org.redisson.client.handler.CommandDecoder.sendNext(CommandDecoder.java:154)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
	at org.redisson.client.handler.CommandDecoder.lambda$decode$0(CommandDecoder.java:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Redisson version:
3.11.7-SNAPSHOT (latest master as of a week ago)

Redis version:
Have seen on both our Redis 3.2 and Redis 4 systems.

**Comment by mrniko** [comment]
@ehontoria Could you help to reproduce this?

**Comment by mrniko** [comment]
Fixed
