### ISSUE TITLE
 Can't write command: (PING)

### ISSUE THREAD

**Issue by lidengke** [redisson/redisson#2420]
8:23:20.220 WARN  [redisson-netty-2-82] io.netty.util.concurrent.AbstractEventExecutor     - A task raised an exception. Task: io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask@1a570461
java.lang.IllegalArgumentException: promise already done: DefaultChannelPromise@d94076a(failure: org.redisson.client.WriteRedisConnectionException: Channel has been closed! Can't write command: (PING), params: [] to channel: [id: 0x21828792, L:/127.0.0.1:50674 ! R:127.0.0.1/127.0.0.1:6379])
	at io.netty.channel.AbstractChannelHandlerContext.isNotValidPromise(AbstractChannelHandlerContext.java:880)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:763)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:700)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1091)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1062)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Redis version
Redis-x64-3.2.100
### Redisson version
3.11.4

**Comment by mrniko** [comment]
Cause: Channel has been closed
