### ISSUE TITLE
WriteRedisConnectionException

### ISSUE THREAD

**Issue by lidengke** [redisson/redisson#2421]
Caused by: org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:46:queue:0, freeConnectionsAmount=8, freeConnectionsCounter=value:48:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1185329979 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x76ae4a9f, L:/127.0.0.1:54653 ! R:127.0.0.1/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@606a9fc7(success)], command=(BLPOP), params=[task_queue9, 1], codec=org.redisson.codec.FstCodec]], command: (BLPOP), params: [task_queue14, 1] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:294)
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:77)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:179)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:176)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1018)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:874)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1365)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1091)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1062)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
Caused by: io.netty.channel.ExtendedClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
### Redisson version
3.11.4

**Comment by mrniko** [comment]
Cause: closed channel

**Comment by lidengke** [comment]
> Cause: closed channel

When restart application,  this exception occurs

**Comment by mrniko** [comment]
set `pingConnectionInterval` setting

**Comment by lidengke** [comment]
> set `pingConnectionInterval` setting
I have set pingInterval as followed: 
setConnectionPoolSize(redissonConfig.getConnectionPoolSize())
                .setIdleConnectionTimeout(3 * 60 * 1000)
                .setKeepAlive(true)
                .setPingConnectionInterval(3000)
                .setSubscriptionConnectionMinimumIdleSize(5)
                .setAddress("redis://" + redissonConfig.getServers())
                .setTcpNoDelay(true)
                .setRetryAttempts(3)
                .setRetryInterval(1000)
                .setConnectTimeout(6000);

**Comment by mrniko** [comment]
check your network
