### ISSUE TITLE
ClassNotFoundException: org.hibernate.cache.spi.support.AbstractReadWriteAccess$Item

### ISSUE THREAD

**Issue by bnjdpn** [redisson/redisson#2430]
I use Redission and Redission-Hibernate and got this error but cannot figure why.

### Actual behavior
```
org.redisson.client.RedisException: Unexpected exception while processing command

at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:401)

at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:205)

at org.redisson.RedissonObject.get(RedissonObject.java:94)

at org.redisson.RedissonMap.get(RedissonMap.java:266)

at org.redisson.hibernate.RedissonStorage.getFromCache(RedissonStorage.java:69)

at org.hibernate.cache.spi.support.AbstractReadWriteAccess.get(AbstractReadWriteAccess.java:70)

at org.hibernate.engine.internal.CacheHelper.fromSharedCache(CacheHelper.java:32)

at org.hibernate.event.internal.DefaultLoadEventListener.getFromSharedCache(DefaultLoadEventListener.java:654)

Caused by: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:org.hibernate.cache.spi.support.AbstractReadWriteAccess$Item loader:jdk.internal.loader.ClassLoaders$AppClassLoader@3c9c0d96

at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)

at org.redisson.codec.FstCodec$1.decode(FstCodec.java:242)

at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)

at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215)

at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153)

at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)

at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)

at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)

Caused by: java.lang.RuntimeException: class not found CLASSNAME:org.hibernate.cache.spi.support.AbstractReadWriteAccess$Item loader:jdk.internal.loader.ClassLoaders$AppClassLoader@3c9c0d96

at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:235)

at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190)

at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173)

at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478)

at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939)

at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347)

at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)

at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)

Caused by: java.lang.ClassNotFoundException: org.hibernate.cache.spi.support.AbstractReadWriteAccess$Item

at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)

at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)

at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

at java.base/java.lang.Class.forName0(Native Method)

at java.base/java.lang.Class.forName(Unknown Source)

at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:197)

at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190)

at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173)
```

### Redisson version
3.11.2

**Comment by mrniko** [comment]
Seems there is an issue with classloader. Where hibernate and redisson lib are located ?

**Comment by bnjdpn** [comment]
> Seems there is an issue with classloader. Where hibernate and redisson lib are located ?

- `redisson` come from an other Maven module named `cache`
- `redisson-hibernate` is defined in my module who throw the exception (a Spring Boot app)
- `hibernate` (5.3.10.Final) come from an other module named `database` who use `spring-boot-starter-data-jpa` (2.1.7.RELEASE)

**Comment by mrniko** [comment]
The point is that these both libs should be loaded by the same classloader

**Comment by bnjdpn** [comment]
> The point is that these both libs should be loaded by the same classloader

Moving dependency will not resolve this right ?

**Comment by mrniko** [comment]
Yes.
