### ISSUE TITLE
Reddison AWS ElastiCache Redis Cluster connection issues

### ISSUE THREAD

**Issue by concurrent-recursion** [redisson/redisson#2438]
When attempting to connect to our AWS ElastiCache Redis instance using the application.yaml configuration below.

### Expected behavior
Successful connection

### Actual behavior
I receive the following exception when trying to use the RedissonClient

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	... 148 common frames omitted
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:165) ~[redisson-3.11.5.jar:3.11.5]
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200) ~[redisson-3.11.5.jar:3.11.5]
	at org.redisson.Redisson.<init>(Redisson.java:120) ~[redisson-3.11.5.jar:3.11.5]
	at org.redisson.Redisson.create(Redisson.java:160) ~[redisson-3.11.5.jar:3.11.5]
	at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:164) ~[redisson-spring-boot-starter-3.11.5.jar:3.11.5]
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$bd180327.CGLIB$redisson$1(<generated>) ~[redisson-spring-boot-starter-3.11.5.jar:3.11.5]
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$bd180327$$FastClassBySpringCGLIB$$8f45c9cd.invoke(<generated>) ~[redisson-spring-boot-starter-3.11.5.jar:3.11.5]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$bd180327.redisson(<generated>) ~[redisson-spring-boot-starter-3.11.5.jar:3.11.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	... 149 common frames omitted
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://node-03.our-redis-instance-name.ssv2ov.use1.cache.amazonaws.com:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.11.5.jar:3.11.5]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
```

### Steps to reproduce or test case
Created Spring Boot Application (2.2.1), Added redisson-spring-boot-starter (3.11.5)

Created a spring Scheduled function to execute every second that uses RLock to getLock(), then tryLock(), then unlock()

The AWS ElastiCache Redis configuration is using TLS encryption (Encryption-in-transit) , and I'm able to connect using the same information using the instructions provided by [AWS here](https://aws.amazon.com/premiumsupport/knowledge-center/elasticache-connect-redis-node/)

### Redis version
AWS ElastiCache Redis
Engine: Clustered Redis
Encryption-in-Transit: Yes
Redis Version 5.0.5

### Redisson version
3.11.5
### Redisson configuration
```
spring:
  redis:
    host: clustercfg.our-redis-instance-name.ssv2ov.use1.cache.amazonaws.com
    port: 6379
    password: ourRedisPassword
    ssl: true
    cluster:
      nodes: node01.our-redis-instance-name.ssv2ov.use1.cache.amazonaws.com:6379,node02.our-redis-instance-name.ssv2ov.use1.cache.amazonaws.com:6379,node03.our-redis-instance-name.ssv2ov.use1.cache.amazonaws.com:6379
```

**Comment by mrniko** [comment]
Please set `TRACE` logging level for `org.redisson` and share logs for this issue.

**Comment by concurrent-recursion** [comment]
[redisson-test-log.txt](https://github.com/redisson/redisson/files/3912153/redisson-test-log.txt)
I have attached a copy of the log files with org.redisson set to TRACE

Let me know if you need anything else, Thanks!

**Comment by mrniko** [comment]
Thank you! Seems you have network issues. Did you check network for issues?

**Comment by concurrent-recursion** [comment]
It turns out the correct config was the following (where REDIS_HOST is the clustercfg node)

```
 spring:
   redis:
     password: ${REDIS_PASSWORD}
     cluster:
       nodes: rediss://${REDIS_HOST}:${REDIS_PORT:6379}
```

This connected to the secured cluster in AWS

Thanks for your help

**Comment by rohimsh** [comment]
`redis` with `s` i.e. `rediss` is important, this is what we had missed in our case.
