### ISSUE TITLE
Encoder NPE

### ISSUE THREAD

**Issue by ehontoria** [redisson/redisson#2493]
**Actual behavior**
Caused By: java.lang.NullPointerException ·
CommandEncoder.java:131org.redisson.client.handler.CommandEncoder.encode	
CommandEncoder.java:100org.redisson.client.handler.CommandEncoder.encode	
CommandBatchEncoder.java:52org.redisson.client.handler.CommandBatchEncoder.encode	
CommandBatchEncoder.java:32org.redisson.client.handler.CommandBatchEncoder.encode	
MessageToByteEncoder.java:107io.netty.handler.codec.MessageToByteEncoder.write	
CommandBatchEncoder.java:45org.redisson.client.handler.CommandBatchEncoder.write	
AbstractChannelHandlerContext.java:706io.netty.channel.AbstractChannelHandlerContext.invokeWrite0	
AbstractChannelHandlerContext.java:698io.netty.channel.AbstractChannelHandlerContext.invokeWrite	
AbstractChannelHandlerContext.java:780io.netty.channel.AbstractChannelHandlerContext.write	
AbstractChannelHandlerContext.java:691io.netty.channel.AbstractChannelHandlerContext.write	
ChannelDuplexHandler.java:106io.netty.channel.ChannelDuplexHandler.write	
CommandsQueue.java:97org.redisson.client.handler.CommandsQueue.write	
AbstractChannelHandlerContext.java:706io.netty.channel.AbstractChannelHandlerContext.invokeWrite0	
AbstractChannelHandlerContext.java:753io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush	
AbstractChannelHandlerContext.java:778io.netty.channel.AbstractChannelHandlerContext.write	
AbstractChannelHandlerContext.java:747io.netty.channel.AbstractChannelHandlerContext.writeAndFlush	
DefaultChannelPipeline.java:1031io.netty.channel.DefaultChannelPipeline.writeAndFlush	
AbstractChannel.java:310io.netty.channel.AbstractChannel.writeAndFlush	
CommandsQueue.java:123org.redisson.client.handler.CommandsQueue.sendData	
CommandsQueue.java:100org.redisson.client.handler.CommandsQueue.write

**Redis version**
Seen on versions 3 and 4

**Redisson version**
3.11.7-SNAPSHOT (latest as of a couple weeks ago)

**Redisson configuration**
Master-Slave Cluster configuration

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/2419

**Comment by kurenchuksergey** [comment]
I have the same problem in redisson-3.13.5
Stack trace:
		at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:131) ~[redisson-3.13.5.jar:3.13.5]
		at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:100) ~[redisson-3.13.5.jar:3.13.5]
		at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:56) ~[redisson-3.13.5.jar:3.13.5]
		at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:76) ~[redisson-3.13.5.jar:3.13.5]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45) ~[redisson-3.13.5.jar:3.13.5]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:88) ~[redisson-3.13.5.jar:3.13.5]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:114) ~[redisson-3.13.5.jar:3.13.5]
		at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:91) ~[redisson-3.13.5.jar:3.13.5]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by kurenchuksergey** [comment]
@mrniko it is my fail, i have invoke getSet(null)

**Comment by mrniko** [comment]
Name check added
