### ISSUE TITLE
使用spring实例化TypedJsonJacksonCodec，报方法org.redisson.codec.TypedJsonJacksonCodec.<init>()不存在

### ISSUE THREAD

**Issue by Vensence** [redisson/redisson#2496]
![image](https://user-images.githubusercontent.com/22963992/71355159-2f3e2200-25b9-11ea-9754-8bb3075d60ed.png)

在使用如上方式配置，构造codec实例时，报初始化方法不存在，如下是异常栈：
Caused by: java.lang.NoSuchMethodException: org.redisson.codec.TypedJsonJacksonCodec.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	... 82 common frames omitted

redisson版本3.11.5

**Comment by Vensence** [comment]
redisson版本3.11.5

**Comment by mrniko** [comment]
TypedJsonJacksonCodec doesn't have default constrctor

**Comment by sdvdxl** [comment]
这个类为啥不搞个 INSTANCE，而且是必须传参呢？
