### ISSUE TITLE
java.lang.IllegalStateException: Failed to introspect Class [org.redisson.spring.cache.RedissonCacheStatisticsAutoConfiguration] from ClassLoader

### ISSUE THREAD

**Issue by jchobantonov** [redisson/redisson#2508]
Env: Tomcat/8.5.35
Deploying spring boot as web application :
Spring Boot v2.1.6.RELEASE
Spring v5.1.8.RELEASE
the web app contains 
@EnableCaching spring annotation

in tomcat lib I have following jars:
redisson-all-3.11.1-SNAPSHOT.jar
redisson-tomcat-8-3.11.1-SNAPSHOT.jar

During web app boot from tomcat here is the exception:

```
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration$AuditEventRepositoryConfiguration
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:59)
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:447)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:128)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
        at java.util.concurrent.FutureTask.run(FutureTask.java:277)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.redisson.spring.cache.RedissonCacheStatisticsAutoConfiguration] from ClassLoader [java.net.URLClassLoader@ccf6af1b]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:507)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:404)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:389)
        at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:447)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$$Lambda$299.00000000147FF510.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1671)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:738)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:679)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:647)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1518)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1023)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:190)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:157)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanType(BeanTypeRegistry.java:150)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:138)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$$Lambda$297.0000000013A73830.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Iterator.java:127)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:133)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:97)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:268)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:261)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:250)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:170)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:145)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:46)
        ... 30 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org.springframework.boot.actuate.metrics.cache.CacheMeterBinderProvider
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:377)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:729)
        at java.net.URLClassLoader.access$400(URLClassLoader.java:95)
        at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1184)
        at java.security.AccessController.doPrivileged(AccessController.java:730)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:604)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
        at java.lang.Class.getDeclaredMethodsImpl(Native Method)
        at java.lang.Class.getDeclaredMethods(Class.java:929)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)
        ... 54 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.metrics.cache.CacheMeterBinderProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:609)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
        ... 68 common frames omitted
```

The missing class 'org.springframework.boot.actuate.metrics.cache.CacheMeterBinderProvider' is in spring-boot-actuator-2.1.6.RELEASE.jar that is inside the web application inside WEB-INF/lib folder

I guess the issue is because the redisson library is inside tomcat system lib and the introspection happens from the web application -  e.g. different classloaders - I guess redisson tomcat lib can't load classes from war file where the CacheMeterBinderProvider class is located - If I remove redisson lib from tomcat the web application deploys and functions as intended

If I put a break point into org.springframework.util.ReflectionUtils method's getDeclaredMethods
where the exception occur here is the exception stack trace from this method and exception that occur:
The getDeclaredMethods is invoked with parameter "org.redisson.spring.cache.RedissonCacheStatisticsAutoConfiguration" for bean redissonCacheMeterBinderProvider
here is the exception : 

```
java.lang.NoClassDefFoundError: org.springframework.boot.actuate.metrics.cache.CacheMeterBinderProvider
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:377)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:729)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:95)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1184)
	at java.security.AccessController.doPrivileged(AccessController.java:730)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:604)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	at java.lang.Class.getDeclaredMethodsImpl(Native Method)
	at java.lang.Class.getDeclaredMethods(Class.java:929)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:404)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:389)
	at org.springframework.util.ReflectionUtils.getAllDeclaredMethods(ReflectionUtils.java:434)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getCandidateFactoryMethods(BeanTypeRegistry.java:257)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getFactoryMethod(BeanTypeRegistry.java:243)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getFactoryMethod(BeanTypeRegistry.java:238)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getFactoryMethodReturnType(BeanTypeRegistry.java:217)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:188)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:157)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanType(BeanTypeRegistry.java:150)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:138)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$$Lambda$292.0000000018682530.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:127)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:133)
	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:97)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:268)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:261)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:250)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:170)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:145)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:46)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:447)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:128)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.metrics.cache.CacheMeterBinderProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:609)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:924)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:869)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:852)
	... 65 more
```

Note there are no "org.springframework" libs in Tomcat lib directory (only inside war lib directory).
The class "org.springframework.boot.actuate.metrics.cache.CacheMeterBinderProvider" is defined only inside /WEB-INF/lib/spring-boot-actuator-2.1.6.RELEASE.jar of the war file (no such class inside tomcat lib or another jar file inside the war file)

If I define this inside spring boot web app in the @Configuration:
```
@EnableAutoConfiguration(excludeName = {"org.redisson.spring.cache.RedissonCacheStatisticsAutoConfiguration"})
```
Then I get this exception:
```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cachesEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/cache/CachesEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'cachesEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cacheManager' defined in class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]: Unsatisfied dependency expressed through method 'cacheManager' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheCacheManager' defined in class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.cache.CacheManager]: Factory method 'jCacheCacheManager' threw exception; nested exception is java.lang.IllegalStateException: Default configuration hasn't been specified!
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
        at java.util.concurrent.FutureTask.run(FutureTask.java:277)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:811)
```
So I can't exclude redisson auto configuration. The javax.cache package is only defined inside redisson;s lib redisson-all-3.11.1-SNAPSHOT.jar - there are no javax.cache packages bundled with the war file

**Comment by jchobantonov** [comment]
Note that if I add 
```
@EnableAutoConfiguration(excludeName = {"org.redisson.spring.cache.RedissonCacheStatisticsAutoConfiguration"})
```
Then in order to not get that JCache do not have default impl I need to specify the cache type in application.properties file as well like this:

```
spring.cache.type=CAFFEINE
```

only then the web application will load correctly but the downside is that the web application needs to know that it should exclude RedissonCacheStatisticsAutoConfiguration

Probably RedissonCacheStatisticsAutoConfiguration should inspect the spring.cache.type (or to add dependency on this property to activate the auto configuration) and if it is JCACHE only then to activate redisson cache auto configuration

**Comment by mrniko** [comment]
Can you add follow line to RedissonCacheStatisticsAutoConfiguration and check?

`@ConditionalOnProperty(name = "spring.cache.type", havingValue = "REDIS")`

**Comment by mrniko** [comment]
I think it's better to modify ConditionalOnBean:

@ConditionalOnBean({CacheManager.class, RedissonCache.class})

**Comment by mrniko** [comment]
Yes, we need to change ConditionalOnBean, since RedissonCacheStatisticsAutoConfiguration applied only to RedissonCache instances.

**Comment by jchobantonov** [comment]
@mrniko following annotation when added is working:
```
@ConditionalOnProperty(name = "spring.cache.type", havingValue = "REDIS")
```
e.g. I don't get the exception.

I have also tied this:
Instead of : 
```
@ConditionalOnClass(MeterBinder.class)
```

I have change it to : 
```
@ConditionalOnClass({MeterBinder.class, RedissonCache.class})
```
and without putting @ConditionalOnProperty is also working - it is a bit strange because RedissonCache is a class in the same package as RedissonCacheStatisticsAutoConfiguration but it is working for me - e.g. the app do not have in it's classpath RedissonCache

So I guess the proper way should be to change this:
```
@ConditionalOnClass(MeterBinder.class)
```
to 
```
@ConditionalOnClass({MeterBinder.class, CacheMeterBinderProvider.class, RedissonCache.class})
```
I'm adding CacheMeterBinderProvider as the class is needed for the whole thing to work and this is the class that it complains it is not in the classpath - not sure if you should add this class in ConditionalOnClass but I guess it should
FYI just setting it to : 
```
@ConditionalOnClass({MeterBinder.class, CacheMeterBinderProvider.class})
```
did not work out for me - the same exception that the CacheMeterBinderProvider.class was not found.

As for the following condition only : 
```
@ConditionalOnProperty(name = "spring.cache.type", havingValue = "REDIS")
```
The problem with this I guess is if we use redisson as tomcat session replication and in the web application we do use redis as cache but not using redisson library - so the spring.cache.type will be redis but we should not load redisson as default library to provide the cache 

I saw in your test cases that you are using 'spring.redis.redisson.config' to get the redisson yml file out of the env so I guess we should use both spring.cache.type = REDIS and spring.redis.redisson.config to be set - so to end up with this:
```
@ConditionalOnExpression("'${spring.cache.type:none}'.equalsIgnoreCase('REDIS') && '${spring.redis.redisson.config:}'.length() > 0")
```
This way we should know because of the existence of 'spring.redis.redisson.config' we are using redisson as cache and because  of 'spring.cache.type=REDIS' we are using redis as cache

**Comment by mrniko** [comment]
Could you try `@ConditionalOnBean({CacheManager.class, RedissonCache.class})` ? This should work, because it takes into account presence of RedissonCache bean in spring context.

**Comment by jchobantonov** [comment]
@mrniko it is working

**Comment by mrniko** [comment]
@jchobantonov 

Thanks for help!

**Comment by mrniko** [comment]
Fixed
