### ISSUE TITLE
Memory Leak in SentinelConnectionManager

### ISSUE THREAD

**Issue by markusdlugi** [redisson/redisson#2539]
Might be connected to https://github.com/redisson/redisson/issues/2120, but I wasn't too sure about that, so I decided to create a new issue instead.

**Expected behavior**

No memory leak?

**Actual behavior**

SentinelConnectionManager is leaking memory because it stores too many connections to the sentinels in the `nodeConnections` map.

We are using a singleton Redisson instance for connecting to our replicated Redis instance (3 nodes, 3 sentinels). After running for some days, we are experiencing high GC times and OOM errors. Upon investigating the heap dump, we noticed that the SentinelConnectionManager stores nearly 50,000 connection to the same 3 sentinels in its `nodeConnections` map. However, the `sentinels` map itself only contains the expected 3 entries.

<img width="593" alt="sentinelconnectionmanager_heap" src="https://user-images.githubusercontent.com/19145587/72245770-9451ca00-35f1-11ea-8516-bb3aeca96700.png">

I tried analyzing and reproducing the leak myself, but I wasn't too successful since I am not familiar with your code. Would be great if you could have a look what could cause such a behavior :)

Unfortunately can't provide the heap dump since it might contain sensitive data.

**Steps to reproduce or test case**

N/A

**Redis version**

4.0.2

**Redisson version**

3.11.3

**Redisson configuration**

```
config.useSentinelServers().setMasterName("mymaster")
    .addSentinelAddress(redisSentinelAddress)
    .setPassword("")
    .setReadMode(ReadMode.MASTER)
    .setSubscriptionMode(SubscriptionMode.MASTER)
    .setMasterConnectionPoolSize(64)
    .setRetryInterval(2000)
    .setRetryAttempts(3)
    .setConnectTimeout(1000)
    .setTimeout(5000);
```

**Comment by mrniko** [comment]
Unable to reproduce it. Could you investigate the cause? here is the method for debug https://github.com/redisson/redisson/blob/f7b3fbc64a422e625f974b23f1d5dfc73542ad1e/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L248

**Comment by jchobantonov** [comment]
@mrniko the only place where nodeConnections is getting populated is in MasterSlaveConnectionManager.connectToNode and SentinelConnectionManager is the only one that will pass not null RedisClient (and null RedisURI) - now because RedisClient do not implement hashCode and equals as RedisURI it could happen that if you pass each time different RedisClient object (even thought that is connected to the same server having the same config) those objects't won't match unless it is the same object. If each time we create new RedisClient with the same config and invoking the connectToNode the nodeCollection will get bigger and bigger because no one will clear this out - probably a new weak hashmap would be needed for the case where instead of RedisURI you pass RedisClient - this way if you discard your instance of RedisClient and it is ready to be garbage collected it will be discarded from the nodeConnections cache (probably the connection should also be closed)

Also in MasterSlaveConnectionManager you do have this method as well closeNodeConnections() - but nowhere you are removing the connection from the nodeConnections  as you do in closeNodeConnection(RedisConnection conn)

**Comment by mrniko** [comment]
> it could happen that if you pass each time different RedisClient object

This couldn't be happen since they gathered from `sentinels` map which maps `RedisClient` object per `RedisURI`.

> If each time we create new RedisClient with the same config

The point is that RedisClient isn't created each time.

**Comment by markusdlugi** [comment]
Hi again,

thanks for your analysis efforts. I added some logging to our test environment and this is a stack trace of when a new connection is added to the `nodeConnections` map:

```
at org.redisson.connection.MasterSlaveConnectionManager.lambda$connectToNode$0(MasterSlaveConnectionManager.java:274) 
at org.redisson.connection.MasterSlaveConnectionManager.dt_access$1258(MasterSlaveConnectionManager.java) 
at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) 
at org.redisson.misc.RedissonPromise.dt_access$237(RedissonPromise.java) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) 
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) 
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) 
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527) 
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98) 
at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82) 
at org.redisson.client.RedisClient$2$1.run(RedisClient.java:232) 
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) 
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) 
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) 
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
```

So it doesn't seem to originate from the SentinelConnectionManager really - I thought so because all the connections in the `nodeConnections` map were for the sentinels, but apparently it's just from normal client usage, I guess? Then the question would be why the connections are not re-used, or rather, why they are never removed after usage?

**Comment by mrniko** [comment]
Due to async nature of connection process you'll never see that `client.connectAsync` orginiated from SentinelConnectionManager but from netty thread and `RedisClient.connectAsync` method.

**Comment by mrniko** [comment]
Can you debug if RedisClient instance created too many times? Currenlty I see this is the only cause of memory consumption.

**Comment by markusdlugi** [comment]
So I can already tell that there are two ways RedisClients are added - via `SentinelConnectionManager.updateSentinels()` and also via `SentinelConnectionManager.scheduleSentinelDNSCheck()`. Stack traces of both ways:

```
at org.redisson.client.RedisClient.create(RedisClient.java:81) 
at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:436) 
at org.redisson.connection.SentinelConnectionManager.registerSentinel(SentinelConnectionManager.java:523) 
at org.redisson.connection.SentinelConnectionManager.access$500(SentinelConnectionManager.java:70) 
at org.redisson.connection.SentinelConnectionManager$1$2.operationComplete(SentinelConnectionManager.java:281) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493) 
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) 
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) 
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527) 
at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:90) 
at io.netty.resolver.InetSocketAddressResolver$2.operationComplete(InetSocketAddressResolver.java:86) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493) 
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) 
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) 
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527) 
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98) 
at io.netty.resolver.dns.DnsResolveContext$1.operationComplete(DnsResolveContext.java:218) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) 
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) 
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) 
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527) 
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98) 
at io.netty.resolver.dns.DnsNameResolver.trySuccess(DnsNameResolver.java:898) 
at io.netty.resolver.dns.DnsNameResolver.doResolveAllCached(DnsNameResolver.java:997) 
at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:91) 
at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:234) 
at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1038) 
at io.netty.resolver.dns.DnsNameResolver.access$500(DnsNameResolver.java:91) 
at io.netty.resolver.dns.DnsNameResolver$5.run(DnsNameResolver.java:1021) 
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) 
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) 
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) 
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
at java.lang.Thread.run(Thread.java:748)
```

```
at org.redisson.client.RedisClient.create(RedisClient.java:81) 
at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:436) 
at org.redisson.connection.SentinelConnectionManager.registerSentinel(SentinelConnectionManager.java:523) 
at org.redisson.connection.SentinelConnectionManager.updateSentinels(SentinelConnectionManager.java:480) 
at org.redisson.connection.SentinelConnectionManager.lambda$updateState$6(SentinelConnectionManager.java:469) 
at org.redisson.connection.SentinelConnectionManager.dt_access$1028(SentinelConnectionManager.java) 
at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) 
at org.redisson.misc.RedissonPromise.dt_access$237(RedissonPromise.java) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493) 
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) 
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) 
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527) 
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98) 
at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82) 
at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:460) 
at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:455) 
at org.redisson.client.handler.CommandDecoder.decodeResult(CommandDecoder.java:444) 
at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:438) 
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393) 
at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215) 
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153) 
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122) 
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505) 
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) 
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) 
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) 
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) 
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) 
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) 
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
at java.lang.Thread.run(Thread.java:748)
```

However, after having a look at the code, I don't know how this is possible since the code does seem to check if the URI isn't already contained in the `sentinels` map. I'll try and debug further to find out why it creates a new client anyway.

**Comment by mrniko** [comment]
> I don't know how this is possible since the code does seem to check if the URI isn't already contained in the sentinels map

Also you should see a lot of follow messages in log: `sentinel: {} added`

**Comment by markusdlugi** [comment]
Okay, so the problem is that we are running our Redis cluster on OpenShift / Kubernetes. The cluster is exposed at a route which resolves to `172.30.55.27` - I guess some integrated OpenShift load balancer is listening at that address. When connecting, it will forward you to one of the actual instances, which in our case are `10.221.5.13`, `10.221.8.219` and `10.221.21.203`.

Now what we observed is that the `SentinelConnectionManager.updateState()` will for some reason only resolve to 3 addresses, but will sometimes switch which addresses it resolves. So some custom logging we added there looked like this:

```
January 21st 2020, 11:33:12.302	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:13.311	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://172.30.55.27:26379, redis://10.221.5.13:26379
January 21st 2020, 11:33:14.317	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://172.30.55.27:26379, redis://10.221.5.13:26379
January 21st 2020, 11:33:15.319	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:16.325	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:17.328	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:18.334	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://172.30.55.27:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:19.339	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:20.344	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:21.352	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:22.358	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
January 21st 2020, 11:33:23.365	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://172.30.55.27:26379, redis://10.221.5.13:26379
January 21st 2020, 11:33:24.369	Calling updateSentinels with newUris redis://10.221.8.219:26379, redis://10.221.5.13:26379, redis://10.221.21.203:26379
```
Since the `updateSentinels` method also removes stuff from the `sentinels` map, this will then lead to a new `RedisClient` with associated `RedisConnection` being added again after every switch-up of the resolved addresses. Now I'm not sure why exactly the `updateState()` method will only resolve to exactly three sentinels and switch them up from time to time - maybe because of the filtering it does? In contrast to that, the resolver used in the `scheduleSentinelDNSCheck()` will only resolve to the load balancer (172) IP.

In my opinion, this behavior should be fixed by:

1. Ensuring that removing a sentinel from the `sentinels` map also removes the connection from the parent class `nodeConnections`.
2. Ideally, `updateState()` should only resolve to the same 3/4 sentinels and not switch them up every time, though not sure yet how this can be accomplished. I'm happy to test any proposals if you have any idea how to change the code here.

**Comment by mrniko** [comment]
Thank you for research! I think the problem is that some sentinels different list of available sentinels.

**Comment by mrniko** [comment]
sentinels list should be the same this is why I add current sentinel into newUris list:

https://github.com/redisson/redisson/blob/603552df559d7199524ce65d6db4cd2000c85c76/redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java#L457

**Comment by mrniko** [comment]
Fixed. Please try attached snapshot version:

[redisson-3.12.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4091646/redisson-3.12.1-SNAPSHOT.jar.zip)

**Comment by markusdlugi** [comment]
Thanks for the snapshot. Of course, properly removing the connection after removing a sentinel from the map helps with our memory leak, but we tried to further investigate the root cause for why so many connections are created and closed in the first place.

We found out that the primary reason for this is our load balancer in front of our sentinels, as already described in my previous post. Since we are running our cluster in OpenShift, we don't know the IP addresses of all sentinels in advance, so we rely on our load balancer to connect to the cluster. And even though the load balancer IP is removed from the `sentinels` map soon after connection because the sentinels themselves don't know about it, it will keep getting re-added because of the DNS check which only knows the load balancer IP and adds it back to the `sentinels` map.

We tested running our application without the DNS check, but then we lost the ability to reconnect to the cluster in case all sentinels go down at the same time, because we never tried to connect via the load balancer anymore. So to alleviate this problem, we created a PR that allows to only run the DNS check in case all connections fail. Would be great if you could have a look: https://github.com/redisson/redisson/pull/2563
