### ISSUE TITLE
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 6e3d30b7-83b1-433a-9335-5e8b9916d3ac thread-id: 731

### ISSUE THREAD

**Issue by hezhiqiang** [redisson/redisson#2546]
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 6e3d30b7-83b1-433a-9335-5e8b9916d3ac thread-id: 731 
    at org.redisson.RedissonLock.lambda$unlockAsync$3(RedissonLock.java:580) 
    at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) 
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) 
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) 
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) 
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) 
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) 
    at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) 
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) 
    at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82) 
    at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:483) 
    at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:476) 
    at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:461) 
    at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:447) 
    at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:169) 
    at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) 
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) 
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) 
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) 
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) 
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) 
    at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) 
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) 
    at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82) 
    at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:444) 
    at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:439) 
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370) 
    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) 
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) 
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) 
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:493) 
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) 
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) 
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) 
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) 
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) 
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) 
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) 
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) 
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) 
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) 
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
    at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
RLock should be unlocked by the same thread locked it.
