### ISSUE TITLE
java.net.MalformedURLException: Invalid host

### ISSUE THREAD

**Issue by xebex** [redisson/redisson#2548]
Redisson version: 3.12.0

When using ipv6, we get the following error:

java.lang.IllegalArgumentException: java.net.MalformedURLException: Invalid host: [[22be:ffee:0:f101::328]
	at org.redisson.misc.RedisURI.<init>(RedisURI.java:54)
	at org.redisson.connection.SentinelConnectionManager.convert(SentinelConnectionManager.java:595)
	at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:167)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:197)
	at org.redisson.Redisson.<init>(Redisson.java:120)
	at org.redisson.Redisson.create(Redisson.java:160)
	...
Caused by: java.net.MalformedURLException: Invalid host: [[22be:ffee:0:f101::328]
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.redisson.misc.RedisURI.<init>(RedisURI.java:49)
	... 82 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid host: [[22be:ffee:0:f101::328]
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:195)
	at java.net.URL.<init>(URL.java:622)
	... 85 common frames omitted
	
It seems that in org.redisson.connection.SentinelConnectionManager#createAddress, the square bracket is added to the address; then in new RedisURI(), the square bracket was added AGAIN.

**Comment by mrniko** [comment]
Fixed. Thanks for report

Please try attached build and give your feedback:
[redisson-3.12.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4084734/redisson-3.12.1-SNAPSHOT.jar.zip)
