### ISSUE TITLE
ElastiCache/Redis - RedisConnectionException and RedisResponseTimeoutException

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#2549]
****We use redis distributed delay queues for queuing data for future process and connecting to redis using node from each shard in cluster.** Around 10% of the data is lost due to these errors.

**Redis client version -3.9.1**

We see RedisConnectionException and RedisResponseTimeoutException**

**org.redisson.client.RedisConnectionException**: 

SlaveConnectionPool no available Redis entries.  Disconnected hosts: [1.2.4.3/1.1.1.1:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:217)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:244)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:471)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:580)
	at org.redisson.command.CommandAsyncService.getConnection(CommandAsyncService.java:814)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:671)
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:760)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

**RedisResponseTimeoutException: Redis server response timeout (3000 ms) occurred for command:".** 

**Here is the complete error.**

org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local result = {}; local items = redis.call('lrange', KEYS[1], 0, -1); for i, v in ipairs(items) do ..., 1, redisson_delay_queue:{delayEventQueue-e-prod}] channel: [id: 0x0f2e4a10, L:/ - R:]
	at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:882)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

**Redis configuration is below.  We have configured single node from each shard, what is the recommended approach for node configuration, cluster endpoint or nodes from each shard?** 

{
  "clusterServersConfig": {
    "idleConnectionTimeout": 10000,
    "pingTimeout": 1000,
    "connectTimeout": 10000,
    "timeout": 3000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "reconnectionTimeout": 3000,
    "failedAttempts": 3,
    "password": null,
    "subscriptionsPerConnection": 5,
    "clientName": "realTimeEventScheduler",
    "loadBalancer": {
      "class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveSubscriptionConnectionMinimumIdleSize": 1,
    "slaveSubscriptionConnectionPoolSize": 50,
    "slaveConnectionMinimumIdleSize": 10,
    "slaveConnectionPoolSize": 64,
    "masterConnectionMinimumIdleSize": 10,
    "masterConnectionPoolSize": 64,
    "readMode": "SLAVE",
    "nodeAddresses": [
      "redis://node:6379",
      "redis://node:6379",
      "redis://node:6379",
      "redis://node:6379"
    ],
    "scanInterval": 1000
  },
  "threads": 0,
  "nettyThreads": 0,
  "codec": null,
  "useLinuxNativeEpoll": false
}

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by mrniko** [comment]
Also I would recommend to update to 3.10.3 or the latest version. It contains decoding optimizations:

https://github.com/redisson/redisson/blob/master/CHANGELOG.md#26-feb-2019---3103-released
