### ISSUE TITLE
java.lang.NoClassDefFoundError: org.redisson.misc.RedissonPromise

### ISSUE THREAD

**Issue by sharmad1205** [redisson/redisson#2558]
Working with replicaof server. 
Returning data when using RedisDesktopManager. But when I tried to create client following exception occurs with RedissonPromise

`01-23 19:52:03.408 20281-20281/com.example.uhf E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.uhf, PID: 20281
    java.lang.NoClassDefFoundError: org.redisson.misc.RedissonPromise
        at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:663)
        at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:643)
        at org.redisson.connection.MasterSlaveConnectionManager.stopThreads(MasterSlaveConnectionManager.java:727)
        at org.redisson.connection.MasterSlaveConnectionManager.initSingleEntry(MasterSlaveConnectionManager.java:363)
        at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:167)
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:191)
        at org.redisson.Redisson.<init>(Redisson.java:120)
        at org.redisson.Redisson.create(Redisson.java:160)
`
I am using
` implementation 'org.redisson:redisson:3.12.6'`

using config
`config.useMasterSlaveServers()
                .setMasterAddress("redis://<master ip> <master port>")
                .setReadMode(ReadMode.SLAVE)
                .addSlaveAddress("redis://<replica ip> <replica port>");
        config.setCodec(JsonJacksonCodec.INSTANCE);`
same exception occurs using `config.useSingleServer()`

**Comment by mrniko** [comment]
seems there is a some problem with classloading in your application. Is there complete example to reproduce?

**Comment by sharmad1205** [comment]
@mrniko  
My Server is a replica of main server like
`configs.putString("bind", "0.0.0.0");
configs.putString("maxmemory", "1GB");
configs.putString("port", "10000");
configs.putString("protected-mode", "no");
configs.putString("masterauth", "XXX);
configs.putString("requirepass", "XXX");
configs.putString("replicaof", "XXX.XXX.XXX.XXX 6379");`

Also tried with redisson config like
`Config config = new Config();
config.useSingleServer()
.setAddress("redis://<myreplicaserver>:10000")
.setPassword("XXXXXX");
client = Redisson.create();`

However I can connect to my replica through third party desktop application RedisDesktopManager
But this crash come on line `Redisson.create()`

**Comment by mrniko** [comment]
`org.redisson.misc.RedissonPromise` is in jar. You need to fix this classpath issue.

**Comment by sharmad1205** [comment]
@mrniko Thanks for replying, I am using in android with gradle implementation
`implementation 'org.redisson:redisson:3.12.6'`

While importing the RedissonPromise is there. But `Redisson.Create()` function didn;t find the class path.
