### ISSUE TITLE
Command still hasn't been written into connection?

### ISSUE THREAD

**Issue by bellevue800** [redisson/redisson#2559]
There was almost no load on the system and it has almost no activity with only one idle connection  (we keep two connections in reserve - connectionMinimumIdleSize: 2) and the freeConnectionsCounter=63  (out of  connectionPoolSize: 64).  

How come we received the “Command still hasn't been written into connection” error message? It seems like something was preventing Redisson from sending commands to Redis, resulting in a timeout exception...

org.redisson.client.RedisTimeoutException: **Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings** Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=1, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://example8872.redis.cache.windows.net:6380], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@491802721 [redisClient=[addr=rediss:// example8872.redis.cache.windows.net:6380], channel=[id: 0xdfc88972, L:/10.23.209.100:55594 - R: example8872.redis.cache.windows.net/52.111.71.236:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@52cca638(failure: java.util.concurrent.CancellationException)], command=(HMSET), params=[p-bb:redisson:tomcat_session:EFE72C79B569DA602D9867772D1BA0D3, PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), PooledUnsafeDirectByteBuf(freed), ...], codec=org.redisson.codec.CompositeCodec@2ae5abfe]], command: (HGETALL), params: [p-bb:redisson:tomcat_session:EFE72C79B969DA602D9865372D1BA0D3] after 5 retry attempts
      at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:202) ~[redisson-all.jar:3.11.6]
      at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680) ~[netty-common-4.1.32.Final.jar:3.11.6]
      at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755) ~[netty-common-4.1.32.Final.jar:3.11.6]
      at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483) ~[netty-common-4.1.32.Final.jar:3.11.6
      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.32.Final.jar:3.11.6]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

------------------------------------------
singleServerConfig:
  idleConnectionTimeout: 30000
  connectTimeout: 30000
  timeout: 5000
  retryAttempts: 5
  retryInterval: 5000
  subscriptionsPerConnection: 5
  clientName: null
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 2
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 10000
threads: 32
nettyThreads: 64
codec: !<org.redisson.codec.FstCodec> {}

**Comment by mrniko** [comment]
Seems you trying to store big payload with HMSET command. I would recommend to increase `retryInterval` setting or split payload into several chunks.

**Comment by bellevue800** [comment]
How big the payload is considered too big for HMSET command using Redisson? Thanks mrniko.

**Comment by bellevue800** [comment]
> I would recommend to increase retryInterval

Again, there was almost no activity on the system when the error message was received. Thanks again mrniko!       --> my question is how big the payload is too big for HMSET.

**Comment by mrniko** [comment]
> my question is how big the payload is too big for HMSET

Depends on environment. Did you try to split it?

**Comment by bellevue800** [comment]
No we did not. The payload is really small - it was a java.util.Date object which only contains a serializable long... but still we got that "Command still hasn't been written into connection" error. We have looked into the source code... Please correct me if I am wrong, but it does not seem be related to payload size. Please see RedisExecutor.java, around Line 200. Thanks.

**Comment by mrniko** [comment]
this means that even after all attempts writeFuture wasn't succefully completed. Which means write operation not executed over network channel.

**Comment by bellevue800** [comment]
what could cause writeFuture to fail? Thanks.

**Comment by bellevue800** [comment]
According to the if statements in RedisExecutor.java, around Line 200, we got that error message because: writeFurure.isDone() is false,
writeFuture is not null, 
writeFuture.cancel() is false  i.e., not cancelled. **Why is writeFurure.isDone() not true? Thanks.**

**Comment by mrniko** [comment]
> Why is writeFurure.isDone() not true? Thanks.

https://github.com/redisson/redisson/issues/2559#issuecomment-578390516

**Comment by bellevue800** [comment]
Line 1:                       if (writeFuture == null || !writeFuture.isDone()) {
Line 2:                          if (attempt == attempts) {
Line 3:                               if (writeFuture != null && writeFuture.cancel(false)) {
Line 4                                    if (exception == null)
All 4 lines have to be true. If Line 3 is true, writeFuture is not null. If writeFuture is not null, for Line 1, writeFuture.isDone() has to be false. Am I missing something? Please kindly advise. Thanks.

**Comment by mrniko** [comment]
Sorry, I can't explain this in other way than I did already in my comment.

**Comment by bellevue800** [comment]
So if writeFurure.isDone() is false, I assume the write operation was executed but somehow blocked? Meaning, it did not succeed, did not fail, and did was not cancelled either? Thanks.

**Comment by mrniko** [comment]
it means that it's still in progress in this case.

**Comment by mrniko** [comment]
I faced this issue only when all nettyThreads are busy.

**Comment by bellevue800** [comment]
Thanks! Makes sense/Oh I see.

**Comment by bellevue800** [comment]
But for our case, the load was **really** low...

**Comment by bellevue800** [comment]
But why was it blocked....

**Comment by bellevue800** [comment]
or, "in progress" (until it got timed out?)

**Comment by mrniko** [comment]
Probably the cause in slow network layer

**Comment by bellevue800** [comment]
Got it and thanks for your comment. I think we can close this case now. Thank you again, mrniko!

**Comment by swtrustly** [comment]
We've experienced the same thing and threads got timed out pretty easily. I could reproduce the error with only four requests to the external API of the service. In our case, we found that there were several `get` invocations in a row to the same object (Spring Reactive code). Refactoring of the code to only do one `get` and give the object as a parameter solved the issue.
So all in all, our problem was a threading blocking/race condition because of several calls in a row.

**Comment by deepak-auto** [comment]
@mrniko We are seeing the same error in one of our environments as well. The throughput in that env is really low (5-10 ops), so I am thinking how could our service with such low throughput trigger this sort of an error. Interestingly, we do not see too many of these errors in our main environment which receives 1000x more throughput. Could you tell us how to deal with this interesting problem?

**Comment by zcz3313** [comment]
> We've experienced the same thing and threads got timed out pretty easily. I could reproduce the error with only four requests to the external API of the service. In our case, we found that there were several `get` invocations in a row to the same object (Spring Reactive code). Refactoring of the code to only do one `get` and give the object as a parameter solved the issue.
> So all in all, our problem was a threading blocking/race condition because of several calls in a row.

we have also met the same problem, can you give some example codes to reproduce it?

**Comment by zcz3313** [comment]
@swtrustly

**Comment by swtrustly** [comment]
> @swtrustly

Way too old. We've replaced Redisson in this system.

**Comment by mrniko** [comment]
@zcz3313 

Did you define `pingConnectionInterval` setting?

**Comment by zcz3313** [comment]
> @zcz3313
> 
> Did you define `pingConnectionInterval` setting?
@mrniko 
No. But I have seen some comments that might give me some clues, e.g [this](https://github.com/redisson/redisson/issues/2647#issuecomment-602390188) and [this](https://github.com/redisson/redisson/issues/2911#issue-655379753).
So, then I upgrate my redisson version from 3.12.4 to 3.13.6 and define pingConnectionInterval and keepAlive setting in production environment.
I need to watch the log a few days to see if it works.

**Comment by mrniko** [comment]
@zcz3313 

Also make sure you don't use blocking commands in async/rx/reactive handlers.

**Comment by zcz3313** [comment]
> @zcz3313
> 
> Also make sure you don't use blocking commands in async/rx/reactive handlers.

@mrniko 
We use RedisTemplate (Implemented by Redisson) in Spring Cloud Gateway.
As I know, Spring Cloud Gateway is designed by reactive code.
My code example is shown as below.
```java
stringRedisTemplate.opsForHash().putAll(key, map);

redisTemplate.opsForHash().entries(key)
```

Will this have any effect?

**Comment by mrniko** [comment]
@zcz3313 

No

**Comment by mrniko** [comment]
@zcz3313 

> I need to watch the log a few days to see if it works.

Any update?

**Comment by zcz3313** [comment]
> @zcz3313
> 
> > I need to watch the log a few days to see if it works.
> 
> Any update?

No, it does'nt work. I changed to jedis. What's the meaning of 'don't use blocking commands in async/rx/reactive handlers'? Can you show me an example?

**Comment by mrniko** [comment]
> What's the meaning of 'don't use blocking commands in async/rx/reactive handlers'? Can you show me an example?

you don't need to worry about it if you don't use Redisson directly.

Can you to set following settings:

subscriptionConnectionMinimumIdleSize: 1
subscriptionConnectionPoolSize: 8
connectionMinimumIdleSize: 2
connectionPoolSize: 8

**Comment by zcz3313** [comment]
> @zcz3313
> 
> > What's the meaning of 'don't use blocking commands in async/rx/reactive handlers'? Can you show me an example?
> 
> you don't need to worry about it if you don't use Redisson directly.
> 
> Can you to set following settings:
> 
> subscriptionConnectionMinimumIdleSize: 1
> subscriptionConnectionPoolSize: 8
> connectionMinimumIdleSize: 2
> connectionPoolSize: 8

I'll try it if we deploy another system in prod env.
The old system is running well now.
Thanks at all!

**Comment by zcz3313** [comment]
@mrniko 
> 
> > What's the meaning of 'don't use blocking commands in async/rx/reactive handlers'? Can you show me an example?
> 
> you don't need to worry about it if you don't use Redisson directly.
> 
> Can you to set following settings:
> 
> subscriptionConnectionMinimumIdleSize: 1
> subscriptionConnectionPoolSize: 8
> connectionMinimumIdleSize: 2
> connectionPoolSize: 8

I'll try it if we deploy another system in prod env.
The old system is running well now.
Thanks at all!

**Comment by zcz3313** [comment]
@mrniko 

> What's the meaning of 'don't use blocking commands in async/rx/reactive handlers'? Can you show me an example?
> 
> you don't need to worry about it if you don't use Redisson directly.
> 
> Can you to set following settings:
> 
> subscriptionConnectionMinimumIdleSize: 1
> subscriptionConnectionPoolSize: 8
> connectionMinimumIdleSize: 2
> connectionPoolSize: 8

I'll try it if we deploy another system in prod env.
The old system is running well now.
Thanks at all!

**Comment by zcz3313** [comment]
@mrniko 

> Can you to set following settings:
> 
> subscriptionConnectionMinimumIdleSize: 1
> subscriptionConnectionPoolSize: 8
> connectionMinimumIdleSize: 2
> connectionPoolSize: 8

I'll try it if we deploy another system in prod env.
The old system is running well now.
Thanks at all!

**Comment by niko-autonomic** [comment]
Resurrecting this thread as we had the same issue in a low-volume redis instance. 

For us, It seems this issue is potentially related to CPU throttling on cloud deployments. Adding `--no-cpu-throttling` to our on GCP CloudRun container which connects via Redisson to the Redis instnace resolved it for our client.
