### ISSUE TITLE
How to properly load redisson dependencies inside a jar file

### ISSUE THREAD

**Issue by AlanPrado** [redisson/redisson#2564]
Hello guys,

I've setup Redission, Redission-Hibernate and Spring Data Cache to work with Spring Boot.

Pom definition:
```
	<properties>
		<redisson-spring-boot-starter.version>3.11.6</redisson-spring-boot-starter.version>
	</properties>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
		</dependency>

		<!-- redisson configuration begin -->
		<!-- For more information refer to documentation: https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter#spring-boot-starter -->
		<dependency>
			<!-- for Spring Data Redis v.2.1.x -->
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-data-21</artifactId>
			<version>${redisson-spring-boot-starter.version}</version>
		</dependency>
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-boot-starter</artifactId>
			<version>${redisson-spring-boot-starter.version}</version>
		</dependency>
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-hibernate-53</artifactId>
			<version>${redisson-spring-boot-starter.version}</version>
		</dependency>
		<!-- redisson configuration end -->

```

When I start the application I'm getting the following warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/XXX/.m2/repository/de/ruedigermoeller/fst/2.57/fst-2.57.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

When I start the application through eclipse application lunch, everything works fine. But when I create my application jar (mvn package), and run it by prompt command and issue a request for a cached resource, I'm getting the following error:

```
ERROR 2020-01-27 16:46:41,393 [redisson-netty-5-11] org.redisson.client.handler.CommandDecoder:decodeCommand(212): Unable to decode data. channel: [id: 0x2137d2ce, L:/127.0.0.1:22780 - R:localhost/127.0.0.1:9000], reply: ReplayingDecoderByteBuf(ridx=122, widx=122), command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, Location, redisson__timeout__set:{Location}, redisson__idle__set:{Location}, redisson__map_cache__last_access__set:{Location}, {Location}:redisson_options, 1580150801152, PooledUnsafeDirectByteBuf(ridx: 0, widx: 470, cap: 512)]
java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:org.hibernate.cache.spi.support.AbstractReadWriteAccess$SoftLockImpl loader:jdk.internal.loader.ClassLoaders$AppClassLoader@c387f44
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar!/:?]
        at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209) [redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147) [redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) [redisson-3.11.6.jar!/:3.11.6]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) [netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.RuntimeException: class not found CLASSNAME:org.hibernate.cache.spi.support.AbstractReadWriteAccess$SoftLockImpl loader:jdk.internal.loader.ClassLoaders$AppClassLoader@c387f44
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:235) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar!/:?]
        ... 24 more
Caused by: java.lang.ClassNotFoundException: org.hibernate.cache.spi.support.AbstractReadWriteAccess$SoftLockImpl
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:415) ~[?:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:197) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar!/:?]
        ... 24 more
WARN  2020-01-27 16:46:41,401 [redisson-netty-5-11] io.netty.channel.DefaultChannelPipeline:onUnhandledInboundException(1152): An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:org.hibernate.cache.spi.support.AbstractReadWriteAccess$SoftLockImpl loader:jdk.internal.loader.ClassLoaders$AppClassLoader@c387f44
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:org.hibernate.cache.spi.support.AbstractReadWriteAccess$SoftLockImpl loader:jdk.internal.loader.ClassLoaders$AppClassLoader@c387f44
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar!/:?]
        at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) ~[redisson-3.11.6.jar!/:3.11.6]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        ... 17 more
Caused by: java.lang.RuntimeException: class not found CLASSNAME:org.hibernate.cache.spi.support.AbstractReadWriteAccess$SoftLockImpl loader:jdk.internal.loader.ClassLoaders$AppClassLoader@c387f44
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:235) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar!/:?]
        at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) ~[redisson-3.11.6.jar!/:3.11.6]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: org.hibernate.cache.spi.support.AbstractReadWriteAccess$SoftLockImpl
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:415) ~[?:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:197) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar!/:?]
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar!/:?]
        at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147) ~[redisson-3.11.6.jar!/:3.11.6]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) ~[redisson-3.11.6.jar!/:3.11.6]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
        ... 17 more
```

I have checked the dependencies inside the jar and I could find a nested dependency in the lib folder "./BOOT-INF/lib/hibernate-core-5.4.10.Final.jar".

I found the issue [2430](https://github.com/redisson/redisson/issues/2430), but in my case, all dependencies belongs to the same module.

What I'm missing?

Thanks in advance, Alan

**Comment by AlanPrado** [comment]
I found the issue, it seems that the thread was not handle by spring context.

Change from:
```
    public void initAsyncTask() {
         CompletableFuture.supplyAsync(() ->  doStuff());
    }
```

To:
```
    @Async
    public void initAsyncTask() {
        doStuff();
    }
```
