### ISSUE TITLE
spring data redis to redisson api

### ISSUE THREAD

**Issue by materia2021** [redisson/redisson#2583]
I've recently used spring-data redis and planning to move to redisson without spring.

How do I migrate this snippet of codes to redisson without flushing / reinserting my previous data.

`@RedisHash("client")
public class Client implements Serializable {

	@Id
	@Indexed
	private String id;
	@Indexed
	private String computerName;
	@Indexed
	private String ipAddress;

}`

`
PagingAndSortingRepository.findAll()
`

I tried using RSet but it throws an NPE

`
RSet<Client> rSet = client.getSet("client");
     rSet.forEach(c -> {
          System.out.println(c.toString());
});`

Unable to decode data. channel: [id: 0x5ea156f1, L:/127.0.0.1:62502 - R:localhost/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=58, widx=58), command: (SSCAN), params: [client, 0, COUNT, 10]

java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at 
`

**Comment by mrniko** [comment]
Redisson uses FSTCodec by default and I assume you used different codec for object stored with spring data. Try to use StringCodec or BinaryCodec.

**Comment by materia2021** [comment]
> 
> 
> Redisson uses FSTCodec by default and I assume you used different codec for object stored with spring data. Try to use StringCodec or BinaryCodec.

Thanks for the reply, but I didn't set any codec so I think it's safe to say that I used the default codec of spring data.

I tried all the available codecs for Redisson but none of them work.
It either throws Parse or Cast Class Exception

**Comment by mrniko** [comment]
I'm afraid reinserting is the only way then.
