### ISSUE TITLE
JCacheEventCodec fails to read class name causing ClassNotFoundException

### ISSUE THREAD

**Issue by rchigvintsev** [redisson/redisson#2593]
Hi! Thanks for your work! I'm pretty new to this client and now trying to understand how it should be configured.
I'm using single node of Redis (5.0.7) with Redisson 3.12.1 and keep getting an error:

```
org.redisson.client.handler.CommandPubSubDecoder,[redisson-netty-2-26:]  Unable to decode data. channel: [id: 0x21b2c047, L:/127.0.0.1:63365 - R:127.0.0.1/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=1060, widx=3729)
java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME: loader:ParallelWebappClassLoader
```
As you can see classname is an empty string. Here is the full stacktrace:
```
at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar:?]
at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250) ~[redisson-3.12.1.jar:3.12.1]
at org.redisson.jcache.JCacheEventCodec$1.decode(JCacheEventCodec.java:51) ~[redisson-3.12.1.jar:3.12.1]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368) ~[redisson-3.12.1.jar:3.12.1]
at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412) ~[redisson-3.12.1.jar:3.12.1]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377) ~[redisson-3.12.1.jar:3.12.1]
at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:76) ~[redisson-3.12.1.jar:3.12.1]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[redisson-3.12.1.jar:3.12.1]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:91) ~[redisson-3.12.1.jar:3.12.1]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
Looking at the source code of `JCacheEventCodec` I noticed that it reads length of key differently depending on the platform. I'm running Java on Windows machine while Redis is on Linux. Now I want to figure out is it a bug or am I doing something in a wrong way?

BTW I tried to rebuild Redisson with reading key length as long (as if it was Linux or Mac) and the error disappeared.

**Comment by mrniko** [comment]
> BTW I tried to rebuild Redisson with reading key length as long (as if it was Linux or Mac) and the error disappeared.

Duplicated with https://github.com/redisson/redisson/issues/2588

**Comment by rchigvintsev** [comment]
@mrniko 
Thank you for response! I've just tested version 3.12.2 and unfortunately nothing changed.

**Comment by mrniko** [comment]
Where did you deploy Redis?

**Comment by mrniko** [comment]
`readLongLE` is correct method for Linux.

**Comment by rchigvintsev** [comment]
Redis is deployed in Ubuntu which in its turn is running on Windows 10 as an application. Java VM is running on Windows, not on Linux.

**Comment by mrniko** [comment]
Could you connect to redis through redis-cli and execute INFO SERVER command? Please share output then

**Comment by rchigvintsev** [comment]
Here is the output:

# Server
redis_version:5.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:1e63cf681bd3cc1b
redis_mode:standalone
os:Linux 4.4.0-17134-Microsoft x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.4.0
process_id:191
run_id:cfb2b3483d9f178c897457946d38fe4cf42136c3
tcp_port:6379
uptime_in_seconds:37
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:4987402
executable:/home/rchigvintsev/redis-stable/src/./redis-server
config_file:

**Comment by mrniko** [comment]
`Linux 4.4.0-17134-Microsoft x86_64`

Who would belive in that core name 10 years ago... Anyway, which method works for it, readLong?

**Comment by rchigvintsev** [comment]
Yea :) And yes, it seems `readLongLE` works.
