### ISSUE TITLE
`addAndGet` operation fail on `RMap` with write-behind mode enabled

### ISSUE THREAD

**Issue by 9you** [redisson/redisson#2600]
We have some counter stored in RMap (LongCodec) so `addAndGet` operation is used. Unfortunately, following exception thrown when MapWriteBehindTask is invoked.

```
2020-02-20 06:06:12.708  WARN 2817 --- [sson-netty-2-13] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$652/251788397.operationComplete()

java.lang.IllegalArgumentException: java.io.IOException: java.lang.RuntimeException: Class org.redisson.misc.RedissonPromise does not implement Serializable or externalizable
	at org.redisson.RedissonObject.encode(RedissonObject.java:300)
	at org.redisson.RedissonList.addAsync(RedissonList.java:123)
	at org.redisson.RedissonList.addAsync(RedissonList.java:119)
	at org.redisson.RedissonList.add(RedissonList.java:114)
	at org.redisson.MapWriteBehindTask.addTask(MapWriteBehindTask.java:123)
	at org.redisson.RedissonMap.lambda$mapWriterFuture$5(RedissonMap.java:361)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:482)
	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:475)
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:460)
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:446)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:164)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:444)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:439)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.lang.RuntimeException: Class org.redisson.misc.RedissonPromise does not implement Serializable or externalizable
	at org.redisson.codec.FstCodec$2.encode(FstCodec.java:279)
	at org.redisson.RedissonObject.encode(RedissonObject.java:298)
	... 53 common frames omitted
Caused by: java.lang.RuntimeException: Class org.redisson.misc.RedissonPromise does not implement Serializable or externalizable
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:144)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:369)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectFields(FSTObjectOutput.java:664)
	at org.nustaq.serialization.FSTObjectOutput.defaultWriteObject(FSTObjectOutput.java:546)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:458)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:204)
	at org.redisson.codec.FstCodec$2.encode(FstCodec.java:271)
	... 54 common frames omitted
```

**Steps to reproduce or test case**
```
public class MapAddAndGetTest {

    @Test
    public void testEntrySet() throws InterruptedException, ExecutionException {
        Map<Long, Long> storage = new HashMap<>();
        storage.put(1L, 1L);
        storage.put(2L, 2L);
        storage.put(3L, 3L);
        
        RMap<Long, Long> map = getWriteBehindTestMap("test", storage);

        map.addAndGetAsync(1L, 10L).get();
    }
    
    protected <K, V> MapWriter<K, V> createMapWriter(Map<K, V> map) {
        return new MapWriter<K, V>() {

            @Override
            public void write(Map<K, V> values) {
                map.putAll(values);
                System.out.println("map " + map);
            }

            @Override
            public void delete(Collection<K> keys) {
                for (K key : keys) {
                    map.remove(key);
                }
                System.out.println("delete " + keys + " map " + map);
            }
            
        };
    }
    
    protected <K, V> MapLoader<K, V> createMapLoader(Map<K, V> map) {
        return new MapLoader<K, V>() {
            @Override
            public V load(K key) {
                return map.get(key);
            }

            @Override
            public Iterable<K> loadAllKeys() {
                return map.keySet();
            }
        };
    }
    
    protected <K, V> RMap<K, V> getWriteBehindTestMap(String name, Map<K, V> map) {
        MapOptions<K, V> options = MapOptions.<K, V>defaults()
                                    .writer(createMapWriter(map))
                                    .writeMode(WriteMode.WRITE_BEHIND);
        return redisson.getMap(name, LongCodec.INSTANCE, options);        
    }

}
```

**Redis version**
3.2.12

**Redisson version**
3.12.2

**Redisson configuration**
`codec: !<org.redisson.codec.FstCodec> {}`

**Comment by 9you** [comment]
My temporary workaround look like this:
```
    public RFuture<V> addAndGetAsync(K key, Number value) {
        checkKey(key);
        checkValue(value);
        
        RFuture<V> future = addAndGetOperationAsync(key, value);
        if (hasNoWriter()) {
            return future;
        }
        
        RPromise<V> result = new RedissonPromise<>();
        future.onComplete((res, e) -> {
            if (e != null) {
                result.tryFailure(e);
                return;
            }
            
            RFuture<V> writeFuture = mapWriterFuture(future, new MapWriterTask.Add(key, res));

            writeFuture.onComplete((wRes, wE) -> {
                if (wE != null) {
                    result.tryFailure(wE);
                }
                result.trySuccess(wRes);
            });
        });

        return result;
    }
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
