### ISSUE TITLE
ERR unknown command 'AUTH' while connecting sentinel

### ISSUE THREAD

**Issue by wenzhizhang** [redisson/redisson#2621]
Hi,
We met below exception in Redisson 3.12.2, could you please help have a check?
```
2020-03-02-T06:00:10.148+0200 | clab847node12 | | ne3sws-ping-consumer | ERROR | org.redisson.connection.SentinelConnectionManager | Exception occurred:
org.redisson.client.RedisConnectionException: Unable to connect to: redis://clab847node12:26379
        at org.redisson.client.RedisClient.connect(RedisClient.java:162) ~[?:?]
        at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:108) ~[?:?]
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:198) ~[?:?]
        at org.redisson.Redisson.<init>(Redisson.java:59) ~[?:?]
        at org.redisson.Redisson.create(Redisson.java:99) ~[?:?]
        at com.nokia.oss.ne3sws.data.repo.cache.RedissionFactory.getOrCreateRedissonClient(RedissionFactory.java:57) ~[?:?]
        at com.nokia.oss.ne3sws.data.repo.cache.RedissionFactory.getRedissonClient(RedissionFactory.java:81) ~[?:?]
        at com.nsn.oss.mf.mediation.ne3sws.ping.consumer.PingTaskConsumer.consume(PingTaskConsumer.java:66) ~[?:?]
        at com.nsn.oss.mf.mediation.ne3sws.ping.consumer.PingTaskConsumer.lambda$start$1(PingTaskConsumer.java:53) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: org.redisson.client.RedisException: ERR unknown command 'AUTH'. channel: [id: 0x3a7ae6cd, L:/10.32.236.132:34692 - R:clab847node12/10.32.236.132:26379] command: (AUTH), params: [******]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[?:?]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]

```
There is a small change in MasterSlaveConnectionManager.createRedisConfig() against Redisson 3.10.1:

3.10.1:
```
    if (type != NodeType.SENTINEL)
    {
      redisConfig.setDatabase(this.config.getDatabase());
      redisConfig.setPassword(this.config.getPassword());
    }
```

3.12.2:
```
        if (type != NodeType.SENTINEL) {
            redisConfig.setDatabase(this.config.getDatabase());
        }
```
Is this change relevant?

**Comment by mrniko** [comment]
What Redis version do you use?

**Comment by mrniko** [comment]
> Is this change relevant?

Yes, since 5.0 version. Sentinel support auth by password.

**Comment by wenzhizhang** [comment]
Hi,
Thanks for feedback. 
redis-server --version
Redis server v=4.0.10 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=aea1c0d1e5faccb6

So when the password is added to the configuration, is command "AUTH" always executed when connecting sentinel?

**Comment by mrniko** [comment]
it's used only if PING command to this server throws "auth required" error

https://github.com/redisson/redisson/blob/6e1bafdb23da5e13caa4182bad8da220cfa2cc40/redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java#L192

**Comment by mrniko** [comment]
Unable to reproduce error with Redis 4.0.14
