### ISSUE TITLE
ARGV[1] get nil when run lua script  through redissonClient.getScript().eval()

### ISSUE THREAD

**Issue by TonyLuo** [redisson/redisson#2627]
**Expected behavior**

**Actual behavior**
```
2020-03-09 14:29:00.710 ERROR 3220 --- [  XNIO-1 task-1] c.b.warehouse.aop.logging.LoggingAspect  : Exception in com.boss.warehouse.service.StockService.decrease() with cause = 'NULL' and exception = 'ERR Error running script (call to f_831aef7dfc7feb389c8650a16fce035ad2ea1820): @user_script:1: user_script:1: attempt to compare number with nil . channel: [id: 0xdfd95d2a, L:/192.168.35.12:63350 - R:192.168.0.167/192.168.0.167:6379] command: (EVAL), params: [ if (redis.call('exists', KEYS[1]) == 1) then      local stock_qty = tonumber(redis.call('get', KEYS..., 2, Stock:2:325, -5, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 256)]'

org.redisson.client.RedisException: ERR Error running script (call to f_831aef7dfc7feb389c8650a16fce035ad2ea1820): @user_script:1: user_script:1: attempt to compare number with nil . channel: [id: 0xdfd95d2a, L:/192.168.35.12:63350 - R:192.168.0.167/192.168.0.167:6379] command: (EVAL), params: [ if (redis.call('exists', KEYS[1]) == 1) then      local stock_qty = tonumber(redis.call('get', KEYS..., 2, Stock:2:325, -5, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 256)]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-03-09 14:29:00.723 ERROR 3220 --- [  XNIO-1 task-1] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.redisson.client.RedisException: ERR Error running script (call to f_831aef7dfc7feb389c8650a16fce035ad2ea1820): @user_script:1: user_script:1: attempt to compare number with nil . channel: [id: 0xdfd95d2a, L:/192.168.35.12:63350 - R:192.168.0.167/192.168.0.167:6379] command: (EVAL), params: [ if (redis.call('exists', KEYS[1]) == 1) then      local stock_qty = tonumber(redis.call('get', KEYS..., 2, Stock:2:325, -5, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 256)]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-03-09 14:29:01.062  WARN 3220 --- [  XNIO-1 task-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.redisson.client.RedisException: ERR Error running script (call to f_831aef7dfc7feb389c8650a16fce035ad2ea1820): @user_script:1: user_script:1: attempt to compare number with nil . channel: [id: 0xdfd95d2a, L:/192.168.35.12:63350 - R:192.168.0.167/192.168.0.167:6379] command: (EVAL), params: [ if (redis.call('exists', KEYS[1]) == 1) then      local stock_qty = tonumber(redis.call('get', KEYS..., 2, Stock:2:325, -5, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 256)]]

```
**Steps to reproduce or test case**
```
  private Long changeStockQty(int quantity) {
        String key = "testLuaScriptKey";
        List<Object> params =Arrays.asList(quantity);
        String luaScript =
            " if (redis.call('exists', KEYS[1]) == 1) then " +
                "     local stock_qty = tonumber(redis.call('get', KEYS[1]));" +
                "     local quantity = tonumber(ARGV[1]);" +
                "     if (quantity > 0) then " +
                "         return redis.call('incrby', KEYS[1],  quantity);" +
                "     end;" +
                "     if (stock_qty >= (0 - quantity)) then" +
                "         return redis.call('incrby', KEYS[1],  quantity);" +
                "     end;" +
                "     return -1;" +
                " end;" +
                " return -2;";
        return redissonClient.getScript().eval(RScript.Mode.READ_WRITE,
            luaScript,
            RScript.ReturnType.VALUE,
            Arrays.asList(key,quantity),
            params.toArray());
    }
```
**Redis version**

**Redisson version**
3.12.3
**Redisson configuration**

**Comment by mrniko** [comment]
ARGV[1] can't be converted to number since it was serialized by default binary FstCodec. You need to use LongCodec or StringCodec instead: 

```java
redissonClient.getScript(LongCodec.INSTANCE);
```

**Comment by TonyLuo** [comment]
it works. thanks

**Comment by tavin** [comment]
what's the fastest codec that can handle both Long and String in the script arguments?
