### ISSUE TITLE
java.io.IOException: Failed to read the next byte

### ISSUE THREAD

**Issue by jansonlow** [redisson/redisson#2643]
Hi,

I've run into the following exception and searching online does not yield any useful information. This is a Springboot app and the following is the config:

`private RedissonClient getElastiCacheClient() {
        if (redissonClient == null) {
            log.info("Creating Redisson client, connecting to Redis: {}", redisEndpoint);
            Config config = new Config();
            config.useReplicatedServers()
                    .setScanInterval(2000)
                    .addNodeAddress(redisEndpoint)
                    .setReadMode(ReadMode.SLAVE);
            redissonClient = Redisson.create(config);
        }

        return redissonClient;
    }

    @Bean
    @Qualifier("tableOne")
    public RMapCache<String, String> tableOne() {
        log.info("Intializing tableOne...");
        return getElastiCacheClient().getMapCache("tableOne");
    }

    @Bean
    @Qualifier("tableTwo")
    public RMapCache<String, MyAppRequest> tableTwo() {
        log.info("Intializing tableTwo...");
        return getElastiCacheClient().getMapCache("tableTwo");
    }`

We have multiple apps that are using tableOne and tableTwo, some writes some reads/writes. Each app has multiple instances.

This exception happens after the initialization of tableTwo. TableOne has always been fine. We are able to circumvent this by doing tableTwo().clear() during startup but the following error returns when it is being used. Has anyone run into this issue before or have any guess/insight of what's going on?

ERROR 2020-03-19 14:11:13,346 [redisson-netty-2-17] org.redisson.client.handler.CommandDecoder app=myApp version=2.0.1.0 : Unable to decode data. channel: [id: 0x110ba4d5, L:/172.31.57.100:38648 - R:my-app.eq0m8j.ng.0001.use1.cache.amazonaws.com/172.31.50.140:6379], reply: ReplayingDecoderByteBuf(ridx=165, widx=165), command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, MyAppTable, redisson__timeout__set:{MyAppTable}, redisson__idle__set:{MyAppTable}, redisson__map_cache__last_access__set:{MyAppTable}, {MyAppTable}:redisson_options, 1584627073343, PooledUnsafeDirectByteBuf(ridx: 0, widx: 11, cap: 256)]
java.io.IOException: java.io.IOException: java.io.IOException: Failed to read the next byte
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar!/:?]
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:228) ~[redisson-3.11.0.jar!/:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384) ~[redisson-3.11.0.jar!/:?]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215) ~[redisson-3.11.0.jar!/:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153) ~[redisson-3.11.0.jar!/:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122) ~[redisson-3.11.0.jar!/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar!/:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.36.Final.jar!/:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.io.IOException: java.io.IOException: Failed to read the next byte
	at org.redisson.codec.FstCodec$FSTDefaultStreamCoderFactory$1.readStringUTF(FstCodec.java:145) ~[redisson-3.11.0.jar!/:?]
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:168) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar!/:?]
	... 24 more
Caused by: java.io.IOException: Failed to read the next byte
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFByte(FSTStreamDecoder.java:294) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFInt(FSTStreamDecoder.java:252) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.coders.FSTStreamDecoder.readStringUTF(FSTStreamDecoder.java:77) ~[fst-2.57.jar!/:?]
	at org.redisson.codec.FstCodec$FSTDefaultStreamCoderFactory$1.readStringUTF(FstCodec.java:141) ~[redisson-3.11.0.jar!/:?]
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:168) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar!/:?]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar!/:?]
	... 24 more

**Comment by mrniko** [comment]
Hi,

make shure you don't share the same name with different type of objects. Is there any code sample to reproduce it?

**Comment by jansonlow** [comment]
Do you mean using the same table to store different type of objects? It was in test tableTwo started off storing <String,String> and later on <String,Object>. We did flushall and also did table.clear() though. The code I included was it. interacting with tableTwo triggers the exception. Most of the time right after initialization we see the exception.

**Comment by mrniko** [comment]
I mean to check if the same name shared with any different Redisson object.
