### ISSUE TITLE
Question about PingConnectionInterval and KeepAlive

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#2647]
Redisson: 3.12.1
Java: 1.8

In production we saw below error few times. As per some closed issues if we set `pingConnectionInterval`, will the excess idle connections be closed after `idleConnectionTimeout` ? 
And also enabling `KeepAlive` solved the issue for any? 

```
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:230:queue:0, freezed=false, freezeReason=null, client=[addr=redis://<removed>:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1929783894 [redisClient=[addr=redis://<removed>:6379], channel=[id: 0x3a9bcda0, L:/<<removed>>:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@63c1de5f(success)], command=(BLPOP), params=[userqueue2, 60], codec=org.redisson.client.codec.StringCodec]], command: (BLPOP), params: [userqueue2, 60] after 3 retry attempts
    at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:280)
    at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:60)
    at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:162)
    at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:159)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
    at org.redisson.client.handler.CommandsQueue.channelInactive(CommandsQueue.java:83)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
```

```
Config config = new Config();
		config.setCodec(StringCodec.INSTANCE);
		
		ReplicatedServersConfig replicatedServersConfig = config.useReplicatedServers()
				.setScanInterval(2000) 
				.setReadMode(READ_MODE) 
				.setTimeout(CacheConstants.TIMEOUT) 
				.setMasterConnectionPoolSize(CacheConstants.MAX_TOTAL_CONNECTIONS)
				.setSlaveConnectionPoolSize(CacheConstants.SLAVE_MAX_TOTAL_CONNECTIONS);
```

**Comment by mrniko** [comment]
> As per some closed issues if we set pingConnectionInterval, will the excess idle connections be closed after idleConnectionTimeout ?

Yes, idle connections will be closed even with `pingConnectionInterval` setting.

> And also enabling KeepAlive solved the issue for any?

It's worth to try it.

**Comment by rgampa** [comment]
Thanks @mrniko for quick reply.

**Comment by rgampa** [comment]
Hi @mrniko , after enabling `pingConnectionInterval` with 3 sec, we see below warnings in production, I think Redisson is trying submit PING command on the connection blocked by `BLPOP`. Is there a way to not submit the PING command on a busy connection or suppress the WARN log to be printed? 

``` 
{"timestamp":"2020-03-23T19:59:14.022-0400","level":"WARN","thread":"redisson-netty-24-23","logger":"org.redisson.client.handler.CommandDecoder","message":"response has been skipped due to timeout! channel: [id: 0x63b7887b, L:/<removed>:57810 - R:<removed>/<removed>:6379], command: (PING), params: []","context":"default"}
```

**Comment by mrniko** [comment]
this issue was already fixed in https://github.com/redisson/redisson/issues/1855 which version do you use in production?

**Comment by rgampa** [comment]
Hi @mrniko, due to this PING timeout exception on busy connection, will redisson mark the respective connection as bad, and destroy it? 
And also when we receive `WriteRedisConnectionException` even after 3 default retries, will redisson destroy the respective connection in the pool? After setting `pingConnectionInterval` to 3 sec, I saw this exception couple of times in production.

**Comment by mrniko** [comment]
Closed channel is reconnected automatically.

**Comment by mrniko** [comment]
Fixed
