### ISSUE TITLE
RedissonBoundedBlockingQueue drainTo method got infinite hung

### ISSUE THREAD

**Issue by empty117** [redisson/redisson#2651]
**Expected behavior**
RedissonBoundedBlockingQueue drainTo method will return result.

**Actual behavior**

RedissonBoundedBlockingQueue drainTo method got infinite hung.

"ne3sws-ping-consumer" Id=368 WAITING on io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise@72e4e41f
  CPU time=14.375 secs, USER time=9.47 secs, MEMORY allocation=397318568 bytes
  Java callstack:
        at java.lang.Object.wait(Native Method)
        -  waiting on io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise@72e4e41f
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:252)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:142)
        at org.redisson.RedissonObject.get(RedissonObject.java:90)
        at org.redisson.RedissonBoundedBlockingQueue.drainTo(RedissonBoundedBlockingQueue.java:298)
        at com.nsn.oss.mf.mediation.ne3sws.ping.consumer.PingTaskConsumer.consume(PingTaskConsumer.java:69)
        at com.nsn.oss.mf.mediation.ne3sws.ping.consumer.PingTaskConsumer.lambda$start$1(PingTaskConsumer.java:53)
        at com.nsn.oss.mf.mediation.ne3sws.ping.consumer.PingTaskConsumer$$Lambda$88/1358833464.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@4d8bb13b

**Steps to reproduce or test case** Unknown/..

**Redis version** any

**Redisson version** 3.12.2

**Redisson configuration** 3 Sentinels + 1M+1S

**Comment by empty117** [comment]
Get operation on other object got hung as well:

"thread-571" Id=133899 WAITING on io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise@2126ad9b
  CPU time=0.584 secs, USER time=0.45 secs, MEMORY allocation=72017416 bytes
  Java callstack:
        at java.lang.Object.wait(Native Method)
        -  waiting on io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise@2126ad9b
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:252)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:142)
        at org.redisson.RedissonObject.get(RedissonObject.java:90)
        at org.redisson.RedissonMap.get(RedissonMap.java:267)

**Comment by mrniko** [comment]
Do you use any async methods in your code? or any listeners?

**Comment by empty117** [comment]
All netty threads and redisson threads are in some state, like below:

"redisson-netty-2-1" Id=356 RUNNABLE (in native)
  CPU time=403.848 secs, USER time=250.88 secs, MEMORY allocation=7690601680 bytes
  Java callstack:
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@29d9a769
	-  locked java.util.Collections$UnmodifiableSet@28e559bd
	-  locked sun.nio.ch.EPollSelectorImpl@4e4e641e
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:807)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

"redisson-3-3" Id=2512 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5279861c
  CPU time=2.681 secs, USER time=1.89 secs, MEMORY allocation=145946216 bytes
  Java callstack:
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5279861c
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by empty117** [comment]
Yes, we used async method and listener on one RMapCache object:
- getAllAsync
- containsKeyAsync
- fastPutAsync

Meanwhile, another JAVA process(Also using Redisson) executed clear on this RMapCache, that equals DEL on Redis map,

**Comment by empty117** [comment]
I can share full thread dump with mail(Not willing to post on github by company policy), Please share your mail address.

**Comment by mrniko** [comment]
Please make sure that all calls in async listeners are non-blocking.

**Comment by empty117** [comment]
I don't see any blocking operation in async listener,  and now all netty threads are in epollWait state like i shared before.

**Comment by mrniko** [comment]
I already faced similar issue and problem was that async listener blocks netty-thread since it executed by this thread.

**Comment by empty117** [comment]
@mrniko : could you share your mail address? i can send threaddump..

**Comment by mrniko** [comment]
@empty117 

Here it is: tbewqeh@wootap.me

**Comment by empty117** [comment]
@mrniko  Dump was sent, plz help to check.

**Comment by mrniko** [comment]
I didn't receive it.

**Comment by mrniko** [comment]
Could you attach it to issue?

**Comment by empty117** [comment]
[threadDump.zip](https://github.com/redisson/redisson/files/4379426/threadDump.zip)

**Comment by empty117** [comment]
@mrniko : attached, please let me know after you downloaded it, i will delete it after you got, thanks

**Comment by mrniko** [comment]
Thank you! Could you share Redisson configuration as well?

**Comment by empty117** [comment]
sentinelServersConfig:
  #If pooled connection not used for a timeout time and current connections amount bigger than minimum idle connections pool size, then it will closed and removed from pool. Value in milliseconds
  idleConnectionTimeout: 10000
  #Timeout in milliseconds during connecting to any Redis server
  connectTimeout: 10000
  #Redis server response timeout in milliseconds. Starts to countdown when Redis command was successfully sent.
  timeout: 5000
  #Error will be thrown if Redis command can't be sended to Redis server after retryAttempts. But if it sent successfully then timeout will be started.
  retryAttempts: 3
  #Time interval in milliseconds after which another one attempt to send Redis command will be executed
  retryInterval: 1500
  #password can be runtime changed
  password: "Tbrz+...="
  #Subscriptions per Redis connection limit.
  subscriptionsPerConnection: 5
  clientName: "client"
  #Minimum idle subscription (pub/sub) connection amount for each slave node
  subscriptionConnectionMinimumIdleSize: 1
  #Maximum subscription (pub/sub) connection pool size for each slave node
  subscriptionConnectionPoolSize: 50
  #Redis 'slave' node minimum idle connection amount for each slave node
  slaveConnectionMinimumIdleSize: 1
  #Redis 'slave' node maximum connection pool size for each slave node
  slaveConnectionPoolSize: 1
  #Redis 'master' node minimum idle connection amount for each master node
  masterConnectionMinimumIdleSize: 32
  #Redis 'master' node maximum connection pool size
  masterConnectionPoolSize: 256
  #NetAct redis server default masterName
  masterName: "master"
  #All read/write go to master only to keep data consistency
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  #sentinel address could be replaced at installation/upgrade/scaling time
  sentinelAddresses:
  - "redis://sentinel1:26379"
  - "redis://sentinel16:26379"
  - "redis://sentile17:26379"
threads: 0
nettyThreads: 0
#default
codec: !<org.redisson.codec.JsonJacksonCodec> {}
#default java NIO implementation
transportMode: "NIO"

**Comment by mrniko** [comment]
Thank you! What is the netty version you use?

**Comment by empty117** [comment]
@mrniko :it's 4.1.45

**Comment by mrniko** [comment]
how often does this issue happen? Is there any conditions?

**Comment by empty117** [comment]
Sorry i didn't find how to reproduce it, and the condition is not clear, it happened only one time...

**Comment by mrniko** [comment]
How many days application was online before this issue happened?

**Comment by empty117** [comment]
about 1 day.

**Comment by mrniko** [comment]
Do you see any exceptions in logs?

**Comment by mrniko** [comment]
Any update?
