### ISSUE TITLE
 Unable to decode data...InvalidDefinitionException..Collections$SetFromMap..no Creators

### ISSUE THREAD

**Issue by cloudswindow** [redisson/redisson#2654]
- tomcat8
- codec: org.redisson.codec.JsonJacksonCodec
- readMode: MEMORY
- updateMode: AFTER_REQUEST
- redisson-tomcat-8-3.12.2.jar
- redisson-all-3.12.2.jar

error stack :

``` 
[redisson-netty-2-28] ERROR org.redisson.client.handler.CommandPubSubDecoder - Unable to decode data. channel: [id: 0x3c021770, L:/10.0.0.85:52584 - R:r-8vbjwkx5e2lpm7j5ws.redis.zhangbei.rds.aliyuncs.com/10.0.0.126:6379], reply: ReplayingDecoderByteBuf(ridx=271, widx=271)
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.util.Collections$SetFromMap` (no Creators, like default construct, exist): no default no-arguments constructor found
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 100] (through reference chain: org.redisson.tomcat.AttributeRemoveMessage["names"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	...

	... 
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:95)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:76)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:91)
```

So i saw the source of 

> RedissonSession.java

 :

![image](https://user-images.githubusercontent.com/813633/77735780-1a54ad00-7046-11ea-9518-9de7f4f51ba2.png)

![image](https://user-images.githubusercontent.com/813633/77735796-1fb1f780-7046-11ea-9307-893d421308ff.png)

The class SetFromMap of Collections don't have no args construct method....
how can i fixed this .
Thx

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by cloudswindow** [comment]
Thx，so how long i have to wait for 3.12.4...
