### ISSUE TITLE
Redisson error when create client

### ISSUE THREAD

**Issue by DayZerd** [redisson/redisson#2662]
Hello, when I create a client I have an error with netty...
`java.lang.NoSuchMethodError: io.netty.util.NetUtil.isIpV4StackPreferred()Z
        at io.netty.resolver.dns.DnsNameResolver.<clinit>(DnsNameResolver.java:119) ~[?:?]
        at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:52) ~[?:?]
        at io.netty.resolver.dns.DnsAddressResolverGroup.<init>(DnsAddressResolverGroup.java:56) ~[?:?]
        at org.redisson.connection.DnsAddressResolverGroupFactory.create(DnsAddressResolverGroupFactory.java:33) ~[?:?]
        at org.redisson.connection.DnsAddressResolverGroupFactory.create(DnsAddressResolverGroupFactory.java:28) ~[?:?]
        at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:211) ~[?:?]
        at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:163) ~[?:?]
        at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:34) ~[?:?]
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:195) ~[?:?]
        at org.redisson.Redisson.<init>(Redisson.java:59) ~[?:?]
        at org.redisson.Redisson.create(Redisson.java:99) ~[?:?]`

The code:
`private void redis(){
        Config config = new Config();
        config.useSingleServer().setAddress("redis://127.0.0.1:6379");
        RedissonClient redisson = Redisson.create(config);
}`
I use the last version of redisson

**Comment by mrniko** [comment]
Check netty version in classpath. Seems you have old one or two different versions
