### ISSUE TITLE
ERROR reactor.core.scheduler.Schedulers:319 : Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by jiang890910bo** [redisson/redisson#2681]
I had use the version:
compile group: 'org.redisson', name: 'redisson-spring-boot-starter', version: '3.12.4',.
The Questions :
 2020-04-07 22:27:34.275 [parallel-4] ERROR reactor.core.scheduler.Schedulers:319 : Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: org/springframework/data/redis/connection/ReactiveStreamCommands
        at org.redisson.spring.data.connection.RedissonConnectionFactory.getReactiveConnection(RedissonConnectionFactory.java:149)
        at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:56)
        at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
        at reactor.core.publisher.Mono.subscribe(Mono.java:3882)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:123)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.springframework.data.redis.connection.ReactiveStreamCommands
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 common frames omitted

**Comment by mrniko** [comment]
Make sure you have latest version of spring-data-redis in dependency. https://github.com/redisson/redisson/tree/master/redisson-spring-data#1-add-redisson-spring-data-dependency-into-your-project
