### ISSUE TITLE
publish  message  throw exception

### ISSUE THREAD

**Issue by boot-vue** [redisson/redisson#2687]
rtopic  can  receive message,  but throw exception on publish message  every time.

```bash
spring-boot: 2.1.2.RELEASE
redisson-spring-boot-starter: 3.11.5
```

```java
 RTopic rTopic = redissonClient.getTopic("xxx");
        rTopic.addListener(Long.class, (channel, msg) -> {
            log.info("收到消息: {}", msg);
        });


-------------------

 RTopic rTopic = redissonClient.getTopic("xxx");
rTopic.publishAsync(System.currentTimeMillis());

```

```java
Exception in thread "redisson-3-11" java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@71f5bc7c has been closed already
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1067)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1100)
        at group.xxxx.SpringUtil.getBean(SpringUtil.java:51)
        at group.xxxx.handleMsg(RedissonMq.java:73)
        at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
        at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:78)
        at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$0(CommandPubSubDecoder.java:184)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "redisson-3-17" Exception in thread "redisson-3-3" java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1c08adcb has been closed already
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1067)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1100)
        at group.xxx.SpringUtil.getBean(SpringUtil.java:51)
        at group.xxx.handleMsg(RedissonMq.java:73)
        at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
        at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:78)
        at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$0(CommandPubSubDecoder.java:184)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1
        at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:293)
Exception in thread "redisson-3-7"      at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:460)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:430)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:422)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:279)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:270)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:241)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:450)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:426)
        at io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:271)
        at io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:32)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@55d9ff04 has been closed already
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1067)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1100)
        at group.xxx.SpringUtil.getBean(SpringUtil.java:51)
        at group.xxxx.handleMsg(RedissonMq.java:73)
        at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
        at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:78)
        at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$0(CommandPubSubDecoder.java:184)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "redisson-3-1" java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1dc92408 has been closed already
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1067)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1100)
        at group.xxx.SpringUtil.getBean(SpringUtil.java:51)
        at group.xxx.handleMsg(xxx.java:73)
        at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
        at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:78)
        at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$0(CommandPubSubDecoder.java:184)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by boot-vue** [comment]
if message  Object  is basic class  such as  integer , long.....,  no exception.

but  other class it throw exception. shuch  as: 

```java
public class CustMsg implements Serializable {

    private static final long serialVersionUID = 9134649686694856723L;

    private Long id;
    private s String name;
    private String key; 

....getter settter
}
```



publish( CustMsg  )  ---> throw  exception

**Comment by boot-vue** [comment]
spring boot  2.2.6.RELEASE
redisson-spring-boot-starter  3.12.4   

there  is  no  such problem

**Comment by mrniko** [comment]
> org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@71f5bc7c has been closed already

Seems problem in a closed application context

**Comment by boot-vue** [comment]
throgh  this  way,  it  can  run  normal  and   don't  throw  exception.

I guess the problem  is  exist  two different  way  to  seriaize object  in my  code

redistemplate I use fastjson  to  serialize object,  and  redissonClient I used default jsckson serialize.

```java
 rTopic.addListener(String.class, (channel, msg) -> {
            XXX message = JSON.parseObject(msg, XXX.class);
            log.info("收到消息: {}", message);
        });



      XXX message = new XXX(....);
      rTopic.publishAsync(JSON.toJSONString(message));
```
