### ISSUE TITLE
Simplifying debugging of sentinel connection problems

### ISSUE THREAD

**Issue by thoraage** [redisson/redisson#2699]
**Is your feature request related to a problem? Please describe.**

Yes; it's a problem. It's difficult to debug connection problems when connecting to sentinel servers fails. Example log below. When each sentinel node connection fails, a small warning with no stack trace and real error message is emitted. When finally no connection is made a message with list of servers tried is included. We've no information about the actual underlying problem.

`
2020-04-15T10:50:49,472Z WARN  org.redisson.connection.SentinelConnectionManager - Can't connect to sentinel server. Unable to connect to: redis://siggydiggy:26379 
2020-04-15T10:50:51,495Z] ERROR org.redisson.client.RedisConnectionException: Unable to connect to Redis sentinel servers: redis://siggydiggy:26379,
        at org.redisson.connection.SentinelConnectionManager.checkAuth(SentinelConnectionManager.java:235) ~[redisson-3.11.6.jar:3.11.6]
        at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:104) ~[redisson-3.11.6.jar:3.11.6]
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:197) ~[redisson-3.11.6.jar:3.11.6]
        at org.redisson.Redisson.<init>(Redisson.java:120) ~[redisson-3.11.6.jar:3.11.6]
        at org.redisson.Redisson.create(Redisson.java:160) ~[redisson-3.11.6.jar:3.11.6]
 `

**Describe the solution you'd like**

Collect the exceptions in a list and output them with stack traces after it's established that no connection was made.

**Describe alternatives you've considered**

Log stack dumps to INFO or DEBUG.

**Comment by mrniko** [comment]
Fixed
