### ISSUE TITLE
error in RedissonBoundedBlockingQueue

### ISSUE THREAD

**Issue by hellocrest** [redisson/redisson#2706]
when I use this method in project：
`RedissonBoundedBlockingQueue.offer(V e, long timeout, TimeUnit unit)`
I fount some error like this:
`at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "redisson-3-3737" java.lang.Error: Maximum permit count exceeded
at java.base/java.util.concurrent.Semaphore$Sync.tryReleaseShared(Semaphore.java:198)
at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1382)
at java.base/java.util.concurrent.Semaphore.release(Semaphore.java:619)
at org.redisson.pubsub.SemaphorePubSub.onMessage(SemaphorePubSub.java:44)
at org.redisson.pubsub.SemaphorePubSub.onMessage(SemaphorePubSub.java:26)
at org.redisson.pubsub.PublishSubscribe$4.onMessage(PublishSubscribe.java:129)
at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:78)
at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$0(CommandPubSubDecoder.java:184)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)`

seems like the message's value is too large,bug I'm not sure,and I  can't reproduce the error.
`SemaphorePubSub.onMessage(RedissonLockEntry value, Long message)`
**jdk version**
11
**Redisson version**
3.11.5

**Comment by mrniko** [comment]
It's strange to see that, since values are 0 or 1.

**Comment by hellocrest** [comment]
Since the first `tryAcquire(permits)`return false,may be there are some network jitter cause netty sticky package,and the method `SemaphorePubSub.onMessage` receives some value not 0 or 1.
`@Override
    public boolean tryAcquire(int permits, long waitTime, TimeUnit unit) throws InterruptedException {
        long time = unit.toMillis(waitTime);
        long current = System.currentTimeMillis();

        if (tryAcquire(permits)) {
            return true;
        }

        time -= System.currentTimeMillis() - current;
        if (time <= 0) {
            return false;
        }

        current = System.currentTimeMillis();
        RFuture<RedissonLockEntry> future = subscribe();
        if (!future.await(time, TimeUnit.MILLISECONDS)) {
            return false;
        }

        try {
            time -= System.currentTimeMillis() - current;
            if (time <= 0) {
                return false;
            }
            
            while (true) {
                current = System.currentTimeMillis();
                if (tryAcquire(permits)) {
                    return true;
                }

                time -= System.currentTimeMillis() - current;
                if (time <= 0) {
                    return false;
                }

                // waiting for message
                current = System.currentTimeMillis();

                getEntry().getLatch().tryAcquire(permits, time, TimeUnit.MILLISECONDS);

                time -= System.currentTimeMillis() - current;
                if (time <= 0) {
                    return false;
                }
            }
        } finally {
            unsubscribe(future);
        }
//        return get(tryAcquireAsync(permits, waitTime, unit));
    }`

**Comment by mrniko** [comment]
This might caused by issue in FstCodec. MarshallingCodec is now default, which is stable. Use it.

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/3573
