### ISSUE TITLE
org.redisson.client.RedisException: Unexpected exception while processing command

### ISSUE THREAD

**Issue by wuguanyu** [redisson/redisson#2721]

**Comment by wuguanyu** [comment]
How to resolve this issue? . When more requests to redis , Our system always occured this issue

**Comment by mrniko** [comment]
Please share fullstack trace

**Comment by wuguanyu** [comment]
org.redisson.client.RedisException: Unexpected exception while processing command
    at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:338)
    at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:140)
    at org.redisson.RedissonObject.get(RedissonObject.java:90)
    at org.redisson.RedissonList.readAll(RedissonList.java:110)
    at com.shuidihuzhu.common.util.redisson.RedissonHandlerImpl.getList(RedissonHandlerImpl.java:318)
    at com.shuidihuzhu.common.util.redisson.RedissonHandlerImpl$$FastClassBySpringCGLIB$$cdcffef4.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
    at com.shuidihuzhu.eb.grafana.configuration.plugin.redis.RedissonAspect.doAround(RedissonAspect.java:99)
    at jdk.internal.reflect.GeneratedMethodAccessor339.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)

**Comment by wuguanyu** [comment]
org.redisson.client.RedisException: Unexpected exception while processing command
    at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:338)
    at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:140)
    at org.redisson.RedissonObject.get(RedissonObject.java:90)
    at org.redisson.RedissonList.readAll(RedissonList.java:110)

**Comment by wuguanyu** [comment]
org.redisson.command.CommandAsyncService.class    

public <V> RedisException convertException(RFuture<V> future) {
        if (future.cause() instanceof RedisException) {
            return (RedisException) future.cause();
        }
        return new RedisException("Unexpected exception while processing command", future.cause());
    }

 @Override
    public <V> V get(RFuture<V> future) {
        try {
            future.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        if (future.isSuccess()) {
            return future.getNow();
        }

        throw convertException(future);
    }

**Comment by mrniko** [comment]
It's not enought. I need similar size of stacktrace

https://github.com/redisson/redisson/issues/2723#issuecomment-618250500

**Comment by wuguanyu** [comment]
I think it is not real stacktrace

**Comment by wuguanyu** [comment]
@mrniko  This is top line of all stacktrace

**Comment by wuguanyu** [comment]
org.redisson.client.RedisException: Unexpected exception while processing command
    at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:338)
    at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:140)
    at org.redisson.RedissonObject.get(RedissonObject.java:90)
    at org.redisson.RedissonBucket.get(RedissonBucket.java:97)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
    at jdk.internal.reflect.GeneratedMethodAccessor393.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
    at com.shuidihuzhu.cf.enhancer.aop.RedissonHystrixCommand.doRun(RedissonHystrixCommand.java:37)
    at org.springframework.cloud.sleuth.instrument.hystrix.TraceCommand.run$sw(TraceCommand.java:66)
    at org.springframework.cloud.sleuth.instrument.hystrix.TraceCommand.run$sw(TraceCommand.java)
    at org.springframework.cloud.sleuth.instrument.hystrix.TraceCommand$sw.call
    at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
    at org.springframework.cloud.sleuth.instrument.hystrix.TraceCommand.run(TraceCommand.java)
    at com.shuidihuzhu.cf.enhancer.aop.RedissonHystrixCommand.run$sw(RedissonHystrixCommand.java)
    at com.shuidihuzhu.cf.enhancer.aop.RedissonHystrixCommand$sw.call
    at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
    at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
    at org.apache.skywalking.apm.plugin.hystrix.v1.SWHystrixConcurrencyStrategyWrapper$WrappedCallable.call(SWHystrixConcurrencyStrategyWrapper.java:58)
    at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70)
    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)

**Comment by wuguanyu** [comment]
@mrniko

**Comment by mrniko** [comment]
Could you update to the latest version and try it again?

**Comment by wuguanyu** [comment]
@mrniko Our redisson version is 3.11.5 
This issue is caused by this reason

**Comment by mrniko** [comment]
I don't see `Caused by: ` in this exception. It should be right under `at java.lang.Thread.run(Thread.java:834)` line

**Comment by wuguanyu** [comment]
Full stacktrace set above, I can't see any valid real exception info

**Comment by wuguanyu** [comment]
@mrniko  I think it lack  important log  in the following code

return new RedisException("Unexpected exception while processing command", future.cause());

**Comment by wuguanyu** [comment]
We don't see Which is real class implement future

**Comment by wuguanyu** [comment]
@mrniko Thanks for your support, I have already know this problem in which case occured
 Our system use hystrix,We set timeout by ourself, When time  get data from redission  greater than timeout which setted   by ourself, Current thread is be interupted

**Comment by v8sagar** [comment]
@wuguanyu 
I am getting

`
javax.cache.processor.EntryProcessorException: javax.cache.CacheException: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.jcache.JCache.invoke(JCache.java:2857) ~[redisson-3.13.2.jar:3.13.2]
	at io.github.bucket4j.grid.jcache.JCacheProxy.execute(JCacheProxy.java:54) ~[bucket4j-jcache-4.10.0.jar:na]
	at io.github.bucket4j.grid.GridBucket.execute(GridBucket.java:270) ~[bucket4j-core-4.10.0.jar:na]
	at io.github.bucket4j.grid.GridBucket.tryConsumeAndReturnRemainingTokensImpl(GridBucket.java:96) ~[bucket4j-core-4.10.0.jar:na]
	at io.github.bucket4j.AbstractBucket.tryConsumeAndReturnRemaining(AbstractBucket.java:603) ~[bucket4j-core-4.10.0.jar:na]
	at com.enveyo.api.filter.TenantThrottlingFilter.doFilter(TenantThrottlingFilter.java:54) ~[main/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at javax.servlet.FilterChain$doFilter.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[groovy-2.4.13.jar:2.4.13]






Caused by: javax.cache.CacheException: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.jcache.JCache.evalWrite(JCache.java:376) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.jcache.JCache.getValueLocked(JCache.java:229) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.jcache.JMutableEntry.getValue(JMutableEntry.java:63) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.jcache.JMutableEntry.exists(JMutableEntry.java:86) ~[redisson-3.13.2.jar:3.13.2]
	at io.github.bucket4j.grid.jcache.ExecuteProcessor.process(ExecuteProcessor.java:69) ~[bucket4j-jcache-4.10.0.jar:na]
	at io.github.bucket4j.grid.jcache.ExecuteProcessor.process(ExecuteProcessor.java:33) ~[bucket4j-jcache-4.10.0.jar:na]
	at org.redisson.jcache.JCache.invoke(JCache.java:2845) ~[redisson-3.13.2.jar:3.13.2]
	... 113 common frames omitted
Caused by: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:350) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:147) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.RedissonObject.get(RedissonObject.java:90) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.jcache.JCache.evalWrite(JCache.java:374) ~[redisson-3.13.2.jar:3.13.2]
	... 119 common frames omitted`

**Comment by abdulwhd964** [comment]
@mrniko, could you please provide your suggestion on this

**Comment by abdulwhd964** [comment]
im using redisson version 3.20.1 and jackson as 2.17.2
