### ISSUE TITLE
Node not discovered

### ISSUE THREAD

**Issue by smirandamedallia** [redisson/redisson#2732]
Seeing the following exception in logs which results in command failure:
```
org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=15299, addr=redis://10.x.x.239:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet
        at express.security.session.store.RedisHashStore.logAsyncError(RedisHashStore.java:141)
        at express.security.session.store.RedisHashStore.lambda$removeAsync$6(RedisHashStore.java:136)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
```

**Redis version**
`5.0.5`
**Redisson version**
`3.10.5`
**Redisson configuration**
```
{
	"clusterServersConfig": {
		"idleConnectionTimeout": 5000,
		"pingTimeout": 250,
		"connectTimeout": 250,
		"timeout": 250,
		"retryAttempts": 3,
		"retryInterval": 150,
		"failedSlaveReconnectionInterval": 300,
		"failedSlaveCheckInterval": 6000,
		"password": "****",
		"subscriptionsPerConnection": 5,
		"clientName": "abc",
		"loadBalancer": {
			"class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
		},
		"subscriptionConnectionMinimumIdleSize": 1,
		"subscriptionConnectionPoolSize": 5,
		"slaveConnectionMinimumIdleSize": 5,
		"slaveConnectionPoolSize": 5,
		"masterConnectionMinimumIdleSize": 5,
		"masterConnectionPoolSize": 10,
		"readMode": "MASTER",
		"subscriptionMode": "MASTER",
		"nodeAddresses": [10.x.x.235:6379,10.x.x.236:6379,10.x.x.237:6379,10.x.x.238:6379,10.x.x.239:6379,10.x.x.240:6379,10.x.x.241:6379,10.x.x.242:6379,10.x.x.243:6379,10.x.x.244:6379,10.x.x.245:6379,10.x.x.246:6379,10.x.x.247:6379,10.x.x.248:6379,10.x.x.249:6379],
		"scanInterval": 1000,
		"pingConnectionInterval": 0,
		"keepAlive": false,
		"tcpNoDelay": false
	},
	"threads": 10,
	"nettyThreads": 10
}
```

Is the above issue resolved by: https://github.com/redisson/redisson/issues/2234 ?

**Comment by mrniko** [comment]
This issue can't be resolved since reported node hasn't been discoveredy due to delay in topology update on Redis side. To overcome this increase retryAttempts and/or retryInterval settings
