### ISSUE TITLE
Can't connect to server for AWS ElastiCache Redis

### ISSUE THREAD

**Issue by coldray** [redisson/redisson#2743]
### Background
I'm using redis as a lock manager in my application. I set up the AWS elasticache redis server with 1 primary and 2 replicas. 

### Expected behavior

All Redisson clients can connect to the server 

### Actual behavior

My application is running on mutiple ec2 instances, there is always some instances(for example 2/10, 5/30) can't connect to elasticache redis server. 

### Steps to reproduce or test case

When I deploy the application through beanstalk. There is always some instance fail at the healthcheck. When I check the log of those instances. Here is what I found:

```
7:49:43.767 [redisson-netty-9-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
17:49:43.767 [redisson-netty-9-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
17:49:43.767 [redisson-netty-9-2] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@48fb807b
17:49:43.798 [redisson-netty-9-2] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: DatagramPacket(=> /(ip address), PooledUnsafeDirectByteBuf(freed))
17:49:43.894 [redisson-netty-9-2] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0xf7a028f9] RECEIVED: [42375: /172.30.0.2:53], DatagramDnsResponse(from: /172.30.0.2:53, to: /0.0.0.0:46149, 42375, QUERY(0), NoError(0), RD RA)
17:49:43.897 [redisson-netty-9-2] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0xf7a028f9] WRITE: [51958: /172.30.0.2:53], DefaultDnsQuestion(redis endpoint). IN A)
17:49:43.904 [redisson-netty-9-2] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: DatagramPacket(=> /(ip address), PooledUnsafeDirectByteBuf(freed))
17:49:43.915 [redisson-netty-9-2] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: DatagramDnsResponse(from: /(ip address), to: /0.0.0.0:46149, 42375, QUERY(0), NoError(0), RD RA)
17:49:43.921 [redisson-netty-9-2] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0xf7a028f9] RECEIVED: [51958: /172.30.0.2:53], DatagramDnsResponse(from: /(ip address), to: /0.0.0.0:46149, 51958, QUERY(0), NoError(0), RD RA)
17:49:43.965 [redisson-netty-9-2] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: DatagramDnsResponse(from: /(ip address), to: /0.0.0.0:46149, 51958, QUERY(0), NoError(0), RD RA)
17:49:44.055 [redisson-netty-9-3] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1]
17:49:44.058 [redisson-netty-9-3] DEBUG io.netty.handler.ssl.JdkSslContext - Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA]
17:49:44.227 [redisson-netty-9-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xea4a64c3, L:/(ip address) - R:(redis master endpoint)/(ip address):6379] SSLEngine.closeInbound() raised an exception.
17:49:44.230 [redisson-netty-9-3] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: PooledUnsafeDirectByteBuf(freed)
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.connection.ReplicatedConnectionManager.<init>(ReplicatedConnectionManager.java:98) ~[redisson-3.12.5.jar:3.12.5]
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:206) ~[redisson-3.12.5.jar:3.12.5]
	at org.redisson.Redisson.<init>(Redisson.java:64) ~[redisson-3.12.5.jar:3.12.5]
	at org.redisson.Redisson.create(Redisson.java:104) ~[redisson-3.12.5.jar:3.12.5]

```

### Redis version

5.0.5

### Redisson version

3.12.5

### Redisson configuration

I use replicated serverConfig and I only pass the one master endpoint in the config.

  ```
    // 1. Create config object  
  Config config = new Config();  
 ReplicatedServersConfig replicatedServersConfig = config.useReplicatedServers();  
    String redisURIFormat = "rediss://%s:%d";  
  replicatedServersConfig.addNodeAddress(String.format(redisURIFormat, context.get().getEndpoint(), context.get().getPort()));  
  replicatedServersConfig.setPassword(context.get().getAuthToken());  
 return Redisson.create(config);

**Comment by mrniko** [comment]
Please share full stacktrace. I don't see the root exception.

**Comment by coldray** [comment]
Because when I set the log level to trace, there are lots of logs. Previously I use grep command to find redisson related logs. That's not deep enough to find the root cause. So I looked into the log file and found that. It looks to me is the jar conflict issue. I have many io netty jar which is lower than the redisson's version 4.1.48.Final. Is there a way to exclude all of them in pom file, right now I have to exclude each of them one by one. 
io.netty.util.ReferenceCountUtil - Failed to release a message: DatagramPacket(=> /172.30.0.2:53, PooledUnsafeDirectByteBuf(freed))
java.lang.IncompatibleClassChangeError: Class io.netty.util.Recycler$DefaultHandle does not implement the requested interface io.netty.util.internal.ObjectPool$Handle
	at io.netty.buffer.PooledByteBuf.recycle(PooledByteBuf.java:179) ~[netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.PooledByteBuf.deallocate(PooledByteBuf.java:174) ~[netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:110) ~[netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100) ~[netty-buffer-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultAddressedEnvelope.release(DefaultAddressedEnvelope.java:101) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:257) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:149) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsQueryContext.writeQuery(DnsQueryContext.java:136) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsQueryContext.sendQuery(DnsQueryContext.java:118) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsQueryContext.query(DnsQueryContext.java:113) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsNameResolver.query0(DnsNameResolver.java:948) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:343) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsResolveContext.followCname(DnsResolveContext.java:758) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsResolveContext.onResponseCNAME(DnsResolveContext.java:594) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsResolveContext.onExpectedResponse(DnsResolveContext.java:568) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:409) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:62) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:370) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:192) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:184) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:984) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by mrniko** [comment]
> It looks to me is the jar conflict issue

That's right
