### ISSUE TITLE
Ratelimiter occur error in aliyun redis

### ISSUE THREAD

**Issue by 1985815103** [redisson/redisson#2754]
**Exception as below:**

[05-06 21:59:06] [ERROR] [http-nio-8889-e] o.a.c.c.C.[.[.[/showservice].[dispatcherServlet]   - Servlet.service() for servlet [dispatcherServlet] in context with path [/showservice] threw exception
org.redisson.client.RedisException: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression. channel: [id: 0x7091849f, L:/172.16.156.8:38216 - R:r-bp128ubvf0obdjoh62.redis.rds.aliyuncs.com/172.16.156.9:6379] command: (EVAL), params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 3, live:rate-limiter:119.126.28.207:1000, {live:rate-limiter:119.126.28.217:1000}:value, {live:rate-limiter:119.126.28.207:1000}:value:3a0eaa24-eead-492b-990f-458f32dcc846, 1, 3a0eaa24-eead-492b-990f-458f32dcc846]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:371)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**config：**
ReplicatedServersConfig replicatedServersConfig = config.useReplicatedServers()
                    // 主节点变化扫描间隔时间
                    .setScanInterval(2000)
                    .addNodeAddress(aliyunRedisAddress);

            if (redisConfig.hasPassword()) {
                replicatedServersConfig.setPassword(redisConfig.getPassword());
            }
redissonClient = Redisson.create(config);

**redis:**  aliyun redis cluster

**redisson:** 3.12.5

**Comment by mrniko** [comment]
Please contact Redis vendor on this issue. Redis OS doesn't have it.
