### ISSUE TITLE
(missing no-arg constructor): org.apache.catalina.realm.GenericPrincipal

### ISSUE THREAD

**Issue by wabuhigleh** [redisson/redisson#2757]
Environment: 
- RHEL 7.7
- Apache Tomcat 9.0.31
- AWS ElastiCache/Redis

Scenario: 
An app is hosted by two tomcat instances, Tomcat A, and Tomcat B, both are configured with AWS ElastiCache/Redis. The host is registered with AWS Application Load Balancer (sticky enabled).
- The user logon to Tomcat A, and the session is cached by Redis -- good.
- I killed Tomcat A
- Load balancer started forwarding the traffic to Tomcat B -- Expected
- The user continue to work wit the app
- Tomcat B detect the change, and try to fetch session id from Redis, the I get this error, see stack dump:

* conext.xml
 readMode="MEMORY" updateMode="DEFAULT" broadcastSessionEvents="true"

* redisson.yaml
singleServerConfig:
   address: "redis://*********************:6379"
   pingConnectionInterval: 60000
   timeout: 60000
nettyThreads: 256
codec: !<org.redisson.codec.KryoCodec> {}

* Redis/Kryo libraries:
reflectasm-1.11.9.jar
redisson-tomcat-9-3.12.5.jar
redisson-all-3.12.5.jar
objenesis-2.1.jar
kryo-serializers-0.45.jar
kryo-4.0.2.jar
minlog-1.3.0.jar

* Stack dump

Caused by: com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): org.apache.catalina.realm.GenericPrincipal
        at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1319) ~[kryo-4.0.2.jar:?]
        at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1127) ~[kryo-4.0.2.jar:?]
        at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1136) ~[kryo-4.0.2.jar:?]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:562) ~[kryo-4.0.2.jar:?]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:538) ~[kryo-4.0.2.jar:?]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:816) ~[kryo-4.0.2.jar:?]
        at org.redisson.codec.KryoCodec$1.decode(KryoCodec.java:63) ~[redisson-all-3.12.5.jar:3.12.5]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368) ~[redisson-all-3.12.5.jar:3.12.5]
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412) ~[redisson-all-3.12.5.jar:3.12.5]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377) ~[redisson-all-3.12.5.jar:3.12.5]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[redisson-all-3.12.5.jar:3.12.5]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[redisson-all-3.12.5.jar:3.12.5]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[redisson-all-3.12.5.jar:3.12.5]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[redisson-all-3.12.5.jar:3.12.5]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[redisson-all-3.12.5.jar:3.12.5]

**Comment by mrniko** [comment]
Did you try MarshallingCodec or SerializationCodec?

**Comment by wabuhigleh** [comment]
I have tried both, With MarshallingCodec, it only works with Redis 3.12.6 RC (I get ymal paraser error when using the released version 3.12.5).
Both MarshallingCodec and SerializationCodec fails on serializing ThreadLocal
java.io.NotSerializableException: java.land.ThreadLocal
This happens because ThreadLocal is not serializable.
This issue didn't happen with Kryo because ThreadLocal has no-args contractor.

**Comment by mrniko** [comment]
I don't see ThreadLocal object in GenericPrincipal
