### ISSUE TITLE
JsonJacksonCodec decode occur error

### ISSUE THREAD

**Issue by 1985815103** [redisson/redisson#2768]
**The trace log as below:**
field "liveStreamUrl" decode error

[05-14 16:09:10] [TRACE] [redisson-netty-] org.redisson.client.handler.CommandEncoder         - channel: [id: 0xad3d7088, L:/172.16.155.255:37622 - R:172.16.156.8/172.16.156.8:6379] message: *2
$3
GET
$18
show:1021:ex-basic

[05-14 16:09:10] [TRACE] [redisson-netty-] org.redisson.client.handler.CommandDecoder         - reply: $905
{"@class":"com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention","activityId":"1021","likesNum": 51931727,"liveScenceList":["java.util.ArrayList",[{"@class":"com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene","endDate":["java.util.Date", 158
9384580000],"name":"第一场","startDate":["java.util.Date", 1589373780000]},{"@class":"com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene","name":"第二场"},{"@class":"com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene","name":"第三场"}
,{"@class":"com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene","name":"第四场"},{"@class":"com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene","name":"第五场"}]],"onlineUsers": 0,"productDeposit": 10000,"repeatBuySwitch": true,"sixNu
m": 52471575,"userNum": 0,"liveStreamUrl": http://ivi.bupt.edu.cn/hls/zjhd.m3u8}
, channel: [id: 0xad3d7088, L:/172.16.155.255:37622 - R:172.16.156.8/172.16.156.8:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5c3ce058(incomplete)], command=(GET), params=[show:1021:ex-basic], codec=org.redisson.
codec.JsonJacksonCodec]
[05-14 16:09:10] [ERROR] [redisson-netty-] org.redisson.client.handler.CommandDecoder         - Unable to decode data. channel: [id: 0xad3d7088, L:/172.16.155.255:37622 - R:172.16.156.8/172.16.156.8:6379], reply: ReplayingDecoderByteBuf(ridx=913, w
idx=913), command: (GET), params: [show:1021:ex-basic]
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'http': was expecting ('true', 'false' or 'null')
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 874]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3532)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2627)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1053)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:193)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:712)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:95)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**redis data as below:**
{
  "@class": "com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention",
  "activityId": "1021",
  "likesNum": 51931727,
  "liveScenceList": [
    "java.util.ArrayList",
    [
      {
        "@class": "com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene",
        "endDate": [
          "java.util.Date",
           1589384580000
        ],
        "name": "第一场",
        "startDate": [
          "java.util.Date",
           1589373780000
        ]
      },
      {
        "@class": "com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene",
        "name": "第二场"
      },
      {
        "@class": "com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene",
        "name": "第三场"
      },
      {
        "@class": "com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene",
        "name": "第四场"
      },
      {
        "@class": "com.xiaoyun.show.cache.buckets.live.ActivityLiveBasicExtention$Scene",
        "name": "第五场"
      }
    ]
  ],
  "onlineUsers":   0,
  "productDeposit":   10000,
  "repeatBuySwitch":   true,
  "sixNum":   52471575,
  "userNum":   0,
  "liveStreamUrl": "http://ivi.bupt.edu.cn/hls/zjhd.m3u8"
}

redis : 5.0.4 (open source product)
redisson: 3.12.5

**Comment by mrniko** [comment]
Set type of liveStreamUrl to String
