### ISSUE TITLE
cluster throw WriteRedisConnectionException while slave become new master after master shutdown

### ISSUE THREAD

**Issue by xuyu** [redisson/redisson#2802]
**Expected behavior**

use new master and everything is OK

**Actual behavior**

use connection of the shutdown master

**Steps to reproduce or test case**

cluster three master and three slave
master A, slave B
kill A, then B as master
start A, then A as slave of B
kill B, then A as master
start B, then B as slave of A
kill A, then B as master
now cluster status is OK, 
but throw WriteRedisConnectionException because try to use connect of A

**Redis version**

5.0.8

**Redisson version**

3.12.5

**Redisson configuration**
```java
ClusterServersConfig clusterServersConfig = config.useClusterServers()
                .addNodeAddress(hosts.split(","))
                .setScanInterval(3000)
                .setTimeout(6000)
                .setRetryAttempts(5)
                .setRetryInterval(2000)
                .setMasterConnectionPoolSize(4096)
                .setSlaveConnectionPoolSize(4096)
                .setFailedSlaveCheckInterval(60000)
                .setFailedSlaveReconnectionInterval(2000);
```

**ClusterConnectionManager log**
```
2020-05-28 11:18:56.940  INFO 26538 --- [redisson-netty-2-32] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /127.0.0.1:6302
2020-05-28 11:18:56.943  INFO 26538 --- [redisson-netty-2-48] o.r.cluster.ClusterConnectionManager     : slave redis://127.0.0.1:6302 removed for slot ranges: [[10923-16383]]
2020-05-28 11:18:56.944  INFO 26538 --- [redisson-netty-2-48] o.r.cluster.ClusterConnectionManager     : 5461 slots removed from redis://127.0.0.1:6302
2020-05-28 11:18:56.961  INFO 26538 --- [redisson-netty-2-48] o.r.cluster.ClusterConnectionManager     : 5461 slots found to add
2020-05-28 11:18:56.971  INFO 26538 --- [redisson-netty-2-17] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for localhost/127.0.0.1:6302
2020-05-28 11:18:56.971  INFO 26538 --- [redisson-netty-2-20] o.r.connection.pool.SlaveConnectionPool  : 24 connections initialized for localhost/127.0.0.1:6302
2020-05-28 11:18:56.970  INFO 26538 --- [redisson-netty-2-34] o.redisson.connection.MasterSlaveEntry   : master localhost/127.0.0.1:6302 used as slave
2020-05-28 11:18:56.971  INFO 26538 --- [redisson-netty-2-34] o.redisson.connection.MasterSlaveEntry   : master localhost/127.0.0.1:6303 has changed to localhost/127.0.0.1:6302
2020-05-28 11:18:56.972  INFO 26538 --- [redisson-netty-2-34] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for localhost/127.0.0.1:6302
2020-05-28 11:18:59.966 DEBUG 26538 --- [redisson-netty-2-3] o.r.cluster.ClusterConnectionManager     : cluster nodes state got from /127.0.0.1:6302:
5ec50797bf8d7a08a20897c4526cf5c79ae3141a 127.0.0.1:6301@16301 master - 0 1590635939847 1401 connected 5461-10922
836876ef2f59d27763ac6d544646ba7e09a0a14b 127.0.0.1:6300@16300 slave a193501df69576dad18211c0a1a83b7fc3b420bf 0 1590635939000 1397 connected
9248c2d8804c57a69caf7609cb366fafc41079c5 127.0.0.1:6303@16303 master,fail - 1590635928512 1590635927000 1404 disconnected
a27f76d092ec9962d6cdd82a688c3ba1ac15be2d 127.0.0.1:6302@16302 myself,master - 0 1590635937000 1405 connected 10923-16383
86a07d1c4dd106159160330bf77fa58c325269ca 127.0.0.1:6305@16305 slave 5ec50797bf8d7a08a20897c4526cf5c79ae3141a 0 1590635939344 1401 connected
a193501df69576dad18211c0a1a83b7fc3b420bf 127.0.0.1:6304@16304 master - 0 1590635939545 1397 connected 0-5460
```

**WriteRedisConnectionException**
```
2020-05-28 11:19:35.162 ERROR 26538 --- [http-nio-9009-exec-8] h.g.d.r.e.GlobalExceptionHandler         : [GET /api/account/profile] WriteRedisConnectionException, Unable to write command into connection! Node source: NodeSource [slot=16115, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:4096:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6303], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1887531326 [redisClient=[addr=redis://127.0.0.1:6303], channel=[id: 0x901eed94, L:0.0.0.0/0.0.0.0:45234], currentCommand=null], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, CN:realme_useragent_record, redisson__timeout__set:{CN:realme_useragent_record}, redisson__idle__set:{CN:realme_useragent_record}, redisson__map_cache__last_access__set:{CN:realme_useragent_record}, {CN:realme_useragent_record}:redisson_options, 1590635964663, PooledUnsafeDirectByteBuf(ridx: 0, widx: 122, cap: 256)] after 5 retry attempts, WriteRedisConnectionException

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=16115, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:4096:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6303], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1887531326 [redisClient=[addr=redis://127.0.0.1:6303], channel=[id: 0x901eed94, L:0.0.0.0/0.0.0.0:45234], currentCommand=null], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, CN:realme_useragent_record, redisson__timeout__set:{CN:realme_useragent_record}, redisson__idle__set:{CN:realme_useragent_record}, redisson__map_cache__last_access__set:{CN:realme_useragent_record}, {CN:realme_useragent_record}:redisson_options, 1590635964663, PooledUnsafeDirectByteBuf(ridx: 0, widx: 122, cap: 256)] after 5 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:270) ~[redisson-3.12.5.jar!/:3.12.5]
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58) ~[redisson-3.12.5.jar!/:3.12.5]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:155) ~[redisson-3.12.5.jar!/:3.12.5]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:152) ~[redisson-3.12.5.jar!/:3.12.5]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1104) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	... 12 common frames omitted
```

Everything is OK after restart java application.

**Comment by mrniko** [comment]
Fixed! Thanks for report
