### ISSUE TITLE
spring-integration unlock error when use redisson

### ISSUE THREAD

**Issue by wangwei-ying** [redisson/redisson#2803]
use redisson and spring-integration 
```
  @Bean
    public RedisLockRegistry redisLockRegistry(RedisConnectionFactory redisConnectionFactory){
        return new RedisLockRegistry(redisConnectionFactory,"spring-cloud");
    }

    @Component
    public class Run implements CommandLineRunner {

        @Autowired
        private RedisLockHelper redisLockHelper;



        @Autowired
        private RedisLockRegistry springRedisLock;

        @Override
        public void run(String... args) throws Exception {
            String uuid = UUID.randomUUID().toString();


            springRedisLock.obtain("lock").lock();

            springRedisLock.obtain("lock").unlock();


            for (;;){}
        }
    }

```
```xml
 <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.12.5</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-integration</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-redis</artifactId>
        </dependency>
```
spring-boot version 2.2.5

**Expected behavior**

unlock success

**Actual behavior**

unlock error 

```
java.lang.StackOverflowError: null
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.unlink(DefaultedRedisConnection.java:83) ~[spring-data-redis-2.2.5.RELEASE.jar:2.2.5.RELEASE]

```

**Steps to reproduce or test case**

```
default Long unlink(byte[]... keys) {
		return keyCommands().unlink(keys);
	}

```
this ```keyCommands() ``` retuen this OBJECT  occur  recursion.
Maybe,we need override method unlink in ```RedissonConnection```
**Redis version**

**Redisson version**
 <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.12.5</version>
        </dependency>
**Redisson configuration**

**Comment by mrniko** [comment]
Fixed! Thanks for report
