### ISSUE TITLE
Unexpected exception while processing command

### ISSUE THREAD

**Issue by Vcgoyo** [redisson/redisson#2804]
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:353)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:150)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonMap.get(RedissonMap.java:267)
	at org.redisson.spring.cache.RedissonCache.get(RedissonCache.java:73)
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:73)
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:554)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:519)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:401)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.alsc.saas.crm.commons.log.aspect.LogAspect.doAroundAdvice(LogAspect.java:36)
	at com.alsc.saas.crm.commons.log.aspect.LogInfrastructureAspect.doAroundAdvice(LogInfrastructureAspect.java:25)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.alsc.saas.promobatch.infrastructure.intergration.activity.BizCacheSnapshotClientImpl$$EnhancerBySpringCGLIB$$d1d96015.queryUserByCustomerIdCache(<generated>)
	at com.alsc.saas.promobatch.application.hander.activity.common.SimpleCustomerVoucherSendProcessor.checkIn(SimpleCustomerVoucherSendProcessor.java:29)
	at com.alsc.saas.promobatch.application.hander.activity.common.SimpleCustomerVoucherSendProcessor.checkIn(SimpleCustomerVoucherSendProcessor.java:21)
	at com.alsc.saas.promobatch.application.hander.activity.AbstractVoucherSendProcessorHandler.processRecord(AbstractVoucherSendProcessorHandler.java:70)
	at com.alsc.saas.promobatch.application.hander.activity.AbstractVoucherSendProcessorHandler.processRecord(AbstractVoucherSendProcessorHandler.java:34)
	at com.alsc.saas.crmbatch.interfaces.processor.ProcessorFacade.process(ProcessorFacade.java:182)
	at com.alibaba.schedulerx.worker.container.ThreadContainer.start(ThreadContainer.java:84)
	at com.alibaba.schedulerx.worker.container.ThreadContainer.run(ThreadContainer.java:57)
	at com.alibaba.schedulerx.worker.container.ThreadContainer.start(ThreadContainer.java:113)
	at com.alibaba.schedulerx.worker.container.ThreadContainer.run(ThreadContainer.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:861)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:213)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:60)

I use spirng cache and throw this exception  I can't see what is the real exception it throw

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by Vcgoyo** [comment]
@mrniko 3.12.3 
 My Redis tps  got to 40W/s , redis node cpu over 100% and the request hit the same spring cache key, I think maybe  the  reason of this exception is the redis server timeout, But why can't I see the timeout exception?

**Comment by mrniko** [comment]
It might have a problem with codec similar to https://github.com/redisson/redisson/issues/2723#issuecomment-618250500

Try to switch to MarshallingCodec
