### ISSUE TITLE
Scheduled Executor Example Fails

### ISSUE THREAD

**Issue by cemremengu** [redisson/redisson#2808]
**Expected behavior**
This should work according to [examples](https://github.com/redisson/redisson/wiki/9.-distributed-services#941-distributed-scheduled-executor-service-overview)
```
    var executor = redisson.getExecutorService("scheduled-executor");
    executor.registerWorkers(WorkerOptions.defaults());
    executor.schedule((Runnable & Serializable) () -> {
      System.out.println("task has been executed!");
    }, 10, TimeUnit.SECONDS);
```

**Actual behavior**
Throws exception

```
2020-05-31 19:53:29.726 | WARN  | rrent.DefaultPromise:580   | An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$797/0x00000008006ec440.operationComplete()
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.redisson.remote.RemoteServiceRequest (java.lang.String is in module java.base of loader 'bootstrap'; org.redisson.remote.RemoteServiceRequest is in unnamed module of loader 'app')
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) ~[redisson-3.13.0.jar:3.13.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82) ~[redisson-3.13.0.jar:3.13.0]
	at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:481) ~[redisson-3.13.0.jar:3.13.0]
	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:474) ~[redisson-3.13.0.jar:3.13.0]
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:459) ~[redisson-3.13.0.jar:3.13.0]
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:445) ~[redisson-3.13.0.jar:3.13.0]
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:163) ~[redisson-3.13.0.jar:3.13.0]
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) ~[redisson-3.13.0.jar:3.13.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82) [redisson-3.13.0.jar:3.13.0]
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:444) [redisson-3.13.0.jar:3.13.0]
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:439) [redisson-3.13.0.jar:3.13.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370) [redisson-3.13.0.jar:3.13.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) [redisson-3.13.0.jar:3.13.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) [redisson-3.13.0.jar:3.13.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) [redisson-3.13.0.jar:3.13.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Steps to reproduce or test case**

**Redis version**
`6.x`

**Redisson version**
`3.13.0`

**Redisson configuration**
```
  @Bean
  public RedissonClient redis(){
    Config config = new Config();
    config.useClusterServers().addNodeAddress(url);
    config.setCodec(StringCodec.INSTANCE);
    return Redisson.create(config);
  }
```

**Comment by mrniko** [comment]
StringCodec couldn't be used to serialize Java task. Please use different codec https://github.com/redisson/redisson/wiki/4.-data-serialization
