### ISSUE TITLE
StreamInfoDecoder relies on field order of XINFO response

### ISSUE THREAD

**Issue by fawitte** [redisson/redisson#2818]
**Expected behavior**
When using redis streams with redisson, the expected behaviour is, that redisson is able to identify the fields of the xinfo response for streams and fill the StreamInfo type accordingly.

**Actual behavior**
While switching from redis 5.0.6 to redis 6.0.4 I experienced, that the fields "groups" and "last-generated-id" have switched their positions. The result is, that I get an ClassCastException because redisson tries to cast the String "last-generated-id" to Long "groups".

```
Jun 05 11:12:10 my-linux java[13004]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
Jun 05 11:12:10 my-linux java[13004]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
Jun 05 11:12:10 my-linux java[13004]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Jun 05 11:12:10 my-linux java[13004]: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.protocol.decoder.StreamInfoDecoder.decode(StreamInfoDecoder.java:45) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.protocol.decoder.StreamInfoDecoder.decode(StreamInfoDecoder.java:32) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.protocol.decoder.ListMultiDecoder2.decode(ListMultiDecoder2.java:46) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:421) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[LIB.jar!/:?]
Jun 05 11:12:10 my-linux java[13004]: ... 1 more
```

**Steps to reproduce or test case**
- Use redis Version 6.0.4.
- Connect redisson client to this database.
- Get stream info with redisson RStream:
```java
RStream<String, StreamEntry> tmp = client.getStream("existing:redis:stream");
tmp.getInfo().getLastGeneratedId();
```

**Redis version**
== 6.0.4

**Redisson version**
<= 3.13.0

**Redisson configuration**
singleServerConfig:
  address: 192.168.1.5

**Comment by WirrWar2850** [comment]
The XINFO response using redis-cli looks as follows for the 2 redis versions mentioned:

**redis 5.0.6**
```
192.168.1.5:6379> xinfo stream existing:redis:stream
 1) "length"
 2) (integer) 3602
 3) "radix-tree-keys"
 4) (integer) 1201
 5) "radix-tree-nodes"
 6) (integer) 2461
 7) "groups"
 8) (integer) 0
 9) "last-generated-id"
10) "1591349101747-0"
```

**redis 6.0.4**
```
192.168.1.5:6379> xinfo stream existing:redis:stream
 1) "length"
 2) (integer) 465
 3) "radix-tree-keys"
 4) (integer) 93
 5) "radix-tree-nodes"
 6) (integer) 196
 7) "last-generated-id"
 8) "1591348727350-0"
 9) "groups"
10) (integer) 0
```

**Comment by mrniko** [comment]
Fixed
