### ISSUE TITLE
RedisNodeNotFoundException after redis cluster restart

### ISSUE THREAD

**Issue by smirandamedallia** [redisson/redisson#2839]
**Expected behavior**
The client to reconnect to new masters

**Actual behavior**
Seeing this exception
```
Caused by: org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=15421, addr=redis://x.x.x.89:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet.
	at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundFuture(MasterSlaveConnectionManager.java:615)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:567)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:647)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:116)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:245)
```

**Steps to reproduce or test case**
Happens in production after the redis cluster is restarted

**Redis version**
`5.0.5`

**Redisson version**
`3.11.6`

**Redisson configuration**
```
x.x.x.81:6379,x.x.x.82:6379,x.x.x.83:6379,x.x.x.84:6379,x.x.x.85:6379,x.x.x.86:6379,x.x.x.87:6379,x.x.x.88:6379,x.x.x.89:6379

redis-json-config=\
{\
   "clusterServersConfig":{\
      "idleConnectionTimeout":10000,\
      "pingTimeout":250,\
      "connectTimeout":5000,\
      "timeout":3000,\
      "retryAttempts":3,\
      "retryInterval":1500,\
      "failedSlaveReconnectionInterval":3000,\
      "failedSlaveCheckInterval":60000,\
      "password":"xxx",\
      "subscriptionsPerConnection":5,\
      "clientName":"CLIENT_NAME",\
      "loadBalancer":{\
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"\
      },\
      "subscriptionConnectionMinimumIdleSize":1,\
      "subscriptionConnectionPoolSize":5,\
      "slaveConnectionMinimumIdleSize":1,\
      "slaveConnectionPoolSize":5,\
      "masterConnectionMinimumIdleSize":5,\
      "masterConnectionPoolSize":10,\
      "readMode":"MASTER",\
      "subscriptionMode":"MASTER",\
      "nodeAddresses":[REDIS_CLUSTER_IPS],\
      "scanInterval":5000,\
      "pingConnectionInterval": 0,\
      "keepAlive": false,\
      "tcpNoDelay": false\
   },\
   "threads":10,\
   "nettyThreads":10\
}
```

After the redis cluster restart the error is showing up only on a small percentage of instances. The rest were able to reconnect as expected the p95 latency was under 20ms for fetching a single key from a hashset and around 100ms for fetching the entire hashset

**Comment by smirandamedallia** [comment]
[trace-redisson-sorted.log](https://github.com/redisson/redisson/files/4783632/trace-redisson-sorted.log)

Following is the output of:
```
ClusterNodesGroup clusterNodesGroup = client.getClusterNodesGroup();
clusterNodesGroup.pingAll();
clusterNodesGroup.getNodes();
```
```
[
RedisClientEntry [client=[addr=redis://x.x.x.81:6379], type=MASTER], 
RedisClientEntry [client=[addr=redis://x.x.x.86:6379], type=MASTER], 
RedisClientEntry [client=[addr=redis://x.x.x.82:6379], type=MASTER]]
```
The new masters now are: `84,85,89`

**Comment by mrniko** [comment]
Fixed in 3.11.1 version. Please try it and give feedback

**Comment by smirandamedallia** [comment]
Is there a backport or a work around cause I couldn't go above version `3.11` since some config attributes were removed.

**Comment by mrniko** [comment]
I'm afraid no

**Comment by smirandamedallia** [comment]
🙏 will try and work around the configuration issue
