### ISSUE TITLE
Using lockAsync with Scala Akka 

### ISSUE THREAD

**Issue by shahrakesh** [redisson/redisson#2847]
Hi,

Does lockAsync / unlockAsync and bucket async APIs work with Akka actor using Scala/Play?

I am getting the exceptin below:

java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id

Is that because of unlockAsync being triggered inside Future of lockAsync? I am using Scala converters to get Scala Futures from these APIs.

If I generate my own thread ids using random long then it does work.

Thanks
Rakesh

**Comment by shahrakesh** [comment]
Complete Exception stack trace:

java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 557321d4-b4c4-4154-85d4-83b6bee99eb2 thread-id: 26
        at org.redisson.RedissonLock.lambda$unlockAsync$3(RedissonLock.java:601)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
        at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:451)

**Comment by mrniko** [comment]
use methods with threadId parameter.

**Comment by shahrakesh** [comment]
Thanks for confirming.
