### ISSUE TITLE
DefaultSavedRequest cannot be cast to org.springframework.security.web.savedrequest.SavedRequest

### ISSUE THREAD

**Issue by mnapoleonv** [redisson/redisson#2862]
I see this same issues from #1850 but nothing about how it was fixed or what to do.  
My setup is redisson-all.3.13.1 and redisson-tomcat-8-3.13.  I have the RedissonSessionManager configured.  
`2020-06-19T07:28:51.226 ERROR org.springframework.boot.web.servlet.support.ErrorPageFilter - Forwarding to error page from request [/login] due to exception [org.springframework.security.web.savedrequest.DefaultSavedRequest cannot be cast to org.springframework.security.web.savedrequest.SavedRequest]
java.lang.ClassCastException: org.springframework.security.web.savedrequest.DefaultSavedRequest cannot be cast to org.springframework.security.web.savedrequest.SavedRequest
        at org.springframework.security.web.savedrequest.HttpSessionRequestCache.getRequest(HttpSessionRequestCache.java:74)
        at org.springframework.security.web.authentication.SavedRequestAwareAuthenticationSuccessHandler.onAuthenticationSuccess(SavedRequestAwareAuthenticationSuccessHandler.java:77)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:326)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:240)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)`

Is there something I am most likely missing?

**Comment by mrniko** [comment]
It's a classpath issue same spring lib present in two classloaders. Probably one in tomcat/lib and another in webapp

**Comment by mnapoleonv** [comment]
So I had the spring-security-web jar in both my app and tomcat/lib.  When I remove it from tomcat/lib I get 
`io.netty.handler.codec.DecoderException:` java.io.IOException: java.lang.ClassNotFoundException: org.springframework.security.web.savedrequest.DefaultSavedRequest`

And thanks for helping me out/

**Comment by mrniko** [comment]
did you try to move it to tomcat/lib

**Comment by mnapoleonv** [comment]
I had it in tomcat/lib and got the error from the about unable to cast DefaultSavedRequest cannot be cast to org.springframework.security.web.savedrequest.SavedRequest

**Comment by mrniko** [comment]
Can you try SerializationCodec since it's currentThreadClassLoader aware? Retain libs in same locations.

**Comment by mnapoleonv** [comment]
That seemed to do the trick.  At least no more errors in logs.  Thanks

**Comment by mrniko** [comment]
Could you switch back to default MarshallingCodec and replace redisson libs with these?

[redisson-tomcat-8-3.13.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4805319/redisson-tomcat-8-3.13.2-SNAPSHOT.jar.zip)
[redisson-all-3.13.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4805320/redisson-all-3.13.2-SNAPSHOT.jar.zip)

**Comment by mnapoleonv** [comment]
I can give it a try in a bit

**Comment by mnapoleonv** [comment]
I change my redisson.yaml to have
codec: null

And used the two snapshots you gave me and got the same exception
`java.lang.ClassNotFoundException: org.springframework.security.web.savedrequest.DefaultSavedRequest`

spring-security-web jar is only in the webapp and not the tomcat/lib directory

**Comment by mrniko** [comment]
please put spring-security-web jar into tomcat/lib also

**Comment by mrniko** [comment]
Fixed

**Comment by mrniko** [comment]
With any other codec issue could be resolved with `useThreadClassLoader: false` setting
