### ISSUE TITLE
How could i deserialize a value which put by RedisTemplate of Spring from redis ? 

### ISSUE THREAD

**Issue by Chasun-fhd** [redisson/redisson#2867]
How could i deserialize a value which put by RedisTemplate of Spring from redis ? 

especially when i used RedisTemplate of spring before in my project, and now changed to Redisson.

I get an deserialize failed error.

 `redisTemplate.opsForValue().set("hello", "world", 5, TimeUnit.MINUTES);
  String result = (String)client.getBucket("hello").get();
`

>exception stack as follows:
, channel: [id: 0x0451a86f, L:/127.0.0.1:60224 - R:127.0.0.1/127.0.0.1:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2875662c(incomplete)], command=(GET), params=[hello], codec=org.redisson.codec.JsonJacksonCodec]
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'world': was expecting ('true', 'false' or 'null')
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 11]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3532)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2627)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:95)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:352)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:128)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)

**Comment by mrniko** [comment]
I think you need to use either StringCodec or BinaryCodec
