### ISSUE TITLE
error: Provider org.redisson.jcache.JCachingProvider not a subtype

### ISSUE THREAD

**Issue by sam701** [redisson/redisson#2876]
I am running tomcat with Equinox and want to use redisson for session storage. The shared session storage works fine but I have this error in my `localhost.xxx.log`. 

```
java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: Provider org.redisson.jcache.JCachingProvider not a subtype
	java.util.ServiceLoader.fail(ServiceLoader.java:239)
	java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:438)
	javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:432)
	java.security.AccessController.doPrivileged(Native Method)
	javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:432)
	javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:370)
	javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:351)
	javax.cache.Caching.getCachingProvider(Caching.java:142)
```

Here is my `redisson.config.yaml`
```
useThreadClassLoader: false

singleServerConfig:
  address: "redis://redis:6379"
```

I am not actually interested in replacing the caching provider. I'd like to use redisson only for shared session storage.

Appreciate your ideas.

**Comment by mrniko** [comment]
I only can say obvious here: `JCachingProvider` loaded with a different classloader than `javax.cache.spi.CachingProvider` interface it implementing.

**Comment by sam701** [comment]
👍  😄  thanks, that helped. I removed `cache-api-*.jar` from webapp, so that there is just one implementation bundled in `redisson-all-*`

**Comment by sam701** [comment]
Hmm, unfortunately, the issue is still present. Here is the setup: 
- tomcat runs a webapp that uses `ehcache` with `cache-api-1.0.0`
- `redisson-all.jar` and `redisson-tomcat-8.jar` are located in `tomcat/lib`

As soon as the webapp calls `Caching.getCachingProvider(EhcacheCachingProvider.class.getName(), this.getClass().getClassLoader());`, there is the exception `Provider org.redisson.jcache.JCachingProvider not a subtype`. As far as I understand Ehcache extends the `CachingProvider` from the webapp ClassLoader, but the Redisson extends the `CachingProvider` from the tomcat (common) ClassLoader.

Removing `cache-api` jar from the webapp, as I described above, is fragile, because Redisson can change its `cache-api` version any time. Another approach I see is to additionally copy `redisson-all.jar` to the webapp `WEB-INF/lib` directory. But it is also a hack, since the webapp does not need it. @mrniko What would you recommend to deal with Ehcache in the webapp?

**Comment by mrniko** [comment]
I would recommend you to replace ehcache with redisson :)

**Comment by sam701** [comment]
😄   got it. 

But honestly I ended up writing my own redis session manager. It is really tiny one with a sigle dependency to jedis.

**Comment by adbhutrai** [comment]
Do we have any update on this? We are facing the same problem with Spring and ehcache on tomcat 10. We don't want to use redis cache for local cache.

**Comment by mrniko** [comment]
@adbhutrai 

Can you share the stacktrace?

**Comment by mrniko** [comment]
@adbhutrai 

Did you try to remove META-INF\services\javax.cache.spi.CachingProvider file from Redisson jar file?

**Comment by adbhutrai** [comment]
No, I did not remove that.

**Comment by adbhutrai** [comment]
Here is the stacktrace of the error:

21-Mar-2024 16:37:37.365 INFO [main] org.apache.catalina.core.ApplicationContext.log 2 Spring WebApplicationInitializers detected on classpath
21-Mar-2024 16:37:38.491 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
21-Mar-2024 16:38:13.698 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
	org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheCacheManager' defined in class path resource []: Failed to instantiate [org.springframework.cache.jcache.JCacheCacheManager]: Factory method 'jCacheCacheManager' threw exception with message: Error creating bean with name 'cacheManager' defined in class path resource []: Failed to instantiate [javax.cache.CacheManager]: Factory method 'cacheManager' threw exception with message: javax.cache.spi.CachingProvider: org.redisson.jcache.JCachingProvider not a subtype
		at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:489)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1166)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:946)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)
		at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:394)
		at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:274)
		at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:102)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4436)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4876)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:712)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:969)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:771)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:423)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1629)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:845)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:240)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:757)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
	Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.jcache.JCacheCacheManager]: Factory method 'jCacheCacheManager' threw exception with message: Error creating bean with name 'cacheManager' defined in class path resource []: Failed to instantiate [javax.cache.CacheManager]: Factory method 'cacheManager' threw exception with message: javax.cache.spi.CachingProvider: org.redisson.jcache.JCachingProvider not a subtype
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
		... 56 more
	Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheManager' defined in class path resource []: Failed to instantiate [javax.cache.CacheManager]: Factory method 'cacheManager' threw exception with message: javax.cache.spi.CachingProvider: org.redisson.jcache.JCachingProvider not a subtype
		at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:489)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1166)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
		at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:362)
		at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:334)
		at ie.davy.configuration.spring.ServicesConfiguration$$SpringCGLIB$$0.cacheManager(<generated>)
		at ie.davy.configuration.spring.ServicesConfiguration.jCacheCacheManager(ServicesConfiguration.java:71)
		at ie.davy.configuration.spring.ServicesConfiguration$$SpringCGLIB$$0.CGLIB$jCacheCacheManager$1(<generated>)
		at ie.davy.configuration.spring.ServicesConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
		at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
		at ie.davy.configuration.spring.ServicesConfiguration$$SpringCGLIB$$0.jCacheCacheManager(<generated>)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
		... 57 more
	Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.cache.CacheManager]: Factory method 'cacheManager' threw exception with message: javax.cache.spi.CachingProvider: org.redisson.jcache.JCachingProvider not a subtype
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
		... 80 more
	Caused by: java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: org.redisson.jcache.JCachingProvider not a subtype
		at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
		at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
		at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
		at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:448)
		at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:442)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
		at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:442)
		at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:529)
		at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:476)
		at javax.cache.Caching.getCachingProvider(Caching.java:226)
		at ie.davy.configuration.spring.ServicesConfiguration.cacheManager(ServicesConfiguration.java:79)
		at ie.davy.configuration.spring.ServicesConfiguration$$SpringCGLIB$$0.CGLIB$cacheManager$0(<generated>)
		at ie.davy.configuration.spring.ServicesConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
		at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
		at ie.davy.configuration.spring.ServicesConfiguration$$SpringCGLIB$$0.cacheManager(<generated>)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
		... 81 more
21-Mar-2024 16:38:15.259 INFO [main] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext

**Comment by mrniko** [comment]
removing META-INF\services\javax.cache.spi.CachingProvider file should resolve the issue
