### ISSUE TITLE
RedisResponseTimeoutException bug

### ISSUE THREAD

**Issue by pluone** [redisson/redisson#2886]
redisson client config 

```
    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer()
            .setAddress("redis://" + redisHost + ":" + redisPort)
            .setPassword(redisPass);
        return Redisson.create(config);
    }
```

use the redisson lock
```
RLock lock = redissonClient.getLock("lock_key");
if (lock.tryLock()) {
  try{
      // do business logic
  }finally {
    lock.unlock();
  }
}

```

**Expected behavior**
get lock and continue to do business logic

**Actual behavior**
after first time fail and three times retry fail, I got RedisResponseTimeoutException

```
Caused by: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, settlement_platform:importPaymentList, 30000, 91e0ee36-9066-482f-a10f-80a80a921772:58], channel: [id: 0xc05adfb7, L:/192.168.1.102:54095 - R:172.20.10.104/172.20.10.104:6379]
    at org.redisson.command.CommandAsyncService$8.run (CommandAsyncService.java:934)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire (HashedWheelTimer.java:682)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts (HashedWheelTimer.java:757)
    at io.netty.util.HashedWheelTimer$Worker.run (HashedWheelTimer.java:485)
    at java.lang.Thread.run (Thread.java:748)
```

**Steps to reproduce or test case**
the prerequisite is 
1. your redis server require a password auth
2. your redisson client in a NAT

your redis server config have this:

```
tcp-keepalive 300
```

after 5 minute you will get this `RedisResponseTimeoutException` problem, however the redis server did not receive the request at all.

**Redis version**
5.0.4

**Redisson version**
3.11.1

**Redisson configuration**
```
    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer()
            .setAddress("redis://" + redisHost + ":" + redisPort)
            .setPassword(redisPass);
        return Redisson.create(config);
    }
```

**Comment by pluone** [comment]
redis server reset the connection, then happed `RedisResponseTimeoutException`

![image](https://user-images.githubusercontent.com/13798072/86348248-fc749500-bc91-11ea-89af-1fe994b53f34.png)

**Comment by mrniko** [comment]
Could you set `TRACE` logging level for `org.redisson` package and share output?

**Comment by pluone** [comment]
> Could you set `TRACE` logging level for `org.redisson` package and share output?

Hi, I setup a spring boot demo app like this, in the beginning, everything is ok, after five minutes, I get a `RedisResponseTimeoutException`.

```
@GetMapping("/api/foo")
    public Object foo() {
        RLock lock = redissonClient.getLock("myLock");
        if (lock.tryLock()) {
            try {
                log.info("lock acquired!");
                Thread.sleep(1500);
                log.info("doing business");
                return "ok";
            } catch (InterruptedException e) {
                e.printStackTrace();
            } finally {
                lock.unlock();
                log.info("lock released!");
            }
        }
        return "error";
    }
```

The trace log as follows:

```
2020-07-06 10:32:07.983 DEBUG 1628 --- [nio-8080-exec-2] o.redisson.command.CommandAsyncService   : acquired connection for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using node 172.20.10.104/172.20.10.104:6379... RedisConnection@802094900 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x90f45d75, L:/192.168.1.103:50688 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:07.984 TRACE 1628 --- [sson-netty-2-20] o.r.client.handler.CommandEncoder        : channel: [id: 0x90f45d75, L:/192.168.1.103:50688 - R:172.20.10.104/172.20.10.104:6379] message: *6
$4
EVAL
$336
if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);
$1
1
$6
myLock
$5
30000
$39
2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63

2020-07-06 10:32:08.100 DEBUG 1628 --- [pool-1-thread-1] o.r.client.handler.ConnectionWatchdog    : reconnecting RedisConnection@802094900 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x90f45d75, L:/192.168.1.103:50688 ! R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2517ffa0(incomplete)], command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63], codec=org.redisson.client.codec.LongCodec]] to 172.20.10.104/172.20.10.104:6379 
2020-07-06 10:32:08.121 TRACE 1628 --- [sson-netty-2-22] o.r.client.handler.CommandEncoder        : channel: [id: 0xb476e66a, L:/192.168.1.103:50960 - R:172.20.10.104/172.20.10.104:6379] message: *2
$4
AUTH(password masked)
2020-07-06 10:32:08.131 TRACE 1628 --- [sson-netty-2-22] o.r.client.handler.CommandDecoder        : reply: +OK
, channel: [id: 0xb476e66a, L:/192.168.1.103:50960 - R:172.20.10.104/172.20.10.104:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@416ae54a(incomplete)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:08.131 DEBUG 1628 --- [sson-netty-2-22] o.r.client.handler.ConnectionWatchdog    : RedisConnection@802094900 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xb476e66a, L:/192.168.1.103:50960 - R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@416ae54a(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]] connected to 172.20.10.104/172.20.10.104:6379, command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@416ae54a(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:10.999 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : connection released for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@802094900 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xb476e66a, L:/192.168.1.103:50960 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:10.999 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : attempt 1 for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63]
2020-07-06 10:32:11.000 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : acquired connection for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using node 172.20.10.104/172.20.10.104:6379... RedisConnection@1122918872 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x8112e742, L:/192.168.1.103:50687 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:11.000 TRACE 1628 --- [sson-netty-2-24] o.r.client.handler.CommandEncoder        : channel: [id: 0x8112e742, L:/192.168.1.103:50687 - R:172.20.10.104/172.20.10.104:6379] message: *6
$4
EVAL
$336
if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);
$1
1
$6
myLock
$5
30000
$39
2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63

2020-07-06 10:32:11.100 DEBUG 1628 --- [pool-1-thread-1] o.r.client.handler.ConnectionWatchdog    : reconnecting RedisConnection@1122918872 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x8112e742, L:/192.168.1.103:50687 ! R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@8d73112(incomplete)], command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63], codec=org.redisson.client.codec.LongCodec]] to 172.20.10.104/172.20.10.104:6379 
2020-07-06 10:32:11.125 TRACE 1628 --- [sson-netty-2-24] o.r.client.handler.CommandEncoder        : channel: [id: 0xaae50fd0, L:/192.168.1.103:50961 - R:172.20.10.104/172.20.10.104:6379] message: *2
$4
AUTH(password masked)
2020-07-06 10:32:11.141 TRACE 1628 --- [sson-netty-2-24] o.r.client.handler.CommandDecoder        : reply: +OK
, channel: [id: 0xaae50fd0, L:/192.168.1.103:50961 - R:172.20.10.104/172.20.10.104:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@40048fe4(incomplete)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:11.141 DEBUG 1628 --- [sson-netty-2-24] o.r.client.handler.ConnectionWatchdog    : RedisConnection@1122918872 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xaae50fd0, L:/192.168.1.103:50961 - R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@40048fe4(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]] connected to 172.20.10.104/172.20.10.104:6379, command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@40048fe4(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:14.095 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : connection released for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1122918872 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xaae50fd0, L:/192.168.1.103:50961 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:14.095 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : attempt 2 for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63]
2020-07-06 10:32:14.095 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : acquired connection for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using node 172.20.10.104/172.20.10.104:6379... RedisConnection@1419565762 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xe8e58021, L:/192.168.1.103:50708 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:14.096 TRACE 1628 --- [isson-netty-2-6] o.r.client.handler.CommandEncoder        : channel: [id: 0xe8e58021, L:/192.168.1.103:50708 - R:172.20.10.104/172.20.10.104:6379] message: *6
$4
EVAL
$336
if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);
$1
1
$6
myLock
$5
30000
$39
2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63

2020-07-06 10:32:14.200 DEBUG 1628 --- [pool-1-thread-1] o.r.client.handler.ConnectionWatchdog    : reconnecting RedisConnection@1419565762 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xe8e58021, L:/192.168.1.103:50708 ! R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@12fd094a(incomplete)], command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63], codec=org.redisson.client.codec.LongCodec]] to 172.20.10.104/172.20.10.104:6379 
2020-07-06 10:32:14.213 TRACE 1628 --- [sson-netty-2-28] o.r.client.handler.CommandEncoder        : channel: [id: 0xbd52f679, L:/192.168.1.103:50964 - R:172.20.10.104/172.20.10.104:6379] message: *2
$4
AUTH(password masked)
2020-07-06 10:32:14.224 TRACE 1628 --- [sson-netty-2-28] o.r.client.handler.CommandDecoder        : reply: +OK
, channel: [id: 0xbd52f679, L:/192.168.1.103:50964 - R:172.20.10.104/172.20.10.104:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5095d3d(incomplete)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:14.224 DEBUG 1628 --- [sson-netty-2-28] o.r.client.handler.ConnectionWatchdog    : RedisConnection@1419565762 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xbd52f679, L:/192.168.1.103:50964 - R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5095d3d(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]] connected to 172.20.10.104/172.20.10.104:6379, command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5095d3d(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:17.197 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : connection released for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1419565762 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0xbd52f679, L:/192.168.1.103:50964 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:17.197 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : attempt 3 for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63]
2020-07-06 10:32:17.197 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : acquired connection for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using node 172.20.10.104/172.20.10.104:6379... RedisConnection@825960439 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x9ef585dc, L:/192.168.1.103:50709 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:17.198 TRACE 1628 --- [sson-netty-2-14] o.r.client.handler.CommandEncoder        : channel: [id: 0x9ef585dc, L:/192.168.1.103:50709 - R:172.20.10.104/172.20.10.104:6379] message: *6
$4
EVAL
$336
if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);
$1
1
$6
myLock
$5
30000
$39
2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63

2020-07-06 10:32:17.297 DEBUG 1628 --- [pool-1-thread-1] o.r.client.handler.ConnectionWatchdog    : reconnecting RedisConnection@825960439 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x9ef585dc, L:/192.168.1.103:50709 ! R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@e8c8e6d(incomplete)], command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63], codec=org.redisson.client.codec.LongCodec]] to 172.20.10.104/172.20.10.104:6379 
2020-07-06 10:32:17.326 TRACE 1628 --- [sson-netty-2-30] o.r.client.handler.CommandEncoder        : channel: [id: 0x087aee5e, L:/192.168.1.103:50966 - R:172.20.10.104/172.20.10.104:6379] message: *2
$4
AUTH(password masked)
2020-07-06 10:32:17.351 TRACE 1628 --- [sson-netty-2-30] o.r.client.handler.CommandDecoder        : reply: +OK
, channel: [id: 0x087aee5e, L:/192.168.1.103:50966 - R:172.20.10.104/172.20.10.104:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4487764e(incomplete)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:17.351 DEBUG 1628 --- [sson-netty-2-30] o.r.client.handler.ConnectionWatchdog    : RedisConnection@825960439 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x087aee5e, L:/192.168.1.103:50966 - R:172.20.10.104/172.20.10.104:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4487764e(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]] connected to 172.20.10.104/172.20.10.104:6379, command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4487764e(success)], command=(AUTH), params=[vpvqlmwhrFuA6JaI], codec=null]
2020-07-06 10:32:20.297 DEBUG 1628 --- [pool-1-thread-1] o.redisson.command.CommandAsyncService   : connection released for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.20.10.104:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@825960439 [redisClient=[addr=redis://172.20.10.104:6379], channel=[id: 0x087aee5e, L:/192.168.1.103:50966 - R:172.20.10.104/172.20.10.104:6379], currentCommand=null]
2020-07-06 10:32:20.310 ERROR 1628 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63], channel: [id: 0x087aee5e, L:/192.168.1.103:50966 - R:172.20.10.104/172.20.10.104:6379]] with root cause

org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, myLock, 30000, 2bf9b25e-81f6-4c93-a22f-d3f3f46f96e0:63], channel: [id: 0x087aee5e, L:/192.168.1.103:50966 - R:172.20.10.104/172.20.10.104:6379]
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:934) ~[redisson-3.11.1.jar:3.11.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

```

**Comment by mrniko** [comment]
> redis server reset the connection, then happed RedisResponseTimeoutException

Try to set `pingConnectionInterval` setting
