### ISSUE TITLE
Set Redisson config using AWS ElastiCache as Clustered Mode

### ISSUE THREAD

**Issue by daviddelucca** [redisson/redisson#2888]
Hey there!

What is the proper way to configure Redisson when you have a AWS ElastiCache Redis running as Clustered Mode? I have tried to set using it as follows:

```
    val nodeAddress = "redis://test-rest-encryption-0001-001.p0vefj.0001.use1.cache.amazonaws.com:6379" 
    val config = Config()
    val configCluster = config.useClusterServers().addNodeAddress(nodeAddress)
    val client = Redisson.create(config)
```

Node endpoint: test-rest-encryption-0001-001.p0vefj.0001.use1.cache.amazonaws.com
Configuration endpoint: test-rest-encryption.p0vefj.clustercfg.use1.cache.amazonaws.com

For `nodeAddress`, I have tried to use configuration endpoint and node endpoint but fails in both case (connection timed out):

```
21:04:39.542 [main] WARN  o.r.cluster.ClusterConnectionManager - connection timed out: test-rest-encryption-0001-001.p0vefj.0001.use1.cache.amazonaws.com/172.31.19.41:6379
Exception in thread "main" org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:144)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:237)
	at org.redisson.Redisson.<init>(Redisson.java:117)
	at org.redisson.Redisson.create(Redisson.java:156)
	at aus.web.SessionManagerApplicationKt.main(SessionManagerApplication.kt:23)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: test-rest-encryption-0001-001.p0vefj.0001.use1.cache.amazonaws.com/172.31.19.41:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Am I missing something?

**Comment by mrniko** [comment]
Is your application located in the same security group?

**Comment by daviddelucca** [comment]
Yes, it’s in the same SG!

**Comment by daviddelucca** [comment]
@mrniko I have figured part of the problem: the client throws an exception if I try to connect to cluster with option `Encryption in-transit` enabled. Does this client support Encryption in-transit and Encryption at-rest?

**Comment by mrniko** [comment]
use rediss:// prefix for SSL connection. And select latest Redisson version for new projects.

**Comment by daviddelucca** [comment]
Solved! It was the prefix!
