### ISSUE TITLE
Redis Cluster - fails to calculate key slot when missing closing "}"

### ISSUE THREAD

**Issue by svilenivanovsmule** [redisson/redisson#2896]
I have `{` as part of the key but no `}` because it is part of my domain which is not intended to be used [key hash tags](https://redis.io/topics/cluster-spec#keys-hash-tags). As a result I get:
```
java.lang.StringIndexOutOfBoundsException: begin 10, end -1, length 11
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at org.redisson.cluster.ClusterConnectionManager.calcSlot(ClusterConnectionManager.java:652)
        at org.redisson.command.CommandAsyncService.getNodeSource(CommandAsyncService.java:354)
        at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:366)
        at org.redisson.RedissonSet.sizeAsync(RedissonSet.java:79)
        at org.redisson.RedissonSet.size(RedissonSet.java:74)
```

**Expected behavior**
According to [Redis documentation](https://redis.io/topics/cluster-spec#keys-hash-tags) missing closing `}` is fine, use the whole string to calculate the hash slot. Similarly, if there is no string between `{` and `}` (i.e. `abc{}xyz`), use the whole key too.  

**Actual behavior**
Exception

**Steps to reproduce or test case**
```
redissonClient.getSet<String>("{test").add("1")
```

**Redis version**
6.0.4

**Redisson version**
3.33.1

**Redisson configuration**
All defaults, except 3 nodes bootstrap

**Notes**

I suggest to modify `org.redisson.cluster.ClusterConnectionManager.calcSlot(java.lang.String)` like this:

```java
public int calcSlot(String key) {
    if (key == null) {
        return 0;
    }

    int start = key.indexOf('{');
    if (start != -1) {
        int end = key.indexOf('}');
        // the closing } must be after opening { and the string between them must not be zero length
        if (end != -1 && start + 1 < end) {
            key = key.substring(start + 1, end);
        }
    }

    int result = CRC16.crc16(key.getBytes()) % MAX_SLOT;
    log.debug("slot {} for {}", result, key);
    return result;
}
```

**Comment by svilenivanovsmule** [comment]
BTW, I've just noticed `org.redisson.cluster.ClusterConnectionManager#calcSlot(byte[])` - it has to be fixed too

**Comment by svilenivanovsmule** [comment]
Thank you!
