### ISSUE TITLE
Getting Register a custom serializer implementing instantiate or define empty constructor - redis cache on wildfly

### ISSUE THREAD

**Issue by sunilchaurha** [redisson/redisson#2898]
Hello, When I deploy my code on Wildfly-19 with Redisson client to connect to Redis cluster. I am getting below error.

**Here is my redis configuration**
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 10000
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  scanInterval: 1000
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

**Exception:**

2020-07-07 21:18:13,475 ERROR [org.redisson.client.handler.ErrorsLoggingHandler] (redisson-netty-2-18) Exception occured. Channel: [id: 0x4e4f015f, L:/172.20.137.105:63544 - R:apps-xx-dev-cache.xxxti.use1.cache.amazonaws.com/xx.xx6.88.10:6379]: io.netty.handler.codec.DecoderException: java.io.IOException: java.io.IOException: <undefined referencee>:Failed to instantiate 'com.xxxx.StandardColumnInfo'. Register a custom serializer implementing instantiate or define empty constructor.
	at deployment.pc.ear//io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at deployment.pc.ear//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at deployment.pc.ear//io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
	at deployment.pc.ear//io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
	at deployment.pc.ear//io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
	at deployment.pc.ear//io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at deployment.pc.ear//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at deployment.pc.ear//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at deployment.pc.ear//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at deployment.pc.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at deployment.pc.ear//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at deployment.pc.ear//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at deployment.pc.ear//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at deployment.pc.ear//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at deployment.pc.ear//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at deployment.pc.ear//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at deployment.pc.ear//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at deployment.pc.ear//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at deployment.pc.ear//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: java.io.IOException: <undefined referencee>:Failed to instantiate 'com.xxxx.StandardColumnInfo'. Register a custom serializer implementing instantiate or define empty constructor.
	at deployment.pc.ear//org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at deployment.pc.ear//org.redisson.codec.FstCodec$1.decode(FstCodec.java:250)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:419)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:419)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at deployment.pc.ear//org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at deployment.pc.ear//io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at deployment.pc.ear//io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 26 more
Caused by: java.io.IOException: <undefined referencee>:Failed to instantiate 'com.xxx.StandardColumnInfo'. Register a custom serializer implementing instantiate or define empty constructor.
	at deployment.pc.ear//org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:533)
	at deployment.pc.ear//org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
	at deployment.pc.ear//org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
	at deployment.pc.ear//org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
	at deployment.pc.ear//org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)

Please suggest some help.

**Comment by mrniko** [comment]
Try switch to MarshallingCodec or SerializableCodec

**Comment by sunilchaurha** [comment]
tried with MarshallingCodec but was getting encoding error.

**Comment by mrniko** [comment]
Could you share code example to reproduce it?

**Comment by sunilchaurha** [comment]
Hi, sharing code to reproduce is difficult because there is lot of coupled code. 
For now I overridden BasicCodec and wrote my own codec class. Which works fine as SerializationCode.
