### ISSUE TITLE
PING command still send on IDLE closed channel

### ISSUE THREAD

**Issue by empty117** [redisson/redisson#2902]
**Expected behavior**
PING command should not be sent on IDLE closed connection

**Actual behavior**
PING command send on IDLE closed connection and got closedConnection exception

2020-07-08-T08:49:59.529+0300 | sprintlab449vm16 | | redisson-netty-2-6 | DEBUG | org.redisson.connection.IdleConnectionWatcher | Connection [id: 0xd0aa1eac, L:/10.91.133.162:33333 ! R:/10.91.133.162:6379] has been closed due to idle timeout. Not used for 18502 ms

2020-07-08-T08:51:05.803+0300 | sprintlab449vm16 | | redisson-timer-4-1 | ERROR | org.redisson.client.handler.PingConnectionHandler | Unable to send PING command over channel: [id: 0xd0aa1eac, L:/10.91.133.162:33333 ! R:/10.91.133.162:6379]
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-07-08-T08:51:05.803+0300 | sprintlab449vm16 | | redisson-timer-4-1 | DEBUG | org.redisson.client.handler.PingConnectionHandler | channel: [id: 0xd0aa1eac, L:/10.91.133.162:33333 ! R:/10.91.133.162:6379] closed due to PING response timeout set in 60000 ms

**Steps to reproduce or test case**

pingConnectionInterval=60000
idleConnectionTimeout: 10000,
masterConnectionMinimumIdleSize: 32
masterConnectionPoolSize: 256

**Redis version**
5.0

**Redisson version**
3.13.0

**Redisson configuration**
Sentinel

**Comment by empty117** [comment]
Dose round-robin way got changed in 3.13.0? 
I set: 
idleConnectionTimeout: 10000,
masterConnectionMinimumIdleSize: 32
masterConnectionPoolSize: 256

 but connection got IDLE closed much more frequently than before(3.12.2)

**Comment by empty117** [comment]
@mrniko : Did you get time to check it?

**Comment by hezhengzhou** [comment]
@mrniko  Any update from you?

**Comment by hezhengzhou** [comment]
@mrniko  Still waiting for your support to resolve this issue. thanks!

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/ad94116744d7fadd3aca697bf0101bb80e92cd23 Please update to the latest version.
