### ISSUE TITLE
 Unable to decode data. Unsupported protocol version 252

### ISSUE THREAD

**Issue by alexpassionate** [redisson/redisson#2905]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
 Unable to decode data. channel: [id: 0x1ae86c3a, L:/*:61442 - R:r-bds.aliyuncs.com/****:6379], reply: ReplayingDecoderByteBuf(ridx=657, widx=657), command: (BLPOP), params: [im_send_queue, 0]
java.io.IOException: Unsupported protocol version 252
	at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1360)
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:156)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-07-10 10:48:59,092 [redisson-netty-4-6] ERROR o.r.c.handler.ErrorsLoggingHandler.exceptionCaught(ErrorsLoggingHandler.java:47) - Exception occured. Channel: [id: 0x1ae86c3a, L:/192.168.17.162:61442 - R:r-bp1uk1w7jc64hoqc0rpd.redis.rds.aliyuncs.com/47.111.55.250:6379]
io.netty.handler.codec.DecoderException: java.io.IOException: Unsupported protocol version 252
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unsupported protocol version 252
	at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1360)
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:156)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 28 common frames omitted
2020-07-10 10:48:59,095 [restartedMain] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener.logAutoConfigurationReport(ConditionEvaluationReportLoggingListener.java:101) - 

**Redis version**
  5.0 
**Redisson version**
 3.11.6
**Redisson configuration**
 @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(name = "spring.redisson.mode", havingValue = "single")
    RedissonClient redissonClient(RedissonProperties redissonProperties) {
        Config config = new Config();
        SingleServerConfig serverConfig = config.useSingleServer()
                .setAddress(redissonProperties.getNodeAddresses())
                .setIdleConnectionTimeout(redissonProperties.getIdleConnectionTimeout())
                .setConnectTimeout( redissonProperties.getConnectTimeout())
                .setRetryAttempts(redissonProperties.getRetryAttempts())
                .setRetryInterval(redissonProperties.getRetryInterval())
                .setDatabase(redissonProperties.getDatabase())
                .setConnectionPoolSize(redissonProperties.getConnectionPoolSize())
                .setTimeout(redissonProperties.getTimeOut());
        if (Objects.nonNull(redissonProperties.getPassword())) {
            serverConfig.setPassword(redissonProperties.getPassword());
        }
        return Redisson.create(config);
    }

**Comment by mrniko** [comment]
Seems you are trying to decode data encoded with different codec

**Comment by alexguzun** [comment]
Hi @mrniko ! I got the exact same error after updating from `3.11.0` to `3.13.6`.

It seems that in version 3.13 the default codec was changed (https://github.com/redisson/redisson/blob/master/CHANGELOG.md#25-may-2020---3130-released), but there is no information on how to migrate the data that was encoded with previous version of code. 

Any advice on how to proceed?

**Comment by mrniko** [comment]
just define FstCodec in configuration https://github.com/redisson/redisson/wiki/2.-Configuration#codec

**Comment by alexguzun** [comment]
Hi @mrniko! Thank you for quick reply.

Unfortunatelly, the data seems to be corrupted. After rolling back to previous version of Redisson (3.11.0), got this error: 

```
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:228)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:428)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
```

**Comment by mrniko** [comment]
Default codec has changed in 3.13.0 version "Improvement - default codec changed to MarshallingCodec" https://github.com/redisson/redisson/blob/master/CHANGELOG.md#25-may-2020---3130-released

**Comment by alexguzun** [comment]
Also important to note that this happened only with data in a `org.redisson.RedissonScoredSortedSet`. All other operations were fine with the new version of Redisson.

**Comment by yanjia92** [comment]
Any process on this issue? Same issues met.
