### ISSUE TITLE
RedisTimeoutException on ElastiCache being called by Kubernetes

### ISSUE THREAD

**Issue by daviddelucca** [redisson/redisson#2912]
Hey there!

We moved our code to production and we are facing a lot of timeout errors:

```
org.redisson.client.RedisTimeoutException: Redis server response timeout (0 ms) occured for command: (GET) with params: [5b9220a8bed49eef9219da4007d28fb3] channel: [id: 0xdd5244f5, L:/172.16.93.114:57196 - R:sec-redis-cluster-0003-002.sec-redis-cluster.pu81s0.nae1.cache.amazonaws.com/172.16.70.62:6379]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:697)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at java.lang.Thread.run(Thread.java:834)
```

It's happening for GET and PSETEX commands. I have found the FAQ with possible solutions like increase nettyThreads and I was wondering if our problem is related with FAQ instructions - our code is super simple, it's a spring boot application with the following implementation:

application.properties
```
#CACHE
spring.redis.host=rediss://clustercfg.sec-redis-cluster.pu81s0.nae1.cache.amazonaws.com
spring.redis.port=6379
spring.redis.password=
```

CacheServiceImpl.kt
```
@Service
class CacheServiceImpl(val redissonClient: RedissonClient) : CacheService {

    private val logger = logger<CacheServiceImpl>()

    override fun put(key: String, value: String, expiresInSeconds: Long) {
        val rBucket = getBucket(key)

        rBucket.set(value, expiresInSeconds, TimeUnit.SECONDS)
    }

    override fun get(key: String): String? {
        val rBucket = getBucket(key)

        return rBucket.get()
    }

    private fun getBucket(key: String) = redissonClient.getBucket<String>(key, StringCodec.INSTANCE)
}
```

For now, we don't have massive requests, probably it's missing some configuration or just update Redisson Client because we are using a super outdated version `3.5.6`.

Do you have any other suggestion behind update lib? Do you know if is possible set `nettyThread` using application.properties?

**Comment by mrniko** [comment]
You set 0ms response timeout.

**Comment by daviddelucca** [comment]
I have tried update configuration as 

```
spring.redis.timeout=10000
```

But it takes no effect. Is other syntax or command?

**Comment by daviddelucca** [comment]
I have checked the piece of code that is creating Redisson client and I can see the timeout is set as 3 seconds (getting default value).

**Comment by daviddelucca** [comment]
The other common error is:

```
org.redisson.client.RedisTimeoutException: Redis server response timeout (0 ms) occured for command: (EVAL) with params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, data, redisson__timeout__set:{data}, redisson__idle__set:{data}, redisson__map_cache__last_access__set:{data}, {data}:redisson_options, 1594650741855, SimpleLeakAwareByteBuf(PooledUnsafeDirectByteBuf(ridx: 0, widx: 34, cap: 256))] channel: [id: 0x8d916bbb, L:/172.16.189.213:36762 - R:sec-redis-cluster-0003-002.iti-sec-redis-cluster.pu81s0.nae1.cache.amazonaws.com/172.16.185.140:6379]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:697)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at java.lang.Thread.run(Thread.java:831)
```

**Comment by daviddelucca** [comment]
@mrniko , I just have updated redisson to 3.13.1 and timeout error is gone but the application won't starting. I'm running EKS with 6 nodes and my Kubernetes has 3 pods.

**Comment by daviddelucca** [comment]
```
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: sec-redis-cluster-0002-001.sec-redis-cluster.pu81s0.nae1.cache.amazonaws.com/172.20.65.246:6379 Disconnected hosts: [sec-redis-cluster-0002-001.sec-redis-cluster.pu81s0.nae1.cache.amazonaws.com/172.20.65.246:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:254)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:480)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:641)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:643)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:243)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
```

**Comment by daviddelucca** [comment]
```
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host:sec-redis-cluster-0002-001.sec-redis-cluster. pu81s0.nae1.cache.amazonaws.com/172.20.65.246:6379 Disconnected hosts: [sec-redis-cluster-0002-001.sec-redis-cluster. pu81s0.nae1.cache.amazonaws.com/172.20.65.246:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:254)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:480)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:641)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:643)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:243)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
```

**Comment by daviddelucca** [comment]
3.13.2 throws the same exceptions

@mrniko should I do any aditional configuration to work with Amazon ElasticCache? I have set host using node endpoint and cluster endpoint, both throws me exceptions. The lib is only working if I have a single pod running - it fails when launch using multiple pods.

**Comment by daviddelucca** [comment]
Since the timeout error is gone, I'll open a new thread with new error. I'll be glad if you could give me some ideas
