### ISSUE TITLE
Caused by: org.redisson.client.RedisException: ERR unsupported unit provided. please use m, km, ft, mi.

### ISSUE THREAD

**Issue by hegphegp** [redisson/redisson#2920]
```
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: ERR unsupported unit provided. please use m, km, ft, mi. channel: [id: 0x872913fa, L:/127.0.0.1:45976 - R:/127.0.0.1:6379] command: (GEORADIUS), params: [[116, 101, 115, 116, 45, 108, 111, 99, 97, 116, ...], 116.9412419137, 39.2212812254, 6378.137, , WITHCOORD, COUNT, 3, ASC]; nested exception is org.redisson.client.RedisException: ERR unsupported unit provided. please use m, km, ft, mi. channel: [id: 0x872913fa, L:/127.0.0.1:45976 - R:/127.0.0.1:6379] command: (GEORADIUS), params: [[116, 101, 115, 116, 45, 108, 111, 99, 97, 116, ...], 116.9412419137, 39.2212812254, 6378.137, , WITHCOORD, COUNT, 3, ASC]
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48) ~[redisson-spring-data-23-3.13.2.jar:3.13.2]
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35) ~[redisson-spring-data-23-3.13.2.jar:3.13.2]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:217) ~[redisson-spring-data-23-3.13.2.jar:3.13.2]
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:212) ~[redisson-spring-data-23-3.13.2.jar:3.13.2]
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:378) ~[redisson-spring-data-23-3.13.2.jar:3.13.2]
	at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:759) ~[redisson-spring-data-23-3.13.2.jar:3.13.2]
	at org.redisson.spring.data.connection.RedissonConnection.geoRadius(RedissonConnection.java:2026) ~[redisson-spring-data-23-3.13.2.jar:3.13.2]
	at org.springframework.data.redis.core.DefaultGeoOperations.lambda$radius$7(DefaultGeoOperations.java:181) ~[spring-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) ~[spring-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) ~[spring-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) ~[spring-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.data.redis.core.DefaultGeoOperations.radius(DefaultGeoOperations.java:181) ~[spring-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.condingfly.Application.testNearByXY(Application.java:98) [classes/:na]
	at com.condingfly.Application.run(Application.java:41) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 5 common frames omitted
Caused by: org.redisson.client.RedisException: ERR unsupported unit provided. please use m, km, ft, mi. channel: [id: 0x872913fa, L:/127.0.0.1:45976 - R:/127.0.0.1:6379] command: (GEORADIUS), params: [[116, 101, 115, 116, 45, 108, 111, 99, 97, 116, ...], 116.9412419137, 39.2212812254, 6378.137, , WITHCOORD, COUNT, 3, ASC]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[redisson-3.13.2.jar:3.13.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[redisson-3.13.2.jar:3.13.2]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]
```

**Comment by mrniko** [comment]
Can you share the code to reproduce the issue?

**Comment by hegphegp** [comment]
This is my fault. I ran the wrong command. sorry.

**Comment by ruanun** [comment]
I encountered the same problem when using Redis geo for the project, but it worked fine when using km units

@hegphegp

**Comment by mrniko** [comment]
@ruanun 

Can you share the code to reproduce issue?
