### ISSUE TITLE
(XREADGROUP) in redisson-spring-data cause READONLY You can't write against a read only replica

### ISSUE THREAD

**Issue by dragonlayout** [redisson/redisson#2925]
**Expected behavior**
I start to use redis stream as a mq to send log record,  I add a record to the stream in client service , when I try to get the log record from the redis stream I got the exception. 

**What I Think**
From #2663, and [redis website](https://redis.io/topics/streams-intro), the command `XREADGROUP` 
> XREADGROUP is a write command because even if it reads from the stream, the consumer group is modified as a side effect of reading, so it can be only called in master instances.

#2663 fix  `redisson/src/main/java/org/redisson/RedissonStream.java` method `readGroupAsync`, so I think maybe `org.redisson.spring.data.connection` method `xReadGroup`
```java
if (readOptions.getBlock() != null && readOptions.getBlock() > 0) {
            return connection.read(streams[0].getKey(), ByteArrayCodec.INSTANCE, XREADGROUP_BLOCKING, params.toArray());
        }
        return connection.read(streams[0].getKey(), ByteArrayCodec.INSTANCE, XREADGROUP, params.toArray());
```
should change to use the write operation.

**Actual behavior**
```java
[2020-07-17 14:54:13.872] [] [ERROR] [pool-2-thread-1] [org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer$LoggingErrorHandler.handleError(DefaultStreamMessageListenerContainer.java:350)] - Unexpected error occurred in scheduled task.
org.springframework.dao.InvalidDataAccessApiUsageException: READONLY You can't write against a read only replica.. channel: [id: 0xcda54d5b, L:/10.220.2.31:41268 - R:redis-1.redis.wechat-test.svc.cluster.prod/10.220.2.20:6379] command: (XREADGROUP), params: [GROUP, redis-log-service, null:null, COUNT, 10, STREAMS, [108, 111, 103, 95, 115, 116, 114, 101, 97, 109, ...], >]; nested exception is org.redisson.client.RedisException: READONLY You can't write against a read only replica.. channel: [id: 0xcda54d5b, L:/10.220.2.31:41268 - R:redis-1.redis.wechat-test.svc.cluster.prod/10.220.2.20:6379] command: (XREADGROUP), params: [GROUP, redis-log-service, null:null, COUNT, 10, STREAMS, [108, 111, 103, 95, 115, 116, 114, 101, 97, 109, ...], >]
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:217) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:212) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:378) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
	at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:759) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
	at org.redisson.spring.data.connection.RedissonStreamCommands.xReadGroup(RedissonStreamCommands.java:617) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.xReadGroup(DefaultedRedisConnection.java:591) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.DefaultStreamOperations$4.inRedis(DefaultStreamOperations.java:310) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.DefaultStreamOperations$RecordDeserializingRedisCallback.doInRedis(DefaultStreamOperations.java:376) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.DefaultStreamOperations$RecordDeserializingRedisCallback.doInRedis(DefaultStreamOperations.java:371) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.DefaultStreamOperations.read(DefaultStreamOperations.java:305) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.core.StreamOperations.read(StreamOperations.java:458) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$getReadFunction$2(DefaultStreamMessageListenerContainer.java:232) ~[spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:138) [spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:123) [spring-data-redis-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.redisson.client.RedisException: READONLY You can't write against a read only replica.. channel: [id: 0xcda54d5b, L:/10.220.2.31:41268 - R:redis-1.redis.wechat-test.svc.cluster.prod/10.220.2.20:6379] command: (XREADGROUP), params: [GROUP, redis-log-service, null:null, COUNT, 10, STREAMS, [108, 111, 103, 95, 115, 116, 114, 101, 97, 109, ...], >]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365) ~[redisson-3.13.2.jar!/:3.13.2]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[redisson-3.13.2.jar!/:3.13.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[redisson-3.13.2.jar!/:3.13.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[redisson-3.13.2.jar!/:3.13.2]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
	... 1 more
```

**Steps to reproduce or test case**
1. setup MasterSlave redisson config
2. add a record using redis stream api
3. try to get the stream message use `StreamMessageListenerContainer ` and `StreamListener`
**Redis version**
5.0.4

**Redisson version**
3.13.2

**Redisson configuration**
```java
config.setThreads(0)
                .setNettyThreads(0)
                .setCodec(JsonJacksonCodec.INSTANCE)
                .setTransportMode(TransportMode.NIO);
        MasterSlaveServersConfig masterSlaveServersConfig =
                config.useMasterSlaveServers()
                .setIdleConnectionTimeout(10000)
                .setConnectTimeout(10000)
                .setTimeout(3000)
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setClientName("master-slave-redis-server")
                .setMasterAddress("redis://" + redisProperties.getMaster().getHost() + ":" + redisProperties.getMaster().getPort())
                .addSlaveAddress("redis://" + redisProperties.getSlave().getHost() + ":" + redisProperties.getSlave().getPort())
                .setSubscriptionsPerConnection(5)
                .setSubscriptionConnectionPoolSize(50)
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setMasterConnectionMinimumIdleSize(32)
                .setMasterConnectionPoolSize(64)
                .setSlaveConnectionMinimumIdleSize(32)
                .setSlaveConnectionPoolSize(64)
                .setDatabase(redisProperties.getMaster().getDatabase())
                .setDnsMonitoringInterval(5000);
```

**Comment by mrniko** [comment]
Fixed
