### ISSUE TITLE
When performing failover, RedisConnectionException is thrown when accessing the cache after failover.

### ISSUE THREAD

**Issue by Ryosuke-mm** [redisson/redisson#2932]
Please let me know because an unexpected event has occurred.

**□Expected behavior**
Successful access to the cache once failover is complete

**□Actual behavior**
RedisConnectionException is thrown when getting cache

**□Conditions that cause an exception**
I tried it several times, but I have confirmed that this event occurs only when information is acquired from the cache during failover.

**□Steps to reproduce or test case**
State at start：master A, slave B
Step1：kill slaveB
Step2、create slaveC, slaveD
Step3、Fail over Master A
State at the time of error:slave A, master B,slave C

**□Redisson version**
3.13.2

**□Exception Log**

```
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: process-rg.mme3hi.ng.0001.apne1.cache.amazonaws.com/XXX.XX.XXX.XXX:6379 Disconnected hosts: [process-rg.mme3hi.ng.0001.apne1.cache.amazonaws.com/XXX.XX.XXX.XX:6379]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218)
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:254)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:499)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:641)
        at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:640)
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115)
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:243)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**□Other**
Since this phenomenon first occurred in version 3.6.5, I tried 3.3.12 but the phenomenon did not resolve.
In version 3.6.5, throw WriteRedisConnectionException

I would like support.

**Comment by mrniko** [comment]
Could you attach Redisson log from start moment?

**Comment by Ryosuke-mm** [comment]
I do not have it now, so I will attach it after acquisition.

**Comment by Ryosuke-mm** [comment]
>Could you attach Redisson log from start moment?

Attach additional information.

best regard.

[Redisson-#2932-log_20200721.txt](https://github.com/redisson/redisson/files/4951375/Redisson-.2932-log_20200721.txt)

**Comment by mrniko** [comment]
Could you set `trace` logging level for `org.redisson` and include output in log?

**Comment by mrniko** [comment]
Fixed
