### ISSUE TITLE
Redis Sentinel - RedissonAutoConfiguration (SpringBoot) - StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kuikiker** [redisson/redisson#2934]
SpringBoot application does not start due to the following 'StringIndexOutOfBoundsException' exception when the RedissonClient is tried to be instantiated:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'rediss
on' threw exception; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -3
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
        ... 156 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -3
        at java.lang.String.substring(String.java:1967)
        at org.redisson.misc.RedisURI.<init>(RedisURI.java:46)
        at org.redisson.connection.SentinelConnectionManager.checkAuth(SentinelConnectionManager.java:209)
        at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:88)
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200)
        at org.redisson.Redisson.<init>(Redisson.java:64)
        at org.redisson.Redisson.create(Redisson.java:104)
        at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:172)
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$5c6ec47d.CGLIB$redisson$0(<generated>)
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$5c6ec47d$$FastClassBySpringCGLIB$$22e43b97.invoke(<gene
rated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363
)
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$5c6ec47d.redisson(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 157 more
```

Spring redis properties:
```
spring:
  cache:
    redis:
      time-to-live: 1800000 # 30 minutes
  redis:
    sentinel:
      master: redis-master
      nodes:
        - app-redis-headless.app.svc.cluster.local
    port: 26379
    password: ${REDIS_PASSWORD}
```
The line of code that fails seems to be this one (RedisURI.java:46):
`String ipV6Host = uri.substring(uri.indexOf("://")+3, uri.lastIndexOf(":"));`

**Comment by mrniko** [comment]
you need to define `redis://` or `rediss://` prefixes in Redis url

**Comment by kuikiker** [comment]
> you need to define `redis://` or `rediss://` prefixes in Redis url

I thought that those URLs were composed by SpringBoot or something before, because the validation at RedisURI class just before the line that is throwing the exception validates that the URL starts with 'redis://' or 'rediss://' and it is not complaining there.
```
        if (!uri.startsWith("redis://")
                && !uri.startsWith("rediss://")) {
            throw new IllegalArgumentException("Redis url should start with redis:// or rediss:// (for SSL connection)");
        }
```
