### ISSUE TITLE
RedissonMapCache 在发布 lruItemValue 的 remove 事件时 未进行 struct.unpack 

### ISSUE THREAD

**Issue by 26888588** [redisson/redisson#2941]
问题版本：
    最新版本3.13.2
问题描述：

我使用的是 RMapCache 组件做为有界lru队列使用，具体用法如下：
 RMapCache<Long, UserGroupCounter> rMapCache = redissonClient.getMapCache(generateUserGroupQueueKey(userId),
                codec, LocalCachedMapOptions.<Long, UserGroupCounter>defaults().evictionPolicy(EvictionPolicy.LRU)
                        .timeToLive(-1));
rMapCache.trySetMaxSize(5);
       
rMapCache.addListener(new UserGroupEvictListener());

现象是：
当新增的数据超过阈值后，客户接收到了称除事件，但是序列化报错，报错信息：
Caused by: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME: loader:sun.misc.Launcher$AppClassLoader@7591083d
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar:na]
FSTObjectInput.java:247
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:70) ~[redisson-3.9.1.jar:na]
FstCodec.java:70
	at org.redisson.codec.MapCacheEventCodec.decode(MapCacheEventCodec.java:103) ~[redisson-3.9.1.jar:na]
MapCacheEventCodec.java:103
	at org.redisson.codec.MapCacheEventCodec.access$100(MapCacheEventCodec.java:34) ~[redisson-3.9.1.jar:na]
MapCacheEventCodec.java:34
	at org.redisson.codec.MapCacheEventCodec$1.decode(MapCacheEventCodec.java:47) ~[redisson-3.9.1.jar:na]
MapCacheEventCodec.java:47
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:352) ~[redisson-3.9.1.jar:na]
CommandDecoder.java:352
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:413) ~[redisson-3.9.1.jar:na]
CommandDecoder.java:413
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378) ~[redisson-3.9.1.jar:na]
CommandDecoder.java:378
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:78) ~[redisson-3.9.1.jar:na]
CommandPubSubDecoder.java:78
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108) ~[redisson-3.9.1.jar:na]
CommandDecoder.java:108
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
	... 28 common frames omitted
Caused by: java.lang.RuntimeException: class not found CLASSNAME: loader:sun.misc.Launcher$AppClassLoader@7591083d
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:235) ~[fst-2.57.jar:na]
FSTClazzNameRegistry.java:235
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190) ~[fst-2.57.jar:na]
FSTClazzNameRegistry.java:190
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173) ~[fst-2.57.jar:na]
FSTClazzNameRegistry.java:173
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar:na]
FSTStreamDecoder.java:478
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar:na]
FSTObjectInput.java:939
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar:na]
FSTObjectInput.java:347
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar:na]
FSTObjectInput.java:331
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar:na]
FSTObjectInput.java:311
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar:na]
FSTObjectInput.java:245
	... 39 common frames omitted

经过对代码跟踪，定位到问题的原因是由于lua脚本处理逻辑有漏洞导致：

org.redisson.RedissonMapCache.putOperationAsync

                "        if cacheSize > maxSize then" +
                "            local lruItems = redis.call('zrange', lastAccessTimeSetName, 0, cacheSize - maxSize - 1);" +
                "            for index, lruItem in ipairs(lruItems) do" +
                "                if lruItem then" +
                "                    local lruItemValue = redis.call('hget', KEYS[1], lruItem);" +
                "                    redis.call('hdel', KEYS[1], lruItem);" +
                "                    redis.call('zrem', KEYS[2], lruItem);" +
                "                    redis.call('zrem', KEYS[3], lruItem);" +
                "                    redis.call('zrem', lastAccessTimeSetName, lruItem);" +
                "                    if lruItemValue ~= false then " +
                    "                    local removedChannelName = KEYS[7];" +
                    "                    local msg = struct.pack('Lc0Lc0', string.len(lruItem), lruItem, string.len(lruItemValue), lruItemValue);" +
                    "                    redis.call('publish', removedChannelName, msg);" +
                                    "end; " +
                "                end;" +
                "            end" +
                "        end;" + 

                local msg = struct.pack('Lc0Lc0', string.len(lruItem), lruItem, string.len(lruItemValue), lruItemValue);

 由上代码可知，对需要移除的数据未进行struct.unpack操作，修改后：
  				local tt, liv = struct.unpack('dLc0', lruItemValue);"+
                    "                    local msg = struct.pack('Lc0Lc0', string.len(lruItem), lruItem, string.len(liv), liv);" +

问题得以解决，同样的操作在该类中还有好几处，时间问题不再给出。

**Comment by mrniko** [comment]
How can it process invalid data correctly?

**Comment by 26888588** [comment]
> How can it process invalid data correctly?

Sorry, I used the translation software directly. I think it's better for me to use Chinese。

**Comment by mrniko** [comment]
according to stackttrace you use 3.9.1 version and not 3.13.2

**Comment by mrniko** [comment]
Fixed! Thanks for report
