### ISSUE TITLE
Failure on ProxyJCacheConfiguration

### ISSUE THREAD

**Issue by charlesdmir** [redisson/redisson#2945]
Hello,
I have an application on Spring boot 2.2.6 using Caffeine Cache with `@EnableCaching` and `@Cachable` annotations.

```
@Bean
    fun cacheManager(caffeineConfig: CaffeineConfig): CacheManager {
        val caches: MutableList<CaffeineCache> = ArrayList()
        for (cacheMap in caffeineConfig.caches) {
            val entry: Map.Entry<String, String> = cacheMap.entries.iterator().next()
            val cacheName: String = entry.key
            val cacheSpec: CaffeineSpec = CaffeineSpec.parse(entry.value)
            val caffeineCache: CaffeineCache = CaffeineCache(cacheName, Caffeine.from(cacheSpec).recordStats().build())
            caches.add(caffeineCache)
        }

        val simpleCacheManager: SimpleCacheManager = SimpleCacheManager()
        simpleCacheManager.setCaches(caches)
        return simpleCacheManager
    }
```

And I'm trying to integrate redisson 3.12.5 to only read from a Redis cache.
```
@Bean
    @Profile("!dev")
    fun reboundDataCache(): RedissonClient {
        val config = Config()
        config.useClusterServers()
            .addNodeAddress(this.redisHost)
            .setReadMode(ReadMode.MASTER_SLAVE)
            .setTimeout(this.readTimeout)
            .setConnectTimeout(this.connectTimeout)
            .setCheckSlotsCoverage(false)

        return Redisson.create(config)
    }
```
When the app is starting up I'm getting this error and the app fails to start:

```
020-07-28 16:42:14.305 main ERROR org.springframework.boot.SpringApplication Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'meterRegistryPostProcessor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/MetricsAutoConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalJCacheAdvisor' defined in class path resource [org/springframework/cache/jcache/config/ProxyJCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.jcache.interceptor.BeanFactoryJCacheOperationSourceAdvisor]: Factory method 'cacheAdvisor' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheOperationSource' defined in class path resource [org/springframework/cache/jcache/config/ProxyJCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.jcache.interceptor.JCacheOperationSource]: Factory method 'cacheOperationSource' threw exception; nested exception is java.lang.NoSuchFieldError: cacheManager
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:240)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:722)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.expedia.api.customer.ApplicationKt.main(Application.kt:17)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalJCacheAdvisor' defined in class path resource [org/springframework/cache/jcache/config/ProxyJCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.jcache.interceptor.BeanFactoryJCacheOperationSourceAdvisor]: Factory method 'cacheAdvisor' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheOperationSource' defined in class path resource [org/springframework/cache/jcache/config/ProxyJCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.jcache.interceptor.JCacheOperationSource]: Factory method 'cacheOperationSource' threw exception; nested exception is java.lang.NoSuchFieldError: cacheManager
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:109)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:94)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:76)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:347)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalJCacheAdvisor' defined in class path resource [org/springframework/cache/jcacDisconnected from the target VM, address: '127.0.0.1:57790', transport: 'socket'
```

Any clue?

**Comment by mrniko** [comment]
> Failed to instantiate [org.springframework.cache.jcache.interceptor.JCacheOperationSource]: Factory method 'cacheOperationSource' threw exception; nested exception is java.lang.NoSuchFieldError: cacheManager
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)

Make sure you don't have two different versions of spring in classpath

**Comment by charlesdmir** [comment]
I checked, and this is what I have from spring 
```
org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-actuator:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-autoconfigure:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-configuration-processor:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-actuator:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-json:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-log4j2:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-reactor-netty:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-test:jar:2.2.6.RELEASE:test
org.springframework.boot:spring-boot-starter-validation:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-webflux:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-starter:jar:2.2.6.RELEASE:compile
org.springframework.boot:spring-boot-test-autoconfigure:jar:2.2.6.RELEASE:test
org.springframework.boot:spring-boot-test:jar:2.2.6.RELEASE:test
org.springframework.boot:spring-boot:jar:2.2.6.RELEASE:compile
org.springframework.cloud:spring-cloud-commons:jar:2.2.0.RC1:compile
org.springframework.cloud:spring-cloud-context:jar:2.2.0.RC1:compile
org.springframework.cloud:spring-cloud-starter-vault-config:jar:2.2.0.RC1:compile
org.springframework.cloud:spring-cloud-starter:jar:2.2.0.RC1:compile
org.springframework.cloud:spring-cloud-vault-config:jar:2.2.0.RC1:compile
org.springframework.security.oauth:spring-security-oauth2:jar:2.3.7.RELEASE:compile
org.springframework.security:spring-security-config:jar:5.2.2.RELEASE:compile
org.springframework.security:spring-security-core:jar:5.2.2.RELEASE:compile
org.springframework.security:spring-security-crypto:jar:5.2.2.RELEASE:compile
org.springframework.security:spring-security-rsa:jar:1.0.7.RELEASE:compile
org.springframework.vault:spring-vault-core:jar:2.2.0.RC1:compile
org.springframework:spring-aop:jar:5.2.5.RELEASE:compile
org.springframework:spring-beans:jar:5.2.5.RELEASE:compile
org.springframework:spring-context-support:jar:4.3.14.RELEASE:compile
org.springframework:spring-context:jar:5.2.5.RELEASE:compile
org.springframework:spring-core:jar:5.2.5.RELEASE:compile
org.springframework:spring-expression:jar:5.2.5.RELEASE:compile
org.springframework:spring-jcl:jar:5.2.5.RELEASE:compile
org.springframework:spring-test:jar:5.2.5.RELEASE:test
org.springframework:spring-web:jar:5.2.5.RELEASE:compile
org.springframework:spring-webflux:jar:5.2.5.RELEASE:compile
```

**Comment by charlesdmir** [comment]
A colleague found it on my comment the discrepancy on versions:
```
org.springframework:spring-context-support:jar:4.3.14.RELEASE:compile
org.springframework:spring-context:jar:5.2.5.RELEASE:compile
```

**Comment by sunnyding602** [comment]
Thank you soooo much! I had the same issue, after I upgrading spring-context-support and spring-context to the same version the issue disappeared. I will want to figure out where it's trying to creating the ProxyJCacheConfiguration class
