### ISSUE TITLE
MapCache EntryRemovedListener  not working

### ISSUE THREAD

**Issue by KP-story** [redisson/redisson#2948]
Hello,

I've encountered a  bug when using EntryRemovedListener .
       mappCache.addListener(new EntryRemovedListener() {
            @Override
            public void onRemoved(EntryEvent event) {
                System.out.println("onRemoved name " + event.getKey());

            }
When i run test , i got the errors .
Caused by: java.io.CharConversionException: Invalid UTF-32 character 0x1ff0000 (above 0x0010ffff) at char #2, byte #11)
	at com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:195)
	at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:158)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:250)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2378)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:672)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4620)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4469)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3471)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:95)
	at org.redisson.codec.BaseEventCodec.decode(BaseEventCodec.java:53)
	at org.redisson.codec.MapCacheEventCodec$1.decode(MapCacheEventCodec.java:42)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:422)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:71)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:91)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 common frames omitted

But, another listener as EntryExpiredListener works well

My setup:
redisson 3.13.2 run on window with oracle java 11.0.7
Redis version=6.0.5 on docker

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2941
