### ISSUE TITLE
Error : org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries, with version 3.13.2 and 3.13.1.

### ISSUE THREAD

**Issue by ajaygl** [redisson/redisson#2953]
**Expected behavior**

We are using Redisson for AWS elasticache cluster and established connection should work consistently without any exception or error.

**Actual behavior**

Redisson client fails with the following exception  randomly , have to restart the application. 

org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: NA:6379 Disconnected hosts: [NA:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:254)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:480)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:641)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:643)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:243)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Steps to reproduce or test case**

We are using redis in our multiple microservices and  the above exception happens very randomly in any of the services after some days.

**Redis version**
   
    AWS elastic cluster.

**Redisson version**
   
   Tried both 3.13.1 and 3.13.2 but same issue .

**Redisson configuration**
                
               Config config = new Config();
		config.useClusterServers()
				.setMasterConnectionMinimumIdleSize(10)
				.setMasterConnectionPoolSize(10)
				.setSlaveConnectionPoolSize(10)
				.setSlaveConnectionMinimumIdleSize(10)
				.addNodeAddress(REDIS_URL_PREFIX + redisUrl + ":" + redisPort);

**Comment by mrniko** [comment]
Try this solution: 

https://github.com/redisson/redisson/issues/2881#issuecomment-661838317

**Comment by mrniko** [comment]
Could you set logging level `debug` for `org.redisson` package and share output from Redisson start moment up to moment of error?

**Comment by ajaygl** [comment]
Hi Mrniko,
Thanks for responding, this is really difficult to reproduce as it happens randomly after some days,
so have error log only, we see the comment that this been fixed https://github.com/redisson/redisson/issues/2750 with latest release 3.13.2 but still we see the same issue.  Could you please help us in resolving this.

**Comment by mrniko** [comment]
@cwj-bot 

Could you share log output?

**Comment by mrniko** [comment]
do you have some error like `java.lang.IllegalStateException: Can't find` in logs?

**Comment by mrniko** [comment]
I see it. Can you also find error like `java.lang.IllegalStateException: Can't find` in logs?

**Comment by mrniko** [comment]
@cwj-bot 

https://github.com/redisson/redisson/issues/2953#issuecomment-668413362

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2932

**Comment by ajaygl** [comment]
@mrniko  you mean in next release  3.13.3 will have this fix ? Please confim !

**Comment by mrniko** [comment]
yes

**Comment by ajaygl** [comment]
@mrniko Thanks for your help !!!  Will try with 3.13.3.
