### ISSUE TITLE
JCache removeAsync throws NPE when remove fails

### ISSUE THREAD

**Issue by wilkina** [redisson/redisson#2963]
Test setup:

**Expected behavior**
Failure reported as original failure cause (RedisTimeoutException)

**Actual behavior**
Null pointer when Redisson updates stats bean
Notice the explicit null argument https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/misc/RedissonPromise.java#L183
Then the boolean unboxing in the listener https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/jcache/JCache.java#L1720 
This causes NullPointerException

**Steps to reproduce or test case**
Have several JCache caches. Start application. Suspend Redis server to force connection timeouts. Call removeAll() on an existing JCache

**Redis version**
6.0.4

**Redisson version**
3.13.3

**Redisson configuration**
Default SingleServer connecting to localhost with FstCodec

**Comment by mrniko** [comment]
Please share exception stacktrace

**Comment by wilkina** [comment]
Note this stack trace is from 3.13.1 as I'm not in an easy position to repro under 3.13.3 right now.

An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$34/275529226.operationComplete()
java.lang.NullPointerException: null
        at org.redisson.jcache.JCache.lambda$removeAsync$33(JCache.java:1720) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[redisson-3.13.1.jar!/:3.13.1]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.jcache.JCache.lambda$waitSync$7(JCache.java:661) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[redisson-3.13.1.jar!/:3.13.1]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:469) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:461) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:445) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:163) ~[redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[redisson-3.13.1.jar!/:3.13.1]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) [redisson-3.13.1.jar!/:3.13.1]
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:228) [redisson-3.13.1.jar!/:3.13.1]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.50.Final.jar!/:4.1.50.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

**Comment by mrniko** [comment]
Fixed! Thanks for report
