### ISSUE TITLE
CommandPubSubDecoder: Unable to decode data & NPE

### ISSUE THREAD

**Issue by idler41** [redisson/redisson#2964]
o.r.c.handler.ErrorsLoggingHandler - Exception occured. Channel: [id: xx, L:/XX.XX.XX.XX:XX - R:r-XX/XX.XX.XX.XX:6379]
    io.netty.handler.codec.DecoderException: java.lang.NullPointerException
    	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
    	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NullPointerException: null
    	at org.redisson.client.handler.CommandPubSubDecoder.messageDecoder(CommandPubSubDecoder.java:212)
    	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:426)
    	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
    	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:71)
    	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
    	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:91)
    	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
    	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
    	
    o.r.c.handler.CommandPubSubDecoder - Unable to decode data. channel: [id: xx, L:/XX.XX.XX.XX:XX - R:r-XX/XX.XX.XX.XX:6379], reply: ReplayingDecoderByteBuf(ridx=94, widx=94)
    java.lang.NullPointerException: null
        at org.redisson.client.handler.CommandPubSubDecoder.messageDecoder(CommandPubSubDecoder.java:212)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:426)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:71)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:91)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
    	
Redis version

5.0

Redisson version

3.13.2

Redisson configuration

    @Configuration
    public class RedissonClientConfig {
        @Value("${act.redis.host}")
        private String host;
    
        @Value("${act.redis.port}")
        private String port;
    
        @Value("${act.redis.password:}")
        private String password;
    
        @Bean
        public RedissonClient redissonClient() {
            Config config = new Config();
            SingleServerConfig singleServerConfig = config.useSingleServer().setAddress("redis://" + host + ":" + port);
            if (StringUtils.isNotEmpty(password)) {
                singleServerConfig.setPassword(password);
            }
            //序列化方式设置为fastJson
            config.setCodec(new FastJsonCodec());
            return Redisson.create(config);
        }
    
    }
    
    public class FastJsonCodec extends BaseCodec {
        private final Encoder encoder = in -> {
            ByteBuf out = ByteBufAllocator.DEFAULT.buffer();
            try {
                ByteBufOutputStream os = new ByteBufOutputStream(out);
                JSON.writeJSONString(os, in,SerializerFeature.WriteClassName);
                return os.buffer();
            } catch (IOException e) {
                out.release();
                throw e;
            } catch (Exception e) {
                out.release();
                throw new IOException(e);
            }
        };
    
        private final Decoder<Object> decoder = (buf, state) ->
                JSON.parseObject(new ByteBufInputStream(buf), Object.class);
    
        @Override
        public Decoder<Object> getValueDecoder() {
            return decoder;
        }
        @Override
        public Encoder getValueEncoder() {
            return encoder;
        }
    }

**Comment by mrniko** [comment]
Can you reproduce it with default codec?

**Comment by idler41** [comment]
sorry, I can't reproduce this problem because it comes up occasionally

**Comment by idler41** [comment]
> Can you reproduce it with default codec?

sorry, I can't reproduce this problem because it comes up occasionally

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by xwqsean** [comment]
redisson升级到3.18.1也出现了这个问题？

**Comment by wangchao950202** [comment]
@mrniko @mrniko 
Why does it appear as empty?
![image](https://github.com/user-attachments/assets/703bb20d-06bc-4321-9d84-94dcaa996612)

**Comment by wangchao950202** [comment]
@idler41 Why does it appear as empty?
![image](https://github.com/user-attachments/assets/2bfcf28a-00ad-48d9-9c9d-db019566a519)

**Comment by mrniko** [comment]
@wangchao950202 

I couldn't reproduce it
