### ISSUE TITLE
Redisson throw an RedissonShutdownException 

### ISSUE THREAD

**Issue by eng7miky** [redisson/redisson#2972]
Hi, 

I am facing problem in redisson after a while of running the application. it threw an exception with the following stack trace.
![image](https://user-images.githubusercontent.com/2690942/89841035-375fc780-db72-11ea-881f-da62fc521d92.png)
and it failed to recover from that state untill the application is restarted. we also found another exception with the same stack trace
`org.redisson.RedissonShutdownException: Redisson is shutdown
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:109)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:610)
        at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:595)
        at org.redisson.RedissonLock.isHeldByThread(RedissonLock.java:543)
        at org.redisson.RedissonLock.isHeldByCurrentThread(RedissonLock.java:538)
`

Redisson version: 3.13.2

can anyone help me how shall we recover from this problem without restarting application? also what is the cause of that problem?

**Comment by mrniko** [comment]
> can anyone help me how shall we recover from this problem without restarting application? 

Find the code where you call `Redisson.shutdown` method this is the cause.

**Comment by UzimakiNaruto** [comment]
same error 🐶

**Comment by mrniko** [comment]
Seems you invoke RedissonClient shutdown somethere. Also make sure you use 3.12.1+ in classpath.

**Comment by kishoreJeyaMurugesan** [comment]
how to resolve the Redisson shutdown error
