### ISSUE TITLE
Tomcat session deserialisation error for object of Vector type

### ISSUE THREAD

**Issue by hnadackalEV** [redisson/redisson#2989]
Redis 4
Tomcat 9
Redisson 3.13.3

The session details are maintained in a  Vector class which doesn't have a default constructor

Sample class below:

public class Test1 extends Vector implements Serializable
{
                
  private String cName;
 
                public Test1(String sName)      # This is the only constructor
                {
                                c = sName;
                }
}

While deserialising session data , we are getting following error

[redisson-netty-2-12] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0x62b212db, L:/192.168.15.3:51412 - R:redis-svc/[ip:port], reply: ReplayingDecoderByteBuf(ridx=187, widx=416), command: (HGETALL), params: [redisson:tomcat_session:8F92D92D6DFCA04B858558540BB52535]
java.io.IOException: java.lang.InstantiationException: Test1
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
        at org.redisson.codec.FstCodec$1.decode(FstCodec.java:228)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:428)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393)
…
Caused by: java.lang.InstantiationException: Test1
        at java.lang.Class.newInstance(Class.java:427)
        at org.nustaq.serialization.serializers.FSTCollectionSerializer.instantiate(FSTCollectionSerializer.java:83)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:501)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)

**Comment by hnadackalEV** [comment]
Raised as an issue
