### ISSUE TITLE
Redis tomcat session deserialisation fails for vector without default constructor

### ISSUE THREAD

**Issue by hnadackalEV** [redisson/redisson#2990]
**Expected behavior**

We are using RedissonSessionManager to store tomcat sessions to Redis. When session object contains object of type Java Vector  without default constructor, it  throws a deserialisation exception

[redisson-netty-2-12] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0x62b212db, L:/192.168.15.3:51412 - R:redis-svc/[ip:port], reply: ReplayingDecoderByteBuf(ridx=187, widx=416), command: (HGETALL), params: [redisson:tomcat_session:8F92D92D6DFCA04B858558540BB52535]
java.io.IOException: java.lang.InstantiationException: Test1
at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
at org.redisson.codec.FstCodec$1.decode(FstCodec.java:228)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:384)
at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:428)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393)
…
Caused by: java.lang.InstantiationException: Test1
at java.lang.Class.newInstance(Class.java:427)
at org.nustaq.serialization.serializers.FSTCollectionSerializer.instantiate(FSTCollectionSerializer.java:83)
at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:501)
at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)

**Actual behavior**
Session should get stored and retrieved from redis

**Steps to reproduce or test case**
The session details are maintained in a Vector class which doesn't have a default constructor. When we try to add this to redis session it fails

Sample class below:

public class Test1 extends Vector implements Serializable
{

private String cName;

            public Test1(String sName)      # This is the only constructor
            {
                            cName = sName;
            }
}
**Redis version**

**Redisson version**
Redis 4

**Redisson configuration**

singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://IP:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Try to use `MarshallingCodec` or `SerializationCodec` instead.
