### ISSUE TITLE
CastException when doing healthcheck with spring

### ISSUE THREAD

**Issue by axelczk** [redisson/redisson#3001]
**Expected behavior**
UP

**Actual behavior**
DOWN because of the exception

`2020-08-21 15:02:50.698  WARN 1 --- [oundedElastic-1] o.s.b.a.r.RedisReactiveHealthIndicator   : Redis health check failed

java.lang.ClassCastException: class com.sun.proxy.$Proxy122 cannot be cast to class org.redisson.Redisson (com.sun.proxy.$Proxy122 and org.redisson.Redisson are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @1d56ce6a)
        at org.redisson.spring.data.connection.RedissonConnectionFactory.getReactiveConnection(RedissonConnectionFactory.java:149) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499) ~[spring-cloud-context-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.redisson.spring.data.connection.RedissonConnectionFactory$$EnhancerBySpringCGLIB$$503ddcc5.getReactiveConnection(<generated>) ~[redisson-spring-data-23-3.13.2.jar!/:3.13.2]
        at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85) ~[reactor-core-3.3.9.RELEASE.jar!/:3.3.9.RELEASE]
        at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:225) ~[reactor-core-3.3.9.RELEASE.jar!/:3.3.9.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.9.RELEASE.jar!/:3.3.9.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.9.RELEASE.jar!/:3.3.9.RELEASE]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]`

**Steps to reproduce or test case**
Create a project that use org.springframework.cloud.context.config

`@Configuration
public class RedisConfig {

    @Autowired
    private BeanFactory factory;

    @Bean
    @RefreshScope
    public RedisConfigurationProperties properties() {
        return new RedisConfigurationProperties();
    }

    @Bean
    @RefreshScope
    public RedissonClient redissonClient(RedisConfigurationProperties props) {
        Config config = new Config();
        config.useSingleServer().setAddress(String.format("redis://%s:%s", props.getHost(), props.getPort()));

        RedissonClient redissonClient = Redisson.create(config);

        return redissonClient;
    }

    @Bean
    @RefreshScope
    public RedissonConnectionFactory redissonConnectionFactory(RedissonClient redisson) {
        return new RedissonConnectionFactory(redisson);
    }
}`

Do a get on /actuator/health

**Redisson version**
3.13.3, with redisson-spring-boot-starter (3.13.3) and redisson-spring-data-23 (3.13.3)

**Redisson configuration**
Single server 
    host: localhost
    port: 6379

**Comment by mrniko** [comment]
Fixed! Thanks for report
