### ISSUE TITLE
Running into RedisTimeoutException when using Redisson, ElastiCache in AWS lambda when high traffic comes in

### ISSUE THREAD

**Issue by Weixin8999** [redisson/redisson#3009]
Hi

We are using Redisson to connect to ElastiCache to get RBucket in the AWS lambda. The trigger of the AWS lambda is a SQS(with batch size 10). The logic for this lambda is to get the RBucket for each message from SQS.(Redisson.get(BUCKET_KEY))

When traffic is low, no exception happens(***TPS is around 50***), but when traffic becomes higher(**Max TPS is around 900**), the invocation and concerencent number for lambda function is getting higher, and then some RedisTimeoutExceptions are thrown by Redisson. Therefore, the backlog of the SQS is increasing. 

Here is the detailed Exception log when executing Redisson.get():
```
2020-08-20 00:11:57 ##redisson-netty-1-3 ERROR ReplicatedConnectionManager:193 - Command execution timeout for default-replication-group.no4.ng.0001.euw1.cache.amazonaws.com/10.0.14.79:6379
org.redisson.client.RedisTimeoutException: Command execution timeout for default-replication-group.no2m94.ng.0001.euw1.cache.amazonaws.com/10.0.14.79:6379
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:193) [Redisson-3.x.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-all-4.1.jar:4.1.48.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [netty-all-4.1.jar:4.1.48.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-all-4.1.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

Here is the current Redisson Config, the other 
```
final Config config = new Config();
config.setCodec(new JsonJacksonCodec(new ObjectMapper()));
config.setNettyThreads(64);
config.useReplicatedServers()
    .setReadMode(ReadMode.SLAVE)
    .setTimeout(60000)
    .addNodeAddress(redisUrl);
return Redisson.create(config);
```

Here are some question I want to get cleared:

1. I'm wondering what the detailed root cause for ```org.redisson.client.RedisTimeoutException: Command execution timeout for ```. Is that means the Redisson config```timout``` is shorter than expected? But I think purely increasing the timeout seems cannot scale up the capacity to handle the high TPS.

2. To resolve this issue, how can I modify the Redisson Config to handle such a high traffic? I followed the [Redisson FAQ](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it) to scale up the config, but not sure how to come up with a suitable config.

**Comment by mrniko** [comment]
> I followed the Redisson FAQ to scale up the config, but not sure how to come up with a suitable config.

It depends on specific case.

**Comment by Weixin8999** [comment]
Thank you for the reply. I'll try to update the Redisson version. 

But I'm still wondering what the real root cause for this type of ```RedisTimeoutException: Command execution timeout for <address>```, which will definitely help me to tune the configuration for Redisson client.

**Comment by mrniko** [comment]
Here is the [ReliableQueue](https://redisson.pro/docs/data-and-services/queues/#reliable-queue) object you could use instead of SQS
