### ISSUE TITLE
RedisConnectionException while retrieving from redis

### ISSUE THREAD

**Issue by eng7miky** [redisson/redisson#3019]
Faced a problem while using redisson client after random period of time. the generated stack trace is: 
`org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: /10.183.127.25:6379 Disconnected hosts: [k-dtce-rb-prd42/10.183.127.
25:6379]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218)
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:254)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:499)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:641)
        at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:640)
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115)
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:243)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
$$$`
the problem that the client does not recover until the application is restarted while another instances using that client is working normally.

Config:
redis.bulk_size=10000
redis.timeout=3000
redis.connection.timeout=10000
redis.idle.connection.timeout=10000
redis.retry.attempts=3
redis.retry.interval=1500
redis.batch.retry.attempts=3
redis.batch.retry.interval=1500
redis.batch.response.timeout=3000
redis.lock.wait.time.milliseconds=1000
redis.lock.lease.time.milliseconds=1000
redis.netty.threads=32
## Redis Cluster Configs ##
redis.cluster.master.pool.size=64
redis.cluster.slave.pool.size=64
redis.cluster.master.minimum.idle.size=24
redis.cluster.slave.minimum.idle.size=24
redis.ping.connection.interval=2000
redis.keep.alive=true
redis.tcp.no.delay=true

CLient: redisson 3.13.2

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2932
