### ISSUE TITLE
RateLimiter Bug on 3.13.3 : bad argument #2 to 'unpack' (data string too short)

### ISSUE THREAD

**Issue by ACBingo** [redisson/redisson#3025]
**My Code**
```
private RRateLimiter rt;

@PostConstruct
 public void init(){
     rt = redissonClient.getRateLimiter("rt2");
     rt.trySetRate(RateType.OVERALL, 100, 5, RateIntervalUnit.SECONDS);
 }

@GetMapping("")
    public void test(){

        System.out.println(rt.availablePermits());

        rt.acquire(1);

        System.out.println(rt.availablePermits());
    }
```

**Expected behavior**

**Actual behavior**

first call test() function， works fine， but after 5 SECONDS（after one period）， will throw exception

```
org.redisson.client.RedisException: ERR Error running script (call to f_a953e1748e38137c3168a683556aa561bd05b340): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x36f2cda8, L:/10.2.47.198:60323 - R:fenbi-notify-push-redis-dev.redis.rds.aliyuncs.com/10.13.160.82:6379] command: (EVAL), params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 5, rt2, {rt2}:value, {rt2}:value:f45a9de8-95b9-47f1-aef2-759c37d9f60a, {rt2}:permits, {rt2}:permits:f45a9de8-95b9-47f1-aef2-759c37d9f60a, 1599018405084]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365) ~[redisson-3.13.3.jar:3.13.3]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[redisson-3.13.3.jar:3.13.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[redisson-3.13.3.jar:3.13.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[redisson-3.13.3.jar:3.13.3]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Steps to reproduce or test case**

**Redis version**

**Redisson version**

         <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-data-18</artifactId>
            <version>3.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.13.3</version>
        </dependency>

Only 3.13.3 have this problem
There is no problem on 3.13.2

**Redisson configuration**

config.setCodec(JsonJacksonCodec.INSTANCE);

**Comment by mrniko** [comment]
Unable to reproduce the issue. Here is my test:

```java
        RRateLimiter rt = redisson.getRateLimiter("rt2");
        rt.trySetRate(RateType.OVERALL, 100, 5, RateIntervalUnit.SECONDS);

        rt.acquire(1);

        Thread.sleep(6000);

        rt.acquire(1);
```

**Comment by ACBingo** [comment]
try this
```
        RRateLimiter rt = redissonClient.getRateLimiter("rt3");
        rt.trySetRate(RateType.OVERALL, 100, 5, RateIntervalUnit.SECONDS);

        System.out.println(rt.availablePermits());

        rt.acquire(1);

        Thread.sleep(6000);

        System.out.println(rt.availablePermits());
```

the cause maybe by rt.availablePermits()

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by ACBingo** [comment]
Thanks for your excellent work!

**Comment by adaboinanagarro** [comment]
this is not fixed i still see the issue in 3.16.7 version

**Comment by mrniko** [comment]
@adaboinanagarro 

Can you share sample code to reproduce?

**Comment by MorningTider** [comment]
This bug also occurred in version 3.17.1
