### ISSUE TITLE
 java.lang.String cannot be cast to [B thanks for help

### ISSUE THREAD

**Issue by theodore414** [redisson/redisson#3029]
Exception in thread "redisson-3-22" java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at org.redisson.spring.data.connection.RedissonSubscription$2.onPatternMessage(RedissonSubscription.java:85)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:84)
	at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$0(CommandPubSubDecoder.java:181)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
How to reproduce this issue?

**Comment by theodore414** [comment]
> How to reproduce this issue?
I think that's a specific situation.

our project integrated Spring Security 5.3.4.RELEASE，redis 2.3.0 release and redisson 3.13.4.
we use Spring Security intercept and authenticate login users. 
We suspect that it is a problem in the serialization of string after the frame sent a message after the sessionid expired.

I think maybe something wrong in here.
    @Bean
    public SpringSessionBackedSessionRegistry sessionRegistry() {
        return new SpringSessionBackedSessionRegistry(new RedissonSessionRepository(redissonClient,eventPublisher));
    }

Please have a look, thank you for help.

**Comment by theodore414** [comment]
we modify RedissonSubscription class code that problem fix

@Override
    protected void doPsubscribe(byte[]... patterns) {
        RedisPubSubListener<?> listener2 = new BaseRedisPubSubListener() {
            @Override
            public void onPatternMessage(CharSequence pattern, CharSequence channel, Object message) {
                byte[] b ;
                if(message instanceof String){
                    b = ((String)message).getBytes();
                }else{
                    b = (byte[])message;
                }
                DefaultMessage msg = new DefaultMessage(((ChannelName)channel).getName(), b);
//                DefaultMessage msg = new DefaultMessage(((ChannelName)channel).getName(), (byte[])message);
                getListener().onMessage(msg, ((ChannelName)pattern).getName());
            }
        };

**Comment by mrniko** [comment]
Fixed

**Comment by ergouliang** [comment]
Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to [B
on org.redisson.spring.data.connection.RedissonSubscription#doSubscribe

**Comment by mrniko** [comment]
@ergouliang 

Which Redisson PRO version do you use?
Can you share code example to reproduce it?

**Comment by mrniko** [comment]
How to reproduce it?
