### ISSUE TITLE
CommandDecoder - Unable to decode data. reply: $X

### ISSUE THREAD

**Issue by annapurnaTechmojo** [redisson/redisson#3039]
[redis.txt](https://github.com/redisson/redisson/files/5189101/redis.txt)
```
[ERROR] 2020-09-02 07:59:46.207 [redisson-netty-4-4] [,] CommandDecoder - Unable to decode data. reply: $768
���^B{"email":"********.******@*****.COM","firstName":"**** ******","lastName":"******"}
, channel: [id: 0xb9754a6f, L:/*.*.*.*:36479 - R:redis.com/*.*.*.*:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@46b21510(failure: java.util.concurrent.CancellationException)], command=(EVAL), params=[local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, ********.******@*****.COM, redisson__timeout__set:{********.******@*****.COM}, redisson__idle__set:{********.******@*****.COM}, redisson__map_cache__last_access__set:{********.******@*****.COM}, {********.******@*****.COM}:redisson_options, 1599029983066, PooledUnsafeDirectByteBuf(freed)], codec=org.redisson.codec.FstCodec]
java.util.concurrent.CancellationException: null
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263) ~[?:1.8.0_141]
        at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:239) ~[redisson-3.10.0.jar:?]
        at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:887) ~[redisson-3.10.0.jar:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]```


Observing Similar Errors in Our Logs since few days
Attached a file with similar errors

Please help me with this

Redisson Version - 
                 <dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-data-20</artifactId>
			<version>3.10.0</version>
		</dependency>
We have a single server config
Redisson Yaml
```{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "password":"*****************",
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://redis.com:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.codec.FstCodec"
   },
   "transportMode":"NIO"
}```
Thank You

**Comment by mrniko** [comment]
It's obvious that you store in json format instead of fst - default codec for Redisson 3.10.0
