### ISSUE TITLE
Encountering NullPointerException when a bunch of requests hit the web app in short period

### ISSUE THREAD

**Issue by Ethns** [redisson/redisson#3047]
When a bunch of requests hit the web app in short period (e.g. 2000 requests  in 5 min), tomcat-redisson-9 throws NPE attached on the bottom, the issue refers to below line of code.
https://github.com/redisson/redisson/blob/9579ee735a7fc57a0461c1e4c321954659b26d87/redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/UpdateValve.java#L56
I've tried with various versions of redisson-tomcat-9(3.12.3, 3.12.4, 3.13.0, 3.13.4), but the issue stick to below line of code.

redisson version: 3.13.4
redisson-tomcat-9 version: 3.13.4

```
[http-nio-8080-exec-4] ERROR org.apache.coyote.http11.Http11Processor - Error processing request java.lang.NullPointerException: null
  at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:56) [redisson-tomcat-9-3.13.0.jar:3.13.0]
  at org.apache.catalina.connector.CoyoteAdapter.service (CoyoteAdapter.java:343) [catalina.jar:9.0.33]
  at org.apache.coyote.http11. Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
  at org.apache.coyote. AbstractProcessorLight.process(AbstractProcessorLight.java:65) [ tomcat-coyote.jar:9.0.33]
  at org.apache.coyote. AbstractProtocol$connectionHandler.process(AbstractProtocol.java:868) [ tomcat-coyote.jar:9.0.33]
  at org.apache.tomcat.util.net.NioEndpoint SocketProcessor.doRun(NioEndpoint.java:1594) [ tomcat-coyote.jar:9.0.33]
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [ tomcat-coyote.jar:9.0.33]
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128) [?:?]
  at java.util.concurrent.ThreadPoolExecutor $Worker.run(ThreadPoolExecutor.java:628) [?:?]
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [ tomcat-util.jar:9.0.33]
  at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mrniko** [comment]
please rollback to 3.13.3 version while I'm fixing this

**Comment by mrniko** [comment]
Please try version attached

[redisson-tomcat-9-3.13.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5212250/redisson-tomcat-9-3.13.5-SNAPSHOT.jar.zip)

**Comment by Ethns** [comment]
Thanks @mrniko, is it a known issue?

**Comment by mrniko** [comment]
no

**Comment by Ethns** [comment]
hi @mrniko
I've tried the version attached, but error still exists

redisson version: 3.13.4
redisson-tomcat-9 version: 3.13.5-SNAPSHOT
``` 
13-Sep-2020 14:16:09.356 [http-nio-8080-exec-9] SEVERE org.apache.coyote.http11.Http11Processor.service Error processing request 
java.lang.NullPointerException
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:58)
	at org.apache.catalina.connector.CoyoteAdapter.service (CoyoteAdapter.java:343)
	at org.apache.coyote.http11. Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote. AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote. AbstractProtocol$connectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor $Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:834)		
```
may I know what 2 lines did you add in UpdateValve?

**Comment by mrniko** [comment]
`request.getContext()` is null. Is there any code I could use to reproduce it?

**Comment by Ethns** [comment]
@mrniko the issue still exists after i switched to the latest TC9 (9.0.37)
The step to reproduce it is just accessing any non-existent URL path as highlighting on below screenshot:
![image](https://user-images.githubusercontent.com/12314312/93015009-179c4300-f5f9-11ea-9a69-1eef52ea3fe6.png)

**Comment by mrniko** [comment]
Fixed
