### ISSUE TITLE
With Fst Codec during readall java.io.IOException: java.lang.RuntimeException: unable to find class for code 50

### ISSUE THREAD

**Issue by dahiyahimanshu** [redisson/redisson#3052]
**Expected behavior**
Junit should pass
**Actual behavior**
`2020-09-15 16:28:06,812 ERROR org.redisson.client.handler.CommandDecoder [redisson-netty-1-6]: Unable to decode data. channel: [id: 0x2d695109, L:/127.0.0.1:43810 - R:127.0.0.1/127.0.0.1:6399], reply: ReplayingDecoderByteBuf(ridx=252, widx=252), command: (SMEMBERS), params: [bucket-fst]
java.io.IOException: java.lang.RuntimeException: unable to find class for code 50
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar:na]
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:164) ~[redisson-3.10.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368) [redisson-3.10.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:412) [redisson-3.10.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377) [redisson-3.10.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:201) [redisson-3.10.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:143) [redisson-3.10.3.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122) [redisson-3.10.3.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) [netty-codec-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
Caused by: java.lang.RuntimeException: unable to find class for code 50
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:180) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar:na]
	... 37 common frames omitted`
**Steps to reproduce or test case**
`package com.mycomosi.eaa.alarm.propagation.infrastructure.chain

import java.util

import com.mycomosi.eaa.common.domain.topology._
import com.mycomosi.eaa.common.infrastructure.redis.RedisClientPool
import com.mycomosi.eaa.common.infrastructure.redis.v2_1.{NodeInstanceRto, RelationshipInstanceRto, TopologyInstanceRto}
import com.mycomosi.eaa.common.infrastructure.topology.cache.Converter
import org.junit.runner.RunWith
import org.nustaq.serialization.FSTConfiguration
import org.redisson.Redisson
import org.redisson.config.Config
import org.scalatest.junit.JUnitRunner
import org.scalatest.{BeforeAndAfter, BeforeAndAfterAll, FlatSpec, Matchers}
import redis.embedded.RedisServer

import scala.collection.JavaConverters._

@RunWith(classOf[JUnitRunner])
class FstCodecTest extends FlatSpec with Matchers with BeforeAndAfter with BeforeAndAfterAll {
  val redisUrl = "redis://127.0.0.1:6399"
  val redisServer = RedisServer.builder()
    .port(6399)
    .setting("bind 127.0.0.1") // secure + prevents popups on Windows
    .setting("maxmemory 128M")
    .build();

  def toRto(o: NodeInstance): NodeInstanceRto = {
    new NodeInstanceRto(o.id, o.name,
      o.ik,
      o.nodeTemplateId,
      o.nodeTemplateName)
  }

  private def toRto(o: RelationshipInstance): RelationshipInstanceRto = {
    val attributes = new util.HashMap[String, String]()
    o.attributes.foreach(x => attributes.put(x._1, x._2))
    new RelationshipInstanceRto(o.srcId, o.dstId, o._relationType, attributes)
  }

  def toRto(o: TopologyInstance): TopologyInstanceRto = {
    //To avoid issue on FST serializer of Class scala.collection.convert.Wrappers$MapWrapper does not implement Serializable or externalizable
    val nodeInstances = new java.util.ArrayList[NodeInstanceRto]()
    o.nodeInstances.foreach(x => nodeInstances.add(toRto(x)))

    val relationShips = new java.util.ArrayList[RelationshipInstanceRto]()
    o.relationshipInstances.foreach(x => relationShips.add(toRto(x)))

    new TopologyInstanceRto(o.id,
      o.startDate,
      o.endDate,
      o.topologyTemplateId,
      o.version,
      nodeInstances,
      relationShips)
  }

  def createConfig: Config = {
    val conf: FSTConfiguration = FSTConfiguration.createDefaultConfiguration()
    conf.registerClass(List(classOf[TopologyInstanceRto]).toArray: _*)
    val fstCodec = new org.redisson.codec.FstCodec(conf)
    val config = new Config()
    config.useSingleServer.setAddress(redisUrl)
    config.setCodec(fstCodec)
    config
  }

  override def beforeAll() {
    redisServer.start
  }

  override def afterAll() {
    RedisClientPool.shutdown
    redisServer.stop
  }

  "Measure Topology set get with different Codecs" should " correctly serialize and deserialize and provide measurement" in {
    val redisClient = Redisson.create(createConfig)

    val nodeInstance2_1 = NodeInstance("nodeId4", "nodeName4", "ik", "mocId2", "mocName2")
    val rel1 = RelationshipInstance("nodeId1", "nodeId2", 3.shortValue(), Map[String, String]())
    val version = "version"
    val topo2 = TopologyInstance("Topo2", 0, 10L, "mocId2", version, nodeInstance2_1:: Nil, rel1:: Nil)

    var rtos = (topo2 :: Nil).map(Converter.toRto)

    val b = redisClient.getSet[TopologyInstanceRto]("bucket-fst")
    b.addAll(rtos.toList.asJava)
    b.readAll()
  }

}`
**Redis version**
4.0

**Redisson version**
3.10.3

**Redisson configuration**
single

**Comment by mrniko** [comment]
Try to use MarshallingCodec instead
