### ISSUE TITLE
Fail to start with Tomcat8

### ISSUE THREAD

**Issue by bianchi2** [redisson/redisson#3053]
I followed instructions for Tomcat, copied two jars to lib dir, edited context.xml, created conf.yaml, however, keep getting:

```
15-Sep-2020 11:38:07.402 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal The session manager failed to start
 org.apache.catalina.LifecycleException: Failed to start component [org.redisson.tomcat.RedissonSessionManager[/coreweb]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5253)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1852)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
	at org.redisson.config.Config.fromJSON(Config.java:584)
	at org.redisson.tomcat.RedissonSessionManager.buildClient(RedissonSessionManager.java:342)
	at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:234)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
```
Do I need add more libs to classpath?

**Comment by mrniko** [comment]
com.fasterxml.jackson.core.JsonFactory is already included in `redisson-all.jar`
