### ISSUE TITLE
reddison can not stop my program

### ISSUE THREAD

**Issue by taagholi** [redisson/redisson#3109]
I wrote a program to test the connection to Redis, it successfully connected to Radis but the program does not stop in the end.

redisson.yaml
```properties
singleServerConfig:
idleConnectionTimeout: 10000
connectTimeout: 10000
timeout: 3000
retryAttempts: 3
retryInterval: 1500
password: null
subscriptionsPerConnection: 5
clientName: null
address: "redis://127.0.0.1:6379"
subscriptionConnectionMinimumIdleSize: 1
subscriptionConnectionPoolSize: 50
connectionMinimumIdleSize: 24
connectionPoolSize: 64
database: 0
dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SnappyCodec> {}
transportMode: "NIO" 
```

my dependency in Gradle:
```Gradle
'org.redisson:redisson-hibernate-52:3.13.5'
```

when Get thread dump, my console:
```console
"redisson-netty-2-24@7998" prio=5 tid=0x2e nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(WindowsSelectorImpl.java:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked <merged>(a sun.nio.ch.WindowsSelectorImpl)
	  - locked <merged>(a java.util.Collections$UnmodifiableSet)
	  - locked <merged>(a io.netty.channel.nio.SelectedSelectionKeySet)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:805)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:748) 
```

I think the problem is in netty, but my netty version is final (4.1.52)

**Comment by mrniko** [comment]
Is there example code to reproduce it?

**Comment by taagholi** [comment]
xxx

**Comment by taagholi** [comment]
Hiberantate Configuration:
```java
            configuration.setProperty(Environment.USE_SECOND_LEVEL_CACHE, "true");
            configuration.setProperty(Environment.CACHE_REGION_FACTORY, org.redisson.hibernate.RedissonRegionFactory.class.getName());
            configuration.setProperty(Environment.CACHE_REGION_PREFIX, "hibernate");
            configuration.setProperty("hibernate.cache.redisson.config", "redis/redisson.yaml");
```
Entity
```java

import com.fanap.domain.loan.basicinfo.centralinfo.RelationType;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;


@Entity
@Cacheable
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name="t_LoanTopic")
public class LoanTopic extends com.fanap.domain.shared.Entity{

    private String modificationDate;
    private String name;
    private Integer percent;
    private String topicCode;

    public LoanTopic() {
    }
    
    @Column(name="c_modificationDate")
    public String getModificationDate() {
        return this.modificationDate;
    }

    public void setModificationDate(String modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="c_name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="c_percent")
    public Integer getPercent() {
        return this.percent;
    }

    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    
    @Column(name="c_topicCode")
    public String getTopicCode() {
        return this.topicCode;
    }

    public void setTopicCode(String topicCode) {
        this.topicCode = topicCode;
    }
    

}
```

```java
public static void main(String[] args) throws Exception {
        log.info("start");
        HibernateSession session = HibernateManager.createSession();
        try {
            LoanTopic loanTopic = (LoanTopic) session.load(LoanTopic.class, 18416868581L);
        } finally {
            session.close();
        }
        log.info("after first load");
        session = HibernateManager.createSession();
        try {
            LoanTopic loanTopic = (LoanTopic) session.load(LoanTopic.class, 18416868581L);
        } finally {
            session.close();
        }
        log.info("waiting for terminate.....");
    }
```

best regards..

**Comment by mrniko** [comment]
You need to shutdown Hibernate Session factory

**Comment by taagholi** [comment]
session.close() represent session was closed(shut downed).

After adding the dependency redisson to my project, even if I write a main that only prints Hello world, there is this problem.

**Comment by mrniko** [comment]
call `SessionFactory.close()` method

**Comment by diddowill** [comment]
Essentially this is still reddisson's problem. I use reddission client directly and meet the same issue. 
With method shutdown() called on reddison client, my program exit normally.
