### ISSUE TITLE
High contention on AsyncSemaphore

### ISSUE THREAD

**Issue by XMitya** [redisson/redisson#3111]
Hi,

We have a cluster of services that extensively use Redisson 3.13.4. But CPU load and throughput are not equal for all instances. We found that the bigger CPU, then bigger latency and lower throughput. The main difference of such instance is in high contention on AsyncSemaphore object. Is it possible to reduce it somehow? For example, use few connection pools, instead of one or we need to use few Redisson clients? 
Here is for comparison node with high and low CPU:
![Screenshot_20201008_093014](https://user-images.githubusercontent.com/2520475/95423111-3916f300-0949-11eb-9d3e-0fa75c3f8355.png)
![Screenshot_20201008_093034](https://user-images.githubusercontent.com/2520475/95423121-3ddba700-0949-11eb-8df0-f90351874ea2.png)

Stack trace from profiler in netty thread:
```
Java Monitor Blocked
 at org.redisson.pubsub.AsyncSemaphore.acquire(Runnable, int)
 at org.redisson.pubsub.AsyncSemaphore.acquire(Runnable)
 at org.redisson.connection.ClientConnectionsEntry.acquireConnection(Runnable)
 at org.redisson.connection.pool.ConnectionPool.acquireConnection(ClientConnectionsEntry, Runnable)
 at org.redisson.connection.pool.ConnectionPool.acquireConnection(RedisCommand, ClientConnectionsEntry)
 at org.redisson.connection.pool.MasterConnectionPool.get(RedisCommand)
 at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(RedisCommand)
 at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(NodeSource, RedisCommand)
 at org.redisson.command.RedisExecutor.getConnection()
 at org.redisson.command.RedisExecutor.execute()
 at org.redisson.command.CommandAsyncService.async(boolean, NodeSource, Codec, RedisCommand, Object[], RPromise, boolean)
 at org.redisson.command.CommandAsyncService.writeAsync(String, Codec, RedisCommand, Object[])
 at org.redisson.RedissonExpirable.expireAsync(long, TimeUnit)
 at org.redisson.RedissonSet.expireAsync(long, TimeUnit)
 at com.tango.stream.service.viewer.ViewerAliveService.lambda$markAsChanged$13(long, long, RSet, Boolean)
 at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture, Consumer, CompletableFuture$UniAccept)
 at java.util.concurrent.CompletableFuture$UniAccept.tryFire(int)
 at java.util.concurrent.CompletableFuture.postComplete()
 at java.util.concurrent.CompletableFuture.complete(Object)
 at org.redisson.misc.RedissonPromise.trySuccess(Object)
 at org.redisson.command.RedisExecutor.handleReference(RPromise, Object)
 at org.redisson.command.RedisExecutor.handleSuccess(RPromise, RFuture, Object)
 at org.redisson.command.RedisExecutor.handleResult(RPromise, RFuture)
 at org.redisson.command.RedisExecutor.checkAttemptPromise(RPromise, RFuture)
 at org.redisson.command.RedisExecutor.lambda$execute$3(RPromise, RFuture, Object, Throwable)
 at org.redisson.misc.RedissonPromise.lambda$onComplete$0(BiConsumer, Future)
 at io.netty.util.concurrent.DefaultPromise.notifyListener0(Future, GenericFutureListener)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultFutureListeners)
 at io.netty.util.concurrent.DefaultPromise.notifyListenersNow()
 at io.netty.util.concurrent.DefaultPromise.notifyListeners()
 at io.netty.util.concurrent.DefaultPromise.setValue0(Object)
 at io.netty.util.concurrent.DefaultPromise.setSuccess0(Object)
 at io.netty.util.concurrent.DefaultPromise.trySuccess(Object)
 at org.redisson.misc.RedissonPromise.trySuccess(Object)
 at org.redisson.client.handler.CommandDecoder.completeResponse(CommandData, Object, Channel)
 at org.redisson.client.handler.CommandDecoder.handleResult(CommandData, List, Object, boolean, Channel)
 at org.redisson.client.handler.CommandDecoder.decode(ByteBuf, CommandData, List, Channel, boolean, List)
 at org.redisson.client.handler.CommandDecoder.decodeCommand(Channel, ByteBuf, QueueCommand)
 at org.redisson.client.handler.CommandDecoder.decode(ChannelHandlerContext, ByteBuf, QueueCommand)
 at org.redisson.client.handler.CommandDecoder.decode(ChannelHandlerContext, ByteBuf, List)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ChannelHandlerContext, ByteBuf, List)
 at io.netty.handler.codec.ReplayingDecoder.callDecode(ChannelHandlerContext, ByteBuf, List)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ChannelHandlerContext, Object)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext, Object)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(ChannelHandlerContext, Object)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext, Object)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(Object)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read()
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(SelectionKey, AbstractNioChannel)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized()
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys()
 at io.netty.channel.nio.NioEventLoop.run()
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run()
 at io.netty.util.internal.ThreadExecutorMap$2.run()
 at io.netty.util.concurrent.FastThreadLocalRunnable.run()
 at java.lang.Thread.run()
```

Thanks!

**Comment by mrniko** [comment]
I refactored AsyncSemaphore, try version attached.

[redisson-3.13.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5352699/redisson-3.13.6-SNAPSHOT.jar.zip)

**Comment by XMitya** [comment]
I will try and come back. Thanks!

**Comment by mrniko** [comment]
Fixed
