### ISSUE TITLE
java.lang.ClassCastException occurs when RedissonSessionRepository restore a session with JsonJacksonCodec

### ISSUE THREAD

**Issue by dknc** [redisson/redisson#3133]
Redis 3.13.4 

When setting a sub class of JsonJacksonCode to RedisConfig.
The restored Session RMAP actually store Integer for maxInactiveInterval, thus class cast exception occurs.

```

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at org.redisson.spring.session.RedissonSessionRepository.loadSession(RedissonSessionRepository.java:288)
	at org.redisson.spring.session.RedissonSessionRepository.findById(RedissonSessionRepository.java:358)
	at org.redisson.spring.session.RedissonSessionRepository.findById(RedissonSessionRepository.java:58)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getRequestedSession(SessionRepositoryFilter.java:351)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:289)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:192)
```

**Comment by mrniko** [comment]
`org.redisson.spring.session.RedissonSessionRepository` was deprecated. Please read [the documentation](https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#147-spring-session)
