### ISSUE TITLE
Null pointer on RMapCache destroy

### ISSUE THREAD

**Issue by kolle1986** [redisson/redisson#3147]
Hello, I'm getting null pointer exception when try to destroy RMapCache in EvictionScheduler line 74 (remove(String name)). Error occuring on tasks object.

**Comment by mrniko** [comment]
unable to reproduce it with the latest version.

**Comment by kolle1986** [comment]
> unable to reproduce it with the latest version.

We use 3.12.5 version because it's not so easy to change it now in production due to codecs collisions, you know.

**Comment by mrniko** [comment]
tasks object is final and not null

**Comment by kolle1986** [comment]
``

> in 3.12.5 version EvictionScheduler.tasks field is final and not null

`
public void remove(String name) {
        **EvictionTask task = tasks.remove(name);**
        if (task != null) {
            task.getScheduledFuture().cancel(false);
        }
    }
`

I assumed it's tasks object but it is maybe something else that cause null pointer in bold line in EvictionScheduler.class

**Comment by mrniko** [comment]
Caused by null used as name. Check your code

**Comment by kolle1986** [comment]
Already check that, but RMapCache has name, print it all the time before calling destroy();
Thanks for the answers anyway!

**Comment by kolle1986** [comment]
destroy() in RedissonMapCache.class - getName() for map returns value before trying to delete
```
 @Override
    public void destroy() {
        if (evictionScheduler != null) {
            evictionScheduler.remove(getName()); //getName() for map returns value before trying to delete
        }
        if (writeBehindService != null) {
            writeBehindService.stop(getName());
        }
    }
```
Even map.touch() returns true.

**Comment by mrniko** [comment]
can you share full stacktrace?

**Comment by kolle1986** [comment]
Here it is, now the null pointer is always at line 76, don't know how exactly.

```
java.lang.NullPointerException
	at org.redisson.eviction.EvictionScheduler.remove(EvictionScheduler.java:76)
	at org.redisson.RedissonSetCache.destroy(RedissonSetCache.java:413)
	at com.mnocompany.smspay.backend.rediscache.RedissonUtils.destroySet(OurRedissonUtils.java:408)
	at com.mnocompany.smspay.backend.rediscache.HandsetCache.ourMethod(OurClass.java:572)
	at com.mnocompany.smspay.backend.rediscache.HandsetCache.updateMccMncNetworksTest(OurClass.java:525)
	at com.mnocompany.smspay.backend.rediscache.HandsetCache.updateMaps(OurClass.java:486)
	at com.mnocompany.smspay.backend.HandsetsUpdater.storeOtherClass(OtherClass.java:554)
	at com.mnocompany.smspay.backend.services.HandsetsServices.updateHandsetFromHeartbeat(OurServices.java:515)
	at com.mnocompany.smspay.backend.restinterface.AppUserMobRest.processingHeartbeat(OurRest.java:823)
	at com.mnocompany.smspay.backend.restinterface.AppUserMobRest.postPing(OurRest.java:685)
	at sun.reflect.GeneratedMethodAccessor334.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:432)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:395)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mrniko** [comment]
Sorry, unable to reproduce it. The only reason is `null` value used as name.

**Comment by kolle1986** [comment]
Alright maybe it is worth updating the redisson lib but for us it is little hard because we use old FST codec for some map values objects serializing. So, in your opinion should we anyway force upgrade to latest version (e.g. 3.13.6) whatever it takes somehow because there is lot of important changes and improvements since this version we use (before you changed default codec)? Just asking this as advice comes from you! 

Thanks again, after this I will close this issue.

**Comment by mrniko** [comment]
> Alright maybe it is worth updating the redisson lib but for us it is little hard because we use old FST codec for some map values objects serializing

I don't see any problem here since you can define FST codec explicitly in config.
Yes, I would recommend you to update. Since I use latest version for testing.

**Comment by kolle1986** [comment]
Considering lib update

**Comment by kolle1986** [comment]
@mrniko updated redisson lib to newest version (3.13.6), but had to degrade again to previous (3.12.5) due to large and fast memory increasing on Aws instance. And on new version (3.13.6), we had error on destroy map. I'm sending you --bigkeys summary and I can send you monitor log if it is helps something to figure out what is the problem. Thanks in advance.
[redis bigkeys.txt](https://github.com/redisson/redisson/files/5482874/redis.bigkeys.txt)

**Comment by mrniko** [comment]
Can you share Redisson config and error stacktrace with 3.13.6 version?

**Comment by kolle1986** [comment]
Here is config: 
`config.useReplicatedServers()
                        .addNodeAddress(endpoint)
                        .setMasterConnectionPoolSize(1024)
                        .setMasterConnectionMinimumIdleSize(64)
                        .setSlaveConnectionPoolSize(1024)
                        .setSlaveConnectionMinimumIdleSize(64)
                        .setSubscriptionConnectionPoolSize(1024)
                        .setSubscriptionConnectionMinimumIdleSize(64)
                        .setConnectTimeout(10000)
                        .setIdleConnectionTimeout(5000)
                        .setRetryAttempts(5)
                        .setKeepAlive(true)
                        .setPingConnectionInterval(5*1000)
                        .setRetryInterval(3000);
                config.setThreads(1024);
                config.setNettyThreads(512);`

I'm sending you redis monitor log, 
[redis monitor.txt.zip](https://github.com/redisson/redisson/files/5486310/redis.monitor.txt.zip)
but we actualy don't have any errors in application server log, just memory increasing terribly. After returned to previous one (3.12.5) it got back to much slower incline (E.g. aws instance memory that lasts 12 hours and with 3.13.6  just half an hour). I hope you can really figure out from this log what is the problem.

Thank a lot again!

**Comment by mrniko** [comment]
probably the cause in codec it has changed since 3.13.0 version. You can set it back to FST.

**Comment by kolle1986** [comment]
Yes, but in new version (3.13.6) we set default codec to FST in config, this is config for 3.12.5

**Comment by mrniko** [comment]
can you try 3.13.0 version as well?

**Comment by kolle1986** [comment]
Alright, you mean there are some possible critical changes between 3.13.0  and 3.13.6 that causes our problems ?

**Comment by mrniko** [comment]
I just want to find out which version introduces this.

**Comment by kolle1986** [comment]
Ok, we will try ASAP because it is production environment so we must find a good moment for that. Thank you! I will let you know!

**Comment by kolle1986** [comment]
@mrniko tried with version as you suggested 3.13.0 and problem is still the same. I'm sending you screeshot of memory utilization on AWS instance after we deployed version. You'll see exact moment with peak, fast increase with 3.13.0 after slow increase before that with version 3.12.5. And yeah, still got that error (npe) on destroy map.

<img width="1016" alt="Screenshot 2020-11-12 at 10 03 20" src="https://user-images.githubusercontent.com/7590709/98920102-f9a36f80-24cf-11eb-9e70-c965770485f1.png">

**Comment by mrniko** [comment]
npe) on destroy map fixed in https://github.com/redisson/redisson/issues/4230
