### ISSUE TITLE
Redisson is shutdown

### ISSUE THREAD

**Issue by pengqiao1024** [redisson/redisson#3150]
在低并发时无此现象  当并发达到一定量级后出现如下错误(版本3.0.1)：
org.redisson.client.RedisException: Unexpected exception while processing command
        at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:307) ~[redisson-3.0.1.jar:?]
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:150) ~[redisson-3.0.1.jar:?]
        at org.redisson.command.CommandSyncService.evalWrite(CommandSyncService.java:83) ~[redisson-3.0.1.jar:?]
        at org.redisson.RedissonLock.unlock(RedissonLock.java:354) ~[redisson-3.0.1.jar:?]
        at com.oppo.ocloud.file.common.tool.lock.RedissonLock.unlock(RedissonLock.java:76) ~[ocloud-file-common-tool-1.0.5-SNAPSHOT.jar:?]
        at com.oppo.ocloud.file.common.service.ReplaceFileIdService.doReplace(ReplaceFileIdService.java:165) ~[ocloud-file-common-job-1.0-SNAPSHOT.jar:?]
        at com.oppo.ocloud.file.common.service.ReplaceFileIdService.lambda$processReplaceFileIdJob$1(ReplaceFileIdService.java:109) ~[ocloud-file-common-job-1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.redisson.RedissonShutdownException: Redisson is shutdown
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:463) ~[redisson-3.0.1.jar:?]
        at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:439) ~[redisson-3.0.1.jar:?]
        at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:381) ~[redisson-3.0.1.jar:?]
        at org.redisson.command.CommandSyncService.evalWrite(CommandSyncService.java:82) ~[redisson-3.0.1.jar:?]
        ... 9 more

**Comment by mrniko** [comment]
update Redisson version
