### ISSUE TITLE
DNSMonitor switches master and slave frequently

### ISSUE THREAD

**Issue by rexzhong79626** [redisson/redisson#3152]
there are three sentinel node, and one master node and on slave node.
redis and sentinel config file in attachment file.
redisson version:3.12.2
Redis server v=4.0.10
[config.zip](https://github.com/redisson/redisson/files/5423032/config.zip)
error/info log as below:

2020-10-22-T18:07:36.018+0800 | lrc3vm16 | | redisson-netty-2-10 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.17/172.18.81.17:6379 has changed to 172.18.81.16/172.18.81.16:6379
2020-10-22-T18:07:38.018+0800 | lrc3vm16 | | redisson-netty-2-10 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.16/172.18.81.16:6379 has changed to 172.18.81.17/172.18.81.17:6379
2020-10-22-T18:07:40.026+0800 | lrc3vm16 | | redisson-netty-2-7 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.17/172.18.81.17:6379 has changed to 172.18.81.16/172.18.81.16:6379
2020-10-22-T18:07:41.035+0800 | lrc3vm16 | | redisson-netty-2-12 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.16/172.18.81.16:6379 has changed to 172.18.81.17/172.18.81.17:6379
2020-10-22-T18:07:42.037+0800 | lrc3vm16 | | redisson-netty-2-8 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.17/172.18.81.17:6379 has changed to 172.18.81.16/172.18.81.16:6379
2020-10-22-T18:07:43.135+0800 | lrc3vm16 | | redisson-netty-2-10 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.16/172.18.81.16:6379 has changed to 172.18.81.17/172.18.81.17:6379
2020-10-22-T18:07:44.052+0800 | lrc3vm16 | | redisson-netty-2-4 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.17/172.18.81.17:6379 has changed to 172.18.81.16/172.18.81.16:6379
2020-10-22-T18:07:46.066+0800 | lrc3vm16 | | redisson-netty-2-4 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.16/172.18.81.16:6379 has changed to 172.18.81.17/172.18.81.17:6379
2020-10-22-T18:07:48.106+0800 | lrc3vm16 | | redisson-netty-2-11 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.17/172.18.81.17:6379 has changed to 172.18.81.16/172.18.81.16:6379
2020-10-22-T18:07:50.105+0800 | lrc3vm16 | | redisson-netty-2-6 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.16/172.18.81.16:6379 has changed to 172.18.81.17/172.18.81.17:6379
2020-10-22-T18:07:51.107+0800 | lrc3vm16 | | redisson-netty-2-4 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.17/172.18.81.17:6379 has changed to 172.18.81.16/172.18.81.16:6379
2020-10-22-T18:07:59.133+0800 | lrc3vm16 | | redisson-netty-2-3 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.16/172.18.81.16:6379 has changed to 172.18.81.17/172.18.81.17:6379
2020-10-22-T18:08:02.334+0800 | lrc3vm16 | | redisson-netty-2-6 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.17/172.18.81.17:6379 has changed to 172.18.81.16/172.18.81.16:6379
2020-10-22-T18:08:04.470+0800 | lrc3vm16 | | redisson-netty-2-10 | INFO  | org.redisson.connection.SingleEntry | master 172.18.81.16/172.18.81.16:6379 has changed to 172.18.81.17/172.18.81.17:6379

There are no other debug logs here. For example, I want to print the following log, How should I configure log4j?
log.debug("Request sent to resolve ip address for master host: {}", entry.getKey().getHost());
log.debug("Resolved ip: {} for master host: {}", future.getNow().getAddress(), entry.getKey().getHost());
log.info("Detected DNS change. Master {} has changed ip from {} to {}",  entry.getKey(), 
                 currentMasterAddr.getAddress().getHostAddress(), newMasterAddr.getAddress().getHostAddress());

**Comment by rexzhong79626** [comment]
error log as below:
2020-10-22-T18:07:00.837+0800 | lrc3vm16 | | ne3sws-ping-consumer | ERROR | com.nsn.oss.mf.mediation.ne3sws.ping.consumer.PingTaskConsumer | Exception when consume ping task
org.redisson.client.RedisException: ERR Error running script (call to f_3b208cb8c03e10fa792f7115018d26ce1baf395d): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   . channel: [id: 0x59d340cb, L:/172.18.81.16:37273 - R:172.18.81.17/172.18.81.17:6379] command: (EVAL), params: [local elemNum = math.min(ARGV[1], redis.call('llen', KEYS[1])) - 1;local vals = redis.call('lrange',..., 3, NE3SWS-PING-TASK, redisson_bqs:{NE3SWS-PING-TASK}, redisson_sc:redisson_bqs:{NE3SWS-PING-TASK}, 200]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355) ~[redisson-3.12.2.jar:3.12.2]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[redisson-3.12.2.jar:3.12.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[redisson-3.12.2.jar:3.12.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[redisson-3.12.2.jar:3.12.2]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by mrniko** [comment]
set dnsMonitoringInterval = -1

**Comment by rexzhong79626** [comment]
How to configure in log4j to print the following debug log:
There are no other debug logs here. For example, I want to print the following log, How should I configure log4j?
log.debug("Request sent to resolve ip address for master host: {}", entry.getKey().getHost());
log.debug("Resolved ip: {} for master host: {}", future.getNow().getAddress(), entry.getKey().getHost());
log.info("Detected DNS change. Master {} has changed ip from {} to {}", entry.getKey(),
currentMasterAddr.getAddress().getHostAddress(), newMasterAddr.getAddress().getHostAddress());

Our current configuration is as follows:
<Logger name="org.redisson" level="DEBUG"></Logger>
