### ISSUE TITLE
Class cast exception when working with RMapCache<String, String>

### ISSUE THREAD

**Issue by mlemnaru** [redisson/redisson#3156]
I have this RMapCache<String, String> stored in redis. Each key has a 30s TTL

Everything behaves normally but from time to time I get this class cast exception which causes a lot of issues down the line.

```
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at org.redisson.client.protocol.decoder.MapCacheScanResultReplayDecoder.decode(MapCacheScanResultReplayDecoder.java:35)
	at org.redisson.client.protocol.decoder.MapCacheScanResultReplayDecoder.decode(MapCacheScanResultReplayDecoder.java:30)
	at org.redisson.client.protocol.decoder.ListMultiDecoder2.decode(ListMultiDecoder2.java:46)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:421)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

I can't tell why this is happening , I am using redisson **3.12.5**
Any idea what is happening over here ? 

We have multiple nodes that are updating the same map inserting and deleting keys , different TTL's for each.
All nodes are time synced 

Any help will be greatly apreciated. 

Thanks

**Comment by honestAnt** [comment]
I have a similar situation;
This error often occurs when there are findany methods in the code that use streams such as RList、RSet、RMapCache etc;

java version：1.8.0_171
redisson version：3.11.5
redis server version：5.0.6

error info：

[sson-netty-2-25] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

io.netty.handler.codec.DecoderException: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at org.redisson.client.protocol.decoder.MapCacheScanResultReplayDecoder.decode(MapCacheScanResultReplayDecoder.java:35)
	at org.redisson.client.protocol.decoder.MapCacheScanResultReplayDecoder.decode(MapCacheScanResultReplayDecoder.java:30)
	at org.redisson.client.protocol.decoder.ListMultiDecoder2.decode(ListMultiDecoder2.java:46)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:431)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:387)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 common frames omitted

**Comment by honestAnt** [comment]
@mrniko  When I store the data in redis, it is RSET < string >, but after the data is read, the redisson side is decoded into mapcache;

![企业微信截图_a636dfc0-1a70-4dec-916a-f27f9c0d5353](https://user-images.githubusercontent.com/15356873/99636886-08b19100-2a7f-11eb-8a1f-1c3104299529.png)
![企业微信截图_e2e2bf42-095f-45f4-b56b-e4adf51a256c](https://user-images.githubusercontent.com/15356873/99637192-765dbd00-2a7f-11eb-893c-f98e5fed9748.png)

**Comment by mrniko** [comment]
@honestAnt 

you can't store data in RSet and use RSetCache to read data.

**Comment by honestAnt** [comment]
> @honestAnt
> 
> you can't store data in RSet and use RSetCache to read data.

sorry, My description is wrong，I have read and written RSetCache；

**Comment by mrniko** [comment]
Fixed

**Comment by formanojhr** [comment]
@mrniko we have a similar problem in 3.17.4 redisson version. We have a RMapCache<byte[], Object> when we do DeserCLass a = RMapCache.get() we get the follwing
Exception loading key :[B@61073a79 ! java.lang.ClassCastException: class java.lang.String cannot be cast to class  DeserCLass (java.lang.String is in module java.base of loader 'bootstrap'; DeserCLass is in unnamed module of loader 'app') ! at

**Comment by mrniko** [comment]
@formanojhr 

Is it reproduceable?

**Comment by formanojhr** [comment]
@mrniko  it is reproducible in our deployed regression tests. Have not tried reproducing it in a unit test. The object read is a class for deserializing(readObject). It fails in some cases(wonder when redis Elastic cache is having too much load). But clearly the library seems to return a String instead of null or the written value type.

**Comment by mrniko** [comment]
@formanojhr 
We have an issue fixed in 3.19.2 version `Fixed - command replies don't match if exception is thrown in CommandEncoder`. Can you try it?

**Comment by formanojhr** [comment]
will do @mrniko thx.

**Comment by formanojhr** [comment]
@mrniko I think 3.19.2 seems to have fixed this issue. After updating the version, seeing almost none of the exceptions
