### ISSUE TITLE
Rmap.addAndGet method throws NumberFormat exception

### ISSUE THREAD

**Issue by akshitjain** [redisson/redisson#3188]
**Expected behavior**
This should not throw an error. It should convert the number to long but it is converting to int

**Actual behavior**
RedisExeption is thrown 

message: Unable to decode data. channel: [id: 0x9866744b, L:/172.18.167.145:48328 - R:xxxxx-0001-001.xxxxx.oi7ujc.use1.cache.amazonaws.com/10.75.xxx.xx:6379], reply: ReplayingDecoderByteBuf(ridx=18, widx=18), command: (HINCRBYFLOAT), params: [BucketUpdates_urn:aaid:yyyyyyyyy:xxxxxxxx-6aa7-4a52-xxxx-xxxxxxxxxxxx, PooledUnsafeDirectByteBuf(ridx: 0, widx: 23, cap: 256), -12218]

Stack trace:
stack_trace: java.lang.NumberFormatException: For input string: "-3753018785"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.redisson.client.protocol.convertor.NumberConvertor.convert(NumberConvertor.java:42)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:441)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Steps to reproduce or test case**
Map<String, Number> nonZeroBucketUpdates;
RMap<String, Number> distributedBucketUpdates =redissonClient.getMap("BucketUpdates_urn:aaid:yyyyyyyyy:xxxxxxxx-6aa7-4a52-xxxx-xxxxxxxxxxxx");
nonZeroBucketUpdates.forEach(distributedBucketUpdates::addAndGet);

**Redis version**
5.0.6

**Redisson version**
3.13.1

**Redisson configuration**
redissonConfig.setCodec(new JsonJacksonCodec())
          .setNettyThreads(64)
          .setReadMode(ReadMode.MASTER)
          .addNodeAddress(redisProperties.getNodes().toArray(new String[] {}))
          .setPassword(redisProperties.getAuthToken())

**Comment by akshitjain** [comment]
@marko-stankovic any help?

**Comment by mrniko** [comment]
Unable to reporoduce it using this test:

```java
RMap<Integer, Long> map3 = getMap("getAll", new CompositeCodec(redisson.getConfig().getCodec(), LongCodec.INSTANCE));
map3.put(1, 100L);

Long res3 = map3.addAndGet(1, 12L);
assertThat(res3).isEqualTo(112L);
Long res4 = map3.get(1);
assertThat(res4).isEqualTo(112L);
```

**Comment by akshitjain** [comment]
I have got the issue. Actually it converts the type of input to Number. So there can be issue when the actual type is lost and the number is greater than the range of Integer which is default for Number
