### ISSUE TITLE
断线重连后watchdog不再生效

### ISSUE THREAD

**Issue by burgleaf** [redisson/redisson#3194]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
1.使用redisson加锁
`redissonClient.getLock("LOCK_NAME").Lock()`
2.加锁成功后断开本地与redis服务器的网络，使redisson的watchdog报错
`ERROR org.redisson.RedissonLock - Can't update lock LOCK_NAME expiration
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: null, params: null, channel: [id: 0x1e676dd8, L:/192.168.20.49:58477 - R:/192.168.2.21:6379]
    at org.redisson.command.RedisExecutor$3.run(RedisExecutor.java:333)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)`
`
3.让网络恢复正常，且"LOCK_NAME"这个锁自动失效后，**再使用redissonClient.getLock("LOCK_NAME").Lock()加锁后watchdog就不再生效了**

**Redis version**
3.13.6
**Redisson version**
4.0.9

**Comment by mrniko** [comment]
merged
