### ISSUE TITLE
偶发错误org.redisson.client.handler.CommandPubSubDecoder - Unable to decode data.

### ISSUE THREAD

**Issue by bean326** [redisson/redisson#3204]
用的阿里云的集群版redis，会偶发这个错误，但是不确定是执行什么出的错
[] [ERROR] 2020-11-11 15:10:13.897 [redisson-netty-2-8] org.redisson.client.handler.CommandPubSubDecoder - Unable to decode data. channel: [id: 0xcbbfbec3, L:/10.11.9.221:33926 - R:r-uf6lps934bbmd03q4e.redis.rds.aliyuncs.com/10.11.9.239:6379], reply: ReplayingDecoderByteBuf(ridx=140, widx=362)
java.lang.NullPointerException: null
[] [WARN ] 2020-11-11 15:10:13.897 [redisson-netty-2-8] io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

要怎么排查是具体什么的错啊，要怎么解决

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/2964
