### ISSUE TITLE
Redisson 3.13.6 + Kryo 5.0.0: Class is not registered

### ISSUE THREAD

**Issue by avillev** [redisson/redisson#3217]
**Expected behavior**

I should be able to serialize any Pojo.

**Actual behavior**

java.lang.IllegalArgumentException: Class is not registered: com.rakuten.rapid.cache.v2.entity.TopEntity
Note: To register this class use: kryo.register(com.rakuten.rapid.cache.v2.entity.TopEntity.class);

	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:512)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:546)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:641)
	at org.redisson.codec.KryoCodec$2.encode(KryoCodec.java:87)

**Steps to reproduce or test case**

With those versions of Redisson and Kryo. Just set up a simple client. The boolean "RegistrationRequired" is true by default now on Kryo and any new serialization will fail.

**Redis version**

Any

**Redisson version**

3.13.6

**Redisson configuration**

Use KryoCodec

**Comment by mrniko** [comment]
for Kryo5 use `Kryo5Codec`
