### ISSUE TITLE
How to programmatically initialize redisson hibernate second level cache

### ISSUE THREAD

**Issue by smirandamedallia** [redisson/redisson#3239]
My application uses:
```
org.redisson:redisson-hibernate-53:3.13.6
org.redisson:redisson:3.13.1
org.redisson:redisson-spring-data-22:3.12.5
id 'org.springframework.boot' version '2.3.0.RELEASE'
```
I am using spring boot along with redisson for http session management and spring data. The configuration is programmatically initialized and works well. 
I am trying to add hibernate 2nd level cache back by redis. I cannot find documentation on how this can be done programmatically. I have the following beans: `RedissonClient`, `RedissonConnectionFactory` and `RedisTemplate`

**Comment by smirandamedallia** [comment]
Upgraded to redisson `3.14.0` now 
I have added the following class 
```
@Configuration
@DependsOn("redis-client")
public class RedissonPersistenceCachingConfiguration extends RedissonRegionFactory {
	private RedissonClient redissonClient;

	@Autowired
	public RedissonPersistenceCachingConfiguration(RedissonClient redissonClient) {
		this.redissonClient = redissonClient;
	}

	@Override
	protected RedissonClient createRedissonClient(Map properties) {
		return redissonClient;
	}
}
```

The `RedissonClient` looks to be injected as expected but hibernate initialization fails with the below error

```
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.MetadataBuilderImpl$MetadataBuildingOptionsImpl.<init>(MetadataBuilderImpl.java:694)
	at org.hibernate.boot.internal.MetadataBuilderImpl.<init>(MetadataBuilderImpl.java:122)
	at org.hibernate.boot.MetadataSources.getMetadataBuilder(MetadataSources.java:141)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:238)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:168)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:52)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Could not instantiate named strategy class [com.medallia.sso.relay.configuration.RedissonPersistenceCachingConfiguration]
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:247)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:192)
	at org.hibernate.cache.internal.RegionFactoryInitiator.resolveRegionFactory(RegionFactoryInitiator.java:93)
	at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:47)
	at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:32)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	... 15 more
Caused by: org.hibernate.service.spi.ServiceException: Unable to call constructor of RegionFactory impl [com.medallia.sso.relay.configuration.RedissonPersistenceCachingConfiguration]
	at org.hibernate.cache.internal.StrategyCreatorRegionFactoryImpl.create(StrategyCreatorRegionFactoryImpl.java:65)
	at org.hibernate.cache.internal.StrategyCreatorRegionFactoryImpl.create(StrategyCreatorRegionFactoryImpl.java:23)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:243)
	... 21 more
Caused by: java.lang.InstantiationException: com.medallia.sso.relay.configuration.RedissonPersistenceCachingConfiguration
	at java.base/java.lang.Class.newInstance(Class.java:571)
	at org.hibernate.cache.internal.StrategyCreatorRegionFactoryImpl.create(StrategyCreatorRegionFactoryImpl.java:62)
	... 23 more
Caused by: java.lang.NoSuchMethodException: com.medallia.sso.relay.configuration.RedissonPersistenceCachingConfiguration.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	... 24 more
```
is there another way of sharing the previously created `RedissonClient` ?

**Comment by smirandamedallia** [comment]
any updates on this @mrniko

**Comment by mrniko** [comment]
`java.lang.NoSuchMethodException: com.medallia.sso.relay.configuration.RedissonPersistenceCachingConfiguration.<init>()`

You need to check your class constructor

**Comment by smirandamedallia** [comment]
@mrniko 
Yes I see that but even adding a default constructor in `RedissonPersistenceCachingConfiguration` doesn't help since when
`RedissonRegionFactory#prepareForUse` is called the Overriden method `createRedissonClient` returns `null` since the `RedissonClient` is never injected. 

Mainly what I am trying to do is have `RedissonRegionFactory` use the `RedissonClient` which already has been created (I have already created one for spring sessions).
`RedissonRegionFactory` looks to only support creating a client from properties rather than reusing one if it already exists as a bean

**Comment by smirandamedallia** [comment]
@mrniko any suggests on above

**Comment by mrniko** [comment]
I can suggest you to put Redisson in JNDI and use JndiRedissonRegionFactory

**Comment by moose-ahh** [comment]
Do you have an example of this? I keep reading about it, but I don't see any examples. Maybe I haven't looked deep enough

**Comment by chenygs** [comment]
``/**
 * @Author chenygs
 * @Date 2023/3/7 15:38
 */
@AllArgsConstructor
public class New2RedisRegionFactory extends RedissonRegionFactory {
    private static final long serialVersionUID = 8887392285596501033L;

    private RedissonClient redissonClient;

    @Override
    protected RedissonClient createRedissonClient(Map properties) {
        return redissonClient;
    }
}


    @Bean
    @Primary
    public HibernatePropertiesCustomizer setRegionFactory(RedissonClient redisson) {
        return hibernateProperties -> {
            hibernateProperties.put(AvailableSettings.USE_SECOND_LEVEL_CACHE, true);
            hibernateProperties.put(AvailableSettings.CACHE_REGION_FACTORY, new New2RedisRegionFactory(redisson));
            hibernateProperties.put(AvailableSettings.CACHE_REGION_PREFIX, "imv3::");
            hibernateProperties.put(AvailableSettings.JPA_SHARED_CACHE_MODE, SharedCacheMode.ENABLE_SELECTIVE);
            hibernateProperties.put(AvailableSettings.USE_QUERY_CACHE, true);
//            hibernateProperties.put("hibernate.cache.redisson.entity.expiration.time_to_live", "7000");
        };
    }
