### ISSUE TITLE
isHeldByCurrentThread() goes wrong

### ISSUE THREAD

**Issue by VicQwz** [redisson/redisson#3242]
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:338)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:140)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonLock.isHeldByThread(RedissonLock.java:523)
	at org.redisson.RedissonLock.isHeldByCurrentThread(RedissonLock.java:517)
	at com.hikvision.ga.vnsc.mls.modules.distribute.redis.RedissonDistributedLocker.unlock(RedissonDistributedLocker.java:49)
	at com.hikvision.ga.vnsc.mls.modules.distribute.redis.RedissLockUtil.unlock(RedissLockUtil.java:30)
	at com.hikvision.ga.vnsc.mls.modules.privilege.handler.CountHandler.updateCurrentLink(CountHandler.java:776)
	at com.hikvision.ga.vnsc.mls.modules.privilege.handler.CountHandler.updateSingleCurrentLink(CountHandler.java:530)
	at com.hikvision.ga.vnsc.mls.modules.privilege.handler.CountHandler.updateCountByRegister(CountHandler.java:481)
	at com.hikvision.ga.vnsc.mls.modules.notifier.DefaultNotifier.updateLinkEurl(DefaultNotifier.java:251)
	at com.hikvision.ga.vnsc.mls.modules.notifier.DefaultNotifier.notify(DefaultNotifier.java:137)
	at com.hikvision.ga.vnsc.mls.modules.notifier.DefaultNotifier$$FastClassBySpringCGLIB$$b3dd79bb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.hikvision.ga.vnsc.mls.modules.notifier.DefaultNotifier$$EnhancerBySpringCGLIB$$a14831d5.notify(<generated>)
	at com.hikvision.ga.vnsc.mls.modules.module.media.handler.AbstractMessageHandler.notify(AbstractMessageHandler.java:174)
	at com.hikvision.ga.vnsc.mls.modules.module.media.handler.RegisterReqHandler.getResponse(RegisterReqHandler.java:140)
	at com.hikvision.ga.vnsc.mls.modules.module.media.handler.RegisterReqHandler.lambda$doHandle$0(RegisterReqHandler.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:131)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:100)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:56)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:97)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1031)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:298)
	at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:123)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by mrniko** [comment]
check lock name for null value

**Comment by VicQwz** [comment]
Thanks a lot
