### ISSUE TITLE
org.redisson.client.RedisException: ERR Protocol error: invalid bulk length

### ISSUE THREAD

**Issue by gallog** [redisson/redisson#3257]
```Using redisson 3.13.6, redis 5.0.7```
Putting an HashMap we are getting this exception:

```
Exception in thread "main" org.redisson.client.RedisException: ERR Protocol error: invalid bulk length. channel: [id: 0x8f415e63, L:/127.0.0.1:51268 - R:localhost/127.0.0.1:6379] command: (EVAL), params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); if AR..., 3, it.package.cache.MyCache, {it.package.cache.MyCache}:topic, redisson__cache_updates_log:{it.package.cache.MyCache}, PooledUnsafeDirectByteBuf(ridx: 0, widx: 15, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 1124764286, cap: 1128267776), PooledUnsafeDirectByteBuf(ridx: 0, widx: 37, cap: 256), 1, 1607008383620, ...]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:361)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

redis log:
```
34563:M 01 Dec 2020 14:13:04.366 - Protocol error (invalid bulk length) from client: id=5 addr=127.0.0.1:51268 fd=10 name= age=111 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=16384 qbuf-free=16384 obl=42 oll=0 omem=0 events=r cmd=ping. Query buffer during protocol error: '$1124764286....8>.java.util.HashMap......`.' (... more 15660 bytes ...) ''
```

Current redis configuration is `proto-max-bulk-len 1024mb`
The hashmap size is not exceeding this limit

**Comment by mrniko** [comment]
try to use StringCodec
