### ISSUE TITLE
Tomcat session manager registers UsageValve with Engine pipeline

### ISSUE THREAD

**Issue by brecht-yperman-tb** [redisson/redisson#3272]
**Expected behavior**
Since the Manager can only be registered with a Context, the `UsageValve` should not be added to the Engine pipeline, but to the Context pipeline. Or the `UsageValve` should take into account that not all `Session`s are `RedissonSession`s.

**Actual behavior**
If the session manager cannot find a `UsageValve`, it adds a `UsageValve` to the Engine pipeline. The `UsageValve` assumes all `Session`s are `RedissonSession`s.

**Steps to reproduce or test case**
- Have two webapps, one with the default Session Manager, one with `RedissonSessionManager`
- Access the one with the `RedissonSessionManager` first
- Then access the one with the default Session Manager
- An internal server error is returned and the following error is logged
```
Dec 08, 2020 1:03:51 PM org.apache.coyote.http11.Http11Processor service
SEVERE: Error processing request
java.lang.ClassCastException: class org.apache.catalina.session.StandardSession cannot be cast to class org.redisson.tomcat.RedissonSession (org.apache.catalina.session.StandardSession and org.redisson.tomcat.RedissonSession are in unnamed module of loader java.net.URLClassLoader @5bb21b69)
	at org.redisson.tomcat.UsageValve.invoke(UsageValve.java:77)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Redis version**
5.0.9

**Redisson version**
3.3.16

**Redisson configuration**
```
singleServerConfig:
  address: "redis://127.0.0.1:6379"
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
