### ISSUE TITLE
Rename Empty BloomFilter Throws RedisException:no such key

### ISSUE THREAD

**Issue by JisaKun** [redisson/redisson#3297]
Version:3.13.6
Demo:
``` java
String name = "{foo}_1";
String newName = "foo";
RBloomFilter<String> bloomFilter = redissonClient.getBloomFilter(name);
bloomFilter.rename(newName);
```

Exception:
``` 
org.redisson.client.RedisException: ERR Error running script (call to xxx): @user_script:1: ERR no such key . channel: [] command: (EVAL), params: [redis.call('rename', KEYS[1], ARGV[1]);  return redis.call('rename', KEYS[2], ARGV[2]); , 2, {foo}, {foo}_1:config, foo, {foo}:config]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:361)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
```

possible reason：
Bloom Filter is empty now and key `{foo}` doesn't exist ,so rename failed

**Comment by JisaKun** [comment]
Update demo
``` java 
String name = "{foo}_1";
String newName = "foo";
RBloomFilter<String> bloomFilter = redissonClient.getBloomFilter(name);
bloomFilter.tryInit(1000, 0.01);
bloomFilter.rename(newName);
```

I just forgot `tryInit`

**Comment by mrniko** [comment]
Fixed! Thanks for report
