### ISSUE TITLE
Error starting project:Unable to connect to Redis server.

### ISSUE THREAD

**Issue by i-Javan** [redisson/redisson#3306]
**There is a probability that it will happen, not every time it will go wrong。**
![image](https://user-images.githubusercontent.com/47896553/102860416-c954d680-4468-11eb-8665-42b54f914584.png)
![image](https://user-images.githubusercontent.com/47896553/102860675-4718e200-4469-11eb-8ad6-2004f5f0ce4f.png)

config:
singleServerConfig:
    address: "redis://127.0.0.1:6379"
    password: "casa"
    idleConnectionTimeout: 10000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    subscriptionsPerConnection: 5
    clientName: null
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    connectionMinimumIdleSize: 12
    connectionPoolSize: 64
    database: 0
    dnsMonitoringInterval: 5000
  threads: 16
  nettyThreads: 64
  codec: {}
  transportMode: "NIO"

version:3.11.5

**Comment by i-Javan** [comment]
2020-12-22 03:18:11,728 [resource-service   ] INFO  c.c.a.s.i.t.s.TaskSchedulerService - Task Scheduler Service is initialized !
2020-12-22 03:18:11,869 [resource-service   ] INFO  c.c.a.s.i.config.RedissonConfig - redissonClientConfig
{"threads":16,"transportMode":"NIO","singleServerConfig":{"address":"redis://127.0.0.1:6379","password":"casa","idleConnectionTimeout":10000,"connectTimeout":10000,"timeout":3000,"retryAttempts":3,"retryInterval":1500,"subscriptionsPerConnection":5,"clientName":"","subscriptionConnectionMinimumIdleSize":1,"subscriptionConnectionPoolSize":50,"connectionMinimumIdleSize":24,"connectionPoolSize":64,"database":0,"dnsMonitoringInterval":5000},"nettyThreads":32}
2020-12-22 03:18:12,354 [resource-service   ] INFO  org.redisson.Version - Redisson 3.11.5
2020-12-22 03:18:16,690 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x4d757134, L:/127.0.0.1:45518 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,864 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xf07bd47a, L:/127.0.0.1:45486 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,842 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xd911717a, L:/127.0.0.1:45506 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,671 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xdf0659e4, L:/127.0.0.1:45504 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,708 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x7fbe8ee3, L:/127.0.0.1:45498 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,917 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xae506ff3, L:/127.0.0.1:45528 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,867 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x81288cb1, L:/127.0.0.1:45494 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,602 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xeaaf01fe, L:/127.0.0.1:45496 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,641 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xd2363819, L:/127.0.0.1:45502 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,573 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xefaa5b86, L:/127.0.0.1:45516 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,867 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x5945fc2c, L:/127.0.0.1:45484 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,864 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x3f2b1c9b, L:/127.0.0.1:45510 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,913 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x8800ebbc, L:/127.0.0.1:45508 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,913 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x7a858119, L:/127.0.0.1:45512 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,914 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xfbfc029f, L:/127.0.0.1:45488 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,861 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xdace6d51, L:/127.0.0.1:45520 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,924 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x6c7ccb36, L:/127.0.0.1:45514 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,924 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x14d5803f, L:/127.0.0.1:45522 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,925 [resource-service   ] WARN  o.r.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0x5a727e73, L:/127.0.0.1:45500 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:16,926 [resource-service   ] WARN  o.r.c.handler.CommandPubSubDecoder - response has been skipped due to timeout! channel: [id: 0x11006ce0, L:/127.0.0.1:45536 - R:127.0.0.1/127.0.0.1:6379], command: (AUTH), params: (password masked)
2020-12-22 03:18:18,722 [resource-service   ] INFO  org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
2020-12-22 03:18:18,722 [resource-service   ] INFO  org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED paused.
2020-12-22 03:18:18,723 [resource-service   ] INFO  org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
2020-12-22 03:18:18,795 [resource-service   ] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2020-12-22 03:18:18,836 [resource-service   ] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DPUDeviceClient': Unsatisfied dependency expressed through field 'mgrService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskManagerServiceImpl': Unsatisfied dependency expressed through field 'recordEventLogUtil'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'recordEventLogUtil': Unsatisfied dependency expressed through field 'eventLogHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eventLogHandler': Unsatisfied dependency expressed through field 'eventLogAgent'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eventLogAgent': Unsatisfied dependency expressed through field 'eventLogQueue'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eventLogQueue' defined in com.casa.aems.common.config.log.EventLogSupport: Unsatisfied dependency expressed through method 'eventLogQueue' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redissonClient' defined in class path resource [com/casa/aems/service/inventory/config/RedissonConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.casa.aems.service.inventory.InventoryApplication.main(InventoryApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)





Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 106 common frames omitted
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:160)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:330)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:296)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.client.RedisClient$2$1.run(RedisClient.java:240)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://127.0.0.1:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	... 2 common frames omitted



Please.

**Comment by mrniko** [comment]
Unable to reproduce it.
