### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hk0125** [redisson/redisson#3315]
Input code:
```
    Config config = new Config();
    config.useSingleServer().setAddress("redis://127.0.0.1");
    RedissonClient client = Redisson.create(config);
```

Exception Message:

**exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 8, end 5, length 17
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
	at java.base/java.lang.String.substring(String.java:1903)
	at org.redisson.misc.RedisURI.<init>(RedisURI.java:46)
	at org.redisson.connection.MasterSlaveConnectionManager.initSingleEntry(MasterSlaveConnectionManager.java:362)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:159)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:34)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200)
	at org.redisson.Redisson.<init>(Redisson.java:64)
	at org.redisson.Redisson.create(Redisson.java:104)**

Redisson version:
   **3.14.1**

**Comment by mrniko** [comment]
you need to define port as well

**Comment by hk231** [comment]
tks! it may be need a better exception handing

**Comment by dosmanak** [comment]
In kubernetes I'd like to specify the DNS of headless service and in that case, the port even does not make much sense.

**Comment by mrniko** [comment]
Fixed. Thanks for report
