### ISSUE TITLE
RedisTimeoutException: Unable to acquire connection after Redis cluster back to normal

### ISSUE THREAD

**Issue by JellyMilk** [redisson/redisson#3316]
my redisson version:3.12.3

redisson client:
config.setThreads(128).setNettyThreads(128).setCodec(new FstCodec()).setTransportMode(TransportMode.NIO)
                    .setLockWatchdogTimeout(15000)
                    .useClusterServers()
                    .setRetryAttempts(retryAttempts)
                    .setPassword(StringUtils.isBlank(redisPwd)?null:redisPwd)
                    .setLoadBalancer(new RoundRobinLoadBalancer())
                    .setSubscriptionConnectionPoolSize(200)
                    .setSubscriptionConnectionMinimumIdleSize(5)
                    .setSlaveConnectionPoolSize(Integer.parseInt(redisPoolSize)) //redisPoolSize = 512
                    .setMasterConnectionPoolSize(Integer.parseInt(redisPoolSize))
                    .setReadMode(ReadMode.SLAVE)
                    .setSubscriptionMode(SubscriptionMode.SLAVE)
                    .setPingConnectionInterval(0).setKeepAlive(false).setTcpNoDelay(false)
                    .addNodeAddress(redisArraynew);
            return Redisson.create(config);

I use redissonMap to caching data and use RScheduledExecutorService to schedule tasks. Why there's no connection to use  ? Looks for your help, thanks. 

My application error:
2020-12-29 06:02:47.279 [pool-6-thread-1] ERROR RedisCacheUtils [RedisCacheUtils.java:540] - org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=4568, addr=redis://192.168.11.248:6379, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('publish', KEYS..., 2, {v103_cache_tbl}:b2Qvj7NBl3bGr/xULuMlIQ:rw_lock, redisson_rwlock:{v103_cache_tbl}:b2Qvj7NBl3bGr/xULuMlIQ:rw_lock, 1, 15000, e610596c-cb9f-4603-b593-b31f470ef756:172:write] after 0 retry attempts
CommonException: org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=4568, addr=redis://192.168.11.248:6379, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('publish', KEYS..., 2, {v103_cache_tbl}:b2Qvj7NBl3bGr/xULuMlIQ:rw_lock, redisson_rwlock:{v103_cache_tbl}:b2Qvj7NBl3bGr/xULuMlIQ:rw_lock, 1, 15000, e610596c-cb9f-4603-b593-b31f470ef756:172:write] after 0 retry attempts
        RedisCacheUtils.lambda$init$20(RedisCacheUtils.java:537)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=4568, addr=redis://192.168.11.248:6379, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('publish', KEYS..., 2, {v103_cache_tbl}:b2Qvj7NBl3bGr/xULuMlIQ:rw_lock, redisson_rwlock:{v103_cache_tbl}:b2Qvj7NBl3bGr/xULuMlIQ:rw_lock, 1, 15000, e610596c-cb9f-4603-b593-b31f470ef756:172:write] after 0 retry attempts
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:180)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

2020-12-29 06:11:58.381 [pool-7-thread-1] ERROR RedisCacheUtils [RedisCacheUtils.java:552] - Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=381, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:200:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:1024:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.11.26:6380], nodeType=MASTER, firstFail=0]]], command: (HKEYS), params: [v103_sentry_cache] after 0 retry attempts
org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=381, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:200:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:1024:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.11.26:6380], nodeType=MASTER, firstFail=0]]], command: (HKEYS), params: [v103_sentry_cache] after 0 retry attempts
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:180)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2020-12-29 06:12:44.188 [pool-6-thread-1] ERROR RedisCacheUtils [RedisCacheUtils.java:540] - org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=4568, addr=redis://192.168.11.248:6379, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('hset', KEYS[1]..., 1, {v103_cache_tbl}:7swFf8RGPkVjjO6j8DrkYQ:rw_lock, 15000, e610596c-cb9f-4603-b593-b31f470ef756:172:write] after 0 retry attempts
CommonException: org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=4568, addr=redis://192.168.11.248:6379, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('hset', KEYS[1]..., 1, {v103_cache_tbl}:7swFf8RGPkVjjO6j8DrkYQ:rw_lock, 15000, e610596c-cb9f-4603-b593-b31f470ef756:172:write] after 0 retry attempts
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        
        
        
        
redis cluster log:		
master1:
22453:S 29 Dec 06:00:31.187 * Background saving terminated with success
22453:S 29 Dec 06:03:36.058 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
22453:S 29 Dec 06:05:32.040 * 10 changes in 300 seconds. Saving...		

slave1
2648:S 29 Dec 05:56:34.100 * Background AOF rewrite terminated with success
22648:S 29 Dec 05:56:34.101 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
22648:S 29 Dec 05:56:34.101 * Background AOF rewrite finished successfully
22648:S 29 Dec 05:57:25.008 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
22648:S 29 Dec 05:58:03.059 * 10 changes in 300 seconds. Saving...
22648:S 29 Dec 05:58:03.061 * Background saving started by pid 5394
5394:C 29 Dec 05:58:03.200 * DB saved on disk
5394:C 29 Dec 05:58:03.202 * RDB: 0 MB of memory used by copy-on-write
22648:S 29 Dec 05:58:03.261 * Background saving terminated with success
22648:S 29 Dec 06:03:04.039 * 10 changes in 300 seconds. Saving...

master2:
25990:M 29 Dec 05:53:58.201 * Background saving terminated with success
25990:M 29 Dec 05:56:09.391 * Marking node cf2733775061da5d63eaef8ac0fc38bcdd0db410 as failing (quorum reached).
25990:M 29 Dec 05:56:09.722 * Marking node ff6259256766f595afb6c887eaf51a04c4096583 as failing (quorum reached).
25990:M 29 Dec 05:56:11.307 * Clear FAIL state for node cf2733775061da5d63eaef8ac0fc38bcdd0db410: slave is reachable again.
25990:M 29 Dec 05:56:12.312 # Failover auth granted to cf2733775061da5d63eaef8ac0fc38bcdd0db410 for epoch 84
25990:M 29 Dec 05:56:14.034 * Clear FAIL state for node ff6259256766f595afb6c887eaf51a04c4096583: slave is reachable again.
25990:M 29 Dec 05:56:58.036 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
25990:M 29 Dec 05:58:59.050 * 10 changes in 300 seconds. Saving...
25990:M 29 Dec 05:58:59.051 * Background saving started by pid 20065
20065:C 29 Dec 05:58:59.097 * DB saved on disk
20065:C 29 Dec 05:58:59.098 * RDB: 0 MB of memory used by copy-on-write
25990:M 29 Dec 05:58:59.151 * Background saving terminated with success
25990:M 29 Dec 06:04:00.039 * 10 changes in 300 seconds. Saving...

slave2:
6251:S 29 Dec 05:56:08.713 * Marking node ff6259256766f595afb6c887eaf51a04c4096583 as failing (quorum reached).
26251:S 29 Dec 05:56:09.392 * FAIL message received from 8d50b5a9bc578993b77aa729294217a37f80e183 about cf2733775061da5d63eaef8ac0fc38bcdd0db410
26251:S 29 Dec 05:56:11.307 * Clear FAIL state for node cf2733775061da5d63eaef8ac0fc38bcdd0db410: slave is reachable again.
26251:S 29 Dec 05:56:13.188 * Clear FAIL state for node ff6259256766f595afb6c887eaf51a04c4096583: master without slots is reachable again.
26251:S 29 Dec 05:56:58.084 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
26251:S 29 Dec 05:57:03.085 * 10 changes in 300 seconds. Saving...
26251:S 29 Dec 05:57:03.086 * Background saving started by pid 18641
18641:C 29 Dec 05:57:03.371 * DB saved on disk
18641:C 29 Dec 05:57:03.372 * RDB: 0 MB of memory used by copy-on-write
26251:S 29 Dec 05:57:03.386 * Background saving terminated with success
26251:S 29 Dec 06:02:04.067 * 10 changes in 300 seconds. Saving...
26251:S 29 Dec 06:02:04.068 * Background saving started by pid 22346

master3:
21463:M 29 Dec 05:56:12.674 * Starting BGSAVE for SYNC with target: disk
21463:M 29 Dec 05:56:12.677 * Background saving started by pid 8971
8971:C 29 Dec 05:56:12.852 * DB saved on disk
8971:C 29 Dec 05:56:12.854 * RDB: 1 MB of memory used by copy-on-write
21463:M 29 Dec 05:56:12.908 * Background saving terminated with success
21463:M 29 Dec 05:56:12.919 * Synchronization with slave 192.168.11.26:6380 succeeded
21463:M 29 Dec 05:56:14.010 * Clear FAIL state for node ff6259256766f595afb6c887eaf51a04c4096583: slave is reachable again.
21463:M 29 Dec 05:57:02.028 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
21463:M 29 Dec 06:01:13.058 * 10 changes in 300 seconds. Saving...
21463:M 29 Dec 06:01:13.077 * Background saving started by pid 14460
14460:C 29 Dec 06:01:13.312 * DB saved on disk
14460:C 29 Dec 06:01:13.315 * RDB: 1 MB of memory used by copy-on-write
21463:M 29 Dec 06:01:13.378 * Background saving terminated with success

slave3:
21705:M 29 Dec 05:54:45.131 * Background saving terminated with success
21705:M 29 Dec 05:56:09.391 * FAIL message received from 8d50b5a9bc578993b77aa729294217a37f80e183 about cf2733775061da5d63eaef8ac0fc38bcdd0db410
21705:M 29 Dec 05:56:09.715 * Marking node ff6259256766f595afb6c887eaf51a04c4096583 as failing (quorum reached).
21705:M 29 Dec 05:56:11.305 * Clear FAIL state for node cf2733775061da5d63eaef8ac0fc38bcdd0db410: slave is reachable again.
21705:M 29 Dec 05:56:12.311 # Failover auth granted to cf2733775061da5d63eaef8ac0fc38bcdd0db410 for epoch 84
21705:M 29 Dec 05:56:14.002 * Clear FAIL state for node ff6259256766f595afb6c887eaf51a04c4096583: slave is reachable again.
21705:M 29 Dec 05:59:46.078 * 10 changes in 300 seconds. Saving...
21705:M 29 Dec 05:59:46.085 * Background saving started by pid 12375
12375:C 29 Dec 05:59:46.111 * DB saved on disk
12375:C 29 Dec 05:59:46.111 * RDB: 0 MB of memory used by copy-on-write
21705:M 29 Dec 05:59:46.185 * Background saving terminated with success
21705:M 29 Dec 06:03:29.010 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
21705:M 29 Dec 06:04:47.051 * 10 changes in 300 seconds. Saving...
21705:M 29 Dec 06:04:47.052 * Background saving started by pid 17249
17249:C 29 Dec 06:04:47.074 * DB saved on disk
17249:C 29 Dec 06:04:47.074 * RDB: 0 MB of memory used by copy-on-write
21705:M 29 Dec 06:04:47.152 * Background saving terminated with success

**Comment by JellyMilk** [comment]
port 6379 should be master and port 6380 should be slave.
Seems my redis cluster had a master-slave switch after back to normal:

cf2733775061da5d63eaef8ac0fc38bcdd0db410 192.168.11.248:6379 slave ff6259256766f595afb6c887eaf51a04c4096583 0 1609234238184 96 connected
9a18ffa9db843a6ce636fe8d7359f70cec59a307 192.168.11.26:6379 myself,master - 0 0 100 connected 5461-10922
21fbfe9a4b35d9e78ca8c199ab8983ceafbe4116 192.168.11.248:6380 slave 9a18ffa9db843a6ce636fe8d7359f70cec59a307 0 1609234240188 100 connected
ff6259256766f595afb6c887eaf51a04c4096583 192.168.11.26:6380 master - 0 1609234239185 96 connected 0-5460
c53b93ed799da727005832f1ae52c48f71864c4f 192.168.11.250:6380 slave 8d50b5a9bc578993b77aa729294217a37f80e183 0 1609234239685 90 connected
8d50b5a9bc578993b77aa729294217a37f80e183 192.168.11.250:6379 master - 0 1609234238184 90 connected 10923-16383

**Comment by mrniko** [comment]
did you resolve the issue?

**Comment by JellyMilk** [comment]
> did you resolve the issue?

No, still have problem.

when try to read key named "common_service_cache_configuration" failed. and the redis node try to connecting is the failed one 
 but now back again. the key in the slot can query from redis client but cannot by redisson. I have no idea about this.
![image](https://user-images.githubusercontent.com/35791895/103513496-b64cf800-4ea5-11eb-998f-49eebf0721a7.png)
25990:M 31 Dec 03:05:34.033 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
25990:M 31 Dec 03:05:45.036 * FAIL message received from 21fbfe9a4b35d9e78ca8c199ab8983ceafbe4116 about ff6259256766f595afb6c887eaf51a04c4096583
25990:M 31 Dec 03:05:45.036 * FAIL message received from cf2733775061da5d63eaef8ac0fc38bcdd0db410 about c53b93ed799da727005832f1ae52c48f71864c4f
25990:M 31 Dec 03:05:45.142 * Clear FAIL state for node ff6259256766f595afb6c887eaf51a04c4096583: slave is reachable again.
25990:M 31 Dec 03:05:45.839 # Failover auth denied to c53b93ed799da727005832f1ae52c48f71864c4f: its master is up
25990:M 31 Dec 03:05:45.864 # Connection with slave 192.168.11.250:6380 lost.
25990:M 31 Dec 03:05:45.881 # Configuration change detected. Reconfiguring myself as a replica of c53b93ed799da727005832f1ae52c48f71864c4f
25990:S 31 Dec 03:05:46.035 * Connecting to MASTER 192.168.11.250:6380
25990:S 31 Dec 03:05:46.035 * MASTER <-> SLAVE sync started
25990:S 31 Dec 03:05:46.035 * Non blocking connect for SYNC fired the event.
25990:S 31 Dec 03:05:46.036 * Master replied to PING, replication can continue...
25990:S 31 Dec 03:05:46.036 * Partial resynchronization not possible (no cached master)
25990:S 31 Dec 03:05:46.037 * Full resync from master: 2fc3269a640ac24ece68ed9dac6edf214b11ecf0:199501762
25990:S 31 Dec 03:05:46.136 * MASTER <-> SLAVE sync: receiving 1086166 bytes from master
25990:S 31 Dec 03:05:46.140 * MASTER <-> SLAVE sync: Flushing old data
25990:S 31 Dec 03:05:46.143 * MASTER <-> SLAVE sync: Loading DB in memory
25990:S 31 Dec 03:05:46.158 * MASTER <-> SLAVE sync: Finished with success
25990:S 31 Dec 03:05:46.163 * Background append only file rewriting started by pid 24966
25990:S 31 Dec 03:05:46.235 # Start of election delayed for 538 milliseconds (rank #0, offset 199501762).
25990:S 31 Dec 03:05:46.240 * AOF rewrite child asks to stop sending diffs.
24966:C 31 Dec 03:05:46.240 * Parent agreed to stop sending diffs. Finalizing AOF...
24966:C 31 Dec 03:05:46.241 * Concatenating 0.00 MB of AOF diff received from parent.
24966:C 31 Dec 03:05:46.241 * SYNC append only file rewrite performed
24966:C 31 Dec 03:05:46.243 * AOF rewrite: 0 MB of memory used by copy-on-write
25990:S 31 Dec 03:05:46.336 * Background AOF rewrite terminated with success
25990:S 31 Dec 03:05:46.336 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
25990:S 31 Dec 03:05:46.336 * Background AOF rewrite finished successfully
25990:S 31 Dec 03:05:46.837 # Starting a failover election for epoch 143.
25990:S 31 Dec 03:05:55.058 # Currently unable to failover: Waiting for votes, but majority still not reached.
25990:S 31 Dec 03:05:55.459 * Clear FAIL state for node c53b93ed799da727005832f1ae52c48f71864c4f: is reachable again and nobody is serving its slots after some time.


2021-01-04 15:46:09.187 [redisson-timer-4-1] DEBUG org.redisson.command.RedisExecutor [RedisExecutor.java:237] - attempt 12 for command (HGET) and params [common_service_cache_configuration, PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 256)]
2021-01-04 15:46:09.187 [redisson-timer-4-1] DEBUG org.redisson.command.RedisExecutor [RedisExecutor.java:612] - acquired connection for command (HGET) and params [common_service_cache_configuration, PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 256)] from slot NodeSource [slot=13203, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=5, freeSubscribeConnectionsCounter=value:200:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:2048:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.11.250:6379], nodeType=MASTER, firstFail=0]]] using node 192.168.11.250/192.168.11.250:6379... RedisConnection@1096414064 [redisClient=[addr=redis://192.168.11.250:6379], channel=[id: 0x893cb8d3, L:/192.168.11.26:59794 ! R:192.168.11.250/192.168.11.250:6379], currentCommand=null]
2021-01-04 15:46:09.190 [scheduling-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler [TaskUtils.java:96] - Unexpected error occurred in scheduled task.
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=13203, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=5, freeSubscribeConnectionsCounter=value:200:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:2048:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.11.250:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1096414064 [redisClient=[addr=redis://192.168.11.250:6379], channel=[id: 0x893cb8d3, L:/192.168.11.26:59794 ! R:192.168.11.250/192.168.11.250:6379], currentCommand=null], command: (HGET), params: [common_service_cache_configuration, PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 256)] after 12 retry attempts
        at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:270)
        at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58)
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:155)
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:152)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1018)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:874)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1365)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698)
        at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1091)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1062)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ExtendedClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

**Comment by mrniko** [comment]
set pingConnectionInterval = 5000

**Comment by JellyMilk** [comment]
> > Caused by: io.netty.channel.ExtendedClosedChannelException
> 
> set pingConnectionInterval = 5000

Thanks.After several days watching,  this setting works! Redisson debug log:
2021-01-08 09:56:50.512 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0xc2857cb8, L:/192.168.11.26:56356 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.512 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0xd079bb3d, L:/192.168.11.26:56360 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.512 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0x354f5b0d, L:/192.168.11.26:56352 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.512 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0x36990510, L:/192.168.11.26:56368 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.512 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0xc9ed0837, L:/192.168.11.26:56366 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.512 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0x1c607c20, L:/192.168.11.26:56364 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.512 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0x9781b3fd, L:/192.168.11.26:56362 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.513 [redisson-timer-4-1] DEBUG org.redisson.client.handler.PingConnectionHandler [PingConnectionHandler.java:73] - channel: [id: 0xfa80e61e, L:/192.168.11.26:56370 - R:192.168.11.248/192.168.11.248:6380] closed due to PING response timeout set in 3000 ms
2021-01-08 09:56:50.611 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisPubSubConnection@132932421 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0xa14785d9, L:/192.168.11.26:56348 ! R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@30a3068a(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
2021-01-08 09:56:50.611 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisPubSubConnection@372675536 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0x6c06723e, L:/192.168.11.26:56346 ! R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@124fd298(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
2021-01-08 09:56:50.612 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisConnection@1688983946 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0xd2008a32, L:/192.168.11.26:56344 ! R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4b5ba423(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
2021-01-08 09:56:50.612 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisConnection@456505540 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0xacb60d1e, L:/192.168.11.26:56350 ! 
R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2692c200(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
2021-01-08 09:56:50.612 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisConnection@1909134234 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0xf9b7a969, L:/192.168.11.26:56354 ! R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@ead070e(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
2021-01-08 09:56:50.612 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisPubSubConnection@1069823507 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0xa411213d, L:/192.168.11.26:56358 ! R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@629adf51(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
2021-01-08 09:56:50.612 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisConnection@1168005298 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0xc2857cb8, L:/192.168.11.26:56356 ! R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@74f6159d(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
2021-01-08 09:56:50.612 [redisson-timer-4-1] DEBUG org.redisson.client.handler.ConnectionWatchdog [ConnectionWatchdog.java:108] - reconnecting RedisConnection@1974016468 [redisClient=[addr=redis://192.168.11.248:6380], channel=[id: 0xd079bb3d, L:/192.168.11.26:56360 ! R:192.168.11.248/192.168.11.248:6380], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@44c45bc1(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.11.248:6380])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]] to 192.168.11.248/192.168.11.248:6380
