### ISSUE TITLE
aliyun redis cluster throw exception

### ISSUE THREAD

**Issue by colddew** [redisson/redisson#3325]
```
org.redisson.client.RedisException: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression. channel: [id: 0xf08ae8b0, L:/xxx - R:xxx] command: (EVAL), params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 3, token:refresh:xxx, {token:refresh:xxx}:value, {token:refresh:xxx}:value:xxx, 1]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
```

遇到与 #2754 一样的问题，使用redisson的RRateLimiter做限流，访问阿里云的cluster会抛上述异常。如果参考链接 https://www.cnblogs.com/tinywan/p/13064510.html 的解决方案，请问lua脚本在工程的什么位置改怎么改，或者有其它兼容或者解决办法吗，谢谢

**Comment by mrniko** [comment]
It's aliyun bug if you look closer at script you'll see that it uses KEYS[]

**Comment by colddew** [comment]
https://help.aliyun.com/document_detail/145968.html

![image](https://user-images.githubusercontent.com/6032545/104033581-b08b4580-520a-11eb-98bd-7a17b879fa5d.png)

咨询了阿里云的技术支持给出的答复是，云redis集群实例在使用lua脚本时，需要所有操作的key以数组形式来传递，且需要操作的key都在同一个slot中。另外看了redisson限流功能的lua脚本了，里面涉及多个key[]数组赋值给临时变量，感觉redisson的限流功能是被废了。暂时想到是重新按照lua脚本逻辑重写了，不确定直接改造lua脚本能不能实现
