### ISSUE TITLE
Avro utf8 string cannot be deserialized properly using JsonJacksonCodec

### ISSUE THREAD

**Issue by deltaark** [redisson/redisson#3327]
Avro Utf8 string cannot be deserialized properly by jsonjacksoncodec

Avro utf8 string is serialized as binary object but being deserialized as string hence causes transformation exception

12:12:48.700 [redisson-netty-2-11] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0xab6c8391, L:/127.0.0.1:60267 - R:/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=204, widx=204), command: (HGET), params: [SESSIONS, PooledUnsafeDirectByteBuf(ridx: 0, widx: 12, cap: 256)]
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 69] (through reference chain: com.avro.SessionData["displayName"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1148)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:63)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserializeWithType(StringDeserializer.java:71)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserializeWithType(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:147)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:710)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3503)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:95)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
12:12:48.700 [redisson-netty-2-11] DEBUG org.redisson.command.RedisExecutor - connection released for command (HGET) and params [SESSIONS, PooledUnsafeDirectByteBuf(ridx: 0, widx: 12, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@434413671 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xab6c8391, L:/127.0.0.1:60267 - R:/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@435e0643(failure: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 69] (through reference chain: com.avro.SessionData["displayName"]))], command=(HGET), params=[SESSIONS, PooledUnsafeDirectByteBuf(ridx: 0, widx: 12, cap: 256)], codec=org.redisson.codec.JsonJacksonCodec]]
Exception in thread "main" 12:12:48.701 [redisson-netty-2-11] ERROR org.redisson.client.handler.ErrorsLoggingHandler - Exception occured. Channel: [id: 0xab6c8391, L:/127.0.0.1:60267 - R:/127.0.0.1:6379]
io.netty.handler.codec.DecoderException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 69] (through reference chain: com.avro.SessionData["displayName"])
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Expected behavior**

Avro utf8 should be serialized as string and deserialized as string
OR
Avro utf8 should be serialized as binary object and deserialized as binary object

**Actual behavior**

Avro utf8 string is serialized as binary object but being deserialized as string hence causing transformation exception

**Steps to reproduce or test case**
avro sample used
``
{
    "name": "SessionData",
    "type": "record",
    "namespace": "com.avro",
    "doc": "Session information",
    "fields": [
      {
        "name": "sessionId",
        "type": [
            "null",
            "string"
        ],
        "doc": "the unique identifier for the session"
      },
      {
        "name": "displayName",
        "type": [
            "null",
            "string"
        ],
        "doc": "the display name of participant"
      },
      {
        "name": "updateTimeMillis",
        "type": "long",
        "doc": "timestamp(miliseconds since wpoch) at which this dialog was last updated"
      }
    ]
  }
`
Code Sample
`
package com.redis.redissampleconnector;

import java.util.HashMap;
import java.util.Map;

import org.apache.avro.util.Utf8;
import org.redisson.Redisson;
import org.redisson.api.RMap;
import org.redisson.api.RedissonClient;
import org.redisson.codec.JsonJacksonCodec;

import com.avro.SessionData;

public class RedisCodecJsonJacksonTest {
	private static RMap<String, SessionData> sessionRMap = null;
	
	public static void main(String[] args) {

		String keyStr = "keytest123";
		RedissonClient redissonClient = Redisson.create();

		JsonJacksonCodec testCodec = new JsonJacksonCodec();
		testCodec.getObjectMapper().findAndRegisterModules();

		sessionRMap = redissonClient.getMap("SESSIONS", testCodec);
		
		SessionData testSession  = new SessionData();
		testSession.setUpdateTimeMillis(System.currentTimeMillis());

		testSession.setDisplayName(keyStr);

		testSession.setDisplayName(new Utf8("James"));
		System.out.println("Current Time: " + testSession.getUpdateTimeMillis() );
		sessionRMap.put(keyStr, testSession);
		
		SessionData retSession = sessionRMap.get(keyStr);
		
		System.out.println("Stored Time: " + retSession.getUpdateTimeMillis() );
		
		
	}

}
`

**Redis version**

**Redisson version**

**Redisson configuration**

**Comment by mrniko** [comment]
you need to define AvroJacksonCodec explicitly with type and AvroSchema

**Comment by deltaark** [comment]
AvroJacksonCodec has lot of limitation doesn't support map or "Any" type


`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: "Any" type (usually for `java.lang.Object`) not supported: `expectAnyFormat` called with type [simple type, class java.lang.annotation.Annotation]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.dataformat.avro.schema.VisitorFormatWrapperImpl.expectAnyFormat(VisitorFormatWrapperImpl.java:174)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.acceptJsonFormatVisitor(UnknownSerializer.java:66)
	at com.fasterxml.jackson.dataformat.avro.schema.ArrayVisitor.itemsFormat(ArrayVisitor.java:57)
	at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.acceptJsonFormatVisitor(ObjectArraySerializer.java:332)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.schemaFieldForWriter(RecordVisitor.java:174)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.optionalProperty(RecordVisitor.java:117)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:840)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:897)
	at com.fasterxml.jackson.dataformat.avro.schema.ArrayVisitor.itemsFormat(ArrayVisitor.java:57)
	at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.acceptJsonFormatVisitor(ObjectArraySerializer.java:332)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.schemaFieldForWriter(RecordVisitor.java:174)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.optionalProperty(RecordVisitor.java:117)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:840)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:897)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.schemaFieldForWriter(RecordVisitor.java:174)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.optionalProperty(RecordVisitor.java:117)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:840)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:897)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.schemaFieldForWriter(RecordVisitor.java:174)
	at com.fasterxml.jackson.dataformat.avro.schema.RecordVisitor.optionalProperty(RecordVisitor.java:117)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:840)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:897)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4358)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4337)
	at com.fasterxml.jackson.dataformat.avro.AvroMapper.schemaFor(AvroMapper.java:186)`

**Comment by mrniko** [comment]
Try to use another codec in this case.

**Comment by deltaark** [comment]
Most codecs failed as they don't support null values. Jackson and Avro support these.

**Comment by mrniko** [comment]
Did you try MarshallingCodec?
