### ISSUE TITLE
Problem with serialisation/deserialisation query cache for Hibernate Cache

### ISSUE THREAD

**Issue by rhrytsiv** [redisson/redisson#3331]
I am using:

- redisson 3.14.1
- hibernate 5.4.12

codec: **SnappyCodec**
When I try to put query data to Redis I receive an error

`Caused by: java.lang.IllegalArgumentException: java.io.NotSerializableException: org.hibernate.metamodel.model.convert.internal.JpaAttributeConverterImpl
	at org.redisson.command.CommandAsyncService.encodeMapKey(CommandAsyncService.java:727) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.RedissonObject.encodeMapKey(RedissonObject.java:297) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.RedissonMapCache.getOperationAsync(RedissonMapCache.java:524) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.RedissonMap.getAsync(RedissonMap.java:1072) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.RedissonMap.get(RedissonMap.java:618) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.hibernate.RedissonStorage.getFromCache(RedissonStorage.java:102) ~[redisson-hibernate-53-3.14.1.jar:3.14.1]
	... 136 common frames omitted
Caused by: java.io.NotSerializableException: org.hibernate.metamodel.model.convert.internal.JpaAttributeConverterImpl
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1080) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50) ~[jboss-marshalling-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344) ~[na:1.8.0_191]
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790) ~[na:1.8.0_191]
	at java.util.HashMap.writeObject(HashMap.java:1363) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:163) ~[jboss-marshalling-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:193) ~[jboss-marshalling-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1089) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268) ~[jboss-marshalling-river-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58) ~[jboss-marshalling-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111) ~[jboss-marshalling-2.0.10.Final.jar:2.0.10.Final]
	at org.redisson.codec.MarshallingCodec$4.encode(MarshallingCodec.java:170) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.codec.SnappyCodec$4.encode(SnappyCodec.java:96) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.command.CommandAsyncService.encodeMapKey(CommandAsyncService.java:725) ~[redisson-3.14.1.jar:3.14.1]
	... 141 common frames omitted
Caused by: org.jboss.marshalling.TraceInformation: null`

Then I try to change the codec to **Kryo5Codec**
`Caused by: com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): org.hibernate.cache.internal.QueryResultsCacheImpl$CacheItem
	at com.esotericsoftware.kryo.util.DefaultInstantiatorStrategy.newInstantiatorOf(DefaultInstantiatorStrategy.java:114) ~[kryo-5.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1119) ~[kryo-5.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1128) ~[kryo-5.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:153) ~[kryo-5.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:118) ~[kryo-5.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-5.0.3.jar:na]
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:95) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) ~[redisson-3.14.1.jar:3.14.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102) ~[redisson-3.14.1.jar:3.14.1]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	... 1 common frames omitted`

What am I doing wrong?

**Comment by mrniko** [comment]
can you provide test code to reproduce it?

**Comment by rhrytsiv** [comment]
Entity:
`@Entity
@Table(name = "account_quota_messages")
@Getter
@Setter
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class AccountQuotaMessagesEntity extends BaseDateTrackingEntity {

  @EmbeddedId private AccountQuotaMessagesKey id;

  @Column(name = "daily_messages_limit", nullable = false)
  private Integer dailyMessagesLimit;

  @Column(name = "monthly_messages_limit", nullable = false)
  private Integer monthlyMessagesLimit;
}`

EmbeddedId:
`@Embeddable
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class AccountQuotaMessagesKey implements Serializable {

  @ManyToOne
  @JoinColumn(name = "account_id", nullable = false)
  private AccountEntity account;

  @Column(name = "message_channel_id", nullable = false, columnDefinition = "TINYINT")
  @Convert(converter = ChannelTypeConverter.class)
  private ChannelType channelType;
}`

Repository:
`  @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
  @QueryHints(@QueryHint(name = "org.hibernate.cacheable", value = "true"))
  @Query(
      "SELECT aqm.monthlyMessagesLimit FROM AccountQuotaMessagesEntity aqm "
          + "WHERE aqm.id.account.id = :accountId AND aqm.id.channelType = :channelType")
  Integer findAccountMonthlyMessagesLimitForChannelType(
      @Param("accountId") String accountId, @Param("channelType") ChannelType channelType);`

Redisson config:
`public static Config createCacheConfig(Map<String, String> props) {
    Config config = new Config();
    config.setCodec(new SnappyCodec());

    ReplicatedServersConfig replicatedServersConfig =
        config
            .useReplicatedServers()
            // connection
            .addNodeAddress(props.get(HOSTS).split(","))
            .setRetryAttempts(Integer.parseInt(props.get(CACHE_CONNECT_RETRIES)))
            .setConnectTimeout(Integer.parseInt(props.get(CACHE_CONNECT_TIMEOUT)))
            .setReadMode(ReadMode.MASTER_SLAVE)
            // pools sizes
            .setSlaveConnectionPoolSize(Integer.parseInt(props.get(CONNECTION_POOL_SIZE)))
            .setSlaveConnectionMinimumIdleSize(
                Integer.parseInt(props.get(CONNECTION_POOL_SIZE_IDLE)))
            .setMasterConnectionPoolSize(Integer.parseInt(props.get(CONNECTION_POOL_SIZE)))
            .setMasterConnectionMinimumIdleSize(
                Integer.parseInt(props.get(CONNECTION_POOL_SIZE_IDLE)))
            // subscription pools sizes
            .setSubscriptionConnectionPoolSize(Integer.parseInt(props.get(SUBSCRIPTION_POOL_SIZE)))
            .setSubscriptionConnectionMinimumIdleSize(
                Integer.parseInt(props.get(SUBSCRIPTION_POOL_SIZE_IDLE)))
            .setSubscriptionsPerConnection(
                Integer.parseInt(props.get(SUBSCRIPTION_PER_CONNECTION)));



    return config;
  }`

**Comment by mrniko** [comment]
try to implement query without repository method.

**Comment by ivan909020** [comment]
When I want to pass Instant to a method attribute I got the same exception (Caused by: java.lang.IllegalArgumentException: java.io.NotSerializableException: org.hibernate.metamodel.model.convert.internal.JpaAttributeConverterImpl)

Query example: 

QueryHints({ @QueryHint(name = CACHEABLE, value = "true")}) 
Entity findByIdAndExpirationDate(Long id, Instant expirationDate);

It works without the Instant attribute. In the database, the expirationDate type is timestamp.

**Comment by mrniko** [comment]
let me check that

**Comment by ivan909020** [comment]
The error is reproduced only with this converter, without it everything works.

@Converter(autoApply = true)
public class InstantConverter implements AttributeConverter<Instant, Timestamp> {

    @Override
    public Timestamp convertToDatabaseColumn(Instant instant) {
        return instant != null ? Timestamp.from(instant) : null;
    }

    @Override
    public Instant convertToEntityAttribute(Timestamp timestamp) {
        return timestamp != null ? timestamp.toInstant() : null;
    }

}

**Comment by ivan909020** [comment]
I guess redisson does not support `AttributeConverter`

**Comment by mrniko** [comment]
Seems it's a hibernate bug because it doesn't work even with `CachingRegionFactory.class` cache provider.

**Comment by mrniko** [comment]
@ivan909020 

Does it work with `CachingRegionFactory.class` ?
