### ISSUE TITLE
BaseRedisBatchExecutor NullPointerException with Redis Cluster

### ISSUE THREAD

**Issue by avcad** [redisson/redisson#3353]
Redisson 3.14 - Redis Cluster with cluster-require-full-coverage=no throwing NPE

I believe the NullPointerException happens because the slot is not allocated.  "MasterSlaveEntry msEntry = getEntry(source);"
returns null, and then get() is called with a null parameter, which is not allowed by the ConcurrentHashMap
Entry entry = commands.get(msEntry);

```
java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:947)
at org.redisson.command.BaseRedisBatchExecutor.addBatchCommandData(BaseRedisBatchExecutor.java:72)
at org.redisson.command.RedisBatchExecutor.execute(RedisBatchExecutor.java:53)
at org.redisson.command.CommandBatchService.async(CommandBatchService.java:144)
at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:367)
at org.redisson.RedissonMap.getAllOperationAsync(RedissonMap.java:260)
at org.redisson.RedissonMap.getAllAsync(RedissonMap.java:226)
```

Could this be updated to return a Redisson exception?

**Comment by mrniko** [comment]
Fixed! Thanks for report
