### ISSUE TITLE
Redis Cluster master down and restart，redisson can‘t update cluster state

### ISSUE THREAD

**Issue by xiaowenyu** [redisson/redisson#3357]
**Expected behavior**
redis cluster master down one by one.After a period of time, restart master node, redisson client can't update cluster state

**Actual behavior**
redisson can't write command to master, and report error.

**Steps to reproduce or test case**
It doesn't have to happen
**1.test case**
    3 master and 3 slave
1.   master 1 down and wait slave 1 become master
2.   master 2 down and wait slave 2 become master
3.   master 3 down and wait slave 3 become master
4.  restart all master and There's a certain probability

**2.redisson can't update cluster state exception**
```java
WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=9394, addr=null, redisClient=null, redirect=null, entry=null], connection:
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:271) ~[redisson-3.14.0.jar:3.14.0]
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58) ~[redisson-3.14.0.jar:3.14.0]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:156) ~[redisson-3.14.0.jar:3.14.0]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:153) ~[redisson-3.14.0.jar:3.14.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1009) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:870) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
```

**3. a redisson-netty thread is runnable and recursion all the time** 
```java
"redisson-netty-2-19" #31 prio=5 os_prio=0 tid=0x00007fac4c03c800 nid=0x4cd5 runnable [0x00007fac9c511000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	- locked <0x00000000fbf21860> (a org.redisson.client.RedisConnectionException)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at org.redisson.client.RedisException.<init>(RedisException.java:35)
	at org.redisson.client.RedisConnectionException.<init>(RedisConnectionException.java:28)
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218)
	at org.redisson.connection.pool.PubSubConnectionPool.get(PubSubConnectionPool.java:32)
	at org.redisson.connection.pool.PubSubConnectionPool.get(PubSubConnectionPool.java:39)
	at org.redisson.connection.balancer.LoadBalancerManager.nextPubSubConnection(LoadBalancerManager.java:204)
	at org.redisson.connection.MasterSlaveEntry.nextPubSubConnection(MasterSlaveEntry.java:519)
	at org.redisson.pubsub.PublishSubscribeService.nextPubSubConnection(PublishSubscribeService.java:267)
	at org.redisson.pubsub.PublishSubscribeService.connect(PublishSubscribeService.java:273)
	at org.redisson.pubsub.PublishSubscribeService.access$200(PublishSubscribeService.java:55)
	at org.redisson.pubsub.PublishSubscribeService$1.run(PublishSubscribeService.java:164)
	at org.redisson.pubsub.AsyncSemaphore.tryRun(AsyncSemaphore.java:86)
	at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:66)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:150)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$0(PublishSubscribeService.java:127)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$68/1506703662.run(Unknown Source)
	at org.redisson.pubsub.AsyncSemaphore.tryRun(AsyncSemaphore.java:86)
	at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:66)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:121)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:115)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:575)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$8(PublishSubscribeService.java:578)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$108/720202126.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:118)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:842)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:499)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:576)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$8(PublishSubscribeService.java:578)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$108/720202126.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:576)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$8(PublishSubscribeService.java:578)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$108/720202126.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:576)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$8(PublishSubscribeService.java:578)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$108/720202126.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:576)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$8(PublishSubscribeService.java:578)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$108/720202126.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:576)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$8(PublishSubscribeService.java:578)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$108/720202126.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:576)
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$8(PublishSubscribeService.java:578)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$108/720202126.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:576)
	at org.redisson.pubsub.PublishSubscribeService.lambda$reattachPubSubListeners$7(PublishSubscribeService.java:568)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$107/1175549604.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at org.redisson.misc.RedissonPromise$$Lambda$2/1011276990.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.pubsub.PublishSubscribeService$5$1$1.onStatus(PublishSubscribeService.java:430)
	at org.redisson.pubsub.PubSubConnectionEntry$1.onStatus(PubSubConnectionEntry.java:187)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:72)
	at org.redisson.client.RedisPubSubConnection$1.operationComplete(RedisPubSubConnection.java:116)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1009)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:870)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Redefined)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(Redefined)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```
**4.Redis version**
6.0.9
**5.Redisson version**
3.14.1

**6.Redisson configuration**
```java
clusterServersConfig:
  idleConnectionTimeout: 60000
  connectTimeout: 10000
  timeout: 60000
  retryAttempts: 3
  retryInterval: 3000
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: "xuanwu-T3st*17"
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 4
  slaveConnectionMinimumIdleSize: 16
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 16
  masterConnectionPoolSize: 64
  readMode: "MASTER_SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "redis://172.16.0.114:8001"
    - "redis://172.16.0.114:8002"
    - "redis://172.16.0.114:8003"
    - "redis://172.16.0.115:8001"
    - "redis://172.16.0.115:8002"
    - "redis://172.16.0.115:8003"
  scanInterval: 2000
  pingConnectionInterval: 5000
  keepAlive: true
  tcpNoDelay: true
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"
useScriptCache: true
```

**Comment by tony1991** [comment]
I‘ve met this problem too. How to deal this question?

**Comment by yusufdaud** [comment]
@xiaowenyu What was the solution

**Comment by Chippyer** [comment]
@xiaowenyu Can you share the process
