### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException

### ISSUE THREAD

**Issue by hczc** [redisson/redisson#3377]
**Expected behavior**

When redis runs for a period of time, there will be abnormal connection
**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
Redis 5.0 
**Redisson version**
3.14.0
**Redisson configuration**
```
Caused by: org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1080288245 [redisClient=[addr=redis://r-wz958c8j0wv3627b5h.redis.rds.aliyuncs.com:6379], channel=[id: 0x3d7905c2, L:/10.0.103.116:53932 ! R:r-wz958c8j0wv3627b5h.redis.rds.aliyuncs.com/10.0.103.175:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@443b360c(failure: java.util.concurrent.CancellationException)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 121, 110, 99, 84, 114, 97, 100, 101, 58, ...]] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:271)
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:156)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:153)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```
```
Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1080288245 [redisClient=[addr=redis://r-wz958c8j0wv3627b5h.redis.rds.aliyuncs.com:6379], channel=[id: 0x3d7905c2, L:/10.0.103.116:53932 ! R:r-wz958c8j0wv3627b5h.redis.rds.aliyuncs.com/10.0.103.175:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@443b360c(failure: java.util.concurrent.CancellationException)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 121, 110, 99, 84, 114, 97, 100, 101, 58, ...]] after 3 retry attempts; nested exception is org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1080288245 [redisClient=[addr=redis://r-wz958c8j0wv3627b5h.redis.rds.aliyuncs.com:6379], channel=[id: 0x3d7905c2, L:/10.0.103.116:53932 ! R:r-wz958c8j0wv3627b5h.redis.rds.aliyuncs.com/10.0.103.175:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@443b360c(failure: java.util.concurrent.CancellationException)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 121, 110, 99, 84, 114, 97, 100, 101, 58, ...]] after 3 retry attempts
```

**Comment by mrniko** [comment]
try to set pingConnectionInterval = 5000

**Comment by hczc** [comment]
What does it mean pingConnectionInterval ？

**Comment by mrniko** [comment]
used for ping connections. current value is 30 secs, but you can try to reduce it to 5 seconds. This helped to some users

**Comment by Yuxuebing** [comment]
Have you fix it?

**Comment by Yuxuebing** [comment]
Have you fix it? @hczc

**Comment by SagarParikh93** [comment]
@hczc , Can you please tell above solution worked for you or not?

**Comment by jamesbury3** [comment]
Hi @hczc I've been seeing the same issue with redisson 3.16.8 and was also wondering whether changing the pingConnectionInterval resolved this for you. Also, I wanted to check if you needed to update your retryInterval and retryAttempts values

**Comment by mlakshminara** [comment]
@mrniko 

Can you confirm whether reducing pingInterval property solves org.redisson.client.WriteRedisConnectionException. We are experiencing this issue when executing Redis commands

Redis version: 3.16.0
