### ISSUE TITLE
version  upgrade

### ISSUE THREAD

**Issue by wl980868110** [redisson/redisson#3392]
redisson-all-3.12.1.jar  upgrade  redisson-all-3.14.0.jar 
compiler error  
org.nustaq.serialization.annotations.Version;    cannot find      so  add  fst-2.57.jar
start fail   
java.lang.NoClassDefFoundError: org/objenesis/Objenesis
	at org.redisson.codec.FstCodec.<init>(FstCodec.java:182)
	at com.game.logical.global.RedissonUtils.buildRedissonConfig(RedissonUtils.java:45)
	at com.game.logical.global.RedissonUtils.<init>(RedissonUtils.java:35)
Caused by: java.lang.ClassNotFoundException: org.objenesis.Objenesis
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

add objenesis-2.5.1.jar
normal start  
org.redisson.transaction.TransactionException: Unable to execute transaction
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:287)
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:258)

Caused by: org.redisson.client.RedisException: ERR unknown command 'WAIT'. channel: [id: 0x7208d34e, L:/10.2.100.83:20976 - R:/10.2.12.183:6379] command: (WAIT), params: [1, 5000]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:343)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:247)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:189)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)

redisson-all-3.12.1.jar  升级到  redisson-all-3.14.0.jar 
 Import  org.nustaq.serialization.annotations.Version  报错  我就添加了 fst-2.57.jar
启动时报错
java.lang.NoClassDefFoundError: org/objenesis/Objenesis
	at org.redisson.codec.FstCodec.<init>(FstCodec.java:182)
	at com.game.logical.global.RedissonUtils.buildRedissonConfig(RedissonUtils.java:45)
	at com.game.logical.global.RedissonUtils.<init>(RedissonUtils.java:35)
Caused by: java.lang.ClassNotFoundException: org.objenesis.Objenesis
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Could you tell me how to resolve this problem

我就添加了
add objenesis-2.5.1.jar
能正常启动 但是在执行事务是异常  事务混滚

org.redisson.transaction.TransactionException: Unable to execute transaction
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:287)
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:258)

Caused by: org.redisson.client.RedisException: ERR unknown command 'WAIT'. channel: [id: 0x7208d34e, L:/10.2.100.83:20976 - R:/10.2.12.183:6379] command: (WAIT), params: [1, 5000]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:343)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:247)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:189)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)

**Comment by mrniko** [comment]
> ERR unknown command 'WAIT`

update your Redis to 3.0+
