### ISSUE TITLE
Can't execute SENTINEL commands on /192.168.28.129:63376

### ISSUE THREAD

**Issue by 983674707** [redisson/redisson#3404]
## exception log
```
Can't execute SENTINEL commands on /192.168.28.129:63376

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL SENTINELS), params: [mymaster], Redis client: [addr=redis://192.168.28.129:63376]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
**There are three sentinels in total. This anomaly occurs every time you start it. A sentinel anomaly appears randomly, but it can be used normally.**

**Comment by 983674707** [comment]
> ## exception log
> ```
> Can't execute SENTINEL commands on /192.168.28.129:63376
> 
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL SENTINELS), params: [mymaster], Redis client: [addr=redis://192.168.28.129:63376]
> 	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207)
> 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
> 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
> 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)
> ```
> 
> **There are three sentinels in total. This anomaly occurs every time you start it. A sentinel anomaly appears randomly, but it can be used normally.**

**Comment by mrniko** [comment]
Have you resolved the issue?

**Comment by 983674707** [comment]
@mrniko No, it's weird, it should not be my code problem
## code
```
/**
 * @author 冷益飞
 * @date 2020/12/7 14:34
 * @description redisson
 **/
@Configuration
public class RedissonConfiguration {
    /**
     * redisson 连接地址格式
     */
    private static final String REDISSON_FORMAT = "redis://%s:%s";

    /**
     * @author 冷益飞
     * @date 2021/1/13
     * @description 转redis连接地址
     * @param hostname:
     * @param port:
     * @return {@link String}
     **/
    private String format(String hostname, int port) {
        return String.format(REDISSON_FORMAT, hostname, port);
    }

    /**
     * @author 冷益飞
     * @date 2020/12/7
     * @description RedissonClient
     * @param redisConnectionFactory:
     * @return {@link RedissonClient}
     **/
    @Bean
    public RedissonClient redissonClient(RedisConnectionFactory redisConnectionFactory) {
        Config config = new Config().setCodec(new StringCodec());
        LettuceConnectionFactory factory = (LettuceConnectionFactory) redisConnectionFactory;
        RedisSentinelConfiguration sentinelConfiguration = factory.getSentinelConfiguration();
        // sentinel 模式
        if (sentinelConfiguration != null) {
            // sentinel节点
            String[] sentinelNodes = sentinelConfiguration.getSentinels()
                    .stream()
                    .filter(p -> StringUtils.isNotBlank(p.getHost()) && p.getPort() != null)
                    .map(p -> format(p.getHost(), p.getPort()))
                    .toArray(String[]::new);

            // 构造redissonClient配置信息
            config.useSentinelServers()
                    .addSentinelAddress(sentinelNodes)
                    .setMasterName(sentinelConfiguration.getMaster() == null ? null : sentinelConfiguration.getMaster().getName())
                    .setReadMode(ReadMode.SLAVE)
                    .setPassword(factory.getPassword())
                    .setSentinelPassword(new String(sentinelConfiguration.getSentinelPassword().get()))
                    .setDatabase(sentinelConfiguration.getDatabase());
            return Redisson.create(config);
        }
        // single 模式
        config.useSingleServer().setAddress(format(factory.getHostName(), factory.getPort())).setPassword(factory.getPassword());
        return Redisson.create(config);
    }
}

```
## application.yml
```
spring:
  redis:
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-idle: 8
        max-wait: 10s
        min-idle: 2
      shutdown-timeout: 3s
    database: 0
    sentinel:
      master: mymaster
      password: 123456
      nodes: 192.168.28.129:63376,192.168.28.129:63377,192.168.28.129:63378
    password: 654321
```
## pom.xml
```
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>3.15.0</version>
            </dependency>
```

**Comment by yun-yun** [comment]
same problem.
like https://github.com/redisson/redisson/issues/3283
through the test,:
this not happen in 3.12.4
this will happen in  3.12.5 or higher

My current version is 3.15.0, and I use this configuration so that it doesn't report errors:
```
Config config = new Config();
config.useSentinelServers()
        .addSentinelAddress("redis://192.168.55.181:26379",
                "redis://192.168.55.182:26379",
                "redis://192.168.55.183:26379")
        .setDatabase(1)
        .setPassword("*****")
        .setTimeout(30000)
        .setMasterName("mymaster");
RedissonClient redisson = Redisson.create(config);
```
If I don't set this amount of timeout, it will report an error.
```
14:36:42.380 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.181:6379 to redis://192.168.55.181:6379
14:36:42.384 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.14:6379 to redis://192.168.55.14:6379
14:36:42.384 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.181:6379 to redis://192.168.55.181:6379
14:36:51.412 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.15:6379 to redis://192.168.55.15:6379
14:36:51.412 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.181:6379 to redis://192.168.55.181:6379
14:37:02.482 [redisson-timer-4-1] ERROR org.redisson.connection.SentinelConnectionManager - Can't execute SENTINEL commands on /192.168.55.183:26375
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL SENTINELS), params: [mymaster], Redis client: [addr=redis://192.168.55.183:26375]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
14:37:09.475 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.14:6379 to redis://192.168.55.14:6379
14:37:09.475 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.181:6379 to redis://192.168.55.181:6379
14:37:09.475 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.15:6379 to redis://192.168.55.15:6379
```

**Comment by mrniko** [comment]
Fix merged

**Comment by fei406854287** [comment]
i use redisson version is 3.14.1 ,so i have the same  issue.   after i add .setCheckSentinelsList(false),   the   exception not ever happen.  :) :)
