### ISSUE TITLE
error in simple for loop: Command still hasn't been written into connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. 

### ISSUE THREAD

**Issue by yun-yun** [redisson/redisson#3430]
environment:
redisson: 3.15.0
redis: 6.0.10

when i use this procedure:

```
public static void main(String[] args) throws InterruptedException {
        Config config = new Config();
        config.useSentinelServers()
                .addSentinelAddress("redis://192.168.55.181:26375",
                        "redis://192.168.55.182:26375",
                        "redis://192.168.55.183:26375")
                .setDatabase(1)
                .setPassword("******")
                .setTimeout(20000)
                .setMasterName("mymaster");
        RedissonClient redisson = Redisson.create(config);

        for (int i = 0; i < 100; i++) {
            RBucket<Object> aaa = redisson.getBucket("aaa");
            aaa.set("bbb", 1, TimeUnit.MINUTES);
            System.out.println(i);
            Thread.sleep(1000);
        }

        Thread.sleep(1000 * 60 * 10);
        redisson.shutdown();
    }
```

it will print:
```
11
14:51:14.439 [main] DEBUG org.redisson.command.RedisExecutor - acquired connection for command (PSETEX) and params [aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using node /192.168.55.181:6379... RedisConnection@1534083691 [redisClient=[addr=redis://192.168.55.181:6379], channel=[id: 0x0b3be710, L:/192.168.21.91:5368 - R:/192.168.55.181:6379], currentCommand=null]
14:51:14.442 [redisson-netty-2-29] DEBUG org.redisson.command.RedisExecutor - connection released for command (PSETEX) and params [aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@1534083691 [redisClient=[addr=redis://192.168.55.181:6379], channel=[id: 0x0b3be710, L:/192.168.21.91:5368 - R:/192.168.55.181:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@cfb74d3(success)], command=(PSETEX), params=[aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)], codec=org.redisson.codec.MarshallingCodec]]
12
14:51:15.443 [main] DEBUG org.redisson.command.RedisExecutor - acquired connection for command (PSETEX) and params [aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using node /192.168.55.181:6379... RedisConnection@1591385168 [redisClient=[addr=redis://192.168.55.181:6379], channel=[id: 0xe0810f73, L:/192.168.21.91:5370 - R:/192.168.55.181:6379], currentCommand=null]
14:51:15.446 [redisson-netty-2-10] DEBUG org.redisson.command.RedisExecutor - connection released for command (PSETEX) and params [aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@1591385168 [redisClient=[addr=redis://192.168.55.181:6379], channel=[id: 0xe0810f73, L:/192.168.21.91:5370 - R:/192.168.55.181:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5c2126ad(success)], command=(PSETEX), params=[aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)], codec=org.redisson.codec.MarshallingCodec]]
13
14:51:16.456 [main] DEBUG org.redisson.command.RedisExecutor - acquired connection for command (PSETEX) and params [aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using node /192.168.55.181:6379... RedisConnection@950739596 [redisClient=[addr=redis://192.168.55.181:6379], channel=[id: 0x8c317eb9, L:/192.168.21.91:5371 - R:/192.168.55.181:6379], currentCommand=null]
14:51:22.812 [redisson-timer-4-1] DEBUG org.redisson.command.RedisExecutor - connection released for command (PSETEX) and params [aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@950739596 [redisClient=[addr=redis://192.168.55.181:6379], channel=[id: 0x8c317eb9, L:/192.168.21.91:5371 - R:/192.168.55.181:6379], currentCommand=null]
Exception in thread "main" org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. Try to increase nettyThreads setting. Payload size in bytes: 6. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@950739596 [redisClient=[addr=redis://192.168.55.181:6379], channel=[id: 0x8c317eb9, L:/192.168.21.91:5371 - R:/192.168.55.181:6379], currentCommand=null], command: (PSETEX), params: [aaa, 60000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:205)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
14:51:30.290 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.14:6379 to redis://192.168.55.14:6379
14:51:30.290 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.181:6379 to redis://192.168.55.181:6379
14:51:32.318 [redisson-timer-4-1] ERROR org.redisson.connection.SentinelConnectionManager - Can't execute SENTINEL commands on /192.168.55.182:26375
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL SENTINELS), params: [mymaster], Redis client: [addr=redis://192.168.55.182:26375]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
14:51:39.315 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.181:6379 to redis://192.168.55.181:6379
14:51:39.316 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.15:6379 to redis://192.168.55.15:6379
14:51:39.316 [redisson-netty-2-31] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.14:6379 to redis://192.168.55.14:6379
14:51:49.328 [redisson-netty-2-12] DEBUG org.redisson.connection.SentinelConnectionManager - nat mapped uri: redis://192.168.55.181:6379 to redis://192.168.55.181:6379
```

**Comment by mrniko** [comment]
Unable to reproduce.

Please record session with https://jdk.java.net/jmc/7/ and share result file.

**Comment by yun-yun** [comment]
Haven't got a clue
[flight_recording_180181testredisRedissonDemo10956_2021-02-22_17-42-50_4aa13753.zip](https://github.com/redisson/redisson/files/6021071/flight_recording_180181testredisRedissonDemo10956_2021-02-22_17-42-50_4aa13753.zip)

**Comment by mrniko** [comment]
You have two exceptions. I need full stacktraces from logs.
