### ISSUE TITLE
How to handle Avro schema change in Redisson

### ISSUE THREAD

**Issue by brijnkh** [redisson/redisson#3433]

**Comment by mrniko** [comment]
You need to store AvroSchema somethere and then use it explicitly during acquiring Redisson objects.

```java
AvroSchema schema = ....

RList<MyObject> list = redisson.getList("myList", new AvroJacksonCodec(MyObject.class, schema));
```

**Comment by brijnkh** [comment]
Hi Nikita,

In this case as well, schema will be fixed..
It is possible that in the list, objects are there with different versions
of schemas.
So it is not possible by storing schema somewhere. Because at a point
of retrieving the list we do not know what kind of schema we are going to
face.
I think we need to find a way to make it backward compatible.

Regards
Brijesh

**Comment by mrniko** [comment]
I introduced AvroVersionedJacksonCodec. It supports multiple types with single writeSchema and multiple readSchema, when we have different schema of the same object.

```java
        AvroVersionedJacksonCodec avroCodec = new AvroVersionedJacksonCodec();
        AvroSchema writeSchema = ...
        AvroSchema readSchemaV1 = ...
        AvroSchema readSchemaV2 = ...
        avroCodec.addSchema(TestObject.class, writeSchema, readSchemaV1, readSchemaV2);

```

Please try version attached.

[redisson-3.15.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6162222/redisson-3.15.2-SNAPSHOT.jar.zip)

**Comment by brijnkh** [comment]
@mrniko 
**It is giving a NullPointerException for write and read operation both.**

**stacktrace**

Exception in thread "main" java.lang.IllegalArgumentException: java.io.IOException: java.lang.NullPointerException
	at org.redisson.command.CommandAsyncService.encodeMapKey(CommandAsyncService.java:701)
	at org.redisson.RedissonObject.encodeMapKey(RedissonObject.java:301)
	at org.redisson.RedissonMap.getOperationAsync(RedissonMap.java:1148)
	at org.redisson.RedissonMap.getAsync(RedissonMap.java:1155)
	at org.redisson.RedissonMap.get(RedissonMap.java:639)
	at com.company.redis.redissampleconnector.RedisCodecAvroTargetDataReaderTest.runThroughAvroJacksonCodec(RedisCodecAvroTargetDataReaderTest.java:83)
	at com.company.redis.redissampleconnector.RedisCodecAvroTargetDataReaderTest.main(RedisCodecAvroTargetDataReaderTest.java:41)
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:91)
	at org.redisson.command.CommandAsyncService.encodeMapKey(CommandAsyncService.java:699)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.redisson.codec.AvroVersionedJacksonCodec$AvroExtendedMapper.writeValue(AvroVersionedJacksonCodec.java:160)
	at org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:84)
	... 7 more

**Code snippet:**

AvroMapper am = new AvroMapper();
AvroSchema schema = am.schemaFrom(..);
AvroSchema schema2 = am.schemaFrom(..);
AvroVersionedJacksonCodec typedJsonJackson = new AvroVersionedJacksonCodec();
typedJsonJackson.addSchema(Target.class,schema, schema2);

Config config = new Config();
config.setCodec(typedJsonJackson);
config.useSingleServer().setAddress("redis://localhost:6379");
RedissonClient redissonClient = Redisson.create(config);


String keyStr = "key1";

targetMap = redissonClient.getMap("TARGETS", typedJsonJackson);

Target retTarget = targetMap.get(keyStr);

**Comment by mrniko** [comment]
String type used as key isn't an avro type. Use `new CompositeCodec(StringCodec.INSTANCE, typedJsonJackson)`

**Comment by mrniko** [comment]
did you try it?

**Comment by brijnkh** [comment]
I tried it.. But I found two issues..
**Issue 1:**
It is still failing while reading from redis. If schema has changed.

Code:

AvroMapper am = new AvroMapper();
AvroSchema schema = am.schemaFrom(new File("Path of the avsc file 1"));
AvroSchema schema2 = am.schemaFrom(new File("Path of the avsc file 2"));
AvroVersionedJacksonCodec typedJsonJackson = new AvroVersionedJacksonCodec();
typedJsonJackson.addSchema(.class,schema2, schema);
CompositeCodec compCodec = new CompositeCodec(StringCodec.INSTANCE, typedJsonJackson);
Config config = new Config();
config.setCodec(compCodec);
config.useSingleServer().setAddress("redis://localhost:6379");
RedissonClient redissonClient = Redisson.create(config);
String keyStr = "key1";
targetMap = redissonClient.getMap("MAP_NAME",compCodec);

Exception:

java.lang.NullPointerException: null
	at org.redisson.codec.AvroVersionedJacksonCodec$AvroExtendedMapper.readValue(AvroVersionedJacksonCodec.java:179)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:99)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
15:33:30.082 [redisson-netty-2-5] DEBUG org.redisson.command.RedisExecutor - connection released for command (HGET) and params [MAP_NAME, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@674912564 [redisClient=[addr=redis://localhost:6379], channel=[id: 0x9960ac2f, L:/127.0.0.1:57499 - R:localhost/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@52acecee(failure: java.lang.NullPointerException)], command=(HGET), params=[MAP_NAME, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256)], codec=org.redisson.codec.CompositeCodec@92988930]]
Exception in thread "main" 15:33:30.083 [redisson-netty-2-5] ERROR org.redisson.client.handler.ErrorsLoggingHandler - Exception occured. Channel: [id: 0x9960ac2f, L:/127.0.0.1:57499 - R:localhost/127.0.0.1:6379]
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
	at org.redisson.codec.AvroVersionedJacksonCodec$AvroExtendedMapper.readValue(AvroVersionedJacksonCodec.java:179)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:99)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 common frames omitted
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:324)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:121)
	at org.redisson.RedissonObject.get(RedissonObject.java:81)
	at org.redisson.RedissonMap.get(RedissonMap.java:639)

**Issue2:**

It is not able to handle logicalType:
For example: If I have below property in avsc:
{
"name": "updateTimeMillis",
 "type": {
 "type": "long",
 "logicalType": "timestamp-millis"
	},
"doc": "timestamp(miliseconds since wpoch) at which this object was last updated"
}

Getting below exception:

Exception in thread "main" java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: Failed to create Record type from LONG (through reference chain: package.avro.Target["updateTimeMillis"])
	at org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:717)
	at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:305)
	at org.redisson.RedissonMap.putOperationAsync(RedissonMap.java:1336)
	at org.redisson.RedissonMap.putAsync(RedissonMap.java:1322)
	at org.redisson.RedissonMap.put(RedissonMap.java:644)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to create Record type from LONG (through reference chain: package.avro.Target["updateTimeMillis"])
	at com.fasterxml.jackson.dataformat.avro.ser.AvroWriteContext._createRecord(AvroWriteContext.java:203)
	at com.fasterxml.jackson.dataformat.avro.ser.AvroWriteContext._createObjectContext(AvroWriteContext.java:252)
	at com.fasterxml.jackson.dataformat.avro.ser.ObjectWriteContext.createChildObjectContext(ObjectWriteContext.java:57)
	at com.fasterxml.jackson.dataformat.avro.AvroGenerator.writeStartObject(AvroGenerator.java:394)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:174)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:400)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1512)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1217)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1043)
	at org.redisson.codec.AvroVersionedJacksonCodec$AvroExtendedMapper.writeValue(AvroVersionedJacksonCodec.java:161)
	at org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:84)
	at org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:715)
	
	
	... 6 more
	Suppressed: com.fasterxml.jackson.core.JsonGenerationException: Failed to close AvroGenerator: (java.lang.NullPointerException): null of long in field updateTimeMillis of package.Target
		at com.fasterxml.jackson.dataformat.avro.AvroGenerator.close(AvroGenerator.java:347)
		at com.fasterxml.jackson.databind.util.ClassUtil.closeOnFailAndThrowAsIOE(ClassUtil.java:486)
		at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1219)
		... 10 more
	Caused by: java.lang.NullPointerException: null of long in field updateTimeMillis of package.Target
		at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:183)
		at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:177)
		at com.fasterxml.jackson.dataformat.avro.ser.NonBSGenericDatumWriter.write(NonBSGenericDatumWriter.java:123)
		at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:72)
		at com.fasterxml.jackson.dataformat.avro.ser.RootContext.complete(RootContext.java:122)
		at com.fasterxml.jackson.dataformat.avro.AvroGenerator._complete(AvroGenerator.java:621)
		at com.fasterxml.jackson.dataformat.avro.AvroGenerator.close(AvroGenerator.java:342)
		... 12 more

Same happens if I try to store string as new utf8("Name").

With normal avroJacksonCodec issue 2 was not there.

**Comment by brijnkh** [comment]
@mrniko Am I using it the correct way?
logicalType as well as  utf8() object was working with normal avroJacksonCodec..

**Comment by mrniko** [comment]
it's hard to say. Issue 1 happens since AvroVersionedJacksonCodec unable to find proper schema for stored object. Did you define it in `addSchema()` args? can you share full sample code I could run?

**Comment by brijnkh** [comment]
Sure.. I will share it in some time.

**Comment by brijnkh** [comment]
**Schema:**

{
    "name": "SchemaEvol",
    "type": "record",
    "namespace": "com.avro",
    "doc": "SchemaEvol information",
    "fields": [
      {
        "name": "schemaEvolId",
        "type": [
            "null",
            "string"
        ],
        "doc": "the unique identifier for the SchemaEvol"
      },
      {
        "name": "displayName",
        "type": [
            "null",
            "string"
        ],
        "doc": "the display name"
      },
      {
        "name": "firstName",
        "type": [
            "null",
            "string"
        ],
        "doc": "the first name of participant"
      },
      {
        "name": "middleName",
        "type": [
            "null",
            "string"
        ],
        "doc": "the middle name of participant"
      },
      {
        "name": "lastName",
        "type": [
            "null",
            "string"
        ],
        "doc": "the last name of participant"
      },
      {
        "name": "status",
        "type": {
          "name": "Status",
          "type": "enum",
            "symbols": [
              "ACTIVE",
              "TERMINATED"
            ]
        },
        "doc": "the status"
      },
      {
        "name": "createTimeMillis",
       "type": "long",
        "doc": "timestamp(miliseconds since wpoch) at which object was created"
      },
      {
        "name": "updateTimeMillis",
         "type": {
         "type": "long",
         "logicalType": "timestamp-millis"
            },
        "doc": "timestamp(miliseconds since wpoch) at which object was last updated"
      },
      {
        "name": "contextParameters",
	"doc": "additional information of object",
	"type": [
		"null",
                {
                	"type": "map",
                        "values": [
                        	"null",
                                "string"
                            ]
                        }
                     ],
                     "default": null
                   }
    ]
  }

**Code:**

public class RedisCodecAvroJacksonTest {
	private static RMap<String, SchemaEvol> schemaEvolMap = null;

	public static void main(String[] args) throws IOException {
		writeThroughVersionedAvroJacksonCodec();
	}

	private static void writeThroughVersionedAvroJacksonCodec() throws IOException {
		ClassLoader classLoader = RedisCodecAvroJacksonTest.class.getClassLoader();
		AvroMapper am = new AvroMapper();
		AvroSchema schema = am.schemaFrom(new File(classLoader.getResource("avro/schemaevol.avsc").getFile()));
		AvroVersionedJacksonCodec sourceCodec = new AvroVersionedJacksonCodec();
		sourceCodec.addSchema(SchemaEvol.class, schema);

		CompositeCodec compCodec = new CompositeCodec(StringCodec.INSTANCE, sourceCodec);
		Config config = new Config();
		config.setCodec(compCodec);
		config.useSingleServer().setAddress("redis://localhost:6379");

		RedissonClient redissonClient = Redisson.create(config);

		String keyStr = "key1";

		schemaEvolMap = redissonClient.getMap("SCHEMAEVOL");

		SchemaEvol testSchemaEvol = new SchemaEvol();
		testSchemaEvol.setUpdateTimeMillis(Instant.now());
		testSchemaEvol.setSchemaEvolId("123");
		testSchemaEvol.setDisplayName(new Utf8("James"));
		Map<CharSequence, CharSequence> params = new HashMap<CharSequence, CharSequence>();
		params.put("Language", "Engish");
		testSchemaEvol.setStatus(Status.ACTIVE);
		testSchemaEvol.setContextParameters(params);

		System.out.println("Current Time: " + testSchemaEvol.getUpdateTimeMillis());
		schemaEvolMap.put(keyStr, testSchemaEvol);

		SchemaEvol retSchemaEvol = schemaEvolMap.get(keyStr);

		System.out.println("Stored Time: " + retSchemaEvol.getUpdateTimeMillis());
		System.out.println("SchemaEvol: " + retSchemaEvol);
	}

	private static void readThroughVersionedAvroJacksonCodec() throws IOException {
		AvroMapper am = new AvroMapper();
		ClassLoader classLoader = RedisCodecAvroJacksonTest.class.getClassLoader();
		AvroSchema schema = am.schemaFrom(new File(classLoader.getResource("avro/schemaevol.avsc").getFile()));
		AvroVersionedJacksonCodec sourceCodec = new AvroVersionedJacksonCodec();
		sourceCodec.addSchema(SchemaEvol.class, schema);

		CompositeCodec compCodec = new CompositeCodec(StringCodec.INSTANCE, sourceCodec);
		Config config = new Config();
		config.setCodec(compCodec);
		config.useSingleServer().setAddress("redis://localhost:6379");

		RedissonClient redissonClient = Redisson.create(config);

		String keyStr = "key1";

		schemaEvolMap = redissonClient.getMap("SCHEMAEVOL");

		SchemaEvol retSchemaEvol = schemaEvolMap.get(keyStr);

		System.out.println("Stored Time: " + retSchemaEvol.getUpdateTimeMillis());
		System.out.println("Schema Evol: " + retSchemaEvol);
	}

}
