### ISSUE TITLE
Deserialization issue with Kryo5Codec post schema change.

### ISSUE THREAD

**Issue by brijnkh** [redisson/redisson#3436]

**Comment by brijnkh** [comment]
Java Code:

Kryo5Codec testCodec = new Kryo5Codec(RedisCodecAvroSessionDataReaderTest.class.getClassLoader());
Config config = new Config();
config.useSingleServer().setAddress("redis://localhost:6379");
config.setCodec(testCodec);
RedissonClient redissonClient = Redisson.create(config);
try {
	String keyStr = "keytest12";
	sessionRMap = redissonClient.getMap("SESSIONS", testCodec);
	SessionData retSession = sessionRMap.get(keyStr);
	System.out.println("Stored Display Name: " + retSession.getDisplayName());
	System.out.println("Stored Time: " + retSession.getUpdateTimeMillis());
	System.out.println("Stored Extra Display Name: " + retSession.getExtraDisplayName());
} catch (Exception e) {
	e.printStackTrace();
} finally {
	redissonClient.shutdown();
}

Avro Updated schema:

{
"name": "SessionData",
"type": "record",
"namespace": "com.avro",
"doc": "Session information",
"fields": [
{
"name": "sessionId",
"type": [
"null",
"string"
],
"doc": "the unique identifier for the session"
},
{
"name": "displayName",
"type": [
"null",
"string"
],
"doc": "the display name of participant"
},
{
"name": "updateTimeMillis",
"type": "long",
"doc": "timestamp(miliseconds) at which record was last updated"
},
{
"name": "extraDisplayName",
"type": [
"null",
"string"
],
"doc": "the Extra display name of participant"
}
]
}

**Note: extraDisplayName field is the one which was added later in the schema.**

**Expected Behavior:**
Deserialization works normally.

**Actual behavior:**
Getting below exception:
11:49:27.290 [redisson-netty-2-10] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0x1f101757, L:/127.0.0.1:53427 - R:localhost/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=101, widx=101), command: (HGET), params: [SESSIONS, PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256)]
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1696722528

t com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:167)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691)
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:118)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:124)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:95)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)

**Comment by mrniko** [comment]
This issue related to codec itself, not Redisson. JacksonJsonCodec works fine in this case.

**Comment by brijnkh** [comment]
@mrniko we have an issue with JsonJacksonCodec right? #3327 
I need to deserialize post change in schema.

**Comment by mrniko** [comment]
I mean use JsonJacksonCodec without schema usage.

**Comment by brijnkh** [comment]
@mrniko Is there any other way to handle schema change?

**Comment by mrniko** [comment]
I can't suggest the other solution
