### ISSUE TITLE
slaveConnectionPool can't reconnect in sentinel model

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#3442]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**

**Redisson version**
3.14.1
**Redisson configuration**
failedSlaveCheckInterval = 180000

in redisson sentinel model:
use chaosblade to inject network delay in to redis port,keep delay time more than failedSlaveCheckInterval,
when netword delay finish, slaveConnectionPool not reconnect to redis slave node, slaveConnectionPool‘s all ClientConnectionsEntry in to RECONNECT status and keep throw exception:

org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: 192.168.17.50/192.168.17.50:6316 Disconnected hosts: [192.168.17.50/192.168.17.50:6316, 192.168.17.52/192.168.17.52:6316, 192.168.17.51/192.168.17.51:6316]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:267) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:500) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:572) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:648) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:116) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:244) ~[redisson-3.14.1.jar!/:3.14.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]

it‘s a bug?or i can set any config to fix it?

**Comment by mrniko** [comment]
please share Redisson log output

**Comment by mikawudi** [comment]
keep call RBucket.get
inject netword delay keep 300s

when 0~180s
redisson throw:
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1095482038 [redisClient=[addr=redis://192.168.17.52:6316], channel=[id: 0xf8ba4cbf, L:/192.168.16.41:34436 ! R:192.168.17.52/192.168.17.52:6316], currentCommand=null], command: (GET), params: [test] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:271) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:156) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:153) ~[redisson-3.14.1.jar!/:3.14.1]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1009) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:870) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]
Caused by: io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.54.Final.jar!/:4.1.54.Final]

when time > 180s, throw:
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: 192.168.17.50/192.168.17.50:6316 Disconnected hosts: [192.168.17.50/192.168.17.50:6316] Hosts disconnected due to errors during `failedSlaveCheckInterval`: [192.168.17.51/192.168.17.51:6316, 192.168.17.52/192.168.17.52:6316]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:267) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:500) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:572) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:648) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:116) ~[redisson-3.14.1.jar!/:3.14.1]
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:244) ~[redisson-3.14.1.jar!/:3.14.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]

**Comment by mrniko** [comment]
the problem might be arise in org.redisson.connection.pool.ConnectionPool#scheduleCheck() method

**Comment by yllions** [comment]
I also met this error log in production environment. which version will fix this bug ?

redisson version is 3.15.0

**Comment by mikawudi** [comment]
@yllions chinese here? not good at english.....
这个异常我们这边的出现场景是,连续failedSlaveCheckInterval时间内,sentinel告知redisson节点可用,但是redisson实际和对应告知的slave节点连接失败或者执行命令一直失败,持续failedSlaveCheckInterval时间后,会触发slaveUp尝试重连整个entry,但是这时候网络还是有问题,导致这次整个entry的重连还是失败,最后把这个节点卡在一个不可恢复的中间状态了.....已经提交pr了,还在审核和优化代码,我不确定你是不是也遇到的是一样的问题

**Comment by mrniko** [comment]
Fix merged
