### ISSUE TITLE
redis重启之后某些服务器连接redis一直没恢复报MasterConnectionPool no available Redis entries错误

### ISSUE THREAD

**Issue by cclouds** [redisson/redisson#3464]
Caused by: org.redisson.client.RedisConnectionException: MasterConnectionPool no available Redis entries.  Disconnected hosts: [/1**.**.**.**]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:198)
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:31)
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:535)
	at org.redisson.connection.SingleEntry.connectionReadOp(SingleEntry.java:45)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:807)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:496)
	at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:351)
	at org.redisson.RedissonBucket.getAsync(RedissonBucket.java:102)
	at org.redisson.RedissonBucket.get(RedissonBucket.java:97)
	... 146 more

redisson配置
.setFailedAttempts(1).setConnectTimeout(300).setRetryAttempts(0).setTimeout(100);

**Comment by cclouds** [comment]
version
3.6.0

**Comment by mrniko** [comment]
Update to 3.6.5 version.

**Comment by cclouds** [comment]
> Update to 3.6.5 version.

Thank you
