### ISSUE TITLE
CommandDecoder:181 - Unable to decode data. channel: Unsupported protocol version 0

### ISSUE THREAD

**Issue by tomaytotomato** [redisson/redisson#3465]
I am trying to store a basic POJO called **MobileNotificationDTO** inside an RMap<Long,MobileNotificationDTO> using `MarshallingCodec`

```
public class MobileNotificationDTO implements Serializable {

    private Long id;
    private LocalDateTime createdOn;
    private boolean sent;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
    }

    public boolean isSent() {
        return sent;
    }

    public void setSent(boolean sent) {
        this.sent = sent;
    }
}

```

Writing an integration test, it is failing to retrieve the POJO from the map

```
    @Before
    public void setUp() throws Exception {

        Config config = new Config();

        ObjectMapper objectMapper = new ObjectMapper();
        config.setCodec(new MarshallingCodec());
        config.useSingleServer()
                .setAddress("redis://localhost:6379");


        redissonClient = Redisson.create(config);
        cache = new MobileNotificationsCache(redissonClient);
    }


    @Test
    public void put_WhenMobileNotificationIsSet_ThenValueIsCachedCorrectly() {
        final Long id = 682124L;
        final LocalDateTime createdOn = LocalDateTime.now();
        final MobileNotificationDTO dto = new MobileNotificationDTO();
        dto.setId(123L);
        dto.setCreatedOn(createdOn);
        dto.setSent(true);

        redissonClient.getMapCache(MobileNotificationsCache.CACHE_NAME).put(id, dto);

        RMap<Long, MobileNotificationDTO> map = redissonClient.getMapCache(MobileNotificationsCache.CACHE_NAME, new LongCodec());
        assertThat(map.size()).isEqualTo(1);
        MobileNotificationDTO result = map.get(id);
        assertThat(result.getId()).isEqualTo(123L);
        assertThat(result.getCreatedOn()).isEqualTo(createdOn);
        assertThat(result.isSent()).isTrue();

    }
```

The full error is as follows

>  ERROR CommandDecoder:181 - Unable to decode data. channel: [id: 0x6ef3b6fd, L:/127.0.0.1:57900 - R:localhost/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=171, widx=171), command: (HGET), params: [MOBILE_NOTIFICATIONS, PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256)]
> java.io.IOException: Unsupported protocol version 0
> 	at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1348)
> 	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:150)
> 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:359)
> 	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178)
> 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
> 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
> 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)
> 2021-03-10 18:57:56 ERROR ErrorsLoggingHandler:47 - Exception occured. Channel: [id: 0x6ef3b6fd, L:/127.0.0.1:57900 - R:localhost/127.0.0.1:6379]
> io.netty.handler.codec.DecoderException: java.io.IOException: Unsupported protocol version 0

Any ideas how to fix this issue? I have tried JsonMarshallingCode and StringCodec but still the same error

**Comment by hipopular** [comment]
2021-08-06 14:53:42.691 [redisson-netty-2-6] [] ERROR org.redisson.client.handler.ErrorsLoggingHandler => Exception occured. Channel: [id: 0x8fff9d26, L:/10.190.0.233:63675 - R:r-8vbz2r5xf2yoegjljz.redis.zhangbei.rds.aliyuncs.com/10.180.7.11:6379]
Exception in thread "TW-SINGLE_GOODS" org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:324)
	at org.redisson.command.CommandAsyncService.getInterrupted(CommandAsyncService.java:137)
	at org.redisson.RedissonBlockingDeque.takeFirst(RedissonBlockingDeque.java:209)
	at com.oristartech.wmc.core.support.robot.TaskWorker.run(TaskWorker.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unsupported protocol version 0
	at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1375)
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:145)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:366)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

有没有办法解决，最新版本3.16.1

**Comment by mrniko** [comment]
@hipopular 

You're trying to decode data serialized with different codec. Not a default one.

**Comment by hipopular** [comment]
> @hippopular
> 
> 您正在尝试解码使用不同编解码器序列化的数据。不是默认的。

为什么回出现这种情况 ，写入的数据 读取都是默认编解码器的 没有自定义噢 ，只有在阿里云上有这种问题 ，很奇怪

**Comment by hipopular** [comment]
为什么会出现这种情况 ，写入的数据 读取都是默认编解码器的 没有自定义噢 ，只有在阿里云上有这种问题 ，很奇怪

**Comment by mrniko** [comment]
@hipopular 

You can set `TRACE` logging level for `org.redisson.client.handler.CommandDecoder` to spot an actual value.

**Comment by DrunkLife** [comment]
本地没问题，也是阿里云上报错
2021-09-03 06:55:06 ERROR [org.redisson.client.handler.CommandPubSubDecoder.decodeCommand:76] - [Unable to decode data. channel: [id: 0xa04d6c75, L:/172.16.215.79:42976 - R:/172.16.215.78:6379], reply: ReplayingDecoderByteBuf(ridx=562, widx=562)]
java.io.IOException: Unsupported protocol version 123
	at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1375) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:145) ~[redisson-3.15.5.jar!/:3.15.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358) ~[redisson-3.15.5.jar!/:3.15.5]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402) ~[redisson-3.15.5.jar!/:3.15.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367) ~[redisson-3.15.5.jar!/:3.15.5]
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:72) [redisson-3.15.5.jar!/:3.15.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116) [redisson-3.15.5.jar!/:3.15.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:88) [redisson-3.15.5.jar!/:3.15.5]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) [netty-codec-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
