### ISSUE TITLE
java.util.ServiceConfigurationError: org.jboss.marshalling.ProviderDescriptor: Error reading configuration file

### ISSUE THREAD

**Issue by xrths** [redisson/redisson#3483]
hello, I spent my day trying to debug but I didn't succeed, do you have an idea?

```
java.util.ServiceConfigurationError: org.jboss.marshalling.ProviderDescriptor: Error reading configuration file
        at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_212]
        at java.util.ServiceLoader.parse(ServiceLoader.java:309) ~[?:1.8.0_212]
        at java.util.ServiceLoader.access$200(ServiceLoader.java:185) ~[?:1.8.0_212]
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357) ~[?:1.8.0_212]
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393) ~[?:1.8.0_212]
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474) ~[?:1.8.0_212]
        at org.jboss.marshalling.Marshalling.loadMarshallerFactory(Marshalling.java:112) ~[?:?]
        at org.jboss.marshalling.Marshalling.getProvidedMarshallerFactory(Marshalling.java:101) ~[?:?]
        at org.redisson.codec.MarshallingCodec.<init>(MarshallingCodec.java:218) ~[?:?]
        at org.redisson.codec.MarshallingCodec.<init>(MarshallingCodec.java:195) ~[?:?]
        at org.redisson.codec.MarshallingCodec.<init>(MarshallingCodec.java:191) ~[?:?]
        at org.redisson.config.Config.<init>(Config.java:103) ~[?:?]
        at org.redisson.Redisson.<init>(Redisson.java:62) ~[?:?]
        at org.redisson.Redisson.create(Redisson.java:104) ~[?:?]
        at fr.xrths.lyranetwork.Main.redisSetup(Main.java:59) ~[?:?]
        at fr.xrths.lyranetwork.Main.onEnable(Main.java:45) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:309) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:320) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:275) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:732) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.Bukkit.reload(Bukkit.java:540) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:137) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:626) ~[meowspigot.jar:1.0-Beta]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:589) ~[meowspigot.jar:1.0-Beta]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:409) ~[meowspigot.jar:1.0-Beta]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$run$6(MinecraftServer.java:602) ~[meowspigot.jar:1.0-Beta]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$schedule$7(MinecraftServer.java:668) ~[meowspigot.jar:1.0-Beta]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/org.jboss.marshalling.ProviderDescriptor not found in /data/plugins/LyraNetwork-SPIGOT-0.0.1-SNAPSHOT.jar
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144) ~[?:1.8.0_212]
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152) ~[?:1.8.0_212]
        at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_212]
        at java.util.ServiceLoader.parse(ServiceLoader.java:304) ~[?:1.8.0_212]
        ... 35 more
```

**Comment by mrniko** [comment]
does LyraNetwork-SPIGOT-0.0.1-SNAPSHOT.jar contains all libs used by Redisson including jboss.marshalling?

**Comment by xrths** [comment]
My POM.XML looks like this:
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>fr.xrths</groupId>
	<artifactId>LyraNetwork-SPIGOT</artifactId>
	<packaging>jar</packaging>
	<version>0.0.1-SNAPSHOT</version>

	<name>LyraNetwork-SPIGOT</name>
	<description>PROTOTYPE</description>
	<url>https://xrths.fr</url>

	<developers>
		<developer>
			<name>Thomas R.</name>
			<url>https://xrths.fr</url>
		</developer>
	</developers>

	<properties>
		<!-- Author and MainClass are used in plugin.yml -->
		<author>xrths</author>
		<mainClass>fr.xrths.lyranetwork.Main</mainClass>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>plugin.yml</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>plugin.yml</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.4</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<!-- This adds the Spigot Maven repository to the build -->
		<repository>
			<id>spigot-repo</id>
			<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
		</repository>
	</repositories>

	<dependencies>
		<!--Spigot API -->
		<dependency>
			<groupId>org.spigotmc</groupId>
			<artifactId>spigot-api</artifactId>
			<version>1.8.8-R0.1-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>

		<!--Bukkit API -->
		<dependency>
			<groupId>org.bukkit</groupId>
			<artifactId>bukkit</artifactId>
			<version>1.8.8-R0.1-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.15.1</version>
		</dependency>

		<dependency>
			<groupId>com.eclipsesource.minimal-json</groupId>
			<artifactId>minimal-json</artifactId>
			<version>0.9.5</version>
		</dependency>

	</dependencies>

</project>
```

**Comment by mrniko** [comment]
seems shaded archive doesn't include ProviderDescriptor file. Try to use redisson-all.jar instead
