### ISSUE TITLE
 ERROR org.redisson.connection.DNSMonitor 112 - Unable to resolve redis.address

### ISSUE THREAD

**Issue by GreatAsia** [redisson/redisson#3486]
**Expected behavior**

Do not print such logs

**Actual behavior**

Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.xxx.xxx:5x] query timed out after 5000 milliseconds (no stack trace available)
2021-03-16 15:35:48,398 [redisson-netty-2-18] ERROR org.redisson.connection.DNSMonitor 112 - Unable to resolve redis.host
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis.hostl' failed to resolve 'redis.host' after 2 queries 
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:816)
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:777)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:310)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:299)
        at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62)
        at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:356)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216)
        at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43)
        at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:166)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.xx.xx.x:x3] query timed out after 5000 milliseconds (no stack trace available)

**Steps to reproduce or test case**

   After use, the exception log is printed every five seconds

**Redis version**
  
**Redisson version**
3.15.0
**Redisson configuration**
  Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://"+addressUrl)
                .setConnectTimeout(20000)
                .setRetryInterval(20000)
                .setTimeout(20000);
        return Redisson.create(config);

**Comment by mrniko** [comment]
Hiding exceptions is a bad practice. I think you need to fix your dns resolver.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1625
