### ISSUE TITLE
ClassNotFoundException when using ServiceLoader

### ISSUE THREAD

**Issue by HesterQ** [redisson/redisson#3503]
Hey, while writing plugins for BungeeCord proxy I ran into a problem with ClassLoader.  Plugins use the redisson library to create the network It works like this:
1. BungeeCord loads available plugins
2. One of the plugins contains the redisson library and connects to redis
3. Another plugin use the previously loaded plugin with the library to synchronize the objects

All plugins are loaded using the same ClassLoader, so the same ClassLoader also loads the redisson library, and knows about classes that we serialize and keep in redis. Unfortunately the plugin that is loaded in step 3 throws a error like:

```
Exception in thread "main" org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:351)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:148)
	at org.redisson.RedissonObject.get(RedissonObject.java:81)
	at org.redisson.RedissonBucket.get(RedissonBucket.java:104)
	at org.hesterq.redis.plugin.ExternalDataListener.tryGet(ExternalDataListener.java:22)
	at org.hesterq.redis.plugin.ExternalPlugin.enable(ExternalPlugin.java:31)
	at org.hesterq.redis.Server.main(Server.java:74)
Caused by: java.io.IOException: java.lang.ClassNotFoundException: org.hesterq.redis.plugin.ExternalData
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.hesterq.redis.plugin.ExternalData
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129)
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1033)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1366)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:216)
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:151)
	... 23 more
```

So I wrote small ServiceLoader application to reproduce that issue. 

**Steps to reproduce or test case**
https://github.com/HesterQ/RedisServer

1. clone repo: https://github.com/HesterQ/RedisServer.git
2. redis-cli config set notify-keyspace-events KEA
3. ./test.sh for auto-install

or manually 

1. clone repo: https://github.com/HesterQ/RedisServer.git
2. mvn clean install
3. copy all generated plugin jars (RedisServer-WriterPlugin; RedisServer-RedisProviderPlugin; RedisServer-ReaderPlugin) to RedisServer-Server\target\plugins\
4. redis-cli config set notify-keyspace-events KEA
5. run RedisServer-Server-1.0.0-SNAPSHOT.jar

**Redis version**
6.0.10

**Redisson version**
```
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson-all</artifactId>
	<version>3.15.1</version>
</dependency>
```

**Redisson configuration**
```
Config config = new Config();
config.useSingleServer().setAddress("redis://127.0.0.1:6379");
```

**Comment by Lorak-mmk** [comment]
I also tried to do `.setCodec(new MarshallingCodec(getClass().getClassLoader()))` in `RedisProviderPlugin`, but it didn't help. It seems like maybe `MarshallingCodec` is using other `ClassLoader` than the one specified in constructor?

**Comment by mrniko** [comment]
> It seems like maybe MarshallingCodec is using other ClassLoader than the one specified in constructor?

No, you can see it in debug

**Comment by Lorak-mmk** [comment]
I may be wrong, but I don't think that's true? To test this, I subclassed URLClassLoader (to easily see if my class loader is in stacktrace), and made it print requests for classes in `org.hesterq` package, along with stack traces. I also added the `.setCodec` line I mentioned before. Modified version of example can be found here: https://github.com/Lorak-mmk/RedisServer
I attached the log of the modified example. In lines 57-65 you can see, that my class loader is able to correctly load ExternalData class. Later, when error happens (so from line 81), you can see that my class loader is not mentioned in any stacktrace, despite being explicitly set as a loader to use by MarshallingCodec (line 24 in RedisProviderPlugin.java). Also, my class loader doesn't print anything about being requested to load ExternalData class by MarshallingCodec.

[log.txt](https://github.com/redisson/redisson/files/6170762/log.txt)

**Comment by mrniko** [comment]
In your code I don't see where you create MarshallingCodec with passed classloader. Classloader works fine. Here is my test:

```java
    public static class LoggingClassLoader extends ClassLoader {

        @Override
        public Class<?> findClass(String name) throws ClassNotFoundException {
            System.out.println("[LoggingClassLoader] findClass start: " + name);
            Class<?> ret = super.findClass(name);
            return ret;
        }

        protected Class<?> loadClass(String name, boolean resolve)
                throws ClassNotFoundException {
            System.out.println("[LoggingClassLoader] loadClass start " + name);
            Class<?> result = super.loadClass(name, resolve);
            System.out.println("[LoggingClassLoader] loadClass finished: " + name + ", result: " + result);
            return result;
        }
    }

        Config config = new Config();
        config.setCodec(new MarshallingCodec(new MarshallingCodec.LoggingClassLoader()));
        config.useSingleServer()
             .setAddress(RedisRunner.getDefaultRedisServerBindAddressAndPort());

        Config config = createConfig();
        RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("test", 1));
        RedissonNode node = RedissonNode.create(nodeConfig);

        RExecutorService e = redisson.getExecutorService("test");
        e.submit(new DelayedTask(1000, "testcounter"));
        e.submit(new DelayedTask(1000, "testcounter"));
        for (int i = 0; i < 20; i++) {
            e.submit(new RunnableTask());
        }
        Thread.sleep(1500);
```

log output:

```
[LoggingClassLoader] loadClass start java.util.concurrent.Callable
[LoggingClassLoader] loadClass finished: java.util.concurrent.Callable, result: interface java.util.concurrent.Callable
[LoggingClassLoader] loadClass start java.io.Serializable
[LoggingClassLoader] loadClass finished: java.io.Serializable, result: interface java.io.Serializable
[LoggingClassLoader] loadClass start java.lang.Object
[LoggingClassLoader] loadClass finished: java.lang.Object, result: class java.lang.Object
[LoggingClassLoader] loadClass start sun.reflect.SerializationConstructorAccessorImpl
[LoggingClassLoader] loadClass finished: sun.reflect.SerializationConstructorAccessorImpl, result: class sun.reflect.SerializationConstructorAccessorImpl
[LoggingClassLoader] loadClass start java.lang.Throwable
[LoggingClassLoader] loadClass finished: java.lang.Throwable, result: class java.lang.Throwable
[LoggingClassLoader] loadClass start java.lang.InterruptedException
```

**Comment by mrniko** [comment]
set `useThreadClassLoader` = `false` in configuration.

**Comment by Lorak-mmk** [comment]
> set `useThreadClassLoader` = `false` in configuration.

Yep, that was the issue - we didn't know about this option, thanks.
