### ISSUE TITLE
RScheduledExecutorService

### ISSUE THREAD

**Issue by gitHubForLz** [redisson/redisson#3529]
when I use it in Distribute Schedule  ,Runnable method  depencies on spring context(i.e `@Service` `UserService.class` and `@Mapper` `UserMapper.class` include more indirection depencies )   each other must implemnts `Serializable` ,This way is unfriendly,so I suggest ...

**Comment by mrniko** [comment]
you can mark non-serializable fields as `transient`.

**Comment by gitHubForLz** [comment]
Hello! `IHelloService.java` not  implements  `Serializable`

`RedissonExecutortService.java`
```java

@Service
public class RedissonExecutortService {

    @Autowired
    RedissonClient redissonClient;

    @Autowired
    RunnableTask runnableTask;

    @PostConstruct
    public void method01() {
        ExecutorService executor = Executors.newSingleThreadExecutor();
        WorkerOptions options = WorkerOptions.defaults()

                // Defines workers amount used to execute tasks.
                // Default is 1.


                // Defines custom ExecutorService to execute tasks
                // Config.executor is used by default.
                .executorService(executor)

                // Defines task timeout since task execution start moment
                .taskTimeout(60, TimeUnit.SECONDS);
        RScheduledExecutorService executorService = redissonClient.getExecutorService("STOCK_METADATA_PARSE_TASK");
        executorService.registerWorkers(options);
        RLock rlock = redissonClient.getLock("ScheduledExecutorService");
        RScheduledFuture<?> stock_metadata_parse_task = executorService.scheduleAtFixedRate(runnableTask, 0, 5, TimeUnit.SECONDS
            );
      }

}
```

 `RunnableTask.java`
```java
@Service
public class RunnableTask implements Runnable, Serializable {

    @Autowired
    @org.springframework.data.annotation.Transient
    @javax.persistence.Transient
    private IHelloService service;

    @Override
    public void run() {
          service.hello();
    }
}
```
 using `@Transient` at `service` field is invalid,run has a exception 
```
Exception in thread "Thread-13" java.lang.IllegalArgumentException: java.io.NotSerializableException: com.lz.redisson.HelloService
	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:383)
	at org.redisson.RedissonExecutorService.scheduleAtFixedRateAsync(RedissonExecutorService.java:952)
	at org.redisson.RedissonExecutorService.scheduleAtFixedRate(RedissonExecutorService.java:942)
	at com.lz.redisson.RedissonExecutortService.lambda$createThread$0(RedissonExecutortService.java:82)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.NotSerializableException: com.lz.redisson.HelloService
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
	at org.redisson.codec.MarshallingCodec$4.encode(MarshallingCodec.java:170)
	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:378)
	... 4 more
```
this ,run it's ok
```java
@Service
public class RunnableTask implements Runnable, Serializable {

    @Autowired
    BeanFactory applicationContext;

    @Override
    public void run() {
        IHelloService service = applicationContext.getBean(IHelloService .class);
        service.hello();
    }
}
```

**Comment by gitHubForLz** [comment]
> you can mark non-serializable fields as `transient`.

Hello ! this my code,  `IHelloService.java` not  implements  `Serializable`.

`RedissonExecutortService.java`
```java

@Service
public class RedissonExecutortService {

    @Autowired
    RedissonClient redissonClient;

    @Autowired
    RunnableTask runnableTask;

    @PostConstruct
    public void method01() {
        ExecutorService executor = Executors.newSingleThreadExecutor();
        WorkerOptions options = WorkerOptions.defaults()

                // Defines workers amount used to execute tasks.
                // Default is 1.


                // Defines custom ExecutorService to execute tasks
                // Config.executor is used by default.
                .executorService(executor)

                // Defines task timeout since task execution start moment
                .taskTimeout(60, TimeUnit.SECONDS);
        RScheduledExecutorService executorService = redissonClient.getExecutorService("STOCK_METADATA_PARSE_TASK");
        executorService.registerWorkers(options);
        RLock rlock = redissonClient.getLock("ScheduledExecutorService");
        RScheduledFuture<?> stock_metadata_parse_task = executorService.scheduleAtFixedRate(runnableTask, 0, 5, TimeUnit.SECONDS
            );
      }

}
```

 `RunnableTask.java`
```java
@Service
public class RunnableTask implements Runnable, Serializable {

    @Autowired
    @org.springframework.data.annotation.Transient
    @javax.persistence.Transient
    private IHelloService service;

    @Override
    public void run() {
          service.hello();
    }
}
```
 using `@Transient` at `service` field is invalid,run has a exception 
```
Exception in thread "Thread-13" java.lang.IllegalArgumentException: java.io.NotSerializableException: com.lz.redisson.HelloService
	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:383)
	at org.redisson.RedissonExecutorService.scheduleAtFixedRateAsync(RedissonExecutorService.java:952)
	at org.redisson.RedissonExecutorService.scheduleAtFixedRate(RedissonExecutorService.java:942)
	at com.lz.redisson.RedissonExecutortService.lambda$createThread$0(RedissonExecutortService.java:82)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.NotSerializableException: com.lz.redisson.HelloService
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
	at org.redisson.codec.MarshallingCodec$4.encode(MarshallingCodec.java:170)
	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:378)
	... 4 more
```
this ,run it's ok
```java
@Service
public class RunnableTask implements Runnable, Serializable {

    @Autowired
    BeanFactory applicationContext;

    @Override
    public void run() {
        IHelloService service = applicationContext.getBean(IHelloService .class);
        service.hello();
    }
}
```

**Comment by mrniko** [comment]
> using @Transient at service field is invalid,run has a exception

I meant `transient` keyword. https://www.javatpoint.com/transient-keyword
As option you can use JsonJacksonCodec.

**Comment by gitHubForLz** [comment]
> > using @transient at service field is invalid,run has a exception
> 
> I meant `transient` keyword. https://www.javatpoint.com/transient-keyword
> As option you can use JsonJacksonCodec.

o... thank u

**Comment by gitHubForLz** [comment]
> > using @transient at service field is invalid,run has a exception
> 
> I meant `transient` keyword. https://www.javatpoint.com/transient-keyword
> As option you can use JsonJacksonCodec.

I just used your way ，but the `service` occur NPE
```java
   @Autowired
    transient HelloService service;
```
```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_261]
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:105) ~[redisson-3.13.6.jar:3.13.6]
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:444) [redisson-3.13.6.jar:3.13.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
Caused by: java.lang.NullPointerException: null
	at com.lz.redisson.RunnableTask.run(RunnableTask.java:28) ~[classes/:na]
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:345) ~[redisson-3.13.6.jar:3.13.6]
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:357) ~[redisson-3.13.6.jar:3.13.6]
	at org.redisson.executor.TasksRunnerService.scheduleAtFixedRate(TasksRunnerService.java:134) ~[redisson-3.13.6.jar:3.13.6]
	... 11 common frames omitted
```

**Comment by mrniko** [comment]
Did you define BeanFactory on task executor side?

**Comment by gitHubForLz** [comment]
> Did you define BeanFactory on task executor side?
no ,I just want get bean from spring container .

**Comment by mrniko** [comment]
You need to define Spring beanFactory setting https://github.com/redisson/redisson/wiki/12.-Standalone-node#beanfactory

**Comment by CarryWll** [comment]
Please how did you solve this problem in the end?

**Comment by scyslz** [comment]
> Please how did you solve this problem in the end?

1. configure BeanFactory to WorkerOptions
```
        WorkerOptions options = WorkerOptions.defaults()

                // Defines workers amount used to execute tasks.
                // Default is 1.


                // Defines custom ExecutorService to execute tasks
                // Config.executor is used by default.
                .executorService(executor)

                // Defines task timeout since task execution start moment
                .taskTimeout(60, TimeUnit.SECONDS)
                .beanFactory(beanFactory)
                ;
```
2. then explicitly get target Service from injecting BeanFactory, like the `RunnableTask.java` above

**Comment by CarryWll** [comment]
Is it configured like this?

```
    @Autowired
    private BeanFactory beanFactory;

    @PostConstruct
    public void init() {
        ExecutorService executor = Executors.newSingleThreadExecutor();
        WorkerOptions options = WorkerOptions.defaults()
                .executorService(executor)
                .beanFactory(beanFactory)
                .taskTimeout(60, TimeUnit.SECONDS);
        this.executorService = redissonClient.getExecutorService(DetectTaskJobConstants.SCHEDULER_KEY);
        this.executorService.registerWorkers(options);
    }
```
I still get an error

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.ai.detect.service.IDetectTaskService' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at com.ai.detect.core.task.schedule.DetectTaskScheduler.run(DetectTaskScheduler.java:67)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:340)
	at org.redisson.executor.TasksRunnerService.scheduleWithFixedDelay(TasksRunnerService.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:106)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:458)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
