### ISSUE TITLE
Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by NaveenSadhana** [redisson/redisson#3536]
Hi Team,

while we are using Redisson 2.15.1. 
Java 1.7.80
With 3 redis clusters and 3 application instances
with below redisson.conf 

`{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "failedSlaveReconnectionInterval":3000,
      "failedSlaveCheckInterval":60000,
      "password":null,
      "subscriptionsPerConnection":10,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "slaveConnectionMinimumIdleSize":1,
      "slaveConnectionPoolSize":2,
      "masterConnectionMinimumIdleSize":1,
      "masterConnectionPoolSize":2,
      "readMode":"MASTER",
      "subscriptionMode":"MASTER",
      "nodeAddresses":[
         "master1",
 	 "master2”,
	 "master3”,
	 "master1-slave1”,
	 "master1-slave2”,
 	 "master1-slave3”,
 	 "master2-slave1”,
	 "master2-slave2”,
 	 "master2-slave3”,
 	 "master3-slave1”,
	 "master3-slave2”,
 	 "master3-slave3”,

      ],
      "scanInterval":1000,
      "pingConnectionInterval": 0,
      "keepAlive": false,
      "tcpNoDelay": false,
   },
   "threads":0,
   "nettyThreads": 0,
   "codec":{
      "class":"org.redisson.codec.SerializationCodec"
   },
   "transportMode":"NIO"
}`

And getting below error.

org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:414)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:211)
	at org.redisson.RedissonObject.get(RedissonObject.java:75)
	at org.redisson.RedissonMap.putAll(RedissonMap.java:296)
	at org.redisson.tomcat.RedissonSession.access(RedissonSession.java:117)
	at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:176)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2855)
	at org.apache.catalina.connector.Request.getSession(Request.java:2254)
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:60)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.redisson.codec.CompositeCodec.getValueDecoder(CompositeCodec.java:74)
	at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:464)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:329)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:130)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

**Comment by mrniko** [comment]
`valueDecoder` passed to `CompositeCodec` is `null`.

**Comment by NaveenSadhana** [comment]
@mrniko, the error qps is 0.01 out of 24.5 success qps.... This issue is not occurring all the time. So not able to replicate frequently and also not able to replicate in DEV environment

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version
