### ISSUE TITLE
org.redisson.client.RedisResponseTimeoutException 

### ISSUE THREAD

**Issue by zhaojian770627** [redisson/redisson#3547]
our server sometimes throw a exception ,the flow ,then the sytem is unavailable，how to solve this problem,thinks
09:44:13.798 [http-nio-8080-exec-10] ERROR com.yonyoucloud.fi.ml.matctr.controller.MatCtrController 223 excute - Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (SCAN), params: [0, MATCH, LOCK:FI:PCM:ML_ROLL_CALC:2178455676211456_2186231617491200, COUNT, 10], channel: [id: 0xe84efdef, L:/172.21.178.133:58668 - R:172.20.49.236/172.20.49.236:6352]
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (SCAN), params: [0, MATCH, LOCK:FI:PCM:ML_ROLL_CALC:2178455676211456_2186231617491200, COUNT, 10], channel: [id: 0xe84efdef, L:/172.21.178.133:58668 - R:172.20.49.236/172.20.49.236:6352]
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:935)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
Try to follow these steps: https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception
