### ISSUE TITLE
some time we see exception on DNSMonitor 

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3548]
hi,
we see some time following exception at the log , we don't know the reason for it 

2021-04-12 06:15:11.452 ERROR [redisson-netty-2-15] [UID:, MSG_ID:] [org.redisson.connection.DNSMonitor] <Unable to resolve **********.amazonaws.com>
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[na:1.8.0_261]
	at java.util.ArrayList.get(ArrayList.java:435) ~[na:1.8.0_261]
	at io.netty.resolver.dns.DnsNameResolver.doResolveCached(DnsNameResolver.java:613) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:593) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:527) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at org.redisson.connection.DNSMonitor.monitorMasters(DNSMonitor.java:103) ~[redisson-3.14.0.jar:3.14.0]
	at org.redisson.connection.DNSMonitor.access$300(DNSMonitor.java:45) ~[redisson-3.14.0.jar:3.14.0]
	at org.redisson.connection.DNSMonitor$1.run(DNSMonitor.java:92) ~[redisson-3.14.0.jar:3.14.0]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-all-4.1.15.Final.jar:4.1.15.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_261]

**Comment by mrniko** [comment]
I assume the issue in netty resolver. Did you try to update netty?

**Comment by wdaas** [comment]
to which version we need to update it? currently, I see  4.1.15, 
is there a specific reason why it happens and when?
because other Radisson behaviour works fine?

**Comment by mrniko** [comment]
to the latest

**Comment by wdaas** [comment]
thanks.
but i can't understand the exception and why it happens, if you can share with us?

**Comment by mrniko** [comment]
According to stacktrace this issue happens in netty. I don't know the reason. Since 4.1.15 version a lot of issues regarding dns resolving have been fixed.

**Comment by wdaas** [comment]
thanks alot
