### ISSUE TITLE
An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$477/641664202.operationComplete()

### ISSUE THREAD

**Issue by wedtlcy** [redisson/redisson#3551]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**5.X***

**3.14.1**

**Redisson configuration**

An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$477/641664202.operationComplete()
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.getOrDefault(ConcurrentHashMap.java:1588)
	at org.redisson.pubsub.PublishSubscribeService.getConnectionsQueue(PublishSubscribeService.java:222)
	at org.redisson.pubsub.PublishSubscribeService.access$100(PublishSubscribeService.java:55)
	at org.redisson.pubsub.PublishSubscribeService$5$1.run(PublishSubscribeService.java:410)
	at org.redisson.pubsub.AsyncSemaphore.tryRun(AsyncSemaphore.java:86)
	at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:66)
	at org.redisson.pubsub.PublishSubscribeService$5.run(PublishSubscribeService.java:407)
	at org.redisson.pubsub.AsyncSemaphore.tryRun(AsyncSemaphore.java:86)
	at org.redisson.pubsub.AsyncSemaphore.acquire(AsyncSemaphore.java:66)
	at org.redisson.pubsub.PublishSubscribeService.unsubscribe(PublishSubscribeService.java:397)
	at org.redisson.pubsub.PublishSubscribeService.lambda$reattachPubSub$6(PublishSubscribeService.java:512)
	at org.redisson.pubsub.PublishSubscribeService$$Lambda$1307/1783130940.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3606)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.redisson.pubsub.PublishSubscribeService.reattachPubSub(PublishSubscribeService.java:507)
	at org.redisson.cluster.ClusterConnectionManager$$Lambda$625/1213684246.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.redisson.cluster.ClusterConnectionManager.checkSlotsMigration(ClusterConnectionManager.java:707)
	at org.redisson.cluster.ClusterConnectionManager.lambda$null$9(ClusterConnectionManager.java:463)
	at org.redisson.cluster.ClusterConnectionManager$$Lambda$622/1202605701.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at org.redisson.misc.RedissonPromise$$Lambda$477/641664202.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183)
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181)
	at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$10(ClusterConnectionManager.java:462)
	at org.redisson.cluster.ClusterConnectionManager$$Lambda$621/1480608532.accept(Unknown Source)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at org.redisson.misc.RedissonPromise$$Lambda$477/641664202.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:433)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:427)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
Fixed in 3.15.1 during refactoring. Please update to the latest version.
