### ISSUE TITLE
exception in redisson decode

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3552]
hi,

is following exception is also related to netty version or there is other problem , by the way wasn't happen to us before production :)

2021-04-13 00:56:32.886 ERROR [redisson-netty-5-6] [UID:, MSG_ID:] [org.redisson.client.handler.CommandDecoder] <Unable to decode data. channel: [id: 0x7cf299d2, L:/10.20.30.46:60492 - R**********amazonaws.com/*********], reply: ReplayingDecoderByteBuf(ridx=731, widx=16046), command: (HGETALL), params: [redisson:tomcat_session:FC5EA1D579A23B0EABBE7309D03486F2.APP_EMEA_2103]>

java.io.IOException: java.lang.ClassNotFoundException: com.panaya.as.blexecuter.imp.BaseBLContext
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:153) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.codec.SnappyCodec$3.decode(SnappyCodec.java:84) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356) [redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:400) [redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365) [redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178) [redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) [redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [redisson-all-3.14.0.jar:3.14.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: com.panaya.as.blexecuter.imp.BaseBLContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_261]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_261]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_261]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_261]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_261]
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1033) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1366) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:216) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:151) ~[redisson-all-3.14.0.jar:3.14.0]
	... 26 common frames omitted
2021-04-13 00:56:32.887 ERROR [redisson-netty-5-6] [UID:, MSG_ID:] [org.redisson.client.handler.ErrorsLoggingHandler] <Exception occured. Channel: [id: 0x7cf299d2, L:/10.20.30.46:60492 - R:emea-redis.mugo7l.ng.0001.euw1.cache.amazonaws.com/10.20.100.149:6379]>
io.netty.handler.codec.DecoderException: java.io.IOException: java.lang.ClassNotFoundException: com.panaya.as.blexecuter.imp.BaseBLContext
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[redisson-all-3.14.0.jar:3.14.0]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [redisson-all-3.14.0.jar:3.14.0]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [redisson-all-3.14.0.jar:3.14.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_261]
Caused by: java.io.IOException: java.lang.ClassNotFoundException: com.panaya.as.blexecuter.imp.BaseBLContext
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:153) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.codec.SnappyCodec$3.decode(SnappyCodec.java:84) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:400) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102) ~[redisson-all-3.14.0.jar:3.14.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[redisson-all-3.14.0.jar:3.14.0]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[redisson-all-3.14.0.jar:3.14.0]
	... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.panaya.as.blexecuter.imp.BaseBLContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_261]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_261]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_261]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_261]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_261]
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1033) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1366) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:216) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[redisson-all-3.14.0.jar:3.14.0]
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:151) ~[redisson-all-3.14.0.jar:3.14.0]
	... 26 common frames omitted

**Comment by mrniko** [comment]
That's related to class loader problem. Try to set `useThreadClassLoader` = false.

**Comment by wdaas** [comment]
to add it to redisson.yaml file ?
is there is a reason why it happens to us in specific env and other env not even it is same code and configuration?,

**Comment by mrniko** [comment]
> to add it to redisson.yaml file ?

Yes.

> is there is a reason why it happens to us in specific env and other env not even it is same code and configuration?,

To answer this question you need to debug look at classloader hierarchy.

**Comment by lilaizhencn** [comment]
when i test use openj9, also throw this error.
