### ISSUE TITLE
Null pointer exception is thrown when performing action and redis server is down

### ISSUE THREAD

**Issue by andrzejkaras** [redisson/redisson#3563]
**Expected behavior**:  Redisson Client should throw checked exception or return bool value when operation on RBucket can not be performed because server is down 

**Actual behavior** When single server will be shut down during application work and some operation on RBucket will be performed, then NullPointer exception exception is thrown. Also redisson treats RBucket object as not null one.

An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$731/0x0000000840e3b040.operationComplete()
java.lang.NullPointerException: null
	at org.redisson.client.RedisConnection.send(RedisConnection.java:169) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.command.RedisExecutor.sendCommand(RedisExecutor.java:622) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:151) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) ~[redisson-3.15.0.jar:3.15.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:139) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:606) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:591) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.RedissonObject.deleteAsync(RedissonObject.java:202) ~[redisson-3.15.0.jar:3.15.0]
	at org.redisson.RedissonObject.delete(RedissonObject.java:197) ~[redisson-3.15.0.jar:3.15.0]

**Steps to reproduce or test case**

1. Turn on redis and redisson with single server mode
2. Save some value by using RBucket 
3. Shut down redis server
4. Try to save / remove another value by using RedissonClient (by using RBucket)

**Redis version**  6.2.0

**Redisson version** 3.15.0

**Redisson configuration**
- single server
- REDIS_MIN_CONNECTION_POOL_SIZE: 24
- REDIS_MAX_CONNECTION_POOL_SIZE: 64
- REDIS_IDLE_CONNECTION_TIMEOUT=300000
- REDIS_RETRY_ATTEMPTS=0
- REDIS_TIMEOUT=500
- REDIS_CONNECT_TIMEOUT=1000

Setting pingConnectionInterval does not do the work. I think that send method from RedisConnection class is culprit, it does not check whether channel has null value.

```
    public <T, R> ChannelFuture send(CommandData<T, R> data) {
        return channel.writeAndFlush(data);
    }

```

**Comment by gietki** [comment]
Yeah, I came across identical scenario today. Why o why do you throw NPE?

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version:
Here is my test:
```java
        RedisProcess runner = new RedisRunner()
                .appendonly(true)
                .randomDir()
                .randomPort()
                .run();

        Config config = new Config();
        config.useSingleServer().setAddress(runner.getRedisServerAddressAndPort());

        RedissonClient r = Redisson.create(config);

        r.getBucket("myBucket").set(1);
        assertThat(r.getBucket("myBucket").get()).isEqualTo(1);

        Assertions.assertEquals(0, runner.stop());

        AtomicBoolean hasError = new AtomicBoolean();
        try {
            r.getBucket("myBucket").get();
        } catch (Exception e) {
            e.printStackTrace();
            // skip error
            hasError.set(true);
        }

        assertThat(hasError.get()).isTrue();

        RedisProcess pp = new RedisRunner()
                .appendonly(true)
                .port(runner.getRedisServerPort())
                .dir(runner.getDefaultDir())
                .run();

        assertThat(r.getBucket("myBucket").get()).isEqualTo(1);

        r.shutdown();

        Assertions.assertEquals(0, pp.stop());
```

Error:
```java
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1655154940 [redisClient=[addr=redis://localhost:50239], channel=[id: 0x80475a3f, L:/127.0.0.1:50310 ! R:localhost/127.0.0.1:50239], currentCommand=null], command: (GET), params: [myBucket] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:278)
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:60)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:161)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:158)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1009)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:870)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```

**Comment by andrzejkaras** [comment]
Test also works on my side.

I changed code to execute `Redisson.create(config)` everytime redis operation is needed. Thanks to that everything works correctly. But I think this is not efficient approach.

Could I ask about some good practises to store RedissonClients that were created before in order to reuse  them in next calls?

I am attaching example of factory that store clients.

```
public abstract class AbstractRemoteCacheClientFactory {
    private static final Logger LOG = LogManager.getLogger(AbstractRemoteCacheClientFactory.class);
    private static final RedisProperties properties = RedisProperties.getInstance();
    private RedissonClient client = null;

    protected AbstractRemoteCacheClientFactory() {
    }

    public RedissonClient get(RemoteCacheType cacheType) {
        if (!properties.getEnabled()) {
            LOG.info("Remote cache disabled");
            return null;
        }

        synchronized (this) {
            if (client == null) {
                client = createClient(cacheType);
                return client;
            } else if (client.isShutdown() || client.isShuttingDown()) {
                client = createClient(cacheType);
            }

            return client;
        }
    }

    private RedissonClient createClient(RemoteCacheType cacheType) {
        Config config = new Config();
        config
            .useSingleServer()
            .setAddress(properties.getConnectionURL())
            .setConnectionMinimumIdleSize(properties.getMinConnectionPoolSize())
            .setConnectionPoolSize(properties.getMaxConnectionPoolSize())
            .setIdleConnectionTimeout(properties.getIdleConnectionTimeout())
            .setDatabase(getDatabaseId(cacheType))
            .setRetryAttempts(properties.getRetryAttempts())
            .setTimeout(properties.getTimeout())
            .setConnectTimeout(properties.getConnectTimeout());

        try {
            return Redisson.create(config);
        } catch (RedisConnectionException | RejectedExecutionException e) {
            LOG.error("Can not establish connection with remote cache");
        }

        return null;
    }
}
```

Thanks for help!

**Comment by mrniko** [comment]
Creating client each time takes additional time. You can use it as singleton, it's fully thread-safe.

**Comment by andrzejkaras** [comment]
Yes but look at factory presented above. When I use client returned from it I receive nullpointer exception I showed at the start (in edge case when redis is down).

**Comment by mrniko** [comment]
Try to use the latest version.

**Comment by andrzejkaras** [comment]
So I did. I tested it today on 3.15.4 as you mentioned.

**Comment by mrniko** [comment]
can you also provide log for `org.redisson` package with `debug` logging level?

**Comment by mrniko** [comment]
Can you provide full test case to reproduce it?

**Comment by willy23martin** [comment]
Good morning:

I hope you are doing well. 
I have been dealing with this NullPointerException during the last week. I did a search and I found some examples about how to implement the redissonClient.shutdown(...) method. Every example shows that before shutdown the redissonClient needs to be validated if it is not equals null; then, if it isn't, shutdown could be excecuted:

https://www.codota.com/code/java/methods/org.redisson.Redisson/shutdown 

I am curious about those examples and I want to validate with Redisson team if this is a good practice. 
Finally, there is an exception you can use to verify if the shutdown() was excecuted without any error, as I understood: https://www.javadoc.io/doc/org.redisson/redisson/3.15.3/org/redisson/RedissonShutdownException.html 
After I get the redissonClient null validation implemented I have never received and error message thrown by this RedissonShutdownException, so I understood both approaches are necessary. 

I really appreciate if the Redisson team can validate those approaches and if can give us some advices or recommendations about the bests practices. 

Thank you so much in advance.

**Comment by mrniko** [comment]
@andrzejkaras 

I added assertion if channel == null.

Please try version attached. 

[redisson-3.15.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6374603/redisson-3.15.5-SNAPSHOT.jar.zip)

**Comment by andrzejkaras** [comment]
When using that version I am getting 

```
java.lang.NoClassDefFoundError: io/netty/resolver/dns/DnsAddressResolverGroup
	at org.redisson.config.Config.<init>(Config.java:91) ~[redisson-3.15.5-SNAPSHOT.jar:3.15.5-SNAPSHOT]
```

On `new Config()` line.

**Comment by mrniko** [comment]
please check that you have correct netty version in classpath

**Comment by andrzejkaras** [comment]
Previous version works without any problems with creating config.

**Comment by mrniko** [comment]
I didn't change netty version since 3.15.4 version. Please note it's not all in single jar package. It doesn't contain dependencies as redisson-all jar
