### ISSUE TITLE
Redisson cluster cannot recover from "missing slot"

### ISSUE THREAD

**Issue by olotenko** [redisson/redisson#3587]
A test program is pushing a bunch of requests (`evalSha` for lock-free evaluation) repeatedly. Then bounced Redis Cluster in the middle of it. The connections were lost, then discovered within seconds, as expected. However, Redisson is stuck unable to recover from this condition:
```
org.redisson.client.RedisNodeNotFoundException: Node for slot: 13907 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.
	at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundException(MasterSlaveConnectionManager.java:554)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:508)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:534)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:121)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```
Redis cluster state is fine:
```
127.0.0.1:6379> cluster nodes
fe0223c0b542837bd94699d1af3c19e4ac31178f 172.28.1.2:6379@16379 master - 0 1619718045643 2 connected 5461-10922
5d8b390298d2962cf69385d3e15b71dc432d5280 172.28.1.5:6379@16379 slave af2498fa4bb5ad08751bfb52a954a36964510e59 0 1619718045000 1 connected
af2498fa4bb5ad08751bfb52a954a36964510e59 172.28.1.1:6379@16379 myself,master - 0 1619718043000 1 connected 0-5460
9e3493660fd571eb3454de79fd85776bfe3f81e5 172.28.1.3:6379@16379 master - 0 1619718044000 3 connected 10923-16383
9e23832ccbefdd2d20a410848fecc092efd78b1e 172.28.1.4:6379@16379 slave 9e3493660fd571eb3454de79fd85776bfe3f81e5 0 1619718045000 3 connected
76585e6d75f61b98178df0c6aafcba6a0de0d8b3 172.28.1.6:6379@16379 slave fe0223c0b542837bd94699d1af3c19e4ac31178f 0 1619718044541 2 connected
```

**Expected behavior**

Eventually discover the hash slot is available.

**Actual behavior**

Retrying the same sequence of operations does not recover even after 5 minutes.

**Steps to reproduce or test case**

1. Start Redis cluster
2. Loop evalSha across all cluster nodes.
3. Bounce Redis cluster in the middle of the loop
4. Observe the failures

Observe that restarting the Redisson (bounce microservice in this case) recovers - so the issue is not in Redis cluster.

**Redis version**

```
127.0.0.1:6379> info
# Server
redis_version:6.2.1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:fa5dfffb0053744e
redis_mode:cluster
os:Linux 4.14.35-1902.3.1.el7uek.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:8.3.0
process_id:1
process_supervised:no
run_id:84f6b708cd93f23cb33317537d55220e8bd94b61
tcp_port:6379
server_time_usec:1619718169208450
uptime_in_seconds:1922
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:9105433
executable:/data/redis-server
config_file:/usr/local/etc/redis/redis.conf
io_threads_active:0
```

**Redisson version**

`3.15.4`

**Redisson configuration**

```
@ApplicationScoped
public class RedissonClientProvider {
   public RedissonClientProvider() {
   }

   @Produces
   @ApplicationScoped
   public RedissonClient cluster(@ConfigProperty(name = "jedis.cluster.addresses") String[] addresses) {
      Config config = new Config();
      config.useClusterServers()
            .addNodeAddress(Arrays.stream(addresses).map(a -> "redis://" + a).toArray(n -> new String[n]))
            .setRetryAttempts(3);
      return Redisson.create(config);
   }
}
```

Config: just a bunch of `hostname:port`, no password.

Cluster is the minimal set of nodes: 6 redis containers, dataset is tiny (100K 10Byte strings).

`/usr/local/etc/redis/redis.conf`:
```
port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
```

**Comment by mrniko** [comment]
Unable to reproduce. Can you share Redisson log with logging level `debug` for `org.redisson` package?

**Comment by olotenko** [comment]
[redisson.logs.zip](https://github.com/redisson/redisson/files/6407595/redisson.logs.zip)

**Comment by olotenko** [comment]
The relevant piece of code:
```
   protected final RedissonClient redClient;

   protected static final Codec BOOK_CODEC = new TypedJsonJacksonCodec(Book.class);
   protected static final StringCodec STRING_CODEC = StringCodec.INSTANCE;
   protected static final LongCodec LONG_CODEC = LongCodec.INSTANCE;

   protected static final Codec EVAL_CODEC = new StringCodec() {
      @Override
      public Encoder getValueEncoder() {
         return new Encoder() {
            @Override
            public ByteBuf encode(Object in) throws IOException {
               if (in instanceof String || in instanceof Integer || in instanceof Long) {
                  return STRING_CODEC.getValueEncoder().encode(in);
               }

               return BOOK_CODEC.getValueEncoder().encode(in); // this isn't necessarily a Book, but it doesn't matter on encoding path
            }
         };
      }

      @Override
      public Decoder<Object> getValueDecoder() {
         return new Decoder<Object>() {
            @Override
            public Object decode(ByteBuf in, State state) throws IOException {
               if (in.isReadable() && in.getByte(0) == '{') { // ok, now we know it is Book
                  return BOOK_CODEC.getValueDecoder().decode(in, state);
               }

               return STRING_CODEC.getValueDecoder().decode(in, state);
            }
         };
      }
   };

   public Optional<String> eval(String script, String sha1, List<String> keys, Object... argv) {
      if (sha1 == null) {
         sha1 = "";
      }

      Object r;
      RScript rscript = redClient.getScript(EVAL_CODEC);
      try {
         r = rscript.evalSha(keys.get(0), RScript.Mode.READ_WRITE, sha1, RScript.ReturnType.INTEGER, (List)keys, argv);
      } catch(RuntimeException e) {
         sha1 = rscript.scriptLoadAsync(keys.get(0), script).join();
         r = rscript.evalSha(keys.get(0), RScript.Mode.READ_WRITE, sha1, RScript.ReturnType.INTEGER, (List)keys, argv);
      }
      return r == null? Optional.empty(): Optional.of(sha1);
   }
```

**Comment by mrniko** [comment]
Can you try it with version attached?

[redisson-3.15.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6413028/redisson-3.15.5-SNAPSHOT.jar.zip)

**Comment by olotenko** [comment]
This version appears to recover from this type of failure, thanks.

**Comment by mrniko** [comment]
Thanks for testing! Fixed
