### ISSUE TITLE
spring boot application bootstrap:  java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: org.redisson.jcache.JCachingProvider Unable to get public no-arg constructor

### ISSUE THREAD

**Issue by lilaizhencn** [redisson/redisson#3611]
**Expected behavior**
The program starts normally
**Actual behavior**
```
java.util.ServiceConfigurationError: javax.cache.spi.CachingProvider: Provider org.redisson.jcache.JCachingProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_262]
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[?:1.8.0_262]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[?:1.8.0_262]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_262]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_262]
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:448) ~[cache-api-1.1.1.jar!/:?]
        at javax.cache.Caching$CachingProviderRegistry$1.run(Caching.java:442) ~[cache-api-1.1.1.jar!/:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_262]
        at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:442) ~[cache-api-1.1.1.jar!/:?]
        at javax.cache.Caching$CachingProviderRegistry.getCachingProviders(Caching.java:410) ~[cache-api-1.1.1.jar!/:?]
        at javax.cache.Caching.getCachingProviders(Caching.java:187) ~[cache-api-1.1.1.jar!/:?]
        at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$JCacheProviderAvailableCondition.getMatchOutcome(JCacheCacheConfiguration.java:160) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberOutcomes.getConditionOutcome(AbstractNestedCondition.java:194) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberOutcomes.<init>(AbstractNestedCondition.java:188) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberConditions.lambda$getMatchOutcomes$0(AbstractNestedCondition.java:168) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at java.util.Map.forEach(Map.java:630) ~[?:1.8.0_262]
        at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1507) ~[?:1.8.0_262]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberConditions.getMatchOutcomes(AbstractNestedCondition.java:168) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition$MemberMatchOutcomes.<init>(AbstractNestedCondition.java:78) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.autoconfigure.condition.AbstractNestedCondition.getMatchOutcome(AbstractNestedCondition.java:63) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.4.4.jar!/:2.4.4]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:489) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at com.ontrade.perpetual.provider.PerpetualProviderApplication.main(PerpetualProviderApplication.java:44) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[ontrade-perpetual-provider.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[ontrade-perpetual-provider.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[ontrade-perpetual-provider.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[ontrade-perpetual-provider.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JacksonException
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_262]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_262]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_262]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_262]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_262]
        ... 42 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JacksonException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[ontrade-perpetual-provider.jar:0.0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_262]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_262]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_262]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_262]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_262]
        ... 42 more
```

**Steps to reproduce or test case**
spring boot version: 2.4.4

**Redis version**
5.0

**Redisson version**
3.15.5

**Redisson configuration**
redisson config:
```
  @Bean(value = "redissonClient")
  @Primary
  public RedissonClient redissonClient() {
    Config config = new Config();
    config.useSingleServer()
            .setAddress("redis://" + redisProperties.getHost() + ":" + redisProperties.getPort())
            .setPassword(redisProperties.getPassword());
    if (!System.getProperty("java.version").startsWith("1.8")) {
      log.info("redisson init close useThreadClassLoader");
      config.setUseThreadClassLoader(false);
    }
    return Redisson.create(config);
  }
```

**Comment by mrniko** [comment]
`NoClassDefFoundError: com/fasterxml/jackson/core/JacksonException`

You need to update Jackson lib

**Comment by lilaizhencn** [comment]
that's ok. thank you .  
spring boot 's jackson version is 2.11.4 need upgrade to 2.12
