### ISSUE TITLE
spring boot 2.5.0  with  redisson 3.15.5 Not compatible  :  zadd command will throw stackoverFlow error

### ISSUE THREAD

**Issue by lilaizhencn** [redisson/redisson#3623]
use spring data redis's factory for redisTemplate  was ok
```
  /**
   * 默认通用的 stringRedisTemplate.
   */
  @Bean(name = "stringRedisTemplate")
  @Primary
  public StringRedisTemplate stringRedisTemplate(@Autowired @Qualifier("templateFactory") RedisConnectionFactory redisConnectionFactory) {
    return new StringRedisTemplate(redisConnectionFactory);
  }

  @Bean(name = "templateFactory")
  public RedisConnectionFactory redisConnectionFactory() {

    LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
            .commandTimeout(Duration.ofSeconds(2))
            .shutdownTimeout(Duration.ZERO)
            .build();
    RedisStandaloneConfiguration configuration = new RedisStandaloneConfiguration(redisProperties.getHost(), redisProperties.getPort());
    configuration.setPassword(RedisPassword.of(redisProperties.getPassword()));
    return new LettuceConnectionFactory(configuration, clientConfig);
  }


```

use redisson's factory for redisTemplate  was error

```
  /**
   * 默认通用的 stringRedisTemplate.
   */
  @Bean(name = "stringRedisTemplate")
  @Primary
  public StringRedisTemplate stringRedisTemplate(@Autowired @Qualifier("redissonConnectionFactory") RedissonConnectionFactory redisConnectionFactory) {
    return new StringRedisTemplate(redisConnectionFactory);
  }

  @Primary
  @Bean(name = "redissonConnectionFactory")
  public RedissonConnectionFactory redissonConnectionFactory(@Autowired @Qualifier("redissonClient") RedissonClient redissonClient) {
    return new RedissonConnectionFactory(redissonClient);
  }

java.lang.StackOverflowError
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:877)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:877)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:877)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:877)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:877)

``` 
my test code is 
```
  @Autowired
  private StringRedisTemplate stringRedisTemplate;
  String stopProfitKey = "test.profit.key";
  String stopLossKey = "test.loss.key";
  @Test
  void contextLoads() {
    stringRedisTemplate.execute(new SessionCallback<List<Object>>() {
      @Override
      public <K, V> List<Object> execute(RedisOperations<K, V> operations)
              throws DataAccessException {
        String id = String.valueOf(10001);

        RedisOperations<String, String> operation = (RedisOperations<String, String>) operations;
        operation.multi();
        //先清除止盈缓存
        operation.boundZSetOps(stopProfitKey).remove(id);
        operation.boundZSetOps(stopProfitKey).add(id, 1);
        //先清除止损缓存
        operation.boundZSetOps(stopLossKey).remove(id);
        operation.boundZSetOps(stopLossKey).add(id, -1);
        return operation.exec();
      }
    });
  }
```

**Comment by mrniko** [comment]
Spring Boot 2.5.0 uses Redis Spring Data 2.5.0. Support of Redis Spring Data 2.5.0 isn't implemented yet. As temporary workaround try to use Spring Boot 2.4.6.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3661
