### ISSUE TITLE
Need help with configurations while enabling SSL

### ISSUE THREAD

**Issue by sauman07** [redisson/redisson#3624]
I am using redisson-3.15.3.jar in my application and need to enable SSL. I have enabled SSL at redis with the help of this URL https://dzone.com/articles/how-to-connect-to-redis-on-java-over-ssl
It helped me generate two files: a .crt file and a .key file.
Now I need the configuration to send SSL encrypted calls to redis. I have tried the following but it didn't work:
![image](https://user-images.githubusercontent.com/25014663/119354053-0abe0c00-bcbd-11eb-9e8c-59c5a8c4c6d6.png)

CC: @mrniko

**Comment by sauman07** [comment]
`singleServerConfig:
  idleConnectionTimeout: 10000
  timeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: rediss://0.0.0.0:6379
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
  sslEnableEndpointIdentification: true
  sslTruststore: file:///D:/workspace/stunnel/redis.crt
  sslTruststorePassword: pwd
  sslKeystore: file:///D:/workspace/stunnel/redis.key
  sslKeystorePassword: pwd
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: NIO
`

**Comment by sauman07** [comment]
`singleServerConfig:
  idleConnectionTimeout: 10000
  timeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: rediss://0.0.0.0:6379
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
  sslEnableEndpointIdentification: true
  sslTruststore: file:///D:/workspace/stunnel/redis.crt
  sslTruststorePassword: pwd
  sslKeystore: file:///D:/workspace/stunnel/redis.key
  sslKeystorePassword: pwd
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: NIO
`

**Comment by sauman07** [comment]
singleServerConfig:
  idleConnectionTimeout: 10000
  timeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: rediss://0.0.0.0:6379
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
  sslEnableEndpointIdentification: true
  sslTruststore: file:///D:/workspace/stunnel/redis.crt
  sslTruststorePassword: pwd
  sslKeystore: file:///D:/workspace/stunnel/redis.key
  sslKeystorePassword: pwd
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: NIO

**Comment by mrniko** [comment]
> I have tried the following but it didn't work:

Which error do you get?

**Comment by sauman07** [comment]
> > I have tried the following but it didn't work:
> 
> Which error do you get?

24-May-2021 19:22:00.879 WARNING [redisson-netty-2-9] io.netty.channel.ChannelInitializer.exceptionCaught Failed to initialize a channel. Closing: [id: 0xbaa2fcfe]
 java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.redisson.client.handler.RedisChannelInitializer.initSsl(RedisChannelInitializer.java:129)
        at org.redisson.client.handler.RedisChannelInitializer.initChannel(RedisChannelInitializer.java:79)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
Make you stored certificate in truststore.

**Comment by michael-o** [comment]
@sauman07 Dude, really? Have you actually reviewe what you did? You have applied either DER or RFC 7468 encoded certs which Java cannot use. Create a PKCS#12 keystore and learn the difference between keystore and truststore. 

This one is invalid because it has nothing to do with Redisson.

**Comment by sauman07** [comment]
> @sauman07 Dude, really? Have you actually reviewe what you did? You have applied either DER or RFC 7468 encoded certs which Java cannot use. Create a PKCS#12 keystore and learn the difference between keystore and truststore.
> 
> This one is invalid because it has nothing to do with Redisson.

Yes I created PKCS12 keystore and replaced it the exception I pasted bellow. Maybe some issue in SSL configuration at Redis server.
Caused by: java.nio.channels.ClosedChannelException
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1063)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)

**Comment by michael-o** [comment]
Generally, use `testssl.sh` to verify your server setup. On client side use `-Djavax.net.debug=all`.
