### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by heixiaoma** [redisson/redisson#3628]
`Exception in thread "main" java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:124)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:37)`

<netty.version>4.1.65.Final</netty.version>

**Comment by heixiaoma** [comment]
> check that you have the same version of netty libs in classpath.


<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson</artifactId>
    <version>3.15.6</version>
</dependency>

bug fix
