### ISSUE TITLE
Getting connection refused error while trying to use reddison-hibernate as hibernate second level cache

### ISSUE THREAD

**Issue by sounroy** [redisson/redisson#3641]
Hi All,

Getting connection refused error while trying to use reddison-hibernate as hibernate second level cache
Please note that redis server is up and accepting redis-cli commands.
reddison hibernate version used : redisson-hibernate-53 as I am using spring data jpa that gives hibernate 5.X latest.
Also reddison.yaml is configured.

Getting the following error/
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
app_1    | Caused by: java.net.ConnectException: Connection refused
app_1    |      at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_292]
app_1    |      at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[na:1.8.0_292]
app_1    |      at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
app_1    |      at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_292]
app_1    |

**Comment by sounroy** [comment]
@mrniko 
I am getting this error. could u please tell what am I missing ?


APPLICATION FAILED TO START
app_1    | ***************************
app_1    |
app_1    | Description:
app_1    |
app_1    | An attempt was made to call a method that does not exist. The attempt was made from the following location:
app_1    |
app_1    |     org.redisson.hibernate.RedissonRegionFactory.nextTimestamp(RedissonRegionFactory.java:168)
app_1    |
app_1    | The following method did not exist:
app_1    |
app_1    |     org.redisson.api.RedissonClient.getScript(Lorg/redisson/client/codec/Codec;)Lorg/redisson/api/RScript;
app_1    |

**Comment by sounroy** [comment]
Issue was compatiblity between jar of reddision client & reddison hibernate.
As of now things look good. Thanks .
