### ISSUE TITLE
schedule service  timeout will cause old running task to cancel the whole job when finish error

### ISSUE THREAD

**Issue by gaosjx** [redisson/redisson#3652]
my redission version is 3.15.1. using spring boot 2.4.1.

i run a task once per second, and will finish in 3 seconds,  but the timeout is 2 second,  this will trigger a new task to run, when the old task finish,  it will encounter and error, which cause the whole schedule task will no run anymore.

here is my example to reproduce the case:

``` java


@Slf4j
@SpringBootTest
public class TimeoutDemo {

    @Autowired
    private BeanFactory beanFactory;

    @Autowired
    private RedissonClient redisson;
    
    private static final String scheduleName = "timeout23";
   
    // flag for only wait first time
    private static final AtomicBoolean flag = new AtomicBoolean(false);

    @Test
    public void testTimeout() {
        RScheduledExecutorService executorService = getExecutorService();

        Runnable task = (Runnable & Serializable) () -> {
            log.info("hello world executed start {}", System.currentTimeMillis());
            // sleep not work, interrupt state will clear, see
            // at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:244)

            // only wait first time
            if(flag.compareAndSet(false, true)) {
                final long l = System.currentTimeMillis();
                while (System.currentTimeMillis() <= l + 3*1000) {
                }
            }
            log.info("hello world executed end  {}", System.currentTimeMillis());
        };
        executorService.schedule(task, CronSchedule.of("0/1 * * * * ?"));
        sleep();
    }

 
    // here i set the task timeout to 2 seconds
    private RScheduledExecutorService getExecutorService() {
        ExecutorOptions executorOptions = ExecutorOptions.defaults()
                .taskRetryInterval(15, TimeUnit.SECONDS);
        RScheduledExecutorService executorService = redisson.getExecutorService(scheduleName, executorOptions);
        WorkerOptions workerOptions = WorkerOptions.defaults().taskTimeout(2, TimeUnit.SECONDS);
        workerOptions.beanFactory(beanFactory);
        executorService.registerWorkers(workerOptions);
        return executorService;
    }

    private void sleep() {
        while (true) {
            silentSleep(1000);
        }
    }

    private void silentSleep(int millis) {
        try {
            Thread.sleep(millis);
        } catch (Exception e) {

        }
    }

}
```

this is the output log

```
00:38:20.096 [redisson-3-4] INFO  - [hello world executed start 1623256700096                                        ] - Caller+0	 at com.hello.redis.redisson.executor.schedule.TimeoutDemo.lambda$testTimeout$f0854f4e$1(TimeoutDemo.java:36)
00:38:22.104 [redisson-3-6] INFO  - [hello world executed start 1623256702104                                        ] - Caller+0	 at com.hello.redis.redisson.executor.schedule.TimeoutDemo.lambda$testTimeout$f0854f4e$1(TimeoutDemo.java:36)
00:38:23.098 [redisson-3-4] INFO  - [hello world executed end  1623256703098                                         ] - Caller+0	 at com.hello.redis.redisson.executor.schedule.TimeoutDemo.lambda$testTimeout$f0854f4e$1(TimeoutDemo.java:42)
00:38:23.105 [redisson-3-4] ERROR - [Can't execute: RemoteServiceRequest [requestId=018a42b46241520950c05530460c14abd8, methodName=schedule, signature=[J@138edd39, args=[org.redisson.executor.params.ScheduledCronExpressionParameters@77413796], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1623256699204]] - Caller+0	 at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:119)
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:105)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:453)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@154c1471(incomplete)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:142)
	at org.redisson.remote.AsyncRemoteProxy$2.cancel(AsyncRemoteProxy.java:299)
	at org.redisson.executor.TasksRunnerService.schedule(TasksRunnerService.java:158)
	... 12 common frames omitted
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@154c1471(incomplete)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:244)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:139)
	... 14 common frames omitted
00:38:25.105 [redisson-3-6] INFO  - [hello world executed end  1623256705105  
```

> at org.redisson.executor.TasksRunnerService.schedule(TasksRunnerService.java:158)

and at this line the  catch exception is 

```
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@71752bda(incomplete)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:142)
	at org.redisson.command.CommandSyncService.evalWrite(CommandSyncService.java:70)
	at org.redisson.executor.TasksRunnerService.finish(TasksRunnerService.java:388)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:352)
	at org.redisson.executor.TasksRunnerService.schedule(TasksRunnerService.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:105)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:453)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@71752bda(incomplete)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:244)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:139)
	... 17 more

```

Redis version
redis 5.0.7

Redisson version
3.15.1

Redisson configuration
```java
    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient(){
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379")
        ;
        return Redisson.create(config);
    }
```

**Comment by gaosjx** [comment]
Redis version
redis 5.0.7

Redisson version
3.15.1

Redisson configuration
```java
    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient(){
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379")
        ;
        return Redisson.create(config);
    }
```

**Comment by gaosjx** [comment]
Looking forward to your reply.. thanks..  @mrniko

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by gaosjx** [comment]
The fix hasn't been released yet, but we want to use it because we in the production environment.

I downloaded the source code today, switched to the corresponding tag(3.15.1) and tried to build it with the this fixed change, but the Maven dependency couldn't be found.

Is there any instruction to build the project, thanks  @mrniko 

![image](https://user-images.githubusercontent.com/19669879/123455248-10887380-d614-11eb-996a-5a3251cf89d6.png)

**Comment by mom1705** [comment]
My stack trace is below Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@140d6eb0(incomplete)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:212)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 13 more


and I am still getting same on recently released 3.16

**Comment by mrniko** [comment]
@mom1705 

Can you share full stacktrace?

**Comment by mom1705** [comment]
org.redisson.client.RedisException: java.lang.InterruptedException:
***@***.***(incomplete)
org.redisson.client.RedisException: java.lang.InterruptedException:
***@***.***(incomplete)
        at
org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
        at org.redisson.RedissonObject.get(RedissonObject.java:82)
        at org.redisson.RedissonList.add(RedissonList.java:115)
        at
com.nokia.fm.SnmpToClogAlarm.clearHBMissingAlarm(SnmpToClogAlarm.java:213)
        at com.nokia.fm.HeartBeat.clearHBMissingAlarm(HeartBeat.java:184)
        at com.nokia.fm.HeartBeat$1.onResponse(HeartBeat.java:258)
        at org.snmp4j.Snmp.processPdu(Snmp.java:1300)
        at
org.snmp4j.MessageDispatcherImpl.fireProcessPdu(MessageDispatcherImpl.java:694)
        at
org.snmp4j.MessageDispatcherImpl.dispatchMessage(MessageDispatcherImpl.java:310)
        at
org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:390)
        at
org.snmp4j.MessageDispatcherImpl.processMessage(MessageDispatcherImpl.java:350)
        at
org.snmp4j.transport.AbstractTransportMapping.fireProcessMessage(AbstractTransportMapping.java:76)
        at
org.snmp4j.transport.DefaultUdpTransportMapping$ListenThread.run(DefaultUdpTransportMapping.java:430)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException:
***@***.***(incomplete)
        at
io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:244)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at
org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 13 more

**Comment by mrniko** [comment]
Application server may interrupt threads.

**Comment by mom1705** [comment]
I am seeing that only one thread is leading to this which was to process snmp4j packets as below

 ResponseListener listener = new ResponseListener() {
            @Override
            public void onResponse(ResponseEvent event) {
