### ISSUE TITLE
Redisson running under Quarkus throws ClassNotFoundException

### ISSUE THREAD

**Issue by magnusvage** [redisson/redisson#3655]
I am trying to use a Redisson pubsub solution between several nodes running jobs.
Redisson crashes when trying to deserialize a message published by another node.
Quarkus version: 1.13.4.Final

**Expected behavior**
The message subscriber should receive the message without error
**Actual behavior**
Publishing works just fine. When the subscriber receives a message, a ClassNotFoundException is thrown during deserialization
```
2021-05-26 12:39:38,151 ERROR [org.red.cli.han.CommandPubSubDecoder] (redisson-netty-2-13) Unable to decode data. channel: [id: 0xb6172e95, L:/127.0.0.1:56969 - R:localhost/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=228, widx=228): java.io.IOException: java.lang.ClassNotFoundException: org.acme.interfaces.dto.DTOJobTerminationRequest
        at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:148)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367)
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:72)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:88)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: org.acme.interfaces.dto.DTOJobTerminationRequest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:421)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:416)
        at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129)
        at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1048)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231)
        at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
        at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:146)
        ... 25 more
```
**Steps to reproduce or test case**
Subscribe to any message while running Redisson under Quarkus

**Redis version**
redis_version:5.0.8

**Redisson version**
3.15.6

**Redisson configuration**
```
        Config config = new Config();
        config.useSingleServer().setAddress(connectionString);
        redissonClient = Redisson.create(config);
```

**Comment by magnusvage** [comment]
Solved it by adding a custom coded to the config:

```
        Codec codec = new JsonJacksonCodec(Thread.currentThread().getContextClassLoader());
        config.setCodec(codec);
```

Should this be necessary or can this be fixed in Redisson to use the correct class loader?

**Comment by mrniko** [comment]
Unable to reproduce it using Redisson quarkus integration module.

**Comment by magnusvage** [comment]
@mrniko is the Redisson quarkus integration module available for use yet?

**Comment by mrniko** [comment]
I plan to release it during this month
