### ISSUE TITLE
ClassCastException occurs 

### ISSUE THREAD

**Issue by ahsanbagwan** [redisson/redisson#3659]
I'm seeing these errors in logs, this for `Instant` and others for Enums as well

My value serializer is `StringSerializer` and the codec is not defined explicitly so it would be picking by default.

What would be the issue? Do I need to change to JDK serializer or Jackson one?

```
2021-06-14 15:00:19,622 ERROR org.redisson.client.handler.CommandDecoder [redisson-netty-5-21] Unable to decode data. channel: [id: 0xa39136eb, L:/10.11.4.187:52704 - R:redis/172.20.33.10:6379], reply: ReplayingDecoderByteBuf(ridx=712, widx=712), command: (HGET), params: [new-vendor-date, PooledUnsafeDirectByteBuf(ridx: 0, widx: 469, cap: 512)]
java.lang.ClassCastException: Cannot cast java.lang.String to java.time.Instant
    at java.base/java.lang.Class.cast(Unknown Source)
    at org.jboss.marshalling.reflect.SerializableField.setObject(SerializableField.java:342)
    at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1864)
    at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1778)
    at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1406)
    at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283)
    at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231)
    at org.jboss.marshalling.river.RiverUnmarshaller.doReadCollectionObject(RiverUnmarshaller.java:187)
    at org.jboss.marshalling.river.RiverUnmarshaller.readCollectionData(RiverUnmarshaller.java:861)
```

**Comment by mrniko** [comment]
Can you provide code example? Which StringSerializer do you use?

**Comment by ahsanbagwan** [comment]
StringRedisSerializer

**Comment by mrniko** [comment]
default codec isn't compatible with StringRedisSerializer. Try to use StringCodec instead
