### ISSUE TITLE
Invalidate cache (2LD Cache Hibernate) if add or remove column in entity.

### ISSUE THREAD

**Issue by EinBexiii** [redisson/redisson#3668]
**Expected behavior**

It should not throw an error and only use the columns that are present in the entity, unfortunately I don't know exactly how redisson stores that. 

**Actual behavior**
If you have an entity and add or remove a column and try to load it, you get an error.

**Steps to reproduce or test case**

Run 2 Java applications use hibernate-core (5.5.2.Final) and redisson-hibernate-53 (3.13.4) and setup redisson 2LD cache.

First Application has the "old" entity like:

`
public class TestEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "p_id", updatable = false, unique = true, nullable = false)
    private Long id;

    @NaturalId
    @Column(name = "p_uuid")
    private String uuid;

    @Column(name = "p_name")
    private String name;

    @Column(name = "test_int")
    private int test;
}
`

And the second application has the "new" entity like:

`
public class TestEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "p_id", updatable = false, unique = true, nullable = false)
    private Long id;

    @NaturalId
    @Column(name = "p_uuid")
    private String uuid;

    @Column(name = "p_name")
    private String name;

    @Column(name = "test_int")
    private int test;

    @Column(name = "bool")
    private boolean bool;
}
`

Then try to load it on the first application it will work. But then try to load it on the second application and you will get this exception:

`java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at org.hibernate.type.TypeHelper.assemble(TypeHelper.java:97)
        at org.hibernate.cache.spi.entry.StandardCacheEntryImpl.assemble(StandardCacheEntryImpl.java:135)
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.convertCacheEntryToEntity(CacheEntityLoaderHelper.java:308)
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.processCachedEntry(CacheEntityLoaderHelper.java:174)
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.loadFromSecondLevelCache(CacheEntityLoaderHelper.java:147)
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:523)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:327)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1215)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1204)
        at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:203)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2819)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2796)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2752)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2796)
        at org.hibernate.internal.SessionImpl$SimpleNaturalIdLoadAccessImpl.load(SessionImpl.java:3241)
        at net.rushnation.rushhandler.command.CommandTest$CommandInsert.run(CommandTest.java:27)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at net.rushnation.rushhandler.utils.terminal.TerminalConsole.runCommand(TerminalConsole.java:24)
        at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168)
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
        at net.rushnation.rushhandler.RushHandler.lambda$setupTerminal$2(RushHandler.java:202)
        at java.base/java.lang.Thread.run(Thread.java:834)`

if you clear the cache and load it on the second application first and try to load in on the first application you will get this error:

`org.hibernate.PropertyAccessException: Could not set field value [true] value by reflection : [class net.rushnation.database.entities.test.TestEntity.name] setter of net.rushnation.database.entities.test.TestEntity.name
        at org.hibernate.property.access.spi.SetterFieldImpl.set(SetterFieldImpl.java:72) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:681) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:144) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:5242) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.cache.spi.entry.StandardCacheEntryImpl.assemble(StandardCacheEntryImpl.java:159) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.convertCacheEntryToEntity(CacheEntityLoaderHelper.java:308) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.processCachedEntry(CacheEntityLoaderHelper.java:174) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.loader.entity.CacheEntityLoaderHelper.loadFromSecondLevelCache(CacheEntityLoaderHelper.java:147) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:523) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:327) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1215) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1204) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:203) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2819) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2796) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2752) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2796) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at org.hibernate.internal.SessionImpl$SimpleNaturalIdLoadAccessImpl.load(SessionImpl.java:3241) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at net.rushnation.rushhandler.command.CommandTest$CommandInsert.run(CommandTest.java:27) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at picocli.CommandLine.access$1300(CommandLine.java:145) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at picocli.CommandLine.execute(CommandLine.java:2078) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at net.rushnation.rushhandler.utils.terminal.TerminalConsole.runCommand(TerminalConsole.java:24) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at net.rushnation.rushhandler.RushHandler.lambda$setupTerminal$2(RushHandler.java:202) ~[rushhandler-1.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.String field net.rushnation.database.entities.test.TestEntity.name to java.lang.Boolean
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:780) ~[?:?]
        at org.hibernate.property.access.spi.SetterFieldImpl.set(SetterFieldImpl.java:52) ~[rushhandler-1.0-SNAPSHOT.jar:?]`

**Redis version**

redis_version:5.0.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:94145a25ce04923
redis_mode:standalone

**Redisson version**

 <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-hibernate-53</artifactId>
            <version>3.13.4</version>
        </dependency>

**Redisson configuration**

singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 8000
  retryAttempts: 3
  retryInterval: 1500
  password: 
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 16
  connectionMinimumIdleSize: 10
  connectionPoolSize: 32
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 16
codec: null
useThreadClassLoader: false

**Comment by mrniko** [comment]
hibernate doesn't provide API to detect data structure changes. You need to handle it.

**Comment by EinBexiii** [comment]
> hibernate doesn't provide API to detect data structure changes. You need to handle it.

is there any example of how to handle it?
