### ISSUE TITLE
MOVED redirection loop detected on AWS Elasticache

### ISSUE THREAD

**Issue by UzimakiNaruto** [redisson/redisson#3685]
**Expected behavior**
works fine.

**Actual behavior**
```java
org.redisson.client.RedisException: MOVED redirection loop detected. Node redis://188.34.174:6379 has further redirect to redis://188.34.63.174:6379

	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:412)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:164)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:78)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:317)
```

**Steps to reproduce or test case**

```java

Config config = new Config();
config
    .useReplicatedServers()
    .setReadMode(ReadMode.MASTER)
    .addNodeAddress("redis://awsendpoint:6379");

RedissonClient redisson = Redisson.create(config);
int i = 0;
while (true) {
    RBucket<Object> buc = redisson.getBucket(String.valueOf(i++));
    buc.set(i);
    System.out.println(buc.get());
    buc.delete();
}

```

**Redis version**
3.2.10

**Redisson version**
test on 3.13.3, 3.15.0, 3.15.6

**Redisson configuration**
```java
Config config = new Config();
config
    .useReplicatedServers()
    .setReadMode(ReadMode.MASTER)
    .addNodeAddress("redis://awsendpoint:6379");
```

It works fine when use cluster config. but the cluster mode has bug when redis failover, like https://github.com/redisson/redisson/issues/3635 ,  I want to try replicated mode. and found the issue.

**Comment by mrniko** [comment]
useReplicatedServers can't be used with Redis cluster.

**Comment by UzimakiNaruto** [comment]
😞 Thanks for your response, 

But what's the difference between `Master slave mode` and 'Replicated mode'?

**Comment by mrniko** [comment]
with `Replicated mode` the role of each node is polled to determine if a failover has occurred resulting in a new master.
