### ISSUE TITLE
redisson crashing 

### ISSUE THREAD

**Issue by mom1705** [redisson/redisson#3689]
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@2e24330d(incomplete)
org.redisson.client.RedisException: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@2e24330d(incomplete)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
        at org.redisson.RedissonObject.get(RedissonObject.java:82)
        at org.redisson.RedissonList.add(RedissonList.java:115)
  
Caused by: java.lang.InterruptedException: ImmediateEventExecutor$ImmediatePromise@2e24330d(incomplete)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:212)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        ... 13 more
^C

**Comment by mrniko** [comment]
How to reproduce it?
