### ISSUE TITLE
Getting UndeclaredThrowableException when cache down while doing rlos.get()

### ISSUE THREAD

**Issue by mayurgoenka** [redisson/redisson#3697]
https://stackoverflow.com/questions/19690653/undeclaredthrowableexception-thrown-by-indexoutofboundsexception
https://amitstechblog.wordpress.com/2011/07/24/java-proxies-and-undeclaredthrowableexception/

Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:767)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)

Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.redisson.liveobject.core.LiveObjectInterceptor.intercept(LiveObjectInterceptor.java:133)

rlos.get() causing this. As per above writeups method.invoke calls needs to be handled explicitly.

**Comment by mrniko** [comment]
Fixed! Thanks for report
