### ISSUE TITLE
Live object batch persist error

### ISSUE THREAD

**Issue by liucq200518** [redisson/redisson#3710]
Code:
```java
Config config = new Config();
        config.setThreads(5);
        config.useSingleServer().setAddress("redis://192.168.7.214:6379");
        RedissonClient redissonClient = Redisson.create(config);
        long docId = IdUtil.getSnowflake(1, 1).nextId();
        RLiveObjectService liveObjectService = redissonClient.getLiveObjectService();
        InventoryDocTemp[] inventoryDocTemps = new InventoryDocTemp[0];
        for (int i = 0; i < 100; i++) {
            InventoryDocTemp inventoryDocTemp = new InventoryDocTemp();
            inventoryDocTemp.setDocType("pur_settle");
            inventoryDocTemp.setDocId(docId);
            inventoryDocTemp.setShardId(IdUtil.getSnowflake(1, 1).nextId());
            inventoryDocTemp.setTenantTag("3");
            inventoryDocTemps = ArraysUtil.append(inventoryDocTemps,inventoryDocTemp);
        }

        liveObjectService.persist(inventoryDocTemps);

        redissonClient.shutdown();
```
Exception:
```java
Exception in thread "main" jodd.bean.BeanException: Setter failed: jodd.introspector.Setter$1@127e70c5; <--- java.lang.IllegalStateException: Batch already executed!
	at jodd.bean.BeanUtilUtil.invokeSetter(BeanUtilUtil.java:118)
	at jodd.bean.BeanUtilBean.setSimpleProperty(BeanUtilBean.java:210)
	at jodd.bean.BeanUtilBean._setIndexProperty(BeanUtilBean.java:408)
	at jodd.bean.BeanUtilBean.setIndexProperty(BeanUtilBean.java:400)
	at jodd.bean.BeanUtilBean.setProperty(BeanUtilBean.java:475)
	at jodd.bean.BeanCopy.visitProperty(BeanCopy.java:183)
	at jodd.bean.BeanVisitor.visit(BeanVisitor.java:177)
	at org.redisson.liveobject.misc.AdvBeanCopy.copy(AdvBeanCopy.java:37)
	at org.redisson.RedissonLiveObjectService.copy(RedissonLiveObjectService.java:682)
	at org.redisson.RedissonLiveObjectService.persist(RedissonLiveObjectService.java:226)
	at com.keyway.business.core.BusinessCoreTest.main(BusinessCoreTest.java:62)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jodd.introspector.Setter$1.invokeSetter(Setter.java:39)
	at jodd.bean.BeanUtilUtil.invokeSetter(BeanUtilUtil.java:113)
	... 10 more
Caused by: java.lang.IllegalStateException: Batch already executed!
	at org.redisson.command.CommandBatchService.executeAsync(CommandBatchService.java:218)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:195)
	at org.redisson.liveobject.core.AccessorInterceptor.removeIndex(AccessorInterceptor.java:213)
	at org.redisson.liveobject.core.AccessorInterceptor.intercept(AccessorInterceptor.java:159)
	at com.keyway.business.core.inventory.entity.po.InventoryDocTemp$ByteBuddy$uXgkKRpi.setDocType(Unknown Source)
	... 16 more
---[cause]------------------------------------------------------------------------
java.lang.IllegalStateException: Batch already executed!
	at org.redisson.command.CommandBatchService.executeAsync(CommandBatchService.java:218)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:195)
	at org.redisson.liveobject.core.AccessorInterceptor.removeIndex(AccessorInterceptor.java:213)
	at org.redisson.liveobject.core.AccessorInterceptor.intercept(AccessorInterceptor.java:159)
	at com.keyway.business.core.inventory.entity.po.InventoryDocTemp$ByteBuddy$uXgkKRpi.setDocType(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jodd.introspector.Setter$1.invokeSetter(Setter.java:39)
	at jodd.bean.BeanUtilUtil.invokeSetter(BeanUtilUtil.java:113)
	at jodd.bean.BeanUtilBean.setSimpleProperty(BeanUtilBean.java:210)
	at jodd.bean.BeanUtilBean._setIndexProperty(BeanUtilBean.java:408)
	at jodd.bean.BeanUtilBean.setIndexProperty(BeanUtilBean.java:400)
	at jodd.bean.BeanUtilBean.setProperty(BeanUtilBean.java:475)
	at jodd.bean.BeanCopy.visitProperty(BeanCopy.java:183)
	at jodd.bean.BeanVisitor.visit(BeanVisitor.java:177)
	at org.redisson.liveobject.misc.AdvBeanCopy.copy(AdvBeanCopy.java:37)
	at org.redisson.RedissonLiveObjectService.copy(RedissonLiveObjectService.java:682)
	at org.redisson.RedissonLiveObjectService.persist(RedissonLiveObjectService.java:226)
	at com.keyway.business.core.BusinessCoreTest.main(BusinessCoreTest.java:62)
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
