### ISSUE TITLE
Unsupported protocol version 50

### ISSUE THREAD

**Issue by shiguota** [redisson/redisson#3713]
Retrieve data error，Beg big guy to help see

 Caused by: java.io.IOException: Unsupported protocol version 50
	at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1375) ~[jboss-marshalling-river-2.0.11.Final.jar:2.0.11.Final]
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:145) ~[redisson-3.16.0.jar:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358) ~[redisson-3.16.0.jar:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177) ~[redisson-3.16.0.jar:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116) ~[redisson-3.16.0.jar:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101) ~[redisson-3.16.0.jar:3.16.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	... 17 common frames omitted

**Comment by mrniko** [comment]
update your JDK to 1.8+
