### ISSUE TITLE
ClassNotFoundException Exception RemoteServiceResponse

### ISSUE THREAD

**Issue by abhijit911turbo** [redisson/redisson#3735]
Hi, 
We are intermediately getting ClassNotFoundException exception while using redisson-spring-data-23:3.16.0. Could someone guide on the issue and its resolution please.

Using bare minimum config as below.
            config.useClusterServers()
                    .addNodeAddress(host)
                    .setPassword(password)
                    .setPingConnectionInterval(pingConnectionInterval)
                    .setKeepAlive(keepAlive);

2021-07-19 15:52:53.763 ERROR 17 --- [sson-netty-2-31] o.r.client.handler.CommandDecoder        : Unable to decode data. channel: [id: 0x810739dd, L:/10.118.165.160:58932 - R:euw-dev-004-develop-redis.redis.cache.windows.net/10.118.221.36:6379], reply: ReplayingDecoderByteBuf(ridx=2003, widx=2003), command: (BLPOP), params: [{remote_response}:c99cdcb5-dc74-4ed0-8a21-b62e5d392436, 0]

java.io.IOException: java.lang.ClassNotFoundException: org.redisson.remote.RemoteServiceResponse
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:148) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101) ~[redisson-3.16.0.jar!/:3.16.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.ClassNotFoundException: org.redisson.remote.RemoteServiceResponse
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1048) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:146) ~[redisson-3.16.0.jar!/:3.16.0]
	... 25 common frames omitted

2021-07-19 15:52:53.765 ERROR 17 --- [sson-netty-2-31] org.redisson.remote.AsyncRemoteProxy     : Can't get response from {remote_response}:c99cdcb5-dc74-4ed0-8a21-b62e5d392436

java.io.IOException: java.lang.ClassNotFoundException: org.redisson.remote.RemoteServiceResponse
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:148) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101) ~[redisson-3.16.0.jar!/:3.16.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.ClassNotFoundException: org.redisson.remote.RemoteServiceResponse
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1048) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:146) ~[redisson-3.16.0.jar!/:3.16.0]
	... 25 common frames omitted

2021-07-19 15:52:53.767 ERROR 17 --- [sson-netty-2-31] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x810739dd, L:/10.118.165.160:58932 - R:euw-dev-004-develop-redis.redis.cache.windows.net/10.118.221.36:6379]

io.netty.handler.codec.DecoderException: java.io.IOException: java.lang.ClassNotFoundException: org.redisson.remote.RemoteServiceResponse
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.io.IOException: java.lang.ClassNotFoundException: org.redisson.remote.RemoteServiceResponse
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:148) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116) ~[redisson-3.16.0.jar!/:3.16.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101) ~[redisson-3.16.0.jar!/:3.16.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
	... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.redisson.remote.RemoteServiceResponse
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1048) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231) ~[jboss-marshalling-river-2.0.11.Final.jar!/:2.0.11.Final]
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[jboss-marshalling-2.0.11.Final.jar!/:2.0.11.Final]
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:146) ~[redisson-3.16.0.jar!/:3.16.0]
	... 25 common frames omitted

**Comment by mrniko** [comment]
This is a classloader problem.
