### ISSUE TITLE
Issue with AWS Elasticache using ReplicatedConfig when failover

### ISSUE THREAD

**Issue by axelczk** [redisson/redisson#3736]
Hello,

We are working through issues using Redisson with AWS Elasticache during switch between master/slave. 

We currently have a replicated cluster of size 2: 1 master and 1 replicated node. AWS Elasticache provides two DNS endpoint: the primary one, and the reader. 
Sometime on a failover, there is a switch between the master and the slave behind the DNS and redisson update his connexion. But it seem that the Redisson switch is incorrect and our service can't proceed command when this occurs. 

Here is some log to help:
```
Jul 18, 2021 @ 08:57:42.757 ERROR redisson-netty-2-1 Can't process the remote service request.
org.redisson.client.RedisException: READONLY You can't write against a read only replica.. channel: [id: 0x7bdd858d, L:/X.X.2.68:37420 - R:READ_ONLY_DNS/X.X.1.13:6379] command: (BLPOP), params: [{redisson_mapreduce:org.redisson.executor.RemoteExecutorService}, 0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
	
Jul 18, 2021 @ 08:57:42.759 INFO redisson-netty-2-1 24 connections initialized for PRIMARY_DNS/X.X.1.13:6379
Jul 18, 2021 @ 08:57:42.769 ERROR redisson-netty-2-1 Can't process the remote service request. 
Jul 18, 2021 @ 08:57:47.799 INFO redisson-netty-2-1 1 connections initialized for PRIMARY_DNS/X.X.2.27:6379 
Jul 18, 2021 @ 08:57:48.764 INFO redisson-netty-2-1 master PRIMARY_DNS/X.X.2.27:6379 has changed to READ_ONLY_DNS/X.X.1.13:6379 
Jul 18, 2021 @ 08:57:48.764 INFO redisson-netty-2-1 master READ_ONLY_DNS/X.X.1.13:6379 used as slave 
Jul 18, 2021 @ 08:57:48.764 INFO redisson-netty-2-1 24 connections initialized for READ_ONLY_DNS/X.X.1.13:6379 
Jul 18, 2021 @ 08:57:48.772 ERROR redisson-netty-2-1 Can't process the remote service request. 
Jul 18, 2021 @ 08:57:52.794 INFO redisson-netty-2-1 1 connections initialized for PRIMARY_DNS/X.X.1.13:6379 
Jul 18, 2021 @ 08:57:52.796 ERROR redisson-netty-2-1 Can't process the remote service request. 
Jul 18, 2021 @ 08:57:54.779 INFO redisson-netty-2-1 24 connections initialized for PRIMARY_DNS/X.X.1.13:6379 
Jul 18, 2021 @ 08:58:00.794 ERROR redisson-netty-2-1 Can't process the remote service request. 
Jul 18, 2021 @ 08:58:05.792 INFO redisson-netty-2-1 master PRIMARY_DNS/X.X.2.27:6379 used as slave 
Jul 18, 2021 @ 08:58:05.793 INFO redisson-netty-2-1 24 connections initialized for PRIMARY_DNS/X.X.2.27:6379 
Jul 18, 2021 @ 08:58:05.793 INFO redisson-netty-2-1 master READ_ONLY_DNS/X.X.1.13:6379 has changed to PRIMARY_DNS/X.X.2.27:6379 
Jul 18, 2021 @ 08:58:06.799 INFO redisson-netty-2-1 1 connections initialized for PRIMARY_DNS/X.X.1.13:6379 
Jul 18, 2021 @ 08:58:06.802 ERROR redisson-netty-2-1 Can't process the remote service request. 
```

Redisson config:

```
var config = new Config();
config.useReplicatedServers().addNodeAddress(props.getHosts().toArray(new String[0]));

var nodeConfig = new RedissonNodeConfig(config);
nodeConfig.setBeanFactory(factory);

var redissonClient = Redisson.create(config);
var node = RedissonNode.create(nodeConfig, redissonClient);
node.start();

return redissonClient;
```

Redisson version: 3.12
Redis version: 5.0.6

**Comment by mrniko** [comment]
> Sometime on a failover, there is a switch between the master and the slave behind the DNS and redisson update his connexion. But it seem that the Redisson switch is incorrect and our service can't proceed command when this occurs.

Did you define all nodes in config? Elasticache topology in replicated mode updated only through changing `role` attribute returned by `INFO REPLICATION` command.

**Comment by axelczk** [comment]
Inside the config, props.getHosts return a list of endpoint:
redis://PRIMARY_DNS:6379/, redis://READ_ONLY_DNS:6379/

We do not use the elasticache node endpoint.

**Comment by mrniko** [comment]
I tested it with default dnsMonitoringInterval setting set to `5000` and it works.

ReplicatedConnectionManager detects changes if nodes defined as hosts.

**Comment by axelczk** [comment]
Yes this error persisted after the failover. The service was stuck without the possibility to write on Redis until we restarted it.

**Comment by mrniko** [comment]
sorry, dnsMonitoringInterval should be `-1`. But resolver still works in scheduleMasterChangeCheck method.

**Comment by mrniko** [comment]
Fixed
