### ISSUE TITLE
Class cast exceptions on CommandsData

### ISSUE THREAD

**Issue by ddehen** [redisson/redisson#3743]
We're using redisson pro and getting class cast exceptions. Our dependencies in maven look like:

```
<dependency>
    <groupId>pro.redisson</groupId>
    <artifactId>redisson-spring-boot-starter</artifactId>
    <version>3.16.0-5</version>
    <exclusions>
        <exclusion>
            <groupId>pro.redisson</groupId>
            <artifactId>redisson-spring-data-25</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>pro.redisson</groupId>
    <artifactId>redisson-spring-data-23</artifactId>
    <version>3.16.0-5</version>
</dependency>
```

The exceptions we're getting:
```
2021-07-24 10:05:51,341 [trace=,span=] ERROR ErrorsLoggingHandler:47   - Exception occured. Channel: [id: 0x32a400e8, L:/192.168.205.61:55165 ! R:xuqsfh-0015-001.xuqsfh.gnfyko.euw1.cache.amazonaws.com/10.223.14.197:6379]
java.lang.ClassCastException: class org.redisson.client.protocol.CommandsData cannot be cast to class org.redisson.client.protocol.CommandData (org.redisson.client.protocol.CommandsData and org.redisson.client.protocol.CommandData are in unnamed module of loader 'app')
	at org.redisson.client.handler.CommandsQueue.channelInactive(CommandsQueue.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at org.redisson.client.handler.ConnectionWatchdog.channelInactive(ConnectionWatchdog.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1121)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Does someone have an idea how to resolve this?

**Comment by mrniko** [comment]
you can switch to 3.16.0-3 version as workaround.

**Comment by mrniko** [comment]
Can you provide test code to reproduce it?

**Comment by mrniko** [comment]
3.16.0-6 version has been released. Please try it.

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/commit/675f9dea91339c9aaad1d89dd94504bf84a1a845

**Comment by ddehen** [comment]
Thanks, the new version has fixed the class cast exceptions.
