### ISSUE TITLE
sslProtocols parse issue

### ISSUE THREAD

**Issue by chomiczon** [redisson/redisson#3748]
Hi.
After adding sslProtocols option to redisson.yaml file I get error below:
redisson version: 3.16.1 for tomcat 8
After removing sslProtocols line no errors reported in tomcat console

`28-Jul-2021 14:43:15.259 SEVERE [main] org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans Exception processing Global JNDI Resources
	javax.naming.NamingException: Can't parse yaml config conf/redisson.yaml [Root exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: (String)"---
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: P@ssword
  subscriptionsPerConnection: 5
  clientName: "Client"
  address: "rediss://redis.local:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 1
  dnsMonitoringInterval: 5000
  sslProvider: OPENSSL
  sslProtocols: TLSv1.2
thread"[truncated 95 chars]; line: 1, column: 3]]
		at org.redisson.JndiRedissonFactory.buildClient(JndiRedissonFactory.java:57)
		at org.redisson.JndiRedissonFactory.getObjectInstance(JndiRedissonFactory.java:45)
		at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:96)
		at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
		at org.apache.naming.NamingContext.lookup(NamingContext.java:847)
		at org.apache.naming.NamingContext.lookup(NamingContext.java:157)
		at org.apache.naming.NamingContextBindingsEnumeration.nextElementInternal(NamingContextBindingsEnumeration.java:115)
		at org.apache.naming.NamingContextBindingsEnumeration.next(NamingContextBindingsEnumeration.java:69)
		at org.apache.naming.NamingContextBindingsEnumeration.next(NamingContextBindingsEnumeration.java:32)
		at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans(GlobalResourcesLifecycleListener.java:131)
		at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans(GlobalResourcesLifecycleListener.java:138)
		at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans(GlobalResourcesLifecycleListener.java:105)
		at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.lifecycleEvent(GlobalResourcesLifecycleListener.java:80)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:763)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:688)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
`

**Comment by mrniko** [comment]
>  Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9)

Seems you have incorrect yaml format.

**Comment by chomiczon** [comment]
[redisson.yaml.txt](https://github.com/redisson/redisson/files/6894419/redisson.yaml.txt)

Attach my yaml file

**Comment by mrniko** [comment]
wrap values in "..."

**Comment by chomiczon** [comment]
I've tired, the same error

**Comment by mrniko** [comment]
try this:
```
  sslProtocols:
  - "TLSv1.2"
```

**Comment by mrniko** [comment]
sslProvider value also should be in "..."

**Comment by chomiczon** [comment]
Yes, this is it. It's expects list not a single value
