### ISSUE TITLE
java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by Sneakometer** [redisson/redisson#3758]
Hello, first time using redisson. I have a very basic setup with redisson 3.16.1 running on jdk 16.
Trying to use redis for a simple cache: `RMap<UUID, String> uuidCache;`
The setup is just like the basic examplte from the README.
But when launching the app, this exception is printed and redis doesn't seem to work.
```
 [15:30:37 ERROR] [org.redisson.client.handler.ErrorsLoggingHandler]: Exception occured. Channel: [id: 0x8a9de85b, L:/127.0.0.1:53284 - R:127.0.0.1/127.0.0.1:6379]
[03.08 15:30:38.240] INFO: [Proxy-2] java.lang.ExceptionInInitializerError: null
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1321) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1064) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:146) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:366) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.Thread.run(Thread.java:831) [?:?]
[03.08 15:30:38.240] INFO: [Proxy-2] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.util.AbstractMap() accessible: module java.base does not "opens java.util" to unnamed module @53b75da5
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.reflect.Constructor.setAccessible(Constructor.java:181) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.<init>(JDKSpecific.java:147) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:84) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.ClassValue.getFromHashMap(ClassValue.java:228) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.ClassValue.getFromBackup(ClassValue.java:210) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.ClassValue.get(ClassValue.java:116) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:76) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.ClassValue.getFromHashMap(ClassValue.java:228) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.ClassValue.getFromBackup(ClassValue.java:210) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at java.lang.ClassValue.get(ClassValue.java:116) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:152) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:146) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    at org.jboss.marshalling.river.ClassDescriptors.<clinit>(ClassDescriptors.java:101) ~[?:?]
[03.08 15:30:38.240] INFO: [Proxy-2]    ... 30 more
```

Is this a knows issue?
Thanks for help.

**Comment by mrniko** [comment]
JDK 16 introduced internal encapsulation. You can read more about it here - https://blogs.oracle.com/javamagazine/java-runtime-encapsulation-internals#anchor_6.

Фdd follow setting to JVM parameters:

--add-opens=java.base/java.util=ALL-UNNAMED

**Comment by Sneakometer** [comment]
Is there any codec with proper java 16 support that does not require to set some jvm flag?
