### ISSUE TITLE
Issue when testing failover on AWS Elaticache

### ISSUE THREAD

**Issue by ieiayaobb** [redisson/redisson#3762]
**Redis version**
5.0.0
**Redisson version**
3.11.6 / 3.16.1
**Redisson configuration**
threads: 16
nettThreads: 64
scanInterval: 5000
retryAttempts: 0
timeout: 5000

Hi, I'm facing an issue when testing failover on AWS Elaticache

I'm using Redis Cluster with 2 slots, each slot contains 1 master and 1 slave.
It takes about 8 minutes after I trigger a failover event and the Redis works well but my services seem cannot recover by themselves.

I dump a thread capture and may get some useful information:
 - I'm using jetty as our web container and the operation I'm using with Redisson is quite simple - this.redissonClient.getBucket()
 - The reason why the service cannot recover is that threads are blocked in JVM, I can see __900__ qtp* in JVM and their states look like this:
```
"qtp821513849-296" #296 prio=5 os_prio=0 tid=0x00007fe8f78eb800 nid=0x164 in Object.wait() [0x00007fe8b03b7000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:252)
	- locked <0x000000069ca55c50> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:142)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonBucket.get(RedissonBucket.java:97)
...
```
 - And the redisson-netty-* threads are all in epollWait
```
"redisson-netty-2-64" #1114 prio=5 os_prio=0 tid=0x00007fe8d5130000 nid=0x496 runnable [0x00007fe84e3b4000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000691506e68> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000691506e58> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000691506e10> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

From my understanding, when the web requests try to get data from Redis Cluster, one of the nodes takes the task asynchronously then callback to the service by Netty epoll. So when the master failover, the tasks on this node cannot answer anymore, which makes those qtp* threads cannot finish.

I'm wondering if my guess is correct and how I can solve this issue, like giving a timeout for web requests or returning exceptions from Redisson side?

Although failover is not a common case, it still hurts a lot when my service cannot recover automatically.

Expecting for your response, thanks a lot.

**Comment by mrniko** [comment]
did you try to set retryAttempts = 1?

**Comment by ieiayaobb** [comment]
Well, this really works. Although it takes some time, the service can finally recover by itself.

However, this gains more questions on me: why retyAttempts=1 can work but retryAttempts=3 cannot.
I'm using both 3.16.1 and 3.10.0 this time, both of them can work well with retryAttepts=1. And the online issue happened with 3.10.0 and retryAttempts=3.

Can you help explain the backend logic or reason why make this happen? thanks in advance.

**Comment by mrniko** [comment]
> And the online issue happened with 3.10.0 and retryAttempts=3.

Does it mean that 3.16.1 version works with retryAttempts=3?

**Comment by ieiayaobb** [comment]
I didn't try that, are there any changes after 3.10.0.

**Comment by ieiayaobb** [comment]
Hello @mrniko ,
Any idea about my question?

**Comment by mrniko** [comment]
Will try to reproduce issue.

**Comment by mrniko** [comment]
unable to reproduce it with 3.16.3

**Comment by ieiayaobb** [comment]
Is it possible to give some detail environment you were using for reproducing, maybe I can learn from it.

**Comment by mrniko** [comment]
Redis Cluster 3 masters and single slave per master.
