### ISSUE TITLE
Exceptions when changing node type in AWS Elasticache on the fly

### ISSUE THREAD

**Issue by Vorotyntsev** [redisson/redisson#3771]
We tried to update underlying node type in our Elasticache Redis cluster. When AWS starts switching to newly created nodes, we see a lot of exception:
```
org.redisson.client.RedisException: MOVED redirection loop detected. Node redis://<node_address>:6379 has further redirect to redis://<same_node_address>:6379
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:404) ~[redisson-3.13.5.jar:3.13.5]
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:164) ~[redisson-3.13.5.jar:3.13.5]
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[redisson-3.13.5.jar:3.13.5]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) ~[redisson-3.13.5.jar:3.13.5]
	at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:78) ~[redisson-3.13.5.jar:3.13.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:339) ~[redisson-3.13.5.jar:3.13.5]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) ~[redisson-3.13.5.jar:3.13.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) ~[redisson-3.13.5.jar:3.13.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) ~[redisson-3.13.5.jar:3.13.5]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[netty-handler-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224) ~[netty-handler-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271) ~[netty-handler-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Is it possible to scale Redis cluster vertically on the fly using Redisson?

Engine Version Compatibility: 6.0.5
Redisson version: 3.13.5, also tried 3.16.1

**Comment by mrniko** [comment]
> Is it possible to scale Redis cluster vertically on the fly using Redisson?

Of course.

Can you share log with `TRACE` logging level for `org.redisson` package?

**Comment by Vorotyntsev** [comment]
I will rerun the test tomorrow. Should I look for some specific logs? I guess we'll have millions of logs in total

**Comment by mrniko** [comment]
First off I need all logs produced by ClusterConnectionManager

**Comment by Vorotyntsev** [comment]
Here are the logs from a single backend service considering `<redis>-0005` only. During this test it was the first one to throw exceptions. File contains logs few minutes before the exceptions started and the first exception itself. 
I excluded logs like `slot <int> for <key>`
[logs.txt](https://github.com/redisson/redisson/files/6975422/logs.txt)

**Comment by mrniko** [comment]
thanks for provided logs. Can you also give logs a few minutes before `MOVED redirection loop detected` exception?

**Comment by Vorotyntsev** [comment]
+15 previous minutes
[logs-2.txt](https://github.com/redisson/redisson/files/6982835/logs-2.txt)

**Comment by mrniko** [comment]
sorry, can you share log entries with TRACE logging level for the same period of time?

**Comment by mrniko** [comment]
In your log I see that cluster node state returns hostname instead of ip addresses. Is it result of ip address replacement applied to log? or original log output?

hosts example: `<redis>-0003-001.<redis>.amazonaws.com`, `<redis>-0001-002.<redis>.amazonaws.com` ...

**Comment by mrniko** [comment]
Please try attached version.

[redisson-3.16.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7045541/redisson-3.16.2-SNAPSHOT.jar.zip)

**Comment by Vorotyntsev** [comment]
It's an original log output, I just replaced the sensitive data with <redis>

**Comment by Vorotyntsev** [comment]
I'll try this version today, thanks

**Comment by Vorotyntsev** [comment]
Hello. This version didn't help, I saw NPE on some pods.
[logs-4.txt](https://github.com/redisson/redisson/files/7075359/logs-4.txt)

**Comment by mrniko** [comment]
Thanks for feedback!

Please try attached version.
[redisson-3.16.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7076269/redisson-3.16.2-SNAPSHOT.jar.zip)

**Comment by Vorotyntsev** [comment]
Sorry for the delay.
This version is much better. One of exceptions (see attached file) is ```LOADING Redis is loading the dataset in memory```. Does it mean that AWS started redirecting from an old node to new before a new node is ready? Sounds like a bug for me
[logs-5.txt](https://github.com/redisson/redisson/files/7097404/logs-5.txt)

**Comment by mrniko** [comment]
Can you share more logs for the same node before `LOADING Redis is loading the dataset in memory` ?

**Comment by mrniko** [comment]
Can you confirm that "MOVED redirection loop detected" error has gone?

**Comment by Vorotyntsev** [comment]
Which logs do you need? Attached ClusterConnectionManager logs.
[logs-6.txt](https://github.com/redisson/redisson/files/7098019/logs-6.txt)

Yes, ```MOVED redirection loop detected``` are gone

**Comment by mrniko** [comment]
I need more information on IP L:/<ip>:49724 - R:<ip>/<ip>:6379 to find it in cluster nodes state.

**Comment by Vorotyntsev** [comment]
I could find only these logs with ":49724"
[logs-7.txt](https://github.com/redisson/redisson/files/7098100/logs-7.txt)

**Comment by mrniko** [comment]
R:/:6379 - redis address.

**Comment by mrniko** [comment]
There is nothing to do with `LOADING Redis is loading the dataset in memory` since it's reported by Redis when it loads data. I'm closing this issue since it has been resolved.

**Comment by Vorotyntsev** [comment]
Do I understand correctly that MOVED redirection loop will be fixed in 3.16.2 release and LOADING is a bug on AWS side?

**Comment by Vorotyntsev** [comment]
So redisson doesn't try to send requests to nodes that report LOADING?

**Comment by mrniko** [comment]
Redisson resends commands again and again until it reaches retryattemts limit.

**Comment by Vorotyntsev** [comment]
Got you, thanks a lot!

**Comment by f-sander** [comment]
@mrniko Could we not immediately freeze connections upon receiving a `LOADING` response to prevent further requests being send to the node?

**Comment by avcad** [comment]
This was my concern as well when I saw this change:
https://github.com/redisson/redisson/blob/92d22f8867c68d42a0b35e1a186498040980cd01/redisson/src/main/java/org/redisson/client/handler/PingConnectionHandler.java#L86


We tested failover in the past and it worked fine, but I was concern that with this change, it could be extended
The standard failover:
