### ISSUE TITLE
nginx PROXY redis

### ISSUE THREAD

**Issue by wl980868110** [redisson/redisson#3775]
org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 150.109.250.34/150.109.250.34:6379
        at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:160)
        at org.redisson.connection.pool.ConnectionPool$1$$Lambda$22/44206143.accept(Unknown Source)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
        at org.redisson.misc.RedissonPromise$$Lambda$17/1473623671.operationComplete(Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:330)
        at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:296)
        at org.redisson.connection.pool.ConnectionPool$$Lambda$21/1213290808.accept(Unknown Source)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
        at org.redisson.misc.RedissonPromise$$Lambda$17/1473623671.operationComplete(Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
        at org.redisson.client.RedisClient$2$1.run(RedisClient.java:240)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.redisson.client.RedisException: ERR unknown command 'PROXY'. channel: [id: 0x25e8b191, L:/172.29.0.4:39298 - R:150.109.250.34/150.109.250.34:6379] command: (AUTH), params: (password masked)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        ... 4 more

**Comment by mrniko** [comment]
there is no `proxy` command in Redis.

**Comment by wl980868110** [comment]
The problem of our PROXY
