### ISSUE TITLE
Deserialization difference between RedissonMap and RedissonLocalCachedMap

### ISSUE THREAD

**Issue by Sovietaced** [redisson/redisson#3792]
**Expected behavior**

I was writing some unit tests and I discovered that I could not perform any operations on a second instance of `RedissonLocalCachedMap` when I was storing non primitive key/values in the map. 

My expectation is that a second instance of `RedissonLocalCachedMap` would be able to read values from a map as long as `RedissonMap` could. This is preventing me from using `RedissonLocalCachedMap` in my code. 

**Actual behavior**

```
An exception is thrown
Unexpected exception while processing command
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:324)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:121)
	at org.redisson.RedissonObject.get(RedissonObject.java:82)
	at org.redisson.RedissonMap.readAllValues(RedissonMap.java:850)
	at ai.argo.viaduct.discovery.redis.RedissonDemo.localCachedMapNotWorking(RedissonDemo.kt:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at ...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3585)
	at org.redisson.codec.TypedJsonJacksonCodec$2.decode(TypedJsonJacksonCodec.java:63)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Steps to reproduce or test case**

```kotlin
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.redisson.api.LocalCachedMapOptions
import org.redisson.api.RLocalCachedMap
import org.redisson.api.RMap
import org.redisson.client.codec.Codec
import org.redisson.codec.TypedJsonJacksonCodec
import java.util.UUID

class RedissonDemo : RedisIntegrationTestBase() {

    data class DemoObject(
        val id: UUID
    )


    @BeforeEach
    fun beforeEach() {
        redisClient.keys.flushall()
    }

    @Test
    fun mapWorking() {
        val map1: RMap<String, DemoObject> = redisClient.getMap("test", generateCodec())
        val map2: RMap<String, DemoObject> = redisClient.getMap("test", generateCodec())
        map1.put("key", DemoObject(UUID.randomUUID()))
        map1.readAllValues()
        map2.readAllValues()
    }

    @Test
    fun localCachedMapNotWorking() {
        val map1: RLocalCachedMap<String, DemoObject> = redisClient.getLocalCachedMap("test", generateCodec(), LocalCachedMapOptions.defaults())
        val map2: RLocalCachedMap<String, DemoObject> = redisClient.getLocalCachedMap("test", generateCodec(), LocalCachedMapOptions.defaults())
        map1.put("key", DemoObject(UUID.randomUUID()))
        map1.readAllValues()
        map2.readAllValues() // FAILS HERE
    }

    /**
     * Generates a Jackson codec that supports Kotlin classes.
     */
    private fun generateCodec(): Codec {
        // Needed to serialize/deserialize kotlin objects into redis
        val objectMapper = jacksonObjectMapper()
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

        return TypedJsonJacksonCodec(String::class.java, DemoObject::class.java, objectMapper)
    }
}
```

**Redis version**
6+

**Redisson version**
3.15.5

**Redisson configuration**
```kotlin
val address: String = redis.host
val port: Int = redis.firstMappedPort
val config = Config()
config.useSingleServer().address = "redis://$address:$port"
redisClient = Redisson.create(config)
```

**Comment by mrniko** [comment]
> Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]

It's data serialization problem. Seems you store plain string value and not json.

**Comment by mrniko** [comment]
Fixed! Thanks for report
