### ISSUE TITLE
exception class loader 

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3793]
hi,
we have the following exception even we change the configuration to :

useThreadClassLoader = false

java.io.IOException: java.lang.ClassNotFoundException: com.panaya.as.blexecuter.imp.BaseBLContext
at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:153) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.codec.SnappyCodec$3.decode(SnappyCodec.java:84) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356) [redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:400) [redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365) [redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178) [redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) [redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [redisson-all-3.14.0.jar:3.14.0]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: com.panaya.as.blexecuter.imp.BaseBLContext
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1952) ~[catalina.jar:7.0.105]
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1795) ~[catalina.jar:7.0.105]
at java.lang.Class.forName0(Native Method) ~[na:1.8.0_261]
at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_261]
at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1033) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1366) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:216) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:151) ~[redisson-all-3.14.0.jar:3.14.0]
... 26 common frames omitted

**Comment by wdaas** [comment]
io.netty.handler.codec.DecoderException: java.io.IOException: java.lang.ClassNotFoundException: org.springframework.security.core.context.SecurityContextImpl
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[redisson-all-3.14.0.jar:3.14.0]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [redisson-all-3.14.0.jar:3.14.0]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [redisson-all-3.14.0.jar:3.14.0]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_261]
Caused by: java.io.IOException: java.lang.ClassNotFoundException: org.springframework.security.core.context.SecurityContextImpl
at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:153) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.codec.SnappyCodec$3.decode(SnappyCodec.java:84) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:400) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102) ~[redisson-all-3.14.0.jar:3.14.0]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[redisson-all-3.14.0.jar:3.14.0]
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[redisson-all-3.14.0.jar:3.14.0]
... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.security.core.context.SecurityContextImpl
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1952) ~[catalina.jar:7.0.105]
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1795) ~[catalina.jar:7.0.105]
at java.lang.Class.forName0(Native Method) ~[na:1.8.0_261]
at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_261]
at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1033) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1366) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:216) ~[redisson-all-3.14.0.jar:3.14.0]
at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41) ~[redisson-all-3.14.0.jar:3.14.0]
at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:151) ~[redisson-all-3.14.0.jar:3.14.0]
... 26 common frames omitted

**Comment by mrniko** [comment]
Try this config:
```java
        Codec codec = new MarshallingCodec(Thread.currentThread().getContextClassLoader());
        config.setCodec(codec);
```

**Comment by wdaas** [comment]
hi,
how we can do that in configuration, I think this exception is related to Redisson tomcat session?

**Comment by mrniko** [comment]
It's classloader problem.

**Comment by mrniko** [comment]
where did you put Redisson jar ? in application or tomcat/lib?

**Comment by wdaas** [comment]
we have it in both
in  tomcat lib 
we added redisson-all-3.14.0 and redisson-tomcat-7-3.14.0

and at application jar we have:
redisson 3.14.0
and
redisson-tomcat-7

**Comment by mrniko** [comment]
remove jars in application

**Comment by wdaas** [comment]
in our case, we have jars in the application to support using redisson also as a cache if we deleted in maven how we can do it ?

we using redisson as a session manager and as a cache client.

**Comment by mrniko** [comment]
Use `provided` maven scope. https://howtodoinjava.com/maven/maven-dependency-scopes/

**Comment by wdaas** [comment]
hi,
we tried to remove jar from app, but it wasn't able to recognize the app classes that we saved in the cache ?
