### ISSUE TITLE
port out of range:-1 if host is starting with slash

### ISSUE THREAD

**Issue by Diarsid** [redisson/redisson#3807]
**Description**
If hostname is given to Config with leading slash it causes exception 'port out of range:-1'

**Expected behavior**
Either of two variants:
1) exception about incorrect **host** should be thrown
2) slash should be trimmed silently from host string and proceed.

**Actual behavior**
Exception about incorrect **port** instead of incorrect **host**.
```
java.lang.IllegalArgumentException: port out of range:-1

	at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.base/java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:254)
	at org.redisson.client.RedisClient.resolveAddr(RedisClient.java:192)
	at org.redisson.connection.MasterSlaveEntry.setupMasterEntry(MasterSlaveEntry.java:118)
	at org.redisson.connection.MasterSlaveEntry.setupMasterEntry(MasterSlaveEntry.java:108)
	at org.redisson.connection.MasterSlaveConnectionManager.initSingleEntry(MasterSlaveConnectionManager.java:334)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:143)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:30)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:190)
	at org.redisson.Redisson.<init>(Redisson.java:67)
	at org.redisson.Redisson.create(Redisson.java:108)
```
This behaviour is very misleading and cause to search a ghost mistake with port configuration instead of host typo.

**Steps to reproduce or test case**
```
        int port = 6379;
        String host = "/localhost";      // <- hostname is started with slash by config mistake, typo, etc.
        Config config = new Config();
        config
                .useSingleServer()
                .setAddress("redis://" + host + ":" + port)
                .setDatabase(0);

        redisson = Redisson.create(config);
```

**Redisson version**
```
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.16.1</version>
        </dependency>
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
