### ISSUE TITLE
mset command (getBuckets().set(Map<String, ?>)) in redis cluster throw CROSSSLOT

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#3810]
Redisson: 3.6.1
redis: 6.2.5 in cluster mode
use redisson.getBucket().get(keys...) success,
but when i use redisson.getBucket().set(Map<String,?>) and keys hashed in different slot,throw a CROSSSLOT
it's a bug? or because of other considerations
and i can pr to fix it?

 [redisson-netty-2-2] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.183:7000 added for slot ranges: [[10923-16383]]
[redisson-netty-2-2] INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 192.168.1.187/192.168.1.187:7000
Exception in thread "main" org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x04b473c3, L:/172.30.1.206:52837 - R:192.168.1.183/192.168.1.183:7000] command: (MSET), params: [test123221, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256), tesdasdadasdasdasd1, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256), tesdasdasd3221, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256)]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:353)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
Fixed! Thanks for report
