### ISSUE TITLE
HINCRBYFLOAT  java.lang.NumberFormatException: For input string: "PONG"

### ISSUE THREAD

**Issue by lintghi** [redisson/redisson#3817]
**Expected behavior**
Not Execption

**Actual behavior**

long addTypeAmount(int type, long amount) {
RMap<Integer, Number> map = redisson.getMap("sumAmount:Id:7");

Number sum = map.addAndGet(type, amount);
return sum == null ? 0 : sum.longValue();
}

09-07 11:38:17.364 ERROR[CommandDecoder] - Unable to decode data. channel: [id: 0xb42d4b58, L:/192.168.0.1:44540 - R:192.168.0.1/192.168.0.1:7011], reply: ReplayingDecoderByteBuf(ridx=7, widx=7), command: (HINCRBYFLOAT), params: [sumAmount:Id:7, Poo
ledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100]
java.lang.NumberFormatException: For input string: "PONG"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.redisson.client.protocol.convertor.NumberConvertor.convert(NumberConvertor.java:38)
        at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:432)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:316)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
09-07 11:38:17.364 ERROR[ErrorsLoggingHandler] - Exception occured. Channel: [id: 0xb42d4b58, L:/192.168.0.1:44540 - R:192.168.0.1/192.168.0.1:7011]
io.netty.handler.codec.DecoderException: java.lang.NumberFormatException: For input string: "PONG"
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "PONG"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.redisson.client.protocol.convertor.NumberConvertor.convert(NumberConvertor.java:38)
        at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:432)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:316)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        ... 17 common frames omitted

**Steps to reproduce or test case**

**Redis version**
6.2

**Redisson version**
3.16.2

**Redisson configuration**

    <bean id="jsonJacksonCodec" class="org.redisson.codec.JsonJacksonCodec" />

    <redisson:client id="redisson"
                     name="redisson"
                     codec-ref="jsonJacksonCodec"
                     >

		<redisson:cluster-servers client-name="client1" 
				retry-attempts="0" 
				master-connection-minimum-idle-size="150" 
				master-connection-pool-size="150" 
				slave-connection-minimum-idle-size="150" 
				slave-connection-pool-size="150"
				connect-timeout="30000"
				read-mode="SLAVE"
		>
			<redisson:node-address value="redis://192.168.0.1:7011"/>
			<redisson:node-address value="redis://192.168.0.2:7011"/>
			<redisson:node-address value="redis://192.168.0.3:7011"/>
			<redisson:node-address value="redis://192.168.0.1:7012"/>
			<redisson:node-address value="redis://192.168.0.2:7012"/>
			<redisson:node-address value="redis://192.168.0.3:7012"/>
		</redisson:cluster-servers>                                
		
    </redisson:client>

**Comment by mrniko** [comment]
Can you share Redisson logs in `TRACE` level?

**Comment by lintghi** [comment]
18:21:01.773 T[CommandDecoder] - reply: $4
5400
, channel: [id: 0xfffff615, L:/192.168.0.1:35223 - R:192.168.0.2/192.168.0.2:7012], 
command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@c81afc9(incomplete)], 
command=(HINCRBYFLOAT), params=[sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100], codec=org.redisson.client.codec.StringCodec]

18:21:01.773 D[RedisExecutor] - connection released for command (HINCRBYFLOAT) and params [sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100] from 
slot NodeSource [slot=11698, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@1432387595 [redisClient=[addr=redis://192.168.0.2:7012], 
channel=[id: 0xfffff615, L:/192.168.0.1:35223 - R:192.168.0.2/192.168.0.2:7012], 
currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@c81afc9(success: 5400)], 
command=(HINCRBYFLOAT), params=[sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100], codec=org.redisson.client.codec.StringCodec]]

.....

18:21:01.774 T[CommandDecoder] - reply: $4
5700
, channel: [id: 0xb5019495, L:/192.168.0.1:26778 - R:172.16.100.223/172.16.100.223:7011], 
command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@44d063c1(incomplete)], 
command=(HGET), params=[sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256)], codec=org.redisson.codec.JsonJacksonCodec]
18:21:01.774 T[CommandEncoder] - channel: [id: 0x581a48a0, L:/192.168.0.1:38885 - R:192.168.0.2/192.168.0.2:7011] message: *3
$6
CLIENT
$5
REPLY
$3
OFF

18:21:01.774 D[RedisExecutor] - connection released for command (HGET) and params [sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256)] from 
slot NodeSource [slot=11698, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@624217440 [redisClient=[addr=redis://172.16.100.223:7011], 
channel=[id: 0xb5019495, L:/192.168.0.1:26778 - R:172.16.100.223/172.16.100.223:7011], 
currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@44d063c1(success: 5700)], 
command=(HGET), params=[sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256)], codec=org.redisson.codec.JsonJacksonCodec]]

.....

18:21:01.775 T[CommandDecoder] - reply: +OK
, channel: [id: 0x7df0a965, L:/192.168.0.1:35585 - R:192.168.0.2/192.168.0.2:7012], 
command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@1296910e(incomplete)], 
command=(HINCRBYFLOAT), params=[sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100], codec=org.redisson.client.codec.StringCodec]


18:21:01.775 E[CommandDecoder] - Unable to decode data. channel: [id: 0x7df0a965, L:/192.168.0.1:35585 - R:192.168.0.2/192.168.0.2:7012], reply: ReplayingDecoderByteBuf(ridx=5, widx=5), 
command: (HINCRBYFLOAT), params: [sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100]
java.lang.NumberFormatException: For input string: "OK"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.redisson.client.protocol.convertor.NumberConvertor.convert(NumberConvertor.java:38)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:432)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:316)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

18:21:01.775 D[RedisExecutor] - connection released for command (HINCRBYFLOAT) and params [sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100] from s
lot NodeSource [slot=11698, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@275105941 [redisClient=[addr=redis://192.168.0.2:7012], 
channel=[id: 0x7df0a965, L:/192.168.0.1:35585 - R:192.168.0.2/192.168.0.2:7012], 
currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@1296910e(failure: java.lang.NumberFormatException: For input string: "OK")], 
command=(HINCRBYFLOAT), params=[sumAmount:Id:31, PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), 100], codec=org.redisson.client.codec.StringCodec]]

**Comment by lintghi** [comment]
i downgrade to redisson 2.15.2, it's gone.  in the high pressure, this issue alway arise.

**Comment by mrniko** [comment]
can you try 3.16.0 version?

**Comment by mrniko** [comment]
as workaround don't use RBatch object with `.skipResult()` option.

**Comment by lintghi** [comment]
ok, thanks

**Comment by mrniko** [comment]
Fixed
