### ISSUE TITLE
RedissonV3.16.2 write null command to slave node when use epoll transportMode

### ISSUE THREAD

**Issue by Moouna** [redisson/redisson#3828]
Redisson: 3.16.2
Netty: 4.1.67.Final
Netty-epoll : 4.1.67.Final

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=2, freeConnectionsCounter=value:15:queue:0, freezeReason=null, client=[addr=redis://10.178.22.6:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1103912317 [redisClient=[addr=redis://10.178.22.6:6379], channel=[id: 0x7839e36f, L:/10.171.102.45:46670 ! R:10.178.22.6/10.178.22.6:6379], currentCommand=null], command: null, params: null after 0 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:280)
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:60)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:161)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:158)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1017)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:878)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

Redisson Config
    Config config = new Config();
    config.setTransportMode(OsUtils.getTransportMode());
    ClusterServersConfig serversConfig = config.useClusterServers();
    serversConfig.setReadMode(ReadMode.MASTER_SLAVE);
    serversConfig.setRetryInterval(1500);
    serversConfig.setRetryAttempts(0); 
    serversConfig.setConnectTimeout(10000);
    serversConfig.setMasterConnectionPoolSize(15);
    serversConfig.setSlaveConnectionPoolSize(15);
    serversConfig.setMasterConnectionMinimumIdleSize(2);
    serversConfig.setSlaveConnectionMinimumIdleSize(2);
    serversConfig.setSubscriptionConnectionMinimumIdleSize(0);

You can't try to checkFuture by write command to redis, the slave node in redis cluster shouldn't be allowed to do this.

**Comment by Moouna** [comment]
It also occurred in NIO mode 
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=2, freeConnectionsCounter=value:15:queue:0, freezeReason=null, client=[addr=redis://10.178.217.234:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@429192474 [redisClient=[addr=redis://10.177.169.198:6379], channel=[id: 0x40904f5a, L:/10.170.176.152:49034 ! R:10.177.169.198/10.177.169.198:6379], currentCommand=null], command: null, params: null after 0 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:280)
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:60)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:161)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:158)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1017)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:878)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

**Comment by mrniko** [comment]
> You can't try to checkFuture by write command to redis, the slave node in redis cluster shouldn't be allowed to do this.

Could you clarify here? According to exception master node is used.

**Comment by mrniko** [comment]
`command: null` means batch of commands.

**Comment by Moouna** [comment]
RBatch batch = client.createBatch(BatchOptions.defaults());
keys.forEach(key -> {
    batch.getBucket(key, StringCodec.INSTANCE).getAsync();
});
BatchResult<?> res = batch.execute();
Map<String, T> map = new HashMap<>();
for (int i = 0; i < res.getResponses().size(); i++) {
    map.put(keys.get(i), (T) res.getResponses().get(i));
}
return map;

the only code use redisson is to read, but send write command ?

**Comment by Moouna** [comment]
I will check all the commands，may be send null to redisson

**Comment by Moouna** [comment]
it happened again
log info and other infos 

Redis request {"batches":{"aaaaaaa_test":{"hashFields":{"1A5":6,"1A6":7}},"clusterId":7} exception org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=2, freeConnectionsCounter=value:15:queue:0, freezeReason=null, client=[addr=redis://10.178.56.44:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@871543246 [redisClient=[addr=redis://10.178.56.44:6379], channel=[id: 0x9ee45f4d, L:/10.170.63.26:40934 ! R:10.178.56.44/10.178.56.44:6379], currentCommand=null], command: null, params: null after 1 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:280)
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:60)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:161)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:158)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1017)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:878)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139)
		at reactor.core.publisher.Mono.block(Mono.java:1727)
		at com.test.RedisRepositoryReactorImpl.get(RedisRepositoryReactorImpl.java:87)
		at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:51)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)



RBatchReactive batch=client.createBatch(batchOptions());
            boolean emptyBatch = true;
            for (QueryBatchBean requestBatch : request.getBatches().values()) {
                if (requestBatch == null || StringUtils.isEmpty(requestBatch.getHashKey()) || requestBatch.getHashFields()==null|| requestBatch.getHashFields().size() == 0) {
                    log.error("Redis request error :{}",requestBatch==null?null:JSON.toJSONString(requestBatch.getKey()));
                    continue;
                }
                Set set = requestBatch.getHashFields().keySet();
                emptyBatch=false;
                Mono<Map<String, String>> mono = batch.getMap(requestBatch.getHashKey())
                    .getAll(set);
                mono.subscribe(
                    res->{
                        requestBatch.getHashFields().entrySet().stream().forEach(
                            entry->{
                                String result = res.get(entry.getKey());
                                if(result==null){
                                    return;
                                }
                                response.getFeatures().get(requestBatch.getKey())
                                    .set(entry.getValue(), result);
                            }
                        );
                    }
                );
                mono.doOnError(
                    exception -> {
                        log.error("Redis query error,{}", ExceptionUtils.getStackTrace(exception));
                    }
                );
            }
            if(!emptyBatch){
                try {
                    BatchResult<?> responses = batch.execute()
                        .block(Duration.ofMillis(Constants.RESPONSE_TIMEOUT));
                }catch (Exception e){
                    log.error("Redis request {} exception {}",JSON.toJSONString(request),ExceptionUtils.getStackTrace(e));
                }

            }else{
                if(batch!=null){
                    batch.discard();
                }
            }

**Comment by mrniko** [comment]
Can you try it with 3.16.0 version?

**Comment by mrniko** [comment]
You can't use `requestBatch` in `mono.subscribe` since it will be in executed executed. Also make sure you don't call blocking methods in `mono.subscribe` callback.

**Comment by Moouna** [comment]
`if(request==null||request.getBatches()==null||response==null||response.getFeatures()==null){
            return;
        }
        RBatchReactive batch = client.createBatch(batchOptions());
        boolean emptyBatch = true;
        List<QueryBatchBean> temp = new ArrayList<>(request.getBatches().values());
        for (QueryBatchBean requestBatch : temp) {
            if (requestBatch == null || StringUtils.isEmpty(requestBatch.getHashKey())
                || requestBatch.getHashFields() == null
                || requestBatch.getHashFields().size() == 0) {
                log.error("Redis request error :{}",
                    requestBatch == null ? null : JSON.toJSONString(requestBatch.getKey()));
                continue;
            }
            Set set = requestBatch.getHashFields().keySet();
            emptyBatch = false;
            batch.getMap(requestBatch.getHashKey())
                .getAll(set);

        }
        if (!emptyBatch) {
            try {
                BatchResult<?> responses =batch.execute().block(Duration.ofMillis(Constants.RESPONSE_TIMEOUT));
                for (int i = 0; i < responses.getResponses().size(); i++) {
                    Map<String,String> map =(Map<String,String>)responses.getResponses().get(i);
                    QueryBatchBean requestBatch = temp.get(i);
                    map.forEach((key,value)->{
                        response.getFeatures().get(requestBatch.getKey())
                            .set(requestBatch.getHashFields().get(key), value);
                    });
                }
            } catch (Exception e) {
                log.error("Redis request {} exception {} ,chance {}",
                    JSON.toJSONString(request),
                    ExceptionUtils.getStackTrace(e), false);
            }

        } else {
            if (batch != null) {
                batch.discard();
            }
        }`

error again

how to use reactive batch api in redisson

**Comment by mrniko** [comment]
Did you try to increase connections amount?
