### ISSUE TITLE
Unexpected exception while processing command

### ISSUE THREAD

**Issue by 1171971708** [redisson/redisson#3843]
### `org.redisson.client.RedisException: Unexpected exception while processing command`

**Demo Code**

```
@Slf4j
@SpringBootTest
class RedisTest {
	private static final Integer SUM_I = 1000;
	private static final Integer SECONDS = 60 * 60;
	private static final ExecutorService EXECUTOR_SERVICE = Executors.newFixedThreadPool(SUM_I);
	@Resource  private RedisService redisService;

	@Test  void test() { 
		// init redis value  
		for (int i = 1; i <= SUM_I; i++) {
            setRedis(i);  
        }

        // create task  
        List<FutureTask<Integer>> futureTasks = Lists.newArrayList();
        for (int i = 1; i <= SUM_I; i++) { 
        	int finalI = i;  FutureTask<Integer> futureTask = new FutureTask<>(() -> getRedis(finalI));
        	  futureTasks.add(futureTask); 
	    } 

	   // get redis value  
	   futureTasks.forEach(EXECUTOR_SERVICE::submit);  
	   for (int i = 0; i < futureTasks.size(); i++) {
            Integer value = null;  
            try {
                value = futureTasks.get(i).get();  
            } catch (Exception e) {
                e.printStackTrace();  
            } 
            int skipI = i + 1;  
            if (Objects.nonNull(value)) {
                futureTasks.stream()
                        .skip(skipI)
                        .forEach(task -> task.cancel(true));  
                break;  
            }
        }
    } 

    private void setRedis(Integer no) {
        String key = "TEST:" + no;  
        redisService.set(key, no, SECONDS); 
    }

    private Integer getRedis(Integer no) {
        String key = "TEST:" + no;
        try {
            Thread.sleep(500L + no);  
        } catch (InterruptedException e) {
            e.printStackTrace();  
        }
        Integer redisNo = redisService.get(key);  
        System.out.println("TEST:" + redisNo);  
        return redisNo;  
    }
}
```

![image](https://user-images.githubusercontent.com/38726443/134446214-7cd53dd3-e626-4332-95bd-7b1ead812d37.png)

**Comment by mrniko** [comment]
unable to reproduce it. Below is an output:

```
TEST:4
TEST:7
TEST:1
TEST:8
TEST:3
TEST:5
TEST:2
TEST:6
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
TEST:9
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
TEST:13
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
TEST:12
	at java.base/java.lang.Thread.run(Thread.java:834)
TEST:16
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
TEST:11
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
TEST:10
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at org.redisson.RedissonTest.getRedis(RedissonTest.java:91)
	at org.redisson.RedissonTest.lambda$test1$0(RedissonTest.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
TEST:15
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
TEST:14
```
