### ISSUE TITLE
when use CompletableFuture.runAsync to create thread we got no class definition found from redisson 

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3858]
when start new thread using CompletableFuture.runAsync we have no class definition found 

we have useThreadClassLoader: true

org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:351)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:148)
	at org.redisson.RedissonObject.get(RedissonObject.java:81)
	at org.redisson.RedissonMap.get(RedissonMap.java:618)

Caused by: java.io.IOException: java.lang.ClassNotFoundException: com.panaya.domain.tm.entityMetaData.PemEntity
	at org.redisson.codec.MarshallingCodec$3.decode(MarshallingCodec.java:153)
	at org.redisson.codec.SnappyCodec$3.decode(SnappyCodec.java:84)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:356)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(Byt

**Comment by mrniko** [comment]
thread classloader of executor passed to CompletableFuture.runAsync isn't aware of these classes.
