### ISSUE TITLE
redis-sentinel connection with ssl not working as expected

### ISSUE THREAD

**Issue by MrAbdul** [redisson/redisson#3875]
we have three VMs running redis and redis-sentinal in ssl mode. and we are facing issue connecting to it with redisson

**Expected behavior**
we should be able to connect with redisson to the cluster

**Actual behavior**
2021-10-10 13:20:42.150 [restartedMain] INFO  org.redisson.Version                               : Redisson 3.16.3
2021-10-10 13:20:43.399 [restartedMain] INFO  o.r.c.SentinelConnectionManager                    : master: redis://yyy.yyy.yyy.yyy:6379 added
2021-10-10 13:20:43.410 [restartedMain] INFO  o.r.c.SentinelConnectionManager                    : slave: rediss://xxx.xxx.xxx.xxx:6379 added
2021-10-10 13:20:43.411 [restartedMain] INFO  o.r.c.SentinelConnectionManager                    : slave: rediss://xxx.xxx.xxx.xxx:6379 added
2021-10-10 13:20:43.491 [redisson-netty-2-7] INFO  o.r.c.SentinelConnectionManager                    : sentinel: rediss://xxx.xxx.xxx.xxx:26379 added
2021-10-10 13:20:43.497 [redisson-netty-2-8] INFO  o.r.c.SentinelConnectionManager                    : sentinel: rediss://xxx.xxx.xxx.xxx:26379 added
2021-10-10 13:20:43.497 [redisson-netty-2-9] INFO  o.r.c.SentinelConnectionManager                    : sentinel: rediss://xxx.xxx.xxx.xxx:26379 added
2021-10-10 13:21:13.645 [restartedMain] WARN  c.b.p.utilities.CacheUtil                          : Problem connecting to redis server, check the configurations, or if the server is up and reachable
2021-10-10 13:21:13.646 [restartedMain] WARN  c.b.p.utilities.CacheUtil                          : Redisson configuration loacation is D:\oracle\domains\ecore_domain\resources\redisonConfig.yml
2021-10-10 13:21:13.649 [restartedMain] ERROR c.b.p.utilities.CacheUtil                          : Exception occurred at restartedMain Exception Message
org.redisson.client.RedisConnectionException: Unable to connect to Redis server: yyy.yyy.yyy.yyy/yyy.yyy.yyy.yyy:6379
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:158)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:310)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$2(ConnectionPool.java:276)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
	at org.redisson.client.RedisClient$2$1.run(RedisClient.java:242)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://yyy.yyy.yyy.yyy:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:255)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	... 2 common frames omitted

**Steps to reproduce or test case**
use the provided configuration and connect to to the cluster using ssl

**Redis version**
6.0.9
**Redisson version**
6.0.9
**Redisson configuration**
---
sentinelServersConfig:
  idleConnectionTimeout: 100000
  connectTimeout: 100000
  timeout: 30000
  retryAttempts: 3
  retryInterval: 1500
  password: "XXXXXXXXXXXX"
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: false
  sslProvider: "JDK"
  sslTruststore: "file:/path/to/redis-cluster.jks"
  sslTruststorePassword: "changeit"
  sslKeystore: "file:/path/to/redis-cluster.jks"
  sslKeystorePassword: "changeit"
  sslProtocols:
  - "TLSv1.2"
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
  nameMapper: !<org.redisson.api.DefaultNameMapper> {}
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  dnsMonitoringInterval: 5000
  sentinelAddresses:
  - "rediss://xxx.xxx.xxx.xxx:26379"
  - "rediss://xxx.xxx.xxx.xxx:26379"
  - "rediss://yyy.yyy.yyy.yyy:26379"
  natMapper: !<org.redisson.api.DefaultNatMapper> {}
  masterName: "redis-cluster"
  sentinelPassword: "XXXXXX"
  database: 0
  scanInterval: 1000
  checkSentinelsList: true
  checkSlaveStatusWithSyncing: true
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.MarshallingCodec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 300000
reliableTopicWatchdogTimeout: 6000000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}

**Comment by MrAbdul** [comment]
[trace output.txt](https://github.com/redisson/redisson/files/7321366/trace.output.txt)
attached is the trace output, I have masked the IP address and passwords.

**Comment by mrniko** [comment]
unable to find this output in your log. Also there are no entries for SslHandler object.

**Comment by MrAbdul** [comment]
then it might be a problem with the configuration, can you please let me know if this version of redisson supports redis 6 sentinel  and everything running tls (the redis nodes and the sentinel nodes)?
have this use case been tested? so I dont waste more time on this issue.

**Comment by MrAbdul** [comment]
hello, I figured it out, I created an edited build of redisson 3.16.4 and edited the place where I thought the issue is at,
i just changed RedisURIDecoder.java
I edited the function decode from this:
`    @Override
    public RedisURI decode(List<Object> parts, State state) {
        if (parts.isEmpty()) {
            return null;
        }
        return new RedisURI("redis", (String) parts.get(0), Integer.valueOf((String) parts.get(1)));
    }`

to this:
`    @Override
    public RedisURI decode(List<Object> parts, State state) {
        if (parts.isEmpty()) {
            return null;
        }
        return new RedisURI("rediss", (String) parts.get(0), Integer.valueOf((String) parts.get(1)));
    }`

and now it works 

please check this out and confirm why i needed that hack?
