### ISSUE TITLE
Transaction.commit

### ISSUE THREAD

**Issue by wl980868110** [redisson/redisson#3881]
redisson 3.12.1  The thread is always in this state

at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:142)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:160)
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:288)
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:261)
	at com.game.logical.crossmine.redissonstream.UpdateCrossMineRoleInfo.updateCrossMineRoleInfo(UpdateCrossMineRoleInfo.java:142)
	at com.game.logical.crossmine.redissonstream.UpdateCrossMineRoleInfo$$Lambda$214/219323629.apply(Unknown Source)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:151)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)

**Comment by wl980868110** [comment]
What's the problem

**Comment by mrniko** [comment]
@wl980868110 

Can you provide test case to reproduce?
