### ISSUE TITLE
Systematic timeouts since 3.16.1

### ISSUE THREAD

**Issue by Cesarla** [redisson/redisson#3883]
**Expected behavior**
No negative performance impact between redisson releases.

**Actual behavior**
After upgrading to redisson 3.16.3 from 3.15.0 operations started to time out, once it got rolled back, timeouts got back to regular values:
<img width="774" alt="Screenshot 2021-10-12 at 13 36 57" src="https://user-images.githubusercontent.com/1880223/136957251-0c00cd3c-7cb3-483c-a8b9-9b09adc810ce.png">

I've tried to gradually bump from 3.15.0 all the way to 3.16.3, and we experience the same performance problems when migrating from redisson 3.16.0 to 3.16.1.

Most of the timeouts are either `PSETEX` or lock acquiring and renewals:
```
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (100 ms) occured after 0 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (PSETEX), params: [com.xxx.yyy.events:Transactions.8:offset, 2678400000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 87, cap: 512)], channel: [id: 0xb9149117, L:/10.2.140.166:54946 - R:10.31.32.14/10.31.32.14:6379]
	at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$5(RedisExecutor.java:339)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
Caused by: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (1100 ms) occured after 0 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: null, params: null, channel: [id: 0xb9149117, L:/10.2.140.166:54946 - R:10.31.32.14/10.31.32.14:6379]
	at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$5(RedisExecutor.java:339)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
```

**Redis version**
Redis 5 (sentinel)

**Redisson version**
I've tested since 3.15.0 all the way until 3.16.3, and I can reproduce the issue on 3.16.1, 3.16.2 and 3.16.3

**Redisson configuration**
The settings hasn't changed across different versions:
```
transportMode: EPOLL
nettyThreads: 256
maxConnections: 128
connectTimeout: 75
timeout: 100
retryAttempts: 0
pingConnectionInterval: 0
```

**Comment by mrniko** [comment]
Any update?

**Comment by Cesarla** [comment]
Hi @mrniko, I have collected the two JFR session, a baseline with 3.16.0 and another one with the problematic 3.16.1. I will shared them in ~1h.
