### ISSUE TITLE
Regression in 3.16.3 fails EVALSHA operation on multiple-shard Redis Cluster with authenticated connections

### ISSUE THREAD

**Issue by vsemenov** [redisson/redisson#3888]
Redisson version 3.16.3 EVALSHA no longer works with AWS ElastiCache Redis Cluster that has more than 1 shard when the Redisson client is configured to use Redis authentication and TLS connections.

Downgrading to Redisson version 3.12.5 fixes this issue, and operations with multiple shard clusters with authentication work as expected.

**Expected behavior**
EVALSHA operation on multi-shard cluster completes successfully when connection is using Redis authentication

**Actual behavior**
The following code works on multi-shard clusters when clsuter Redis authentication and TLS connections are disabled, but fails when Redis authentication and TLS connections are enabled.
```
EVALSHA fails with the following error:
org.springframework.dao.InvalidDataAccessApiUsageException: Node: NodeSource [slot=11092, addr=rediss://XXXXXX-0002-001.XXXXXX.XXXXXX.usw2.cache.amazonaws.com:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.; nested exception is org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=11092, addr=rediss://XXXXXX-0002-001.XXXXXX.XXXXXX.usw2.cache.amazonaws.com:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:52)
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:195)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:190)
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:356)
	at org.redisson.spring.data.connection.RedissonConnection.write(RedissonConnection.java:722)
	at org.redisson.spring.data.connection.RedissonConnection.evalSha(RedissonConnection.java:1931)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy257.evalSha(Unknown Source)
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.eval(DefaultScriptExecutor.java:77)
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.lambda$execute$0(DefaultScriptExecutor.java:68)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
```

**Steps to reproduce or test case**
1. Create AWS ElastiCache Redis Cluster 5.0.6 and enable authentication and TLS connections
2. Use Redisson 3.16.3 to perform operations against that cluster such as EVALSHA

**Redis version**
5.0.6

**Redisson version**
3.16.3

**Redisson configuration**
```
final Config config = new Config();
config.setCodec(getKryoCodec())
		.useClusterServers()
		.setScanInterval(1000)
		.setReadMode(ReadMode.MASTER)
		.setRetryAttempts(3)
		.setRetryInterval(1000)
		.setTimeout(5000)
		.setIdleConnectionTimeout(10000)
		.setPassword(redisPassword)
		.addNodeAddress(redisClusterConfigurationEndpoint);
return Redisson.create(config);
```

Thank you!

**Comment by mrniko** [comment]
Please try attached version.

[redisson-3.16.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7344312/redisson-3.16.4-SNAPSHOT.jar.zip)
