### ISSUE TITLE
springboot 2.2.9 use redisson-spring-boot-starter 3.16.3 always throw 【StackOverflowError】

### ISSUE THREAD

**Issue by renjiancheng** [redisson/redisson#3905]
**Expected behavior**
true
**Actual behavior**
java.lang.StackOverflowError
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:801)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:801)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:801)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:801)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:801)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:801)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:801)

**Steps to reproduce or test case**
application.yml
```yaml
spring:
  redis:
    host: 192.168.1.113
    port: 6379
    database: 2
```
code
```java
@SpringBootTest
@Slf4j
class SpringBootRedissonDemoApplicationTests {
    @Resource
    private RedisTemplate<String,String> redisTemplate;

    @Test
    void contextLoads() {
        redisTemplate.opsForZSet().add("test","test1",1);
    }

}
```
**Redis version**
5.7
**Redisson version**
3.16.3
**Redisson configuration**

**Comment by R-juzi** [comment]
here：
![image](https://user-images.githubusercontent.com/59160257/138258661-707eab2c-9011-42b8-af7c-bd7fbca20216.png)
I solved this problem by changing the dependency to Redisson instead of redisson-spring-boot-starter，but  the bug is true

**Comment by mrniko** [comment]
Unable to reproduce. RedissonConnection implements both zAdd() methods.

**Comment by R-juzi** [comment]
The method being called is `default Boolean zAdd(byte[] key, double score, byte[] value)`,

**Comment by mrniko** [comment]
@Sid-27 

Make sure that you have redisson-spring-data-23 in classpath, if you use Spring Data Redis v.2.3.x
