### ISSUE TITLE
Unable to change master after the Redis singleServer changes Ip address

### ISSUE THREAD

**Issue by lokeshg98** [redisson/redisson#3906]
Hi, we are using singleServerConfig to connect to Redis server hosted in Cloud. we are using Redisson client 3.16.0 and pointing to elastic cache Reader endpoint and Redis server is running with one master one read replica. After the Redis server changes the IP address, DnsMonitor detected the IP address change correctly but is not able to connect again and throwing error 

```
1634782854423,"2021-10-21 02:20:54,423 | INFO  | redisson-netty-2-4                                                           | c.m.d.c.r.DataCacheConfig - Disconnected to redishostname redishostname1/IP1 redishostname1"
1634782854430,"2021-10-21 02:20:54,430 | INFO  | redisson-netty-2-4                                                           | c.m.d.c.r.DataCacheConfig - Trying to Reconnect after disconnection "
1634782854636,"2021-10-21 02:20:54,635 | INFO  | redisson-netty-2-4                                                           | org.redisson.Version - Redisson 3.16.0"
1634782854933,"2021-10-21 02:20:54,933 | INFO  | redisson-netty-14-6                                                          | c.m.d.c.r.DataCacheConfig - Connected to redishostname1 redishostname1/IP1 redishostname1"
1634782854935,"2021-10-21 02:20:54,935 | INFO  | redisson-netty-14-6                                                          | o.r.c.p.MasterPubSubConnectionPool - 1 connections initialized for redishostname1/IP1:6379"
1634782854938,"2021-10-21 02:20:54,938 | INFO  | redisson-netty-14-8                                                          | o.r.c.pool.MasterConnectionPool - 2 connections initialized for redishostname1/IP1:6379"
1634783767604,"2021-10-21 02:36:07,603 | INFO  | redisson-netty-5-5                                                           | c.m.d.c.r.DataCacheConfig - Disconnected to redishostname2 redishostname2/IP5 redishostname2"
1634783767604,"2021-10-21 02:36:07,604 | INFO  | redisson-netty-5-5                                                           | c.m.d.c.r.DataCacheConfig - Trying to Reconnect after disconnection "
1634783767745,"2021-10-21 02:36:07,745 | INFO  | redisson-netty-5-5                                                           | org.redisson.Version - Redisson 3.16.0"
1634783768133,"2021-10-21 02:36:08,133 | INFO  | redisson-netty-17-6                                                          | c.m.d.c.r.DataCacheConfig - Connected to redishostname2 redishostname2/IP6 redishostname2"
1634783768141,"2021-10-21 02:36:08,140 | INFO  | redisson-netty-17-7                                                          | o.r.c.pool.MasterConnectionPool - 2 connections initialized for redishostname2/IP6:6379"
1634783768218,"2021-10-21 02:36:08,217 | INFO  | redisson-netty-17-8                                                          | o.r.c.p.MasterPubSubConnectionPool - 1 connections initialized for redishostname2/IP6:6379"
1634783779207,"2021-10-21 02:36:19,207 | INFO  | redisson-netty-5-9                                                           | o.redisson.connection.DNSMonitor - Detected DNS change. Master rediss://redishostname2:6379 has changed ip from IP5 to IP7"
1634783779245,"2021-10-21 02:36:19,245 | ERROR | redisson-netty-5-10                                                          | o.r.connection.SingleEntry - Unable to change master from: redishostname2/IP5:6379 to: rediss://redishostname2:6379"
1634783779245,org.redisson.client.RedisConnectionException: Unable to connect to Redis server: redishostname2/IP7:6379
1634783779245,	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:158)
1634783779245,	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
1634783779245,	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
1634783779245,	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:328)
1634783779245,	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:294)
1634783779245,	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
1634783779245,	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
1634783779245,	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
1634783779245,	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:251)
1634783779245,	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
1634783779245,	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
1634783779245,	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
1634783779245,	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
1634783779245,	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
1634783779245,	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
1634783779245,	at java.base/java.lang.Thread.run(Unknown Source)
1634783779245,Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: redishostname2/IP7:6379
1634783779245,Caused by: java.net.ConnectException: Connection refused
1634783779245,	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
1634783779245,	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
1634783779245,	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
1634783779245,	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
1634783779245,	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
1634783779245,	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
1634783779245,	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
1634783779245,	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
1634783779245,	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
1634783779245,	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
1634783779245,	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by mrniko** [comment]
It's a network problem. Check if application may connect to this host.

**Comment by lokeshg98** [comment]
Yes, Application is able to connect to the host. Before the Ip address change, Application was able to connect to the host and could fetch the data. After Ip address changes, it is not able to connect automatically. When we restart the Application , it is able to connect to Redis again successfully.
