### ISSUE TITLE
Redisson reconnection issue | version : 3.16.3

### ISSUE THREAD

**Issue by arorashivam** [redisson/redisson#3924]
Please find the following series of events that bring the redisson connection to dead state

1. Redis server goes down, please find the logs : 
```
at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:255)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] - [redisson-timer-4-1] - [requestId: ] - o.r.c.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0xd51b2a0e, L:/**:** - R:<host>/<ip>:<port>]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://<host>:<port>]
```
2. After this redisson detects the DNS change, the switch to new master couldn't happen because we have disabled connection to public IP using Azure's private redis endpoint feature. Please find the logs : 

```
[INFO] - [redisson-netty-2-21] - [requestId: ] - org.redisson.connection.DNSMonitor - Detected DNS change. Master rediss://<host>:<port> has changed ip from ip1 to ip2
[ERROR] - [redisson-netty-2-22] - [requestId: ] - org.redisson.connection.SingleEntry - Unable to change master from: <host>/<ip1>:<port> to: rediss://<host>:<port>
org.redisson.client.RedisConnectionException: Unable to connect to Redis server: <host>/<ip2>:<port>
 	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:158)
 	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
 	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
 	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:310)
 	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$2(ConnectionPool.java:276)
 	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
 	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
 	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:251)
 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: <host>/<ip2>:<port>
 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
 	... 7 common frames omitted
```

Now after this, we keep seeing such logs where the DNS monitor looks for the change in IP and throws error that it is not able to connect even though the redis server becomes healthy again. 

Now if we hit the service we get (though, now the redis server is up): 

```
  java.lang.NullPointerException: null
 	at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:179)
 	at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:234)
 	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:41)
 	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:488)
 	at org.redisson.connection.SingleEntry.connectionReadOp(SingleEntry.java:42)
 	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:549)
 	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:555)
 	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:121)
 	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:581)
 	at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:343)
 	at org.redisson.RedissonMap.getOperationAsync(RedissonMap.java:1168)
 	at org.redisson.RedissonMap.getAsync(RedissonMap.java:1175)
 	at org.redisson.RedissonMap.get(RedissonMap.java:659)
 	at org.redisson.spring.cache.RedissonCache.get(RedissonCache.java:77)
 	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:73)
 	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:571)
 	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:536)
 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:402)
 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
 	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 	at java.base/java.lang.Thread.run(Thread.java:829)
```

Please find the following connection config : 
```
        singleServerConfig.setAddress("rediss://<host>:<port>")
                .setDatabase(0)
                .setConnectTimeout(10000)
                .setConnectionPoolSize(64)
                .setConnectionMinimumIdleSize(24);
```
Redisson version : 3.16.3

Also, If we restart the service it will be able to connect properly.

Edit : Issue is somewhat similar to : https://github.com/redisson/redisson/issues/2996

**Comment by arorashivam** [comment]
@mrniko by the time the issue is being addressed is there any work around for the given scenario? 

Also it would be great if you could highlight, how the fix would look like for the raised concern? 

will it be gracefully handling the issue of "not able to acquire connection?" instead of NPE 
OR 
The fix would be to attempt for re-connection after such failure? (primarily expecting this)

And it would be generous of you, If you could also highlight the ETA for the release of 3.16.5 ?

**Comment by mrniko** [comment]
Fixed. 

I'm afraid there is no work around for this fix. ETA is current month.

**Comment by arorashivam** [comment]
@mrniko can we bind any hook/callback listening to redisson client logging for the connection issues and on such an event refresh the redisson bean?
Is there any way we can add such a callback?

**Comment by arorashivam** [comment]
@mrniko Hey, is there any update on when is this bug fix will be released? Thanks

**Comment by mrniko** [comment]
it has already been released

**Comment by arorashivam** [comment]
Thanks @mrniko. Just to confirm this is released as part of `3.16.4`?

**Comment by mrniko** [comment]
It's part of 3.16.5

**Comment by arorashivam** [comment]
@mrniko Okay thanks again. Just one last question, I can see the latest release is `3.16.4` when is `3.16.5` getting released?

**Comment by arorashivam** [comment]
@mrniko Unfortunately I am still getting errors when performing the same exercise. However this time rather than getting NullPointerException, I keep getting the following logs : 
`2021-12-16 10:52:11,217 - [ERROR] - [redisson-netty-2-7] - [requestId: ] - org.redisson.connection.DNSMonitor - Unable to resolve ***
java.net.UnknownHostException: failed to resolve ‘***’ after 4 queries 
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1046) 
at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:999) 
at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:417) 
at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:970) 
at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:65) 
at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:470) 
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) 
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) 
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) 
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) 
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) 
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) 
at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:201) 
at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:193) 
at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1301) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) 
at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) 
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) 
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) 
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
at java.base/java.lang.Thread.run(Thread.java:829) `

**Comment by mrniko** [comment]
Please check your dns server. You can also turn on netty logs to check which address is used.

**Comment by arorashivam** [comment]
DNS server is resolving the correct IP
`telnet *** 6380`
and it got connected successfully to the privateLink ip.

**Comment by mrniko** [comment]
please turn on netty logs and check if netty uses correct dns servers.

**Comment by arorashivam** [comment]
@mrniko Okay does setting the log level to TRACE would print the internal logging of netty as well?

**Comment by cm175036** [comment]
Has this issue been resolved? Still facing connection issues using redisson 3.16.8

**Comment by mrniko** [comment]
@cm175036 

Please update netty to the latest version.

**Comment by pcc-grewal** [comment]
Hi @mrniko, I am from same team as @cm175036 and even after updating netty to latest version (4.1.74.Final) while using redisson (3.16.8, excluded netty-codec from this dependency to pick the 4.1.74.Final), still same issue occurring. 

there is this info INFO o.r.c.DNSMonitor - Detected DNS change. Master .... IP xxxx changed to IP yyyy
then error 
ERROR o.r.c.SingleEntry - Unable to change master from: xxxx to <dnsName>.redis.redis.cache.windows.net:6380

Caused by org.redisson.client.RedisConnectionException: Unable to connect to Redis server: yyyyy

Caused by: java.util.concurrent.CompletionException: java.nio.channels.ClosedChannelException


Caused by: java.nio.channels.ClosedChannelException: null

**Comment by mrniko** [comment]
@pcc-grewal 

Try to set dnsMonitoringInterval = -1

**Comment by maranza** [comment]
Greetings.

I am facing the same issue, Can i have an example of how to interact with netty? I see above suggestions that we should turn on logs for netty, I would specifically like to configure proxy on Netty. Please Assist.
