### ISSUE TITLE
j.l.IllegalArgumentException: port out of range:-1 with Sentinel setup

### ISSUE THREAD

**Issue by kshchepanovskyi** [redisson/redisson#3932]
I noticed weird warnings in our logs during investigation of one of issues:

```
level | WARN
logger_name | io.netty.util.concurrent.DefaultPromise
message | An exception was thrown by org.redisson.misc.RedissonPromise$Lambda$1511/0x0000000801836b20.operationComplete()

j.l.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:152)
	at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:263)
	at o.r.c.MasterSlaveConnectionManager.resolveIP(MasterSlaveConnectionManager.java:706)
	at o.r.c.MasterSlaveConnectionManager.resolveIP(MasterSlaveConnectionManager.java:695)
	at o.r.c.SentinelConnectionManager.resolveIP(SentinelConnectionManager.java:617)
	at o.r.c.SentinelConnectionManager.lambda$checkSlavesChange$20(SentinelConnectionManager.java:460)
	at o.r.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at i.n.u.c.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at i.n.u.c.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at i.n.u.c.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at i.n.u.c.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at i.n.u.c.DefaultPromise.setValue0(DefaultPromise.java:616)
	at i.n.u.c.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at i.n.u.c.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at o.r.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at o.r.c.handler.CommandDecoder.completeResponse(CommandDecoder.java:460)
	at o.r.c.handler.CommandDecoder.handleResult(CommandDecoder.java:454)
	at o.r.c.handler.CommandDecoder.decodeResult(CommandDecoder.java:443)
	at o.r.c.handler.CommandDecoder.decodeList(CommandDecoder.java:437)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:392)
	at o.r.c.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at i.n.h.c.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at i.n.h.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at i.n.h.c.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at i.n.c.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	... 12 frames truncated
```

Right before this warning, trace logs:

```
channel: [id: 0x786eaac2, L:/10.0.41.255:43594 - R:10.0.31.235/10.0.31.235:26379] message: *3
$8
SENTINEL
$9
SENTINELS
$8
mymaster
```

```
reply: *2
*28
$4
name
$40
5f4ff5b1f3024ce375ab027ac24adb717305f02c
$2
ip
$10
10.0.56.43
$4
port
$5
26379
$5
runid
$40
5f4ff5b1f3024ce375ab027ac24adb717305f02c
$5
flags
$8
sentinel
$21
link-pending-commands
$1
0
$13
link-refcount
$1
1
$14
last-ping-sent
$1
0
$18
last-ok-ping-reply
$3
718
$15
last-ping-reply
$3
718
$23
down-after-milliseconds
$5
60000
$18
last-hello-message
$2
56
$12
voted-leader
$1
?
$18
voted-leader-epoch
$1
0
*28
$4
name
$40
6b28db582bd8af66c1e0ddbcc9afcce2daba4354
$2
ip
$10
10.0.60.42
$4
port
$5
26379
$5
runid
$40
6b28db582bd8af66c1e0ddbcc9afcce2daba4354
$5
flags
$8
sentinel
$21
link-pending-commands
$1
0
$13
link-refcount
$1
1
$14
last-ping-sent
$1
0
$18
last-ok-ping-reply
$3
316
$15
last-ping-reply
$3
316
$23
down-after-milliseconds
$5
60000
$18
last-hello-message
$3
426
$12
voted-leader
$1
?
$18
voted-leader-epoch
$1
7
, channel: [id: 0x786eaac2, L:/10.0.41.255:43594 - R:10.0.31.235/10.0.31.235:26379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@34d3a715(incomplete)], command=(SENTINEL SENTINELS), params=[mymaster], codec=org.redisson.client.codec.StringCodec]
```

```
reply: *2
$11
10.0.31.235
$4
6379
*5
*44
$4
name
$16
10.0.58.188:6379
$2
ip
$11
10.0.58.188
$4
port
$4
6379
$5
runid
$0

$5
flags
$12
s_down,slave
$21
link-pending-commands
$3
103
$13
link-refcount
$1
1
$14
last-ping-sent
$9
167589089
$18
last-ok-ping-reply
$9
167589089
$15
last-ping-reply
$9
167589089
$11
s-down-time
$9
167529071
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$1
0
$13
role-reported
$5
slave
$18
role-reported-time
$9
167589089
$21
master-link-down-time
$1
0
$18
master-link-status
$3
err
$11
master-host
$1
?
$11
master-port
$1
0
$14
slave-priority
$3
100
$17
slave-repl-offset
$1
0
$17
replica-announced
$1
1
*42
$4
name
$15
10.0.60.42:6379
$2
ip
$10
10.0.60.42
$4
port
$4
6379
$5
runid
$40
38ac99a2a058225db080405b2701473967fa0a8c
$5
flags
$5
slave
$21
link-pending-commands
$1
0
$13
link-refcount
$1
1
$14
last-ping-sent
$1
0
$18
last-ok-ping-reply
$3
316
$15
last-ping-reply
$3
316
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$4
9649
$13
role-reported
$5
slave
$18
role-reported-time
$9
167578985
$21
master-link-down-time
$1
0
$18
master-link-status
$2
ok
$11
master-host
$11
10.0.31.235
$11
master-port
$4
6379
$14
slave-priority
$3
100
$17
slave-repl-offset
$11
12625586437
$17
replica-announced
$1
1
*44
$4
name
$15
10.0.36.94:6379
$2
ip
$10
10.0.36.94
$4
port
$4
6379
$5
runid
$40
5de7475daacc09beb036ecbc0ced560a3db62b4b
$5
flags
$12
s_down,slave
$21
link-pending-commands
$2
60
$13
link-refcount
$1
1
$14
last-ping-sent
$9
167014504
$18
last-ok-ping-reply
$9
167015344
$15
last-ping-reply
$9
167015344
$11
s-down-time
$9
166954476
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$9
167015560
$13
role-reported
$5
slave
$18
role-reported-time
$9
167589089
$21
master-link-down-time
$1
0
$18
master-link-status
$2
ok
$11
master-host
$11
10.0.31.235
$11
master-port
$4
6379
$14
slave-priority
$3
100
$17
slave-repl-offset
$10
9241323106
$17
replica-announced
$1
1
*42
$4
name
$15
10.0.56.43:6379
$2
ip
$10
10.0.56.43
$4
port
$4
6379
$5
runid
$40
1ccbc44a900dfea4c23c8f85cca350c75f1c335a
$5
flags
$5
slave
$21
link-pending-commands
$1
0
$13
link-refcount
$1
1
$14
last-ping-sent
$1
0
$18
last-ok-ping-reply
$3
316
$15
last-ping-reply
$3
316
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$4
9649
$13
role-reported
$5
slave
$18
role-reported-time
$9
166976648
$21
master-link-down-time
$1
0
$18
master-link-status
$2
ok
$11
master-host
$11
10.0.31.235
$11
master-port
$4
6379
$14
slave-priority
$3
100
$17
slave-repl-offset
$11
12625586437
$17
replica-announced
$1
1
*44
$4
name
$16
10.0.14.221:6379
$2
ip
$11
10.0.14.221
$4
port
$4
6379
$5
runid
$0

$5
flags
$25
s_down,slave,disconnected
$21
link-pending-commands
$1
3
$13
link-refcount
$1
1
$14
last-ping-sent
$9
167589089
$18
last-ok-ping-reply
$9
167589089
$15
last-ping-reply
$9
167589089
$11
s-down-time
$9
167529071
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$1
0
$13
role-reported
$5
slave
$18
role-reported-time
$9
167589089
$21
master-link-down-time
$1
0
$18
master-link-status
$3
err
$11
master-host
$1
?
$11
master-port
$1
0
$14
slave-priority
$3
100
$17
slave-repl-offset
$1
0
$17
replica-announced
$1
1
, channel: [id: 0x786eaac2, L:/10.0.41.255:43594 - R:10.0.31.235/10.0.31.235:26379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@25919dc9(incomplete)], command=(SENTINEL SLAVES), params=[mymaster], codec=org.redisson.client.codec.StringCodec]
```

```
reply: *2
$11
10.0.31.235
$4
6379
*5
*44
$4
name
$16
10.0.58.188:6379
$2
ip
$11
10.0.58.188
$4
port
$4
6379
$5
runid
$0

$5
flags
$12
s_down,slave
$21
link-pending-commands
$3
103
$13
link-refcount
$1
1
$14
last-ping-sent
$9
167589089
$18
last-ok-ping-reply
$9
167589089
$15
last-ping-reply
$9
167589089
$11
s-down-time
$9
167529071
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$1
0
$13
role-reported
$5
slave
$18
role-reported-time
$9
167589089
$21
master-link-down-time
$1
0
$18
master-link-status
$3
err
$11
master-host
$1
?
$11
master-port
$1
0
$14
slave-priority
$3
100
$17
slave-repl-offset
$1
0
$17
replica-announced
$1
1
*42
$4
name
$15
10.0.60.42:6379
$2
ip
$10
10.0.60.42
$4
port
$4
6379
$5
runid
$40
38ac99a2a058225db080405b2701473967fa0a8c
$5
flags
$5
slave
$21
link-pending-commands
$1
0
$13
link-refcount
$1
1
$14
last-ping-sent
$1
0
$18
last-ok-ping-reply
$3
316
$15
last-ping-reply
$3
316
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$4
9649
$13
role-reported
$5
slave
$18
role-reported-time
$9
167578985
$21
master-link-down-time
$1
0
$18
master-link-status
$2
ok
$11
master-host
$11
10.0.31.235
$11
master-port
$4
6379
$14
slave-priority
$3
100
$17
slave-repl-offset
$11
12625586437
$17
replica-announced
$1
1
*44
$4
name
$15
10.0.36.94:6379
$2
ip
$10
10.0.36.94
$4
port
$4
6379
$5
runid
$40
5de7475daacc09beb036ecbc0ced560a3db62b4b
$5
flags
$12
s_down,slave
$21
link-pending-commands
$2
60
$13
link-refcount
$1
1
$14
last-ping-sent
$9
167014504
$18
last-ok-ping-reply
$9
167015344
$15
last-ping-reply
$9
167015344
$11
s-down-time
$9
166954476
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$9
167015560
$13
role-reported
$5
slave
$18
role-reported-time
$9
167589089
$21
master-link-down-time
$1
0
$18
master-link-status
$2
ok
$11
master-host
$11
10.0.31.235
$11
master-port
$4
6379
$14
slave-priority
$3
100
$17
slave-repl-offset
$10
9241323106
$17
replica-announced
$1
1
*42
$4
name
$15
10.0.56.43:6379
$2
ip
$10
10.0.56.43
$4
port
$4
6379
$5
runid
$40
1ccbc44a900dfea4c23c8f85cca350c75f1c335a
$5
flags
$5
slave
$21
link-pending-commands
$1
0
$13
link-refcount
$1
1
$14
last-ping-sent
$1
0
$18
last-ok-ping-reply
$3
316
$15
last-ping-reply
$3
316
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$4
9649
$13
role-reported
$5
slave
$18
role-reported-time
$9
166976648
$21
master-link-down-time
$1
0
$18
master-link-status
$2
ok
$11
master-host
$11
10.0.31.235
$11
master-port
$4
6379
$14
slave-priority
$3
100
$17
slave-repl-offset
$11
12625586437
$17
replica-announced
$1
1
*44
$4
name
$16
10.0.14.221:6379
$2
ip
$11
10.0.14.221
$4
port
$4
6379
$5
runid
$0

$5
flags
$25
s_down,slave,disconnected
$21
link-pending-commands
$1
3
$13
link-refcount
$1
1
$14
last-ping-sent
$9
167589089
$18
last-ok-ping-reply
$9
167589089
$15
last-ping-reply
$9
167589089
$11
s-down-time
$9
167529071
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$1
0
$13
role-reported
$5
slave
$18
role-reported-time
$9
167589089
$21
master-link-down-time
$1
0
$18
master-link-status
$3
err
$11
master-host
$1
?
$11
master-port
$1
0
$14
slave-priority
$3
100
$17
slave-repl-offset
$1
0
$17
replica-announced
$1
1
, channel: [id: 0x786eaac2, L:/10.0.41.255:43594 - R:10.0.31.235/10.0.31.235:26379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@65cf84fb(incomplete)], command=(SENTINEL GET-MASTER-ADDR-BY-NAME), params=[mymaster], codec=org.redisson.client.codec.StringCodec]
```

**Redis version**
6.2.5

**Redisson version**
3.16.4

**Redisson configuration**
```
Using redis sentinel configuration: mater=mymaster, nodes=[redis://redis-sentinel-node-0.redis-sentinel-headless:26379, redis://redis-sentinel-node-1.redis-sentinel-headless:26379, redis://redis-sentinel-node-2.redis-sentinel-headless:26379]
```

**Comment by mrniko** [comment]
I see the reason. Your config returns master-port = 0 and master-host = ?.

**Comment by mrniko** [comment]
Fixed! Thanks for report.

**Comment by ghollies** [comment]
@mrniko we are also running into this issue when a master is killed and failover occurs, the disconnected slave reports`?` as host and `-1` as port, preventing the async updateSlave from working, and the client is broken until we restart the app.

Do you have an ETA as to when this fix will be in a release?

**Comment by mrniko** [comment]
@ghollies 

During this month.
