### ISSUE TITLE
IdleConnectionWatcher closes active PubSubConnections

### ISSUE THREAD

**Issue by SplotyCode** [redisson/redisson#3957]
We have a Problem were subscriptions seem to be removed (still in PublishSubscribeService#name2PubSubConnection but not showing on redis server itself)
**Expected behavior**
PubSubConnections should not be closed

**Actual behavior**
PubSubConnections get closed even with multiple active subscriptions that don't get reconnected from watchdog as the RedisConnection was marked as closed via setClosed(true)
```	at org.redisson.client.RedisConnection.setClosed(RedisConnection.java:304) ~[?:?]
	at org.redisson.client.RedisConnection.closeAsync(RedisConnection.java:353) ~[?:?]
	at org.redisson.connection.IdleConnectionWatcher.lambda$new$1(IdleConnectionWatcher.java:77) ~[?:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [our-jar]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176) [our-jar]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [our-jar]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [our-jar]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [our-jar]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [our-jar]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [our-jar]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [our-jar]
	at java.base/java.lang.Thread.run(Thread.java:832) [?:?]
```
**Steps to reproduce or test case**
Not yet but maybe if you could point us in a direction
**Redis version**
5.0.3
**Redisson version**
3.16.4
**Redisson configuration**
Single node with 
useThreadClassLoader=: alse
nettyThreads: 4
subscriptionConnectionPoolSize: 12
connectionMinimumIdleSize: 6

**Comment by mrniko** [comment]
Fixed! Thanks for report
