### ISSUE TITLE
Mybatis RedissonCache cannot read config file `redisson.yaml`

### ISSUE THREAD

**Issue by gcdd1993** [redisson/redisson#3959]
**Expected behavior**

**Actual behavior**
throw error
```bash
Caused by: java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:167) ~[na:na]
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:na]
	at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:174) ~[redisson-3.16.4.jar:3.16.4]
	at org.redisson.config.Config.fromYAML(Config.java:632) ~[redisson-3.16.4.jar:3.16.4]
	at org.redisson.mybatis.RedissonCache.setRedissonConfig(RedissonCache.java:106) ~[redisson-mybatis-3.16.4.jar:3.16.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:180) ~[mybatis-3.5.7.jar:3.5.7]
	... 63 common frames omitted
```

**Steps to reproduce or test case**
add StudentMapper.java
```java
@Mapper
public interface StudentMapper extends BaseMapper<StudentPo> {
    @Override
    StudentPo selectById(@Param("id") Serializable id);
}
```
add StudentMapper.xml
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<mapper namespace="io.github.gcdd1993.mybatis.cache.mapper.StudentMapper">
    <cache type="org.redisson.mybatis.RedissonCache">
        <property name="timeToLive" value="200000"/>
        <property name="maxIdleTime" value="100000"/>
        <property name="maxSize" value="100000"/>
        <property name="redissonConfig" value="redisson.yaml"/>
    </cache>
    <select id="selectById" resultType="io.github.gcdd1993.mybatis.cache.model.StudentPo">
        select *
        from student
        where id = #{id}
    </select>
</mapper>
```
add redisson.yaml at `src/main/resources/redisson.yaml`
```yaml
singleServerConfig:
  address: "redis://127.0.0.1:16379"
```

at `org.redisson.mybatis.RedissonCache#105`, i found
```java
InputStream is = getClass().getResourceAsStream(config);
```

is it should be `InputStream is = getClass().getClassLoader().getResourceAsStream(config);`?

**Redis version**
6.2.6

**Redisson version**
3.16.4

**Redisson configuration**
`src/main/resources/redisson.yaml`
```yaml
singleServerConfig:
  address: "redis://127.0.0.1:16379"
```

**Comment by gcdd1993** [comment]
use `/redisson.yaml` instead of `redisson.yaml`, it works

**Comment by mrniko** [comment]
Fixed! Thanks for report
