### ISSUE TITLE
java.lang.IllegalArgumentException: Can't parse packet

### ISSUE THREAD

**Issue by b2k4j** [redisson/redisson#3962]
I got such an error when I try to clear the RedissonLocalCachedMap.
`Redisson version:3.16.3
`
```
2021-11-19 11:45:11:912 [redisson-netty-2-6] TRACE org.redisson.client.handler.CommandPubSubDecoder.decode:134 - reply: *3
$7
message
$43
{bdcampus:bdcampus-bind-fullKeyCache}:topic
$115
{"@class":"org.redisson.cache.LocalCachedMapClear","releaseSemaphore":false,"requestId":"cB+BvVX2HzwIsdIW11VcsA=="}
, channel: [id: 0x00eb8b6e, L:/100.66.209.243:49952 - R:redis-cluster/100.66.209.208:6379], command: null
2021-11-19 11:45:11:912 [redisson-netty-2-3] DEBUG org.redisson.command.RedisExecutor.releaseConnection:536 - connection released for command (EVALSHA) and params [34cf7f8699dd099ce2a9aa94e01d4942168c7a3f, 3, bdcampus:bdcampus-bind-fullKeyCache, {bdcampus:bdcampus-bind-fullKeyCache}:topic, redisson__cache_updates_log:{bdcampus:bdcampus-bind-fullKeyCache}, PooledUnsafeDirectByteBuf(ridx: 0, widx: 115, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 60, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@1829243899 [redisClient=[addr=redis://redis-cluster:6379], channel=[id: 0xc6fc6d40, L:/100.66.209.243:49954 - R:redis-cluster/100.66.209.208:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@c12e552(success: true)], command=(EVALSHA), params=[34cf7f8699dd099ce2a9aa94e01d4942168c7a3f, 3, bdcampus:bdcampus-bind-fullKeyCache, {bdcampus:bdcampus-bind-fullKeyCache}:topic, redisson__cache_updates_log:{bdcampus:bdcampus-bind-fullKeyCache}, PooledUnsafeDirectByteBuf(ridx: 0, widx: 115, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 22, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 60, cap: 256)], codec=org.redisson.client.codec.LongCodec], usage=0]
2021-11-19 11:45:11:913 [redisson-netty-2-6] ERROR org.redisson.client.handler.CommandPubSubDecoder.decodeCommand:88 - Unable to decode data. channel: [id: 0x00eb8b6e, L:/100.66.209.243:49952 - R:redis-cluster/100.66.209.208:6379], reply: ReplayingDecoderByteBuf(ridx=190, widx=190)
java.lang.IllegalArgumentException: Can't parse packet
	at org.redisson.cache.LocalCachedMessageCodec$1.decode(LocalCachedMessageCodec.java:112)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:383)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:427)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:84)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-11-19 11:45:11:913 [redisson-netty-2-6] ERROR org.redisson.client.handler.ErrorsLoggingHandler.exceptionCaught:47 - Exception occured. Channel: [id: 0x00eb8b6e, L:/100.66.209.243:49952 - R:redis-cluster/100.66.209.208:6379]
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Can't parse packet
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Can't parse packet
	at org.redisson.cache.LocalCachedMessageCodec$1.decode(LocalCachedMessageCodec.java:112)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:383)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:427)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:84)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 common frames omitted
```

**Comment by mrniko** [comment]
Unable to reproduce it. Below is my code:

```java
        RLocalCachedMap<Object, Object> localCachedMap = redisson.getLocalCachedMap("udi-test",
                        LocalCachedMapOptions.defaults());

        localCachedMap.put("1", "2");
        localCachedMap.put("3", "4");

        localCachedMap.clear();
```
