### ISSUE TITLE
Cannot inject dependencies into runnable scheduled task

### ISSUE THREAD

**Issue by jeff-weng** [redisson/redisson#3963]
Hi, I am having trouble injecting beans into scheduled tasks. I am able to connect with redis to do other things so I don't believe it is a configuration issue.  ​I saw someone else had posted a similar issue but it seems like it got closed without being resolved: https://github.com/redisson/redisson/issues/2318

Essentially, I am trying to schedule a tasks on a distributed server to send a reminder to a user after x amount of time. In order to do this, I need to inject a bean to be able to get the current state of the user at the time the task is executed and another bean to be able to send the notification. However, I am running into the same Null Pointer and Not Serializable exceptions as from the issue above.

I have also tried another approach where I register the task to a RRemoteService so when it tries to execute, it will call a server-side RRemoteService that has the dependencies autowired. However, when I do that, it gives an IllegalArgumentException: Unable to serialize lambda. 

I'm pretty stuck on what to do and I was wondering if someone could help provide guidance on if this would even be possible with Redisson or if I should try to find another solution? It would be helpful if someone could provide an example of an @Autowired service being injected into a task and it working.

**Comment by mrniko** [comment]
Unable to reproduce it. Below is the test.

Run this class first and next one second.

```java
public class RedissonExecutorServiceSpringTest {

    private static final String EXECUTOR_NAME = "spring_test";

    @Configuration
    @ComponentScan
    public static class Application {

        @Bean(destroyMethod = "shutdown")
        RedissonNode redissonNode(BeanFactory beanFactory) {
            Config config = new Config();
            config.useSingleServer()
                    .setAddress("redis://127.0.0.1:6379");
            RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
            nodeConfig.setExecutorServiceWorkers(Collections.singletonMap(EXECUTOR_NAME, 1));
            nodeConfig.setBeanFactory(beanFactory);
            RedissonNode node = RedissonNode.create(nodeConfig);
            node.start();
            return node;
        }

    }

    private static AnnotationConfigApplicationContext context;
    
    @BeforeAll
    public static void beforeTest() throws FailedToStartRedisException, IOException, InterruptedException {
        context = new AnnotationConfigApplicationContext(Application.class);
    }

    @AfterAll
    public static void afterTest() {
        context.close();
    }

    @Test
    public void testRunnable() throws InterruptedException {
        Thread.sleep(5000000);
    }

}
```

```java
public class RedissonExecutorServiceSpringTest2 {

    public static class SampleRunnable implements Runnable, Serializable {

        @Autowired
        private SampleBean bean;
        
        @RInject
        private RedissonClient redisson;
        
        public SampleRunnable() {
        }

        @Override
        public void run() {
            String res = bean.myMethod("runnable");
            redisson.getBucket("result").set(res);
        }

    }
    
    public static class SampleCallable implements Callable<String>, Serializable {

        @Autowired
        private SampleBean bean;
        
        public SampleCallable() {
        }

        @Override
        public String call() throws Exception {
            return bean.myMethod("callable");
        }
        
    }

    @Service
    public static class SampleBean {

        public String myMethod(String key) {
            return "hello " + key;
        }

    }

    private static final String EXECUTOR_NAME = "spring_test";

    @Test
    public void testRunnable() throws InterruptedException {
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379");
        RedissonClient redisson = Redisson.create(config);
        redisson.getExecutorService(EXECUTOR_NAME).execute(new SampleRunnable());
        
        Thread.sleep(500);

        assertThat(redisson.getBucket("result").get()).isEqualTo("hello runnable");
    }

    @Test
    public void testCallable() throws InterruptedException {
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379");
        RedissonClient redisson = Redisson.create(config);
        RExecutorFuture<String> future = redisson.getExecutorService(EXECUTOR_NAME).submit(new SampleCallable());
        
        Thread.sleep(500);

        assertThat(future.sync().getNow()).isEqualTo("hello callable");
    }
    
}
```

**Comment by jeff-weng** [comment]
Thanks for the example, I'll try this out

**Comment by jeff-weng** [comment]
Using this method, how do I use the RScheduledExecutorService ? My config looks like the following:
`@Configuration
@ComponentScan
public class RedissonConfig {

    @Value("${spring.redis.host}")
    private String redisHost;

    @Bean(destroyMethod = "shutdown")
    RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer().setAddress(redisHost);
        return Redisson.create(config);
    }

    @Bean(destroyMethod = "shutdown")
    RedissonNode redissonNode(BeanFactory beanFactory) {
        Config config = new Config();
        config.useSingleServer().setAddress(redisHost);
        RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("scheduledTaskExecutor", 1));
        nodeConfig.setBeanFactory(beanFactory);
        RedissonNode node = RedissonNode.create(nodeConfig);
        node.start();
        return node;
    }
    
    @Bean(destroyMethod = "shutdown")
    RScheduledExecutorService executor(BeanFactory beanFactory, RedissonClient client) {
        WorkerOptions options = WorkerOptions.defaults()
                .workers(5)
                .beanFactory(beanFactory)
                .addListener((TaskStartedListener) taskId -> log.info("Scheduled task with taskId={} started", taskId))
                .addListener((TaskFailureListener) (taskId, exception) -> log.info("Scheduled task with taskId={} failed", taskId));
        RScheduledExecutorService executorService = client.getExecutorService("scheduledTaskExecutor");
        executorService.registerWorkers(options);
        return executorService;
    }
}
`

but I am getting `java.lang.IllegalArgumentException: java.io.NotSerializableException: org.springframework.scheduling.support.DelegatingErrorHandlingRunnable
	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:383)
	at org.redisson.RedissonExecutorService.scheduleWithFixedDelayAsync(RedissonExecutorService.java:1018)
	at org.redisson.RedissonExecutorService.scheduleWithFixedDelay(RedissonExecutorService.java:1008)
	at org.redisson.RedissonExecutorService.scheduleWithFixedDelay(RedissonExecutorService.java:54)
	at org.springframework.scheduling.concurrent.ConcurrentTaskScheduler.scheduleWithFixedDelay(ConcurrentTaskScheduler.java:254)
	at org.springframework.scheduling.config.ScheduledTaskRegistrar.scheduleFixedDelayTask(ScheduledTaskRegistrar.java:528)
	at org.springframework.scheduling.config.ScheduledTaskRegistrar.scheduleFixedDelayTask(ScheduledTaskRegistrar.java:502)
	at org.springframework.scheduling.config.ScheduledTaskRegistrar.scheduleTasks(ScheduledTaskRegistrar.java:379)
	at org.springframework.scheduling.config.ScheduledTaskRegistrar.afterPropertiesSet(ScheduledTaskRegistrar.java:349)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.finishRegistration(ScheduledAnnotationBeanPostProcessor.java:314)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:233)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.onApplicationEvent(ScheduledAnnotationBeanPostProcessor.java:105)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:426)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:943)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
`

**Comment by jeff-weng** [comment]
Is there a way to change the RedissonNodeConfig to set the executor as `RScheduledExecutorService`? I saw in a different example that we can create an RScheduledExecutorService as following:
```
        WorkerOptions options = WorkerOptions.defaults()
                .workers(5)
                .beanFactory(beanFactory)
                .addListener((TaskStartedListener) taskId -> log.info("Scheduled task with taskId={} started", taskId))
                .addListener((TaskFailureListener) (taskId, exception) -> log.info("Scheduled task with taskId={} failed", taskId));
        RScheduledExecutorService executorService = client.getExecutorService("scheduledTaskExecutor");
        executorService.registerWorkers(options);
```
However, I'm not too sure how to use RedissonNode and RScheduledExecutorService in tandem

**Comment by mrniko** [comment]
> Is there a way to change the RedissonNodeConfig to set the executor as RScheduledExecutorService?

What is the point of Redisson Node usage then? Redisson Node uses own ExecutorService to execute tasks.

**Comment by cloudgyb** [comment]
Run task throw exception：
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 18 common frames omitted

**Comment by newGaoXin** [comment]
@cloudgyb 
I also have this problem, which is caused by the introduction of spring-dev-tools. If you also use it in the project, try to set the dependent to runtime, and you can get the beans in the container normally after compiling and running.
If you want to run locally through idea, you can try to comment out the spring-dev-tools dependency
