### ISSUE TITLE
 SlaveConnectionPool no available Redis entries after Redis pod restart

### ISSUE THREAD

**Issue by ramprasad1996** [redisson/redisson#3983]
**Expected behaviour** : When the Redis pod(stateful set) restarts, the application should be able to reconnect to the redis pod automatically. 

**Actual behaviour** : When the Redis pod restarts, the application is unable to reconnect to Redis even after multiple retry attempts. I tried this in a single node setup. When Redis pod is brought down, another pod is spun up in few seconds. But the app is unable to reconnect automatically. After the app pod restart, it works fine. 

This is the exception thrown.
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: <host>/<ip> Disconnected hosts: [<host>/<ip>]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:216)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:275)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:503)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:549)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:572)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:124)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:254)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Redis version** : 6.2.3

**Redisson version** : 
Tried both 3.15.5 and 3.16.4 - Facing same issue in both

**Redisson configuration** : 
config.useReplicatedServers()
                .setReadMode(ReadMode.MASTER_SLAVE)
                .setScanInterval(masterScanInterval)
                .setPassword(redisPassword)
                .addNodeAddress(redisUrl.split(","))

Please let me know if there's any workaround for this other than the restart. Thanks

**Comment by mrniko** [comment]
Are ips changed after Redis restart? Can you share debug log for `org.redisson.connection.ReplicatedConnectionManager` class?

**Comment by ramprasad1996** [comment]
Hi @mrniko 
The ips are changed after Redis restart
Please find the logs
**During startup of app :**
26 Nov 2021 09:05:03,047  INFO [main]  ReplicatedConnectionManager:78 - redis://redis-0.redis.test.svc.cluster.local:6379 is the master
 26 Nov 2021 09:05:03,047  WARN [main]  ReplicatedConnectionManager:91 - ReadMode = MASTER_SLAVE, but slave nodes are not found! Please specify all nodes in replicated mode.
 26 Nov 2021 09:05:03,121  INFO [redisson-netty-5-23]  MasterPubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.224:6379
 26 Nov 2021 09:05:03,206  INFO [redisson-netty-5-23]  MasterConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.224:6379
 26 Nov 2021 09:05:03,246  INFO [redisson-netty-5-24]  PubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.224:6379
 26 Nov 2021 09:05:03,269  INFO [redisson-netty-5-10]  SlaveConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.224:6379
 
**After Redis restart**

26 Nov 2021 09:05:26,509 DEBUG [redisson-netty-2-11]  ReplicatedConnectionManager:124 - Current master: redis-0.redis.test.svc.cluster.local/10.244.216.224:6379
 26 Nov 2021 09:05:29,521 ERROR [redisson-timer-4-1]  ReplicatedConnectionManager:146 - Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://redis-0.redis.test.svc.cluster.local:6379]
 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://redis-0.redis.test.svc.cluster.local:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

26 Nov 2021 09:05:56,420 ERROR [redisson-timer-4-1]  PingConnectionHandler:77 - Unable to send PING command over channel: [id: 0x3334c7e4, L:/10.244.216.205:35428 - R:redis-0.redis.test.svc.cluster.local/10.244.216.224:6379]
 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://redis-0.redis.test.svc.cluster.local:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

26 Nov 2021 09:05:59,527 DEBUG [redisson-netty-2-18]  ReplicatedConnectionManager:124 - Current master: redis-0.redis.test.svc.cluster.local/10.244.216.224:6379
 26 Nov 2021 09:05:59,596  INFO [redisson-netty-2-26]  MasterPubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.238:6379
 26 Nov 2021 09:05:59,607 ERROR [redisson-netty-2-30]  LoadBalancerManager:127 - Can't find redis-0.redis.test.svc.cluster.local/10.244.216.238:6379 in slaves! Available slaves: [[addr=redis://redis-0.redis.test.svc.cluster.local:6379]]
 26 Nov 2021 09:05:59,618  INFO [redisson-netty-2-30]  MasterSlaveEntry:473 - master redis-0.redis.test.svc.cluster.local/10.244.216.224:6379 has changed to redis-0.redis.test.svc.cluster.local/10.244.216.238:6379
 26 Nov 2021 09:05:59,619  INFO [redisson-netty-2-30]  MasterConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.238:6379
 26 Nov 2021 09:06:03,239 ERROR [redisson-timer-7-1]  PingConnectionHandler:77 - Unable to send PING command over channel: [id: 0x4ce6e2ce, L:/10.244.216.205:36724 - R:redis-0.redis.test.svc.cluster.local/10.244.216.224:6379]
 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://redis-0.redis.test.svc.cluster.local:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
26 Nov 2021 09:06:06,343 DEBUG [redisson-netty-5-18]  ReplicatedConnectionManager:124 - Current master: redis-0.redis.test.svc.cluster.local/10.244.216.224:6379
 26 Nov 2021 09:06:06,389  INFO [redisson-netty-5-14]  MasterPubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.238:6379
 26 Nov 2021 09:06:06,408 ERROR [redisson-netty-5-31]  LoadBalancerManager:127 - Can't find redis-0.redis.test.svc.cluster.local/10.244.216.238:6379 in slaves! Available slaves: [[addr=redis://redis-0.redis.test.svc.cluster.local:6379]]
 26 Nov 2021 09:06:06,412  INFO [redisson-netty-5-31]  MasterSlaveEntry:473 - master redis-0.redis.test.svc.cluster.local/10.244.216.224:6379 has changed to redis-0.redis.test.svc.cluster.local/10.244.216.238:6379
 26 Nov 2021 09:06:06,413  INFO [redisson-netty-5-31]  MasterConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.238:6379

**Comment by mrniko** [comment]
Can you try version attached? It should output exception happening during master failover.

[redisson-3.16.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7608440/redisson-3.16.5-SNAPSHOT.jar.zip)

**Comment by ramprasad1996** [comment]
Hi @mrniko  , 

I tested by replacing the latest jar and below are the logs. I could not find any difference between the previous logs. 

**During startup :** 

 29 Nov 2021 07:42:57,251  INFO [main]  Version:41 - Redisson 3.16.5.SNAPSHOT
 29 Nov 2021 07:42:58,050  INFO [main]  ReplicatedConnectionManager:82 - redis://redis-0.redis.test.svc.cluster.local:6379 is the master
 29 Nov 2021 07:42:58,050  WARN [main]  ReplicatedConnectionManager:95 - ReadMode = MASTER_SLAVE, but slave nodes are not found! Please specify all nodes in replicated mode.
 29 Nov 2021 07:42:58,312  INFO [redisson-netty-2-9]  MasterPubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.249:6379
 29 Nov 2021 07:42:58,364  INFO [redisson-netty-2-23]  MasterConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.249:6379
 29 Nov 2021 07:42:58,420  INFO [redisson-netty-2-23]  PubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.249:6379
 29 Nov 2021 07:42:58,459  INFO [redisson-netty-2-8]  SlaveConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.249:6379

**After Redis pod restart :**

29 Nov 2021 07:43:31,573 ERROR [redisson-timer-4-1]  ReplicatedConnectionManager:173 - Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://redis-0.redis.test.svc.cluster.local:6379]
 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://redis-0.redis.test.svc.cluster.local:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

29 Nov 2021 07:43:58,374 ERROR [redisson-timer-4-1]  PingConnectionHandler:77 - Unable to send PING command over channel: [id: 0x28b422d6, L:/10.244.216.250:53838 - R:redis-0.redis.test.svc.cluster.local/10.244.216.249:6379]
 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://redis-0.redis.test.svc.cluster.local:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

29 Nov 2021 07:44:01,693  INFO [redisson-netty-2-23]  MasterPubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.251:6379
 29 Nov 2021 07:44:01,721 ERROR [redisson-netty-2-8]  LoadBalancerManager:127 - Can't find redis-0.redis.test.svc.cluster.local/10.244.216.251:6379 in slaves! Available slaves: [[addr=redis://redis-0.redis.test.svc.cluster.local:6379]]
 29 Nov 2021 07:44:01,723  INFO [redisson-netty-2-8]  MasterSlaveEntry:473 - master redis-0.redis.test.svc.cluster.local/10.244.216.249:6379 has changed to redis-0.redis.test.svc.cluster.local/10.244.216.251:6379
 29 Nov 2021 07:44:01,723  INFO [redisson-netty-2-8]  MasterConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.251:6379
 29 Nov 2021 07:44:05,667  INFO [qtp1008789974-49]  QueueMetrics:53 - Total queue count is 0
 29 Nov 2021 07:44:05,670  INFO [qtp1008789974-49]  QueueMetrics:73 - number of metric samples in queue_count_by_apiid gauge is 0
 29 Nov 2021 07:44:06,734  INFO [redisson-netty-5-18]  MasterPubSubConnectionPool:166 - 1 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.251:6379
 29 Nov 2021 07:44:06,740 ERROR [redisson-netty-5-4]  LoadBalancerManager:127 - Can't find redis-0.redis.test.svc.cluster.local/10.244.216.251:6379 in slaves! Available slaves: [[addr=redis://redis-0.redis.test.svc.cluster.local:6379]]
 29 Nov 2021 07:44:06,741  INFO [redisson-netty-5-4]  MasterSlaveEntry:473 - master redis-0.redis.test.svc.cluster.local/10.244.216.249:6379 has changed to redis-0.redis.test.svc.cluster.local/10.244.216.251:6379
 29 Nov 2021 07:44:06,742  INFO [redisson-netty-5-4]  MasterConnectionPool:166 - 24 connections initialized for redis-0.redis.test.svc.cluster.local/10.244.216.251:6379
 29 Nov 2021 07:44:12,693 ERROR [exclude-request-reader]  TestRedisCacheReadWriterImpl:154 - Error while readKeyListByGivenBucketName from cache : {} 
 org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: redis-0.redis.test.svc.cluster.local/10.244.216.251:6379 Disconnected hosts: [redis-0.redis.test.svc.cluster.local/10.244.216.249:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:216)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:275)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:503)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:549)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:572)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:124)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:254)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

29 Nov 2021 07:44:31,674 DEBUG [redisson-netty-2-10]  ReplicatedConnectionManager:184 - Current master redis-0.redis.test.svc.cluster.local/10.244.216.251:6379 unchanged
29 Nov 2021 07:44:36,737 DEBUG [redisson-netty-5-13]  ReplicatedConnectionManager:184 - Current master redis-0.redis.test.svc.cluster.local/10.244.216.251:6379 unchanged

**Comment by mrniko** [comment]
Hi @ramprasad1996,

Thanks for testing.
Here is another version.

[redisson-3.16.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7616619/redisson-3.16.5-SNAPSHOT.jar.zip)

**Comment by ramprasad1996** [comment]
Thank you @mrniko, this is working ! 
When would this version be released ?

**Comment by mrniko** [comment]
During next week.

Fixed!

**Comment by hbprotoss** [comment]
@mrniko Could you please explain how bad things happened before?
