### ISSUE TITLE
Stuck on joining HashedWheelTimer worker thread when shutting down

### ISSUE THREAD

**Issue by SplotyCode** [redisson/redisson#3984]
Sometimes Redisson seems to be stuck when calling Redisson.shutdown(). Some Services are stuck for mutliple days. But it seems to be a very rare event,
```
"Server thread" #35 prio=5 os_prio=0 cpu=31288610.68ms elapsed=200436.69s tid=0x00007f6d9b42d000 nid=0x3f4809 in Object.wait()  [0x00007f6d374ed000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.1/Native Method)
	- waiting on <no object reference available>
	at java.lang.Thread.join(java.base@14.0.1/Thread.java:1297)
	- locked <0x0000000745219408> (a io.netty.util.concurrent.FastThreadLocalThread)
	at io.netty.util.HashedWheelTimer.stop(HashedWheelTimer.java:383)
	at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:622)
	at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:585)
	at org.redisson.Redisson.shutdown(Redisson.java:658)
	at net.gommehd.idlecommons.session.connect.redisson.PrefixedRedisClient.shutdown(PrefixedRedisClient.java:562)
	at net.gommehd.idlecommons.session.connect.redisson.RedissonSession.close(RedissonSession.java:21)
	at net.gommehd.idlecommons.session.SessionModule.onDisable(SessionModule.java:48)
	at net.gommehd.goframe.core.loader.ModuleLoader.disableModules(ModuleLoader.java:248)
	at net.gommehd.goframe.core.ModuleLoaderPlugin.onDisable(ModuleLoaderPlugin.java:65)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:338)
	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:461)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:596)
	at java.lang.Thread.run(java.base@14.0.1/Thread.java:832)
```

This is the Thread netty tries to join. Stack trace does not seem to change over time (took multiple thread dumps)
```
"redisson-timer-10-1" #199 prio=5 os_prio=0 cpu=124713629.34ms elapsed=200430.55s tid=0x00007f6b4c060000 nid=0x3f48ab runnable  [0x00007f6c20bf6000]
   java.lang.Thread.State: RUNNABLE
	at java.util.WeakHashMap$HashIterator.hasNext(java.base@14.0.1/WeakHashMap.java:800)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:191)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@14.0.1/Thread.java:832)
```
**Expected behavior**
 Redisson.shutdown() should be blocking but not for ever
**Actual behavior**
Redisson.shutdown() is stuck for days (in some rare cases) and the Timer thread is taking huge amounts of processing power (this is not a typical profiler bug with parking threads but acutally showing in the process list)
**Steps to reproduce or test case**
Not tried but maybe if you could point us in a direction.
**Redis version**
5.0.3
**Redisson version**
3.16.5-SNAPSHOT (as we need the topic fix)
**Redisson configuration**
Single node with
useThreadClassLoader=: alse
nettyThreads: 4
subscriptionConnectionPoolSize: 12
connectionMinimumIdleSize: 6

**Comment by SplotyCode** [comment]
Never mind i am sorry
