### ISSUE TITLE
Why Redisson is unable to connect?

### ISSUE THREAD

**Issue by IM-IgniteDEV** [redisson/redisson#3988]
On connection with redis I'm getting this:

org.redisson.client.RedisConnectionException: Unable to connect to Redis server: IP/IP:6379
        at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:158) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[patched_1.17.1.jar:git-Airplane-92]
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:313) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$3(ConnectionPool.java:279) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[patched_1.17.1.jar:git-Airplane-92]
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at org.redisson.client.RedisClient$2$1.run(RedisClient.java:242) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.17.1.jar:git-Airplane-92]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://IP:6379]
        at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251) ~[CuriosLibrary-1.1.0-BETA-shaded(1).jar:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) ~[patched_1.17.1.jar:git-Airplane-92]

**Comment by SplotyCode** [comment]
Can you connect with redis-cli -h to the server from that host?

**Comment by IM-IgniteDEV** [comment]
@SplotyCode Yes, I can connect.

**Comment by IM-IgniteDEV** [comment]
Any Ideas?

**Comment by mrniko** [comment]
is there any firewall which deny connecting for JVM?

**Comment by IM-IgniteDEV** [comment]
`[12:21:49 WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by org.redisson.client.RedisClient$2.operationComplete()
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.AbstractEventExecutorGroup.execute(AbstractEventExecutorGroup.java:115) ~[patched_1.17.1.jar:git-Airplane-92]
        at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:249) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:222) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:502) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:342) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:772) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:749) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:769) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [patched_1.17.1.jar:git-Airplane-92]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[12:21:49 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to v1.1.0-BETA
org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 3 of 24 were initialized. Redis server: X:X:6379
        at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:158) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[patched_1.17.1.jar:git-Airplane-92]
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:313) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$3(ConnectionPool.java:279) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[patched_1.17.1.jar:git-Airplane-92]
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at org.redisson.client.RedisClient$2$1.run(RedisClient.java:242) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.17.1.jar:git-Airplane-92]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://X:6379]
        at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251) ~[CuriosLibrary-1.1.0-BETA-shaded(2).jar:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) ~[patched_1.17.1.jar:git-Airplane-92]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) ~[patched_1.17.1.jar:git-Airplane-92]
        ... 2 more`

**Comment by IM-IgniteDEV** [comment]
> is there any firewall which deny connecting for JVM?

Port opened even whole firewall disabled, not working.

**Comment by mrniko** [comment]
Sorry, unable to reproduce it. Seems a network problem.
