### ISSUE TITLE
 ERR Error running script (call to f_0fd7cdd6c1224471b29d6f7fc503462f3b252f12): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short

### ISSUE THREAD

**Issue by ashwinreal** [redisson/redisson#3989]
I am unable to understand this error. Please help.
` Execution exception[[RedisException: ERR Error running script (call to f_0fd7cdd6c1224471b29d6f7fc503462f3b252f12): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0xd4089e92, L:/10.212.134.41:60921 - R:core-dev-redis.6cbkbd.0001.aps1.cache.amazonaws.com/192.168.2.46:6379] command: (EVAL), params: [local result = {}; local idleKeys = {}; local res; if (#ARGV == 4) then  res = redis.call('hscan', K..., 3, ALLUS_XXX, redisson__timeout__set:{ALLUS_XXX}, redisson__idle__set:{ALLUS_XXX}, 1637948919729, 0, 10]]]\
`

I am trying to read using `getMapCache(ALLUS_XXX)`

also, in redis cli if I do `hgetall ALLUS_XXX`.  This is the output

```
 1) "3"
 2) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"3\",\"ax\":\"21\",\"bp\":331.27,\"ap\":331.3,\"bs\":2,\"as\":1,\"t\":\"1637948895747\",\"q\":\"42893371\",\"z\":3}"
 3) "2"
 4) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"2\",\"ax\":\"19\",\"bp\":330.03,\"ap\":330.13,\"bs\":2,\"as\":3,\"t\":\"1637949585689\",\"q\":\"46053648\",\"z\":3}"
 5) "12"
 6) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"12\",\"ax\":\"11\",\"bp\":329.91,\"ap\":330.25,\"bs\":1,\"as\":12,\"t\":\"1637949676507\",\"q\":\"46258127\",\"z\":3}"
 7) "9"
 8) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"9\",\"ax\":\"15\",\"bp\":330.43,\"ap\":330.44,\"bs\":3,\"as\":3,\"t\":\"1637949113455\",\"q\":\"43838492\",\"z\":3}"
 9) "15"
10) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"15\",\"ax\":\"12\",\"bp\":330.34,\"ap\":330.37,\"bs\":2,\"as\":4,\"t\":\"1637949549028\",\"q\":\"45809932\",\"z\":3}"
11) "10"
12) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"10\",\"ax\":\"12\",\"bp\":330.26,\"ap\":330.37,\"bs\":1,\"as\":2,\"t\":\"1637949585833\",\"q\":\"46055016\",\"z\":3}"
13) "18"
14) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"18\",\"ax\":\"11\",\"bp\":330.15,\"ap\":330.25,\"bs\":2,\"as\":12,\"t\":\"1637949683953\",\"q\":\"46258667\",\"z\":3}"
15) "1"
16) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"1\",\"ax\":\"17\",\"bp\":330.21,\"ap\":330.31,\"bs\":4,\"as\":1,\"t\":\"1637949583379\",\"q\":\"46033150\",\"z\":3}"
17) "11"
18) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"11\",\"ax\":\"12\",\"bp\":329.91,\"ap\":330.2,\"bs\":4,\"as\":1,\"t\":\"1637949688637\",\"q\":\"46259504\",\"z\":3}"
19) "7"
20) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"7\",\"ax\":\"11\",\"bp\":330.15,\"ap\":330.25,\"bs\":2,\"as\":12,\"t\":\"1637949684316\",\"q\":\"46258719\",\"z\":3}"
21) "20"
22) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"20\",\"ax\":\"12\",\"bp\":330.11,\"ap\":330.26,\"bs\":1,\"as\":1,\"t\":\"1637949586232\",\"q\":\"46058248\",\"z\":3}"
23) "19"
24) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"19\",\"ax\":\"11\",\"bp\":329.91,\"ap\":330.25,\"bs\":2,\"as\":12,\"t\":\"1637949676537\",\"q\":\"46258138\",\"z\":3}"
25) "8"
26) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"8\",\"ax\":\"11\",\"bp\":330.06,\"ap\":330.25,\"bs\":1,\"as\":12,\"t\":\"1637949685035\",\"q\":\"46258880\",\"z\":3}"
27) "17"
28) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"17\",\"ax\":\"17\",\"bp\":329.37,\"ap\":330.16,\"bs\":2,\"as\":2,\"t\":\"1637949606270\",\"q\":\"46241118\",\"z\":3}"
29) "21"
30) "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"21\",\"ax\":\"12\",\"bp\":330.9,\"ap\":331.09,\"bs\":1,\"as\":1,\"t\":\"1637949581667\",\"q\":\"46012327\",\"z\":3}"
```

This is easlily reproducible,
1. ` HMSET ALLUS_XXX 1 "{\"ev\":\"Q\",\"sym\":\"XXX\",\"bx\":\"1\",\"ax\":\"20\",\"bp\":157.2,\"ap\":157.21,\"bs\":5,\"as\":1,\"t\":\"1637949207844\",\"q\":\"60303179\",\"z\":3}"`
2. Now try to access this using redisson `getMapCache("ALLUS_XXX").readAllEntrySet()`

**Comment by mrniko** [comment]
use the same codec for data store and reading

**Comment by ashwinreal** [comment]
> use the same codec for data store and reading

What is the codec when we add keys using redis-cli  and want to read using redisson  @mrniko ?  I tried a few at random did not work

**Comment by SplotyCode** [comment]
Have you tried StringCodec?

**Comment by ashwinreal** [comment]
i have tried both
` redisService.client.getMapCache(key, StringCodec.INSTANCE ).readAllEntrySet()
      redisService.client.getMapCache(key, ByteArrayCodec.INSTANCE ).readAllEntrySet()
`

**Comment by ashwinreal** [comment]
I feel this should not be hard to do , there should be a codec already defined for this ... all I am trying to do is `HMSET test_key 1 "123"
` 
and then read this using redission. Somehow I am not getting any of the codecs to work . 
Do I need to define a custom codec for this ? Pls suggest

**Comment by ashwinreal** [comment]
@mrniko @SplotyCode I am really stuck here . Any suggestions pls ?

**Comment by mrniko** [comment]
you can insert/update RMapCache entries only through its API or try RMap object

**Comment by ashwinreal** [comment]
yes, this works 
`client.getMap(key, StringCodec.INSTANCE).readAllEntrySet`
Thanks @mrniko

**Comment by chanhengseang3** [comment]
I got this error after added StringCodec.INSTANCE
`redissonClient.getBoundedBlockingQueue("key", StringCodec.INSTANCE)`
```
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 65
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:433)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:490)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:442)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
