### ISSUE TITLE
Why Redisson is  connect  Timeout?

### ISSUE THREAD

**Issue by larry6** [redisson/redisson#3995]
[DC-STG][ERROR][sort][2021-11-28 15:02:10.497][]-[]-[][Thread-12] (ThreadPoolAgent.java:55)[get()] -> 系统异常
java.util.concurrent.ExecutionException: org.springframework.dao.InvalidDataAccessApiUsageException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=19, freeConnectionsCounter=value:59:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.53.179:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@131875383 [redisClient=[addr=redis://192.168.53.179:6379], channel=[id: 0x699c31ec, L:/100.111.156.155:48866 - R:192.168.53.179/192.168.53.179:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@18ca11e9(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.53.179:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 122, 45, 100, 99, 58, 115, 111, 114, 116, ...]] after 3 retry attempts; nested exception is org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=19, freeConnectionsCounter=value:59:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.53.179:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@131875383 [redisClient=[addr=redis://192.168.53.179:6379], channel=[id: 0x699c31ec, L:/100.111.156.155:48866 - R:192.168.53.179/192.168.53.179:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@18ca11e9(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.53.179:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 122, 45, 100, 99, 58, 115, 111, 114, 116, ...]] after 3 retry attempts
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at com.szatc.biz.service.sort.common.agent.ThreadPoolAgent.get(ThreadPoolAgent.java:52) [classes!/:1.0.0-SNAPSHOT]
        at com.szatc.biz.service.sort.sort.impl.DataCacheImpl.init(DataCacheImpl.java:135) [classes!/:1.0.0-SNAPSHOT]
        at com.szatc.biz.service.sort.sort.SortManagerCommon.setTime(SortManagerCommon.java:42) [classes!/:1.0.0-SNAPSHOT]
        at com.szatc.biz.service.sort.sort.impl.SortServiceImpl.sortRealtime(SortServiceImpl.java:63) [classes!/:1.0.0-SNAPSHOT]
        at com.szatc.biz.service.sort.controller.job.SortJobHandler.sortRealTime(SortJobHandler.java:109) [classes!/:1.0.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor579.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29) [xxl-job-core-2.3.0.jar!/:?]
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:163) [xxl-job-core-2.3.0.jar!/:?]
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=19, freeConnectionsCounter=value:59:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.53.179:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@131875383 [redisClient=[addr=redis://192.168.53.179:6379], channel=[id: 0x699c31ec, L:/100.111.156.155:48866 - R:192.168.53.179/192.168.53.179:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@18ca11e9(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.53.179:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 122, 45, 100, 99, 58, 115, 111, 114, 116, ...]] after 3 retry attempts; nested exception is org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=19, freeConnectionsCounter=value:59:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.53.179:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@131875383 [redisClient=[addr=redis://192.168.53.179:6379], channel=[id: 0x699c31ec, L:/100.111.156.155:48866 - R:192.168.53.179/192.168.53.179:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@18ca11e9(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.53.179:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 122, 45, 100, 99, 58, 115, 111, 114, 116, ...]] after 3 retry attempts
        at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48) ~[redisson-spring-data-21-3.11.2.jar!/:3.11.2]
        at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35) ~[redisson-spring-data-21-3.11.2.jar!/:3.11.2]
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:234) ~[redisson-spring-data-21-3.11.2.jar!/:3.11.2]
        at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:229) ~[redisson-spring-data-21-3.11.2.jar!/:3.11.2]
        at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:459) ~[redisson-spring-data-21-3.11.2.jar!/:3.11.2]
        at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:840) ~[redisson-spring-data-21-3.11.2.jar!/:3.11.2]
        at org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:574) ~[redisson-spring-data-21-3.11.2.jar!/:3.11.2]
        at org.springframework.data.redis.cache.DefaultRedisCacheWriter.lambda$get$1(DefaultRedisCacheWriter.java:109) ~[spring-data-redis-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.data.redis.cache.DefaultRedisCacheWriter.execute(DefaultRedisCacheWriter.java:242) ~[spring-data-redis-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.data.redis.cache.DefaultRedisCacheWriter.get(DefaultRedisCacheWriter.java:109) ~[spring-data-redis-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.data.redis.cache.RedisCache.lookup(RedisCache.java:82) ~[spring-data-redis-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.cache.support.AbstractValueAdaptingCache.get(AbstractValueAdaptingCache.java:58) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:73) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:554) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:519) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:401) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at com.szatc.biz.service.sort.service.impl.PointsKeywordServiceImpl$$EnhancerBySpringCGLIB$$d538eda5.selectAll(<generated>) ~[classes!/:1.0.0-SNAPSHOT]
        at com.szatc.biz.service.sort.sort.impl.DataCacheImpl.lambda$init$0(DataCacheImpl.java:117) ~[classes!/:1.0.0-SNAPSHOT]
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70) ~[spring-cloud-sleuth-core-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_91]
Caused by: org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=19, freeConnectionsCounter=value:59:queue:0, freezed=false, freezeReason=null, client=[addr=redis://192.168.53.179:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@131875383 [redisClient=[addr=redis://192.168.53.179:6379], channel=[id: 0x699c31ec, L:/100.111.156.155:48866 - R:192.168.53.179/192.168.53.179:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@18ca11e9(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://192.168.53.179:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[115, 122, 45, 100, 99, 58, 115, 111, 114, 116, ...]] after 3 retry attempts
        at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715) ~[redisson-3.11.2.jar!/:3.11.2]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-all-4.1.58.Final.jar!/:4.1.58.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-all-4.1.58.Final.jar!/:4.1.58.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-all-4.1.58.Final.jar!/:4.1.58.Final]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_91]

**Comment by mrniko** [comment]
Did you try to increase/reduce connections pool size and/or increase netty threads?
