### ISSUE TITLE
redis 三主三从，redisson如何配置master地址？yml文件里只让配置一个地址，使用时，另外两个master找不到

### ISSUE THREAD

**Issue by wen1652166675** [redisson/redisson#3997]
2021-11-30 21:12:10.804 [http-nio-8010-exec-5] ERROR o.a.c.c.C.[.[.[/psai_saas].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/psai_saas] threw exception [Request processing failed; nested exception is org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=1627, addr=//101.253.171.129:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet] with root cause
org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=1627, addr=//101.253.171.129:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet
        at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:543)
        at org.redisson.command.CommandAsyncService.getConnection(CommandAsyncService.java:684)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:539)
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:628)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
        at java.lang.Thread.run(Thread.java:748)

rdisson version :3.8.2

#Redisson配置
masterSlaveServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedAttempts: 3
  password: "is666"
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  slaveAddresses:
    - "redis://101.253.171.129:6380"
    - "redis://101.253.171.130:6380"
    - "redis://101.253.171.131:6380"
  masterAddress: "redis://101.253.171.131:6379"
  database: 0
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
In case of three masters you need to use Cluster mode or Proxy mode if all masters are the same.
