### ISSUE TITLE
Unable to connect to host using DNS resolver on Java 9+

### ISSUE THREAD

**Issue by jsa34** [redisson/redisson#4004]
**Expected behavior**
Using Java 16/17 I can connect with a host by host name successfully, just as with Java 8

**Actual behavior**
When running the same code with Java 8, I can successfully connect to a remote host by name, but with Java 9, 16 and 17 I cannot.

Stacktrace:
java.lang.ExceptionInInitializerError
at xxx
Caused by: java.net.UnknownHostException: failed to resolve 'somehost' after 10 queries
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1046)
at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:999)
at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:417)
at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:628)
at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:65)
at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:461)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:200)
at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:192)
at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1301)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)

**Steps to reproduce or test case**
I am using Redisson, which is using Netty:

    Config config = new Config();
    config.useSingleServer()
            .setAddress("redis://somehost:5379");
    CLIENT = Redisson.create(config);

**Redis version**
6.2.6 (dockerised)

**Redisson version**
Tried 3.16.4 and 3.16.5

**Redisson configuration**
As above

**Comment by mrniko** [comment]
Please create this issue in netty project.

**Comment by jsa34** [comment]
Raised as:
https://github.com/netty/netty/issues/11885

And netty versions on the classpath:
C:\Users\me\.m2\repository\io\netty\netty-codec-http\4.1.67.Final\netty-codec-http-4.1.67.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-transport-native-epoll\4.1.67.Final\netty-transport-native-epoll-4.1.67.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-transport-native-kqueue\4.1.67.Final\netty-transport-native-kqueue-4.1.67.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-transport-native-unix-common\4.1.67.Final\netty-transport-native-unix-common-4.1.67.Final.jar;
C:\Users\me\.m2\repository\org\asynchttpclient\async-http-client\2.12.3\async-http-client-2.12.3.jar;
C:\Users\me\.m2\repository\org\asynchttpclient\async-http-client-netty-utils\2.12.3\async-http-client-netty-utils-2.12.3.jar;
C:\Users\me\.m2\repository\io\netty\netty-codec-socks\4.1.60.Final\netty-codec-socks-4.1.60.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-handler-proxy\4.1.60.Final\netty-handler-proxy-4.1.60.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-transport-native-epoll\4.1.60.Final\netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar;
C:\Users\me\.m2\repository\io\netty\netty-transport-native-kqueue\4.1.60.Final\netty-transport-native-kqueue-4.1.60.Final-osx-x86_64.jar;
C:\Users\me\.m2\repository\com\typesafe\netty\netty-reactive-streams\2.0.4\netty-reactive-streams-2.0.4.jar;
C:\Users\me\.m2\repository\org\redisson\redisson\3.16.5\redisson-3.16.5.jar;
C:\Users\me\.m2\repository\io\netty\netty-common\4.1.70.Final\netty-common-4.1.70.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-codec\4.1.70.Final\netty-codec-4.1.70.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-buffer\4.1.70.Final\netty-buffer-4.1.70.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-transport\4.1.70.Final\netty-transport-4.1.70.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-resolver\4.1.70.Final\netty-resolver-4.1.70.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-resolver-dns\4.1.70.Final\netty-resolver-dns-4.1.70.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-codec-dns\4.1.70.Final\netty-codec-dns-4.1.70.Final.jar;
C:\Users\me\.m2\repository\io\netty\netty-handler\4.1.70.Final\netty-handler-4.1.70.Final.jar;

**Comment by jsa34** [comment]
A little bit of investigation:

Java 8 - both hostname and FQHN resolve
Java 9+ - only FQHN resolves

At least I have found a workaround.

Odd as pinging hostname resolves to expected host...

**Comment by mrniko** [comment]
> Odd as pinging hostname resolves to expected host

Do you mean pinging which is PING command execution over connection ?

**Comment by jsa34** [comment]
Pinging as in when opening a command prompt and executing the "ping" command to the hostname (i.e. "ping somehost"

**Comment by mrniko** [comment]
redis-cli has different hostname resolution method.

**Comment by mrniko** [comment]
Thanks for you tip. I'm closing it.
