### ISSUE TITLE
Can't Find Node in Slaves in Version 3.16.5

### ISSUE THREAD

**Issue by elakian** [redisson/redisson#4005]
**Expected behavior**
Have 1 master and 1 slave (with AWS ElastiCache). When testing failover by through modifying of the node type of the redis instance, expect after failover that there are no errors when querying the new master/slave. 

**Actual behavior**
Getting the following error message: 
`Can't find replicaAddr/<host> in slaves! Available slaves: [[addr=master1Addr], [addr=master1Addr], [addr=master1Addr], [addr=replicaAddr]]`

Trace:

 ```
   at java.lang.Thread.getStackTrace(Thread.java:1596)
    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
    at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
    at ch.qos.logback.classic.Logger.error(Logger.java:530)
    at org.redisson.connection.balancer.LoadBalancerManager.unfreeze(LoadBalancerManager.java:127)
    at org.redisson.connection.MasterSlaveEntry.slaveUp(MasterSlaveEntry.java:424)
    at org.redisson.connection.ReplicatedConnectionManager.slaveUp(ReplicatedConnectionManager.java:206)
    at org.redisson.connection.ReplicatedConnectionManager.lambda$checkNode$5(ReplicatedConnectionManager.java:195)
    at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
    at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
    at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
    at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:460)
    at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:454)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:385)
    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:831)
```

**Steps to reproduce or test case**
1. Deploy Service
2. Modify node type of redis instance
3. View application logs and see errors

**Redis version**
6.0.5

**Redisson version**
3.16.5

**Redisson configuration**
```
    redissonConfig
      .useReplicatedServers()
      .setTimeout(5000)
      .setNodeAddresses(addressList);
```

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.16.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7647470/redisson-3.16.6-SNAPSHOT.jar.zip)

**Comment by elakian** [comment]
Getting a different error message after failover:

```
WriteRedisConnectionException
Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@673818101 [redisClient=[addr=replicaAddr], channel=[id: 0x7b953602, L:/10.0.14.6:50966 ! R:replicaAddr/<host>], currentCommand=null, usage=1], command: (GET), params: [<key>] after 3 retry attempts
```

**Comment by mrniko** [comment]
can you share Redisson logs at `debug` logging level?

**Comment by elakian** [comment]
@mrniko , here's a dump of the logs
[log.txt](https://github.com/redisson/redisson/files/7663220/log.txt)

**Comment by elakian** [comment]
@mrniko , appreciate the help! Any timeframe for getting 3.16.7? No immediate rush, but just would be helpful for planning. Thanks!

**Comment by mrniko** [comment]
Fixed! It will be released by the end of this month.

**Comment by elakian** [comment]
@mrniko thanks! Is it possible to get it is out sooner? We are planning a full migration over to redisson but need fail overs to be handled before doing so. If not, no worries. Thanks again.

**Comment by elakian** [comment]
@mrniko , just in case, can I test an updated jar with the fix to verify on our side. Thanks!

**Comment by mrniko** [comment]
@elakian 

I attached version for testing.

[redisson-3.16.7-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7691459/redisson-3.16.7-SNAPSHOT.jar.zip)

**Comment by elakian** [comment]
@mrniko, seems like after fail over there is still issues. For successful requests, latency seems way up.

Here's the errors and trace: [errors.txt](https://github.com/redisson/redisson/files/7695064/errors.txt)

**Comment by elakian** [comment]
Here's another error type:

```
RedisResponseTimeoutException
Redis server response timeout (5000 ms) occured after 3 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (GET), params: [<key>], channel: [id: 0x5622166e, L:/<host>- R:masterAddr/<host>]
```

**Comment by mrniko** [comment]
@elakian 

Can you share full log in `debug` logging level for `org.redisson` package?

**Comment by mrniko** [comment]
Also try to increase retry attempts to survive the failover

**Comment by elakian** [comment]
Here's some logs from ecs:
[logs](https://github.com/redisson/redisson/files/7705208/log-events-viewer-result.1.csv)

**Comment by stevenzyang** [comment]
@mrniko the failover itself happens without downtime. Seems like the existing connection is dead but isn't cleaned up by redisson

**Comment by mrniko** [comment]
Specify `pingConnectionInterval` param

**Comment by mrniko** [comment]
@elakian 

Can you share full log since the moment of failover started till it's ended?

**Comment by mrniko** [comment]
@stevenzyang 

Can you share Redisson version you use and its config?

**Comment by elakian** [comment]
@mrniko , @stevenzyang is referring to the same snapshot version and same config.
Here's the service logs for when changing node type is initiated, and to when it's over and queries failing:
[logs](https://github.com/redisson/redisson/files/7712962/log-events-viewer-result.2.csv)

**Comment by mrniko** [comment]
@elakian 

Do you use blocking invocation in Redisson async handlers?

**Comment by elakian** [comment]
@mrniko, using non-blocking (getAsync)

**Comment by mrniko** [comment]
Please try attached version.

[redisson-3.16.7-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7727061/redisson-3.16.7-SNAPSHOT.jar.zip)

**Comment by elakian** [comment]
Seems to be fixed. Thanks @mrniko!

**Comment by mrniko** [comment]
@elakian 

Thanks for help!
