### ISSUE TITLE
Got a NullPointerException in WriteReadLock

### ISSUE THREAD

**Issue by allmelgr** [redisson/redisson#4016]
java.lang.NullPointerException: null
        at org.redisson.RedissonBaseLock.createCommandBatchService(RedissonBaseLock.java:238) ~[redisson-3.16.2.jar!/:3.16.2]
        at org.redisson.RedissonBaseLock.evalWriteAsync(RedissonBaseLock.java:212) ~[redisson-3.16.2.jar!/:3.16.2]
        at org.redisson.RedissonWriteLock.tryLockInnerAsync(RedissonWriteLock.java:55) ~[redisson-3.16.2.jar!/:3.16.2]
        at org.redisson.RedissonLock.tryAcquireAsync(RedissonLock.java:175) ~[redisson-3.16.2.jar!/:3.16.2]
        at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:143) ~[redisson-3.16.2.jar!/:3.16.2]
        at org.redisson.RedissonLock.tryLock(RedissonLock.java:223) ~[redisson-3.16.2.jar!/:3.16.2]

the redis model is cluster

**Comment by mrniko** [comment]
how to reproduce it?

**Comment by allmelgr** [comment]
I can't reproduce it yet, small probability event. If i could reproduce it, i will report it

**Comment by hepengju** [comment]
we meet this issue too.
redisson: 3.16.0
Maybe when redis cluster meet some problems, then masterSlaveEntry change to null.

![img_v2_eb50fd15-0f52-4840-95f5-e8ebb57f608g](https://user-images.githubusercontent.com/26279882/201846255-1d07e826-c04c-4e40-94d0-64805bf41db5.jpg)
![image](https://user-images.githubusercontent.com/26279882/201847176-e73a2bc4-a0be-4159-a51e-3e3508a653d6.png)

**Comment by mrniko** [comment]
Fixed in 3.17.7+ version https://github.com/redisson/redisson/commit/a5502b6744bf86d3550b80548212a087bfe8fa20. Please update
