### ISSUE TITLE
Error while aquiring ReadWriteLock and Lock at the same time

### ISSUE THREAD

**Issue by NeoZephyr** [redisson/redisson#4022]
When I call method `runWithRwLock` and method `runWithMultiLock` at same time, it works fine. When I call method `runWithLock` and method `runWithRwLock`/`runWithMultiLock`, the following error is frequently reported

```
2021-12-16 12:30:22.647 [pool-1-thread-1] ERROR com.pain.blue.cache.RedisTest:217 - lockAndUnlock
org.redisson.client.RedisTimeoutException: Subscribe timeout: (7500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:118)
	at org.redisson.RedissonLock.lock(RedissonLock.java:185)
	at org.redisson.RedissonLock.lock(RedissonLock.java:156)
	at com.pain.blue.cache.RedisTest.runWithRwLock(RedisTest.java:254)
	at com.pain.blue.cache.RedisTest.lambda$benchmark$2(RedisTest.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**This is my test code:**

```
private static void benchmark() throws InterruptedException {
    ArrayBlockingQueue<Runnable> queue = new ArrayBlockingQueue<>(5000);
    ThreadPoolExecutor executor = new ThreadPoolExecutor(5, 20, 30, TimeUnit.SECONDS, queue, new ThreadPoolExecutor.CallerRunsPolicy());
    Config config = new Config();
    config.useSingleServer()
            .setAddress("redis://127.0.0.1:6379")
            .setSubscriptionsPerConnection(5000)
            .setSubscriptionConnectionPoolSize(50);
    config.setLockWatchdogTimeout(15 * 1000);
    RedissonClient client = Redisson.create(config);
    AtomicLong counter = new AtomicLong();
    long startTime = System.currentTimeMillis();
    Random random = new Random();

    for (int i = 0; i < 100000; ++i) {
        int ii = i;
        executor.submit(() -> {
            try {
                int resource1 = random.nextInt(20);
                int resource2 = random.nextInt(20);
                int resource3 = random.nextInt(20);
                boolean write = ii % 2 == 0;
                // runWithLock(client, String.valueOf(resource1));
                runWithRwLock(client, String.valueOf(resource2), write);
                runWithMultiLock(client, String.valueOf(resource3), write);
                log.info("task: {}, count: {}", ii, counter.incrementAndGet());
            } catch (Exception ex) {
                ex.printStackTrace();
                log.error("lockAndUnlock", ex);
            }
        });
    }

    executor.shutdown();
    executor.awaitTermination(1000, TimeUnit.SECONDS);

    long endTime = System.currentTimeMillis();
    client.shutdown();

    log.info("counter: {}, cost: {}", counter.get(), (endTime - startTime));
}

private static void runWithLock(RedissonClient client, String resource) throws InterruptedException {
    log.info("{}, prepare lock", Thread.currentThread().getId());
    RLock lock = client.getLock(resource);
    log.info("{}, before lock", Thread.currentThread().getId());
    lock.lock(800, TimeUnit.MILLISECONDS);
    log.info("{}, after lock", Thread.currentThread().getId());
    Thread.sleep(10);
    log.info("{}, unlock", Thread.currentThread().getId());
    lock.unlock();
}

private static void runWithRwLock(RedissonClient client, String resource, boolean write) throws InterruptedException {
    log.info("{}, prepare {} lock", Thread.currentThread().getId(), write ? "write" : "read");
    RReadWriteLock rwLock = client.getReadWriteLock(resource);
    RLock lock;

    if (write) {
        lock = rwLock.writeLock();
    } else {
        lock = rwLock.readLock();
    }

    log.info("{}, before {} lock", Thread.currentThread().getId(), write ? "write" : "read");
    lock.lock(800, TimeUnit.MILLISECONDS);
    log.info("{}, after {} lock", Thread.currentThread().getId(), write ? "write" : "read");
    Thread.sleep(10);
    log.info("{}, {} unlock", Thread.currentThread().getId(), write ? "write" : "read");
    lock.unlock();
}

private static void runWithMultiLock(RedissonClient client, String resource, boolean write) throws InterruptedException {
    log.info("{}, prepare {} lock", Thread.currentThread().getId(), write ? "write" : "read");
    RReadWriteLock rwLock1 = client.getReadWriteLock(resource);
    int value = Integer.parseInt(resource);
    RReadWriteLock rwLock2 = client.getReadWriteLock(String.valueOf(value + 3));
    RReadWriteLock rwLock3 = client.getReadWriteLock(String.valueOf(value + 6));
    RReadWriteLock rwLock4 = client.getReadWriteLock(String.valueOf(value + 9));
    RLock lock1;
    RLock lock2;
    RLock lock3;
    RLock lock4;

    if (write) {
        lock1 = rwLock1.writeLock();
        lock2 = rwLock2.writeLock();
        lock3 = rwLock3.writeLock();
        lock4 = rwLock4.writeLock();
    } else {
        lock1 = rwLock1.readLock();
        lock2 = rwLock2.readLock();
        lock3 = rwLock3.readLock();
        lock4 = rwLock4.readLock();
    }

    RLock lock = client.getMultiLock(lock1, lock2, lock3, lock4);

    log.info("{}, before {} lock", Thread.currentThread().getId(), write ? "write" : "read");
    lock.lock(800, TimeUnit.MILLISECONDS);
    log.info("{}, after {} lock", Thread.currentThread().getId(), write ? "write" : "read");
    Thread.sleep(10);
    log.info("{}, {} unlock", Thread.currentThread().getId(), write ? "write" : "read");
    lock.unlock();
}
```

**Comment by mrniko** [comment]
> the following error is frequently reported

Did  you try to increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters?

**Comment by NeoZephyr** [comment]
> 



> > the following error is frequently reported
> 
> Did you try to increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters?

How big can these two parameters be increased, I increased some and it does not seem to work

**Comment by mrniko** [comment]
Different types of objects: Lock with ReadWriteLock can't share the same name.
