### ISSUE TITLE
org.springframework.dao.QueryTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource 

### ISSUE THREAD

**Issue by xiaonannet** [redisson/redisson#4028]
[http-nio-30050-exec-8] jnpf.ResultException                    : org.springframework.dao.QueryTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@544414644 [redisClient=[addr=redis://218.90.122.145:6370], channel=[id: 0x78a18e59, L:/10.115.43.189:60890 - R:/218.90.122.145:6370], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@56f03af3(failure: java.util.concurrent.CancellationException)], command=(GET), params=[[103, 99, 108, 108, 111, 103, 105, 110, 95, 116, ...]], codec=org.redisson.client.codec.ByteArrayCodec]], command: (GET), params: [[103, 99, 108, 108, 111, 103, 105, 110, 95, 116, ...]] after 3 retry attempts; nested exception is org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@544414644 [redisClient=[addr=redis://218.90.122.145:6370], channel=[id: 0x78a18e59, L:/10.115.43.189:60890 - R:/218.90.122.145:6370], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@56f03af3(failure: java.util.concurrent.CancellationException)], command=(GET), params=[[103, 99, 108, 108, 111, 103, 105, 110, 95, 116, ...]], codec=org.redisson.client.codec.ByteArrayCodec]], command: (GET), params: [[103, 99, 108, 108, 111, 103, 105, 110, 95, 116, ...]] after 3 retry attempts
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48)
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:223)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:218)
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:384)
	at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:765)
	at org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:499)
	at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53)
	at jnpf.util.RedisUtil.getString(RedisUtil.java:216)
	at jnpf.util.UserProvider.get(UserProvider.java:56)
	at jnpf.util.UserProvider.get(UserProvider.java:72)
	at jnpf.DataSourceBindAspect.doAroundService(DataSourceBindAspect.java:58)
	at sun.reflect.GeneratedMethodAccessor605.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by mrniko** [comment]
Can you share your Redisson config?

**Comment by zchen-flashhold** [comment]
Same issue, any update here

**Comment by mrniko** [comment]
@zchen-flashhold 

did you try to reduce connection pool and/or increase nettyThreads ?

**Comment by zchen-flashhold** [comment]
```
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  clientName: rcs-redis
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 1
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 1
  dnsMonitoringInterval: 5000
  nettyThreads: 64
codec: !<org.redisson.codec.JsonJacksonCodec> { }
transportMode: "NIO"
```
Our configuration look like this. We change nettyThreads from 32 to 64, but we encounter the same problem

**Comment by mrniko** [comment]
try to set connectionMinimumIdleSize = 16 and connectionPoolSize = 32

**Comment by zchen-flashhold** [comment]
What's relationship between connectionPool and nettyThreads? Does the value of nettyThread should be large than the connectionPool (the sum of subscriptionConnectionPoolSize and connectionPoolSize)
