### ISSUE TITLE
[Bug] Version 3.16.6: RedisConnectionException: Unable to init enough connections amount

### ISSUE THREAD

**Issue by slisaasquatch** [redisson/redisson#4048]
**Expected behavior**

I should be able to create a `RedissonClient`

**Actual behavior**

This only happens with version 3.16.6. 3.16.4 doesn't cause this error. Also, this error only happens with the local [embedded Redis](https://mvnrepository.com/artifact/com.github.kstyrc/embedded-redis/0.6). On a real remote Redis server, it works fine.

On create, I get this error:

```
org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 16 of 24 were initialized. Redis server: localhost/127.0.0.1:6614
        at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:158)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:313)
        at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$3(ConnectionPool.java:279)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96)
        at org.redisson.client.RedisClient$2$2.run(RedisClient.java:251)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: failed to create a new resolver
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:72)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:194)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        ... 7 common frames omitted
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioDatagramChannel
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:46)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)
        at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
        at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:497)
        at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:488)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:92)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:77)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:70)
        ... 22 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:44)
        ... 30 common frames omitted
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:90)
        at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:119)
        ... 34 common frames omitted
Caused by: java.net.SocketException: maximum number of DatagramSockets reached
        at sun.net.ResourceManager.beforeUdpCreate(ResourceManager.java:73)
        at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:107)
        at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:42)
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:88)
        ... 35 common frames omitted
```

**Steps to reproduce or test case**

N/A

**Redis version**

https://mvnrepository.com/artifact/com.github.kstyrc/embedded-redis/0.6

**Redisson version**

3.16.6

**Redisson configuration**

**Comment by mrniko** [comment]
Which mode is use?

**Comment by slisaasquatch** [comment]
What do you mean by mode?

This is my code for creating a `RedissonClient`:

```java
	final org.redisson.config.Config rConfig = new org.redisson.config.Config();
	rConfig.useSingleServer()
			.setAddress("redis://localhost:6614")
			.setPassword(null);
	final RedissonClient redissonClient = Redisson.create(rConfig);
```

**Comment by mrniko** [comment]
Try 3.16.7 version it might be caused by this issue https://github.com/redisson/redisson/issues/4011
