### ISSUE TITLE
Redisson WriteRedisConnectionException timeout

### ISSUE THREAD

**Issue by xushaoxiao** [redisson/redisson#4057]
```
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1343879621 [redisClient=[addr=redis://172.31.142.7:6379], channel=[id: 0x371731e4, L:/10.0.134.241:35464 ! R:172.31.142.7/172.31.142.7:6379], currentCommand=null, usage=0], command: (EVAL), params: [local key = KEYS[1] local obj = ARGV[1] local items = redis.call('lrange', key, 0, -1) for i=1,#item..., 1, testJobUnitsPopKey_83924b22-20cd-4d42-abc6-5c236e8792c9, PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256)] after 3 retry attempts
        at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:282) ~[redisson-3.16.7.jar!/:3.16.7]
        at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:62) ~[redisson-3.16.7.jar!/:3.16.7]
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:165) ~[redisson-3.16.7.jar!/:3.16.7]
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:162) ~[redisson-3.16.7.jar!/:3.16.7]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1021) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:882) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: io.netty.channel.StacklessClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
```

**Comment by xushaoxiao** [comment]
redisson version has been released from 3.16.2 to 3..16.7

**Comment by mrniko** [comment]
Try to reduce connection pool size.

**Comment by xushaoxiao** [comment]
```yaml
---
singleServerConfig:
  idleConnectionTimeout: 60000
  connectTimeout: 1000
  timeout: 30000
  retryAttempts: 5
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: testing-framework-redis-client
  address: "redis://172.31.142.7:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
#  pingConnectionInterval: 1000
threads: 16
nettyThreads: 32
codec:
  class: org.redisson.codec.JsonJacksonCodec
transportMode: "NIO"
```

I used default settings @mrniko

**Comment by dingzuobing** [comment]
The problem is resolved?@xushaoxiao

**Comment by xiangshaonumber1** [comment]
How did you solve this problem @xushaoxiao , its standalone and I also use the default config
