### ISSUE TITLE
ERR WAIT cannot be used with slave instances

### ISSUE THREAD

**Issue by waykar-prashant** [redisson/redisson#4068]
This occurs when trying to acquire a lock.
Currently, we are using redisson library 3.16.3 with readmode: SLAVE

`Caused by: org.redisson.client.RedisException: ERR WAIT cannot be used with slave instances. Please also note that since Redis 4.0 if a slave is configured to be writable (which is not the default) writes to slaves are just local and are not propagated.. channel: [id: 0x90c58500, L:/172.16.189.108:43192 - R:10.112.94.132/10.112.94.132:15003] command: (WAIT), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@35eeb35e(incomplete)], params: [1, 1000]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:271)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1432)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted`

**Comment by waykar-prashant** [comment]
@mrniko can you please help with the above question?

**Comment by mrniko** [comment]
Seems you defined slave as master. Use master instead.

**Comment by waykar-prashant** [comment]
@mrniko Can you please help me understand "use master instead"? 
We are currently using Azure Redis Cache and below is the config I use. Do you see any problem with the config I am using?
The error message says "since Redis 4.0 if a slave is configured to be writable (which is not the default) writes to slaves are just local and are not propagated.."

`Config config = Config.fromYAML(this.getClass().getResource(redisConfigFile));
                if (lockConfiguration.getHostAddress() != null) {
                    config.useClusterServers().setNodeAddresses(Arrays.asList(lockConfiguration.getHostAddress()));
                }
                redissonClient = Redisson.create(config);`


`clusterServersConfig:
  idleConnectionTimeout: ${REDIS_IDLE_CONNECTION_TIMEOUT:-10000}
  connectTimeout: ${REDIS_CONNECTION_TIMEOUT:-10000}
  timeout: ${REDIS_TIMEOUT:-10000}
  retryAttempts: ${REDIS_RETRY_ATTEMPTS:-10}
  retryInterval: ${REDIS_RETRY_INTERVAL:-1500}
  failedSlaveReconnectionInterval: ${REDIS_FAILED_SLAVE_RECONNECTION_INTERVAL:-3000}
  failedSlaveCheckInterval: ${REDIS_FAILED_SLAVE_CHECK_INTERVAL:-60000}
  nodeAddresses:
    - ${REDIS_HOST:-null}
  password: ${REDIS_PASSWORD:-null}
  subscriptionsPerConnection: ${REDIS_SUBSCRIPTIONS_PER_CONNECTION:-5}
  clientName: ${REDIS_CLIENT_NAME:-null}
  loadBalancer: ${REDIS_LOAD_BALANCER:-!<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}}
  subscriptionConnectionMinimumIdleSize: ${REDIS_SUBCRIPTION_CONNECTION_MINIMUM_IDLE_SIZE:-1}
  subscriptionConnectionPoolSize: ${REDIS_SUBSCRIPTION_POOL_SIZE:-50}
  slaveConnectionMinimumIdleSize: ${REDIS_SLAVE_CONNECTION_MINIMUM_IDLE_SIZE:-24}
  slaveConnectionPoolSize: ${REDIS_SLAVE_CONNECTION_POOL_SIZE:-128}
  masterConnectionMinimumIdleSize: ${REDIS_MASTER_CONNECTION_MINIMUM_IDLE_SIZE:-24}
  masterConnectionPoolSize: ${REDIS_MASTER_CONNECTION_POOL_SIZE:-128}
  readMode: ${REDIS_READ_MODE:-"SLAVE"}
  subscriptionMode: ${REDIS_SUBSCRIPTION_MODE:-"SLAVE"}
  scanInterval: ${REDIS_SCAN_INTERVAL:-1000}
  pingConnectionInterval: ${REDIS_PING_CONNECTION_INTERVAL:-0}
  keepAlive: ${REDIS_KEEP_ALIVE:-false}
  tcpNoDelay: ${REDIS_TCP_NO_DELAY:-false}
threads: ${REDIS_THREADS:-64}
nettyThreads: ${REDIS_NETTY_THREADS:-128}
codec: ${REDIS_CODEC:-!<org.redisson.codec.FstCodec> {}}
transportMode: ${REDIS_TRANSPORT_MODE:-"NIO"}
lockWatchdogTimeout: 60000`

**Comment by mrniko** [comment]
Can you set `TRACE` logging level for `org.redisson` package and share output?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/6223
