### ISSUE TITLE
Unable to resolve master.****.cache.amazonaws.com

### ISSUE THREAD

**Issue by Brainhu** [redisson/redisson#4069]
**Expected behavior**

expected no exception

**Actual behavior**

 Unable to resolve master.****.cache.amazonaws.com

io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'master.****.cache.amazonaws.com' failed to resolve 'master.****.cache.amazonaws.com'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:463) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.100.0.10:53] query via UDP timed out after 5000 milliseconds (no stack trace available)

**Steps to reproduce or test case**

sometimes happen,no regular

**Redis version**
ElastiCache 5.0.6

**Redisson version**

redisson 3.13.6

**Redisson configuration**

spring:
  redis:
    protocol: rediss
    redisson:
      enabled: true
 host: **
 port:**
 ssl: true
 lettuce:
      pool:
        max-active: 300
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000

**Comment by mrniko** [comment]
> io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.100.0.10:53] query via UDP timed out after 5000 milliseconds

You need to check dns server.

**Comment by Brainhu** [comment]
> > io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.100.0.10:53] query via UDP timed out after 5000 milliseconds
> 
> You need to check dns server.

如果是dns 的问题整个k8s 集群里面的服务都会有问题，但是现象是几十个服务会有几个出现这个异常，发生的频率是1-2 天一次。

**Comment by Brainhu** [comment]
> > io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.100.0.10:53] query via UDP timed out after 5000 milliseconds
> 
> You need to check dns server.

If it is DNS problem, there will be happened all over the entire K8S cluster, but the phenomenon is a few services, there are several exceptions, and the frequency of occurrence is 1-2 days.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1625
