### ISSUE TITLE
I have migrate my spring boot prject from 1.5.x to 2.3.12 and I have used redis cache to get the user details but it is not working

### ISSUE THREAD

**Issue by shuaib313** [redisson/redisson#4070]
when I am tring the get the data from redisson.getmap it is showing this error

[sson-netty-4-11] o.r.client.handler.CommandDecoder : Unable to decode data. channel: [id: xcvyreds, L:/23.24.234.53 - R:master.cf-73gdvfrcbs.qr2rmb.apse2.cache.amazonaws.com/10.192.6.121:3245], reply: ReplayingDecoderByteBuf(ridx=41, widx=1549), command: (HSCAN), params: [3JlYxMiJ9.eyJzdWIiOiJoMTAxOTAzIXRlZCI6MTY0MTk2XNzIjoiQ1QtRGFzaGJvYXJeyJhbGciOiJSUzUiwiYNjE1ODc3NSwia..., 0, COUNT, 10]
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] java.io.IOException: java.lang.NullPointerException
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.codec.FstCodec$1.decode(FstCodec.java:164)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:364)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:408)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:373)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:408)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:373)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:199)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:139)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
2022-01-12T13:32:41.812+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.NullPointerException: null
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
2022-01-12T13:32:41.813+05:30 [APP/PROC/WEB/0] [OUT] ... 37 common frames omitted

**Comment by mrniko** [comment]
Please note default codec has changed since 3.13.0 version. You need to specify FstCodec explicitly in config.

**Comment by shuaib313** [comment]
@mrniko could you share me example of hoe to use FstCodec config please.

**Comment by shuaib313** [comment]
I have changes the radisson version to 3.8.1 and it worked for me Thanks 👍
