### ISSUE TITLE
> > io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.100.0.10:53] query via UDP timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by Brainhu** [redisson/redisson#4074]
> > io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.100.0.10:53] query via UDP timed out after 5000 milliseconds
> 
> You need to check dns server.

If it is DNS problem, there will be happened all over the entire K8S cluster, but the phenomenon is a few services, there are several exceptions, and the frequency of occurrence is 1-2 days.

_Originally posted by @Brainhu in https://github.com/redisson/redisson/issues/4069#issuecomment-1011823268_

**Comment by mrniko** [comment]
It might be a network problem aswell.

**Comment by Brainhu** [comment]
> It might be a network problem as well. Also I can suggest you to update netty lib.
which version ？latest ?

**Comment by mrniko** [comment]
@chenyu1st 

I'm unable to reproduce it. Check network and dns network also update netty.

**Comment by Brainhu** [comment]
> @mrniko Hello, I also encountered this problem, how did you solve it in the end? redisson 3.16.0 netty 4.1.43 2022-02-06T11:21:15.662Z,[redisson-netty-2-23],ERROR,org.redisson.connection.DNSMonitor,112,Unable to resolve redis, io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis' failed to resolve 'redis.svc.cluster.local' at ... Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.10.0.10:53] query via UDP timed out after 5000 milliseconds (no stack trace available)

not yet, i will try to update redission to latest

**Comment by youdang123** [comment]
> > @mrniko Hello, I also encountered this problem, how did you solve it in the end? redisson 3.16.0 netty 4.1.43 2022-02-06T11:21:15.662Z,[redisson-netty-2-23],ERROR,org.redisson.connection.DNSMonitor,112,Unable to resolve redis, io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis' failed to resolve 'redis.svc.cluster.local' at ... Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.10.0.10:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
> 
> not yet, i will try to update redission to latest

I had the same problem and you solved it this way

**Comment by youdang123** [comment]
> cluster

I had the same problem and you solved it this way

**Comment by mrniko** [comment]
Here is the solution https://github.com/redisson/redisson/issues/4248#issuecomment-1107424810

**Comment by gujunhua** [comment]
Hello, I would like to know whether to update the version to 3.17.4，Is that ok?

**Comment by gujunhua** [comment]
> Here is the solution [#4248 (comment)](https://github.com/redisson/redisson/issues/4248#issuecomment-1107424810)

Hello, I would like to know whether to update the version to 3.17.4，Is that ok?

**Comment by mrniko** [comment]
@gujunhua 

https://github.com/redisson/redisson/issues/4074#issuecomment-1129729403

**Comment by gujunhua** [comment]
> @gujunhua
> 
> [#4074 (comment)](https://github.com/redisson/redisson/issues/4074#issuecomment-1129729403)

I used your plan，I haven't had the problem in two weeks. We will continue to give feedback，think you

**Comment by gstkenpo** [comment]
if you are using spring boot, try to update it to the latest sprint boot version. Mine was using spring-cloud-dependencies:2020.0.2 and org.springframework.boot:2.4.4. After I update it to 2021.0.3 and 2.7.2, the problem just solve

**Comment by mmcroom** [comment]
We are trying to get rid of these ERRORS in our production logs. We have been seeing this for a couple of years now. Looking at the comments above (https://github.com/redisson/redisson/issues/4248#issuecomment-1107424810), we have added the following as suggested. We are still getting the errors. We are logging out the settings at startup and they are being set:

**DnsAddressResolverGroupFactory minTtl 120, maxTtl 120, negativeTtl 60**

We are using spring boot 2.6.8 and spring cloud dependency 2021.0.2.

What is the latest on this issue? Is it being pushed to some future release?

public class DnsAddressResolverGroupFactory implements AddressResolverGroupFactory {
    
    @Override
    public DnsAddressResolverGroup create(Class<? extends DatagramChannel> channelType,
            DnsServerAddressStreamProvider nameServerProvider) {
        DnsAddressResolverGroup group = new DnsAddressResolverGroup(new DnsNameResolverBuilder()
                .channelType(NioDatagramChannel.class)
                .ttl(120, 120)
                .negativeTtl(60)
                .nameServerProvider(DnsServerAddressStreamProviders.platformDefault());
        return group;
    }

**Comment by mrniko** [comment]
@mmcroom 

An alternative solution: https://aws.amazon.com/premiumsupport/knowledge-center/dns-resolution-failures-ec2-linux/?nc1=h_ls

**Comment by umutkocasarac** [comment]
Hi @mrniko,

We have started to see this error a lot since we introduce the new big cluster (100+ nodes) to our system. Having own DnsAddressResolverGroupFactory helped us, but one thing we noticed was each event loop is having its own dnscache on the netty side so we started to pass singleton Dns cache instance to netty as below.

```
class DnsAddressResolverGroupFactory : AddressResolverGroupFactory {
    override fun create(
        p0: Class<out DatagramChannel>,
        p1: DnsServerAddressStreamProvider
    ): AddressResolverGroup<InetSocketAddress> {
        return DnsAddressResolverGroup(
            DnsNameResolverBuilder().channelType(NioDatagramChannel::class.java)
                .resolveCache(DNS_CACHE)
                .cnameCache(CNAME_CACHE)
        )
    }
}

However, we are still seeing this error once in a while. We have created an [issue](https://github.com/netty/netty/issues/12842) for netty DNS resolver already but in the meantime, we find out that reducing the DNS query count is reducing the error rate significantly. I have a [PR](https://github.com/redisson/redisson/pull/4577) for limiting DNS queries (it is disabled by default).

**Comment by jiangyijian78** [comment]
@mrniko Hello, I also encountered this problem ， how solve it?
redisson 3.19.1
netty 4.1.87.Final

**Comment by chenyu1st** [comment]
> @mrniko Hello, I also encountered this problem ， how solve it? redisson 3.19.1 netty 4.1.87.Final

At present, the way I solve it is to directly add the configuration of hostAliases to the container, and this problem does not appear after adding it

**Comment by jiangyijian78** [comment]
What should I do if the domain uses a dynamic IP?

**Comment by jiangyijian78** [comment]
> > @mrniko Hello, I also encountered this problem ， how solve it? redisson 3.19.1 netty 4.1.87.Final
> 
> At present, the way I solve it is to directly add the configuration of hostAliases to the container, and this problem does not appear after adding it


What should I do if the domain uses a dynamic IP?

**Comment by chenyu1st** [comment]
> > > @mrniko Hello, I also encountered this problem ， how solve it? redisson 3.19.1 netty 4.1.87.Final
> > 
> > 
> > At present, the way I solve it is to directly add the configuration of hostAliases to the container, and this problem does not appear after adding it
> 
> What should I do if the domain uses a dynamic IP?

There is no good solution for the time being, because when our company's architecture deploys redis, it is either the redis service of aws or the persistent redis of k8s, and its service will not be updated. In this case, we only use the hostAliases method to solve this problem

**Comment by jiangyijian78** [comment]
> > > > @mrniko Hello, I also encountered this problem ， how solve it? redisson 3.19.1 netty 4.1.87.Final
> > > 
> > > 
> > > At present, the way I solve it is to directly add the configuration of hostAliases to the container, and this problem does not appear after adding it
> > 
> > 
> > What should I do if the domain uses a dynamic IP?
> 
> There is no good solution for the time being, because when our company's architecture deploys redis, it is either the redis service of aws or the persistent redis of k8s, and its service will not be updated. In this case, we only use the hostAliases method to solve this problem

我尝试过使用全局代理工具来解决这个问题， 但是在netty在调用时会自动绕过服务器的全局代理工具， 这是为啥呢？

**Comment by Abahafart** [comment]
I have some issue that looks as the same.
Here my code
```
    @Bean
    public LettuceConnectionFactory redisClusterConnectionFactory(@Value("${redis.host}") String host,
                                                                  @Value("${redis.port}") Integer port) {
        RedisClusterConfiguration clusterConfiguration = new RedisClusterConfiguration();
        clusterConfiguration.clusterNode(host, port);
        return new LettuceConnectionFactory(clusterConfiguration);
    }
```
```
Caused by: java.net.UnknownHostException: Failed to resolve 'elastic-cache-xxx-xxx-xxx-xxx-xxx.xxx.xxx.xxx.cache.amazonaws.com' after 3 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047) ~[netty-resolver-dns-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000) ~[netty-resolver-dns-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418) ~[netty-resolver-dns-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66) ~[netty-resolver-dns-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467) ~[netty-resolver-dns-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:256) ~[netty-resolver-dns-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:208) ~[netty-resolver-dns-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	... 1 common frames omitted
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/xxx.xxx.xxx.xxx:xx] query via UDP timed out after 5000 milliseconds (no stack trace available)
```
Anyone could solve it?

**Comment by mrniko** [comment]
@Abahafart

You need to define SequentialDnsAddressResolverFactory with concurrencyLevel = 4 or 6

Yaml config example:

```yaml
addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> 4
```

**Comment by ly1412** [comment]
@Abahafart hi  We recently encourter this same problem , is yours solved?

**Comment by Carllion** [comment]
Using redisson 3.18.0 netty 4.1.85.Final, we also encounter this same problem

**Comment by mrniko** [comment]
@Carllion 

[Try this](https://github.com/redisson/redisson/issues/4074#issuecomment-1526961988)
