### ISSUE TITLE
Quarkus redisson config fails to load in cluster mode with only one node address

### ISSUE THREAD

**Issue by Adler95** [redisson/redisson#4076]
Configuration is not successfully loaded if there is only one node address configured in cluster mode.
```
quarkus:
  redisson:
    cluster-servers-config:
      node-addresses: 
      - "redis://127.0.0.1:16379"
```

**Expected behavior**
Configuration should be loaded successfully, documentation states that only one is required.
![image](https://user-images.githubusercontent.com/41158044/149326958-7d7d1ef0-3e40-40c7-86fd-bc47a82a055a.png)

**Actual behavior**
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('redis://127.0.0.1:16379')
 at [Source: (StringReader); line: 3, column: 18] (through reference chain: org.redisson.config.Config["clusterServersConfig"]->org.redisson.config.ClusterServersConfig["nodeAddresses"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:284)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:192)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:150)
	at org.redisson.config.Config.fromYAML(Config.java:620)
	at io.quarkus.redisson.client.runtime.RedissonClientProducer.create(RedissonClientProducer.java:45)
```

**Steps to reproduce or test case**
- Setup Quarkus project
- Add redisson-quarkus-20 dependency
- Configure Redisson client to use cluster mode with single node address

**Redis version**
6.2.6

**Redisson version**
```
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-quarkus-20</artifactId>
            <version>3.16.7</version>
        </dependency>
```

**Redisson configuration**
```
quarkus:
  redisson:
    cluster-servers-config:
      node-addresses: 
      - "redis://127.0.0.1:16379"
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
