### ISSUE TITLE
org.redisson.client.RedisException: ERR unknown command 'WAIT'

### ISSUE THREAD

**Issue by yohugSu** [redisson/redisson#4082]
When I use Redisson of V3.14.1 and advanced version, it occur a error such as code below. But if I use V3.14.0 and older version, the error didn't occur.My redis is redis-5.0_0.3.4 of community version and it deploys as cluster mode.My jdk version is 1.8.0_261. 
I guess it has something to do with the jdk version or netty-buffer version.But I can't find the answer.

`
org.redisson.client.RedisException: ERR unknown command 'WAIT'. channel: [id: 0x037ca630, L:/【my redis cluster Ip:my port】 - R:/【my redis cluster Ip:my port】] command: (WAIT), params: [1, 1000]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:346)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:247)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:189)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

When I use V3.16.7, it also occur the same error, and the error contains '[promise=ImmediateEventExecutor$ImmediatePromise@6d864451(incomplete)], params: [1, 1000]', such as:

`org.redisson.client.RedisException: ERR unknown command 'WAIT'. channel: [id: 0xbf4ecfcf, L:/【my redis cluster Ip:my port】 - R:/【my redis cluster Ip:my port】] command: (WAIT), promise: RedissonPromise 
[promise=ImmediateEventExecutor$ImmediatePromise@6d864451(incomplete)], params: [1, 1000]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:271)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by mrniko** [comment]
Lock object uses WAIT command to sync lock state with slaves. WAIT commands is available since Redis 3.0. You need to check your Redis setup.

**Comment by yohugSu** [comment]
这是来自QQ邮箱的假期自动回复邮件。收到！！谢谢！！

**Comment by yohugSu** [comment]
> Lock object uses WAIT command to sync lock state with slaves. WAIT commands is available since Redis 3.0. You need to check your Redis setup.

WAIT command is support. I found my redis cluster mode is not direct mode but redis-cluster-proxy mode. I think you can try to test the redis-cluster-proxy mode. I use redis-cluster-proxy by Aliyun, and I don't know if redisson that  is V3.14.0 and advanced version supports redis-cluster-proxy mode.

**Comment by mrniko** [comment]
redis-cluster-proxy by Aliyun seems doesn't support WAIT command. Please contact developer.

**Comment by yohugSu** [comment]
> redis-cluster-proxy by Aliyun seems doesn't support WAIT Redis command. Please contact developer.

Thanks, it is not support WAIT Redis command indeed, need to open direct-connection-mode.
https://help.aliyun.com/document_detail/185969.html
