### ISSUE TITLE
Classloader issue when using RScheduledExecutorService

### ISSUE THREAD

**Issue by nylund** [redisson/redisson#4084]
Classloader error thrown when invoking method of Autowired Spring Bean in a Runnable task. 

```
@Configuration
public class RedissonConfig {

  public static final String EXECUTOR_NAME = "spring_test";

  @Bean(destroyMethod = "shutdown")
  RedissonNode redissonNode(BeanFactory beanFactory) {
    Config config = new Config();
    config.useSingleServer()
        .setAddress("redis://127.0.0.1:6379");
    RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
    nodeConfig.setExecutorServiceWorkers(Collections.singletonMap(EXECUTOR_NAME, 1));
    nodeConfig.setBeanFactory(beanFactory);
    RedissonNode node = RedissonNode.create(nodeConfig);
    node.start();
    return node;
  }

  @Bean
  RedissonClient redissonClient() {
    Config config = new Config();
    config.useSingleServer()
        .setAddress("redis://127.0.0.1:6379");
    return Redisson.create(config);
  }

}

@Component
public class SomeService {

  void doSomething() {
    System.out.println("Hello");
  }

}


public class Task implements Runnable, Serializable {

  @Autowired private SomeService someService;

  public Task() {
  }

  @Override
  public void run() {
    someService.doSomething();
  }
}



@Slf4j
@Service
public class TaskStarter implements InitializingBean {

  @Autowired
  BeanFactory beanFactory;

  @Autowired
  RedissonClient redissonClient;

  @Override
  public void afterPropertiesSet() throws Exception {
    WorkerOptions options = WorkerOptions
        .defaults()
        .beanFactory(beanFactory)
        .workers(1)
        .addListener((TaskStartedListener) taskId -> log.info("Scheduled task with taskId={} started", taskId))
        .addListener((TaskFailureListener) (taskId, exception) -> log.info("Scheduled task with taskId={} failed", taskId))
        .taskTimeout(60, TimeUnit.SECONDS);

    var executor = redissonClient.getExecutorService(EXECUTOR_NAME);
    executor.registerWorkers(options);

    executor.schedule(new Task(), 1, TimeUnit.SECONDS);
  }
}

public class Task implements Runnable, Serializable {

  @Autowired private RedissonClient redissonClient;
  @Autowired private SomeService someService;

  public Task() {
  }

  @Override
  public void run() {
    someService.doSomething();
  }
}
```

This gives following error:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-01-20 21:03:17.695  INFO 15619 --- [           main] com.example.redisson.DemoApplication     : Starting DemoApplication using Java 11 on.....
2022-01-20 21:03:17.697  INFO 15619 --- [           main] com.example.redisson.DemoApplication     : No active profile set, falling back to default profiles: default
2022-01-20 21:03:18.256  INFO 15619 --- [           main] org.redisson.Version                     : Redisson 3.16.7
2022-01-20 21:03:18.276  WARN 15619 --- [           main] i.n.r.d.DnsServerAddressStreamProviders  : Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
2022-01-20 21:03:18.526  INFO 15619 --- [sson-netty-2-18] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 127.0.0.1/127.0.0.1:6379
2022-01-20 21:03:18.600  INFO 15619 --- [sson-netty-2-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 127.0.0.1/127.0.0.1:6379
2022-01-20 21:03:18.741  INFO 15619 --- [           main] org.redisson.Version                     : Redisson 3.16.7
2022-01-20 21:03:18.792  INFO 15619 --- [sson-netty-5-17] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 127.0.0.1/127.0.0.1:6379
2022-01-20 21:03:18.820  INFO 15619 --- [sson-netty-5-14] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 127.0.0.1/127.0.0.1:6379
2022-01-20 21:03:18.828  INFO 15619 --- [           main] org.redisson.RedissonNode                : 8 map reduce worker(s) registered
2022-01-20 21:03:18.835  INFO 15619 --- [           main] org.redisson.RedissonNode                : 1 worker(s) registered for ExecutorService with 'spring_test' name
2022-01-20 21:03:18.835  INFO 15619 --- [           main] org.redisson.RedissonNode                : Redisson node started!
2022-01-20 21:03:18.921  INFO 15619 --- [           main] com.example.redisson.DemoApplication     : Started DemoApplication in 1.54 seconds (JVM running for 2.355)
2022-01-20 21:03:19.777  INFO 15619 --- [   redisson-3-4] com.example.redisson.TaskStarter         : Scheduled task with taskId=015c057620e0e95b383063dafe99e9db02 started
2022-01-20 21:03:19.798 ERROR 15619 --- [   redisson-3-4] o.r.e.RedissonExecutorRemoteService      : Can't execute: RemoteServiceRequest [requestId=015c057620e0e95b383063dafe99e9db02, methodName=scheduleRunnable, signature=[3143983607692024834, -697753227114447020], args=[org.redisson.executor.params.ScheduledParameters@729c76b3], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=3600000], date=1642705398721]

java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:106) ~[redisson-3.16.7.jar:3.16.7]
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:458) ~[redisson-3.16.7.jar:3.16.7]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.IllegalAccessError: class com.example.redisson.Task tried to access method com.example.redisson.SomeService.doSomething()V (com.example.redisson.Task is in unnamed module of loader org.redisson.executor.RedissonClassLoader @3ef295fe; com.example.redisson.SomeService is in unnamed module of loader 'app')
	at com.example.redisson.Task.run(Task.java:17) ~[classes/:na]
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:349) ~[redisson-3.16.7.jar:3.16.7]
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:368) ~[redisson-3.16.7.jar:3.16.7]
	at org.redisson.executor.TasksRunnerService.scheduleRunnable(TasksRunnerService.java:203) ~[redisson-3.16.7.jar:3.16.7]
	... 13 common frames omitted

2022-01-20 21:03:19.799  INFO 15619 --- [   redisson-3-4] com.example.redisson.TaskStarter         : Scheduled task with taskId=015c057620e0e95b383063dafe99e9db02 failed

```

I tried a couple of things,

- Supplying class loader to constructor of codec (MarshallingCodec) - no difference
- config.setUseThreadClassLoader(false) - no difference. It does not seem to be used at all TasksRunnerService 

See for full example: https://github.com/nylund/redisson-classloader-issue
Redisson version: 3.16.7

**Comment by mrniko** [comment]
java.lang.IllegalAccessError means that Task class loaded by a different classloader doesn't have an access to method with package level visibility.

Solution is to set public modifier to SomeService.doSomething() method.

  public void doSomething() {
    System.out.println("Hello");
  }

**Comment by nylund** [comment]
Thanks for the clarification. 

Is it a bug though that config.setUseThreadClassLoader(false) does not affect TasksRunnerService?

**Comment by mrniko** [comment]
Thread.currentThread().getContextClassLoader() returns ClassLoader class which doesn't allow to load custom classes. This feature can't be supported in TasksRunnerService
