### ISSUE TITLE
RMapCache EntryExpiredListener doesn't work after AWS ElastiCache failover

### ISSUE THREAD

**Issue by haoyishi** [redisson/redisson#4093]
**Expected behavior**
When AWS ElasticCache fails over, and redisson client automatically reconnects to ElastiCache, the `EntryExpiredListener` , which is added to RMapCache, should still get notified when an entry is expired.

**Actual behavior**
When AWS ElastiCache failed over, and redisson client reconnects, the `EntryExpiredListener` is not notified.
And we see logs like this
```
2022-01-20 17:48:32.645 INFO [redisson-netty-2-36] c.a.redis.RedissonClientManager.onDisconnect:180 :: Redisson client disconnected #1.
2022-01-20 17:48:48.631 ERROR [redisson-netty-2-5] o.r.c.ReplicatedConnectionManager.lambda$run$2:132 :: connection timed out: redis-primary/xxx.xxx.95.146:6379
io.netty.channel.ConnectTimeoutException: connection timed out: redis-primary/xxx.xxx.95.146:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2022-01-20 17:49:04.637 ERROR [redisson-netty-2-37] o.r.c.ReplicatedConnectionManager.lambda$run$2:132 :: connection timed out: redis-primary/xxx.xxx.95.146:6379
io.netty.channel.ConnectTimeoutException: connection timed out: redis-primary/xxx.xxx.95.146:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce or test case**
1. Connect to AWS ElastiCache with Replicated Mode
2. Create RMapCache, add EntryExpiredListener
3. Test with correct behavior:
--3.1 Save key/value pair into RMapCache with ttl= 5 minutes
--3.2 When the key/value expires, `EntryExpiredListener` is notified
4. Test with Failover
--4.1 Save a new Key/value pair into RMapCache with ttl= 5 minutes
--4.2 Failover ElastiCache Primary node
--4.3 After Redisson client reconnects, `EntryExpiredListener` is NOT notified
--4.4 Continue to add another new key/value pair with ttl = 5 minutes
--4.5 When the new key/value pair ttl expires, `EntryExpiredListener` is NOT notified

**Redis version**
AWS ElastiCache
Engine: Redis
Engine Version Compatible with: 6.0.5
1 Primary Node + 1 Replica Node
**Redisson version**
3.16.0

**Redisson configuration**
useReplicatedServers
node address: [redis-primary:6379, redis-replica:6379 ]
connect timeout: 20000
maxCleanUpDelay: 60
timeout: 10000
retry interval: 2000
retry attempt: 6
netty threads: 64

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version. Might be cause by this https://github.com/redisson/redisson/issues/3736

Can you set `trace` logging level for `org.redisson` package, update to 3.16.8 and share log output?

**Comment by haoyishi** [comment]
Hi Nikita,
I upgraded the redisson version to `3.16.8`. When I tested with elati-cache failover, the issue is still there, we cannot receive the notifications when the entry ttl arrives
And we also found something interesting, perhaps related to this issue. We use redis cli connects to redis, and use `pubsub channels` to show all the channels. After failover, some of the `*expired`, `*removed` channels disappeared.
For example, 
#### before failover
```

127.0.0.1:6379> pubsub channels
 1) "redisson_delay_queue_channel:{tasksToExecute}"
 2) "admin_ui_topic"
 3) "redisson_map_cache_removed:{ConversationSession}"
 4) "broadcast"
 5) "redisson_map_cache_removed:{UniversalSession}"
 6) "internal-service_routingTableTopic"
 7) "RemoteExecutionRequest"
 8) "ui"
 9) "redisson_map_cache_expired:{UniversalSession}"
10) "channel_topic"
11) "redisson_map_cache_expired:{ConversationSession}"
12) "redisson_map_cache_expired:{ConversationInactivityTimer}"
13) "__keyevent@0__:expired"
14) "RemoteExecutionResponse"
```

#### After failover
```
127.0.0.1:6379> pubsub channels
 1) "RemoteExecutionRequest"
 2) "__keyevent@0__:expired"
 3) "admin_ui_topic"
 4) "ui"
 5) "internal-service_routingTableTopic"
 6) "RemoteExecutionResponse"
 7) "redisson_map_cache_removed:{UniversalSession}"
 8) "broadcast"
 9) "channel_topic"
10) "redisson_delay_queue_channel:{tasksToExecute}"
```
We are interested in the cache called `ConversationSession`, to which we add expire & remove listeners. As you can see, after failover, the two channels are lost.
Could this be the reason?

**Comment by mrniko** [comment]
Can you try it again and share log with `TRACE` logging level for `org.redisson` package? In my case channels are always resubscribed.

**Comment by haoyishi** [comment]
[redisson_trace_elasti-cache_failover.log](https://github.com/redisson/redisson/files/8065086/redisson_trace_elasti-cache_failover.log)
This is the log from failover to reconnect.

**Comment by haoyishi** [comment]
I tested again. Here is the log. And I checked the topics after failover, the topic for `conversationsession` was still missing.
[redisson_trace_elasti-cache_failover.log](https://github.com/redisson/redisson/files/8065223/redisson_trace_elasti-cache_failover.log)

**Comment by haoyishi** [comment]
This is the trace log.
[redisson_trace_elasti-cache_failover.log](https://github.com/redisson/redisson/files/8073477/redisson_trace_elasti-cache_failover.log)

**Comment by mrniko** [comment]
Unable to reproduce with the latest version.

RMapCache entries are evicted on Redisson side. This process isn't real-time and delay between cleanups could be adjusted with `maxCleanUpDelay` and `minCleanUpDelay` parameters.

https://github.com/redisson/redisson/wiki/2.-Configuration#mincleanupdelay
https://github.com/redisson/redisson/wiki/2.-Configuration#maxcleanupdelay

In your case I would recommend to set maxCleanUpDelay to 30. To check that everything works fine.
