### ISSUE TITLE
Quarkus environment variables not working

### ISSUE THREAD

**Issue by Adler95** [redisson/redisson#4098]
Some environment variables are not working.

```
quarkus:
  redisson:
    single-server-config:
      address: 
      - "redis://127.0.0.1:16379"
```
In case we want to override this value with the environment variable: QUARKUS_REDISSON_SINGLESERVERCONFIG_ADDRESS, the configuration fails to load. It seems that: https://github.com/redisson/redisson/issues/3943 didn't completely solve issues with environment variables.

**Expected behavior**
Configuration should successfully load when using ENV variables.

**Actual behavior**

```
Caused by: javax.enterprise.event.ObserverException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "singleserverconfig" (class org.redisson.config.Config), not marked as ignorable (23 known properties: "eventLoopGroup", "maxCleanUpDelay", "nettyHook", "keepPubSubOrder", "nettyThreads", "threads", "transportMode", "singleServerConfig", "sentinelServersConfig", "reliableTopicWatchdogTimeout", "useScriptCache", "minCleanUpDelay", "connectionListener", "executor", "codec", "replicatedServersConfig", "clusterServersConfig", "useThreadClassLoader", "masterSlaveServersConfig", "addressResolverGroupFactory", "lockWatchdogTimeout", "cleanUpKeysAmount", "referenceEnabled"])
 at [Source: (StringReader); line: 4, column: 3] (through reference chain: org.redisson.config.Config["singleserverconfig"])
	at io.quarkus.arc.impl.EventImpl$ObserverExceptionHandler.lambda$static$0(EventImpl.java:542)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:322)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 13 more
```

**Steps to reproduce or test case**
- Setup Quarkus project
- Add redisson-quarkus-20 dependency
- Set environment variable: QUARKUS_REDISSON_SINGLESERVERCONFIG_ADDRESS

**Redis version**
6.2.6

**Redisson version**
```
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-quarkus-20</artifactId>
            <version>3.16.8</version>
        </dependency>
```

**Comment by mrniko** [comment]
The problem is in name. Unrecognized field "singleserverconfig", the field should be "singleServerConfig"

**Comment by Adler95** [comment]
Yes, I did try, but some SmallRye exception was thrown in that case, probably because this (i think?) doesn't follow MicroProfile specification (where only Alphanumeric and underscore characters are allowed)?

**Comment by mrniko** [comment]
can you try this one with double "_" ? QUARKUS_REDISSON_SINGLE__SERVER__CONFIG_ADDRESS

**Comment by Adler95** [comment]
QUARKUS_REDISSON_SINGLE__SERVER__CONFIG_ADDRESS produces this error:

```
Caused by: javax.enterprise.event.ObserverException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "single" (class org.redisson.config.Config), not marked as ignorable (23 known properties: "eventLoopGroup", "maxCleanUpDelay", "nettyHook", "keepPubSubOrder", "nettyThreads", "threads", "transportMode", "singleServerConfig", "sentinelServersConfig", "reliableTopicWatchdogTimeout", "useScriptCache", "minCleanUpDelay", "connectionListener", "executor", "codec", "replicatedServersConfig", "clusterServersConfig", "useThreadClassLoader", "masterSlaveServersConfig", "addressResolverGroupFactory", "lockWatchdogTimeout", "cleanUpKeysAmount", "referenceEnabled"])
 at [Source: (StringReader); line: 1, column: 34] (through reference chain: org.redisson.config.Config["single"])
	at io.quarkus.arc.impl.EventImpl$ObserverExceptionHandler.lambda$static$0(EventImpl.java:542)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:322)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
```

**Comment by mrniko** [comment]
Fixed. Now QUARKUS_REDISSON_SINGLESERVERCONFIG_ADDRESS should work.
