### ISSUE TITLE
While run task Unable to inject Spring beans

### ISSUE THREAD

**Issue by cloudgyb** [redisson/redisson#4122]
My config class：
```java
@Configuration(proxyBeanMethods = false)
public class DistributedExecutorServiceConfig {
    @Bean(destroyMethod = "")
    public RScheduledExecutorService executorService(RedissonClient redissonClient, ConfigurableListableBeanFactory beanFactory) {
        ExecutorOptions defaults = ExecutorOptions.defaults()
                .taskRetryInterval(2, TimeUnit.SECONDS);
        RScheduledExecutorService executorService = redissonClient
                .getExecutorService("alarm-task-executor", defaults);
        WorkerOptions workerOptions = WorkerOptions.defaults().workers(5).beanFactory(beanFactory);
        executorService.registerWorkers(workerOptions);
        if (executorService.isShutdown()) {
            executorService.delete();
            executorService = redissonClient.getExecutorService("alarm-task-executor", defaults);
            executorService.registerWorkers(workerOptions);
        }
        return executorService;
    }
}
```

my task class:
```java
public class AlarmExceptionRequestDistributedJob implements Runnable, Serializable {
    @JsonIgnore
    private final Logger logger = LoggerFactory.getLogger(getClass());
    @JsonIgnore
    private final String datePattern = "yyyy-MM-dd HH:mm:ss.SSS";
    @JsonIgnore
    private transient final ThreadLocal<SimpleDateFormat> tlDateFormat = ThreadLocal.withInitial(() -> new SimpleDateFormat(datePattern));
    private static final String esProtectiveLogIndex = Constants.ES_PROTECTIVE_LOG_INDEX;
    private AlarmPolicyDTO alarmPolicyDTO;
    @JsonIgnore
    @Autowired
    private BizProtectedObjectMapper bizProtectedObjectMapper;
    @JsonIgnore
    @Autowired
    private EmailSendService emailSendService;
    @JsonIgnore
    @Autowired
    private AliyunSMService aliyunSMService;

    /**
     * 不要删除这个空构造函数，在Jackson序列化时要用
     */
    public AlarmExceptionRequestDistributedJob() {
    }

    public AlarmExceptionRequestDistributedJob(AlarmPolicyDTO alarmPolicyDTO) {
        this.alarmPolicyDTO = alarmPolicyDTO;
    }

    @Override
    public void run() {
        AlarmPolicyDTO alarmPolicy = alarmPolicyDTO;
        BizAlarmPolicy.AlarmType type = alarmPolicy.getType();
        if (!type.equals(BizAlarmPolicy.AlarmType.EXCEPTION_REQUEST)) {
            return;
        }
        Long protectedId = alarmPolicy.getProtectedId();
        //BizProtectedObjectMapper protectedObjectMapper = beanFactory.getBean(BizProtectedObjectMapper.class);
        BizProtectedObject bizProtectedObject = bizProtectedObjectMapper.selectById(protectedId);
        if (bizProtectedObject == null)
            return;
        //omit...
    }
}
```

**then when task running，throw exception：**
```java
2022-02-08 18:52:57.107 ERROR 7748 [  redisson-3-16] (ssonExecutorRemoteService.java:120) : Can't execute: RemoteServiceRequest [requestId=01a9496cb666c612eac5ceb6de3c1b70e6, methodName=scheduleAtFixedRate, signature=[2954431956196527280, 5708544082777223948], args=[org.redisson.executor.params.ScheduledAtFixedRateParameters@5f589620], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1644317002124]
 
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:106)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:324)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:342)
	at org.redisson.executor.TasksRunnerService.scheduleAtFixedRate(TasksRunnerService.java:128)
	... 12 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'null': Unsatisfied dependency expressed through field 'bizProtectedObjectMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.processInjection(AutowiredAnnotationBeanPostProcessor.java:430)
	at org.redisson.executor.SpringTasksInjector.inject(SpringTasksInjector.java:38)
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:319)
	... 14 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 18 common frames omitted

2022-02-08 18:52:59.206 ERROR 7748 [   redisson-3-2] (ssonExecutorRemoteService.java:120) : Can't execute: RemoteServiceRequest [requestId=01a9496cb666c612eac5ceb6de3c1b70e6, methodName=scheduleAtFixedRate, signature=[2954431956196527280, 5708544082777223948], args=[org.redisson.executor.params.ScheduledAtFixedRateParameters@4b93023a], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1644317002124]
 
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:106)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:324)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:342)
	at org.redisson.executor.TasksRunnerService.scheduleAtFixedRate(TasksRunnerService.java:128)
	... 12 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'null': Unsatisfied dependency expressed through field 'bizProtectedObjectMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.processInjection(AutowiredAnnotationBeanPostProcessor.java:430)
	at org.redisson.executor.SpringTasksInjector.inject(SpringTasksInjector.java:38)
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:319)
	... 14 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 18 common frames omitted

2022-02-08 18:53:01.314 ERROR 7748 [   redisson-3-4] (ssonExecutorRemoteService.java:120) : Can't execute: RemoteServiceRequest [requestId=01a9496cb666c612eac5ceb6de3c1b70e6, methodName=scheduleAtFixedRate, signature=[2954431956196527280, 5708544082777223948], args=[org.redisson.executor.params.ScheduledAtFixedRateParameters@4b9f10ae], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1644317002124]
 
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:106)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:324)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:342)
	at org.redisson.executor.TasksRunnerService.scheduleAtFixedRate(TasksRunnerService.java:128)
	... 12 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'null': Unsatisfied dependency expressed through field 'bizProtectedObjectMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.processInjection(AutowiredAnnotationBeanPostProcessor.java:430)
	at org.redisson.executor.SpringTasksInjector.inject(SpringTasksInjector.java:38)
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:319)
	... 14 common frames omitted
````
Expect your help，thanks！

**Comment by mrniko** [comment]
> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'null': Unsatisfied dependency expressed through field 'bizProtectedObjectMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}

I think you need to check your dependencies.

**Comment by cloudgyb** [comment]
> I want to know how to solve this problem. I have encountered the same problem?

I still haven't solved it！

**Comment by CarryWll** [comment]
> > Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'null': Unsatisfied dependency expressed through field 'bizProtectedObjectMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.cssth.web.biz.dao.mapper.BizProtectedObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@com.fasterxml.jackson.annotation.JsonIgnore(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
> 
> I think you need to check your dependencies.

Can you give an example of configuring Spring beans dependencies when run task?
