### ISSUE TITLE
Exception from redis : MasterConnectionPool no available Redis entries

### ISSUE THREAD

**Issue by sreenivasnarayan** [redisson/redisson#4136]
org.redisson.client.RedisConnectionException: MasterConnectionPool no available Redis entries.  Disconnected hosts: [/10.5.4.3:7100]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:195)
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:31)
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:392)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:675)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:489)
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:538)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)

Engine version: 6.x

**Comment by mrniko** [comment]
Can you share redisson logs with `trace` logging level for `org.redisson` package?
