### ISSUE TITLE
Fair Lock attempt to compare nil with number

### ISSUE THREAD

**Issue by sahilm-ti** [redisson/redisson#4153]
In my code, I am trying to acquire a fair lock with a fixed waitTime and leaseTime as so
```kotlin
fairLock.tryLockAsync(waitTime, leaseTime, timeUnit, ID)
```
Occasionally, I face this error
```
ERR Error running script (call to f_762bfafa6be221431a0b668685dd15c926483619): @user_script:1: user_script:1: attempt to compare nil with number. channel: [id: 0xacec2457, L:/10.60.19.200:56300 - R:[redisURI]/[redisURI]:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@7b16e88f[Not completed], params: [while true do local firstThreadId2 = redis.call('lindex', KEYS[2], 0);if firstThreadId2 == false the..., 3, lockName, redisson_lock_queue:{lockName}, redisson_lock_timeout:{lockName}, 36000, 8fe4a548-fa9f-42a3-8482-1d24d038f24f:830040972163392702, 36000, 1645538812661], stack trace: org.redisson.client.RedisException: ERR Error running script (call to f_762bfafa6be221431a0b668685dd15c926483619): @user_script:1: user_script:1: attempt to compare nil with number. channel: [id: 0xacec2457, L:/10.60.19.200:56300 - R:[redisURI]/[redisURI]:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@7b16e88f[Not completed], params: [while true do local firstThreadId2 = redis.call('lindex', KEYS[2], 0);if firstThreadId2 == false the..., 3, lockName, redisson_lock_queue:{lockName}, redisson_lock_timeout:{lockName}, 36000, 8fe4a548-fa9f-42a3-8482-1d24d038f24f:830040972163392702, 36000, 1645538812661]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:271)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I also see a queue is being formed for the fair lock, even though it is not currently held.  
The waiting requests eventually time out after the waitTime expires.
The queue is being formed for the same lock that this exception is being thrown for.  
At times, I have also seen the queue being formed for no reason without this error being thrown. 

I am not able to reproduce this locally, 

**Redis version**

6.x

**Redisson version**

3.16.8

**Redisson configuration**

```kotlin
config.useSingleServer().apply {
    path.toIntOrNull()?.also {
        database = it
    } ?: run {
        logger.warn { "Unable to parse database number: $path from redis configuration" }
    }
}
config.nettyThreads = 64
```

**Comment by x0pHeT** [comment]
I have gotten the same error today.
```
org.redisson.client.RedisException: ERR Error running script (call to f_762bfafa6be221431a0b668685dd15c926483619): @user_script:1: user_script:1: attempt to compare nil with number. channel: [id: 0xb13b069f, L:/10.233.67.253:33442 - R:10.243.88.103/10.243.88.103:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@175567cb[Not completed], params: [while true do local firstThreadId2 = redis.call('lindex', KEYS[2], 0);if firstThreadId2 == false then break;end;local timeout = tonumber(redis.call('zscore', KEYS[3], firstThreadId2));if timeout <= tonumber(ARGV[4]) then redis.call('zrem', KEYS[3], firstThreadId2);redis.call('lpop', KEYS[2]);else break;end;end;if (redis.call('exists', KEYS[1]) == 0) and ((redis.call('exists', KEYS[2]) == 0) or (redis.call('lindex', KEYS[2], 0) == ARGV[2])) then redis.call('lpop', KEYS[2]);redis.call('zrem', KEYS[3], ARGV[2]);local keys = redis.call('zrange', KEYS[3], 0, -1);for i = 1, #keys, 1 do redis.call('zincrby', KEYS[3], -tonumber(ARGV[3]), keys[i]);end;redis.call('hset', KEYS[1], ARGV[2], 1);redis.call('pexpire', KEYS[1], ARGV[1]);return nil;end;if redis.call('hexists', KEYS[1], ARGV[2]) == 1 then redis.call('hincrby', KEYS[1], ARGV[2],1);redis.call('pexpire', KEYS[1], ARGV[1]);return nil;end;local timeout = redis.call('zscore', KEYS[3], ARGV[2]);if timeout ~= false then return timeout - tonumbe..., 3, locked-cnum-access-lock-rnd, redisson_lock_queue:{locked-cnum-access-lock-rnd}, redisson_lock_timeout:{locked-cnum-access-lock-rnd}, 30000, 85d72c9b-2b8d-47a2-9288-b6f92c5d51e1:225, 3, 1715931934757]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:414)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:290)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:228)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Redisson version
org.redisson:redisson-spring-boot-starter:3.27.2

Redis version
6.2.10

**Comment by mrniko** [comment]
Fixed. Thanks for report
