### ISSUE TITLE
Exception when two modules use different Redisson version (3.16.1 and 3.16.8)

### ISSUE THREAD

**Issue by lehuuthanh5** [redisson/redisson#4158]
Hi,
I have 2 module A and B, using same Redisson 3.16.1. The modules are using a RLocalCachedMap. I want to change Redisson version of B server to 3.16.8. And I'm facing with exception.
```
java.lang.IndexOutOfBoundsException: readerIndex(21) + length(1668246830) exceeds writerIndex(264): UnpooledSlicedByteBuf(ridx: 21, widx: 264, cap: 264/264, unwrapped: PooledUnsafeDirectByteBuf(ridx: 672, widx: 896, cap: 1024))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903)
	at org.redisson.cache.LocalCachedMessageCodec.lambda$new$0(LocalCachedMessageCodec.java:68)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:383)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:427)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
```
I know that LocalCachedMessageCodec encode and decode methods were changed for a [reason](https://github.com/redisson/redisson/commit/dd435b1b812a1ec0c377144a70a51f99713c2a94). And this exception is thrown when LocalCachedMap updated.
I wonder that does it have any way to run server A and B with different Redisson version?
P/s: That is my example. Now I have more than 10 modules are using Redisson and I just want to update some of them
Thanks

**Comment by mrniko** [comment]
> I wonder that does it have any way to run server A and B with different Redisson version?

I'm afraid no.
