### ISSUE TITLE
Using any Codec that isn't MarshallingCodec or SerializationCodec with RRemoteService timeout on reply

### ISSUE THREAD

**Issue by Oberonc** [redisson/redisson#4163]
Simplest service interface:
```
public interface IService {
  void ping();
}
```
Service Implementation:
```
public class MyService implements IService {
  public MyService() {
    RedissonClient client = Redisson.create();

    // register myself as a remote service
    client.getRemoteService(JsonJacksonCodec.INSTANCE).register(IService.class, this);
  }

  public void ping() {
    Logger.getGlobal().info("I was pinged");
  }
}
```
Client:
```
public class Client {
  public Client() {
    RedissonClient client = Redisson.create();

    IService service = client.getRemoteService(JsonJacksonCodec.INSTANCE).get(IService.class);

    // test communication with "ping"
    service.ping();
    Logger.getGlobal().info("pinged");
  }
}
```
Service is instantiated locally and then the client (both on same JVM, Redis server is running locally with default Ubuntu 20 configuration)

**Expected behavior**
1. Log to have the line "I was pinged"
2. Log to have the line "pinged"
3. No timeout or exceptions

**Actual behavior**
1. Log has "I was pinged"
2. Exception:
> org.redisson.remote.RemoteServiceTimeoutException: No response after 30000ms for request: RemoteServiceRequest [requestId=46edfd042fba0b14bf6469bb490c0d42, methodName=ping, signature=[-5212114190830492821, -5560568237385073498], args=null, options=RemoteInvocationOptions[ackTimeoutInMillis=1000, executionTimeoutInMillis=30000], date=1645976606667]
	at org.redisson.remote.SyncRemoteProxy$1.invoke(SyncRemoteProxy.java:133)
	at jdk.proxy4/jdk.proxy4.$Proxy47.ping(Unknown Source)

**Steps to reproduce or test case**
Use code above

**Redis version**
```
$ redis-server --version
Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923
```
**Redisson version**
```
<!-- Redis client: Redisson -->
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.16.4</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.13.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.13.0</version>
		</dependency>
```

**Redisson configuration**
As seen in the code, bare minimal

**Comment by mrniko** [comment]
Unable to reproduce. Below is the code:

```java
        RedissonClient r1 = createInstance();
        r1.getRemoteService(JsonJacksonCodec.INSTANCE).register(RemoteInterface.class, new RemoteImpl());
        
        RedissonClient r2 = createInstance();
        RemoteInterface ri = r2.getRemoteService(JsonJacksonCodec.INSTANCE).get(RemoteInterface.class);
        
        ri.voidMethod("someName", 100L);
        Long s = ri.resultMethod(100L);
        assertThat(s).isEqualTo(200);
```
