### ISSUE TITLE
RBlockingDeque java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by xudaqing19940205** [redisson/redisson#4186]
the java program started with an error message :

`java.io.IOException: java.lang.ClassNotFoundException: com.test.delay.queue.vo.ExpireOrder
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:148)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:383)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:427)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.cheche365.partner.service.vo.ExpireOrder
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:129)
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1048)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231)
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
	at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:146)
	... 25 common frames omitted`

this is my code :
`@Component
public class ThreadPoolTaskExecutorRunner implements ApplicationRunner {

    private final ThreadPoolTaskExecutor threadPoolTaskExecutor;

    public ThreadPoolTaskExecutorRunner(ThreadPoolTaskExecutor threadPoolTaskExecutor) {
        this.threadPoolTaskExecutor = threadPoolTaskExecutor;
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        try {
            log.info("ThreadPoolTaskExecutorRunner start");
            threadPoolTaskExecutor.execute(orderTaskFactory.createExpireOrderTask());
            log.info("ThreadPoolTaskExecutorRunner end");
        } catch (Exception e) {
            log.error("ThreadPoolTaskExecutorRunner fail, e : {}", ExceptionUtils.getStackTrace(e));
        }
    }
}`

`
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Slf4j
public class ExpireOrderTask implements Runnable{

    private IDelayQueueService<ExpireOrder> iDelayQueueService;

    @Override
    public void run() {

        while (true){
            try {
                log.info("开始处理订单关闭任务");
                ExpireOrder needCloseExpireOrder = iDelayQueueService.take(ORDER_DELAY_QUEUE);
                log.info("开始处理订单关闭任务param : {}",JSONObject.toJSONString(needCloseExpireOrder));
            } catch (InterruptedException e) {
                log.error("关闭订单失败:{}", ExceptionUtils.getStackTrace(e));
            }
        }
    }
}`

`@Service
public class DelayQueueServiceImpl<T> implements IDelayQueueService<T> {

    private final RedissonClient redissonClient;

    public DelayQueueServiceImpl(RedissonClient redissonClient) {
        this.redissonClient = redissonClient;
    }

    @Override
    public void offerSeconds(T data, long time, String queueName) {
        offer(data, time, TimeUnit.SECONDS, queueName);
    }

    @Override
    public void offer(T data, long time, TimeUnit timeUnit, String queueName) {
        findDelayQueue(queueName).offerAsync(data, time < 0 ? 0 : time, timeUnit);
    }

    @Override
    public T take(String queueName) throws InterruptedException {
        RBlockingDeque<T> blockingQueue = findBlockingQueue(queueName);
        RDelayedQueue<T> delayQueue = findDelayQueue(blockingQueue);
        return blockingQueue.take();
    }

    @Override
    public RBlockingDeque<T> findBlockingQueue(String queueName) {
        return redissonClient.getBlockingDeque(queueName);
    }

    @Override
    public RDelayedQueue<T> findDelayQueue(String queueName) {
        return redissonClient.getDelayedQueue(findBlockingQueue(queueName));
    }

    @Override
    public RDelayedQueue<T> findDelayQueue(RBlockingDeque<T> blockingQueue) {
        return redissonClient.getDelayedQueue(blockingQueue);
    }
}`

I changed the package path of ExpireOrder.class , but I did not find the ExpireOrder task with the old path when I queried redis,now the task is blocking , i need help

**Comment by mrniko** [comment]
You can try to supply a proper classloader to MarshallingCodec or set `useThreadClassLoader` setting to false.
