### ISSUE TITLE
ERROR org.redisson.RedissonReliableTopic - Unable to update subscriber status

### ISSUE THREAD

**Issue by AoElite** [redisson/redisson#4190]
```java
[redisson-netty-2-4] ERROR org.redisson.RedissonReliableTopic - Unable to update subscriber status
org.redisson.client.RedisException: ERR Error running script (call to f_b30befcbe516660e944d8da894811726e3530705): @user_script:1: user_script:1: attempt to compare nil with number. channel: [id: 0x1a2440a1, L:/172.18.0.3:47306 - R:redis-17195.c246.us-east-1-4.ec2.cloud.redislabs.com/3.81.184.117:17195] command: (EVAL), promise: java.util.concurrent.CompletableFuture@24a405b1[Not completed, 1 dependents], params: [local r = redis.call('zscore', KEYS[2], ARGV[2]); if r ~= false then local value = redis.call('incr'..., 5, proxy_events, {proxy_events}:subscribers, {proxy_events}:map, {proxy_events}:counter, {proxy_events}:timeout, 1647932945401-0, c518c60c7e632bf669475666d72b7265, 1647932945401]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
Not to throw a error

**Actual behavior**
A error occuring

**Steps to reproduce or test case**
Unsure, just randomly happened

**Redis version**
6.2.3

**Redisson version**
3.17.0

**Redisson configuration**
```java
Config config = new Config();
        JsonJacksonCodec codec = new JsonJacksonCodec();
        config.setCodec(codec);
        //
        config.setKeepPubSubOrder(true);
        config.setThreads(4);
        config.setNettyThreads(8);
        //
        var msc = config.useSingleServer();
        msc.setUsername(user);
        msc.setPassword(pass);
        //
        msc.setTcpNoDelay(true);
        msc.setKeepAlive(true);
        msc.setConnectionMinimumIdleSize(4);
        msc.setConnectionPoolSize(32);
        //
        msc.setSubscriptionConnectionMinimumIdleSize(1);
        msc.setSubscriptionConnectionPoolSize(32);
        msc.setSubscriptionsPerConnection(5);
        //
        msc.setTimeout(3000);
        msc.setConnectTimeout(10000);
        msc.setRetryAttempts(3);
        msc.setRetryInterval(1500);
        msc.setPingConnectionInterval(10000);
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
