### ISSUE TITLE
version:3.13.6 redisClient.get error Failed to submit a listener notification task. Event loop shut down?

### ISSUE THREAD

**Issue by TA961215** [redisson/redisson#4228]
redisson (version 3.13.6) 
2022-04-13 11:20:37.616 [<10386682678285824><0>] ERROR 7294 {magenta} --- [ol-16-worker-12] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:842) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:499) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) [netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
        at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:153) [redisson-3.13.6.jar!/:3.13.6]
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) ~[redisson-3.13.6.jar!/:3.13.6]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) [netty-common-4.1.65.Final.jar!/:4.1.65.Final]
        at org.redisson.misc.RedissonPromise.onComplete(RedissonPromise.java:181) ~[redisson-3.13.6.jar!/:3.13.6]
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:139) [redisson-3.13.6.jar!/:3.13.6]
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:605) ~[redisson-3.13.6.jar!/:3.13.6]
        at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:368) ~[redisson-3.13.6.jar!/:3.13.6]
        at org.redisson.RedissonBucket.getAsync(RedissonBucket.java:109) ~[redisson-3.13.6.jar!/:3.13.6]
        at org.redisson.RedissonBucket.get(RedissonBucket.java:104) ~[redisson-3.13.6.jar!/:3.13.6]
        at com.vchangyi.boot.redis.client.RedisClient.get(RedisClient.java:109) ~[spring-micro-component-redis-1.0.0-RC2.jar!/:na]
        at com.wuxianji.scrm.analysis.qy.impl.QyRemoteService.getAccessToken(QyRemoteService.java:179) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at com.wuxianji.scrm.analysis.qy.impl.QyRemoteService.sendRequest(QyRemoteService.java:227) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at com.wuxianji.scrm.analysis.qy.impl.QyRemoteService.executeNormal(QyRemoteService.java:169) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at sun.reflect.GeneratedMethodAccessor566.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
        at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499) ~[spring-cloud-context-2.2.9.RELEASE.jar!/:2.2.9.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
        at com.wuxianji.scrm.analysis.qy.impl.QyRemoteService$$EnhancerBySpringCGLIB$$bb9234e2.executeNormal(<generated>) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at com.wuxianji.scrm.analysis.qy.impl.StatisticsServiceImpl.getUserBehavior(StatisticsServiceImpl.java:38) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at com.wuxianji.scrm.analysis.shcedule.MembersEveryDayStatisticsTaskJob.getUserBehavior(MembersEveryDayStatisticsTaskJob.java:623) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at com.wuxianji.scrm.analysis.shcedule.MembersEveryDayStatisticsTaskJob.lambda$getData$4(MembersEveryDayStatisticsTaskJob.java:281) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_202]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_202]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_202]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[na:1.8.0_202]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:404) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[na:1.8.0_202]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[na:1.8.0_202]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[na:1.8.0_202]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:1.8.0_202]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_202]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[na:1.8.0_202]
        at com.wuxianji.scrm.analysis.shcedule.MembersEveryDayStatisticsTaskJob.getData(MembersEveryDayStatisticsTaskJob.java:265) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at com.wuxianji.scrm.analysis.shcedule.MembersEveryDayStatisticsTaskJob.lambda$null$2(MembersEveryDayStatisticsTaskJob.java:247) ~[scrm-analysis-service-1.0-SNAPSHOT.jar!/:na]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_202]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_202]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_202]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[na:1.8.0_202]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_202]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_202]

**Comment by mrniko** [comment]
Check if you don't shutdown Redisson instance. Can you share test code to reproduce?

**Comment by afoxsss** [comment]
你好我想问一下这个问题你解决了吗
