### ISSUE TITLE
NullPointerException when destroy RMapCache

### ISSUE THREAD

**Issue by vladdec** [redisson/redisson#4230]
**Expected behavior**
destroyed RMapCache without exception

**Actual behavior**
Randomly NullPointerException when RMapCache.destroy()
You wrote in https://github.com/redisson/redisson/issues/3147, the only reason is null value used as name. So befeore calling destroy I log RMapCache.getName() and it is not null. In logs is name of used map. 

**Steps to reproduce or test case**

java.lang.NullPointerException: null
	at org.redisson.eviction.EvictionScheduler.remove(EvictionScheduler.java:84) ~[redisson-3.17.0.jar:3.17.0]
	at org.redisson.RedissonMapCache.destroy(RedissonMapCache.java:2700) ~[redisson-3.17.0.jar:3.17.0]
	at myClass.process(myClass.java:44) [classes/:?]
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65) [camel-support-3.16.0.jar:3.16.0]
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:471) [camel-core-processor-3.16.0.jar:3.16.0]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:193) [camel-base-engine-3.16.0.jar:3.16.0]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64) [camel-base-engine-3.16.0.jar:3.16.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:184) [camel-core-processor-3.16.0.jar:3.16.0]
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:399) [camel-base-engine-3.16.0.jar:3.16.0]
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83) [camel-base-engine-3.16.0.jar:3.16.0]
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41) [camel-support-3.16.0.jar:3.16.0]
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:109) [camel-kafka-3.16.0.jar:3.16.0]
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:120) [camel-kafka-3.16.0.jar:3.16.0]
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:80) [camel-kafka-3.16.0.jar:3.16.0]
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:280) [camel-kafka-3.16.0.jar:3.16.0]
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:181) [camel-kafka-3.16.0.jar:3.16.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Redis version**

**Redisson version**
3.17.0

**Redisson configuration**
SentinelServersConfig sentinelServersConfig = redisConfig.useSentinelServers();
			List<String> sentinelAdresses = getSentinelAddresses();
			sentinelServersConfig
					.setUsername(config.getString("user"))
					.setPassword(config.getString("pass"))
					.setMasterName(config.getString("mymaster"))
					.setSslTruststore(new File(config.getString(REDIS_SSL_TRUSTSTORE_LOCATION)).toURI().toURL())
					.setSslTruststorePassword(config.getString(REDIS_SSL_TRUSTSTORE_PASSWORD))
					.setSslEnableEndpointIdentification(false)
					.setSentinelPassword(config.getString(REDIS_SENTINEL_PASSWORD))
					.setPassword(config.getString(REDIS_REDIS_PASSWORD))
					.setTimeout(config.getInt(REDIS_TIMEOUT, 3000))
					.setRetryAttempts(config.getInt(REDIS_RETRY_ATTEMPTS, 3))
					.setRetryInterval(config.getInt(REDIS_RETRY_INTERVAL, 1500))
					.setSentinelAddresses(sentinelAdresses);

**Comment by vladdec** [comment]
Update: Looks like the nullpointer is in EvictionScheduler 
row 84: task.getScheduledFuture() returns null

**Comment by mrniko** [comment]
Fixed! Thanks for report
