### ISSUE TITLE
NoClassDefFound error (can't decode data)

### ISSUE THREAD

**Issue by Rhodless** [redisson/redisson#4234]
I'm trying to store my Rank java class https://www.toptal.com/developers/hastebin/wanubimihu.java
But I have a `NoClassDefFound` exception. Of course I checked if the class existed in my jar file and it does, so the problem comes from decoding.

Here is my config:
```java
this.client = Redisson.create();
this.client.getConfig().setUseThreadClassLoader(false);
this.client.getConfig().setNettyThreads(5);
this.client.getConfig().setCodec(new SerializationCodec());

this.ranks = client.getSet("ranks");
```

Thank you.

**Comment by Rhodless** [comment]
Error: 
```
java.io.IOException: java.lang.ClassNotFoundException: fr.arashi.common.cache.Rank
    at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:148) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:383) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:427) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:427) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[?:?]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) ~[?:?]```

**Comment by mrniko** [comment]
Try to pass proper classloader to MarshallingCodec constructor

**Comment by Rhodless** [comment]
So 
```java
this.client.getConfig().setCodec(new MarshallingCodec());```
instead of
```java
this.client.getConfig().setCodec(new SerializationCodec());```
?

**Comment by Rhodless** [comment]
Anyways I tried it but I have the same error.

**Comment by mrniko** [comment]
Try to pass **proper classloader** to MarshallingCodec constructor
