### ISSUE TITLE
 command: (EXISTS)  java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by chengjungao** [redisson/redisson#4244]
2022-04-19 00:04:56,518 ERROR [redisson-netty-2-1] org.redisson.client.handler.CommandDecoder: Unable to decode data. channel: [id: 0xd17c82a2, L:/172.xx.xx.xx:37059 - R:172.xx.xx.xx/172.xx.xx.xx:8881], reply: ReplayingDecoderByteBuf(ridx=28, widx=28), command: (EXISTS), params: [QualityItem|xxxx]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:27)
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:23)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:432)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2022-04-19 00:04:56,639 ERROR [redisson-netty-2-1] org.redisson.client.handler.ErrorsLoggingHandler: Exception occured. Channel: [id: 0xd17c82a2, L:/172.xx.xx.xx:37059 - R:172.xx.xx.xx/172.xx.xx.xx:8881]
io.netty.handler.codec.DecoderException: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:27)
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:23)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:432)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 more

**Comment by chengjungao** [comment]
Redisson Version： 3.16.2
Redis Cluster ：6.2.4

**Comment by chengjungao** [comment]
I have String Key: xxx , value is Integer ;  but I  get the key  by redisson , got error : java.lang.NumberFormatException: For input string: "PONG"

**Comment by chengjungao** [comment]
This is an accidental phenomenon

**Comment by mrniko** [comment]
@chengjungao 

3.16.4 version has a bug fix - ping command sent for used connection. Please update to the latest version.

**Comment by ruslangm** [comment]
I still reproduced it in redisson version 3.52.0 and valkey version 7.2.11 @mrniko
