### ISSUE TITLE
redisson-all-3.16.1, redisson-tomcat-9-3.16.1 - unable to get value using redisson:tomcat_session  in java code

### ISSUE THREAD

**Issue by arumuk** [redisson/redisson#4253]
SerializationCodec redisSerializationCodec = new SerializationCodec();
Map<String, Object> session =redisson.getMap("redisson:tomcat_session:83C8CA5C1849307884D3683C540C0CDC", redisSerializationCodec);

The above code works fine in redisson-tomcat-8-3.7.5, redisson-all-3.7.5 version in tomcat lib.

After replacing the latest redisson-tomcat-9-3.16.1, redisson-all-3.16.1, the above code not read the value using the key and throw stream exception.

confg:
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://127.0.0.1:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0
   },
  "threads":0,
   "nettyThreads":0,
   "codec":{   
   "class":"org.redisson.codec.SerializationCodec"   
   }
}

**Comment by mrniko** [comment]
Can you share full stacktrace of the exception?

**Comment by arumuk** [comment]
thanks for your quick reply 👍 
****using old jar, the  data save in redis in below format:**
127.0.0.1:6379> hgetall redisson:tomcat_session:05341D84D5470264E9C8129CBB6A3758
 1) "\xac\xed\x00\x05t\x00\x0ebusinessStream"
 2) "\xac\xed\x00\x05t\x00\x03CIE"
 3) "\xac\xed\x00\x05t\x00\rsession:isNew"
 4) "\xac\xed\x00\x05sr\x00\x11java.lang.Boolean\xcd r\x80\xd5\x9c\xfa\xee\x02\x00\x01Z\x00\x05valuexp\x00"
 5) "\xac\xed\x00\x05t\x00\x04user"
 6) "\xac\xed\x00\x05sr\x00'ucles.ccms.nativejava.pojos.user.CAUser\x0b\x9b\xc7a\x8d\xaa\xb0-\x02\x00\aI\x00\x15sessionTimeoutSecondsL\x00\x0ebusinessStreamt\x00\x12Ljava/lang/String;L\x00\ncreditorNoq\x00~\x00\x01L\x00\x05namest\x00,Lucles/ccms/nativejava/pojos/user/UserNames;L\x00\tpermitSett\x00.Lucles/ccms/nativejava/pojos/user/CAPermitSet;L\x00\x10subordinateNamest\x00\x13Ljava/util/HashSet;L\x00\x06userIdq\x00~\x00\x01xp\x00\x00\x03\x84t\x00\x03CIEpsr\x00*ucles.ccms.nativejava.pojos.user.UserNamesp\x18\xbb\x80\xf0\xe6L\xc3\x02\x00\x02L\x00\ruserLoginNameq\x00~\x00\x01L\x00\buserNameq\x00~\x00\x01xpt\x00\x0ecieAmAuthors01t\x00\rcieAmAuthors1sr\x00,ucles.ccms.nativejava.pojos.user.CAPermitSet\xf3\xa6\xde\xa1&u'\xd3\x02\x00\x03Z\x00\x0bisSuperUserL\x00\x10effectivePermitst\x00\x15Ljava/util/ArrayList;L\x00\x0bsourceRolesq\x00~\x00\x04xp\x00sr\x00\x13java.util.ArrayListx\x81\xd2\x1d\x99\xc7a\x9d\x03\x00\x01I\x00\x04sizexp\x00\x00\x00\rw\x04\x00\x00\x00\rsr\x00)ucles.ccms.nativejava.pojos.user.CAPermitl&\x0f\r\\\xbd\xc5K\x02\x00\x03L\x00\x0cachievableIdq\x00~\x00\x01L\x00\x0bpermitLevelt\x000Lucles/ccms/nativejava/pojos/user/CAPermitLevel;L\x00\npermitNamet\x00/Lucles/ccms/nativejava/pojos/user/CAPermitName;xpp~r\x00.ucles.ccms.nativejava.pojos.user.CAPermitLevel\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xr\x00\x0ejava.lang.Enum\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xpt\x00\x04READ~r\x00-ucles.ccms.nativejava.pojos.user.CAPermitName\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xq\x00~\x00\x15t\x00\x19LIBRARY_MANAGEMENT_SCREENsq\x00~\x00\x10pq\x00~\x00\x16~q\x00~\x00\x18t\x00\x0bTASK_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40~q\x00~\x00\x14t\x00\x05WRITE~q\x00~\x00\x18t\x00\x0eREPORTS_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00 ~q\x00~\x00\x18t\x00\x12ADVANCED_AUTHORINGsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00 ~q\x00~\x00\x18t\x00\rSEARCH_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x12ACHIEVABLES_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x0fTAXONOMY_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x19PROJECT_MANAGEMENT_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x18WORKFLOW_TEMPLATE_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\nTCP_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\nTET_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16q\x00~\x00\x19sq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16q\x00~\x00\x1cxsr\x00\x11java.util.HashSet\xbaD\x85\x95\x96\xb8\xb74\x03\x00\x00xpw\x0c\x00\x00\x00\x10?@\x00\x00\x00\x00\x00\x02~r\x00(ucles.ccms.nativejava.constants.CcmsRole\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xq\x00~\x00\x15t\x00\x1bASSESSMENT_MATERIAL_MANAGER~q\x00~\x00Jt\x00\x06AUTHORxpt\x00\x1011003039800005b7"
 7) "\xac\xed\x00\x05t\x00\x18session:lastAccessedTime"
 8) "\xac\xed\x00\x05sr\x00\x0ejava.lang.Long;\x8b\xe4\x90\xcc\x8f#\xdf\x02\x00\x01J\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x01\x80E\xbeo\xd8"
 9) "\xac\xed\x00\x05t\x00\x18session:thisAccessedTime"
10) "\xac\xed\x00\x05sr\x00\x0ejava.lang.Long;\x8b\xe4\x90\xcc\x8f#\xdf\x02\x00\x01J\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x01\x80E\xbeo\xd8"
11) "\xac\xed\x00\x05t\x00\x0btaxonomyIds"
12) "\xac\xed\x00\x05sr\x000ucles.ccms.nativejava.pojos.taxonomy.TaxonomySet&\xc8\xd0\x9cv\x1cL\x97\x02\x00\x01L\x00\x0etaxonomyIdsSett\x00\x13Ljava/util/HashSet;xpsr\x00\x11java.util.HashSet\xbaD\x85\x95\x96\xb8\xb74\x03\x00\x00xpw\x0c\x00\x00\x00\x10?@\x00\x00\x00\x00\x00\x01t\x00$b74c9642-9960-4b31-81d2-681018c2df7ax"
13) "\xac\xed\x00\x05t\x00\x14session:creationTime"
14) "\xac\xed\x00\x05sr\x00\x0ejava.lang.Long;\x8b\xe4\x90\xcc\x8f#\xdf\x02\x00\x01J\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x01\x80E\xbehg"
15) "\xac\xed\x00\x05t\x00\x1bsession:maxInactiveInterval"
16) "\xac\xed\x00\x05sr\x00\x11java.lang.Integer\x12\xe2\xa0\xa4\xf7\x81\x878\x02\x00\x01I\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\a\b"
17) "\xac\xed\x00\x05t\x00\x06ticket"
18) "\xac\xed\x00\x05t\x03\x92DM_TICKET=T0JKIE5VTEwgMAoxMwp2ZXJzaW9uIElOVCBTIDAKMwpmbGFncyBJTlQgUyAwCjEKc2VxdWVuY2VfbnVtIElOVCBTIDAKMTA2NApjcmVhdGVfdGltZSBJTlQgUyAwCjE2NTA0Mzc1NDcKZXhwaXJlX3RpbWUgSU5UIFMgMAoxNjUwNDM4NDQ3CmRvbWFpbiBTVFJJTkcgUyAwCkEgNSB1Y2xlcwp1c2VyX25hbWUgU1RSSU5HIFMgMApBIDEzIGNpZUFtQXV0aG9yczEKcGFzc3dvcmQgU1RSSU5HIFMgMApBIDEyOCBETV9FTkNSX1RFWFRfVjI9QUFBQUVJRzY2NU9nMWp4OHpYUHY2MkRyejk3dkNkUFhRdVF3b2ZDajI5RE1sd1BnbmE0V21qVlh2V2VDQ1RSOHBrZHBsaU1aekdhZFNjaEpFRnoxNUNHUlltbkNBeUdkcTdPNWZvUU5PbUhxUCtTRQpkb2NiYXNlX25hbWUgU1RSSU5HIFMgMApBIDE2IGNhZGV2X3NkY2NtYXAwNDQKaG9zdF9uYW1lIFNUUklORyBTIDAKQSAxMCBzZGNjbWFwMDQ0CnNlcnZlcl9uYW1lIFNUUklORyBTIDAKQSAxNiBjYWRldl9zZGNjbWFwMDQ0CnNpZ25hdHVyZV9sZW4gSU5UIFMgMAoxMzYKc2lnbmF0dXJlIFNUUklORyBTIDAKQSAxMzYgQUFBQUVFV2tuSnBRdHpmYm9URy9RUzkzRThTelVjVEl4NmZoeTZ3VDVrNjZ5Y3ZCRTF0Uk92M3FoL0UyTFVmZmRPRys4YTE5TnNJak1yS2N0UVFyWldwamVqVnNzMTVrZ3dUNjVGenlsejY2blN5Skg1RlNIQXUzWFRwclQ5N1BpQ2NUdXc9PQo="
19) "\xac\xed\x00\x05t\x00\x0fsession:isValid"
20) "\xac\xed\x00\x05sr\x00\x11java.lang.Boolean\xcd r\x80\xd5\x9c\xfa\xee\x02\x00\x01Z\x00\x05valuexp\x01"
127.0.0.1:6379>


using new jar, the  same data save in redis in different format:

127.0.0.1:6379> hgetall redisson:tomcat_session:CBE6B4414A1B7219EEA6FD8AC6638C88
 1) "taxonomyIds"
 2) "\xac\xed\x00\x05sr\x000ucles.ccms.nativejava.pojos.taxonomy.TaxonomySet&\xc8\xd0\x9cv\x1cL\x97\x02\x00\x01L\x00\x0etaxonomyIdsSett\x00\x13Ljava/util/HashSet;xpsr\x00\x11java.util.HashSet\xbaD\x85\x95\x96\xb8\xb74\x03\x00\x00xpw\x0c\x00\x00\x00\x10?@\x00\x00\x00\x00\x00\x01t\x00$b74c9642-9960-4b31-81d2-681018c2df7ax"
 3) "session:thisAccessedTime"
 4) "\xac\xed\x00\x05sr\x00\x0ejava.lang.Long;\x8b\xe4\x90\xcc\x8f#\xdf\x02\x00\x01J\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x01\x80E\xc7\r\xc8"
 5) "session:lastAccessedTime"
 6) "\xac\xed\x00\x05sr\x00\x0ejava.lang.Long;\x8b\xe4\x90\xcc\x8f#\xdf\x02\x00\x01J\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x01\x80E\xc7\r\xc8"
 7) "businessStream"
 8) "\xac\xed\x00\x05t\x00\x03CIE"
 9) "user"
10) "\xac\xed\x00\x05sr\x00'ucles.ccms.nativejava.pojos.user.CAUser\x0b\x9b\xc7a\x8d\xaa\xb0-\x02\x00\aI\x00\x15sessionTimeoutSecondsL\x00\x0ebusinessStreamt\x00\x12Ljava/lang/String;L\x00\ncreditorNoq\x00~\x00\x01L\x00\x05namest\x00,Lucles/ccms/nativejava/pojos/user/UserNames;L\x00\tpermitSett\x00.Lucles/ccms/nativejava/pojos/user/CAPermitSet;L\x00\x10subordinateNamest\x00\x13Ljava/util/HashSet;L\x00\x06userIdq\x00~\x00\x01xp\x00\x00\x03\x84t\x00\x03CIEpsr\x00*ucles.ccms.nativejava.pojos.user.UserNamesp\x18\xbb\x80\xf0\xe6L\xc3\x02\x00\x02L\x00\ruserLoginNameq\x00~\x00\x01L\x00\buserNameq\x00~\x00\x01xpt\x00\x0ecieAmAuthors01t\x00\rcieAmAuthors1sr\x00,ucles.ccms.nativejava.pojos.user.CAPermitSet\xf3\xa6\xde\xa1&u'\xd3\x02\x00\x03Z\x00\x0bisSuperUserL\x00\x10effectivePermitst\x00\x15Ljava/util/ArrayList;L\x00\x0bsourceRolesq\x00~\x00\x04xp\x00sr\x00\x13java.util.ArrayListx\x81\xd2\x1d\x99\xc7a\x9d\x03\x00\x01I\x00\x04sizexp\x00\x00\x00\rw\x04\x00\x00\x00\rsr\x00)ucles.ccms.nativejava.pojos.user.CAPermitl&\x0f\r\\\xbd\xc5K\x02\x00\x03L\x00\x0cachievableIdq\x00~\x00\x01L\x00\x0bpermitLevelt\x000Lucles/ccms/nativejava/pojos/user/CAPermitLevel;L\x00\npermitNamet\x00/Lucles/ccms/nativejava/pojos/user/CAPermitName;xpp~r\x00.ucles.ccms.nativejava.pojos.user.CAPermitLevel\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xr\x00\x0ejava.lang.Enum\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xpt\x00\x04READ~r\x00-ucles.ccms.nativejava.pojos.user.CAPermitName\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xq\x00~\x00\x15t\x00\x19LIBRARY_MANAGEMENT_SCREENsq\x00~\x00\x10pq\x00~\x00\x16~q\x00~\x00\x18t\x00\x0bTASK_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40~q\x00~\x00\x14t\x00\x05WRITE~q\x00~\x00\x18t\x00\x0eREPORTS_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00 ~q\x00~\x00\x18t\x00\x12ADVANCED_AUTHORINGsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00 ~q\x00~\x00\x18t\x00\rSEARCH_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x12ACHIEVABLES_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x0fTAXONOMY_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x19PROJECT_MANAGEMENT_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\x18WORKFLOW_TEMPLATE_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\nTCP_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16~q\x00~\x00\x18t\x00\nTET_SCREENsq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16q\x00~\x00\x19sq\x00~\x00\x10t\x00\x141--g-kkxyinao-b31f40q\x00~\x00\x16q\x00~\x00\x1cxsr\x00\x11java.util.HashSet\xbaD\x85\x95\x96\xb8\xb74\x03\x00\x00xpw\x0c\x00\x00\x00\x10?@\x00\x00\x00\x00\x00\x02~r\x00(ucles.ccms.nativejava.constants.CcmsRole\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xq\x00~\x00\x15t\x00\x06AUTHOR~q\x00~\x00Jt\x00\x1bASSESSMENT_MATERIAL_MANAGERxpt\x00\x1011003039800005b7"
11) "ticket"
12) "\xac\xed\x00\x05t\x03\x92DM_TICKET=T0JKIE5VTEwgMAoxMwp2ZXJzaW9uIElOVCBTIDAKMwpmbGFncyBJTlQgUyAwCjEKc2VxdWVuY2VfbnVtIElOVCBTIDAKMTA3MgpjcmVhdGVfdGltZSBJTlQgUyAwCjE2NTA0MzgxMTIKZXhwaXJlX3RpbWUgSU5UIFMgMAoxNjUwNDM5MDEyCmRvbWFpbiBTVFJJTkcgUyAwCkEgNSB1Y2xlcwp1c2VyX25hbWUgU1RSSU5HIFMgMApBIDEzIGNpZUFtQXV0aG9yczEKcGFzc3dvcmQgU1RSSU5HIFMgMApBIDEyOCBETV9FTkNSX1RFWFRfVjI9QUFBQUVBWGhrVlFIYWh4SzNFZ0RDWW14RmtpZWg5b2R2dllYZGEzTFMveUJacFZPSm80Y0JOMWJWTmVtcGMrdmlzNm4rSUtlNzRjeWgwRmVkeTd5aS9sRDJLMGMwOXVhWnRNblFGc3hqclEvdE53Ywpkb2NiYXNlX25hbWUgU1RSSU5HIFMgMApBIDE2IGNhZGV2X3NkY2NtYXAwNDQKaG9zdF9uYW1lIFNUUklORyBTIDAKQSAxMCBzZGNjbWFwMDQ0CnNlcnZlcl9uYW1lIFNUUklORyBTIDAKQSAxNiBjYWRldl9zZGNjbWFwMDQ0CnNpZ25hdHVyZV9sZW4gSU5UIFMgMAoxMzYKc2lnbmF0dXJlIFNUUklORyBTIDAKQSAxMzYgQUFBQUVKODNJRzBBYUlRZytBZ2hSdk9MRmxWWmNWOTl1VzJFTjhxOHY5VXY4TTBETk82TzBOSVhHUG1yTXlNdEhvWXYyYVpuc21CVkl5VGpOOW9JY2U0YTc1by96ZGhCMzZSU0d1ajZoMUh6NDJ2aUY1cktCUGMyQ3hJS2lJT003bG9lQ1E9PQo="
127.0.0.1:6379>

-------------------------------------------------------------------------------------------------
RMap<String, Object> session =redisson.getMap("redisson:tomcat_session:4899CC5C803FE9816ADF64105A895440", redisSerializationCodec);
if (session.get("user") != null) { }

if the data is saved as in first format, I got user details.
If the data is saved in second format , user data unable to fetch, and exception occurs in debug mode,

Note: The excpetion occurs in debug mode , not all time. now i unable to generate the exception. but there is no outcome

**Comment by arumuk** [comment]
14:03:44.392 [main] ERROR org.redisson.config.Config - JSON configuration is deprecated and will be removed in future!
14:03:44.408 [main] ERROR org.redisson.config.Config - JSON configuration is deprecated and will be removed in future!
14:04:32.238 [redisson-netty-2-2] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0xdee8d4f3, L:/127.0.0.1:56557 - R:127.0.0.1/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=35, widx=2805), command: (HSCAN), params: [redisson:tomcat_session:DFDE820966D594986AC74125964FC71E, 0, COUNT, 10]
java.io.StreamCorruptedException: invalid stream header: 7461786F
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358) ~[?:1.8.0_202]
	at org.redisson.codec.CustomObjectInputStream.<init>(CustomObjectInputStream.java:36) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.codec.SerializationCodec$1.decode(SerializationCodec.java:54) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:366) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183) [redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122) [redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107) [redisson-3.16.1.jar:3.16.1]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by arumuk** [comment]
> Can you share full stacktrace of the exception?

14:03:44.392 [main] ERROR org.redisson.config.Config - JSON configuration is deprecated and will be removed in future!
14:03:44.408 [main] ERROR org.redisson.config.Config - JSON configuration is deprecated and will be removed in future!
14:04:32.238 [redisson-netty-2-2] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0xdee8d4f3, L:/127.0.0.1:56557 - R:127.0.0.1/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=35, widx=2805), command: (HSCAN), params: [redisson:tomcat_session:DFDE820966D594986AC74125964FC71E, 0, COUNT, 10]
java.io.StreamCorruptedException: invalid stream header: 7461786F
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358) ~[?:1.8.0_202]
	at org.redisson.codec.CustomObjectInputStream.<init>(CustomObjectInputStream.java:36) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.codec.SerializationCodec$1.decode(SerializationCodec.java:54) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:366) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375) ~[redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183) [redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122) [redisson-3.16.1.jar:3.16.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107) [redisson-3.16.1.jar:3.16.1]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by mrniko** [comment]
Tomcat Session attributes encoding has changed since 3.10.1 version.
