### ISSUE TITLE
RedissonSession tomcat 8: ClassCastException on high load

### ISSUE THREAD

**Issue by Drofff** [redisson/redisson#4254]
**Actual behavior**
From time to time, during high load, we see the following exception appear:

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
 at org.redisson.tomcat.RedissonSession.load(RedissonSession.java:446)
 at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:188)
 at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:168)
 at org.apache.catalina.connector.Request.doGetSession(Request.java:2995)
 at org.apache.catalina.connector.Request.getSession(Request.java:2454)
 at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896)
 at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231)
 at org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper.saveContext(HttpSessionSecurityContextRepository.java:347)
 at org.springframework.security.web.context.HttpSessionSecurityContextRepository.saveContext(HttpSessionSecurityContextRepository.java:151)
 at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:114)

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
 at org.redisson.tomcat.RedissonSession.load(RedissonSession.java:446)
 at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:188)
 at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:168)
 at <our code that calls "session.getAttribute()">
```
At a first glance, it looks similar to https://github.com/redisson/redisson/issues/1713 though we surely have only one Redisson version writing to and reading from our Redis instance. Moreover, the issue seems to be happening because the value of `session:creationTime` is somehow set to an `Integer`.

**Steps to reproduce or test case**
Not easily reproducible

**Redis version**
6.0.5

**Redisson version**
redisson-tomcat-8 3.16.0

**Redisson configuration**
A default config using AWS ElastiCache connection string

**Comment by Drofff** [comment]
A workaround might be to update the `load` method to cast the values a bit more safely, i.e. [here](https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java#L447):
```
Number creationTime = (Number) attrs.remove(CREATION_TIME_ATTR);
if (creationTime != null) {
    this.creationTime = creationTime.longValue();
}
```

**Comment by mrniko** [comment]
@Drofff

Does you solution resolves the issue completely?

**Comment by mrniko** [comment]
Any update?

**Comment by Drofff** [comment]
Hey @mrniko, thanks for taking a look into this one!

I'm trying to verify the fix at this moment. Though I'll have to let it run in prod for a week or two to make sure the fix actually worked, after that will let you know here immediately 🙂 

Yes, we do use the exact same version across all Tomcat instances and we have a dedicated instance specifically for sessions so there are no more readers/writers.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4262

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/7005
