### ISSUE TITLE
isExists throws cast exception

### ISSUE THREAD

**Issue by KingArthur0902** [redisson/redisson#4262]
**Expected behavior**
just return true or false
**Actual behavior**
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:326)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:123)
	at org.redisson.RedissonObject.get(RedissonObject.java:82)
	at org.redisson.RedissonObject.isExists(RedissonObject.java:236)
	at com.zhiyou.bootstarter.redis.support.BaseRedissonTemplate.exists(BaseRedissonTemplate.java:150)
	at com.zhiyou.module.items.support.ItemSyncUtils.setSyncTaskField(ItemSyncUtils.java:247)
	at com.zhiyou.module.items.service.server.puller.ItemSyncPriorityTaskPuller.handleTask(ItemSyncPriorityTaskPuller.java:114)
	at com.zhiyou.module.items.service.server.puller.ItemSyncPriorityTaskPuller.handleTask(ItemSyncPriorityTaskPuller.java:38)
	at com.zhiyou.tw.consumer.BaseTaskPuller.lambda$null$0(BaseTaskPuller.java:181)
	at com.zhiyou.bootstarter.routing.DsSwitcher.ready(DsSwitcher.java:80)
	at com.zhiyou.tw.consumer.BaseTaskPuller.lambda$processingOneByOne$1(BaseTaskPuller.java:180)
	at com.zhiyou.dsrouter.core.thread.RoutingRunner.run(RoutingRunner.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:27)
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:23)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:449)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:333)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
**Steps to reproduce or test case**
it does not present every time
**Redis version**
5.0.5
**Redisson version**
3.16.6
**Redisson configuration**
config.useClusterServers()
                    .setPingConnectionInterval(10000)
                    .setScanInterval(200000)
                    .setMasterConnectionMinimumIdleSize(5)
                    .setSlaveConnectionMinimumIdleSize(5)
                    .addNodeAddress(properties.getAddress().split(","))
                    .setPassword(properties.getPassword());

**Comment by mrniko** [comment]
It might be related of incorrect handling of String response to PING response. Which was fixed in 3.17.0. Can you try this version?

**Comment by KingArthur0902** [comment]
ok

**Comment by mrniko** [comment]
Fixed
