### ISSUE TITLE
DNS query failed

### ISSUE THREAD

**Issue by bharathkopparapu** [redisson/redisson#4264]
**Expected behavior**
DNS lookup should be successfull

**Actual behavior**
11:21:33 |  | ERROR | org.redisson.cluster.ClusterConnectionManager | Unable to resolve rediss://eqhv-prod-redis-sh-0001-001.maskedIP:6379
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'eqhv-prod-redis-sh-0001-001.maskedIP' failed to resolve 'eqhv-prod-redis-sh-0001-001.eqhv-prod-redis-sh.ab4gwe.use1.cache.amazonaws.com'
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:964)
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:923)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:395)
        at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64)
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:444)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225)
        at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/maskedIp] query via UDP timed out after 5000 milliseconds (no stack trace availabl
e)
11:21:33 |  | ERROR | org.redisson.cluster.ClusterConnectionManager | Node: NodeSource [slot=2157, addr=null, redisClient=null, redirect=null, entry=null] ca
n't be found

org.redisson.client.RedisNodeNotFoundException: Node for slot: 2157 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.
        at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundException(MasterSlaveConnectionManager.java:562)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:513)
        at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:594)
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:124)
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:254)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Steps to reproduce or test case**
Testing from On-prem servers to AWS Elastic cache Redis

**Redis version**

**Redisson version**
3.17.1

**Redisson configuration**
redis.cluster.address=rediss://masked:6379
redis.nettyThreads=2
redis.sslTruststore=
redis.sslTruststorePassword=
redis.keepAlive=true
redis.pingConnectionInterval=0
redis.password=masked
redis.connTimeOut=1000
redis.readTimeOut=3000

**Comment by mrniko** [comment]
Use this solution https://github.com/redisson/redisson/issues/4248#issuecomment-1107424810

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1625
