### ISSUE TITLE
3.16.1 distribute lock can not write any keys,  occurred at trylock.  The weird thing is that all params are null, currentCommand=null], command: null, params: null ....

### ISSUE THREAD

**Issue by wsq2025** [redisson/redisson#4325]
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:115:queue:0, freezeReason=null, client=[addr=redis://sys-redis-a3024959c1bf4635-proxy-svc.product-cec-cbc.svc.cluster.local:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1541628161 [redisClient=[addr=redis://sys-redis-a3024959c1bf4635-proxy-svc.product-cec-cbc.svc.cluster.local:6379], channel=[id: 0x8ea04cbe, L:0.0.0.0/0.0.0.0:40218], currentCommand=null], command: null, params: null after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:280)
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:60)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:161)
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:158)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1017)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:878)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

**Comment by wsq2025** [comment]
the redis mode above is proxy, the layer is master-slave,。by the way redission dns check is closed

**Comment by mrniko** [comment]
command: null means RBatch object used by RLock object.

**Comment by zuoyueer** [comment]
I also got this exception, it doesn't seem to affect my program.
`
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2022-06-02 14:45:52.529 default [redisson-timer-8-1] ERROR o.r.c.handler.PingConnectionHandler -[][:]- Unable to send PING command over channel: [id: 0x74757eba, L:/192.168.253.113:52063 ! R:/10.80.92.200:6379]
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2022-06-02 14:45:52.621 default [redisson-timer-8-1] ERROR o.r.c.handler.PingConnectionHandler -[][:]- Unable to send PING command over channel: [id: 0xd9525c32, L:0.0.0.0/0.0.0.0:51682]
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2022-06-02 14:45:52.621 default [redisson-timer-8-1] ERROR o.r.c.handler.PingConnectionHandler -[][:]- Unable to send PING command over channel: [id: 0x47e63abe, L:0.0.0.0/0.0.0.0:51683]
`

**Comment by mrniko** [comment]
@zuoyueer 

The channel is closed according to your log

**Comment by wsq2025** [comment]
> command: null means RBatch object used by RLock object.

![1655980827308](https://user-images.githubusercontent.com/49111560/175284836-f1b3c4ce-a50d-4ac8-b944-3a05e367ec6b.png)

picture above shows one request regularity, first trylock error, then release lock error.

**Comment by mrniko** [comment]
3.16.1 has a connection leak problem. Try to use latest version
