### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Can't decode replay

### ISSUE THREAD

**Issue by ritwickgupta** [redisson/redisson#4333]
I am getting the following error when I am trying to connect to Memorystore Redis on GCP. This works fine locally but not on Google Cloud. I have double-checked the IP and It's correct. VPC is set up correctly as well. This was working before with Jedis Library.

org.redisson.Version : Redisson 3.17.2

Config Code
```
    public RedissonClient redissonClient(@Value("${redis.host}") String host, @Value("${redis.port}") String port) {

        if (!StringUtils.hasText(host) || !StringUtils.hasText(port)) {
            throw new RuntimeException("missing cache configuration");
        }

        log.info("Connecting Broker to Redis at: " + host);

        Config config = new Config();
        config.useSingleServer().setAddress("redis://" + host + ":" + port);
        return Redisson.create(config);
    }
}
```

```
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Can't decode replay: F
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:398) ~[redisson-3.17.2.jar!/:3.17.2]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198) ~[redisson-3.17.2.jar!/:3.17.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[redisson-3.17.2.jar!/:3.17.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) ~[redisson-3.17.2.jar!/:3.17.2]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.74.Final.jar!/:4.1.74.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na] 
```

**Comment by mrniko** [comment]
The problem is in data encoding. Try to clean data stored with a different codec or use the same codec with Redisson.

**Comment by ritwickgupta** [comment]
I see. I get this during Redisson Client bean creation. 

How do I know which codec Memorystore is using?

**Comment by ritwickgupta** [comment]
I am getting this at app bootup. Memorystore has no data stored and I am not setting the codec anywhere explicitly. I am just using default.

Could it be possible that the Memorystore Redis instance is using a different codec?

**Comment by mrniko** [comment]
I don't think so. Can you set `trace` logging level for `org.redisson` and share output from application start?

**Comment by kaviarasupgk** [comment]
I am also getting the same issue. Could you please share the solution for this and that would be helpful

**Comment by priyankgosalia** [comment]
We're getting the same error while connecting to Redis on GCP. Was there ever a solution to this issue? Any leads would be helpful.
