### ISSUE TITLE
ClusterConnectionManager频繁打印slots added,slots removed #4146

### ISSUE THREAD

**Issue by tianyangyang427** [redisson/redisson#4338]
Is this bug planned to be fixed in the new version? The bugs "3.17.1" and "3.17.2" still exist

**Comment by mrniko** [comment]
I need Redisson logs in `trace` logging level to get the cause.

**Comment by tianyangyang427** [comment]
This is a screenshot of the log at runtime
![image](https://user-images.githubusercontent.com/25681699/172078375-f5dad83d-b6bd-415d-8da2-b7a3193e7f50.png)

**Comment by mrniko** [comment]
Sorry, I need Redisson logs in `trace` logging level to understand the cause.

**Comment by Yan-Zhi-Bin** [comment]
3.15.5版本也存在这个问题，3.12.4版本没有这个问题

**Comment by huangkengwei** [comment]
> Sorry, I need Redisson logs in `trace` logging level to understand the cause.

Hi, I have same problem on version 3.17.4. 

Here is my trace log, I hope it could be helpful. 

Thanks.

[trace.log](https://github.com/redisson/redisson/files/9382716/trace.log)

**Comment by mrniko** [comment]
@huangkengwei 

I don't see any slots added/removed messages in your log

**Comment by qiuzhihui1990** [comment]
Hi, I have same problem about this,
first time i use version 3.16.8 , and then i change the version to  3.17.5 and 3.15.5, but it still happen。

now I use the 3.15.5 version redisson, and redis server is 5.0.5
this is my redisson config:

        RedisInfo redisInfo = getRedisInfo();
        Config config = new Config();
        config.useClusterServers()
                .addNodeAddress("redis://" + redisInfo.getHost() + ":" + redisInfo.getPort())
                .setPassword(redisInfo.getPassword())
                .setRetryAttempts(3)
                .setRetryInterval(100)
                .setConnectTimeout(3000)
                .setTimeout(3000);

and I use the BloomFilter in my project like this:

 private RBloomFilter<String> registerMobileBloomFilter;

@PostConstruct
    public void init() {
        mobileBloomFilter = redissonClient.getBloomFilter(
                Constants.REDIS_KEY_PREFIX + "mobile");
}

// first time init and add after listener kafka topic
if (!registerMobileBloomFilter.isExists()) {
    mobileBloomFilter.tryInit(100000000L, 0.00001);
 }
mobileBloomFilter.add(mobile);

// the BloomFilter use for check
public static final String REDIS_KEY_PREFIX = "xxxxx:yyyy:";
private RBloomFilter<String> mobileBloomFilter;


// this method will be called 90 millions every day
 private Mono<Boolean> checkExist(String mobileMd5) {
    boolean isExist = mobileBloomFilter.contains(mobileMd5);
}

and then the added/removed info logs will appear after the application run about a day
after added/removed info logs appear thousand times, the error logs "8681 hasn't been discovered yet" will appear, the 8681 is the slot of method connectionManager.calcSlot(key), key is mobileBloomFilter.
only this slot error has,and this error slot will continue until i restart the application
logs is follow:
2022-08-30 12:28:57,734 redisson-netty-3-3 INFO org.redisson.cluster.ClusterConnectionManager ClusterConnectionManager.java:679 [trace=,span=] - 11904 slots added to redis://172.21.74.256:6379
-10
2022-08-30 12:28:57,735 redisson-netty-3-3 INFO org.redisson.cluster.ClusterConnectionManager ClusterConnectionManager.java:693 [trace=,span=] - 7872 slots removed from redis://172.21.74.256:6379
0
2022-08-30 12:28:57,751 blocking-pool-redis-1 ERROR com.zz.ff.pp.exception.ServiceExceptionHandler ServiceExceptionHandler.java:34 [trace=61fd029e6c69425f908b17c98e29c342,span=5f450c9caec671b5] - 服务异常, Node for slot: 8681 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings. org.redisson.client.RedisNodeNotFoundException: Node for slot: 8681 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings. at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundException(MasterSlaveConnectionManager.java:559) Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: Error has been observed at the following site(s): |_ checkpoint ⇢ Handler com.zz.ff.pp.controller.FeatureController#checkCreditGranting(FeatureQueryReq, String, ServerHttpRequest) [DispatcherHandler] Stack trace: at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundException(MasterSlaveConnectionManager.java:559) at org.redisson.command.BaseRedisBatchExecutor.getEntry(BaseRedisBatchExecutor.java:67) at org.redisson.command.BaseRedisBatchExecutor.addBatchCommandData(BaseRedisBatchExecutor.java:75) at org.redisson.command.RedisBatchExecutor.execute(RedisBatchExecutor.java:53) at org.redisson.command.CommandBatchService.async(CommandBatchService.java:159) at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:550) at org.redisson.command.CommandAsyncService.evalReadAsync(CommandAsyncService.java:380) at org.redisson.RedissonBloomFilter.addConfigCheck(RedissonBloomFilter.java:192) at org.redisson.RedissonBloomFilter.contains(RedissonBloomFilter.java:164) at com.zz.ff.pp.service.feature.impl.CreditGrantingFeatureServiceImpl.lambda$checkRegisterMobileExist$11(CreditGrantingFeatureServiceImpl.java:212) at com.zz.ff.pp.service.feature.impl.CreditGrantingFeatureServiceImpl$$Lambda$1723/1197822486.get(Unknown Source) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)
+1
2022-08-30 12:28:57,753 redisson-netty-3-3 INFO org.redisson.cluster.ClusterConnectionManager ClusterConnectionManager.java:656 [trace=,span=] - 7872 slots found to add

so, why this error happen, and how can i reslove this?

**Comment by qiuzhihui1990** [comment]
@mrniko 

and I find the RedisNodeNotFoundException will appear between slots removed and add

2022-08-31 14:22:45,745 redisson-netty-3-3 INFO org.redisson.cluster.ClusterConnectionManager ClusterConnectionManager.java:693 [trace=,span=] - 4032 slots removed from redis://172.21.74.256:6379

2022-08-31 14:22:45,748 blocking-pool-redis-7 ERROR com.zz.ff.pp.exception.ServiceExceptionHandler ServiceExceptionHandler.java:34 [trace=3a44c6df6f02f0a76ff60587bfe1ad4d,span=70c2b66e386b81d9] - 服务异常, Node for slot: 8681 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings. org.redisson.client.RedisNodeNotFoundException: Node for slot: 8681 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings. at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundException(MasterSlaveConnectionManager.java:559) Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: Error has been observed at the following site(s): |_ checkpoint ⇢ Handler com.zz.ff.pp.controller.FeatureController#checkCreditGranting(FeatureQueryReq, String, ServerHttpRequest) [DispatcherHandler] Stack trace: at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundException(MasterSlaveConnectionManager.java:559) at org.redisson.command.BaseRedisBatchExecutor.getEntry(BaseRedisBatchExecutor.java:67) at org.redisson.command.BaseRedisBatchExecutor.addBatchCommandData(BaseRedisBatchExecutor.java:75) at org.redisson.command.RedisBatchExecutor.execute(RedisBatchExecutor.java:53) at org.redisson.command.CommandBatchService.async(CommandBatchService.java:159) at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:550) at org.redisson.command.CommandAsyncService.evalReadAsync(CommandAsyncService.java:380) at org.redisson.RedissonBloomFilter.addConfigCheck(RedissonBloomFilter.java:192) at org.redisson.RedissonBloomFilter.contains(RedissonBloomFilter.java:164) at com.zz.ff.pp.service.feature.impl.CreditGrantingFeatureServiceImpl.lambda$checkRegisterMobileExist$11(CreditGrantingFeatureServiceImpl.java:212) at com.zz.ff.pp.service.feature.impl.CreditGrantingFeatureServiceImpl$$Lambda$1695/2124545668.get(Unknown Source) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

2022-08-31 14:22:45,750 redisson-netty-3-3 INFO org.redisson.cluster.ClusterConnectionManager ClusterConnectionManager.java:656 [trace=,span=] - 4032 slots found to add

**Comment by yan11xiang** [comment]
I had the same problem. redis server

**Comment by mrniko** [comment]
@qiuzhihui1990 
@yan11xiang 

Can you share the logs with `trace` for `org.redisson` package?

**Comment by atokr** [comment]
redis 服务器版本：4.0.14
redisson 版本：3.17.7
RedisNodeNotFoundException异常导致的业务中断, 堆栈如下, 没有trace日志
每天均有7,8笔
![image](https://user-images.githubusercontent.com/23493090/210028968-416a6c6d-ae32-4e36-9f4f-04c775576b89.png)

**Comment by mrniko** [comment]
@ark-byte

Did you check slots coverage?
Can you share the logs with trace for org.redisson package?

**Comment by guid-git** [comment]
how to reslove it?

**Comment by guid-git** [comment]
> are the logs with trace for org.redisson pack



> redis 服务器版本：4.0.14 redisson 版本：3.17.7 RedisNodeNotFoundException异常导致的业务中断, 堆栈如下, 没有trace日志 每天均有7,8笔 ![image](https://user-images.githubusercontent.com/23493090/210028968-416a6c6d-ae32-4e36-9f4f-04c775576b89.png)

后来怎么解决的？

**Comment by mrniko** [comment]
@niquba 

Redis servers report incorrect cluster state. For example, slot 5514 is in migrating state, but this slot doesn't belong to any master.

**Comment by mrniko** [comment]
@guid-git 

Can you share the logs with trace for `org.redisson` package?

**Comment by guid-git** [comment]
2023-08-08 19:24:06.836 - TID:5669a65795ed42d9b10bb399f694edc4.547.16914938447880067 ERROR [AsyncExecutor-7] [SimpleAsyncUncaughtExceptionHandler.java:39] Unexpected exception occurred invoking async method: public java.lang.Boolean com.yst.apm.collector.biz.ApmCollectorBiz.createServices(com.yst.apm.collector.api.request.ApmCreateRequest)
org.redisson.client.RedisNodeNotFoundException: Node for slot: 10797 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.

**Comment by guid-git** [comment]
2023-08-08 19:24:06.836 - TID:5669a65795ed42d9b10bb399f694edc4.547.16914938447880067 ERROR [AsyncExecutor-7] [SimpleAsyncUncaughtExceptionHandler.java:39] Unexpected exception occurred invoking async method: public java.lang.Boolean com.xxxxx.createServices(com.xxxxxxx)
org.redisson.client.RedisNodeNotFoundException: Node for slot: 10797 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.

**Comment by guid-git** [comment]
redis cluster 6.2.6   redisson use 3.17.7 、3.15.4  has the same error log

**Comment by mrniko** [comment]
Can you share logs in a single file?

**Comment by guid-git** [comment]
> Can you share logs in a single file?

[error.log](https://github.com/redisson/redisson/files/12298893/error.log)
[info.log](https://github.com/redisson/redisson/files/12298894/info.log)

**Comment by guid-git** [comment]
@mrniko please help me , If there's no way, we can only replace the redisson client

**Comment by mrniko** [comment]
@guid-git 

Sorry, I asked for the logs with `trace` logging level for `org.redisson` package, but got with `info`.

**Comment by zgyin** [comment]
[trace.txt](https://github.com/redisson/redisson/files/12405475/trace.txt)

version：3.12.0
@mrniko

**Comment by mrniko** [comment]
@zgyin 

Can you get it with 3.17.0 or the latest version?

**Comment by zgyin** [comment]
[trace.txt](https://github.com/redisson/redisson/files/12414948/trace.txt)
version：3.17.0
@mrniko

**Comment by mrniko** [comment]
@zgyin 

Can you try attached version?
[redisson-3.23.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/12415883/redisson-3.23.4-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
I attached a new updated version.

[redisson-3.23.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/12418360/redisson-3.23.4-SNAPSHOT.jar.zip)

**Comment by zgyin** [comment]
> @zgyin I attached a new updated version.
> 
> [redisson-3.23.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/12418360/redisson-3.23.4-SNAPSHOT.jar.zip)

Okay, the problem is occasional, I need a few days to reproduce it

**Comment by zgyin** [comment]
It has been 4 days and the problem no longer appears
@mrniko

**Comment by mrniko** [comment]
@zgyin 

Good. Thanks for testing
