### ISSUE TITLE
RedissonReactiveScriptingCommands convert function List transformations with different element types are not supported

### ISSUE THREAD

**Issue by galfordliu** [redisson/redisson#4353]
all version.
org.redisson.spring.data.connection.RedissonReactiveScriptingCommands

```
 protected <T> Flux<T> convert(Mono<T> m) {
        return (Flux<T>) m.map(e -> {
            if (e.getClass().isArray()) {
                return ByteBuffer.wrap((byte[])e);
            }
            if (e instanceof List) {
                if (((List) e).get(0).getClass().isArray()) {
                    return ((List<byte[]>)e).stream().map(v -> ByteBuffer.wrap(v)).collect(Collectors.toList());
                }
            }
            return e;
        }).flux();
    }
```

Lua script
```
local ret = {}
local mysqlKeys = {}
table.insert(ret, 'test1')
table.insert(ret, 'test2')
table.insert(ret, 'test3')
table.insert(ret, mysqlKeys)

return ret
 
```

![image](https://user-images.githubusercontent.com/6939901/172850511-d3863867-ca4d-4ad4-ad51-46dfc97988a3.png)

list.get(0) is byte[], but, list.get(3) is ArrayList. 

```
throws java.lang.ClassCastException: java.util.ArrayList cannot be cast to [B
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.redisson.spring.data.connection.RedissonReactiveScriptingCommands.lambda$convert$8(RedissonReactiveScriptingCommands.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
	at org.redisson.reactive.CommandReactiveService.lambda$reactive$1(CommandReactiveService.java:65)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:521)
	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:513)
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:501)
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:478)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:172)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:460)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:454)
	at org.redisson.client.handler.CommandDecoder.decodeResult(CommandDecoder.java:443)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:437)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
```

**Comment by mrniko** [comment]
Unable to reproduce with 3.17.3. Below is the test case:

```java
        String s = "local ret = {}" +
                    "local mysqlKeys = {}" +
                    "table.insert(ret, 'test1')" +
                    "table.insert(ret, 'test2')" +
                    "table.insert(ret, 'test3')" +
                    "table.insert(ret, mysqlKeys)" +
                    "return ret";

        List s2 = connection.scriptingCommands().eval(s.getBytes(), ReturnType.MULTI, 0);
        Assertions.assertThat(s2).isNotEmpty();
```

**Comment by galfordliu** [comment]
> Unable to reproduce with 3.17.3. Below is the test case:
> 
> ```java
>         String s = "local ret = {}" +
>                     "local mysqlKeys = {}" +
>                     "table.insert(ret, 'test1')" +
>                     "table.insert(ret, 'test2')" +
>                     "table.insert(ret, 'test3')" +
>                     "table.insert(ret, mysqlKeys)" +
>                     "return ret";
> 
>         List s2 = connection.scriptingCommands().eval(s.getBytes(), ReturnType.MULTI, 0);
>         Assertions.assertThat(s2).isNotEmpty();
> ```

Please Try Reactive!

**Comment by mrniko** [comment]
Fixed
