### ISSUE TITLE
Getting RedisResponseTimeoutException on application restart

### ISSUE THREAD

**Issue by alexwibowo** [redisson/redisson#4355]
Hi all,

I'm currently using a very simple redisson config:
`
singleServerConfig:
  address: "redis://localhost:6379"
`

My application put an object to redisson map. I'm not sure if the object size is 'too big', but this is what I can see when i run the 'DEBUG OBJECT' command in redis-cli:

`
1) "myRegistry"
127.0.0.1:6379> DEBUG OBJECT myRegistry
Value at:0xffffae3d9f80 refcount:1 encoding:hashtable serializedlength:9311 lru:10678472 lru_seconds_idle:36
` 

When I restart the application, it is stuck for a while, before crashing with this exception:

`
Caused by: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (8000 ms) occured after 3 retry attempts, is non-idempotent command: false. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (HSCAN), params: [myRegistry, 0, COUNT, 10], channel: [id: 0x193a3b4d, L:/127.0.0.1:52606 - R:localhost/127.0.0.1:6379]
	at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$5(RedisExecutor.java:342)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
`

I've tried increasing nettyThreads to 128, and increasing timeout to 8000, without any success.  If I delete the key 'myRegistry', then I can start the application again.  Is there something obvious that I've missed ? Is it due to the object size ? I'm using redisson 3.17.1.

**Comment by mrniko** [comment]
Check the network
