### ISSUE TITLE
Netty threads in waiting state during fastPut of RLocalCachedMap

### ISSUE THREAD

**Issue by spathros** [redisson/redisson#4367]
We use Redisson 3.17.0 and redis version 6.0.8. We have three threads in the same host which do fastPut() on a RLocalCachedMap. The throughput is around 500 for each thread. Some of the threads go into WAITING state during fastPut() as seen from thread dump below.

```
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000006515fa310> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:114)
at org.redisson.RedissonObject.get(RedissonObject.java:82)
at org.redisson.RedissonMap.fastPut(RedissonMap.java:1285)
at com.oracle.pic.controltower.cache.DeviceServiceCache.putDeviceDo(DeviceServiceCache.java:248)
```

redisson config is as below:
 scanInterval: 1000
  masterConnectionPoolSize: 128
  masterConnectionMinimumIdleSize: 128
  sslEnableEndpointIdentification: false
  idleConnectionTimeout: 30000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 1
  retryInterval: 300
  readMode: "MASTER"
  pingConnectionInterval: 0
  keepAlive: true

  tcpNoDelay: true
  dnsMonitoringInterval: 5000
  threads: 16
  nettyThreads: 128

Are the threads in waiting state for response from redis server? We do not see any slowlogs or RedisTimeout exceptions for this too. Could you please help?

Will attach the trace logs for redisson package

**Comment by spathros** [comment]
We don't have the trace logs for when one of the threads goes into waiting state

**Comment by mrniko** [comment]
How do you create RLocalCachedMap object?

**Comment by spathros** [comment]
We inject this object as a singleton
redissonClient.getLocalCachedMap(Cache.deviceUuidToDeviceCache.name(), options)

**Comment by mrniko** [comment]
Unable to reproduce. Below is my test.

```java
    public void test1() throws InterruptedException {
        ExecutorService e = Executors.newFixedThreadPool(3);

        LocalCachedMapOptions<String, String> options = LocalCachedMapOptions.<String, String>defaults()
                .loader(new MapLoader<String, String>() {
                    @Override
                    public String load(String key) {
                        return "value " + key;
                    }

                    @Override
                    public Iterable<String> loadAllKeys() {
                        return Collections.emptyList();
                    }
                }).cacheSize(500000).evictionPolicy(EvictionPolicy.LRU);

        RLocalCachedMap<String, String> cachedMap = redisson.getLocalCachedMap("myMap11", options);

        for (int i = 0; i < 500*3*100; i++) {
            int j = i;
            e.submit(() -> {
                cachedMap.fastPut("" + j, "" + j);
            });
        }

        e.shutdown();
        assertThat(e.awaitTermination(100, TimeUnit.SECONDS)).isTrue();
    }
```
