### ISSUE TITLE
When the business thread is interrupted, watchdog renew listener keeps renewing lock

### ISSUE THREAD

**Issue by Coean** [redisson/redisson#4368]
**Expected behavior**
when tryLock is interrupted, watchdog renew listener is cancelled too

**Actual behavior**
when the thread is interrupted, watchdog keeps renewing lock, but i think it should not be renewed.

Someone once reported this issue in [Issue-2714](https://github.com/redisson/redisson/issues/2714)

and then another PR announced that it had solved the issue, but I don't think it had.
https://github.com/redisson/redisson/pull/3826

We can see the KEY LOGIC in the PR above, which detects whether watch dog's thread is interrupted, not whether our business thread is interrupted.

https://github.com/redisson/redisson/blob/45549df0bcba14fe0ada0b7cdb44699170547c56/redisson/src/main/java/org/redisson/RedissonBaseLock.java#L171

**Steps to reproduce or test case**
```java
 public void testLockRenewedAfterInterruptedTryLock() throws InterruptedException {
        final CountDownLatch countDownLatch = new CountDownLatch(1);
        RLock lock = redisson.getLock("myLock");

        Thread thread = new Thread(() -> {
            if (!lock.tryLock()) {
                return;
            }
            countDownLatch.countDown();
        });
        thread.start();
        countDownLatch.await();
        thread.interrupt();

        TimeUnit.SECONDS.sleep(45);
        lock.isLocked() // **Expected return false but it will be return true**
    }
```

**Redis version**
Redis 5.0.10

**Redisson version**
3.17.3

**Comment by mrniko** [comment]
This issue explained here https://github.com/redisson/redisson/issues/2714#issuecomment-894146033

https://github.com/redisson/redisson/pull/3826 related to a different issue.

**Comment by mrniko** [comment]
I agree that `Thread.currentThread().isInterrupted()` check in `scheduleExpirationRenewal()` is useless.

**Comment by panhoucheng** [comment]
> I agree that `Thread.currentThread().isInterrupted()` check in `scheduleExpirationRenewal()` is useless.

I'm glad that we can have the same cognition, and I submitted a PR to remove this unnecessary check from this very important method..

**Comment by mrniko** [comment]
You call the code from reactor. I think they interrupt the thread since it blocks the call. Try to use RLockReactive instead.

**Comment by HJK181** [comment]
> You call the code from reactor. I think they interrupt the thread since it blocks the call. Try to use RLockReactive instead.

I'll give it a try, but the code worked before while it was also called from reactor.

**Comment by HJK181** [comment]
Result of reactive tests:
```
lock.tryLock(100, timeoutDuration.toMillis() / 2, TimeUnit.MILLISECONDS)
                .flatMap(lockAquired -> {
                   ...
                })
                .doFinally((bla) -> {
                    lock.unlock().subscribe();
                });
```
gives me
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 13da7223-da92-4369-9e01-9d695ab8881a thread-id: 132
Caused by: java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 13da7223-da92-4369-9e01-9d695ab8881a thread-id: 132
	at org.redisson.RedissonBaseLock.lambda$unlockAsync0$2(RedissonBaseLock.java:301)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxCreate] :
	reactor.core.publisher.Flux.create(Flux.java:649)
	org.redisson.reactive.CommandReactiveService.reactive(CommandReactiveService.java:47)
Error has been observed at the following site(s):
	*__Flux.create ⇢ at org.redisson.reactive.CommandReactiveService.reactive(CommandReactiveService.java:47)
	|_   Flux.next ⇢ at org.redisson.reactive.CommandReactiveService.reactive(CommandReactiveService.java:76)
Original Stack Trace:
		at org.redisson.RedissonBaseLock.lambda$unlockAsync0$2(RedissonBaseLock.java:301)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
		at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:371)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
		at org.redisson.command.CommandBatchService.lambda$execute$9(CommandBatchService.java:486)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
		at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:625)
		at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:177)
		at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:583)
		at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:196)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
		at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:337)
		at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:228)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:1583)
```
However, the error is gone if I capture the current Thread id before acquiring the log while also passing that ID to unlock. 
```
 long id = Thread.currentThread().getId();
 lock.tryLock(100, timeoutDuration.toMillis() / 2, TimeUnit.MILLISECONDS)
                .flatMap(lockAquired -> {
                   ...
                })
                .doFinally((bla) -> {
                    lock.unlock(id).subscribe();
                });
```

**Comment by HJK181** [comment]
@mrniko Any idea why this is the behavior of the code executed in Spring-Cloud-Gateway with Virtual Threads

```
long id = Thread.currentThread().getId();
log.debug("ID Top {}", id);
lock.tryLock(100, timeoutDuration.toMillis() / 2, TimeUnit.MILLISECONDS)
              .flatMap(lockAquired -> {
                 log.debug("ID flatMap {}", Thread.currentThread().getId());
                 log.debug("LOCK ACQUIRED: {}", lockAquired);
              })
              .doFinally((bla) -> {
                 log.debug("IDfinally {}", Thread.currentThread().getId());
                 lock.unlock(id).subscribe();
              });
....
2024-01-26T15:35:43.422Z DEBUG 1 --- [gateway] [sson-netty-3-11] .CustomServiceInstanceListSupplier : IDfinally 51
2024-01-26T15:35:46.171Z DEBUG 1 --- [gateway] [ndedElastic-760] .CustomServiceInstanceListSupplier : ID Top 915
2024-01-26T15:35:46.174Z DEBUG 1 --- [gateway] [sson-netty-3-17] .CustomServiceInstanceListSupplier : ID flatMap 63
2024-01-26T15:35:46.174Z DEBUG 1 --- [gateway] [sson-netty-3-17] .SmartsuggestServiceInstanceListSupplier : LOCK ACQUIRED: true
```

while the order is different when using some Gist:
```
Flux.just(emptyList())
  .flatMap(list -> Mono.defer(() -> {
	  try {
		  Thread.sleep(1000);
	  }
	  catch (InterruptedException e) {
		  throw new RuntimeException(e);
	  }
	  return Mono.just(list);
  }))
  .flatMap(list -> {
	  System.out.println("next");
	  return Mono.just(list);
  })
  .doFinally(list -> System.out.println("finally"))
  .subscribe();
  ...
  ID Top 1
  ID flatMap 1
  IDfinally 1
```

**Comment by seakider** [comment]
@HJK181 

> lock.tryLock(100, timeoutDuration.toMillis() / 2, TimeUnit.MILLISECONDS)

According to the Reactive interface code example in the documentation, you should use the interface parameterized with threadId when acquiring or unlocking a lock.

As for your question about the order, I don't think it should be relevant to redisson.
