### ISSUE TITLE
NotSerializableException in RBucket set operation

### ISSUE THREAD

**Issue by soyef** [redisson/redisson#4377]
**Redisson version: 3.17.2**
**Java 8**

**Exception:**
Caused by: java.io.NotSerializableException: 
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274) ~[jboss-marshalling-river-2.0.11.Final.jar:2.0.11.Final]
	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58) ~[jboss-marshalling-2.0.11.Final.jar:2.0.11.Final]
	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111) ~[jboss-marshalling-2.0.11.Final.jar:2.0.11.Final]
	at org.redisson.codec.MarshallingCodec.lambda$new$1(MarshallingCodec.java:161) ~[redisson-3.17.2.jar:3.17.2]
	at org.redisson.command.CommandAsyncService.encode(CommandAsyncService.java:625) ~[redisson-3.17.2.jar:3.17.2]

**Sample Code**
private void put(String cacheKeyPrefix, String itemKey, T object) {
	RBucket<T> bucket = redisson.getBucket(cacheKeyPrefix + itemKey);
	bucket.set(object, cacheEntryTTLMilliSeconds, TimeUnit.MILLISECONDS);
}

Here object can be any dynamo db table object

**Redisson Config**
Config config = new Config();
    config.useClusterServers().setClientName(serviceName)
        .setSlaveConnectionPoolSize(slaveConnectionPoolSize2)
        .setMasterConnectionPoolSize(masterConnectionPoolSize2)
        .setConnectTimeout(connectTimeoutMs)
        .setTimeout(commandTimeoutMs)
        .setScanInterval(scanIntervalMs)
        .setReadMode(ReadMode.MASTER_SLAVE)
        .addNodeAddress(StringUtils.split(cacheClusterHostNames2, ','));

    return (Redisson) Redisson.create(config);

The same code was working with redisson 3.5.6

@mrniko

**Comment by mrniko** [comment]
Default codec has changed since then. You need to define JsonJacksonCodec explicitly.
