### ISSUE TITLE
Handle exception when Redis is down

### ISSUE THREAD

**Issue by diltheyaislan** [redisson/redisson#4390]
I'm using Redisson with the JCache implementation and it's working great.

But I need to manage the scenario if Redis is down, and if the connection fails I would like to get the data from another source.
When turning off Redis and fetching data via JCache, exceptions are thrown several times:
`org.redisson.client.RedisResponseTimeoutException`, `org.redisson.client.RedisTimeoutException`, and `org.redisson.client.WriteRedisConnectionException`.

I've tried using try/catch in the `get` method call of `javax.cache.Cache`, but I still can't handle the exception and the application crashes.

I would like to know what is the best practice to handle Redis unavailability exceptions at runtime with Redisson using JCache?

Here are the exceptions thrown with Redis down:

```
Caused by: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts, is non-idempotent command: false. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (EVAL), params: [if redis.call('hexists', KEYS[1], ARGV[2]) == 0 then return 0;end;local expireDateScore = redis.call..., 2, CACHE, jcache_timeout_set:{CACHE}, 1656922068654, PooledUnsafeDirectByteBuf(ridx: 0, widx: 40, cap: 256)], channel: [id: 0x5afe813f, L:/127.0.0.1:52382 - R:localhost/127.0.0.1:6379]
	at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$5(RedisExecutor.java:342)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

```
ERROR [org.redisson.client.handler.PingConnectionHandler] (redisson-timer-4-1) Unable to send PING command over channel: [id: 0x66577cba, L:/127.0.0.1:50646 - R:localhost/127.0.0.1:6379]: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://localhost:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.23.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/12926115/redisson-3.23.6-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
You need to catch CacheException.

```java
        try {
            cache.get(myKey);
        } catch (CacheException e) {
            ...
        }
```
