### ISSUE TITLE
SlaveConnectionPool no available

### ISSUE THREAD

**Issue by wangnimaa** [redisson/redisson#4408]
we use redisson version 3.16.2

org.springframework.data.redis.RedisConnectionFailureException: SlaveConnectionPool no available Redis entries. Master entry host: ip:port Disconnected hosts: [ip:port] Hosts disconnected due to errors during `failedSlaveCheckInterval`: [ip:port]; nested exception is org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: ip:port Disconnected hosts: [ip:port] Hosts disconnected due to errors during `failedSlaveCheckInterval`: [ip:port]
        at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:40)
        at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
        at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:230)
        at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:225)
        at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:386)
        at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:760)
        at org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:501)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:296)
        at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:46)
        at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:57)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:207)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:91)
        at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:43)

**Comment by mrniko** [comment]
Fixed in 3.17.0+
