### ISSUE TITLE
能否给一份与springboot的版本对应关系？

### ISSUE THREAD

**Issue by YoanLz** [redisson/redisson#4420]
我使用了多种版本都不能解决一下问题，
2022-07-15 09:22:22.773 ERROR 12572 --- [nio-8082-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause

java.lang.StackOverflowError: null
	at org.springframework.data.redis.connection.DefaultedRedisConnection.geoSearch(DefaultedRedisConnection.java:1550) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.geoSearch(DefaultedRedisConnection.java:1550) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.geoSearch(DefaultedRedisConnection.java:1550) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.geoSearch(DefaultedRedisConnection.java:1550) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.geoSearch(DefaultedRedisConnection.java:1550) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.geoSearch(DefaultedRedisConnection.java:1550) ~[spring-data-redis-2.6.1.jar:2.6.1]

**Comment by mrniko** [comment]
Fixed. Thanks for report!
