### ISSUE TITLE
Unable to acquire subscription lock after 

### ISSUE THREAD

**Issue by GNeeraja5** [redisson/redisson#4431]
Hi, we have seen this  `Unable to acquire subscription lock after 3000ms. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters` in our service, it looks like a transient issue but would like to understand what are the suggested values for `subscriptionsPerConnection/subscriptionConnectionPoolSize`. I see the defaults as 5/50 respectively. 
We have our cache through put for one of the near caches is ~30k+, I've read `subscriptionsPerConnection/subscriptionConnectionPoolSize` getting used for RLocalCachedMap. As we are using LocalCacheMap, would like to understand how we should configure these parameters for better support.

I went through this documentation to read about what are these params https://github.com/redisson/redisson/wiki/2.-Configuration but is there any detailed documentation to understand how they are getting used in RLocalCachedMap.

Redisson Client version: 3.17.3

Config:
connectTimeout: 10000
timeout: 3000
threads: 16
nettyThreads: 64

Stack Trace:
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 3000ms. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
        at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$5(PublishSubscribeService.java:194)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted

**Comment by mrniko** [comment]
There is no formula for these settings. Try to set subscriptionsPerConnection = 500 for your case.

**Comment by GNeeraja5** [comment]
okay, what about subscriptionConnectionPoolSize? Also, do we have any detailed documentation on what these parameters and how they are getting used in RLocalCacheMap.

**Comment by mrniko** [comment]
PubSub is used by RLocalCacheMap thus these settings affects it.
