### ISSUE TITLE
使用阿里云Redis集群的代理模式，同时使用Redsson做分布式锁时异常

### ISSUE THREAD

**Issue by somta** [redisson/redisson#4434]
前提
阿里云Redis集群的代理模式，同时使用Redsson做分布式锁

1.使用Redsson 1.14.0版本，使用lock方法能正常使用

2.升级到Redsson 1.14.1，使用lock方法出现以下异常
org.redisson.client.RedisException: ERR unknown command 'WAIT'. channel: [id: 0x7f74e48b, L:/172.16.74.253:62435 - R:/47.104.121.48:6379] command: (WAIT), params: [1, 1000]

	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:343)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:247)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:189)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)

问题
是在1.14.1改了lock方法的实现方式吗？看发出来的记录又没有相关说明

**Comment by mrniko** [comment]
Redisson uses WAIT command for slaves sync of lock state. Try to upgrade Redis to 3.0+

**Comment by somta** [comment]
I am using aliyun Redis 5.0, but there is still a problem

**Comment by mrniko** [comment]
Seems it doesn't support WAIT command

**Comment by somta** [comment]
Redsson 1.14.0 version is supported, but Redsson 1.14.1 and later versions have exceptions

**Comment by mrniko** [comment]
there is no such version

**Comment by somta** [comment]
> Redsson 1.14.0 version is supported, but Redsson 1.14.1 and later versions have exceptions

Sorry, I provided the wrong version, Redsson 3.14.0 version is supported, but Redsson 3.14.1 and later versions have exceptions

**Comment by SYZ-Coder** [comment]
你好，请问解决了嘛，是使用更高版本的redisson就行了嘛
