### ISSUE TITLE
Search domain query failed. Original hostname: 'r-xx.redis.rds.aliyuncs.com' failed to resolve 'r-xx.redis.rds.aliyuncs.com.default.svc.kaimeng.test.local'

### ISSUE THREAD

**Issue by XiongMMaq** [redisson/redisson#4435]
redisson : 3.13.1
netty: 4.1.49
aliyun redis : 5.0.5

Exception:

2022-07-20 22:29:18.348 [TID:N/A] [redisson-netty-5-21] [ERROR] org.redisson.connection.DNSMonitor - Unable to resolve [r-xx.redis.rds.aliyuncs.com](http://r-xx.redis.rds.aliyuncs.com/)
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: '[r-xx.redis.rds.aliyuncs.com](http://r-xx.redis.rds.aliyuncs.com/)' failed to resolve '[r-xx.redis.rds.aliyuncs.com.default.svc.kaimeng.test.local](http://r-xx.redis.rds.aliyuncs.com.default.svc.kaimeng.test.local/)'
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1014)
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:967)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414)
        at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63)
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:463)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225)
        at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/[192.168.0.10:53](http://192.168.0.10:53/)] query via UDP timed out after 5000 milliseconds (no stack trace available)

Occasional dns parsing exceptions , Is there any good solution?

**Comment by mrniko** [comment]
Some vendors has DNS query limit. Make sure you didn't face it.

**Comment by XiongMMaq** [comment]
In most cases, it is normal access; Only occasionally

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1625
