### ISSUE TITLE
redisson in 3.17.4, ping operation and pubsub operation in same redis connection

### ISSUE THREAD

**Issue by fightzhong** [redisson/redisson#4436]
our redisson version is 3.17.4, only use distributedLock and getset operation, i know distributedLock rely on publish/subscribe, then cause exception:

[redisson-timer-12-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x0fc73ad8, L:/ip1:60669 - R:host/ip2:port]
org.redisson.client.RedisException: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context. channel: [id: 0x0fc73ad8, L:/ip1:60669 - R:host/ip2:port] command: (PING), promise: java.util.concurrent.CompletableFuture@716e6295[Not completed, 1 dependents], params: []
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:98)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
> ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context. 

It's a Redis vendor specific issue. Which do you use?

**Comment by fightzhong** [comment]
> 
do you mean the redis version? my redis version is 2.8.4

**Comment by fightzhong** [comment]
It seems to be caused by the internal implementation of the redisson distributed lock,We didn't have such a problem in older redisson versions, lastday we upgrade the redisson version , then cause this problem

**Comment by fightzhong** [comment]
my redisson configuration is customized as follows:

Config.threads: 4
Config.nettyThreads: 8
SingleServerConfig.ConnectionMinimumIdleSize: 4
SingleServerConfig.keepAlive: true
SingleServerConfig.database: 0
SingleServerConfig.ConnectionPoolSize: 8

other properties are default value

**Comment by mrniko** [comment]
Early versions didn't ping pubsub channels.

> ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context

This error tells that Redis vendor doesn't support ping of PUBSUB channels. While Redis does.

**Comment by Comven** [comment]
> Early versions didn't ping pubsub channels.
> 
> > ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context
> 
> This error tells that Redis vendor doesn't support ping of PUBSUB channels. While Redis does.

how to resolve the problem without upgrade redis ?

**Comment by mrniko** [comment]
I'm afraid there is no solution.
