### ISSUE TITLE
COMMAND should not execute at SLAVE NODE when SLAVE READONLY

### ISSUE THREAD

**Issue by facelezzzz** [redisson/redisson#4442]
Hi,today we got an error:
```
org.redisson.client.RedisException: ERR Error running script (call to f_dd58b5241e0c5d436462d410d973bfc8ca285f5a): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   . channel: [id: 0x7b61ef51, L:/192.168.89.141:52082 - R:cdh01/172.21.13.212:6379] command: (EVAL), params: [local expiredIds = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, -1); if #expiredIds ..., 3, xetesh:xbound:line:212:callee:enfoiaj214312:limited-semaphore, {xetesh:xbound:line:212:callee:enfoiaj214312:limited-semaphore}:timeout, redisson_sc:{xetesh:xbound:line:212:callee:enfoiaj214312:limited-semaphore}, PooledUnsafeDirectByteBuf(ridx: 0, widx: 13, cap: 256)]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:343)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:178)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:102)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
```

and we have a cluster:
```
172.21.13.212:6379> CLUSTER NODES
6db37ba38c9e56a8fc118a9676622a9696b66477 172.21.13.213:6379@16379 master - 0 1658740475000 6 connected 0-5461
eb186c9dcf9f935d9dd328329cd10243d542f25a 172.21.13.212:6380@16380 slave 29f3a042230c16a3ba3121b47ef765f3071405ef 0 1658740477312 5 connected
65b27a7ad5d813f8005c1bee015054036b82d85c 172.21.13.213:6380@16380 master - 0 1658740476312 4 connected 5462-10923
29f3a042230c16a3ba3121b47ef765f3071405ef 172.21.13.214:6380@16380 master - 0 1658740478314 5 connected 10924-16383
8f7affe6a2c45dc2325bafe390c3113f1051c12e 172.21.13.214:6379@16379 slave 65b27a7ad5d813f8005c1bee015054036b82d85c 0 1658740477000 4 connected
569cd35b255d861f1e405398e784b961e1137e09 172.21.13.212:6379@16379 myself,slave 6db37ba38c9e56a8fc118a9676622a9696b66477 0 1658740474000 1 connected
```

As shown in the previous cluster nodes command,172.21.13.212:6379 is a slave of 172.21.13.213:6379.

any advice? thx

**Expected behavior**

call to f_dd58b5241e0c5d436462d410d973bfc8ca285f5a should be at MASTER NODE (172.21.13.213:6379)

**Actual behavior**
call to f_dd58b5241e0c5d436462d410d973bfc8ca285f5a at SLAVE NODE (172.21.13.212:6379)

**Steps to reproduce or test case**
Sometimes it appears

**Redis version**
```
172.21.13.212:6379> info
# Server
redis_version:4.0.14

172.21.13.212:6379> CLUSTER INFO
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:6
cluster_stats_messages_ping_sent:276803
cluster_stats_messages_pong_sent:259188
cluster_stats_messages_publish_sent:17723280
cluster_stats_messages_sent:18259271
cluster_stats_messages_ping_received:259188
cluster_stats_messages_pong_received:276804
cluster_stats_messages_publish_received:9166512
cluster_stats_messages_auth-req_received:1
cluster_stats_messages_received:9702505
```

**Redisson version**
```
redisson-spring-boot-starter:3.14.1
```

**Redisson configuration**
```
spring.redis.redisson.config={"clusterServersConfig":{"retryAttempts":20,"retryInterval":2000,"nodeAddresses":["redis://172.21.13.212:6379","redis://172.21.13.213:6379","redis://172.21.13.214:6379","redis://172.21.13.212:6380","redis://172.21.13.213:6380","redis://172.21.13.214:6380"],"connectTimeout":30000},"codec":{"class":"org.redisson.codec.JsonJacksonCodec"}}
```

**Comment by facelezzzz** [comment]
sorry for misconfiguration
