### ISSUE TITLE
Command execution timeout for command: (PING)

### ISSUE THREAD

**Issue by WLP-Lxr** [redisson/redisson#4451]
redisson version: 3.17.0
redis version: 6.2.4
reids cluster: master 20    slaves 40
redis config：
  connectTimeout: 5000
  timeout: 1000
  retryAttempts: 3
  retryInterval: 100
  slaveConnectionMinimumIdleSize: 5
  slaveConnectionPoolSize: 10
  masterConnectionMinimumIdleSize: 1
  masterConnectionPoolSize: 5
  idleConnectionTimeout: 10000
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  scanInterval: 30000
  threads: 0
  nettyThreads: 16
  transportMode: NIO

I always receive this error with same servers ：

ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x100dcad5, L:XXXX / - R:XXXX]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://XXXXX]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:245)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

My older redisson version is 3.16.7，I tried to upgrade the redisson version to 3.17.0 ，But it can't solve this problem.

**Comment by mrniko** [comment]
Can you share full stacktrace?

**Comment by WLP-Lxr** [comment]
[redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x954e36ba, L:0.0.0.0/0.0.0.0:40500 ! R:xxxxxxx]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://xxxxxxxxx]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:245)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by WLP-Lxr** [comment]
> Can you share full stacktrace?

[redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x954e36ba, L:0.0.0.0/0.0.0.0:40500 ! R:xxxxxxx]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://xxxxxxxxx]
at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:245)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

**Comment by khuynhthanhchiluyen** [comment]
it's the same for me, even after that my application tried to connect back again to redis

**Comment by lee-create** [comment]
it's the same for me (redisson v3.17.5, redis v6.2.7), I suspect there is a problem here。
![image](https://user-images.githubusercontent.com/54739954/186124930-f335d92f-bddd-4525-a19a-560390e6c3f2.png)

**Comment by mrniko** [comment]
It might be connected to https://github.com/redisson/redisson/issues/4441

**Comment by lee-create** [comment]
> 它可能连接到#4441
OK，I see，thanks。
