### ISSUE TITLE
Question: What will cause permanent blocking

### ISSUE THREAD

**Issue by 421119407** [redisson/redisson#4457]
Hello,I have a problem in my project.
My thread is inexplicably blocked forever. Also, Redisson-netty-thread works fine (RUNNABLE).
Please under what circumstances does this happen?
redission version: 3.12.5
Thread Stack:
`"Thread-132199" #807065 prio=10 os_prio=0 tid=0x00007f2461b6f000 nid=0xfc5f in Object.wait() [0x00007f23f39f8000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:252)
	- locked <0x00000006e509c548> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:139)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonLock.unlock(RedissonLock.java:477)
	at com.ecom.schedule.xxl.XxlScheduleManager.scanNewJob(XxlScheduleManager.java:161)
	at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)`

**Comment by mrniko** [comment]
Can you share Redisson config?

**Comment by 421119407** [comment]
redis:
    sentinel:
      master: XXX
      nodes:
        - xxx
        - xxx
        - xxx
    database: 0
Other configurations of redisson are used by default.
redisson-netty thread count is 32.
I have a question to ask, if the redis request does not receive the response, will it cause continuous blocking?

**Comment by 421119407** [comment]
> Can you share Redisson config?

redis:
sentinel:
master: XXX
nodes:
- xxx
- xxx
- xxx
database: 0
Other configurations of redisson are used by default.
redisson-netty thread count is 32.
I have a question to ask, if the redis request does not receive the response, will it cause continuous blocking?

**Comment by mrniko** [comment]
> I have a question to ask, if the redis request does not receive the response, will it cause continuous blocking?

I'm working on fix

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4459
