### ISSUE TITLE
Redisson async call gets stuck with Redisson Tracing

### ISSUE THREAD

**Issue by dannylee-** [redisson/redisson#4461]
I have a setup where we use Redisson for sessions and other caches.

When a session is retrieved from Redis, it has to deserialize the object and during deserialization of one of our objects, we make another call to Redis using RMap.get().

At that point, I ran into this IllegalStateException (https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/command/CommandAsyncService.java#L122).

So what I did was replaced RMap.get() with an RMap.getAsync().toCompletableFuture().get() (Basically just copied CommandAsyncService.get() except without the Thread name check).  So something like this:

```
RFuture<Object> future = rMap.getAsync(key);
try {
  return future.toCompletableFuture().get();
} catch (InterruptedException e) {
  future.cancel(true);
  Thread.currentThread().interrupt();
  throw new RedisException(e);
} catch (ExecutionException e) {
  if (e.getCause() instanceof RedisException) {
    throw (RedisException)e.getCause();
  }
  throw new RedisException("Unexpected exception while processing command", e.getCause());
}
```

This caused the CompletableFuture to never complete with the following stacktrace.  This also wasn't a nested redisson call, so it wasn't even running as a thread that started with "redisson-netty"

```
java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c2dc4850> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.appiancorp.cache.RedisCacheBase.lambda$get$1(RedisCacheBase.java:153)
```

I saw this issue comment - https://github.com/redisson/redisson/issues/3549#issuecomment-818739165, so I thought the worst that could happen was a timeout somewhere.  So I have two questions:

1.  Any ideas on why the above change would cause CompletableFuture to get stuck?
2. Do you have an example of running the RMap.get() call in a separate executor service?

**Comment by dannylee-** [comment]
It looks like it has something to do with the tracing library we are using with redisson.  I haven't figured out why, but for anyone else running into this issue, we are using opentracing-redis-redission-0.1.16

**Comment by dannylee-** [comment]
I've zero'd in on the issue.  It looks like the [TracingRedissonHelper](https://github.com/opentracing-contrib/java-redis-client/blob/master/opentracing-redis-redisson/src/main/java/io/opentracing/contrib/redis/redisson/TracingRedissonHelper.java#L37) is wrapping the future (that has already been completed) with a CompletableRFuture and the CompletableRFuture doesn't override the toCompletableFuture, so it's status is still "Not completed".  Since the redis call was already successful, the new future is waiting on a signal that will never come.

There's still some weirdness going on that I can't explain (it doesn't seem like a race condition).  Still investigating.

**Comment by dannylee-** [comment]
I think the bug is in [this class](https://github.com/opentracing-contrib/java-redis-client/blob/9f9def3f0fa0eab5712f125ae774349a688a89dc/opentracing-redis-redisson/src/main/java/io/opentracing/contrib/redis/redisson/TracingRedissonHelper.java#L71).  It's creating the span, but then we never pass the span to the continueScopeSpan call.  Instead, we get the span from [tracer.getSpan](https://github.com/opentracing-contrib/java-redis-client/blob/master/opentracing-redis-redisson/src/main/java/io/opentracing/contrib/redis/redisson/TracingRedissonHelper.java#L36), which isn't the correct span since we never activated the built span.

If the activeSpan happened to be null, then it would never complete the wrapped future and therefore, when you call onCompletableFuture().get() on wrapped future, it gets stuck.

**Comment by dannylee-** [comment]
I'm not 100% sure this is the correct fix (still getting familiar with the tracing library), but this at least prevented it from a hanging - https://github.com/opentracing-contrib/java-redis-client/compare/master...dannylee-:java-redis-client:redisson-fix-async?expand=1
