### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH)

### ISSUE THREAD

**Issue by qq502361472** [redisson/redisson#4463]
偶发启动报错，错误信息
```java
2022-08-04 17:00:54.345  INFO 5732 --- [           main] com.test.config.RedissonConfig           : ===> 加载集群模式的redisson ...
2022-08-04 17:00:54.534  INFO 5732 --- [           main] org.redisson.Version                     : Redisson 3.17.3
2022-08-04 17:00:55.239  INFO 5732 --- [           main] o.r.cluster.ClusterConnectionManager     : Redis cluster nodes configuration got from **.*.**.**/**.*.**.**:6379:
d148f0c1b019ecd8b15bf207d3ef188737111708 **.*.**.**:6381@16381 slave 2a3da9cbc3360a6be187477e12d38601c8f7f825 0 1659603638070 30 connected
99497eadb64dee7e6328a0ed0cb948094f5aa1e9 **.*.**.**:6383@16383 slave f564ccc551dd3378658fef692f766b18d624a369 0 1659603640079 28 connected
2a3da9cbc3360a6be187477e12d38601c8f7f825 **.*.**.**:6384@16384 master - 0 1659603639000 30 connected 5461-10922
ac94323e413fb99e7ee8a8dcb8fc075300d505e6 **.*.**.**:6380@16380 master - 0 1659603639075 25 connected 10923-16383
b24b326be748f470e1871ba09135396362cf110e **.*.**.**:6379@16379 myself,slave ac94323e413fb99e7ee8a8dcb8fc075300d505e6 0 1659603640000 24 connected
f564ccc551dd3378658fef692f766b18d624a369 **.*.**.**:6382@16382 master - 0 1659603641088 28 connected 0-5460

2022-08-04 17:00:55.810  INFO 5732 --- [isson-netty-2-1] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for **.*.**.**/**.*.**.**:6384
2022-08-04 17:00:55.811  INFO 5732 --- [isson-netty-2-6] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for **.*.**.**/**.*.**.**:6380
2022-08-04 17:00:55.816  INFO 5732 --- [isson-netty-2-2] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for **.*.**.**/**.*.**.**:6382
2022-08-04 17:00:59.032  INFO 5732 --- [isson-netty-2-8] o.r.c.pool.MasterConnectionPool          : 32 connections initialized for **.*.**.**/**.*.**.**:6380
2022-08-04 17:00:59.041  INFO 5732 --- [isson-netty-2-3] o.r.c.pool.MasterConnectionPool          : 32 connections initialized for **.*.**.**/**.*.**.**:6384
2022-08-04 17:00:59.055  INFO 5732 --- [isson-netty-2-1] o.r.c.pool.MasterConnectionPool          : 32 connections initialized for **.*.**.**/**.*.**.**:6382
2022-08-04 17:00:59.366  INFO 5732 --- [isson-netty-2-1] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for **.*.**.**/**.*.**.**:6379
2022-08-04 17:00:59.366  INFO 5732 --- [isson-netty-2-6] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for **.*.**.**/**.*.**.**:6381
2022-08-04 17:00:59.428  INFO 5732 --- [isson-netty-2-2] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for **.*.**.**/**.*.**.**:6383
2022-08-04 17:01:02.575  INFO 5732 --- [isson-netty-2-2] o.r.cluster.ClusterConnectionManager     : slaves: [redis://**.*.**.**:6381] added for slot ranges: [[5461-10922]]
2022-08-04 17:01:02.575  INFO 5732 --- [isson-netty-2-2] o.r.cluster.ClusterConnectionManager     : master: redis://**.*.**.**:6384 added for slot ranges: [[5461-10922]]
2022-08-04 17:01:02.575  INFO 5732 --- [isson-netty-2-2] o.r.connection.pool.SlaveConnectionPool  : 32 connections initialized for **.*.**.**/**.*.**.**:6381
2022-08-04 17:01:02.629  INFO 5732 --- [isson-netty-2-7] o.r.cluster.ClusterConnectionManager     : slaves: [redis://**.*.**.**:6383] added for slot ranges: [[0-5460]]
2022-08-04 17:01:02.629  INFO 5732 --- [isson-netty-2-7] o.r.cluster.ClusterConnectionManager     : master: redis://**.*.**.**:6382 added for slot ranges: [[0-5460]]
2022-08-04 17:01:02.629  INFO 5732 --- [isson-netty-2-7] o.r.connection.pool.SlaveConnectionPool  : 32 connections initialized for **.*.**.**/**.*.**.**:6383
2022-08-04 17:01:04.236 ERROR 5732 --- [isson-netty-2-3] o.r.cluster.ClusterConnectionManager     : unable to add slave for: redis://**.*.**.**:6380 slot ranges: [[10923-16383]]

java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 24 of 32 were initialized. Redis server: **.*.**.**/**.*.**.**:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire$$$capture(CompletableFuture.java:646) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[na:1.8.0_301]
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:151) ~[redisson-3.17.3.jar:3.17.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[na:1.8.0_301]
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:307) ~[redisson-3.17.3.jar:3.17.3]
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:273) ~[redisson-3.17.3.jar:3.17.3]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[na:1.8.0_301]
	at org.redisson.client.RedisClient$1$1.run(RedisClient.java:226) ~[redisson-3.17.3.jar:3.17.3]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_301]
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 24 of 32 were initialized. Redis server: **.*.**.**/**.*.**.**:6379
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:150) ~[redisson-3.17.3.jar:3.17.3]
	... 19 common frames omitted
Caused by: java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://**.*.**.**:6379]
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925) ~[na:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913) ~[na:1.8.0_301]
	... 11 common frames omitted
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://**.*.**.**:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.3.jar:3.17.3]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	... 2 common frames omitted
```
配置
```java
 @Bean(destroyMethod = "shutdown")
    @ConditionalOnProperty(name = "redis.model", havingValue = "cluster", matchIfMissing = false)
    public RedissonClient redisson() {
        log.info("===> 加载集群模式的redisson ...");
        String[] nodes = redisProperties.getCluster().getNodes().stream()
                .map(node -> REDIS_PROTOCOL_PREFIX + node).toArray(String[]::new);

        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config
                .setCodec(JsonJacksonCodec.INSTANCE)
                .setThreads(redissonProperties.getThreads())
                .setNettyThreads(redissonProperties.getNettyThreads())
                .useClusterServers();
        clusterServersConfig
                .setPassword(redisProperties.getPassword())//设置密码
                .setPingConnectionInterval(redissonProperties.getPingConnectionInterval()) // ping连接间隔
                .setScanInterval(redissonProperties.getScanInterval()) // 主节点变化扫描间隔时间
                .setRetryInterval(redissonProperties.getRetryInterval()) // 命令重试发送时间间隔
                .setTimeout(redissonProperties.getTimeout()) // 命令等待超时
                .setSubscriptionConnectionPoolSize(redissonProperties.getSubscriptionConnectionPoolSize()) // 从节点发布和订阅连接池大小
                .setSubscriptionConnectionMinimumIdleSize(redissonProperties.getSubscriptionConnectionMinimumIdleSize()) // 从节点发布和订阅连接的最小空闲连接数
                .setSlaveConnectionPoolSize(redissonProperties.getSlaveConnectionPoolSize()) // 从节点连接池大小
                .setSlaveConnectionMinimumIdleSize(redissonProperties.getSlaveConnectionMinimumIdleSize()) //从节点最小空闲连接数
                .setMasterConnectionPoolSize(redissonProperties.getMasterConnectionPoolSize()) // 主节点连接池大小
                .setMasterConnectionMinimumIdleSize(redissonProperties.getMasterConnectionMinimumIdleSize()); // 主节点最小空闲连接数
//        if (!SpringUtil.getBean(RedisKeyConcatComponent.class).isProdOrUat()) {
//            clusterServersConfig.setNameMapper(new CustomNameMapper());
//        }
        clusterServersConfig
                .addNodeAddress(nodes)
                .setConnectTimeout(redissonProperties.getConnectTimeout())
                .setPassword(redisProperties.getPassword());
        return Redisson.create(config);
    }

    /**
     * 集群模式下优先加载RedissonConfig ,加载lettuceConfig集群下redis key过期监听会失败
     */
    @Bean
    @Order(Ordered.LOWEST_PRECEDENCE - 3)
    public RedissonConnectionFactory redissonConnectionFactory(RedissonClient redisson) {
        return new RedissonConnectionFactory(redisson);
    }

    @Bean
    public RedisMessageListenerContainer redisMessageListenerContainer(RedisConnectionFactory redisConnectionFactory) {
        RedisMessageListenerContainer container = new RedisMessageListenerContainer();
        container.setConnectionFactory(redisConnectionFactory);
        return container;
    }
```

```java
@Data
@ConfigurationProperties(prefix = "redisson.cluster")
public class RedissonProperties {

    /**
     * ping连接间隔
     */
    private Integer pingConnectionInterval = 30000;
    /**
     * 从节点最小空闲连接数
     * 多从节点的环境里，每个 从服务节点里用于普通操作（非 发布和订阅）的最小保持连接数（长连接）。长期保持一定数量的连接有利于提高瞬时读取反映速度。
     */
    private Integer slaveConnectionMinimumIdleSize = 24;

    /**
     * 从节点连接池大小
     * 多从节点的环境里，每个 从服务节点里用于普通操作（非 发布和订阅）连接的连接池最大容量。连接池的连接数量自动弹性伸缩。
     */
    private Integer slaveConnectionPoolSize = 64;

    /**
     * 主节点最小空闲连接数
     * 多从节点的环境里，每个 主节点的最小保持连接数（长连接）。长期保持一定数量的连接有利于提高瞬时写入反应速度。
     */
    private Integer masterConnectionMinimumIdleSize = 24;

    /**
     * 主节点连接池大小
     * 主节点的连接池最大容量。连接池的连接数量自动弹性伸缩。
     */
    private Integer masterConnectionPoolSize = 64;

    /**
     * 从节点发布和订阅连接的最小空闲连接数
     * 多从节点的环境里，每个 从服务节点里用于发布和订阅连接的最小保持连接数（长连接）。Redisson内部经常通过发布和订阅来实现许多功能。长期保持一定数量的发布订阅连接是必须的。
     */
    private Integer subscriptionConnectionMinimumIdleSize = 1;

    /**
     * 从节点发布和订阅连接池大小
     * 多从节点的环境里，每个 从服务节点里用于发布和订阅连接的连接池最大容量。连接池的连接数量自动弹性伸缩。
     */
    private Integer subscriptionConnectionPoolSize = 50;

    /**
     * 主节点变化扫描间隔时间
     * 对主节点变化节点状态扫描的时间间隔。单位是毫秒。
     *
     */
    private Integer scanInterval = 5000;

    /**
     * Netty线程池数量
     * 这个线程池数量是在一个Redisson实例内，被其创建的所有分布式数据类型和服务，以及底层客户端所一同共享的线程池里保存的线程数量。
     */
    private Integer nettyThreads = 32;

    /**
     * 命令重试发送时间间隔，单位：毫秒
     * 在某个节点执行相同或不同命令时，连续 失败 failedAttempts（执行失败最大次数） 时，该节点将被从可用节点列表里清除，直到 reconnectionTimeout（重新连接时间间隔） 超时以后再次尝试。
     */
    private Integer retryInterval = 1500;
    private int retryAttempts = 3;

    /**
     * 命令等待超时，单位：毫秒
     * 等待节点回复命令的时间。该时间从命令发送成功时开始计时。
     */
    private Integer timeout = 3000;

    /**
     * 线程池数量
     * 这个线程池数量被所有RTopic对象监听器，RRemoteService调用者和RExecutorService任务共同共享。
     */
    private Integer threads = 16;

    private int failedSlaveReconnectionInterval = 3000;

    private int failedSlaveCheckInterval = 180000;

    private ReadMode readMode = ReadMode.SLAVE;
    private SubscriptionMode subscriptionMode = SubscriptionMode.MASTER;
    private long dnsMonitoringInterval = 5000;
    private int connectTimeout = 10000;
    private int idleConnectionTimeout = 10000;
}
```

```yaml
redis:
  model: cluster
redisson:
  cluster:
    pingConnectionInterval: 30000
    slaveConnectionMinimumIdleSize: 32
    slaveConnectionPoolSize: 64
    masterConnectionMinimumIdleSize: 32
    masterConnectionPoolSize: 64
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 8
    scanInterval: 5000
    nettyThreads: 8
    retryInterval: 1500
    timeout: 5000
    connectionTimeout: 10000
    threads: 4
```

**Comment by mrniko** [comment]
It's a connection issue. Try to reduce size of connection pool.

**Comment by qq502361472** [comment]
我减小了连接数，配置主从分别都是2，还是偶尔会出现AUTH命令超时的问题

**Comment by CRIOCM** [comment]
@qq502361472 你是macos吗？把连接池改小就好了是吗？

**Comment by qq502361472** [comment]
> @qq502361472 你是macos吗？把连接池改小就好了是吗？

没好，我不是mac，我是windows和linux都有问题

**Comment by qq502361472** [comment]
你有微信吗，我们加一下微信13120535479



发自我的iPhone


------------------ Original ------------------
From: XJH233 ***@***.***&gt;
Date: Wed,Aug 10,2022 6:07 PM
To: redisson/redisson ***@***.***&gt;
Cc: HuJian ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [redisson/redisson] org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH) (Issue #4463)





 
@qq502361472 你是macos吗？把连接池改小就好了是吗？

**Comment by libinglong** [comment]
This issue should not be closed. We do not need to reduce the connetion pool size unless the server connection is full.

**Comment by zeuschou001** [comment]
The cause and solution of the problem have not been given yet. Why is this problem closed?
