### ISSUE TITLE
Redis URL issue, not able to resolve correct URI -  hostname can't be null error

### ISSUE THREAD

**Issue by ankits114** [redisson/redisson#4475]
Hi Team,

We are facing issue while setting address for redis.

config.useSingleServer().setAddress(redis://192.168.8.8:8787);

We are getting following values for the above address url :

[2022-08-09 02:04:44,367] INFO  [RedissonUtil.java,185] addressCreator : 192.168.8.8:8787
[2022-08-09 02:04:44,368] INFO  [RedissonUtil.java,188] redisConnectionUrl : redis://192.168.8.8:8787
[2022-08-09 02:04:44,377] INFO  [RedissonUtil.java,191] redisConnectionUrl address : //redis://192.168.8.8:8787
[2022-08-09 02:04:44,385] INFO  [RedissonUtil.java,192] config.useSingleServer().getAddress().getHost() : redis
[2022-08-09 02:04:44,385] INFO  [RedissonUtil.java,193] config.useSingleServer().getAddress().getPort() : -1
[2022-08-09 02:04:44,386] INFO  [RedissonUtil.java,194] config.useSingleServer().getAddress().getPath() : //192.168.8.8:8787
[2022-08-09 02:04:44,388] INFO  [RedissonUtil.java,195] config.useSingleServer().getAddress().getScheme() : null
[2022-08-09 02:04:44,389] INFO  [RedissonUtil.java,196] config.useSingleServer().getAddress().getAuthority() : redis:
[2022-08-09 02:04:44,389] INFO  [RedissonUtil.java,197] config.useSingleServer().getAddress().getSchemeSpecificPart() : //redis://192.168.8.8:8787
[2022-08-09 02:04:44,392] INFO  [RedissonUtil.java,198] config.useSingleServer().getAddress().toString() : //[redis://192.168.8.8:8787](redis://54.251.163.28:8992)

Caused by: java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
	at org.redisson.client.RedisClient.<init>(RedisClient.java:93)
	at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:310)
	at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:298)
	at org.redisson.connection.SingleEntry.setupMasterEntry(SingleEntry.java:47)
	at org.redisson.connection.MasterSlaveConnectionManager.initEntry(MasterSlaveConnectionManager.java:247)
	at org.redisson.connection.MasterSlaveConnectionManager.init(MasterSlaveConnectionManager.java:229)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:155)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:43)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:166)
	at org.redisson.Redisson.<init>(Redisson.java:103)

On the same server for other application, same code and same url is working fine without any error.

if i changed the url to only IP and port then it is working fine.
e.g. config.useSingleServer().setAddress(192.168.8.8:8787);

could you please help to get the RCA of this issue asap.

Thanks,

**Comment by ankits114** [comment]
Any update team ?

**Comment by mrniko** [comment]
Unable to reproduce
