### ISSUE TITLE
retry not working when Lua script attempted to execute a command 

### ISSUE THREAD

**Issue by kamalbctg** [redisson/redisson#4482]
some time getting following exception in log when perform manual failover. will retry work in this case?
```
org.redisson.client.RedisException: ERR Error running script (call to f_c120d5c92fb6e155437575ff8931f09bf72e4148): @user_script:1: @user_script: 1: Lua script attempted to execute a command while the cluster is down. channel: [id: 0xd7747050, L:/172.17.0.8:52830 - R:100.67.68.6/100.67.68.6:7002] command: (EVAL), params: [redis.replicate_commands();local connection, qpm, qps, min, sec, logcon;connection =  tonumber(redis..., 0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:345)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mrniko** [comment]
I think failover executed incorrectly since topology reports to early that Redis node with IP 100.67.68.6 joined and could be used for commands execution.

**Comment by kamalbctg** [comment]
Thank you for reply, Does retry work in this scenario?

**Comment by mrniko** [comment]
No, since Lau engine reports an error
