### ISSUE TITLE
What about creating a task cron expression

### ISSUE THREAD

**Issue by liuzhi45** [redisson/redisson#4506]
When I create a task I use the following code:
` RedissonClient redissonClient = SpringUtil.getBean(RedissonClient.class);
 RScheduledExecutorService executorService = redissonClient.getExecutorService("schedule-executor-new");
 executorService.schedule(taskId,new RunnableTask(), CronSchedule.of("0 0 0 * * ? "));`
 
But there will be an Invalid cron expression exception:
`Caused by: java.lang.IllegalArgumentException: Invalid cron expression [0 0 0 * * ? *], expected 6 field, got 7
	at org.redisson.executor.CronExpression.<init>(CronExpression.java:295) ~[redisson-3.17.5.jar:3.17.5]
	at org.redisson.executor.CronExpression.<init>(CronExpression.java:282) ~[redisson-3.17.5.jar:3.17.5]
	at org.redisson.executor.TasksRunnerService.schedule(TasksRunnerService.java:140) ~[redisson-3.17.5.jar:3.17.5]`
          
Where am i doing wrong?
use version 3.17.5

**Comment by SplotyCode** [comment]
Currently the optional year field (7th field) is not supported you can simply remove it. See #4438

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/95553c8efba4534b50b125c8bde5117346f2a118
