### ISSUE TITLE
Failure when connecting on Sentinel SSL

### ISSUE THREAD

**Issue by jaudiger** [redisson/redisson#4519]
**Expected behavior**

When the certificates do only contain DNS names and not IP for the Redis nodes, it should work.

But maybe I missed something in the configuration of the sentinels on my application side. I don't know why it tries to resolve the DNS when authenticating the Redis nodes.

**Actual behavior**

```log
2022-08-30 14:55:20.772 DEBUG 322276 --- [isson-netty-2-4] org.redisson.client.RedisConnection      : Connection created [addr=rediss://redis-node-0.redis-headless.default.svc.cluster.local:26379]
2022-08-30 14:55:21.006  INFO 322276 --- [           main] o.r.c.SentinelConnectionManager          : master: rediss://10.42.0.149:6379 added
2022-08-30 14:55:21.050 DEBUG 322276 --- [           main] o.r.c.SentinelConnectionManager          : slave rediss://10.42.0.150:6379 state: {name=redis-node-1.redis-headless.default.svc.cluster.local:6379, ip=redis-node-1.redis-headless.default.svc.cluster.local, port=6379, runid=c7c4aedf8b7988d9faddca722afb2b4aa8cf6bb1, flags=slave, link-pending-commands=0, link-refcount=1, last-ping-sent=0, last-ok-ping-reply=498, last-ping-reply=498, down-after-milliseconds=4000, info-refresh=6399, role-reported=slave, role-reported-time=1549342, master-link-down-time=0, master-link-status=ok, master-host=redis-node-0.redis-headless.default.svc.cluster.local, master-port=6379, slave-priority=100, slave-repl-offset=593045, replica-announced=1}
2022-08-30 14:55:21.051  INFO 322276 --- [           main] o.r.c.SentinelConnectionManager          : slave: rediss://10.42.0.150:6379 added
2022-08-30 14:55:21.076 DEBUG 322276 --- [           main] o.r.c.SentinelConnectionManager          : slave rediss://10.42.0.151:6379 state: {name=redis-node-2.redis-headless.default.svc.cluster.local:6379, ip=redis-node-2.redis-headless.default.svc.cluster.local, port=6379, runid=86d5e00d94d3b63a7813638dd5b2eeee66df3214, flags=slave, link-pending-commands=0, link-refcount=1, last-ping-sent=0, last-ok-ping-reply=308, last-ping-reply=308, down-after-milliseconds=4000, info-refresh=7056, role-reported=slave, role-reported-time=1519266, master-link-down-time=0, master-link-status=ok, master-host=redis-node-0.redis-headless.default.svc.cluster.local, master-port=6379, slave-priority=100, slave-repl-offset=592784, replica-announced=1}
2022-08-30 14:55:21.076  INFO 322276 --- [           main] o.r.c.SentinelConnectionManager          : slave: rediss://10.42.0.151:6379 added
2022-08-30 14:55:21.170 DEBUG 322276 --- [sson-netty-2-10] org.redisson.client.RedisConnection      : Connection created [addr=rediss://10.42.0.151:26379]
2022-08-30 14:55:21.187 DEBUG 322276 --- [isson-netty-2-1] org.redisson.client.RedisConnection      : Connection created [addr=rediss://10.42.0.149:26379]
2022-08-30 14:55:21.188 DEBUG 322276 --- [sson-netty-2-12] org.redisson.client.RedisConnection      : Connection created [addr=rediss://10.42.0.150:26379]
2022-08-30 14:55:21.222 ERROR 322276 --- [sson-netty-2-10] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xc345b295, L:/10.42.0.0:40614 ! R:10.42.0.151/10.42.0.151:26379]

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 10.42.0.151 found
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 10.42.0.151 found
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1549)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1395)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	... 17 common frames omitted
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 10.42.0.151 found
	at java.base/sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:165)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:101)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:452)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:426)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:292)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
	... 31 common frames omitted

2022-08-30 14:55:21.224 ERROR 322276 --- [isson-netty-2-2] o.r.c.SentinelConnectionManager          : javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 10.42.0.151 found
```

**Steps to reproduce or test case**

- Launch Redis with 3 nodes + sentinels with SSL support
- Certificates are only configured with the DNS of the servers, and does not contain the IP

**Redis version**

7.0.4

**Redisson version**

3.17.6

**Redisson configuration**

Just setting the master name and the sentinels' hosts.

**Comment by mrniko** [comment]
Seems ssl certificate doesn't have this IP address. You need to set `sslEnableEndpointIdentification = false` in this case
