### ISSUE TITLE
NullPointerException with Micronaut graalvm

### ISSUE THREAD

**Issue by viacheslav-maksimov** [redisson/redisson#4543]
**Expected behavior**
No exceptions while executing application with graalvm and micronaut.

**Steps to reproduce or test case**
The exception throws at the time of raising context. 

**Actual behavior**
`07:54:59.724 [redisson-netty-2-2] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.client.RedisClient$1.operationComplete()
java.lang.NullPointerException: null
        at org.redisson.client.RedisClient$1.operationComplete(RedisClient.java:217)
        at org.redisson.client.RedisClient$1.operationComplete(RedisClient.java:206)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
07:54:59.724 [redisson-netty-2-1] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.client.RedisClient$2.operationComplete()
java.lang.NullPointerException: null
        at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:274)
        at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:263)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
07:54:59.724 [redisson-netty-2-2] ERROR org.redisson.client.handler.ErrorsLoggingHandler - Exception occured. Channel: [id: 0xd86ac778, L:/172.XX.X.X:36006 - R:XXXXXXXXXXX/172.XX.XX.XX:6379]
java.lang.NullPointerException: null
        at org.redisson.client.handler.PingConnectionHandler.channelActive(PingConnectionHandler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
        at org.redisson.client.handler.ConnectionWatchdog.channelActive(ConnectionWatchdog.java:66)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)`

**Redis version**
7.0.4

**Redisson version**
3.17.5

**Micronaut version(lambda)**
3.6.0

**Graalvm version**
graalvm-ce:ol8-java11-22.2.0

**MAVEN_VERSION**
3.8.6

**Redisson configuration**
 reflect-config.json with following parameters:
[
  {
    "name": "java.lang.reflect.Proxy",
    "fields": [
      {
        "name": "h"
      }
    ]
  },
  {
    "name": "org.redisson.client.handler.ConnectionWatchdog",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.redisson.client.handler.PingConnectionHandler",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.handler.codec.dns.DatagramDnsQueryEncoder",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.channel.DefaultChannelPipeline$HeadContext",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.redisson.client.handler.CommandEncoder",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.redisson.client.handler.CommandBatchEncoder",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.redisson.client.handler.ErrorsLoggingHandler",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.channel.DefaultChannelPipeline$TailContext",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.resolver.dns.DnsNameResolver$1",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.resolver.dns.DnsNameResolver$2",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.resolver.dns.DnsNameResolver$3",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.handler.codec.dns.DatagramDnsQueryEncoder",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.redisson.client.handler.RedisChannelInitializer",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer$1",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer$2",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer$3",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer$4",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer$1",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.handler.codec.http.HttpContentDecompressor",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.handler.codec.http.HttpClientCodec",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.micronaut.http.client.netty.DefaultHttpClient$HttpClientInitializer",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "io.netty.bootstrap.ServerBootstrap$1",
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  }
]

**Comment by mrniko** [comment]
Can you share some sample project to run?

**Comment by viacheslav-maksimov** [comment]
there is a sample project with embedded application to simplify the running - https://github.com/viacheslav-maksimov/micronaut-demo-graalvm

**Comment by mrniko** [comment]
Much thanks for the sample project! I updated redisson-micronaut\redisson-micronaut-30\src\main\resources\META-INF\native-image\org.redisson\redisson\reflect-config.json please copy or wait for the next release.

**Comment by viacheslav-maksimov** [comment]
I already had this configuration in my reflect-config.json. Is something else changed?

**Comment by mrniko** [comment]
I'm afraid no, it differs even by size. Anyway I also updated it today.

**Comment by viacheslav-maksimov** [comment]
But how can be resolved my NullpointerException?

**Comment by mrniko** [comment]
It's related to incorrect reflect-config.json

I reproduced the NPE then added description for Proxy object to redisson-micronaut\redisson-micronaut-30\src\main\resources\META-INF\native-image\org.redisson\redisson\reflect-config.json and replaced it your's copy. Now it works.

**Comment by arenick001** [comment]
maybe the same question...
```
Caused by: java.lang.ExceptionInInitializerError
        at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:150)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.<init>(DnsServerAddressStreamProviders.java:130)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder.<clinit>(DnsServerAddressStreamProviders.java:128)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders.unixDefault(DnsServerAddressStreamProviders.java:117)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:113)
        at org.redisson.connection.ServiceManager.<init>(ServiceManager.java:206)
        at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:78)
        at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:28)
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:200)
        at org.redisson.Redisson.<init>(Redisson.java:70)
        at org.redisson.Redisson.create(Redisson.java:115)
        at org.redisson.micronaut.RedissonFactory.redisson(RedissonFactory.java:47)
        at org.redisson.micronaut.$RedissonFactory$Redisson0$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
        ... 102 more
Caused by: java.lang.NullPointerException
        at java.base@17.0.6/sun.net.dns.ResolverConfigurationImpl.stringToList(ResolverConfigurationImpl.java:69)
        at java.base@17.0.6/sun.net.dns.ResolverConfigurationImpl.loadConfig(ResolverConfigurationImpl.java:136)
        at java.base@17.0.6/sun.net.dns.ResolverConfigurationImpl.nameservers(ResolverConfigurationImpl.java:159)
        at jdk.naming.dns@17.0.6/com.sun.jndi.dns.DnsContextFactory.serversForUrls(DnsContextFactory.java:149)
        at jdk.naming.dns@17.0.6/com.sun.jndi.dns.DnsContextFactory.getContext(DnsContextFactory.java:81)
        at jdk.naming.dns@17.0.6/com.sun.jndi.dns.DnsContextFactory.urlToContext(DnsContextFactory.java:120)
        at jdk.naming.dns@17.0.6/com.sun.jndi.dns.DnsContextFactory.getInitialContext(DnsContextFactory.java:64)
        at java.naming@17.0.6/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
        at java.naming@17.0.6/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at java.naming@17.0.6/javax.naming.InitialContext.init(InitialContext.java:236)
        at java.naming@17.0.6/javax.naming.InitialContext.<init>(InitialContext.java:208)
        at java.naming@17.0.6/javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:130)
        at io.netty.resolver.dns.DirContextUtils.addNameServers(DirContextUtils.java:49)
        at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:55)
        ... 116 more
```
redisson-micronaut-40: 3.29.0
micronaut: 4.4.6


> It's related to incorrect reflect-config.json
> 
> I reproduced the NPE then added description for Proxy object to redisson-micronaut\redisson-micronaut-30\src\main\resources\META-INF\native-image\org.redisson\redisson\reflect-config.json and replaced it your's copy. Now it works.

so I should replace reflect-config. json in the Redisson package instead of adding this file in the resources section of my project, right? @mrniko

**Comment by mrniko** [comment]
@arenick001 

It's a different problem. Netty can't parse your system's dns settings. try to update netty to the latest version and check /etc/resolv.conf file for correct format.

**Comment by arenick001** [comment]
> @arenick001
> 
> It's a different problem. Netty can't parse your system's dns settings. try to update netty to the latest version and check /etc/resolv.conf file for correct format.

@mrniko Thanks for reply. I use win11 and the problem occurred when project was running as **native image**. Redisson needs to connect to the Redis service in Docker. But everything runs well via IDEA. I don't know if this is a bug or if there is an issue with my configuration

**Comment by mrniko** [comment]
which netty version do you use?

**Comment by arenick001** [comment]
> which netty version do you use?

redisson-micronaut-40: 3.29.0

**Comment by mrniko** [comment]
can you check classpath?

**Comment by arenick001** [comment]
I just solved this problem with the help from [this issue](https://github.com/oracle/graal/issues/4304). Thank you all the same. @mrniko

**Comment by mrniko** [comment]
@arenick001 
Did you use this solution https://github.com/oracle/graal/issues/4304#issuecomment-1107528415 ?

**Comment by arenick001** [comment]
yeh, more precisely, this conversation -> https://github.com/oracle/graal/issues/4304#issuecomment-1107528415
