### ISSUE TITLE
Can't RListMultimap and RSetMultimap put all empty lists?

### ISSUE THREAD

**Issue by shenjing-bing** [redisson/redisson#4571]
```
    public static void main(String[] args) throws InterruptedException, ExecutionException {
        RListMultimap<Long, User> listMultimap = redissonClient.getListMultimap("collect:user:id");
        List<User> users = new ArrayList<>();
        listMultimap.replaceValues(1L, users);
    }
```

**Comment by shenjing-bing** [comment]
Exception in thread "main" org.redisson.client.RedisException: ERR Error running script (call to f_14dc1e87333d3c39a062860d397ef11da8930bc4): @user_script:1: @user_script: 1: Wrong number of args calling Redis command From Lua script. channel: [id: 0xe54e634a, L:/192.168.220.24:57449 - R:/192.168.1.26:6379] command: (EVAL), params: [redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); local members = redis.call('lrange', KEYS[2], 0, -1);..., 2, collect:user1, {collect:user1}:JutJg2DWN7JBYmzULRCUtw, PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256), JutJg2DWN7JBYmzULRCUtw]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
I recommend to use `fastRemove(key)` instead in this case.

**Comment by mrniko** [comment]
Fixed! Thanks for report
