### ISSUE TITLE
Attempt to unlock lock, not locked by current thread by node id

### ISSUE THREAD

**Issue by JanCizmar** [redisson/redisson#4574]
Hi there, 

I am getting a lot of these errors logged. I am using the the Lock (RLock) according to documentation. So I am not doing anything special. The documentation says:

> If Redisson instance which acquired lock crashes then such lock could hang forever in acquired state. To avoid this Redisson maintains lock watchdog, it prolongs lock expiration while lock holder Redisson instance is alive. By default lock watchdog timeout is 30 seconds and can be changed through [Config.lockWatchdogTimeout](https://github.com/redisson/redisson/wiki/2.-Configuration#lockwatchdogtimeout) setting.

I am not sure, but it seems like some other instance locked the lock and crashed and the watchdog is trying to unlock it and fails. 

The information about origin of the unlock action is missing in the stack trace, since the unlocking happens asynchronously and I my code probably doesn't originate it.

```
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 6e0f0261-922f-4ca9-9275-5cd246e2e294 thread-id: 197
    at org.redisson.RedissonBaseLock.lambda$unlockAsync$2(RedissonBaseLock.java:323)
    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
    at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
    at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:322)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
    at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:162)
    at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:470)
    at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:171)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
    at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:318)
    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:832)
```

The method I am using for locking (kotlin):
```
  fun withLocking(name: String, fn: () -> Unit) {
    val lock = this.getLock(name)
    lock.lock()
    try {
      fn()
    } finally {
      lock.unlock()
    }
```

**Comment by mrniko** [comment]
Unable to reproduce it

**Comment by JanCizmar** [comment]
Seems like it was maybe some mistake on my side. It wasn't logged for one week. So maybe I just haven't updated my services properly after fixing this issue. (I was unlocking the lock manually, but then I red docs and find out it's unlocking automatically when stale) Sorry!
