### ISSUE TITLE
Unable to unfreeze entry  when redis goes down in kuberentes (bitnami/redis)

### ISSUE THREAD

**Issue by lbornov2** [redisson/redisson#4584]
**Expected behavior**
If the redis sentinel master goes down for a short amount of time, and comes back up in less than `down-after-milliseconds` (i.e. a new master is not picked), redisson should continue to use the master

**Actual behavior**
The pod continuously streams the following output:
```
2022-10-06 16:14:29.868 ERROR 1 --- [isson-netty-2-3] o.r.c.balancer.LoadBalancerManager       : Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:87:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:138:queue:0, freezeReason=SYSTEM, client=[addr=redis://10.0.3.173:6379], nodeType=SLAVE, firstFail=1665072869858]

java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 10.0.3.173/10.0.3.173:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1423)
	at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1144)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:154)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:317)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$7(ConnectionPool.java:276)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:307)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 10.0.3.173/10.0.3.173:6379
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:153)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:317)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$7(ConnectionPool.java:276)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
	... 8 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Host is unreachable: 10.0.3.173/10.0.3.173:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	... 11 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Host is unreachable: 10.0.3.173/10.0.3.173:6379
Caused by: java.net.NoRouteToHostException: Host is unreachable
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

And:
```
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 10.0.3.173/10.0.3.173:6379
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:153)
	... 19 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Host is unreachable: 10.0.3.173/10.0.3.173:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	... 11 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Host is unreachable: 10.0.3.173/10.0.3.173:6379
Caused by: java.net.NoRouteToHostException: Host is unreachable
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Steps to reproduce or test case**
1) Install redis in sentinel configuration using the latest bitnami helm chart
```
helm install "${APP_NAME}-redis" bitnami/redis \
             --version "17.3.1" \
             --set sentinel.enabled=true \
             --set auth.password="${REDIS_PASSWORD}" \
             --set replica.replicaCount=3 \
             --set global.redis.password="${REDIS_PASSWORD}"
```

2) Now, you have 3 redis nods running:
```
kubectl get pods | grep redis
test2021-redis-node-0                   2/2     Running     0             14m
test2021-redis-node-1                   2/2     Running     0             14m
test2021-redis-node-2                   2/2     Running     0             13m
```

3) Some information about the sentinel master:
```
kubectl exec -it test2021-redis-node-1 bash -c sentinel
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@test2021-redis-node-1:/$ redis-cli -a $REDIS_PASSWORD -p 26379
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:26379> sentinel master mymaster
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "test2021-redis-node-0.test2021-redis-headless.default.svc.cluster.local"
 ...
 21) "down-after-milliseconds"
22) "60000"
....
32) "failover-timeout"
33) 180000
....
```

4) As you can see, node 0 is the master, so let's kill it:
```
kubectl delete pods/test2021-redis-node-0 --force --grace-period=0
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "test2021-redis-node-0" force deleted
```

5) Node 0 stays as the master, since it was down for ~10 seconds, which is less than the value of `down-after-milliseconds`, which is set to 60s.  So the output of step 3 is still the same.

6) The application server continuously streams the exceptions which I sent, and keeps streaming them long after (I monitored the logs for ~5 minutes) the master came back up.  The pod is not useable until it restarts (via failed healthcheck or manually, at that point it doesn't matter).

**Redis version**
7.0.5

**Redisson version**
3.17.7

**Redisson configuration**
```
---
sentinelServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 5000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  password: "whatever"
  sentinelAddresses:
  - "redis://test2021-redis-headless:26379"
  masterName: "mymaster"
  keepAlive: true
  database: 0
  checkSentinelsList: false
eventLoopGroup: null
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SnappyCodec> {}
transportMode: "NIO"

#https://github.com/redisson/redisson/issues/4356
addressResolverGroupFactory: !<org.company.redis.CustomDnsAddressResolverGroupFactory> {}
```

And the addressResolver:
```
/**
 * Required to fix https://github.com/redisson/redisson/issues/4356
 * @author lbornov2
 *
 */
public class CustomDnsAddressResolverGroupFactory implements AddressResolverGroupFactory {
    
    @Override
    public DnsAddressResolverGroup create(Class<? extends DatagramChannel> channelType,
            DnsServerAddressStreamProvider nameServerProvider) {
        final DnsAddressResolverGroup group = new DnsAddressResolverGroup(new DnsNameResolverBuilder()
                .channelType(NioDatagramChannel.class)
                .authoritativeDnsServerCache(NoopAuthoritativeDnsServerCache.INSTANCE)
                .nameServerProvider(DnsServerAddressStreamProviders.platformDefault()));
        return group;
    }

}
```

**Comment by mrniko** [comment]
Can you share logs for `org.redisson` in `trace` logging level? From application start moment till errors appeared

**Comment by lbornov2** [comment]
@mrniko  logs attached with `-Dlogging.level.org.redisson=TRACE` option for the app, from application start until ~3 minutes after the master back came up.

I can confirm that the exception is present in the attached log.

[reddison.4584.log](https://github.com/redisson/redisson/files/9731866/reddison.4584.log)

**Comment by lbornov2** [comment]
This also happens if I set down-after-milliseconds and failover-timeout to small values, i.e. 5000

```
  downAfterMilliseconds: 5000
  failoverTimeout: 5000
````

Killing the master (node 0) results in sentinel picking a new master:
```
127.0.0.1:26379> sentinel master mymaster
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "test2021-redis-node-2.test2021-redis-headless.default.svc.cluster.local"
```

But the logs still have the exception that I put in the ticket description.

**Comment by mrniko** [comment]
Cause is `Host is unreachable: 10.0.3.40` You need to check your network.

**Comment by lbornov2** [comment]
@mrniko - I disagree, and let me proove it.

IP addresses before killing master (both redis and sentinel have the same IP address in kubernetes):

node 0 - `10.0.3.95`
node 1 - `10.0.3.211`
node 2 - `10.0.3.149`


Then, I kill master.

IP addresses after killing master (both redis and sentinel have the same IP address in kubernetes):

node 0 - `10.0.3.200`
node 1 - `10.0.3.211`
node 2 - `10.0.3.149`

As you can see, node 0 came up with a new IP address.

However, the exception is:
```
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Host is unreachable: 10.0.3.95/10.0.3.95:6379
```

It's using the old IP address!

**Comment by mrniko** [comment]
Can you also include into this output netty logs? set `TRACE` for `io.netty.resolver` to see how dns resolver detects IP change.

**Comment by lbornov2** [comment]
Sure.

See attached.

IP addresses before killing master (both redis and sentinel have the same IP address in kubernetes):

node 0 - `10.0.3.173`
node 1 - `10.0.3.211`
node 2 - `10.0.3.95`

Then, I kill master.

IP addresses after killing master (both redis and sentinel have the same IP address in kubernetes):

node 0 - `10.0.3.54`
node 1 - `10.0.3.211`
node 2 - `10.0.3.95`

FYI,  pod of running java application is able to detect new IP addresses:

```
bash-5.1$ nslookup test2021-redis-headless
Server:		172.20.0.10
Address:	172.20.0.10:53

Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.211
Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.95
Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.54

```

The logs are from start until ~3 minutes after redis came back up

[4584.dns.log](https://github.com/redisson/redisson/files/9744071/4584.dns.log)

**Comment by mrniko** [comment]
Did you bind the same host to all Redis nodes? I'm afraid such configuration isn't supported yet for sentinel mode.

**Comment by lbornov2** [comment]
@mrniko  - not sure what you mean by "same host to all Redis nodes".

I have this in my redisson.yaml:
```
  sentinelAddresses:
  - "redis://test2021-redis-headless:26379"
```

That address resolves to all sentinel nodes, i.e:

```
bash-5.1$ nslookup test2021-redis-headless
Server:		172.20.0.10
Address:	172.20.0.10:53

Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.211
Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.95
Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.54
```

Are you saying that the redisson.yaml should look like this instead?
```
  sentinelAddresses:
  - "redis://test2021-redis-node-0:26379"
  - "redis://test2021-redis-node-1:26379"
  - "redis://test2021-redis-node-2:26379"
  ...
  - "redis://test2021-redis-node-N:26379"
```

**Comment by mrniko** [comment]
According to the log DNS resolver also stops work correctly. So Redisson is unable to resolve the hostname

**Comment by lbornov2** [comment]
@mrniko  - the operating system is able to detect the new IP address, the problem is that the Redisson DNS resolver is using the old IP address.

Also note that this issue does NOT occur if I kill a slave (i.e. node 2).  The logs stabilize after a few seconds.  It seems like something else is going on here.

**Comment by mrniko** [comment]
Master hostname can't be resolved due to error: `io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'test2021-redis-node-0.test2021-redis-headless.default.svc.cluster.local'`

**Comment by mrniko** [comment]
Another reason is that entry remains in DNS cache. Try to use DnsAddressResolverGroup config below.

```java
        final DnsAddressResolverGroup group = new DnsAddressResolverGroup(new DnsNameResolverBuilder()
                .channelType(NioDatagramChannel.class)
                .resolveCache(NoopDnsCache.INSTANCE)
                .cnameCache(NoopDnsCnameCache.INSTANCE)
                .nameServerProvider(DnsServerAddressStreamProviders.platformDefault()));
```

**Comment by mrniko** [comment]
For slaves and master the same host name resolver method is used

**Comment by lbornov2** [comment]
@mrniko  - just tried using the following:

```
public class CustomDnsAddressResolverGroupFactory implements AddressResolverGroupFactory {
    
    @Override
    public DnsAddressResolverGroup create(Class<? extends DatagramChannel> channelType,
            DnsServerAddressStreamProvider nameServerProvider) {
        final DnsAddressResolverGroup group = new DnsAddressResolverGroup(new DnsNameResolverBuilder()
                .channelType(NioDatagramChannel.class)
                .resolveCache(NoopDnsCache.INSTANCE)
                .cnameCache(NoopDnsCnameCache.INSTANCE)
                .nameServerProvider(DnsServerAddressStreamProviders.platformDefault()));
        return group;
    }

}
```

I have this in the redisson.yaml:
```
addressResolverGroupFactory: !<org.company.redis.CustomDnsAddressResolverGroupFactory> {}
```

Any other ideas?  Could it be that the connection pool is holding into old values?

**Comment by lbornov2** [comment]
> Master hostname can't be resolved due to error: `io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'test2021-redis-node-0.test2021-redis-headless.default.svc.cluster.local'`

That error is only temporary.  The operating system is able to correctly resolve that after the redis node which I killed comes back up:

```
bash-5.1$ nslookup test2021-redis-node-0.test2021-redis-headless.default.svc.cluster.local
Server:		172.20.0.10
Address:	172.20.0.10:53


Name:	test2021-redis-node-0.test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.31

bash-5.1$ nslookup test2021-redis-node-1.test2021-redis-headless.default.svc.cluster.local
Server:		172.20.0.10
Address:	172.20.0.10:53


Name:	test2021-redis-node-1.test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.4

bash-5.1$ nslookup test2021-redis-node-2.test2021-redis-headless.default.svc.cluster.local
Server:		172.20.0.10
Address:	172.20.0.10:53


Name:	test2021-redis-node-2.test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.40

bash-5.1$ nslookup test2021-redis-headless
Server:		172.20.0.10
Address:	172.20.0.10:53

Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.40
Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.4
Name:	test2021-redis-headless.default.svc.cluster.local
Address: 10.0.3.31
```

I confirm that the results of the `nslookup` command are correct.

I also confirm that the exception:
```
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'test2021-redis-node-0.test2021-redis-headless.default.svc.cluster.local'
```

Disappears rather quickly.

The only exceptions left are:
```
2022-10-10 10:12:31.961 ERROR 1 --- [isson-netty-5-2] o.r.c.balancer.LoadBalancerManager       : Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:110:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:182:queue:0, freezeReason=SYSTEM, client=[addr=redis://10.0.3.192:6379], nodeType=SLAVE, firstFail=1665396751955]
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 10.0.3.192/10.0.3.192:6379
```

**Comment by mrniko** [comment]
I added more logs. Can you try version attached? with `debug` logging level for `org.redisson` package.

[redisson-3.17.8-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/9745883/redisson-3.17.8-SNAPSHOT.jar.zip)

**Comment by lbornov2** [comment]
IP adds before killing master:

node 0: `10.0.3.68`
node 1: `10.0.3.164`
node 2: `10.0.3.40`

ip addrs after killing master (node 0)
node 0: `10.0.3.93`
node 1: `10.0.3.164`
node 2: `10.0.3.40`

md5sum of the jar being used is `371eb733d0083ca615677844d52e9680`

Logs:
[4584.debug.log](https://github.com/redisson/redisson/files/9747534/4584.debug.log)

**Comment by mrniko** [comment]
According to the log master IP is 10.0.3.40. Please check your config

**Comment by lbornov2** [comment]
Let's try this again:

IP addresses at start:

node 0: `10.0.3.55`
node 1: `10.0.3.173`
node 2: `10.0.3.211`

The master according to sentinel configs is `node 1`
```
127.0.0.1:26379> sentinel master mymaster
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "test2021-redis-node-1.test2021-redis-headless.default.svc.cluster.local"
```

Now, let's kill the master:
```
kubectl delete pods/test2021-redis-node-1 --force --grace-period=0
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "test2021-redis-node-1" force deleted
```

The new master according to sentinel is `node 0`
```
sentinel master mymaster
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "test2021-redis-node-0.test2021-redis-headless.default.svc.cluster.local"
```

IP addresses after node 0 (killed above) came up:

node 0: `10.0.3.55`
node 1: `10.0.3.11`
node 2: `10.0.3.211`

I still see this in the logs a few minutes after all redis nodes are up.  Seems like it's using the old IP:
```
Caused by: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: 10.0.3.173/10.0.3.173:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	... 11 common frames omitted
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: 10.0.3.173/10.0.3.173:6379
```

`10.0.3.173` is the IP of the master which was killed!

```
2022-10-11 08:29:47.174 ERROR 1 --- [isson-timer-7-1] o.r.c.balancer.LoadBalancerManager       : Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:59:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:82:queue:0, freezeReason=SYSTEM, client=[addr=redis://10.0.3.173:6379], nodeType=SLAVE, firstFail=1665476911450]
```


This one is new, didn't see this before:
```
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. Server: 10.0.3.173/10.0.3.173:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1452)
	at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2337)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreeze(LoadBalancerManager.java:160)
	at org.redisson.connection.balancer.LoadBalancerManager.lambda$unfreeze$2(LoadBalancerManager.java:166)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. Server: 10.0.3.173/10.0.3.173:6379
```

Again, `10.0.3.173` is the IP of the master which was killed.  So, redisson is hanging onto that value somewhere


Logs:
[4584.new.log](https://github.com/redisson/redisson/files/9753078/4584.new.log)

**Comment by mrniko** [comment]
Thanks for the logs. Please try a new build below.

[redisson-3.17.8-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/9753482/redisson-3.17.8-SNAPSHOT.jar.zip)

**Comment by lbornov2** [comment]
md5sum of jar when running in container: `da9a311ec80592df06e8f03114fcf4c3`

I now see this in the logs after killing master (node 0).  Node 2 becomes the new master.
```
2022-10-11 10:17:38.564 DEBUG 1 --- [sson-netty-2-23] o.r.c.SentinelConnectionManager          : Resolved master IP: redis://10.0.3.173:6379 for host: redis://test2021-redis-node-2.test2021-redis-headless.default.svc.cluster.local:6379
```
[4584.fixed.log](https://github.com/redisson/redisson/files/9754102/4584.fixed.log)


With the new jar, it looks like it's able to survive several restarts of master and/or slave.  So much better.

Any idea when this version will be released?

**Comment by mrniko** [comment]
During this month.

**Comment by lbornov2** [comment]
> During this month. Thanks for help!

All good, mate.  Thanks for being helpful and not brushing the issue off.

**Comment by olessio** [comment]
Small question: 
when a pod is being deleted and restarted with new IP, Redisson still logs messages like
`org.redisson.connection.SentinelConnectionManager : slaveDown {old_ip}`
What is the use case of collecting all ever used IPs?
Is it just a matter of logging? Or does Redisson perform any other actions with this outdated IP?

**Comment by mrniko** [comment]
Are these messages continues to appear? can you share logs with `trace` logging level for `org.redisson`?

**Comment by olessio** [comment]
@mrniko 
I was using 3.17.4 and I was getting the same exceptions as in this ticket description:
`Unable to unfreeze entry`

I've tried your redisson-3.17.8-SNAPSHOT.jar.zip to make sure it fixes the problem: indeed there were no more exceptions. But I kept seeing 
`DEBUG org.redisson.connection.SentinelConnectionManager : slaveDown {old_ip}`
about each second.

Of course INFO log level will hide all of them, but I want to be sure that Redisson does not waste some resources by constantly querying {old_ip}

**Comment by mrniko** [comment]
I didn't add this line into commit.

**Comment by olessio** [comment]
@mrniko 
I downloaded snapshot from here https://github.com/redisson/redisson/issues/4584#issuecomment-1274371363

Here is decompiled SentinelConnectionManager 
<img width="956" alt="Screenshot 2022-10-14 at 10 31 47" src="https://user-images.githubusercontent.com/7859461/195801057-c6a3291c-ae9c-4f0e-8cd0-36e1cc0dff32.png">

**Comment by mrniko** [comment]
It's from snapshot not from the code commited to github

**Comment by olessio** [comment]
Having no `log.debug` in the committed code does not mean that method itself (`slaveDown`) is not invoked.
So I think my questions still remains valid: does Redisson keep track of all ever used IPs? If yes, does Redisson perform some operation on these IPs (verifying accessibility, etc)?

**Comment by mrniko** [comment]
> does Redisson keep track of all ever used IPs?

no, why? all ips are gathered from topology info

**Comment by relgames** [comment]
@mrniko Do you have an approximate ETA for 3.17.8? Previously you mentioned "during this month" which was in October...

**Comment by olessio** [comment]
We use 3.18.0 release, initial problem has been fixed: Redisson manages to reconnect.
But, recently we saw that one of our services which uses Redisson client was polluting the log after the reconnect with next exceptions:

```
ERROR 1 [] [redisson-timer-4-1] org.redisson.connection.balancer.LoadBalancerManager : Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:85:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:134:queue:0, freezeReason=SYSTEM, client=[addr=redis://10.83.19.20:6379], nodeType=SLAVE, firstFail=1669808100722]

 java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 4 were initialized. Server: 10.83.19.20/10.83.19.20:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1452)
	at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2337)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreeze(LoadBalancerManager.java:160)
	at org.redisson.connection.balancer.LoadBalancerManager.lambda$unfreeze$2(LoadBalancerManager.java:166)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 4 were initialized. Server: 10.83.19.20/10.83.19.20:6379
	at org.redisson.connection.pool.ConnectionPool.createConnection(ConnectionPool.java:104)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:92)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:77)
	at org.redisson.connection.pool.SlaveConnectionPool.initConnections(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreeze(LoadBalancerManager.java:157)
	... 6 common frames omitted

```

10.83.19.20 - **old** redis IP, which no longer exists after redis has been restarted by kubernetes.
Unfortunately, I have no exact steps to reproduce as it happened only once and in only one our service (all others have been reconnected as well and didn't throw these exceptions).

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4902
