### ISSUE TITLE
In quarkus, can not build native when use jackson codec

### ISSUE THREAD

**Issue by seepine** [redisson/redisson#4586]
**Expected behavior**
build success

**Actual behavior**
```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.ByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufAllocator.class'). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.ByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufAllocator.class'). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
        at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:555)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:168)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:410)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:594)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:124)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:624)
Error: Image build request failed with exit status 1
```

**Steps to reproduce or test case**
in code
```java
Config config = new Config();
// ...
config.setCodec(new JsonJacksonCodec());
Redisson.create(config);
```
build with dockerfile
```dockerfile
FROM quay.io/quarkus/ubi-quarkus-native-image:21.3-java11 AS build
USER root
RUN microdnf install findutils
COPY --chown=quarkus:quarkus  ./ /code
RUN chmod 755 /code/gradlew
# RUN tree -d
USER quarkus
WORKDIR /code
RUN ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.native-image-xmx=4g -x test

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:1.0
WORKDIR /work/
COPY --from=build /code/build/*-runner /work/application
RUN chmod 775 /work
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

**Redisson version**
3.17.7

**Redisson configuration**
```
quarkus.redisson.single-server-config.address=redis://localhost:6379
```

**Comment by flauschie** [comment]
Still an issue with 3.19.3

**Comment by mrniko** [comment]
> io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from jar:file:///code/build/koi-0.0.1-beta.12-native-image-source-jar/lib/io.netty.netty-buffer-4.1.79.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil

It's an image configuration issue

**Comment by flauschie** [comment]
netty buffer enforces init at runtime:

Args = --initialize-at-run-time=io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.ByteBufAllocator,io.netty.buffer.ByteBufUtil,io.netty.buffer.AbstractReferenceCountedByteBuf

whereas JsonJacksonCodec seems to go for build time - e.g.:

Error: Classes that should be initialized at run time got initialized during image building:
io.netty.buffer.PooledByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). org.redisson.codec.JsonJacksonCodec caused initialization of this class with the following trace: 
	at io.netty.buffer.PooledByteBuf.<clinit>(PooledByteBuf.java:29)
	at io.netty.buffer.PoolArena$DirectArena.newByteBuf(PoolArena.java:716)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:128)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:174)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:108)
	at org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:81)

This didn't work for me:
--initialize-at-run-time=org.redisson.codec.JsonJacksonCodec

**Comment by mrniko** [comment]
Fixed. Thanks for report
