### ISSUE TITLE
使用zPopMin方法 报java.lang.StackOverflowError错误

### ISSUE THREAD

**Issue by xooch95** [redisson/redisson#4639]
**Expected behavior**

**Actual behavior**

```
java.lang.StackOverflowError
	at org.springframework.data.redis.connection.RedisConnection.zSetCommands(RedisConnection.java:141)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zPopMin(DefaultedRedisConnection.java:972)
```

**Steps to reproduce or test case**

```
ZSetOperations.TypedTuple typedTuple = redisTemplate.opsForZSet().popMin("test");
```

**Redis version**
Redis server v=6.2.7 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=de14a0caa93e54e

**Redisson version**
3.16.8

**Redisson configuration**

**Spring boot version**
2.6.12

**Comment by frankie202** [comment]
Maybe you should ask this question in spring-boot.

**Comment by mrniko** [comment]
Fixed! Thanks for report. More than 25 methods were implemented
