### ISSUE TITLE
how to change the default Future executor not using the default ForkJoinPool.common

### ISSUE THREAD

**Issue by HashZhang** [redisson/redisson#4641]
if there is too much locks or other  RFuture Objs, then we may get:

```
Caused by: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:1819) ~[?:?]
	at java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3446) ~[?:?]
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3432) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072) ~[?:?]
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:114) ~[redisson-3.17.0.jar!/:3.17.0]
	at org.redisson.RedissonObject.get(RedissonObject.java:82) ~[redisson-3.17.0.jar!/:3.17.0]
	at org.redisson.RedissonLock.unlock(RedissonLock.java:302) ~[redisson-3.17.0.jar!/:3.17.0]

```

**Comment by mrniko** [comment]
how to reproduce it?

**Comment by HashZhang** [comment]
> at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072) ~[?:?]

you can set java.util.concurrent.ForkJoinPool.common.parallelism to 1, and produce a lot of Rlock, then lock and unlock them at the same time

**Comment by mrniko** [comment]
Redisson isn't choosing the common pool here. The blocking call inherits whatever thread the caller is on. You only hit this if you're invoking Redisson's blocking methods from common-pool workers, from inside CompletableFuture.thenApply/thenRun/... continuations without an explicit executor, or from parallelStream().forEach(...). Both default to the common pool. The Caffeine maintainer gives the same canonical diagnosis in a parallel thread: futures blocking on futures causes shared-pool starvation.

The real fix is to not block on the common pool, in roughly this priority order:

- Use Redisson's async API methods unlockAsync() / lockAsync() rather than unlock() inside an async pipeline.

- If you must call the blocking methods from a callback, give that stage its own executor: thenApplyAsync(fn, myExecutor) instead of thenApply(fn), and avoid parallelStream() for work that blocks. A dedicated bounded pool keeps the blocking off the FJP.
