### ISSUE TITLE
Error while attempting to set lock : java.lang.IllegalStateException: Only 2 of 17 slaves were synced

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#4646]
Hello @mrniko ,

We are running in to error `java.lang.IllegalStateException: Only 2 of 17 slaves were synced` while attempting to set lock value from redisson. Please note that we are using AWS Elasticache and this issue is occuring continously since many days. Also the count of the slaves in the error message keeps on changing. I checked other similar issues like https://github.com/redisson/redisson/issues/4154 and it seems that you have mentioned to set `checkLockSyncedSlaves `to false.

The exception occurs when attempting to invoke the `tryLock `method of `RLock `object. Below is the exception trace

`org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:276) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.RedissonObject.get(RedissonObject.java:82) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:144) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:218) ~[redisson-3.17.4.jar:3.17.4]
	at com.successmetricsinc.repository.cached.CachedRepository.testAndSetCacheWriteLock(CachedRepository.java:217) ~[PerformanceEngine-2022.10.04-SNAPSHOT.jar:?]
	at com.successmetricsinc.UI.ApplicationContext.loadContext(ApplicationContext.java:769) [Reporting-2022.10.04-SNAPSHOT.jar:?]
	at com.successmetricsinc.UI.ApplicationContext.loadContextWithRetries(ApplicationContext.java:638) [Reporting-2022.10.04-SNAPSHOT.jar:?]
	at com.successmetricsinc.UI.ApplicationContext.reloadContext(ApplicationContext.java:1476) [Reporting-2022.10.04-SNAPSHOT.jar:?]
	at com.successmetricsinc.UI.ApplicationContext$FileMonitor$2.onStop(ApplicationContext.java:1679) [Reporting-2022.10.04-SNAPSHOT.jar:?]
	at org.apache.commons.jci.monitor.FilesystemAlterationObserverImpl.notifyOnStop(FilesystemAlterationObserverImpl.java:267) [commons-jci-fam-1.0.jar:1.0]
	at org.apache.commons.jci.monitor.FilesystemAlterationObserverImpl.checkAndNotify(FilesystemAlterationObserverImpl.java:333) [commons-jci-fam-1.0.jar:1.0]
	at org.apache.commons.jci.monitor.FilesystemAlterationMonitor.run(FilesystemAlterationMonitor.java:122) [commons-jci-fam-1.0.jar:1.0]
	at java.lang.Thread.run(Thread.java:829) [?:?]

Caused by: java.lang.IllegalStateException: Only 2 of 15 slaves were synced
	at org.redisson.RedissonBaseLock.lambda$evalWriteAsync$0(RedissonBaseLock.java:226) ~[redisson-3.17.4.jar:3.17.4]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:322) ~[redisson-3.17.4.jar:3.17.4]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:162) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:478) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:172) ~[redisson-3.17.4.jar:3.17.4]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:318) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[redisson-3.17.4.jar:3.17.4]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) ~[redisson-3.17.4.jar:3.17.4]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]`

Please note we are using redisson version 3.17.4. 
Can you help us to understand what should be the cause for this and how can we mitigate this. Please note that setting the above mentioned parameter would require us to redeploy our production application which may not be feasible. Is there any other way this can be solved.?

Thanks,
Yash

**Comment by mrniko** [comment]
Try 3.17.5 version it has fix for slaves sync check.
