### ISSUE TITLE
Command execution timeout for command: (PING), params: [], Redis client: 

### ISSUE THREAD

**Issue by acemno** [redisson/redisson#4664]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://10.61.1.95:7005]
    at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)

经常报这个错误，好几个月了，没有解决

之前在issues中得知，升级版本为3.17.6可以解决，现在已经是3.17.6了，依然报错。

我的redisson配置如下：
ClusterServersConfig clusterServersConfig = config.useClusterServers();
clusterServersConfig.setScanInterval(2000);
clusterServersConfig.setIdleConnectionTimeout(10000);
clusterServersConfig.setPingConnectionInterval(5000);
clusterServersConfig.setConnectTimeout(3000);
for (String ip : split) {
    clusterServersConfig.addNodeAddress("redis://"+ip);
}
RedissonClient redisson = Redisson.create(config);

**Comment by RecursionHs** [comment]
这个错你本地dev环境报的？

**Comment by acemno** [comment]
> 
不是dev，是生产环境，那ip是redis集群环境中其中一个内网ip，三主三从其中一个

**Comment by mrniko** [comment]
try to specify natMapper object https://github.com/redisson/redisson/wiki/2.-Configuration#natmapper

**Comment by StriveStar** [comment]
> > 
> 
> 不是dev，是生产环境，那ip是redis集群环境中其中一个内网ip，三主三从其中一个

有解决吗 我这边连本地的redis也报这个错，我也升级到3.17.6版本
