### ISSUE TITLE
Unable to send PING command over channel: (Command execution timeout for command: (PING), params: [], Redis client:)

### ISSUE THREAD

**Issue by 120011676** [redisson/redisson#4681]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
redis last

**Redisson version**
···xml
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.18.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.redisson</groupId>
                    <artifactId>redisson-spring-data-27</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-data-20</artifactId>
            <version>3.18.0</version>
        </dependency>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.2.RELEASE</version>
        <relativePath/> 
    </parent>
```

**Redisson configuration**
127.0.0.1


```log
2022-11-17 15:57:58.516 [redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x8db826c1, L:/127.0.0.1:58910 - R:127.0.0.1/127.0.0.1:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.18.0.jar:3.18.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
2022-11-17 15:57:58.517 [redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x4eb292bc, L:/127.0.0.1:58908 - R:127.0.0.1/127.0.0.1:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.18.0.jar:3.18.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by 120011676** [comment]
remove

**Comment by mrniko** [comment]
Check your network or increase pingConnectionInterval
