### ISSUE TITLE
restart application, unable to connect redis server 

### ISSUE THREAD

**Issue by sqsteve** [redisson/redisson#4685]
Redisson version : 3.18.0 
Spring boot version : 2.5.10 
Laptop: M1 Pro
Java version : 8 
redis provider: aliyun  Mater-slave  connect proxy address 

`  @Bean(destroyMethod = "shutdown")
    public RedissonClient getRedisson() throws InterruptedException {
        Config config = new Config();

        config.useSingleServer().setAddress("redis://"+redisProperties.getHost() + ":"+redisProperties.getPort());
        config.useSingleServer().setConnectTimeout(1000)
                .setConnectionMinimumIdleSize(1)
                .setConnectionPoolSize(1)
                .setIdleConnectionTimeout(10000)
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setTimeout(3000);
        config.useSingleServer().setDatabase(redisProperties.getDatabase());
        config.useSingleServer().setPassword(redisProperties.getPassword());
      config.useSingleServer().setDnsMonitoringInterval(-1);
        return Redisson.create(config);
    }`

for the reason , i cover up the redis address and ip below. 
I'm make sure the address and password is correct.

start the project local, the first time is correct like 

`[2022-11-18 17:08:20.565] [INFO] [redisson-netty-4-5] [] o.r.c.pool.MasterConnectionPool 162 - 1 connections initialized for r-xxx.aliyuncs.com/xx:6379

[2022-11-18 17:08:20.578] [INFO] [redisson-netty-4-6] [] o.r.c.p.MasterPubSubConnectionPool 162 - 1 connections initialized for r-xxx.aliyuncs.com/xx:6379`

when i restart the application, sometimes show the error like 

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'getRedisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: Unable to connect to Redis server: xxx/xxx:6379
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 19 common frames omitted
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: xxx/xx:6379
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:154)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:318)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:277)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: xxx/xx:6379
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
	... 11 common frames omitted
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: xxx/xxx:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	... 8 common frames omitted

i turn on the netty log  some log like 

>[2022-11-18 17:09:15.307] [DEBUG] [main] [] i.n.u.i.l.InternalLoggerFactory 63 - Using SLF4J as the default logging framework
[2022-11-18 17:09:15.318] [DEBUG] [main] [] io.netty.util.NetUtil 135 - -Djava.net.preferIPv4Stack: false
[2022-11-18 17:09:15.318] [DEBUG] [main] [] io.netty.util.NetUtil 136 - -Djava.net.preferIPv6Addresses: false
[2022-11-18 17:09:15.320] [DEBUG] [main] [] io.netty.util.NetUtilInitializations 129 - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
[2022-11-18 17:09:15.322] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 460 - -Dio.netty.noUnsafe: false
[2022-11-18 17:09:15.322] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 954 - Java version: 8
[2022-11-18 17:09:15.323] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 135 - sun.misc.Unsafe.theUnsafe: available
[2022-11-18 17:09:15.324] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 159 - sun.misc.Unsafe.copyMemory: available
[2022-11-18 17:09:15.325] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 202 - java.nio.Buffer.address: available
[2022-11-18 17:09:15.327] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 272 - direct buffer constructor: available
[2022-11-18 17:09:15.328] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 350 - java.nio.Bits.unaligned: available, true
[2022-11-18 17:09:15.328] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 424 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
[2022-11-18 17:09:15.328] [DEBUG] [main] [] i.n.util.internal.PlatformDependent0 446 - java.nio.DirectByteBuffer.<init>(long, int): available
[2022-11-18 17:09:15.328] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 1116 - sun.misc.Unsafe: available
[2022-11-18 17:09:15.329] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 1237 - -Dio.netty.tmpdir: /var/folders/vc/_2p03gkx20n29tqx0l97dp140000gn/T (java.io.tmpdir)
[2022-11-18 17:09:15.329] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 1316 - -Dio.netty.bitMode: 64 (sun.arch.data.model)
[2022-11-18 17:09:15.330] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 1084 - Platform: MacOS
[2022-11-18 17:09:15.331] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 178 - -Dio.netty.maxDirectMemory: 7635730432 bytes
[2022-11-18 17:09:15.333] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 185 - -Dio.netty.uninitializedArrayAllocationThreshold: -1
[2022-11-18 17:09:15.334] [DEBUG] [main] [] io.netty.util.internal.CleanerJava6 92 - java.nio.ByteBuffer.cleaner(): available
[2022-11-18 17:09:15.334] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 205 - -Dio.netty.noPreferDirect: false
[2022-11-18 17:09:15.335] [DEBUG] [main] [] io.netty.util.NetUtil 187 - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
[2022-11-18 17:09:15.344] [DEBUG] [main] [] i.n.u.i.InternalThreadLocalMap 86 - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
[2022-11-18 17:09:15.344] [DEBUG] [main] [] i.n.u.i.InternalThreadLocalMap 89 - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
[2022-11-18 17:09:15.350] [DEBUG] [main] [] i.n.r.DefaultHostsFileEntriesResolver 53 - -Dio.netty.hostsFileRefreshInterval: 0
[2022-11-18 17:09:15.354] [DEBUG] [main] [] i.n.u.internal.NativeLibraryLoader 78 - -Dio.netty.native.workdir: /var/folders/vc/_2p03gkx20n29tqx0l97dp140000gn/T (io.netty.tmpdir)
[2022-11-18 17:09:15.354] [DEBUG] [main] [] i.n.u.internal.NativeLibraryLoader 83 - -Dio.netty.native.deleteLibAfterLoading: true
[2022-11-18 17:09:15.354] [DEBUG] [main] [] i.n.u.internal.NativeLibraryLoader 87 - -Dio.netty.native.tryPatchShadedId: true
[2022-11-18 17:09:15.354] [DEBUG] [main] [] i.n.u.internal.NativeLibraryLoader 91 - -Dio.netty.native.detectNativeLibraryDuplicates: true
[2022-11-18 17:09:15.363] [DEBUG] [main] [] i.n.u.internal.NativeLibraryLoader 369 - Successfully loaded the library /var/folders/vc/_2p03gkx20n29tqx0l97dp140000gn/T/libnetty_resolver_dns_native_macos_x86_643182802181767469727.dylib
[2022-11-18 17:09:15.368] [DEBUG] [main] [] i.n.r.d.DnsServerAddressStreamProviders 65 - io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider: available
[2022-11-18 17:09:15.381] [DEBUG] [main] [] i.n.u.internal.NativeLibraryLoader 369 - Successfully loaded the library /var/folders/vc/_2p03gkx20n29tqx0l97dp140000gn/T/libnetty_transport_native_kqueue_x86_64868312100536843593.dylib
[2022-11-18 17:09:15.423] [DEBUG] [main] [] io.netty.util.ResourceLeakDetector 129 - -Dio.netty.leakDetection.level: simple
[2022-11-18 17:09:15.424] [DEBUG] [main] [] io.netty.util.ResourceLeakDetector 130 - -Dio.netty.leakDetection.targetRecords: 4
[2022-11-18 17:09:15.428] [DEBUG] [main] [] i.n.util.ResourceLeakDetectorFactory 196 - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@673a9db4
[2022-11-18 17:09:15.431] [DEBUG] [main] [] i.n.util.internal.PlatformDependent 967 - org.jctools-core.MpscChunkedArrayQueue: available
[2022-11-18 17:09:18.213] [INFO] [main] [] c.a.a.spring.ArthasConfiguration 70 - Arthas agent start success.
[2022-11-18 17:09:18.476] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 155 - -Dio.netty.allocator.numHeapArenas: 20
[2022-11-18 17:09:18.478] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 156 - -Dio.netty.allocator.numDirectArenas: 20
[2022-11-18 17:09:18.478] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 158 - -Dio.netty.allocator.pageSize: 8192
[2022-11-18 17:09:18.478] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 163 - -Dio.netty.allocator.maxOrder: 11
[2022-11-18 17:09:18.478] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 167 - -Dio.netty.allocator.chunkSize: 16777216
[2022-11-18 17:09:18.478] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 168 - -Dio.netty.allocator.smallCacheSize: 256
[2022-11-18 17:09:18.479] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 169 - -Dio.netty.allocator.normalCacheSize: 64
[2022-11-18 17:09:18.479] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 170 - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
[2022-11-18 17:09:18.479] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 171 - -Dio.netty.allocator.cacheTrimInterval: 8192
[2022-11-18 17:09:18.479] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 172 - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
[2022-11-18 17:09:18.479] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 173 - -Dio.netty.allocator.useCacheForAllThreads: true
[2022-11-18 17:09:18.479] [DEBUG] [main] [] i.n.buffer.PooledByteBufAllocator 174 - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
[2022-11-18 17:09:18.487] [DEBUG] [main] [] io.netty.buffer.ByteBufUtil 87 - -Dio.netty.allocator.type: pooled
[2022-11-18 17:09:18.488] [DEBUG] [main] [] io.netty.buffer.ByteBufUtil 96 - -Dio.netty.threadLocalDirectBufferSize: 0
[2022-11-18 17:09:18.488] [DEBUG] [main] [] io.netty.buffer.ByteBufUtil 99 - -Dio.netty.maxThreadLocalCharBufferSize: 16384
[2022-11-18 17:09:18.490] [DEBUG] [main] [] io.netty.util.Recycler 85 - -Dio.netty.recycler.maxCapacityPerThread: 4096
[2022-11-18 17:09:18.491] [DEBUG] [main] [] io.netty.util.Recycler 86 - -Dio.netty.recycler.ratio: 8
[2022-11-18 17:09:18.491] [DEBUG] [main] [] io.netty.util.Recycler 87 - -Dio.netty.recycler.chunkSize: 32
[2022-11-18 17:09:18.491] [DEBUG] [main] [] io.netty.util.Recycler 88 - -Dio.netty.recycler.blocking: false
[2022-11-18 17:09:18.496] [DEBUG] [main] [] io.netty.buffer.AbstractByteBuf 63 - -Dio.netty.buffer.checkAccessible: true
[2022-11-18 17:09:18.497] [DEBUG] [main] [] io.netty.buffer.AbstractByteBuf 64 - -Dio.netty.buffer.checkBounds: true
[2022-11-18 17:09:18.497] [DEBUG] [main] [] i.n.util.ResourceLeakDetectorFactory 196 - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@62a78446
[2022-11-18 17:09:18.544] [INFO] [main] [] org.redisson.Version 41 - Redisson 3.18.0
[2022-11-18 17:09:18.546] [DEBUG] [main] [] i.n.c.MultithreadEventLoopGroup 44 - -Dio.netty.eventLoopThreads: 20
[2022-11-18 17:09:18.548] [DEBUG] [main] [] io.netty.channel.nio.NioEventLoop 109 - -Dio.netty.noKeySetOptimization: false
[2022-11-18 17:09:18.548] [DEBUG] [main] [] io.netty.channel.nio.NioEventLoop 110 - -Dio.netty.selectorAutoRebuildThreshold: 512
[2022-11-18 17:09:18.578] [DEBUG] [main] [] io.netty.channel.DefaultChannelId 79 - -Dio.netty.processId: 6367 (auto-detected)
[2022-11-18 17:09:18.581] [DEBUG] [main] [] io.netty.channel.DefaultChannelId 101 - -Dio.netty.machineId: 98:dd:60:ff:fe:79:5a:cf (auto-detected)
[2022-11-18 17:09:18.613] [DEBUG] [redisson-netty-4-2] [] i.n.util.ResourceLeakDetectorFactory 196 - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@7f8cf667
[2022-11-18 17:09:18.621] [DEBUG] [redisson-netty-4-2] [] i.netty.resolver.dns.DnsQueryContext 117 - [id: 0x74d07d13] WRITE: UDP, [41370: /fe80:0:0:0:5655:d5ff:fe5c:a86c%17:53], DefaultDnsQuestion(r-xxxx.aliyuncs.com. IN A)
[2022-11-18 17:09:18.629] [DEBUG] [redisson-netty-4-2] [] i.netty.resolver.dns.DnsQueryContext 117 - [id: 0x74d07d13] WRITE: UDP, [25155: /fe80:0:0:0:5655:d5ff:fe5c:a86c%17:53], DefaultDnsQuestion(r-xxxxaliyuncs.com. IN AAAA)
[2022-11-18 17:09:18.640] [DEBUG] [redisson-netty-4-2] [] i.netty.resolver.dns.DnsNameResolver 1302 - [id: 0x74d07d13] RECEIVED: UDP [41370: /fe80:0:0:0:5655:d5ff:fe5c:a86c%17:53], DatagramDnsResponse(from: /fe80:0:0:0:5655:d5ff:fe5c:a86c%17:53, to: /0:0:0:0:0:0:0:0:57300, 41370, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(r-xxxxaliyuncs.com. IN A)
	DefaultDnsRawRecord(r-xxxx.aliyuncs.com. 1 IN A 4B)
[2022-11-18 17:09:18.679] [DEBUG] [redisson-netty-4-2] [] i.netty.resolver.dns.DnsNameResolver 1302 - [id: 0x74d07d13] RECEIVED: UDP [25155: /fe80:0:0:0:5655:d5ff:fe5c:a86c%17:53], DatagramDnsResponse(from: /fe80:0:0:0:5655:d5ff:fe5c:a86c%17:53, to: /0:0:0:0:0:0:0:0:57300, 25155, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(r-xxxx.aliyuncs.com. IN AAAA)
	DefaultDnsRawRecord(rds.aliyuncs.com. 547 IN SOA 67B)
	DefaultDnsRawRecord(OPT flags:0 udp:512 0B)
[2022-11-18 17:09:19.741] [DEBUG] [redisson-netty-4-2] [] io.netty.buffer.PoolThreadCache 224 - Freed 3 thread-local buffer(s) from thread: redisson-netty-4-2
[2022-11-18 17:09:19.779] [WARN] [main] [] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext 591 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getRedisson' defined in class path resource [com/config/db/RedisConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'getRedisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: Unable to connect to Redis server: xxx.aliyuncs.com/xxx:6379

I add netty dependency 
>      <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-resolver-dns-native-macos</artifactId>
            <scope>runtime</scope>
            <classifier>osx-aarch_64</classifier>
            <version>4.1.74.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>

 

@mrniko

**Comment by mrniko** [comment]
try to update to the latest version of netty. I saw they fixed a dns issue arising in macos

**Comment by sqsteve** [comment]
> try to update to the latest version of netty. I saw they fixed a dns issue arising in macos

it's not work update version of netty  @mrniko 

       <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-resolver-dns-native-macos</artifactId>
            <scope>runtime</scope>
            <classifier>osx-aarch_64</classifier>
            <version>4.1.85.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.85.Final</version>
        </dependency>

**Comment by mrniko** [comment]
Unable to reproduce issue. Please check your network
