### ISSUE TITLE
Implement AWS IAM authentication for elasticache on redis 7

### ISSUE THREAD

**Issue by servionsolutions** [redisson/redisson#4713]
**Is your feature request related to a problem? Please describe.**
No problem, but it would allow for increased security as well as a more AWS-native auth solution.

**Describe the solution you'd like**
It would be great if redisson could support the new IAM-based authentication tokens for AWS elasticache. This is a new feature that AWS has released in their redis engine v7:
[IAM release announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-elasticache-supports-iam-authentication-redis-clusters/)
[IAM docs for elasticache](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth-iam.html)

It looks like it may require the ability to rotate out short lived tokens, thus we may need a way to provide a credential provider to redisson. Perhaps there is an interface that we can implement to provide a token to redisson, similar to the example in the AWS docs with lettuce.

Also would be important to make sure that long/persistent connections are able to continue to be supported beyond 12/24 hour windows.

**Describe alternatives you've considered**
Continue to utilize ACLs with user and usergroup.  This works, however IAM is more secure and doesn't require credential rotation.

**Comment by mrniko** [comment]
Done. Thanks for idea!

**Comment by shiranyo** [comment]
@mrniko 
Thanks for that!
What is the expected behavior if the password is expired? 
idle connection will be broken and fetch the new password from the credentials manager?

**Comment by mrniko** [comment]
@shiranyo 

How is the expired password changed?

**Comment by shiranyo** [comment]
@mrniko 
via the provided credentialsResolver that generates a new token every 15 minutes. 
Based on the [ElastiCache IAM documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth-iam.html), after 12 hours, the connection will be disconnected. At that point, I wish it will try to reconnect using the new token (using `credentialsResolver.resolve()..`)

What is the expected behavior?

**Comment by mrniko** [comment]
@shiranyo 

Idle connections are also use credentialsResolver. All should work

**Comment by shiranyo** [comment]
@mrniko right.
So when the zWRONGPASS (invalid username-password pair)` error is suddenly raised against the pool after 12 hours, will they try to reconnect seamlessly?

**Comment by mrniko** [comment]
@shiranyo 

Can you provide any test? Unable to reproduce it with the test below.

```java
    @Test
    public void testCredentials() throws IOException, InterruptedException {
        RedisProcess runner = new RedisRunner()
                .nosave()
                .randomDir()
                .randomPort()
                .requirepass("1234")
                .run();

        AtomicReference<String> ii = new AtomicReference<>("1234");

        Config config = new Config();
        config.useSingleServer()
                .setConnectionMinimumIdleSize(1)
                .setConnectionPoolSize(10)
                .setCredentialsResolver(new CredentialsResolver() {
                    @Override
                    public CompletionStage<Credentials> resolve(InetSocketAddress address) {
                        return CompletableFuture.completedFuture(new Credentials(null, ii.get()));
                    }
                })
                .setAddress(runner.getRedisServerAddressAndPort());
        RedissonClient redisson = Redisson.create(config);

        RedisSingle s = redisson.getRedisNodes(RedisNodes.SINGLE);
        s.getInstance().setConfig("requirepass", "tester");
        ii.set("tester");
        RBucket<String> b = redisson.getBucket("test");
        b.set("123");

        List<CompletionStage<?>> ff = new ArrayList<>();
        for (int i = 0; i < 10000; i++) {
            RBucket<String> b2 = redisson.getBucket("test");
            RFuture<Void> f = b2.setAsync("123");
            ff.add(f);
        }

        ff.forEach(r -> r.toCompletableFuture().join());

        redisson.shutdown();
        runner.stop();

    }
```

**Comment by shiranyo** [comment]
@mrniko 
Existing connections will not be forcibly terminated, unlike Elasticache, where connections are disconnected after the 12 hours period. 
In your example, the connection remains active, and new connections will appropriately fetch the updated password from the CredentialsResolver, but it is using the existing ones. no?

**Comment by mrniko** [comment]
@shiranyo 

> WRONGPASS (invalid username-password pair) error is suddenly raised against the pool after 12 hours

Can you share detailed log?

**Comment by mrniko** [comment]
@shiranyo 

Please try attached version.

[redisson-3.25.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13839227/redisson-3.25.3-SNAPSHOT.jar.zip)

**Comment by shiranyo** [comment]
@mrniko, I plan to test the attached version in response to the issue.

Upon reviewing the logs from version 3.24.1, it appears that there were successful background reconnection attempts. However, issues arose while trying to use the client during that time, resulting in the following error:

```
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase nettyThreads setting. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@608742589 [redisClient=[addr=rediss://master.hidden.cache.amazonaws.com:6379], channel=[id: 0x649c95ef, L:/192.168.122.160:57240 ! R:master.hidden.cache.amazonaws.com/10.228.1.15:6379], currentCommand=null, usage=1], command: (EVAL), params: [local result = 0;for j = 1, #KEYS, 1 do local expireSet; if ARGV[2] ~= '' then expireSet = redis.call('pexpire', KEYS[j], ARGV[1], ARGV[2]); else expireSet = redis.call('pexpire', KEYS[j], ARGV[1]); end; if expireSet == 1 then result = expireSet;end; end; return result; , 1, hey, 86400000, ] after 5 retry attempts

	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:357)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:195)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:877)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```

My testing settings are: 

```
nettyThreads=32
connectionMinimumIdleSize=128
connectionPoolSize=256
retryInterval=5000
pingConnectionInterval=30000
connectTimeout=5000
timeout=2000
retryAttempts=5
```


Attaching the full logs:
[nettyerror.log](https://github.com/redisson/redisson/files/13852560/nettyerror.log)

**Comment by rgampa** [comment]
Hi @shiranyo I am also trying to use `CredentialsResolver` to support password rotations, I have a follow up question, in your tests you gave 5 retryAttempts. Though in the background the errors were happening (WriteRedisConnectionException), I assume from the client point of view it won't be an issue as internal retries will use the refreshed connections with new credentials, can you confirm? cc @mrniko

**Comment by mrniko** [comment]
@shiranyo 

When does it happen?
