### ISSUE TITLE
Redisson 3.18.1 - NullPointerException in messageDecoder

### ISSUE THREAD

**Issue by avcad** [redisson/redisson#4725]
We just upgraded Redisson 3.18.0 to 3.18.1 and started noticing this exception frequently.
I rolled back to 3.18.0 and now I can't reproduce it.

[12/7/22 22:18:01:235 GMT] 00000064 id=         org.redisson.client.handler.CommandDecoder                   E decodeCommand Unable to decode data. channel: [id: 0x005d8606, L:/192.168.109.238:59018 - R:redis-master.redis.svc.cluster.local./10.103.240.236:6379], reply: ReplayingDecoderByteBuf(ridx=279, widx=279)
java.lang.NullPointerException
	at org.redisson.client.handler.CommandDecoder.messageDecoder(CommandDecoder.java:477)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:438)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:399)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:227)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:825)

looks like getCommand() is null?
https://github.com/redisson/redisson/blob/3c4db93f147ecbb978c7bdfc32b22f69aceaf8e9/redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java#L477

**Comment by avcad** [comment]
[redisson.log](https://github.com/redisson/redisson/files/10181023/redisson.log)

**Comment by avcad** [comment]
The same log is also showing several ClassCastException (also new)

[12/7/22 22:27:45:042 GMT] 00000064 id=         org.redisson.client.handler.ErrorsLoggingHandler             E exceptionCaught Exception occured. Channel: [id: 0x005d8606, L:/192.168.109.238:59018 - R:redis-master.redis.svc.cluster.local./10.103.240.236:6379]
io.netty.handler.codec.DecoderException: java.lang.ClassCastException: java.lang.String incompatible with java.lang.Long
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:825)
Caused by: java.lang.ClassCastException: java.lang.String incompatible with java.lang.Long
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:27)
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:23)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:456)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:340)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 more

**Comment by mrniko** [comment]
It seems to be related to RBatch object in REDIS_WRITE_ATOMIC mode. Can you reproduce it?

**Comment by avcad** [comment]
Hi @mrniko,
We are able to reproduce in 3.18.1.

From our testing, we think it's coming from this commit:

Fixed - command replies don't match if connection pool size < 10 and at least one command failed. 
https://github.com/redisson/redisson/tree/5a60e7e0cb99e6cfadb370dac3f4d81621716d33

https://github.com/redisson/redisson/issues/4693

e.g we pick the commit prior and the problem doesn't happen

I was unable to reproduce in dev, but I grabbed a log from QA.

[redisson_trace.log](https://github.com/redisson/redisson/files/10190440/redisson_trace.log)

**Comment by mrniko** [comment]
Please share Redisson config

**Comment by mrniko** [comment]
Thanks for the logs!

Please try attached version

[redisson-3.18.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/10192636/redisson-3.18.2-SNAPSHOT.jar.zip)
