### ISSUE TITLE
Redisson error while springboot startup

### ISSUE THREAD

**Issue by shannonantony** [redisson/redisson#4752]
**Expected behavior**
I am using Redisson ver. 3.19.0 with springboot 2.5.2. while starting up I see netty error. I have redis sentinel cluster running at IP1:26379, IP2:26379 and IP3:26379(master)

**Actual behavior**

I get following error while starting up springboot

2022-12-18 16:48:36.515 [redisson-netty-2-9] [ERROR]: o.r.connection.SentinelConnectionManager      - io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: connect: 10.241.243.152/10.241.243.152:0
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: connect: IP2/IP2:0
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: connect: 10.241.243.152/10.241.243.152:0
Caused by: java.net.BindException: Cannot assign requested address: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:586)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:853)
	at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:91)
	at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:88)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:88)
	at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:315)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:248)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

Not able to understand why netty is trying to connect to port 0. Application works normally and I could hit my controller endpoints an d get results successfully. Please let me know how do I get rid of this error above. Not sure it has any adverse effect on the application performance.

**Steps to reproduce or test case**

**Redis version**
Redis 7.0
**Redisson version**
Redisson 3.19.0
**Redisson configuration**

Appreciate your help

thanks

Jay

**Comment by shannonantony** [comment]
Usecase: I am using Redisson for Distributed Lock feature.

**Comment by shannonantony** [comment]
After lot of trial and error, I could eliminate the error by putting master node in the beginning in the spring application.properties file as below

from
spring.redis.sentinel.nodes=IP1:26379,IP2:26379,IP3(master):26379

to

spring.redis.sentinel.nodes=IP3:26379(master),IP2:26379,IP1:26379

NO IDEA why this fixed the exception? :(

Please let me know if anyone has any clue

thanks

Jay

**Comment by mrniko** [comment]
Unable to reproduce it.
