### ISSUE TITLE
getAndDelete is not support?

### ISSUE THREAD

**Issue by kevinsir** [redisson/redisson#4783]
getAndDelete is not support?

I use getAndDelete 

`Caused by: java.lang.StackOverflowError: null
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getDel(DefaultedRedisConnection.java:292)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getDel(DefaultedRedisConnection.java:292)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getDel(DefaultedRedisConnection.java:292)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getDel(DefaultedRedisConnection.java:292)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getDel(DefaultedRedisConnection.java:292)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getDel(DefaultedRedisConnection.java:292)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getDel(DefaultedRedisConnection.java:292)`

**Redis version**
6.2.1
**Redisson version**
3.17.4
** springboot version**
2.6.10

**Comment by mrniko** [comment]
Unable to reproduce it. Make sure that you have redisson-spring-data-26 module in classpath

**Comment by mrniko** [comment]
Fixed in 3.18.0 version
