### ISSUE TITLE
how to avoid getting ClassCastException while reading values from RList<String>

### ISSUE THREAD

**Issue by mariokoehler** [redisson/redisson#4785]
We are using RList<String> to store some UUIDs. Every once in a while (once a month or so) the state of the RList seems to get corrupted and when we try to access the String values from the list we get ClassCastExceptions that tell us that you can't cast a java.lang.Float to a java.lang.String.

We're now wondering what may be the source of this problem, because we are sure that we don't put Float values into the list ourselves. This is the code in question, it gets the List from the Redis server and checks if a given UUID is contained in that list:

`
	public boolean runningRequestExists(Agency agency, Client client, Company company, ResultContent resultContent, String customerId) {

		if (!isEnabled)
			return false;

		String uid = getUid(agency, client, company, resultContent, customerId, false);

		RedissonClient rc = getClient();
		if (rc == null) {
			log.error("could not check running request, because client was null.");
			return false;
		}

		RList<String> list = redisson.getList(SET_IDENTIFIER);
		if (list == null) {
			log.error("could not check running request, because list was null.");
			return false;
		}

		// if we can't determine the status (because an exception will throw below) then
		// we assume there is no request running.
		boolean retValue = false;
		
		try {
			// for reasons unknown so far, we observed that in rare cases a ClassCastException might
			// be thrown here. If that happens we "ignore" the whole check and assume there
			// is no request running.
			retValue = list.stream().filter(i -> Optional.ofNullable(i).isPresent() && i.startsWith(uid) ).findAny().isPresent();
		} catch (Throwable t) {
			log.catching(t);
		}
		
		return retValue;
	}
`

The UUIDs themselves are a simple String concatenation of several ENUM sub-identifiers (so definitely nothing that could be mistaken for a Float):

`
	private String getUid(Agency agency, Client client, Company company, ResultContent resultContent, String customerId, boolean includeRandomUUID) {
		return agency.getDbEnumname() + ":" + client.getDbEnumname() + ":" + company.getCompanyName() + ":" + resultContent.getDbEnumname() + ":" + customerId
				+ (includeRandomUUID ? ":" + UUID.randomUUID() : "");
	}
`

And the exception is thrown almost at the end where "retValue = list.stream(...)" is evaluated. When that expression gets to the findAny() the exception is thrown:

`
Caused by: java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.String (java.lang.Float and java.lang.String are in module java.base of loader 'bootstrap')
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at de.otto.cccs.craproxy.util.ElasticacheHelper.runningRequestExists(ElasticacheHelper.java:243)
`

We would appreciate any suggestions as to what might cause this and how to mitigate it.

Is it for example possible that this might be related to the Codec used to serialize the instances? Right now, as you can see, we don't explicitly set a specific Codec. Is that something we should try? If so, what codec would be a good choice?

Thanks in advance for any help!

best regards
Mario Köhler

**Comment by mrniko** [comment]
> Caused by: java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.String

Try to use the default codec.
