### ISSUE TITLE
Replica connections keep growing into the thousands even though connection pool limit is 64

### ISSUE THREAD

**Issue by Strydom** [redisson/redisson#4803]
**Expected behavior**

Connections pool to be capped at 64.
We only have 10 k8s pods. So that should be max 640 connections per pod per redis node.

**Actual behavior**

We have thousands of connections to each replica node and they keep growing.
This only happened when I switched to using Redisson for reading, instead of Lettuce.
You can see the switch over in the graph:
<img width="1452" alt="Screenshot 2023-01-19 at 18 58 27" src="https://user-images.githubusercontent.com/2946828/213535609-540b2e28-5fd6-4096-a277-05aeb3a1f5c7.png">

We are using Redisson for batch writing as well and that is taking much more load than the reads but its connections to the master nodes is correctly staying below 640, currently around 490.

Another graph showing new connections being made all the time.
![Redis connections](https://user-images.githubusercontent.com/2946828/213543250-e5d91098-1f4b-4809-a87f-8a6c17cbede2.png)

**Steps to reproduce or test case**

```
override suspend fun read(trx: String, timeout: Long?): List<Placeholder> {
    val resolvedTimeout = timeout ?: blockTime // 1000
    val stream = redissonClient.reactive().getStream<String, String>(trx, StringCodec.INSTANCE)

    return stream
        .read(
            StreamReadArgs
                .greaterThan(StreamMessageId(0, 0))
                .timeout(Duration.ofMillis(resolvedTimeout))
        )
        .awaitSingle()
        .map { response ->
            response.value.map { Placeholder(it.key, it.value) }
        }
        .flatten()
}
```

**Redis version**
7.0.5

**Redisson version**
3.19.1

**Redisson configuration**
```
val config = Config()
val clusterServersConfig = config.useClusterServers()
clusterServersConfig.nodeAddresses = listOf("rediss://$host:$port")
clusterServersConfig.password = password
clusterServersConfig.isKeepAlive = false
clusterServersConfig.scanInterval = 30000

return Redisson.create(config)
```

**Comment by mrniko** [comment]
There is no `awaitSingle()` method in Mono interface

**Comment by mrniko** [comment]
Unable to reproduce with the test below.

```java
        RedisRunner master1 = new RedisRunner().port(6890).randomDir().nosave();
        RedisRunner master2 = new RedisRunner().port(6891).randomDir().nosave();
        RedisRunner master3 = new RedisRunner().port(6892).randomDir().nosave();
        RedisRunner slave1 = new RedisRunner().port(6900).randomDir().nosave();
        RedisRunner slave2 = new RedisRunner().port(6901).randomDir().nosave();
        RedisRunner slave3 = new RedisRunner().port(6902).randomDir().nosave();
        RedisRunner slave4 = new RedisRunner().port(6903).randomDir().nosave();

        ClusterRunner clusterRunner = new ClusterRunner()
                .addNode(master1, slave1, slave4)
                .addNode(master2, slave2)
                .addNode(master3, slave3);
        ClusterProcesses process = clusterRunner.run();

        Thread.sleep(5000);

        Config config = new Config();
        config.useClusterServers()
                .setLoadBalancer(new RandomLoadBalancer())
                .addNodeAddress(process.getNodes().stream().findAny().get().getRedisServerAddressAndPort());
        RedissonClient redisson = Redisson.create(config);

        RStream<String, String> stream = redisson.getStream("test", StringCodec.INSTANCE);

        for (int i = 0; i < 10000; i++) {
            Map<StreamMessageId, Map<String, String>> t = stream.read(
                    StreamReadArgs
                            .greaterThan(new StreamMessageId(0, 0))
                            .timeout(Duration.ofMillis(1000))
            );
        }
```

**Comment by mrniko** [comment]
Is it a **replicated** or **cluster** AWS Elasticache setup?

**Comment by Strydom** [comment]
Cluster AWS Elasticache setup. With 3 shards, each with 2 replicas

**Comment by Strydom** [comment]
The new connections seem correlated with traffic
![Requests](https://user-images.githubusercontent.com/2946828/213665383-0f79e8ea-4402-44ab-a819-2a6dd39f5c08.png)
![Redis connections](https://user-images.githubusercontent.com/2946828/213665389-6d132796-a93f-4f0e-af1f-db67c7e1509a.png)

**Comment by mrniko** [comment]
Can you provide some test case to reproduce it?

**Comment by Strydom** [comment]
I'm not sure I can reproduce it, seems to only be an issue on our production environment, which seems to point to high load being the cause?

Does this connection pattern look correct for this kind of request pattern? It seems correct to me, the current connections always drop back down after a spike. This is in our test environment.
![Requests](https://user-images.githubusercontent.com/2946828/213677951-fe5d7528-496a-4e55-8bf2-014731d67137.png)
![Redis connections](https://user-images.githubusercontent.com/2946828/213676362-375316ce-d9c6-487b-ad7a-099034100e90.png)

I will ask our database team if they can provide the memory dump

**Comment by Strydom** [comment]
I just redeployed the app, looks like num connections has capped out and no more connections can be made to the replicas. `Unable to connect to Redis server`. The writing connected to master nodes is working fine.

**Comment by mrniko** [comment]
> Does this connection pattern look correct for this kind of request pattern? It seems correct to me, the current connections always drop back down after a spike. 

It's an issue. Can you share the logs with trace logging level for `org.redisson` package?

> As for a test case the only difference i can see from my code and your test code is that you are not using Kotlin coroutines. Not sure if that could cause an issue?

It shouldn't.

**Comment by Strydom** [comment]
I got the logs from my local connecting to test env and i added these config settings:
```
clusterServersConfig.masterConnectionMinimumIdleSize = 1
clusterServersConfig.slaveConnectionMinimumIdleSize = 1
clusterServersConfig.subscriptionConnectionMinimumIdleSize = 1
```
I then fired a few requests. Do you want me to get logs from test env directly?

[redisson.log](https://github.com/redisson/redisson/files/10466654/redisson.log)

**Comment by mrniko** [comment]
"Connection created" in your logs is expected if you set IdleSize = 1 but overall connections shouldn't exceed the limit. Can you provide the logs with "Connection created" amount exceed  the limit?

**Comment by Strydom** [comment]
In production the errors are
```
exception: { [[-]](https://splunk.prod.egmonitoring.expedia.com/en-US/app/search/search?q=search%20index%3D%22eg-runtime-rcp%22%20kube_namespace%3D%22experience-manager%22%20sourcetype%3D%22kube%3Acontainer%3Aexperience-placeholders-api%22%20region%3D%22us-west-2%22%20%7C%20spath%20level%20%7C%20search%20level%3DERROR%7C%20spath%20logger_name%20%7C%20search%20logger_name%3D%22org.redisson*%22&earliest=-2h%40m&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&display.events.timelineEarliestTime=1674219180&display.events.timelineLatestTime=1674219240&sid=1674222428.7363_74A8010F-0152-4D34-A2CF-20634C54649C#)
     exception_class: java.util.concurrent.CompletionException
     exception_message: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 100.71.64.64/100.71.64.64:6379
     stacktrace: java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 100.71.64.64/100.71.64.64:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:155)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:318)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:277)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.client.RedisClient$1$1.run(RedisClient.java:241)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 100.71.64.64/100.71.64.64:6379
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:154)
	... 21 more
Caused by: java.util.concurrent.CompletionException: java.nio.channels.ClosedChannelException
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
	... 13 more
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1065)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	... 4 more

   }
   level: ERROR
   log_type: main
   logger_name: org.redisson.cluster.ClusterConnectionManager
   mdc: { [[+]](https://splunk.prod.egmonitoring.expedia.com/en-US/app/search/search?q=search%20index%3D%22eg-runtime-rcp%22%20kube_namespace%3D%22experience-manager%22%20sourcetype%3D%22kube%3Acontainer%3Aexperience-placeholders-api%22%20region%3D%22us-west-2%22%20%7C%20spath%20level%20%7C%20search%20level%3DERROR%7C%20spath%20logger_name%20%7C%20search%20logger_name%3D%22org.redisson*%22&earliest=-2h%40m&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&display.events.timelineEarliestTime=1674219180&display.events.timelineLatestTime=1674219240&sid=1674222428.7363_74A8010F-0152-4D34-A2CF-20634C54649C#)
   }
   message: Can't add slave: rediss://100.71.64.64:6379
   source_host: experience-placeholders-api-us-west-2-master-template-676d8rpz2
   thread_name: redisson-netty-3-11
```

**Comment by mrniko** [comment]
Can you try version attached on test environment with 8K+ connections spikes? log level is 'debug' for `org.redisson.command` package. Look for `forceFastReconnectAsync executed for ... ` messages

[redisson-3.19.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/10466883/redisson-3.19.2-SNAPSHOT.jar.zip)

**Comment by Strydom** [comment]
Test doesn't have 8k connection spikes. Those are the requests coming into the app. The connections in test env peaked around 90 per node. Which is still higher than the default pool limit of 64.
With that info does test env still look like it is an issue?

**Comment by Strydom** [comment]
>Can you try version attached on test environment with 8K+ connections spikes? log level is 'debug' for org.redisson.command package. Look for forceFastReconnectAsync executed for ...  messages

So just to be clear I will start the application locally using this new version. The application will connect to the test cluster. I will use gatling to run some load on it.

**Comment by Strydom** [comment]
I haven't been able to get anything to break on test environment, haven't seen any of those logs you asked for.
I think test environment is healthy. I will get our database team to re-start the cluster and report back.

**Comment by Strydom** [comment]
Okay so we have re-started the cluster to wipe lost connections. I've also switched back to Lettuce for reading for now. We still have Redisson setup though and are using it for batch writing.
Now we are getting lots thousands of errors like this
```
exception_class: reactor.core.Exceptions.ErrorCallbackNotImplemented
     exception_message: org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=14663, addr=rediss://100.71.65.117:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.
     stacktrace: reactor.core.Exceptions$ErrorCallbackNotImplemented: org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=14663, addr=rediss://100.71.65.117:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.
Caused by: org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=14663, addr=rediss://100.71.65.117:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.
	at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundException(MasterSlaveConnectionManager.java:566)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:515)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:643)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:124)
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:298)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by mrniko** [comment]
Can you share the logs from application start moment till the appearance of this error?

**Comment by mrniko** [comment]
Try to set `dnsMonitoringInterval = -1` in production to resolve this issue. I think it's related to issue then a single AWS hostname resolves to a multiple slave node IPs. Please check that

**Comment by mrniko** [comment]
Unable to reproduce it using AWS Elasticache Cluster with 3 shards and each has 2 replicas.

Below is the test.

```java
        Config c = new Config();
        c.useClusterServers().addNodeAddress(args.length > 0 ? args[0] : "redis://127.0.0.1:6901");
        RedissonClient redisson = Redisson.create(c);


        ExecutorService e = Executors.newFixedThreadPool(128);
        for (int i = 0; i < 100000; i++) {
            int j = i;
            e.submit(() -> {
                try {
                    RStream<String, String> stream = redisson.getStream("test" + ThreadLocalRandom.current().nextLong(), StringCodec.INSTANCE);
                    Map<StreamMessageId, Map<String, String>> t = stream.read(
                            StreamReadArgs
                                    .greaterThan(new StreamMessageId(0, 0))
                                    .timeout(Duration.ofMillis(ThreadLocalRandom.current().nextInt(10, 2000)))
                    );
                    if (j % 10 == 0) {
                        log.info("index: " + j);
                    }
                } catch (Exception ex) {
                    log.error(ex.getMessage(), ex);
                }
            });
        }
        e.shutdown();
        assert e.awaitTermination(3, TimeUnit.HOURS);
```

**Comment by mrniko** [comment]
Do you have any update?

**Comment by Strydom** [comment]
Hi, thanks for following up. I'm not sure when this will get investigated again on our side. I've moved off the project for now but will make sure the new team follow up on this. Not a high priority for us as the app is working fine with Redisson for writes and Lettuce for reads, but It makes sense to push for a single library.

**Comment by mrniko** [comment]
@Strydom 

Can you share logs from production from application start moment till the first error appearance?

**Comment by PyAntony** [comment]
I have had the same issue as described here. I am using the Vertx Redis client so I don't know if my problem is relevant to this situation or not. You can find more info here: https://github.com/vert-x3/vertx-redis-client/issues/365.
