### ISSUE TITLE
Issue with connecting Redisson to Azure Redis Enterprise via SSL.

### ISSUE THREAD

**Issue by Paveltrof86** [redisson/redisson#4806]
Hello!
We test our app on Azure Redis Enterprise cluster.
We are just trying to implement Redisson and testing performance. At the moment we use it for locks, queues, etc.
We also use `JedisConnectionFactory`.

On Redis Enterprise we disabled "Non-TLS access only"
![insights](https://user-images.githubusercontent.com/19744837/213648389-4948bf81-428a-418d-bd64-a70a60a52c3b.jpg)

Connect via IP:PORT
rediss://xx.xxx.xx.x:8500
![cluster nodes](https://user-images.githubusercontent.com/19744837/213651237-746a3558-2060-47f6-a6c6-1c28edcdc120.jpg)

Our code, like:

```
public JedisConnectionFactory jedisConnectionFactory() {
....
   jedisConfig = JedisClientConfiguration.builder()
					.connectTimeout(Duration.ofMillis(Integer.MAX_VALUE)).readTimeout(Duration.ofMillis(Integer.MAX_VALUE))
					.useSsl().and().usePooling().build();
   RedisClusterConfiguration clusterConfig = new RedisClusterConfiguration(this.configParams.getRedisHostsPorts())
...
   ...setPassword();
   jedisConFactory = new JedisConnectionFactory(clusterConfig, jedisClientConfig);
   return jedisConFactory;
}

public RedissonClient redisson() {
   Config config = new Config();
...
   ClusterServersConfig  serverConfig = config.useClusterServers();
   this.configParams.getRedisHostsPorts().forEach(hp -> serverConfig .addNodeAddress("rediss://" + hp));
   serverConfig .setReadMode(ReadMode.MASTER);
   setTimeOut()
   setPassword()
...
   return Redisson.create(config);
}
```

Jedis connects with ssl.
But with Redisson we have this:

```
......
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:145) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:196) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.Redisson.<init>(Redisson.java:68) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.Redisson.create(Redisson.java:109) ~[redisson-3.18.0.jar:3.18.0]
	... 45 more

Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address xx.xxx.xx.x found
	at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source) ~[?:1.8.0_361]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_361]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source) ~[?:1.8.0_361]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1549) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1395) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_361]

Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address  xx.xxx.xx.x found
	at sun.security.util.HostnameChecker.matchIP(Unknown Source) ~[?:1.8.0_361]
	at sun.security.util.HostnameChecker.match(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source) ~[?:1.8.0_361]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source) ~[?:1.8.0_361]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_361]
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source) ~[?:1.8.0_361]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1549) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1395) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_361]

```

If I use `clusterServersConfig.setSslEnableEndpointIdentification(false)` - everything works fine. But we don`t want to use it.

Thank you!

**Comment by mrniko** [comment]
Here is the explanation.
https://stackoverflow.com/questions/29157861/java-certificateexception-no-subject-alternative-names-matching-ip-address
