### ISSUE TITLE
Quarkus non native mode: Unable to find class when doing Rtopic publish with my own DTO

### ISSUE THREAD

**Issue by denysandriyanov** [redisson/redisson#4815]
Hello. I am trying to publish a message of  my own type (NotificationDTO ) to Rtopic.

here is a type of message
```
@RegisterForReflection
@Builder(toBuilder = true)
@Data
public class NotificationDTO {
    @NotNull
    private String id;
    @NotNull
    private String type;
    @NotNull
    private String data;
}
```

I am getting:
com.esotericsoftware.kryo.KryoException: Unable to find class: com.avid.configurator.service.dto.redis.NotificationDTO
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:182)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:151)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:107)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:390)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:434)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:399)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:87)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.avid.configurator.service.dto.redis.NotificationDTO
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:479)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:176)

Could you please advice. Thank you

**Comment by mrniko** [comment]
Did you try to set `useThreadClassLoader = false` setting?

**Comment by denysandriyanov** [comment]
Hello, no, could you please suggest where exactly it should be set?

**Comment by mrniko** [comment]
it's a Redisson setting. Should be set in configuration https://github.com/redisson/redisson/wiki/2.-Configuration#usethreadclassloader

**Comment by denysandriyanov** [comment]
Hello, thank you, i tried this, unfortunately still failing with exception i mentioned

**Comment by mrniko** [comment]
Can you share the code to reproduce it
