### ISSUE TITLE
Redisson 3.19.2 - fail to (de)serialization Object with Kryo5Codec

### ISSUE THREAD

**Issue by sunxiang0918** [redisson/redisson#4834]
Hello!
Since redisson 3.19.2 . the Kryo5Codec changed the InstantiatorStrategy from StdInstantiatorStrategy to SimpleInstantiatorStrategy.  
But, when I (de)serialization some Object which has no no-arg constructor, redisson will throw KryoException.

Do you know how to fix this error? 
Thank you for your help.

**Expected behavior**

can (de)serialization Object without no-arg constructor.

**Actual behavior**

throw KryoException like this:

`
Caused by: com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): com.xxxxxx.User 
	at org.redisson.codec.Kryo5Codec$SimpleInstantiatorStrategy.newInstantiatorOf(Kryo5Codec.java:94) 
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1190) 
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1199) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:163) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:122) 
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880) 
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:157) 
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:390) 
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205) 
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) 
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120) 
`

**Steps to reproduce or test case**

The VO struct like this:

kotlin:

```kotlin
data class User(var name:String, var age:Int)
```

or  java:

```java
public class User{

    private String name;

    private Integer age;

    public User(String name,Integer age) {
        this.name = name;
        this.age = age;
    }

    ...
    getter/setter
    ...

}
```

**Redis version**
redis 7.0.8

**Redisson version**
 redisson 3.19.2

**Redisson configuration**

**Comment by mrniko** [comment]
Below is the temporary solution:

```java
    private static class SimpleInstantiatorStrategy implements org.objenesis.strategy.InstantiatorStrategy {

        StdInstantiatorStrategy ss = new StdInstantiatorStrategy();

        @Override
        public <T> ObjectInstantiator<T> newInstantiatorOf(Class<T> type) {
            // Reflection.
            try {
                Constructor ctor;
                try {
                    ctor = type.getConstructor((Class[]) null);
                } catch (Exception ex) {
                    ctor = type.getDeclaredConstructor((Class[]) null);
                    ctor.setAccessible(true);
                }
                final Constructor constructor = ctor;
                return new ObjectInstantiator() {
                    public Object newInstance() {
                        try {
                            return constructor.newInstance();
                        } catch (Exception ex) {
                            throw new KryoException("Error constructing instance of class: " + className(type), ex);
                        }
                    }
                };
            } catch (Exception ignored) {
            }

            if (type.isMemberClass() && !Modifier.isStatic(type.getModifiers()))
                throw new KryoException("Class cannot be created (non-static member class): " + className(type));
            else {
                return ss.newInstantiatorOf(type);
            }
        }
    }
```

**Comment by sunxiang0918** [comment]
Thanks for your help!

**Comment by russtam** [comment]
Same exception for class with default constructor.

Spring Boot 3.0.2
Hibernate ORM core version 6.1.6.Final
org.redisson:redisson-hibernate-6:3.19.2  or org.redisson:redisson-hibernate-53:3.19.2
(with org.redisson:redisson-spring-boot-starter:3.19.2 - not starting because "org.hibernate.cache.CacheException: Caching was explicitly requested, but no RegionFactory was defined and there is not a single registered RegionFactory")

Entity class:
```
@Entity
@Table(name = "test_tbl", schema = "test")
@Cache(region = "testCache", usage = CacheConcurrencyStrategy.READ_WRITE)
public class TestEntity implements Serializable {

	@Serial
	private static final long serialVersionUID = 6164997737405848573L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	Long id;

	String name;

	Short age;

	public TestEntity() {
	}

	public TestEntity(Long id, String name, Short age) {
		this.id = id;
		this.name = name;
		this.age = age;
	}

	public TestEntity(String name, Short age) {
		this.name = name;
		this.age = age;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getAge() {
		return age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	@Override
	public String toString() {
		return "TestEntity{" +
				"id=" + id +
				", name='" + name + '\'' +
				", age=" + age +
				'}';
	}

}
```
Exception:
```
o.r.client.handler.CommandDecoder        : Unable to decode data. channel: [id: 0xaddd6637, L:/127.0.0.1:51806 - R:localhost/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=202, widx=202), command: (EVAL), promise: java.util.concurrent.CompletableFuture@1a56dd53[Not completed, 1 dependents], params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[2]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if expireDate <= tonumber(ARGV[1]) then return nil; end; return val; , 2, testCache, redisson__timeout__set:{testCache}, 1675587544568, PooledUnsafeDirectByteBuf(ridx: 0, widx: 85, cap: 256)]
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): 

org.hibernate.cache.spi.support.AbstractReadWriteAccess$Item
	at org.redisson.codec.Kryo5Codec$SimpleInstantiatorStrategy.newInstantiatorOf(Kryo5Codec.java:94) ~[redisson-3.19.2.jar:3.19.2]
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1190) ~[kryo-5.4.0.jar:na]
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1199) ~[kryo-5.4.0.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:163) ~[kryo-5.4.0.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:122) ~[kryo-5.4.0.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880) ~[kryo-5.4.0.jar:na]
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:157) ~[redisson-3.19.2.jar:3.19.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:390) ~[redisson-3.19.2.jar:3.19.2]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205) ~[redisson-3.19.2.jar:3.19.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[redisson-3.19.2.jar:3.19.2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120) ~[redisson-3.19.2.jar:3.19.2]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
