### ISSUE TITLE
Master change issue in replicated mode

### ISSUE THREAD

**Issue by siarheibarsukou** [redisson/redisson#4845]
Hi. We've noticed master change errors in our logs and we try to figure out what could be the reason of them. As a client we use Redisson 3.19.1 with replicated servers configuration. And as a server we use managed Redis in IBM Cloud which consists of one master node and one replica. I understand that it's perfectly fine for managed Redis to change its IP address but I'd like to understand why we see errors like below at that moment.

Here is a stacktrace:
```
2023-02-01 12:07:35,821 [redisson-netty-2-10] ERROR org.redisson.connection.SingleEntry - Unable to change master from: URL/IP1:PORT to: rediss://URL:PORT
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 23 of 24 were initialized. Redis server: URL/IP2:PORT
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:155) ~[redisson-3.19.1.jar!/:3.19.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:318) ~[redisson-3.19.1.jar!/:3.19.1]
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:277) ~[redisson-3.19.1.jar!/:3.19.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.client.RedisClient$1$1.run(RedisClient.java:241) ~[redisson-3.19.1.jar!/:3.19.1]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 23 of 24 were initialized. Redis server: URL/IP2:PORT
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:154) ~[redisson-3.19.1.jar!/:3.19.1]
	... 19 more
Caused by: java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=rediss://URL:PORT]
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:245) ~[redisson-3.19.1.jar!/:3.19.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	... 2 more
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=rediss://URL:PORT]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.19.1.jar!/:3.19.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	... 2 more
2023-02-01 12:07:35,821 [redisson-netty-2-10] ERROR org.redisson.connection.ReplicatedConnectionManager - Unable to change master to URL/IP3:PORT
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 23 of 24 were initialized. Redis server: URL/IP2:PORT
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:155) ~[redisson-3.19.1.jar!/:3.19.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:318) ~[redisson-3.19.1.jar!/:3.19.1]
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:277) ~[redisson-3.19.1.jar!/:3.19.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.client.RedisClient$1$1.run(RedisClient.java:241) ~[redisson-3.19.1.jar!/:3.19.1]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 23 of 24 were initialized. Redis server: URL/IP2:PORT
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:154) ~[redisson-3.19.1.jar!/:3.19.1]
	... 19 more
Caused by: java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=rediss://URL:PORT]
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:245) ~[redisson-3.19.1.jar!/:3.19.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	... 2 more
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=rediss://URL:PORT]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.19.1.jar!/:3.19.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	... 2 more
```

**Comment by mrniko** [comment]
Can you share connections amount graph for this node?

**Comment by mrniko** [comment]
Also check result of INFO REPLICATION command. This is why IP is being changed

**Comment by siarheibarsukou** [comment]
Here is the output of INFO REPLICATION:
```
role:master
connected_slaves:1
slave0:ip=127.0.0.1,port=8500,state=online,offset=6372709721345,lag=0
master_replid:c1af2c4befafca930dd05fffb20c274c68a6898d
master_replid2:04b3816c2bb4b467fb4f1bd23f4030a8b828074e
master_repl_offset:6372709721345
second_repl_offset:6160029437299
repl_backlog_active:1
repl_backlog_size:10485760
repl_backlog_first_byte_offset:6372699235586
repl_backlog_histlen:10485760
```
As for connections amount. We saw up to 75 connections at peak but usually it's 20-25 which correlates with our settings:
```
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  subscriptionsPerConnection: 5
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
```

**Comment by mrniko** [comment]
Please share logs from application start moment till the issue appeared.

**Comment by siarheibarsukou** [comment]
We've looked into our console logs and found very strange behaviour. I can see that master switches between three IP addresses almost every seconds. It feels like there is a kind of load balancer.
```
2023-01-31 19:02:39,111 [main] INFO  org.redisson.Version - Redisson 3.19.1
2023-01-31 19:02:39,783 [main] INFO  org.redisson.connection.ReplicatedConnectionManager - rediss://URL:PORT is the master
2023-01-31 19:02:39,900 [redisson-netty-2-13] INFO  org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for URL/IP1:PORT
2023-01-31 19:02:40,398 [redisson-netty-2-23] INFO  org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for URL/IP1:PORT
2023-01-31 19:02:41,440 [redisson-netty-2-26] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP3:PORT
2023-01-31 19:02:42,504 [redisson-netty-2-31] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:02:43,584 [redisson-netty-2-6] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP2:PORT
2023-01-31 19:02:44,627 [redisson-netty-2-22] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP1:PORT to rediss://IP3:PORT
2023-01-31 19:02:45,688 [redisson-netty-2-13] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:02:46,755 [redisson-netty-2-15] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:02:47,800 [redisson-netty-2-21] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP2:PORT
2023-01-31 19:02:48,820 [redisson-netty-2-18] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP1:PORT to rediss://IP3:PORT
2023-01-31 19:02:49,848 [redisson-netty-2-22] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP1:PORT to rediss://IP2:PORT
2023-01-31 19:02:50,890 [redisson-netty-2-29] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP2:PORT
2023-01-31 19:02:51,936 [redisson-netty-2-28] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP2:PORT
2023-01-31 19:02:55,096 [redisson-netty-2-7] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:02:56,147 [redisson-netty-2-19] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP1:PORT
2023-01-31 19:02:57,182 [redisson-netty-2-26] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP1:PORT to rediss://IP2:PORT
2023-01-31 19:02:59,252 [redisson-netty-2-20] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP3:PORT
2023-01-31 19:03:00,291 [redisson-netty-2-30] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP2:PORT
2023-01-31 19:03:01,363 [redisson-netty-2-12] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:03:02,408 [redisson-netty-2-22] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:03:03,441 [redisson-netty-2-18] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP1:PORT
2023-01-31 19:03:04,473 [redisson-netty-2-10] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP1:PORT to rediss://IP2:PORT
2023-01-31 19:03:05,542 [redisson-netty-2-6] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:03:06,646 [redisson-netty-2-8] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP3:PORT
2023-01-31 19:03:07,835 [redisson-netty-2-12] INFO  org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for URL/IP2:PORT
2023-01-31 19:03:08,267 [redisson-netty-2-32] INFO  org.redisson.connection.SingleEntry - master URL/IP1:PORT has changed to URL/IP2:PORT
2023-01-31 19:03:08,268 [redisson-netty-2-32] INFO  org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for URL/IP2:PORT
2023-01-31 19:03:09,269 [redisson-netty-2-5] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP3:PORT to rediss://IP2:PORT
2023-01-31 19:03:10,311 [redisson-netty-2-6] INFO  org.redisson.connection.ReplicatedConnectionManager - Hostname: rediss://URL:PORT has changed IP from: URL/IP2:PORT to rediss://IP1:PORT
2023-01-31 19:03:11,436 [redisson-netty-2-9] INFO  org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for URL/IP2:PORT
2023-01-31 19:03:11,890 [redisson-netty-2-15] INFO  org.redisson.connection.SingleEntry - master URL/IP2:PORT has changed to URL/IP2:PORT
2023-01-31 19:03:11,891 [redisson-netty-2-15] INFO  org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for URL/IP2:PORT
...
```
