### ISSUE TITLE
Getting Redis Timeout Exception. Not sure why. Could you please help here? 

### ISSUE THREAD

**Issue by sakethbalijepalli** [redisson/redisson#4846]
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (GET) with params: [C1V23I31371874L] channel: [id: 0xe5eaf15c, L:/169.254.76.1:51424 - R redis url:6379]
at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:704)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
at java.lang.Thread.run(Thread.java:750)

Redis configuration - 
 @Bean(name = "redissonClient", destroyMethod = "shutdown")
  public RedissonClient redisClient() {
    LOG.info("redis created");
    Config config = new Config();
    config.useSingleServer().setAddress(env.getProperty("redis.url"))
    .setConnectionMinimumIdleSize(4)
    .setRetryAttempts(1);
    return Redisson.create(config);
  }
  
  Redisson version - 
  
  <dependency>
   <groupId>org.redisson</groupId>
   <artifactId>redisson</artifactId>
   <version>3.6.5</version>
</dependency>

**Comment by sakethbalijepalli** [comment]
@mrniko

**Comment by sakethbalijepalli** [comment]
Other issue is - 

[redisson-netty-1-4] ERROR org.redisson.connection.DNSMonitor - Unable to resolve prod-ui.9nnkk0.0001.usw2.cache.amazonaws.com
io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'prod-ui.9nnkk0.0001.usw2.cache.amazonaws.com' failed to resolve 'prod-ui.9nnkk0.0001.usw2.cache.amazonaws.com'
at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:728)
at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:670)
at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:306)
at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:295)
at io.netty.resolver.dns.DnsNameResolverContext.access$700(DnsNameResolverContext.java:60)
at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:346)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:223)
at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42)
at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:162)
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/169.254.78.1:53] query timed out after 5000 milliseconds (no stack trace available)

Getting this error as well. @mrniko

**Comment by mrniko** [comment]
@sakethbalijepalli 

This issue fixed in 3.18.0

**Comment by mrniko** [comment]
> Other issue is -

@sakethbalijepalli

This issue fixed in 3.18.0

**Comment by sakethbalijepalli** [comment]
Okay @mrniko thanks a lot!

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by sakethbalijepalli** [comment]
Can we go with a newer version like 3.19.1 or 3.18.0 would suffice?

**Comment by sakethbalijepalli** [comment]
> https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

Yes, i saw this link before.

**Comment by mrniko** [comment]
you can use 3.19.3

**Comment by sakethbalijepalli** [comment]
Okay, thanks.

**Comment by sakethbalijepalli** [comment]
Hi, so we are getting the below error after changing the version to 3.19.3 - 
[redisson-netty-2-36] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0x7ecc4c62, L:/169.254.76.1:36150 - R:redis.net/:6379], reply: ReplayingDecoderByteBuf(ridx=19, widx=19), command: (GET), promise: java.util.concurrent.CompletableFuture@229d2339[Not completed, 1 dependents], params: [C3923836184161W]
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 32
at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393)
at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:750)
[redisson-netty-2-36] ERROR org.redisson.client.handler.ErrorsLoggingHandler - Exception occured. Channel: [id: 0x7ecc4c62, L:/169.254.76.1:36150 - R:redis.net/:6379]
io.netty.handler.codec.DecoderException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 32
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:750)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 32
at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393)
at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
org.redisson.client.RedisException: Unexpected exception while processing command
at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:280)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
at org.redisson.RedissonObject.get(RedissonObject.java:83)
at org.redisson.RedissonBucket.get(RedissonBucket.java:135)


Could you please help me why we are getting this error?
