### ISSUE TITLE
Nullpointer Exception when using RRateLimiter instance with RMapCache 

### ISSUE THREAD

**Issue by k1sneha** [redisson/redisson#4861]
The requirement is to use Map of `userId` and `RRateLimiter` instances (`Map<Int, RRateLimiter>`), to throttle a request for given user based on number of permits decided by a configuration. 

When `RMapCache` is used to leverage `TTL`, a **null pointer exception** is thrown when the `RRateLimiter` instance is retrieved for **2nd** time. Attaching relevant code and exception.

Is there any way to fix this ?

**Provider:**

```kt
class RRateLimiterCacheProvider @Inject constructor(
    loader: RRateLimiterLoader,
    redissonClient: RedissonClient,
) : Provider<MutableMap<String, RRateLimiter>> {

    private val cache = redissonClient.getMapCache(
        "RRateLimiterCache", defaults<String, RRateLimiter>()
            .loader(loader)
            .syncStrategy(UPDATE)
            .maxIdle(6, HOURS)
    )

    override fun get(): MutableMap<String, RRateLimiter> = WrappedMap(cache)

    class WrappedMap(private val rMapCache: RMapCache<String, RRateLimiter>) :
        MutableMap<String, RRateLimiter> by rMapCache {

        override fun put(key: String, value: RRateLimiter): RRateLimiter = rMapCache.put(key, value, 6, HOURS)
    }

}

```

**Loader:**

```kt
class RRateLimiterLoader @Inject constructor(
    private val service: Service,
    private val redissonClient: RedissonClient,
) : MapLoader<Int, RRateLimiter> {

    override fun load(userId: Int): RRateLimiter {

        val limiter =
            redissonClient.getRateLimiter("Request_" + userId);

        limiter.trySetRate(PER_CLIENT, getPermits(), 1, MINUTES)
        return limiter;
    }

    private fun getPermits(): Long =
        toLong(service.getConfiguration(CONF), 2L)

    override fun loadAllKeys(): MutableIterable<Int> {
        TODO("No implementation required here since we don't have any use case to load all keys at once")
    }
}

```
**Get map**

```java
   public RRateLimiter getRRateLimiter(final int userId) {
        try {
            return RRateLimiterCache.get(userId);
        }
        catch (final RedisException e) {
            throw rte(e, MSG_CANNOT_GET_RATE_LIMITER, userId);
        }
    }
```

**Exception**

```log
Caused by: java.lang.NullPointerException
        at org.redisson.liveobject.core.RedissonObjectBuilder.getObject(RedissonObjectBuilder.java:245)
        at org.redisson.liveobject.core.RedissonObjectBuilder.fromReference(RedissonObjectBuilder.java:229)
        at org.redisson.liveobject.core.RedissonObjectBuilder.fromReference(RedissonObjectBuilder.java:214)
        at org.redisson.liveobject.core.RedissonObjectBuilder.tryHandleReference0(RedissonObjectBuilder.java:432)
        at org.redisson.liveobject.core.RedissonObjectBuilder.tryHandleReference(RedissonObjectBuilder.java:426)
        at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:567)
        at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:559)
        at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:547)
        at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:524)
        at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:176)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:460)
        at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:454)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:385)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

```

**Comment by mrniko** [comment]
RRateLimiter can't be stored in RMap objects

**Comment by k1sneha** [comment]
> RRateLimiter can't be stored in RMap objects

Do we have any other alternative options ? We are in process of moving Guava caches to Redisson. We have a use case as shown above, to provide multiple `RRateLimiter` instances as the rates may vary based on configuration.  This works perfectly with the [Guava RateLimiter]( https://guava.dev/releases/19.0/api/docs/index.html?com/google/common/util/concurrent/RateLimiter.html) and the map as  `LoadingCache<Int, RateLimiter>`

**Comment by mrniko** [comment]
Store RateLimiter name instead of instance
