### ISSUE TITLE
Command execution timeout for command: (PING)

### ISSUE THREAD

**Issue by StriveStar** [redisson/redisson#4865]
This bug is sporadic. I have check network is normal, but machine memory usage is high. machine memory usage can influence this bug?

Use redisson version: 3.17.6.

redisson config:
ClusterServersConfig clusterServersConfig = config.useClusterServers();
clusterServersConfig.setScanInterval(2000);
clusterServersConfig.setIdleConnectionTimeout(10000);
clusterServersConfig.setPingConnectionInterval(5000);
clusterServersConfig.setConnectTimeout(3000);
for (String ip : split) {
clusterServersConfig.addNodeAddress("redis://"+ip);
}
RedissonClient redisson = Redisson.create(config);

error stack: 
[redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x8db826c1, L:/127.0.0.1:58910 - R:127.0.0.1/127.0.0.1:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) 
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) 
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) 
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
	at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by xiahuhu1** [comment]
I have the save questions,and this question comes up every day at 9:00 a.m https://github.com/redisson/redisson/issues/4852#issue-1575623745

**Comment by mrniko** [comment]
> but machine memory usage is high

Did you check a memory dump?
