### ISSUE TITLE
Testing servers by drop 5 minutes - Unable to init enough connections amount! Only 0 of 3 were initialized.

### ISSUE THREAD

**Issue by alexworkgit** [redisson/redisson#4872]
Hello i testing app used redisson, my configuration 6 instances of redis and 3 sentinels, one server 2 instance of redis, cache+database+sentinel and on each server my app with redisson. I run "drop script" from other server, that go down servers for 5minutes cycling and througth some time (4-5 downs of servers in cycle) i have error in logs "Unable to init enough connections amount! Only 0 of 3 were initialized." on first or second server more often. After i see error, i am kill "drop script", wait for all server go to up and look that error, that not go away. My app get data from http and put in cache and use locks, but transfering data not affected to error. I am appended file log with error bottom.

dropscript.sh:
```
HOSTS='172.18.20.166 172.18.20.167 172.18.20.168'

while [ 1 = 1 ]; do
  for v in $HOSTS; do
    echo "$(date +"%T") Go down host $v"
    ssh root@$v 'ip link set eth0 down && sleep 5m && ip link set eth0 up'
    echo "$(date +"%T") Go up host $v "
    #sleep 1m
  done 
  echo "Wait for next cycle 10s"
  sleep 10s
done 
exit
```

**Expected behavior**
No errors.
**Actual behavior**
Log from one of servers with error.
full: [redisson.log](https://github.com/redisson/redisson/files/10764405/redisson.log)
short:
```
11:29:25 Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:53:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:70:queue:0, freezeReason=MANAGER, client=[addr=redis://172.18.20.168:6380], nodeType=SLAVE, firstFail=1676615073796]
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 3 were initialized. Server: 172.18.20.168/172.18.20.168:6380
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
	at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1321)
	at java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2238)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:197)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:122)
	at org.redisson.connection.MasterSlaveEntry.slaveUpAsync(MasterSlaveEntry.java:467)
	at org.redisson.connection.SentinelConnectionManager.addSlave(SentinelConnectionManager.java:595)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$16(SentinelConnectionManager.java:470)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$22(SentinelConnectionManager.java:458)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:470)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:464)
	at org.redisson.client.handler.CommandDecoder.decodeResult(CommandDecoder.java:453)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:447)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 3 were initialized. Server: 172.18.20.168/172.18.20.168:6380
	at org.redisson.connection.pool.ConnectionPool.createConnection(ConnectionPool.java:104)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:92)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:77)
	at org.redisson.connection.pool.SlaveConnectionPool.initConnections(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:194)
	... 38 common frames omitted
11:29:25 Unable to add slave redis://172.18.20.168:6380
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 3 were initialized. Server: 172.18.20.168/172.18.20.168:6380
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
	at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1321)
	at java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2238)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:197)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:122)
	at org.redisson.connection.MasterSlaveEntry.slaveUpAsync(MasterSlaveEntry.java:467)
	at org.redisson.connection.SentinelConnectionManager.addSlave(SentinelConnectionManager.java:595)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$16(SentinelConnectionManager.java:470)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$22(SentinelConnectionManager.java:458)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:470)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:464)
	at org.redisson.client.handler.CommandDecoder.decodeResult(CommandDecoder.java:453)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:447)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 3 were initialized. Server: 172.18.20.168/172.18.20.168:6380
	at org.redisson.connection.pool.ConnectionPool.createConnection(ConnectionPool.java:104)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:92)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:77)
	at org.redisson.connection.pool.SlaveConnectionPool.initConnections(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:194)
	... 38 common frames omitted
11:29:25 Can't execute SENTINEL commands on 172.18.20.168/172.18.20.168:26379
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 3 were initialized. Server: 172.18.20.168/172.18.20.168:6380
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
	at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1321)
	at java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2238)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:197)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:122)
	at org.redisson.connection.MasterSlaveEntry.slaveUpAsync(MasterSlaveEntry.java:467)
	at org.redisson.connection.SentinelConnectionManager.addSlave(SentinelConnectionManager.java:595)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$16(SentinelConnectionManager.java:470)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$22(SentinelConnectionManager.java:458)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:470)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:464)
	at org.redisson.client.handler.CommandDecoder.decodeResult(CommandDecoder.java:453)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:447)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 3 were initialized. Server: 172.18.20.168/172.18.20.168:6380
	at org.redisson.connection.pool.ConnectionPool.createConnection(ConnectionPool.java:104)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:92)
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:77)
	at org.redisson.connection.pool.SlaveConnectionPool.initConnections(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:194)
	... 38 common frames omitted
```

**Steps to reproduce or test case**
./dropscript.sh

**Redis version**
6.2.6
**Redisson version**
3.19.3
**Redisson configuration**
In my app i initialize two instance dbMaster(redis as database) and cacheMaster(redis as cache) of redis by code bottom.
```
        Config config = new Config();
        config.setLockWatchdogTimeout(4*60*1000);
        SentinelServersConfig connect = config.useSentinelServers().setMasterName(redisDbName);
        if (hosts.size() < 2) connect.setCheckSentinelsList(false);
        LoadBalancer loadBalancer = new RoundRobinLoadBalancer();
        connect.setSentinelAddresses(hosts);
        connect.setLoadBalancer(loadBalancer);
        //.addSentinelAddress("redis://172.18.20.166:26379", "redis://172.18.20.167:26379", "redis://172.18.20.168:26379");
        connect.setMasterConnectionMinimumIdleSize(3);
        connect.setSlaveConnectionMinimumIdleSize(3);
        RedissonClient client = Redisson.create(config);
```

**Comment by mrniko** [comment]
> ... 38 common frames omitted

We need full stacktrace to get the cause.

**Comment by alexworkgit** [comment]
> > ... 38 common frames omitted
> 
> We need full stacktrace to get the cause.

How get full stacktrace in logs ?

**Comment by alexworkgit** [comment]
> > ... 38 common frames omitted
> 
> We need full stacktrace to get the cause.

How i can get full stacktrace ?

**Comment by alexworkgit** [comment]
Log writed with log level DEBUG. How expand sub exceptions in redisson ?

**Comment by alexworkgit** [comment]
When testing with ./dropscript.sh, if I set data with redisson after a while I get an error "READONLY" bottom. At the first message occurence, I stop the dropscript, the server that was down rises within 5 minutes, but the error remains. 
``` 
09:13:30 connection released for command (SET) and params [data.test-3674393, PooledUnsafeDirectByteBuf(ridx: 0, widx: 5880, cap: 8192)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@1190779222 [redisClient=[addr=redis://172.18.20.166:6379], channel=[id: 0xf39ca867, L:/172.18.20.166:53522 - R:172.18.20.166/172.18.20.166:6379], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@5d7c7f88[Completed exceptionally: org.redisson.client.RedisException: READONLY You can't write against a read only replica.. channel: [id: 0xf39ca867, L:/172.18.20.166:53522 - R:172.18.20.166/172.18.20.166:6379] command: (SET), promise: java.util.concurrent.CompletableFuture@5d7c7f88[Not completed, 1 dependents], params: [data.test-3674393, PooledUnsafeDirectByteBuf(ridx: 0, widx: 5880, cap: 8192)]], command=(SET), params=[data.test-3674393, PooledUnsafeDirectByteBuf(ridx: 0, widx: 5880, cap: 8192)], codec=org.redisson.codec.Kryo5Codec], usage=0]
```
I think it's because of this connection bug where the redisson can't connect to the sentinel and update the state.
```
11:29:25 Can't execute SENTINEL commands on 172.18.20.168/172.18.20.168:26379
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 3 were initialized. Server: 172.18.20.168/172.18.20.168:6380
```

**Comment by mrniko** [comment]
> READONLY You can't write against a read only replica

You need to check your Redis configuration.

**Comment by alexworkgit** [comment]
> > READONLY You can't write against a read only replica
> 
> You need to check your Redis configuration.

After error sentinel's select right master and two slave, but redisson errors remain.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4902
