### ISSUE TITLE
Command execution timeout for command: (INFO REPLICATION)

### ISSUE THREAD

**Issue by ki224822** [redisson/redisson#4884]
I'm using below stack

**Amazon ElastiCache**: Redis-6.2.6
**spring boot**: 2.3.4.RELEASE
**redisson**: org.redisson:redisson-spring-data-23:3.19.3

**RedissonClient**
```
@Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useReplicatedServers().addNodeAddress(getAddress())
            .setScanInterval(3000)
            .setRetryAttempts(2);

        return Redisson.create(config);
    }
```

**Exception**
```
java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://cache-003.amazonaws.com:6379]
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:250)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://cache-003.amazonaws.com:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:249)
	... 5 common frames omitted
```

Why is an exception being thrown? how can i solve it?

**Comment by mrniko** [comment]
Can you share Redisson logs since application start moment?

**Comment by ki224822** [comment]
Thanks for comment
Please understand that the elasticcache endpoint has been slightly modified due to security issues.
ElasticCache spec is primary(1), replica(2)
Should I connect to the default endpoint with a useSingleServer Config?

`2023-02-22 00:01:03.382  INFO 20077 --- [           main] org.redisson.Version                     : Redisson 3.19.3
2023-02-22 00:01:03.925  INFO 20077 --- [           main] o.r.c.ReplicatedConnectionManager        : redis://001.cache.amazonaws.com:6379 is the master
2023-02-22 00:01:03.955  INFO 20077 --- [           main] o.r.c.ReplicatedConnectionManager        : redis://002.cache.amazonaws.com:6379 is a slave
2023-02-22 00:01:03.988  INFO 20077 --- [           main] o.r.c.ReplicatedConnectionManager        : redis://003.cache.amazonaws.com:6379 is a slave
2023-02-22 00:01:04.074  INFO 20077 --- [sson-netty-2-21] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for 001.cache.amazonaws.com/10.148.36.238:6379
2023-02-22 00:01:04.142  INFO 20077 --- [sson-netty-2-28] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for 001.cache.amazonaws.com/10.148.36.238:6379
2023-02-22 00:01:04.157  INFO 20077 --- [sson-netty-2-12] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for 003.cache.amazonaws.com/10.148.33.104:6379
2023-02-22 00:01:04.163  INFO 20077 --- [sson-netty-2-21] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for 002.cache.amazonaws.com/10.148.35.77:6379
2023-02-22 00:01:04.227  INFO 20077 --- [sson-netty-2-29] o.r.connection.pool.SlaveConnectionPool  : 24 connections initialized for 003.cache.amazonaws.com/10.148.33.104:6379
2023-02-22 00:01:04.232  INFO 20077 --- [sson-netty-2-30] o.r.connection.pool.SlaveConnectionPool  : 24 connections initialized for 002.cache.amazonaws.com/10.148.35.77:6379 `

**Comment by mrniko** [comment]
Did you try to increase timeout?

**Comment by ki224822** [comment]
Thanks for the comment .
Rather than increasing the interval, I chose to use the single server, and it is operating normally without errors.

**Comment by heqiqi** [comment]
in cluster mode , 3 shards and 3 replica, met the same issue.

`org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts, is non-idempotent command: false Check connection with Redis node: xxxxxx for TCP packet drops.  
Try to increase nettyThreads and/or timeout settings. Command: (INFO REPLICATION), params: [], channel: [id: 0x5b62f1bd, L:/10.0.0.0:49696 - R:10.0.0.250/10.0.0.250:6379]
 at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$9(RedisExecutor.java:402)
 at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
 at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
 at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:748)`

**Comment by mrniko** [comment]
Fixed. Thanks for report.
