### ISSUE TITLE
The eventLoopGroup cannot be configured with yaml

### ISSUE THREAD

**Issue by thoot-235** [redisson/redisson#4888]
redisson:
      config: |
        singleServerConfig: 
          password: "123456@pass"
          subscriptionsPerConnection: 5               
          clientName: tddst                          
          address: "redis://192.168.1.65:6379"
          database: 0
        threads: 16                                   
        nettyThreads: 32      
        codec: !<org.redisson.codec.JsonJacksonCodec> {}   
        transportMode: "NIO"                         
        cleanUpKeysAmount: 100  
        addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> {}        
        eventLoopGroup: io.netty.channel.nio.NioEventLoopGroup    

or #eventLoopGroup: !<io.netty.channel.nio.NioEventLoopGroup> {}

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is java.lang.IllegalArgumentException: Can't parse config
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 61 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can't parse config
	at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:145)
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$9934575b.CGLIB$redisson$5(<generated>)
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$9934575b$$FastClassBySpringCGLIB$$cbd4ecc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$9934575b.redisson(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 62 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'singleServerConfig': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"singleServerConfig: 
  "[truncated 1991 chars]; line: 1, column: 19]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2961)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2002)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:116)
	at org.redisson.config.Config.fromJSON(Config.java:589)
	at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:142)
	... 72 common frames omitted
	Suppressed: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.netty.channel.EventLoopGroup` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (StringReader); line: 33, column: 17] (through reference chain: org.redisson.config.Config["eventLoopGroup"])
		at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
		at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
		at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
		at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
		at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
		at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
		at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:150)
		at org.redisson.config.Config.fromYAML(Config.java:642)
		at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:139)
		... 72 common frames omitted

**Comment by thoot-235** [comment]
use Version
'springBootVersion', "2.7.7"
'springCloudVersion', "2021.0.5"
redisson : org.redisson:redisson-spring-boot-starter:3.19.3
JDK: JavaVersion.VERSION_11

**Comment by mrniko** [comment]
Fixed! Thanks for report
