### ISSUE TITLE
Issue with org.redisson.client.protocol.convertor.NumberConvertor

### ISSUE THREAD

**Issue by gs-asrivastav** [redisson/redisson#4889]
**Expected behavior**
```
RMap<String, Long> cache = client.getMapCache(KEY);
String key = "abcd";
Long val = 375653043488240L;

cache.addAndGet(key, val);
```
This should add the the 375653043488240 to the current value of "abcd" key and return the sum  

**Actual behavior**
```
2023-02-22 16:39:26 [index:app.name_IS_UNDEFINED] ERROR [redisson-netty-5-5] [ip:] [cId:] [rId:]  org.redisson.client.handler.CommandDecoder:Unable to decode data. channel: [id: 0xfe388cfe, L:/127.0.0.1:59725 - R:localhost/127.0.0.1:59679], reply: ReplayingDecoderByteBuf(ridx=26, widx=26), command: (EVAL), promise: java.util.concurrent.CompletableFuture@4e7b2a04[Not completed, 1 dependents], params: [local value = redis.call('hget', KEYS[1], ARGV[2]); local expireDate = 92233720368547758; local t = ..., 8, gs-test-redisson-number-hash, redisson__timeout__set:{gs-test-redisson-number-hash}, redisson__idle__set:{gs-test-redisson-number-hash}, redisson_map_cache_created:{gs-test-redisson-number-hash}, redisson_map_cache_updated:{gs-test-redisson-number-hash}, redisson__map_cache__last_access__set:{gs-test-redisson-number-hash}, redisson_map_cache_removed:{gs-test-redisson-number-hash}, {gs-test-redisson-number-hash}:redisson_options, ...]
java.lang.NumberFormatException: For input string: "3.7565304348824e+14"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.redisson.client.protocol.convertor.NumberConvertor.convert(NumberConvertor.java:38)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:449)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:385)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
```

**Steps to reproduce or test case**
```
RMap<String, Long> cache = client.getMapCache(KEY);
String key = "abcd";
Long val = 375653043488240L;

cache.addAndGet(key, val);
```

**Redis version**

**Redisson version**

**Redisson configuration**
- Used a single node configuration, any configuration would do.

**Comment by gs-asrivastav** [comment]
The root cause of the issue is: 
1. The updation of the value happens with StringCodec which includes the E14 in the redis value
2. When you use the NumberConverter class, it is assigned to the long block 
3. It tries to parse as `Long.parseLong(..)` which fails

**Comment by mrniko** [comment]
Fixed! Thanks for report
