### ISSUE TITLE
Service can't connect to Redis slave: java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 21 of 24 were initialized.

### ISSUE THREAD

**Issue by brijnkh** [redisson/redisson#4896]
**Expected Behavior:**
After Upgrading Azure redis 4 to Azure Redis 6, redisson should be able to connect to nodes normally.

**Actual Behavior:**
Redisson is not able to connect to slave with the below exception:
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 21 of 24 were initialized. Redis server: xx.xxx.xx.x/xx.xxx.xx.x:xxxxx
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
    at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:154)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
    at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:317)
    at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$7(ConnectionPool.java:276)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
    at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
    at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
    at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 21 of 24 were initialized. Redis server: xx.xxx.xx.x/xx.xxx.xx.x:xxxxx
    at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$1(ConnectionPool.java:153)
    ... 21 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: xx.xxx.xx.x/xx.xxx.xx.x:xxxxx
    at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
    ... 13 common frames omitted
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: xx.xxx.xx.x/xx.xxx.xx.x:xxxxx
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
    at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
    ... 8 common frames omitted

**Steps To Reproduce:**
Migrate from Azure Redis 4 to Azure Redis 6

**Redisson version:**
3.17.3

**Comment by mrniko** [comment]
This is a network issue. Ask Azure support if you have connection limit

**Comment by brijnkh** [comment]
@mrniko I appreciate your quick response.
I checked the client connections. 
Maximum number of clients used by all our services combined did not breach 9k mark.
Our organization uses Azure P2 subscription for cache for the particular environment, which allows 15k connections.
I believe connection limit was not breached in this case.

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.19.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/10839664/redisson-3.19.4-SNAPSHOT.jar.zip)

**Comment by brijnkh** [comment]
Sure. Will let you know after testing. Thanks for the quick response again.

**Comment by brijnkh** [comment]
@mrniko While we are preparing environment, for the validation, can you please tell me, if we should check any logs during testing?
What have you fixed and in which direction shall we be checking during testing?

**Comment by mrniko** [comment]
I reduced amount of connections created in parallel. It's now 1. You don't need to check logs

**Comment by mrniko** [comment]
Did it help?

**Comment by brijnkh** [comment]
We could not perform testing against it.
Most probably it will happen next week

**Comment by brijnkh** [comment]
@mrniko we did not observe the issue after using the latest patch.
Is it possible to get the official release with the fix?
We are anyways planning to adopt 3.20.x. By any chance is this fix committed there?

**Comment by mrniko** [comment]
@brijnkh 

Thank you for confirmation. You can find the commit above.

**Comment by mrniko** [comment]
@zld12580 

Try to reduce connections amount established by Redisson. I might have a connections amount limit set by Redis vendor.
