### ISSUE TITLE
java.lang.IllegalStateException: None of slaves were synced

### ISSUE THREAD

**Issue by Hello629** [redisson/redisson#4899]
**Expected behavior**

**We are seeing below stack traces with a large count: 
Exception 1: 
org.redisson.client.RedisException: Unexpected exception while processing command    at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:276)    at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)    at org.redisson.RedissonObject.get(RedissonObject.java:82)    at org.redisson.RedissonLock.unlock(RedissonLock.java:306)
**### Caused by: java.lang.IllegalStateException: None of slaves were synced**

Exception 2:
"**### org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 45000ms.** Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.\n\tat org.redisson.pubsub.PublishSubscribeService.lambda$timeout$7(PublishSubscribeService.java:241)\n\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)\n\tat io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)\n\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)\n\tat io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)\n\tat io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:750)\n"}

**

**We are not able to reproduce this in less load but in production, we see a considerable number of exceptions after upgrading to 3.17.7 **

Redis Engine Version
**5.0.6** 

Redisson Version
**3.17.7**

Redisson Configuration:
**cluster.scan.interval.timeoutMillis=30000
connection.max.pool.size=1000
connection.max.retry.count=10
connection.min.idle.size=100
connection.retry.delayMillis=1500
connection.timeoutMillis=60000
idle.connection.timeoutMillis=10000
lock.timeoutMillis=10000
op.timeoutMillis=30000
subscription.connection.max.pool.size=50
subscription.per.connection.size=10**

We are still working on the replicable scenario to provide but can you guys suggest any quick settings or suggestions?

**Comment by Hello629** [comment]
Duplicate of https://github.com/redisson/redisson/issues/4822
