### ISSUE TITLE
Unable to init enough connections amount! Only 0 of 1 were initialized.

### ISSUE THREAD

**Issue by alexworkgit** [redisson/redisson#4902]
I am testing against 3 servers redis+sentinel, connecting redisson from pc, it connect to all servers, then iam start drop-script, it drop server by cycle for 5minutes. After some time i catch error 
"Unable to init enough connections amount! Only 0 of 1 were initialized.", i am stop drop-script, all servers is going up, but error steel present.

Problem if ClientConnectionsEntry is failed+freezed(MANAGED/SYSTEM) and after sentinel return slave is up for this ClientConnectionsEntry, section never reconnected and all time is exception. 

Bottom described calls from checkSlavesChange with my comments, where i think has problem.
```
SentinelConnectionManager.java
    private CompletionStage<Void> checkSlavesChange(SentinelServersConfig cfg, RedisConnection connection) {
	...
        return addSlave(slaveAddr).whenComplete((r, e) -> {

SentinelConnectionManager.java
    private CompletableFuture<Void> addSlave(RedisURI uri) {
	...
	CompletableFuture<Boolean> f = entry.slaveUpAsync(uri, FreezeReason.MANAGER);

MasterSlaveEntry.java
    public CompletableFuture<Boolean> slaveUpAsync(RedisURI address, FreezeReason freezeReason) {
        return slaveBalancer.unfreezeAsync(address, freezeReason);
    }

LoadBalancerManager.java
    public CompletableFuture<Boolean> unfreezeAsync(ClientConnectionsEntry entry, FreezeReason freezeReason) {
	...
        futures.add(slaveConnectionPool.initConnections(entry));

ConnectionPool.java
    public CompletableFuture<Void> initConnections(ClientConnectionsEntry entry) {
        return initConnections(entry, false);
    }

ConnectionPool.java
    private CompletableFuture<Void> initConnections(ClientConnectionsEntry entry, boolean checkFreezed) {
	...
        createConnection(checkFreezed, requests, entry, initPromise, minimumIdleSize, initializedConnections);

ConnectionPool.java
    private void createConnection(boolean checkFreezed, AtomicInteger requests, ClientConnectionsEntry entry,
                                  CompletableFuture<Void> initPromise, int minimumIdleSize, AtomicInteger initializedConnections) {

        if ((checkFreezed && entry.isFreezed()) || !tryAcquireConnection(entry)) {

ConnectionPool.java
    protected boolean tryAcquireConnection(ClientConnectionsEntry entry) {
        if (entry.getNodeType() == NodeType.SLAVE && entry.isFailed()) {
            checkForReconnect(entry, null);
            return false;
        }
        return true;
    }

ConnectionPool.java
    private void checkForReconnect(ClientConnectionsEntry entry, Throwable cause) {
        masterSlaveEntry.slaveDownAsync(entry, FreezeReason.RECONNECT).thenAccept(r -> {
            if (r) {
                log.error("slave {} has been disconnected after {} ms interval since moment of the first failed connection",
                    entry.getClient().getAddr(), config.getFailedSlaveCheckInterval(), cause);
                scheduleCheck(entry);
            }
        });
    }

MasterSlaveEntry.java
    public CompletableFuture<Boolean> slaveDownAsync(ClientConnectionsEntry entry, FreezeReason freezeReason) {
        ClientConnectionsEntry e = slaveBalancer.freeze(entry, freezeReason);

LoadBalancerManager.java
    
    // freezeReason = RECONNECT 
    // connectionEntry.getFreezeReason() == MANAGER
    
    @SuppressWarnings("BooleanExpressionComplexity")
    public ClientConnectionsEntry freeze(ClientConnectionsEntry connectionEntry, FreezeReason freezeReason) {	
        if (connectionEntry == null || (connectionEntry.isFailed() 
                && connectionEntry.getFreezeReason() == FreezeReason.RECONNECT
                    && freezeReason == FreezeReason.RECONNECT)) {
            return null;
        }

        synchronized (connectionEntry) {
            if (connectionEntry.isFreezed()) {
                return null;				// return this because section is already freezed.
            }

            // only RECONNECT freeze reason could be replaced
            if (connectionEntry.getFreezeReason() == null
                    || connectionEntry.getFreezeReason() == FreezeReason.RECONNECT
                        || (freezeReason == FreezeReason.MANAGER 
                                && connectionEntry.getFreezeReason() != FreezeReason.MANAGER 
                                    && connectionEntry.getNodeType() == NodeType.SLAVE)) {
                connectionEntry.setFreezeReason(freezeReason);
                return connectionEntry;
            }
        }

        return connectionEntry;
    }

MasterSlaveEntry.java
   public CompletableFuture<Boolean> slaveDownAsync(ClientConnectionsEntry entry, FreezeReason freezeReason) {
        ClientConnectionsEntry e = slaveBalancer.freeze(entry, freezeReason);
        if (e == null) { 					// e = null return false
            return CompletableFuture.completedFuture(false); 
        }

ConnectionPool.java
    private void checkForReconnect(ClientConnectionsEntry entry, Throwable cause) {
        masterSlaveEntry.slaveDownAsync(entry, FreezeReason.RECONNECT).thenAccept(r -> {
            if (r) {			// r is false, and reconnect not schedule and error loop after next sentinel request.
                log.error("slave {} has been disconnected after {} ms interval since moment of the first failed connection",
                    entry.getClient().getAddr(), config.getFailedSlaveCheckInterval(), cause);
                scheduleCheck(entry);
            }
        });
    }

and then upper throw exception.
```
One stack trace
```
2023-03-02 15:00:40,711 ERROR org.redisson.connection.balancer.LoadBalancerManager [redisson-netty-2-1] Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:52:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:66:queue:0, freezeReason=MANAGER, client=[addr=redis://172.18.20.167:6379], nodeType=SLAVE, firstFail=1677750955534]
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 1 were initialized. Server: 172.18.20.167/172.18.20.167:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
	at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1321)
	at java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2238)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:197)
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:122)
	at org.redisson.connection.MasterSlaveEntry.slaveUpAsync(MasterSlaveEntry.java:467)
	at org.redisson.connection.SentinelConnectionManager.addSlave(SentinelConnectionManager.java:595)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$16(SentinelConnectionManager.java:470)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at org.redisson.connection.SentinelConnectionManager.lambda$checkSlavesChange$22(SentinelConnectionManager.java:458)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:470)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:464)
	at org.redisson.client.handler.CommandDecoder.decodeResult(CommandDecoder.java:453)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:447)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```
Full debug log with all exceptions from start app to error.

[app.log](https://github.com/redisson/redisson/files/10870567/app.log)

**Redis version**
6.2.6
**Redisson version**
3.19.3

**Steps to reproduce or test case**

Application.java
```
package com.test.appclean;

import org.redisson.Redisson;
import org.redisson.api.RedissonClient;
import org.redisson.config.Config;
import org.redisson.config.SentinelServersConfig;
import org.redisson.connection.balancer.LoadBalancer;
import org.redisson.connection.balancer.RoundRobinLoadBalancer;

import java.util.Arrays;
import java.util.List;


public class Application {
    /**
     * Entry point.
     *
     * @param args agrs
     */
    public static void main(final String[] args) throws InterruptedException {
        System.out.println("Hello world");

        RedissonClient cache = createRedissonCache();
        //RedissonClient database = createRedissonDatabase();

        Thread.sleep(7 * 24 * 60 * 60 * 1000);
    }

    public static RedissonClient createRedissonCache() {

        String redisDbName = "cacheMaster";
        String redisAddresses = "redis://172.18.20.166:26379,redis://172.18.20.167:26379,redis://172.18.20.168:26379";

        List<String> hosts = Arrays.asList(redisAddresses.split(","));

        Config config = new Config();

        SentinelServersConfig connect = config.useSentinelServers().setMasterName(redisDbName);
        if (hosts.size() < 2) connect.setCheckSentinelsList(false);
        LoadBalancer loadBalancer = new RoundRobinLoadBalancer();

        connect.setLoadBalancer(loadBalancer);
        connect.setSentinelAddresses(hosts);
        connect.setMasterConnectionMinimumIdleSize(1);
        connect.setSlaveConnectionMinimumIdleSize(1);

        RedissonClient client = Redisson.create(config);
        return client;
    }

}

```

dropscript.sh:
```
#!/bin/sh

trap ctrl_c INT
function ctrl_c() {
    echo "Ctrl + C happened"
    exit
}

HOSTS='172.18.20.166 172.18.20.167 172.18.20.168'

while [ 1 = 1 ]; do
  for v in $HOSTS; do
    echo "$(date +"%T") Go down host $v"
    ssh root@$v 'ip link set eth0 down && sleep 5m && ip link set eth0 up'
    echo "$(date +"%T") Go up host $v "
    #sleep 1m
   # exit
  done
  echo "Wait for next cycle 10s"
  sleep 10s
done
```
```
[root@localhost test]# ./dropmanager.sh
14:34:00 Go down host 172.18.20.166
14:39:40 Go up host 172.18.20.166
14:39:40 Go down host 172.18.20.167
14:45:18 Go up host 172.18.20.167
14:45:18 Go down host 172.18.20.168
14:50:19 Go up host 172.18.20.168
Wait for next cycle 10s
14:50:29 Go down host 172.18.20.166
14:55:29 Go up host 172.18.20.166
14:55:29 Go down host 172.18.20.167
^CKilled by signal 2.
Ctrl + C happened
[root@localhost test]#
```

**Comment by mrniko** [comment]
>at 1078 line: Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: 172.18.20.167/172.18.20.167:26379

connection is still can't be established. I don't see that ConnectionWatchdog able to reconnect channel of this node. There is no "... connected to ..." message after this error.

**Comment by mrniko** [comment]
> org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:194)
	... 38 common frames omitted

Can expand stacktraces?

**Comment by alexworkgit** [comment]
I am build app with your [redisson-3.20.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/10871970/redisson-3.20.1-SNAPSHOT.jar.zip) and test 2 hours. Usually this error appeared within 15-20 minutes or 4-5 server drops, but with 3.20.1 no errors.

[app.log](https://github.com/redisson/redisson/files/10881005/app.log)

```
[root@localhost test]# ./dropmanager.sh13:11:38 Go down host 172.18.20.166
13:17:17 Go up host 172.18.20.166
13:17:17 Go down host 172.18.20.167
13:22:56 Go up host 172.18.20.167
13:22:56 Go down host 172.18.20.168
13:27:56 Go up host 172.18.20.168
Wait for next cycle 10s
13:28:06 Go down host 172.18.20.166
13:33:06 Go up host 172.18.20.166
13:33:06 Go down host 172.18.20.167
13:38:46 Go up host 172.18.20.167
13:38:46 Go down host 172.18.20.168
13:43:46 Go up host 172.18.20.168
Wait for next cycle 10s
13:43:56 Go down host 172.18.20.166
13:49:34 Go up host 172.18.20.166
13:49:34 Go down host 172.18.20.167
13:54:34 Go up host 172.18.20.167
13:54:34 Go down host 172.18.20.168
13:59:34 Go up host 172.18.20.168
Wait for next cycle 10s
13:59:44 Go down host 172.18.20.166
14:05:24 Go up host 172.18.20.166
14:05:24 Go down host 172.18.20.167
14:11:03 Go up host 172.18.20.167
14:11:03 Go down host 172.18.20.168
14:16:03 Go up host 172.18.20.168
Wait for next cycle 10s
14:16:13 Go down host 172.18.20.166
14:21:14 Go up host 172.18.20.166
14:21:14 Go down host 172.18.20.167
14:26:53 Go up host 172.18.20.167
14:26:53 Go down host 172.18.20.168
14:31:54 Go up host 172.18.20.168
Wait for next cycle 10s
14:32:04 Go down host 172.18.20.166
14:37:04 Go up host 172.18.20.166
14:37:04 Go down host 172.18.20.167
14:42:44 Go up host 172.18.20.167
14:42:44 Go down host 172.18.20.168
^[314:47:44 Go up host 172.18.20.168
Wait for next cycle 10s
14:47:54 Go down host 172.18.20.166
14:52:54 Go up host 172.18.20.166
14:52:54 Go down host 172.18.20.167
14:58:34 Go up host 172.18.20.167
14:58:34 Go down host 172.18.20.168
^CKilled by signal 2.
Ctrl + C happened
[root@localhost test]#
```

**Comment by mrniko** [comment]
Great! Thanks for report and testing.

**Comment by Lc-1995** [comment]
> 请尝试附加版本。
> 
> [redisson-3.20.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/10871970/redisson-3.20.1-SNAPSHOT.jar.zip)

Can You update to maven repository?

**Comment by mrniko** [comment]
@Lc-1995 

I'm afraid no.

**Comment by Lc-1995** [comment]
> @Lc-1995
> 
> I'm afraid no.

why？So how should this problem be solved？

**Comment by mrniko** [comment]
@CyrilDevOps 

It's done.
