### ISSUE TITLE
Getting java.lang.ClassNotFoundException: org.apache.catalina.session.ManagerBase upon adding Redisson jars

### ISSUE THREAD

**Issue by cverma** [redisson/redisson#4916]
Hi,

I have an existing Java(using openj9 version 1.8.0_222) application which runs on Apache Tomcat 8.
I am trying to add Redisson jar to replicate the Tomcat Session in Redis.

1. I have downloaded the redisson-all-3.20.0.jar and redisson-tomcat-8-3.20.0.jar and put them in Tomcat's lib folder.
2. I have updated the Tomcat's context.xml file to include the RedissonSessionManager, as below:
<Manager className="org.redisson.tomcat.RedissonSessionManager"
    			configPath="${catalina.base}/conf/redisson.yml" 
    			readMode="REDIS" updateMode="DEFAULT" broadcastSessionEvents="true"
    			keyPrefix="" />
3. I have also made the redisson.yml file with redis config information and put it in the Tomcat's catalina base's conf folder.

I built the project and on starting the Tomcat server, it is giving me error on ManagerBase class not found, as below:
Caused by: java.lang.NoClassDefFoundError: org.apache.catalina.session.ManagerBase
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:389)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:933)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:116)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1203)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1476)
	at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:537)
	at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:475)
	at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:738)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:310)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:108)

I have made the changes as per the readme files, as described above, but not sure what else could be the reason for the above issue.
Can you please take a look at it?

Thanks,

**Comment by mrniko** [comment]
Unable to reproduce it
