### ISSUE TITLE
Redisson 3.17.7 in Sentinel Mode Locks hang forever

### ISSUE THREAD

**Issue by piyush-harness** [redisson/redisson#4917]
Hi,

We recently upgraded our Redisson version from 3.13.3. to 3.17.7 and facing a weird Locking behavior in Redis Sentinel mode only, Standalone and Cluster Mode are working just fine. 

We are running a background thread which processing records from database and acquires distributed lock using lock.tryLock method. The application works fine for sometime but after 1-2 hours this background thread gets stuck on acquiring the lock and its hanged forever and its not even respecting the waitTime or leaseTime.

This issue is only observed is 3.17.7 version and Redis running in Sentinel mode.
In 3.13.3 this was working as expected as expected for all Redis modes.

We have not noticed any failover activity on server side when this issue happens. I think there's some regression that got introduced. 

Is there a solution to this problem?
Will upgrading to 3.18.1 solve this problem @mrniko ? 

P.S: We cannot upgrade beyond 3.18.1 because later version have introduced Kryo 5 as compile time dependency and we are running on Kryo 4.

Thanks.

Locking Code:
---------------
> RLock lock = client.getLock(name); 
boolean locked = lock.tryLock(0, timeout.toMillis(), TimeUnit.MILLISECONDS); 
      if (locked) { 
        log.debug("Lock acquired on {} for timeout {}", name, timeout); 
        return RedisAcquiredLock.builder().lock(lock).build(); 
 }

Unlocking Code:
-----------------
>  if (lock != null && lock.isHeldByCurrentThread()) {
      lock.unlock();
    }

Thread Dump:
--------------
> [outbox-poll-service-thread-NextGenManager](https://jstack.review/#tda_2_threaddetails_0x00007fc9101f3000)awaiting notification on [ [0x0000000709c24688](https://jstack.review/#tda_2_sync_0x0000000709c24688) ]
at jdk.internal.misc.Unsafe.park(java.base@11.0.15/Native Method)
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.15/LockSupport.java:194)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.15/CompletableFuture.java:1796)
at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.15/ForkJoinPool.java:3128)
at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.15/CompletableFuture.java:1823)
at java.util.concurrent.CompletableFuture.get(java.base@11.0.15/CompletableFuture.java:1998)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:109)
at org.redisson.RedissonObject.get(RedissonObject.java:82)
at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:144)
at org.redisson.RedissonLock.tryLock(RedissonLock.java:218)
at io.harness.lock.redis.RedisPersistentLocker.acquireLock(RedisPersistentLocker.java:65)
at io.harness.lock.redis.RedisPersistentLocker.tryToAcquireLock(RedisPersistentLocker.java:103)
at io.harness.outbox.OutboxEventPollJob.pollAndHandleOutboxEvents(OutboxEventPollJob.java:74)
at io.harness.outbox.OutboxEventPollJob.run(OutboxEventPollJob.java:65)
at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.15/Executors.java:515)
at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

**Comment by mrniko** [comment]
> We cannot upgrade beyond 3.18.1 because later version have introduced Kryo 5 as compile time dependency and we are running on Kryo 4.

You can use `org.redisson.codec.KryoCodec` which is Kryo 4 compatible.

**Comment by piyush-harness** [comment]
Thanks @mrniko Does below fix applies to sentinel mode as well? 

> "Fixed - RLock can only be obtained by single redisson node if None of slaves were synced error occurred"

**Comment by kapilgarg1996** [comment]
@mrniko @piyush-harness is there any update on the above ?

**Comment by mrniko** [comment]
Can you share the reproducer?

**Comment by mrniko** [comment]
Unable to reproduce with the latest version.
