### ISSUE TITLE
CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by yarivMobitti** [redisson/redisson#4927]
Hi, I'm receiving an error that says 'CROSSSLOT Keys in request don't hash to the same slot' and I'm not sure why. Here's my Radisson configuration:

            Config config = new Config();
            config.setNettyThreads(128);
            ClusterServersConfig clusterConfig = config.useClusterServers();
            clusterConfig.setTimeout(5000);
            clusterConfig.setSlaveConnectionPoolSize(128);
            clusterConfig.setMasterConnectionPoolSize(128);
            clusterConfig.addNodeAddress(memoryDBParams.getAddress());

And here's the operation that's causing the issue:

          RTransaction transaction = client.createTransaction(TransactionOptions.defaults());
          transaction.getMap(mapName).delete();
          transaction.getMap(mapName).putAll(map);
          transaction.commit();

Radisson version:  3.17.5
Redis: Memory db in aws (cluster mode )

     
 Can you help me figure out what might be causing this error?

exception:

at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at filters.CorsFilter.doFilter(CorsFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at filters.ErrorHandleFilter.doFilter(ErrorHandleFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisException: CROSSSLOT Keys in request don't    CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x7e3d7560, L:/10.1.40.10:55246 - R:10.1.12.15/10.1.12.15:6379] command: (EXEC), promise: java.util.concurrent.CompletableFuture@353f8e03[Not completed], params: []
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
        at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:271)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

**Comment by mrniko** [comment]
Transactions aren't compatible with Redis cluster setup

**Comment by yarivMobitti** [comment]
Could you please explain the correct way to do it with cluster mode? How can I run more than one operation atomically? In this case, I need to delete and putAll. Is there an available function in Redisson that simply replaces the value of a key? (in this case my map)

**Comment by mrniko** [comment]
@yarivMobitti 

I have just test your case. Unable to reproduce the issue using the code below in cluster mode.

```java
        RTransaction transaction = redisson.createTransaction(TransactionOptions.defaults());
        transaction.getMap("test1").delete();
        Map<String, String> map = new HashMap<>();
        map.put("1", "1");
        map.put("2", "2");
        transaction.getMap("test1").putAll(map);
        transaction.commit();
```

**Comment by supportMobitti** [comment]
@mrniko hi
any comment about this topic ?
thanks

**Comment by mrniko** [comment]
Hi @supportMobitti

Can you share the code to reproduce the issue?

**Comment by supportMobitti** [comment]
Hi, back to this issue

i guess im not doing anything special, you can see the code and more details below:
Redis version: 6.2 (memory db on aws), 1 shards, 2 nodes
Redisson version: 3.17.5

`Config config = new Config();
		ClusterServersConfig clusterConfig = config.useClusterServers();
		clusterConfig.setTimeout(5000);
		clusterConfig.setSlaveConnectionPoolSize(128);
		clusterConfig.setMasterConnectionPoolSize(128);
		clusterConfig.addNodeAddress("myAddress");
		client = Redisson.create(config);

		Set<Object> mySet = new HashSet<>();
		mySet.add(1);
		mySet.add(2);
		mySet.add(3);
		
		RTransaction transaction = client.createTransaction(TransactionOptions.defaults());
		transaction.getSet("mySetName").delete();
		transaction.getSet("mySetName").addAll(mySet);
		transaction.commit();`

**Comment by supportMobitti** [comment]
Hi, back to this issue

i guess im not doing anything special, you can see the code and more details below:
Redis version: 6.2 (memory db on aws), 1 shards, 2 nodes
Redisson version: 3.17.5


 Config config = new Config();
		ClusterServersConfig clusterConfig = config.useClusterServers();
clusterConfig.setTimeout(5000);
clusterConfig.setSlaveConnectionPoolSize(128);
		clusterConfig.setMasterConnectionPoolSize(128);
		clusterConfig.addNodeAddress("myAddress");
		client = Redisson.create(config);
		Set<Object> mySet = new HashSet<>();
		mySet.add(1);
		mySet.add(2);
		mySet.add(3);
		RTransaction transaction = client.createTransaction(TransactionOptions.defaults());
		transaction.getSet("mySetName").delete();
		transaction.getSet("mySetName").addAll(mySet);
		transaction.commit();

**Comment by mrniko** [comment]
@supportMobitti 

Thanks for the code. It works find with the latest version.
