### ISSUE TITLE
Redisson map (spring boot cache) aren't working after elasticache security update 

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#4940]
We had to apply aws elasticache security update on our redis server,
on a cluster redis (2 shards of 2 nodes (writer+replica)) and on a replicated redis (writer + 2 replica)
map doesn't seem to work anymore after update even if there was no more low level 'connection error' message anymore.

I had to recycle our application to stop that problem.

Looking at aws cloudwatch mertrics we had connections on each nodes after the patch update.

**Expected behavior**
No error at all, redisson should be able to acces redis normally after the security update.

**Actual behavior**
 org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@4322e2b4[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null],

**Steps to reproduce or test case**
Don't know if it is reproductible, it was an AWS security update, it was applied by AWS on the replica, then there was a failover of the writer nodes to apply it to the latest nodes.

**Redis version**
6.2.6

**Redisson version**
3.20.1

**Redisson configuration**
replicatedServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: ${REDIS_PERMS_PASSWORD}
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "rediss://....cache.amazonaws.com:6379"
    - "rediss://....cache.amazonaws.com:6379"
    - "rediss://....cache.amazonaws.com:6379"
  scanInterval: 1000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"

clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: ${REDIS_CLOSURE_PASSWORD}
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "rediss://clustercfg.....cache.amazonaws.com:6379"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"

**Comment by CyrilDevOps** [comment]
Only messages that seems not normal were like : 

 message: Unable to change master to ...cache.amazonaws.com/a.b.c.d:6379
     stack_trace: java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 2 of 24 were initialized. Redis server: ....cache.amazonaws.com/a.b.c.d:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:155)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:318)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:277)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.client.RedisClient$1$1.run(RedisClient.java:248)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 2 of 24 were initialized. Redis server: ....cache.amazonaws.com/a.b.c.d:6379
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:154)
	... 19 common frames omitted
Caused by: java.util.concurrent.CompletionException: org.redisson.client.RedisException: ERR max number of clients reached. channel: [id: 0xf4ce2e3f, L:/10a.b.c.d:58484 - R:....cache.amazonaws.com/a.b.c.d:6379] command: (AUTH), params: (password masked)
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:87)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:380)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	... 4 common frames omitted
Caused by: org.redisson.client.RedisException: ERR max number of clients reached. channel: [id: 0xf4ce2e3f, L:/10a.b.c.d:58484 - R:....cache.amazonaws.com/a.b.c.d:6379] command: (AUTH), params: (password masked)
	... 32 common frames omitted

     thread_name: redisson-netty-5-15 

Our normal number of connections on the replicated is around 250 per node.
Looking at cloudwatch, I see variation during the patching but nothing crazy abnormal, nothing hitting the limit of redis (65k I think).

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.20.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11108413/redisson-3.20.2-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Updated.

[redisson-3.20.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11109623/redisson-3.20.2-SNAPSHOT.jar.zip)

**Comment by CyrilDevOps** [comment]
Thanks, I will try to test it,
looking with our dev team how I can include a jar directly instead of pulling from maven in our cicd
and trying to reproduce the problem in our dev with reboot/failover now that it is already fully patched.

**Comment by CyrilDevOps** [comment]
any way/pattern I should play with my nodes in AWS to trigger redisson to reproduce the problem ?

**Comment by mrniko** [comment]
You can trigger failover manually on AWS Elasticache https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/AutoFailover.html#auto-failover-test

**Comment by CyrilDevOps** [comment]
I was able to run some container with redisson 3.20.1 and other with the 3.20.2 snapshot,
after playing with redis node (delete/create, reboot, failover ...) until I seems to have make the problem
again, the containers with the redisson 3.20.2 snapshot seems to be ok (not logging any error),
and the container with 3.20.1 where logging the access error.
I did test with the replicated redis, not the clustered one.

**Comment by mrniko** [comment]
Thanks for testing.

Resolved in https://github.com/redisson/redisson/issues/4716

**Comment by mrniko** [comment]
@CyrilDevOps 

The end of this month.

**Comment by CyrilDevOps** [comment]
This is fixed in the newest release ? 3.21.0 ?

**Comment by mrniko** [comment]
Yes.
