### ISSUE TITLE
ClassCastException in RedissonConnection.

### ISSUE THREAD

**Issue by ReasonH** [redisson/redisson#4946]
I use Redisson with Spring boot application.
```java
    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setHashKeySerializer(new StringRedisSerializer());
        redisTemplate.setHashValueSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        redisTemplate.setEnableTransactionSupport(true);
        return redisTemplate;
    }
```

When I call this method
```java
public long increment(String combinedKey, long delta) {
    redisTemplate.getConnectionFactory().getConnection().incrBy(combinedKey.getBytes(), delta);
}
```

RedissonConnection throw exception sometimes.
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at org.redisson.spring.data.connection.RedissonConnection.incrBy(RedissonConnection.java:583)
```

Maybe the problem is happening with this code.
```java
    public Long incrBy(byte[] key, long value) {
        return (Long)this.write(key, StringCodec.INSTANCE, RedisCommands.INCRBY, key, value);
    }
```

If I already set a cache, these exception does not occur. 
Exceptions are occurring **intermittently(not always)**. 
I expect that sequence with delta value is set based on 0 in normal case, so it should be able to be cast normally.
What is the problem?

**Comment by ReasonH** [comment]
Additional commnet.
Although RedissonConnection made an exception, it was confirmed that the value was set normally in the cache.
It's just that an exception occurs in the process of type casting the result value.

**Comment by mrniko** [comment]
Which Redisson version?

**Comment by ReasonH** [comment]
Current, I use 3.17.5

**Comment by mrniko** [comment]
You need to update to 3.19.2 or higher

> Fixed - command replies don't match if exception is thrown in CommandEncoder

**Comment by ReasonH** [comment]
Ok, I'll test with fixed version. Thanks a lot!

**Comment by ReasonH** [comment]
I have update 3.20.1. I'm using spring-boot 2.7.1
Here is my pom.xml. I exclude redisson-spring-data-30, and add redisson-spring-data-27 (for compitability with spring-boot)
```
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>${redisson.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.redisson</groupId>
                    <artifactId>redisson-spring-data-30</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-data-27</artifactId>
            <version>${redisson.version}</version>
        </dependency>
```

Also, I fixed my code to use RedissonAtomicLong instead of redissonConnection.
But I still face this classCastException.

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at java.base/java.util.stream.Collectors.lambda$summarizingLong$72(Unknown Source)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.redisson.spring.data.connection.RedissonClusterConnection.del(RedissonClusterConnection.java:505)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.lambda$remove$3(DefaultRedisCacheWriter.java:195)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.execute(DefaultRedisCacheWriter.java:308)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.remove(DefaultRedisCacheWriter.java:195)
	at org.springframework.data.redis.cache.RedisCache.evict(RedisCache.java:200)
	at org.springframework.cache.transaction.TransactionAwareCacheDecorator$2.afterCommit(TransactionAwareCacheDecorator.java:121)
```

The exception rising only when Spring cahceManager evict cache. (after commit by transactionAware() option)
I current use redisson with CacheManager in some case.

**Comment by mrniko** [comment]
Can you share the code to reproduce it?

**Comment by ReasonH** [comment]
Here is my code sample.

### Case1
First. It didn't use `@Transactional`, just delete cache using by redisTemplate.

#### Caller
```java
@Service
@RequiredArgsConstructor
class ServiceImpl implements Service {

    private final RedisValueCacheRepository<Boolean> repository;

    @Override
    public void remove(AdminRequest request) {
        repository.remove(request.getKey());
    }
}
```
#### Callee
```java
@Slf4j
@RequiredArgsConstructor
@Repository
public class RedisValueCacheRepository<V> {

    private final RedisTemplate<String, V> redisTemplate;
    public void remove(String cacheName) {
        redisTemplate.delete(cacheName);
    }
}
```

Sometimes, I got exception such as
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at java.base/java.util.stream.Collectors.lambda$summarizingLong$72(Unknown Source)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.redisson.spring.data.connection.RedissonClusterConnection.del(RedissonClusterConnection.java:505)
	at org.springframework.data.redis.core.RedisTemplate.lambda$delete$3(RedisTemplate.java:723)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.delete(RedisTemplate.java:723)
```

### Case2
The caller is @Transactional, also I use both redisTemplate and Spring cache abstraction (@CacheEvict) together.

First, the @Transactional method call method for clearing cache.
```java
@Transactional
public void txService(AdminRequest request) {
        // other transaction process
        cacheService.foo(request.getKey(), request.getSubKeys());
        // etc...
}
```

next the `claerCache` method call delete cache logic internally.
```java
@Service
@RequiredArgsConstructor
class CacheService {
    private final TemplateCache<String> templateCache;
    private final AbstractionCache abstractionCache;

    public void clearCache(String key, String[] subKey) {    
        abstractionCache.evict(key);
        templateCache.deleteMulti(key, subKey);
    }
}
```
```java
@Service
class AbstractionCache {
    @Override
    @CacheEvict(cacheNames = TEMP_CACHE_NAME, key = "#key")
    public void evict(String key) {
    }
}
```
```java
@Service
class TemplateCache<V> {
    private final RedisTemplate<String, V> redisTemplate;

    public void deleteHashValues(String key, String[] subKeys) {
        if (keys.length == 0) {
            return;
        }
        HashOperations<String, String, V> hashOps = redisTemplate.opsForHash();
        hashOps.delete(key, subKeys);
    }
}
```

The case 2 throw exception. (hardly)
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at java.base/java.util.stream.Collectors.lambda$summarizingLong$72(Unknown Source)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.redisson.spring.data.connection.RedissonClusterConnection.del(RedissonClusterConnection.java:505)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.lambda$remove$3(DefaultRedisCacheWriter.java:195)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.execute(DefaultRedisCacheWriter.java:308)
	at org.springframework.data.redis.cache.DefaultRedisCacheWriter.remove(DefaultRedisCacheWriter.java:195)
	at org.springframework.data.redis.cache.RedisCache.evict(RedisCache.java:200)
	at org.springframework.cache.transaction.TransactionAwareCacheDecorator$2.afterCommit(TransactionAwareCacheDecorator.java:121)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCommit(TransactionSynchronizationUtils.java:135)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerAfterCommit(TransactionSynchronizationUtils.java:123)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCommit(AbstractPlatformTransactionManager.java:936)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:782)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
```

It's my RedisCacheConfig class

```java
@Configuration
@EnableCaching
public class RedisCacheConfig {

    @Value("${spring.redis.cluster.nodes}")
    private List<String> clusterNodes;

    @Bean
    public RedissonClient redissonClient() {
        int clusterSize = clusterNodes.size();
        Config config = new Config();
        config.setNettyThreads(64);
        config
                .useClusterServers()
                .setKeepAlive(true)
                .addNodeAddress(clusterNodes.toArray(new String[clusterSize]))
                .setReadMode(ReadMode.MASTER_SLAVE);
        return Redisson.create(config);
    }

    @Bean
    public RedissonConnectionFactory redisConnectionFactory(RedissonClient redissonClient) {
        return new RedissonConnectionFactory(redissonClient);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setHashKeySerializer(new StringRedisSerializer());
        redisTemplate.setHashValueSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        redisTemplate.setEnableTransactionSupport(true); // transaction support
        return redisTemplate;
    }

    @Bean
    public CacheManager redisCacheManager(RedissonConnectionFactory redisConnectionFactory) {
        return RedisCacheManager.builder(redisConnectionFactory)
                .cacheDefaults(redisCacheConfig())
                .withInitialCacheConfigurations(cacheKeyMap())
                .transactionAware() // transaction support
                .build();
    }

    private RedisCacheConfiguration redisCacheConfig() {
        GenericJackson2JsonRedisSerializer jsonRedisSerializer = new GenericJackson2JsonRedisSerializer();
        RedisSerializationContext.SerializationPair<Object> pair = RedisSerializationContext.SerializationPair.fromSerializer(jsonRedisSerializer);

        return RedisCacheConfiguration.defaultCacheConfig().serializeValuesWith(pair).disableCachingNullValues();
    }
    // omitted below
}
```

**Comment by ReasonH** [comment]
I got same exception when I use RedissonAtomicLong.
```java

@Slf4j
@RequiredArgsConstructor
@Repository
public class TemplateCache {
    private final RedissonClient redissonClient;
    public long increment(String cacheName, String key) {
        return redissonClient.getAtomicLong(cacheName).incrementAndGet();
    }
```

```java
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at org.redisson.RedissonAtomicLong.incrementAndGet(RedissonAtomicLong.java:132)
```

Is there a problem with the way I use RedissonClient, or the connection pooling setup?

**Comment by mrniko** [comment]
Unable to reproduce. Can you set `TRACE` logging level for `org.redisson` package and share the output?

**Comment by ReasonH** [comment]
Unfortunately, the we can't test this because of the schedule, so the we concluded turning off the the transaction support option temporarily.

If I go through this problem again, I will re-open the issue. Thanks for the help

**Comment by mrniko** [comment]
Unable to reproduce. Below is the test.

```java
@SpringJUnitConfig
@SpringBootTest(
        classes = RedissonApplication.class,
        properties = {
            "spring.redis.redisson.file=classpath:redisson.yaml",
            "spring.redis.timeout=10000"
        })
public class RedissonAutoConfigurationTest {

    @Autowired
    CacheService cacheService;
    @Autowired
    CacheService2 cacheService2;
    @Autowired
    private RedissonClient redisson;

    @Test
    public void testApp() {
        redisson.getKeys().flushall();

        for (int i = 1; i < 10; i++) {
            cacheService.put("k100"+i, "v");
            cacheService2.clearCache("k1002" + i, new String[] {"k2" + i, "k3" + i});
        }
    }
    
}

@Service
public class CacheService {

    @Autowired
    private RedisTemplate<String, Object> redisTemplate;

    @Transactional
    public void put(String key, String value) {
        ValueOperations<String, Object> valueOps = redisTemplate.opsForValue();
        valueOps.set(key, value);
    }

}

@Service
public class CacheService2 {

    @Autowired
    private RedisTemplate<String, Object> redisTemplate;

    @Autowired
    private CacheService3 cacheService3;

    public void clearCache(String key, String[] subKey) {
        cacheService3.evict(key);
        redisTemplate.opsForHash().delete(key, subKey);
    }

}

@Service
public class CacheService3 {

    @Autowired
    private RedisTemplate<String, Object> redisTemplate;

    @Autowired
    private RedissonClient redissonClient;

    @CacheEvict(cacheNames = "test", key = "#key")
    public void evict(String key) {
        System.out.println("evicted " + key);
    }

}

@SpringBootApplication
@Configuration
@EnableTransactionManagement
@EnableCaching
public class RedissonApplication {

    public static void main(String[] args) {
        SpringApplication.run(RedissonApplication.class, args);
    }

    @Bean
    public RedissonTransactionManager transactionManager(RedissonClient redisson) {
        return new RedissonTransactionManager(redisson);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setHashKeySerializer(new StringRedisSerializer());
        redisTemplate.setHashValueSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        redisTemplate.setEnableTransactionSupport(true); // transaction support
        return redisTemplate;
    }

    private RedisCacheConfiguration redisCacheConfig() {
        GenericJackson2JsonRedisSerializer jsonRedisSerializer = new GenericJackson2JsonRedisSerializer();
        RedisSerializationContext.SerializationPair<Object> pair = RedisSerializationContext.SerializationPair.fromSerializer(jsonRedisSerializer);

        return RedisCacheConfiguration.defaultCacheConfig().serializeValuesWith(pair).disableCachingNullValues();
    }

    @Bean
    public CacheManager redisCacheManager(RedissonConnectionFactory redisConnectionFactory) {
        return RedisCacheManager.builder(redisConnectionFactory)
                .cacheDefaults(redisCacheConfig())
                .transactionAware() // transaction support
                .build();
    }

}
