### ISSUE TITLE
     stack_trace: java.lang.NullPointerException: Cannot invoke "org.redisson.connection.ClientConnectionsEntry.getClient()" because "this.masterEntry" is null

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#4947]
**Expected behavior**
n/a

**Actual behavior**
     logger_name: io.netty.util.concurrent.AbstractEventExecutor
     message: A task raised an exception. Task: org.redisson.client.RedisClient$1$1@2a85aa51
     stack_trace: java.lang.NullPointerException: Cannot invoke "org.redisson.connection.ClientConnectionsEntry.getClient()" because "this.masterEntry" is null
        at org.redisson.connection.MasterSlaveEntry.getClient(MasterSlaveEntry.java:406)
        at org.redisson.connection.MasterSlaveConnectionManager.getNodeType(MasterSlaveConnectionManager.java:313)
        at org.redisson.connection.MasterSlaveConnectionManager.lambda$createRedisConfig$4(MasterSlaveConnectionManager.java:291)
        at org.redisson.client.RedisClient$1$1.run(RedisClient.java:244)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

**Steps to reproduce or test case**
One of our freshly started container logged this warning. we use a basic elastiache 2 replica 1 writer redis with redis 6.2.6

**Redis version**
6.2.6 and 6.0.5

**Redisson version**
3.20.1

**Redisson configuration**

**Comment by mrniko** [comment]
Fixed! Thanks for report
