### ISSUE TITLE
[version 3.12.2]WriteRedisConnectionException: Unable to write command into connection

### ISSUE THREAD

**Issue by cloudInspire** [redisson/redisson#4959]
my redission is 3.12.2, appears after a period of time

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://200.200.200.200:16379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@2052166695 [redisClient=[addr=redis://200.200.200.200:16379], channel=[id: 0x90c76170, L:0.0.0.0/0.0.0.0:51008], currentCommand=null], command: (HLEN), params: [PROECSSIONG_IMAGE] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:271) ~[redisson-3.12.2.jar!/:3.12.2]
	at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:59) ~[redisson-3.12.2.jar!/:3.12.2]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:156) ~[redisson-3.12.2.jar!/:3.12.2]
	at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:153) ~[redisson-3.12.2.jar!/:3.12.2]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:866) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1379) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:958) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	... 15 more

2、my code like this:
  RLock rlock = redissionClient.getLock(RedisKey.DUMP_LOCK);
  rlock.lock(10, TimeUnit.SECONDS);
  try{
       RMap<String, Object> oMap = redissionClient.getMap(RedisKey.PROCESSING_MAP);

     ....
   }catch(Execption e){
    log.error("");
  } finally{
      if(rlock.isLocked() && rlock.isHeldByCurrentThread()){
             rlock.unlock();
       }
    }

**Comment by cloudInspire** [comment]
the execption at  redissionClient.getMap(RedisKey.PROCESSING_MAP)

**Comment by mrniko** [comment]
> Caused by: java.nio.channels.ClosedChannelException

Define `pingConnectionInterval` setting to reconnect closed channels automatically

**Comment by cloudInspire** [comment]
I've set it up  pingConnectionInterval(3000)

**Comment by mrniko** [comment]
Also please review this section as well https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by mrniko** [comment]
did you try to reduce connections pool size?
