### ISSUE TITLE
Jdk11下，使用CompletableFuture.runAsync()方法异步调用redissonClient.getMap()，抛异常java.lang.ClassNotFoundException: org.redisson.RedissonReference

### ISSUE THREAD

**Issue by Jarvan-Song** [redisson/redisson#4965]
**Expected behavior**

return RMap which i need 

**Actual behavior**
org.redisson.client.RedisException: Unexpected exception while processing command
  at o.r.c.CommandAsyncService.convertException(CommandAsyncService.java:324)
  at o.r.c.CommandAsyncService.get(CommandAsyncService.java:121)
  at o.r.RedissonObject.get(RedissonObject.java:81)
  at o.r.RedissonMap.get(RedissonMap.java:639)
  at c.s.b.a.s.d.LemmaDispatcher.size(LemmaDispatcher.java:186)
  at c.s.b.a.s.d.r.LemmaRenderer.renderLemmaHead(LemmaRenderer.java:173)
  at c.s.b.a.s.d.r.LemmaRenderer.lambda$render$0(LemmaRenderer.java:150)
  at j.u.c.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
  at j.u.c.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
  at j.u.c.ForkJoinTask.doExec(ForkJoinTask.java:290)
  at j.u.c.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  at j.u.c.ForkJoinPool.scan(ForkJoinPool.java:1656)
  at j.u.c.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  at j.u.c.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused By: java.io.IOException: java.lang.ClassNotFoundException: org.redisson.RedissonReference
  at o.r.c.MarshallingCodec.lambda$new$0(MarshallingCodec.java:148)
  ...23 more
Caused By: java.lang.ClassNotFoundException: org.redisson.RedissonReference
  at j.i.l.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
  at j.i.l.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  at j.l.ClassLoader.loadClass(ClassLoader.java:522)
  at j.l.Class.forName(Class.java:398)
  at o.j.m.AbstractClassResolver.loadClass(AbstractClassResolver.java:129)
  at o.j.m.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110)
  at o.j.m.r.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1048)
  at o.j.m.r.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381)
  at o.j.m.r.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298)
  at o.j.m.r.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231)
  at o.j.m.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
  at o.r.c.MarshallingCodec.lambda$new$0(MarshallingCodec.java:146)
  at o.r.c.h.CommandDecoder.decode(CommandDecoder.java:358)
  at o.r.c.h.CommandDecoder.decodeCommand(CommandDecoder.java:177)
  at o.r.c.h.CommandDecoder.decode(CommandDecoder.java:116)
  at o.r.c.h.CommandDecoder.decode(CommandDecoder.java:101)
  at i.n.h.c.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
  at i.n.h.c.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
  at i.n.h.c.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
  at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  at i.n.c.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  at i.n.c.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  at i.n.c.n.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  at i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
  at i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  at i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  at i.n.c.n.NioEventLoop.run(NioEventLoop.java:493)
  at i.n.u.c.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  at i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at i.n.u.c.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at j.l.Thread.run(Thread.java:829)
**Steps to reproduce or test case**

**Redis version**
2.8
**Redisson version**
3.15.2
**Redisson configuration**
useSingleServer

**Comment by mrniko** [comment]
MarshallingCodec is deprecated. You need to use Kryo5Codec instead.

**Comment by Jarvan-Song** [comment]
> MarshallingCodec is deprecated. You need to use Kryo5Codec instead and latest Kryo lib.

thanks, as you guide, this problem is solved by update version to 3.19.0

**Comment by mrniko** [comment]
3.19.0 version uses Kryo5Codec by default
