### ISSUE TITLE
Replication config loops infinitely if all servers are down

### ISSUE THREAD

**Issue by lievenvaneeckhaute** [redisson/redisson#4968]
We use Redis as a cache in a replicated setup. It rarely happens, but sometimes all the redises are down. 
The cache is nice to have, but we'd like to skip the cache whenever it is not available.

**Expected behavior**
Whenever all servers are down and data is requested, we get an exception so we can catch it and continue without the cache.

**Actual behavior**
Infinite loop of this exception hanging our server:
ERROR [2023-04-18 06:53:02,752] [redisson-netty-5-42] [,,] org.redisson.connection.ReplicatedConnectionManager: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379

**Steps to reproduce or test case**
Setup a replicated redisson config and have a redis server running(1 server will also reproduce the issue) 
After the initial startup of the client, shutdown the redis server.
Trigger a redisson.get(key).
=> infinite loop with the above stack trace.

**Redis version**
5.0.14
**Redisson version**
3.19.3
**Redisson configuration**
replicatedServersConfig:
{
   "slaveConnectionMinimumIdleSize":24,
   "database":0,
   "loadBalancer":{
      "index":"-1"
   },
   "masterConnectionMinimumIdleSize":24,
   "connectTimeout":30000,
   "username":null,
   "subscriptionsPerConnection":5,
   "sslTruststore":null,
   "sslProtocols":null,
   "masterConnectionPoolSize":64,
   "nodeAddresses":[
      "redis://localhost:6379"
   ],
   "slaveConnectionPoolSize":64,
   "readMode":"SLAVE",
   "timeout":30000,
   "credentialsResolver":{
      "future":"java.util.concurrent.CompletableFuture@7a274521[Completed normally]"
   },
   "sslTruststorePassword":null,
   "pingConnectionInterval":30000,
   "nameMapper":{
   },
   "failedSlaveReconnectionInterval":3600,
   "subscriptionMode":"MASTER",
   "subscriptionConnectionMinimumIdleSize":1,
   "dnsMonitoringInterval":6000,
   "retryAttempts":3,
   "clientName":null,
   "sslEnableEndpointIdentification":true,
   "sslKeystore":null,
   "keepAlive":false,
   "tcpNoDelay":true,
   "log":"Logger[config]",
   "scanInterval":1000,
   "failedSlaveCheckInterval":60000,
   "subscriptionConnectionPoolSize":50,
   "idleConnectionTimeout":10000,
   "retryInterval":10000,
   "password":null,
   "sslProvider":"JDK",
   "sslKeystorePassword":null
}

**Comment by mrniko** [comment]
Unable to reproduce. Below is the test.

```java
        RedisProcess p1 = new RedisRunner().randomPort().randomDir().nosave().run();
        RedisProcess p2 = new RedisRunner().randomPort().randomDir().nosave().run();

        Config config = new Config();
        config.useReplicatedServers().addNodeAddress(p1.getRedisServerAddressAndPort(), p2.getRedisServerAddressAndPort());
        RedissonClient r = Redisson.create(config);

        p1.stop();
        p2.stop();

        Thread.sleep(5000);

        RMap<String, String> r2 = r.getMap("test");
        Assertions.assertThrows(RedisException.class, () -> {
            r2.get("1");
        });
```
