### ISSUE TITLE
Unable to write command into connection! 

### ISSUE THREAD

**Issue by shanmahesh** [redisson/redisson#4978]
Redisson version: 3.19.0
Elasticache: 1 Master and 1 Replica (replicationgroup)

 config
            .useReplicatedServers()
            .addNodeAddress(elastiCacheNode);

The first log shows IP switch and is unable to evict. Consecutive logs show unable to write. Need some help with the issue.
Application doesn't recover until restart.

2023-04-18 07:07:50.913  INFO 7 --- [sson-netty-2-23] o.r.c.ReplicatedConnectionManager        : Hostname: redis://XXX-elasticache.XXX.ng.0001.usw2.cache.amazonaws.com:6379 has changed IP from: xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379 to redis://100.67.53.161:6379
2023-04-18 07:07:51.921  INFO 7 --- [sson-netty-2-29] o.r.c.ReplicatedConnectionManager        : Hostname: redis://xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com:6379 has changed IP from: xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379 to redis://100.67.53.161:6379
2023-04-18 07:07:52.934  INFO 7 --- [sson-netty-2-10] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379
2023-04-18 07:07:52.952  INFO 7 --- [sson-netty-2-23] o.redisson.connection.MasterSlaveEntry   : master xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379 has changed to xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379
2023-04-18 07:07:52.952  INFO 7 --- [sson-netty-2-23] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379
2023-04-18 07:07:52.954  INFO 7 --- [sson-netty-2-28] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379
2023-04-18 07:07:52.955  INFO 7 --- [   redisson-3-3] o.r.pubsub.PublishSubscribeService       : listeners of 'redisson_countdownlatch__channel__{{lockMap}:QaQmBH1OqGQgoff4RL3ZxA:countdownlatch}' channel to '[addr=redis://xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com:6379]' have been resubscribed
2023-04-18 07:07:53.043  INFO 7 --- [sson-netty-2-10] o.r.connection.pool.SlaveConnectionPool  : 24 connections initialized for xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379
2023-04-18 07:07:54.966  INFO 7 --- [sson-netty-2-13] o.r.c.ReplicatedConnectionManager        : Hostname: redis://xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com:6379 has changed IP from: xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.161:6379 to redis://100.67.53.220:6379
2023-04-18 07:26:08.977 ERROR 7 --- [sson-netty-2-13] o.r.eviction.MapCacheEvictionTask        : Unable to evict elements for 'lockMap'

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@2065200276 [redisClient=[addr=redis://xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com:6379], channel=[id: 0x8eebdd4c, L:/100.67.0.177:52808 ! R:xxxxx-elasticache.xxxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379], currentCommand=null, usage=1], command: (EVAL), params: [if redis.call('setnx', KEYS[6], ARGV[4]) == 0 then return -1;end;redis.call('expire', KEYS[6], ARGV[3]); local expiredKeys1 = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); for i, key in ipairs(expiredKeys1) do local v = redis.call('hget', KEYS[1], key); if v ~= false then local t, val = struct.unpack('dLc0', v); local msg = struct.pack('Lc0Lc0', string.len(key), key, string.len(val), val); local listeners = redis.call('publish', KEYS[4], msg); if (listeners == 0) then break;end; end;end;for i=1, #expiredKeys1, 5000 do redis.call('zrem', KEYS[5], unpack(expiredKeys1, i, math.min(i+4999, table.getn(expiredKeys1)))); redis.call('zrem', KEYS[3], unpack(expiredKeys1, i, math.min(i+4999, table.getn(expiredKeys1)))); redis.call('zrem', KEYS[2], unpack(expiredKeys1, i, math.min(i+4999, table.getn(expiredKeys1)))); redis.call('hdel', KEYS[1], unpack(expiredKeys1, i, math.min(i+4999, table.getn(expiredKeys1)))); end; local expiredKeys2 = redis.call('zrangebyscore', KEYS[..., 6, lockMap, redisson__timeout__set:{lockMap}, redisson__idle__set:{lockMap}, redisson_map_cache_expired:{lockMap}, redisson__map_cache__last_access__set:{lockMap}, redisson__execute_task_once_latch:{lockMap}, 1681802764239, 100, ...] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:325) ~[redisson-3.19.0.jar!/:3.19.0]
	at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:169) ~[redisson-3.19.0.jar!/:3.19.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar!/:4.1.82.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[netty-transport-4.1.82.Final.jar!/:4.1.82.Final]

Consecutive logs with further transactions...

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1533719890 [redisClient=[addr=redis://xxxx-elasticache.xxxx.ng.0001.usw2.cache.amazonaws.com:6379], channel=[id: 0x57f3a125, L:/100.67.0.177:52890 ! R:xxxx-elasticache.xxxx.ng.0001.usw2.cache.amazonaws.com/100.67.53.220:6379], currentCommand=null, usage=1], command: (EVAL), params: [local insertable = false; local value = redis.call('hget', KEYS[1], ARGV[5]); if value == false then insertable = true; else local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[5]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], ARGV[5]); if expireIdle ~= false then expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate <= tonumber(ARGV[1]) then insertable = true; end; end; if insertable == true then if tonumber(ARGV[2]) > 0 then redis.call('zadd', KEYS[2], ARGV[2], ARGV[5]); else redis.call('zrem', KEYS[2], ARGV[5]); end; if tonumber(ARGV[3]) > 0 then redis.call('zadd', KEYS[3], ARGV[3], ARGV[5]); else redis.call('zrem', KEYS[3], ARGV[5]); end; local maxSize = tonumber(redis.call('hget', KEYS[7], 'max-size')); if maxSize ~= nil and maxSize ~= 0 then     local currentTime = tonumb..., 7, lockMap, redisson__timeout__set:{lockMap}, redisson__idle__set:{lockMap}, redisson_map_cache_created:{lockMap}, redisson__map_cache__last_access__set:{lockMap}, redisson_map_cache_removed:{lockMap}, {lockMap}:redisson_options, 1681804371240, ...] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:325)
	at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:169)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

**Comment by mrniko** [comment]
You need to increase retryAttemps interval to survive the failover.

**Comment by shanmahesh** [comment]
The situation/errors lasted for 4 hours, continued to get the same errors until the application was restarted. Looks like the connections didn't get reset after the failover.

**Comment by shanmahesh** [comment]
> The situation/errors lasted for 4 hours, continued to get the same errors until the application was restarted. Looks like the connections didn't get reset after the failover.

**Comment by hansh0801** [comment]
track

**Comment by mrniko** [comment]
Did you specify all Redis nodes? you shouldn't use replica hostname just a Redis hostnames

**Comment by shanmahesh** [comment]
> Did you specify all Redis nodes? you shouldn't use replica hostname just Redis hostnames

Yes I have one primary, so given only that on the config.

config
.useReplicatedServers()
.addNodeAddress(elastiCacheNode);

elastiCacheNode -> Primary Node

**Comment by mrniko** [comment]
You need to define all Redis hostnames you will find them in cluster redis nodes details.

**Comment by RafiyaB** [comment]
Is there any solution for this? Please let me know as i am getting repeated this issue.

**Comment by shanmahesh** [comment]
Hi, I just got this issue once, it didn't repeat again so for. I have added more observability to notify immediately to mitigate. Sorry couldn't help. Please post if you find a solution.
