### ISSUE TITLE
JndiRedissonFactory provides unhelpful error details when using YAML configuration

### ISSUE THREAD

**Issue by koczadly-uos** [redisson/redisson#4985]
**Expected behavior**
Error message specifying the cause

**Actual behavior**
Receive an error message/stacktrace which explains that the contents are not valid JSON (which of course they're not, it's YAML)

```text
24-Apr-2023 15:46:44.805 SEVERE [main] org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans Exception processing Global JNDI Resources
        javax.naming.NamingException: Can't parse yaml config C:\Tools\Tomcat\apache-tomcat-8.5.85 - Redis test/conf/redisson.yaml [Root exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'singleServerConfig': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"singleServerConfig:
  address: "redis://localhost:6379"
codec:
  class: "test""; line: 1, column: 19]]
                at org.redisson.JndiRedissonFactory.buildClient(JndiRedissonFactory.java:57)
                at org.redisson.JndiRedissonFactory.getObjectInstance(JndiRedissonFactory.java:45)
                at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:96)
                at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:331)
                at org.apache.naming.NamingContext.lookup(NamingContext.java:846)
                at org.apache.naming.NamingContext.lookup(NamingContext.java:157)
                at org.apache.naming.NamingContextBindingsEnumeration.nextElementInternal(NamingContextBindingsEnumeration.java:115)
                at org.apache.naming.NamingContextBindingsEnumeration.next(NamingContextBindingsEnumeration.java:69)
                at org.apache.naming.NamingContextBindingsEnumeration.next(NamingContextBindingsEnumeration.java:32)
                at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans(GlobalResourcesLifecycleListener.java:138)
                at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans(GlobalResourcesLifecycleListener.java:145)
                at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.createMBeans(GlobalResourcesLifecycleListener.java:112)
                at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.lifecycleEvent(GlobalResourcesLifecycleListener.java:87)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:787)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:695)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'singleServerConfig': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"singleServerConfig:
  address: "redis://localhost:6379"
codec:
  class: "test""; line: 1, column: 19]
                at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
                at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:759)
                at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3038)
                at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2079)
                at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:805)
                at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4817)
                at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723)
                at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
                at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
                at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:127)
                at org.redisson.config.Config.fromJSON(Config.java:605)
                at org.redisson.JndiRedissonFactory.buildClient(JndiRedissonFactory.java:55)
                ... 24 more
```

**Steps to reproduce or test case**
1. Create an invalid configuration (eg. codec class which doesn't exist)
2. Receive stacktrace

**Redis version**
N/A

**Redisson version**
3.20.1

**Redisson configuration**
```yaml
singleServerConfig:
  address: "redis://localhost:6379"
codec:
  class: "test"
```

**Comment by mrniko** [comment]
What if the file has a different extension?

**Comment by mrniko** [comment]
Fixed! Thanks for report
