### ISSUE TITLE
Getting NPE in RBucket get(), FSTCodec

### ISSUE THREAD

**Issue by AK-007** [redisson/redisson#4987]
I am using Redisson version: '3.12.3' in my Springboot Java project.

I am storing a Java object in Redisson RBucket [Elasticache] which implements Serializable class.

Whenever I delete some variable from the class, I start getting NPE in get() call, until the objects stored in Redis expires.
Also I changed another Enum field and removed one enum from it. That is also leading to issues, as I think apparently enum are being stored by the enum number. 

Attaching screenshots and stack trace for both.

1. Is there any way to make this backward compatible?
2. How should I proceed, should I use some different codec? 
3. Should I bump up Redisson version? 
4. Also separate question, which codec is the fastest in performance? Is it used by default in the latest Redisson 3.20.1?

![image (13)](https://user-images.githubusercontent.com/26346816/234114228-b322de3f-cd58-4e2f-8e22-d9fa446f9ecc.png)

`2023-04-25 02:07:27,005 [redisson-netty-2-15] [ - ] ERROR o.r.c.h.CommandDecoder - Unable to decode data
java.lang.ArrayIndexOutOfBoundsException: 2
	at org.nustaq.serialization.FSTObjectInput.instantiateEnum(FSTObjectInput.java:485) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:432) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:364) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.serializers.FSTArrayListSerializer.instantiate(FSTArrayListSerializer.java:63) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:501) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar:na]
	... 33 common frames omitted
Wrapped by: java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar:na]
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250) ~[redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368) [redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) [redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) [redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) [redisson-3.12.3.jar:3.12.3]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526) [netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275) [netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322) [netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]`

![image (12)](https://user-images.githubusercontent.com/26346816/234114217-f70e5ee3-3e67-487b-8001-330977e14f4c.png)

`2023-04-25 02:07:27,004 [redisson-netty-2-18] [ - ] ERROR o.r.c.h.CommandDecoder - Unable to decode data
java.lang.NullPointerException: null
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311) ~[fst-2.57.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245) ~[fst-2.57.jar:na]
	... 33 common frames omitted
Wrapped by: java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247) ~[fst-2.57.jar:na]
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250) ~[redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:368) [redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196) [redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134) [redisson-3.12.3.jar:3.12.3]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104) [redisson-3.12.3.jar:3.12.3]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526) [netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275) [netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322) [netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]`

**Comment by mrniko** [comment]
FSTCodec was deprecated. You need to use Kryo5Codec instead.

> Whenever I delete some variable from the class, I start getting NPE in get() call

It's better to use JacksonJsonCodec which support such modifications.

> Is it used by default in the latest Redisson 3.20.1?

Kryo5Codec is default codec with good performance.

**Comment by AK-007** [comment]
@mrniko does JacksonJsonCodec perform better than Kryo5Codec?
Does Kryo5Codec allow backward compatibility with fields [addition or removal]?
