### ISSUE TITLE
Even after updating the version to 3.19.3 we are still getting the below error, could you please check this? Thanks. 

### ISSUE THREAD

**Issue by sakethbalijepalli** [redisson/redisson#4996]
ERROR org.redisson.connection.DNSMonitor - Unable to resolve Redis URL
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'Redis-URL' and search domain query for configured domains failed as well: [us-west-2.compute.internal]
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1069)
at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1022)
at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:489)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:256)
at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:208)

**Comment by mrniko** [comment]
Try to define SequentialDnsAddressResolverFactory with concurrencyLevel = 4

Yaml config example:

```yaml
singleServerConfig:
  address: "redis://127.0.0.1:6311"
addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> 4
```

**Comment by sakethbalijepalli** [comment]
.setAddressResolverGroupFactory(new SequentialDnsAddressResolverFactory(4) 
So this?

**Comment by mrniko** [comment]
yes

**Comment by sakethbalijepalli** [comment]
Thanks. Will try and let you know.

**Comment by sakethbalijepalli** [comment]
Even after adding the setter we are still getting the same issue. @mrniko

**Comment by sakethbalijepalli** [comment]
@Bean(name = "redissonClient", destroyMethod = "shutdown")
public RedissonClient redisClient() {
Config config = new Config();
config.setNettyThreads(64).setAddressResolverGroupFactory(new SequentialDnsAddressResolverFactory(4))
.useSingleServer().setAddress(env.getProperty("redis.url"))
.setRetryAttempts(1).setConnectionPoolSize(64).setKeepAlive(true).setPingConnectionInterval(45000);
return Redisson.create(config);
}

This is the bean config we have.

**Comment by mrniko** [comment]
try SequentialDnsAddressResolverFactory with concurrencyLevel 1 or 2

**Comment by mrniko** [comment]
Also check if us-west-2.compute.internal is really can be resolved

**Comment by sakethbalijepalli** [comment]
Sure.
