### ISSUE TITLE
Command still hasn't been written into connection in SpringCloud Gateway

### ISSUE THREAD

**Issue by liqiang-fit2cloud** [redisson/redisson#4999]
Hi there,
we are using redisson in SpringCloud Gateway, but exceptions happened occasionally.
<img width="902" alt="image" src="https://user-images.githubusercontent.com/20766823/234843481-edfafb65-5501-45f4-bfe4-36b399f1a48b.png">
Gateway log:
`2023-04-24 12:22:28,764 [redisson-timer-5-1] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler ? - [612260a7-272756]  500 Server Error for HTTP GET "/performance/performance/report/content/ActiveThreadsChart/1d94f567-40dc-4971-9e55-730e016160a9"
org.springframework.data.redis.RedisSystemException: Command still hasn't been written into connection! Check connection with Redis node: 10.50.101.81/10.50.101.81:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1177950668 [redisClient=[addr=redis://10.50.101.81:6379], channel=[id: 0xa556b3ba, L:/172.30.10.7:41296 - R:10.50.101.81/10.50.101.81:6379], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@136334d9[Completed normally], command=(HMGET), params=[[115, 112, 114, 105, 110, 103, 58, 115, 101, 115, ...], [115, 101, 115, 115, 105, 111, 110, 65, 116, 116, ...]], codec=org.redisson.client.codec.ByteArrayCodec], usage=1], command: (EXISTS), params: [[115, 112, 114, 105, 110, 103, 58, 115, 101, 115, ...]] after 3 retry attempts
	at org.redisson.spring.data.connection.RedissonBaseReactive.lambda$read$5(RedissonBaseReactive.java:91)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ io.metersphere.gateway.filter.LoginFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/performance/performance/report/content/ActiveThreadsChart/1d94f567-40dc-4971-9e55-730e016160a9" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.redisson.spring.data.connection.RedissonBaseReactive.lambda$read$5(RedissonBaseReactive.java:91)
		at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3773)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.FluxCreate$BaseSink.error(FluxCreate.java:474)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:802)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.error(FluxCreate.java:747)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:237)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.error(FluxCreate.java:189)
		at org.redisson.reactive.CommandReactiveService.lambda$reactive$1(CommandReactiveService.java:60)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
		at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:572)
		at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:554)
		at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:542)
		at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:193)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
		at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:273)
		at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
		at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
		at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
		at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
		at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 10.50.101.81/10.50.101.81:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1177950668 [redisClient=[addr=redis://10.50.101.81:6379], channel=[id: 0xa556b3ba, L:/172.30.10.7:41296 - R:10.50.101.81/10.50.101.81:6379], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@136334d9[Completed normally], command=(HMGET), params=[[115, 112, 114, 105, 110, 103, 58, 115, 101, 115, ...], [115, 101, 115, 115, 105, 111, 110, 65, 116, 116, ...]], codec=org.redisson.client.codec.ByteArrayCodec], usage=1], command: (EXISTS), params: [[115, 112, 114, 105, 110, 103, 58, 115, 101, 115, ...]] after 3 retry attempts
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:270)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-24 12:22:31,653 [redisson-netty-3-63] WARN  com.zaxxer.hikari.pool.PoolBase ? - DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@644972d6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
2023-04-24 12:22:31,835 [redisson-netty-3-64] WARN  com.zaxxer.hikari.pool.PoolBase 179 - DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3c46bef6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
2023-04-24 12:22:34,341 [redisson-netty-3-56] WARN  com.zaxxer.hikari.pool.PoolBase ? - DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7545e57e (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
2023-04-24 12:22:44,563 [redisson-timer-5-1] ERROR o.r.c.handler.PingConnectionHandler 92 - Unable to send PING command over channel: [id: 0xa556b3ba, L:/172.30.10.7:41296 - R:10.50.101.81/10.50.101.81:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://10.50.101.81:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:255)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

redisson.yml
`
singleServerConfig:
  password: ${REDIS_PASSWORD}
  address: "redis://${REDIS_HOST}:${REDIS_PORT}"
  database: 0
  timeout: 5000
  retryAttempts: 5
  connectionPoolSize: 128
threads: 32
nettyThreads: 512
`
I am sure the threads is enough for the application.

But I didn't find any useful information from above stacktrace, it's so appreciated you can help us out.

By the way we are using redisson-3.20.1.

**Comment by liqiang-fit2cloud** [comment]
more information
we can see the exception is thrown always right after a warning of HikariCP which is database connection pool.
`2023-04-24 12:22:11,630 [redisson-netty-3-63] WARN  com.zaxxer.hikari.pool.PoolBase ? - DatebookHikariCP - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1c737ff8 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.`
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/20766823/234849338-832414c1-47eb-41d8-88cd-b0c7c6aba034.png">
I am not sure if they are related, but they always occur 100% together, I don't even know why the HikariCP warning is logged by a redisson-netty thread.

**Comment by liqiang-fit2cloud** [comment]
Our gateway project is here https://github.com/metersphere/metersphere/tree/main/framework/gateway

**Comment by mrniko** [comment]
there are might be multiple causes for this issue: like CPU throttling, network issues.

**Comment by liqiang-fit2cloud** [comment]
I believe CPU is fine and I didn't observe network issue from browser or logs.
Do you have any idea we can get more detailed information? like log severity?
BTW I am wondering why redisson thread(redisson-netty-3-63) throw HikariCP warning.
![image](https://user-images.githubusercontent.com/20766823/235030220-38efec4e-ba1e-4c57-aebd-342789b41a9f.png)

**Comment by mrniko** [comment]
I think the problem is in Blocking invocation in async/reactive/rx listeners. Please check that. All listeners are invoked by netty threads and blocking call may cause such errors - https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by liqiang-fit2cloud** [comment]
do you mean some block like this https://github.com/metersphere/metersphere/blob/main/framework/gateway/src/main/java/io/metersphere/gateway/controller/LoginController.java#L62?

**Comment by mrniko** [comment]
Yes, this is what I meant. I think I can introduce a new setting to use internal executorService or not for this case.

**Comment by mrniko** [comment]
If't 

> do you mean some block like this https://github.com/metersphere/metersphere/blob/main/framework/gateway/src/main/java/io/metersphere/gateway/controller/LoginController.java#L62?

Blocking calls should be avoided in reactive methods. Can you contact the project team regarding this issue?

**Comment by mrniko** [comment]
is `userLoginService.getUserDTO` a blocking call?

**Comment by liqiang-fit2cloud** [comment]
low performance sometimes.

**Comment by mrniko** [comment]
Sorry, low performance where?

**Comment by liqiang-fit2cloud** [comment]
> low performance sometimes.

userLoginService.getUserDTO

**Comment by liqiang-fit2cloud** [comment]
> is `userLoginService.getUserDTO` a blocking call?

not blocking but low performance sometimes.

**Comment by mrniko** [comment]
Then it should be executed in a different thread
