### ISSUE TITLE
NPE after upgrading to Redisson 3.21.0 on Quarkus 3

### ISSUE THREAD

**Issue by alexcatit** [redisson/redisson#5006]
Calling a RLocalCachedMap.keySet(String pattern) on Redisson 3.21.0 on Quarkus 3.0.1.Final now throws the exception

`
2023-05-02 14:29:02,554 ERROR [org.red.cli.han.CommandDecoder] (redisson-netty-5-17) Unable to decode data. channel: [id: 0xfe1e0923, L:/192.168.0.28:62970 - R:test.test.mydomain/192.168.0.161:6379], reply: ReplayingDecoderByteBuf(ridx=24, widx=24), command: (EVAL), promise: java.util.concurrent.CompletableFuture@3d85087f[Not completed, 1 dependents], params: [local result = {}; local res; if (#ARGV == 3) then  res = redis.call('hscan', KEYS[1], ARGV[1], 'match', ARGV[2], 'count', ARGV[3]); else  res = redis.call('hscan', KEYS[1], ARGV[1], 'count', ARGV[2]); end;for i, value in ipairs(res[2]) do if i % 2 ~= 0 then local key = res[2][i]; table.insert(result, key); end; end;return {res[1], result};, 1, test, 0, 1-*, 10]: java.lang.NullPointerException: Cannot invoke "org.redisson.client.codec.Codec.getValueDecoder()" because "this.valueCodec" is null
	at org.redisson.codec.CompositeCodec.getValueDecoder(CompositeCodec.java:74)
	at org.redisson.client.protocol.decoder.MultiDecoder.getDecoder(MultiDecoder.java:38)
	at org.redisson.client.protocol.decoder.ObjectListReplayDecoder.getDecoder(ObjectListReplayDecoder.java:63)
	at org.redisson.client.protocol.decoder.ListMultiDecoder2.getDecoder(ListMultiDecoder2.java:41)
	at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:490)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:437)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:437)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
`

Here is the example code to reproduce

```
    static class TestClass implements Serializable {

        public TestClass(String attribute) {
            this.attribute = attribute;
        }

        private String attribute;

    }

RLocalCachedMap<Object, Object> map = redisson.getLocalCachedMap("test", new CompositeCodec(StringCodec.INSTANCE, JsonJacksonCodec.INSTANCE), LocalCachedMapOptions.defaults());  
map.put("1-1", new TestClass("Test!"));  
Set<Object> set = map.keySet("1-*");
```

Maybe related on new improvement  released on 3.21.0 "RMap.keySet() method shouldn't load map values"?

**Comment by mrniko** [comment]
Fixed. Thanks for report!

**Comment by alexcatit** [comment]
There is any workaround waiting 3.21.1 milestone?

**Comment by mrniko** [comment]
This is the temporary workaround for the issue:
`new CompositeCodec(StringCodec.INSTANCE, JsonJacksonCodec.INSTANCE, StringCodec.INSTANCE)`
