### ISSUE TITLE
We are using the redis version 3.17.4 and we are getting the below error, could you please check this?

### ISSUE THREAD

**Issue by nivitha16** [redisson/redisson#5028]
I am getting this below error randomly while trying to fetch with a string key. (Sample String Key: C3V23748167269J)

Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 3)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391) ~[jackson-core-2.13.3.jar:2.13.3]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735) ~[jackson-core-2.13.3.jar:2.13.3]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:713) ~[jackson-core-2.13.3.jar:2.13.3]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3057) ~[jackson-core-2.13.3.jar:2.13.3]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:756) ~[jackson-core-2.13.3.jar:2.13.3]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058) ~[jackson-databind-2.9.5.jar:2.9.5]
        at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:99) ~[redisson-3.17.4.jar:3.17.4]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:383) ~[redisson-3.17.4.jar:3.17.4]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198) ~[redisson-3.17.4.jar:3.17.4]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[redisson-3.17.4.jar:3.17.4]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) ~[redisson-3.17.4.jar:3.17.4]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
        ... 17 more

**Comment by nivitha16** [comment]
@mrniko

**Comment by nivitha16** [comment]
@mrniko can you check this issue?

**Comment by mrniko** [comment]
Sorry, I can't reproduce it locally. It can be caused by trying to read data encoded with a different codec

**Comment by qwqeq** [comment]
We used RedissonBlockingQueue in our project. This error occurred when we updated the production environment. However, we tried to reproduce this problem locally, but it never occurred. So can you guys try to analyze the possible causes of the problem?
