### ISSUE TITLE
[org.redisson.client.handler.CommandPubSubDecoder] [CommandPubSubDecoder.java:91] - Unable to decode data. channel: [id: 0x61b64334, L:/10.1.60.139:22374 - R:10.1.60.166/10.1.60.166:3513], reply: ReplayingDecoderByteBuf(ridx=109, widx=112)

### ISSUE THREAD

**Issue by ratnashanker** [redisson/redisson#5029]
Redis Version : redis-7.0.10
Redisson Version:3.20.0
Scenario: Issue is coming after upgrading redisson from 3.16.1 to 3.20.0
Exception:
[org.redisson.client.handler.CommandPubSubDecoder] [CommandPubSubDecoder.java:91] - Unable to decode data. channel: [id: 0x61b64334, L:/10.1.60.139:22374 - R:10.1.60.166/10.1.60.166:3513], reply: ReplayingDecoderByteBuf(ridx=109, widx=112)
java.lang.IndexOutOfBoundsException: readerIndex(21) + length(1970038111) exceeds writerIndex(38): UnpooledSlicedByteBuf(ridx: 21, widx: 38, cap: 38/38, unwrapped: PooledUnsafeDirectByteBuf(ridx: 109, widx: 112, cap: 112))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at org.redisson.cache.LocalCachedMessageCodec.lambda$new$0(LocalCachedMessageCodec.java:68) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:437) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:87) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94) ~[redisson-3.20.0.jar:3.20.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2023-05-09 02:41:24.071] [GTRN-NA] [NA] [NA] [NA] [NEOENGG-APPS-60-139] [redisson-netty-2-13] [ERROR] [org.redisson.client.handler.ErrorsLoggingHandler] [ErrorsLoggingHandler.java:47] - Exception occured. Channel: [id: 0x61b64334, L:/10.1.60.139:22374 - R:10.1.60.166/10.1.60.166:3513]
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(21) + length(1970038111) exceeds writerIndex(38): UnpooledSlicedByteBuf(ridx: 21, widx: 38, cap: 38/38, unwrapped: PooledUnsafeDirectByteBuf(ridx: 109, widx: 112, cap: 112))
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[netty-codec-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(21) + length(1970038111) exceeds writerIndex(38): UnpooledSlicedByteBuf(ridx: 21, widx: 38, cap: 38/38, unwrapped: PooledUnsafeDirectByteBuf(ridx: 109, widx: 112, cap: 112))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903) ~[netty-buffer-4.1.89.Final.jar:4.1.89.Final]
	at org.redisson.cache.LocalCachedMessageCodec.lambda$new$0(LocalCachedMessageCodec.java:68) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:437) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:87) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[redisson-3.20.0.jar:3.20.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94) ~[redisson-3.20.0.jar:3.20.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.89.Final.jar:4.1.89.Final]
	... 17 more

**Comment by mrniko** [comment]
since 3.19.0 version default has been changed to Kryo5Codec. Try to clear redis db or migrate to a new codec

**Comment by ratnashanker** [comment]
Hi Team,

We already uses CustomMarshallingCodec and Kryo5Codec since redisson 3.16.1.
We already flushed redis, when issue reported in logs.
Issue was still coming after redis flush.

Regards
Ratna Shanker Mishra

**Comment by ratnashanker** [comment]
Hi Nikita,
 
We are creating RMap with specific codec either CustomMarshallingCodec  or  Kryo5Codec means same codec uses in read and write operation.

Regards
Ratna Shanker Mishra

**Comment by ratnashanker** [comment]
Issue still coming.

**Comment by liliexuan** [comment]
I also encountered an issue during the upgrade today. We've been using our custom encoder, the JsonJacksonCodec, from the very beginning instead of the default configuration. It seems that this problem hasn't been resolved yet, but it was closed.

**Comment by liliexuan** [comment]
> Issue still coming on every sentinel setup.

Did you manage to solve this problem later, buddy? If you did, could you please share the solution with me?

**Comment by mrniko** [comment]
@liliexuan 

Can you share the code to reproduce it?

**Comment by liliexuan** [comment]
> [@liliexuan @liliexuan](https://github.com/liliexuan)
> 
> Can you share the code to reproduce it?您能分享代码来重现它吗？

The code in the attachment contains two different versions of Redisson, namely 3.16.4 and 3.39. When the two applications are started separately, the error can be reproduced. I am using the local cache strategy. In my understanding, with the local cache strategy, it seems that the encoding of the local cache cannot be changed. The JsonJacksonCodec I set should not be taking effect, and I can't find a way to change the encoding of the local cache. In this situation, it seems that the only solution is to set storeMode(LocalCachedMapOptions.StoreMode.LOCALCACHE) and syncStrategy(LocalCachedMapOptions.SyncStrategy.INVALIDATE). If there is a better solution, please let me know. Thank you!

[redisson-demo.zip](https://github.com/user-attachments/files/18902182/redisson-demo.zip)

**Comment by liliexuan** [comment]
> [@liliexuan](https://github.com/liliexuan)
> 
> Can you share the code to reproduce it?



> > [@liliexuan @liliexuan](https://github.com/liliexuan)
> > Can you share the code to reproduce it?
> 
@mrniko 
> The code in the attachment contains two different versions of Redisson, namely 3.16.4 and 3.39. When the two applications are started separately, the error can be reproduced. I am using the local cache strategy. In my understanding, with the local cache strategy, it seems that the encoding of the local cache cannot be changed. The JsonJacksonCodec I set should not be taking effect, and I can't find a way to change the encoding of the local cache. In this situation, it seems that the only solution is to set storeMode(LocalCachedMapOptions.StoreMode.LOCALCACHE) and syncStrategy(LocalCachedMapOptions.SyncStrategy.INVALIDATE). If there is a better solution, please let me know. Thank you!
> 
> [redisson-demo.zip](https://github.com/user-attachments/files/18902182/redisson-demo.zip)
