### ISSUE TITLE
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 14500ms. Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.

### ISSUE THREAD

**Issue by ratnashanker** [redisson/redisson#5046]
Hi Team, 

That is very old issue and we assumed that it fixed in version 3.17.2 through https://github.com/redisson/redisson/commit/6dac3399a01fc515a240083e9af376d7a5fd161e commit but issue still coming.
Following are the details: 
Redis Version : redis-7.0.10
Redisson Version:3.20.0
Exception:
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 14500ms. Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
                at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$5(PublishSubscribeService.java:219) ~[redisson-3.20.0.jar:3.20.0]
                at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
                at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
                at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
                at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
                at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
                at java.lang.Thread.run(Thread.java:834) [?:?]

Regards
Ratna Shanker Mishra

**Comment by ratnashanker** [comment]
Thanks Nikita.

Can you please share me the relevant settings ?

Regards
Ratna Shanker Mishra

**Comment by ratnashanker** [comment]
Issue is not coming after increasing subscriptionConnectionPoolSize, timeout and subscriptionsPerConnection value.
