### ISSUE TITLE
RedissonBatch.execute() hangs infinitely waiting for RedissonPromise

### ISSUE THREAD

**Issue by nguyenminhtri455** [redisson/redisson#5053]
Hi,

I'm encountering a problem with Redisson, specifically when multiple threads call the RedissonBatch.execute() method. In some cases, the execution becomes indefinitely stuck. Here is the corresponding stacktrace that I observed in jstack:

``CentralPool-iop-task_CA_5-2247" #2247 prio=5 os_prio=0 cpu=2362.04ms elapsed=8661.57s tid=0x00007ff344008000 nid=0xeb5 in Object.wait()  [0x00007ff439898000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(java.base@11.0.18/Native Method)
    - waiting on <no object reference available>
    at java.lang.Object.wait(java.base@11.0.18/Object.java:328)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:253)
    - waiting to re-lock in wait() <0x0000000654900568> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
    at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
    at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
    at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:113)
    at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:205)
    at org.redisson.RedissonBatch.execute(RedissonBatch.java:207)
    at Proxy76aeb385_3985_41c2_8a99_3d39e0d92710.executeBatchWrite(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)``

Around that time, I can see the following error:

`org.redisson.client.RedisException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.. channel: [id: 0x508a901e, L:/1.1.1.5:41296 - R:server-redis/1.1.1.1:6379] command: (PING), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@6fccec7c(incomplete)], params: []
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

This issue occurs sporadically after the application has been running smoothly for a prolonged period of time. Is this a known issue? Please help me!

Redisson version: 3.16.6

**Comment by mrniko** [comment]
What is the Redisson configuration?

**Comment by nguyenminhtri455** [comment]
Hi

Below is the code that I used for Redisson configuration

`    private Config configRedisServer(String url, String username, String password) {
        Config config = new Config();
        SingleServerConfig singleServerConfig = config.useSingleServer().setAddress(url);

        if (!StringUtils.isEmpty(password)) {
            singleServerConfig.setPassword(password);
        }

        if (!StringUtils.isEmpty(username)) {
            singleServerConfig.setUsername(username);
        }

        singleServerConfig
                .setConnectionPoolSize(POOL_SIZE)  ==> 128
                .setTimeout(TIME_OUT) ==> 3000 ms (3s)
                .setRetryInterval(RETRY_INTERVAL) ==> 1500 ms (1.5s)
                .setIdleConnectionTimeout(IDLE_CONNECTION_TIMEOUT) ==> 600000 ms (10m)
                .setSubscriptionsPerConnection(SUBSCRIPTIONS_PER_CONNECTION) ==> 10
                .setKeepAlive(true)
                .setTcpNoDelay(true)
                .setDatabase(0);

        config.setTransportMode(TransportMode.EPOLL);
        config.setLockWatchdogTimeout(LOCK_TIME_OUT); ==> 1000 ms
        config.setNettyThreads(NETTY_THREAD); ==> 0 (Will use default config of Redis (24))
        config.setThreads(THREAD); ==> 32
        return config;
    }`

**Comment by mrniko** [comment]
Is there any code sample to reproduce it?

**Comment by nguyenminhtri455** [comment]
Hi,

I'm not able to reproduce it now, but I checked the get method of CommandAsyncService class based on the stack trace:


`
    @Override
    public <V> V get(RFuture<V> future) {
        if (Thread.currentThread().getName().startsWith("redisson-netty")) {
            throw new IllegalStateException("Sync methods can't be invoked from async/rx/reactive listeners");
        }

        try {
            future.await();
        } catch (InterruptedException e) {
            future.cancel(true);
            Thread.currentThread().interrupt();
            throw new RedisException(e);
        }
        if (future.isSuccess()) {
            return future.getNow();
        }

        throw convertException(future);
    }
`
I'm wondering whether a deadlock will happen if the future never gets completed, right? Could you give me feedback?
