### ISSUE TITLE
Getting IllegalMonitorStateException for RMapCache Read

### ISSUE THREAD

**Issue by amarendrar** [redisson/redisson#5061]
Hi, 
Getting IllegalMonitorStateException while reading the RmapCache from Redis. There is no locks created from application and looks internally redisson uses the locks while reading the keys from Redis. 

Could you please suggest how to overcome this errors if there is a multiple concurrent users tries to read the keys. Is there any configuration need to be added to handle multiple reads from redisson?

Redisson Verison : 3.17.6

StackTrace Error:
```
Caused by: java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: <> thread-id: <> org.redisson.RedissonBaseLock.lambda$unlockAsync$2(RedissonBaseLock.java:323)
java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) 
java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) 
java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:322)
java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:163)
org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:524)
org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:176)
java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:318)^
org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)\r
io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by mrniko** [comment]
you need to make sure that the lock wasn't expired if you use lease parameter.

**Comment by amarendrar** [comment]
I didn't use any lease parameter for the locks. I am using the default values from Redisson Client. is there any default values needs to increase to resolve the Lock issue.

**Comment by mrniko** [comment]
Can you share the full code?

**Comment by mrniko** [comment]
Sorry, I don't see any lock usage

**Comment by amarendrar** [comment]
I found one more error while writing. it is again failed at lock but with proper error

What is this mean **"None of slaves were synced"** . Is there an issue at Redis or need to handle at Redisson to release the lock?

```
Caused by: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:276) 
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115) 
	at org.redisson.RedissonObject.get(RedissonObject.java:82) 
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:144) 
	at org.redisson.RedissonLock.lock(RedissonLock.java:96) 
	at org.redisson.RedissonLock.lock(RedissonLock.java:68) 
	at org.redisson.RedissonMap.computeIfAbsent(RedissonMap.java:388) 

Caused by: java.lang.IllegalStateException: None of slaves were synced
	at org.redisson.RedissonBaseLock.lambda$evalWriteAsync$0(RedissonBaseLock.java:225) 
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) 
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) 
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) 
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) 
	at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:322) 
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) 
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) 
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) 
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) 
	at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:163) 
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:524) 
	at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:176) 
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) 
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) 
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) 
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) 
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:318) 
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210) 
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) 
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) 
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) 
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) 
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) 
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) 
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) 
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) 
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) 
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) 
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) 
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) 
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) 
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) 
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 

```
