### ISSUE TITLE
Redisson is shutdown

### ISSUE THREAD

**Issue by dognsiwei** [redisson/redisson#5069]
version : 3.12.0
application restart 

org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:110)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:609)
	at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:594)
	at org.redisson.RedissonLock.isHeldByThread(RedissonLock.java:522)
	at org.redisson.RedissonLock.isHeldByCurrentThread(RedissonLock.java:517)
	at com.jumstc.fdc.common.util.RedissonUtil.unlock(RedissonUtil.java:56)
	at com.jumstc.fdc.controller.bills.WithdrawalRecordController.asyncApplyWithdrawal$original$eLMkLitb(WithdrawalRecordController.java:749)
	at com.jumstc.fdc.controller.bills.WithdrawalRecordController.asyncApplyWithdrawal$original$eLMkLitb$accessor$Dkq7KY8f(WithdrawalRecordController.java)
	at com.jumstc.fdc.controller.bills.WithdrawalRecordController$auxiliary$MilnQojK.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.jumstc.fdc.controller.bills.WithdrawalRecordController.asyncApplyWithdrawal(WithdrawalRecordController.java)
	at com.jumstc.fdc.controller.bills.WithdrawalRecordController$$FastClassBySpringCGLIB$$bdc0462c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.jumstc.fdc.aspect.LoggerHandler.logAround(LoggerHandler.java:73)

**Comment by dognsiwei** [comment]
How to solve this problem

**Comment by mrniko** [comment]
how to reproduce it?

**Comment by mrniko** [comment]
make sure that Redisson is not in shutdown state
