### ISSUE TITLE
Not support Quarkus dev hot reload?

### ISSUE THREAD

**Issue by seepine** [redisson/redisson#5073]
build.gradle
```gradle
implementation 'org.redisson:redisson-quarkus-30:3.21.3'
```
Startup.java
```java
public class StartRunner {
  @Inject RedissonClient redissonClient;

  public void onStart(@Observes StartupEvent startupEvent) {
     // do something..
     redissonClient.getBucket("xxx").get()
  }
}
```
it can be work when first start application, but modify some code and quarkus auto restart, some error happended
```
org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:122)
	at org.redisson.command.CommandBatchService.lambda$execute$10(CommandBatchService.java:427)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:144)
	at org.redisson.command.CommandBatchService.lambda$execute$11(CommandBatchService.java:372)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:342)
	at org.redisson.command.CommandBatchService.executeAsync(CommandBatchService.java:334)
	at org.redisson.command.CommandAsyncService.lambda$syncedEval$23(CommandAsyncService.java:756)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.redisson.command.CommandAsyncService.syncedEval(CommandAsyncService.java:747)
	at org.redisson.RedissonBaseLock.evalWriteAsync(RedissonBaseLock.java:203)
	at org.redisson.RedissonLock.unlockInnerAsync(RedissonLock.java:331)
	at org.redisson.RedissonBaseLock.unlockAsync0(RedissonBaseLock.java:279)
	at org.redisson.RedissonBaseLock.lambda$unlockAsync$1(RedissonBaseLock.java:275)
	at org.redisson.connection.ServiceManager.execute(ServiceManager.java:389)
	at org.redisson.connection.ServiceManager.execute(ServiceManager.java:384)
	at org.redisson.RedissonBaseLock.unlockAsync(RedissonBaseLock.java:275)
	at org.redisson.RedissonBaseLock.unlock(RedissonBaseLock.java:304)
	at com.seepine.common.startup.StartRunner$2.lock(StartRunner.java:53)
	at com.seepine.tool.lock.Lock.sync(Lock.java:50)
	at com.seepine.tool.cache.Cache.enhance(Cache.java:30)
	at com.seepine.common.startup.StartRunner.onStart(StartRunner.java:24)
	at com.seepine.common.startup.StartRunner_Observer_onStart_fe715f9ed44274545cfe50c0fb73e98251d5dfe2.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
Resulted in: java.lang.RuntimeException: Failed to start quarkus
	... 13 more
Resulted in: io.quarkus.dev.appstate.ApplicationStartException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:58)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:123)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:222)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:203)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:543)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Comment by seepine** [comment]
Closed due to timeout.
