### ISSUE TITLE
No route to host exception is  observed in SentinelConnectionManager after redis version is upgraded 

### ISSUE THREAD

**Issue by SankarBalaji** [redisson/redisson#5088]
hi,
  
    We are using redission version 3.19.0 , with spring boot version 2.7.2   in our micro services environment. 
    Our micro service is runing in a open shift cluster version 4.10.  
     
    We also have the redis running as microservice in the same cluster. Redis is configured as 3 node system(1 master +2 slaves) along with 3 sentinels.  
   
    We are using the sentinel configuration in redission  to connecto to redis server. Also we use sentinel service name as the sentinel address in the redisson config. 
 
     We recently upgraded our  redis from redis_version:6.2.7  to redis_version:7.0.9 . After the redis upgrade we are  observing the no route to host exception from sentinel connection manager. 
     On a closer look at the ips mentioned in the exception, it looks like sentinel connection manager is still trying  to connect to the sentinel with the older ip. (sentinel ip addresses are changed after the redis upgrade). 

     #[310523 11:53:26,757 | femtocellapi-0 | ERROR | redisson-netty-2-19 | SentinelConnectionManager | io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: <old_ip>/<old_ip>:26379]#
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: <old_ip>/<old_ip>:26379
        at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
        at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
        at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: <old_ip>/<old_ip>:26379
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

   Why do we observe this exception ?, since we are using the sentinel service name as the address, it  should resolve to newer ips instead of old IPs. Is there any specific configuration needs to be done to make sure redission picks the latest sentinel ips ?

**Comment by mrniko** [comment]
@SankarBalaji 

> You mean to say the DNS resolver from the openshift cluster ?

That's correct

**Comment by SankarBalaji** [comment]
@mrniko : we have verified with the RHEL.  The service name to POD IP resolution happening properly. 
After the redis upgrade  

[core@mn0021-vs8qj-master-0 drop7Interim]$ oc get svc | grep -i sentinel
cfcm-crdb-redisio-sentinel            ClusterIP      172.x.x.x    <none>          26379/TCP                                         69m
cfcm-crdb-redisio-sentinel-nodes      ClusterIP      None             <none>          26379/TCP                                         69m
[core@mn0021-vs8qj-master-0 drop7Interim]$

Sentinel POD IPs : 

core@mn0021-vs8qj-master-0 drop7Interim]$ oc get pods -o wide | grep sentinel
cfcm-crdb-redisio-sentinel-0                        1/1     Running             0              56m     10.130.3.208   mn0021-vs8qj-worker-nn626   <none>           <none>
cfcm-crdb-redisio-sentinel-1                        1/1     Running             0              56m     10.128.3.193   mn0021-vs8qj-worker-vxbzf   <none>           <none>
cfcm-crdb-redisio-sentinel-2                        1/1     Running             0              57m     10.129.3.250   mn0021-vs8qj-worker-dp7qq   <none>           <none>

From the OCP clusters ip tables: 
[root@mn0021-vs8qj-master-0 ~]# iptables-save | grep -i sentinel
-A KUBE-SERVICES -d 172.x.x.x/32 -p tcp -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel cluster IP" -m tcp --dport 26379 -j KUBE-SVC-LRLIK6FVLJSRA4KU
-A KUBE-SVC-LRLIK6FVLJSRA4KU -d 172.x.x.x/32 ! -i tun0 -p tcp -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel cluster IP" -m tcp --dport 26379 -j KUBE-MARK-MASQ
-A KUBE-SVC-LRLIK6FVLJSRA4KU -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -m statistic --mode random --probability 0.33333333349 -j KUBE-SEP-THUYIFE7VLNMEAWS
-A KUBE-SVC-LRLIK6FVLJSRA4KU -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-HKEUAALAKJ5XUVKG
-A KUBE-SVC-LRLIK6FVLJSRA4KU -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -j KUBE-SEP-L3XNH4OCOX3KTWG6
-A KUBE-SEP-HKEUAALAKJ5XUVKG -s 10.129.3.250/32 -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -j KUBE-MARK-MASQ
-A KUBE-SEP-HKEUAALAKJ5XUVKG -p tcp -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -m tcp -j DNAT --to-destination 10.129.3.250:26379
-A KUBE-SEP-THUYIFE7VLNMEAWS -s 10.128.3.193/32 -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -j KUBE-MARK-MASQ
-A KUBE-SEP-THUYIFE7VLNMEAWS -p tcp -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -m tcp -j DNAT --to-destination 10.128.3.193:26379
-A KUBE-SEP-L3XNH4OCOX3KTWG6 -s 10.130.3.208/32 -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -j KUBE-MARK-MASQ
-A KUBE-SEP-L3XNH4OCOX3KTWG6 -p tcp -m comment --comment "cfcm/cfcm-crdb-redisio-sentinel:tcp-sentinel" -m tcp -j DNAT --to-destination 10.130.3.208:26379
[root@mn0021-vs8qj-master-0 ~]#

[core@mn0021-vs8qj-master-0 amit]$ oc get ep | grep -i sentinel
cfcm-crdb-redisio-sentinel            10.128.3.193:26379,10.129.3.250:26379,10.130.3.208:26379             78m
cfcm-crdb-redisio-sentinel-nodes      10.128.3.193:26379,10.129.3.250:26379,10.130.3.208:26379             78m
[core@mn0021-vs8qj-master-0 amit]$



But in  Redission logs, we are still seeing that, connection manager is  trying to connect to the older sentinel ip 
#[060723 10:41:04,165 | femtocellapi-0 | ERROR | redisson-netty-2-17 | SentinelConnectionManager | io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: 10.130.3.203/10.130.3.203:26379]#
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: 10.130.3.203/10.130.3.203:26379
        at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
        at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
        at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: 10.130.3.203/10.130.3.203:26379
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

Could you please take a look .

**Comment by mrniko** [comment]
> No route to host: 10.130.3.203/10.130.3.203:26379

The problem is in network connection.

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` package and show output?

**Comment by SankarBalaji** [comment]
Attaching  the requested logs. For secutiry reason have jumbled the actual ip adresses. 
Below is the snip from the kubectl get svc 
cfcm-crdb-redisio-sentinel            ClusterIP      172.2.2.2   <none>          26379/TCP                                         41h
cfcm-crdb-redisio-sentinel-nodes      ClusterIP      None             <none>          26379/TCP                                         41h
cfcm-crdb-redisio-server-0            ClusterIP      172.2.3.3     <none>          6379/TCP                                          41h
cfcm-crdb-redisio-server-1            ClusterIP      172.2.4.4  <none>          6379/TCP                                          41h
cfcm-crdb-redisio-server-2            ClusterIP      172.2.5.5  <none>          6379/TCP                                          

cfcm-crdb-redisio-server-2    is the master of the cluster  and we are using the sentinel configuration as indicated earlier and cfcm-crdb-redisio-sentinel  is the svc name which we are using. 
[after_restart_exception.txt](https://github.com/redisson/redisson/files/12024597/after_restart_exception.txt)
[podipchanges.txt](https://github.com/redisson/redisson/files/12024598/podipchanges.txt)
[Redis_before_upgrade.txt](https://github.com/redisson/redisson/files/12024599/Redis_before_upgrade.txt)

**Comment by SankarBalaji** [comment]
@mrniko any findings from the attached logs ?

**Comment by mrniko** [comment]
According to after_restart_exception.txt:1070 line, `SENTINEL SENTINELS` command returns `10.129.3.85` address. Which is unreachable. Check your Redis configuration.
