### ISSUE TITLE
Default getCache method checks for Object class equality

### ISSUE THREAD

**Issue by agupta-hw** [redisson/redisson#5089]
While trying to getCache() by a name, Redisson expects and validates if the object type used in Configuration is of Object and Object.class. While this check is fine, its inconvenient as every Java object extends from Object but since the check is for equality, it fails and is not generic enough. 

```
    public <K, V> Cache<K, V> getCache(String cacheName) {
        this.checkNotClosed();
        Cache<K, V> cache = this.getCache(cacheName, Object.class, Object.class);
        if (cache != null) {
            if (((CompleteConfiguration)cache.getConfiguration(CompleteConfiguration.class)).getKeyType() != Object.class) {
                throw new IllegalArgumentException("Wrong type of key for " + cacheName);
            }

            if (((CompleteConfiguration)cache.getConfiguration(CompleteConfiguration.class)).getValueType() != Object.class) {
                throw new IllegalArgumentException("Wrong type of value for " + cacheName);
            }
        }

        return cache;
    }
```

**Expected behavior**
getCache should return the cache even if the type configured is of different types that is not Object, Object.

**Actual behavior**
Fails with below trace
Caused by: java.lang.IllegalArgumentException: Wrong type of key for myCacheName
	at org.redisson.jcache.JCacheManager.getCache(JCacheManager.java:180)
	at com.test.sample.CacheConfiguration.getCacheByName(MyTestJCacheImpl.java:77)
	... 77 more
]]

**Steps to reproduce or test case**

**Redis version**
Not Applicable

**Redisson version**
3.21.0 (any)

**Redisson configuration**
Not Applicable.

**Comment by agupta-hw** [comment]
Solution: Below is a solution that will work and should make it generic enough for anyone to get a cache instance back, even if they don't know the actual configuration used to create cache. This becomes abstracted out in that case.
      ```
  if (cache != null) {
            if (cache.getConfiguration(CompleteConfiguration.class).getKeyType().isAssignableFrom(Object.class)) {
                throw new IllegalArgumentException("Wrong type of key for " + cacheName);
            }
            if (cache.getConfiguration(CompleteConfiguration.class).getValueType().isAssignableFrom(Object.class) {
                throw new IllegalArgumentException("Wrong type of value for " + cacheName);
            }
        }
```

**Comment by agupta-hw** [comment]
It seems I can't push to this repository to create a PR.
```
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/redisson/redisson.git/'
```
