### ISSUE TITLE
Since upgrading redisson-hibernate-53 from 3.18 to any newer version, we have errors in deserialization

### ISSUE THREAD

**Issue by SchlauFuchs** [redisson/redisson#5118]
Hi,

Since we updated our dependency from redisson-hibernate-53 from 3.18 to any other one we have errors with deserialization from the Redis server. Stack traces look like:
```
java.lang.ClassCastException: class org.hibernate.bytecode.enhance.spi.LazyPropertyInitializer$1 cannot be cast to class [Ljava.lang.Object; (org.hibernate.bytecode.enhance.spi.LazyPropertyInitializer$1 is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @3f985a86; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
at org.hibernate.type.ComponentType.assemble(ComponentType.java:640)
at org.hibernate.type.CollectionType.assemble(CollectionType.java:302)
at org.hibernate.type.TypeHelper.assemble(TypeHelper.java:101)
at org.hibernate.cache.spi.entry.StandardCacheEntryImpl.assemble(StandardCacheEntryImpl.java:135)
at org.hibernate.loader.entity.CacheEntityLoaderHelper.convertCacheEntryToEntity(CacheEntityLoaderHelper.java:308)
at org.hibernate.loader.entity.CacheEntityLoaderHelper.processCachedEntry(CacheEntityLoaderHelper.java:174)
at org.hibernate.loader.entity.CacheEntityLoaderHelper.loadFromSecondLevelCache(CacheEntityLoaderHelper.java:147)
at org.hibernate.persister.entity.AbstractEntityPersister.initializeEnhancedEntityUsedAsProxy(AbstractEntityPersister.java:4541)
at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementAsProxyLazinessInterceptor.forceInitialize(EnhancementAsProxyLazinessInterceptor.java:221)
at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementAsProxyLazinessInterceptor.lambda$handleRead$0(EnhancementAsProxyLazinessInterceptor.java:133)
at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementHelper.performWork(EnhancementHelper.java:206)
at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementAsProxyLazinessInterceptor.handleRead(EnhancementAsProxyLazinessInterceptor.java:98)
at org.hibernate.bytecode.enhance.spi.interceptor.AbstractInterceptor.readObject(AbstractInterceptor.java:153)
at org.workflow.jpa.crs.TransactionType.$$_hibernate_read_description(TransactionType.kt)
at org.workflow.jpa.crs.TransactionType.getDescription(TransactionType.kt:46)
at org.workflow.api.jobs.mapper.JobEntityToDtoMapper.toDTO(JobEntityToDtoMapper.kt:37)
at ork.workflow.api.jobs.JobController.patch(JobController.kt:234)
```

Any suggestions?

**Comment by ArvinEsmailzadeh** [comment]
I have the same issue and its because the default codec in version 3.19+ was changed. https://github.com/redisson/redisson/releases/tag/redisson-3.19.0

**Comment by SchlauFuchs** [comment]
Do we have control over what codec to use when configuring reddison client?

**Comment by SchlauFuchs** [comment]
I was just checking our app, and we have specified the codec:

```kotlin
    @Bean(destroyMethod = "shutdown")
    @Throws(IOException::class)
    @Lazy
    fun redisson(): RedissonClient {
        val config: Config = Config.fromYAML(redissonConfiguration.inputStream)
        config.codec = JsonJacksonCodec(mapper)
        val mapper = object : NameMapper {
            override fun map(name: String): String {
                return "$redissonCachePrefix$name"
            }

            override fun unmap(name: String): String {
                return name.substring(redissonCachePrefix.length)
            }
        }
        config.useSingleServer().nameMapper = mapper
        return Redisson.create(config)
    }
```

but this seems to be ignored by hibernate -does it create its own reddisson client?

**Comment by ArvinEsmailzadeh** [comment]
I'm having a very similar problem to you but you can control the codec being used. Here is a list of them:

https://github.com/redisson/redisson/wiki/4.-data-serialization

Maybe try different ones and see if that fixes your issue?

**Comment by mrniko** [comment]
@SchlauFuchs 

Hibernate Factory creates own Redisson instance. You can override org.redisson.hibernate.RedissonRegionFactory#createRedissonClient method to create a custom client instance. Also you can extract NameMapper logic to a separate class and specify it in yaml configuration.
