### ISSUE TITLE
RMultimapCache eviction after remove by key&value

### ISSUE THREAD

**Issue by SimAntony** [redisson/redisson#5120]
After removing key+value from **RSetMultimapCache**, **MultimapEvictionTask** is not working as expected.

1. Put key/value into RSetMultimapCache with ttl (cache.expireKey())
2. Remove key+value from cache before eviction task started
3. Async execution of MultimapEvictionTask contains the following:
`Unable to evict elements for 'simple-cache'
org.redisson.client.RedisException: ERR user_script:1: attempt to concatenate local 'v' (a boolean value) script: 9d3678f43f997fc1f1c0e595e743c679a150119c, on @user_script:1.. channel: [id: 0x643a1fcc, L:/172.19.0.2:50894 - R:10.10.81.146/10.10.81.146:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@70e6736c[Not completed, 1 dependents], params: [local expiredKeys = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredKeys > 0 then redis.call('zrem', KEYS[2], unpack(expiredKeys)); local values = redis.call('hmget', KEYS[1], unpack(expiredKeys)); local keys = {}; for i, v in ipairs(values) do local name = '{' .. KEYS[1] .. '}:' .. v; table.insert(keys, name); end; redis.call('del', unpack(keys)); redis.call('hdel', KEYS[1], unpack(expiredKeys)); end; return #expiredKeys;, 2, simple-cache, {simple-cache}:redisson_set_multimap_ttl, 1687432822548, 100]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:380)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)`

4. On next execution **redisson_set_multimap_ttl** does not contain the keys that should have been deleted, therefore these keys will never be deleted by eviction

**Comment by mrniko** [comment]
Fixed. Thanks for report
