### ISSUE TITLE
RedisException while deserializing ListMultimapCache eviction results

### ISSUE THREAD

**Issue by kpetroff** [redisson/redisson#5122]
Not sure how to reproduce this exactly, but it is probably related to a by-key expiration in a  `ListMultimapCache`.

```
2023-04-06T09:54:24.118 | netty-2-22 | ERROR | .eviction.MultimapEvictionTask |  | Unable to evict elements for 'EVENT_MM'
org.redisson.client.RedisException: ERR user_script:1: attempt to concatenate local 'v' (a boolean value) script: 9d3678f43f997fc1f1c0e595e743c679a150119c, on @user_script:1.. channel: [id: 0x4ce02aad, L:/10.2.0.194:42140 - R:10.2.1.209/10.2.1.209:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@56603f0d[Not completed, 1 dependents], params: [local expiredKeys = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredKeys > 0 then redis.call('zrem', KEYS[2], unpack(expiredKeys)); local values = redis.call('hmget', KEYS[1], unpack(expiredKeys)); local keys = {}; for i, v in ipairs(values) do local name = '{' .. KEYS[1] .. '}:' .. v; table.insert(keys, name); end; redis.call('del', unpack(keys)); redis.call('hdel', KEYS[1], unpack(expiredKeys)); end; return #expiredKeys;, 2, RT_EVENT_MM, {RT_EVENT_MM}:redisson_list_multimap_ttl, 1680774864117, 100]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:377)
    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Unknown Source) 
```
The eviction task seems to be this one - https://github.com/redisson/redisson/blob/051ad3b79b1942a3f00845304c14e173a3745425/redisson/src/main/java/org/redisson/eviction/MultimapEvictionTask.java#L46C1-L64

A similar issue seems to have been fixed in #1189 with https://github.com/redisson/redisson/commit/f3efba98f83d88187560910e3a3cebd121e9e555

**Steps to reproduce or test case**

WIP - most likely `RMultimapCacheAsync.expireKeyAsynk()`, followed by a `removeAll`

**Redis version**

7.0.11 - but also older ones

**Redisson version**

Seems to be here in all recent versions in the last 1-2 years, e.g. 3.19.1 - 3.22.0

**Redisson configuration**
```
config.setCodec(new JsonJacksonCodec());
config.setTransportMode(TransportMode.NIO);
config.setLockWatchdogTimeout(1_000); // make RLock auto-release faster
```

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5120
