### ISSUE TITLE
ConcurrentModificationException while writing into the RMapCache

### ISSUE THREAD

**Issue by amarendrar** [redisson/redisson#5124]
Hi, 

Getting ConcurrentModificationException while writing into the RmapCache  with concurrent users. Below is the stack errors. 

Could you please suggest to overcome this issue?

```
Caused by: java.lang.IllegalArgumentException: java.io.IOException: java.util.ConcurrentModificationException
	at org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:669) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:350) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonMapCache.fastPutOperationAsync(RedissonMapCache.java:1022) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonMapCache.fastPutAsync(RedissonMapCache.java:914) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonMapCache.fastPut(RedissonMapCache.java:888) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.spring.cache.RedissonCache.put(RedissonCache.java:124) ~[redisson-3.21.3.jar:3.21.3]
```
	

```
Caused by: java.io.IOException: java.util.ConcurrentModificationException
	at org.redisson.codec.MarshallingCodec.lambda$new$1(MarshallingCodec.java:172) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:667) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:350) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonMapCache.fastPutOperationAsync(RedissonMapCache.java:1022) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonMapCache.fastPutAsync(RedissonMapCache.java:914) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.RedissonMapCache.fastPut(RedissonMapCache.java:888) ~[redisson-3.21.3.jar:3.21.3]
	at org.redisson.spring.cache.RedissonCache.put(RedissonCache.java:124) ~[redisson-3.21.3.jar:3.21.3]
```
	
Redis version
AWS Elasticache 7.0.7

Redisson version
3.21.3

**Comment by mrniko** [comment]
Can you share full stacktrace?

**Comment by mrniko** [comment]
Unable to reproduce it. Below is the test.

```java
        ExecutorService e = Executors.newFixedThreadPool(16);
        RMapCache<String, Object> mapCache = redisson.getMapCache("test");

        for (int i = 0; i < 100000; i++) {
            int j = i;
            e.submit(() -> {
                mapCache.fastPut("" + j, j);
            });
        }

        e.shutdown();
        assertThat(e.awaitTermination(100, TimeUnit.SECONDS)).isTrue();
        assertThat(mapCache.size()).isEqualTo(100000);
```
