### ISSUE TITLE
RedisException / UnsupportedOperationException on RMap.fastRemove when used with transaction

### ISSUE THREAD

**Issue by BernhardBln** [redisson/redisson#5131]
**Expected behavior**

No RedisException  when calling fastRemove ;-)

**Actual behavior**

We get an UnsupportedOperationException wrapped inside a RedisException:

```
Caused by: org.redisson.client.RedisException: Unexpected exception while processing command
		at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:299)
		at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:116)
		at org.redisson.RedissonObject.get(RedissonObject.java:90)
		at org.redisson.RedissonMap.fastRemove(RedissonMap.java:1475)

[...]

Caused by: java.lang.UnsupportedOperationException: remove
		at java.base/java.util.Iterator.remove(Iterator.java:102)
		at org.redisson.transaction.BaseTransactionalMap.lambda$fastRemoveOperationAsync$19(BaseTransactionalMap.java:482)
		at org.redisson.transaction.BaseTransactionalObject.lambda$executeLocked$1(BaseTransactionalObject.java:79)
		at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
		at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:595)
		at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:587)
		at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:575)
		at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:552)
		at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:195)
```

**Steps to reproduce or test case**

```
    var tx = redisson.createTransaction(TransactionOptions.defaults());

    var m = tx.getMap("test");
    m.fastPut("x", "y");
    m.fastRemove("x");

    tx.commit();
```

The fastPut before the fastRemove is crucial, if you don't do that the problem seems not to arise (no matter if the entry exists or not).

**Redis version**

Tested with redis docker container "redis:7.0.7-alpine".

**Redisson version**

3.22.1

**Redisson configuration**

Nothing special, I guess

**Comment by mrniko** [comment]
Fixed. Thanks for report
