### ISSUE TITLE
redisson是否支持spring native编译?

### ISSUE THREAD

**Issue by elevenkongqian** [redisson/redisson#5135]
redisson是否支持spring native编译？
mvnw.cmd -DskipTests=true -Dmaven.plugin.validation=VERBOSE -Pnative clean native:compile
os: win10
springboot:3.1.1
graalvm-ee-java17-22.3.2
redisson:3.22.1

**Comment by elevenkongqian** [comment]
support springboot3 native has some new messages?

**Comment by mrniko** [comment]
Unable to reproduce issue using attached project. Can you try it?

[spring-native-image.zip](https://github.com/redisson/redisson/files/12027383/spring-native-image.zip)

**Comment by elevenkongqian** [comment]
> 无法使用附加项目重现问题。你能尝试一下吗？
> 
> [spring-native-image.zip](https://github.com/redisson/redisson/files/12027383/spring-native-image.zip)

Thank @mrniko 
How to generate the native-image/org.redisson/redisson/reflect-config.json configuration file?

and use my porject:
[demo-springboot3.1.tar.gz](https://github.com/redisson/redisson/files/12051197/demo-springboot3.1.tar.gz)
runtime exception is :
`Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'singleServerConfig': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"singleServerConfig:
  address: redis://10.66.186.110:6379
  clientName: demo
  password: hq%TGB*UHB
  database: 11 
  connectTimeout: 10000
  timeout: 3000
  connectionMinimumIdleSize: 8
  connectionPoolSize: 16
codec: !<org.redisson.codec.Kryo5Codec> {}
"transportMode": "NIO"
"; line: 1, column: 19]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:760)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3041)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2082)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:808)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4912)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4818)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
        at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:126)
        at org.redisson.config.Config.fromJSON(Config.java:597)
        at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:163)
        ... 67 common frames omitted
        Suppressed: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'org.redisson.codec.Kryo5Codec' as a subtype of `org.redisson.client.codec.Codec`: no such class found
 at [Source: (StringReader); line: 10, column: 8] (through reference chain: org.redisson.config.Config["codec"])
                at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:2084)
                at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1575)
                at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:76)
                at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
                at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
                at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._deserializeWithNativeTypeId(TypeDeserializerBase.java:267)
                at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:106)
                at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
                at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
                at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
                at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
                at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
                at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
                at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
                at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
                at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:160)
                at org.redisson.config.Config.fromYAML(Config.java:650)
                at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:160)
                ... 67 common frames omitted`


and config application-dev.yml is:
`
logging:
  level:
    root: info
server:
  port: 8081
  undertow:
    threads:
      io: 4
      worker: 8
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://127.0.0.1:49153
          clientName: demo
          password: redispw
          database: 0
          connectTimeout: 10000
          timeout: 3000
          connectionMinimumIdleSize: 8
          connectionPoolSize: 16
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"
`
error log file:
[error.2023-07-14.22.0.log](https://github.com/redisson/redisson/files/12051349/error.2023-07-14.22.0.log)

**Comment by mrniko** [comment]
> please ask how to generate the native-image/org.redisson/redisson/reflect-config.json configuration file?

Here is the documentation https://www.graalvm.org/22.0/reference-manual/native-image/Agent/

> runtime native file exception is :

Fixed. Thanks for report

**Comment by elevenkongqian** [comment]
Thanks @mrniko
