### ISSUE TITLE
引入本框架最新本后项目报错无法运行

### ISSUE THREAD

**Issue by zs1973** [redisson/redisson#5136]
已连接到目标 VM, 地址: ''127.0.0.1:55655'，传输: '套接字''
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.2)

INFO | 2023-06-28 20:52:54.224 | background-preinit | util.Version | HV000001: Hibernate Validator 6.2.3.Final
INFO | 2023-06-28 20:52:54.247 | main | knowmyself.KnowMySelfApplicationKt | Starting KnowMySelfApplicationKt using Java 11.0.15 on DESKTOP-H50QSL0 with PID 21840 (D:\JavaServer\shiji\build\classes\kotlin\main started by zs1973 in D:\JavaServer\shiji)
INFO | 2023-06-28 20:52:54.249 | main | knowmyself.KnowMySelfApplicationKt | The following 1 profile is active: "dev"
INFO | 2023-06-28 20:52:55.255 | main | config.RepositoryConfigurationDelegate | Multiple Spring Data modules found, entering strict repository configuration mode
INFO | 2023-06-28 20:52:55.257 | main | config.RepositoryConfigurationDelegate | Bootstrapping Spring Data Redis repositories in DEFAULT mode.
INFO | 2023-06-28 20:52:55.281 | main | config.RepositoryConfigurationDelegate | Finished Spring Data repository scanning in 11 ms. Found 0 Redis repository interfaces.
INFO | 2023-06-28 20:52:55.744 | main | tomcat.TomcatWebServer | Tomcat initialized with port(s): 8081 (http)
Jun 28, 2023 8:52:55 PM org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["http-nio-8081"]
Jun 28, 2023 8:52:55 PM org.apache.catalina.core.StandardService startInternal
信息: Starting service [Tomcat]
Jun 28, 2023 8:52:55 PM org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet engine: [Apache Tomcat/9.0.65]
Jun 28, 2023 8:52:55 PM org.apache.catalina.core.ApplicationContext log
信息: Initializing Spring embedded WebApplicationContext
INFO | 2023-06-28 20:52:55.871 | main | context.ServletWebServerApplicationContext | Root WebApplicationContext: initialization completed in 1589 ms
Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter.
Parsed mapper file: 'file [D:\JavaServer\shiji\build\resources\main\mapper\AttachmentMapper.xml]'
Parsed mapper file: 'file [D:\JavaServer\shiji\build\resources\main\mapper\LikedUgcMapper.xml]'
Parsed mapper file: 'file [D:\JavaServer\shiji\build\resources\main\mapper\UgcMapper.xml]'
Parsed mapper file: 'file [D:\JavaServer\shiji\build\resources\main\mapper\UserMapper.xml]'
INFO | 2023-06-28 20:52:57.928 | main | web.EndpointLinksResolver | Exposing 1 endpoint(s) beneath base path '/actuator'
INFO | 2023-06-28 20:52:57.977 | main | web.PropertySourcedRequestMappingHandlerMapping | Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
____ ____    ___ ____ _  _ ____ _  _ 
[__  |__| __  |  |  | |_/  |___ |\ | 
___] |  |     |  |__| | \_ |___ | \| 
https://sa-token.cc (v1.34.0)
SaLog -->: 全局配置 SaTokenConfig [tokenName=token, timeout=2592000, activityTimeout=604800, isConcurrent=false, isShare=true, maxLoginCount=12, isReadBody=true, isReadHeader=true, isReadCookie=true, isWriteHeader=false, tokenStyle=random-64, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=true, logLevel=trace, logLevelInt=1, jwtSecretKey=null, basic=, currDomain=null, sameTokenTimeout=86400, checkSameToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]] 
SaLog -->: 全局组件 SaJsonTemplate 载入成功: cn.dev33.satoken.spring.json.SaJsonTemplateForJackson
SaLog -->: 全局组件 SaTokenContext 载入成功: cn.dev33.satoken.spring.SaTokenContextForSpring
SaLog -->: 全局组件 SaTokenDao 载入成功: cn.dev33.satoken.dao.SaTokenDaoRedisJackson

,------.                           ,--.  ,--.         ,--.                         
|  .--. '  ,--,--.  ,---.   ,---.  |  '--'  |  ,---.  |  |  ,---.   ,---.  ,--.--. 
|  '--' | ' ,-.  | | .-. | | .-. : |  .--.  | | .-. : |  | | .-. | | .-. : |  .--' 
|  | --'  \ '-'  | ' '-' ' \   --. |  |  |  | \   --. |  | | '-' ' \   --. |  |    
`--'       `--`--' .`-  /   `----' `--'  `--'  `----' `--' |  |-'   `----' `--'    
                   `---'                                   `--'                        is intercepting.

Jun 28, 2023 8:52:58 PM org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-nio-8081"]
INFO | 2023-06-28 20:52:58.496 | main | tomcat.TomcatWebServer | Tomcat started on port(s): 8081 (http) with context path ''
WARN | 2023-06-28 20:52:58.510 | main | context.AnnotationConfigServletWebServerApplicationContext | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
INFO | 2023-06-28 20:52:58.552 | main | pool.DruidDataSource | {dataSource-0} closing ...
Jun 28, 2023 8:52:58 PM org.apache.coyote.AbstractProtocol pause
信息: Pausing ProtocolHandler ["http-nio-8081"]
Jun 28, 2023 8:52:58 PM org.apache.catalina.core.StandardService stopInternal
信息: Stopping service [Tomcat]
Jun 28, 2023 8:52:58 PM org.apache.coyote.AbstractProtocol stop
信息: Stopping ProtocolHandler ["http-nio-8081"]
Jun 28, 2023 8:52:58 PM org.apache.coyote.AbstractProtocol destroy
信息: Destroying ProtocolHandler ["http-nio-8081"]
INFO | 2023-06-28 20:52:58.739 | main | logging.ConditionEvaluationReportLoggingListener | 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
ERROR | 2023-06-28 20:52:58.761 | main | boot.SpringApplication | Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.22.jar:5.3.22]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) [spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) [spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) [spring-boot-2.7.2.jar:2.7.2]
	at com.planet.knowmyself.KnowMySelfApplicationKt.main(KnowMySelfApplication.kt:17) [main/:?]
Caused by: java.lang.NullPointerException
	at springfox.documentation.spi.service.contexts.Orderings$8.compare(Orderings.java:112) ~[springfox-spi-2.9.2.jar:null]
	at springfox.documentation.spi.service.contexts.Orderings$8.compare(Orderings.java:109) ~[springfox-spi-2.9.2.jar:null]
	at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:37) ~[guava-20.0.jar:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1441) ~[?:?]
	at com.google.common.collect.Ordering.sortedCopy(Ordering.java:855) ~[guava-20.0.jar:?]
	at springfox.documentation.spring.web.plugins.WebMvcRequestHandlerProvider.requestHandlers(WebMvcRequestHandlerProvider.java:57) ~[springfox-spring-web-2.9.2.jar:null]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:138) ~[springfox-spring-web-2.9.2.jar:null]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:135) ~[springfox-spring-web-2.9.2.jar:null]
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750) ~[guava-20.0.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[guava-20.0.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[guava-20.0.jar:?]
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:52) ~[guava-20.0.jar:?]
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50) ~[guava-20.0.jar:?]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:249) ~[guava-20.0.jar:?]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209) ~[guava-20.0.jar:?]
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:614) ~[guava-20.0.jar:?]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:111) ~[springfox-spring-web-2.9.2.jar:null]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:96) ~[springfox-spring-web-2.9.2.jar:null]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167) ~[springfox-spring-web-2.9.2.jar:null]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.22.jar:5.3.22]
	... 14 more
与目标 VM 断开连接, 地址为: ''127.0.0.1:55655'，传输: '套接字''

进程已结束,退出代码1

**Comment by zs1973** [comment]
implementation("org.redisson:redisson-spring-boot-starter:xx.xx.xx"){
        //避免和swagger2的启动器发生冲突
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-actuator'
    }
