### ISSUE TITLE
spring boot 2.6.4 with redisson 3.17.1 : zRevRangeByLex command will throw StackOverflow error

### ISSUE THREAD

**Issue by teletes** [redisson/redisson#5142]
I am using spring boot 2.6.4 with redisson 3.17.1 and I am using the default RedisTemplate (redissonConnectionFactory). 

But StackOverflow error when runing this: 
`redisTemplate.boundZSetOps(SELL_BOARD_KEY).reverseRangeByLex(range, limit);` 

could you please share any help in this regard

This is my test code.
```java
public class DemoTest {

  private static final String SELL_BOARD_KEY = "sell_board";
  @Autowired
  private RedisTemplate redisTemplate;
  @Test
  public void rankList() {
    Set<TypedTuple> range = redisTemplate.boundZSetOps(SELL_BOARD_KEY)
        .reverseRangeByLex(Range.range().gt(0).lt(500)
            , Limit.limit().count(10));
    range.stream().forEach(item -> {
      System.out.println(
          "name：" + Objects.requireNonNull(item.getValue()) + " ==== score："
              + item.getScore());
    });
  }
}
```
Error is 
```
java.lang.StackOverflowError
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zRevRangeByLex(DefaultedRedisConnection.java:1147)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zRevRangeByLex(DefaultedRedisConnection.java:1147)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zRevRangeByLex(DefaultedRedisConnection.java:1147)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zRevRangeByLex(DefaultedRedisConnection.java:1147)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zRevRangeByLex(DefaultedRedisConnection.java:1147)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zRevRangeByLex(DefaultedRedisConnection.java:1147)
```

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5144 Thank you for report!
