### ISSUE TITLE
Unit Test failures

### ISSUE THREAD

**Issue by zcxsythenew** [redisson/redisson#5152]
# Description

`testCancelAndInterruptWithFixedDelay` throws exception below.

```text
2023.07.05 13:18:16.174 ERROR RedissonExecutorRemoteService : Can't execute: RemoteServiceRequest [requestId=36489754196e12b73da86736afd31adf, methodName=scheduleWithFixedDelay, signature=[-8380590311472450156, -6316559224692332948], args=[org.redisson.executor.params.ScheduledWithFixedDelayParameters@4d40cd77], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1688534290976]
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:107)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:434)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.redisson.client.RedisException: java.lang.InterruptedException
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:114)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonBucket.set(RedissonBucket.java:169)
	at org.redisson.executor.ScheduledLongRepeatableTask.run(ScheduledLongRepeatableTask.java:31)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:341)
	at org.redisson.executor.TasksRunnerService.scheduleWithFixedDelay(TasksRunnerService.java:182)
	... 12 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:110)
	... 17 common frames omitted
interrupted 5284868505
2023.07.05 13:18:27.569 ERROR RedissonExecutorRemoteService : Can't execute: RemoteServiceRequest [requestId=f282c580208fd28b591743264f9d1715, methodName=scheduleWithFixedDelay, signature=[-8380590311472450156, -6316559224692332948], args=[org.redisson.executor.params.ScheduledWithFixedDelayParameters@3e45b000], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1688534302377]
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:107)
	at org.redisson.RedissonRemoteService.lambda$executeMethod$11(RedissonRemoteService.java:434)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.redisson.client.RedisException: java.lang.InterruptedException
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:114)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonBucket.set(RedissonBucket.java:169)
	at org.redisson.executor.ScheduledLongRepeatableTask.run(ScheduledLongRepeatableTask.java:31)
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:341)
	at org.redisson.executor.TasksRunnerService.scheduleWithFixedDelay(TasksRunnerService.java:182)
	... 12 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:110)
	... 17 common frames omitted
2023.07.05 13:18:31.315 INFO  RedissonNode : Redisson node has been shutdown successfully

org.opentest4j.AssertionFailedError: 
expected: 0L
 but was: 1L
Expected :0L
Actual   :1L
<Click to see difference>


	at org.redisson.executor.RedissonScheduledExecutorServiceTest.testCancelAndInterruptWithFixedDelay(RedissonScheduledExecutorServiceTest.java:514)


```

# Discussion

This test case has several problems.

## 1. Impossible database access

The Runnable `ScheduledLongRepeatableTask` is problematic. The code is shown below.

```java
    @Override
    public void run() {
        if (redisson.getAtomicLong(counterName).incrementAndGet() == 3) {
            for (long i = 0; i < Long.MAX_VALUE; i++) {
                if (Thread.currentThread().isInterrupted()) {
                    System.out.println("interrupted " + i);
                    redisson.getBucket(objectName).set(i);
                    return;
                }
            }
        }
    }
```

The code may seem logically fine. However, if a thread has been interrupted, it is impossible to access Redis database, otherwise `RedisException` will be thrown with message `java.lang.InterruptedException`. Therefore we may consider clearing the interruption flag and setting it back later if needed.

## 2. Fail to get bucket

In `ScheduledLongRepeatableTask`, we stored a long number into Redis database.

```java
            for (long i = 0; i < Long.MAX_VALUE; i++) {
                if (interrupted) {
                    System.out.println("interrupted " + i);
                    redisson.getBucket(objectName).set(i);
                    return;
                }
            }
```

However, when we get this bucket in `testCancelAndInterruptWithFixedDelay`, it is null.

```java
assertThat(redisson.<Long>getBucket("executed1").get()).isBetween(1000L, Long.MAX_VALUE);
```

```text
java.lang.AssertionError: 
Expecting actual not to be null

	at org.redisson.executor.RedissonScheduledExecutorServiceTest.testCancelAndInterruptWithFixedDelay(RedissonScheduledExecutorServiceTest.java:496)
```

This problem may be related to `Codec`. An alternative solution is simply to replace `getBucket` with `getAtomicLong`.

## 3. Unexpected Redis key

At the end of `testCancelAndInterruptWithFixedDelay`, we deleted keys `counter`, `executed1`, `executed2` and hope that the Redis database will now be empty. However, unfortunately there is still another key that still exists:

```text
{remote_response}:445098f3-e170-41f5-91cc-ed1885e4fb72
```

This key seems to be random and can hardly known in the code of the UT. We have to delete all the keys in another way:

```java
redisson.getKeys().delete(redisson.getKeys().getKeysStream().toArray(String[]::new));
```

**Comment by mrniko** [comment]
Unable to reproduce. Only testDelay() method fails due to reflection restrictions.

**Comment by zcxsythenew** [comment]
@mrniko That can't be possible. In #5150 , you said you met an exception and the stacktrace is shown below:

```text
2023.07.05 07:07:53.153 ERROR RedissonExecutorRemoteService : Can't execute: RemoteServiceRequest [requestId=2672192d7c9e70393305282d2bfb075b, methodName=schedule, signature=[-1302744695517659028, 3362697138470104627], args=[org.redisson.executor.params.ScheduledCronExpressionParameters@1a3e8059], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1688530068040]
java.lang.reflect.InvocationTargetException: null
	... omiited
Caused by: org.redisson.client.RedisException: java.lang.InterruptedException
	at org.redisson.executor.ScheduledLongRepeatableTask.run(ScheduledLongRepeatableTask.java:31)
	... omitted
Caused by: java.lang.InterruptedException: null
	... omitted
```

It says Line 31 of `ScheduledLongRepeatableTask` gets into trouble because of interrupted exception. How can you pass the case `testCancelAndInterruptWithFixedDelay` smoothly without seeing this message?

**Comment by mrniko** [comment]
in my report the problem was in testCancelAndInterruptCronExpression() and not in testCancelAndInterruptWithFixedDelay().

**Comment by zcxsythenew** [comment]
Yes, but you can see their UT codes are similar, and they both use `ScheduledLongRepeatableTask`. Also, in your report, the issue is less likely to be related to cron schedule, but more related to `ScheduledLongRepeatableTask` and its interruption.

I run the test case `testCancelAndInterruptWithFixedDelay` with IntelliJ IDEA and JDK 17, on macOS. What's your test environment? @mrniko

**Comment by mrniko** [comment]
@zcxsythenew 

Win 10, Intelij IDEA, JDK "17.0.3.1"

![image](https://github.com/redisson/redisson/assets/1104661/9a906b4c-ee02-48da-bc10-07650c477ae1)

**Comment by mrniko** [comment]
> Have you tried to run only this case?

The error is reproduced in this case.
