### ISSUE TITLE
How to set up can completely solve the following error, and there are many errors in the log:

### ISSUE THREAD

**Issue by fredeason** [redisson/redisson#5162]
org.springframework.dao.QueryTimeoutException: Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@598742765 [redisClient=[addr=redis://*.*.*.*:6379], channel=[id: 0xe6e88074, L:/10.8.0.18:59155 - R:/*.*.*.*:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2de364ef(incomplete)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (RPOP), params: [[115, 113, 70, 97, 108, 117, 116, 82, 101, 99, ...]] after 0 retry attempts; nested exception is org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@598742765 [redisClient=[addr=redis://*.*.*.*:6379], channel=[id: 0xe6e88074, L:/10.8.0.18:59155 - R:/*.*.*.*:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2de364ef(incomplete)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (RPOP), params: [[115, 113, 70, 97, 108, 117, 116, 82, 101, 99, ...]] after 0 retry attempts
    at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48)
    at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
    at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
    at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:197)
    at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:192)
    at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:358)
    at org.redisson.spring.data.connection.RedissonConnection.write(RedissonConnection.java:724)
    at org.redisson.spring.data.connection.RedissonConnection.rPop(RedissonConnection.java:761)
    at org.springframework.data.redis.connection.DefaultStringRedisConnection.rPop(DefaultStringRedisConnection.java:894)
    at org.springframework.data.redis.core.DefaultListOperations$4.inRedis(DefaultListOperations.java:225)
    at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:222)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189)
    at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
    at org.springframework.data.redis.core.DefaultListOperations.rightPop(DefaultListOperations.java:221)

Caused by: org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@598742765 [redisClient=[addr=redis://*.*.*.*:6379], channel=[id: 0xe6e88074, L:/10.8.0.18:59155 - R:/*.*.*.*:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2de364ef(incomplete)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (RPOP), params: [[115, 113, 70, 97, 108, 117, 116, 82, 101, 99, ...]] after 0 retry attempts
    at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:208)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    ... 1 common frames omitted

The configuration in yml is this:

timeout: 3000
connectTimeout: 10000
idleConnectionTimeout: 10000
retryAttempts: 0
retryInterval: 1500
subscriptionsPerConnection: 5
clientName: null
subscriptionConnectionMinimumIdleSize: 1
subscriptionConnectionPoolSize: 32
connectionMinimumIdleSize: 16
connectionPoolSize: 32
database: 5
dnsMonitoringInterval: 5000

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception
