### ISSUE TITLE
NullPointer when trying to access activeviews in JSF

### ISSUE THREAD

**Issue by marcelocastrillo** [redisson/redisson#5191]
I'm getting a nullpointerexception when processing the activeviewmap using jsf

20-Jul-2023 12:48:27.859 SEVERE [http-nio-8080-exec-3] com.sun.faces.application.view.FaceletViewHandlingStrategy.handleRenderException Error Rendering View[/index.xhtml]
	org.redisson.client.RedisException: Unexpected exception while processing command
		at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:299)
		at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:116)
		at org.redisson.RedissonObject.get(RedissonObject.java:90)
		at org.redisson.RedissonMap.get(RedissonMap.java:654)
		at org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:121)
		at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:102)
		at com.sun.faces.context.SessionMap.get(SessionMap.java:118)
		at com.sun.faces.application.view.ViewScopeManager.processPostConstructViewMap(ViewScopeManager.java:284)
		at com.sun.faces.application.view.ViewScopeManager.processEvent(ViewScopeManager.java:244)
		at com.sun.faces.application.view.ViewScopeEventListener.processEvent(ViewScopeEventListener.java:68)
		at javax.faces.event.SystemEvent.processListener(SystemEvent.java:147)
		at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:134)
		at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2292)
		at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2265)
		at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:344)
		at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:761)
		at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:761)
		at javax.faces.component.UIViewRoot.getViewMap(UIViewRoot.java:1702)
		at com.sun.faces.application.view.ViewScopeContextManager.createBean(ViewScopeContextManager.java:149)
		at com.sun.faces.application.view.ViewScopeContext.get(ViewScopeContext.java:137)
		at org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:84)
		at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
		at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
		at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
		at org.jboss.weld.module.web.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
		at org.jboss.weld.module.web.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
		at org.jboss.weld.environment.servlet.util.ForwardingELResolver.getValue(ForwardingELResolver.java:49)
		at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
		at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:180)
		at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:208)
		at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:93)
		at org.apache.el.parser.AstValue.getValue(AstValue.java:136)
		at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
		at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
		at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:200)
		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:187)
		at javax.faces.component.UIOutput.getValue(UIOutput.java:179)
		at javax.faces.component.UIInput.getValue(UIInput.java:311)
		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:105)
		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:69)
		at org.primefaces.component.inputtext.InputTextRenderer.encodeMarkup(InputTextRenderer.java:92)
		at org.primefaces.component.inputtext.InputTextRenderer.encodeEnd(InputTextRenderer.java:62)
		at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:949)
		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:317)
		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:918)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
		at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:918)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
		at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:491)
		at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
		at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
		at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
		at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:155)
		at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
		at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
		at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:89)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
		at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.redisson.tomcat.UsageValve.invoke(UsageValve.java:71)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1650)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: java.lang.NullPointerException
		at java.util.Collections$SynchronizedMap.entrySet(Collections.java:2615)
		at org.redisson.liveobject.core.RedissonObjectBuilder.tryHandleReference(RedissonObjectBuilder.java:393)
		at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:596)
		at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:588)
		at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:576)
		at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:553)
		at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:195)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
		at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:474)
		at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:468)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:395)
		at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		... 1 more
20-Jul-2023 12:48:37.439 SEVERE [http-nio-8080-exec-3] org.primefaces.application.exceptionhandler.PrimeExceptionHandler.logException Unexpected exception while processing command
	org.redisson.client.RedisException: Unexpected exception while processing command
		at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:299)
		at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:116)
		at org.redisson.RedissonObject.get(RedissonObject.java:90)
		at org.redisson.RedissonMap.get(RedissonMap.java:654)
		at org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:121)
		at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:102)
		at com.sun.faces.context.SessionMap.get(SessionMap.java:118)
		at com.sun.faces.application.view.ViewScopeManager.processPostConstructViewMap(ViewScopeManager.java:284)
		at com.sun.faces.application.view.ViewScopeManager.processEvent(ViewScopeManager.java:244)
		at com.sun.faces.application.view.ViewScopeEventListener.processEvent(ViewScopeEventListener.java:68)
		at javax.faces.event.SystemEvent.processListener(SystemEvent.java:147)
		at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:134)
		at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2292)
		at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2265)
		at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:344)
		at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:761)
		at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:761)
		at javax.faces.component.UIViewRoot.getViewMap(UIViewRoot.java:1702)
		at com.sun.faces.application.view.ViewScopeContextManager.createBean(ViewScopeContextManager.java:149)
		at com.sun.faces.application.view.ViewScopeContext.get(ViewScopeContext.java:137)
		at org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:84)
		at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
		at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
		at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
		at org.jboss.weld.module.web.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
		at org.jboss.weld.module.web.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
		at org.jboss.weld.environment.servlet.util.ForwardingELResolver.getValue(ForwardingELResolver.java:49)
		at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
		at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:180)
		at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:208)
		at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:93)
		at org.apache.el.parser.AstValue.getValue(AstValue.java:136)
		at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
		at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
		at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:200)
		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:187)
		at javax.faces.component.UIOutput.getValue(UIOutput.java:179)
		at javax.faces.component.UIInput.getValue(UIInput.java:311)
		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:105)
		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:69)
		at org.primefaces.component.inputtext.InputTextRenderer.encodeMarkup(InputTextRenderer.java:92)
		at org.primefaces.component.inputtext.InputTextRenderer.encodeEnd(InputTextRenderer.java:62)
		at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:949)
		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:317)
		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:918)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
		at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:918)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
		at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:491)
		at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
		at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
		at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
		at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:155)
		at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
		at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
		at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:89)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
		at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.redisson.tomcat.UsageValve.invoke(UsageValve.java:71)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1650)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: java.lang.NullPointerException
		at java.util.Collections$SynchronizedMap.entrySet(Collections.java:2615)
		at org.redisson.liveobject.core.RedissonObjectBuilder.tryHandleReference(RedissonObjectBuilder.java:393)
		at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:596)
		at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:588)
		at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:576)
		at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:553)
		at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:195)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
		at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:474)
		at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:468)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:395)
		at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

configuration:
<Manager className="org.redisson.tomcat.RedissonSessionManager"
		configPath="${catalina.base}/conf/redisson.yaml" 
		readMode="REDIS" updateMode="DEFAULT" broadcastSessionEvents="false"
		keyPrefix=""/>

singleServerConfig:
  address: "redis://127.0.0.1:6379"

**Comment by mrniko** [comment]
Which Redisson version?

**Comment by mrniko** [comment]
There is the issue Kryo5Codec https://github.com/EsotericSoftware/kryo/issues/997

You need to try a different codec.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5545
