### ISSUE TITLE
RLock cannot be aquired after failover in cluster mode

### ISSUE THREAD

**Issue by naffej** [redisson/redisson#5205]
**Expected behavior**
RLock objects like other "R" objects can still be used after failover. The failover transition is fully invisible to the application.

**Actual behavior**
 `RLock.lock()` call throws an exception after failover.  What I noticed is that the address of the old master is in the message.

```
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.RedisExecutor.convertException(RedisExecutor.java:728)
	at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:176)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:294)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:253)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:257)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 127.0.0.1/127.0.0.1:6890
```

**Steps to reproduce or test case**
I wrote a test to demonstrate the problem.  It's easier to reproduce with this. The test contains a `USE_LOCK` flag, which can be used to deactivate the use of the lock. Without it, the test runs perfectly, so the problem must be with the lock itself not configuration.
```java
    @Test
    public void testLockFailoverInCluster() throws Exception {
        final boolean USE_LOCK = true;

        RedisRunner master1 = new RedisRunner().port(6890).randomDir().nosave();
        RedisRunner master2 = new RedisRunner().port(6891).randomDir().nosave();
        RedisRunner master3 = new RedisRunner().port(6892).randomDir().nosave();
        RedisRunner slave1 = new RedisRunner().port(6900).randomDir().nosave();
        RedisRunner slave2 = new RedisRunner().port(6901).randomDir().nosave();
        RedisRunner slave3 = new RedisRunner().port(6902).randomDir().nosave();
        
        ClusterRunner clusterRunner = new ClusterRunner()
                .addNode(master1, slave1)
                .addNode(master2, slave2)
                .addNode(master3, slave3);
        ClusterProcesses process = clusterRunner.run();
        
        Thread.sleep(6000);

        process.getNodes().forEach(n -> {
            Assertions.assertTrue(n.isAlive(), "Redis Cluster failed to deploy");
            System.out.println(n.getRedisServerAddressAndPort() + " is alive=" + n.isAlive());
        });

        Config config = new Config();
        config.useClusterServers()
        .setRetryAttempts(30)
        .setLoadBalancer(new RoundRobinLoadBalancer())
        .setReadMode(ReadMode.SLAVE)
        .setSubscriptionMode(SubscriptionMode.MASTER)
        .addNodeAddress(process.getNodes().stream().findAny().get().getRedisServerAddressAndPort());
        RedissonClient redisson = Redisson.create(config);
       
        RedisProcess master = process.getNodes().stream().filter(x -> x.getRedisServerPort() == master1.getPort()).findFirst().get();

        // worker definition
        Consumer<Long> worker = (Long param) -> {
            for (int i = 0; i < 100; i++) {
                RLock lock = null;
                int checkpoint = 0;
                try {
                    if (USE_LOCK) {
                        lock = redisson.getLock("LOCK_" + param);
                        checkpoint++;
                        lock.lock();
                        checkpoint++;
                    }
                    RMap<Object, Object> map = redisson.getMap("MAP_" + param);
                    checkpoint++;
                    Integer num = (Integer) map.getOrDefault("var", 0);
                    checkpoint++;
                    map.put("var", ++num);
                    checkpoint++;
                } catch (Exception e) {
                    System.err.println("worker(" + param  + ") exception checkpoint: " + checkpoint);
                    e.printStackTrace();
                } finally {
                    if (lock != null)
                        try {
                            lock.unlock();
                        } catch (Exception e) {
                            System.err.println("worker(" + param  + ") unlock failed");
                            e.printStackTrace();
                        }
                }

                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }

                if (i % 10 == 0) {
                    System.out.println("worker(" + param  + ") step: " + i);
                }

            }
        };

        System.out.println("--- STARTING WORKERS ---");

        List<Thread> workers = new LinkedList<>();
        workers.add(new Thread(() -> worker.accept(Thread.currentThread().getId())));
        workers.add(new Thread(() -> worker.accept(Thread.currentThread().getId())));
        workers.add(new Thread(() -> worker.accept(Thread.currentThread().getId())));
        workers.add(new Thread(() -> worker.accept(Thread.currentThread().getId())));
        workers.add(new Thread(() -> worker.accept(Thread.currentThread().getId())));
        workers.forEach(Thread::start);
        Thread.sleep(5000);

        Set<InetSocketAddress> oldMasters = new HashSet<>();
        Collection<RedisClusterMaster> masterNodes = redisson.getRedisNodes(RedisNodes.CLUSTER).getMasters();
        for (RedisClusterMaster clusterNode : masterNodes) {
            oldMasters.add(clusterNode.getAddr());
        }

        System.out.println("--- STOP MASTER " + master.getRedisServerAddressAndPort() + " ---");
        master.stop();
        System.out.println("--- MASTER " + master.getRedisServerAddressAndPort() + " has been stopped! ---");
        Thread.sleep(10000);

        RedisProcess newMaster = null;
        Collection<RedisClusterMaster> newMasterNodes = redisson.getRedisNodes(RedisNodes.CLUSTER).getMasters();
        for (RedisClusterMaster clusterNode : newMasterNodes) {
            if (!oldMasters.contains(clusterNode.getAddr())) {
                newMaster = process.getNodes().stream().filter(x -> x.getRedisServerPort() == clusterNode.getAddr().getPort()).findFirst().get();
                break;
            }
        }

        assertThat(newMaster).isNotNull();
        System.out.println("--- NEW MASTER PROMOTED ---");

        workers.forEach(t -> {
            try {
                t.join();
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        });
        System.out.println("--- WORKERS FINISHED ---");

        RMap<Object, Object> map1 = redisson.getMap("MAP_" + workers.get(0).getId());
        RMap<Object, Object> map2 = redisson.getMap("MAP_" + workers.get(1).getId());
        RMap<Object, Object> map3 = redisson.getMap("MAP_" + workers.get(2).getId());
        RMap<Object, Object> map4 = redisson.getMap("MAP_" + workers.get(3).getId());
        RMap<Object, Object> map5 = redisson.getMap("MAP_" + workers.get(4).getId());
        int v1 = (Integer) map1.get("var");
        int v2 = (Integer) map2.get("var");
        int v3 = (Integer) map3.get("var");
        int v4 = (Integer) map4.get("var");
        int v5 = (Integer) map5.get("var");

        System.out.println("--- SHUTDOWN REDIS ---");
        redisson.shutdown();
        process.shutdown();

        System.out.println("var1: " + v1);
        System.out.println("var2: " + v2);
        System.out.println("var3: " + v3);
        System.out.println("var4: " + v4);
        System.out.println("var5: " + v5);

        Assertions.assertEquals(100, v1);
        Assertions.assertEquals(100, v2);
        Assertions.assertEquals(100, v3);
        Assertions.assertEquals(100, v4);
        Assertions.assertEquals(100, v5);

    }
```

**Redis version**
3.23.2
**Redisson version**
7.0.11
**Redisson configuration**
See the test code above

Test logs included.
[test_logs.txt](https://github.com/redisson/redisson/files/12195941/test_logs.txt)

**Comment by mrniko** [comment]
Thanks for the provided test. Unable to reproduce. Below is the output.

```
var1: 100
var2: 100
var3: 100
var4: 100
var5: 100
```
