### ISSUE TITLE
tomcat9 is not running with redisson

### ISSUE THREAD

**Issue by taavit21** [redisson/redisson#5211]
Hello!

I´ve used redisson with haproxy for a quite a while now and now i am experincing problems. 
tomcat9 is not running and the only relevant log file is:

```
31-Jul-2023 14:40:34.187 INFO [main] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
31-Jul-2023 14:40:34.210 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
31-Jul-2023 14:41:16.879 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'apiServlet'
31-Jul-2023 14:41:20.037 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'pdfServlet'
31-Jul-2023 14:41:20.243 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'restServlet'
31-Jul-2023 14:41:20.519 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'csvServlet'
31-Jul-2023 14:41:20.685 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'excelServlet'
31-Jul-2023 14:41:20.906 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'uncachedResourceServlet'
31-Jul-2023 14:41:20.982 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'resourceServlet'
31-Jul-2023 14:41:33.155 SEVERE [http-nio-8080-exec-33] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [uncachedResourceServlet] in context with path [/jvis] threw exception
        org.redisson.client.RedisException: Unexpected exception while processing command
                at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:299)
                at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:116)
                at org.redisson.RedissonObject.get(RedissonObject.java:90)
                at org.redisson.RedissonMap.readAllMap(RedissonMap.java:878)
                at org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:132)
                at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:102)
                at org.springframework.security.web.context.HttpSessionSecurityContextRepository.readSecurityContextFromSession(HttpSessionSecurityContextRepository.java:182)
                at org.springframework.security.web.context.HttpSessionSecurityContextRepository.loadContext(HttpSessionSecurityContextRepository.java:112)
                at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:100)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
                at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
                at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
                at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
                at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:62)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
                at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:750)
        Caused by: com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
authorities (org.springframework.security.cas.authentication.CasAuthenticationToken)
authentication (org.springframework.security.core.context.SecurityContextImpl)
                at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:146)
                at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
                at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:799)
                at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:124)
                at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
                at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880)
                at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144)
                at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:393)
                at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:441)
                at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
                at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
                at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
                at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
                at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                ... 1 more
        Caused by: java.lang.UnsupportedOperationException
                at java.util.Collections$UnmodifiableCollection.add(Collections.java:1057)
                at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:241)
                at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:44)
                at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:799)
                at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:124)
                ... 31 more
```

I am running redisson-3.23.2 version.

**Comment by mrniko** [comment]
Try a different codec like SerializationCodec?

**Comment by mrniko** [comment]
As option you need to extend Kryo5Codec, override createKryo() and add follow line:

```kryo.addDefaultSerializer(CasAuthenticationToken.class, new JavaSerializer());```

**Comment by taavit21** [comment]
Your solution about changing codec worked.

I use now:

singleServerConfig:
    address: "redis://IP:6379"
codec: !<org.redisson.codec.SerializationCodec> {}
