### ISSUE TITLE
Reflection Issue since release 3.23.1 with Quarkus native build

### ISSUE THREAD

**Issue by TobiasWnl** [redisson/redisson#5213]
**Expected behavior:**
The Quarkus project should build successfully with reddisson-quarkus-30 version 3.23.1, similar to the successful build with version 3.23.0.

**Actual behavior**
When using reddisson-quarkus-30 version 3.23.1, the build process fails with the following error:
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.redisson.codec.LZ4Codec.<init>(LZ4Codec.java:54)
Parsing context:
   at com.oracle.svm.core.code.FactoryMethodHolder.LZ4Codec_constructor_70a6def4cf8693d59044a1e0062043cc0dbdf52f(generated:0)
   at static root method.(Unknown Source)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:178)
        ... 15 more
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: net.jpountz.lz4.LZ4Factory. This error is reported at image build time because class org.redisson.codec.LZ4Codec is registered for linking at image build time by command line
        at parsing org.redisson.codec.LZ4Codec.<init>(LZ4Codec.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2536)
        ... 46 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: net.jpountz.lz4.LZ4Factory. This error is reported at image build time because class org.redisson.codec.LZ4Codec is registered for linking at image build time by command line
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:515)
        ... 51 more

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.core.code.FactoryMethodHolder.LZ4Codec_constructor_ffae5131a21c6eeaaa34cb8c7609e26d6571086f(generated:0)
Parsing context:
   at static root method.(Unknown Source)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:178)
        ... 13 more
Caused by: com.oracle.graal.pointsto.util.AnalysisError: parsing had failed in another thread
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.shouldNotReachHere(AnalysisError.java:173)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsedHelper(AnalysisMethod.java:795)
        ... 27 more
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: net.jpountz.lz4.LZ4Factory. This error is reported at image build time because class org.redisson.codec.LZ4Codec is registered for linking at image build time by command line
        at parsing org.redisson.codec.LZ4Codec.<init>(LZ4Codec.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2536)
        ... 46 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: net.jpountz.lz4.LZ4Factory. This error is reported at image build time because class org.redisson.codec.LZ4Codec is registered for linking at image build time by command line
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:515)
        ... 51 more
```

**Steps to reproduce**

1. Create a Quarkus project with version 3.2.2.Final.
2. Set the reddisson-quarkus-30 version in the pom.xml to 3.23.1.
```
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson-quarkus-30</artifactId>
    <version>3.23.1</version>
</dependency>
```
3. Build the project using one of those commands:
```
mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true

quarkus build --native "-DskipTests=true" "-Dquarkus.native.container-build=true"
```
4. Observe the build failure due to the reported error.

**Redisson version**
redisson-quarkus-30 version 3.23.1

**Additional information:**

- The build process works without any issues when using reddisson-quarkus-30 version 3.23.0, indicating that the problem might be specific to version 3.23.1.
- The error appears to be related to unresolved types during parsing, specifically concerning net.jpountz.lz4.LZ4Factory.

**System information:**

- Java version: 17.0.8+7, vendor version: Mandrel-23.0.1.2-Final
- Graal compiler: optimization level: 2, target machine: x86-64-v3
- C compiler: gcc (redhat, x86_64, 8.5.0)

**Comment by TobiasWnl** [comment]
**Adding LZ4**

When I add lz4-java to my dependecies...
```
<dependency>
    <groupId>org.lz4</groupId>
    <artifactId>lz4-java</artifactId>
    <version>1.8.0</version>
</dependency>
```
... I get a similar error as before but with Snappy:
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.redisson.codec.SnappyCodecV2$2.encode(SnappyCodecV2.java:83)
Parsing context:
   at org.redisson.command.CommandAsyncService.encodeMapKey(CommandAsyncService.java:651)
   ...
   at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_3148eece06270530b6e0d4d60311411342c82698(generated:0)
   at static root method.(Unknown Source)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:178)
        ... 13 more
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.xerial.snappy.Snappy. Th error is reported at image build time because class org.redisson.codec.SnappyCodecV2$2 is registered for linking at image build time by command line
        at parsing org.redisson.codec.SnappyCodecV2$2.encode(SnappyCodecV2.java:87)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2536)
        ... 34 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.xerial.snappy.Snappy. This error is reported at image build time because class org.redson.codec.SnappyCodecV2$2 is registered for linking at image build time by command line
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:515)
        ... 39 more
```

**Adding Snappy**

So I added snappy-java to my depndencies
```
<dependency>
    <groupId>org.xerial.snappy</groupId>
    <artifactId>snappy-java</artifactId>
    <version>1.1.10.3</version>
</dependency>
```
And I got a different kind of error
```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-1.94.Final.jar' with 'io.netty.buffer.ByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufAllocator.class'). To see why io.netty.buffer.ByteBufAllocator got initialized use trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buer-4.1.94.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocat got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.nettyetty-buffer-4.1.94.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.bufferbstractReferenceCountedByteBuf
io.netty.buffer.PooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledUnsafeDirectByteBufot initialized use --trace-class-initialization=io.netty.buffer.PooledUnsafeDirectByteBuf
io.netty.buffer.PooledByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledByteBuf got initialized use --tce-class-initialization=io.netty.buffer.PooledByteBuf
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.94inal.jar' with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialation=io.netty.buffer.ByteBufUtil
To see how the classes got initialized, use --trace-class-initialization=io.netty.buffer.ByteBufAllocator,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.AbstractReferenceCountedByteBuf,io.netty.buffer.PledUnsafeDirectByteBuf,io.netty.buffer.PooledByteBuf,io.netty.buffer.ByteBufUtil
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-1.94.Final.jar' with 'io.netty.buffer.ByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufAllocator.class'). To see why io.netty.buffer.ByteBufAllocator got initialized use trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buer-4.1.94.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'PooledByteBufAllocator.class'). To see why io.netty.buffer.PooledByteBufAllocat got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.nettyetty-buffer-4.1.94.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.bufferbstractReferenceCountedByteBuf
io.netty.buffer.PooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledUnsafeDirectByteBufot initialized use --trace-class-initialization=io.netty.buffer.PooledUnsafeDirectByteBuf
io.netty.buffer.PooledByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.PooledByteBuf got initialized use --tce-class-initialization=io.netty.buffer.PooledByteBuf
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.94inal.jar' with 'io.netty.buffer.ByteBufUtil' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufUtil.class'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialation=io.netty.buffer.ByteBufUtil
To see how the classes got initialized, use --trace-class-initialization=io.netty.buffer.ByteBufAllocator,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.AbstractReferenceCountedByteBuf,io.netty.buffer.PledUnsafeDirectByteBuf,io.netty.buffer.PooledByteBuf,io.netty.buffer.ByteBufUtil
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.checkDelayedInitialization(ProvenSafeClassInitializationSupport.java:277)
        ... 12 more
```

**Conclusion**
I don't want to have countless unused dependencies attached to my project.

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by TobiasWnl** [comment]
I tried the new version 3.23.3 and the errors were fixed. Thanks a lot!
