### ISSUE TITLE
RScheduledExecutorService with native image compile，java.lang.NoSuchMethodException writeReplace()

### ISSUE THREAD

**Issue by elevenkongqian** [redisson/redisson#5257]
Does RScheduledExecutorService support native image compile？

os: centos7
graalvm：graalvm-ee-java17-22.3.2
springboot:3.1.2
redisson:3.23.2

RedissonConfigBean:
`
@Bean(destroyMethod = "shutdown")
public RedissonNode redissonNode(RedissonClient redissonClient, BeanFactory beanFactory) {
    RedissonNodeConfig nodeConfig = new RedissonNodeConfig(redissonClient.getConfig());
    nodeConfig.setExecutorServiceWorkers(Collections.singletonMap(WeiXinRefreshAccessTokenSchedule.executorServiceName, 1));
    nodeConfig.setBeanFactory(beanFactory);
    RedissonNode node = RedissonNode.create(nodeConfig, redissonClient);
    node.start();
    log.info("redissonNode is start,node id:{}", node.getId());
    return node;
}
`

my Schedule bean:
`
@Slf4j
@RequiredArgsConstructor
@Service
public class WeiXinRefreshAccessTokenSchedule {

    public static final String executorServiceName = "got:account:weixin:refreshAccessTokenSchedule";

    private final RedissonClient redissonClient;

    private final BeanFactory beanFactory;

    @Value("${weixin.refreshAccessToken.cronSchedule:0 0/1 * * * ?}")
    private String refreshAccessTokenCronSchedule;

    @PostConstruct
    public void initRefreshAccessTokenSchedule() {
        ExecutorOptions options = ExecutorOptions.defaults();
        options.taskRetryInterval(0, TimeUnit.MINUTES);
        RScheduledExecutorService executorService = redissonClient.getExecutorService(executorServiceName, options);
        int taskCount = executorService.getTaskCount();
        int countActiveWorkers = executorService.countActiveWorkers();
        log.info("initRefreshAccessTokenSchedule taskCount:{},countActiveWorkers:{}", taskCount, countActiveWorkers);
        if (taskCount == 0) {
            WorkerOptions workerOptions = WorkerOptions.defaults();
            workerOptions.workers(1);
            workerOptions.beanFactory(beanFactory);
            workerOptions.taskTimeout(10, TimeUnit.MINUTES);
            executorService.registerWorkers(workerOptions);
            RExecutorFuture<?> executorFuture = executorService.schedule(new WeiXinRefreshAccessTokenRunnable(), CronSchedule.of(refreshAccessTokenCronSchedule));
            String taskId = executorFuture.getTaskId();
            log.info("initRefreshAccessTokenSchedule start schedule, taskId:{}", taskId);
        }

    }

}
`
and Runnable Bean:
`
@Slf4j
public class WeiXinRefreshAccessTokenRunnable implements Runnable, Serializable {

    @Autowired
    private WeiXinClient weiXinClient;

    @Override
    public void run() {
        log.info("WeiXinRefreshAccessTokenRunnable run");
        String accessToken = weiXinClient.getAccessToken();
        log.info("accessToken:{}", accessToken);
    }
}
`
reflect-config.json:
`
[
  {
    "name": "com.account.schedule.WeiXinRefreshAccessTokenSchedule",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  },
  {
    "name": "com.schedule.WeiXinRefreshAccessTokenRunnable",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  },
  .....
`
serialization-config.json
`
[
  {
    "name": "com.schedule.WeiXinRefreshAccessTokenRunnable"
  }
]
`

used  maven compile: mvn -l mvn-compile.log -X -P prod --batch-mode -T8 -DskipTests=true -Pnative clean native:compile
and run native application error is:
`
[2023-08-16 18:32:06 - ERROR main - - SpringApplication.java- reportFailure - 824] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'weiXinRefreshAccessTokenSchedule': Lambda should implement java.io.Serializable interface
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at com.sincetimes.games.got.account.Application.main(Application.java:21)
Caused by: java.lang.IllegalArgumentException: Lambda should implement java.io.Serializable interface
        at org.redisson.RedissonExecutorService.getClassBody(RedissonExecutorService.java:437)
        at org.redisson.RedissonExecutorService.scheduleAsync(RedissonExecutorService.java:1209)
        at org.redisson.RedissonExecutorService.schedule(RedissonExecutorService.java:1200)
        at org.redisson.RedissonExecutorService.schedule(RedissonExecutorService.java:906)
        at com.schedule.WeiXinRefreshAccessTokenSchedule.initRefreshAccessTokenSchedule(WeiXinRefreshAccessTokenSchedule.java:47)
        at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1874)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1827)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        ... 14 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.schedule.WeiXinRefreshAccessTokenRunnable.writeReplace()
        at java.base@17.0.7/java.lang.Class.getDeclaredMethod(DynamicHub.java:2675)
        at org.redisson.RedissonExecutorService.getClassBody(RedissonExecutorService.java:433)
        ... 22 common frames omitted
`
![image](https://github.com/redisson/redisson/assets/39029094/3d90625b-5ec1-4f91-8660-b00f07d3a2c9)

May I know how to resolve this error?

**Comment by elevenkongqian** [comment]
error with RedissonExecutorService :
![image](https://github.com/redisson/redisson/assets/39029094/477aafe5-1aff-4a0d-a3e0-a9f4c3983cec)
Does this method support native compile？

**Comment by mrniko** [comment]
I think no. Let me know if you found any way.
