### ISSUE TITLE
how to config redisson in spring boot starter ?

### ISSUE THREAD

**Issue by athinboy** [redisson/redisson#5258]
according to :
https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter#spring-boot-starter
https://github.com/redisson/redisson/wiki/2.-Configuration#262-single-instance-yaml-config-format

![image](https://github.com/redisson/redisson/assets/10301079/dc3c722c-a68d-4961-974e-901a6a8f987f)

But,the application can not startup:

Caused by: java.lang.IllegalArgumentException: Can't parse config
	at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:138)
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$3782dba3.CGLIB$redisson$2(<generated>)
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$3782dba3$$FastClassBySpringCGLIB$$3c2bdb2a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$3782dba3.redisson(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 58 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3854)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:116)
	at org.redisson.config.Config.fromJSON(Config.java:589)
	at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:136)

![image](https://github.com/redisson/redisson/assets/10301079/d9fb4ec3-27bf-4bfd-b83e-4bf69192adb9)

![image](https://github.com/redisson/redisson/assets/10301079/f1256a4a-66c5-4538-885d-e54f6b7d7829)

**Comment by mrniko** [comment]
you missed: "config: |" symbol

**Comment by athinboy** [comment]
@mrniko Thanks!
