### ISSUE TITLE
Empty initialisation sequence error when using JNDI with RedissonClient connection

### ISSUE THREAD

**Issue by dkswnkk** [redisson/redisson#5267]
### RedisConfig.java
```java
@Configuration
@EnableRedisRepositories(enableKeyspaceEvents = RedisKeyValueAdapter.EnableKeyspaceEvents.ON_STARTUP)
public class RedisConfig {
...
    private static final String REDISSON_HOST_PREFIX = "rediss://";
    private final ObjectMapper objectMapper;
    
    @Value("${redis.host}")
    private String redisHost;
    
    @Value("${redis.port}")
    private Integer redisPort;
    
    @Value("${redis.database}")
    private int redisSessionDatabase;
   
    @Value("${redis.password}")
    private String redisPassword;

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        LettuceConnectionFactory connectionFactory =
                new LettuceConnectionFactory(redisStandaloneConfiguration(), lettuceClientConfiguration());
        connectionFactory.setDatabase(this.redisSessionDatabase);
        
        return connectionFactory;
    }

    @Bean
    RedisStandaloneConfiguration redisStandaloneConfiguration() {
        RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();
        redisStandaloneConfiguration.setHostName(this.redisHost);
        redisStandaloneConfiguration.setPort(this.redisPort);
        redisStandaloneConfiguration.setPassword(this.redisPassword);
        
        return redisStandaloneConfiguration;
    }

    @Bean
    LettuceClientConfiguration lettuceClientConfiguration() {
        return LettuceClientConfiguration
                .builder()
                .useSsl()
                .build();
    }

    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer()
                .setAddress(REDISSON_HOST_PREFIX + this.redisHost + ":" + this.redisPort)
                .setPassword(this.redisPassword)
                .setSslEnableEndpointIdentification(true);
                
        return Redisson.create(config);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate() {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory());
        redisTemplate.setKeySerializer(new StringRedisSerializer());

        Jackson2JsonRedisSerializer<String> stringJackson2JsonRedisSerializer = new Jackson2JsonRedisSerializer<>(String.class);
        stringJackson2JsonRedisSerializer.setObjectMapper(objectMapper);
        redisTemplate.setValueSerializer(stringJackson2JsonRedisSerializer);

        return redisTemplate;
    }
    ...
}
```

The only thing I added to the existing config was the RedissonClient.

### Error
```java
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.sql.DataSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value="securityDataSource")}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1394)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 188 common frames omitted
```

### DataSourceConfig
```java
@Slf4j
@Configuration
@RequiredArgsConstructor
public class DataSourceConfig {
   // ... Other definitions


    @Bean
    public DataSource securityDataSource() {
        return getDataSource();
    }

    private DataSource getDataSource() {
        JndiObjectFactoryBean jndi = new JndiObjectFactoryBean();
        jndi.setProxyInterface(DataSource.class);
        jndi.setJndiName(JndiResource.JNDI_NAME);
        jndi.setResourceRef(true);
        try {
            jndi.afterPropertiesSet();
            return (DataSource) jndi.getObject();
        } catch (NamingException ne) {
            log.error(JndiResource.JNDI_NAME, ne);
            return null;
        }
    }
    
    // ... Other definitions
}
```

What's weird is that instead of injecting the DataSource with JNDI from there, I injected it using HikariCP as shown below, and it works fine.

```java
@Slf4j
@Configuration
@RequiredArgsConstructor
public class DataSourceConfig {
   // ... 
   
    public DataSource securityDataSource() {
        return getDataSource();
    }
    
    private DataSource getDataSource() {
        HikariConfig config = new HikariConfig();
        config.setDriverClassName(Driver.class.getName());
        config.setJdbcUrl("url");
        config.setUsername("username");
        config.setPassword("password");
        config.setMaximumPoolSize(size);

        return new HikariDataSource(config);
    }
}
```

We identified the cause.

The root of the problem was in the injection of the ObjectMapper in the RedisConfig. The ServletConfig had an ObjectMapper defined, and the PublicAuthInterceptor contained a PrincipalRepository that required DB access, which caused an error because it tried to access the securityDataSource before it was created.

### ServletConfig.java
```java
@Configuration
@RequiredArgsConstructor
public class ServletConfig implements WebMvcConfigurer {
    //  ... Other definitions

   
    private final PublicAuthInterceptor publicAuthInterceptor;

    @Bean
    public ObjectMapper objectMapper() {
      // ... objectMapper settings
    }

    // ...
}
```

### PublicAuthInterceptor.java
```java
@Slf4j
@Component
@RequiredArgsConstructor
public class PublicAuthInterceptor implements HandlerInterceptor {

 private final PrincipalRepository principalRepository;
    // ...

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        // principalRepository use codes
    }
    
    // ...
}
```

But there are two things I don't understand.

1. both HikariCP and JNDI methods work fine, except for the RedissClient Bean.
2. if I add only the RedissClient Bean, it doesn't work with JNDI's method (it works if I leave out the ObjectMapper Bean)

```java
    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer()
                .setAddress(REDISSON_HOST_PREFIX + this.redisHost + ":" + this.redisPort)
                .setPassword(this.redisPassword)
                .setSslEnableEndpointIdentification(true);
                
        return Redisson.create(config);
    }
```

I was wondering if you could answer my question?

**Comment by mrniko** [comment]
I don't see where you add Redisson in JNDI
