### ISSUE TITLE
NullPointerException with Redisson on Struts Based App

### ISSUE THREAD

**Issue by caseytrumble** [redisson/redisson#5275]
I am in the process of migrating a legacy struts 1 (upgrading or changing struts isn't an option unfortunately) based application from WebLogic to OpenShift. Part of this migration includes moving away from Coherence (tightly coupled with WebLogic) to another session management option, such as Redisson. However, I am seeing some issues with what appears like some interaction between struts and Redisson for some of the pages in the app.
```
javax.servlet.ServletException: BeanUtils.populate
	at org.apache.struts.util.RequestUtils.populate(RequestUtils.java:475) ~[struts-core-1.3.10.jar:1.3.10]
	at org.apache.struts.chain.commands.servlet.PopulateActionForm.populate(PopulateActionForm.java:50) ~[struts-core-1.3.10.jar:1.3.10]
	at org.apache.struts.chain.commands.AbstractPopulateActionForm.execute(AbstractPopulateActionForm.java:60) ~[struts-core-1.3.10.jar:1.3.10]
	at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51) ~[struts-core-1.3.10.jar:1.3.10]
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191) ~[commons-chain-1.2.jar:1.2]
	at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:305) ~[commons-chain-1.2.jar:1.2]
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191) [commons-chain-1.2.jar:1.2]
	at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283) [struts-core-1.3.10.jar:1.3.10]
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913) [struts-core-1.3.10.jar:1.3.10]
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462) [struts-core-1.3.10.jar:1.3.10]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) [servlet-api.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-websocket.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.20.0.jar:2.20.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:9.0.78]
	at org.redisson.tomcat.UsageValve.invoke(UsageValve.java:71) [redisson-tomcat-9-3.23.1.jar:3.23.1]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.78]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.78]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.78]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.78]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-coyote.jar:9.0.78]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.78]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) [tomcat-coyote.jar:9.0.78]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-coyote.jar:9.0.78]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.78]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.78]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.78]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.78]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: java.lang.NullPointerException
	at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:983) ~[commons-beanutils-1.9.4.jar:1.9.4]
	at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:823) ~[commons-beanutils-1.9.4.jar:1.9.4]
	at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:431) ~[commons-beanutils-1.9.4.jar:1.9.4]
	at org.apache.struts.util.RequestUtils.populate(RequestUtils.java:473) ~[struts-core-1.3.10.jar:1.3.10]
````

The issue always appears as a NullPointerException (normally in commons-beanutils) from a `BeanUtils.populate()` call in struts. However, if I disable Redisson then the page works fine. I can see the `org.redisson.tomcat.UsageValve` in the stack trace. The NullPointerException happens before it even gets to my action class for the page. The only way I have gotten the page to work with Redisson running is to change the struts action path scope to request. 
```
<!-- Originally session, testing with request scope -->
<action path="/tab/example"
      type="com.example.actions.ExampleAction"
      name="exampleForm"
      scope="request"
      validate="false">
      <forward name="success" path="/WEB-INF/pages/example/exampleTab.jsp"/>
</action>
```
However, changing this kind of defeats the purpose of using session management. This will cause users to have to relogin between requests/redirects. Has anyone had similar issues with struts and Redisson? Any possible solutions I could try?

**Comment by mrniko** [comment]
Did you try to set readMode = MEMORY?

**Comment by caseytrumble** [comment]
I did play around with some of the RedissonSessionManager properties including setting readMode=MEMORY. It did seem to help with some pages, but others still have the same error. These are the properties I currently am using:
```
<Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="${catalina.base}/conf/redisson.conf"
             keyPrefix="my-app-key"
             readMode="MEMORY"
             updateMode="DEFAULT"
             broadcastSessionUpdates="true" />
```

**Comment by caseytrumble** [comment]
I think I should explain further on my last comment. I found that using the readMode=MEMORY property does work if creating a fresh session. I see a catalina/tomcat log that looks similar to this:
`org.redisson.tomcat.RedissonSessionManager.findSession Session 780E700CDBB0070B5A46BC7F92C47DCC can't be found`

If that shows, then the app behaves as it should. If that log doesn't show, I am assuming the session can be found and attempts to restore it, I get the same original error. Almost like the session is not properly restored? Not exactly sure why I am seeing inconsistent behavior when I set readMode=MEMORY.

**Comment by mrniko** [comment]
you can turn on Redisson logs for both apps to check what is the cause of this error.

**Comment by mrniko** [comment]
did you try to set Redisson setting readMode = MASTER ?

**Comment by caseytrumble** [comment]
Setting readMode to master did not resolve the issue either.

I ended up creating custom versions of `DynaActionForm` and `DynaProperty` from `commons-beanutils` that struts uses to deserialize the session objects/beans from Redisson. For some reason struts it not able to determine the data types from the session (or it ignores it) and this was leading to the `NullPointerException` in `RequestUtils.populate`. My custom version determines the class type on the fly and sets the type attribute if it is null. This seems to resolve my issue.

Looks like more of an issue with the `commons-beanutils` library than struts or Redisson.
