### ISSUE TITLE
RedisTimeoutException: Unable to acquire connection and Redisson is shutdown

### ISSUE THREAD

**Issue by Taylo0or** [redisson/redisson#5288]
Recently we encountered this problem online, and the addition of retryTimes does not work, can you share the reason, the following are some of the error logs.

1. 
`java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@3d511574[Completed exceptionally]Increase connection pool size. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=1, freeConnectionsCounter=value:0:queue:18798, freezeReason=null, client=[addr=redis://r-rj95styb5q4i0hc1rp.redis.rds.aliyuncs.com:6379], nodeType=MASTER, firstFail=0]]], command: null, params: null after 2 retry attempts
        at org.redisson.RedissonBaseLock.lambda$evalWriteAsync$0(RedissonBaseLock.java:226)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:284)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:166)
        at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:524)
        at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:176)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:256)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@3d511574[Completed exceptionally]Increase connection pool size. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=1, freeConnectionsCounter=value:0:queue:18798, freezeReason=null, client=[addr=redis://xxx.xxx.xxx.xxx:6379], nodeType=MASTER, firstFail=0]]], command: null, params: null after 2 retry attempts
        at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:241)
        ... 7 common frames omitted`

2.
`java.util.concurrent.CompletionException: org.redisson.RedissonShutdownException: Redisson is shutdown
        at org.redisson.RedissonBaseLock.lambda$evalWriteAsync$0(RedissonBaseLock.java:226)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
        at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:848)
        at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2168)
        at org.redisson.misc.CompletableFutureWrapper.handle(CompletableFutureWrapper.java:208)
        at org.redisson.RedissonBaseLock.evalWriteAsync(RedissonBaseLock.java:224)
        at org.redisson.RedissonBaseLock.renewExpirationAsync(RedissonBaseLock.java:179)
        at org.redisson.RedissonBaseLock$1.run(RedissonBaseLock.java:140)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.redisson.RedissonShutdownException: Redisson is shutdown
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:118)
        at org.redisson.command.CommandBatchService.executeAsync(CommandBatchService.java:345)
        at org.redisson.RedissonBaseLock.evalWriteAsync(RedissonBaseLock.java:223)
        ... 9 common frames omitted`

3
`2023-08-26 13:34:24 [schedule-pool-5] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
org.redisson.client.RedisException: java.lang.InterruptedException
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:113)
        at org.redisson.RedissonKeys$2.iterator(RedissonKeys.java:152)
        at org.redisson.iterator.BaseIterator.hasNext(BaseIterator.java:55)
        at org.redisson.misc.CompositeIterator.hasNext(CompositeIterator.java:38)
        at cn.hutool.core.collection.ListUtil.list(ListUtil.java:106)
        at cn.hutool.core.collection.ListUtil.toList(ListUtil.java:220)
        at cn.hutool.core.collection.IterUtil.toList(IterUtil.java:519)
        at cn.hutool.core.collection.IterUtil.toList(IterUtil.java:506)
        at com.xxx.components.tool.utils.redis.RedisUtils.keys(RedisUtils.java:395)
        at xxxxx 
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)

        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.InterruptedException: null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:109)
        ... 44 common frames omitted
2023-08-26 13:34:24 [schedule-pool-5] ERROR c.a.components.tool.utils.Threads - null
java.util.concurrent.CancellationException: null
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.xxx.components.tool.utils.Threads.printException(Threads.java:59)
        at com.xxx.components.tool.config.ThreadPoolConfig$1.afterExecute(ThreadPoolConfig.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)`

**Comment by Taylo0or** [comment]
Redisson Version:  3.17.7

**Comment by Taylo0or** [comment]
@mrniko please help me [苦涩]

**Comment by mrniko** [comment]
> Increase connection pool size

Try to do it
