### ISSUE TITLE
conflict reactive-streams between my webapp and redisson-all

### ISSUE THREAD

**Issue by s-sugimori** [redisson/redisson#5292]
I have a web application with org.reactivestreams:reactive-streams in dependency.
To be precise, the dependency is defined as software.amazon.awssdk:sdk-core:2.20.140 and transitively references org.reactivestreams:reactive-streams:1.0.4.

I also use tomcat session manager.
I have placed redisson-all-3.23.4.jar and redisson-tomcat-10-3.23.4.jar in tomcat_base/lib according to the instructions in this [doc](https://github.com/redisson/redisson/tree/master/redisson-tomcat).
The tomcat version used is 10.1.x.
redisson-all is a fat jar, but a look at the contents shows that org.reactivestreams:reactive-streams:1.0.4 is being used.

When I start the application, I get the following error
Similar to Issue #5233 

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'preFilterAuthorizationAdvisor' defined in class path resource [org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'preFilterAuthorizationMethodInterceptor' parameter 3: Error creating bean with name 'preAuthorizeAuthorizationAdvisor' defined in class path resource [org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'preAuthorizeAuthorizationMethodInterceptor' parameter 5: Error creating bean with name 'postFilterAuthorizationAdvisor' defined in class path resource [org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'postFilterAuthorizationMethodInterceptor' parameter 3: Error creating bean with name 'postAuthorizeAuthorizationAdvisor' defined in class path resource [org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'postAuthorizeAuthorizationMethodInterceptor' parameter 5: Error creating bean with name 'org.springframework.transaction.config.internalTransactionAdvisor' defined in class path resource [org/springframework/transaction/annotation/ProxyTransactionManagementConfiguration.class]: Unsatisfied dependency expressed through method 'transactionAdvisor' parameter 1: Error creating bean with name 'transactionInterceptor' defined in class path resource [org/springframework/transaction/annotation/ProxyTransactionManagementConfiguration.class]: Failed to instantiate [org.springframework.transaction.interceptor.TransactionInterceptor]: Factory method 'transactionInterceptor' threw exception with message: loader constraint violation: when resolving method 'java.util.concurrent.Flow$Publisher reactor.adapter.JdkFlowAdapter.publisherToFlowPublisher(org.reactivestreams.Publisher)' the class loader org.apache.catalina.loader.ParallelWebappClassLoader @ad7cc49 of the current class, org/springframework/core/ReactiveAdapterRegistry$ReactorRegistrar, and the class loader java.net.URLClassLoader @41629346 for the method's defining class, reactor/adapter/JdkFlowAdapter, have different Class objects for the type org/reactivestreams/Publisher used in the signature (org.springframework.core.ReactiveAdapterRegistry$ReactorRegistrar is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @ad7cc49, parent loader java.net.URLClassLoader @41629346; reactor.adapter.JdkFlowAdapter is in unnamed module of loader java.net.URLClassLoader @41629346, parent loader 'app')
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:550)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:111)
	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:280)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1102)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:509)
	... 46 more
```

I think the cause is due to reactivestreams related classes being loaded from a different class loader.
How can I resolve this?
As a temporary solution, I have excluded org.reactivestreams:reactive-streams from the web app dependency.

```
            <exclusions>
                <exclusions>
                    <groupId>org.reactivestreams</groupId>
                    <artifactId>reactive-streams</artifactId>
                </exclusions>
            </exclusions>
```

**Comment by mrniko** [comment]
As option you can add redisson.jar with dependencies you need https://github.com/redisson/redisson/wiki/15.-Dependency-list

**Comment by s-sugimori** [comment]
@mrniko 
Thank you for your answer.
I have one more question.
Is there a problem if I place the library required to use tomcat session manager in the web application lib (i.e. added to dependency in pom.xml) instead of tomcat/lib?

**Comment by mrniko** [comment]
@s-sugimori 
classloader issues may appear.

**Comment by s-sugimori** [comment]
ok, thank you.
