### ISSUE TITLE
io.netty.resolver.dns.DnsNameResolverTimeoutException: [38256: /192.168.0.10:53] DefaultDnsQuestion(r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com.customer.svc.cluster.local. IN A) query '38256' via UDP timed out after 5000 milliseconds (no stack trace available)

### ISSUE THREAD

**Issue by wjswk** [redisson/redisson#5296]
SpringBoot 2.6.5

<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson-spring-boot-starter</artifactId>
    <version>3.23.4</version>
    <exclusions>
        <exclusion>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <groupId>org.springframework.boot</groupId>
        </exclusion>
    </exclusions>
</dependency>

open-jdk17

k8s  pod 

2023-09-08T19:25:36.260551395+08:00 SLF4J: Class path contains multiple SLF4J bindings.

2023-09-08T19:25:36.260819516+08:00 SLF4J: Found binding in [jar:file:/mnt/mf-backend-chatbot-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/logback-classic-1.2.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]

2023-09-08T19:25:36.260835277+08:00 SLF4J: Found binding in [jar:file:/mnt/mf-backend-chatbot-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]

2023-09-08T19:25:36.260846750+08:00 SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

2023-09-08T19:25:36.363312032+08:00 SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

2023-09-08T19:25:37.214103227+08:00 2023-09-08 19:25:37.210 [main] [] INFO  c.a.b.n.c.u.NacosConfigPropertiesUtils - nacosConfigProperties : NacosConfigProperties{serverAddr='mse-80a0d732-p.nacos-ans.mse.aliyuncs.com:8848', contextPath='null', encode='null', endpoint='null', namespace='null', accessKey='******', secretKey='******', ramRoleName='null', autoRefresh=true, dataId='null', dataIds='switch,hello,text', group='mf-backend-chatbot', type=PROPERTIES, maxRetry='null', configLongPollTimeout='null', configRetryTime='null', enableRemoteSyncConfig=false, extConfig=[], bootstrap=Bootstrap{enable=true, logEnable=false}}

2023-09-08T19:25:37.225440137+08:00 

2023-09-08T19:25:37.225456042+08:00   .   ____          _            __ _ _

2023-09-08T19:25:37.225461389+08:00  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \

2023-09-08T19:25:37.225500008+08:00 ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

2023-09-08T19:25:37.225528072+08:00  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )

2023-09-08T19:25:37.225533714+08:00   '  |____| .__|_| |_|_| |_\__, | / / / /

2023-09-08T19:25:37.225537443+08:00  =========|_|==============|___/=/_/_/_/

2023-09-08T19:25:37.226720552+08:00  :: Spring Boot ::               (v2.6.15)

2023-09-08T19:25:37.226731952+08:00 

2023-09-08T19:25:37.331263957+08:00 2023-09-08 19:25:37.330 [background-preinit] [] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.2.5.Final

2023-09-08T19:25:37.355418431+08:00 2023-09-08 19:25:37.354 [main] [] INFO  c.a.b.n.c.u.NacosConfigPropertiesUtils - nacosConfigProperties : NacosConfigProperties{serverAddr='mse-80a0d732-p.nacos-ans.mse.aliyuncs.com:8848', contextPath='null', encode='null', endpoint='null', namespace='null', accessKey='******', secretKey='******', ramRoleName='null', autoRefresh=true, dataId='null', dataIds='switch,hello,text', group='mf-backend-chatbot', type=PROPERTIES, maxRetry='null', configLongPollTimeout='null', configRetryTime='null', enableRemoteSyncConfig=false, extConfig=[], bootstrap=Bootstrap{enable=true, logEnable=false}}

2023-09-08T19:25:37.641056595+08:00 2023-09-08 19:25:37.640 [main] [] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success.

2023-09-08T19:25:37.641248938+08:00 2023-09-08 19:25:37.641 [main] [] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl success.

2023-09-08T19:25:48.442125200+08:00 2023-09-08 19:25:48.441 [main] [] INFO  c.a.b.n.c.util.NacosConfigLoader - load config from nacos, data-id is : switch, group is : mf-backend-chatbot

2023-09-08T19:25:48.745412837+08:00 2023-09-08 19:25:48.745 [main] [] INFO  c.a.b.n.c.util.NacosConfigLoader - load config from nacos, data-id is : hello, group is : mf-backend-chatbot

2023-09-08T19:25:49.048396905+08:00 2023-09-08 19:25:49.048 [main] [] INFO  c.a.b.n.c.util.NacosConfigLoader - load config from nacos, data-id is : text, group is : mf-backend-chatbot

2023-09-08T19:25:49.075891217+08:00 2023-09-08 19:25:49.075 [main] [] INFO  c.m.b.chatbot.ChatbotApplication - Starting ChatbotApplication v0.0.1-SNAPSHOT using Java 17.0.1 on mf-backend-chatbot-7599c4df84-vszv5 with PID 1 (/mnt/mf-backend-chatbot-0.0.1-SNAPSHOT.jar started by root in /mnt)

2023-09-08T19:25:49.076283498+08:00 2023-09-08 19:25:49.076 [main] [] DEBUG c.m.b.chatbot.ChatbotApplication - Running with Spring Boot v2.6.15, Spring v5.3.27

2023-09-08T19:25:49.076889768+08:00 2023-09-08 19:25:49.076 [main] [] INFO  c.m.b.chatbot.ChatbotApplication - The following 1 profile is active: "dev"

2023-09-08T19:25:50.561818862+08:00 2023-09-08 19:25:50.561 [main] [] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode

2023-09-08T19:25:50.564859445+08:00 2023-09-08 19:25:50.564 [main] [] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data Redis repositories in DEFAULT mode.

2023-09-08T19:25:50.601325384+08:00 2023-09-08 19:25:50.601 [main] [] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 20 ms. Found 0 Redis repository interfaces.

2023-09-08T19:25:51.710879349+08:00 2023-09-08 19:25:51.710 [main] [] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)

2023-09-08T19:25:51.719630033+08:00 2023-09-08 19:25:51.719 [main] [] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]

2023-09-08T19:25:51.720061708+08:00 2023-09-08 19:25:51.719 [main] [] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]

2023-09-08T19:25:51.720235596+08:00 2023-09-08 19:25:51.720 [main] [] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.75]

2023-09-08T19:25:51.764366826+08:00 2023-09-08 19:25:51.764 [main] [] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext

2023-09-08T19:25:51.764509906+08:00 2023-09-08 19:25:51.764 [main] [] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 2644 ms

2023-09-08T19:26:13.204758493+08:00  _ _   |_  _ _|_. ___ _ |    _ 

2023-09-08T19:26:13.204786285+08:00 | | |\/|_)(_| | |_\  |_)||_|_\ 

2023-09-08T19:26:13.204790092+08:00      /               |         

2023-09-08T19:26:13.205172508+08:00                         3.5.3.1 

2023-09-08T19:26:13.341523783+08:00 2023-09-08 19:26:13.341 [main] [] INFO  org.redisson.Version - Redisson 3.23.4

2023-09-08T19:26:38.163276297+08:00 2023-09-08 19:26:38.163 [main] [] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatService': Unsatisfied dependency expressed through field 'intelligentAgentService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'intelligentAgentService': Unsatisfied dependency expressed through field 'redissonClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redissonClient' defined in class path resource [com/modelbest/backend/chatbot/common/config/RedissionConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [customer.svc.cluster.local, svc.cluster.local, cluster.local]

2023-09-08T19:26:38.169354029+08:00 2023-09-08 19:26:38.169 [main] [] INFO  c.a.n.s.c.a.c.NacosValueAnnotationBeanPostProcessor - class com.alibaba.nacos.spring.context.annotation.config.NacosValueAnnotationBeanPostProcessor was destroying!

2023-09-08T19:26:38.169486565+08:00 2023-09-08 19:26:38.169 [main] [] INFO  c.a.n.s.b.f.a.AnnotationNacosInjectedBeanPostProcessor - class com.alibaba.nacos.spring.beans.factory.annotation.AnnotationNacosInjectedBeanPostProcessor was destroying!

2023-09-08T19:26:38.171854885+08:00 2023-09-08 19:26:38.171 [main] [] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]

2023-09-08T19:26:38.188640323+08:00 2023-09-08 19:26:38.188 [main] [] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

2023-09-08T19:26:38.188657833+08:00 

2023-09-08T19:26:38.188663714+08:00 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2023-09-08T19:26:38.207026541+08:00 2023-09-08 19:26:38.206 [main] [] ERROR o.s.boot.SpringApplication - Application run failed

2023-09-08T19:26:38.207049736+08:00 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatService': Unsatisfied dependency expressed through field 'intelligentAgentService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'intelligentAgentService': Unsatisfied dependency expressed through field 'redissonClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redissonClient' defined in class path resource [com/modelbest/backend/chatbot/common/config/RedissionConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [customer.svc.cluster.local, svc.cluster.local, cluster.local]

2023-09-08T19:26:38.207056210+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)

2023-09-08T19:26:38.207061411+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)

2023-09-08T19:26:38.207066802+08:00     at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)

2023-09-08T19:26:38.207071659+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)

2023-09-08T19:26:38.207076782+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)

2023-09-08T19:26:38.207080974+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)

2023-09-08T19:26:38.207085048+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)

2023-09-08T19:26:38.207089983+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

2023-09-08T19:26:38.207093917+08:00     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

2023-09-08T19:26:38.207097858+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

2023-09-08T19:26:38.207101843+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

2023-09-08T19:26:38.207117399+08:00     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)

2023-09-08T19:26:38.207121673+08:00     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)

2023-09-08T19:26:38.207125574+08:00     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)

2023-09-08T19:26:38.207129310+08:00     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)

2023-09-08T19:26:38.207133165+08:00     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)

2023-09-08T19:26:38.207137057+08:00     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423)

2023-09-08T19:26:38.207141243+08:00     at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)

2023-09-08T19:26:38.207145131+08:00     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)

2023-09-08T19:26:38.207148996+08:00     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)

2023-09-08T19:26:38.207152963+08:00     at com.modelbest.backend.chatbot.ChatbotApplication.main(ChatbotApplication.java:17)

2023-09-08T19:26:38.207156756+08:00     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2023-09-08T19:26:38.207160551+08:00     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

2023-09-08T19:26:38.207164389+08:00     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2023-09-08T19:26:38.207184105+08:00     at java.base/java.lang.reflect.Method.invoke(Method.java:568)

2023-09-08T19:26:38.207188596+08:00     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)

2023-09-08T19:26:38.207192386+08:00     at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)

2023-09-08T19:26:38.207196196+08:00     at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)

2023-09-08T19:26:38.207199940+08:00     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2023-09-08T19:26:38.207206190+08:00 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'intelligentAgentService': Unsatisfied dependency expressed through field 'redissonClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redissonClient' defined in class path resource [com/modelbest/backend/chatbot/common/config/RedissionConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [customer.svc.cluster.local, svc.cluster.local, cluster.local]

2023-09-08T19:26:38.207210693+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)

2023-09-08T19:26:38.207214693+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)

2023-09-08T19:26:38.207219168+08:00     at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)

2023-09-08T19:26:38.207228446+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)

2023-09-08T19:26:38.207232471+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)

2023-09-08T19:26:38.207236046+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)

2023-09-08T19:26:38.207239624+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)

2023-09-08T19:26:38.207243465+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

2023-09-08T19:26:38.207246959+08:00     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

2023-09-08T19:26:38.207250512+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

2023-09-08T19:26:38.207254351+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

2023-09-08T19:26:38.207257843+08:00     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)

2023-09-08T19:26:38.207261700+08:00     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)

2023-09-08T19:26:38.207265604+08:00     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)

2023-09-08T19:26:38.207269474+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)

2023-09-08T19:26:38.207274158+08:00     ... 28 common frames omitted

2023-09-08T19:26:38.207289548+08:00 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redissonClient' defined in class path resource [com/modelbest/backend/chatbot/common/config/RedissionConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [customer.svc.cluster.local, svc.cluster.local, cluster.local]

2023-09-08T19:26:38.207293616+08:00     at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)

2023-09-08T19:26:38.207297450+08:00     at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)

2023-09-08T19:26:38.207301076+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)

2023-09-08T19:26:38.207304838+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)

2023-09-08T19:26:38.207308434+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)

2023-09-08T19:26:38.207312389+08:00     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)

2023-09-08T19:26:38.207320064+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

2023-09-08T19:26:38.207323938+08:00     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

2023-09-08T19:26:38.207331336+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

2023-09-08T19:26:38.207335603+08:00     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

2023-09-08T19:26:38.207339347+08:00     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)

2023-09-08T19:26:38.207343045+08:00     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)

2023-09-08T19:26:38.207346653+08:00     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)

2023-09-08T19:26:38.207350485+08:00     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)

2023-09-08T19:26:38.207354280+08:00     ... 42 common frames omitted

2023-09-08T19:26:38.207359393+08:00 Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [customer.svc.cluster.local, svc.cluster.local, cluster.local]

2023-09-08T19:26:38.207363146+08:00     at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)

2023-09-08T19:26:38.207366904+08:00     at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)

2023-09-08T19:26:38.207370425+08:00     ... 55 common frames omitted

2023-09-08T19:26:38.207391673+08:00 Caused by: org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [customer.svc.cluster.local, svc.cluster.local, cluster.local]

2023-09-08T19:26:38.207395942+08:00     at org.redisson.client.RedisClient.lambda$resolveAddr$0(RedisClient.java:207)

2023-09-08T19:26:38.207399773+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

2023-09-08T19:26:38.207403394+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)

2023-09-08T19:26:38.207407084+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)

2023-09-08T19:26:38.207422992+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

2023-09-08T19:26:38.207427282+08:00     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

2023-09-08T19:26:38.207430836+08:00     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

2023-09-08T19:26:38.207434827+08:00     at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:110)

2023-09-08T19:26:38.207438493+08:00     at io.netty.resolver.InetSocketAddressResolver$1.operationComplete(InetSocketAddressResolver.java:62)

2023-09-08T19:26:38.207442114+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

2023-09-08T19:26:38.207450071+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)

2023-09-08T19:26:38.207453813+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)

2023-09-08T19:26:38.207457419+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

2023-09-08T19:26:38.207461097+08:00     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

2023-09-08T19:26:38.207464700+08:00     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

2023-09-08T19:26:38.207468154+08:00     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

2023-09-08T19:26:38.207471530+08:00     at io.netty.resolver.dns.DnsNameResolver.tryFailure(DnsNameResolver.java:1025)

2023-09-08T19:26:38.207474987+08:00     at io.netty.resolver.dns.DnsNameResolver.access$400(DnsNameResolver.java:93)

2023-09-08T19:26:38.207478600+08:00     at io.netty.resolver.dns.DnsNameResolver$6.operationComplete(DnsNameResolver.java:1045)

2023-09-08T19:26:38.207482548+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

2023-09-08T19:26:38.207486036+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)

2023-09-08T19:26:38.207489972+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

2023-09-08T19:26:38.207493898+08:00     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

2023-09-08T19:26:38.207497624+08:00     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

2023-09-08T19:26:38.207501427+08:00     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

2023-09-08T19:26:38.207505055+08:00     at io.netty.resolver.dns.DnsResolveContext$1.operationComplete(DnsResolveContext.java:236)

2023-09-08T19:26:38.207508487+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

2023-09-08T19:26:38.207512068+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)

2023-09-08T19:26:38.207515649+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

2023-09-08T19:26:38.207519350+08:00     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

2023-09-08T19:26:38.207523099+08:00     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

2023-09-08T19:26:38.207526752+08:00     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

2023-09-08T19:26:38.207530530+08:00     at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1096)

2023-09-08T19:26:38.207534350+08:00     at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1035)

2023-09-08T19:26:38.207538083+08:00     at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:422)

2023-09-08T19:26:38.207541933+08:00     at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66)

2023-09-08T19:26:38.207545581+08:00     at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:493)

2023-09-08T19:26:38.207549401+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

2023-09-08T19:26:38.207553071+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)

2023-09-08T19:26:38.207556790+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)

2023-09-08T19:26:38.207560710+08:00     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

2023-09-08T19:26:38.207564477+08:00     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

2023-09-08T19:26:38.207572265+08:00     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

2023-09-08T19:26:38.207575994+08:00     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

2023-09-08T19:26:38.207579689+08:00     at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:261)

2023-09-08T19:26:38.207583431+08:00     at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:208)

2023-09-08T19:26:38.207587054+08:00     at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)

2023-09-08T19:26:38.207590569+08:00     at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)

2023-09-08T19:26:38.207594094+08:00     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

2023-09-08T19:26:38.207597762+08:00     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)

2023-09-08T19:26:38.207601394+08:00     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)

2023-09-08T19:26:38.207605294+08:00     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)

2023-09-08T19:26:38.207624113+08:00     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

2023-09-08T19:26:38.207628574+08:00     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

2023-09-08T19:26:38.207632278+08:00     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

2023-09-08T19:26:38.207636048+08:00     at java.base/java.lang.Thread.run(Thread.java:833)

2023-09-08T19:26:38.207640333+08:00 Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [customer.svc.cluster.local, svc.cluster.local, cluster.local]

2023-09-08T19:26:38.207644469+08:00     at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1088)

2023-09-08T19:26:38.207648430+08:00     ... 23 common frames omitted

2023-09-08T19:26:38.207652475+08:00 Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [38256: /192.168.0.10:53] DefaultDnsQuestion(r-2zeinsud32pq15lncd.redis.rds.aliyuncs.com.customer.svc.cluster.local. IN A) query '38256' via UDP timed out after 5000 milliseconds (no stack trace available)

**Comment by mrniko** [comment]
make sure that you have 4.1.88+ netty version in classpath. Try to set addressResolverGroupFactory = new SequentialDnsAddressResolverFactory(2 or 4);
