### ISSUE TITLE
Encountered unregistered class ID

### ISSUE THREAD

**Issue by Loudbooks** [redisson/redisson#5297]
Hi!

I'm having the follow error whenever a message is published to Redis. Anything whatsoever, including just strings. I cannot figure out where it's coming from. I am registering the listener as follow:

```java
this.redissonClient.getPatternTopic("*").addListenerAsync(String.class, new RedisListener(server));
```

```
[20:35:07 ERROR] [org.redisson.client.handler.CommandPubSubDecoder]: Unable to decode data. channel: [id: 0x34040095, L:/172.18.0.4:60388 - R:15.204.174.230/15.204.174.230:8001], reply: ReplayingDecoderByteBuf(ridx=43, widx=43)
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 91
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159) ~[?:?]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758) ~[?:?]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869) ~[?:?]
        at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:394) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:442) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:403) ~[?:?]
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:88) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.lang.Thread.run(Thread.java:887) [?:?]
[20:35:07 ERROR] [org.redisson.client.handler.ErrorsLoggingHandler]: Exception occured. Channel: [id: 0x34040095, L:/172.18.0.4:60388 - R:15.204.174.230/15.204.174.230:8001]
io.netty.handler.codec.DecoderException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 91
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.lang.Thread.run(Thread.java:887) [?:?]
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 91
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159) ~[?:?]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758) ~[?:?]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869) ~[?:?]
        at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:394) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:442) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:403) ~[?:?]
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:88) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        ... 17 more

```

Anyone know where the issue is coming from and how I can fix it?

**Comment by mrniko** [comment]
You need to override org.redisson.codec.Kryo5Codec#createKryo() method and register missed classes.

through 
```java
kryo.addDefaultSerializer(MyClass.class, new JavaSerializer());
```
