### ISSUE TITLE
Command still hasn't been written into connection! Try to increase nettyThreads setting

### ISSUE THREAD

**Issue by lcc0739** [redisson/redisson#5305]
**Expected behavior**

**Actual behavior**

I'm using redisson version 3.16.4, and confirm that there is a bug here where we have an instance of our application with a connection in it, and there has been a fixed connection that keeps reporting an error.   This error lasts as long as it occurs and does not recover until a reboot. 

We've also looked at some previous issues that have added nettythread , which didn't work.

```
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 0. Node source: NodeSource [slot=6076, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@902022049 [redisClient=[addr=redis://xxx], channel=[id: 0xaad2183a, L:/1xxx - R:xxxxx], currentCommand=null, usage=0], command: (ZSCAN), params: [CACHE_CONTRACT_AUTOMATIC_GOODS_CODE_MAPPING_KEY_15262_8100339, 0, COUNT, 10] after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:222)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```
<img width="1618" alt="image" src="https://github.com/redisson/redisson/assets/13074295/f120fb78-15f4-49c5-af7e-735f824e7a2f">

This instance will consistently report errors and it will always be this connection！！！！！！

Here is the dump for this redissonConnection。。

```
@NioSocketChannel[
    logger=@LocationAwareSlf4JLogger[LocationAwareSlf4JLogger(io.netty.channel.socket.nio.NioSocketChannel)],
    DEFAULT_SELECTOR_PROVIDER=@EPollSelectorProvider[sun.nio.ch.EPollSelectorProvider@7e615922],
    config=@NioSocketChannelConfig[io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig@1ee05eb],
    METADATA=@ChannelMetadata[io.netty.channel.ChannelMetadata@263c5862],
    EXPECTED_TYPES=@String[ (expected: ByteBuf, FileRegion)],
    flushTask=@[io.netty.channel.nio.AbstractNioByteChannel$1@12481cbd],
    inputClosedSeenErrorOnRead=@Boolean[false],
    logger=@LocationAwareSlf4JLogger[LocationAwareSlf4JLogger(io.netty.channel.nio.AbstractNioChannel)],
    ch=@SocketChannelImpl[java.nio.channels.SocketChannel[connected local=/xxxx  remote=xxxx]],
    readInterestOp=@Integer[1],
    selectionKey=@SelectionKeyImpl[sun.nio.ch.SelectionKeyImpl@320576e],
    readPending=@Boolean[true],
    clearReadPendingRunnable=@[io.netty.channel.nio.AbstractNioChannel$1@247bb415],
    connectPromise=null,
    connectTimeoutFuture=@ScheduledFutureTask[ScheduledFutureTask@74baf78a(failure: io.netty.util.concurrent.DefaultPromise$StacklessCancellationException, task: CANCELLED, deadline: 10588639078, period: 0)],
    requestedRemoteAddress=@InetSocketAddress[xx],
    $assertionsDisabled=@Boolean[true],
    logger=@LocationAwareSlf4JLogger[LocationAwareSlf4JLogger(io.netty.channel.AbstractChannel)],
    parent=null,
    id=@DefaultChannelId[aad2183a],
    unsafe=@NioSocketChannelUnsafe[io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe@58a75ab],
    pipeline=@DefaultChannelPipeline[DefaultChannelPipeline{(RedisConnectionHandler#0 = org.redisson.client.handler.RedisConnectionHandler), (ConnectionWatchdog#0 = org.redisson.client.handler.ConnectionWatchdog), (CommandEncoder#0 = org.redisson.client.handler.CommandEncoder), (CommandBatchEncoder#0 = org.redisson.client.handler.CommandBatchEncoder), (CommandsQueue#0 = org.redisson.client.handler.CommandsQueue), (PingConnectionHandler#0 = org.redisson.client.handler.PingConnectionHandler), (CommandDecoder#0 = org.redisson.client.handler.CommandDecoder), (ErrorsLoggingHandler#0 = org.redisson.client.handler.ErrorsLoggingHandler)}],
    unsafeVoidPromise=@VoidChannelPromise[io.netty.channel.VoidChannelPromise@57752c53],
    closeFuture=@CloseFuture[AbstractChannel$CloseFuture@2ed7e1b4(incomplete)],
    localAddress=@InetSocketAddress[/xx],
    remoteAddress=@InetSocketAddress[xxx],
    eventLoop=@NioEventLoop[io.netty.channel.nio.NioEventLoop@4919cfcf],
    registered=@Boolean[true],
    closeInitiated=@Boolean[false],
    initialCloseCause=null,
    strValActive=@Boolean[true],
    strVal=@String[[id: 0xaad2183a, L:/xxxx - R:xxxx]],
    ATTRIBUTES_UPDATER=@AtomicReferenceFieldUpdaterImpl[java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl@48d28fd9],
    EMPTY_ATTRIBUTES=@DefaultAttribute[][isEmpty=true;size=0],
    attributes=@DefaultAttribute[][isEmpty=false;size=3],
    $assertionsDisabled=@Boolean[true],
]
```

and found that the channel's isWritable is false. while all other normal channels are true.

 
<img width="1440" alt="image" src="https://github.com/redisson/redisson/assets/13074295/e6901515-b13b-41e0-9e73-9cb200357a36">

**Steps to reproduce or test case**

**Redis version**
[proxy](https://cloud.tencent.com/document/product/239/18336)  Redis 4.0 proxy 
 
**Redisson version**
3.16.4
**Redisson configuration**

```

 @Bean
    RedissonClient redisson() throws Exception {
        Config config = new Config();
        ClusterServersConfig clusterConfig = config.useClusterServers()
            .setScanInterval(2000)
            .setKeepAlive(true)
            .setMasterConnectionPoolSize(80)
            .setMasterConnectionMinimumIdleSize(80)
            .setSlaveConnectionPoolSize(80)
            .setSlaveConnectionMinimumIdleSize(80)
            .setReadMode(ReadMode.valueOf(master))
            .setPingConnectionInterval(3000);
        for (String str : address) {
            clusterConfig.addNodeAddress(str);
            log.info("cluster address========"+str);
        }
        log.info("cluster redisson readMode======="+readMode);
        config.setCodec(new JsonJacksonCodec());
        return Redisson.create(config);
    }
```

**Comment by lcc0739** [comment]
Add some more information

tcp link initiated a large number of TCP dup ACK, indicating that there is a packet loss, and the server/client are asking for retransmission, in addition to no other packets, suspect that the link has failed, the need to rebuild the connection

<img width="1572" alt="image" src="https://github.com/redisson/redisson/assets/13074295/2f1d5d9c-bce0-4980-b503-201413958396">

channel information

![image](https://github.com/redisson/redisson/assets/13074295/e27a1986-a45c-40ac-96e1-4740589ffef1)


channel outboundBuffer information
![image](https://github.com/redisson/redisson/assets/13074295/aea4d168-8b30-4915-84ef-57b6fd157ef8)

**Comment by mrniko** [comment]
Can you try the latest version?

**Comment by lcc0739** [comment]
> Can you try the latest version?

no,I can't,please fix this bug

**Comment by lcc0739** [comment]
@

> Can you try the latest version?


Can you try the latest version?

no,I can't,please fix this bug @mrniko

**Comment by lcc0739** [comment]
> Can you try the latest version?



no,I can't,please fix this bug

**Comment by lcc0739** [comment]
> Can you try the latest version?

no,I can't,please fix this bug    @mrniko

**Comment by mrniko** [comment]
unable to reproduce it with the latest version

**Comment by lcc0739** [comment]
> unable to reproduce it with the latest version

Please give me a fix idea and guidance I need to fix it in this version  @mrniko

**Comment by lcc0739** [comment]
@mrniko  hi，Please give me some guidance, we did a lot of customization in this version 3.16.4 and would like to fix it in this version!

**Comment by lcc0739** [comment]
I can't find the code to call isWritable in the latest code, how did I have to fix it?  @mrniko

**Comment by mrniko** [comment]
I'm sorry, but this version 3.16.x line isn't developed anymore.

**Comment by wzgl998877** [comment]
Has this problem been solved?I encountered the same problem, what is the solution?

**Comment by mrniko** [comment]
@wzgl998877 

You need to refer to https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception
