### ISSUE TITLE
NullPointerException in CommandPubSubDecoder

### ISSUE THREAD

**Issue by eerojm** [redisson/redisson#5308]
When shutting down an application that uses Redisson, we are manually calling `redissonClient.shutdown()`.
Application uses `RLocalCachedMaps`.

Sometimes, after calling `redissonClient.shutDown()`, but before said action finishes, we get a `NullPointerException` in logs.
This only happens occasionally and may or may not be related to Redisson receiving cache update messages during `shutdown()`.

**Expected behavior**
```
No errors logged during:

        log.info("Shutting down Redisson client")
        redissonClient.shutdown()
        log.info("Redisson client shutdown finished")
```

**Actual behavior**
```
        log.info("Shutting down Redisson client")
        redissonClient.shutdown()

 NPE is logged here

        log.info("Redisson client shutdown finished")
```

Stacktrace:
```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.List.get(int)" is null
	at org.redisson.client.handler.CommandPubSubDecoder.selectDecoder(CommandPubSubDecoder.java:287)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:441)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:100)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Steps to reproduce or test case**

As the error is only logged occasionally, it is difficult to provide exact steps for reproducing it, but there seems to be the possibility for a NPE [here](https://github.com/redisson/redisson/blob/8ac0fcf1d22c43f7dddc0c7f503a43342ffb4ed9/redisson/src/main/java/org/redisson/client/handler/CommandPubSubDecoder.java#L287), when `parts.get(0)` returns a `null` for some reason.

**Redis version**
6.2.6

**Redisson version**
3.23.4

**Redisson configuration**

We are using `RLocalCachedMap`.

**Comment by mrniko** [comment]
Which Redis vendor do you use?

**Comment by eerojm** [comment]
> Which Redis vendor do you use?

We are using Redis in AWS.
```
INFO
# Server
redis_version:6.2.6
redis_mode:standalone
os:Amazon ElastiCache
```

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by eerojm** [comment]
Thank you! :)
