### ISSUE TITLE
how to remove subscriptionConnection configuration

### ISSUE THREAD

**Issue by unasd** [redisson/redisson#5332]
I only use Redisson for the purpose of storing session data. 
The Redisson configuration includes the subscriptionConnectionPoolSize setting by default. 
Is there a way to remove this setting? 
Also, I am curious if there will be any issues with storing or retrieving session data if this setting is removed.

**Comment by mrniko** [comment]
set subscriptionConnectionMinimumIdleSize = 0

**Comment by unasd** [comment]
thank you
I configured it as you suggested and noticed that redis connections decreased.
However, an error occurs during initialization. Can I ignore it?

The settings and error message are as follows.

settings
```yaml
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 0
  clientName: "client"
  address: "rediss://redis.cache.windows.net:6380"
  password: "xxxx
  subscriptionConnectionMinimumIdleSize: 0
  subscriptionConnectionPoolSize: 0
  connectionMinimumIdleSize: 1
  connectionPoolSize: 10
  database: 0
  dnsMonitoringInterval: 5000
codec: !<org.redisson.codec.SerializationCodec> {}
```

error message
```java
[2023-10-11 09:34:11:701][DEBUG][org.redisson.command.RedisExecutor:sendCommand:616] acquired connection for command (PUBLISH) and params [[100, 108, 101, 110, 99, 58, 100, 103, 119, 50, ...], [-84, -19, 0, 5, 115, 114, 0, 17, 106, 97, ...]] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using node redis.cache.windows.net/10.10.10.10:6380... RedisConnection@842035855 [redisClient=[addr=rediss://redis.cache.windows.net:6380], channel=[id: 0x4e55af9d, L:/10.10.10.10:47354 - R:redis.cache.windows.net/10.10.10.10:6380], currentCommand=null, usage=1]
[2023-10-11 09:34:11:705][DEBUG][org.redisson.command.RedisExecutor:releaseConnection:651] connection released for command (PUBLISH) and params [[100, 108, 101, 110, 99, 58, 100, 103, 119, 50, ...], [-84, -19, 0, 5, 115, 114, 0, 17, 106, 97, ...]] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@842035855 [redisClient=[addr=rediss://redis.cache.windows.net:6380], channel=[id: 0x4e55af9d, L:/10.10.10.10:47354 - R:redis.cache.windows.net/10.10.10.10:6380], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@1615c3e0[Completed normally], command=(PUBLISH), params=[[100, 108, 101, 110, 99, 58, 100, 103, 119, 50, ...], [-84, -19, 0, 5, 115, 114, 0, 17, 106, 97, ...]], codec=org.redisson.client.codec.StringCodec], usage=0]
[2023-10-11 09:34:12:774][ERROR][org.springframework.data.redis.listener.RedisMessageListenerContainer:handleSubscriptionException:656] SubscriptionTask aborted with exception:
org.redisson.client.RedisTimeoutException: Unable to acquire connection for subscription after 3 attempts. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribeService.trySubscribe(PublishSubscribeService.java:349) ~[redisson-3.23.4.jar:3.23.4]
	at org.redisson.pubsub.PublishSubscribeService.lambda$connect$21(PublishSubscribeService.java:486) ~[redisson-3.23.4.jar:3.23.4]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
```

**Comment by mrniko** [comment]
you need to remove RedisMessageListenerContainer
