### ISSUE TITLE
Deadlock in publshing message to PriorityQueue in multi-threaded environment

### ISSUE THREAD

**Issue by nkant17** [redisson/redisson#5354]
I have multiple worker threads publishing message to a Redis priority Queue. I'm observing that all worker threads are waiting to acquire a semaphore  (0x000000008b0e8800) as shown in below thread dump. I'm using Redisson client.  3.22.0.  
My thread dump do now show any thread already acquired the same semaphore. 

```
"worker-817435795" #48 prio=5 os_prio=0 cpu=4635.96ms elapsed=250263.14s tid=0x00007f87966b1740 nid=0x40 waiting on condition  [0x00007f87692fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.5/Native Method)
	- parking to wait for  <0x000000008b0e8800> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.5/LockSupport.java:252)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.5/AbstractQueuedSynchronizer.java:717)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(java.base@17.0.5/AbstractQueuedSynchronizer.java:1074)
	at java.util.concurrent.Semaphore.tryAcquire(java.base@17.0.5/Semaphore.java:415)
	at org.redisson.RedissonLock.lock(RedissonLock.java:121)
	at org.redisson.RedissonLock.lock(RedissonLock.java:67)
	at org.redisson.RedissonPriorityQueue.add(RedissonPriorityQueue.java:151)
	at com.qualcomm.microservice.positioning.services.messaging.rds.RedissonMessagingMgr.publishQueue(RedissonMessagingMgr.java:67)
	at com.qualcomm.microservice.positioning.common.Worker.getUserRequestObjFromRedisAndProcess(Worker.java:91)
	at com.qualcomm.microservice.positioning.common.Worker.run(Worker.java:175)
	at java.lang.Thread.run(java.base@17.0.5/Thread.java:833)

"worker-661775617" #49 prio=5 os_prio=0 cpu=5197.28ms elapsed=250263.14s tid=0x00007f87966b21d0 nid=0x41 waiting on condition  [0x00007f86f45c7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.5/Native Method)
	- parking to wait for  <0x000000008b0e8800> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.5/LockSupport.java:252)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.5/AbstractQueuedSynchronizer.java:717)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(java.base@17.0.5/AbstractQueuedSynchronizer.java:1074)
	at java.util.concurrent.Semaphore.tryAcquire(java.base@17.0.5/Semaphore.java:415)
	at org.redisson.RedissonLock.lock(RedissonLock.java:121)
	at org.redisson.RedissonLock.lock(RedissonLock.java:67)
	at org.redisson.RedissonPriorityQueue.add(RedissonPriorityQueue.java:151)
	at com.qualcomm.microservice.positioning.services.messaging.rds.RedissonMessagingMgr.publishQueue(RedissonMessagingMgr.java:67)
	at com.qualcomm.microservice.positioning.common.Worker.getUserRequestObjFromRedisAndProcess(Worker.java:108)
	at com.qualcomm.microservice.positioning.common.Worker.run(Worker.java:175)
```

Thanks,
Nishi

**Comment by wilkina** [comment]
I'm encountering the same issue with a deadlock on version 3.17.3

**Comment by mmerrill3** [comment]
I too have run across this issue in 1.21.3 version of redis.  Multiple threads waiting for common semaphore, but apparently no other thread has obtained the semaphore.

**Comment by mmerrill3** [comment]
> I too have run across this issue in 3.21.3 version of redis. Multiple threads waiting for common semaphore, but apparently no other thread has obtained the semaphore.

I am trying an approach where I have a singleton instance of the priority blocking queue.  Before, I was invoking add on a new instance of the queue. I think it may be related to that.  Also, the code at RedissonLock.java:121 is a wait to acquire the semaphore for a TTL.  If that times out, the flow is in a forever loop to try again.  Not sure why that is just now, since apparently the semaphore can never be acquired.  I do think its related to calling new for each queue, which creates a new local semaphore.

**Comment by wilkina** [comment]
Just a note that we have successfully worked around this issue by wrapping access to the priority queue with our own semaphore.

**Comment by mmerrill3** [comment]
> Just a note that we have successfully worked around this issue by wrapping access to the priority queue with our own semaphore.

did you extend RedissonLock with your own implementation?

**Comment by mmerrill3** [comment]
I have implemented my own priorityqueue without a redisson lock as a workaround.  I tried to restrict the PriorityQueue to a singleton instance, but I still see threads waiting on the same semaphore.

I think this line is suspect, where the release is dependent upon the queue size.  What if the queue size is 0?

            value.getLatch().release(value.getLatch().getQueueLength());

**Comment by mrniko** [comment]
Can anyone try the attached version?

[redisson-3.25.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13627962/redisson-3.25.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
A new update.

[redisson-3.25.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13628088/redisson-3.25.1-SNAPSHOT.jar.zip)

**Comment by mmerrill3** [comment]
> Can anyone try the attached version?
> 
> [redisson-3.25.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13627962/redisson-3.25.1-SNAPSHOT.jar.zip)

Hi @mrniko, is there a commit that fixes this?  I couldn't see from master branch what would fix this.

**Comment by mrniko** [comment]
@mmerrill3 

Here it is https://github.com/redisson/redisson/commit/825d23ed1167683e0f1189e7cc8ce97ff0063574

**Comment by mmerrill3** [comment]
I didn't get a chance to test this out, but I'll plan on trying out the latest version in the coming weeks.
