### ISSUE TITLE
RedLock deadLock :  TryLock InterruptedException on lock success.

### ISSUE THREAD

**Issue by wiseyan** [redisson/redisson#5358]
Hello, when the thread successfully acquired the lock, while waiting for the result to return, the execution thread interrupted, causing an exception to be thrown, the actual thread has acquired the lock and successfully renewed.  
 the latest version is used, 
the exception information is as follows :

org.redisson.client.RedisException: java.lang.InterruptedException
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:114)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:143)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:222)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:306)
	at com.mandao.cloud.product.manager.redis.RedisLock.trySucLock(RedisLock.java:86)
	at 
......
 
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:110)
	... 7 common frames omitted

**Comment by mrniko** [comment]
it may happen if thread was interrupted after lock was successfully acquired, but no response was received from Redis at that moment

**Comment by wiseyan** [comment]
Currently I am catching the thread interrupt exception, then determining whether to acquire the lock and then forcing the lock release handling. Prevents deadlocks.
