### ISSUE TITLE
 java.lang.String cannot be cast to [B

### ISSUE THREAD

**Issue by guaguaguaxia** [redisson/redisson#5363]
java.lang.String cannot be cast to [B

java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:479) ~[redisson-spring-data-27-3.17.4.jar:3.17.4]
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:404) ~[spring-data-redis-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57) ~[spring-data-redis-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60) ~[spring-data-redis-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) ~[spring-data-redis-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) ~[spring-data-redis-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) ~[spring-data-redis-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53) ~[spring-data-redis-2.3.3.RELEASE.jar:2.3.3.RELEASE]

Hello,

**I've been encountering an intermittent issue with the project. Here's a summary:

1.The problem does not consistently manifest—it's sporadic.

2.I'm unable to provide specific steps to reproduce the issue.

3.After the application runs online for an uncertain period of time—ranging from a few days to sometimes even months—the issue arises.

4.Once the problem occurs, not all connections are affected. Only a subset of connections experience the problem.

5.Restarting the project makes the issue go away, at least temporarily.**

Given the nature of the problem, I understand that pinpointing the root cause might be challenging. However, I wanted to bring this to your attention in case there's any insight or potential troubleshooting steps you could suggest.

Thank you for your assistance!

**Expected behavior**

**Actual behavior**
can' work 
**Steps to reproduce or test case**
don't know how to reproduce
**Redis version**
5.0
**Redisson version**
3.17.4
**Redisson configuration**

**Comment by guaguaguaxia** [comment]
@mrniko  i read the same situation issue already,it seems just upgrade the Redisson version and it will be ok?

**Comment by guaguaguaxia** [comment]
search "cannot be cast to" in issues,most suggestions are about upgrade the version

**Comment by mrniko** [comment]
Can you try the latest version?
