### ISSUE TITLE
JsonJacksonCodec fails to serialize Throwable on Java17

### ISSUE THREAD

**Issue by tomj-vm** [redisson/redisson#5369]
Jackson ObjectMapper configured by `org.redisson.codec.JsonJacksonCodec` is able to successfully serialize Throwable instance on Java11. On Java17 it fails because it tries to access private field by reflection.

This is caused by annotation on `org.redisson.codec.JsonJacksonCodec.ThrowableMixIn`: `fieldVisibility = Visibility.ANY`. Changing this value to `fieldVisibility = Visibility.NON_PRIVATE` or `fieldVisiblity = Visibility.PROTECTED_AND_PUBLIC` fixes the issue for me.

Alternatively also adding this compile flag works:
```
--add-opens java.base/java.lang=ALL-UNNAMED
```
but then it will be required to be added by all users of the library.

**Expected behavior**
The `JsonJacksonCodec` is able to serialize and deserialize instance of `Throwable`.

**Actual behavior**
The `JsonJacksonCodec` throws exception when serializing `Throwable`
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `java.lang.RuntimeException`: Failed to construct BeanSerializer for [simple type, class java.lang.RuntimeException]: (java.lang.IllegalArgumentException) Failed to call `setAccess()` on Field 'detailMessage' (of class `java.lang.Throwable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @14acaea5

	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:72)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadTypeDefinition(SerializerProvider.java:1280)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:475)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:295)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:240)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1503)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1451)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:556)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:834)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:307)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3964)
	at org.redisson.codec.JsonJacksonCodecTest.shouldSerializeAndDeserializeThrowable(JsonJacksonCodecTest.java:54)
```

**Steps to reproduce or test case**

Test case that can be added to `org.redisson.codec.JsonJacksonCodecTest` to verify behaviour:
```java
  /**
     * This test will pass on Java11 (with Illegal reflective operation warning) and
     * fail on Java17 with the exception message:
     * <pre>
     *     Invalid type definition for type `java.lang.RuntimeException`:
     *     Failed to construct BeanSerializer for [simple type, class java.lang.RuntimeException]: (java.lang.IllegalArgumentException)
     *     Failed to call `setAccess()` on Field 'detailMessage' (of class `java.lang.Throwable`) due to `java.lang.reflect.InaccessibleObjectException`,
     *     problem: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible:
     *     module java.base does not "opens java.lang" to unnamed module @14acaea5
     * </pre>
     */
    @Test
    public void shouldSerializeAndDeserializeThrowable() throws JsonProcessingException {
        //given
        ObjectMapper objectMapper = JsonJacksonCodec.INSTANCE.getObjectMapper();
        //when
        String serialized = objectMapper.writeValueAsString(new RuntimeException("Example message"));
        RuntimeException deserialized = objectMapper.readValue(serialized, RuntimeException.class);
        //then
        Assertions.assertEquals("Example message", deserialized.getMessage());
    }
```

**Redis version**
not relevant

**Redisson version**
3.23.5, confirmed also in 3.23.6-SNAPSHOT source code

**Redisson configuration**
Default JsonJacksonCodec.INSTANCE configuration.

**Comment by tomj-vm** [comment]
Since it is a month without response and I run into this issue in second codebase where I am updating to Java17. Should I propose an PR to fix this? Will it be accepted?
