### ISSUE TITLE
Version 3.23.4: RedisTimeoutException: Command execution timeout for command: (PING)

### ISSUE THREAD

**Issue by EricCeng** [redisson/redisson#5371]
When using Redisson V3.23.4, the following exception occurred in the log:

> 2023-10-17 09:34:53.172 [redisson-timer-6-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0xb8f97598, L:/127.0.0.1:34556 - R:127.0.0.1/127.0.0.1:6322]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6322]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

According #3867, the issue should have been fixed...

I want to know why this problem occurred again, and how can I solve it?

The following is redisson client config code:

> public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6322");
        return Redisson.create(config);
    }

**Comment by HiAscend** [comment]
i hava same error in k8s container，the error repeat always，this is full stack ,fall stack

` 
2023-10-17 15:21:47.848||-|-|-|ERROR|redisson-timer-6-1|org.redisson.client.handler.PingConnectionHandler.?:?|Unable to send PING command over channel: [id: 0x1c64b4ce, L:/10.233.86.122:49416 - R:10.51.23.119/10.51.23.119:6381]
 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://10.51.23.119:6381]
 	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
 	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.lang.Thread.run(Thread.java:748)
 2023-10-17 15:21:47.848|-|-|-|ERROR|redisson-timer-6-1|org.redisson.client.handler.PingConnectionHandler.?:?|Unable to send PING command over channel: [id: 0x3a31f4f0, L:/10.233.86.122:49422 - R:10.51.23.119/10.51.23.119:6381]
 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://10.51.23.119:6381]
 	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
 	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.lang.Thread.run(Thread.java:748)`

my redis config is
spring: 
  redis:
    host: 10.51.23.119
    port: 6381
    password: xxxxxx

version:
springcloud3.0.6
springboot2.5.14
redisson-spring-boot-starter 3.17.7

**Comment by mrniko** [comment]
Try version attached.

[redisson-3.23.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/12926375/redisson-3.23.6-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
resolved

**Comment by chenhao26-nineteen** [comment]
> Try version attached.
> 
> [redisson-3.23.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/12926375/redisson-3.23.6-SNAPSHOT.jar.zip)

Hello, when will this version be released back to the Maven repository?

**Comment by mrniko** [comment]
you need to use 3.24.1+ version

**Comment by chenhao26-nineteen** [comment]
Okay, thank you
