### ISSUE TITLE
Version 3.15.2 Waiting on object monitor when concurrently call RMapCache.get(Object key)

### ISSUE THREAD

**Issue by heroPeak** [redisson/redisson#5373]
The jstack info is:
"qtp1314740929-352" #352 prio=5 os_prio=0 tid=0x00007faa8c024000 nid=0x1a4 in Object.wait() [0x00007fa9da0e1000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:253)
        - locked <0x00000000f4e91788> (a io.netty.util.concurrent.ImmediateEventExecutor$ImmediatePromise)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
        at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
        at org.redisson.RedissonObject.get(RedissonObject.java:81)
        at org.redisson.RedissonMap.get(RedissonMap.java:639)
        at com.zte.xrexplore.edgeagent.helper.AlgorithmNodeCacheHelper.getNodeList(AlgorithmNodeCacheHelper.java:38)
        at com.zte.xrexplore.edgeagent.service.AlgorithmRegService.selectRegNode(AlgorithmRegService.java:91)
        at com.zte.xrexplore.edgeagent.service.impl.PlainModuleServiceImpl.reg(PlainModuleServiceImpl.java:249)
        at com.zte.xrexplore.edgeagent.controller.PlainModuleController.reg(PlainModuleController.java:132)
        at com.zte.xrexplore.edgeagent.controller.PlainModuleController$$FastClassBySpringCGLIB$$1add120b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.zte.xrexplore.edgeagent.controller.PlainModuleController$$EnhancerBySpringCGLIB$$945c2d1b.reg(<generated>)
        at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1043)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)

**Comment by mrniko** [comment]
try 3.17.6 version
