### ISSUE TITLE
KryoException on trying to upgrade from 3.15.5 to 3.23.5.



### ISSUE THREAD

**Issue by debraj-spotnana** [redisson/redisson#5375]
I am trying to upgrade redisson Java client from 3.15.5 to 3.23.5. I am getting the below error with 3.23.5.

```
 Caused by: com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
 Serialization trace:
 travelArrangers_ (com.spotnana.proto.v1.obt.traveler.GetTravelArrangersResponse)
     at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:146)
     at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
     at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880)
     at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144)
     at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:394)
     at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
     at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
     at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
     at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
     ... 17 common frames omitted
 Caused by: java.lang.UnsupportedOperationException: null
     at java.base/java.util.Collections$UnmodifiableCollection.add(Collections.java:1067)
     at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:241)
     at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:44)
     at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:799)
     at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:124)
     ... 26 common frames omitted

```

Can someone let me know are there any upgrade steps that I need to follow?

**Comment by mrniko** [comment]
Default codec has changed since 3.19.0 version to Kryo5Codec. You may need to migrate data or clear Redis data base or define deprecated MarshallingCodec in the configuration.

**Comment by amrit9326** [comment]
Hi , I'm also facing the same issue , I updated the pom from 3.17.7 to 3.23.5 and since then I'm getting below error , can anyone help.

Error :
onfigure.logging.ConditionEvaluationReportLogger","written_at":"2023-10-19T10:22:31.662Z","thread":"main","type":"log"}
   2023-10-19T15:52:31.69+0530 [APP/PROC/WEB/0] OUT {"msg":"Application run failed","level":"ERROR","written_ts":"1697710951696641305","logger":"org.springframework.boot.SpringApplication","written_at":"2023-10-19T10:22:31.694Z","thread":"main","type":"log","stacktrace":["org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisTemplate' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Unsatisfied dependency expressed through method 'redisTemplate' parameter 0: Error creating bean with name 'redissonConnectionFactory' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Unsatisfied dependency expressed through method 'redissonConnectionFactory' parameter 0: Error creating bean with name 'redisson' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception with message: com/esotericsoftware/kryo/serializers/DefaultSerializers$UUIDSerializer","\tat org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801)","\tat org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:545)","\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)","\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)","\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)","\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)","\tat org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)","\tat org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)","\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)","\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)","\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)","\tat org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)","\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)","\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)","\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)","\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)","\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:315)","\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)","\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)","\tat com.sap.dvh.Application.main(Application.java:21)","\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)","\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)","\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)",
   


Code :

@Configuration
public class RedisConfig {

  private static final Logger logger = LoggerFactory.getLogger(RedisConfig.class);

  @Autowired
  private VcapUtils vcapUtils;

  @Bean
  public Config config() {
    Config config = new Config();
  //  logger.info("AMRIT : {}", vcapUtils.getRedisURI());
    config.useSingleServer().setAddress(vcapUtils.getRedisURI());
    config.setCodec(new SerializationCodec());
    return config;
  }

  @Bean(name = "SpringCM")
  public CacheManager cacheManager(Config config) {
    CacheManager cacheManager = Caching.getCachingProvider().getCacheManager();
    cacheManager.createCache("rateLimit", RedissonConfiguration.fromConfig(config));
    return cacheManager;
  }

  @Bean
  public ProxyManager<String> proxyManager(CacheManager cacheManager) {
    return new JCacheProxyManager<>(cacheManager.getCache("rateLimit"));
  }
}
Please not when I'm using 3.17.7 the code is working fine but when I'm updating my pom to 3.23.5 it isn't working.
