### ISSUE TITLE
CPU Consumption is very high(~100%) on the server not allowing other services any CPU

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#5378]
Hello @mrniko ,

We are running redisson version 3.18.0 on our production application. We faced an issue once during some connectivity problems with Elasticache server when the CPU consumption of the server went as high as 100% and since we are running other services, it does not allow CPU to other services. When checking the dumps, we see that redisson netty and other threads were consuming more CPU and we are also seeing errors like below

` ERROR - Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:64:queue:0, freezeReason=RECONNECT, client=[addr=rediss://10.57.1.143:6379], nodeType=SLAVE, firstFail=1695984265922] java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. Server: 10.57.1.143/10.57.1.143:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1452) ~[?:?]
	at java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2337) ~[?:?]
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:197) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:122) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.connection.MasterSlaveEntry.slaveUpAsync(MasterSlaveEntry.java:467) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.cluster.ClusterConnectionManager.addRemoveSlaves(ClusterConnectionManager.java:564) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.cluster.ClusterConnectionManager.checkSlaveNodesChange(ClusterConnectionManager.java:490) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$11(ClusterConnectionManager.java:467) ~[redisson-3.18.0.jar:3.18.0]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.redisson.connection.MasterSlaveConnectionManager.lambda$resolveIP$4(MasterSlaveConnectionManager.java:728) ~[redisson-3.18.0.jar:3.18.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.InetSocketAddressResolver$1.operationComplete(InetSocketAddressResolver.java:60) [netty-resolver-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsNameResolver.trySuccess(DnsNameResolver.java:1009) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsNameResolver$6.operationComplete(DnsNameResolver.java:1038) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsNameResolver.trySuccess(DnsNameResolver.java:1009) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1021) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:471) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:232) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:224) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1314) [netty-resolver-dns-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. Server: 10.57.1.143/10.57.1.143:6379
	at org.redisson.connection.pool.ConnectionPool.createConnection(ConnectionPool.java:104) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:92) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:77) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.connection.pool.SlaveConnectionPool.initConnections(SlaveConnectionPool.java:30) ~[redisson-3.18.0.jar:3.18.0]
	at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:194) ~[redisson-3.18.0.jar:3.18.0]
	... 67 more`

Can you please help regarding the same.

**Comment by jainyash88** [comment]
[threadump09292023.txt](https://github.com/redisson/redisson/files/13029657/threadump09292023.txt)

Please find the attached threaddump file as well

**Comment by mrniko** [comment]
from you thread dump I don't see that redisson threads are busy with redisson code.

**Comment by jainyash88** [comment]
@mrniko If you look at the redisson timer thread , there are 3 of them each of which has consumed more than 1500 seconds of CPU time. For example below one has consumed around 2693 seconds

`"redisson-timer-10-1" #618 prio=5 os_prio=0 cpu=2693781.25ms elapsed=1706293.79s tid=0x0000000074bea800 nid=0x4f8 waiting on condition  [0x000000008724f000]
`
Apart from that other redisson-netty threads have consumed around 200 seconds in total..Is that normal? Please note that we were seeing thousands of error log entries  as below in one day

`ERROR - Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:64:queue:0, freezeReason=RECONNECT, client=[addr=rediss://10.57.1.143:6379], nodeType=SLAVE, firstFail=1695984265922] java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. 

Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. Server: 10.57.1.143/10.57.1.143:6379 at org.redisson.connection.pool.ConnectionPool.createConnection(ConnectionPool.java:104) ~[redisson-3.18.0.jar:3.18.0] at `

Also note that this is happening only on one server. We have multiple servers each of which is running application that uses same redisson client connecting to the same AWS Elasticache server. However others are not running in to this issue. Moreover this server only ran in to 100% CPU usage..

**Comment by mrniko** [comment]
It seems to be caused by this issue https://github.com/redisson/redisson/issues/3980. Please update to the latest version
