### ISSUE TITLE
PingConnectionHandler ERROR

### ISSUE THREAD

**Issue by ykrenz** [redisson/redisson#5388]
[] [eventId-42827b565f0d4d80b4f42f868aa75195] [PingConnectionHandler.java,97,org.redisson.client.handler.PingConnectionHandler,lambda$sendPing$1] [Unable to send PING command over channel: [id: 0x36c756fa, L:/10.7.74.157:36688 - R:r-wz9go0wmxu58bvyauh.redis.rds.aliyuncs.com/xxxxxx:6379]] ## ' org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://xxxxxx:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

<dependency>
  <groupId>org.redisson</groupId>
   <artifactId>redisson</artifactId>
    <version>3.17.6</version>
</dependency>

config:
String address;
String password;
int database;
int pingConnectionInterval = 30000;

**Comment by mrniko** [comment]
Upgrade to 3.26.1+ version
