### ISSUE TITLE
RedisException: ERR invalid expire time in set; at 3.24.2

### ISSUE THREAD

**Issue by wbsch52** [redisson/redisson#5392]
Hi,

I got an Exception is `org.redisson.client.RedisException: ERR Error running script (call to f_6866459238a13a701d42f4971f12d9f3a50e2442): @user_script:1: ERR invalid expire time in set` when the code try to unlock the lock.

My environments are as follows:
redisson: 3.24.2
redisson-spring-data-26: 3.24.2
spring-data-redis: 2.7.5
Redis Server: 5.0.7

My code example below:
```
String lockKey = "example";
RLock lock = redissonClient.getLock(lockKey);
if (lock.isLocked()) {
    // do something...
    return;
}
try {
    lock.lock();
    // do something...
} finnaly {
    lock.unlock(); // I got an Exception at this line.
}
```

Stacktrace detail:
```
org.redisson.client.RedisException: ERR Error running script (call to f_6866459238a13a701d42f4971f12d9f3a50e2442): @user_script:1: ERR invalid expire time in set . channel: [id: 0x2656a120, L:/127.0.0.1:60056 - R:localhost/127.0.0.1:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@6858402c[Not completed], params: [local val = redis.call('get', KEYS[3]); if val ~= false then return tonumber(val);end; if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); redis.call('set', KEYS[3], 0, 'px', ARGV[5]); return 0; else redis.call('del', KEYS[1]); redis.call(ARGV[4], KEYS[2], ARGV[1]); redis.call('set', KEYS[3], 1, 'px', ARGV[5]); return 1; end; , 3, example, redisson_lock__channel:{example}, redisson_unlock_latch:{example}:8ded394b2d991fe45ded7e1491c0b857, 0, 30000, 3ad56635-077c-4062-865e-fda6e8c40f9b:130, PUBLISH, 0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:381)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:279)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:217)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Could you check this issue please?

Thanks alot.

**Comment by mrniko** [comment]
Can you share Redisson config?

**Comment by wbsch52** [comment]
> Can you share Redisson config?

This is my Redisson config:
```
singleServerConfig:
    address: "redis://localhost:6379"
    database: 0
    password: "Helloworld"
    keepAlive: true
    tcpNoDelay: true
    timeout: 2000
    connectTimeout: 2000
    retryAttempts: 0
    retryInterval: 500
    pingConnectionInterval: 5000
codec: !<org.redisson.codec.JsonJacksonCodec> {}
```

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by hetasanghvi** [comment]
seeing this again today

**Comment by mrniko** [comment]
which Redisson version?
