### ISSUE TITLE
Redisson.getBlockingDeque：java.lang.NoClassDefFoundError: java/util/SequencedCollection

### ISSUE THREAD

**Issue by xqdd** [redisson/redisson#5402]
```log
java.lang.NoClassDefFoundError: java/util/SequencedCollection
	at org.redisson.Redisson.getBlockingDeque(Redisson.java:618) ~[redisson-3.24.3.jar:3.24.3]
```

**Expected behavior**

not error

**Actual behavior**

throw exception

**Steps to reproduce or test case**

use java8 with spring boot 2.4.4

**Redis version**

7.0.3

**Redisson version**

3.24.3

**Redisson configuration**

normal

**Comment by timnick-snow** [comment]
some error!

```java
        RedissonClient redissonClient = Redisson.create(config);

        RDeque<String> deque = redissonClient.getDeque("test-deque");
        deque.addLast("foo");

        assertThat(deque.pollFirst()).isEqualTo("foo");
```


```text
java.lang.NoClassDefFoundError: java/util/SequencedCollection

	at org.redisson.Redisson.getDeque(Redisson.java:603)
	at SimpleTest.fun5(SimpleTest.java:32)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: java.util.SequencedCollection
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more
```

work fine on java21.  but error on java8/11/17

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by xiohuchi** [comment]
我也遇到了，什么时候能修复这个错误

**Comment by xiohuchi** [comment]
3.24.4 版本什么时候发布呀

**Comment by timnick-snow** [comment]
> 我也遇到了，什么时候能修复这个错误

我已经回退到 3.23.5 版本了

**Comment by xiohuchi** [comment]
我先退回至3.23.3版本，等3.24.4版本发布再升上去

**Comment by xiohuchi** [comment]
> > 我也遇到了，什么时候能修复这个错误
> 
> 我已经回退到 3.23.5 版本了

好巧啊，一早上居然有人跟我遇到一样的问题，我也是退回版本了

**Comment by V0idk** [comment]
shit, what a rookie bug

**Comment by mrniko** [comment]
@V0idk 

Did you upgrade to 3.25.0 or higher?
