### ISSUE TITLE
RedisTimeoutException Error Message

### ISSUE THREAD

**Issue by sumlittle** [redisson/redisson#5428]
2023-11-13 at 08:26:00 AST ERROR org.redisson.client.handler.PingConnectionHandler 89 lambda$sendPing$1 - Unable to send PING command over channel: [id: 0x029cbc21, L:/fd00:0:17:3005:0:0:0:11:32926 - R:fd00:0:17:3002:0:0:0:73/fd00:0:17:3002:0:0:0:73:26381] org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://fd00:0:17:3002:0:0:0:73:26381]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256) ~[redisson-3.23.5.jar!/:3.23.5]
	at org.redisson.client.RedisConnection$$Lambda$596/85443820.run(Unknown Source) ~[?:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) [netty-common-4.1.52.Final.jar!/:4.1.52.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) [netty-common-4.1.52.Final.jar!/:4.1.52.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) [netty-common-4.1.52.Final.jar!/:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.52.Final.jar!/:4.1.52.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_11]

**Comment by KalpeshPatil02** [comment]
Verify that the Redis server at the address redis://fd00:0:17:3002:0:0:0:73:26381 is up and running. Ensure that there are no network issues or firewall rules preventing the Redisson client from connecting to the Redis server.

**Comment by sumlittle** [comment]
This is the version we use.

		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-boot-starter</artifactId>
			<version>3.23.5</version>
			<exclusions>
				<exclusion>
					<groupId>org.redisson</groupId>
					<artifactId>redisson-spring-data-31</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-data-21</artifactId>
			<version>3.23.5</version>
		</dependency>
		We used The redis connection is normal. Our environment is an intranet and there is no firewall between us.

**Comment by mrniko** [comment]
You need to upgrade to 3.26.1+ version.
