### ISSUE TITLE
Redisson Stability issues with cluster configuration endpoint

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#5446]
Hello @mrniko 

We are facing stability issues when using the cluster configuration endpoint. Please note that so far we used individual Node addresses for connection configuration.

However as suggested by AWS we need to use the cluster configuration endpoint. However when using the same, we run in to different exceptions time and again. We tested out with a sample application that just saves a very small map and reads the same. It is very minimal load. However after running for few hours , I see below exceptions. Note that there is no increase in the activity with redis

`org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase nettyThreads setting. Node source: NodeSource [slot=7638, addr=rediss://10.1.22.135:6379, redisClient=null, redirect=MOVED, entry=null], connection: RedisConnection@1211406248 [redisClient=[addr=rediss://clustercfg.qaw01-flipper-esse-s002.gzreim.usw1.cache.amazonaws.com:6379], channel=[id: 0xabade193, L:0.0.0.0/0.0.0.0:59718], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@4b773f99[Not completed, 1 dependents], command=(GET), params=[abc], codec=org.redisson.client.codec.StringCodec], usage=1], command: (GET), params: [abc] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:357) ~[redisson-3.24.3.jar:3.24.3]
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:195) ~[redisson-3.24.3.jar:3.24.3]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:57) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:57) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndCompleteAll(AbstractCoalescingBufferQueue.java:360) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndFailAll(AbstractCoalescingBufferQueue.java:218) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:908) ~[netty-handler-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:821) ~[netty-handler-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:802) ~[netty-handler-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:88) ~[redisson-3.24.3.jar:3.24.3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:905) ~[netty-handler-4.1.100.Final.jar:4.1.100.Final]
	... 22 more`

`org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (10000 ms) occured after 3 retry attempts, is non-idempotent command: false Check connection with Redis node: clustercfg.qaw01-flipper-esse-s002.gzreim.usw1.cache.amazonaws.com/10.1.22.242:6379 for TCP packet drops or bandwidth limits.  Try to increase nettyThreads and/or timeout settings. Command: (GET), params: [abc], channel: [id: 0xc780a91f, L:0.0.0.0/0.0.0.0:55772]
	at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$9(RedisExecutor.java:419) ~[redisson-3.24.3.jar:3.24.3]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[?:?]
` 

Not sure what is causing this and why we dont run in to these issues when using Node addresses.

I am also attaching the logs. Can you please help to check the same
[ClusterConfigurationEndpointlogs.txt](https://github.com/redisson/redisson/files/13426680/ClusterConfigurationEndpointlogs.txt)

**Comment by mrniko** [comment]
It's SSL issue. Can you recreate the AWS cluster?

**Comment by mrniko** [comment]
> @mrniko The SSL configuration is not an issue.. 

`io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:905) ~[netty-handler-4.1.100.Final.jar:4.1.100.Final] ... 22 more`

**Comment by jainyash88** [comment]
@mrniko We are seeing this error after sometime and there was successful read/write operation with redis. Please note that the same error does NOT appear when using node addresses

**Comment by hlms** [comment]
@mrniko ,  
Any updates on this?  
Re-creating AWS Cluster isn't an option when one runs into such issues in production. 

Such issues would force people to move to another redis client.

**Comment by mrniko** [comment]
@hlms 

Can you share the Redisson config?

**Comment by mrniko** [comment]
It's related to this issue [SSLEngine closed already](https://github.com/netty/netty/issues/12555)

**Comment by mrniko** [comment]
@jainyash88 

Can you share the logs from the application start moment?

**Comment by hlms** [comment]
Sure, @mrniko .  
We (@jainyash88 and I) will collect the requested information, and will provide the update.

**Comment by mrniko** [comment]
I also need Redisson config you use

**Comment by jainyash88** [comment]
@mrniko Please find the config as below

`{
   "clusterServersConfig":{
      "idleConnectionTimeout":1000,
      "connectTimeout":1000,
      "timeout":2500,
      "retryAttempts":2,
      "retryInterval":500,
      "failedSlaveReconnectionInterval":1000,
      "failedSlaveCheckInterval":6000,
      "password":"wjfjd3ENDfGSbrCUTEzZDYspxPy5dn2W6FhGChCG4VwR2UUvRVWvjQHsD67QeDXH",
      "subscriptionsPerConnection":5,
      "clientName":null,
      "subscriptionConnectionPoolSize":50,
      "slaveConnectionMinimumIdleSize":32,
      "slaveConnectionPoolSize":64,
      "masterConnectionMinimumIdleSize":32,
      "masterConnectionPoolSize":64,
      "readMode":"SLAVE",
      "subscriptionMode":"SLAVE",
      "nodeAddresses":[
         "rediss://clustercfg.qaw01-appcontext-esse-s001.gzreim.usw1.cache.amazonaws.com:6379"
      ],
      "scanInterval":1000,
      "pingConnectionInterval":0,
      "keepAlive": false,
      "tcpNoDelay": false
   },
   "threads":32,
   "nettyThreads":32,
   "transportMode":"NIO"
}`

Also please let me know how to share the log file. The log file is quite huge (> 500 MB) as I have enabled debug logs. Please note that I cannot enable trace logs as that generates humongous files and saturates our storage.

**Comment by jainyash88** [comment]
[ClusterConfig.json](https://github.com/redisson/redisson/files/13647022/ClusterConfig.json)

Attached the Redisson config file here. The content is same as mentioned on the above comment.

**Comment by mrniko** [comment]
@jainyash88 

I need the logs from the start application moment till the first appearance of the first WriteRedisConnectionException. Is it possible?

**Comment by jainyash88** [comment]
[RedissonDebugLogs.log](https://github.com/redisson/redisson/files/13648958/RedissonDebugLogs.log)

@mrniko We are seeing DNS errors with cluster configuration endpoint and it seems redisson is not able to recover from the same for a long time. Attaching the logs for the issue.. I have taken a section of logs where I see the issue and I can see that redisson reports DNS issues for a long time. Please note if we use node addresses we do NOT run in to this issue. Also we do not have any issues on the AWS cluster.

cc @hlms

**Comment by jainyash88** [comment]
@mrniko As of now the logs do NOT show WriteRedisConnectionException. I can see issues with DNS resolution and have attached the logs earlier.

**Comment by mrniko** [comment]
make sure that you have 4.1.88 or later netty version in classpath. 

Try to set `addressResolverGroupFactory = new SequentialDnsAddressResolverFactory(N);` in Redisson configuration.

Yaml config

`addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> N`

N is the number 1, 2 ... you need to find the optimal one for your application.

**Comment by mrniko** [comment]
Any update?

**Comment by jainyash88** [comment]
@mrniko I can try with SequentialDnsAddressResolverFactory. However can you let me know how to decide the optimal number N for our application. Does it require multiple rounds of testing? Also you have marked the milestones for this issue. Are you going to address this in the upcoming releases?

**Comment by mrniko** [comment]
@jainyash88 

> Does it require multiple rounds of testing?

I recommend to start with 1. If it fine then you can continue to increase this value until you meet the issue. 

> Are you going to address this in the upcoming releases?

You don't need to wait for any release. SequentialDnsAddressResolverFactory has been available since 3.18.0 version.

> Are you asking to reduce this and test?

yes.

**Comment by mrniko** [comment]
@jainyash88 

Is there any update?
