### ISSUE TITLE
If the lock is not obtained, an exception occurs

### ISSUE THREAD

**Issue by freedom0123** [redisson/redisson#5461]
Redission Java
1）version：3.17.4
2）code

```java
@Scheduled(cron = "${data.schedule}")
    public void execute() {
        RLock rLock = redissonClient.getLock(key);
        try {
            if (rLock.tryLock(10, TimeUnit.MILLISECONDS)) {
                dataService.handlerOtherService();
            }
        } catch (InterruptedException e) {
            log.error("中断异常：",e);
            Thread.currentThread().interrupt();
        } finally {
            if (rLock.isLocked() && rLock.isHeldByCurrentThread()) {
                rLock.unlock();
            }
        }
    }
```
In a 5-master and 5-slave environment, the lock is added in this way. When the lock is not obtained, an exception occurs
```markdown
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:235)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:297)
	at com.channelsoft.datasync.task.DataUpdateTask.execute(DataUpdateTask.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4662
