### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalStateException: Subscription registration timeout exceeded.

### ISSUE THREAD

**Issue by shixingze** [redisson/redisson#5482]
采用版本号
```
<spring-boot.version>2.7.9</spring-boot.version>
<redisson.version>3.20.0</redisson.version>
```

报错位置
```
@onopen
public void onOpen(Session session, @PathParam("userId") String roomId, @PathParam("zcjCode") String zcjCode) throws Exception {
this.roomId = roomId;
try {
//获取sessionId作为通道号
stringRedisTemplate.opsForValue().set(WEBSOCKET + session.getId(),"roomid:"+roomId);
//redis存储访问session
stringRedisTemplate.opsForValue().set(zcjCode,session.getId());
LOGGER.info("建立监听sessionID为["+session.getId()+"]");
//创建监听对象
RedisMessageListener redisMessageListener = new RedisMessageListener(session.getId(), session);
//添加监听
redisMessageListenerMap.put(session.getId(),redisMessageListener);
SessionDoman doman = new SessionDoman(System.currentTimeMillis(),session.getId(),session);
sessionList.put(session.getId(),doman);
container.addMessageListener(redisMessageListener, channelTopic);
}catch (Exception e){
LOGGER.error("建立监听发生错误["+session.getId()+"]");
throw new RuntimeException(e);
}
System.out.println("ceshi");

}
```
异常

**Comment by shixingze** [comment]
异常
2023-12-04 17:09:08 [XNIO-1 task-1] ERROR c.r.c.websocket.GetMessageWebSocket - 建立监听发生错误[5_aEzFvXwfFfyey4O4DbShzbem_naeTa5QRJZGdD]
2023-12-04 17:09:08 [XNIO-1 task-1] ERROR c.r.c.websocket.GetMessageWebSocket - 发生错误session为[5_aEzFvXwfFfyey4O4DbShzbem_naeTa5QRJZGdD]
java.lang.RuntimeException: java.lang.IllegalStateException: Subscription registration timeout exceeded.
	at com.ruoyi.carloadermgr.websocket.GetMessageWebSocket.onOpen(GetMessageWebSocket.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87)
	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$3.run(AnnotatedEndpoint.java:158)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:600)
	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint.invokeMethod(AnnotatedEndpoint.java:153)
	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint.onOpen(AnnotatedEndpoint.java:102)
	at io.undertow.websockets.jsr.EndpointSessionHandler.onConnect(EndpointSessionHandler.java:129)
	at io.undertow.websockets.jsr.JsrWebSocketFilter$1.handleUpgrade(JsrWebSocketFilter.java:165)
	at io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(HttpReadListener.java:390)
	at io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(HttpServerConnection.java:244)
	at io.undertow.server.HttpServerExchange.invokeExchangeCompleteListeners(HttpServerExchange.java:1353)
	at io.undertow.server.HttpServerExchange.terminateResponse(HttpServerExchange.java:1637)
	at io.undertow.server.Connectors.terminateResponse(Connectors.java:182)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:199)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:197)
	at io.undertow.conduits.HeadStreamSinkConduit.exitFlush(HeadStreamSinkConduit.java:192)
	at io.undertow.conduits.HeadStreamSinkConduit.flush(HeadStreamSinkConduit.java:133)
	at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
	at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119)
	at org.xnio.channels.Channels.flushBlocking(Channels.java:63)
	at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:626)
	at io.undertow.servlet.spec.HttpServletResponseImpl.closeStreamAndWriter(HttpServletResponseImpl.java:502)
	at io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:591)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:334)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Subscription registration timeout exceeded.
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:280)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.addListener(RedisMessageListenerContainer.java:668)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.addMessageListener(RedisMessageListenerContainer.java:537)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.addMessageListener(RedisMessageListenerContainer.java:548)
	at com.ruoyi.carloadermgr.websocket.GetMessageWebSocket.onOpen(GetMessageWebSocket.java:69)
	... 47 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:269)
	... 51 common frames omitted
2023-12-04 17:09:08 [conseScheduled-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task

**Comment by mrniko** [comment]
Which Redisson configuration?

**Comment by shixingze** [comment]
> 哪种 Redisson 配置？
this

redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 7
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${ruoyi.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 4
    # 连接池大小
    connectionPoolSize: 16
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 1000000
    # 命令等待超时，单位：毫秒
    timeout: 100000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

**Comment by mrniko** [comment]
Can you try the attached module?

[redisson-spring-data-27-3.25.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13658400/redisson-spring-data-27-3.25.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed. Thanks for report
