### ISSUE TITLE
RedissonMultiLock attempt to unlock lock, not locked by current thread by node id: d0ab590d-f55b-4c1b-9c13-0e67ad1543f9 thread-id: 1

### ISSUE THREAD

**Issue by YLongGe** [redisson/redisson#5484]
An error occurs when using RedissonMultiLock, used method ->  lock.lock(10, TimeUnit.SECONDS);

java.util.concurrent.CompletionException: java.lang.IllegalMonitorStateException: **attempt to unlock lock, not locked by current thread by node id: d0ab590d-f55b-4c1b-9c13-0e67ad1543f9 thread-id: 1**
       at org.redisson.RedissonBaseLock.lambda$unlockAsync$2(RedissonBaseLock.java:325)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:322)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:162)
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:478)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:172)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:318)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:210)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: d0ab590d-f55b-4c1b-9c13-0e67ad1543f9 thread-id: 1
	at org.redisson.RedissonBaseLock.lambda$unlockAsync$2(RedissonBaseLock.java:323)
	... 39 more

My code is as follows:

    @Resource
    private RedissonClient redissonClient;

    @Test
    void testRedisLock() {
        RLock lock1 = redissonClient.getLock("lock-test-" + 1L);
        RLock lock2 = redissonClient.getLock("lock-test-" + 2L);
        RLock lock3 = redissonClient.getLock("lock-test-" + 3L);

        RLock lock = redissonClient.getMultiLock(lock1, lock2, lock3);
        try {
            lock.lock(10, TimeUnit.SECONDS);
            Thread.sleep(1000);
            log.info("thread-id: {}", Thread.currentThread().getId());
        } catch (InterruptedException e) {
           Thread.currentThread().interrupt();
        } finally {
            lock.unlock();
        }
    }

**redis is a cluster mode**

**version:**
  <groupId>org.redisson</groupId>
  <artifactId>redisson-spring-boot-starter</artifactId>
  <version>3.17.1</version>

 
Thanks.

**Comment by mrniko** [comment]
Can you try 3.24.3 version?

**Comment by YLongGe** [comment]
I have switched to 3.24.3 version, It still doesn't work. 
The error remains the same as before.

> Can you try 3.24.3 version?

**Comment by javalxg** [comment]
why
