### ISSUE TITLE
Command execution timeout for command: (CLUSTER NODES)

### ISSUE THREAD

**Issue by kkrgwbj** [redisson/redisson#5489]
23-12-07 01:27:10.038 ERROR 25499
            --- [isson-timer-7-1] o.r.c.ClusterConnectionManager           : Unable to execute (CLUSTER NODES)

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=redis://10.218.105.15:6380]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256) ~[redisson-3.24.1.jar!/:3.24.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:719) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:707) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:794) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:507) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Redis version**

7.0

**Redisson version**

3.24.1

**Redisson configuration**

cluster

**Comment by easybyr** [comment]
我也遇见同样的报错信息，使用的redisson版本：3.21.1，请问解决了吗？

**Comment by Shawn070** [comment]
same error, 3.12.2

**Comment by mshahmoradi87** [comment]
We have same error for both CLUSTER NODES and PING

Redis: 7.1 aws serverless
redisson 3.29.0

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://1.1.1.1:6379]
at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:750)


org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=rediss://1.1.1.1:6379]
at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:750)

**Comment by MartinLim94-Work** [comment]
we have the same error...

Redis: 7.1 AWS Serverless
redisson: 3.32.0
redisson configuration: cluster

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=rediss://10.12.9.60:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by mshahmoradi87** [comment]
> we have the same error...
> 
> Redis: 7.1 AWS Serverless redisson: 3.32.0 redisson configuration: cluster
> 
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=rediss://10.12.9.60:6379] at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253) at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:1583)

Try redisson 3.36.0, there were some related improvements

**Comment by ZhaoJianxin1021** [comment]
we have the same error...
redis version 5.0.5   cluster
redisson.client,RedisTimeoutlxception:Command execution timeout for command: (CLUSTER NoDES), params: [l, Redis client: [addr=redis://10.16.65.73:7005 org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253) at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by ZhaoJianxin1021** [comment]
we have the same error...
redis version 5.0.5   cluster
redisson.client,RedisTimeoutlxception:Command execution timeout for command: (CLUSTER NoDES), params: [l, Redis client: [addr=redis://10.16.65.73:7005 org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253) at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by mrniko** [comment]
@ZhaoJianxin1021 

Did you try 3.36.0 or higher version?
