### ISSUE TITLE
NullPointerException at RedissonBaseLock.evalWriteAsync

### ISSUE THREAD

**Issue by youxiaxiaomage** [redisson/redisson#5492]
java.lang.NullPointerException: null
        at org.redisson.RedissonBaseLock.evalWriteAsync(RedissonBaseLock.java:217) ~[redisson-3.16.8.jar!/:3.16.8]
        at org.redisson.RedissonFairLock.tryLockInnerAsync(RedissonFairLock.java:156) ~[redisson-3.16.8.jar!/:3.16.8]
        at org.redisson.RedissonLock.tryAcquireAsync(RedissonLock.java:173) ~[redisson-3.16.8.jar!/:3.16.8]
        at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:144) ~[redisson-3.16.8.jar!/:3.16.8]
        at org.redisson.RedissonLock.tryLock(RedissonLock.java:218) ~[redisson-3.16.8.jar!/:3.16.8]

source code 

```
protected <T> RFuture<T> evalWriteAsync(String key, Codec codec, RedisCommand<T> evalCommandType, String script, List<Object> keys, Object... params) {
        MasterSlaveEntry entry = commandExecutor.getConnectionManager().getEntry(getRawName());
        int availableSlaves = entry.getAvailableSlaves();

        CommandBatchService executorService = createCommandBatchService(availableSlaves);
        RFuture<T> result = executorService.evalWriteAsync(key, codec, evalCommandType, script, keys, params);
        if (commandExecutor instanceof CommandBatchService) {
            return result;
        }

        RFuture<BatchResult<?>> future = executorService.executeAsync();
        CompletionStage<T> f = future.handle((res, ex) -> {
            if (ex == null && res.getSyncedSlaves() != availableSlaves) {
                throw new CompletionException(new IllegalStateException("Only "
                                                        + res.getSyncedSlaves() + " of " + availableSlaves + " slaves were synced"));
            }

            return result.getNow();
        });
        return new CompletableFutureWrapper<>(f);
}
```
int availableSlaves = entry.getAvailableSlaves();  this line has occurred npe.
Redis version
6.2.4

Redisson version 3.16.8

**Comment by mrniko** [comment]
Fixed in 3.17.7 version.
