### ISSUE TITLE
NullPointerException while shutting down multiple instance of ReddisonClient

### ISSUE THREAD

**Issue by Ionuc** [redisson/redisson#5508]
**Background**
I have a client server which is connecting to a redis cluster using a yaml file. In the production setup, the server will create 2 RedissonClient to the same Redis Cluster, where each will a different RLocalCacheMap for 2 different models. When the server will shutdown, it will close both ReddissonClients

**Expected behavior**
When ,closing both clients, no exception to be thrown

**Actual behavior**
A NullPointerException is thrown with the stacktrace 

`
11-30 00:47:10,680 [redisson-netty-2-3] [CommandPubSubDecoder] ERROR: Unable to decode data. channel: [id: 0x6181f951, L:/<ip>:<processNr> - R:<ip>/<ip>:<port>], reply: ReplayingDecoderByteBuf(ridx=8124, widx=8124)
java.lang.NullPointerException
        at org.redisson.client.handler.CommandPubSubDecoder.selectDecoder(CommandPubSubDecoder.java:252)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:437)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:402)
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:99)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
`

**Steps to reproduce or test case**
This error appears once in a month, where the server is started and closed each day.
Steps to reproduce:
- create 2 RedissonClients
- create a RLocalCacheMap, where the key codec is StringCodec, and the value codec is JsonJacksonCodec
- close both clients using "redissonClient.shutdown()" method

**Redis version**
Redis version 6.2.6

**Redisson version**
Redisson version 3.21.3

**Redisson configuration**
Redisson yamml configuration file:
clusterServersConfig:
nodeAddresses:
- "redis://url1:port1"
- "redis://url2:port2"
- ....
idleConnectionTimeout: 30000
connectTimeout: 15000
timeout: 5000
retryAttempts: 3
retryInterval: 3000
failedSlaveReconnectionInterval: 15000
failedSlaveCheckInterval: 60000
subscriptionsPerConnection: 5
subscriptionConnectionMinimumIdleSize: 1
subscriptionConnectionPoolSize: 50
slaveConnectionMinimumIdleSize: 2
slaveConnectionPoolSize: 24
masterConnectionMinimumIdleSize: 2
masterConnectionPoolSize: 24
readMode: "MASTER"
subscriptionMode: "MASTER"
scanInterval: 1000
pingConnectionInterval: 60000
keepAlive: false
tcpNoDelay: true

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5308
