### ISSUE TITLE
RedisTimeoutException

### ISSUE THREAD

**Issue by MochaMousse** [redisson/redisson#5509]
Version: 3.24.1
```
2023-12-18T04:11:16.409+08:00 org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=redis://192.168.0.1:7000]
2023-12-18T04:11:16.409+08:00   at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256) ~[redisson-3.24.1.jar!/:3.24.1]
2023-12-18T04:11:16.409+08:00   at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
2023-12-18T04:11:16.409+08:00   at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
2023-12-18T04:11:16.409+08:00   at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
2023-12-18T04:11:16.409+08:00   at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
2023-12-18T04:11:16.409+08:00   at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
2023-12-18T04:11:16.409+08:00   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
2023-12-18T04:11:16.409+08:00   at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
```

**Comment by mrniko** [comment]
Upgrade to 3.36.0 version or higher
