### ISSUE TITLE
Command Execution Timeout for Command : (AUTH)

### ISSUE THREAD

**Issue by Ataoglan** [redisson/redisson#5515]
Hello,

I am trying to connect redis server with password but I am getting timeout exception. I read same questions but didnt help me. Currently I am using 3.24.3 version redisson, Here is my config,

    Config config = new Config();
    config.useClusterServers().addNodeAddress(endpoint) //endpoint = redis://+url+:6379
          .setPassword(password)
              .setSslEnableEndpointIdentification(false)
        .setMasterConnectionMinimumIdleSize(2)
              .setMasterConnectionPoolSize(3)
              .setConnectTimeout(10000)
              .setTimeout(10000);
    

    return Redisson.create(config);

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` package and share the output since the application start moment?

**Comment by Ataoglan** [comment]
```
2023-12-20T11:03:04.665+03:00 TRACE 76011 --- [isson-netty-1-6] o.r.client.handler.CommandEncoder        : channel: [id: 0x6386b25d, L:/192.000:61755 - R:test.redis.com/192.000:6379] message: *2
$4
AUTH(password masked)
2023-12-20T11:03:04.665+03:00 TRACE 76011 --- [isson-netty-1-6] o.r.client.handler.CommandEncoder        : channel: [id: 0x6386b25d, L:/192.000:61755 - R:test.redis.com/192.000:6379] message: *1
$4
PING

2023-12-20T11:03:14.585+03:00  WARN 76011 --- [           main] o.r.cluster.ClusterConnectionManager     : null
2023-12-20T11:03:16.477+03:00 DEBUG 76011 --- [isson-netty-1-9] org.redisson.client.RedisConnection      : Connection created [addr=redis://test.redis.com:6379]
2023-12-20T11:03:16.577+03:00 TRACE 76011 --- [isson-netty-1-9] o.r.client.handler.CommandEncoder        : channel: [id: 0x7b6410e1, L:/192.000:61758 - R:test.redis.com/192.000:6379] message: *2
$4
AUTH(password masked)
2023-12-20T11:03:16.577+03:00 TRACE 76011 --- [isson-netty-1-9] o.r.client.handler.CommandEncoder        : channel: [id: 0x7b6410e1, L:/192.000:61758 - R:test.redis.com/192.000:6379] message: *1
$4
PING

2023-12-20T11:03:26.096+03:00  WARN 76011 --- [           main] o.r.cluster.ClusterConnectionManager     : null
2023-12-20T11:03:27.607+03:00 DEBUG 76011 --- [sson-netty-1-12] org.redisson.client.RedisConnection      : Connection created [addr=redis://test.redis.com:6379]
2023-12-20T11:03:27.688+03:00 TRACE 76011 --- [sson-netty-1-12] o.r.client.handler.CommandEncoder        : channel: [id: 0x3af5d340, L:/192.000:61761 - R:test.redis.com/192.000:6379] message: *2
$4
AUTH(password masked)
2023-12-20T11:03:27.689+03:00 TRACE 76011 --- [sson-netty-1-12] o.r.client.handler.CommandEncoder        : channel: [id: 0x3af5d340, L:/192.000:61761 - R:test.redis.com/192.000.23.42:6379] message: *1
$4
PING

2023-12-20T11:03:37.608+03:00  WARN 76011 --- [           main] o.r.cluster.ClusterConnectionManager     : null
2023-12-20T11:03:37.618+03:00  WARN 76011 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: Factory method 'redissonClient' threw exception with message: Can't connect to servers!
2023-12-20T11:03:37.619+03:00  INFO 76011 --- [nformed client)] net.spy.memcached.MemcachedConnection    : Shut down memcached client
2023-12-20T11:03:37.620+03:00  INFO 76011 --- [           main] org.eclipse.jetty.server.Server          : Stopped Server@7604198a{STOPPING}[11.0.17,sto=0]
2023-12-20T11:03:37.623+03:00  INFO 76011 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@4597e6e3{application,/,[file:///private/var/folders/lx/pt8b_xmj3zl1gk3k8slk56wm0000gp/T/jetty-docbase.8102.9751972298805093555/, jar:file:/Users/ozcan/.m2/repository/org/webjars/swagger-ui/5.2.0/swagger-ui-5.2.0.jar!/META-INF/resources],STOPPED}
2023-12-20T11:03:37.635+03:00  INFO 76011 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-20T11:03:37.646+03:00 ERROR 76011 --- [           main] o.s.boot.SpringApplication               : Application run failed
```

**Comment by Ataoglan** [comment]
with cli I can ping the redis server btw @mrniko

**Comment by mrniko** [comment]
>  Exception encountered during context initialization - cancelling refresh attempt: Factory method 'redissonClient' threw exception with message: Can't connect to servers!

Can you share the full stacktrace?

**Comment by Ataoglan** [comment]
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-6.0.13.jar:6.0.13]
	... 60 common frames omitted
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.doConnect(ClusterConnectionManager.java:164) ~[redisson-3.25.1.jar:3.25.1]
	at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:196) ~[redisson-3.25.1.jar:3.25.1]
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:220) ~[redisson-3.25.1.jar:3.25.1]
	at org.redisson.Redisson.<init>(Redisson.java:65) ~[redisson-3.25.1.jar:3.25.1]
	at org.redisson.Redisson.create(Redisson.java:110) ~[redisson-3.25.1.jar:3.25.1]
	at rotate.app.config.RedisConfig.redissonClient(RedisConfig.java:35) ~[classes/:na]
	at rotate.app.config.RedisConfig$$SpringCGLIB$$0.CGLIB$redissonClient$0(<generated>) ~[classes/:na]
	at rotate.app.config.RedisConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.13.jar:6.0.13]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.13.jar:6.0.13]
	at rotate.app.config.RedisConfig$$SpringCGLIB$$0.redissonClient(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.13.jar:6.0.13]
	... 61 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://test.redis.tazedirekt.com:6379]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[na:na]
	at org.redisson.cluster.ClusterConnectionManager.doConnect(ClusterConnectionManager.java:96) ~[redisson-3.25.1.jar:3.25.1]
	... 74 common frames omitted
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://test.redis.tazedirekt.com:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256) ~[redisson-3.25.1.jar:3.25.1]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]

**Comment by mrniko** [comment]
try `rediss://` url prefix
