### ISSUE TITLE
ARGV array inside a Lua script have wrong values

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [redisson/redisson#5519]
Hello, we use Redis to run GCR algorithm for rate limiting functionality.

To do this, we use Lua script that we execute on one of the Redis nodes. The script content is very similar to the one from [here](https://github.com/rwz/redis-gcra/blob/master/vendor/perform_gcra_ratelimit.lua)

The problem that occurs from time to time, under high load, is that the `ARGV` array has wrong values. This array contains arguments for GCR algorithm - burst, rate, period, and cost. We always pass `1` as a cost, it is hardcoded value, see below:

```kotlin
// example in kotlin
script.evalSha<ArrayList<Any>>(
            key, // key
            RScript.Mode.READ_WRITE,
            scriptSha,
            RScript.ReturnType.MULTI,
            listOf(key), // keys
            burst, // ARGV[1]
            rate, // ARGV[2]
            period,  // ARGV[3]
            1, // // ARGV[4], cost
        ).awaitSingle()
```

What we experienced is that the cost property had a wrong value, instead of 1, it was set to 10_000_000.

We passed these values as arguments: 10_000_000, 10_000_000, 1, 1

Inside the script, these values were used: 10_000_000, 10_000_000, 1, 10_000_000 (we returned ARGV from a script to debug this).

**Expected behavior**

Proper values are passed to the script

**Actual behavior**

Sometimes, under high load, ARGV array has wrong values

**Steps to reproduce or test case**

Unfortunately, i couldn't reproduce this issue locally 🙁 

**Redis version**

We use ElasticCache cluster (3 master nodes + 3 replica nodes). We use the same key for all the operations. Engine version: `5.0.6`.

**Redisson version**

org.redisson:redisson-spring-boot-starter:3.24.3

**Redisson configuration**

Defaults, we set `SPRING_DATA_REDIS_CLUSTER_NODES` to a cluster config node address, we turn SSL on, and we provide password via `SPRING_DATA_REDIS_PASSWORD`.

**Comment by mrniko** [comment]
I hear about such an issue for the first time. 

> We need to wait a few minutes to experience the issue.

You can set `trace` logging level for `org.redisson.client.handler.CommandEncoder` to check that Redisson sends args in correct order.

**Comment by mrniko** [comment]
Unable to reproduce with the test below.

```java
        ExecutorService e = Executors.newFixedThreadPool(32);

        AtomicInteger errors = new AtomicInteger();
        for (int i = 0; i < 1_000_000; i++) {
            e.submit(() -> {
                try {
                    RScript script = redisson.getScript(StringCodec.INSTANCE);
                    List<Object> res = script.eval(RScript.Mode.READ_ONLY, "return {ARGV[1], ARGV[2], ARGV[3], ARGV[4]}",
                            RScript.ReturnType.MULTI, Arrays.asList(1, 2, 3, 4));
                    assertThat(res).isEqualTo(Arrays.asList("1", "2", "3", "4"));
                } catch (Exception ex) {
                    errors.incrementAndGet();
                }
            });
        }
        e.shutdown();
        assertThat(e.awaitTermination(100, TimeUnit.SECONDS)).isTrue();
        assertThat(errors).hasValue(0);
```

**Comment by AleksanderBrzozowski** [comment]
@mrniko 

I was able to capture some logs, here are the logs from `org.redisson.client.handler.CommandEncoder`:

```text
$7
EVALSHA
$40
<<script sha>>
$1
1
$78
<<key>>
$8
10000000
$8
10000000
$8
10000000
$8
10000000 -- cost which should always be 1
```

I also captured a log from `org.redisson.command.RedisExecutor`, and it had the same value for a cost - `10_000_000` instead of `1`.

What I found more, which might cause this issue is:

```
WARN Failed to release a message: PooledUnsafeDirectByteBuf(freed)
```

And here is the stacktrace:

<details>
  <summary>Stacktrace</summary>

  ```text
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:116)
	at org.redisson.command.RedisExecutor.free(RedisExecutor.java:355)
	at org.redisson.command.RedisExecutor.free(RedisExecutor.java:350)
	at org.redisson.command.RedisExecutor.lambda$execute$1(RedisExecutor.java:153)
	at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:172)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2480)
	at org.redisson.misc.CompletableFutureWrapper.cancel(CompletableFutureWrapper.java:256)
	at org.redisson.reactive.CommandReactiveService.lambda$reactive$0(CommandReactiveService.java:52)
	at reactor.core.publisher.FluxCreate$SinkDisposable.dispose(FluxCreate.java:1118)
	at reactor.core.publisher.FluxCreate$BaseSink.disposeResource(FluxCreate.java:499)
	at reactor.core.publisher.FluxCreate$BaseSink.cancel(FluxCreate.java:486)
	at reactor.core.publisher.MonoNext$NextSubscriber.cancel(MonoNext.java:114)
	at reactor.core.publisher.Operators.terminate(Operators.java:1277)
	at reactor.core.publisher.StrictSubscriber.cancel(StrictSubscriber.java:155)
	at kotlinx.coroutines.reactor.MonoKt$awaitSingleOrNull$2$1$onSubscribe$1.invoke(Mono.kt:51)
	at kotlinx.coroutines.reactor.MonoKt$awaitSingleOrNull$2$1$onSubscribe$1.invoke(Mono.kt:51)
	at kotlinx.coroutines.InvokeOnCancel.invoke(CancellableContinuationImpl.kt:573)
	at kotlinx.coroutines.CancellableContinuationImpl.callCancelHandler(CancellableContinuationImpl.kt:215)
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:180)
	at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:190)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1475)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:596)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source)
	at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:596)
	at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
	at io.grpc.kotlin.ServerCalls$serverCallListener$1.onCancel(ServerCalls.kt:275)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.micrometer.core.instrument.binder.grpc.ObservationGrpcServerCallListener.onCancel(ObservationGrpcServerCallListener.java:57)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.micrometer.core.instrument.binder.grpc.MetricCollectingServerCallListener.onCancel(MetricCollectingServerCallListener.java:75)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:370)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:359)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:909)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
  ```

</details>

Basically, we have a gRPC API that supports Cancellation, which means that if the timeout passes, a gRPC server cancels a request - which is what happens in our case. 

When cancellation occurs, Kotlin coroutine calls `Subscription.cancel()` method.

I am pretty sure that the issue may be occurring due to the problems with freeing Netty Buffers. However, I wonder why do we got these errors, is it due to wrong usage of the Redisson library? Any thoughts?

**Comment by mrniko** [comment]
I see there is a `awaitSingle` method call, but evalSha doesn't return any object with such method is it a wrapper?

**Comment by AleksanderBrzozowski** [comment]
> Which Redisson version is it?

3.24.3

And netty versions are:
```
Gradle: io.netty:netty-buffer:4.1.100.Final
Gradle: io.netty:netty-codec:4.1.100.Final
Gradle: io.netty:netty-codec-dns:4.1.100.Final
Gradle: io.netty:netty-common:4.1.100.Final
Gradle: io.netty:netty-handler:4.1.100.Final
Gradle: io.netty:netty-resolver:4.1.100.Final
Gradle: io.netty:netty-resolver-dns:4.1.100.Final
Gradle: io.netty:netty-transport:4.1.100.Final
Gradle: io.netty:netty-transport-native-unix-common:4.1.100.Final
```

**Comment by mrniko** [comment]
Sorry, I'm afraid it's not 3.24.3 version. Method line numbers below don't match with the source code.

  at org.redisson.command.RedisExecutor.free(RedisExecutor.java:355)
  at org.redisson.command.RedisExecutor.free(RedisExecutor.java:350)
  at org.redisson.command.RedisExecutor.lambda$execute$1(RedisExecutor.java:153)
  at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:172)

**Comment by AleksanderBrzozowski** [comment]
🤦 

My fault - It's because during the test, I decided to overwrite RedisExecutor to only log when certain condition is met.

Here is a valid stacktrace:

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90)
at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:116)
at org.redisson.command.RedisExecutor.free(RedisExecutor.java:343)
at org.redisson.command.RedisExecutor.free(RedisExecutor.java:338)
at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:566)
at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:202)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:87)
at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:136)
at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:57)
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:96)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:88)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)\n
```

And one more that I found:

```
io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
at io.netty.buffer.PooledUnsafeDirectByteBuf.memoryAddress(PooledUnsafeDirectByteBuf.java:241)
at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:524)
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:193)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1104)
at org.redisson.client.handler.CommandEncoder.writeArgument(CommandEncoder.java:173)
at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:122)
at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:57)
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:96)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:88)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)\n
```

**Comment by mrniko** [comment]
IllegalReferenceCountException has been fixed

**Comment by mrniko** [comment]
Can you try the master branch?

**Comment by AleksanderBrzozowski** [comment]
> Fixed - IllegalReferenceCountException is thrown when canceling a met…

Yeah, I can try. Could you tell me how I can do that? Is there any snapshot version that I can use?

**Comment by mrniko** [comment]
You can pull the code from the master branch or use the attached archive.

[redisson-3.25.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13779599/redisson-3.25.3-SNAPSHOT.jar.zip)

**Comment by AleksanderBrzozowski** [comment]
@mrniko 

I tried to reproduce issue twice by running the same load test. Exceptions about `IllegalReferenceCountException` are gone, and I didn't encounter the problem with invalid ARGV values. Seems that your fix helped 👍 

I assume that the fix will be included in version 3.26.0 of Redisson? What is +/- estimated date for new version release?

Btw. Thanks for your help! 🙂

**Comment by mrniko** [comment]
@AleksanderBrzozowski 

Hi. Do you use Kotlin Coroutines with Redisson?

**Comment by AleksanderBrzozowski** [comment]
Yes, we use reactive API, and `kotlinx.coroutines.reactor.awaitSingle()` to switch from reactive to coroutines API

**Comment by mrniko** [comment]
What should be change in this code https://github.com/redisson/redisson/issues/5667#issuecomment-1977064711 to make it work?
