### ISSUE TITLE
Several different errors like SlaveConnectionPool no available entries, NOAUTH and slaves added\remove events cause connection issues.

### ISSUE THREAD

**Issue by yizmailovSF** [redisson/redisson#5532]
Hey,

I saw that similar issues have been addressed recently but seems we're keep facing them with redisson version 3.24.1 where they were fixed.

We use AWS elasticache with clustered mode and autoscaling.

This is our redisson config:
```
          config
              .useClusterServers()
              .addNodeAddress(
                  getAddress(redisProperties.getHost(), redisProperties.getPort()));
```

We use defaults for master\slave connection pool sizes.

I believe that all these issues are related so I list them here:
1. We constantly see that slaves are added and removed:
```
slave: rediss://xx.xx.xx.xx:6379 added for slot ranges: [[3243-11434]]
24 connections initialized for xx.xx.xx.xx/xx.xx.xx.xx:6379
slave rediss://xx.xx.xx.xx:6379 removed for slot ranges: [[3243-11434]]
slave: rediss://xx.xx.xx.xx:6379 added for slot ranges: [[3243-11434]]
24 connections initialized for xx.xx.xx.xx/xx.xx.xx.xx:6379
slave rediss://xx.xx.xx.xx:6379 removed for slot ranges: [[3243-11434]]
```
We see these messages regardless of any actual failovers or slot rebalancing in elasticache, NODE LIST keeps resulting in the same output but these messages keep showing, sometimes as frequently as every couple of minutes.

2. Whenever there is a "removed for slot ranges" message without subsequent "added for slot ranges" message we start getting NOAUTH connection errors:
```
org.redisson.client.RedisAuthRequiredException: NOAUTH Authenticati.. .2.1.9.1.1.1.1.1.1.u.concurrent.CompletableFuture@38703397[Not completed, 2 dependents], command=(READONLY), params=[], codec=null]
	... 32 common frames omitted
Wrapped by: java.util.concurrent.CompletionException: org.redisson.client.RedisAuthRequiredException: NOAUTH Authenticati.. .2.1.9.1.1.1.1.1.1.u.concurrent.CompletableFuture@38703397[Not completed, 2 dependents], command=(READONLY), params=[], codec=null]
	at j.b.u.c.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at j.b.u.c.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at j.b.u.c.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1423)
	at j.b.u.c.CompletableFuture.postComplete(CompletableFuture.java:506)
	at j.b.u.c.CompletableFuture.completeExceptionally(CompletableFuture.java:2094)
	at o.r.client.protocol.CommandData.tryFailure(CommandData.java:87)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:368)
	at o.r.c.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at i.n.h.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at i.n.h.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at i.n.h.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1382)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1245)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1294)
```
`Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:64:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:78:queue:0, freezeReason=MANAGER, client=[addr=rediss://xx.xx.xx.xx:6379], nodeType=SLAVE] attempt: 1 of 3`

We use a credential resolver in our redisson config which makes the password to be sent with each request so I doubt that this NOAUTH message is the actual issue here.

3. We see plenty of `org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries` which I guess is the result of issues 1 + 2.

It seems that this issue happens mostly during high loads, after restarts it seems to go away until the next time.

From some reading I did here in other issues, I understand that it might be some DNS related issue, if that's actually it:
1. We have around 12 pods with redisson clients running, these errors occur usually in 1-2 pods and not in the others, how come DNS works properly in some and not in others?
2. Will the usage of SequentialDnsAddressResolverFactory with non default concurrency level help here? Do I also need to set a ttl for netty dns cache? 

Thanks.

**Comment by mrniko** [comment]
Hello,

> Will the usage of SequentialDnsAddressResolverFactory with non default concurrency level help here? 

Yes, it can help. Try to pass 1 to its constructor.

**Comment by yizmailovSF** [comment]
> Hello,
> 
> > Will the usage of SequentialDnsAddressResolverFactory with non default concurrency level help here?
> 
> Yes, it can help. Try to pass 1 to its constructor.

Hey @mrniko, tried that and it didn't help, I also tried to create a custom SequentialDnsAddressResolverFactory with a low value for dns cache.

It's not a DNS issue, I verified that same hosts always resolve to the same IP address and there is always 1 to 1 mapping between a host and an IP.

**Comment by mrniko** [comment]
> We use a credential resolver in our redisson config which makes the password to be sent with each request so I doubt that this NOAUTH message is the actual issue here.

Make sure that the CredentialsResolver object returns a non-null password

**Comment by mrniko** [comment]
> It's not a DNS issue, I verified that same hosts always resolve to the same IP address and there is always 1 to 1 mapping between a host and an IP.

Other hosts many not reach dns requests limit.

**Comment by yizmailovSF** [comment]
> > We use a credential resolver in our redisson config which makes the password to be sent with each request so I doubt that this NOAUTH message is the actual issue here.
> 
> Make sure that the CredentialsResolver object returns a non-null password

CredentialsResolver always resolves to a valid passowrd.

> > It's not a DNS issue, I verified that same hosts always resolve to the same IP address and there is always 1 to 1 mapping between a host and an IP.
> 
> Other hosts many not reach dns requests limit.

hmm if it were some dns limit I would have expected to see the same issues on other pods but out of 12-15 pods we have that use redisson it usually happens on no more than 2-3 at the same time.

**Comment by yizmailovSF** [comment]
@mrniko It seems that these added\removed for slot ranges do not appear when I set just 1 replica node per shard, as soon as I scale it up these messages show up regularly even though cluster nodes response doesn't change.

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` package and share the log since the application start till the moment then you get an error after slaves scaling?

**Comment by yizmailovSF** [comment]
> Can you set `trace` logging level for `org.redisson` package and share the log since the application start till the moment then you get an error after slaves scaling?

Not sure that I'll be able to get trace logs in this environment, after I change the shards to have just 1 replica per shard I don't see these "false" slave added\removed for slot ranges messages, will wait couple of more days to see if the issue is reproduced.

thanks.

**Comment by yizmailovSF** [comment]
@mrniko Unfortunately I'm not able to get debug\trace logs for this scenario but it's pretty consistent, whenever we have more than 1 replica per shard we have these "removed for slot ranges" messages followed by these NOAUTH errors.

When it's just a single replica all works fine.

Any idea what could be the reason?
