### ISSUE TITLE
Unable to expire Rset key when use Transaction

### ISSUE THREAD

**Issue by dracenliu** [redisson/redisson#5536]
**Expected behavior**
Be able to expire Rset key successful when use Transaction 

**Actual behavior**
Redisson has exception

**Steps to reproduce or test case**

```
2023-12-27 15:03:43.674 [main] INFO  org.redisson.Version : Redisson 3.17.5
2023-12-27 15:03:45.650 [redisson-netty-2-5] INFO  o.r.c.p.MasterPubSubConnectionPool : 1 connections initialized for 127.0.0.1/127.0.0.1:6379
2023-12-27 15:03:45.717 [redisson-netty-2-19] INFO  o.r.c.pool.MasterConnectionPool : 24 connections initialized for 127.0.0.1/127.0.0.1:6379
Exception in thread "main" org.redisson.transaction.TransactionTimeoutException: Transaction was discarded due to timeout 5000 milliseconds
	at org.redisson.transaction.RedissonTransaction.checkTimeout(RedissonTransaction.java:276)
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:242)
	at org.redisson.transaction.RedissonTransaction.commit(RedissonTransaction.java:236)
	at com.hollyland.account.api.server.RedissonExample.main(RedissonExample.java:28)
```

```java
public class RedissonExample {
    public static void main(String[] args){
        // Create a Redisson client instance
        RedissonClient redisson = Redisson.create();

        // Start a transaction
        TransactionOptions options = TransactionOptions.defaults();
        RTransaction transaction = redisson.createTransaction(options);

        // Get the RSet within the transaction
        RSet<String> set = transaction.getSet("mySet");
        set.add("value1");
        // Set the expiration for the RSet
        set.expire(Instant.now().plusSeconds(50L)); // Set the expiration time in seconds

        // Commit the transaction
        transaction.commit();

        // Shutdown the Redisson client
        redisson.shutdown();
        LockSupport.park(new Object());
    }
}
```
**Redis version**
6.2.6

**Redisson version**
 3.17.5

**Redisson configuration**
use default

**Comment by SHxKM** [comment]
@dracenliu did you find a solution to this?

**Comment by SHxKM** [comment]
I can reproduce this as well, @mrniko is this expected behavior or due to limitation in Redisson?

**Comment by dracenliu** [comment]
> @dracenliu did you find a solution to this?

Not yet!

**Comment by eggnee** [comment]
@dracenliu Did you find a solution to this?

**Comment by TomasTokaMrazek** [comment]
Still present in latest version 3.45.0.

My workaround is to use hash map with key and value set to the same value. Wasted memory space, but expiration works.

**Comment by ETOZHEKIM** [comment]
Still pain

**Comment by mrniko** [comment]
Unable to reproduce the issue using the given test and Redisson 4.3.1
