### ISSUE TITLE
  In scenarios where network jitter leads to connection interruption, the code logic cannot continue after reconnection

### ISSUE THREAD

**Issue by sharmaxia** [redisson/redisson#5539]
Expected behavior：
When network recovers，redisson re-establish the connection and continue the code logic.

Actual behavior:
When network recovers and the connection has been re-establish, The detailed error report is as follows:
```
[redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0xa3c219f7, L:/10.0.16.8:44854 - R:10.0.16.6/10.0.16.6:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://10.0.16.6:6379]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
...(many 'Unable to send PING command over channel' errors)...
[redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0xf94ff1c0, L:/10.0.16.8:45156 - R:10.0.16.6/10.0.16.6:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://10.0.16.6:6379]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
[redisson-timer-4-1] ERROR org.redisson.cluster.ClusterConnectionManager - Unable to execute (CLUSTER NODES)
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=redis://10.0.16.6:6379]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Here is my test code:
```
package org.example;
import org.redisson.Redisson;
import org.redisson.api.RAtomicLong;
import org.redisson.api.RedissonClient;
import org.redisson.config.Config;
import org.redisson.connection.balancer.RoundRobinLoadBalancer;
import java.io.File;
import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        Config config = Config.fromYAML(new File("/data/home/sharmaxia/redissontest/src/main/resources/config-file.yaml"));
        RedissonClient redisson = Redisson.create(config);
        int i = 0;
        while(i++ < 1000000){
            RAtomicLong atomicLong = redisson.getAtomicLong(Integer.toString(i));
            atomicLong.getAndDecrement();
        }
        redisson.shutdown();
    }
}
```

And the config:
```
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: ********
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  nodeAddresses:
    - "redis://10.0.16.6:6379"
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: NIO
lockWatchdogTimeout: 30000
keepPubSubOrder: true
```

The issue can be reproduced by using the following command to simulate network interruption and recovering:
```
sudo iptables -A INPUT -s 10.0.16.6 -p tcp --sport 6379 -m conntrack --ctstate NEW,ESTABLISHED -j DROP

sudo iptables -D INPUT -s 10.0.16.6 -p tcp --sport 6379 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
```

**Comment by mrniko** [comment]
These errors happen only for a short period of time after network interruption.
