### ISSUE TITLE
Loop/Retry connection pool issue on redisson 3.25.0  

### ISSUE THREAD

**Issue by hieuhtr** [redisson/redisson#5548]
When upgrading Redisson from `3.23.0` to `3.25.0`/`3.25.2`, I'm facing loop/retry issue on init connection pool lead to downtime on application.

We set `slaveConnectionMinimumIdleSize = masterConnectionMinimumIdleSize = 1000` for such a long time

Version `3.23.0` --> no issue
```
log="2024-01-04 01:01:18.848  INFO  [           main] org.redisson.Version                     : Redisson 3.23.0"
log="2024-01-04 01:01:19.584  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-04 01:01:19.612  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-04 01:01:28.546  INFO  [on-netty-2-1000] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.95.188:6379"
log="2024-01-04 01:01:28.572  INFO  [sson-netty-2-15] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for redis-xxx-2/10.3.63.4:6379"
log="2024-01-04 01:01:38.468  INFO  [sson-netty-2-12] o.r.connection.pool.SlaveConnectionPool  : 1000 connections initialized for redis-xxx-2/10.3.63.4:6379"
log="2024-01-04 01:01:43.007 DEBUG  [       Thread-3] c.l.w.c.c.InjectTokenRequestTransformer  : Fetching client internal token from oauth"
log="2024-01-04 01:01:45.164  WARN  [           main] s.a.a.transfer.s3.S3TransferManager      : The provided DefaultS3AsyncClient is not an instance of S3CrtAsyncClient, and thus multipart upload/download feature is not enabled and resumable file upload is not supported. To benefit from maximum throughput, consider using S3AsyncClient.crtBuilder().build() instead."
log="2024-01-04 01:01:45.205  INFO  [           main] org.redisson.Version                     : Redisson 3.23.0"
log="2024-01-04 01:01:45.226  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-04 01:01:45.240  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-04 01:01:54.428  INFO  [on-netty-5-1000] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.95.188:6379"
log="2024-01-04 01:01:54.441  INFO  [sson-netty-5-13] o.r.c.pool.PubSubConnectionPool          : 1 connections initialized for redis-xxx-2/10.3.63.4:6379"
log="2024-01-04 01:02:04.664  INFO  [sson-netty-5-12] o.r.connection.pool.SlaveConnectionPool  : 1000 connections initialized for redis-xxx-2/10.3.63.4:6379"
...
log="2024-01-04 01:02:15.244 DEBUG  [           main] c.l.workflow.config.AsyncConfiguration   : Created Async Task Executor core size 50"
log="2024-01-04 01:02:18.882  WARN  [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath."
log="2024-01-04 01:02:18.903  WARN  [           main] s.o.SpringCloudSecurityAutoConfiguration : All Spring Cloud Security modules and starters are deprecated. They will be moved to individual projects in the next major release."
log="2024-01-04 01:02:20.706 DEBUG  [           main] c.l.w.c.logging.LoggingRequestFilter     : Filter 'loggingRequestFilter' configured for use"
log="2024-01-04 01:02:20.959  INFO  [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final"
log="2024-01-04 01:02:21.195  INFO  [           main] com.localizedirect.workflow.WorkflowApp  : Started WorkflowApp in 76.747 seconds (JVM running for 78.518)"
log="2024-01-04 01:02:21.491  INFO  [           main] c.l.w.c.sync.event.AppReadySyncListener  : Check 0 sync(s) on application started. "
log="2024-01-04 01:02:21.495  INFO  [           main] com.localizedirect.workflow.WorkflowApp  : "
log=----------------------------------------------------------
log="	Application 'workflow' is running! Access URLs:"
log="	Local: 		http://localhost:8087/"
log="	Profile(s): 	[staging]"

``` 

But it's loop almost 15-17 times when upgrading to `3.25.0` or `3.25.2` --> downtime as well

I also noticed that our redis elasticache server has received ~15-17K new connections during that starting-up
<img width="637" alt="image" src="https://github.com/redisson/redisson/assets/10110737/6aeb3eb7-dc42-4fd9-a56e-4ee9f10b1bdd">
 
```
log="2024-01-03 07:10:35.986  INFO  [           main] org.redisson.Version                     : Redisson 3.25.0"
log="2024-01-03 07:10:37.223  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:10:37.268  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:10:49.783  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:10:49.785  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:10:50.036  INFO  [sson-netty-2-44] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:11:01.917  INFO  [sson-netty-2-11] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:11:02.295  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:11:02.297  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:11:14.183  INFO  [sson-netty-2-14] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:11:14.798  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:11:14.800  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:11:26.807  INFO  [sson-netty-2-17] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:11:27.302  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:11:27.303  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:11:39.432  INFO  [sson-netty-2-20] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:11:39.805  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:11:39.807  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:11:51.536  INFO  [sson-netty-2-23] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:11:52.308  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:11:52.310  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:12:04.066  INFO  [sson-netty-2-26] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:12:04.812  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:12:04.814  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:12:16.383  INFO  [sson-netty-2-29] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:12:17.315  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:12:17.318  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:12:28.872  INFO  [sson-netty-2-32] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:12:29.820  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:12:29.821  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:12:42.323  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:12:42.325  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:12:43.252  INFO  [son-netty-2-157] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:12:54.586  INFO  [sson-netty-2-38] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:12:54.826  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:12:54.828  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:13:07.330  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:13:07.332  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:13:09.030  INFO  [son-netty-2-243] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:13:19.855  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:13:19.860  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:13:22.198  INFO  [son-netty-2-202] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:13:32.362  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:13:32.364  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:13:34.017  INFO  [son-netty-2-249] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:13:44.865  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-2:6379 is a slave"
log="2024-01-03 07:13:44.871  INFO  [           main] o.r.c.ReplicatedConnectionManager        : rediss://redis-xxx-1:6379 is the master"
log="2024-01-03 07:13:49.727  INFO  [son-netty-2-546] o.r.c.pool.MasterConnectionPool          : 1000 connections initialized for redis-xxx-1/10.3.63.4:6379"
log="2024-01-03 07:13:57.680  WARN  [isson-timer-4-1] io.netty.channel.AbstractChannel         : Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x6b082514]"
log=
log="java.util.concurrent.RejectedExecutionException: event executor terminated"
log="   at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)"
log="   at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)"
log="   at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)"
log="   at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)"
log="   at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)"
log="   at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)"
log="   at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:483)"
log="   at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87)"
log="   at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81)"
log="   at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)"
log="   at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)"
log="   at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155)"
log="   at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)"
log="   at java.base/java.lang.Thread.run(Thread.java:840)"
log=
log="2024-01-03 07:13:57.683 ERROR  [isson-timer-4-1] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?"
log=
log="java.util.concurrent.RejectedExecutionException: event executor terminated"
log="	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)"
log="	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)"
log="	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)"
log="	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)"
log="	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)"
log="	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)"
log="	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)"
log="	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:499)"
log="	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)"
log="	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)"
log="	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)"
log="	at org.redisson.client.handler.ConnectionWatchdog.tryReconnect(ConnectionWatchdog.java:116)"
log="	at org.redisson.client.handler.ConnectionWatchdog.lambda$reconnect$1(ConnectionWatchdog.java:97)"
log="	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)"
log="	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)"
log="	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)"
log="	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)"
log="	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)"
log="	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)"
log="	at java.base/java.lang.Thread.run(Thread.java:840)"
```

After that, we must set idle size back to 500 and so far there is no issue. But we cannot use this value for our production context. Is it a bug from redisson pov?

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.25.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13827779/redisson-3.25.3-SNAPSHOT.jar.zip)

**Comment by hieuhtr** [comment]
Hi @mrniko Thank you for your effort!!! I got it and sent it to my team.
