### ISSUE TITLE
NullPointerException when adding or removing shards in ElastiCache

### ISSUE THREAD

**Issue by nigelmenger** [redisson/redisson#5560]
**Expected behavior**
Redisson handles addition or removal of shards with no issues.

**Actual behavior**
```
   exception: java.lang.NullPointerException: null
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:372)
	at o.r.c.h.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:92)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:94)
	at i.n.h.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at i.n.h.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at i.n.h.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
Wrapped by: io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at i.n.h.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at i.n.h.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1471)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
	at i.n.h.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at i.n.h.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
   level: ERROR
   logger: org.redisson.client.handler.ErrorsLoggingHandler
   message: Exception occured. Channel: [id: 0xe652f647, L:/10.32.105.248:50792 - R:10.34.115.143/10.34.115.143:6379]
   thread: redisson-netty-1-26
```

**Steps to reproduce or test case**
Add or remove shards in ElastiCache while service using Redisson is connected.

**Redis version**
ElastiCache engine version 7.1.0

**Redisson version**
3.25.2

**Redisson configuration**
```
useClusterServers()
timeout = 30000
isCheckLockSyncedSlaves = false
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
