### ISSUE TITLE
RedisConnectionException: Can't find entry for 

### ISSUE THREAD

**Issue by abaowhy** [redisson/redisson#5571]
**Expected behavior**
No Error
**Actual behavior**
org.redisson.client.RedisConnectionException: Can't find entry for [addr=redis://172.31.19.88:6379]
        at org.redisson.connection.balancer.LoadBalancerManager.getConnection(LoadBalancerManager.java:308)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:594)
        at org.redisson.command.RedisExecutor.connectionReadOp(RedisExecutor.java:742)
        at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:669)
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128)
        at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:317)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
**Steps to reproduce or test case**
1、redis has a large dataset（4G）
2、remove rdb or aof of master node
3、Failover the shard of Redis cluster
**Redis version**
6.2.6（all version）
**Redisson version**
3.20.1
**Redisson configuration**
default
**clue**
172.31.19.88 is the old slave, currently it is the master， its slave is loading the dataset.
**Redisson  seems like get the address of the master in the address pool of slave。**

**Comment by mrniko** [comment]
Which Redis command was executed?

**Comment by abaowhy** [comment]
> Which Redis command was executed?
Any read command on the replica of the failover shard.

**Comment by mrniko** [comment]
can you set `trace` logging level for `org.redisson` package and share the output since application start moment?

**Comment by abaowhy** [comment]
> can you set `trace` logging level for `org.redisson` package and share the output since application start moment?

@mrniko There are a lot of trace logs, how can I give you the logs.

**Comment by abaowhy** [comment]
Error reporting time： 2024-01-18 23:07:48 ~ 2024-01-18 23:08:09.
[Uploading 2024-01-18.gz…]()

**Comment by abaowhy** [comment]
@mrniko Another ERROR: before slave loading dataset，the memory of slave is empty， redisson  will throw a error(java.lang.NullPointerException).

**Comment by mrniko** [comment]
@abaowhy 

> application will throw an error(java.lang.NullPointerException)

Can you share a full stacktrace?

**Comment by dgolombek** [comment]
We saw this same failure with 3.24.2 as well:

```
	org.redisson.client.RedisConnectionException: Can't find entry for [addr=redis://<ip>:6379]
	at org.redisson.connection.balancer.LoadBalancerManager.getConnection(LoadBalancerManager.java:274)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:660)
	at org.redisson.command.RedisExecutor.connectionReadOp(RedisExecutor.java:756)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:683)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:129)
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:329)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Can't find entry for [addr=redis://172.18.22.102:6379]
		at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
		at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
		at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:599)
		at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:571)
		at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:202)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
		at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
		at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:199)
		... 8 common frames omitted
	Caused by: org.redisson.client.RedisConnectionException: Can't find entry for [addr=redis://<ip>:6379]
```

I see that this code has been rewritten since, so we plan to upgrade and try again. For reference, this happened during an ElastiCache upgrade, and we saw #4936 happen, although at slightly lesser levels -- 4k exceptions, but they never stopped, we had to restart instances to stop the logging.
