### ISSUE TITLE
need fix dns query timeout

### ISSUE THREAD

**Issue by hellojukay** [redisson/redisson#5572]
Is there any plan to update netty to 4.1.105.Final , and fix the udp dns querry timeout  5000ms 
  in https://github.com/redisson/redisson/issues/1625

Now netty 4.1.105 support connect fallback when dns query failed
![image](https://github.com/redisson/redisson/assets/10371891/1bb1434e-89e2-4739-80bf-da4bcbdb0a6d)

https://github.com/netty/netty/pull/13778
https://github.com/netty/netty/pull/13757

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by hellojukay** [comment]
It is not enough https://github.com/netty/netty/blob/3c8df3a4d4b0ffe8116e254de29ef52a94f9adc5/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java#L204 , 
https://github.com/netty/netty/blob/3c8df3a4d4b0ffe8116e254de29ef52a94f9adc5/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java#L163

By default TCP fallback is not enbaled

**Comment by hellojukay** [comment]
Where is a PR to fix the problem https://github.com/redisson/redisson/pull/5573

**Comment by SHxKM** [comment]
We still see this error on Redisson `3.37.0` @mrniko

**Comment by SHxKM** [comment]
> @SHxKM 
> 
> can you share the stacktrace?

There's no stacktrace @mrniko , it's a warning emitted on startup. But I think it's some kind of dependency resolution issue? 

(the way I got to this message by the way is that I'm investigating high non-heap memory usage in 1 service, could this dependency resolution issue cause this when Redisson is used heavily?)

**Comment by WhatAKitty** [comment]
Still see this error also on Redisson 3.37.0 @mrniko 
```java
20:32:25.551 [redisson-netty-1-4] ERROR org.redisson.connection.DNSMonitor - Unable to resolve xxxxxx.rds.aliyuncs.com
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'xxxxxxxxxxxxxxx.rds.aliyuncs.com' [A(1)] and search domain query for configured domains failed as well: [hz.ali.com]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1150)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1097)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:455)
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:70)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:524)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:343)
	at io.netty.resolver.dns.DnsQueryContext.onQueryWriteCompletion(DnsQueryContext.java:264)
	at io.netty.resolver.dns.DnsQueryContext.access$600(DnsQueryContext.java:51)
	at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:255)
	at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:252)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
	at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:754)
	at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:339)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:319)
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:158)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:929)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:893)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1319)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:916)
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:253)
	at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:398)
	at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:321)
	at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:99)
	at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:283)
	at io.netty.resolver.dns.DnsNameResolver.resolveNow(DnsNameResolver.java:1302)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1286)
	at io.netty.resolver.dns.DnsNameResolver.access$700(DnsNameResolver.java:96)
	at io.netty.resolver.dns.DnsNameResolver$8.run(DnsNameResolver.java:1233)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: io.netty.resolver.dns.DnsNameResolverException: [5958: /[fd00:1:0:0:0:0:0:1]:53] DefaultDnsQuestion(r-8vb114feda635574.redis.zhangbei.rds.aliyuncs.com. IN A) failed to send a query '5958' via UDP (no stack trace available)
Caused by: java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
	at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:1016)
	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:973)
	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:896)
	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:297)
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:929)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:893)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1319)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:916)
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:253)
	at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:398)
	at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:321)
	at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:99)
	at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:283)
	at io.netty.resolver.dns.DnsNameResolver.resolveNow(DnsNameResolver.java:1302)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1286)
	at io.netty.resolver.dns.DnsNameResolver.access$700(DnsNameResolver.java:96)
	at io.netty.resolver.dns.DnsNameResolver$8.run(DnsNameResolver.java:1233)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by XinsuiChen** [comment]
i also got the above error on Redisson 3.40.0 @mrniko

**Comment by RealForce1024** [comment]
I'm going to upgrade to version 3.45.1 ​and monitor the system to verify if the issue persists.

**Comment by mrniko** [comment]
@RealForce1024 @XinsuiChen 

That depends on dns provider. Also make sure that Netty 4.1.105 or higher is in classpath

**Comment by kingman-zhang** [comment]
I try the  version of 3.49.0,and I start up my program,the console print this msg:
2025-06-13 14:31:51.353  WARN 77142 --- [                main] [5013b4a4-3ff0-4d79-b18c-4a1e911f7869] 2025-06-13 14:31:31.856  WARN 77142 --- [                main] [5013b4a4-3ff0-4d79-b18c-4a1e911f7869] .r.c.SequentialDnsAddressResolverFactory : DNS TCP fallback on UDP query timeout disabled. Upgrade Netty to 4.1.105 or higher.
It seen's this problem is  not fixed,please to fix it ,because it will wait a long time when it try to link the redis server.

**Comment by yuHanSlefLog** [comment]
I'm going to upgrade to version 3.45.1 ​and isuue occur same time ，finally i noticed that update the version of netty， i exclude the the netty from redisson-spring-data-27 （maybe should exclude the old version netty of maven），and i try to input the netty that version belong to 4.1.105.Final 。 final it works but not sure for to work normal with long time（ps： the netty is belong to spring-data-redis，maybe should control by  the version of netty in redisson-spring-data-27）
