### ISSUE TITLE
RLock giving ERR unknown command 'wait' on aws redis serverless

### ISSUE THREAD

**Issue by mshahmoradi87** [redisson/redisson#5586]
wait command is not supported [aws redis serverless](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/SupportedCommands.html)

**Actual behavior**
ERR unknown command 'wait'

**Redis version**
7.2 aws serverless

**Redisson version**
3.26.0

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by mshahmoradi87** [comment]
@mrniko 
Hi, 

> 
> I see this error is happening again on some services, no clue what changed, with both redis and valkey serverless,
> 
> we have setReadMode(ReadMode.MASTER), could this cause the error ? 
> we are atm on redisson 3.45.1 
> shall we disable wait config.setWaitTimeout(-1) ?

looks like there is a fix on 3.48.0 , checking, https://github.com/redisson/redisson/commit/d0676f1fced00965afa7b24b1e1952d43b16c6d8

`unexpected exception happened during .....
org.redisson.client.RedisException: ERR unknown command 'wait', with args beginning with: 1. channel:..........] command: (WAIT), params: [1, 1000], promise: java.util.concurrent.CompletableFuture@54594a34[Not completed]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:425)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:294)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:232)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:148)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:124)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1519)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1377)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1428)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)`
