### ISSUE TITLE
DelayedQueue:org.redisson.client.RedisException: ERR user_script:1: bad argument #2 to 'unpack' (data string too short)

### ISSUE THREAD

**Issue by haidiiii** [redisson/redisson#5595]
redisson 版本 3.25.0,使用延迟队列时报错，大概每5秒钟就会出现一次错误
> this.blockingQueue = redissonClient.getBlockingQueue("test");
this.delayedQueue = redissonClient.getDelayedQueue(blockingQueue);
delayedQueue.offer("test", MILLIS_PER_DAY, TimeUnit.MILLISECONDS);
this.blockingQueue.subscribeOnElements(str -> log.info(str));

错误信息如下：

> 2024-01-30 14:31:56.841 ERROR 1 --- [isson-netty-2-8] org.redisson.QueueTransferTask          : ERR user_script:1: bad argument #2 to 'unpack' (data string too short) script: a3a86b949561b56e14c274ad54368afeff259bc8, on @user_script:1.. channel: [id: 0x47576374, L:/172.18.0.4:49416 - R:10.10.5.34/10.10.5.34:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@2fdcd267[Not completed, 1 dependents], params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredValues > 0 then for i, v in ipairs(expiredValues) do local randomId, value = struct.unpack('Bc0Lc0', v);redis.call('rpush', KEYS[1], value);redis.call('lrem', KEYS[3], 1, v);end; redis.call('zrem', KEYS[2], unpack(expiredValues));end; local v = redis.call('zrange', KEYS[2], 0, 0, 'WITHSCORES'); if v[1] ~= nil then return v[2]; end return nil;, 3, test, redisson_delay_queue_timeout:{test}, redisson_delay_queue:{test}, 1706596316840, 100]
org.redisson.client.RedisException: ERR user_script:1: bad argument #2 to 'unpack' (data string too short) script: a3a86b949561b56e14c274ad54368afeff259bc8, on @user_script:1.. channel: [id: 0x47576374, L:/172.18.0.4:49416 - R:10.10.5.34/10.10.5.34:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@2fdcd267[Not completed, 1 dependents], params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredValues > 0 then for i, v in ipairs(expiredValues) do local randomId, value = struct.unpack('Bc0Lc0', v);redis.call('rpush', KEYS[1], value);redis.call('lrem', KEYS[3], 1, v);end; redis.call('zrem', KEYS[2], unpack(expiredValues));end; local v = redis.call('zrange', KEYS[2], 0, 0, 'WITHSCORES'); if v[1] ~= nil then return v[2]; end return nil;, 3, test, redisson_delay_queue_timeout:{test}, redisson_delay_queue:{test}, 1706596316840, 100]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:404)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by mrniko** [comment]
Unable to reproduce. Below is the sample code.

```java
        RBlockingQueue<Object> blockingQueue = redisson.getBlockingQueue("test");
        RDelayedQueue<Object> delayedQueue = redisson.getDelayedQueue(blockingQueue);
        delayedQueue.offer("test", 1000, TimeUnit.MILLISECONDS);
        blockingQueue.subscribeOnElements(str -> System.out.println("str " + str));

        Thread.sleep(60000);
```

**Comment by haidiiii** [comment]
@mrniko 这个不是必现的，也不知道什么时候就出现了，而且还不知道怎么才能停止掉。
你能通过异常信息看出是什么问题吗？

**Comment by mrniko** [comment]
It might be connected to old data format used by RedissonDelayedQueue in previous Redisson versions. It has been changed since 3.21.1 version.

https://github.com/redisson/redisson/blob/master/CHANGELOG.md#11-may-2023---3211-released

**Comment by ghsyyj** [comment]
How should I handle this data?，my version is 
      <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.23.1</version>
        </dependency>

**Comment by mrniko** [comment]
@ghsyyj 

Can you share your exception trace?

**Comment by ghsyyj** [comment]
OK。
2024-07-23 16:27:48,457 ERROR redisson-netty-2-3 ConvoId= CorrId= PageId= [org.redisson.QueueTransferTask:147] ERR Error running script (call to f_a3a86b949561b56e14c274ad54368afeff259bc8): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x9afbe6e4, L:/172.20.50.210:60886 - R:r-uf6acipsdbwmuqbrle.redis.rds.aliyuncs.com/172.29.5.175:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@77660e09[Not completed, 1 dependents], params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredValues > 0 then for i, v in ipairs(expiredValues) do local randomId, value = struct.unpack('Bc0Lc0', v);redis.call('rpush', KEYS[1], value);redis.call('lrem', KEYS[3], 1, v);end; redis.call('zrem', KEYS[2], unpack(expiredValues));end; local v = redis.call('zrange', KEYS[2], 0, 0, 'WITHSCORES'); if v[1] ~= nil then return v[2]; end return nil;, 3, delayQueue:readyQueue:FlexibleSpaceOrderNearUse, redisson_delay_queue_timeout:{delayQueue:readyQueue:FlexibleSpaceOrderNearUse}, redisson_delay_queue:{delayQueue:readyQueue:FlexibleSpaceOrderNearUse}, 1721723268429, 100]
org.redisson.client.RedisException: ERR Error running script (call to f_a3a86b949561b56e14c274ad54368afeff259bc8): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x9afbe6e4, L:/172.20.50.210:60886 - R:r-uf6acipsdbwmuqbrle.redis.rds.aliyuncs.com/172.29.5.175:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@77660e09[Not completed, 1 dependents], params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredValues > 0 then for i, v in ipairs(expiredValues) do local randomId, value = struct.unpack('Bc0Lc0', v);redis.call('rpush', KEYS[1], value);redis.call('lrem', KEYS[3], 1, v);end; redis.call('zrem', KEYS[2], unpack(expiredValues));end; local v = redis.call('zrange', KEYS[2], 0, 0, 'WITHSCORES'); if v[1] ~= nil then return v[2]; end return nil;, 3, delayQueue:readyQueue:FlexibleSpaceOrderNearUse, redisson_delay_queue_timeout:{delayQueue:readyQueue:FlexibleSpaceOrderNearUse}, redisson_delay_queue:{delayQueue:readyQueue:FlexibleSpaceOrderNearUse}, 1721723268429, 100]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:380) [redisson-3.23.1.jar:3.23.1]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205) [redisson-3.23.1.jar:3.23.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) [redisson-3.23.1.jar:3.23.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120) [redisson-3.23.1.jar:3.23.1]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) [netty-codec-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
2024-07-23 16:27:48,504 ERROR redisson-netty-2-13 ConvoId= CorrId= PageId= [org.redisson.QueueTransferTask:147] ERR Error running script (call to f_a3a86b949561b56e14c274ad54368afeff259bc8): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x01c9fc1e, L:/172.20.50.210:60891 - R:r-uf6acipsdbwmuqbrle.redis.rds.aliyuncs.com/172.29.5.175:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@464b2607[Not completed, 1 dependents], params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredValues > 0 then for i, v in ipairs(expiredValues) do local randomId, value = struct.unpack('Bc0Lc0', v);redis.call('rpush', KEYS[1], value);redis.call('lrem', KEYS[3], 1, v);end; redis.call('zrem', KEYS[2], unpack(expiredValues));end; local v = redis.call('zrange', KEYS[2], 0, 0, 'WITHSCORES'); if v[1] ~= nil then return v[2]; end return nil;, 3, delayQueue:readyQueue:FlexibleSpaceOrderNearEnding, redisson_delay_queue_timeout:{delayQueue:readyQueue:FlexibleSpaceOrderNearEnding}, redisson_delay_queue:{delayQueue:readyQueue:FlexibleSpaceOrderNearEnding}, 1721723268474, 100]
org.redisson.client.RedisException: ERR Error running script (call to f_a3a86b949561b56e14c274ad54368afeff259bc8): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x01c9fc1e, L:/172.20.50.210:60891 - R:r-uf6acipsdbwmuqbrle.redis.rds.aliyuncs.com/172.29.5.175:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@464b2607[Not completed, 1 dependents], params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #expiredValues > 0 then for i, v in ipairs(expiredValues) do local randomId, value = struct.unpack('Bc0Lc0', v);redis.call('rpush', KEYS[1], value);redis.call('lrem', KEYS[3], 1, v);end; redis.call('zrem', KEYS[2], unpack(expiredValues));end; local v = redis.call('zrange', KEYS[2], 0, 0, 'WITHSCORES'); if v[1] ~= nil then return v[2]; end return nil;, 3, delayQueue:readyQueue:FlexibleSpaceOrderNearEnding, redisson_delay_queue_timeout:{delayQueue:readyQueue:FlexibleSpaceOrderNearEnding}, redisson_delay_queue:{delayQueue:readyQueue:FlexibleSpaceOrderNearEnding}, 1721723268474, 100]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:380) [redisson-3.23.1.jar:3.23.1]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205) [redisson-3.23.1.jar:3.23.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) [redisson-3.23.1.jar:3.23.1]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120) [redisson-3.23.1.jar:3.23.1]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) [netty-codec-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by ghsyyj** [comment]
@mrniko

**Comment by ghsyyj** [comment]
@mrniko when i using <redisson-spring-boot-starter version:3.13.3> this version, which is the nearest version that matches this version’s data?

> It might be connected to old data format used by RedissonDelayedQueue in previous Redisson versions. It has been changed since 3.21.1 version.
> 
> https://github.com/redisson/redisson/blob/master/CHANGELOG.md#11-may-2023---3211-released

**Comment by ghsyyj** [comment]
> It might be connected to old data format used by RedissonDelayedQueue in previous Redisson versions. It has been changed since 3.21.1 version.
> 
> https://github.com/redisson/redisson/blob/master/CHANGELOG.md#11-may-2023---3211-released

when i using this version '<artifactId>redisson-spring-boot-starter-3.13.3</artifactId>', which is the nearest version that matches this version’s data?

**Comment by mrniko** [comment]
Did you try to recreate the queue? Redisson 3.21.1+ has `Breaking change - RedissonDelayedQueue internal data format changed` change.

**Comment by ghsyyj** [comment]
> Did you try to recreate the queue? Redisson 3.21.1+ has `Breaking change - RedissonDelayedQueue internal data format changed` change.

Thanks，I will implement this function using a different method.
