### ISSUE TITLE
errorMessage:ERR bad lua script for redis cluster, first parameter of redis.call/redis.pcall must be a single literal string. 

### ISSUE THREAD

**Issue by congyouzhi** [redisson/redisson#5596]
errorMessage:ERR bad lua script for redis cluster, first parameter of redis.call/redis.pcall must be a single literal string. 

redis_version:5.0.13
redisson_version:3.25.2

**Comment by mrniko** [comment]
Is there any way to reproduce it?

**Comment by myoss** [comment]
redis version: `5.0.5`

```xml
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>3.24.3</version>
            </dependency>
```

```java
RLock lock = redissonClient.getFairLock(key);
lock.tryLock(a, b);

lock.unlock(); // throw exception
```

```log
org.redisson.client.RedisException: ERR bad lua script for redis cluster, first parameter of redis.call/redis.pcall must be a single literal string. channel: [id: 0x372b9a77, L:/198.18.0.1:56875 - R:198.18.1.93:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@45f39e74[Not completed], params: [local val = redis.call('get', KEYS[5]); if val ~= false then return tonumber(val);end; while true do local firstThreadId2 = redis.call('lindex', KEYS[2], 0);if firstThreadId2 == false then break;end; local timeout = tonumber(redis.call('zscore', KEYS[3], firstThreadId2));if timeout <= tonumber(ARGV[4]) then redis.call('zrem', KEYS[3], firstThreadId2); redis.call('lpop', KEYS[2]); else break;end; end;if (redis.call('exists', KEYS[1]) == 0) then local nextThreadId = redis.call('lindex', KEYS[2], 0); if nextThreadId ~= false then redis.call(ARGV[5], KEYS[4] .. ':' .. nextThreadId, ARGV[1]); end; redis.call('set', KEYS[5], 1, 'px', ARGV[6]); return 1; end;if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); redis.call('set', KEYS[5], 0, 'px', ARGV[6]); return 0; end; redis.call('del', KEYS[1]); redis.call('set', KEYS[5], 1, 'px', ARGV[6]); local next..., 5, object2_aa111a, redisson_lock_queue:{object2_aa111a}, redisson_lock_timeout:{object2_aa111a}, redisson_lock__channel:{object2_aa111a}, redisson_unlock_latch:{object2_aa111a}:632e4dfe98cc22e54937aa92a18ee7d5, 0, 30000, 2976cdba-0055-43f5-afd8-51dd35e0f861:94, ...]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:404)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:290)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:228)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by mrniko** [comment]
@myoss 

Unable to reproduce with the latest version and the test below

```java
        GenericContainer<?> cc = createRedis("5.0.14");
        cc.start();

        Config c = createConfig(cc);
        RedissonClient redissonClient = Redisson.create(c);
        RLock lock = redissonClient.getFairLock("lock");
        lock.tryLock(10, TimeUnit.SECONDS);
        lock.unlock();
```

**Comment by mrniko** [comment]
@myoss 

Can you run your code with `trace` logging level for `org.redisson` and share output?

**Comment by myoss** [comment]
[redisson-trace.log](https://github.com/redisson/redisson/files/14524302/redisson-trace.log)
@mrniko FYI

**Comment by mrniko** [comment]
@myoss @congyouzhi 

Which Redis vendor do you use?

**Comment by yuansh** [comment]
Ali cloud Redis，redis version 6.8.14

**Comment by guoyangqiao** [comment]
Any progress?

**Comment by mrniko** [comment]
Unfortunately, it's a limitation of Ali cloud redis server. Since original Redis allows to define command as variable.

**Comment by zouxyan** [comment]
@mrniko @guoyangqiao @yuansh 

I got same question using proxy mode of alicloud Redis cluster. The proxy would check your lua scripts and this is probably where the exception happen. 

You can set the `script_check_enable` to `0` in the alicloud redis configuration page to avoid the check. This works for me. And reference is [here](https://help.aliyun.com/zh/redis/support/usage-of-lua-scripts?spm=5176.2020520104.0.0.7b8b3f1bLDgnVY).

![image](https://github.com/redisson/redisson/assets/20838799/44be993e-2dfd-4bc1-8a10-691dd9b1e048)

**Comment by Lee0110** [comment]
I'm having the same issue, has anyone solved it

**Comment by zouxyan** [comment]
@Lee0110 I got the same from aliyun redis service and solved. Maybe it can help you ⬇️

> [@mrniko](https://github.com/mrniko) [@guoyangqiao](https://github.com/guoyangqiao) [@yuansh](https://github.com/yuansh)
> 
> I got same question using proxy mode of alicloud Redis cluster. The proxy would check your lua scripts and this is probably where the exception happen.
> 
> You can set the `script_check_enable` to `0` in the alicloud redis configuration page to avoid the check. This works for me. And reference is [here](https://help.aliyun.com/zh/redis/support/usage-of-lua-scripts?spm=5176.2020520104.0.0.7b8b3f1bLDgnVY).
> 
> ![image](https://github.com/redisson/redisson/assets/20838799/44be993e-2dfd-4bc1-8a10-691dd9b1e048)

**Comment by Lee0110** [comment]
> [@Lee0110](https://github.com/Lee0110) I got the same from aliyun redis service and solved. Maybe it can help you ⬇️
> 
> > [@mrniko](https://github.com/mrniko) [@guoyangqiao](https://github.com/guoyangqiao) [@yuansh](https://github.com/yuansh)
> > I got same question using proxy mode of alicloud Redis cluster. The proxy would check your lua scripts and this is probably where the exception happen.
> > You can set the `script_check_enable` to `0` in the alicloud redis configuration page to avoid the check. This works for me. And reference is [here](https://help.aliyun.com/zh/redis/support/usage-of-lua-scripts?spm=5176.2020520104.0.0.7b8b3f1bLDgnVY).
> > ![image](https://github.com/redisson/redisson/assets/20838799/44be993e-2dfd-4bc1-8a10-691dd9b1e048)

谢谢了啊，我们运维不给改，只能不用redisson了

**Comment by 1900353090** [comment]
Switching to the 3.16.0 version of redisson-all seems to work，The config.useSingleServer() mode is used
