### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection!

### ISSUE THREAD

**Issue by tianheilea** [redisson/redisson#5602]
报错日志：
2024-01-25 00:00:11 [schedule-pool-2] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
org.springframework.dao.QueryTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.30.0.48/172.30.0.48:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=null, addr=null, redisClient=[addr=redis://172.30.0.48:6379], redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=30, freeConnectionsCounter=value:98:queue:0, freezeReason=null, client=[addr=redis://172.30.0.48:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1677992605 [redisClient=[addr=redis://172.30.0.48:6379], channel=[id: 0x668c97e9, L:/172.30.0.64:57798 - R:172.30.0.48/172.30.0.48:6379], currentCommand=null, usage=1], command: (SCAN), params: [92, MATCH, apollo_heart_beat*, COUNT, 10] after 3 retry attempts; nested exception is org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.30.0.48/172.30.0.48:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=null, addr=null, redisClient=[addr=redis://172.30.0.48:6379], redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=30, freeConnectionsCounter=value:98:queue:0, freezeReason=null, client=[addr=redis://172.30.0.48:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1677992605 [redisClient=[addr=redis://172.30.0.48:6379], channel=[id: 0x668c97e9, L:/172.30.0.64:57798 - R:172.30.0.48/172.30.0.48:6379], currentCommand=null, usage=1], command: (SCAN), params: [92, MATCH, apollo_heart_beat*, COUNT, 10] after 3 retry attempts
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48)
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:204)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:199)
	at org.redisson.spring.data.connection.RedissonConnection$1.doScan(RedissonConnection.java:281)
	at org.springframework.data.redis.core.ScanCursor.scan(ScanCursor.java:90)
	at org.springframework.data.redis.core.ScanCursor.hasNext(ScanCursor.java:184)
	at com.city.lidar.schedule.ApolloCheckStatus.lambda$getKeysWithPrefix$0(ApolloCheckStatus.java:93)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
	at com.city.lidar.schedule.ApolloCheckStatus.getKeysWithPrefix(ApolloCheckStatus.java:98)
	at com.city.lidar.schedule.ApolloCheckStatus.checkStatus(ApolloCheckStatus.java:107)
	at sun.reflect.GeneratedMethodAccessor219.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.30.0.48/172.30.0.48:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=null, addr=null, redisClient=[addr=redis://172.30.0.48:6379], redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=30, freeConnectionsCounter=value:98:queue:0, freezeReason=null, client=[addr=redis://172.30.0.48:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1677992605 [redisClient=[addr=redis://172.30.0.48:6379], channel=[id: 0x668c97e9, L:/172.30.0.64:57798 - R:172.30.0.48/172.30.0.48:6379], currentCommand=null, usage=1], command: (SCAN), params: [92, MATCH, apollo_heart_beat*, COUNT, 10] after 3 retry attempts
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:253)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted

### **version：**
redisson：3.17.6

**### redis config：**
redisson:
  keyPrefix:
  threads: 16
  nettyThreads: 32
  transportMode: "NIO"
  singleServerConfig:
    clientName: nnn
    connectionMinimumIdleSize: 32
    connectionPoolSize: 100
    idleConnectionTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    subscriptionsPerConnection: 5
    dnsMonitoringInterval: 5000

 The above error logic is executed in a scheduled task, but I am not sure if it is due to this issue.
After a scan request error occurs, all subsequent errors are the same. I searched for the answer on the issues page, but couldn't find it. But it is unclear whether this issue has been fixed,

**Comment by mrniko** [comment]
Try to increase nettyThreads setting
