### ISSUE TITLE
Error trying to execute opsForCluster().randomKey(clusterNode) on spring RedisTemplate

### ISSUE THREAD

**Issue by federico-weisse-sportsbet** [redisson/redisson#5615]
**Expected behavior**
Retrieve a random Key from the specific node

**Actual behavior**
Exception as the remove method is not supported in the list implementation
```
java.lang.UnsupportedOperationException: null
	at java.base/java.util.AbstractList.remove(AbstractList.java:167) ~[na:na]
	at org.redisson.command.CommandAsyncService.retryReadRandomAsync(CommandAsyncService.java:239) ~[redisson-3.26.0.jar:3.26.0]
	at org.redisson.command.CommandAsyncService.readRandomAsync(CommandAsyncService.java:233) ~[redisson-3.26.0.jar:3.26.0]
```
**Steps to reproduce or test case**
```
      for (RedisClusterNode clusterNode : connectionFactory.getClusterConnection().clusterGetNodes()) {
            String key = sprintRedisTemplate.opsForCluster().randomKey(clusterNode); 
        }
```
**Redis version**
6.2.6
**Redisson version**
3.26.0 (also tested in 3.23.5)
**Redisson configuration**
redis.clustered: true

**Comment by mrniko** [comment]
Fixed. Thanks for report
