### ISSUE TITLE
Closing JCache cache throws IllegalStateException

### ISSUE THREAD

**Issue by theigl** [redisson/redisson#5619]
**Expected behavior**

I can close a JCache cache backed by Redisson.

**Actual behavior**

An `IllegalStateException` is thrown:

```
java.lang.IllegalStateException
	at org.redisson.jcache.JCache.checkNotClosed(JCache.java:119)
	at org.redisson.jcache.JCache.getCacheManager(JCache.java:3110)
	at org.redisson.jcache.JCacheManager.getName(JCacheManager.java:289)
	at org.redisson.jcache.JCacheManager.queryNames(JCacheManager.java:257)
	at org.redisson.jcache.JCacheManager.unregisterStatisticsBean(JCacheManager.java:338)
	at org.redisson.jcache.JCacheManager.closeCache(JCacheManager.java:211)
	at org.redisson.jcache.JCache.close(JCache.java:3124)
	at JCacheTest.shouldGetCacheValueAfterClosingCache(JCacheTest.java:43)
```

**Steps to reproduce or test case**

```java
class JCacheTest {

	private static final String CACHE_PROVIDER = JCachingProvider.class.getName();

	private static final int TTL = 5000;
	private static final int MAX_IDLE_TIME = 0;
	private static final String ANY_CACHE = "myCache";
	private static final String ANY_KEY = "anyKey";
	private static final String ANY_VALUE = "anyValue";

	@Inject
	private RedissonClient redissonClient;

	@Test
	void shouldGetCacheValueAfterClosingCache() {
		final Configuration<Object, Object> cfg = RedissonConfiguration.fromInstance(redissonClient,
				BaseCacheConfiguration.RedisCacheConfiguration.createConfiguration(new CacheConfig(TTL, MAX_IDLE_TIME)));
		final Cache<Object, Object> cache = createCache(ANY_CACHE, cfg);
		cache.put(ANY_KEY, ANY_VALUE);

		cache.close();

		final Cache<Object, Object> newCache = createCache(ANY_CACHE, cfg);

		newCache.get(ANY_KEY);
	}

	private static Cache<Object, Object> createCache(String cacheName, Configuration<Object, Object> configuration) {
		final CachingProvider p = Caching.getCachingProvider(CACHE_PROVIDER);
		final CacheManager cm = p.getCacheManager();
		return cm.createCache(cacheName, configuration);
	}
}
```

**Redis version**
6.0

**Redisson version**
3.26.0 (Last working version: 3.24.3)

This has been broken by this commit: https://github.com/redisson/redisson/commit/00d758eb9310839415c23bf3a26fd72496387163

**Comment by mrniko** [comment]
Fixed. Thanks for report
