### ISSUE TITLE
Redisson is throwing exception after upgrading it to latest version(3.26.0)

### ISSUE THREAD

**Issue by Shalaka1197** [redisson/redisson#5622]
@mrniko I have upgraded it to latest version as per mentioned by you #5416.That errors are not coming but some other errors are coming and issue is still persist. It is not able to connect to Redis pods after restart of redis pods on server. Please check and let me know further steps on this.
I am using ClusterServers redis.

`NAjava.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: <IP>:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.connection.ConnectionsHolder.lambda$createConnection$1(ConnectionsHolder.java:184)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.connection.ConnectionsHolder.promiseFailure(ConnectionsHolder.java:218)
	at org.redisson.connection.ConnectionsHolder.lambda$createConnection$4(ConnectionsHolder.java:204)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:308)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: <ip>:6379
	at org.redisson.connection.ConnectionsHolder.lambda$createConnection$1(ConnectionsHolder.java:183)
	... 19 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: <ip>:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
	... 11 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: <ip>:6379
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
`

`
ERROR-  Can't update cluster state 
java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out after 20000 ms: <IP>:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:308)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out after 20000 ms: <IP>:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	... 8 common frames omitted
`  

`org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: Not all slots covered! Only 10923 slots are available. Set checkSlotsCoverage = false to avoid this check.`

**Comment by Shalaka1197** [comment]
yes network is fine @mrniko

**Comment by Shalaka1197** [comment]
Below info I got when I used this cmd : cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384

**Comment by mrniko** [comment]
Can you share Redisson logs with `trace` logging level for `org.redisson` package from the start moment?

**Comment by Shalaka1197** [comment]
Please see below logs which are repeated printed .
```
TRACE-reply: $775
f7b0b10aa177a948c4f04516ad01399b56e4dd5f :0@0 master,noaddr - 1707827726001 1707827726001 41 disconnected 10923-16383
1d42633c7ec76a293a396df95df83563350411a6 ip:6379@16379 slave f7b0b10aa177a948c4f04516ad01399b56e4dd5f 0 1707836844117 41 connected
ae76d60aeded2c925cfc3dbf3e5866f369dce257 ip:6379@16379 slave 555a06e2d112349a053e09b37bbce2ba580a0847 0 1707836843114 43 connected


TRACE-channel: [id: 0x79bf29d2, L:/ip:43964 - R:redis/ip:6379] message: *2
$7
CLUSTER
$5
NODES

TRACE-reply: +PONG
, channel: [id: 0x85b3e473, L:/ip:59892 - R:ip/ip:6379], command: CommandData [promise=java.util.concurrent.CompletableFuture@4709fb20[Not completed, 1 dependents], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]
```


After setting checkSlotsCoverage = false this field the below exceptions are coming. Please let me know workaround for this.
`
Caused by: org.redisson.client.RedisNodeNotFoundException: Node for slot: 11235 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.
	at org.redisson.connection.ServiceManager.createNodeNotFoundException(ServiceManager.java:333)
	at org.redisson.command.RedisExecutor.connectionReadOp(RedisExecutor.java:781)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:708)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:127)
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:323)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.util.concurrent.CompletionException: org.redisson.client.RedisNodeNotFoundException: Node for slot: 11235 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.
		at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
		at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:614)
		at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:586)
		at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:196)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
		at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:193)
		... 6 common frames omitted
	Caused by: org.redisson.client.RedisNodeNotFoundException: Node for slot: 11235 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.
`

**Comment by mrniko** [comment]
Unfortunately, CLUSTER NODES reply doesn't contain any valid Redis master node.

**Comment by mrniko** [comment]
Can you share the log from the start moment?

**Comment by Shalaka1197** [comment]
@mrniko Please see this file which contains the logs.
[redis-logs.csv](https://github.com/redisson/redisson/files/14400951/redis-logs.csv)

**Comment by mrniko** [comment]
`master,noaddr - 1707827726001 1707827726001 41 disconnected 10923-16383` means that master containing 11235 isn't connected. You need to check your cluster state.
