### ISSUE TITLE
ConcurrentModificationException in LRUCacheMap

### ISSUE THREAD

**Issue by adrian-skybaker** [redisson/redisson#5626]
When running parallel threads with many different codecs, I'm able to generate a ConcurrentModificationException for the org.redisson.command.RedisExecutor#CODECS LRUCacheMap cache:

```
java.util.ConcurrentModificationException
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.remove(LinkedHashMap.java:777)
        at org.redisson.cache.LRUCacheMap.onMapFull(LRUCacheMap.java:92)
        at org.redisson.cache.AbstractCacheMap.put(AbstractCacheMap.java:181)
        at org.redisson.cache.AbstractCacheMap.put(AbstractCacheMap.java:174)
        at org.redisson.command.RedisExecutor.getCodec(RedisExecutor.java:747)
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:124)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:605)
        at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:357)
        at org.redisson.RedissonJsonBucket.getAsync(RedissonJsonBucket.java:100)
        at org.redisson.RedissonJsonBucket.get(RedissonJsonBucket.java:92)
```

This exception is actually lost (I had to find it via a debugger), because `handleError` then fails with:

```
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.join()" because "connectionFuture" is null
        at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:614)
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:200)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:605)
        at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:357)
        at org.redisson.RedissonJsonBucket.getAsync(RedissonJsonBucket.java:100)
        at org.redisson.RedissonJsonBucket.get(RedissonJsonBucket.java:92)
```

Although not LRU, I would recommend https://github.com/ben-manes/caffeine rather than debugging and maintaining an original LRU implementation in redisson.

**Comment by mrniko** [comment]
Fixed.

Caffeine is too heavy for such a small task.

**Comment by adrian-skybaker** [comment]
>Fixed.

Thank you!

>Caffeine is too heavy for such a small task.

Do you mean in terms of dependencies? Library size? I believe if you compared a benchmark against this implementation you will find it lower overhead.

**Comment by mrniko** [comment]
I mean library size.
