### ISSUE TITLE
Failed to parse yaml configuration throws NoSuchMethodError com.fasterxml.jackson.annotation.JsonTypeInfo.requireTypeIdForSubtypes()

### ISSUE THREAD

**Issue by maliksajidhussain** [redisson/redisson#5630]
Trying to parse the yaml configuration as JSON configuration obsoleted. Getting exception while parsing yaml configuration as string
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.OptBoolean com.fasterxml.jackson.annotation.JsonTypeInfo.requireTypeIdForSubtypes()

**Should parse the yaml configuration**

**Throw NoSuchMethodError com.fasterxml.jackson.annotation.OptBoolean  com.fasterxml.jackson.annotation.JsonTypeInfo.requireTypeIdForSubtypes()**

**Pass the configuration as string and above exception throw**

**7.2.3**

**3.26.1**

**singleServerConfig:
  idleConnectionTimeout: 500
  connectTimeout: 500
  timeout: 1000
  retryAttempts: 2
  retryInterval: 500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: redis://196.166.1.2:6379
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
transportMode: NIO**

`java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.OptBoolean com.fasterxml.jackson.annotation.JsonTypeInfo.requireTypeIdForSubtypes()'
	at com.fasterxml.jackson.annotation.JsonTypeInfo$Value.from(JsonTypeInfo.java:427) ~[jackson-annotations-2.16.1.jar:1.0]
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findPolymorphicTypeInfo(JacksonAnnotationIntrospector.java:670) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector._findTypeResolver(JacksonAnnotationIntrospector.java:1579) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findTypeResolver(JacksonAnnotationIntrospector.java:677) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findTypeDeserializer(BasicDeserializerFactory.java:1807) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findPropertyTypeDeserializer(BasicDeserializerFactory.java:2042) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.resolveMemberAndTypeAnnotations(BasicDeserializerFactory.java:2409) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:907) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:584) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:277) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:436) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:371) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:285) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:265) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:163) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:5030) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4900) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814) ~[jackson-databind-2.16.1.jar:2.16.1]
	at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:161) ~[redisson-3.26.1.jar:3.26.1]
	at org.redisson.config.Config.fromYAML(Config.java:657) ~[redisson-3.26.1.jar:3.26.1]`

**Comment by maliksajidhussain** [comment]
This issue was due to jackson-annotation classes loaded from a shaded jar which was an older version of jackson annotation. After updating the version in shaded jar fix the issue. But the strange thing is why redission loading classes from a shaded jar rather from the jar available on classpath.
