### ISSUE TITLE
WriteRedisConnectionException: Unable to write command into connection!

### ISSUE THREAD

**Issue by timigv** [redisson/redisson#5635]
Hi, my app has a healthcheck (we try to get a nonexistent bucket) to redis cluster every 6 seconds. We don't have other operations with redis yet, only the healtcheck. The cluster is AWS Elasticache Serverless. It works well for ~ 15 hours after the app starting, but then this error appeared. It was early morning, there was no load on the app
```
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Check CPU usage of the JVM. Try to increase nettyThreads setting. Node source: NodeSource [slot=14391, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@141655746 [redisClient=[addr=rediss://172.***:6380], channel=[id: 0x43aa527f, L:/172.***:47760 ! R:172***/172.***:6380], currentCommand=null, usage=1], command: (GET), params: [pingHealthcheck] after 3 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:351)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:189)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:877)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```
The reddison version is 3.26.1. The config is
```
Config config = new Config();
config.setCodec(new JsonJacksonCodec(configureObjectMapper()))
  .useClusterServers()
  .addNodeAddress(redisUrl)
  .setCredentialsResolver(sessionIamAuthTokenResolver);
return Redisson.create(config);
```
JVM metrics (error appeared at 6:07)
<img width="1718" alt="Screenshot 2024-02-15 at 9 40 31 AM" src="https://github.com/redisson/redisson/assets/157492446/0564ae79-0108-4208-9353-b3315fefe1df">

**Comment by timigv** [comment]
Close because it was problem with user permissions

**Comment by mrniko** [comment]
@timigv 

Redis user permissions?
