### ISSUE TITLE
Can Redisson be used for Tomcat session cache? Getting java.lang.ClassNotFoundException on broadcasting session updates

### ISSUE THREAD

**Issue by vk185160** [redisson/redisson#5639]
I am trying to integrate redisson with tomcat(8.5.96) I am using Kryo5Codec as it is recommended and it can serialise the non serializable classes as well. This is the configuration I am using 

redisson.conf

```
{
"singleServerConfig":{
  "password": "localpassword",
  "address": "redis://localhost:6379"
},
"threads":0,
"nettyThreads":0,
"transportMode":"NIO"
}
```

`<Manager className="com.liferay.redis.redisson.integration.tomcat.APRedissonSessionManager" configPath="${catalina.base}/redisson.conf"  readMode="MEMORY" updateMode="AFTER_REQUEST" broadcastSessionEvents="true" broadcastSessionUpdates="true"/>`

Codec settings
```
public class APRedissonSessionManager extends RedissonSessionManager {

    protected RedissonClient buildClient() throws LifecycleException {
        RedissonClient redissonClient = super.buildClient();

        Config config = redissonClient.getConfig();

        config.setCodec(new Kryo5Codec(Thread.currentThread().getContextClassLoader()));
        return redissonClient;
    }
```

I do have redisson-all and redisson-tomcat-8 of version 3.20.0 in my tomcat/lib folder
(because of slf4j version conflict I am not able to use latest versions of these two lib)

I am not seeing any issues with single tomcat instance but with multiple tomcat instances as soon as we set an attribute of java object type in one instance we get this error in another instance

```
Feb 13, 2024 10:55:18 PM org.redisson.tomcat.RedissonSessionManager$2 onMessage
SEVERE: Unable to handle topic message
com.esotericsoftware.kryo.KryoException: Unable to find class: com.packageA.classA
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:182)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:151)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:222)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:44)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:877)
        at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144)
        at org.redisson.tomcat.AttributeMessage.toObject(AttributeMessage.java:75)
        at org.redisson.tomcat.AttributesPutAllMessage.getAttrs(AttributesPutAllMessage.java:56)
        at org.redisson.tomcat.RedissonSessionManager$2.onMessage(RedissonSessionManager.java:300)
        at org.redisson.tomcat.RedissonSessionManager$2.onMessage(RedissonSessionManager.java:273)
        at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
        at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:68)
        at org.redisson.client.handler.CommandPubSubDecoder$1.run(CommandPubSubDecoder.java:164)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.packageA.classA
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1338)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1150)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:176)
        ... 17 more

```

We do have multiple webapps deployed in our tomcat webapps and we are sharing the user session created by ROOT of the tomcat with other webapps by this configuration 

`<Context crossContext="true"   sessionCookieName="SESSIONID"  sessionCookiePathUsesTrailingSlash="false" path="/ROOT" cookies="true" reloadable="true" >`

**Comment by mrniko** [comment]
Try to define https://github.com/redisson/redisson/wiki/2.-Configuration#usethreadclassloader = false

**Comment by vk185160** [comment]
that classA is present in WEB-INF directory of that specific webapp in all tomcat instances. also tried with "useThreadClassLoader":"false" still the same issue

**Comment by mrniko** [comment]
`that classA is present in WEB-INF directory of that specific webapp`

try to place it into every webapp

**Comment by vk185160** [comment]
why should it present in every webapp? because that classA is being used in webApp-A which contains that class. wouldn't that be enough? in our use case we don't want that class to be present in every webapp. that way we need to all classes of each webapp which we are storing in session to the remaining webapps that's proper solution.

**Comment by vk185160** [comment]
this is just one instance and it is happening for all those classes of the webapps whichever we are storing in session with setAttribute invocation(). but one thing what I observed is with readMode as REDIS we don't see any issues but there are some attributes which are getting updated and not set to redis via setAttribute invocation but with readMode as MEMORY that will be taken care. so we want to go use readMode as MEMORY.

**Comment by vk185160** [comment]
One more thing we have overriden tomcat's context.xml with conf/Catalina/localhost/ROOT.xml file which does look this 
```
<Context crossContext="true"   sessionCookieName="SESSIONID"  sessionCookiePathUsesTrailingSlash="false" path="/ROOT" cookies="true" reloadable="true" >

<Resources cachingAllowed="false" />

<Manager className="com.liferay.redis.redisson.integration.tomcat.APRedissonSessionManager" configPath="${catalina.base}/redisson.conf"  readMode="MEMORY" updateMode="AFTER_REQUEST" broadcastSessionEvents="true" broadcastSessionUpdates="true"/>


</Context>
```

**Comment by vk185160** [comment]
@mrniko any idea?

**Comment by mrniko** [comment]
Your change new Kryo5Codec(Thread.currentThread().getContextClassLoader()) isn't used in Redisson.

**Comment by mrniko** [comment]
You need to define new Kryo5Codec(Thread.currentThread().getContextClassLoader()) before Redisson start.
