### ISSUE TITLE
ClassCastException when using FlushListener along with LocalCachedMap

### ISSUE THREAD

**Issue by numsu** [redisson/redisson#5650]
**Expected behavior**
Redisson should not throw an error

**Actual behavior**
Redis is throwing an exception when using the new FlushListener and a LocalCachedMap gets an event.
```
java.lang.ClassCastException: class org.redisson.cache.LocalCachedMapInvalidate cannot be cast to class java.lang.String (org.redisson.cache.LocalCachedMapInvalidate is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @4b45a2f5; java.lang.String is in module java.base of loader 'bootstrap')
	at org.redisson.pubsub.PublishSubscribeService$2.onMessage(PublishSubscribeService.java:245)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:68)
	at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$2(CommandPubSubDecoder.java:221)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Steps to reproduce or test case**
1. Create a LocalCachedMap instance with default configuration
2. Add a FlushListener
3. Make alterations to the LocalCachedMap

**Redis version**
7.0.10

**Redisson version**
3.27.0

**Redisson configuration**
```
---
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: "NIO"
protocol: RESP3
```

**Comment by mrniko** [comment]
Thanks for report. Fixed
