### ISSUE TITLE
NPE on ClusterConnectionManager

### ISSUE THREAD

**Issue by dannywils** [redisson/redisson#5663]
**Expected behavior**

No NullPointerException

**Actual behavior**

NullPointerException

```
   exception: java.lang.NullPointerException: null
	at j.b.u.c.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at j.b.u.c.CompletableFuture.postComplete(CompletableFuture.java:506)
	at j.b.u.c.CompletableFuture.complete(CompletableFuture.java:2073)
	at o.r.connection.ConnectionsHolder.lambda$createConnection$1(ConnectionsHolder.java:190)
	at j.b.u.c.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at j.b.u.c.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at j.b.u.c.CompletableFuture.postComplete(CompletableFuture.java:506)
	at j.b.u.c.CompletableFuture.complete(CompletableFuture.java:2073)
	at o.r.connection.ConnectionsHolder.connectedSuccessful(ConnectionsHolder.java:222)
	at o.r.connection.ConnectionsHolder.lambda$createConnection$4(ConnectionsHolder.java:211)
Wrapped by: java.util.concurrent.CompletionException: java.lang.NullPointerException
	at j.b.u.c.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at j.b.u.c.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at j.b.u.c.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
	at j.b.u.c.CompletableFuture.postComplete(CompletableFuture.java:506)
	at j.b.u.c.CompletableFuture.complete(CompletableFuture.java:2073)
	at o.r.connection.ConnectionsHolder.lambda$createConnection$1(ConnectionsHolder.java:190)
	at j.b.u.c.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at j.b.u.c.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at j.b.u.c.CompletableFuture.postComplete(CompletableFuture.java:506)
	at j.b.u.c.CompletableFuture.complete(CompletableFuture.java:2073)
   level: ERROR
   logger: org.redisson.cluster.ClusterConnectionManager
```

**Steps to reproduce or test case**

Not sure. Doesn't happen often. 
- 1x 2/29/24
- 1x 2/25/24
- 3x 2/23/24

**Redis version**

7.1

**Redisson version**

3.27.0

**Redisson configuration**

```
Clustered AWS ElastiCache
LZ4Codec
retryAttempts = 10
retryInterval = 2s
pingConnectionInterval = 60s
isCheckLockSyncedSlaves = false
```

**Comment by mrniko** [comment]
When does it happen?

**Comment by mrniko** [comment]
Fixed. Thanks for report
