### ISSUE TITLE
unable to decode data

### ISSUE THREAD

**Issue by huskyui** [redisson/redisson#5671]
## error msg
```
Unable to decode data. channel: [id: 0xd1e0fc7b, L:/127.0.0.1:42784 - R:redisproxy.xx/xxx.xxx.xxx.xxx:7605] message: *3
$11
unsubscribe
$73
redisson_lock__channel:{lock:jf:send:batch3:ohmdTt0k-0ZOHdBXeezFazpRKqto}
:0
*3
$7
message
$73
redisson_lock__channel:{lock:jf:send:batch3:ohmdTt0k-0ZOHdBXeezFazpRKqto}
$1
0
\njava.lang.NullPointerException: null
	at org.redisson.client.handler.CommandPubSubDecoder.selectDecoder(CommandPubSubDecoder.java:242)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:348)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:410)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:375)
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:78)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
## version

redisson  3.8.2

## create redisson code
```
public RedissonClient createRedissonClient() {
        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.useClusterServers();
        CacheConfig cacheConfig = getCacheConfig();
        List<RedisConfig> instances = cacheConfig.getInstances();
        instances.forEach(t -> clusterServersConfig.addNodeAddress(NODE_ADDRESS_PREFIX + t.getIp()));
        String password = instances.get(0).getPassword();
        if (StringUtils.isNotEmpty(password)) {
            clusterServersConfig.setPassword(password);
        }
        clusterServersConfig.setPassword(instances.get(0).getPassword());
        clusterServersConfig.setSlaveConnectionMinimumIdleSize(1);
        clusterServersConfig.setMasterConnectionMinimumIdleSize(1);

        return Redisson.create(config);
    }
```

## desc

Previously, we were using a Redis Cluster in our system. However, yesterday, we switched to utilizing a Redis proxy. Since then, we have intermittently encountered a specific bug.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5308
