### ISSUE TITLE
Listener removal UnsupportedOperationException

### ISSUE THREAD

**Issue by Aurelien30000** [redisson/redisson#5673]
**Expected behavior**
No error.

**Actual behavior**
```java
java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.add(AbstractList.java:155) ~[?:?]
        at java.util.AbstractList.add(AbstractList.java:113) ~[?:?]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:338) ~[?:?]
        at fr.aurelien30000.domidependencies.lib.redisson.RedissonObject.removeListenerAsync(RedissonObject.java:517) ~[DomiDependencies-bukkit-1.13.4-all.jar:?]
        at fr.aurelien30000.domidependencies.lib.redisson.RedissonBucket.removeListenerAsync(RedissonBucket.java:394) ~[DomiDependencies-bukkit-1.13.4-all.jar:?]
 ...]
```

**Steps to reproduce or test case**
- Add a simple listener to a bucket. ``RedissonBucket#addListenerAsync``
- Store the listener id.
- Remove the listener from the bucket and see the error. ``RedissonBucket#removeListenerAsync``

**Redis version**
``7.2.3``

**Redisson version**
``3.27.1`` _(running on ``openjdk version "21.0.2" 2024-01-16 LTS``)_

**Redisson configuration**
Nothing special

Thanks!

**Comment by mrniko** [comment]
Fixed. Thanks for report
