### ISSUE TITLE
ConcurrentModificationException thrown on RedissonSession save method

### ISSUE THREAD

**Issue by KatieRegnierTR** [redisson/redisson#5677]
**Expected behavior**
Using Redisson based Tomcat Session Manager; no exceptions are thrown and sessions aren't lost prematurely.

**Actual behavior**
Sessions are expiring earlier than expected and we are seeing the following error:

```
SEVERE: Exception Processing [...]
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:154)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:44)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
	at org.redisson.codec.Kryo5Codec$5.encode(Kryo5Codec.java:171)
	at org.redisson.tomcat.AttributeMessage.toByteArray(AttributeMessage.java:60)
	at org.redisson.tomcat.AttributesPutAllMessage.<init>(AttributesPutAllMessage.java:43)
	at org.redisson.tomcat.RedissonSession.createPutAllMessage(RedissonSession.java:238)
	at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:432)
	at org.redisson.tomcat.RedissonSessionManager.store(RedissonSessionManager.java:420)
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:74)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Steps to reproduce or test case**
This is seen when we run regression tests that repeatedly log in/out, creating and destroying multiple sessions originating from the same user. Only happens intermittently and not on the same tests every time. 

**Redis version**
7.1
**Redisson version**
3.27.0
**Redisson configuration**
Happens in both clustered and single node instances, however marginally less in a clustered configuration (2 nodes, 2 shards per node).

Redisson Tomcat Session Manager configurations:
- ReadMode: MEMORY
- UpdateMode: AFTER_REQUEST
- BroadcastSessionEvents: true
- We do have a custom keyPrefix
- Everything else is default values

Tomcat version: 9.0.86
Java version: 11

**Comment by mrniko** [comment]
It's a Kryo lib issue.

@theigl 

Hi. Can you look at it?

**Comment by theigl** [comment]
This is most likely not a Kryo issue. It looks like the Kryo encoder is given an `ArrayList` that is modified concurrently by another thread. Kryo always assumes it has exclusive access to the data during serialization. The user of Kryo has to make sure that the data can be safely serialized.

**Comment by mrniko** [comment]
@theigl 

Thank you for review. Let me check that.

**Comment by mrniko** [comment]
@theigl 

map passed into createPutAllMessage isn't changed since it's life scope is createPutAllMessage method. You can check org.redisson.tomcat.RedissonSession.save() method.

**Comment by theigl** [comment]
Kryo does not write/remove data from lists so it can't be responsible for the exception. An other thread must access the list at the same time. If you look closely the stacktrace, the error happens in `ArrayList`, not in a map. So there must be a list somewhere in the map that gets modified.

**Comment by mrniko** [comment]
You are right. User stores list as Tomcat Session attribute.

**Comment by mrniko** [comment]
Fixed. Thanks for report
