### ISSUE TITLE
why Redisson.java Declare the class as final?

### ISSUE THREAD

**Issue by zyong2004** [redisson/redisson#5689]
redisson 3.17.6  , i write a aspect to monitor api operation,it is work well
example:
` @Pointcut("execution(* org.redisson.api.*.*(..))")`

upgrade to 3.27.2 , An error was reported when the application was started：
`Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class org.redisson.Redisson: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class org.redisson.Redisson
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:208) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:471) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:350) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]`

**Comment by mrniko** [comment]
To avoid bugs with improperly extended classes.

**Comment by zyong2004** [comment]
Is there an interface that can be used as a monitoring item?

**Comment by mrniko** [comment]
Redisson object implements RedissonClient interface. You can use it.

**Comment by zyong2004** [comment]
It doesn't work with aop because Redison.java declares the class final

**Comment by mrniko** [comment]
try to use Delegation pattern
