### ISSUE TITLE
 Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME)

### ISSUE THREAD

**Issue by JanCizmar** [redisson/redisson#5696]
Hello,

first of all thanks for this great project! 

On production, we are getting a lot of these errors, while running the Redis sentinel. The Redis nodes don't show any signs of errors or downtime. Is there any way I can maybe instruct Redisson to retry these commands or can someone point me to the right direction to debug this?

I suspect these errors for being cause of our cache is not being evicted correctly which is super painful hard to debug issue, since the Stack trace doesn't say much.

```
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME), params: [mymaster], Redis client: [addr=redis://10.224.1.0:26379]
```

```
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME), params: [mymaster], Redis client: [addr=redis://10.224.1.0:26379]
    at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:833)
java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME), params: [mymaster], Redis client: [addr=redis://10.224.1.0:26379]
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
    at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:254)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by mrniko** [comment]
Please refer to this section https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by JanCizmar** [comment]
Thanks. I am still not sure why exactly is `GET-MASTER-ADDR-BY-NAME` executed? Is this happening periodically to get new master or does this signalize that there is a new master? Also, when I increase the `retryAttempts ` will it try the operation with other client or it will query the same client again? 

The docs say there are 3 retryAttempts by default. We have 3 replicas running, so it seems unlikely that any replica doesn't respond in the default 3000ms in 3 attempts.

**Comment by ivan-sirosh** [comment]
The same happens for us. Redis is deployed by bitnami helm chart. 3 instances.

example of sentinel.conf
```
sentinel known-replica de-sqcx-test-master redis-sentinel-node-0.redis-sentinel-headless.de-sqcx-test.svc.cluster.local 6379
sentinel known-sentinel de-sqcx-test-master redis-sentinel-node-2.redis-sentinel-headless.de-sqcx-test.svc.cluster.local 26379 5f4ff5b1f3024ce375ab027ac24adb717305f02c
sentinel known-sentinel de-sqcx-test-master redis-sentinel-node-1.redis-sentinel-headless.de-sqcx-test.svc.cluster.local 26379 5add24b6f14969527b26e2b3d62ebfa73e2de554
sentinel known-replica de-sqcx-test-master redis-sentinel-node-1.redis-sentinel-headless.de-sqcx-test.svc.cluster.local 6379
sentinel announce-hostnames yes
sentinel resolve-hostnames yes
sentinel announce-port 26379
sentinel announce-ip "redis-sentinel-node-0.redis-sentinel-headless.de-sqcx-test.svc.cluster.local"
```

and exception:
```json
{"@timestamp":"2024-07-31T14:36:37.870Z","log.level":"ERROR","message":"Can't execute SENTINEL commands on 192.168.92.103/192.168.92.103:26379","ecs.version": "1.2.0","service.name":"sqcx-s
ervice-snapshot-maker-trigger","event.dataset":"sqcx-service-snapshot-maker-trigger","process.thread.name":"redisson-timer-5-1","log.logger":"org.redisson.connection.SentinelConnectionManag
er","error.type":"java.util.concurrent.CompletionException","error.message":"org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-N
AME), params: [de-sqcx-test-master], Redis client: [addr=redis://192.168.92.103:26379]","error.stack_trace":"java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutExcept
ion: Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME), params: [de-sqcx-test-master], Redis client: [addr=redis://192.168.92.103:26379]\n\tat java.base/java.util.co
ncurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)\n\tat java.base/j
ava.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat j
ava.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)\n\tat org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:254)\n\tat i
o.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)\n\tat io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)\n\tat io.netty.util.Hashe
dWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)\n\tat io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)\n\tat io.netty.util.HashedW
heelTimer$Worker.run(HashedWheelTimer.java:494)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:
1583)\nCaused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME), params: [de-sqcx-test-master], Redis client: [addr=re
dis://192.168.92.103:26379]\n\tat org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)\n\t... 7 more\n"}
```

@JanCizmar was you able to solve the problem?

**Comment by mvkirillov** [comment]
We have exactly the same problem. 
Redis is deployed by bitnami helm chart. 3 instances.
Redisson 3.25.0

**Comment by JanCizmar** [comment]
@ivan-sirosh Hi Ivan, sorry for the delay. 

No, it still happens time to time and it's annoying since it may cause inconsistencies between the database and Redis, but we currently don't have the time budget to dig into it. I hope it will be fixed in future releases. 🚀

**Comment by mrniko** [comment]
Fixed. Thanks for report.
