### ISSUE TITLE
NullPointerException Possibly Triggered in RedissonCountDownLatch.await Method

### ISSUE THREAD

**Issue by xj-66** [redisson/redisson#5704]
When using the RedissonCountDownLatch class's await method, a NullPointerException exception may occur. According to the stack trace, the exception occurs at line 139 of the RedissonCountDownLatch class.

**Steps to reproduce or test case**
```java
private static RedissonClient createRedisson() {
        String host = ConfigUtils.getServiceProperty("redis_url");
        String port = ConfigUtils.getServiceProperty("redis_port");
        String password = ConfigUtils.getServiceProperty("redis_password");

        Config config = new Config();
        config.setTransportMode(TransportMode.NIO);
        SingleServerConfig singleServerConfig = config.useSingleServer();
        singleServerConfig.setAddress("redis://" + host + ":" + port);
        singleServerConfig.setPassword(password);


        singleServerConfig.setPingConnectionInterval(30000);
        singleServerConfig.setSubscriptionConnectionPoolSize(1); 
        singleServerConfig.setConnectionPoolSize(2); 
        singleServerConfig.setConnectionMinimumIdleSize(1); 
        singleServerConfig.setSubscriptionsPerConnection(1);

        singleServerConfig.setRetryAttempts(5);
        singleServerConfig.setRetryInterval(1000);

        return Redisson.create(config);
    }
```
```java
RedissonClient client = createRedisson();

// Executing this section in a multi-threaded environment throws an exception
RCountDownLatch c1 = client.getCountDownLatch(key1);
c1.trySetCount(1);
c1.await(timeout, TimeUnit.SECONDS);

```
```java
java.lang.NullPointerException
	at org.redisson.RedissonCountDownLatch.await(RedissonCountDownLatch.java:139)
	at xxx.CommandUtil.countDownAwait(CommandUtil.java:183)
	at xxx.CommandUtil.waitResponse(CommandUtil.java:108)
	at xxx.doPost(LocationPhone.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at xxx.service(BaseServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at xxx.doFilter(SessionActionFilter.java:148)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:209)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:244)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Redis version**
Redis 4.0

**Redisson version**
3.25.2

**Comment by wynn5a** [comment]
Hello, `xxx.CommandUtil.countDownAwait` maybe the key to reproduce, can you share more code about this method?

**Comment by mrniko** [comment]
Fixed. Thanks for report
