### ISSUE TITLE
Failed to submit a listener notification task. Event loop shut down?

### ISSUE THREAD

**Issue by Charles7c** [redisson/redisson#5710]
**Expected behavior**

When restarting the project in IntelliJ IDEA, there are no errors and it can be restarted normally.

**Actual behavior**

```
2024-03-24 10:39:34 ERROR [SpringApplicationShutdownHook] i.n.u.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:862)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at org.redisson.client.RedisPubSubConnection.unsubscribe(RedisPubSubConnection.java:143)
	at org.redisson.pubsub.PubSubConnectionEntry.unsubscribe(PubSubConnectionEntry.java:251)
	at org.redisson.pubsub.PublishSubscribeService.unsubscribeLocked(PublishSubscribeService.java:684)
	at org.redisson.pubsub.PublishSubscribeService.lambda$removeListenerAsync$54(PublishSubscribeService.java:953)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at org.redisson.pubsub.PublishSubscribeService.removeListenerAsync(PublishSubscribeService.java:940)
	at org.redisson.pubsub.PublishSubscribeService.removeListenerAsync(PublishSubscribeService.java:921)
	at org.redisson.RedissonTopic.removeListenerAsync(RedissonTopic.java:171)
	at org.redisson.RedissonTopic.removeListener(RedissonTopic.java:177)
	at com.alicp.jetcache.redisson.RedissonBroadcastManager.close(RedissonBroadcastManager.java:60)
	at com.alicp.jetcache.SimpleCacheManager.lambda$close$0(SimpleCacheManager.java:44)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at com.alicp.jetcache.SimpleCacheManager.close(SimpleCacheManager.java:42)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:221)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1182)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1117)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1083)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:173)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1034)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Steps to reproduce or test case**

https://github.com/charles7c/continew-admin
1.Start the project
2.Restart the project

**Redis version**

7.2.3

**Redisson version**

3.27.2

**Redisson configuration**

I don't have any extra configuration, I even directly reuse the existing Redis configuration.

Here is a snippet of my configuration:

```java
    private void buildSingleModeConfig(Config config, String protocolPrefix) {
        SingleServerConfig singleServerConfig = config.useSingleServer();
        SingleServerConfig customSingleServerConfig = properties.getSingleServerConfig();
        if (null != customSingleServerConfig) {
            BeanUtil.copyProperties(properties.getSingleServerConfig(), singleServerConfig);
        }
        // 下方配置如果为空，则使用 Redis 的配置
        singleServerConfig.setDatabase(redisProperties.getDatabase());
        if (CharSequenceUtil.isBlank(singleServerConfig.getPassword())) {
            singleServerConfig.setPassword(redisProperties.getPassword());
        }
        if (CharSequenceUtil.isBlank(singleServerConfig.getAddress())) {
            singleServerConfig.setAddress(protocolPrefix + redisProperties
                .getHost() + StringConstants.COLON + redisProperties.getPort());
        }
    }
```

**Comment by mrniko** [comment]
The issue is that RedissonBroadcastManager calls topic listener removal after Redisson was shutdown.

**Comment by mrniko** [comment]
Shutdown check added

**Comment by DolphaGo** [comment]
@mrniko 

I upgraded to version 3.30 and still have the same issue?

**Comment by mrniko** [comment]
resolved in https://github.com/redisson/redisson/issues/5795
