### ISSUE TITLE
 Unsupported protocol version 34

### ISSUE THREAD

**Issue by willzgw** [redisson/redisson#5749]
**Version**:
```
<dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson-spring-data-22</artifactId>
      <version>3.15.4</version>
    </dependency>
```
**Background**:
Previously I wrote some data in default codec() through Redisson, now I want to switch the encoding to **JSON**. 
Both **old** data and **new** data are exist in the map, for example:
```
10.169.75.15:6379[9]> hkeys gw_cluster_names
1) "\"gateway\""
2) "\"10.169.66.94:8443\""
3) "\"10.169.66.147:8443\""
4) "\x04>\x1110.169.66.94:8443"
5) "\x04>\x1210.169.66.147:8443"
6) "\x04>\agateway"
```
It reports the following error:
```
2024-04-03 10:44:41 [redisson-netty-2-13,null] ERROR CommandPubSubDecoder - [bTxId: , bSpanId: , bMode: ] Unable to decode data. channel: [id: 0x945b1674, L:/10.169.67.100:62282 - R:/10
.169.75.15:6379], reply: ReplayingDecoderByteBuf(ridx=330, widx=330) (CommandPubSubDecoder.java:76)
java.io.IOException: Unsupported protocol version 34
        at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1375)
        at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:145)
        at org.redisson.codec.BaseEventCodec.decode(BaseEventCodec.java:53)
        at org.redisson.codec.MapCacheEventCodec$1.decode(MapCacheEventCodec.java:39)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367)
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:72)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:88)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2024-04-03 10:44:41 [redisson-netty-2-13,null] ERROR ErrorsLoggingHandler - [bTxId: , bSpanId: , bMode: ] Exception occured. Channel: [id: 0x945b1674, L:/10.169.67.100:62282 - R:/10.169
.75.15:6379] (ErrorsLoggingHandler.java:47)
io.netty.handler.codec.DecoderException: java.io.IOException: Unsupported protocol version 34
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Unsupported protocol version 34
        at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1375)
        at org.redisson.codec.MarshallingCodec.lambda$new$0(MarshallingCodec.java:145)
        at org.redisson.codec.BaseEventCodec.decode(BaseEventCodec.java:53)
        at org.redisson.codec.MapCacheEventCodec$1.decode(MapCacheEventCodec.java:39)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:358)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:402)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:367)
        at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:72)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:116)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:88)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        ... 17 common frames omitted
```
The stack trace can't tell that which line of my code called it.
Can anyone help with this question?
Thanks in advance!

**Comment by mrniko** [comment]
it's a bad practice to store data in different formats in the same map.
