### ISSUE TITLE
ConcurrentModificationException on RedissonSession.save() still being thrown after fix

### ISSUE THREAD

**Issue by KatieRegnierTR** [redisson/redisson#5755]
As a follow up to this bug: [ConcurrentModificationException thrown on RedissonSession save method](https://github.com/redisson/redisson/issues/5677)

**Expected behavior**
Using Redisson based Tomcat Session Manager; no exceptions are thrown and sessions aren't lost prematurely.

**Actual behavior**
We cherry picked the two commits related to bug 5677 in order to test out the fix. However, we are still seeing a ConcurrentModificationException, but now with a different stack trace:

```
SEVERE: Exception Processing [...]
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:154)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:44)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
	at org.redisson.codec.Kryo5Codec$5.encode(Kryo5Codec.java:171)
	at org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:866)
	at org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:356)
	at org.redisson.RedissonMap.encodeMapKeys(RedissonMap.java:1063)
	at org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:787)
	at org.redisson.RedissonMap.putAllAsync(RedissonMap.java:728)
	at org.redisson.RedissonMap.putAll(RedissonMap.java:681)
	at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:424)
	at org.redisson.tomcat.RedissonSessionManager.store(RedissonSessionManager.java:420)
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:74)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1786)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
Wondering if there are any other changes that have been made since the 3.27.2 release that would contribute to resolving this? If not, it looks like the issue persists, we'd appreciate any help you can offer. 

**Steps to reproduce or test case**
This is seen when we run regression tests that repeatedly log in/out, creating and destroying multiple sessions originating from the same user. Only happens intermittently and not on the same tests every time.

**Redis version**
7.1

**Redisson version**
3.27.2
_Using the latest AttributesPutAllMessage.java and RedissonSession.java files included (unreleased versions)_

**Redisson configuration**
Happens in both clustered and single node instances, however marginally less in a clustered configuration (2 nodes, 2 shards per node).

Redisson Tomcat Session Manager configurations:

ReadMode: MEMORY
UpdateMode: AFTER_REQUEST
BroadcastSessionEvents: true
We do have a custom keyPrefix
Everything else is default values
Tomcat version: 9.0.86
Java version: 11

**Comment by mrniko** [comment]
Thanks for testing. Will look into that

**Comment by mrniko** [comment]
Thanks for report. Fixed in https://github.com/redisson/redisson/issues/5677
