### ISSUE TITLE
Redisson v3.25.2 Throws Exception While Decoding PubSub Message

### ISSUE THREAD

**Issue by nnanda2016** [redisson/redisson#5768]
My Environment:

```
Redis Version: 6.2
Redisson Version: 3.25.2
```
While reading a pubsub message, following exception is thrown
```java
2024-04-09 16:03:33.710  WARN 9621 --- [bscriber-SE-6-4] c.g.c.p.v.StreamingSubscriberConnection  : Setting response: SUCCESSFUL on outstanding messages
2024-04-09 16:03:36.788 TRACE 9621 --- [isson-netty-2-3] o.r.client.handler.CommandPubSubDecoder  : reply: *3
$7
message
$15
demoPubSubTopic
$11
MESSAGE-003
, channel: [id: 0x97739e54, L:/127.0.0.1:50816 - R:127.0.0.1/127.0.0.1:6379], command: null
2024-04-09 16:03:36.823 ERROR 9621 --- [isson-netty-2-3] o.r.client.handler.CommandPubSubDecoder  : Unable to decode data. channel: [id: 0x97739e54, L:/127.0.0.1:50816 - R:127.0.0.1/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=57, widx=57)

com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 75
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159) ~[kryo-5.5.0.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758) ~[kryo-5.5.0.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869) ~[kryo-5.5.0.jar:na]
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:394) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:442) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:403) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:88) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94) ~[redisson-3.23.5.jar:3.23.5]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2024-04-09 16:03:36.824 ERROR 9621 --- [isson-netty-2-3] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x97739e54, L:/127.0.0.1:50816 - R:127.0.0.1/127.0.0.1:6379]

io.netty.handler.codec.DecoderException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 75
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 75
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159) ~[kryo-5.5.0.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758) ~[kryo-5.5.0.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869) ~[kryo-5.5.0.jar:na]
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:144) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:394) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:442) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:403) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandPubSubDecoder.decodeCommand(CommandPubSubDecoder.java:88) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[redisson-3.23.5.jar:3.23.5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:94) ~[redisson-3.23.5.jar:3.23.5]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	... 17 common frames omitted
```

The client code looks like this:

```java
package com.demo;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.redisson.api.RTopic;
import org.redisson.api.RedissonClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("demo")
@Slf4j
public class RedisPubSubClientDemoIntTest {
    @Autowired
    private RedissonClient redissonClient;

    @Test
    public void listenToPubSub() {
        final RTopic topic = redissonClient.getTopic("demoPubSubTopic");
        topic.addListener(String.class, (channel, message) -> {
            log.info("RECEIVED MESSAGE. Message: {}", message);
        });

        try {
            log.info("Waiting for message...");
            Thread.sleep(30000);
        } catch (InterruptedException e) {
            log.error("InterruptedException while waiting for messages.");
        }
    }
}
```

Message is published from Redis-CLI
```bash
127.0.0.1:6379> PUBLISH demoPubSubTopic "MESSAGE-003"
(integer) 2
```

The CLI command is able to receive the messages
```bash
1) "message"
2) "demoPubSubTopic"
3) "MESSAGE-003"
```

Appreciate if you could help.

**Comment by mrniko** [comment]
> Message is published from Redis-CLI

Default codec is Kryo5Codec. You need to use StringCodec.

redissonClient.getTopic("demoPubSubTopic", StringCodec.INSTANCE);

**Comment by nnanda2016** [comment]
Thank you @mrniko . Appreciate your help.
