### ISSUE TITLE
Unknown argument `ASC` at position 12 for <main>

### ISSUE THREAD

**Issue by mengpp-0001** [redisson/redisson#5770]
According to the above query method, SORTBY's nargs should be 2, but I don't know why it is now 1, whether this problem is a bug

Redis version: 7.2.4
Redisson version: 3.27.2

error sql
`"FT.AGGREGATE" "idx-alarm" "*" "GROUPBY" "1" "@ajType" "REDUCE" "COUNT" "0" "AS" "count" "SORTBY" "1" "@ajType" "ASC"`

java code
`AggregationResult aggregate = redissonClient.getSearch()
                .aggregate(indexName, search, AggregationOptions.defaults()
                        .groupBy(GroupBy.fieldNames("@ajType").reducers(Reducer.count().as("count")))
                        .sortBy(new SortedField("@ajType"))
                );`

`org.redisson.client.RedisException: Unknown argument `ASC` at position 12 for <main>. channel: [id: 0x3e747bd7, L:/192.168.105.242:57790 - R:192.168.104.205/192.168.104.205:16389] command: (FT.AGGREGATE), promise: java.util.concurrent.CompletableFuture@1fbabed[Not completed, 1 dependents], params: [idx-alarm, *, GROUPBY, 1, @ajType, REDUCE, COUNT, 0, AS, count, ...]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:414)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by mrniko** [comment]
Fixed. Thanks for report
