### ISSUE TITLE
EMF | OPTION_USE_PACKAGE_NS_URI_AS_LOCATION 

### ISSUE THREAD

**Issue by Masood312** [redisson/redisson#5779]
In the provided Java call stack, it appears that HttpURLConnection is attempting to establish a connection. 
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1238)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.plainConnect0(HttpURLConnection.java:1174)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.plainConnect(HttpURLConnection.java:1068)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.connect(HttpURLConnection.java:1002)

I'm seeking guidance on how to disable this behavior. 

I suspect that the EMF framework might be initiating unnecessary connections. 

I would like to utilize the OPTION_USE_PACKAGE_NS_URI_AS_LOCATION feature to address this issue. 

Could you please advise on how to set OPTION_USE_PACKAGE_NS_URI_AS_LOCATION to false so that the EMF framework does not wait for the connection?

Here is the full call stack.

```
Java callstack:
4XESTACKTRACE                at java/net/PlainSocketImpl.socketConnect(Native Method)
4XESTACKTRACE                at java/net/AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:380)
5XESTACKTRACE                   (entered lock: java/net/SocksSocketImpl@0x00000007FB649CF8, entry count: 1)
4XESTACKTRACE                at java/net/AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236)
4XESTACKTRACE                at java/net/AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218)
4XESTACKTRACE                at java/net/SocksSocketImpl.connect(SocksSocketImpl.java:403)
4XESTACKTRACE                at java/net/Socket.connect(Socket.java:682)
4XESTACKTRACE                at java/net/Socket.connect(Socket.java:622)
4XESTACKTRACE                at sun/net/NetworkClient.doConnect(NetworkClient.java:192)
4XESTACKTRACE                at sun/net/www/http/HttpClient.openServer(HttpClient.java:494)
4XESTACKTRACE                at sun/net/www/http/HttpClient.openServer(HttpClient.java:589)
5XESTACKTRACE                   (entered lock: sun/net/www/http/HttpClient@0x00000007FB649DB8, entry count: 1)
4XESTACKTRACE                at sun/net/www/http/HttpClient.<init>(HttpClient.java:256)
4XESTACKTRACE                at sun/net/www/http/HttpClient.New(HttpClient.java:360)
4XESTACKTRACE                at sun/net/www/http/HttpClient.New(HttpClient.java:378)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1238)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.plainConnect0(HttpURLConnection.java:1174)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.plainConnect(HttpURLConnection.java:1068)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.connect(HttpURLConnection.java:1002)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.getInputStream0(HttpURLConnection.java:1582(Compiled Code))
5XESTACKTRACE                   (entered lock: sun/net/www/protocol/http/HttpURLConnection@0x00000007FB649E28, entry count: 2)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.getInputStream(HttpURLConnection.java:1510)
5XESTACKTRACE                   (entered lock: sun/net/www/protocol/http/HttpURLConnection@0x00000007FB649E28, entry count: 1)
4XESTACKTRACE                at org/eclipse/emf/ecore/resource/impl/URIConverterImpl.createURLInputStream(URIConverterImpl.java:566)
4XESTACKTRACE                at org/eclipse/emf/ecore/resource/impl/URIConverterImpl.createInputStream(URIConverterImpl.java:453)
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLHandler.getPackageForURI(XMLHandler.java:2292(Compiled Code))
4XESTACKTRACE                at org/eclipse/emf/ecore/sdo/util/DataGraphResourceFactoryImpl$DataGraphResourceImpl$LoadImpl$2.getPackageForURI(DataGraphResourceFactoryImpl.java:685)
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLHandler.getFactoryForPrefix(XMLHandler.java:2186(Compiled Code))
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLHandler.createObjectByType(XMLHandler.java:1156)
4XESTACKTRACE                at org/eclipse/emf/ecore/sdo/util/DataGraphResourceFactoryImpl$DataGraphResourceImpl$LoadImpl$2.handleFeature(DataGraphResourceFactoryImpl.java:587)
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLHandler.processElement(XMLHandler.java:898(Compiled Code))
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLHandler.startElement(XMLHandler.java:873(Compiled Code))
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLHandler.startElement(XMLHandler.java:641(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/parsers/AbstractSAXParser.startElement(Bytecode PC:299(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/impl/XMLDocumentFragmentScannerImpl.scanStartElement(Bytecode PC:311(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/impl/XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Bytecode PC:416(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/impl/XMLDocumentFragmentScannerImpl.scanDocument(Bytecode PC:26(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/parsers/XML11Configuration.parse(Bytecode PC:134(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/parsers/XML11Configuration.parse(Bytecode PC:29(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/parsers/XMLParser.parse(Bytecode PC:11(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/parsers/AbstractSAXParser.parse(Bytecode PC:43(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/jaxp/SAXParserImpl$JAXPSAXParser.parse(Bytecode PC:53(Compiled Code))
4XESTACKTRACE                at org/apache/xerces/jaxp/SAXParserImpl.parse(Bytecode PC:61(Compiled Code))
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLLoadImpl.load(XMLLoadImpl.java:236)
4XESTACKTRACE                at org/eclipse/emf/ecore/xmi/impl/XMLResourceImpl.doLoad(XMLResourceImpl.java:179)
4XESTACKTRACE                at org/eclipse/emf/ecore/resource/impl/ResourceImpl.load(ResourceImpl.java:1094(Compiled Code))
4XESTACKTRACE                at org/eclipse/emf/ecore/sdo/impl/EDataGraphImpl$EDataGraphExternalizable.readExternal(EDataGraphImpl.java:598)
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1444(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/BlockUnmarshaller.readObject(BlockUnmarshaller.java:149(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/BlockUnmarshaller.readObject(BlockUnmarshaller.java:135(Compiled Code))
4XESTACKTRACE                at org/eclipse/emf/ecore/sdo/impl/EDataGraphImpl$EDataObjectExternalizable.readExternal(EDataGraphImpl.java:650)
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1444(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:246(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.readFields(RiverUnmarshaller.java:1879(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1793(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1421(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/river/RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231(Compiled Code))
4XESTACKTRACE                at org/jboss/marshalling/AbstractObjectInput.readObject(AbstractObjectInput.java:41)
4XESTACKTRACE                at org/redisson/codec/MarshallingCodec.lambda$new$0(MarshallingCodec.java:146)
4XESTACKTRACE                at org/redisson/codec/MarshallingCodec$$Lambda$26/0x0000000000000000.decode(Bytecode PC:6)
4XESTACKTRACE                at org/redisson/client/handler/CommandDecoder.decode(CommandDecoder.java:383(Compiled Code))
4XESTACKTRACE                at org/redisson/client/handler/CommandDecoder.decodeList(CommandDecoder.java:420(Compiled Code))
4XESTACKTRACE                at org/redisson/client/handler/CommandDecoder.decode(CommandDecoder.java:392(Compiled Code))
4XESTACKTRACE                at org/redisson/client/handler/CommandDecoder.decodeCommandBatch(CommandDecoder.java:271(Compiled Code))
4XESTACKTRACE                at org/redisson/client/handler/CommandDecoder.decodeCommand(CommandDecoder.java:210(Compiled Code))
4XESTACKTRACE                at org/redisson/client/handler/CommandDecoder.decode(CommandDecoder.java:137(Compiled Code))
4XESTACKTRACE                at org/redisson/client/handler/CommandDecoder.decode(CommandDecoder.java:113(Compiled Code))

```

**Comment by Masood312** [comment]
@mrniko, do you have any suggestion.

**Comment by mrniko** [comment]
That's an interesting issue. MarshallingCodec was deprecated long time ago. You need to use Kryo5Codec instead, which is default one now.
