### ISSUE TITLE
Redisson java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by LiHanGod** [redisson/redisson#5788]
**Expected behavior**

No Exception

**Actual behavior**

Exception

**Steps to reproduce or test case**

```java
Config config = new Config();
config.useSingleServer().setAddress("redis://10.0.0.3:6379")
        .setTimeout(3000)
        .setConnectionPoolSize(10)
        .setConnectionMinimumIdleSize(0);
RedissonClient redisson = Redisson.create(config);
```

```shell
4月 16, 2024 9:57:21 下午 org.redisson.Version logVersion
信息: Redisson 3.28.0
4月 16, 2024 10:01:13 下午 org.redisson.connection.ConnectionsHolder lambda$initConnections$1
信息: 1 connections initialized for 10.0.0.3/10.0.0.3:6379
4月 16, 2024 10:01:16 下午 org.redisson.connection.ConnectionsHolder lambda$initConnections$1
信息: 1 connections initialized for 10.0.0.3/10.0.0.3:6379
4月 16, 2024 10:01:19 下午 org.redisson.connection.ConnectionsHolder lambda$initConnections$1
信息: 1 connections initialized for 10.0.0.3/10.0.0.3:6379
Exception in thread "main" org.redisson.client.RedisConnectionException: java.util.concurrent.TimeoutException
	at org.redisson.connection.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:229)
	at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:193)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:218)
	at org.redisson.Redisson.<init>(Redisson.java:70)
	at org.redisson.Redisson.create(Redisson.java:115)
	at pers.Main.main(Main.java:21)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.redisson.connection.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:225)
	... 5 more
```

**Redis version**

7.2.4

**Redisson version**

Redisson 3.28.0

**Exception reason**
```java
//org.redisson.connection.MasterSlaveConnectionManager 

    protected void doConnect(Set<RedisURI> disconnectedSlaves, Function<RedisURI, String> hostnameMapper) {
        try {
            if (config.isSlaveNotUsed()) {
                masterSlaveEntry = new SingleEntry(this, config);
            } else {
                masterSlaveEntry = new MasterSlaveEntry(this, config);
            }

            RedisURI uri = new RedisURI(config.getMasterAddress());
            String hostname = hostnameMapper.apply(uri);
            CompletableFuture<RedisClient> masterFuture = masterSlaveEntry.setupMasterEntry(uri, hostname);
            try {
                masterFuture.get(config.getConnectTimeout()*config.getMasterConnectionMinimumIdleSize(), TimeUnit.MILLISECONDS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            } catch (ExecutionException | TimeoutException e) {
                throw new RedisConnectionException(e);
            }

            if (!config.isSlaveNotUsed()) {
                CompletableFuture<Void> fs = masterSlaveEntry.initSlaveBalancer(disconnectedSlaves, hostnameMapper);
                try {
                    fs.get(config.getConnectTimeout()*config.getSlaveConnectionMinimumIdleSize(), TimeUnit.MILLISECONDS);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } catch (ExecutionException | TimeoutException e) {
                    throw new RedisConnectionException(e);
                }
            }

            startDNSMonitoring(masterFuture.getNow(null));
        } catch (Exception e) {
            internalShutdown();
            if (e instanceof CompletionException) {
                if (e.getCause() instanceof RuntimeException) {
                    throw (RuntimeException) e.getCause();
                }
                throw new RedisConnectionException(e.getCause());
            }
            throw e;
        }
    }
```
```java
masterFuture.get(config.getConnectTimeout()*config.getMasterConnectionMinimumIdleSize(), TimeUnit.MILLISECONDS); 
// MinimumIdleSize = 0，Interrupt thread
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
