### ISSUE TITLE
Call [RStream.autoClaim] throws ClassCastException after deleting the idle pending message

### ISSUE THREAD

**Issue by blueice1986** [redisson/redisson#5789]
**Expected behavior**
return the deleted message ids and pending messages without exception

**Actual behavior**
throw ClassCastException at first call [RStream.autoClaim]
**Steps to reproduce or test case**
```java
// initialization
@Bean
    public RedissonClient redissonClient(){
        Config config = new Config();
        config.setCodec(StringCodec.INSTANCE);
        config.useSingleServer()
                .setAddress(redisUrl);
        return Redisson.create(config);
    }
// receive method
public List<MqResponseEntity<long[]>> receiveMessageWithLongPolling(String queueUrl, String groupName, String consumerName, int maxNumberOfMessages) {
        RStream<String, Object> stream = redisson.getStream(queueUrl);
        int retrieveMessageCountRemain = maxNumberOfMessages;
        try {
            StreamCreateGroupArgs name = StreamCreateGroupArgs.name(groupName);
            name.id(StreamMessageId.ALL);
            stream.createGroup(name);
        } catch (RedisBusyException redisBusyException){
        }
        stream.createConsumer(groupName, consumerName);
        AutoClaimResult<String, Object> claimResult = stream.autoClaim(groupName, consumerName, 1L, TimeUnit.SECONDS, StreamMessageId.MIN, retrieveMessageCountRemain);
        Map<StreamMessageId, Map<String, Object>> claimResultMessages = claimResult.getMessages();
        Map<StreamMessageId, Map<String, Object>> allMessages = new LinkedHashMap<>(claimResultMessages);
        retrieveMessageCountRemain -= allMessages.size();
        if(retrieveMessageCountRemain > 0){
            Map<StreamMessageId, Map<String, Object>> messages = stream.readGroup(groupName,
                    consumerName, StreamReadGroupArgs.neverDelivered()
                            .count(retrieveMessageCountRemain)
                            .timeout((Duration.ofSeconds(20))));

            allMessages.putAll(messages);
        }
        List<MqResponseEntity<long[]>> result = new ArrayList<>(allMessages.size());
        for (Map.Entry<StreamMessageId, Map<String, Object>> entry : allMessages.entrySet()) {
            StreamMessageId messageId = entry.getKey();
            Map<String, Object> msg = entry.getValue();
            MqResponseEntity<long[]> mqResponseEntity = MqResponseEntity.<long[]>builder()
                    .id(new long[]{messageId.getId0(), messageId.getId1()})
                    .body(JSONUtils.toJsonString(msg))
                    .build();

            result.add(mqResponseEntity);
        }
        return result;
    }
// delete message
    public void deleteMessage(String queueName, List<MqResponseEntity<long[]>> messages) {
        RStream<String, Object> stream = redisson.getStream(queueName);
        StreamMessageId[] streamMessageIds = messages.stream()
                .map(e -> new StreamMessageId(e.getId()[0], e.getId()[1]))
                .toArray(StreamMessageId[]::new);

        stream.remove(streamMessageIds);
    }
// MqResponseEntity
@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class MqResponseEntity<T> {
    private T id;

    private String body;
}
 // test case
    @Test
    public void testReceive() throws Exception{
        String queueName = "test_0416_2";
        int j = 1;
        int batch = 2;
        //todo send some message to queue
        // ......
        List<MqResponseEntity<long[]>> responseEntities = null;
        do{
            try {
                responseEntities = receiveMessageWithLongPolling(queueName, "g1", "c", batch);
            } catch (Exception e){
                // ---> here is ClassCastException
                e.printStackTrace();
                // recall will right
                responseEntities = receiveMessageWithLongPolling(queueName, "g1", "c", batch);
            }
            System.out.println("recieved messages:" + responseEntities);
           // sleeping,  so that the pending messages can be auto claimed
            Thread.sleep(2000L);
            // delete the pending messages 
            if(j-- <= 0){
                deleteMessage(queueName, responseEntities);
                System.out.println("deleted messages:" + responseEntities);
            }
        }while(responseEntities.size() > 0);
    }

```
**Redis version**
7.2.4
**Redisson version**
3.27.2
**Redisson configuration**
        Config config = new Config();
        config.setCodec(StringCodec.INSTANCE);
        config.useSingleServer()
                .setAddress(redisUrl);
        return Redisson.create(config);

** Exception **
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.redisson.client.protocol.decoder.ObjectMapReplayDecoder2.decode(ObjectMapReplayDecoder2.java:38)
	at org.redisson.client.protocol.decoder.ObjectMapReplayDecoder2.decode(ObjectMapReplayDecoder2.java:31)
	at org.redisson.client.protocol.decoder.ListMultiDecoder2.decode(ListMultiDecoder2.java:47)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:502)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:445)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:493)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:445)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 common frames omitted

**Comment by mrniko** [comment]
Fixed. Thanks for report
