### ISSUE TITLE
Getting ClassCastException while commiting transaction with StringCodec

### ISSUE THREAD

**Issue by raja2102598** [redisson/redisson#5792]
I want to use String Codec for my keys, is there any way to fix this exception.

Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to org.redisson.cache.LocalCachedMapDisabledKey
	at org.redisson.cache.LocalCacheListener.add(LocalCacheListener.java:134)
	at org.redisson.RedissonLocalCachedMap.init(RedissonLocalCachedMap.java:99)
	at org.redisson.RedissonLocalCachedMap.<init>(RedissonLocalCachedMap.java:76)
	at org.redisson.Redisson.getLocalCachedMap(Redisson.java:386)

**Steps to reproduce or test case**

```
RedissonClient redissonClient = createRedissonClient();
CompositeCodec CODEC = new CompositeCodec(
            new StringCodec(), new SnappyCodecV2());;
RLocalCachedMap < Object, Object > localCachedMap = redissonClient.getLocalCachedMap(
            LocalCachedMapOptions.name("test1").codec(CODEC));
RTransaction transaction = redissonClient.createTransaction(
            TransactionOptions.defaults());
RLocalCachedMap < Object, Object > transactionLocalCachedMap = transaction.getLocalCachedMap(
            localCachedMap);
transactionLocalCachedMap.put("1", "1");
transaction.commit();
```

**Redis version**
7.2.4
**Redisson version**
3.28.0
**Redisson configuration**

```
String redisClusterUrls = "redis://localhost:7000,redis://localhost:7001,redis://localhost:7002,redis://localhost:7003,redis://localhost:7004,redis://localhost:7005";config.setThreads(Integer.parseInt("100"))
	.setNettyThreads(Integer.parseInt("100"))
	.setUseThreadClassLoader(false)
	.setUseScriptCache(true)
	.useClusterServers()
        .addNodeAddress(redisClusterUrls.split(","))
	.setReadMode(ReadMode.MASTER_SLAVE)
	.setTimeout(Integer.parseInt("5") * 60 * 1000)
	.setConnectTimeout(Integer.parseInt("5") * 60 * 1000)
	.setRetryInterval(5000)
	.setRetryAttempts(6)
	.setSubscriptionsPerConnection(Integer.parseInt("100"))
	.setSubscriptionConnectionPoolSize(Integer.parseInt("1000"))
	.setMasterConnectionPoolSize(Integer.parseInt("1000"))
	.setSlaveConnectionPoolSize(Integer.parseInt("1000"))
```

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by raja2102598** [comment]
Thank you for fixing the issue so fast. 

Also when can we expect the release of 3.28.1 ?

**Comment by mrniko** [comment]
During this month
