### ISSUE TITLE
Cannot create Redisson Client if it cannot connect to the only Slave in SLAVE and MASTER_SLAVE read mode

### ISSUE THREAD

**Issue by shailender-bathula** [redisson/redisson#580]
Hi all

As the issue title says, we cannot create Redisson Client if it cannot connect to the only Slave in SLAVE and MASTER_SLAVE read mode. While this looks like the expected behaviour, since creation of RedissonClient object can be very critical for an application startup, may be the redisson library can fallback to something more forgiving, like using the Master for reads with some error logs.

We have encountered this issue due to firewall rules not being setup correctly (which can happen, no matter how much effort is put in) and the consequence of this was our app did not start up and the deployment had to be rolled back. We couldn't explain why Redisson Client cannot be created when the connection to the Master was working, until I tested it out using the unit test below.

We have fixed up the firewall rules, but just wanted to inform as this feels like a rough edge. By the way, we were using 2.2.13 and this issue seems to be in the latest release 2.2.24 as well.

Thanks

The setup used for the unit test below is:
- Master listening on localhost:6379
- Slave listening on localhost:6380
- Sentinels running on localhost:5000, localhost:5001 and localhost:5002
- All the above processes running in a guest VM
- Unit test running on the host without port forwarding to guest 6380

``` java
import org.apache.log4j.BasicConfigurator;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.redisson.Config;
import org.redisson.ReadMode;
import org.redisson.Redisson;
import org.redisson.RedissonClient;
import org.redisson.SentinelServersConfig;

public class CannotCreateRedissonClientIfCannotConnectToSlaveTest {

    static {
        // For logging to console
        BasicConfigurator.configure();
    }

    private SentinelServersConfig sentinelServersConfig;
    private Config config;
    private RedissonClient redissonClient;

    @Before
    public void beforeEachTest() throws InterruptedException {
        config = new Config();
        sentinelServersConfig = config.useSentinelServers();
        sentinelServersConfig.setMasterName("mymaster");
        sentinelServersConfig.addSentinelAddress(new String[] { "localhost:5000", "localhost:5001", "localhost:5002" });
    }

    @After
    public void afterEachTest() {
        if (redissonClient != null) {
            redissonClient.shutdown();
        }
    }

    @Test
    public void testReadModeSlave() {
        sentinelServersConfig.setReadMode(ReadMode.SLAVE);
        redissonClient = Redisson.create(config);
    }

    @Test
    public void testReadModeMasterSlave() {
        sentinelServersConfig.setReadMode(ReadMode.MASTER_SLAVE);
        redissonClient = Redisson.create(config);
    }

    @Test
    public void testReadModeMaster() {
        sentinelServersConfig.setReadMode(ReadMode.MASTER);
        redissonClient = Redisson.create(config);
    }

}
```

`testReadModeSlave` and `testReadModeMaster` tests fail with the following error:

```
org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 5 were initialized. Server: /127.0.0.1:6380
    at org.redisson.connection.pool.ConnectionPool$2.operationComplete(ConnectionPool.java:112)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
    at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:247)
    at org.redisson.connection.pool.ConnectionPool.access$200(ConnectionPool.java:43)
    at org.redisson.connection.pool.ConnectionPool$3.operationComplete(ConnectionPool.java:213)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
    at org.redisson.connection.ClientConnectionsEntry$1.operationComplete(ClientConnectionsEntry.java:148)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:416)
    at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:141)
    at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:134)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:604)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:564)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:276)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:545)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:6380
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
    ... 7 more
```

I have also seen the following error when running the tests above, but does not seem to happen consistently:

```
io.netty.util.concurrent.DefaultPromise An exception was thrown by org.redisson.connection.pool.ConnectionPool$3.operationComplete() java.lang.NullPointerException
        at org.redisson.connection.MasterSlaveEntry.slaveDown(MasterSlaveEntry.java:120)
        at org.redisson.connection.MasterSlaveEntry.slaveDown(MasterSlaveEntry.java:114)
        at org.redisson.connection.pool.ConnectionPool.checkForReconnect(ConnectionPool.java:285)
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:249)
        at org.redisson.connection.pool.ConnectionPool.access$200(ConnectionPool.java:43)
        at org.redisson.connection.pool.ConnectionPool$3.operationComplete(ConnectionPool.java:218)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
        at org.redisson.connection.ClientConnectionsEntry$1.operationComplete(ClientConnectionsEntry.java:147)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
        at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:416)
        at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:108)
        at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:101)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:564)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
        at io.netty.channel.nio.AbstractNioChannel.doClose(AbstractNioChannel.java:462)
        at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:236)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:628)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:551)
        at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:593)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mrniko** [comment]
Did you solve this issue?

**Comment by shailender-bathula** [comment]
No sorry, haven't had the chance to look into fixing it.
