### ISSUE TITLE
Issue #4963 Back: Unable to find session error arise if Tomcat session was deleted or expired

### ISSUE THREAD

**Issue by JosephWitthuhnTR** [redisson/redisson#5835]
**Expected behavior**
Sessions should expire or end without writing errors and stack traces to log.

**Actual behavior**
We see a bunch of errors like this written to our logs:

```
[2024-05-02 14:23:00.198-0500] org.redisson.tomcat.RedissonSessionManager$1 onMessage
SEVERE: Unable to handle topic message
java.lang.IllegalStateException: Unable to find session: 9C310DE3F4E9461417DA9D906A2E43F5
	at org.redisson.tomcat.RedissonSessionManager$1.onMessage(RedissonSessionManager.java:318)
	at org.redisson.tomcat.RedissonSessionManager$1.onMessage(RedissonSessionManager.java:279)
	at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:68)
	at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$2(CommandPubSubDecoder.java:221)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It looks like [this commit](https://github.com/redisson/redisson/commit/def51ad50423a37e74cc9a44f120ae17343c8fc4#diff-0118471e2905c823fdad2f66f28f2bb5d48226207df0cbad5bcb2f4c5bf7d490L319) to support #4963 was undone at some point? Looking at the file history, I'm not sure what the reason was. (none of the subsequent commits on that file show it being undone, unless I am missing something)

**Steps to reproduce or test case**
Run regression testing against an application that creates sessions, ends sessions, and allows sessions to expire. The more application server instances you run, the more noisy the logs seem to get.

**Redis version**
7.1

**Redisson version**
3.29.0

**Redisson configuration**
Clustered configuration (2 nodes, 2 shards per node).

Redisson Tomcat Session Manager configurations:

ReadMode: MEMORY
UpdateMode: AFTER_REQUEST
BroadcastSessionEvents: true
We do have a custom keyPrefix
Everything else is default values
Tomcat version: 9.0.86
Java version: 11

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/4963 fixes only case for SessionDestroyedMessage

**Comment by mrniko** [comment]
Fixed. Thanks for report
