### ISSUE TITLE
eval  when value is json str ,not execute

### ISSUE THREAD

**Issue by changyoutianxia** [redisson/redisson#5881]
**Expected behavior**
org.redisson.client.RedisException: ERR user_script:2: Expected value but found invalid token at character 1 script: bf74b6f1f9537dfddb0df4d0aa70f50e3897a550, on @user_script:2.. channel: [id: 0x0bd8740e, L:/192.168.166.1:65324 - R:env.crazyim.com/192.168.166.129:21001] command: (EVAL), promise: java.util.concurrent.CompletableFuture@7267c394[Not completed, 1 dependents], params: [ local key = KEYS[1] 
 local maps = cjson.decode(ARGV[1]) for field, value in pairs(maps) do 
    redis.call('HSET', key, field, value) 
end 
, 1, crazyim:core:sequence:target:ee, PooledUnsafeDirectByteBuf(ridx: 0, widx: 41, cap: 256)]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:415)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Actual behavior**

  execute

**Steps to reproduce or test case**
 java:

        Map<String, Long> filedMap = new HashMap<>();
        filedMap.put(ID, 1L);
        filedMap.put(MAX_VALUE, 2L);
        // 设置当前值和最大值
        redissonClient.getScript().eval(RScript.Mode.READ_WRITE, getSyncHSetRedisStr(), RScript.ReturnType.VALUE, "aa",JSONUtils.toJson(filedMap));

    public String getSyncHSetRedisStr() {

        return " local key = KEYS[1] \n" +
                " local maps = cjson.decode(ARGV[1]) " +
                "for field, value in pairs(maps) do \n" +
                "    redis.call('HSET', key, field, value) \n" +
                "end \n";
    }

**Redis version**
 7.0
**Redisson version**
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>3.30.0</version>
            </dependency>
**Redisson configuration**

spring:
  redis:
    database: 0
    host: env.crazyim.com
    port: 21001
    password: crazyim

**Comment by changyoutianxia** [comment]
when test other encode has other str
 expression  ((PooledUnsafeDirectByteBuf)encode(Arrays.asList(values), codec).get(0)).toString(Charset.defaultCharset())
![dfedf843858ad2a72dd14cd7e020506](https://github.com/redisson/redisson/assets/46896358/f9f2c089-cf10-4de0-8711-e2c1bb32d545)

**Comment by changyoutianxia** [comment]
need  .getScript(StringCodec.INSTANCE)
