### ISSUE TITLE
Redisson json set doesn't accept "=" as json string key

### ISSUE THREAD

**Issue by inampar** [redisson/redisson#5894]
**Expected behavior**
Any number of keys with '=' should be allowed

**Actual behavior**

When using JSON of type below, it allows only 1 key to have '=' in key name

![image](https://github.com/redisson/redisson/assets/162435267/1b28c340-03b3-4f49-9773-8fabcfff983d)
**Steps to reproduce or test case**

 ```
TypeReference<Map<String,Pojo>> ref = new TypeReference<Map<String, Pojo>>() {

        };

       RJsonBucket bucket= redissonClient.getJsonBucket("equalToErrorKey", new JacksonCodec<>(ref));
       if(!bucket.isExists()){
           bucket.set(Map.of("POP=", Pojo.builder().ainteger(1).twoString("2").build())); //This will work
       }
       bucket.set("ABC=1", Pojo.builder().ainteger(1).twoString("2").build()); //It will start failing from here
       bucket.set("ABCD=1", Pojo.builder().ainteger(1).twoString("2").build());
       bucket.set("ABF1=", Pojo.builder().ainteger(1).twoString("2").build());
```
It works if we do not use "=" as keys like below
     
```
 bucket.set("ABC1", Pojo.builder().ainteger(1).twoString("2").build()); //It will start failing from here
       bucket.set("ABCD1", Pojo.builder().ainteger(1).twoString("2").build());
       bucket.set("ABF1", Pojo.builder().ainteger(1).twoString("2").build());
```

Pojo class:
```
@Data
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Pojo implements Serializable {

    private String oneString;
    private String twoString;
    private Long oneLing;
    private Integer ainteger;
    private Double aDouble;
}
```
**Redis version**

**Redisson version**
3.30.0
**Redisson configuration**

**Comment by inampar** [comment]
@mrniko 
Any suggestions/quick workaround /fix for this?

**Comment by ling0900** [comment]
could you paste some error message？

**Comment by inampar** [comment]
@ling0900 

`bucket.set("ABC=1", Pojo.builder().ainteger(1).twoString("2").build()); //It will start failing from here`

2024-05-22T17:27:20.294+05:30 ERROR 26412 --- [RedisStreamIssue] [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: **org.redisson.client.RedisException: Error occurred on position 5, "$.ABC ---->>>> =1", expected one of the following: EOI, '..'.. channel: [id: 0x88d2c1b8, L:/127.0.0.1:53915 - R:localhost/127.0.0.1:6379] command: (JSON.SET), promise: java.util.concurrent.CompletableFuture@c98ce6a[Not completed, 1 dependents], params: [dss:fx:rates, ABC=1, PooledUnsafeDirectByteBuf(ridx: 0, widx: 30, cap: 256)]] with root cause**

**org.redisson.client.RedisException: Error occurred on position 5, "$.ABC ---->>>> =1", expected one of the following: EOI, '..'.. channel: [id: 0x88d2c1b8, L:/127.0.0.1:53915 -** R:localhost/127.0.0.1:6379] command: (JSON.SET), promise: java.util.concurrent.CompletableFuture@c98ce6a[Not completed, 1 dependents], params: [dss:fx:rates, ABC=1, PooledUnsafeDirectByteBuf(ridx: 0, widx: 30, cap: 256)]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:415) ~[redisson-3.29.0.jar:3.29.0]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216) ~[redisson-3.29.0.jar:3.29.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[redisson-3.29.0.jar:3.29.0]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120) ~[redisson-3.29.0.jar:3.29.0]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[netty-codec-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

**Comment by ling0900** [comment]
Please focus on the JSON values rather than the keys for this question.

**Comment by inampar** [comment]
@ling0900 

```
if(!bucket.isExists()){
          bucket.set(Map.of("POP=", Pojo.builder().ainteger(1).twoString("2").build())); //This will work
}
```
This above snippet works as I already mentioned.
What doesn't work is below after execution of above

```
 bucket.set("ABC=1", Pojo.builder().ainteger(1).twoString("2").build()); //It will start failing from here
      bucket.set("ABCD=1", Pojo.builder().ainteger(1).twoString("2").build());
      bucket.set("ABF1=", Pojo.builder().ainteger(1).twoString("2").build());
```

Can you please elaborate on -

`if structure coulde be removed, also`

**Comment by ling0900** [comment]
this is a question...

jdk11 is ok,hhh

and the redis version , mybe u can use the latest


"command: (JSON.SET)," here,  is related: https://github.com/RedisJSON/RedisJSON/pull/916

**Comment by mrniko** [comment]
`=` symbol should be escaped like this `$["ABC=1"]`
```java
bucket.set("$[\"ABC=1\"]", "1231232");
```
