### ISSUE TITLE
redisson netty consumes high cpu

### ISSUE THREAD

**Issue by hongkong9771** [redisson/redisson#5897]
**Expected behavior**

**Actual behavior**
In Redis cluster mode, when the master node crashes, the application's CPU usage reaches 100%, and even after the master node is restored (becoming a slave node), the CPU usage remains very high.
After checking the CPU usage of threads, it was found that the CPU usage of Redisson Netty occupied almost all CPUs. And the error is as follows:
Unable to write command into connection! Check CPU usage of the JVM. Try to increase nettyThreads setting. Node source: NodeSource [slot=12778, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@735738459 [redisClient=[addr=redis://10.4.210.79:7001], channel=[id: 0xe55ebb6d, L:/172.16.61.4:51843 ! R:10.4.210.79/10.4.210.79:7001], currentCommand=null, usage=1], command: (SMEMBERS), params: [******] after 0 retry attempts

10.4.210.79:7001 is a failed master node that has been restored.

![image](https://github.com/redisson/redisson/assets/46513782/83238320-177f-4c03-bca4-268a7ec95837)

"redisson-netty-1-1" #19 prio=5 os_prio=0 tid=0x000055791c7a0000 nid=0x23 runnable [0x00007f479cfbb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000750555158> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000007505c1d90> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007505550b0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:814)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"redisson-netty-1-2" #20 prio=5 os_prio=0 tid=0x000055791c53b000 nid=0x24 runnable [0x00007f479ceba000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000074fa091e0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000750713588> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000074fa09148> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:810)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"redisson-netty-1-30" #56 prio=5 os_prio=0 tid=0x000055791cace800 nid=0x49 runnable [0x00007f479250d000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000074fad9fc0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000075062be20> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000074fad9f28> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:810)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

**Steps to reproduce or test case**
1. Hang down the master node to reproduce it
2. Restore the master node to the slave node while still maintaining the status quo

**Redis version**
5.0.5

**Redisson version**
redisson-spring-boot-starter:3.30.0

**Redisson configuration**
config.useClusterServers()
                        .addNodeAddress(clusterAddresses.toArray(new String[0]))
                        .setPassword(this.config.get(Options.REDIS_PASSWORD))
                        .setConnectTimeout(800)
                        .setTimeout(800)
                        .setRetryAttempts(0)
                        .setRetryInterval(1500)
                        .setMasterConnectionMinimumIdleSize(150)
                        .setMasterConnectionPoolSize(150)
                        .setSlaveConnectionMinimumIdleSize(150)
                        .setSlaveConnectionPoolSize(150)
                        .setReadMode(ReadMode.MASTER_SLAVE);

**Comment by mrniko** [comment]
Can you share Redisson logs?

**Comment by hongkong9771** [comment]
> Can you share Redisson logs?

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Check CPU usage of the JVM. Try to increase nettyThreads setting. Node source: NodeSource [slot=1219, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@854671988 [redisClient=[addr=redis://10.4.210.78:7001], channel=[id: 0xb8305459, L:/172.16.85.204:43785 ! R:10.4.210.78/10.4.210.78:7001], currentCommand=null, usage=1], command: (SISMEMBER), params: [key name, PooledUnsafeDirectByteBuf(ridx: 0, widx: 17, cap: 256)] after 0 retry attempts
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:366)
	at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:197)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1021)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:882)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

**Comment by hongkong9771** [comment]
Only by restarting the application can it be resolved.

**Comment by hongkong9771** [comment]
The situation I encountered is the same as this, The Redisson logs are also similar.
https://giters.com/redisson/redisson/issues/5857

I will try version 3.27.2.

**Comment by hongkong9771** [comment]
> The situation I encountered is the same as this, The Redisson logs are also similar. https://giters.com/redisson/redisson/issues/5857
> 
> I will try version 3.27.2.

I have try 3.27.2, but it stilll didn't work.

**Comment by mrniko** [comment]
Can you try 3.31.0 version?

**Comment by ramjeetm** [comment]
Hi Every,

does anyone has a fix for this issue, please help me I am struggling it
