### ISSUE TITLE
Issue in deserialisation using Kryo5Codec

### ISSUE THREAD

**Issue by arnab-ray** [redisson/redisson#5904]
Upgraded Java version from 11 to 21. This meant that `FstCodec` couldn't be supported, hence I migrated the codec to Kryo5Codec. So the updated redisson with Kryo5Codec is unable to read data written by FstCodec (old redisson version 3.11.3).

**Expected behavior**
It is expected to return a map

```
private RMapCache<String, Integer> apiRateLimitMinuteWiseMapCache;
apiRateLimitMinuteWiseMapCache = redissonClient.getMapCache(MAP_NAME_FOR_MINUTE_WISE);
```

**Actual behavior**
```
Caused by: org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:365)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:179)
	at org.redisson.RedissonObject.get(RedissonObject.java:94)
	at org.redisson.RedissonMap.scanIterator(RedissonMap.java:1480)
	at org.redisson.iterator.RedissonMapIterator.iterator(RedissonMapIterator.java:49)
	at org.redisson.iterator.BaseIterator.hasNext(BaseIterator.java:61)
	at org.redisson.RedissonMap.hashCode(RedissonMap.java:1599)
	at com.groww.credit.master.commons.util.ApiRateLimitRedisCacheUtil.hashCode(ApiRateLimitRedisCacheUtil.java:23)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(Unknown Source)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.requiresDestruction(PersistenceAnnotationBeanPostProcessor.java:401)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.hasApplicableProcessors(DisposableBeanAdapter.java:459)
	at org.springframework.beans.factory.support.AbstractBeanFactory.requiresDestruction(AbstractBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractBeanFactory.registerDisposableBeanIfNecessary(AbstractBeanFactory.java:1854)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
	... 33 common frames omitted
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 6650
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:437)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:494)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:446)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:494)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:446)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Steps to reproduce or test case**
Spring boot `@Bean` creation

```
@Bean
  @Primary
  RedissonClient redisClient() throws Exception {
    final org.springframework.core.io.Resource redisConfigDetail = resourceLoader.getResource(redisConfigPath);
    final Config config = Config.fromYAML(redisConfigDetail.getInputStream());
    if (config.isSentinelConfig())
      config.useSentinelServers();
    else
      config.useSingleServer();
    return Redisson.create(config);
  }
```

**Redis version**
6.2.10

**Spring version**
3.2.0

**Redisson version**
3.30.0

**Redisson configuration**
```
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  address: "redis://${CREDIT_REDIS_URL}:${CREDIT_REDIS_PORT}"
  password: ${CREDIT_REDIS_PASSWORD}
  subscriptionsPerConnection: 5
  clientName: null
  connectionMinimumIdleSize: 30
  connectionPoolSize: 512
  database: 0
threads: 128
nettyThreads: 256
codec: !<org.redisson.codec.Kryo5Codec> {}
transportMode: "NIO"
```

**Comment by arnab-ray** [comment]
@mrniko Kindly help with this

**Comment by raja2102598** [comment]
you should set Kryo5Codec.registrationRequired to false

**Comment by arnab-ray** [comment]
We do not need to set this since the default constructor sets it to false already.

**Comment by mrniko** [comment]
That may happen if stored data encoded with a different codec. Also try to clear Redis database.
