### ISSUE TITLE
RedissonShutdownException: Redisson is shutdown

### ISSUE THREAD

**Issue by app2smile** [redisson/redisson#5933]
Describe:

When I upgraded to version 3.29.0 or higher of Redisson, I observed that The `subscribeOnElements(Consumer<V> consumer)` method is Deprecated
```
@Deprecated
int subscribeOnElements(Consumer<V> consumer);

int subscribeOnElements(Function<V, CompletionStage<Void>> consumer);
```

When using instead methods, the program runs without any issues.
But when the program stops, an error occurs:
```
java.util.concurrent.CompletionException: org.redisson.RedissonShutdownException: Redisson is shutdown
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[na:na]
	at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:632) ~[redisson-3.31.0.jar:3.31.0]
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:614) ~[redisson-3.31.0.jar:3.31.0]
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:602) ~[redisson-3.31.0.jar:3.31.0]
	at org.redisson.command.RedisExecutor.lambda$execute$6(RedisExecutor.java:204) ~[redisson-3.31.0.jar:3.31.0]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[na:na]
	at org.redisson.command.RedisExecutor.lambda$handleBlockingOperations$14(RedisExecutor.java:494) ~[redisson-3.31.0.jar:3.31.0]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[na:na]
	at org.redisson.connection.ServiceManager.lambda$shutdownFutures$2(ServiceManager.java:359) ~[redisson-3.31.0.jar:3.31.0]
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4709) ~[na:na]
	at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5944) ~[na:na]
	at org.redisson.connection.ServiceManager.shutdownFutures(ServiceManager.java:359) ~[redisson-3.31.0.jar:3.31.0]
	at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:509) ~[redisson-3.31.0.jar:3.31.0]
	at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:494) ~[redisson-3.31.0.jar:3.31.0]
	at org.redisson.Redisson.shutdown(Redisson.java:1121) ~[redisson-3.31.0.jar:3.31.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:316) ~[spring-beans-6.1.8.jar:6.1.8]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:249) ~[spring-beans-6.1.8.jar:6.1.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-6.1.8.jar:6.1.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-6.1.8.jar:6.1.8]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1202) ~[spring-beans-6.1.8.jar:6.1.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-6.1.8.jar:6.1.8]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1195) ~[spring-beans-6.1.8.jar:6.1.8]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1186) ~[spring-context-6.1.8.jar:6.1.8]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1147) ~[spring-context-6.1.8.jar:6.1.8]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174) ~[spring-boot-3.3.0.jar:3.3.0]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1093) ~[spring-context-6.1.8.jar:6.1.8]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-3.3.0.jar:3.3.0]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) ~[spring-boot-3.3.0.jar:3.3.0]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: org.redisson.RedissonShutdownException: Redisson is shutdown
	... 24 common frames omitted
```

This is the code:
```
package com.smile.redissondemo;

import jakarta.annotation.PostConstruct;
import org.redisson.api.RBlockingDeque;
import org.redisson.api.RDelayedQueue;
import org.redisson.api.RedissonClient;
import org.redisson.client.codec.StringCodec;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

@SpringBootApplication
public class RedissonDemoApplication implements CommandLineRunner {
    @Autowired
    RedissonClient redissonClient;

    private static RDelayedQueue<String> DELAYED_DEQUE;
    private static RBlockingDeque<String> BLOCKING_DEQUE;


    @PostConstruct
    public void init() {
        BLOCKING_DEQUE = redissonClient.getBlockingDeque("demo_blocking_test", StringCodec.INSTANCE);
        DELAYED_DEQUE = redissonClient.getDelayedQueue(BLOCKING_DEQUE);

        // int subscribeOnElements(Consumer<V> consumer); Deprecated...
//        BLOCKING_DEQUE.subscribeOnElements(s -> {
//            System.out.println("data:" + s);
//        });

        // instead: int subscribeOnElements(Function<V, CompletionStage<Void>> consumer);
        // When stopping the program, error
        BLOCKING_DEQUE.subscribeOnElements(s -> {
            System.out.println("data:" + s);
            return CompletableFuture.completedFuture(null);
        });
    }

    public static void main(String[] args) {
        SpringApplication.run(RedissonDemoApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        DELAYED_DEQUE.offer("1", 1, TimeUnit.SECONDS);
    }
}
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
