### ISSUE TITLE
Remote service exception on shutdown

### ISSUE THREAD

**Issue by AoElite** [redisson/redisson#5947]
### Redis version

7.0

### Redisson version

3.31.0

### Redisson configuration

```java
        Config config = new Config();
        config.setCodec(new JsonJacksonCodec());
        config.setKeepPubSubOrder(true);
        config.setThreads(8);
        config.setNettyThreads(16);
        config.setUseScriptCache(true);
        
        var msc = config.useSingleServer();
        msc.setConnectionMinimumIdleSize(4);
        msc.setConnectionPoolSize(16);
        msc.setIdleConnectionTimeout(10000);
        msc.setSubscriptionConnectionMinimumIdleSize(1);
        msc.setSubscriptionConnectionPoolSize(16);
        msc.setSubscriptionsPerConnection(4);
        msc.setTimeout(3000);
        msc.setConnectTimeout(10000);
        msc.setSubscriptionTimeout(7500);
        msc.setRetryAttempts(15);
        msc.setRetryInterval(2000);
        msc.setPingConnectionInterval(30000);
        msc.setDnsMonitoringInterval(10000);
```

### What is the Expected behavior?

Not to throw an error when shutting down

### What is the Actual behavior?

Exception occurs on shut down

### Additional information

```
[02:03:46 ERROR] [org.redisson.RedissonRemoteService]: Can't process the remote service request with id 630cad0fade43259dfcf9506159925cd
java.util.concurrent.CompletionException: org.redisson.RedissonShutdownException: Redisson is shutdown
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
        at org.redisson.misc.CompletableFutureWrapper.whenComplete(CompletableFutureWrapper.java:223) ~[?:?]
        at org.redisson.RedissonRemoteService.lambda$subscribe$9(RedissonRemoteService.java:278) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:649) ~[?:?]
        at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:625) ~[?:?]
        at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:602) ~[?:?]
        at org.redisson.command.RedisExecutor.lambda$execute$6(RedisExecutor.java:204) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:528) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:522) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decodeResult(CommandDecoder.java:512) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:507) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:449) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) ~[?:?]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120) ~[?:?]
        at rel.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[?:?]
        at rel.io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[?:?]
        at rel.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[?:?]
        at rel.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
        at rel.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at rel.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
        at rel.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at rel.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
        at rel.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
        at rel.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at rel.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
        at rel.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
        at rel.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[?:?]
        at rel.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[?:?]
        at rel.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
        at rel.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
        at rel.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at rel.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.redisson.RedissonShutdownException: Redisson is shutdown
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128) ~[?:?]
        at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:553) ~[?:?]
        at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:449) ~[?:?]
        at org.redisson.RedissonMap.removeOperationAsync(RedissonMap.java:1366) ~[?:?]
        at org.redisson.RedissonMap.removeAsync(RedissonMap.java:1356) ~[?:?]
        at org.redisson.RedissonRemoteService.getTask(RedissonRemoteService.java:500) ~[?:?]
        at org.redisson.RedissonRemoteService.lambda$subscribe$9(RedissonRemoteService.java:277) ~[?:?]
        ... 39 more
        ```

**Comment by mrniko** [comment]
Fixed. Thanks for report
