### ISSUE TITLE
Redis search get index info offset_bits_per_record_avg format exception

### ISSUE THREAD

**Issue by mylife1984** [redisson/redisson#5950]
### Redis version

7.2.4

### Redisson version

3.31.0

### Redisson configuration

  data:
    redis:
      host:  
      port: 6379 
      database: 0 
      password:  

### What is the Actual behavior?

io.netty.handler.codec.DecoderException: java.lang.NumberFormatException: For input string: "15.182429313659668"
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NumberFormatException: For input string: "15.182429313659668"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:709)
	at java.base/java.lang.Long.valueOf(Long.java:1157)
	at org.redisson.client.protocol.decoder.IndexInfoDecoder.toLong(IndexInfoDecoder.java:86)
	at org.redisson.client.protocol.decoder.IndexInfoDecoder.decode(IndexInfoDecoder.java:63)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:506)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:449)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 17 common frames omitted

### Additional information

9) "num_docs"
10) "7"
11) "max_doc_id"
12) "7"
13) "num_terms"
14) "3890"
15) "num_records"
16) "9264"
17) "inverted_sz_mb"
18) "0.06223869323730469"
19) "vector_index_sz_mb"
20) "2.2241592407226563"
21) "total_inverted_index_blocks"
22) "3900"
23) "offset_vectors_sz_mb"
24) "0.01804637908935547"
25) "doc_table_size_mb"
26) "7.009506225585938e-4"
27) "sortable_values_size_mb"
28) "0"
29) "key_table_size_mb"
30) "3.0422210693359375e-4"
31) "geoshapes_sz_mb"
32) "0"
33) "records_per_doc_avg"
34) "1323.4285888671875"
35) "bytes_per_record_avg"
36) "7.044689178466797"
37) "offsets_per_term_avg"
38) "1.0763169527053833"
39) "offset_bits_per_record_avg"
40) "15.182429313659668"
41) "hash_indexing_failures"
42) "0"
43) "total_indexing_time"
44) "32.23899841308594"
45) "indexing"
46) "0"
47) "percent_indexed"
48) "1"
49) "number_of_uses"
50) "10"
51) "cleaning"
52) "0"
53) "gc_stats"

org.redisson.client.protocol.decoder.IndexInfoDecoder

 ii.setOffsetBitsPerRecordAverage(toLong(result, "offset_bits_per_record_avg"));

**Comment by mrniko** [comment]
Merged. Thanks for report
