### ISSUE TITLE
java.net.MalformedURLException: Invalid host: [[fd00:177:177:0:fea4:85b:8409:c4cc]

### ISSUE THREAD

**Issue by flcake** [redisson/redisson#5951]
java.lang.IllegalArgumentException: java.net.MalformedURLException: Invalid host: [[fd00:177:177:0:fea4:85b:8409:c4cc]
        at org.redisson.misc.RedisURI.<init>(RedisURI.java:54)
        at org.redisson.connection.MasterSlaveEntry.initSlaveBalancer(MasterSlaveEntry.java:94)
        at org.redisson.cluster.ClusterConnectionManager.lambda$null$2(ClusterConnectionManager.java:242)
        at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
        at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
        at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:444)
        at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:439)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:826)
Caused by: java.net.MalformedURLException: Invalid host: [[fd00:177:177:0:fea4:85b:8409:c4cc]
        at java.net.URL.<init>(URL.java:645)
        at java.net.URL.<init>(URL.java:508)
        at java.net.URL.<init>(URL.java:457)
        at org.redisson.misc.RedisURI.<init>(RedisURI.java:49)
        ... 36 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid host: [[fd00:177:177:0:fea4:85b:8409:c4cc]
        at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:195)
        at java.net.URL.<init>(URL.java:640)
        ... 39 common frames omitted

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/2548
