### ISSUE TITLE
Connection RST causes "Command execution timeout for command: (CLUSTER NODES)"

### ISSUE THREAD

**Issue by eladbern** [redisson/redisson#5973]
### Redis version

7.1

### Redisson version

3.29.0

### Redisson configuration

```
Config config = new Config();
        config.useClusterServers()
                .addNodeAddress(
                        "rediss://MY-REDIS:6379")
                .setConnectTimeout(500)
                .setTimeout(5000)
                .setRetryAttempts(3)
                .setRetryInterval(200);
```

### What is the Expected behavior?

If a connection is terminated and the client is able to immediately reconnect, its expected that the `cluster nodes` command would not timeout but be retried instead. 

### What is the Actual behavior?

A timeout exception is thrown. This seems to depend on timing leading to the assumption that this might be related to dropping the connection with an in-flight request. 

### Additional information

DEBUG logs attached:
```
2024.06.19 11:03:04.380 DEBUG ClusterConnectionManager : rediss://MY-REDIS:6379 resolved to rediss://172.31.21.158:6379
2024.06.19 11:03:04.380 DEBUG ClusterConnectionManager : rediss://MY-REDIS:6380 resolved to rediss://172.31.21.158:6380
2024.06.19 11:03:09.478 DEBUG ClusterConnectionManager : rediss://MY-REDIS:6379 resolved to [rediss://172.31.21.158:6379]
2024.06.19 11:03:09.578 DEBUG ConnectionWatchdog : reconnecting RedisConnection@212827310 [redisClient=[addr=rediss://MY-REDIS:6379], channel=[id: 0x5ff27dc1, L:/172.31.31.217:45176 ! R:MY-REDIS/172.31.21.158:6379], currentCommand=null, usage=0] to MY-REDIS/172.31.21.158:6379 
2024.06.19 11:03:09.579 DEBUG RedisConnection : Connection created [addr=rediss://MY-REDIS:6379]
2024.06.19 11:03:09.590 DEBUG InsecureTrustManagerFactory : Accepting a server certificate: CN=MY-REDIS
2024.06.19 11:03:09.592 DEBUG SslHandler : [id: 0x77b41d03, L:/172.31.31.217:41502 - R:MY-REDIS/172.31.21.158:6379] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_128_GCM_SHA256
2024.06.19 11:03:09.607 DEBUG ConnectionWatchdog : RedisConnection@212827310 [redisClient=[addr=rediss://MY-REDIS:6379], channel=[id: 0x5ff27dc1, L:/172.31.31.217:45176 ! R:MY-REDIS/172.31.21.158:6379], currentCommand=null, usage=0] connected to MY-REDIS/172.31.21.158:6379, command: null
2024.06.19 11:03:14.578 ERROR ClusterConnectionManager : Unable to execute (CLUSTER NODES)
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=rediss://MY-REDIS:6379]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024.06.19 11:03:14.580 ERROR ClusterConnectionManager : Can't update cluster state
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=rediss://MY-REDIS:6379]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by eladbern** [comment]
Additional information - 
This seems to also apply to user commands. Once the connection is reset while there is an in-flight command, the connection watchdog handler is triggered and immediately triggers reconnect while the command promise is left to fail only upon its timeout.  Only then, does the retry mechanism kicks in. This causes unnecessarily high latency.

**Comment by mshahmoradi87** [comment]
@mrniko would you please look into this issue, we have also faced this.

**Comment by barreeeiroo** [comment]
@eladbern can you check if you have any logs mentioning this exception: `DnsNameResolverTimeoutException`? We are also facing this same issue, and on top of that other exception we found this as well: https://github.com/redisson/redisson/issues/6050.

**Comment by mrniko** [comment]
> Additional information - This seems to also apply to user commands. Once the connection is reset while there is an in-flight command, the connection watchdog handler is triggered and immediately triggers reconnect while the command promise is left to fail only upon its timeout. Only then, does the retry mechanism kicks in. This causes unnecessarily high latency.

Good point. Will fix that.

**Comment by mrniko** [comment]
@eladbern

Done for user commands

**Comment by mrniko** [comment]
Fixed. Thanks for report.
