### ISSUE TITLE
RMap When a Value get from an RMap cannot be converted to a related object When using CompositeCodec Specify mapValueCodec as TypedJsonJacksonCodec.

### ISSUE THREAD

**Issue by sanshi2018** [redisson/redisson#5974]
### Redis version

6.2.12

### Redisson version

3.21.3

### Redisson configuration

Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379");

### What is the Expected behavior?

Line 55 expects map.get(name) to return a value of type Member instead of LinkedHashMap, When using CompositeCodec Specify mapValueCodec as TypedJsonJacksonCodec.

If you don't specify CompositeCodec but use JsonJacksonCodec then it works fine.

The getMemberByName method will throw the following exception

![image](https://github.com/redisson/redisson/assets/49914390/b243813a-210b-482e-bdee-1158b6cc65cc)

`Exception in thread "main" java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class org.redisson.example.collections.Member (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; org.redisson.example.collections.Member is in unnamed module of loader 'app')
	at org.redisson.example.collections.RMapErrorDemo.getMemberByName(RMapErrorDemo.java:69)
	at org.redisson.example.collections.RMapErrorDemo.main(RMapErrorDemo.java:50)`

### What is the Actual behavior?

When I specify the CompositeCodec for the RMap, I am able to convert the object into a json and store it in the hash, and similarly when I fetch the json from redis, it can be automatically converted into the corresponding object.

### Additional information

Full code 👇
``

package org.redisson.example.collections;

import lombok.Getter;
import lombok.Setter;
import org.redisson.Redisson;
import org.redisson.api.RMap;
import org.redisson.api.RedissonClient;
import org.redisson.client.codec.StringCodec;
import org.redisson.codec.CompositeCodec;
import org.redisson.codec.TypedJsonJacksonCodec;
import org.redisson.config.Config;

import java.util.List;

public class RMapErrorDemo {
    static final String MemberKey = "members";
    static final CompositeCodec codec = new CompositeCodec(StringCodec.INSTANCE, new TypedJsonJacksonCodec(Member.class));

    public static void main(String[] args) {
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379");
        RedissonClient redissonClient = Redisson.create(config);

        // create members
        List<Member> members = List.of(
                new Member("张三", "zhangsan", List.of(new Department("1", "技朧部"))),
                new Member("李四", "lisi", List.of(new Department("2", "产品部"))),
                new Member("王五", "wangwu", List.of(new Department("3", "市场部"))),
                new Member("赵六", "zhaoliu", List.of(new Department("4", "运营部"))),
                new Member("孙七", "sunqi", List.of(new Department("5", "财务部")))
        );

        saveMember2Redis(redissonClient, members);

        // get member
        Member member = getMemberByName(redissonClient, "张三");

    }

    public static void saveMember2Redis(RedissonClient redissonClient, List<Member> members) {
        RMap<String, Member> map = redissonClient.getMap(MemberKey, codec);
        for (Member member : members) {
            map.put(member.getName(), member);
        }
    }

    public static Member getMemberByName(RedissonClient redissonClient, String name) {

        RMap<String, Member> map = redissonClient.getMap(MemberKey, codec);

        return map.get(name);
    }
}

@Getter
@Setter
class Member {
    private String name;

    private String alias_name;

    private List<Department> depts;

    public Member(String name, String aliaName, List<Department> depts) {
        this.name = name;
        this.alias_name = aliaName;
        this.depts =  depts;
    }
}

@Getter
@Setter
class Department {
    private String id;

    private String name;

    public Department(String number, String s) {
        this.id = number;
        this.name = s;
    }
}

``

**Comment by YJ2CS** [comment]
I had a similar problem, which I discovered while using a certain project scaffolding. After debugging, I found a situation similar to yours.

And strangely enough, it works fine in the test environment of spring boot, while in the non-test environment, it requires me to specify the codec manually to fix it.

 Anyway, here's my solution:

(The key to solving the problem here is to manually specify the TypeReference)

When I setMap, I don't need to specify the codec manually:

```java
   /**
     * 往Hash中存入数据
     *
     * @param key   Redis键
     * @param hKey  Hash键
     * @param value 值
     */
    public static <T> void setCacheMapValue(final String key, final String hKey, final T value) {
        RMap<String, T> rMap = CLIENT.getMap(key);
        rMap.put(hKey, value);
    }
```
When I getMap, I need to manually specify the codec.

```java
 /**
     * 获得缓存Map的key列表
     *
     * @param key 缓存的键值
     * @return key列表
     */
    public static <T> Set<String> getCacheMapKeySet(final TypeReference<T> typeReference, final String key) {
        RMap<String, T> rMap = CLIENT.getMap(key, new TypedJsonJacksonCodec(typeReference, ObjectMapperSingleton.OBJECT_MAPPER));
        return rMap.keySet();
    }

/**
     * 获取多个Hash中的数据
     *
     * @param key   Redis键
     * @param hKeys Hash键集合
     * @return Hash对象集合
     */
    public static <K, V> Map<K, V> getMultiCacheMapValue(final TypeReference<K> kTypeReference, final TypeReference<V> vTypeReference, final String key, final Set<K> hKeys) {
        RMap<K, V> rMap = CLIENT.getMap(key, new TypedJsonJacksonCodec(kTypeReference, vTypeReference, ObjectMapperSingleton.OBJECT_MAPPER));
        return rMap.getAll(hKeys);
    }
```

Similarly, corresponding to RList, there is a similar operation:

```java
    /**
     * 缓存List数据
     *
     * @param key      缓存的键值
     * @param dataList 待缓存的List数据
     * @return 缓存的对象
     */
    public static <T> boolean setCacheList(final String key, final List<T> dataList) {
        RList<T> rList = CLIENT.getList(key);
        return rList.addAll(dataList);
    }


    /**
     * 获得缓存的list对象
     *
     * @param key 缓存的键值
     * @return 缓存键值对应的数据
     */
    public static <T> List<T> getCacheList(final TypeReference<T> typeReference, final String key) {
        RList<T> rList = CLIENT.getList(key, new TypedJsonJacksonCodec(typeReference, ObjectMapperSingleton.OBJECT_MAPPER));
        return rList.readAll();
    }
```

Here's my configuration, which I'm posting just to show the potential problem, which may be a problem with my configuration items

there are so many possible sources of problems, for example, I'm actually mixing kotlin and java. I have no idea what the problem is.


```java
   @Bean
    public RedissonAutoConfigurationCustomizer redissonCustomizer() {
        return config -> {


            // 这里用的 TypedJsonJacksonCodec ， 在序列化和反序列时，都不包含 @class
            // https://github.com/redisson/redisson/issues/4280
            TypedJsonJacksonCodec jsonCodec = new TypedJsonJacksonCodec(Object.class, String.class, Object.class, ObjectMapperSingleton.OBJECT_MAPPER);
            // 组合序列化 key 使用 String 内容使用通用 json 格式
            CompositeCodec codec = new CompositeCodec(StringCodec.INSTANCE, jsonCodec, jsonCodec);
            config.setThreads(redissonProperties.getThreads())
                .setNettyThreads(redissonProperties.getNettyThreads())
                // 缓存 Lua 脚本 减少网络传输(redisson 大部分的功能都是基于 Lua 脚本实现)
                .setUseScriptCache(true)
                .setCodec(codec)
                // https://github.com/redisson/redisson/issues/4603 反序列化问题
                .setUseThreadClassLoader(false);
            if (SpringUtils.isVirtual()) {
                config.setNettyExecutor(new VirtualThreadTaskExecutor("redisson-"));
            }
            RedissonProperties.SingleServerConfig singleServerConfig = redissonProperties.getSingleServerConfig();
            if (ObjectUtil.isNotNull(singleServerConfig)) {
                // 使用单机模式
                config.useSingleServer()
                    //设置redis key前缀
                    .setNameMapper(new KeyPrefixHandler(redissonProperties.getKeyPrefix()))
                    .setTimeout(singleServerConfig.getTimeout())
                    .setClientName(singleServerConfig.getClientName())
                    .setIdleConnectionTimeout(singleServerConfig.getIdleConnectionTimeout())
                    .setSubscriptionConnectionPoolSize(singleServerConfig.getSubscriptionConnectionPoolSize())
                    .setConnectionMinimumIdleSize(singleServerConfig.getConnectionMinimumIdleSize())
                    .setConnectionPoolSize(singleServerConfig.getConnectionPoolSize());
            }
            // 集群配置方式 参考下方注释
            RedissonProperties.ClusterServersConfig clusterServersConfig = redissonProperties.getClusterServersConfig();
            if (ObjectUtil.isNotNull(clusterServersConfig)) {
                config.useClusterServers()
                    //设置redis key前缀
                    .setNameMapper(new KeyPrefixHandler(redissonProperties.getKeyPrefix()))
                    .setTimeout(clusterServersConfig.getTimeout())
                    .setClientName(clusterServersConfig.getClientName())
                    .setIdleConnectionTimeout(clusterServersConfig.getIdleConnectionTimeout())
                    .setSubscriptionConnectionPoolSize(clusterServersConfig.getSubscriptionConnectionPoolSize())
                    .setMasterConnectionMinimumIdleSize(clusterServersConfig.getMasterConnectionMinimumIdleSize())
                    .setMasterConnectionPoolSize(clusterServersConfig.getMasterConnectionPoolSize())
                    .setSlaveConnectionMinimumIdleSize(clusterServersConfig.getSlaveConnectionMinimumIdleSize())
                    .setSlaveConnectionPoolSize(clusterServersConfig.getSlaveConnectionPoolSize())
                    .setReadMode(clusterServersConfig.getReadMode())
                    .setSubscriptionMode(clusterServersConfig.getSubscriptionMode());
            }
            log.info("初始化 redis 配置");
        };
    }
```

**Comment by sanshi2018** [comment]
> I had a similar problem, which I discovered while using a certain project scaffolding. After debugging, I found a situation similar to yours.
> 
> And strangely enough, it works fine in the test environment of spring boot, while in the non-test environment, it requires me to specify the codec manually to fix it.
> 
> Anyway, here's my solution:
> 
> (The key to solving the problem here is to manually specify the TypeReference)
> 
> When I setMap, I don't need to specify the codec manually:
> 
> ```java
>    /**
>      * 往Hash中存入数据
>      *
>      * @param key   Redis键
>      * @param hKey  Hash键
>      * @param value 值
>      */
>     public static <T> void setCacheMapValue(final String key, final String hKey, final T value) {
>         RMap<String, T> rMap = CLIENT.getMap(key);
>         rMap.put(hKey, value);
>     }
> ```
> 
> When I getMap, I need to manually specify the codec.
> 
> ```java
>     /**
>      * 获取Hash中的数据
>      *
>      * @param key  Redis键
>      * @param hKey Hash键
>      * @return Hash中的对象
>      */
>     public static <T> T getCacheMapValue(final TypeReference<T> typeReference, final String key, final String hKey) {
>         TypeReference stringTypeReference = new TypeReference<String>() {
>         };
>         RMap<String, T> rMap = CLIENT.getMap(key, new TypedJsonJacksonCodec(stringTypeReference, typeReference, ObjectMapperSingleton.OBJECT_MAPPER));
>         return rMap.get(hKey);
>     }
> 
> /**
>      * 获取多个Hash中的数据
>      *
>      * @param key   Redis键
>      * @param hKeys Hash键集合
>      * @return Hash对象集合
>      */
>     public static <K, V> Map<K, V> getMultiCacheMapValue(final TypeReference<K> kTypeReference, final TypeReference<V> vTypeReference, final String key, final Set<K> hKeys) {
>         RMap<K, V> rMap = CLIENT.getMap(key, new TypedJsonJacksonCodec(kTypeReference, vTypeReference, ObjectMapperSingleton.OBJECT_MAPPER));
>         return rMap.getAll(hKeys);
>     }
> ```
> 
> Similarly, corresponding to RList, there is a similar operation:
> 
> ```java
>     /**
>      * 缓存List数据
>      *
>      * @param key      缓存的键值
>      * @param dataList 待缓存的List数据
>      * @return 缓存的对象
>      */
>     public static <T> boolean setCacheList(final String key, final List<T> dataList) {
>         RList<T> rList = CLIENT.getList(key);
>         return rList.addAll(dataList);
>     }
> 
> 
>     /**
>      * 获得缓存的list对象
>      *
>      * @param key 缓存的键值
>      * @return 缓存键值对应的数据
>      */
>     public static <T> List<T> getCacheList(final TypeReference<T> typeReference, final String key) {
>         RList<T> rList = CLIENT.getList(key, new TypedJsonJacksonCodec(typeReference, ObjectMapperSingleton.OBJECT_MAPPER));
>         return rList.readAll();
>     }
> ```
> 
> Here's my configuration, which I'm posting just to show the potential problem, which may be a problem with my configuration items
> 
> there are so many possible sources of problems, for example, I'm actually mixing kotlin and java. I have no idea what the problem is.
> 
> ```java
>    @Bean
>     public RedissonAutoConfigurationCustomizer redissonCustomizer() {
>         return config -> {
> 
> 
>             // 这里用的 TypedJsonJacksonCodec ， 在序列化和反序列时，都不包含 @class
>             // https://github.com/redisson/redisson/issues/4280
>             TypedJsonJacksonCodec jsonCodec = new TypedJsonJacksonCodec(Object.class, String.class, Object.class, ObjectMapperSingleton.OBJECT_MAPPER);
>             // 组合序列化 key 使用 String 内容使用通用 json 格式
>             CompositeCodec codec = new CompositeCodec(StringCodec.INSTANCE, jsonCodec, jsonCodec);
>             config.setThreads(redissonProperties.getThreads())
>                 .setNettyThreads(redissonProperties.getNettyThreads())
>                 // 缓存 Lua 脚本 减少网络传输(redisson 大部分的功能都是基于 Lua 脚本实现)
>                 .setUseScriptCache(true)
>                 .setCodec(codec)
>                 // https://github.com/redisson/redisson/issues/4603 反序列化问题
>                 .setUseThreadClassLoader(false);
>             if (SpringUtils.isVirtual()) {
>                 config.setNettyExecutor(new VirtualThreadTaskExecutor("redisson-"));
>             }
>             RedissonProperties.SingleServerConfig singleServerConfig = redissonProperties.getSingleServerConfig();
>             if (ObjectUtil.isNotNull(singleServerConfig)) {
>                 // 使用单机模式
>                 config.useSingleServer()
>                     //设置redis key前缀
>                     .setNameMapper(new KeyPrefixHandler(redissonProperties.getKeyPrefix()))
>                     .setTimeout(singleServerConfig.getTimeout())
>                     .setClientName(singleServerConfig.getClientName())
>                     .setIdleConnectionTimeout(singleServerConfig.getIdleConnectionTimeout())
>                     .setSubscriptionConnectionPoolSize(singleServerConfig.getSubscriptionConnectionPoolSize())
>                     .setConnectionMinimumIdleSize(singleServerConfig.getConnectionMinimumIdleSize())
>                     .setConnectionPoolSize(singleServerConfig.getConnectionPoolSize());
>             }
>             // 集群配置方式 参考下方注释
>             RedissonProperties.ClusterServersConfig clusterServersConfig = redissonProperties.getClusterServersConfig();
>             if (ObjectUtil.isNotNull(clusterServersConfig)) {
>                 config.useClusterServers()
>                     //设置redis key前缀
>                     .setNameMapper(new KeyPrefixHandler(redissonProperties.getKeyPrefix()))
>                     .setTimeout(clusterServersConfig.getTimeout())
>                     .setClientName(clusterServersConfig.getClientName())
>                     .setIdleConnectionTimeout(clusterServersConfig.getIdleConnectionTimeout())
>                     .setSubscriptionConnectionPoolSize(clusterServersConfig.getSubscriptionConnectionPoolSize())
>                     .setMasterConnectionMinimumIdleSize(clusterServersConfig.getMasterConnectionMinimumIdleSize())
>                     .setMasterConnectionPoolSize(clusterServersConfig.getMasterConnectionPoolSize())
>                     .setSlaveConnectionMinimumIdleSize(clusterServersConfig.getSlaveConnectionMinimumIdleSize())
>                     .setSlaveConnectionPoolSize(clusterServersConfig.getSlaveConnectionPoolSize())
>                     .setReadMode(clusterServersConfig.getReadMode())
>                     .setSubscriptionMode(clusterServersConfig.getSubscriptionMode());
>             }
>             log.info("初始化 redis 配置");
>         };
>     }
> ```
> 
> There are still some details, for example, there are some cases where I shouldn't have used TypeReference, but I don't have time to try it out at the moment, so let's leave it at that for now. Maybe you can try and modify it on top of mine

@YJ2CS I found other solutions in stackoverflow[https://stackoverflow.com/a/78648290/17070930](url) 
Use `new CompositeCodec(StringCodec.INSTANCE, 
    new TypedJsonJacksonCodec(String.class, Member.class))`  In my spring project, I use him as a bean for other programs to use

**Comment by MukjepScarlet** [comment]
This looks like unspecified deserialization type (class) of JSON object. I've encountered similar cases with non-Redisson libraries like Gson (trying to case Gson's LinkedTreeMap to a DTO type)
