### ISSUE TITLE
redisson connection cannot be restored

### ISSUE THREAD

**Issue by liuqian1990** [redisson/redisson#5975]
When reading and writing redis cluster via redisson, after killing all redis pod nodes via chaos mesh, the connection cannot be restored, and the connection address is the address of the pod before killing

#3795

**ERROR**

```2024-06-20 07:55:41.205 - Redis 写入操作失败: Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=7164, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1332437931 [redisClient=[addr=redis://10.4.34.123:6379], channel=[id: 0xf3c6df37, L:/10.4.34.113:50576 ! R:10.4.34.123/10.4.34.123:6379], currentCommand=null, usage=1], command: (SET), params: [key47806, PooledUnsafeDirectByteBuf(ridx: 0, widx: 21, cap: 256)] after 3 retry attempts
2024-06-20T07:55:41.470Z ERROR 1 --- [redis] [sson-netty-2-32] o.r.cluster.ClusterConnectionManager : Can't update cluster state
io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: 10.4.18.36/10.4.18.36:6379
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263) ~[netty-transport-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar!/:4.1.110.Final]
at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]```

[redis-debug.txt](https://github.com/user-attachments/files/15923589/redis-debug.txt)

**Comment by mrniko** [comment]
Can you share Redisson logs with `debug` logging level for `org.redisson` package?

**Comment by liuqian1990** [comment]
redssion  3.16.5

I found the reason. I passed in two hosts, but there was a test that only allowed one.

After all pods are killed, this code will throw the above error
```        
config.useClusterServers()
                .addNodeAddress("redis://woo-redis-cluster-leader:6379", "redis://woo-redis-cluster-follower:6379")
                .setScanInterval(2000); 
```

After all pods are killed,This will automatically restore
```
        config.useClusterServers()
                .addNodeAddress("redis://woo-redis-cluster-leader:6379")
                .setScanInterval(2000); 
```

Because of this, I wrote two kubernetes services, which caused configEndpointHostName to be empty。This leads to the assumption that the network is partitioned.
```
                if (cfg.getNodeAddresses().size() == 1 && !addr.isIP()) {
                    configEndpointHostName = addr.getHost();
                }

   private void scheduleClusterChangeCheck(ClusterServersConfig cfg) {
        monitorFuture = group.schedule(new Runnable() {
            @Override
            public void run() {
                if **(configEndpointHostName != null)** {
                    String address = cfg.getNodeAddresses().iterator().next();
                    RedisURI uri = new RedisURI(address);
                    AddressResolver<InetSocketAddress> resolver = resolverGroup.getResolver(getGroup().next());
                    Future<List<InetSocketAddress>> allNodes = resolver.resolveAll(InetSocketAddress.createUnresolved(uri.getHost(), uri.getPort()));
                    allNodes.addListener(new FutureListener<List<InetSocketAddress>>() {
                        @Override
```

**Comment by mrniko** [comment]
> I found the reason. I passed in two hosts, but there was a test that only allowed one.

have you resolved the issue?

**Comment by liuqian1990** [comment]
Solved, but I don't understand why it is designed this way.

**Comment by mrniko** [comment]
Can you try 3.32.0 version as well? It has cluster failover handling fix
