### ISSUE TITLE
Password is printed to log when failing to authenticate as plaintext. Why isn't it being masked?

### ISSUE THREAD

**Issue by oran5456** [redisson/redisson#5984]
While try to authenticate using wrong password, the password is being printed to log as plain text since it is part of the exception thrown by reddison.

I would like to be able to print the log so we have details on the error, but to have the password masked.

org.redisson.client.RedisWrongPasswordException: WRONGPASS invalid username-password pair or user is disabled.. channel: [id: 0x8c4e60d5, L:/10.30.142.96:52148 - R:clustercfg.realtime-metadata.k.u.c.a.c.2.1.1.u.concurrent.CompletableFuture@4941ae91[Not completed, 2 dependents], command=(AUTH), params=[**password was shown here as plain text**], codec=null]
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:398)
	at o.r.c.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at o.r.c.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at i.n.h.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at i.n.h.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at i.n.h.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
	at i.n.h.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at i.n.h.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at i.n.h.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at i.n.c.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at i.n.c.n.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at i.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at i.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at i.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at i.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at i.n.u.c.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at i.n.u.c.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Wrapped by: java.util.concurrent.ExecutionException: org.redisson.client.RedisWrongPasswordException: WRONGPASS invalid username-password pair or user is disabled.. channel: [id: 0x8c4e60d5, L:/10.30.142.96:52148 - R:clustercfg.realtime-metadata.k.u.c.a.c.2.1.1.u.concurrent.CompletableFuture@4941ae91[Not completed, 2 dependents], command=(AUTH), params=[**password was shown here as plain text**], codec=null]
	at j.b.u.c.CompletableFuture.reportGet(CompletableFuture.java:395)
	at j.b.u.c.CompletableFuture.get(CompletableFuture.java:2028)
	at o.r.c.ClusterConnectionManager.doConnect(ClusterConnectionManager.java:96)
	... 100 common frames omitted
Wrapped by: org.redisson.client.RedisConnectionException: Can't connect to servers!
	at o.r.c.ClusterConnectionManager.doConnect(ClusterConnectionManager.java:159)
	at o.r.c.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:196)
	at o.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:220)
	at org.redisson.Redisson.<init>(Redisson.java:71)
	at org.redisson.Redisson.create(Redisson.java:116)

**Comment by mrniko** [comment]
Which Redisson version?

**Comment by oran5456** [comment]
> Which Redisson version?

3.27.2

**Comment by mrniko** [comment]
Fixed. Thanks for report
