### ISSUE TITLE
Lambda task not work  in RExecutorService

### ISSUE THREAD

**Issue by helensway** [redisson/redisson#6004]
redisson version is 3.28.0 and redis version is 6.0.9 when i run 

 rExecutorService.submit((Runnable & Serializable) () -> {
                logger.info("test-1-sleep-" + j);
            });
it's always report  Error ,how can i deal with this  thank you.

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
	at org.redisson.executor.RedissonExecutorRemoteService.invokeMethod(RedissonExecutorRemoteService.java:106) ~[redisson-3.28.0.jar:3.28.0]
	at org.redisson.RedissonRemoteService.lambda$executeMethod$14(RedissonRemoteService.java:448) [redisson-3.28.0.jar:3.28.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_221]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]
Caused by: java.lang.IllegalStateException: Unable to initialize codec with ClassLoader parameter
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:311) ~[redisson-3.28.0.jar:3.28.0]
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:329) ~[redisson-3.28.0.jar:3.28.0]
	at org.redisson.executor.TasksRunnerService.executeRunnable(TasksRunnerService.java:349) ~[redisson-3.28.0.jar:3.28.0]
	... 11 common frames omitted
Caused by: java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1736) ~[na:1.8.0_221]
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1266) ~[na:1.8.0_221]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2078) ~[na:1.8.0_221]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[na:1.8.0_221]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~[na:1.8.0_221]
	at org.redisson.executor.TasksRunnerService.decode(TasksRunnerService.java:293) ~[redisson-3.28.0.jar:3.28.0]
	... 13 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230) ~[na:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1260) ~[na:1.8.0_221]
	... 17 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
	at com.redisson.a1分布式执行服务.Test2Controller2.$deserializeLambda$(Test2Controller2.java:27) ~[classes/:na]
	... 27 common frames omitted

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version and KryoCodec used as a codec
