### ISSUE TITLE
org.jboss.marshalling not incuded with latest redisson version ?

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#6012]
### Redis version

7.x

### Redisson version

3.32.0

### Redisson configuration

singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 2000
  timeout: 2000
  retryAttempts: 1
  retryInterval: 1500
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://l2-platform-redis:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 200
  database: 0
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.MarshallingCodec> {}

### What is the Expected behavior?

with redisson 3.24.2, no probleme starting a redissonclient with this codec, but with the latest version of redisson
it failed with :
Caused by: java.lang.NoClassDefFoundError: org/jboss/marshalling/ClassResolver
        at java.lang.Class.forName0(Unknown Source)
        at java.lang.Class.forName(Unknown Source)
        at com.fasterxml.jackson.databind.type.TypeFactory.classForName(TypeFactory.java:383)
        at com.fasterxml.jackson.databind.type.TypeFactory.findClass(TypeFactory.java:365)
        at com.fasterxml.jackson.databind.DatabindContext.resolveAndValidateSubType(DatabindContext.java:241)
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:75)
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:69)
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._deserializeWithNativeTypeId(TypeDeserializerBase.java:267)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:106)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
        at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:159)
        at org.redisson.config.Config.fromYAML(Config.java:681)
        ... 11 frames truncated
        ... 174 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jboss.marshalling.ClassResolver
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:150)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 205 common frames omitted

### What is the Actual behavior?

Caused by: java.lang.NoClassDefFoundError: org/jboss/marshalling/ClassResolver
        at java.lang.Class.forName0(Unknown Source)
        at java.lang.Class.forName(Unknown Source)
        at com.fasterxml.jackson.databind.type.TypeFactory.classForName(TypeFactory.java:383)
        at com.fasterxml.jackson.databind.type.TypeFactory.findClass(TypeFactory.java:365)
        at com.fasterxml.jackson.databind.DatabindContext.resolveAndValidateSubType(DatabindContext.java:241)
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:75)
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:69)
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._deserializeWithNativeTypeId(TypeDeserializerBase.java:267)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:106)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
        at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:159)
        at org.redisson.config.Config.fromYAML(Config.java:681)
        ... 11 frames truncated
        ... 174 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jboss.marshalling.ClassResolver
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:150)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 205 common frames omitted

**Comment by CyrilDevOps** [comment]
Looking at redisson pom in maven, until 3.28 :
<dependency>
<groupId>org.jboss.marshalling</groupId>
<artifactId>jboss-marshalling</artifactId>
<version>2.0.11.Final</version>

</dependency>
<dependency>
<groupId>org.jboss.marshalling</groupId>
<artifactId>jboss-marshalling-river</artifactId>
<version>2.0.11.Final</version>

</dependency>

from 3.29 :
 <dependency>
<groupId>org.jboss.marshalling</groupId>
<artifactId>jboss-marshalling</artifactId>
<version>2.0.11.Final</version>
<scope>provided</scope>
<optional>true</optional>
</dependency>
<dependency>
<groupId>org.jboss.marshalling</groupId>
<artifactId>jboss-marshalling-river</artifactId>
<version>2.0.11.Final</version>
<scope>provided</scope>
<optional>true</optional>
</dependency>

<scope>provided</scope>
<optional>true</optional>
are no longer commented. But can't find anything in changelog about this.

**Comment by mrniko** [comment]
It's an optional dependency since the codec was deprecated

**Comment by CyrilDevOps** [comment]
Is there an easy way to switch to other codec ?
If I change the config in my redisson yaml file, my code will not be able to read existing data in redis ?

**Comment by mrniko** [comment]
Unfortunately, no. You need to migrate the data.
