### ISSUE TITLE
Redis Sentintel mode: PubSub stops working after Redis restart

### ISSUE THREAD

**Issue by olessio** [redisson/redisson#6026]
### Redis version

6.2.13

### Redisson version

3.32.0, 3.27.2

### Redisson configuration

SentinelServersConfig

### What is the Expected behavior?

After Redis is up and Redisson has been reconnected, PubSub must keep working.

### What is the Actual behavior?

**Problem 1**
Redisson is failing to create new topic listener
```
org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 7500ms. Try to increase 'subscriptionTimeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$17(PublishSubscribeService.java:413)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Problem 2**
Existing subscriptions are not re-established: Redis command "PUBSUB CHANNELS" returns empty list even though before disconnect there were multiple channels.

**Problem 3**
(I assume it is a consequence of the 1st Problem): RedissonLock stuck at
```
    @Override
    public boolean tryLock(long waitTime, long leaseTime, TimeUnit unit) throws InterruptedException {
       ....
        CompletableFuture<RedissonLockEntry> subscribeFuture = subscribe(threadId);
        try {
            subscribeFuture.get(time, TimeUnit.MILLISECONDS);
```

After service restart, everything works as expected

**Comment by sr11235** [comment]
I am encountering the same issue when failover testing our HA setup on Redis Cloud with Redisson 3.29.0. Redisson is configured to run in single-server mode, as Redis Enterprise hides the clustered topology of the DBs.

**Comment by mrniko** [comment]
Should be fixed in https://github.com/redisson/redisson/pull/6047. Can you try 3.34.0 version?

**Comment by sr11235** [comment]
Could reproduce the issue with a Redis Sentinel setup with version 3.29.0 but not with 3.34.1. Will try a Redis Cloud failover test soon

**Comment by sr11235** [comment]
Issue did not re-appear on new failover test with redisson 3.34.1. Seems to be fixed. Thank you!

**Comment by ninja-** [comment]
@mrniko it seems to be broken again as of org.redisson:redisson:3.37.0 :(

I have a simple one pod Redis.

every time after I do

```
while true; do kubectl delete pod -n redis redis-master-0; sleep 0.1; done
```

let it run for a couple seconds, then stop it, let everything recover.

existing subscriptions stop working, and new ones will fail every time with this error until java restart

**Comment by ninja-** [comment]
the only stacktrace aside from "Query failed with NXDOMAIN" until Redis is back is

```
io.netty.channel.StacklessClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source) ~[xx.jar:?]
```

coming as an exception from one of Reactive tasks that attempts to acquire the lock.

Not sure if that's a specific code path where Redisson forgot to perform unlocking, probably it's irrelevant.

**Comment by ninja-** [comment]
another weird glitch caused by this bug, is that when attempting to get an entirely new lock(unrelated to pubsub) post-restart, the first attempt will always result in StacklessClosedChannelException, and the next attempt will succeed - like some code that removes out-of-date connections is not running

**Comment by ninja-** [comment]
I think one of the code paths across https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java still avoids properly calling unlock :thinking:

**Comment by mrniko** [comment]
@Mortega5 which Redisson version?

**Comment by Mortega5** [comment]
Redisson 3.44.0

**Comment by mrniko** [comment]
merged
