### ISSUE TITLE
"RedissonShutdownException: Redisson is shutdown" error during graceful shutdown (deployment)

### ISSUE THREAD

**Issue by leflamm** [redisson/redisson#6029]
### Redis version

7.0.7

### Redisson version

3.32.0

### Redisson configuration

Default against AWS Elasticache, Cluster Mode disabled

### What is the Expected behavior?

No exception

### What is the Actual behavior?

During deployments of two-instance services using Redisson - when the old instances are shut down - we sometimes see different errors on the instance that either has the lock or doesn't have the lock. So far we are not able to reproduce it during deployments of single-instance services. Deployment includes graceful shutdown which includes a `lock.unlock()`. We do not see any exceptions related to a failing `unlock` call.

This sometimes happens on the instance that has the lock:
```
org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:658)
	at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:601)
	at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:449)
	at org.redisson.command.CommandAsyncService.syncedEval(CommandAsyncService.java:992)
	at org.redisson.RedissonBaseLock.evalWriteSyncedAsync(RedissonBaseLock.java:214)
	at org.redisson.RedissonBaseLock.renewExpirationAsync(RedissonBaseLock.java:184)
	at org.redisson.RedissonBaseLock$1.run(RedissonBaseLock.java:145)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:713)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:701)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:788)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:501)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

This sometimes happens on the instance that does not have the lock:
```
org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:658)
	at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:601)
	at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:449)
	at org.redisson.command.CommandAsyncService.syncedEval(CommandAsyncService.java:992)
	at org.redisson.RedissonBaseLock.evalWriteSyncedAsync(RedissonBaseLock.java:214)
	at org.redisson.RedissonLock.tryLockInnerAsync(RedissonLock.java:219)
	at org.redisson.RedissonLock.tryAcquireAsync(RedissonLock.java:193)
	at org.redisson.RedissonLock.lambda$tryAcquireAsync0$0(RedissonLock.java:160)
	at org.redisson.connection.ServiceManager.execute(ServiceManager.java:514)
	at org.redisson.connection.ServiceManager.execute(ServiceManager.java:509)
	at org.redisson.RedissonLock.tryAcquireAsync0(RedissonLock.java:160)
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:156)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:278)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:320)
	at org.factcast.factus.redis.AbstractRedisProjection.acquireWriteToken(AbstractRedisProjection.java:107)
        ...
```

FYI: this is the `acquireWriteToken` method mentioned in the stack trace. [RedisWriterToken](https://github.com/factcast/factcast/blob/master/factcast-factus-redis/src/main/java/org/factcast/factus/redis/RedisWriterToken.java) is an `AutoCloseable` which includes an `unlock()` call during `close()`. `maxWait` is set to 5 minutes.

```java
  @Override
  public WriterToken acquireWriteToken(@NonNull Duration maxWait) {
    try {
      if (lock.tryLock(maxWait.toMillis(), TimeUnit.MILLISECONDS))
        return new RedisWriterToken(redisson, lock);
    } catch (InterruptedException e) {
      // assume lock unsuccessful
    }
    return null;
  }

```

### Additional information

**Had no such problems with <=3.27.1.** 

Started to see issues with 3.27.2 (with an NPE as cause). Seeing this issue's behavior (or very similar behavior) since 3.28.0 up until 3.32.0

With 3.32.0 errors seem to occur less frequent compared to 3.31.0.

**Comment by mrniko** [comment]
this error may happen only when RedissonClient.shutdown method is called

**Comment by leflamm** [comment]
Yes, this happens while the application (old instance during deployment) is shut down. IMHO the exceptions are unexpected because nobody can react to them anymore (instance shutting down). 

This produces errors and triggers alarms and developers "become error-blind".

**Comment by lcssimonini** [comment]
I currently have the same problem in prod with basically the same setup. Are there any updates regarding this issue?

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by lcssimonini** [comment]
Thank you @mrniko you are the best.
