### ISSUE TITLE
redisson 3.32.0 let my services CPU upto 100%

### ISSUE THREAD

**Issue by RyQcan** [redisson/redisson#6043]
### Redis version

spring-data-redis 2.7.17

### Redisson version

3.32.0

### Redisson configuration

  redis:
    cluster:
      nodes: 
      max-redirects: 1
    port: 6379
    password: 
    lettuce:
      pool:
        min-idle: 8
        max-idle: 16
        max-active: 32
        test-on-borrow: true
    timeout: 3000

### What is the Expected behavior?

no CPU 100%

### What is the Actual behavior?

sometimes one node's CPU upto 100%

### Additional information

2024-07-20 00:38:16,800 [1;31mERROR redisson-timer-4-1[m o.r.c.h.PingConnectionHandler--[] {} Unable to send PING command over channel: [id: 0xb3d83e3b, L:/172.31.17.70:38964 - R:172.31.69.154/172.31.69.154:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.31.69.154:6379]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
> sometimes one node's CPU upto 100%

Did you profile it? CPU overload causes Redisson timeouts since CPU is busy
