### ISSUE TITLE
ClusterConnectionManager NPE

### ISSUE THREAD

**Issue by sclasen** [redisson/redisson#6048]
### Redis version

6.x

### Redisson version

3.33.0

### Redisson configuration

Cluster

### What is the Expected behavior?

ClusterConnectionMaager.checkSlotsMigration should not throw NPE

### What is the Actual behavior?

ClusterConnectionMangter throws NPEs

### Additional information

```java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.redisson.cluster.ClusterConnectionManager.checkSlotsMigration(ClusterConnectionManager.java:757)
	at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$18(ClusterConnectionManager.java:508)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$19(ClusterConnectionManager.java:505)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:530)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:524)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:444)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:218)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:146)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by mrniko** [comment]
Can you share redisson log in debug logging level?

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by mrniko** [comment]
How many master nodes is used in Cluster?

**Comment by sclasen** [comment]
typically 7

**Comment by nfauzia** [comment]
Wont the fix just suppress the symptoms?

Right before the NPE started, all 3 master nodes were removed. Here are some debug logs from that time.

1:59:03.862 PM    { [-]
   logNameSource: org.redisson.cluster.ClusterConnectionManager
   message: 16384 slots removed
   timestamp: 1721743143862
}


1:59:03.862 PM    { [-]
   logNameSource: org.redisson.cluster.ClusterConnectionManager
   message: 10.59.140.195/10.59.140.195:12049 master and related slaves:  removed
   timestamp: 1721743143862
}


1:59:03.860 PM    { [-]
   logNameSource: org.redisson.cluster.ClusterConnectionManager
   message: 10.58.56.26/10.58.56.26:12049 master and related slaves:  removed
   timestamp: 1721743143860
}

1:59:03.858 PM    { [-]
   logNameSource: org.redisson.cluster.ClusterConnectionManager
   message: 10.58.139.195/10.58.139.195:12049 master and related slaves:  removed
   timestamp: 1721743143858
}

**Comment by nfauzia** [comment]
Also, in another environment, we saw a different NPE message

`java.lang.NullPointerException: Cannot invoke "org.redisson.connection.MasterSlaveEntry.slaveDown(org.redisson.misc.RedisURI, org.redisson.connection.ClientConnectionsEntry$FreezeReason)" because "entry" is null at org.redisson.cluster.ClusterConnectionManager.addRemoveSlaves(ClusterConnectionManager.java:595) at org.redisson.cluster.ClusterConnectionManager.checkSlaveNodesChange(ClusterConnectionManager.java:533) at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$16(ClusterConnectionManager.java:503) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) at org.redisson.connection.ConnectionsHolder.connectedSuccessful(ConnectionsHolder.java:195) at org.redisson.connection.ConnectionsHolder.lambda$createConnection$5(ConnectionsHolder.java:190) at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) at org.redisson.client.RedisClient$1$1.run(RedisClient.java:285) at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:840)`


**Followed by a bunch of these**
`added slaves detected for master redis://10.109.1.42:12049. current slaves [] last slaves [redis://10.108.173.204:12049] last failed slaves []`

**Comment by mrniko** [comment]
@nfauzia 

https://github.com/redisson/redisson/issues/6061#issuecomment-2254130493

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/6061

**Comment by sarah-lui** [comment]
@mrniko Do you think [this](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java#L722-L726) could be an issue as well? @nfauzia posted some logs above where all 3 of our master nodes were removed at once, and afterward we only saw 2 of them added back in:

```
1:59:10.182 PM {
   logNameSource: org.redisson.cluster.ClusterConnectionManager
   message: master: redis://10.58.139.195:12049 added for slot ranges: [[0-5461]]
   timestamp: 1721743150182
}

1:59:10.252 PM {
   logNameSource: org.redisson.cluster.ClusterConnectionManager
   message: master: redis://10.58.56.26:12049 added for slot ranges: [[5462-10922]]
   timestamp: 1721743150252
}
```

`10.59.140.195:12049` was the one removed last and we did not see it added to the topology as a master again until restarting.

**Comment by mrniko** [comment]
@sarah-lui 

> @nfauzia posted some logs above where all 3 of our master nodes were removed at once

This is the same cause.
