### ISSUE TITLE
NPEs Continuing in Redisson Tomcat Logs

### ISSUE THREAD

**Issue by JosephWitthuhnTR** [redisson/redisson#6053]
### Redis version

7.1.0

### Redisson version

3.33.0

### Redisson configuration

Clustered configuration (2 nodes, 2 shards per node).

Redisson Tomcat Session Manager configurations:

ReadMode: MEMORY
UpdateMode: AFTER_REQUEST
BroadcastSessionEvents: true
Threads: 64
Transport Mode: EPOLL
SSL Provider: OPENSSL

We do have a custom keyPrefix
Everything else is default values
Tomcat version: 9.0.86
Java version: 11

### What is the Expected behavior?

No NullPointerExceptions.

### What is the Actual behavior?

After your fix for #5995 , we are seeing WAY FEWER NullPointerExceptions in our logs, but do we continue to see a few. I'm wondering if it is just the same (or a similar?) fix that might be needed in more places.

Example stack traces (these seem to be three patterns we are seeing):

```
org.apache.catalina.connector.Request recycleSessionInfo
WARNING: Exception triggered ending access to session while recycling request
java.lang.IllegalStateException: java.lang.NullPointerException
	at org.redisson.tomcat.RedissonSession.createPutAllMessage(RedissonSession.java:235)
	at org.redisson.tomcat.RedissonSession.endAccess(RedissonSession.java:320)
	at org.apache.catalina.connector.Request.recycleSessionInfo(Request.java:539)
	at org.apache.catalina.connector.Request.recycle(Request.java:499)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:424)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at org.redisson.tomcat.RedissonSession.createPutAllMessage(RedissonSession.java:233)
	... 13 more
```

```
org.apache.catalina.core.StandardHostValve invoke
SEVERE: Exception Processing [/mytestendpoint]
java.lang.NullPointerException
	at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:449)
	at org.redisson.tomcat.RedissonSessionManager.store(RedissonSessionManager.java:431)
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:74)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [MyServlet] in context with path [/myservlets] threw exception
java.lang.NullPointerException
	at org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:132)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:101)
	at com.thomsonreuters.wgs.clear.TrmrFilter.getUserGUID(TrmrFilter.java:228)
	at com.thomsonreuters.wgs.clear.TrmrFilter.doFilter(TrmrFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at com.thomsonreuters.wgs.clear.TrmrApiFilter.doFilter(TrmrApiFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:156)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.redisson.tomcat.UpdateValve.invoke(UpdateValve.java:62)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

We are not aware of any side-effects from these errors, but are noticing them in our logs (primarily when we stress test our system or put it under load).

**Comment by mrniko** [comment]
I think the issue that the session is modified with multiple threads. It's not thread-safe object.
