### ISSUE TITLE
Configure Redis to authentication using IAM authentication in a Quarkus application

### ISSUE THREAD

**Issue by subhanus** [redisson/redisson#6067]
Requirement :
Configure Redis(ElastiCache) with Redisson Library to authentication using IAM authentication in a Quarkus application

How can I initialise the `RedissonClient` Bean in a Quarkus application?
I found a documentation where I can manually create Object of `RedissonClient` with  IAM Credential Provider but that won't be managed by Quarkus.
https://redisson.org/articles/how-to-connect-to-redis-using-elasticache-iam-credential-provider.html

And, I also found a documentation of configuring `RedissonClient` and then Injecting the bean in Quarkus application which is managed by quarkus but i don't find any documentation with combination of both.

I just want to configure the `credentials-resolver` and pass that to the quarkus application as `configuration property` and rest handled by quarkus.

**Comment by mrniko** [comment]
Did you try to define it like below?

`quarkus.redisson.single-server-config.credentials-resolver=com.mycompany.Resolver`

**Comment by subhanus** [comment]
I didn't find any documentation for this. I will try.

**Comment by subhanus** [comment]
@mrniko 
I have cluster server config so I tried with :
`quarkus.redisson.cluster-servers-config.credentials-resolver` who value i gave `com.xxx.xx.xx.RedisIAMAuthCredentialsProvider`

My RedisIAMAuthCredentialsProvider looks like this:
`
@ApplicationScoped
public class RedisIAMAuthCredentialsProvider implements CredentialsResolver {

    private static final LMLogger logger = LMLoggerFactory.getLogger(RedisIAMAuthCredentialsProvider.class);

    private final IAMAuthTokenRequest iamAuthTokenRequest = new IAMAuthTokenRequest(
            Configurations.REDIS_USERNAME.get(),
            Configurations.REDIS_REPLICATION_GROUP_ID.get(),
            Configurations.AWS_REGION.get()
            );
    private final AwsCredentialsProvider awsCredentialsProvider = DefaultCredentialsProvider.create();
    private volatile CompletionStage<Credentials> future;
    private volatile Long lastTime = System.currentTimeMillis();



    @Override
    public CompletionStage<Credentials> resolve(InetSocketAddress address) {
        logger.info("Resolving credentials for elasticache");
        if (System.currentTimeMillis() - lastTime > 900*1000 || future == null) {
            String token = iamAuthTokenRequest.toSignedRequestUri(awsCredentialsProvider.resolveCredentials());
            future = CompletableFuture.completedFuture(new Credentials(Configurations.REDIS_USERNAME.get(), token));
            lastTime = System.currentTimeMillis();
        }
        logger.info("Resolved credentials for elasticache");
        return future;
    }
}
`

And I am getting error in Quarkus startup:
`Caused by: java.lang.RuntimeException: Error injecting org.redisson.api.RedissonClient com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility.redisClient
 at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.doCreate(Unknown Source)
 at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.create(Unknown Source)
 at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.create(Unknown Source)
 at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
 at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
 at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
 at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
 at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
 at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
 at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
 at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.get(Unknown Source)
 at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.get(Unknown Source)
 ... 42 more
Caused by: jakarta.enterprise.inject.CreationException: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class org.redisson.config.CredentialsResolver]: missing type id property 'class' (for POJO property 'credentialsResolver')
 at [Source: (StringReader); line: 7, column: 24] (through reference chain: org.redisson.config.Config["clusterserversconfig"]->org.redisson.config.ClusterServersConfig["credentialsresolver"])
 at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.create(Unknown Source)
 at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.create(Unknown Source)
 at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
 at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
 at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
 at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
 at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
 at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
 at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
 at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.get(Unknown Source)
 at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.get(Unknown Source)
 ... 54 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class org.redisson.config.CredentialsResolver]: missing type id property 'class' (for POJO property 'credentialsResolver')
 at [Source: (StringReader); line: 7, column: 24] (through reference chain: org.redisson.config.Config["clusterserversconfig"]->org.redisson.config.ClusterServersConfig["credentialsresolver"])
 at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
 at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2050)
 at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1622)
 at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307)
 at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:211)
 at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:122)
 at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
 at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
 at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
 at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:161)
 at io.quarkus.redisson.client.runtime.RedissonClientProducer.create(RedissonClientProducer.java:78)
 at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.doCreate(Unknown Source)
 ... 65 more`

**Comment by mrniko** [comment]
Can you share a config file?

**Comment by subhanus** [comment]
The configurations are dynamically resolved and set as System property. So there is no file which as the config.

**Comment by mrniko** [comment]
Fixed

**Comment by subhanus** [comment]
@mrniko The fix will be released in which version?

**Comment by mrniko** [comment]
during this month
