### ISSUE TITLE
RMultimapCacheReactive returns Rx Single instead of Reactor Mono

### ISSUE THREAD

**Issue by kramer** [redisson/redisson#6075]
### Redis version

7.4.0

### Redisson version

3.34.1

### Redisson configuration

Irrelevant

### What is the Expected behavior?

[RMultimapCacheReactive](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/RMultimapCacheReactive.java).expireKey should return `reactor.core.publisher.Mono`

### What is the Actual behavior?

[RMultimapCacheReactive](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/RMultimapCacheReactive.java).expireKey returns `io.reactivex.rxjava3.core.Single`

### Additional information

This fails at runtime if the method is called (so I guess the proxied method is actually correct but the interface is faulty):

```
java.lang.AssertionError: expectation "expectComplete" failed (expected: onComplete(); actual: onError(java.lang.ClassCastException: class reactor.core.publisher.MonoNext cannot be cast to class io.reactivex.rxjava3.core.Single (reactor.core.publisher.MonoNext and io.reactivex.rxjava3.core.Single are in unnamed module of loader 'app')))
	at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
	at reactor.test.MessageFormatter.failPrefix(MessageFormatter.java:104)
	at reactor.test.MessageFormatter.fail(MessageFormatter.java:73)
	at reactor.test.MessageFormatter.failOptional(MessageFormatter.java:88)
	at reactor.test.DefaultStepVerifierBuilder.lambda$expectComplete$4(DefaultStepVerifierBuilder.java:344)
	at reactor.test.DefaultStepVerifierBuilder$SignalEvent.test(DefaultStepVerifierBuilder.java:2289)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSignal(DefaultStepVerifierBuilder.java:1529)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1477)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onError(DefaultStepVerifierBuilder.java:1129)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:880)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:805)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:163)
	at org.redisson.reactive.CommandReactiveService.lambda$reactive$1(CommandReactiveService.java:85)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:648)
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:624)
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:601)
	at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:201)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:530)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:524)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:427)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:218)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:146)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.lang.ClassCastException: class reactor.core.publisher.MonoNext cannot be cast to class io.reactivex.rxjava3.core.Single (reactor.core.publisher.MonoNext and io.reactivex.rxjava3.core.Single are in unnamed module of loader 'app')
		at jdk.proxy2/jdk.proxy2.$Proxy162.expireKey(Unknown Source)
		at com.X.lambda$createMapping$2(CmsNotificationProcessor.java:58)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
		... 44 more
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
