### ISSUE TITLE
Observing "Unable to send PING command over channel" even after upgrading the redisson to 3.26.1

### ISSUE THREAD

**Issue by rpranaykumarreddy** [redisson/redisson#6079]
Using:
implementation ('org.redisson:redisson-spring-boot-starter:3.26.1')

Stack Trace:
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.21.4.20:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by mrniko** [comment]
It's not a "Unable to send PING command over channel" error

**Comment by rpranaykumarreddy** [comment]
> It's not a "Unable to send PING command over channel" error

message : Unable to send PING command over channel: [id: 0x5b59XXXX, L:/1x.2xx.x.x:53xxx - R:1xx.xx.x.xx/1xx.xx.x.xx:xxxx]

**Comment by mrniko** [comment]
can you share full stacktrace?

**Comment by rpranaykumarreddy** [comment]
> can you share a full stacktrace?

"_source": {
    "level_value": 40000,
    "message": "Unable to send PING command over channel: [id: 0x5b59XXXX, L:/XX.XXX.X.X:XXXX - R:XXX.XX.X.XX/XXX.XX.X.XX:XXXX]",
    "level": "ERROR",
    "@timestamp": "2024-08-07T21:13:57.077Z",
    "@version": "1",
    "thread_name": "redisson-timer-4-1",
    "stream": "stdout",
    "stack_trace": "org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.21.4.20:6379]\n\tat org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)\n\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)\n\tat io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)\n\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)\n\tat io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)\n\tat io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n",
    "logger_name": "org.redisson.client.handler.PingConnectionHandler"
  }

**Comment by mrniko** [comment]
Can you share Redisson config?

**Comment by mrniko** [comment]
@chaokunyang

Does Apache Fury handle that?

**Comment by rpranaykumarreddy** [comment]
> Can you share Redisson config?

spring:
  application:
    name: ${name}
    version: ${version}
    title: ${title}
    description: ${description}
    database-prefix:  ${database-prefix}
    distributed-locks:
      providers:
        redisson:
          waitTime: 30s
          leaseTime: 5m

**Comment by mrniko** [comment]
Are you able to reproduce this issue locally? what is the CPU load during these errors?

**Comment by rpranaykumarreddy** [comment]
CPU usage :
cluster-1:
first-uservice - 5.92%
second-uservice - 2.20%
third-uservice - 2.91%
 
cluster-2:
first-uservice - 2.02%

**Comment by yuanxiaohua1** [comment]
I'm having the same problem.

redisson version 3.32.0

Exception stack：
 Unable to send PING command over channel: [id: 0x8a0fdf19, L:/xxx.xxx.xxx.xxx:60808 - R:xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx:6379]]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://xxx.xxx.xxx.xxx:6379]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253) ~[redisson-3.32.0.jar!/:3.32.0]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]

**Comment by mrniko** [comment]
@yuanxiaohua1 

Can you share Redisson logs?

**Comment by yuanxiaohua1** [comment]
Only the preceding stack information is printed for more than 100 times. This exception occurs and the CPU usage increases rapidly.

**Comment by mrniko** [comment]
@yuanxiaohua1 

What is the Redisson config?

**Comment by yuanxiaohua1** [comment]
Basically, the default configuration is used.

```
    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {
        return Redisson.create(redissionConfig());
    }

    @Bean
    public Config redissionConfig() {
        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.useClusterServers();
        clusterServersConfig.setTimeout(timeout);
        clusterServersConfig.setPassword(password);
        for (String addr : clusterProperties.getNodes()) {
            clusterServersConfig.addNodeAddress("redis://" + addr);
        }
        return config;
    }

    @Configuration
    @ConfigurationProperties(prefix = "spring.redis.cluster")
    public static class ClusterConfigurationProperties {
        List<String> nodes;
        int maxRedirects;

        public List<String> getNodes() {
            return nodes;
        }

        public void setNodes(List<String> nodes) {
            this.nodes = nodes;
        }

        public int getMaxRedirects() {
            return maxRedirects;
        }

        public void setMaxRedirects(int maxRedirects) {
            this.maxRedirects = maxRedirects;
        }
    }

```

**Comment by mrq1324** [comment]
> I'm having the same problem.
> 
> redisson version 3.32.0
> 
> CPU utilization spikes： ![image](https://private-user-images.githubusercontent.com/45865534/362520330-9e3300e4-e69f-4a9f-8249-4e0f14c78064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTA1NzgsIm5iZiI6MTcyNzI1MDI3OCwicGF0aCI6Ii80NTg2NTUzNC8zNjI1MjAzMzAtOWUzMzAwZTQtZTY5Zi00YTlmLTgyNDktNGUwZjE0Yzc4MDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA3NDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NWRlYTE4MzMzMDQxYmYyY2QwNWE1MjA1YjZhOTYzMzNmMWJkZjZlM2NhZmU3MTZiMWMzOTI4NmUwYzZlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SU66TouKRGFGjJiTjp2ZmNq1llm3u4HAfKkoE0SefQE)
> 
> ![image](https://private-user-images.githubusercontent.com/45865534/362520613-279132f3-88b9-489a-95fa-3fe520b436c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTA1NzgsIm5iZiI6MTcyNzI1MDI3OCwicGF0aCI6Ii80NTg2NTUzNC8zNjI1MjA2MTMtMjc5MTMyZjMtODhiOS00ODlhLTk1ZmEtM2ZlNTIwYjQzNmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA3NDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTZjNDdmYjMwMzU1NjA0YmExMWUzMTRiOTZmZjIxNDM2OGYwN2Y1MDJiOGU2NmI4M2NkZmZiNDdjMzkxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6XNghc01pKWBxYtkqHNkWD1YtoSFqFYmUHPT18gZu2k)
> 
> Exception stack： Unable to send PING command over channel: [id: 0x8a0fdf19, L:/xxx.xxx.xxx.xxx:60808 - R:xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx:6379]] org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://xxx.xxx.xxx.xxx:6379] at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253) ~[redisson-3.32.0.jar!/:3.32.0] at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final] at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final] at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final] at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final] at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final] at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]

Hello, is your problem solved?

**Comment by RyQcan** [comment]
@mrniko  hi~ is this problem fixed in 3.37.0？

**Comment by mrniko** [comment]
@yuanxiaohua1

It can be connected to https://github.com/redisson/redisson/issues/6153

**Comment by yuanxiaohua1** [comment]
After the version is upgraded to 3.37.0, the CPU usage still rises to 100.
![image](https://github.com/user-attachments/assets/7a6ee0fc-a650-4f02-8d8c-ee1cc86a60ef)
![image](https://github.com/user-attachments/assets/2603b512-9e16-490b-9db9-e1e346edc25f)

This is a standby environment. There is no user traffic. A large number of "Command execution timeout for command" messages are displayed.
`[2024-12-04 01:07:19.970] [] [] runlog] [redisson-timer-4-1] [org.redisson.client.handler.PingConnectionHandler] [ERROR] - [ Unable to send PING command over channel: [id: 0x6cdafbf6, L:/172.31.121.240:54104 - R:172.31.120.225/172.31.120.225:6379]]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.31.120.225:6379]
        at org.redisson.client.RedisConnection.lambda$async$2(RedisConnection.java:295) ~[redisson-3.37.0.jar!/:3.37.0]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
[2024-12-04 01:07:19.970] [] [] runlog] [redisson-timer-4-1] [org.redisson.client.handler.PingConnectionHandler] [ERROR] - [ Unable to send PING command over channel: [id: 0x90d73776, L:/172.31.121.240:46700 - R:172.31.121.179/172.31.121.179:6379]]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.31.120.225:6379]
        at org.redisson.client.RedisConnection.lambda$async$2(RedisConnection.java:295) ~[redisson-3.37.0.jar!/:3.37.0]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
[2024-12-04 01:07:19.970] [] [] runlog] [redisson-timer-4-1] [org.redisson.client.handler.PingConnectionHandler] [ERROR] - [ Unable to send PING command over channel: [id: 0x802b1fd4, L:/172.31.121.240:57370 - R:172.31.123.162/172.31.123.162:6379]]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.31.120.225:6379]
        at org.redisson.client.RedisConnection.lambda$async$2(RedisConnection.java:295) ~[redisson-3.37.0.jar!/:3.37.0]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]`

**Comment by mrniko** [comment]
@yuanxiaohua1 

Can you share the Redisson configuration?

**Comment by yuanxiaohua1** [comment]
Redisson config: 
```

    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {
        return Redisson.create(redissionConfig());
    }

    @Bean
    public Config redissionConfig() {
        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.useClusterServers();
        clusterServersConfig.setTimeout(timeout);
        clusterServersConfig.setPassword(password);
        for (String addr : clusterProperties.getNodes()) {
            clusterServersConfig.addNodeAddress("redis://" + addr);
        }
        return config;
    }

    @Configuration
    @ConfigurationProperties(prefix = "spring.redis.cluster")
    public static class ClusterConfigurationProperties {
        List<String> nodes;
        int maxRedirects;

        public List<String> getNodes() {
            return nodes;
        }

        public void setNodes(List<String> nodes) {
            this.nodes = nodes;
        }

        public int getMaxRedirects() {
            return maxRedirects;
        }

        public void setMaxRedirects(int maxRedirects) {
            this.maxRedirects = maxRedirects;
        }
    }
```

**Comment by mrniko** [comment]
@yuanxiaohua1 

Can you share a thread dump?

**Comment by yuanxiaohua1** [comment]
The dump cannot be exported, The thread that causes the CPU usage to increase is redisson-netty-*-*.

![Image](https://github.com/user-attachments/assets/6a1313c6-19c7-4464-b12c-a7c4111a426b)

**Comment by yuanxiaohua1** [comment]
No Redisson-related operation is performed, The following error message is displayed, and the CPU usage increases sharply

>  [runlog] [redisson-timer-4-1] [org.redisson.client.handler.PingConnectionHandler] [ERROR] - [ Unable to send PING command over channel: [id: 0xbb129e1c, L:/172.31.122.130:47118 - R:172.31.123.162/172.31.123.162:6379]]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.31.123.162:6379]
        at org.redisson.client.RedisConnection.lambda$async$2(RedisConnection.java:295) ~[redisson-3.37.0.jar!/:3.37.0]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]

**Comment by mrniko** [comment]
@yuanxiaohua1 

Try to set `pingConnectionInterval = 0`

**Comment by yuanxiaohua1** [comment]
ok, thanks.

**Comment by yuanxiaohua1** [comment]
set pingConnectionInterval = 0, 
What are the effects of disabling the heartbeat check?

**Comment by mrniko** [comment]
this feature helps to detect broken channels if database is used behind a proxy

**Comment by yuanxiaohua1** [comment]
Well, heartbeat detection causes the CPU to soar. Can you help analyze this problem?

**Comment by yuanxiaohua1** [comment]
Very early versions do not have this problem, 22-year-old 3.13.6 version does not have this problem.

**Comment by mrniko** [comment]
how many connections do you have in total?

**Comment by yuanxiaohua1** [comment]
Only timeout is set to 1000 ms. Other configuration items use the default values.

**Comment by mrniko** [comment]
I did a fix of closed channel detection. Can you try a build from the master branch?

**Comment by yuanxiaohua1** [comment]
This is an occasional problem and does not affect the use of the system for the time being. Wait for your new version.
Well, when will a new version be released.

**Comment by mrniko** [comment]
on Monday

**Comment by yuanxiaohua1** [comment]
The Redisson version is expected to be upgraded in early March.

**Comment by yuanxiaohua1** [comment]
After the version is upgraded to 3.44, the CPU usage still increases sharply, but the exception information is different from that before.


The following error information is displayed at the beginning:
> [2025-03-16 05:54:50.863] [] [] [com.huawei.luban.CloudBuild.buildproject.22184] [CloudBuild_buildproject_22184] [buildProject] [runlog] [redisson-timer-4-1] [org.redisson.client.handler.PingConnectionHandler] [ERROR] - [ Unable to send PING command over channel: [id: 0x0d6d3f44, L:/172.31.123.155:60362 - R:172.31.121.179/172.31.121.179:6379]]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.31.121.179:6379,172.31.121.179/172.31.121.179:6379]
        at org.redisson.client.RedisConnection.lambda$async$2(RedisConnection.java:295) ~[redisson-3.44.0.jar!/:3.44.0]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]

Then, the following error information is displayed:
> org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check CPU usage of the JVM. Check that there are no blocking invocations in async/reactive/rx listeners or subscribeOnElements method. Check connection with Redis node: 172.31.122.7/172.31.122.7:6379 for TCP packet drops. Try to increase nettyThreads setting. Netty pending tasks: 9, Node source: NodeSource [slot=594, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1571753640 [redisClient=[addr=redis://172.31.122.7:6379,172.31.122.7/172.31.122.7:6379], channel=[id: 0x88f466e1, L:/172.31.123.155:59678 - R:172.31.122.7/172.31.122.7:6379], currentCommand=null, usage=1], command: (EVAL), params: [local result = 0;for j = 1, #KEYS, 1 do local expireSet; if ARGV[2] ~= '' then expireSet = redis.call('pexpire', KEYS[j], ARGV[1], ARGV[2]); else expireSet = redis.call('pexpire', KEYS[j], ARGV[1]); end; if expireSet == 1 then result = expireSet;end; end; return result; , 1, buildproject:worker:alive:18, 300000, ] after 3 retry attempts
        at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:300) ~[redisson-3.44.0.jar!/:3.44.0]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar!/:4.1.107.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]

**Comment by seakider** [comment]
Can you provide a top thread dump?

**Comment by yuanxiaohua1** [comment]
The thread dump cannot be provided, Some log information is displayed on the page.

**Comment by ethanhere** [comment]
We are seeing almost the same error and exception trace.
Is this issue being fixed? what version should fix it?

**Comment by mrniko** [comment]
@yuanxiaohua1 

Can you try **4.5.0**? it has `PingConnectionHandler` race condition fix

As for RedisTimeoutException please refer to https://redisson.pro/docs/faq/

**Comment by yuanxiaohua1** [comment]
I will give it a try, and I estimate that the results will be available in about two months.
