### ISSUE TITLE
With redisson latest version 3.35.0 quarkus application is not starting

### ISSUE THREAD

**Issue by subhanus** [redisson/redisson#6112]
Hi @mrniko 
Redis version : 7.x.x
Redisson version: 3.35.0
Redisson configuration: 
`quarkus.redisson.codec=com.xxx.xxx.CustomLZ4Codec
quarkus.redisson.address-resolver-group-factory=com.xxx.xxx..redisson.CustomizedSequentialDnsAddressResolverFactory
quarkus.redisson.cluster-servers-config.node-addresses=redis://redis:6379`

jboss.marshalling version:
`
org.jboss.marshalling:jboss-marshalling:2.1.4.Final
`

Error:
`
Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error injecting com.logicmonitor.metricsprocessor.cache.CompanyCache com.logicmonitor.metricsprocessor.metricsinput.kafka.ApacheClientKafkaNormalInput.companyCache
	at com.logicmonitor.metricsprocessor.metricsinput.kafka.ApacheClientKafkaNormalInput_Bean.doCreate(Unknown Source)
	at com.logicmonitor.metricsprocessor.metricsinput.kafka.ApacheClientKafkaNormalInput_Bean.create(Unknown Source)
	at com.logicmonitor.metricsprocessor.metricsinput.kafka.ApacheClientKafkaNormalInput_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c7(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at com.logicmonitor.metricsprocessor.metricsinput.kafka.ApacheClientKafkaNormalInput_Observer_startup_g2WpEPLXLEAkABvQonJZZIL4LXg.notify(Unknown Source)
Caused by: java.lang.RuntimeException: Error injecting com.logicmonitor.metricsprocessor.cache.CompanyCache com.logicmonitor.metricsprocessor.metricsinput.kafka.ApacheClientKafkaNormalInput.companyCache

	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.RuntimeException: Error injecting com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility com.logicmonitor.metricsprocessor.cache.impl.CompanyCacheImpl.dataBackupUtility
	at com.logicmonitor.metricsprocessor.cache.impl.CompanyCacheImpl_Bean.doCreate(Unknown Source)
Caused by: java.lang.RuntimeException: Error injecting com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility com.logicmonitor.metricsprocessor.cache.impl.CompanyCacheImpl.dataBackupUtility

	at com.logicmonitor.metricsprocessor.cache.impl.CompanyCacheImpl_Bean.create(Unknown Source)
	at com.logicmonitor.metricsprocessor.cache.impl.CompanyCacheImpl_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at com.logicmonitor.metricsprocessor.cache.impl.CompanyCacheImpl_Bean.get(Unknown Source)
	at com.logicmonitor.metricsprocessor.cache.impl.CompanyCacheImpl_Bean.get(Unknown Source)
	... 30 more
Caused by: java.lang.RuntimeException: Error injecting org.redisson.api.RedissonClient com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility.redisClient
	at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.doCreate(Unknown Source)
	at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.create(Unknown Source)
Caused by: java.lang.RuntimeException: Error injecting org.redisson.api.RedissonClient com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility.redisClient

	at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.get(Unknown Source)
	at com.logicmonitor.metricsprocessor.metricsbackup.DataBackupUtility_Bean.get(Unknown Source)
	... 42 more
Caused by: jakarta.enterprise.inject.CreationException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.logicmonitor.metricsprocessor.metricsbackup.CustomLZ4Codec`, problem: RIVER
 at [Source: (StringReader); line: 2, column: 75] (through reference chain: org.redisson.config.Config["codec"])
	at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.create(Unknown Source)
Caused by: jakarta.enterprise.inject.CreationException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.logicmonitor.metricsprocessor.metricsbackup.CustomLZ4Codec`, problem: RIVER

	at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.get(Unknown Source)
	at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.get(Unknown Source)
	... 54 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.logicmonitor.metricsprocessor.metricsbackup.CustomLZ4Codec`, problem: RIVER
 at [Source: (StringReader); line: 2, column: 75] (through reference chain: org.redisson.config.Config["codec"])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2014)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.logicmonitor.metricsprocessor.metricsbackup.CustomLZ4Codec`, problem: RIVER

	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:598)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:621)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._deserializeWithNativeTypeId(TypeDeserializerBase.java:269)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:106)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
	at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:159)
	at io.quarkus.redisson.client.runtime.RedissonClientProducer.create(RedissonClientProducer.java:85)
	at io.quarkus.redisson.client.runtime.RedissonClientProducer_ProducerMethod_create_VH06TQCYPIlKWuSlr9UZ1TMEbDQ_Bean.doCreate(Unknown Source)
	... 65 more
Caused by: java.lang.IllegalArgumentException: RIVER
	at org.redisson.codec.MarshallingCodec.<init>(MarshallingCodec.java:222)
	at org.redisson.codec.MarshallingCodec.<init>(MarshallingCodec.java:195)
Caused by: java.lang.IllegalArgumentException: RIVER

	at org.redisson.codec.MarshallingCodec.<init>(MarshallingCodec.java:191)
	at com.logicmonitor.metricsprocessor.metricsbackup.CustomLZ4Codec.<init>(CustomLZ4Codec.java:34)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:121)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:278)
	... 80 more
`

CustomLZ4Codec looks like:

`
public class CustomLZ4Codec extends BaseCodec {

    private static final int DECOMPRESSION_HEADER_SIZE = Integer.SIZE / 8;
    private final LZ4Factory factory = LZ4Factory.nativeInstance();

    private final Codec innerCodec;

    public CustomLZ4Codec() {
        this(new MarshallingCodec());
    }

    public CustomLZ4Codec(Codec innerCodec) {
        this.innerCodec = innerCodec;
    }

    public CustomLZ4Codec(ClassLoader classLoader) {
        this(new MarshallingCodec(classLoader));
    }

    public CustomLZ4Codec(ClassLoader classLoader, CustomLZ4Codec codec) throws ReflectiveOperationException {
        this(copy(classLoader, codec.innerCodec));
    }

    private final Decoder<Object> decoder = new Decoder<Object>() {
        @Override
        public Object decode(ByteBuf buf, State state) throws IOException {
            int decompressSize = buf.readInt();
            ByteBuf out = ByteBufAllocator.DEFAULT.buffer(decompressSize);
            try {
                LZ4SafeDecompressor decompressor = factory.safeDecompressor();
                ByteBuffer outBuffer = out.internalNioBuffer(out.writerIndex(), out.writableBytes());
                int pos = outBuffer.position();
                decompressor.decompress(buf.internalNioBuffer(buf.readerIndex(), buf.readableBytes()), outBuffer);
                int compressedLength = outBuffer.position() - pos;
                out.writerIndex(compressedLength);
                return innerCodec.getValueDecoder().decode(out, state);
            } finally {
                out.release();
            }
        }
    };

    private final Encoder encoder = new Encoder() {

        @Override
        public ByteBuf encode(Object in) throws IOException {
            ByteBuf bytes = null;
            try {
                LZ4Compressor compressor = factory.fastCompressor();
                bytes = innerCodec.getValueEncoder().encode(in);
                ByteBuffer srcBuf = bytes.internalNioBuffer(bytes.readerIndex(), bytes.readableBytes());

                int outMaxLength = compressor.maxCompressedLength(bytes.readableBytes());
                ByteBuf out = ByteBufAllocator.DEFAULT.buffer(outMaxLength + DECOMPRESSION_HEADER_SIZE);
                out.writeInt(bytes.readableBytes());
                ByteBuffer outBuf = out.internalNioBuffer(out.writerIndex(), out.writableBytes());
                int pos = outBuf.position();

                compressor.compress(srcBuf, outBuf);

                int compressedLength = outBuf.position() - pos;
                out.writerIndex(out.writerIndex() + compressedLength);
                return out;
            } finally {
                if (bytes != null) {
                    bytes.release();
                }
            }
        }
    };

    @Override
    public Decoder<Object> getValueDecoder() {
        return decoder;
    }

    @Override
    public Encoder getValueEncoder() {
        return encoder;
    }

}
`

**Comment by subhanus** [comment]
It was working fine with redisson version 
`org.redisson:redisson-quarkus-30:3.27.2`

**Comment by subhanus** [comment]
We found the issue:
Since 3.29.0 version redisson has removed the `org.jboss.marshalling.*` from the Jar artifact.
We will need to explicitly add them in our project.

**Comment by mrniko** [comment]
This codec has been deprecated since version 3.19.0

**Comment by subhanus** [comment]
@mrniko 
Yes we understand that, but since we already have encrypted data using marshalling codec and there is not option to decrypt data written in redis  using the newer KryoCodec/Kryo5Codec/LZ4CodecV2 we had to stick with deprecated codec.

If you can suggest/implement some mechanisms to migrate the data it will be very helpful.

**Comment by mrniko** [comment]
The only solution here is a migration like in any other database.
