### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 89

### ISSUE THREAD

**Issue by Wanan520521** [redisson/redisson#6126]
When executing the command to obtain value in bulk, an error occurs.

Exception in thread "main" org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:369)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:182)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:260)
	at org.redisson.RedissonBatch.execute(RedissonBatch.java:233)
	at ValueTest.main(ValueTest.java:70)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 89
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
	at org.redisson.codec.Kryo5Codec$4.decode(Kryo5Codec.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:442)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:292)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:230)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:146)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Here's the testing code.

`      RBatch batchValue = redisClient.createBatch();
        for (Key key : keyList) {
            String keyType = key.getKeyType();
            String keyStr = key.getKey();
            if (keyType.equals(KeyTypeEnum.STRING.getRTypeName())) {
                batchValue.getBucket(keyStr).getAsync();
            }
            if (keyType.equals(KeyTypeEnum.SET.getRTypeName())) {
                batchValue.getSet(keyStr).readAllAsync();
            }
            if (keyType.equals(KeyTypeEnum.ZSET.getRTypeName())) {
                batchValue.getScoredSortedSet(keyStr).valueRangeAsync(0, -1);
            }
            if (keyType.equals(KeyTypeEnum.HASH.getRTypeName())) {
                batchValue.getMap(keyStr).readAllEntrySetAsync();
            }
            if (keyType.equals(KeyTypeEnum.LIST.getRTypeName())) {
                batchValue.getList(keyStr).readAllAsync();
            }
            if (keyType.equals(KeyTypeEnum.NONE.getRTypeName())) {
                batchValue.getBucket(keyStr).getAsync();
            }
        }

        BatchResult<?> batchResult = batchValue.execute();`
We are seeing this exceptions lately for Redisson 3.34.1.

**Comment by mrniko** [comment]
Which Redisson version did you use before?

**Comment by Wanan520521** [comment]
Also 3.34.1, this is a new feature we have developed

**Comment by Wanan520521** [comment]
> Which Redisson version did you use before?
Also 3.34.1, this is a new feature we have developed
