### ISSUE TITLE
Redisson throw StackOverflowError

### ISSUE THREAD

**Issue by skafenko** [redisson/redisson#6135]
Redisson throw StackOverflowError when get getOperationAsync()

`ERROR: 2024-08-28 16:13:55,825 [org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer]:  Consumer thread error, thread abort.. [1;31m java.lang.StackOverflowError
	
at java.base/java.util.HashMap.removeNode(HashMap.java:845)
	at java.base/java.util.HashMap.remove(HashMap.java:797)
	at java.base/java.util.HashSet.remove(HashSet.java:237)
	at java.base/java.util.Collections$SynchronizedCollection.remove(Collections.java:2107)
	at org.redisson.cache.LRUCacheMap.onValueRead(LRUCacheMap.java:67)
	at org.redisson.cache.AbstractCacheMap.readValue(AbstractCacheMap.java:164)
	at org.redisson.cache.AbstractCacheMap.get(AbstractCacheMap.java:160)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:329)
	at org.redisson.command.RedisExecutor.getCodec(RedisExecutor.java:713)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:126)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:564)
	at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:511)
	at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:381)
	at org.redisson.RedissonMapCache.getOperationAsync(RedissonMapCache.java:488)[m

28-Aug-2024 16:13:55.830 INFO [Thread-8] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
28-Aug-2024 16:13:55.833 INFO [Thread-8] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
`

**Redisson version 3.25.2**

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5626
