### ISSUE TITLE
luascript cannot get params correctly

### ISSUE THREAD

**Issue by william-zong** [redisson/redisson#6139]
### Redis version

redis-stack-server:7.4.0-v0

### Redisson version

3.35.0

### Redisson configuration

    public void test2() {
        String luaScript = "local x = tonumber(ARGV[1]) " +
                "local y = tonumber(ARGV[2]) " +
                "local sum = x + y " +
                "return sum";
   
        long param1 = 10;
        long param2 = 20;
       
        Object result = redissonClient.getScript().eval(
                RScript.Mode.READ_WRITE,
                luaScript,
                RScript.ReturnType.VALUE,
                Arrays.asList(), 
                String.valueOf(param1), String.valueOf(param2)
        );

        log.info("Lua Script Result: " + result);
    }

### What is the Expected behavior?

if correct，i will get 30

### What is the Actual behavior?

org.redisson.client.RedisException: ERR user_script:1: attempt to perform arithmetic on local 'x' (a nil value) script: 49a7d5b488ce3fdf78e91114d751addc3250bccf, on @user_script:1.. channel: [id: 0xe6520082, L:/192.6.78.111:13144 - R:192.6.78.76/192.6.78.76:6371] command: (EVAL), params: [local x = tonumber(ARGV[1]) local y = tonumber(ARGV[2]) local sum = x + y return sum, 0, PooledUnsafeDirectByteBuf(ridx: 0, widx: 3, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 3, cap: 256)], promise: java.util.concurrent.CompletableFuture@69d5ed52[Not completed, 1 dependents]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:420)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:218)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:146)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lyrric** [comment]
specify  a codec.
like this:
`redissonClient.getScript(new StringCodec())`

**Comment by william-zong** [comment]
> specify a codec. like this: `redissonClient.getScript(new StringCodec())`

It worked,thank you
