### ISSUE TITLE
Failed to submit a listener notification task. Event loop shut down?

### ISSUE THREAD

**Issue by SkillKingwjl** [redisson/redisson#6147]
### Redis version

6.0.16

### Redisson version

3.32.0

### Redisson configuration

spring
  data:
    redis:
      host: 172.30.10.76 
      port: 6379 
      database: 4
      password: 123456

### What is the Actual behavior?

Failed to submit a listener notification task. Event loop shut down?

java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:931) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:350) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:343) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:833) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:824) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:814) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:862) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:500) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.111.Final.jar!/:4.1.111.Final]
        at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:196) ~[redisson-3.32.0.jar!/:3.32.0]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357) ~[na:na]
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:175) ~[redisson-3.32.0.jar!/:3.32.0]
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:658) ~[redisson-3.32.0.jar!/:3.32.0]
        at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:395) ~[redisson-3.32.0.jar!/:3.32.0]
        at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:753) ~[redisson-spring-data-33-3.32.0.jar!/:3.32.0]
        at org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:489) ~[redisson-spring-data-33-3.32.0.jar!/:3.32.0]
        at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:54) ~[spring-data-redis-3.3.1.jar!/:3.3.1]
        at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:61) ~[spring-data-redis-3.3.1.jar!/:3.3.1]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:396) ~[spring-data-redis-3.3.1.jar!/:3.3.1]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:363) ~[spring-data-redis-3.3.1.jar!/:3.3.1]
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97) ~[spring-data-redis-3.3.1.jar!/:3.3.1]
        at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:50) ~[spring-data-redis-3.3.1.jar!/:3.3.1]
        at com.atlas.framework.redis.util.RedisUtils.get(RedisUtils.java:65) ~[atlas-spring-boot-starter-redis-2.2.0-snapshot.jar!/:na]
        at com.atlas.framework.redis.util.RedisUtils.get(RedisUtils.java:73) ~[atlas-spring-boot-starter-redis-2.2.0-snapshot.jar!/:na]
        at com.atlas.module.clicker.service.xxx.xxx(ClickSenderServiceImpl.java:142) ~[!/:na]
        at com.atlas.module.clicker.consumer.Consumer.lambda$sendClicksToWorker$0(Consumer.java:572) ~[!/:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[na:na]

**Comment by mrniko** [comment]
Fixed. Thanks for report
