### ISSUE TITLE
redisson cpu 100% run at commandsQueue.java line 79

### ISSUE THREAD

**Issue by honglang1023** [redisson/redisson#6153]
### Redis version

5.0

### Redisson version

3.18.9

### Redisson configuration

singleServerConfig:
        idleConnectionTimeout: 900000
        # 同任何节点建立连接时的等待超时。时间单位是毫秒。
        connectTimeout: 3000
        
        timeout: 200
     
        retryAttempts: 0
        
        retryInterval: 500
        
        connectionMinimumIdleSize: 16
        
        connectionPoolSize: 64

### What is the Actual behavior?

1.cpu still 100% even there is not request on the service.
![redisson](https://github.com/user-attachments/assets/2dcd5f26-3ea4-4821-86c5-dfdf37b6817c)

2.I dump the thread, got three top cpu thread, as below:

"redisson-netty-2-6" #184 prio=5 os_prio=0 cpu=295856.81ms elapsed=3109.81s tid=0x00007fbd7c41bf40 nid=0xbd runnable  [0x00007fbd6c189000]
   java.lang.Thread.State: RUNNABLE
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:79)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
	at org.redisson.client.RedisConnection.send(RedisConnection.java:206)
	at org.redisson.command.RedisExecutor.sendCommand(RedisExecutor.java:590)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:164)
	at org.redisson.command.RedisExecutor$$Lambda$2031/0x000000080241d570.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17/CompletableFuture.java:2147)
	at org.redisson.connection.pool.ConnectionPool.connectedSuccessful(ConnectionPool.java:302)
	at org.redisson.connection.pool.ConnectionPool.connectTo(ConnectionPool.java:266)
	at org.redisson.connection.pool.ConnectionPool.lambda$acquireConnection$2(ConnectionPool.java:226)
	at org.redisson.connection.pool.ConnectionPool$$Lambda$2025/0x000000080241c838.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@17/CompletableFuture.java:718)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17/CompletableFuture.java:2147)
	at org.redisson.misc.AsyncSemaphore.tryRun(AsyncSemaphore.java:79)
	at org.redisson.misc.AsyncSemaphore.release(AsyncSemaphore.java:96)
	at org.redisson.connection.ClientConnectionsEntry.releaseConnection(ClientConnectionsEntry.java:153)
	at org.redisson.connection.pool.ConnectionPool.releaseConnection(ConnectionPool.java:420)
	at org.redisson.connection.pool.ConnectionPool.returnConnection(ConnectionPool.java:416)
	at org.redisson.connection.pool.MasterConnectionPool.returnConnection(MasterConnectionPool.java:34)
	at org.redisson.connection.MasterSlaveEntry.releaseWrite(MasterSlaveEntry.java:611)
	at org.redisson.connection.SingleEntry.releaseRead(SingleEntry.java:48)
	at org.redisson.connection.MasterSlaveConnectionManager.releaseRead(MasterSlaveConnectionManager.java:585)
	at org.redisson.command.RedisExecutor.release(RedisExecutor.java:629)
	at org.redisson.command.RedisExecutor.releaseConnection(RedisExecutor.java:613)
	at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:174)
	at org.redisson.command.RedisExecutor$$Lambda$2035/0x000000080241e278.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.completeExceptionally(java.base@17/CompletableFuture.java:2162)
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:327)
	at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:169)
	at org.redisson.command.RedisExecutor$$Lambda$2034/0x000000080241e040.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:83)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17/Thread.java:833)

"redisson-netty-2-26" #204 prio=5 os_prio=0 cpu=298354.46ms elapsed=3109.79s tid=0x00007fbdd4001810 nid=0xd1 runnable  [0x00007fbcf46f8000]
   java.lang.Thread.State: RUNNABLE
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:79)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
	at org.redisson.client.RedisConnection.send(RedisConnection.java:206)
	at org.redisson.command.RedisExecutor.sendCommand(RedisExecutor.java:590)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:164)
	at org.redisson.command.RedisExecutor$$Lambda$2031/0x000000080241d570.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17/CompletableFuture.java:2147)
	at org.redisson.connection.pool.ConnectionPool.connectedSuccessful(ConnectionPool.java:302)
	at org.redisson.connection.pool.ConnectionPool.connectTo(ConnectionPool.java:266)
	at org.redisson.connection.pool.ConnectionPool.lambda$acquireConnection$2(ConnectionPool.java:226)
	at org.redisson.connection.pool.ConnectionPool$$Lambda$2025/0x000000080241c838.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@17/CompletableFuture.java:718)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17/CompletableFuture.java:2147)
	at org.redisson.misc.AsyncSemaphore.tryRun(AsyncSemaphore.java:79)
	at org.redisson.misc.AsyncSemaphore.release(AsyncSemaphore.java:96)
	at org.redisson.connection.ClientConnectionsEntry.releaseConnection(ClientConnectionsEntry.java:153)
	at org.redisson.connection.pool.ConnectionPool.releaseConnection(ConnectionPool.java:420)
	at org.redisson.connection.pool.ConnectionPool.returnConnection(ConnectionPool.java:416)
	at org.redisson.connection.pool.MasterConnectionPool.returnConnection(MasterConnectionPool.java:34)
	at org.redisson.connection.MasterSlaveEntry.releaseWrite(MasterSlaveEntry.java:611)
	at org.redisson.connection.MasterSlaveConnectionManager.releaseWrite(MasterSlaveConnectionManager.java:575)
	at org.redisson.command.RedisExecutor.release(RedisExecutor.java:631)
	at org.redisson.command.RedisExecutor.releaseConnection(RedisExecutor.java:613)
	at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:174)
	at org.redisson.command.RedisExecutor$$Lambda$2035/0x000000080241e278.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.completeExceptionally(java.base@17/CompletableFuture.java:2162)
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:327)
	at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:169)
	at org.redisson.command.RedisExecutor$$Lambda$2034/0x000000080241e040.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:83)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17/Thread.java:833)

"redisson-netty-2-2" #180 prio=5 os_prio=0 cpu=310901.17ms elapsed=3109.96s tid=0x00007fbcbeb50130 nid=0xb8 runnable  [0x00007fbd6c044000]
   java.lang.Thread.State: RUNNABLE
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:79)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
	at org.redisson.client.RedisConnection.send(RedisConnection.java:206)
	at org.redisson.command.RedisExecutor.sendCommand(RedisExecutor.java:590)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:164)
	at org.redisson.command.RedisExecutor$$Lambda$2031/0x000000080241d570.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17/CompletableFuture.java:2147)
	at org.redisson.connection.pool.ConnectionPool.connectedSuccessful(ConnectionPool.java:302)
	at org.redisson.connection.pool.ConnectionPool.connectTo(ConnectionPool.java:266)
	at org.redisson.connection.pool.ConnectionPool.lambda$acquireConnection$2(ConnectionPool.java:226)
	at org.redisson.connection.pool.ConnectionPool$$Lambda$2025/0x000000080241c838.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@17/CompletableFuture.java:718)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17/CompletableFuture.java:2147)
	at org.redisson.misc.AsyncSemaphore.tryRun(AsyncSemaphore.java:79)
	at org.redisson.misc.AsyncSemaphore.release(AsyncSemaphore.java:96)
	at org.redisson.connection.ClientConnectionsEntry.releaseConnection(ClientConnectionsEntry.java:153)
	at org.redisson.connection.pool.ConnectionPool.releaseConnection(ConnectionPool.java:420)
	at org.redisson.connection.pool.ConnectionPool.returnConnection(ConnectionPool.java:416)
	at org.redisson.connection.pool.MasterConnectionPool.returnConnection(MasterConnectionPool.java:34)
	at org.redisson.connection.MasterSlaveEntry.releaseWrite(MasterSlaveEntry.java:611)
	at org.redisson.connection.SingleEntry.releaseRead(SingleEntry.java:48)
	at org.redisson.connection.MasterSlaveConnectionManager.releaseRead(MasterSlaveConnectionManager.java:585)
	at org.redisson.command.RedisExecutor.release(RedisExecutor.java:629)
	at org.redisson.command.RedisExecutor.releaseConnection(RedisExecutor.java:613)
	at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:174)
	at org.redisson.command.RedisExecutor$$Lambda$2035/0x000000080241e278.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.completeExceptionally(java.base@17/CompletableFuture.java:2162)
	at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:327)
	at org.redisson.command.RedisExecutor.lambda$execute$2(RedisExecutor.java:169)
	at org.redisson.command.RedisExecutor$$Lambda$2034/0x000000080241e040.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:83)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17/Thread.java:833)
3. anaylse the code at line 79 of commandsQueue:
![redissonQ](https://github.com/user-attachments/assets/ba811d26-42b2-47f1-82f4-65ac1442f0c7)
I  believe the cpu is hign because cpu always run lock.compareAndSet, but why the lock not be set as false ?

**Comment by mrniko** [comment]
Which version? there is no 3.18.9 version

**Comment by honglang1023** [comment]
version: 3.18.0

**Comment by mrniko** [comment]
Which JDK version and vendor?
Which OS?

**Comment by honglang1023** [comment]
openjdk 17
os centos 7

**Comment by mrniko** [comment]
This can happen only if thread set lock = true was killed

**Comment by honglang1023** [comment]
this can be reproduced in high press。I will try with newest version to see it can be produced again or not。

**Comment by mrniko** [comment]
any test case?

**Comment by mrniko** [comment]
What CPU is being used?

**Comment by mrniko** [comment]
Can you try attached version or master branch build?

[redisson-3.36.1-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16945255/redisson-3.36.1-SNAPSHOT.jar.zip)

**Comment by honglang1023** [comment]
> Can you try attached version or master branch build?
> 
> [redisson-3.36.1-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16945255/redisson-3.36.1-SNAPSHOT.jar.zip)

can you fix it base version 3.1.8.0? since from 3.1.8.1 version spring-boot-data-redis upgrade to 3.0.0 which change some interface.

**Comment by honglang1023** [comment]
And publish it(snapshot) in center lib, so I can use it directly

**Comment by mrniko** [comment]
> > Can you try attached version or master branch build?
> > [redisson-3.36.1-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16945255/redisson-3.36.1-SNAPSHOT.jar.zip)
> 
> can you fix it base version 3.1.8.0? since from 3.1.8.1 version spring-boot-data-redis upgrade to 3.0.0 which change some interface.

I'm afraid no. You need to exclude redisson-spring-data-30 dependency and add redisson-spring-data-xx you need.

**Comment by honglang1023** [comment]
so, can you publish it (redisson-spring-boot-starter snapshot) in center repository?

**Comment by mrniko** [comment]
Unfortunately, only releases are published in central repo.

**Comment by mrniko** [comment]
Fixed
