### ISSUE TITLE
ProtobufCodec broken

### ISSUE THREAD

**Issue by fdsafgsd** [redisson/redisson#6154]
### Redis version

-

### Redisson version

3.35.0

### Redisson configuration

-

### What is the Actual behavior?

ProtobufCodec don't work with CompositeCodec (maybe at all).
As you can see from the stack trace, the codec lacks the necessary constructor.

Exception:
`Caused by: java.lang.NoSuchMethodException: org.redisson.codec.ProtobufCodec.<init>(java.lang.ClassLoader,org.redisson.codec.ProtobufCodec)
	at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[na:na]
	at java.base/java.lang.Class.getConstructor(Class.java:2442) ~[na:na]
	at org.redisson.client.codec.BaseCodec.copy(BaseCodec.java:48) ~[redisson-3.35.0.jar:3.35.0]
	at org.redisson.codec.CompositeCodec.<init>(CompositeCodec.java:48) ~[redisson-3.35.0.jar:3.35.0]`

**Comment by fdsafgsd** [comment]
With `config.setUseThreadClassLoader(false);` ProtobufCodec works.

**Comment by mrniko** [comment]
Fixed. Thanks for report
