### ISSUE TITLE
Redisson shutdown exception

### ISSUE THREAD

**Issue by PSrinivas0813** [redisson/redisson#6173]
### Redis version

7.4

### Redisson version

3.35.0

### Redisson configuration

We are running our java web application on have Tomcat 10 and intermittently run into the Redisson shutdown error.
We have not observed any specific pattern for this exception.

```
07:34:12.251 WARNING [Catalina-utility-2] org.apache.catalina.core.StandardContext.backgroundProcess Exception processing manager [RedissonSessionManager[StandardEngine[Catalina].StandardHost[localhost].StandardContext[/solutionmanager]]] background process
	org.redisson.RedissonShutdownException: Redisson is shutdown
		at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:125)
		at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:665)
		at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:619)
		at org.redisson.RedissonObject.deleteAsync(RedissonObject.java:392)
		at org.redisson.RedissonObject.delete(RedissonObject.java:387)
		at org.redisson.tomcat.RedissonSession.delete(RedissonSession.java:192)
		at org.redisson.tomcat.RedissonSessionManager.remove(RedissonSessionManager.java:229)
		at org.apache.catalina.session.StandardSession.expire(StandardSession.java:776)
		at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:613)
		at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:594)
		at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:577)
		at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5230)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1301)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1305)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1305)
		at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1283)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1583)
```

redisson.yaml is as follows:

```clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveNodeDetector: !<org.redisson.client.FailedConnectionDetector> {}
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "redis://testinstance-0001-001.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0001-002.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0001-003.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0002-001.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0002-002.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0002-003.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0003-001.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0003-002.i7acag.0001.use1.cache.amazonaws.com:6379"
    - "redis://testinstance-0003-003.i7acag.0001.use1.cache.amazonaws.com:6379"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
threads: 16
nettyThreads: 32
transportMode: "NIO"
codec: !<org.redisson.codec.SerializationCodec> {}
```

Our session manager config in `context.xml` in Tomcat 10 is as follows:

```
	<Manager className="org.redisson.tomcat.RedissonSessionManager" 
		configPath="D:/Data/QA/config/redisson.yaml" 
		readMode="MEMORY" 
		updateMode="AFTER_REQUEST"
		keyPrefix="qa-instance"/>
```

We have added redisson-all and redisson-tomcat jars in to Tomcat lib.
redisson-all-3.35.0
redisson-tomcat-10-3.35.0

Once we get this error, reload also does not help, we have to clear the cache or move to a different browser to start a new session.

### What is the Expected behavior?

We are running into the Redisson shutdown exception.

### What is the Actual behavior?

We should be able to continue browsing through our application without running into Redisson Exception.

@mrniko Can you please advice if we are doing something wrong?

**Comment by PSrinivas0813** [comment]
@mrniko Can you please take a look at this one? Are we missing any configuration?

**Comment by mrniko** [comment]
Fixed. Thanks for report
