### ISSUE TITLE
Unable to send PING command

### ISSUE THREAD

**Issue by mrq1324** [redisson/redisson#6184]
spring-data-reids:3.1.5
redisson:3.23.0

**Whether it is cluster mode or stand-alone mode, the connection problem of this Redis occurs occasionally, and the following error log is displayed**

2024-05-08 09:59:45.190 ERROR 8 --- [Thread-3] c.v.b.d.services.online.MasterManager    :
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.16.18.56/172.16.18.56:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@788904277 [redisClient=[addr=redis://172.16.18.56:6379], channel=[id: 0x4cfcf975, L:/10.245.5.76:54458 - R:172.16.18.56/172.16.18.56:6379], currentCommand=null, usage=1], command: (GET), params: [data:modelTask:masterMachineCode] after 3 retry attempts
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:272) ~[redisson-3.23.0.jar!/:3.23.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

2024-05-08 09:59:45.190 ERROR 8 --- [nioEventLoopGroup-2-1] c.v.b.d.s.online.ModelTaskManager        : publish task error

org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.16.18.56/172.16.18.56:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@690106818 [redisClient=[addr=redis://172.16.18.56:6379], channel=[id: 0xde71acd7, L:/10.245.5.76:54420 - R:172.16.18.56/172.16.18.56:6379], currentCommand=null, usage=1], command: (HGET), params: [data:modelTask:onlineModelIds_record, PooledUnsafeDirectByteBuf(ridx: 0, widx: 5, cap: 256)] after 3 retry attempts
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:272) ~[redisson-3.23.0.jar!/:3.23.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

2024-05-08 09:59:47.590 ERROR 8 --- [redisson-timer-4-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xed799c65, L:/10.245.5.76:54462 - R:172.16.18.56/172.16.18.56:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://172.16.18.56:6379]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256) ~[redisson-3.23.0.jar!/:3.23.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

2024-05-08 09:59:49.194  INFO 8 --- [Thread-3] c.v.b.d.services.online.MasterManager    : lock success
2024-05-08 09:59:49.228  INFO 8 --- [Thread-3] c.v.b.d.s.online.ModelOnlineInfoManager  : find online model : record: 544, 543, 542, 541, 540, 539, 538
2024-05-08 09:59:50.578  INFO 8 --- [Thread-4] c.v.b.d.s.online.ModelTaskManager        : publish task 540_e2e5fc45-e2f9-4a86-8c38-756212f24983, scanPosition null
2024-05-08 09:59:50.579  INFO 8 --- [nioEventLoopGroup-2-1] c.v.b.d.s.online.ModelTaskManager        : receive publish task 540_e2e5fc45-e2f9-4a86-8c38-756212f24983, now time 2024-05-08T09:59:50
2024-05-08 09:59:56.890 ERROR 8 --- [Thread-4] c.v.b.d.s.online.ModelTaskManager        : scan publish task error

org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.16.18.56/172.16.18.56:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@157761129 [redisClient=[addr=redis://172.16.18.56:6379], channel=[id: 0xbb914e8a, L:/10.245.5.76:54460 - R:172.16.18.56/172.16.18.56:6379], currentCommand=null, usage=1], command: (EVAL), params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); return v, 1, data:modelTask:runningInfo, PooledUnsafeDirectByteBuf(ridx: 0, widx: 42, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 80, cap: 256)] after 3 retry attempts
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:272) ~[redisson-3.23.0.jar!/:3.23.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

2024-05-08 09:59:58.290 ERROR 8 --- [redisson-timer-4-1] org.redisson.RedissonBaseLock            : Can't update lock data:modelTaskLock:managerMaster expiration

java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.16.18.56/172.16.18.56:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=20, freeConnectionsCounter=value:60:queue:0, freezeReason=null, client=[addr=redis://172.16.18.56:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@788904277 [redisClient=[addr=redis://172.16.18.56:6379], channel=[id: 0x4cfcf975, L:/10.245.5.76:54458 - R:172.16.18.56/172.16.18.56:6379], currentCommand=null, usage=1], command: null, params: null after 3 retry attempts
	at org.redisson.command.CommandAsyncService.lambda$syncedEval$22(CommandAsyncService.java:759) ~[redisson-3.23.0.jar!/:3.23.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[na:na]
	at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:318) ~[redisson-3.23.0.jar!/:3.23.0]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[na:na]
	at org.redisson.command.CommandBatchService.lambda$execute$9(CommandBatchService.java:448) ~[redisson-3.23.0.jar!/:3.23.0]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[na:na]
	at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:166) ~[redisson-3.23.0.jar!/:3.23.0]
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:553) ~[redisson-3.23.0.jar!/:3.23.0]
	at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:195) ~[redisson-3.23.0.jar!/:3.23.0]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[na:na]
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:275) ~[redisson-3.23.0.jar!/:3.23.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
Caused by: org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.16.18.56/172.16.18.56:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=20, freeConnectionsCounter=value:60:queue:0, freezeReason=null, client=[addr=redis://172.16.18.56:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@788904277 [redisClient=[addr=redis://172.16.18.56:6379], channel=[id: 0x4cfcf975, L:/10.245.5.76:54458 - R:172.16.18.56/172.16.18.56:6379], currentCommand=null, usage=1], command: null, params: null after 3 retry attempts
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:272) ~[redisson-3.23.0.jar!/:3.23.0]
	... 7 common frames omitted

^C
[root@vte-78f5bb4b86-w9zgb vte]# telnet 172.16.18.56 6379
Trying 172.16.18.56...
Connected to 172.16.18.56.
Escape character is '^]'.
^C^C^C^C^C^C

**Comment by mrniko** [comment]
Can you try 3.26.1 version?

**Comment by mrq1324** [comment]
> Can you try 3.26.1 version?

Yes，but still error。

**Comment by mrq1324** [comment]
> Can you try 3.26.1 version?

Yes，but still error。

2024-09-24 09:53:09.795 ERROR 1729 --- [redisson-timer-4-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x66d53f4e, L:/127.0.0.1:39196 - R:127.0.0.1/127.0.0.1:6312]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6312]
        at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253) ~[redisson-3.26.1.jar!/:3.26.1]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706) ~[netty-common-4.1.109.Final.jar!/:4.1.109.Final]
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.109.Final.jar!/:4.1.109.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694) ~[netty-common-4.1.109.Final.jar!/:4.1.109.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781) ~[netty-common-4.1.109.Final.jar!/:4.1.109.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494) ~[netty-common-4.1.109.Final.jar!/:4.1.109.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.109.Final.jar!/:4.1.109.Final]
        at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

**Comment by mrq1324** [comment]
@mrniko

**Comment by iridescenceZz** [comment]
I've encountered the same problem, have you found a solution?

**Comment by mrq1324** [comment]
> I've encountered the same problem, have you found a solution?

Didn't solve it, the author didn't reply to me

**Comment by mrniko** [comment]
Please refer to https://redisson.org/docs/faq/
