### ISSUE TITLE
RSet throws error "too many results to unpack" when invoking retainAll()

### ISSUE THREAD

**Issue by vpaturet** [redisson/redisson#6186]
### Redis version

6.2.12

### Redisson version

3.36.0

### Redisson configuration

Single node

### What is the Expected behavior?

Invoking RSet.retainAll() on a large collection (> 50 000 entries) succeeds.

### What is the Actual behavior?

The following error:
```

org.redisson.client.RedisException: ERR Error running script (call to f_3d6414ebe0b2807190bf1fedabae7b7417a021c1): @user_script:1: user_script:1: too many results to unpack. channel: [id: 0xbc6388f0, L:/127.0.0.1:48818 - R:localhost/127.0.0.1:6379] command: (EVAL), params: [redis.call('sadd', KEYS[2], unpack(ARGV)); local prevSize = redis.call('scard', KEYS[1]); local size = redis.call('sinterstore', KEYS[1], KEYS[1], KEYS[2]);redis.call('del', KEYS[2]); return size ~= prevSize and 1 or 0; , 2, stopPlaceCache, {stopPlaceCache}:redisson_temp, PooledUnsafeDirectByteBuf(ridx: 0, widx: 19, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 19, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 19, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 19, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 19, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 19, cap: 256), ...], promise: java.util.concurrent.CompletableFuture@3a1d2657[Not completed, 1 dependents]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:422)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:220)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:148)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:124)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
