### ISSUE TITLE
Tomcat does not start if  Redis server is down

### ISSUE THREAD

**Issue by adbhutrai** [redisson/redisson#6194]
### Redis version

Azure redis cache

### Redisson version

3.35.0

### Redisson configuration

{
"singleServerConfig": {
"idleConnectionTimeout": 10000,
"connectTimeout": 10000,
"timeout": 3000,
"retryAttempts": 3,
"retryInterval": 1500,
"subscriptionsPerConnection": 5,
"clientName": null,
"address": "rediss://:******************************@server.server.net:6380",
"subscriptionConnectionMinimumIdleSize": 1,
"subscriptionConnectionPoolSize": 50,
"connectionMinimumIdleSize": 10,
"connectionPoolSize": 64,
"database": 0,
"dnsMonitoringInterval": 5000
},
"threads": 0,
"nettyThreads": 0,
"lazyInitialization": true,
codec: !<org.redisson.codec.SerializationCodec> {}
}

 Tomcat redisson session manager config:
	``
 <Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="${catalina.base}/redisson.conf"
             readMode="MEMORY"
             broadcastSessionEvents="true"
             updateMode="AFTER_REQUEST"/>
``

### What is the Expected behavior?

Application should should be able start and run using tomcat memory for session without redis distributed session 

### What is the Actual behavior?

Application is not starting tomcat server is failing with error:
24-Sep-2024 15:55:41.879 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal The session manager failed to start
        org.apache.catalina.LifecycleException: Failed to start component 
[RedissonSessionManager[StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:402)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:179)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4441)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:599)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:571)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:654)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:969)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:771)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:423)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1629)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:109)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:385)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:332)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:776)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:874)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:757)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:569)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
        Caused by: org.redisson.client.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: down-test.redis.cache.windows.net/1.1.1.1:6380
                at org.redisson.connection.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:228)
                at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:188)
                at org.redisson.connection.MasterSlaveConnectionManager.lazyConnect(MasterSlaveConnectionManager.java:172)
                at org.redisson.connection.MasterSlaveConnectionManager.getEntry(MasterSlaveConnectionManager.java:466)
                at org.redisson.connection.MasterSlaveConnectionManager.getWriteEntry(MasterSlaveConnectionManager.java:473)
                at org.redisson.pubsub.PublishSubscribeService.getEntry(PublishSubscribeService.java:582)
                at org.redisson.pubsub.PublishSubscribeService.subscribe(PublishSubscribeService.java:381)
                at org.redisson.RedissonTopic.addListenerAsync(RedissonTopic.java:127)
                at org.redisson.RedissonTopic.addListenerAsync(RedissonTopic.java:123)
                at org.redisson.RedissonTopic.addListener(RedissonTopic.java:110)
                at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:350)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
                ... 40 more
        Caused by: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: down-test.redis.cache.windows.net/1.1.1.1:6380
                at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
                at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
                at org.redisson.connection.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:223)
                ... 51 more
        Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: down-test.redis.cache.windows.net/1.1.1.1:6380
                at org.redisson.connection.ConnectionsHolder.lambda$createConnection$2(ConnectionsHolder.java:165)
                at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
                at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
                at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
                at org.redisson.connection.ConnectionsHolder.lambda$createConnection$5(ConnectionsHolder.java:179)
                at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
                at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
                at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
                at org.redisson.client.RedisClient$1$2.run(RedisClient.java:304)
                at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:840)
        Caused by: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: down-test.redis.cache.windows.net/1.1.1.1:6380
                at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
                at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
                at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)
                ... 11 more
        Caused by: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: down-test.redis.cache.windows.net/1.1.1.1:6380
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
                at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
                at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
                ... 8 more
24-Sep-2024 15:55:41.879 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors

**Comment by usamarafiq7857** [comment]
If your application is failing to start Tomcat when the Redis server is down, it is likely because your application has a hard dependency on Redis at startup. To resolve this issue you can modify your Redis configuration to handle Redis unavailability gracefully.

**Comment by adbhutrai** [comment]
@usamarafiq7857 could you please suggest the required configuration for that. I have already shared what configuration we are using.

**Comment by arelkar** [comment]
@usamarafiq7857 - Appreciate your inputs on required redis configuration to tackle redis unavailability during startup. Thanks in advance.
