### ISSUE TITLE
The Bloom filter encounters an error if a contains() request is made while it is being deleted and updated.

### ISSUE THREAD

**Issue by harry-jang** [redisson/redisson#6197]
I plan to use a scheduler to maintain the Bloom filter for a specific time and then delete and recreate it for use.

However, during the deletion and update process, if a contains() request is made, errors such as "Bloom filter is not initialized yet" or "Bloom filter config has been changed" occur.

Is there any way to avoid these errors?

---
``` java
     // deletion and update process
     public void replaceAll(String key, List<String> values) {
        try {

            RBloomFilter<String> bloomFilter = redissonClient.getBloomFilter(key);

            if (bloomFilter.isExists()) {
                bloomFilter.delete();
            }

            bloomFilter.tryInit(500, 0.03);
            if(!values.isEmpty()) {
                bloomFilter.add(values);
            }

            log.info("BloomFilterClient replaceAll : key={}, values={}", key, values);

        } catch (Exception e) {
            log.warn("BloomFilterClient add occurred : key={}, values={}", key, values, e);
        }
    }

   public boolean contains(String key, String value) {
        try {

            RBloomFilter<String> bloomFilter = redissonClient.getBloomFilter(key);

            if(bloomFilter != null) {
                return bloomFilter.contains(value);
            }
        } catch (Exception e) {
            log.warn("BloomFilterClient contains occurred : key={}, value={}", key, value, e);
            return true;
        }
    }
```
---
[error message]
```
java.lang.IllegalStateException: Bloom filter is not initialized!
	at org.redisson.RedissonBloomFilter.readConfig(RedissonBloomFilter.java:251)
	at org.redisson.RedissonBloomFilter.readConfig(RedissonBloomFilter.java:245)
	at org.redisson.RedissonBloomFilter.contains(RedissonBloomFilter.java:156)
	at org.redisson.RedissonBloomFilter.contains(RedissonBloomFilter.java:200)
```
```
org.redisson.client.RedisException: ERR Error running script (call to f_e678c622b160a7f36fe9f26aecd0c1a5992e5b0c): @user_script:1: user_script:1: Bloom filter config has been changed . channel: [xxx] command: (EVAL), promise: io.opentelemetry.javaagent.instrumentation.redisson.CompletableFutureWrapper@659df58b[Not completed, 1 dependents], params: [local size = redis.call('hget', KEYS[1], 'size');local hashIterations = redis.call('hget', KEYS[1], 'hashIterations');assert(size == ARGV[1] and hashIterations == ARGV[2], 'Bloom filter config has been changed'), 1, :config, 3649, 5]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:381)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:279)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:217)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
```
---

Redisson version:
3.23.5
springboot.version
3.0.6

**Comment by harry-jang** [comment]
> You need to make sure that `bloomFilter.tryInit()` has been called before `contains()` method invocation

Thank you for your response. However, in my case, the Bloom filter is periodically deleted and refreshed during live operations, which is intentional. So, while contains() requests keep coming, the Bloom filter is being reset and updated again. In such a scenario, is the Bloom filter still appropriate?

**Comment by mrniko** [comment]
I think it should return 0 in this case.

**Comment by mrniko** [comment]
Merged
