### ISSUE TITLE
Executor service execution

### ISSUE THREAD

**Issue by mnadeem** [redisson/redisson#621]
The following call does not return 

```
      `RedissonClient redissonClient = Redisson.create();

    RExecutorService executorService = redissonClient.getExecutorService("myExecutor");
    java.util.concurrent.Future<Long> result = executorService.submit(new MyCallable());
    System.out.println("Result : "+result.get());`

       `public class MyCallable  implements Callable<Long> {

@Override
public Long call() throws Exception {
    System.out.println("Executing");

    return 2L;
}`
```

It neither prints "Executing" nor returns

I am using Redis 2.8.2402 and Resisson 2.3.0

**Comment by mrniko** [comment]
Did you run Redisson node instance?

**Comment by mnadeem** [comment]
Yeah I tried both, 

- Ran Redisson node
- Did not run Redisson node

**Comment by mrniko** [comment]
I have just checked tests with 2.8.2400. All works fine. Just clarify your steps:
1. Run Redisson node. It should use same parameters as Redisson does. Don't forget to add `executorServiceThreads`, `executorServiceWorkers` [params](https://github.com/mrniko/redisson/wiki/12.-Standalone-node#122-configuration) to it.  

`java -jar redisson-all.jar <config.json or config.yaml>`
2. Run your application with Redisson

**Comment by mnadeem** [comment]
I have started the node in embedded mode, I will try the other way as well

What would be the minimal config.json file, appreciate if you could help me with that

**Comment by mrniko** [comment]
Here is an example for embedded mode:
        
        Config config = ...

        RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setExecutorServiceThreads(5);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("myExecutor", 2));
        RedissonNode node = RedissonNode.create(nodeConfig);
        node.start();

        RedissonClient redissonClient = Redisson.create(config);
        RExecutorService executorService = redissonClient.getExecutorService("myExecutor");
        Future<Long> result = executorService.submit(new MyCallable());

**Comment by mnadeem** [comment]
Thanks a bundle, closing issue, Now I am getting an age old issue with jackson.

Need to figure out better way of handling it

com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.github.dexecutor.core.task.RetryOnceAndTerminateTask<java.lang.Comparable,java.lang.Object>]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)

**Comment by mrniko** [comment]
It's not a jackson issue. It's working by this way. Just create a default constructor for your task.

**Comment by mnadeem** [comment]
@Test
	public void testDistrutedExecutorService() throws InterruptedException, ExecutionException {

		RedissonClient redissonClient = Redisson.create();

		RedissonNodeConfig nodeConfig = new RedissonNodeConfig(redissonClient.getConfig());
	    nodeConfig.setExecutorServiceThreads(5);
	    nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("myExecutor", 2));
	    RedissonNode node = RedissonNode.create(nodeConfig);
	    node.start();
		
		RExecutorService executorService = redissonClient.getExecutorService("myExecutor");
		java.util.concurrent.Future<Long> result = executorService.submit(new MyCallable(2));
		System.out.println("Result : "+result.get());
       }
      
       import java.util.concurrent.Callable;

    public class MyCallable  implements Callable<Long> {
	
	private Integer data;
	
	public MyCallable(Integer data) {
		this.data = data;
	}
   
    @Override
    public Long call() throws Exception {
        System.out.println("Executing " + data);
       
        return (long) (data * 2);
     }
    }
    
Above code would throw exception
    Caused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: **No suitable constructor found for type [simple type, class com.github.dexecutor.redisson.MyCallable]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)**
 at [Source: io.netty.buffer.ByteBufInputStream@226dad07; line: 1, column: 54]
	at org.redisson.executor.RemoteExecutorServiceImpl.executeCallable(RemoteExecutorServiceImpl.java:176)
	at org.redisson.executor.RemoteExecutorServiceImpl.executeCallable(RemoteExecutorServiceImpl.java:161)

  MyCallable  is my business object (not a value object), which does not have default constructor, and for design concern I don't want to use @JsonCreator  and @JsonProperty across my business objects 

Is there any other way to do it with out having my business object invaded by json marshalling logic (probably external converter, that I would register with Redisosn, the way it works with other Data grids )

**Comment by mrniko** [comment]
You could try to add protected constructor

**Comment by mnadeem** [comment]
It is forcing me to have a protected/public constructor for everything in the object graph.. which would not be recommended and many a times not possible.

**Comment by mrniko** [comment]
You could solve it by adding jackson mixin class with with @JsonCreator into codec. In this case you don't need to customize task.

**Comment by mnadeem** [comment]
How would I register the mixin, with Redisson?

Appreciate if you could help me with that

**Comment by mrniko** [comment]
extend `JsonJacksonCodec` class and override `init` method like that:
```java
protected void init(ObjectMapper objectMapper) {
     super.init(objectMapper);
     objectMapper.addMixIn(MyTask.class, MyTaskMixIn.class);
}
```

**Comment by mnadeem** [comment]
Thanks a bundle Mrniko, for quick reply..  one more thing

I believe, we may have to register class (which extends `JsonJacksonCodec `) , right??

**Comment by mrniko** [comment]
You should define it in config via `codec` setting

**Comment by mnadeem** [comment]
RedissonClient redissonClient = Redisson.create();
		redissonClient.getConfig().setCodec(new MyJsonCodec());

I am getting the following exception
java.lang.IllegalStateException: java.lang.NoSuchMethodException: com.github.dexecutor.redisson.MyJsonCodec.<init>(java.lang.ClassLoader)
	at org.redisson.executor.RemoteExecutorServiceImpl.<init>(RemoteExecutorServiceImpl.java:69)
	at org.redisson.RedissonExecutorService.registerWorkers(RedissonExecutorService.java:240)
	at org.redisson.RedissonNode.start(RedissonNode.java:150)
	at com.github.dexecutor.redisson.RedissonExecutionEngineIntegrationTest.testDistrutedExecutorService(RedissonExecutionEngineIntegrationTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NoSuchMethodException: com.github.dexecutor.redisson.MyJsonCodec.<init>(java.lang.ClassLoader)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at org.redisson.executor.RemoteExecutorServiceImpl.<init>(RemoteExecutorServiceImpl.java:67)
	... 26 more

**Comment by mrniko** [comment]
Delegate constructor with `classLoader` param

**Comment by mnadeem** [comment]
I have tried both

    public MyJsonCodec() {
		super(MyJsonCodec.class.getClassLoader());
	}

And

    public MyJsonCodec() {
		super(Thread.currentThread().getContextClassLoader());
	}

And the setting the code like this

    RedissonClient redissonClient = Redisson.create();
    redissonClient.getConfig().setCodec(new MyJsonCodec());


However getting the following error


_java.lang.IllegalStateException: java.lang.NoSuchMethodException: com.github.dexecutor.redisson.MyJsonCodec.<init>(java.lang.ClassLoader)
	at org.redisson.executor.RemoteExecutorServiceImpl.<init>(RemoteExecutorServiceImpl.java:69)
	at org.redisson.RedissonExecutorService.registerWorkers(RedissonExecutorService.java:240)
	at org.redisson.RedissonNode.start(RedissonNode.java:150)
	at com.github.dexecutor.redisson.RedissonExecutionEngineIntegrationTest.testDistrutedExecutorService(RedissonExecutionEngineIntegrationTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NoSuchMethodException: com.github.dexecutor.redisson.MyJsonCodec.<init>(java.lang.ClassLoader)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at org.redisson.executor.RemoteExecutorServiceImpl.<init>(RemoteExecutorServiceImpl.java:67)
	... 26 more_

**Comment by mrniko** [comment]
Sorry, I mean:
```java
public MyJsonCodec() {
}

public MyJsonCodec(ClassLoader classLoader) {
      super(classLoader);
}

```

**Comment by mnadeem** [comment]
This time I am getting the following exception


23:48:30.969 [redisson-node-1-thread-1] ERROR org.redisson.RedissonRemoteService.invokeMethod 247 - Can't execute: RemoteServiceRequest [requestId=be6c9620f994d0e8c09837f598ef27d8, methodName=executeCallable, args=[com.github.dexecutor.redisson.MyCallable, [B@38795184, [B@24d6ce13], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=86400000], date=1474395510918]
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:240)
	at org.redisson.RedissonRemoteService.access$300(RedissonRemoteService.java:57)
	at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:199)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.github.dexecutor.redisson.MyCallable]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: io.netty.buffer.ByteBufInputStream@4085f7ff; line: 1, column: 54]
	at org.redisson.executor.RemoteExecutorServiceImpl.executeCallable(RemoteExecutorServiceImpl.java:176)
	at org.redisson.executor.RemoteExecutorServiceImpl.executeCallable(RemoteExecutorServiceImpl.java:161)
	... 12 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.github.dexecutor.redisson.MyCallable]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: io.netty.buffer.ByteBufInputStream@4085f7ff; line: 1, column: 54]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1130)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:168)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:74)
	at org.redisson.executor.RemoteExecutorServiceImpl.decode(RemoteExecutorServiceImpl.java:185)
	at org.redisson.executor.RemoteExecutorServiceImpl.executeCallable(RemoteExecutorServiceImpl.java:173)
	... 13 common frames omitted

**Comment by mnadeem** [comment]
Here is my Mixin

    public class MyCallableMixin extends MyCallable {
	
	@JsonCreator
	public MyCallableMixin(Integer data) {
		super(data);
	}

}


And here is my codec class

    public class MyJsonCodec extends JsonJacksonCodec {
	
	public MyJsonCodec() {
	}

	
	public MyJsonCodec(ClassLoader classLoader) {
	      super(classLoader);
	}

	protected void init(ObjectMapper objectMapper) {
	     super.init(objectMapper);
	     objectMapper.addMixIn(MyCallable.class, MyCallableMixin.class);
	}
}

**Comment by mrniko** [comment]
Does it work?

**Comment by mrniko** [comment]
As I remember @JsonCreator should be placed on factory method like:
```java
@JsonCreator
public MyCallable create() {
    return new MyCallable(null);
}
```

**Comment by mnadeem** [comment]
public class MyCallable  implements Callable<Long> {
	
	private Integer data;
	
	public MyCallable(Integer data) {
		this.data = data;
	}

    public Integer getData() {
		return data;
	}

	@Override
    public Long call() throws Exception {
        System.out.println("Executing " + data);
       
        return (long) (data * 2);
    }
}

Here is the mixin

    public abstract class MyCallableMixin  {
	
	@JsonCreator
	public MyCallableMixin(@JsonProperty("data") Integer data) {
	   System.out.println("Mixin called ***********");
	}
	

   }

Here is the driver

    public class JacksonMixIn {
	public static void main(String[] args) throws IOException {
              
		ObjectMapper mapper = new ObjectMapper();
        MyCallable c = new MyCallable(1);
        mapper.addMixIn(MyCallable.class, MyCallableMixin.class);
        String json = mapper.writeValueAsString(c);
		System.out.println(json);
		
		final MyCallable deserializedUser = mapper.readValue(json, MyCallable.class);
        System.out.println(deserializedUser);
    }
}

I deliberatly added public MyCallable .getData method (Otherwise things are breaking, not sure how to handle this case i.e, without adding public  MyCallable .getData method )

Things are working like a charm with the above test code.


**However When I integrate it with Redisson, it just break**


    RedissonClient redissonClient = Redisson.create();
		redissonClient.getConfig().setCodec(new MyJsonCodec());

		RedissonNodeConfig nodeConfig = new RedissonNodeConfig(redissonClient.getConfig());
		//nodeConfig.setCodec(new MyJsonCodec());
	    nodeConfig.setExecutorServiceThreads(5);
	    nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("myExecutor", 2));
	    RedissonNode node = RedissonNode.create(nodeConfig);
	    node.start();
		
		RExecutorService executorService = redissonClient.getExecutorService("myExecutor");
		java.util.concurrent.Future<Long> result = executorService.submit(new MyCallable(2));
		System.out.println("Result : "+result.get());



Here is my codec

    public class MyJsonCodec extends JsonJacksonCodec {

	public MyJsonCodec() {
		super(new ObjectMapper());
	}
	
	public MyJsonCodec(ClassLoader classLoader) {
        super(createObjectMapper(classLoader, new ObjectMapper()));
    }

	protected void init(ObjectMapper objectMapper) {
		super.init(objectMapper);
		objectMapper.addMixIn(MyCallable.class, MyCallableMixin.class);
	}
}

It is giving me the same issue

**Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.github.dexecutor.redisson.MyCallable]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)**

**Comment by mnadeem** [comment]
@mrniko I am not sure if it is a right decision to use Jackson for serialization/deserialization, kindly refer the following [Issue](https://github.com/FasterXML/jackson-databind/issues/1380#issuecomment-248753018)

**Comment by mrniko** [comment]
Actually the problem is here `objectMapper.addMixIn(MyCallable.class, MyCallableMixin.class);` this line should be called with class loaded from classloader used during task invocation

**Comment by mnadeem** [comment]
There are two problems to look on:

- Mixin not working
- Jackson can't serialize/deserialize immutable objects (plus no getter), due to which ExecutorService can't run immutable callables and any immutable objects (plus no getter) passed as parameter to callable.

**Comment by mrniko** [comment]
Which codec do you suggest to use to serialize immutable objects?

**Comment by mrniko** [comment]
I have opened a new issue related to mixin problem https://github.com/redisson/redisson/issues/627

**Comment by mnadeem** [comment]
Really really appreciate that,

Further it would be great, If there is a way to get around with issue number 2, 
for example it would really be a problem if the following callable cannot be distributed (As jackson is expecting getter for **data private member**)

    public class MyCallable  implements Callable<Long> {
    private Integer data;
    public MyCallable(Integer data) {
        this.data = data;
    }

    @Override
    public Long call() throws Exception {
        System.out.println("Executing " + data);

        return (long) (data * 2);
      }
    }

**Comment by mrniko** [comment]
> for example it would really be a problem if the following callable cannot be distributed (As jackson is expecting getter for data private member)

Actually private fields are available for reading by JacksonCodec in Redisson. This driven by [visibility setting](https://github.com/redisson/redisson/blob/d1d3e9098bdc86175c5d9ee366b385ae844e310b/redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java#L137)

**Comment by mnadeem** [comment]
Thanks a bundle @mrniko , that works :+1:
