### ISSUE TITLE
ClassNotFoundException on RLO expire

### ISSUE THREAD

**Issue by vortexthedev** [redisson/redisson#6215]
### Redis version

7.2.4

### Redisson version

3.37.0

### Redisson configuration

Default

### What is the Expected behavior?

Find the class of RLO when it expires using it's class name from map.

### What is the Actual behavior?
Class.forName() returns ClassNotFoundException because the registered class was loaded in different class loader.

```
[17:03:04 WARN]: Exception in thread "redisson-3-1" java.lang.IllegalStateException: Unable to resolve entity from [:redisson_live_object:{03a537666330343836372d633531392d343433342d393237642d343031646662356333363037}:ru.minecomplex.core.api.social.SocialRequest]
[17:03:04 WARN]: 	at org.redisson.RedissonLiveObjectService.resolveEntity(RedissonLiveObjectService.java:98)
[17:03:04 WARN]: 	at org.redisson.RedissonLiveObjectService.lambda$addExpireListener$0(RedissonLiveObjectService.java:84)
[17:03:04 WARN]: 	at org.redisson.PubSubPatternMessageListener.onPatternMessage(PubSubPatternMessageListener.java:83)
[17:03:04 WARN]: 	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:74)
[17:03:04 WARN]: 	at org.redisson.client.handler.CommandPubSubDecoder.lambda$enqueueMessage$2(CommandPubSubDecoder.java:223)
[17:03:04 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[17:03:04 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[17:03:04 WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:03:04 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[17:03:04 WARN]: Caused by: java.lang.ClassNotFoundException: ru.minecomplex.core.api.social.SocialRequest
[17:03:04 WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[17:03:04 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[17:03:04 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[17:03:04 WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[17:03:04 WARN]: 	at java.base/java.lang.Class.forName(Class.java:421)
[17:03:04 WARN]: 	at java.base/java.lang.Class.forName(Class.java:412)
[17:03:04 WARN]: 	at org.redisson.RedissonLiveObjectService.resolveEntity(RedissonLiveObjectService.java:96)
[17:03:04 WARN]: 	... 8 more
```

### Additional information

The solution is to try to get the class by it's name from our registered classes map, otherwise skip the event

```
 private void addExpireListener(CommandAsyncExecutor commandExecutor) {
        if (commandExecutor.getServiceManager().getLiveObjectLatch().compareAndSet(false, true)) {
            String pp = "__keyspace@" + commandExecutor.getServiceManager().getConfig().getDatabase() + "__:redisson_live_object:*";
            String prefix = pp.replace(":redisson_live_object:*", "");
            RPatternTopic topic = new RedissonPatternTopic(StringCodec.INSTANCE, commandExecutor, pp);
            topic.addListenerAsync(String.class, (pattern, channel, msg) -> {
                if (msg.equals("expired")) {
                    String name = channel.toString().replace(prefix, "");
                    Class<?> entity = resolveEntity(name);
                    // Prevent possible NPE because the class may be registered in another instance and not in this one.
                    if(entity == null)
                        return;
                    NamingScheme scheme = commandExecutor.getObjectBuilder().getNamingScheme(entity);
                    Object id = scheme.resolveId(name);
                    deleteExpired(id, entity);
                }
            });
        }
    }
    
    // Search for the class in our registered classes map of this instance
    private Class<?> resolveEntity(String name) {
        String className = name.substring(name.lastIndexOf(":")+1);
        return classCache.keySet().stream().filter(clazz -> clazz.getName().equals(className)).findAny().orElse(null);
    }
```

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by mrniko** [comment]
Fixed.
