### ISSUE TITLE
can't I find the IOUringSocketChannel class in my SpringBoot project

### ISSUE THREAD

**Issue by trifolium-x** [redisson/redisson#6217]
springBoot version: 2.7.18
redisson dependency:
```xml
<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>${redisson.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>redisson-spring-data-32</artifactId>
                    <groupId>org.redisson</groupId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-actuator</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-data-27</artifactId>
            <version>${redisson.version}</version>
        </dependency>
```

configuration Bean:
```java
/**
     * configuration redisson
     */
    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer().setConnectionMinimumIdleSize(Runtime.getRuntime().availableProcessors());
        config.setThreads(Runtime.getRuntime().availableProcessors());
        config.setNettyThreads(Runtime.getRuntime().availableProcessors() + 1);
        config.setCodec(new JsonJacksonCodec());

        String pact = "redis";
        String redisUrl = String.format("%s://%s:%s", pact, redisProperties.getHost(), redisProperties.getPort());
        // other config.useReplicatedServers()...x

        TransportMode transportMode = TransportMode.NIO;
        if (SystemUtil.getOsInfo().isLinux()) {
            transportMode = TransportMode.EPOLL;
        } else if (SystemUtil.getOsInfo().isMacOsX()) {
            transportMode = TransportMode.KQUEUE;
        }
        config.setTransportMode(transportMode)
                .useSingleServer()
                .setAddress(redisUrl)
                .setPassword(redisProperties.getPassword())
                .setDatabase(redisProperties.getDatabase())
                .setNameMapper(new NameMapper() {
                    @Override
                    public String map(String name) {
                        return appConfig.getRedisKeyPrefix() + name;
                    }

                    @Override
                    public String unmap(String name) {
                        return name.substring(appConfig.getRedisKeyPrefix().length());
                    }
                });

        config.setLockWatchdogTimeout(60 * 100);

        return Redisson.create(config);
    }
```
Start app NoClassDefFoundError:
```
Caused by: java.lang.NoClassDefFoundError: io/netty/incubator/channel/uring/IOUringSocketChannel
	at org.redisson.client.RedisClient.applyChannelOptions(RedisClient.java:183)
	at org.redisson.client.RedisClient.createBootstrap(RedisClient.java:139)
	at org.redisson.client.RedisClient.<init>(RedisClient.java:122)
	at org.redisson.client.RedisClient.create(RedisClient.java:82)
	at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:338)
	at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:326)
	at org.redisson.connection.MasterSlaveEntry.setupMasterEntry(MasterSlaveEntry.java:152)
	at org.redisson.connection.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:226)
	at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:196)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:220)
	at org.redisson.Redisson.<init>(Redisson.java:71)
	at org.redisson.Redisson.create(Redisson.java:116)
	at com.yuemia.java.services.springboot.configuration.RedisConfiguration.redissonClient(RedisConfiguration.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 90 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.netty.incubator.channel.uring.IOUringSocketChannel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 108 common frames omitted
```

**Comment by trifolium-x** [comment]
![image](https://github.com/user-attachments/assets/4e74cf5e-e208-46d3-95ec-ff4ee43bc22d)
When I specify to use NIO, this error does not occur.

**Comment by mrniko** [comment]
you need to add it manually:

```
<dependency>
    <groupId>io.netty.incubator</groupId>
    <artifactId>netty-incubator-transport-native-io_uring</artifactId>
    <version>0.0.25.Final</version>
</dependency>
```
