### ISSUE TITLE
ClassCastException using Kryo 5

### ISSUE THREAD

**Issue by Packsolite** [redisson/redisson#6233]
### Redis version

5.0.14

### Redisson version

3.37.0

### Redisson configuration

```
Config config = new Config();
config.useSingleServer()
		.setAddress(getRedisHost())
		.setConnectionMinimumIdleSize(1)
		.setSubscriptionConnectionMinimumIdleSize(1);
var virtualThreadPerTaskExecutor = Executors.newVirtualThreadPerTaskExecutor();
config.setExecutor(virtualThreadPerTaskExecutor);
config.setNettyExecutor(virtualThreadPerTaskExecutor);
config.setCodec(new Kryo5Codec() {
	private Kryo createKryo(ClassLoader classLoader) {
		Kryo kryo = KryoFactory.createWithCommonSerializers();
		if (classLoader != null) {
			kryo.setClassLoader(classLoader);
		}
		return kryo;
	}
});
```

### What is the Expected behavior?

To not print exceptions into the log

### What is the Actual behavior?

Since updating redisson to the latest version, we are seeing increased issues in our applications.
Most commonly, this exception is printed to the application logs:
```
[00:14:59] [/WARN]: java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
[00:14:59] [/WARN]: 	at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:616)
[00:14:59] [/WARN]: 	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:598)
[00:14:59] [/WARN]: 	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:586)
[00:14:59] [/WARN]: 	at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:199)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
[00:14:59] [/WARN]: 	at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:87)
[00:14:59] [/WARN]: 	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:222)
[00:14:59] [/WARN]: 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
[00:14:59] [/WARN]: 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
[00:14:59] [/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[00:14:59] [/WARN]: 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
[00:14:59] [/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[00:14:59] [/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:14:59] [/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:14:59] [/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:14:59] [/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:14:59] [/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[00:14:59] [/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:14:59] [/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:14:59] [/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[00:14:59] [/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[00:14:59] [/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[00:14:59] [/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[00:14:59] [/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[00:14:59] [/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:14:59] [/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:14:59] [/WARN]: 	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
[00:14:59] [/WARN]: 	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
[00:14:59] [/WARN]: Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
[00:14:59] [/WARN]: 	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:27)
[00:14:59] [/WARN]: 	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:23)
[00:14:59] [/WARN]: 	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:510)
[00:14:59] [/WARN]: 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:435)
[00:14:59] [/WARN]: 	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:216)
[00:14:59] [/WARN]: 	... 21 more
```

### Additional information

<dependency>
	<groupId>com.esotericsoftware</groupId>
	<artifactId>kryo</artifactId>
	<version>5.6.2</version>
	<scope>compile</scope>
</dependency>
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson</artifactId>
	<version>3.37.0</version>
	<scope>provided</scope>
</dependency>

**Comment by mrniko** [comment]
I need a code sample to reproduce it

**Comment by Packsolite** [comment]
Okay i managed to repro it with this code locally:
```
public class TestRedis implements MessageListener<Test.Message> {

  private RTopic topic;

  public void test(){
    topic.publishAsync(message);
  }

  public void initialize() {
    var redis = RedisUtil.getDefaultClient();
    topic= redis.getTopic("test");
    topic.addListener(Message .class, this);
  }
  
  @AllArgsConstructor
  @NoArgsConstructor
  @Getter
  public static class Message {
      private UUID senderUuid;
      private String senderName;
      private String format;
      private String message;
      private String server;
  }
}
```

**Comment by mrniko** [comment]
It's a codec issue. Try to use the same version of the codec and Kryo5Codec class

**Comment by mrniko** [comment]
I'll add serialization of SocketAddress and InetAddress objects.

**Comment by Packsolite** [comment]
> It's a codec issue. Try to use the same version of the codec and Kryo5Codec class

I didn't change the kryo nor the codec version. Just bumping redisson does this.

**Comment by mrniko** [comment]
Unable to reproduce with the code below:

```java
    @Test
    void xxx() {
        RSet<MyObject> set = client.getSet("test");
// added with 3.27.0
        for (int i = 0; i < 10; i++) {
            set.add(new MyObject("i" + i, "i" + i));
        }
// tested with 3.37.0
        for (int i = 0; i < 10; i++) {
            assert set.contains(new MyObject("i" + i, "i" + i));
        }
    }

    public static class MyObject {

        private String field1;
        private String field2;

        public MyObject() {

        }

        public MyObject(String field1, String field2) {
            this.field1 = field1;
            this.field2 = field2;
        }

        public String getField1() {
            return field1;
        }

        public void setField1(String field1) {
            this.field1 = field1;
        }

        public String getField2() {
            return field2;
        }

        public void setField2(String field2) {
            this.field2 = field2;
        }
    }
```

**Comment by Packsolite** [comment]
I can still reproduce it with redisson-3.41.0

**Comment by mrniko** [comment]
I'm afraid I can't help here without test code
