### ISSUE TITLE
RedisException "Unexpected exception while processing command" caused by NPE

### ISSUE THREAD

**Issue by yeah007** [redisson/redisson#6304]
**Redisson Configuration:** 
singleServer
Redisson version: 3.27.2
retryAttempts: 6
subscriptionConnectionPoolSize: 100
retryInterval: 3000
dnsMonitoringInterval: 60000
pingConnectionInterval: 50000

RedisException "Unexpected exception while processing command" occurred and it was caused by "Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "java.lang.Throwable.getCause()" is null"

The detail is:
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:353)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:168)
	at org.redisson.RedissonObject.get(RedissonObject.java:95)
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:152)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:231)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:315)
       ...
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "java.lang.Throwable.getCause()" is null
	at org.redisson.command.CommandAsyncService.lambda$handleNoSync$25(CommandAsyncService.java:916)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.redisson.command.RedisExecutor.handleError(RedisExecutor.java:623) 

It seems a bug and please take a look. Thanks.

**Comment by lyrric** [comment]
Can you try 3.39.0 ? It looks like has been fixed.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4153

**Comment by yeah007** [comment]
Sure, will upgrade to new version. Thanks all.

**Comment by yeah007** [comment]
Does 3.31.0 include this fix? @mrniko

**Comment by mrniko** [comment]
yes
