### ISSUE TITLE
redisson-spring-boot-starter-3.31.0 redis cluster with IPV6 init Error

### ISSUE THREAD

**Issue by bigstar119** [redisson/redisson#6313]
### Redis version

5.0

### Redisson version

3.31.0

### Redisson configuration

spring:
  redis:
    cluster:
      nodes:
        - [2001:db8::1]:6379
        - [2001:db8::2]::6379
        - [2001:db8::3]:6379
    password: yourpassword

### What is the Expected behavior?

RedissonClient init success

### What is the Actual behavior?

throw exception like beflow:
Exception in thread "main" java.lang.IllegalArgumentException: java.net.MalformedURLException: Invalid host: [[2001:db8::1]
	at org.redisson.misc.RedisURI.<init>(RedisURI.java:72)
	at com.neusoft.mid.distributelock.redission.biz.LockDemoService.main(LockDemoService.java:26)
Caused by: java.net.MalformedURLException: Invalid host: [[2001:db8::1]
	at java.base/java.net.URL.<init>(URL.java:679)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at org.redisson.misc.RedisURI.<init>(RedisURI.java:58)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Invalid host: [[2001:db8::1]
	at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:195)
	at java.base/java.net.URL.<init>(URL.java:674)
	... 4 more

### Additional information

RedisURI.parseUrl method will create duplicate [] ,when url= redis://[2001:db8::1]:6379
private String parseUrl(String uri) {
        int hostStartIndex = uri.indexOf("://") + 3;
        String urlHost = "http://" + uri.substring(hostStartIndex);
        String ipV6Host = uri.substring(hostStartIndex, uri.lastIndexOf(":"));
        if (ipV6Host.contains("@")) {
            ipV6Host = ipV6Host.split("@")[1];
        }
        if (ipV6Host.contains(":")) {
            **urlHost = urlHost.replace(ipV6Host, "[" + ipV6Host + "]");**
        }
        return urlHost;
    }

**Comment by mrniko** [comment]
you need to omit brackets in the address

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by bigstar119** [comment]
@mrniko sorry ,i can not omit the brackets. if i omit the brackets spring-data-redis will init error, because  org.springframework.data.redis.connection.RedisNode.fromString(String hostPortString)  can not process hostPortString without  brackets like: 2001:db8::1:6379
this problem`s keyponit is the conflict with redission and spring-boot-autoconfigre.
i think ipv6 with brackets is a normal solution, redission should be compatible with it

**Comment by bigstar119** [comment]
@mrniko Thanks
