### ISSUE TITLE
Unexpected exception while processing command

### ISSUE THREAD

**Issue by GX-Wang** [redisson/redisson#6314]
Env:

Redisson: 3.13.1
Redis: 7.2

Unexpected exception while processing command; nested exception is org.redisson.client.RedisException: Unexpected exception while processing command
org.springframework.dao.InvalidDataAccessApiUsageException: Unexpected exception while processing command; nested exception is org.redisson.client.RedisException: Unexpected exception while processing command
at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48)
at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:217)
at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:212)
at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:378)
at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:759)
at org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:493)
at org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:398)
at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57)
at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60)
at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53)
at com.testProj.service.BestRedisUtil$StringOps.get(BestRedisUtil.java:770)
at com.testProj.service.impl.EventPerceptionServiceImpl.saveRsi(EventPerceptionServiceImpl.java:168)
at com.testProj.service.impl.EventPerceptionServiceImpl$$FastClassBySpringCGLIB$$b6c119ff.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.spring framework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
at com.testproject.service.impl.EventPerceptionServiceImpl$$EnhancerBySpringCGLIB$$13796240.saveRsi(<generated>)
at com.testproject.mqtt.MqttMessageHandlerImpl.processMessage(MqttMessageHandlerImpl.java:43)
at com.testproject.mqtt.MqttMessageHandlerImpl.handleMessage(MqttMessageHandlerImpl.java:29)
at com.testproject.callback.MqttSubscriber.messageArrived(MqttSubscriber.java:43)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisException: Unexpected exception while processing command
at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:350)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:147)
at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:210)
... 36 common frames omitted

I have looked similar problems mentioned in Issues before. It is similar to **codec problem** [2723](https://github.com/redisson/redisson/issues/2723) and the bug reported by [3634](https://github.com/redisson/redisson/issues/3634).  But I don't know how to distinguish which issue they belong to.  Please help to confirm~

**Comment by mrniko** [comment]
> ... 36 common frames omitted

Please share the full stack trace

**Comment by GX-Wang** [comment]
This log was captured from the prod environment, but as you can see, it has been folded. o(╥﹏╥)o

**Comment by GX-Wang** [comment]
org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:350)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:147)
	at org.redisson.RedissonObject.get(RedissonObject.java:90)
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:221)
	at org.redisson.RedissonLock.lock(RedissonLock.java:175)
	at org.redisson.RedissonLock.lock(RedissonLock.java:156)
	at com.testProj.service.impl.EventPerceptionServiceImpl.saveRsi(EventPerceptionServiceImpl.java:297)
	at com.testProj.service.impl.EventPerceptionServiceImpl$$FastClassBySpringCGLIB$$b6c119ff.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.testProj.service.impl.EventPerceptionServiceImpl$$EnhancerBySpringCGLIB$$13796240.saveRsi(<generated>)
	at com.testProj.mqtt.MqttMessageHandlerImpl.processMessage(MqttMessageHandlerImpl.java:43)
	at com.testProj.mqtt.MqttMessageHandlerImpl.handleMessage(MqttMessageHandlerImpl.java:29)
	at com.testProj.callback.MqttSubscriber.messageArrived(MqttSubscriber.java:43)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
