### ISSUE TITLE
ClassCastException error happen when use sentinel server mode

### ISSUE THREAD

**Issue by princessd8251** [redisson/redisson#632]
Test code as below:

public class RedissonTest {

	public static void main(String[] args) {
		Config config = new Config();
		config.useSentinelServers()
		.setMasterName("atomic_counter_dev")
		.addSentinelAddress("127.0.0.1:26379");
		
		Redisson.create(config);
	}

}

Redisson 2.3.0
JDK 1.8.0_92

INFO  2016-09-26 14:45:46 [main] org.redisson.Version.logVersion:41 - Redisson 2.3.0
INFO  2016-09-26 14:45:47 [main] o.r.c.SentinelConnectionManager.<init>:80 - master: 127.0.0.1:6379 added
Exception in thread "main" java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.List
	at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:83)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:169)
	at org.redisson.Redisson.<init>(Redisson.java:103)
	at org.redisson.Redisson.create(Redisson.java:133)
	at com.coupang.reconciliation.configuration.RedissonTest.main(RedissonTest.java:14)

**Comment by mrniko** [comment]
Could you please turn on the trace mode and show the Redis replay?

**Comment by princessd8251** [comment]
trace is as below

2016-09-26 23:32:46,776 [main] [INFO ] org.redisson.Version - Redisson 2.3.0
2016-09-26 23:32:46,948 [nioEventLoopGroup-2-1] [TRACE] org.redisson.client.handler.CommandEncoder - channel: [id: 0x7ddb924d, L:/127.0.0.1:54016 - R:/127.0.0.1:26379] message: *3
$8
SENTINEL
$23
GET-MASTER-ADDR-BY-NAME
$18
atomic_counter_dev

2016-09-26 23:32:46,955 [nioEventLoopGroup-2-1] [TRACE] org.redisson.client.handler.CommandDecoder - channel: [id: 0x7ddb924d, L:/127.0.0.1:54016 - R:/127.0.0.1:26379] message: *2
$9
127.0.0.1
$4
6379

2016-09-26 23:32:46,957 [main] [INFO ] o.redisson.connection.SentinelConnectionManager - master: 127.0.0.1:6379 added
2016-09-26 23:32:46,958 [nioEventLoopGroup-2-1] [TRACE] org.redisson.client.handler.CommandEncoder - channel: [id: 0x7ddb924d, L:/127.0.0.1:54016 - R:/127.0.0.1:26379] message: *3
$8
SENTINEL
$6
SLAVES
$18
atomic_counter_dev

2016-09-26 23:32:46,958 [nioEventLoopGroup-2-1] [TRACE] org.redisson.client.handler.CommandDecoder - channel: [id: 0x7ddb924d, L:/127.0.0.1:54016 - R:/127.0.0.1:26379] message: *0

Exception in thread "main" java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.List
	at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:83)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:169)
	at org.redisson.Redisson.<init>(Redisson.java:103)
	at org.redisson.Redisson.create(Redisson.java:133)
	at com.coupang.main.RedissonTest.main(RedissonTest.java:17)

**Comment by mrniko** [comment]
Thanks! I have reproduced it. This is occurs only when there are no configured slaves.

**Comment by mrniko** [comment]
Fixed

**Comment by princessd8251** [comment]
Thanks.  2.4.0 is working perfectly for my case.
