### ISSUE TITLE
Spring Application Freezes When Redis Connection Fails in Redisson

### ISSUE THREAD

**Issue by abdelmouheimen** [redisson/redisson#6326]
When using Redisson with Spring for caching, if Redis is unavailable during a call to get(Object key, Class<T> type) in the RedissonCache class, the application becomes unresponsive because connection problems are not properly caught. Specifically, in the line value = map.get(key);, no exception is handled when a connection issue occurs, causing the application to freeze or fail to start. This behavior prevents the application from handling Redis outages gracefully and violates resilience principles. To resolve this, the map.get(key) call should be wrapped in a try-catch block to handle exceptions like RedisConnectionException and allow the application to log a warning and continue operation.

**Comment by mrniko** [comment]
The exception is rethrown in the latest version. Below is the output

```java
org.redisson.client.WriteRedisConnectionException: test1

	at org.redisson.spring.cache.RedissonCache.get(RedissonCache.java:83)
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:73)
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:524)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedValue(CacheAspectSupport.java:481)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:431)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:395)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.redisson.spring.cache.RedissonSpringCacheTest$SampleBean$$SpringCGLIB$$0.read(<generated>)
	at org.redisson.spring.cache.RedissonSpringCacheTest.testPutGet(RedissonSpringCacheTest.java:180)
```

**Comment by mrniko** [comment]
Unable to reproduce
