### ISSUE TITLE
Memory Leak Issue with Redisson's  AsyncSemaphore in a 3 Master 3 Slave Redis Cluster

### ISSUE THREAD

**Issue by liuayng201314** [redisson/redisson#6328]
Hello,

I'm encountering an issue with Redisson in our production environment. Here are the details of our setup:

JDK Version: 1.8
Redisson Version: 3.27.2
Redis Server Version: 5.0.3
Deployment: 3 Master 3 Slave Sharded Cluster
Web container：tomcat8.5
After about 1.5 months of operation, we've noticed that the memory size of the org.redisson.misc.AsyncSemaphore class has ballooned to 2.5GB, occupying a significant portion of our JVM's old generation space. This has led to continuous Full GC events. Upon analyzing the heap dump, the Leak Suspects report is as follows (attach the diagram here):

![image](https://github.com/user-attachments/assets/16bd6584-1f40-425c-a27f-33e226d98881)
![image](https://github.com/user-attachments/assets/3b7d3163-d19b-4194-b577-20675a0bcc35)
![image](https://github.com/user-attachments/assets/f495cf10-d8f8-481a-9c7e-16874973eca8)

Thread Details:
The thread stack for pool-14-thread-1 is as follows:
> at sun.misc.Unsafe.park(ZJ)V (Native Method)
at java.util.concurrent.locks.LockSupport.parkNanos(Ljava/lang/Object;J)V (LockSupport.java:215)
at java.util.concurrent.CompletableFuture$Signaller.block()Z (CompletableFuture.java:1709)
at java.util.concurrent.ForkJoinPool.managedBlock(Ljava/util/concurrent/ForkJoinPool$ManagedBlocker;)V (ForkJoinPool.java:3323)
at java.util.concurrent.CompletableFuture.timedGet(J)Ljava/lang/Object; (CompletableFuture.java:1788)
at java.util.concurrent.CompletableFuture.get(JLjava/util/concurrent/TimeUnit;)Ljava/lang/Object; (CompletableFuture.java:1928)
at org.redisson.RedissonLock.tryLock(JJLjava/util/concurrent/TimeUnit;)Z (RedissonLock.java:246)
at com.xcc.recinter.quartz.kakfa.KafkaResendSchedule.processTask()V (KafkaResendSchedule.java:76)
at com.xcc.recinter.quartz.ConfigurerScheduling.lambda$configureTasks$0()V (ConfigurerScheduling.java:49)
at com.xcc.recinter.quartz.ConfigurerScheduling$$Lambda$1614.run()V (Unknown Source)
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run()V (DelegatingErrorHandlingRunnable.java:54)
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run()V (ReschedulingRunnable.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; (Executors.java:511)
at java.util.concurrent.FutureTask.run()V (FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Ljava/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask;)V (ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V (ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (ThreadPoolExecutor.java:624)
at java.lang.Thread.run()V (Thread.java:750)

The thread appears to be part of a scheduled task that runs every minute (the task thread pool is set to 5, which might indicate duplicate task execution). The task first attempts to acquire a lock, processes the task, and then releases the lock. The relevant code snippet is as follows:

```
protected void processTask() {
    while (true){
        RLock resenfKafkaLock = null;
        boolean b = false;
        try {
            // Acquire lock from Redis
            RedissonClient redisClient = dynamicRedis.getRedisClient();
            resenfKafkaLock = redisClient.getLock(LockConstants.LOCK_RESEND);
            b = resenfKafkaLock.tryLock(10, 600, TimeUnit.SECONDS);
            if (b) {
                // Process tasks...
                // Return if no tasks
            }
        } catch (Exception ex) {
            logger.error("resend error {}", ex.toString());
        } finally {
            LockUtils.release(resenfKafkaLock, b);
        }
    }
}
```

```
public static void release( RLock r, boolean locked){
    if(r != null && r.isHeldByCurrentThread() && locked){
        r.unlock();
    }
}
```

Redisson's configuration is as follows:
[redisson.txt](https://github.com/user-attachments/files/18048586/redisson.txt)

I'm unsure why there are so many objects accumulating in java.util.concurrent.ConcurrentLinkedQueue. Any insights or suggestions on how to resolve this memory leak issue would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
ly

**Comment by mrniko** [comment]
Which Redisson objects do you use along with RLock?

**Comment by mrniko** [comment]
Unable to reproduce it using the code below. Can you?

```java
            ExecutorService e = Executors.newFixedThreadPool(1000);
            for (int i = 0; i < 1000; i++) {
                e.execute(() -> {
                    while (true){
                        RLock resenfKafkaLock = null;
                        boolean b = false;
                        try {
                            // Acquire lock from Redis
                            RedissonClient redisClient = redisson;
                            resenfKafkaLock = redisClient.getLock("test");
                            b = resenfKafkaLock.tryLock(10, 600, TimeUnit.SECONDS);
                            if (b) {
                                Thread.sleep(10000);
                                // Process tasks...
                                // Return if no tasks
                            }
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        } finally {
                            if(resenfKafkaLock != null && resenfKafkaLock.isHeldByCurrentThread() && b){
                                resenfKafkaLock.unlock();
                            }
                        }
                    }
                });
            }

            e.shutdown();
            e.awaitTermination(100000, TimeUnit.SECONDS);
```

**Comment by liuayng201314** [comment]
> Which Redisson objects do you use along with RLock?
> 
> Do you see any exceptions in logs?

The logs show no anomalies, but the program occasionally experiences high CPU usage, which is suspected to be related to full GC.

**Comment by mrniko** [comment]
Do you use only RedissonClient.getLock() method in your application?

**Comment by mrniko** [comment]
Can you try 3.40.1 version as well?

**Comment by liuayng201314** [comment]
> Unable to reproduce it using the code below. Can you?
> 
> ```java
>             ExecutorService e = Executors.newFixedThreadPool(1000);
>             for (int i = 0; i < 1000; i++) {
>                 e.execute(() -> {
>                     while (true){
>                         RLock resenfKafkaLock = null;
>                         boolean b = false;
>                         try {
>                             // Acquire lock from Redis
>                             RedissonClient redisClient = redisson;
>                             resenfKafkaLock = redisClient.getLock("test");
>                             b = resenfKafkaLock.tryLock(10, 600, TimeUnit.SECONDS);
>                             if (b) {
>                                 Thread.sleep(10000);
>                                 // Process tasks...
>                                 // Return if no tasks
>                             }
>                         } catch (Exception ex) {
>                             ex.printStackTrace();
>                         } finally {
>                             if(resenfKafkaLock != null && resenfKafkaLock.isHeldByCurrentThread() && b){
>                                 resenfKafkaLock.unlock();
>                             }
>                         }
>                     }
>                 });
>             }
> 
>             e.shutdown();
>             e.awaitTermination(100000, TimeUnit.SECONDS);
> ```



> Do you use only RedissonClient.getLock() method in your application?

I have also used other methods in the code, as follows:
```
public static String getStringValue(RedissonClient redissonClient, String key) {
    RBucket<String> bucket = redissonClient.getBucket(key, new StringCodec());
    return bucket.get();
}

public void resetAtomic() {
    RedissonClient redisClient = dynamicRedis.getRedisClient();
    RBucket<Object> bucket = redisClient.getBucket(LockConstants.GET_ATOMIC_LONG);
    bucket.set(0);
}

public Long incrementAndGet() {
    RedissonClient redisClient = dynamicRedis.getRedisClient();
    RAtomicLong atomicLong = redisClient.getAtomicLong(LockConstants.GET_ATOMIC_LONG);
    Long result = atomicLong.incrementAndGet() - 1;
    return result;
}
```
I believe the above methods should not cause the problem in question.

**Comment by liuayng201314** [comment]
> Unable to reproduce it using the code below. Can you?
> 
> ```java
>             ExecutorService e = Executors.newFixedThreadPool(1000);
>             for (int i = 0; i < 1000; i++) {
>                 e.execute(() -> {
>                     while (true){
>                         RLock resenfKafkaLock = null;
>                         boolean b = false;
>                         try {
>                             // Acquire lock from Redis
>                             RedissonClient redisClient = redisson;
>                             resenfKafkaLock = redisClient.getLock("test");
>                             b = resenfKafkaLock.tryLock(10, 600, TimeUnit.SECONDS);
>                             if (b) {
>                                 Thread.sleep(10000);
>                                 // Process tasks...
>                                 // Return if no tasks
>                             }
>                         } catch (Exception ex) {
>                             ex.printStackTrace();
>                         } finally {
>                             if(resenfKafkaLock != null && resenfKafkaLock.isHeldByCurrentThread() && b){
>                                 resenfKafkaLock.unlock();
>                             }
>                         }
>                     }
>                 });
>             }
> 
>             e.shutdown();
>             e.awaitTermination(100000, TimeUnit.SECONDS);
> ```

I have attempted to test in this manner, but was unable to reproduce the issue. I compared the code between versions 3.40.1 and 3.27.2 and noticed that the tryLockInnerAsync method has changed from calling evalWriteSyncedAsync to evalWriteSyncedNoRetryAsync. I am uncertain if this modification will resolve the problem.

I further inspected the contents of org.redisson.misc.AsyncSemaphore, where the java.util.concurrent.atomic.AtomicInteger instance counter is initialized to 0, and the ConcurrentLinkedQueue stores RedisCommand objects with names all being SUBSCRIBE.

I believe that all SUBSCRIBE commands are generated by tryLock, but I am not certain.

**Comment by mrniko** [comment]
In you heap dump I see a lot of RedisTimeoutExceptions but you say that there are no exceptions. I think logs weren't setup properly

**Comment by mrniko** [comment]
> I believe that all SUBSCRIBE commands are generated by tryLock, but I am not certain.

Right, try lock with timeout uses pubsub and Subscribe command

**Comment by liuayng201314** [comment]
> In you heap dump I see a lot of RedisTimeoutExceptions but you say that there are no exceptions. I think logs weren't setup properly

```
// Prepare the first batch
RBatch batch1 = redisClient.createBatch(BatchOptions.defaults());
for (Map.Entry<String, Set<String>> entry : redisAccountMapSet1.entrySet()) {
    RMapAsync<String, String> accountRMap = batch1.getMap(entry.getKey());
    RFuture<Map<String, String>> future = accountRMap.getAllAsync(entry.getValue());
    futures1.put(entry.getKey(), future);
}

// Prepare the second batch
RBatch batch2 = redisClient.createBatch(BatchOptions.defaults());
for (Map.Entry<String, Set<String>> entry : redisAccountMapSet2.entrySet()) {
    RMapAsync<String, String> accountRMap = batch2.getMap(entry.getKey());
    RFuture<Map<String, String>> future = accountRMap.getAllAsync(entry.getValue());
    futures2.put(entry.getKey(), future);
}

// Execute batches in parallel
CompletableFuture<Void> future1 = CompletableFuture.runAsync(batch1::execute, redisTriggerPoolHelper.getFastTriggerPool());
CompletableFuture<Void> future2 = CompletableFuture.runAsync(batch2::execute, redisTriggerPoolHelper.getFastTriggerPool());

// Wait for both futures to complete
CompletableFuture<Void> combinedFuture = CompletableFuture.allOf(future1, future2);
try {
    combinedFuture.get();
} catch (InterruptedException | ExecutionException e) {
    LOG.error("Batch execution failed: {}", e);
}
```
Recently, I have been developing another application that connects to the same Redis cluster and uses RBatch. This operation takes a long time. Is it possible that other applications' operations on the Redis server are taking a long time, causing this phenomenon in my application?

I see that there are a total of 11 instances of trylock in the current program, and they are not called frequently. Can RedisTimeoutExceptions cause the ConcurrentLinkedQueue in AsyncSemaphore to grow to such a large size?

**Comment by mrniko** [comment]
> In the stack trace, I see there are 2931 instances missing, and the printed detail message is: "Unable to acquire subscription lock

Are they all the same "Unable to acquire subscription lock ... " ?

**Comment by liuayng201314** [comment]
> > In the stack trace, I see there are 2931 instances missing, and the printed detail message is: "Unable to acquire subscription lock
> 
> Are they all the same "Unable to acquire subscription lock ... " ?

Yes, all org.redisson.client.RedisTimeoutException exceptions are due to "Unable to acquire subscription lock after 9997ms. Try to increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters."

The most frequent exception is java.util.concurrent.CancellationException, accounting for 2,874,381 entity objects.

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by liuayng201314** [comment]
> Fixed. Thanks for report

Thank you for your help. I have two more questions.
If the data in the listeners is released, will the counter's value ever decrease without subsequently increasing?
I have not been able to reproduce the issue. I tried directly throwing a RedisTimeoutException within the tryLock method code, but I still couldn't reproduce it.

**Comment by liuayng201314** [comment]
Hello,
I recently upgraded Redisson to version 3.40.2 without modifying any other Redisson configuration settings. After running for a while, I encountered a memory leak issue. The current log error message is as follows:
`[2025-04-28 22:09:06,377] 3796914500 [pool-7-thread-6] ERROR org.redisson.RedissonLock:264 - org.redisson.client.RedisTimeoutException: Unable to acquire connection for subscription after 3 attempts. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
java.util.concurrent.ExecutionException: org.redisson.client.RedisTimeoutException: Unable to acquire connection for subscription after 3 attempts. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:250)
	at com.xxx.app.quartz.kakfa.KafkaResendSchedule.processTask(KafkaResendSchedule.java:83)
	at com.xxx.app.quartz.AbstractBaskTask.run(AbstractBaskTask.java:39)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire connection for subscription after 3 attempts. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribeService.trySubscribe(PublishSubscribeService.java:486)
	at org.redisson.pubsub.PublishSubscribeService.lambda$connect$25(PublishSubscribeService.java:601)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:713)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:701)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:788)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:501)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted`
I captured the heap dump and found that there are a large number of SUBSCRIBE operations in the FastRemovalQueue, which is similar to the issue I experienced before.

![Image](https://github.com/user-attachments/assets/c1f51526-2cbe-4a6f-9510-9b42d1309ebb)

![Image](https://github.com/user-attachments/assets/235d7359-e415-4ccb-8156-b0d87e920f1e)

Could you please help me understand what might be causing this issue and how I can resolve it? Thank you!

**Comment by mrniko** [comment]
Fixed.

**Comment by mrniko** [comment]
Here is the test to reproduce it


```java
    @Test
    public void testReentrancy() throws InterruptedException {
        Config config = createConfig();
        config.useSingleServer()
                .setSubscriptionConnectionPoolSize(1)
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSubscriptionsPerConnection(1);

        RedissonClient redisson  = Redisson.create(config);

        for (int i = 0; i < 1000; i++) {
            RLock l = redisson.getLock("lock"+i);
            RFuture<Void> s = l.lockAsync();
        }

        ExecutorService ee = Executors.newFixedThreadPool(12);
        for (int i = 0; i < 1000; i++) {
            int k = i;
            ee.submit(() -> {
                RLock l = redisson.getLock("lock" + k);
                RFuture<Void> s = l.lockAsync();
                s.whenComplete((r, e) -> {
                    if (e != null) {
                        e.printStackTrace();
                    }
                });
            });
        }

        Thread.sleep(1000000);
    }
```

**Comment by liuayng201314** [comment]
**RedisTimeoutException and Memory Growth after Upgrading to Redisson 3.47.0**

**Description:**
After upgrading Redisson from version 3.44.0 to 3.47.0 and applying the fix for the WAITAOF issue (as described in Issue #6579), I encountered new problems during load testing.
Environment:
Redis Version: 5
Redisson Version: 3.47.0
Configuration: Spring Boot Java service using redisson-spring-boot-starter 3.47.0
Current Configuration:
subscriptionsPerConnection: 1
subscriptionConnectionMinimumIdleSize: 1
subscriptionConnectionPoolSize: 1

**Expected Behavior:**
No (or very few) errors recorded within our Redis instance.
Stable memory usage during load testing.

**Actual Behavior:**
RedisTimeoutException:
During load testing, I encountered the following exception:
org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 9995ms. Try to increase 'subscriptionTimeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.

**Stack trace:**

> at org.redisson.pubsub.PublishSubscribeService.lambda$timeout$23(PublishSubscribeService.java:488)
> at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:713)
> at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
> at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:701)
> at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:788)
> at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:501)
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Memory Growth:**
After the load test, memory usage continues to grow. The stack trace shows a large number of Subscribe commands.

**Load Testing Code:**
```
for (int i = 0; i < 1000; i++) {
    RLock l = redisClient1.getLock("lock" + i);
    RFuture<Void> s = l.lockAsync();
}

ExecutorService ee = Executors.newFixedThreadPool(12);
long m = Long.MAX_VALUE;
while (m > 0) {
    for (int i = 0; i < 1000; i++) {
        int k = i;
        ee.submit(() -> {
            RLock l = redisClient1.getLock("lock" + k);
            RFuture<Boolean> s = l.tryLockAsync(10, 600, TimeUnit.SECONDS);
            s.whenComplete((r, e) -> {
                if (e != null) {
                    e.printStackTrace();
                    logger.error("{}", e);
                }
            });
        });
    }
    try {
        Thread.sleep(10000);
    } catch (Exception ex) {
        logger.error("{}", ex);
    }
}
```

**Steps to Reproduce:**
Upgrade Redisson to version 3.47.0.
Apply the fix for the WAITAOF issue.
Run the provided load testing code.
Observe the RedisTimeoutException and memory growth.

**Additional Information:**
The memory growth seems to be related to the large number of Subscribe commands.

**Request:**
I would appreciate any guidance on how to prevent memory growth during load testing. Are there any specific configuration adjustments or code changes that could help mitigate these issues?

Thank you for your assistance.
