### ISSUE TITLE
`RedisTimeoutException` after upgrading to `3.39.0`

### ISSUE THREAD

**Issue by shiranyosef1** [redisson/redisson#6330]
### Redis version

7

### Redisson version

3.39.0

### Redisson configuration

**First Cluster (Cluster Mode Enabled):**  
- `nettyThreads`: 64  
- `connectionPoolMinIdleConnections`: 24  
- `connectionPoolSize`: 256  
- `retryInterval`: 1000  
- `pingConnectionInterval`: 20000  
- `connectionTimeout`: PT20S  
- `readTimeout`: PT5S  
- `retryAttempts`: 3  
- `serverMode`: CLUSTER  

**Second Cluster (Cluster Mode Enabled):**  
- `nettyThreads`: 64  
- `connectionPoolMinIdleConnections`: 24  
- `connectionPoolSize`: 64  
- `retryInterval`: 500  
- `pingConnectionInterval`: 30000  
- `connectionTimeout`: PT5S  
- `readTimeout`: PT0.6S  
- `retryAttempts`: 5  
- `serverMode`: CLUSTER  

### What is the Expected behavior?

Upgrading seccesfully from `3.25.0` to `3.39.0` 

### What is the Actual behavior?

After upgrading from `3.25.0` to `3.39.0`, I am experiencing frequent `org.redisson.client.RedisTimeoutException`.  
Examples include:  

1. **Stacktrace 1:**
    ```text
    org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check CPU usage of the JVM. Check that there are no blocking invocations in async/reactive/rx listeners or subscribeOnElements method. Check connection with Redis node: <REDACTED> for TCP packet drops. Try to increase nettyThreads setting.  
    Node source: NodeSource [slot=3310, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@<ID> [redisClient=[addr=rediss://<REDACTED>], channel=[id: 0x84326370, L:/<REDACTED> - R:<REDACTED>], currentCommand=CommandData [command=(ZRANGEBYSCORE), params: [expiration, 1733324699745, +inf, WITHSCORES], promise: java.util.concurrent.CompletableFuture@<ID>[Completed exceptionally: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (5000 ms) occurred after 3 retry attempts, is non-idempotent command: false. Check connection with Redis node: <REDACTED> for TCP packet drops or bandwidth limits. Try to increase nettyThreads and/or timeout settings. command: (ZRANGEBYSCORE), params: [expiration, 1733324699745, +inf, WITHSCORES], channel: [id: 0x84326370, L:/<REDACTED> - R:<REDACTED>]], codec=org.redisson.codec.JsonJacksonCodec], usage=1], command: (EVAL), params: [...], after 3 retry attempts
        at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:294)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:840)
    ```

2. **Stacktrace 2:**
    ```text
    org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check CPU usage of the JVM. Check that there are no blocking invocations in async/reactive/rx listeners or subscribeOnElements method. Check connection with Redis node: <REDACTED> for TCP packet drops. Try to increase nettyThreads setting.  
    Node source: NodeSource [slot=3310, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@<ID> [redisClient=[addr=rediss://<REDACTED>], channel=[id: 0xb2d80516, L:/<REDACTED> - R:<REDACTED>], currentCommand=CommandData [command=(ZRANGEBYSCORE), params: [expiration, 1733324699745, +inf, WITHSCORES], promise: java.util.concurrent.CompletableFuture@<ID>[Completed exceptionally: java.util.concurrent.CancellationException], codec=org.redisson.codec.JsonJacksonCodec], usage=1], command: (EVAL), params: [...], after 3 retry attempts
    ```

3. **Second Cluster Example:**
    ```text
    org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (600 ms) occurred after 5 retry attempts, is non-idempotent command: false. Check connection with Redis node: <REDACTED> for TCP packet drops or bandwidth limits. Try to increase nettyThreads and/or timeout settings. command: (EVAL), params: [...], channel: [id: 0x5e2127e6, L:/<REDACTED> - R:<REDACTED>]
        at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$10(RedisExecutor.java:450)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:706)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:694)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:781)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:494)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:840)

### Additional information

**What I've Tried:**  
- Increased client CPU  
- Increased `nettyThreads` from 32 to 64  

**Reverting to `3.25.0` resolved the issue.**

**Comment by mrniko** [comment]
Can you try to upgrade to 3.40.1 version and share first 10 exceptions?

**Comment by shiranyosef1** [comment]
This is production env, I can't upgrade. 
I have only the exceptions from the `3.39.0` attempt

**Comment by mrniko** [comment]
Is there any code to reproduce it?

**Comment by shashank412** [comment]
This is very easy to reproduce. When the server is running in a cluster mode and when a client tries to hit the same cache concurrently in multiple threads then this is replicated.

**Comment by mrniko** [comment]
@shashank412 

Can you share the code to reproduce it?

**Comment by shashank412** [comment]
@mrniko 

NOTE : We are able to replicate the issue only when the redis cluster is in a different machine than that of the client program. Running in a cluster mode.

This is the core logic used to simulate this issue. 

public static void executeLoadTestWithThreads(String cacheName, String key, int totalRequests, int threadCount) {
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        CountDownLatch startLatch = new CountDownLatch(1);
        CountDownLatch finishLatch = new CountDownLatch(threadCount);
      
        long startTime = System.currentTimeMillis();
        
        try {
            CONSOLE.info("Starting " + threadCount + " threads to execute " + totalRequests + " total requests...");
            
            // Calculate requests per thread
            int requestsPerThread = totalRequests / threadCount;
            int remainingRequests = totalRequests % threadCount;
            
            // Create and submit threads
            for (int i = 0; i < threadCount; i++) {
                final int threadId = i + 1;
                // Distribute remaining requests among first few threads
                final int threadRequests = requestsPerThread + (i < remainingRequests ? 1 : 0);
                
                executor.submit(() -> {
                    try {
                        // Wait for start signal
                        startLatch.await();
                        
                        // Execute requests for this thread
                        for (int j = 0; j < threadRequests; j++) {
                            try {
                                Object retrieved = redisUtil.getFromHash(cacheName, key); //underneath calls redissonClient.getMap(cacheName); followed by Object value = map.get(key);
                                CONSOLE.debug("Thread " + threadId + " - Request " + (j + 1) + "/" + threadRequests
                                        + " - Retrieved: " + retrieved);
                            } catch (Exception e) {
                                log.error("Thread " + threadId + " - Error in request " + (j + 1), e);
                                CONSOLE.error("Thread " + threadId + " - Error: " + e.getMessage());
                            }
                        }
                        
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        log.error("Thread " + threadId + " interrupted", e);
                    } finally {
                        finishLatch.countDown();
                    }
                });
            }
            
            // Start all threads
            startLatch.countDown();
            CONSOLE.info("All threads started! Waiting for completion...");
            
            // Wait for all threads to complete
            finishLatch.await();
            
            long endTime = System.currentTimeMillis();
            long totalTime = endTime - startTime;
            
            CONSOLE.info("Load test completed!");
            CONSOLE.info("Total threads: " + threadCount);
            CONSOLE.info("Total requests: " + totalRequests);
            CONSOLE.info("Total time: " + totalTime + "ms");
            CONSOLE.info("Average time per request: " + (totalTime / totalRequests) + "ms");
            CONSOLE.info("Requests per second: " + (totalRequests * 1000 / totalTime));
            
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            log.error("Load test interrupted", e);
            CONSOLE.error("Load test interrupted: " + e.getMessage());
        } finally {
            executor.shutdown();
            try {
                if (!executor.awaitTermination(30, java.util.concurrent.TimeUnit.SECONDS)) {
                    executor.shutdownNow();
                }
            } catch (InterruptedException e) {
                executor.shutdownNow();
                Thread.currentThread().interrupt();
            }
        }
    }

**Comment by shashank412** [comment]
Hi @mrniko,

were you able to replicate the issue with the above code?

**Comment by mrniko** [comment]
> Hi [@mrniko](https://github.com/mrniko),
> 
> were you able to replicate the issue with the above code?

@seakider 

Any update?

**Comment by seakider** [comment]
@shashank412 
Unable to reproduce the issue with the above code with Redis clusters and Redisson clients on different machines.

**Comment by mrniko** [comment]
@shashank412 

Can you share the Redisson config?

**Comment by shashank412** [comment]
@mrniko and @seakider 

performanceMode: LOWER_LATENCY_AUTO
clusterServersConfig:
  idleConnectionTimeout: '300000'
  connectTimeout: '5000'
  timeout: '30000'
  retryAttempts: 3
  retryInterval: 1000
  failedSlaveReconnectionInterval: 5000
  failedSlaveNodeDetector: !<org.redisson.client.FailedConnectionDetector> {}
  sslEnableEndpointIdentification: false
  sslProvider: JDK
  password:
  subscriptionsPerConnection: '10'
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: '30'
  slaveConnectionPoolSize: '70'
  masterConnectionMinimumIdleSize: '30'
  masterConnectionPoolSize: '70'
  readMode: 'MASTER_SLAVE'
  subscriptionMode: 'MASTER'
  subscriptionConnectionMinimumIdleSize: '5'
  subscriptionConnectionPoolSize: '20'
  nodeAddresses:
    - 'redis://******.[cache.amazonaws.com:12147](http://cache.amazonaws.com:12147/)'
  scanInterval: '10000'
  pingConnectionInterval: 10000
  keepAlive: true
  tcpNoDelay: true
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 8
codec: !<org.redisson.codec.SnappyCodecV2> {}
registrationKey: *********
keepPubSubOrder: false
transportMode: 'NIO'

**Comment by mrniko** [comment]
change performanceMode: NORMAL and try to set nettyThreads: 32 or 64 or 128
