### ISSUE TITLE
Redisson cannot acquire connection when executing acquireConnection method matches a java.lang.StackOverflowError

### ISSUE THREAD

**Issue by yxd993293** [redisson/redisson#6335]
### Redis version

6.2.5

### Redisson version

3.32.0

### Redisson configuration

nt totalPoolSize = redisProperties.getJedis().getPool().getMaxActive();
int totalIdleSize = redisProperties.getJedis().getPool().getMaxIdle();
int subscriptionConnectionPoolSize = totalPoolSize / 3;
int subscriptionConnectionMinimumIdleSize = totalIdleSize / 3;
int masterConnectionPoolSize = totalPoolSize - subscriptionConnectionPoolSize;
int masterConnectionMinimumIdleSize = totalIdleSize - subscriptionConnectionMinimumIdleSize;
config.useClusterServers()
.addNodeAddress(nodes)
.setConnectTimeout(timeout)
.setPassword(redisProperties.getPassword())
.setMasterConnectionPoolSize(masterConnectionPoolSize)
.setMasterConnectionMinimumIdleSize(masterConnectionMinimumIdleSize)
.setSlaveConnectionPoolSize(0)
.setSlaveConnectionMinimumIdleSize(0)
.setRetryAttempts(10)
.setSubscriptionConnectionPoolSize(subscriptionConnectionPoolSize)
.setSubscriptionConnectionMinimumIdleSize(subscriptionConnectionMinimumIdleSize);

### What is the Actual behavior?

In my program, another recursive call occurred, which led to a java.lang.StackOverflowError. Before the java.lang.StackOverflowError occurred, a connection from Redisson was obtained, which ultimately caused subsequent requests to be unable to obtain a connection.
Exception mesasge:

**Comment by yxd993293** [comment]
Exception messasge:
java.lang.StackOverflowError: null
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at java.util.concurrent.CompletionException.<init>(CompletionException.java:88)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:673)
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683)
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010)
	at org.redisson.connection.ConnectionsHolder.acquireConnection(ConnectionsHolder.java:205)
	at org.redisson.connection.pool.ConnectionPool.acquireConnection(ConnectionPool.java:113)
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:51)
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:564)
	at org.redisson.connection.SingleEntry.connectionReadOp(SingleEntry.java:49)
	at org.redisson.command.RedisExecutor.connectionReadOp(RedisExecutor.java:817)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:733)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:136)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:658)
	at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:395)
After this error occurred, ClientConnectionsEntry.connectionsHolder is all in used. The all usage of connections is euqals 1. 

[arthas@1]$ vmtool --action getInstances --className org.redisson.connection.ClientConnectionsEntry --express "instances[0].connectionsHolder.allConnections" 
@ConcurrentLinkedQueue[
    @RedisConnection[RedisConnection@1057963733 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0xab349684, L:/172.28.203.92:40752 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
    @RedisConnection[RedisConnection@1865625846 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0x79a65734, L:/172.28.203.92:40768 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
    @RedisConnection[RedisConnection@69417238 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0x2290993d, L:/172.28.203.92:40802 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
    @RedisConnection[RedisConnection@2018131057 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0x8ffeb07c, L:/172.28.203.92:40816 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
    @RedisConnection[RedisConnection@100533160 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0x013299dd, L:/172.28.203.92:40822 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
    @RedisConnection[RedisConnection@1817104927 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0xc34a88c6, L:/172.28.203.92:40824 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
    @RedisConnection[RedisConnection@1669856782 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0x22f24c4b, L:/172.28.203.92:40828 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
    @RedisConnection[RedisConnection@682202370 [redisClient=[addr=redis://172.28.203.92:8379], channel=[id: 0x3a79e5de, L:/172.28.203.92:40836 - R:172.28.203.92/172.28.203.92:8379], currentCommand=null, usage=1]],
]

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5971
