### ISSUE TITLE
StackOverflowError  org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd

### ISSUE THREAD

**Issue by MichealJou** [redisson/redisson#6352]
java.lang.StackOverflowError
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.zAdd(DefaultedRedisConnection.java:863)
use :
   Spring Boot: 2.3.5.RELEASE
   spring-cloud: Hoxton.SR9
@mrniko

**Comment by mrniko** [comment]
Make sure that you have redisson-spring-data-23 in classpath, if you use Spring Data Redis v.2.3.x

**Comment by MichealJou** [comment]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/0de49b53-1e68-4980-9a29-14ebab23748d" />

Use is this: have redisson-spring-data-25
Introduce this : [3.16.5](org.redisson:redisson-spring-boot-starter:3.16.5)

**Comment by mrniko** [comment]
for Spring Data Redis v.2.3.x you need to exclude redisson-spring-data-25 and add redisson-spring-data-23

**Comment by MichealJou** [comment]
thanks
