### ISSUE TITLE
Unexpected java.util.concurrent.CancellationException in Redisson 3.30.0

### ISSUE THREAD

**Issue by hs3733250** [redisson/redisson#6358]
I am encountering an issue while using Redisson version 3.30.0. The following error frequently appears in the logs:

2024-12-25 10:32:30.281 ERROR [TID:N/A] [redisson-timer-4-1] org.redisson.command.RedisExecutor Line:207 -->> java.util.concurrent.CancellationException
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
    at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
    at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$11(RedisExecutor.java:423)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.CancellationException: null
    ... 8 common frames omitted

Additional Information:
Is this a known issue, or could it be related to my configuration?
How can I debug or mitigate this problem?
Thank you for your help!

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5913
