### ISSUE TITLE
Trouble while upgrading redisson library

### ISSUE THREAD

**Issue by savvadem** [redisson/redisson#6362]
Hi redisson team
Right now i am upgrading redisson library version  in our old service from version 3.17.4 to 3.29.0.

But i cant start service after upgrade with following problem:
```java 
Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class org.redisson.Redisson: Common causes of this problem include using a final class or a non-visible class
	at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:230) ~[spring-aop-6.1.15.jar:6.1.15]
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:163) ~[spring-aop-6.1.15.jar:6.1.15]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[spring-aop-6.1.15.jar:6.1.15]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.buildProxy(AbstractAutoProxyCreator.java:519) ~[spring-aop-6.1.15.jar:6.1.15]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:466) ~[spring-aop-6.1.15.jar:6.1.15]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:371) ~[spring-aop-6.1.15.jar:6.1.15]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:320) ~[spring-aop-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:438) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1809) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.15.jar:6.1.15]
	... 29 common frames omitted
Caused by: java.lang.IllegalArgumentException: Cannot subclass final class org.redisson.Redisson
```
I checked source code and  `Redisson` is now final, after that if found this in my code

```java
   @Pointcut("target(org.redisson.api.RedissonClient)")
    private void anyRedissonClientMethods() { 
    }
````
This code is for taking metrics to grafana.
The question is, that i need this metrics in grafana, but i dont know how to fix this properly?

**Comment by nfawcett** [comment]
This is similar to https://github.com/redisson/redisson/issues/5556. The suggestion is to implement RedissonClient interface, which I don't think is feasible.

**Comment by mrniko** [comment]
In you case you need to implement a delegator pattern

**Comment by amayamath** [comment]
@Pointcut("target(org.redisson.api.RedissonClient)")
    private void anyRedissonClientMethods() { 
    }

**Comment by savvadem** [comment]
> This issue can be solved by implementing a delegator pattern.

Looks like i need to exclude autoconfiguration and etc to acheive this, and it will be troublesome for upgrading later every time to check is everything alright and autoconfiguration didnt changed. Feels bad to do like this.

**Comment by savvadem** [comment]
@mrniko Feel free to close issue, if there is no other way than wrap redissonclient with my own wrapper.
