### ISSUE TITLE
redis list operation throw exception

### ISSUE THREAD

**Issue by lijunyong** [redisson/redisson#657]
127.0.0.1:6379> lpush name li lee zhang si
(integer) 4
127.0.0.1:6379> lrange name 0 -1
1) "si"
2) "zhang"
3) "lee"
4) "li"
127.0.0.1:6379> 

 RedissonClient redisson = Redisson.create(config);
        RList<String> list = redisson.getList("name");
        ListIterator<String> iterator = list.listIterator();
        while(iterator.hasNext()){
            System.out.println(iterator.next());
        }

Exception in thread "main" org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:305)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:150)
	at org.redisson.RedissonObject.get(RedissonObject.java:55)
	at org.redisson.RedissonList.getValue(RedissonList.java:301)
	at org.redisson.RedissonList$1.hasNext(RedissonList.java:470)
	at com.omniprimeinc.redis.RedisList.main(RedisList.java:18)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'si': was expecting ('true', 'false' or 'null')
 at [Source: io.netty.buffer.ByteBufInputStream@3c130745; line: 1, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)

**Comment by mrniko** [comment]
You should use `StringCodec` instead of default JacksonJSON codec
