### ISSUE TITLE
NullPointerException in CommandDecoder

### ISSUE THREAD

**Issue by smigfu** [redisson/redisson#667]
Hi,

under heavy load we experience a NPE in the CommandDecoder sometimes [1]. Do you have a guess about what could be going wrong here?

Thanks.

Cheers,
Philipp 

[1]
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422) [74:io.netty.codec:4.1.1.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [74:io.netty.codec:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418) [79:io.netty.transport:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390) [79:io.netty.transport:4.1.1.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [76:io.netty.common:4.1.1.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) [76:io.netty.common:4.1.1.Final]
	at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.NullPointerException
	at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:397) ~[275:redisson:2.2.24]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:269) ~[275:redisson:2.2.24]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110) ~[275:redisson:2.2.24]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367) ~[74:io.netty.codec:4.1.1.Final]
	... 20 more

**Comment by mrniko** [comment]
Fixed

**Comment by smigfu** [comment]
Thanks for the quick response 👍
