### ISSUE TITLE
redisson Sentinel error

### ISSUE THREAD

**Issue by lijunyong** [redisson/redisson#675]
```
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson</artifactId>
    <version>2.4.0</version>
</dependency>
```

java:
```
Config config = new Config();
        config.useSentinelServers()
               .setMasterName("mymaster")
               .addSentinelAddress("192.168.109.5:26379");
        RedissonClient redisson = Redisson.create(config);
```

Exception in thread "main" org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 5 were initialized. Server: /127.0.0.1:6380
	at org.redisson.connection.pool.ConnectionPool$2.operationComplete(ConnectionPool.java:120)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:75)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:257)
	at org.redisson.connection.pool.ConnectionPool.access$200(ConnectionPool.java:51)
	at org.redisson.connection.pool.ConnectionPool$3.operationComplete(ConnectionPool.java:221)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:75)
	at org.redisson.connection.ClientConnectionsEntry$1.operationComplete(ClientConnectionsEntry.java:149)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:75)
	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:159)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6380
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	... 3 more

**Comment by mrniko** [comment]
Please check network connection with /127.0.0.1:6380

**Comment by lijunyong** [comment]
the master slave and sentinel On the same machine(192.168.109.5)

**Comment by mrniko** [comment]
Could you please execute `SENTINEL GET-MASTER-ADDR-BY-NAME` and `SENTINEL SLAVES` commands and give their output?

**Comment by lijunyong** [comment]
@mrniko 
```
[root@node1 redis]# ./bin/redis-cli -p 26379
127.0.0.1:26379> SENTINEL get-master-addr-by-name mymaster
1) "192.168.109.5"
2) "6379"
127.0.0.1:26379> 
```
```
127.0.0.1:26379> SENTINEL slaves mymaster
1)  1) "name"
    2) "192.168.109.5:6380"
    3) "ip"
    4) "192.168.109.5"
    5) "port"
    6) "6380"
    7) "runid"
    8) ""
    9) "flags"
   10) "s_down,slave,disconnected"
   11) "link-pending-commands"
   12) "848"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "826935"
   17) "last-ok-ping-reply"
   18) "826935"
   19) "last-ping-reply"
   20) "826935"
   21) "s-down-time"
   22) "796892"
   23) "down-after-milliseconds"
   24) "30000"
   25) "info-refresh"
   26) "1476978739201"
   27) "role-reported"
   28) "slave"
   29) "role-reported-time"
   30) "826935"
   31) "master-link-down-time"
   32) "0"
   33) "master-link-status"
   34) "err"
   35) "master-host"
   36) "?"
   37) "master-port"
   38) "0"
   39) "slave-priority"
   40) "100"
   41) "slave-repl-offset"
   42) "0"
2)  1) "name"
    2) "127.0.0.1:6380"
    3) "ip"
    4) "127.0.0.1"
    5) "port"
    6) "6380"
    7) "runid"
    8) "5d42cb68660c0e202a06c553c9d5f7d3dd7c73c9"
    9) "flags"
   10) "slave"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "875"
   19) "last-ping-reply"
   20) "875"
   21) "down-after-milliseconds"
   22) "30000"
   23) "info-refresh"
   24) "3764"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "826935"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "ok"
   33) "master-host"
   34) "192.168.109.5"
   35) "master-port"
   36) "6379"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "165747"
127.0.0.1:26379> 
```

**Comment by mrniko** [comment]
Could you please turn on Redisson debug level to `trace` and show its output too?

**Comment by mrniko** [comment]
Something wrong with Sentinel configuration. It shows two records for same Redis instance.

**Comment by lijunyong** [comment]
Thanks,I find the error Sentinel configuration
