### ISSUE TITLE
2 different NPEs under heavy load

### ISSUE THREAD

**Issue by smigfu** [redisson/redisson#679]
Hey, I experienced two more NPE if I am using Redisson under load. Do you have an idea what might be the problem? Thx Philipp

`2016-10-25T08:24:20,935 | WARN | LABS | i-5a270ba2 | 2016.0.0.426 | valid_b5099182-52b6-b069-65c6-65fd8b26d7a9 | XXX-Redis-Autobahn-1-2 | io.netty.channel.DefaultChannelPipeline | 2016-10-25T08:23:13,631_twoUserCollaborate_80c54f49-768d-2eee-bcd5-45d1337684b1 | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422) [78:io.netty.codec:4.1.6.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [78:io.netty.codec:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [83:io.netty.transport:4.1.6.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [80:io.netty.common:4.1.6.Final]
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [80:io.netty.common:4.1.6.Final]
at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.NullPointerException
at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:414) ~[285:redisson:2.4.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:280) ~[285:redisson:2.4.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:118) ~[285:redisson:2.4.0]
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367) ~[78:io.netty.codec:4.1.6.Final]
... 20 more`

and

`2016-10-25T08:24:28,370 | WARN | LABS | i-af1e993c | 2016.0.0.426 | valid_0418a877-2e5f-ea68-18d6-76def289edbe | XXX-Redis-Autobahn-1-2 | io.netty.channel.DefaultChannelPipeline | 2016-10-25T08:23:13,631_twoUserCollaborate_1f6eab22-4072-5c98-9e8e-12accb75d2cf | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422) [78:io.netty.codec:4.1.6.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [78:io.netty.codec:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [83:io.netty.transport:4.1.6.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [80:io.netty.common:4.1.6.Final]
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [80:io.netty.common:4.1.6.Final]
at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.NullPointerException
at org.redisson.client.handler.CommandDecoder.selectDecoder(CommandDecoder.java:414) ~[285:redisson:2.4.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:280) ~[285:redisson:2.4.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:118) ~[285:redisson:2.4.0]
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367) ~[78:io.netty.codec:4.1.6.Final]
... 20 more`

**Comment by smigfu** [comment]
I have a 3rd exception message, though I am not sure if this is related:

2016-10-25T08:24:28,360 | WARN | LABS | i-af1e993c | 2016.0.0.426 | valid_0418a877-2e5f-ea68-18d6-76def289edbe | XXX-Redis-Autobahn-1-2 | io.netty.channel.DefaultChannelPipeline | 2016-10-25T08:23:13,631_twoUserCollaborate_1f6eab22-4072-5c98-9e8e-12accb75d2cf | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: *Can't decode replay* 
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422) [78:io.netty.codec:4.1.6.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [78:io.netty.codec:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [83:io.netty.transport:4.1.6.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [83:io.netty.transport:4.1.6.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [80:io.netty.common:4.1.6.Final]
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [80:io.netty.common:4.1.6.Final]
at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.IllegalStateException: Can't decode replay 
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[285:redisson:2.4.0]
at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:118) ~[285:redisson:2.4.0]
at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367) ~[78:io.netty.codec:4.1.6.Final]
... 20 more

**Comment by mrniko** [comment]
Which Redisson version do you use? I think this is the same issue https://github.com/redisson/redisson/issues/667

**Comment by mrniko** [comment]
Please upgrade 2.5.0 version. It has already a fix for CommandDecoder:414 line

**Comment by smigfu** [comment]
Oh, sorry I thought it was backported to 2.4.0 as well. I will upgrade to 2.5.0 (or even 3.0.0) and see if the problem persists. Thanks!
