### ISSUE TITLE
Don't log byte arrays in CommandDecoder

### ISSUE THREAD

**Issue by smigfu** [redisson/redisson#682]
Hi,
we sometimes run into OutOfMemoryException while Redisson is trying to log a warning, since it includes the content in the log message [1]. Would it be possible to check for the instance type and in case of byte[] just log something else? I.e.
`
log.warn("response has been skipped due to timeout! channel: {}, command: {}, result: {}",
                         channel, data, result instanceof byte[] ? result.hashCode() : result);
`
Or omit the content in the WARN-log and do a second INFO-log containing the data. So you can toggle this via the log level?
`
log.warn("response has been skipped due to timeout! channel: {}, command: {}", channel, data);
log.info("skipped response data for timeout {}", result); 
`
From what I can see that's the only place where large content might be locked, though I am not sure about the log.error in CommandDecoder#decode, as it is using the CommandData.toString() content. 

Thanks,
Philipp

[1]
`
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.OutOfMemoryError: Java heap space
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at org.slf4j.helpers.MessageFormatter.byteArrayAppend(MessageFormatter.java:342)
    at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:276)
    at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:227)
    at org.ops4j.pax.logging.slf4j.Slf4jLogger.warn(Slf4jLogger.java:715)
    at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:384)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:283)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:125)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
    ... 18 more
`

**Comment by smigfu** [comment]
Another path where this could happen is at CommandAsyncServices, when the RedisTimeoutException is being created (line 521 - 527). When creating the exception message the params-details are being appended to the message. 

```
if (details.getAttempt() == connectionManager.getConfig().getRetryAttempts()) {
                    if (details.getException() == null) {
                        details.setException(new RedisTimeoutException("Command execution timeout for command: " + command + " with params: " + Arrays.toString(details.getParams())));
                    }
                    details.getAttemptPromise().tryFailure(details.getException());
                    return;
                }
```

Since we sometimes move some larger binaries into the cache this can add up to some huge strings which remain in memory.

Paired with the fact that we use async-logging our service dies a painful death when the Redis connection becomes a little sloppy and lots of RedisTimeoutExceptions are happening because they all are stucked in memory :) 

I have turned of the logging for the case above, but in this case it doesn't help. Would it  be possible to only hand in the params into the exception and construct the message only on demand (maybe with the same check for large binaries as above)?

**Comment by smigfu** [comment]
If you want to I can create a PR for this

**Comment by mrniko** [comment]
Sure! Contributions are always welcome
