### ISSUE TITLE
CommandAsyncService blocks indefinitely 

### ISSUE THREAD

**Issue by smigfu** [redisson/redisson#683]
Hi,
I have a thread stuck in the CommandAsyncService#get() indefinitely waiting for the CountdownLatch. I don't have a particular repro case but this happens every once in a while on our servers (under load). Redis itself is still delivering events and the instance receives objects on other threads as well.
Would it make sense instead of waiting indefinitely on the latch to only wait as long as the timeout is configured (as a safe belt) and abort the action if there hasn't been any success/failure by then? 
Cheers,
Philipp

Redisson-Version: 3.0.0
Redis-Server: ElasticCache w/ engine 3.2.4
Redis-Config: SingleServerConfig w/ mostly the default values

`
java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x000000031c2237d0> (a java.util.concurrent.CountDownLatch$Sync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
    at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:133)
    at org.redisson.RedissonObject.get(RedissonObject.java:55)
    at org.redisson.RedissonBucket.get(RedissonBucket.java:91)
`

**Comment by mrniko** [comment]
> Would it make sense instead of waiting indefinitely on the latch to only wait as long as the timeout is configured (as a safe belt) and abort the action if there hasn't been any success/failure by then? 

Redisson has response timeout and retry attempt timeout

**Comment by mrniko** [comment]
Could you provide your Redisson config?

**Comment by smigfu** [comment]
The config is pretty much the default for SingleServerConfig:

singleServerConfig:
  retryAttempts: 1
  address: XYZ

**Comment by mrniko** [comment]
Do you async callbacks provided by RFeature object?

**Comment by smigfu** [comment]
We do use two Redisson instances (for retrieval and storing). They share the same EventGroupLoop but besides that are completely decoupled.

1. Retrieval: Uses only synchronous methods. Usually in the form getClient().getBucket(key, codec).get(); This is where the problem above occurs.

2. Storing: Is a bachted executor which run every X ms (usually 100ms) and takes up to X (capped at 50 objects). This is the only place where we use async callbacks:
```
final RBatch rBatch = redissonClient.createBatch();
final Promise<Void> promise = batchPromise.getAndSet(ImmediateEventExecutor.INSTANCE.newPromise());
        rBatch.executeSkipResultAsync().handleAsync((result, throwable) ->
        {
            if (throwable != null)
            {
                promise.tryFailure(throwable);
                return null;
            }
            else
            {
                promise.trySuccess(result);
                return result;
            }
        });
```

**Comment by mrniko** [comment]
> final Promise<Void> promise = batchPromise.getAndSet(ImmediateEventExecutor.INSTANCE.newPromise());

This line looks wired. Why do you pass `ImmediateEventExecutor.INSTANCE.newPromise()` as param for `RBucket.getAndSet` method?

**Comment by mrniko** [comment]
Does the problem over?

**Comment by smigfu** [comment]
Yes, the problem is still there. Interestingly I have a similar behavior when trying to build Redisson locally. At some point I get an OutOfMemoryError and afterwards the tests hang indefinitely. I am currently looking into this and whether I can find a connection. The stacktraces I can see are below. I start the surefire with 3GB and still see this error.

```
io.netty.handler.codec.DecoderException: java.lang.OutOfMemoryError: unable to create new native thread
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at org.redisson.client.handler.CommandDecoder.handleMultiResult(CommandDecoder.java:358)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:332)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:301)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:119)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	... 20 more
Test Up Time    = 1330.715 (s)
Heap Usage      = 547.069 (MB)
None Heap Usage = 56.851 (MB)
=============================
Test Up Time    = 1340.718 (s)
Heap Usage      = 550.295 (MB)
None Heap Usage = 56.854 (MB)
```

```
java.lang.OutOfMemoryError: unable to create new native thread[redisson-netty-1219-5] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.client.RedisClient$2.operationComplete()

	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:815)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:747)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.execute(AbstractEventExecutorGroup.java:114)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:153)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:148)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:815)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:747)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.execute(AbstractEventExecutorGroup.java:114)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:153)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:148)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:815)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:747)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.execute(AbstractEventExecutorGroup.java:114)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:153)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:148)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:815)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:747)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.execute(AbstractEventExecutorGroup.java:114)
	at org.redisson.client.RedisClient$3.operationComplete(RedisClient.java:190)
	at org.redisson.client.RedisClient$3.operationComplete(RedisClient.java:185)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:815)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:747)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.execute(AbstractEventExecutorGroup.java:114)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:153)
	at org.redisson.client.RedisClient$2.operationComplete(RedisClient.java:148)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Test Up Time    = 1920.984 (s)
Heap Usage      = 646.797 (MB)
None Heap Usage = 59.136 (MB)
=============================
Test Up Time    = 1930.990 (s)
Heap Usage      = 652.394 (MB)
None Heap Usage = 59.162 (MB)
=============================
Test Up Time    = 1940.994 (s)
Heap Usage      = 656.732 (MB)
None Heap Usage = 59.162 (MB)
=============================
Test Up Time    = 1950.996 (s)
Heap Usage      = 660.674 (MB)
None Heap Usage = 59.164 (MB)
=============================
Test Up Time    = 1960.998 (s)
Heap Usage      = 664.676 (MB)
None Heap Usage = 59.164 (MB)
=============================
Test Up Time    = 1971.000 (s)
Heap Usage      = 669.570 (MB)
None Heap Usage = 59.164 (MB)
=============================
Test Up Time    = 1981.004 (s)
Heap Usage      = 674.107 (MB)
None Heap Usage = 59.185 (MB)
=============================
Test Up Time    = 1991.009 (s)
Heap Usage      = 678.022 (MB)
None Heap Usage = 59.185 (MB)
=============================
Test Up Time    = 2001.012 (s)
Heap Usage      = 682.185 (MB)
None Heap Usage = 59.185 (MB)
=============================
Test Up Time    = 2011.017 (s)
Heap Usage      = 686.473 (MB)
None Heap Usage = 59.185 (MB)
=============================
[pool-895-thread-1] ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:226)
	at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:215)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:317)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:90)
	at org.redisson.client.handler.ConnectionWatchdog.tryReconnect(ConnectionWatchdog.java:103)
	at org.redisson.client.handler.ConnectionWatchdog.access$000(ConnectionWatchdog.java:44)
	at org.redisson.client.handler.ConnectionWatchdog$1.run(ConnectionWatchdog.java:91)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
Test Up Time    = 2021.018 (s)
Heap Usage      = 692.596 (MB)
None Heap Usage = 59.232 (MB)
=============================
Test Up Time    = 2031.019 (s)
Heap Usage      = 696.397 (MB)
None Heap Usage = 59.249 (MB)
=============================
Test Up Time    = 2041.024 (s)
Heap Usage      = 700.143 (MB)
None Heap Usage = 59.252 (MB)
=============================
Test Up Time    = 2051.028 (s)
Heap Usage      = 704.171 (MB)
None Heap Usage = 59.252 (MB)
=============================
Test Up Time    = 2061.029 (s)
Heap Usage      = 708.992 (MB)
None Heap Usage = 59.252 (MB)
=============================
Test Up Time    = 2071.034 (s)
Heap Usage      = 713.409 (MB)
None Heap Usage = 59.264 (MB)
=============================
Test Up Time    = 2081.037 (s)
Heap Usage      = 717.302 (MB)
None Heap Usage = 59.264 (MB)
=============================
Test Up Time    = 2091.042 (s)
Heap Usage      = 721.256 (MB)
None Heap Usage = 59.266 (MB)
=============================
Test Up Time    = 2101.045 (s)
Heap Usage      = 725.255 (MB)
None Heap Usage = 59.271 (MB)
=============================
Test Up Time    = 2111.048 (s)
Heap Usage      = 730.722 (MB)
None Heap Usage = 59.291 (MB)
=============================
Test Up Time    = 2121.053 (s)
Heap Usage      = 734.607 (MB)
None Heap Usage = 59.291 (MB)
=============================
Test Up Time    = 2131.056 (s)
Heap Usage      = 738.432 (MB)
None Heap Usage = 59.291 (MB)
=============================
Test Up Time    = 2141.057 (s)
Heap Usage      = 742.421 (MB)
None Heap Usage = 59.308 (MB)
=============================
Test Up Time    = 2151.062 (s)
Heap Usage      = 747.093 (MB)
None Heap Usage = 59.308 (MB)
=============================
Test Up Time    = 2161.064 (s)
Heap Usage      = 751.697 (MB)
None Heap Usage = 59.307 (MB)
=============================
```

**Comment by smigfu** [comment]
The ```ImmediateEventExecutor.INSTANCE.newPromise()``` is only to hand out an Promise to our notify our internal client upon success of the batch process.

**Comment by mrniko** [comment]
Could you provide some test to reproduce it?

**Comment by smigfu** [comment]
For now all I did was building the project with: ```mvn -DargLine="-Xmx3g -DredisBinary=$REDIS_BIN/redis-server" -Punit-test clean test -e -X```

I can see that there is still enough memory available but no new Threads can be spawned. I build it on MacOS 10.11.6 with 16GB ram...

I will continue instigating.

**Comment by johnou** [comment]
@smigfu heap dump if possible?

**Comment by smigfu** [comment]
Sorry, I am not too responsive at the moment, we have our "go live" this week. I will try to get the heap dumps asap.

**Comment by smigfu** [comment]
Ok, I finally had some time to dig into this. The problem building is related to my OSX version (10.11.6). Apple hat the brilliant idea to limit the number of filedescriptors/user processes and add a little "tool" to prevent this values to be changed. Thus when trying to build on OSX 10.11.6 at some point in time I get the OutOfMemoryError ("unable to create new native thread"). An explanation can be found at [1]. If I run the example program it give me 2024 native threads before running out of memory regardless of any heap sizes assigned to the program. Might be worth mentioning this at the build instructions. TBH I haven't found a proper way to get the build though at the moment.

But this situation is also a lucky coincidence b/c it alows me to reproduce the OutOfMemory situation easily. I created a stack dump and it hangs at exactly the same method as I have experienced on our real servers (which of course are Linux-EC instances, don't have the limits, but run OutOfMemory due to other issues https://github.com/redisson/redisson/issues/682).

```
"Thread-187" #8344 prio=5 os_prio=31 tid=0x00007fa4c3327000 nid=0xee11b waiting on condition [0x0000700044c7e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000790d3ec60> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:134)
	at org.redisson.RedissonObject.get(RedissonObject.java:55)
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:148)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:270)
	at org.redisson.RedissonMultiLock.tryLock(RedissonMultiLock.java:155)
	at org.redisson.RedissonMultiLock.lockInterruptibly(RedissonMultiLock.java:98)
	at org.redisson.RedissonMultiLock.lockInterruptibly(RedissonMultiLock.java:77)
	at org.redisson.RedissonMultiLock.lock(RedissonMultiLock.java:61)
	at org.redisson.RedissonRedLockTest$2.run(RedissonRedLockTest.java:138)

   Locked ownable synchronizers:
	- None
```

I had a look at the netty code the other day and saw that they will swallow the OutOfMemoryError and try to notify any listeners about the failure. See in ```AbstractBootstrap#initAndRegister``` they are catching the OutOfMemoryError and try to notify the listeners (async?), which will fail because no new threads can be created. Thus the ```CommandAsyncService``` will never retrieve the notification and trigger the ```CountDownLatch```. 

```
        try {
            channel = channelFactory.newChannel();
            init(channel);
        } catch (Throwable t) {
            if (channel != null) {
                // channel can be null if newChannel crashed (eg SocketException("too many open files"))
                channel.unsafe().closeForcibly();
            }
            // as the Channel is not registered yet we need to force the usage of the GlobalEventExecutor
            return new DefaultChannelPromise(channel, GlobalEventExecutor.INSTANCE).setFailure(t);
        }
```

Would you agree this theory?


[1] https://plumbr.eu/outofmemoryerror/unable-to-create-new-native-thread

**Comment by mrniko** [comment]
Great research! But how are you getting so many threads?

**Comment by johnou** [comment]
@smigfu full thread dump would be nice if possible? You might also consider lowering the stacksize of your threads by passing in this JVM opt -Xss256k.

**Comment by mrniko** [comment]
@smigfu Netty uses `GlobalEventExecutor.INSTANCE` in `AbstractBootstrap#initAndRegister` method which always has single working thread created during Netty startup.

**Comment by smigfu** [comment]
I think we are currently discussing two issues in parallel, which by coincidence share the same observable problem: Redisson hangs in ```org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:134)```. 

*Maybe* they are also sharing the same cause: Netty fails to inform the client about a failure due to an OutOfMemoryError.

Lets separate this issues:

1. ```OutOfMemoryError: Unable to create new native thread``` during building and testing Redisson through maven. I haven opened https://github.com/redisson/redisson/issues/693 to track this.


2. ```OutOfMemoryError: heap space``` on big beefy machines with 20GB heap and unlimited file descriptors/user procecesses: Lets continue discussing this in here. Btw. I am not 100% sure that the OOM situation is causing this issue, this was just a guess, because the situation got better, after fixing https://github.com/redisson/redisson/issues/682


Sorry for the confusion

**Comment by smigfu** [comment]
@mrniko: ```GlobalEventExecutor.INSTANCE``` will shutdown its single Thread if there hadn't been any commication in the last second. From the JavaDoc:

```
/**
 * Single-thread singleton {@link EventExecutor}.  It starts the thread automatically and stops it when there is no
 * task pending in the task queue for 1 second.  Please note it is not scalable to schedule large number of tasks to
 * this executor; use a dedicated executor.
 */
```

So I guess this still could be a problem?

**Comment by smigfu** [comment]
@johnou: stack size had already been reduced. Let me see if I get a meaningful StackTrace. But as said the OOM in this issue (beefy machines) is not due to Threads (at least from what I know up until now) :)

**Comment by smigfu** [comment]
If I add the following method to the ```org.redisson.client.handler.CommandDecoder``` the client doesn't hang in case of an error (like an OOM). Do you think this is correct adding this here?

```
    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        log.warn("Exception caught. Closing: " + ctx.channel(), cause);
        
        QueueCommand data = ctx.channel().attr(CommandsQueue.CURRENT_COMMAND).get();
        if (data != null) {
            data.tryFailure(cause);
        }
        
        ctx.close();
    }
```

**Comment by johnou** [comment]
Try invoke super exceptionCaught finally cleanup code?

**Comment by smigfu** [comment]
Do you mean like this?

```
    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        log.warn("Exception caught. Closing: " + ctx.channel(), cause);

        try {
            QueueCommand data = ctx.channel().attr(CommandsQueue.CURRENT_COMMAND).get();
            if (data != null) {
                data.tryFailure(cause);
           }

           ctx.close();
        } finally {
           super.exceptionCaught(ctx, cause);
        }
    }
```

**Comment by johnou** [comment]
(I would put the log statement in the try catch too).

**Comment by mrniko** [comment]
@smigfu I think closing channel is not necessary because not all exceptions are related to broken channel.

**Comment by smigfu** [comment]
I will close this issue for now as I think it is more related to netty catching the Throwable and swallowing java.lang.Error and will follow up wIth them on this issue. Lets see what they say :-)

**Comment by antonysychov** [comment]
I have the same problem

"thrift-worker-5" #68 prio=5 os_prio=0 tid=0x00007f575c85f000 nid=0x6e69 waiting on condition [0x00007f5754a9c000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e356d560> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:148)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:134)
	at org.redisson.RedissonBatch.execute(RedissonBatch.java:253)

hangs indefinitely, redisson version 3.4.2
