### ISSUE TITLE
Test redisson error

### ISSUE THREAD

**Issue by zhangmeng0426** [redisson/redisson#708]
十一月 15, 2016 1:47:28 下午 io.netty.util.concurrent.DefaultPromise notifyListener0
警告: An exception was thrown by org.redisson.cluster.ClusterConnectionManager$4.operationComplete()
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:805)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:345)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:748)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:190)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:134)
	at org.redisson.client.RedisConnection.async(RedisConnection.java:179)
	at org.redisson.client.RedisConnection.async(RedisConnection.java:170)
	at org.redisson.client.RedisConnection.async(RedisConnection.java:162)
	at org.redisson.cluster.ClusterConnectionManager.updateClusterState(ClusterConnectionManager.java:361)
	at org.redisson.cluster.ClusterConnectionManager.access$900(ClusterConnectionManager.java:60)
	at org.redisson.cluster.ClusterConnectionManager$4.operationComplete(ClusterConnectionManager.java:355)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:170)
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:85)
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:34)
	at org.redisson.cluster.ClusterConnectionManager.checkClusterState(ClusterConnectionManager.java:345)
	at org.redisson.cluster.ClusterConnectionManager.access$800(ClusterConnectionManager.java:60)
	at org.redisson.cluster.ClusterConnectionManager$3.run(ClusterConnectionManager.java:331)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:237)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

**Comment by zhangmeng0426** [comment]
Redisson-2.5.1.jar   Redis3.2.4  cluster        3 master 3 slaves

**Comment by mrniko** [comment]
"event executor terminated" occurs when Redisson goes shutdown. Please check your application code

**Comment by zhangmeng0426** [comment]
public boolean qySomething(String name){
		System.out.println("1:"+System.currentTimeMillis());
		RedissonClient redisson = getRedisson();
		System.out.println("2:"+System.currentTimeMillis());
		try {  
			
			for(int i=0; i<1000; i++){
				RMap<String, String> map = redisson.getMap(name+"anyMap"+i);
				String ssString = map.get("key"+i);
				System.out.println(ssString);
			}
			System.out.println("3:"+System.currentTimeMillis());
		
	    }catch(Exception e){
	    	e.printStackTrace();
	    }
		
		redisson.shutdown();
		System.out.println("4:"+System.currentTimeMillis());
		return false;  
	}

**Comment by mrniko** [comment]
Fixed
