### ISSUE TITLE
Error retrieving a hash map that was created/written from PHP app

### ISSUE THREAD

**Issue by giantninja** [redisson/redisson#710]
We started using redis hash for our logged in user session data, and I am having trouble getting a simple map of string key/vals.  I made a little test, where I create the same hash map in java/redisson and in PHP, and I am getting errors when I try to read the map that was created in our PHP application.

This is what they look like via rediscli:
```
127.0.0.1:6379> type test_string_map
hash
127.0.0.1:6379> type web:test_string_map
hash

127.0.0.1:6379> hgetall test_string_map
1) "\"key1\""
2) "\"stringval1\""
3) "\"key2\""
4) "\"50\""

127.0.0.1:6379> hgetall web:test_string_map
1) "key1"
2) "stringval1"
3) "key2"
4) "50"
```

Example that triggeres the warning:
```
# test RMap created in redisson (reads/writes fine)
RMap<String, String> testStringMap = redissonClient.getMap("test_string_map");
testStringMap.put("key1", "stringval1");
testStringMap.put("key2", "50");

# error trying to read hash map created in PHP
RMap<String, String> webStringMap = redissonClient.getMap("web:test_string_map");

# ExceptionCaught() event warning in log triggered when I call redissonClient.getMap()

10:19:12,542 11-18-2016 [WARN ] io.netty.channel.DefaultChannelPipeline::warn:151()
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422) ~[rt.runnable.ej.build.30.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489) [rt.runnable.ej.build.30.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451) [rt.runnable.ej.build.30.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [rt.runnable.ej.build.30.jar:?]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [rt.runnable.ej.build.30.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:384) ~[rt.runnable.ej.build.30.jar:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:284) ~[rt.runnable.ej.build.30.jar:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:119) ~[rt.runnable.ej.build.30.jar:?]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367) ~[rt.runnable.ej.build.30.jar:?]
	... 20 more
```

When I try to retrieve a redis hash with redisson that originated in our PHP application (via Predis), I get that exception and I am unable to read that hash map from PHP key: "web:test_string_map"

Is there a way to handle cases like these?

**Comment by jackygurui** [comment]
By default, Redisson uses JacksonJson codec to serialise and deserialise the data. As such, as standard string in JSON representation has a double quote (") around it, and it is then been escaped by redis itself, so you will see things like "\"my_steam\"" in redis-cli.

**Comment by giantninja** [comment]
Wow.  I figured there would be some way to read those, but didn't realize just how easy.  Thank you so much, worked perfectly the first time!!

Rare to find a lib/package that you love this much.  Keep up the great work.

**Comment by jackygurui** [comment]
Thank you.
