### ISSUE TITLE
IndexOutOfBoundsException when reading from RMapCache

### ISSUE THREAD

**Issue by gamefundas** [redisson/redisson#726]
I am using Redisson 3.2.0 and currently facing a problem reading for a cached collection. The following error is thrown

`
"2016-12-07 14:28:01,810 WARN  [redisson-netty-1-2] io.netty.channel.DefaultChannelPipeline   An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
"io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.redisson.client.handler.CommandDecoder.messageDecoder(CommandDecoder.java:392)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:317)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:301)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:119)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        ... 20 common frames omitted
`

**Comment by mrniko** [comment]
Could you please specify Redisson version you use?

**Comment by gamefundas** [comment]
Redisson 3.2.0

**Comment by mrniko** [comment]
During which method call you encounter such problem?

**Comment by gamefundas** [comment]
Its unclear what triggered this exception as the stracktrace is missing some part towards the end. Once I cleaned up the keys in Redis and tried again, this went away.

**Comment by mrniko** [comment]
Done
