### ISSUE TITLE
connection timeout problem

### ISSUE THREAD

**Issue by langyan1022** [redisson/redisson#735]
Hi,In my operating environment, there is firewall settings that interrupt network connections that are not operating within a certain period of time.For some reason, I can't modify firewall settings.

Now when using redisson, the console will throw an exception if it does not operate at some time.

Exception information as follows：

![20161219104636](https://cloud.githubusercontent.com/assets/5259422/21299635/78df1a70-c5d8-11e6-8446-aafbf1782212.png)

`[redisson-netty-1-4] ERROR org.redisson.client.handler.CommandsQueue - Exception occured. Channel: [id: 0xd6666694, L:/10.128.72.171:6310 - R:/10.193.78.30:6379]
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:25)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:362)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:899)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:275)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:662)`
How should I deal with these problems?

**Comment by langyan1022** [comment]
code：
`Config config = new Config();
				config.useSingleServer().setAddress(redisUrl).setConnectionPoolSize(redisConnPoolSize).setConnectTimeout(60000).setIdleConnectionTimeout(3000).setReconnectionTimeout(60000)
						.setPassword(redisPassword);
				
				redissonClient = Redisson.create(config);`

**Comment by mrniko** [comment]
Hi!

Use `setTimeout` setting to change response timeout

**Comment by langyan1022** [comment]
I set this config to 60000ms
but  unsolved.
Long idle time will also appear this exception.

**Comment by mrniko** [comment]
> An existing connection was forcibly closed by the remote host at sun.nio.ch.SocketDispatcher

Now remote host closed connection

**Comment by langyan1022** [comment]
I know.
How should I deal with these problems?

**Comment by mrniko** [comment]
You need to sort out why remote host closes connection.

**Comment by langyan1022** [comment]
firewall settings that interrupt network connections that are not operating within a certain period of time.For some reason, I can't modify firewall settings.

**Comment by langyan1022** [comment]
I modified the redis configuration
 redis.conf

timeout =60
tcp-keeplive=60

running for about 15 hours，No exception error was found。

thanks
