### ISSUE TITLE
NoClassDefFoundError while trying to use FstCodec

### ISSUE THREAD

**Issue by giantninja** [redisson/redisson#736]
Is there an extra configuration setting that needs to be set for setting a different codec via the Config object?  I'm getting this error when setting up the client:

```
java.lang.NoClassDefFoundError: org/nustaq/serialization/FSTConfiguration
	at org.redisson.codec.FstCodec.<init>(FstCodec.java:46) ~[rt.runnable.ej.build.37.jar:?]
	at com.gp.rt.Redis.getSentinelClientJSON(Redis.java:77) ~[rt.runnable.ej.build.37.jar:?]
	at com.gp.rt.Redis.<init>(Redis.java:59) ~[rt.runnable.ej.build.37.jar:?]
```

Setting up the RedissonClient (sentinel) like so:

```java
        Config config = Config.fromJSON(new File(redisSentinelJsonConfig));
        config.setCodec(new FstCodec());

        SentinelServersConfig sentinelConfig = config.useSentinelServers();
        sentinelConfig
            .setMasterName(SENTINEL_MASTER_NAME)
            .setPassword(SENTINEL_PW);

        return Redisson.create(config);
```

Setup:

```
Centos 6.4 -x86_64

Java:
version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Redisson 3.2.2
```

The json configuration is basically copy/paste from the documentation, and it works just fine if I comment out that `config.setCodec(new FstCodec());` line.

Is there an additional maven dependency that needs to be included or something like that?

**Comment by mrniko** [comment]
Hi!
Fst codec is optional dependency. You have to add it manually:
```
<dependency>
            <groupId>de.ruedigermoeller</groupId>
            <artifactId>fst</artifactId>
            <version>2.47</version>
</dependency>
```
