### ISSUE TITLE
org.redisson.client.RedisTimeoutException

### ISSUE THREAD

**Issue by koywang** [redisson/redisson#744]
```
Exception in thread "main" org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (SET) with params: [hello_109579, 109579] channel: [id: 0x96dcff25, L:/192.168.9.225:50421 - R:/192.168.9.125:7503]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
2017-01-09 16:09:07 [WARN] [o.r.c.h.CommandDecoder:385] - response has been skipped due to timeout! channel: [id: 0x96dcff25, L:/192.168.9.225:50421 - R:/192.168.9.125:7503], command: CommandData [promise=org.redisson.misc.RedissonPromise@32a3cf43[Completed exceptionally], command=(SET), params=[hello_109579, 109579], codec=org.redisson.codec.JsonJacksonCodec@1808301b], result: null 

```

redisson版本是3.2.0，做一段时间简单测试，必定会出现这个错误，redis服务器也换了几个，
单机，哨兵，集群 模式都试过，出现几率非常高！！有人出现这类问题么

**Comment by jackygurui** [comment]
您的Redis版本是3.2.0吧？Redisson用的是什么版本呢？

**Comment by koywang** [comment]
@jackygurui  Redisson是3.2.0，redis服务版本是3.2.3

**Comment by jackygurui** [comment]
可以提供一下您的Redisson实例的配置和测试程序吗？

**Comment by koywang** [comment]
```

@Configuration
@ComponentScan
@EnableCaching
public class RedisSupport{

	private static final Logger logger = LoggerFactory.getLogger(RedisSupport2.class);

    @Bean(destroyMethod="shutdown")
    RedissonClient redissonClient() throws IOException {
    	String pathYaml = this.getClass().getResource("/").getPath()+"redis.yaml";
    	File fileYaml = new File(pathYaml);
    	if(fileYaml.exists()){
    		logger.info("加载redis.yaml，创建RedissonClient成功！");
            return Redisson.create(Config.fromYAML(fileYaml));
    	}else{
    		throw new RuntimeException("RedissonClient初始化失败找不到redis配置文件redis.yaml");
    	}
    }
    
    @Bean
    public CacheManager cacheManager(RedissonClient redissonClient) {
    	String pathYaml = this.getClass().getResource("/").getPath()+"spring-cache.yaml";
    	
    	File fileYaml = new File(pathYaml);
    	if(fileYaml.exists()){
    		logger.info("加载spring-cache.yaml");
            return new RedissonSpringCacheManager(redissonClient, "classpath:/spring-cache.yaml");
    	}else{
    		throw new RuntimeException("RedissonClient初始化失败找不到redis配置文件spring-cache.yaml");
    	}
    }
}
```


redis.yaml

```
---
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  nodeAddresses:
  - "redis://10.1.20.159:7000"
  - "redis://10.1.20.159:7001"
  - "redis://10.1.20.159:7002"
  - "redis://10.1.21.2:7001"
  - "redis://10.1.21.2:7002"
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false
```


```
public static void main(String[] args) {
    	GenericXmlApplicationContext context = new GenericXmlApplicationContext();  
        context.setValidating(false);
        context.load("classpath*:root-test.xml");
        context.refresh();
        
        RedissonClient redisson = context.getBean(RedissonClient.class);
        
        for (int i = 0; i <= 99999; i++) {
			RBucket<Integer> rb = redisson.getBucket("hello_"+i);
			rb.set(i,60,TimeUnit.MINUTES);
		}
	}
```



测试main方法，今天下午测试7次集群模式，5次中途报错没跑完

**Comment by jackygurui** [comment]
您试一下这段测试程序，参数您可以自行修改。我测试过无数次都没问题。
```java

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;
import org.redisson.Redisson;
import org.redisson.api.RMap;
import org.redisson.api.RedissonClient;
import org.redisson.client.codec.StringCodec;
import org.redisson.config.Config;

public class TestRedisson {
        public static void main(String[] args) throws InterruptedException {

        int threads = 10; //模拟并发客户端数量
        int iteration = 100000;//每个客户端线性执行操作次数
        //配置开始
        Config c = new Config();
        c.setNettyThreads(0)
                .setThreads(0)
                .useSingleServer()
                .setAddress("127.0.0.1:6379")
                .setConnectionPoolSize(64)
                .setConnectionMinimumIdleSize(10);
        c.setCodec(StringCodec.INSTANCE);
        //配置结束
        ExecutorService e = Executors.newFixedThreadPool(threads);
        final CountDownLatch l = new CountDownLatch(threads);
        RedissonClient t = Redisson.create(c);
        t.getKeys().flushdb();
        t.shutdown();
        long s = System.currentTimeMillis();
        for (int i = 0; i < threads; i++) {
            RedissonClient r = Redisson.create(c);
            RMap<String, String> map = r.getMap("map_" + i);
            e.execute(new Runnable() {
                AtomicInteger cnt = new AtomicInteger(0);

                @Override
                public void run() {
                    for (int j = 0; j < iteration; j++) {
                        map.put("key_" + j, "value_" + j);
                        int runs = cnt.incrementAndGet();
                        if (runs == iteration) {
                            l.countDown();
                            r.shutdown();
                        }
                    }
                }
            });
        }
        l.await();
        System.out.println("REDISSON TIME: " + (System.currentTimeMillis() - s));
        e.shutdown();

    }
}

```

**Comment by koywang** [comment]
[log.zip](https://github.com/redisson/redisson/files/695054/log.zip)


稍微修改了这段代码，改成集群模式和哨兵模式，redis服务端还是3.2.3，跑了几次，换了几个服务器，不能完成一次完整的运行，都出现了超时异常！！单机模式下跑了2遍没出现异常，现在还在测试；
现在是要上线的项目测试阶段出现这个问题，所以比较急，希望能找到问题所在，麻烦你了，
@jackygurui

**Comment by koywang** [comment]
```
 
2017-01-10 09:48:10 [INFO] [o.r.Version:41] - Redisson 3.2.0 
2017-01-10 09:48:10 [INFO] [o.r.c.p.MasterConnectionPool:135] - 10 connections initialized for /192.168.9.125:6379 
2017-01-10 09:48:10 [INFO] [o.r.c.p.SinglePubSubConnectionPool:135] - 1 connections initialized for /192.168.9.125:6379 
2017-01-10 09:48:10 [INFO] [o.r.Version:41] - Redisson 3.2.0 
2017-01-10 09:48:10 [INFO] [o.r.c.p.MasterConnectionPool:135] - 10 connections initialized for /192.168.9.125:6379 
2017-01-10 09:48:10 [INFO] [o.r.c.p.SinglePubSubConnectionPool:135] - 1 connections initialized for /192.168.9.125:6379 
2017-01-10 09:48:10 [INFO] [o.r.Version:41] - Redisson 3.2.0 
2017-01-10 09:48:11 [INFO] [o.r.c.p.MasterConnectionPool:135] - 10 connections initialized for /192.168.9.125:6379 
2017-01-10 09:48:11 [INFO] [o.r.c.p.SinglePubSubConnectionPool:135] - 1 connections initialized for /192.168.9.125:6379 
Exception in thread "pool-2-thread-8" org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, map1_7, key_62727, value_62727] channel: [id: 0x8a13f814, L:/192.168.9.225:49464 - R:/192.168.9.125:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-3" Exception in thread "pool-2-thread-9" org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, map1_2, key_64230, value_64230] channel: [id: 0x944dd295, L:/192.168.9.225:49401 - R:/192.168.9.125:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, map1_8, key_63031, value_63031] channel: [id: 0x4ae0715c, L:/192.168.9.225:49468 - R:/192.168.9.125:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-7" org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, map1_6, key_64593, value_64593] channel: [id: 0xd40b6a32, L:/192.168.9.225:49447 - R:/192.168.9.125:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-5" org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, map1_4, key_63037, value_63037] channel: [id: 0x5d6b0b86, L:/192.168.9.225:49430 - R:/192.168.9.125:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-1" org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, map1_0, key_64747, value_64747] channel: [id: 0x5cc3f154, L:/192.168.9.225:49386 - R:/192.168.9.125:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-10" org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, map1_9, key_64323, value_64323] channel: [id: 0xd153d547, L:/192.168.9.225:49480 - R:/192.168.9.125:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:633)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
```


单机redis服务器测试第三遍的时候也出现了timeout异常

**Comment by jackygurui** [comment]
你把ip换成loopback试一下

**Comment by koywang** [comment]
@jackygurui  loopback 怎么弄？没用过！！

**Comment by jackygurui** [comment]
通常localhost或127.0.0.1地址就是绑定在loopback适配器上的。

**Comment by yanjie108** [comment]
解决了么，碰到相同的问题。

**Comment by jackygurui** [comment]
你要根据自己的的网络环境调整超时时长

**Comment by leichenlei** [comment]
遇到了同样的问题
`org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (LPUSH) with params: [m_p_xx_i_l, {"alert":"","appId":"","badge":0,"deviceType":0,"id":"...] channel: [id: 0x4bb0ac9f, L:/10.27.73.158:3283 - R:/10.25.115.62:7000]
        at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:647)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:625)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:700)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:428)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by jackygurui** [comment]
@leichenlei 你要根据自己的的网络环境和使用情况调整超时时长。

**Comment by dufyun** [comment]
我使用的哨兵模式，我出现这个问题是因为master 宕机了，就报了这个错误！
报这个错误之后。之前的请求全部失败！
在哨兵选举新的master成功后，如果保证之前的请求还能继续，而不是就失败了呢？

**Comment by jackygurui** [comment]
根据你的设置，执行失败的命令会自动重试，只有达到你设定的重试次数以后才会抛出这个错误。当这个错误抛出以后，表明Redisson已经放弃执行这条命令了。如果你还希望让Redisson多尝试几次这个指令，你可以相应调整`retryAttempts`和`retryInterval`这两个参数。

**Comment by mingliangfeng** [comment]
问题解决了没？应该回来分享一下方案

**Comment by jackygurui** [comment]
这不是Redisson的问题，是实际运行环境的影响，需要你自行调整上面两个参数大小。

**Comment by mingliangfeng** [comment]
Not always.

我们的情形是这样的：我们有两个redis servers，一个master，一个Slave；前面还有一个load balancer. 我们的master redis server当机后，Slave自动online。随后redission一直报RedisTimeoutException，但redis server绝对是好的。最后的解决方法是重启redission所在的应用。

一个可能的结果是redission里面的Redis Connection Pool缓存了过期的redis connection.

**Comment by jackygurui** [comment]
由于Redisson自己内部有负载均衡的功能，没有必要再自己搞一个。Redisson具有自我感知能力，在不同类型的redis环境下，它感知拓扑变化的方式也不一样，你自己增加的这个LB会造成Redisson错误的判断当前的节点情况的。建议你采用Redisson自带的LB并去掉不兼容的外部LB。

Redisson的重试机制表现在当命令失败或者列队满后等待时间超过了规定时间，并且该状态持续发生指定的次数以后，Redisson会把这个节点加入一个黑名单，在黑名单里的节点会定期尝试一下，如果连接成功，就剔除黑名单，如果尝试连接再次失败，下次尝试的时间间隔会增加。

**Comment by mingliangfeng** [comment]
这个架构不具备普遍性。Redis一般用来作为缓存中心，被所有的应用系统共用。有些系统并不是java开发的，怎么采用redission的LB?

**Comment by mingliangfeng** [comment]
而且我们使用的方式是config.useSingleServer()，并没有使用Redisson的LB。
我觉得不是Redisson的LB的问题，而是Redisson ConnectionManager的问题。

**Comment by koywang** [comment]
@mingliangfeng  这个其实一直没解决，经常性的提示这个错误！几个参数各种修改了也不行，哎！目前单机，哨兵，集群 在服务器上在本地都N多次使用测试，无法避免（本地测试出现几率小很多），一直在关注更新，但是这个问题一直存在，我是个小新手，无法定位到问题，还是先换回jedis吧！

**Comment by onealcenter** [comment]
可以尝试下设置这两个参数
setMasterConnectionMinimumIdleSize(0)
setSlaveConnectionMinimumIdleSize(0)
应该能解决超时的问题

**Comment by jinshubao** [comment]
我也遇到同样问题，刚上线一切正常，过几天就有问题，很迷惑

**Comment by huangsanyeah** [comment]
how to solve this?I meet a same problem  use3.2.3

**Comment by mrniko** [comment]
@huangsanyeah 

https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

and consider to update to the latest version, since it has improvements for Redis command decoding process.

**Comment by jinshubao** [comment]
我的问题是因为做了中间层代理导致的

发自我的iPhone
