### ISSUE TITLE
tomcat-8.0.39 session 共享读取配置异常

### ISSUE THREAD

**Issue by koywang** [redisson/redisson#745]
redis配置是copy默认yaml配置

redisson版本3.2.0
应用如果直接丢到webapps文件夹下面可以正常运行，但是指定指定路径就报错
```
<Context path="/" docBase="/data/apps/fin" debug="0" reloadable="false" crossContext="true"/>
```
异常日志
```

 2017-01-10 14:48:00 localhost-startStop-1[INFO] ZooKeeper.<init>(379) - Initiating client connection, connectString=10.1.21.4:2181 sessionTimeout=10000 watcher=com.baidu.disconf.core.common.zookeeper.inner.ResilientActiveKeyValueStore@775904fb
 2017-01-10 14:48:00 localhost-startStop-1-SendThread()[INFO] ClientCnxn.startConnect(1058) - Opening socket connection to server /10.1.21.4:2181
 2017-01-10 14:48:00 localhost-startStop-1-SendThread(cas.frontpay.cn:2181)[INFO] ClientCnxn.primeConnection(947) - Socket connection established to cas.frontpay.cn/10.1.21.4:2181, initiating session
 2017-01-10 14:48:00 localhost-startStop-1-SendThread(cas.frontpay.cn:2181)[INFO] ClientCnxn.readConnectResult(736) - Session establishment complete on server cas.frontpay.cn/10.1.21.4:2181, sessionid = 0x158299f32d536a6, negotiated timeout = 10000
 2017-01-10 14:48:02 localhost-startStop-1[INFO] DruidDataSource.init(669) - {dataSource-1} inited
10-Jan-2017 14:48:05.267 SEVERE [localhost-startStop-1] org.redisson.tomcat.RedissonSessionManager.startInternal Can't parse json config /usr/local/tomcat18080/conf/redis.yaml
 com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: /usr/local/tomcat18080/conf/redis.yaml; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.base.ParserBase.reportUnexpectedNumberChar(ParserBase.java:1069)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleInvalidNumberStart(UTF8StreamJsonParser.java:2749)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseNegNumber(UTF8StreamJsonParser.java:1414)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:837)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:748)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2691)
	at org.redisson.config.ConfigSupport.fromJSON(ConfigSupport.java:119)
	at org.redisson.config.Config.fromJSON(Config.java:516)
	at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:149)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5331)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

10-Jan-2017 14:48:05.269 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal The session manager failed to start
 org.apache.catalina.LifecycleException: Failed to start component [org.redisson.tomcat.RedissonSessionManager[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5331)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Can't parse yaml config /usr/local/tomcat18080/conf/redis.yaml
	at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:156)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 12 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Class org.redisson.connection.balancer.RoundRobinLoadBalancer not subtype of [simple type, class org.redisson.connection.balancer.LoadBalancer] (through reference chain: org.redisson.config.Config["clusterServersConfig"]->org.redisson.config.ClusterServersConfig["loadBalancer"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:378)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:338)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1510)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2691)
	at org.redisson.config.ConfigSupport.fromYAML(ConfigSupport.java:143)
	at org.redisson.config.Config.fromYAML(Config.java:587)
	at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:153)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Class org.redisson.connection.balancer.RoundRobinLoadBalancer not subtype of [simple type, class org.redisson.connection.balancer.LoadBalancer]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:329)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:83)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:51)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:158)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._deserializeWithNativeTypeId(TypeDeserializerBase.java:248)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:66)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:488)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	... 23 more

```

**Comment by mrniko** [comment]
> Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: /usr/local/tomcat18080/conf/redis.yaml; line: 1, column: 3]

It's obviously that redis.yaml config file you provide has a wrong format. Could you share its content?

**Comment by koywang** [comment]
@mrniko  redis.yaml
```
---
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  nodeAddresses:
  - "redis://10.1.20.159:7000"
  - "redis://10.1.20.159:7001"
  - "redis://10.1.20.159:7002"
  - "redis://10.1.21.2:7001"
  - "redis://10.1.21.2:7002"
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false
```

**Comment by koywang** [comment]
@mrniko  tomcat/conf/server.xml

```
<?xml version='1.0' encoding='utf-8'?>

<Server port="18005" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
  <GlobalNamingResources>
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname="conf/tomcat-users.xml" />
  </GlobalNamingResources>
  <Service name="Catalina">
    
    <Connector port="18081" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />

    <Connector port="18009" protocol="AJP/1.3" redirectPort="8443" />
    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps" unpackWARs="true" autoDeploy="true">

        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
	
      <Context path="/" docBase="/Users/koy/dev/myapp" debug="0" reloadable="false" crossContext="true"/>
      </Host>
    </Engine>
  </Service>
</Server>

```

**Comment by koywang** [comment]
去掉yaml配置中的属性`loadBalancer`和`codec` 启动成功！！！

**Comment by mrniko** [comment]
also please check redis.yaml in hex editor for chars not visible in editor. It could be BOM characters https://en.wikipedia.org/wiki/Byte_order_mark
