### ISSUE TITLE
RMap get value fail

### ISSUE THREAD

**Issue by QiuMing** [redisson/redisson#754]
My  test code:
```
public void test() {
        RedissonClient redissonClient = RedissonService.redissonClient();
        RMap<String, String> test1 = redissonClient.getMap("test1");
        test1.put("key1", "value2");
        test1.put("key2", "value2");
        test1.keySet().forEach(System.out::println);    //OK

        RMap<String, String> test2 = redissonClient.getMap("test2");
        test2.keySet().forEach(System.out::println);                        //JsonParseException

        RMap<Object, Object> test3 = redissonClient.getMap("test2");        //JsonParseException
        test3.keySet().forEach(x -> {
            String key = (String) x;
            System.out.println(key);
        });
    }
```

This is my test data:
```
localhost:0>hgetall test1
 1)  ""key1""
 2)  ""value2""
 3)  ""key2""
 4)  ""value2""
localhost:0>hgetall test2
 1)  "key1"
 2)  "value1"
 3)  "key2"
 4)  "value2"
localhost:0>
```

And this is error:
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'key1': was expecting ('true', 'false' or 'null')
 at [Source: io.netty.buffer.ByteBufInputStream@27a0a5a2; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3460)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2624)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:854)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:748)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:75)
	at org.redisson.client.codec.MapScanCodec$2.decode(MapScanCodec.java:89)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:283)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:313)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:313)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

```

And jedis work is ok
```
package sample;
import com.alibaba.fastjson.JSON;
import redis.clients.jedis.Jedis;
public class JedisTest {
    public static void main(String[] args) {
        Jedis jedis = new Jedis("127.0.0.1", 6379);
        System.out.println(JSON.toJSONString(jedis.hgetAll("test2")));
        System.out.println(JSON.toJSONString(jedis.hgetAll("test1")));
    }
}

output:
{"key1":"value1","key2":"value2"}
{"\"key1\"":"\"value2\"","\"key2\"":"\"value2\""}
```

My  redisson version is 3.2.3.And how can I get test2 value by redisson?

**Comment by mrniko** [comment]
> And jedis work is ok

Which JSON codec used by jedis?

**Comment by jackygurui** [comment]
```
localhost:0>hgetall test2
 1)  "key1"
 2)  "value1"
 3)  "key2"
 4)  "value2"
//Incorrect format for default JsonJacksonCodec, to decode this you need StringCodec

localhost:0>hgetall test1
 1)  ""key1""
 2)  ""value2""
 3)  ""key2""
 4)  ""value2""
//Correct format for default JsonJacksonCodec
```

Looks like your `test2` isn't encoded by JsonJacksonCodec but you are trying to use the codec to decode the content. Since it is not a valid JSON string, you will be getting a parse exception.

**Comment by QiuMing** [comment]
@jackygurui  yea...I put test2 value by redis desktop manager .I get this error because my project use jedis at first.And now I want to learn and use redisson, and then I get this error.Is there a way to get test2 by redisson ?

@mrniko Jedis seems not use  JSON codec..

**Comment by jackygurui** [comment]
A valid JSON string requires a double quote around the content.  To understand it, lets look at the  following console output:
```
localhost:0>hgetall test1
 1)  ""key1""
 2)  ""value2""
 3)  ""key2""
 4)  ""value2""
```
There are two sets of double quotes wrapped around each item, for instance `""key1""`. It may look strange however it is a valid JSON string because redis-cli wraps any string content with `""` for displaying, so the actual value is "key1" when you retrieved it through a Java client. When you use JsonJacksonCodec to decode `"key1"`, you will get a proper String object back.

With that in mind, when you see "key1" in the redis-cli console, it is actually just `key1` with no quotes, it is not a valid JSON string considered by the JsonJacksonCodec, this, however, can be used with a StringCodec, since `key1` is still a valid string to Java. 

So, to tell redisson use a different codec other than the default one for a particular object, you can do this:
```java
        RMap<String, String> test2 = redissonClient.getMap("test2", StringCodec.INSTANCE);
        test2.keySet().forEach(System.out::println);
```
Now you should be able to get your code run without errors.

**Comment by QiuMing** [comment]
@jackygurui  Thank your very much , your answer solves my problem,thanks
