### ISSUE TITLE
Redisson may log RedissonShutdownException on shutdown when configured with ReplicatedConnectionManager

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#765]
```text
2017-02-08 14:42:54,504 ERROR [globalEventExecutor-2-5] (org.redisson.connection.ReplicatedConnectionManager) Redisson is shutdown
org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.client.RedisConnection.async(RedisConnection.java:181) ~[redisson-2.7.4.jar:?]
	at org.redisson.client.RedisConnection.async(RedisConnection.java:171) ~[redisson-2.7.4.jar:?]
	at org.redisson.client.RedisConnection.async(RedisConnection.java:163) ~[redisson-2.7.4.jar:?]
	at org.redisson.connection.ReplicatedConnectionManager$2$1.operationComplete(ReplicatedConnectionManager.java:179) [redisson-2.7.4.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:85) [redisson-2.7.4.jar:?]
	at org.redisson.misc.RedissonPromise.addListener(RedissonPromise.java:34) [redisson-2.7.4.jar:?]
	at org.redisson.connection.ReplicatedConnectionManager$2.run(ReplicatedConnectionManager.java:167) [redisson-2.7.4.jar:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:233) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by johnou** [comment]
I guess the MasterChangeCheck needs to be interrupted on shutdown.

**Comment by johnou** [comment]
Aha it is interrupted, so I suppose we could catch this exception or something inside and ignore it if shutdown is in progress?

**Comment by johnou** [comment]
@mrniko wdyt?

**Comment by mrniko** [comment]
Yes. `monitorFuture` is already cancelled during shutdown process. I'll add shutdown state checking before INFO_REPLICATION calling

**Comment by mrniko** [comment]
Done
