### ISSUE TITLE
IllegalStateException when accessing an invalidated session

### ISSUE THREAD

**Issue by schroenser** [redisson/redisson#788]
Just using TomEE (Tomcat), when I invalidate a session using `session.invalidate();`, the next request the browser sends still has the old `JSESSIONID`. Tomcat doesn't seem to care about that, creates a new session and changes the cookie.

With redisson however, I get the exception posted below.
It seems that the `ManagerBase` does not return a session with the given ID, which is correct since the session was invalidated earlier, but then a new `RedissionSession` is created with that same ID which in turn leads to the exception.
After that, a new session seems to be created elsewhere, as the response contains a new `JSESSIONID`.

```
ERROR OpenEJB.cdi - ERROR_0020
ERROR org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/miraculix] - Session event listener threw exception
java.lang.IllegalStateException: getAttribute: Session already invalidated
    at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1204)
    at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:108)
    at org.apache.webbeans.web.context.WebContextsService.initSessionContext(WebContextsService.java:455)
    at org.apache.webbeans.web.context.WebContextsService.startContext(WebContextsService.java:307)
    at org.apache.openejb.server.httpd.BeginWebBeansListener.sessionCreated(BeginWebBeansListener.java:149)
    at org.apache.catalina.session.StandardSession.tellNew(StandardSession.java:414)
    at org.apache.catalina.session.StandardSession.setId(StandardSession.java:386)
    at org.redisson.tomcat.RedissonSession.setId(RedissonSession.java:55)
    at org.apache.catalina.session.StandardSession.setId(StandardSession.java:367)
    at org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:120)
    at org.apache.catalina.connector.Request.doGetSession(Request.java:2855)
    at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2515)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:429)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mrniko** [comment]
There is a test which reproduces this case, but it always pass `org.redisson.tomcat.RedissonSessionManagerTest.testInvalidate` can you suggest any fix for it to reproduce your case?

**Comment by schroenser** [comment]
I can't run the tests as IntelliJ complains about the lambda expressions in some test sources. Apparently, they don't support different source versions for source and test. *sigh*

Apart from that, just by reading the test source, I would agree that this is exactly the case I described. So, no issue on your part and I got some kind of problem I'm failing to see.
