### ISSUE TITLE
redisson-tomcat-8-3.3.1.jar not compatible with Tomcat 8.5.2

### ISSUE THREAD

**Issue by schroenser** [redisson/redisson#797]
Using `redisson-tomcat-8-3.3.1.jar` inside a TomEE 7.0.0, which in turn is based on Tomcat 8.5.2, leads to the exception below. It looks like the API has changed from Tomcat 8.0 to 8.5 by at least leaving out `org.apache.catalina.util.LifecycleSupport` as can be seen in [Tomcats repository](http://svn.apache.org/repos/asf/tomcat/tc8.5.x/tags/TOMCAT_8_5_2/java/org/apache/catalina/util/).

```
java.lang.ClassNotFoundException: org.apache.catalina.util.LifecycleSupport
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 40 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: org/apache/catalina/util/LifecycleSupport
    at org.redisson.tomcat.RedissonSessionManager.<init>(RedissonSessionManager.java:46)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
    at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1188)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
    at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1461)
    at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:536)
    at org.apache.catalina.startup.OpenEJBContextConfig.processContextConfig(OpenEJBContextConfig.java:224)
    at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:493)
    at org.apache.catalina.startup.OpenEJBContextConfig.contextConfig(OpenEJBContextConfig.java:271)
    at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:734)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:309)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:401)
    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:115)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:141)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:702)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mrniko** [comment]
Fixed
