### ISSUE TITLE
factory already defined error when starts tomcat with two WAR apps

### ISSUE THREAD

**Issue by ensean** [redisson/redisson#798]
Hi,

    I have met an issue seems have been fixed :( 

- software stack info is as follows:
```
Using CATALINA_BASE:   /opt/appstack/apache-tomcat
Using CATALINA_HOME:   /opt/appstack/apache-tomcat
Using CATALINA_TMPDIR: /opt/appstack/apache-tomcat/temp
Using JRE_HOME:        /opt/appstack/java
Using CLASSPATH:       /opt/appstack/apache-tomcat/bin/bootstrap.jar:/opt/appstack/apache-tomcat/bin/tomcat-juli.jar
Server version: Apache Tomcat/7.0.62
Server built:   May 7 2015 17:14:55 UTC
Server number:  7.0.62.0
OS Name:        Linux
OS Version:     3.10.0-327.36.3.el7.x86_64
Architecture:   amd64
JVM Version:    1.7.0_76-b13
JVM Vendor:     Oracle Corporation
```

- Configuration  in context.xml of tomcat
```
    <Manager className="org.redisson.tomcat.RedissonSessionManager"
         configPath="/opt/appstack/apache-tomcat/conf/redisson.json" />
   
```

- Process  to reproduce this issue

1. stop tomcat
2. cp two app WARs built by maven to $/webapps
3. start tomcat

Please note that, if I place only one war in the webapps directory, this issue won't occur ...

- error  message when this issue occurs
```
信息: Deploying web application archive /opt/appstack/apache-tomcat/webapps/mtopc.war
三月 10, 2017 5:30:52 下午 org.apache.catalina.startup.HostConfig deployWAR
信息: Deploying web application archive /opt/appstack/apache-tomcat/webapps/collaboration.war
三月 10, 2017 5:30:52 下午 org.apache.catalina.deploy.WebXml setVersion
警告: Unknown version string [3.1]. Default version will be used.
三月 10, 2017 5:30:52 下午 org.apache.catalina.deploy.WebXml setVersion
警告: Unknown version string [3.1]. Default version will be used.
三月 10, 2017 5:30:53 下午 org.apache.catalina.core.StandardContext startInternal
严重: The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [org.redisson.tomcat.RedissonSessionManager[/mtopc]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5537)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1930)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Error: factory already defined
        at java.net.URL.setURLStreamHandlerFactory(Unknown Source)
        at org.redisson.misc.URLBuilder.replaceURLFactory(URLBuilder.java:85)
        at org.redisson.misc.URLBuilder.create(URLBuilder.java:110)
        at org.redisson.config.MasterSlaveServersConfig.setMasterAddress(MasterSlaveServersConfig.java:65)
        at org.redisson.connection.SingleConnectionManager.create(SingleConnectionManager.java:72)
        at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:49)
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:255)
        at org.redisson.Redisson.<init>(Redisson.java:115)
        at org.redisson.Redisson.create(Redisson.java:154)
        at org.redisson.tomcat.RedissonSessionManager.startInternal(RedissonSessionManager.java:161)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 12 more
```

**Comment by ensean** [comment]
I am using redisson-all-2.8.1.jar & redisson-tomcat-7-2.8.1.jar

**Comment by mrniko** [comment]
Is it reproduced with only two or more webapps? Do they all use Redisson inside?

**Comment by ensean** [comment]
I currently just have these two apps.. mtopc does not use Redission inside

**Comment by ensean** [comment]
By the way, if I firstly have tomcat started & running with collaboration.war, and then just move mtopc.war to webapps directory, both of these two apps can run correctly..

**Comment by mrniko** [comment]
I did some changes, could you try it again?

**Comment by ensean** [comment]
Would kindly give some instructions on trying the changes you've made? I have not found the release jars, do I need to build it myself?

**Comment by mrniko** [comment]
Use `master` branch

**Comment by ensean** [comment]
@mrniko It works correctly now :100:

**Comment by mrniko** [comment]
Cool!
