### ISSUE TITLE
[StackOverFlowError]

### ISSUE THREAD

**Issue by expitly** [redisson/redisson#824]
I use
Java 1.7.0_75
tomcat-8.0.23
redisson-tomcat-8-2.8.1.jar
redisson-all-2.8.1.jar

=============================================================
[[[[[ Spring Error ]]]]]
org.redisson.client.RedisException: Unexpected exception while processing command
        at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:320)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165)
        at org.redisson.RedissonObject.get(RedissonObject.java:69)
        at org.redisson.RedissonMap.fastPut(RedissonMap.java:436)
        at org.redisson.tomcat.RedissonSession.setAttribute(RedissonSession.java:133)
        at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1441)
        at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:142)
        at org.springframework.web.context.request.ServletRequestAttributes.registerSessionDestructionCallback(ServletRequestAttributes.java:252)
        at org.springframework.web.context.request.ServletRequestAttributes.registerDestructionCallback(ServletRequestAttributes.java:188)
        at org.springframework.web.context.request.AbstractRequestAttributesScope.registerDestructionCallback(AbstractRequestAttributesScope.java:66)
        at org.springframework.beans.factory.support.AbstractBeanFactory.registerDisposableBeanIfNecessary(AbstractBeanFactory.java:1572)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$2.getObject(AbstractBeanFactory.java:341)
        at org.springframework.web.context.request.AbstractRequestAttributesScope.get(AbstractRequestAttributesScope.java:44)
        at org.springframework.web.context.request.SessionScope.get(SessionScope.java:93)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:336)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1021)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:964)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectFactory.getObject(DefaultListableBeanFactory.java:1203)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyProvider.get(DefaultListableBeanFactory.java:1219)
        at com.ets.aop.ControllerAop.etsCrpMngCheck(ControllerAop.java:129)
        at com.ets.ctl.cs.HomeController.main_aroundBody4(HomeController.java:94)
        at com.ets.ctl.cs.HomeController$AjcClosure5.run(HomeController.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.ets.aop.ControllerAop.apiErrorString(ControllerAop.java:103)
        at com.ets.ctl.cs.HomeController.main(HomeController.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:747)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:676)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)                       
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)                         
		at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:195)                    
		at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:159)                                  
		at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:141)                                        
		at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:90)                              
		at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:417)                         
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)              
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)                      
		at com.ets.filter.XssFilter.doFilter(XssFilter.java:37)                                                           
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)              
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)                      
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)                            
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)                            
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)                         
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)                                  
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)                                   
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)                      
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)                               
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)                                    
		at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)                    
		at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)                
		at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)         
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517)                            
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474)                              
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)                                
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)                                
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                             
		at java.lang.Thread.run(Thread.java:745)                                                                          
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java

at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:706)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)

[[[[[Tomcat Error]]]]]

[redisson-netty-1-2] WARN io.netty.channel.AbstractChannelHandlerContext - Failed to mark a promise as failure because it has failed already: DefaultChannelPromise@4e341b8e(failure: io.netty.handler.codec.EncoderException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.Launcher$AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["

....

And

StackOverflowError

**Comment by mrniko** [comment]
Problem occurs during serialization. Which object do you store in session?

**Comment by expitly** [comment]
I use Spring session Object(session Scope Object)

But when I used the Memcached Session manager, it worked.

What should I do..?

**Comment by mrniko** [comment]
Could you share this object so I able to reproduce your case?

**Comment by expitly** [comment]
@Component
@Scope("session")
public class UserSession implements Serializable{
	private static final long serialVersionUID = -3252300364336538509L;
	private String hpNum;
	private long crpNo;
	private String crpNm;
	private int crpRoll;
	private long crpMngNo;	
	private String crpMngNm;
	private String email;
	private int crpMngRoll;
	private String cashYn;
	private String mealYn;
	private String gftYn;

//.... getter, setter...

}


@Component
@Scope("session")
public class AdminSession implements Serializable {
	private static final long serialVersionUID = 3606407650098726503L;
	
	private long empMngNo;
	private String loginId;
	private String empMngNm;
	private String hpNum;
	private String email;
	private int empMngRoll;
	private long empNo;
	private String empNm;
	private int empRoll;

//.. getter .. setter..

}

**Comment by mrniko** [comment]
As workaround try to use another codec

**Comment by expitly** [comment]
Thanks, mrniko.

I use SerializationCodec, It works.
However, the first time I run tomcat, an error occurs. From the second it works without problems.

==================================================================

HTTP Status 500 - Unexpected exception while processing command

org.redisson.client.RedisException: Unexpected exception while processing command
	org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:320)
	org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165)
	org.redisson.RedissonObject.get(RedissonObject.java:69)
	org.redisson.RedissonMap.readAllEntrySet(RedissonMap.java:255)
	org.redisson.tomcat.RedissonSession.load(RedissonSession.java:167)
	org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:121)
	org.apache.catalina.connector.Request.doGetSession(Request.java:2855)
	org.apache.catalina.connector.Request.getSessionInternal(Request.java:2515)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:429)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)
root cause

java.io.IOException: java.lang.ClassNotFoundException: com.seeon.admin.dto.AdminSession
	org.redisson.codec.SerializationCodec$1.decode(SerializationCodec.java:53)
	org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:283)
	org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:313)
	org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302)
	org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	java.lang.Thread.run(Thread.java:745)
root cause

java.lang.ClassNotFoundException: com.seeon.admin.dto.AdminSession
	java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	java.security.AccessController.doPrivileged(Native Method)
	java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	java.lang.ClassLoader.loadClass(ClassLoader.java:425)

**Comment by mrniko** [comment]
back to problem with Jackson serialization. 
This line `com.ets.aop.ControllerAop.etsCrpMngCheck(ControllerAop.java:129)` attempts to store `java.security.ProtectionDomain` into session which is bad idea. When you fix it, all should work properly.

**Comment by rajeshdhanana** [comment]
Is this problem resolved? 
I am facing the same problem

**Comment by liucaiyun1990** [comment]
is this problem resolved? i aslo facing this same problem...
