### ISSUE TITLE
why redisson start up  error   Caused by :NoSuchMethodError

### ISSUE THREAD

**Issue by 1017727621** [redisson/redisson#825]
<context:property-placeholder/>

<context:annotation-config/>
 <redisson:client name="redisson">
    <redisson:single-server address="1xx.xx.xx:6379"/>
    <redisson:list key="phone"></redisson:list>
</redisson:client>

redisson 3.2.4  netty 4.1.8  jackson 2.7.6  tomcat 7.0.73
 jdk 1.7.0_80

Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.addMixIn(Ljava/lang/Class;Ljava/lang/Class;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at org.redisson.codec.JsonJacksonCodec.init(JsonJacksonCodec.java:148)
	at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:95)
	at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:80)
	at org.redisson.codec.JsonJacksonCodec.<clinit>(JsonJacksonCodec.java:55)
	at org.redisson.config.Config.<init>(Config.java:101)
	at org.redisson.Redisson.<init>(Redisson.java:113)
	at org.redisson.Redisson.create(Redisson.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 37 more

**Comment by mrniko** [comment]
Check your classpath to ensure about jackson version. seems it's too old and not 2.7.4

**Comment by 1017727621** [comment]
thank you  due!
but  connections timeout to redis 3.0.7  .   im not sure connections  vmware centos 6.5  redis  server? 
ping 172.16.31.111  ok
Caused by: org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 10 were initialized. Server: /172.16.31.111:6379
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.16.31.111:6379

**Comment by jackygurui** [comment]
It seems that the port is not accessible. Can you try it with redis-cli ?

**Comment by 1017727621** [comment]
sure  redis-cli  -h172.16.31.111 -p 6379 No problem

**Comment by jackygurui** [comment]
Is it possible that you are running the `redis-cli` inside the vm while the Redisson is running on your host machine?

**Comment by 1017727621** [comment]
yes  redisson on my  win7 running    redis server in the vm 
i  Can't  do that?

**Comment by jackygurui** [comment]
I think the problem is your win7 host can't access the vm on port 6379. Can you try and use a telnet program from your win7 host to connect to the redis running inside the vm?

**Comment by 1017727621** [comment]
I am ever so grateful to you for ask to me    thank you

**Comment by jackygurui** [comment]
Thank you for choosing Redisson!

**Comment by ddpa** [comment]
Hello
Were you able to solve the first exception reported?
I'm having the same issue: [java.lang.NoSuchMethodError].  java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.addMixIn(Ljava/lang/Class;Ljava/lang/Class;)Lcom/fasterxml/jackson/databind/ObjectMapper;

How can a i force a compatible version for jackson libraries?

**Comment by mrniko** [comment]
@ddpa Hi! You should update jackson lib to 2.7.x and ensure that you're not mixing two different versions in classpath

**Comment by vtsgroup** [comment]
@ddpa How can update jackson version? Do we need update in Glassfish or Dependency in pom.xml?
