### ISSUE TITLE
putIfAbsent followed by addAndGet causes bad argument #2 to 'unpack' (data string too short)

### ISSUE THREAD

**Issue by andrewmilkowski** [redisson/redisson#827]
Hello , have peculiar situation where below works only first time around (reason for first API call is to establish "expire" on key as addAndGet does not allow one to specify expire)

so below works fine during first run, subsequent runs Redisson throws an exception (below at the end of this post)

thanks for any input on this

RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent");
Object  currValue = mapCache.putIfAbsent("4", 0L, 10000L, TimeUnit.SECONDS);
Object updatedValue = mapCache.addAndGet("4", 1L);
System.out.println("updatedValue: " + updatedValue);

------------

org.redisson.client.RedisException: ERR Error running script (call to f_04ca52da6f32fea58a7378efe5e857fbdc376470): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0xfe4a958b, /127.0.0.1:45434 => /127.0.0.1:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@34c88748[Not completed], command=(EVAL), params=[if redis.call('hexists', KEYS[1], ARGV[4]) == 0 then if tonumber(ARGV[1]) > 0 then redis.call('zadd'..., 3, test_put_if_absent, redisson__timeout__set:{test_put_if_absent}, redisson__idle__set:{test_put_if_absent}, 1490911908793, 0, 0, 4, 0], codec=org.redisson.codec.JsonJacksonCodec@7bb8b36e]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:267)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:831)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:346)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:254)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jackygurui** [comment]
Looks like the RMapCache needs to override the addAndGet and make it aware of packed value.

**Comment by andrewmilkowski** [comment]
thanks much for this is there a public repo I can draw this new patched build(jar from) ?

**Comment by mrniko** [comment]
@andrewmilkowski It's not released yet

**Comment by andrewmilkowski** [comment]
I just ran this patch and failed, 

it works for 

RMap<String, Object> map = redisClient.getMap("test_put_if_absent", StringCodec.INSTANCE);
map.putIfAbsent("4", 0L);
map.addAndGet("4", 1L);
map.putIfAbsent("4", 0L);
System.out.println(map.get("4"));

it fails for:  (subject of original defect...)

RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent",  StringCodec.INSTANCE);
Object currValue = mapCache.putIfAbsent("4", 0L, 10000L, TimeUnit.SECONDS);
Object updatedValue = mapCache.addAndGet("4", 1L);
System.out.println("updatedValue: " + updatedValue);

**Comment by mrniko** [comment]
Fixed
