### ISSUE TITLE
Encountered unregistered class ID: 32

### ISSUE THREAD

**Issue by 1017727621** [redisson/redisson#829]
jdk 1.7  redisson 2.8.2 kryo 3.03
> 
              RList<String> ll=null;
		RLock re = redisson1.getLock("lock");
		for (int i = 0; i < l1.size(); i++) {
			re.tryLock();
			 ll = redisson1.getList("phone",new KryoCodec());

			if (!ll.contains(l1.get(i))) {
				ll.addAsync(l1.get(i));
			} 
			re.unlock();
                }
		System.out.println("cus:="+ll);

> 

> 
     com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 32
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:781)
	at org.redisson.codec.KryoCodec$1.decode(KryoCodec.java:112)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:283)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at    io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
> 
  please tell me  why  kryo with DefaultClassResolver.readClass  to error
   i see #166     kryocodec    ` kryo.setReferences(false);`   was change

**Comment by jackygurui** [comment]
As per #166 suggests you need to register your classes with KryoCodec by using `KryoCodec(List<Class<?>> classes)` constructor.

**Comment by 1017727621** [comment]
i was try it   like that   but it was still no go cause by
 `com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 32`

> 
   	List<String> l1 = new ArrayList<String>();
		l1.add("755");
		l1.add("655");
		RList<String> ll=null;
		List<Class<?>>  list =new ArrayList<Class<?>>();
		list.add(Class.forName("java.lang.String"));
		RLock re = redisson1.getLock("lock");
		for (int i = 0; i < l1.size(); i++) {
			re.tryLock();
			 ll = redisson1.getList("phone",new KryoCodec(list));

			if (!ll.contains(l1.get(i))) {
				ll.addAsync(l1.get(i));
			} 
			re.unlock();
				
	
				
			
		}
		System.out.println("cus:="+ll);
>

**Comment by 1017727621** [comment]
please help me~ ！！！！

**Comment by mrniko** [comment]
@1017727621 What was the cause?
