### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by learn0208** [redisson/redisson#839]
`ENV：
    java version "1.6.0_38" (openjdk) | Apache Tomcat Version 6.0.47`

When i use redisson-all-2.8.2.jar and redisson-tomcat-6-2.8.2.jar two jars, i find this error in logs

`java.lang.UnsupportedClassVersionError: com/fasterxml/jackson/dataformat/yaml/YAMLFactory : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at org.redisson.config.Config.fromJSON(Config.java:594)
        at org.redisson.tomcat.RedissonSessionManager.start(RedissonSessionManager.java:146)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4788)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:803)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:780)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1080)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1003)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:507)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1322)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:325)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1069)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.core.StandardService.start(StandardService.java:525)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:759)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)`

It's not work, how to fix it ,thanks!
@shawyeok

**Comment by mrniko** [comment]
Problem is in Jackson library version. It's compiled with Java 7. Problem could be resolved by downgrade Jackson version

**Comment by mrniko** [comment]
Fixed
