### ISSUE TITLE
No field factory in class Ljava/net/URL

### ISSUE THREAD

**Issue by huayicheng2015** [redisson/redisson#840]
``` Java
                Config config = new Config();
                SingleServerConfig singleServerConfig = config.useSingleServer();
//                ReplicatedServersConfig singleServerConfig = config.useReplicatedServers();
                String address = redisResult.getHost().concat(":").concat(redisResult.getPort());
                singleServerConfig.setAddress(address);
                singleServerConfig.setSubscriptionConnectionMinimumIdleSize(Constant.SUBSCRIPTION_CONNECTION_MINIMUM_IDLE_SIZE);
                singleServerConfig.setSubscriptionConnectionPoolSize(Constant.SUBSCRIPTION_CONNECTION_POOL_SIZE);
                singleServerConfig.setConnectionMinimumIdleSize(Constant.CONNECTION_MINIMUM_IDLE_SIZE);
                singleServerConfig.setTimeout(Constant.TIME_OUT);
                singleServerConfig.setRetryAttempts(Constant.RETRY_ATTEMPTS);
                singleServerConfig.setRetryInterval(Constant.RETRY_INTERVAL);
//                singleServerConfig.setScanInterval(Constant.SCAN_INTERVAL);
                singleServerConfig.setReconnectionTimeout(Constant.RECONNECTION_TIME_OUT);
                singleServerConfig.setFailedAttempts(Constant.FAILED_ATTEMPT);
                singleServerConfig.setPassword(redisResult.getPassword());
                singleServerConfig.setSubscriptionsPerConnection(Constant.SUBSCRIPTIONS_PER_CONNECTION);
                redisson = Redisson.create(config);
```

Configure as above, but raise ```java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field factory in class Ljava/net/URL; (declaration of 'java.net.URL' appears in /system/framework/core-libart.jar)``` Exception.

**Comment by huayicheng2015** [comment]
```redisResult.getHost().concat(":").concat(redisResult.getPort()``` ----> a remote linux host like "123.123.123:4567"

**Comment by mrniko** [comment]
Which JVM do you use?

**Comment by huayicheng2015** [comment]
1.7

**Comment by mrniko** [comment]
Which vendor? oracle, openjdk or something?

**Comment by huayicheng2015** [comment]
Android

**Comment by mrniko** [comment]
Could you provide full stacktrace?

**Comment by huayicheng2015** [comment]
04-13 23:16:34.761 29442-29442/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.medzone.redisson, PID: 29442
                                                   rx.exceptions.OnErrorNotImplementedException: java.lang.NoSuchFieldException: No field factory in class Ljava/net/URL; (declaration of 'java.net.URL' appears in /system/framework/core-libart.jar)
                                                       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                       at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                                                       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                       at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
                                                       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                       at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23)
                                                       at android.view.View.performClick(View.java:5697)
                                                       at android.widget.TextView.performClick(TextView.java:10815)
                                                       at android.view.View$PerformClick.run(View.java:22526)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field factory in class Ljava/net/URL; (declaration of 'java.net.URL' appears in /system/framework/core-libart.jar)
                                                       at org.redisson.misc.URLBuilder.replaceURLFactory(URLBuilder.java:90)
                                                       at org.redisson.misc.URLBuilder.create(URLBuilder.java:110)
                                                       at org.redisson.config.SingleServerConfig.setAddress(SingleServerConfig.java:130)
                                                       at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:72)
                                                       at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:65)
                                                       at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                       at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23) 
                                                       at android.view.View.performClick(View.java:5697) 
                                                       at android.widget.TextView.performClick(TextView.java:10815) 
                                                       at android.view.View$PerformClick.run(View.java:22526) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                    Caused by: java.lang.NoSuchFieldException: No field factory in class Ljava/net/URL; (declaration of 'java.net.URL' appears in /system/framework/core-libart.jar)
                                                       at java.lang.Class.getDeclaredField(Native Method)
                                                       at org.redisson.misc.URLBuilder.replaceURLFactory(URLBuilder.java:77)
                                                       at org.redisson.misc.URLBuilder.create(URLBuilder.java:110) 
                                                       at org.redisson.config.SingleServerConfig.setAddress(SingleServerConfig.java:130) 
                                                       at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:72) 
                                                       at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:65) 
                                                       at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) 
                                                       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) 
                                                       at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23) 
                                                       at android.view.View.performClick(View.java:5697) 
                                                       at android.widget.TextView.performClick(TextView.java:10815) 
                                                       at android.view.View$PerformClick.run(View.java:22526) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by huayicheng2015** [comment]
``` Java
RxView.clicks(binding.btnRedisConfigure).subscribe(new Action1<Void>() {
            @Override
            public void call(Void aVoid) {
                Config config = new Config();
                SingleServerConfig singleServerConfig = config.useSingleServer();
//                ReplicatedServersConfig singleServerConfig = config.useReplicatedServers();
                String address = redisResult.getHost().concat(":").concat(redisResult.getPort());
                singleServerConfig.setAddress(address);
                singleServerConfig.setSubscriptionConnectionMinimumIdleSize(Constant.SUBSCRIPTION_CONNECTION_MINIMUM_IDLE_SIZE);
                singleServerConfig.setSubscriptionConnectionPoolSize(Constant.SUBSCRIPTION_CONNECTION_POOL_SIZE);
                singleServerConfig.setConnectionMinimumIdleSize(Constant.CONNECTION_MINIMUM_IDLE_SIZE);
                singleServerConfig.setTimeout(Constant.TIME_OUT);
                singleServerConfig.setRetryAttempts(Constant.RETRY_ATTEMPTS);
                singleServerConfig.setRetryInterval(Constant.RETRY_INTERVAL);
//                singleServerConfig.setScanInterval(Constant.SCAN_INTERVAL);
                singleServerConfig.setReconnectionTimeout(Constant.RECONNECTION_TIME_OUT);
                singleServerConfig.setFailedAttempts(Constant.FAILED_ATTEMPT);
                singleServerConfig.setPassword(redisResult.getPassword());
                singleServerConfig.setSubscriptionsPerConnection(Constant.SUBSCRIPTIONS_PER_CONNECTION);
                redisson = Redisson.create(config);
            }
        });
```

**Comment by huayicheng2015** [comment]
```String address = redisResult.getHost().concat(":").concat(redisResult.getPort());``` raises the exception

**Comment by huayicheng2015** [comment]
The next code line

**Comment by alextrieutuan** [comment]
I have same problem. Please fix it as soon as possible.

**Comment by mrniko** [comment]
Fixed

**Comment by huayicheng2015** [comment]
when release?
