### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by cbc356326350** [redisson/redisson#845]
Redisson 2.8.0

2017/04/19 04:30:42:306  WARN logging.Slf4JLogger:141 - Failed to mark a promise as failure because it has failed already: DefaultChannelPromise@1e3a7e78(failure: io.netty.handler.codec.EncoderException: java.lang.StackOverflowError), unnotified cause: io.netty.handler.codec.EncoderException: java.lang.StackOverflowError
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:63)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:815)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:795)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1027)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:301)
	at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:102)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:79)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1090)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1137)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1079)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.StackOverflowError
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)

**Comment by mrniko** [comment]
Fixed in 2.8.1 version https://github.com/redisson/redisson/issues/776

**Comment by cbc356326350** [comment]
I already upgrade version to 2.8.1, and there is another problem.

2017/04/20 18:57:44 188036  WARN logging.Slf4JLogger:151 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.Error: factory already defined
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.Error: factory already defined
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1077)
	at org.redisson.misc.URLBuilder.replaceURLFactory(URLBuilder.java:85)
	at org.redisson.misc.URLBuilder.create(URLBuilder.java:110)
	at org.redisson.cluster.ClusterNodeInfo.setAddress(ClusterNodeInfo.java:58)
	at org.redisson.client.protocol.decoder.ClusterNodesDecoder.decode(ClusterNodesDecoder.java:50)
	at org.redisson.client.protocol.decoder.ClusterNodesDecoder.decode(ClusterNodesDecoder.java:35)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:283)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
	... 15 more
2017/04/20 18:57:49 192534 ERROR cluster.ClusterConnectionManager$5:376 - Can't execute CLUSTER_NODES with /115.28.214.229:7002
org.redisson.client.RedisTimeoutException: Command execution timeout for /115.28.214.229:7002
	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:193)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:662)
2017/04/20 18:57:49 193420  WARN logging.Slf4JLogger:151 - An exception was thrown by org.redisson.cluster.ClusterConnectionManager$5.operationComplete()
java.lang.StackOverflowError
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
	at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)

**Comment by mrniko** [comment]
Seems this issue related to https://github.com/redisson/redisson/issues/828 Could you try version compiled from master branch?

**Comment by cbc356326350** [comment]
When do you release the 2.8.3 version?
