### ISSUE TITLE
Redisson 2.8.1,application can not start

### ISSUE THREAD

**Issue by qq5596629** [redisson/redisson#859]
2017/04/21 23:28:43 12283  INFO redisson.Version:41 - Redisson 2.8.1
2017/04/21 23:28:43 12530  INFO pool.ConnectionPool$2$1:137 - 5 connections initialized for /192.168.0.121:7001
2017/04/21 23:28:43 12532 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12535 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12531  INFO pool.ConnectionPool$2$1:137 - 5 connections initialized for /192.168.0.121:7003
2017/04/21 23:28:43 12539 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12545 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12551 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12555 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12558 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12561 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12565 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12568 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12569  INFO cluster.ClusterConnectionManager$2$1$1:294 - master: redis://192.168.0.121:7001 added for slot ranges: [[5461-10922]]
2017/04/21 23:28:43 12572 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12575 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12577  INFO cluster.ClusterConnectionManager$2$1$1:294 - master: redis://192.168.0.121:7003 added for slot ranges: [[0-5460]]
2017/04/21 23:28:43 12579 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12583 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12586 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12589 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12593 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12597 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
2017/04/21 23:28:43 12600 ERROR logging.Slf4JLogger:181 - Failed to submit a listener notification task. Event loop shut down?
java.lang.StackOverflowError
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2944)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1208)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1688)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2944)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1208)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1688)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
	at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
	at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:571)
	at io.netty.util.internal.logging.Slf4JLogger.error(Slf4JLogger.java:181)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:673)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:87)
......

**Comment by mrniko** [comment]
Please check your code. Seems you invoke shutdown right after start

**Comment by qq5596629** [comment]
sometimes application can start, but sometimes can not。it seems to be a random event

**Comment by wangazhang** [comment]
same problem！

**Comment by mrniko** [comment]
Please try latest version 3.4.0/2.9.0

**Comment by mrniko** [comment]
Fixed
