### ISSUE TITLE
java.lang.IllegalStateException: Can't decode replay

### ISSUE THREAD

**Issue by smigfu** [redisson/redisson#863]
I have this message quite often in my logs. There is a `StackOverflowException` happening right before that (though I am not sure whether these two correlate). Do you have an idea what is happening? Is the message too long to be processed? (Just for the context we have a pub/sub on expired keys.)

```
2017-04-26T15:51:45,881 | WARN | io.netty.channel.DefaultChannelPipeline | 2017-04-26T11:55:49,825_load_twoUserCollaborate_d4bd6e09-1bab-d0ff-b03f-823eb4c9442d | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Can't decode replay: *4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_501134d3-f81b-4ad8-dfb9-bc63bbe830a8.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_350da5f7-3827-b630-7744-e9c7ecbf62db.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$46
pack_350da5f7-3827-b630-7744-e9c7ecbf62db.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$85
fc_gzip_b028edc1-2a3a-8d08-5c13-fe25bd1de7de_b2106b913601c201e1687aa7da9f2938b6fc2d03
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_91fd49c4-4bd0-5f78-d0e1-f3f278ba6880.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$46
pack_30c173d4-9f54-5532-24f4-6cca218ca8f2.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$22
__keyevent@0__:expired
$46
pack_f1476d2d-d46f-506a-8f76-4e6e1a34aedd.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$22
__keyevent@0__:expired
$85
fc_gzip_dcd6dbfa-e6b5-3798-64ff-08331278ab61_b68a1cdb9552248089bb739e119929d56e1033d4
*4
$8
pmessage
$16
__keyevent@*__:*
$22
__keyevent@0__:expired
$46
pack_01fb66ff-6c32-07ef-5f15-ae7e009a1e9b.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_660999bc-d87b-73a1-3700-ee494e4e629a.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$46
pack_8cb9d5f8-bf22-e20a-fc22-6c43c6c2209f.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_7f32f80d-ef10-d9fa-0cbc-bc6907b41403.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$46
pack_d3c04450-7a2c-76d6-4694-d1a809373736.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_edfcb536-287a-7f63-7b42-909b5f6b815c.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$46
pack_60cc8f0a-98de-d61c-f6bd-8a90114d41bb.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$22
__keyevent@0__:expired
$45
pack_d1e992c7-ee8a-6b7a-360f-eb340e69d696.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_d1e992c7-ee8a-6b7a-360f-eb340e69d696.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_7e134dc6-9748-521c-5340-e97a1c790ed3.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_ce902045-ea2c-055d-87e2-ded21f156227.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_deba09f5-e7e0-879a-305b-fa0aaef2b12f.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$48
pack_775d43a6-c38e-51ff-72b8-a045871140d6.bitmap
*4
$8
pmessage
$16
__keyevent@*__:*
$22
__keyevent@0__:expired
$45
pack_436b03f5-2a47-c03a-36b5-c65df9fb830d.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$22
__keyevent@0__:expired
$48
pack_0ceea1c5-d2b3-3a28-0246-8116a1588dd8.bitmap
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_e931dc2d-de9a-696e-2c89-35ea0bd926f4.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$48
pack_96ebc9ff-32d9-f910-925d-911a6ac8b53a.bitmap
*4
$8
pmessage
$16
__keyevent@*__:*
$22
__keyevent@0__:expired
$46
pack_c52dee39-468b-4c5f-c9e1-337f2a8ca1be.pack
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_461227e4-88fd-9689-4c9c-f6453c3a4eca.idx
*4
$8
pmessage
$16
__keyevent@*__:*
$21
__keyevent@0__:expire
$45
pack_1a4904bc-3db3-c88b-9560-ea62d0a839c5.idx
*4
$8
pmessage
$16
```

**Comment by mrniko** [comment]
What is the cause of io.netty.handler.codec.DecoderException: java.lang.IllegalStateException ?

**Comment by smigfu** [comment]
I am not 100% sure. In the log on the same thread right before that I can see a `StackOverFlowError`but I don't really know if these two are related.

```
io.netty.handler.codec.DecoderException: java.lang.StackOverflowError
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422) [75:io.netty.codec:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [75:io.netty.codec:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [80:io.netty.transport:4.1.9.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017) [81:io.netty.transport-native-epoll:4.1.9.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:335) [81:io.netty.transport-native-epoll:4.1.9.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [77:io.netty.common:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [77:io.netty.common:4.1.9.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [81:io.netty.transport-native-epoll:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [77:io.netty.common:4.1.9.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [77:io.netty.common:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.StackOverflowError
	at org.redisson.client.handler.CommandDecoder.readBytes(CommandDecoder.java:468) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:279) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:313) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302) ~[?:?]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:337) ~[?:?]
```

**Comment by mrniko** [comment]
Fixed
