### ISSUE TITLE
Lcom/fasterxml/jackson/dataformat/avro/PackageVersion

### ISSUE THREAD

**Issue by huayicheng2015** [redisson/redisson#865]
```
04-27 09:56:07.361 3495-3495/com.medzone.redisson E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.medzone.redisson, PID: 3495
                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/fasterxml/jackson/dataformat/avro/PackageVersion;
                                                                        at org.redisson.codec.DefenceModule.<init>(DefenceModule.java:72)
                                                                        at org.redisson.codec.JsonJacksonCodec.init(JsonJacksonCodec.java:146)
                                                                        at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:102)
                                                                        at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:87)
                                                                        at org.redisson.codec.JsonJacksonCodec.<clinit>(JsonJacksonCodec.java:62)
                                                                        at org.redisson.config.Config.<init>(Config.java:101)
                                                                        at org.redisson.Redisson.<init>(Redisson.java:113)
                                                                        at org.redisson.Redisson.create(Redisson.java:154)
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:84)
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:65)
                                                                        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                                        at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23)
                                                                        at android.view.View.performClick(View.java:5697)
                                                                        at android.widget.TextView.performClick(TextView.java:10815)
                                                                        at android.view.View$PerformClick.run(View.java:22526)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.fasterxml.jackson.dataformat.avro.PackageVersion" on path: DexPathList[[zip file "/data/app/com.medzone.redisson-2/base.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.medzone.redisson-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.medzone.redisson-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                        at org.redisson.codec.DefenceModule.<init>(DefenceModule.java:72) 
                                                                        at org.redisson.codec.JsonJacksonCodec.init(JsonJacksonCodec.java:146) 
                                                                        at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:102) 
                                                                        at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:87) 
                                                                        at org.redisson.codec.JsonJacksonCodec.<clinit>(JsonJacksonCodec.java:62) 
                                                                        at org.redisson.config.Config.<init>(Config.java:101) 
                                                                        at org.redisson.Redisson.<init>(Redisson.java:113) 
                                                                        at org.redisson.Redisson.create(Redisson.java:154) 
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:84) 
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:65) 
                                                                        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) 
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) 
                                                                        at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23) 
                                                                        at android.view.View.performClick(View.java:5697) 
                                                                        at android.widget.TextView.performClick(TextView.java:10815) 
                                                                        at android.view.View$PerformClick.run(View.java:22526) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:158) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                    	Suppressed: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.avro.PackageVersion
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                        		... 24 more
                                                                     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by huayicheng2015** [comment]
#840 
Version: 2.9.0

**Comment by mrniko** [comment]
Are you using Avro codec on Android?

**Comment by mrniko** [comment]
Just add `jackson-dataformat-avro` into classpath as workaround

**Comment by mrniko** [comment]
Done

**Comment by huayicheng2015** [comment]
How to?

**Comment by mrniko** [comment]
use latest version

**Comment by huayicheng2015** [comment]
Is there a version named 2.9.1?

**Comment by mrniko** [comment]
Yes, it's in maven repo

**Comment by huayicheng2015** [comment]
Sorry, I can not find it.

**Comment by mrniko** [comment]
https://repo1.maven.org/maven2/org/redisson/redisson/2.9.1/

**Comment by huayicheng2015** [comment]
I mean jackson-dataformat-avro

**Comment by mrniko** [comment]
Since this dependency was added due to mistake it's removed in 2.9.1. So you don't need avro anymore. Just update Redisson.

**Comment by huayicheng2015** [comment]
All right

**Comment by huayicheng2015** [comment]
A new error occurs, android.os.NetworkOnMainThreadException

**Comment by mrniko** [comment]
Initialize Redisson in separate thread
