### ISSUE TITLE
org.redisson.client.RedisOutOfMemoryException: command not allowed when used memory > 'maxmemory'

### ISSUE THREAD

**Issue by sosojustdo** [redisson/redisson#866]
hello friend 
For blow code with stress test redisson client, but test_redisson_set method add loop items, have Exception message

`public class RedisClientTestUnit extends BaseTest{
	
	public static final int invocations = 1000;
	
	public static final int threads = 1;
	
	public static final int duration = 6000;
	
	@Rule
	public ContiPerfRule rule = new ContiPerfRule();
	
	@Autowired
	private RedissonTemplete<String, Object> redissonTemplete;
	
	@Before
	public void check_bean_is_not_null(){
		Assert.assertNotNull(redissonTemplete);
	}
	
	@Test
	@PerfTest(invocations = invocations, threads = threads, duration = duration)
	public void test_redisson_set(){
		for(long i=1; i<=100000; i++){
			System.out.println(redissonTemplete.hashCode());
			long start = System.currentTimeMillis();
			Order order = new Order(); 
			order.setOrderId(i);
			order.setOrderSn(UUIDUtil.randomString(10));
			redissonTemplete.set(String.valueOf(i), order);
			System.out.println("i:" + (System.currentTimeMillis()-start));
		}
	}
	
	@Test
	@PerfTest(invocations = invocations, threads = threads, duration = duration)
	public void test_redisson_get(){
		for(int i=1; i<=1000; i++){
			long start = System.currentTimeMillis();
			List<Order> orders = (List<Order>) redissonTemplete.get(String.valueOf(i));
			System.out.println(orders.get(0).getOrderSn());
			System.out.println("i:" + (System.currentTimeMillis()-start));
		}
	}
	
}`

**Comment by sosojustdo** [comment]
`Caused by: org.redisson.client.RedisOutOfMemoryException: command not allowed when used memory > 'maxmemory'.. channel: [id: 0x83b21e03, L:/10.16.6.42:54447 - R:/121.42.233.211:16479] data: CommandData [promise=org.redisson.misc.RedissonPromise@74f5c12a, command=(SET), params=[7412, com.llb.cloudyoung.order.pay.model.Order@3f357c9d], codec=org.redisson.codec.JsonJacksonCodec@7efba9a9]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:259)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:126)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by mrniko** [comment]
Such exception is always raisen if overcome Redis memory limit. This is a correct behaviour.
