### ISSUE TITLE
Issues with AvroCodec

### ISSUE THREAD

**Issue by Sylvain-Royer** [redisson/redisson#874]
Running redisson 2.9.1, jasckon dataformat 2.7.2.

I'm attempting to use AvroJacksonCodec with redisson client. This stack trace occurs when attempting to serialize and deserialize avro data from redis.

`Failed to mark a promise as failure because it has failed already: DefaultChannelPromise@60a37695(failure: io.netty.handler.codec.EncoderException: com.fasterxml.jackson.databind.JsonMappingException: Incompatible types: declared root type ([simple type, class com.sumologic.app.api.ProtocolContinuousQueryRecordList]) vs java.lang.String), unnotified cause: io.netty.handler.codec.EncoderException: com.fasterxml.jackson.databind.JsonMappingException: Incompatible types: declared root type ([simple type, class com.sumologic.app.api.ProtocolContinuousQueryRecordList]) vs java.lang.String
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:63)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:815)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:795)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1027)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:301)
	at org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:102)
	at org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:79)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1090)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1137)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1079)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible types: declared root type ([simple type, class com.sumologic.app.api.ProtocolContinuousQueryRecordList]) vs java.lang.String
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:262)
	at com.fasterxml.jackson.databind.SerializerProvider._reportIncompatibleRootType(SerializerProvider.java:1115)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:225)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1425)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1129)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsBytes(ObjectWriter.java:1025)
	at org.redisson.codec.AvroJacksonCodec$AvroExtendedMapper.writeValueAsBytes(AvroJacksonCodec.java:52)
	at org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:75)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:103)
	at org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:45)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 32 more
`

This is how the codec is being created (note, the environment is scala).

`  private val codec = new AvroJacksonCodec(
    classOf[ProtocolContinuousQueryRecordList],
    new AvroSchema(ProtocolContinuousQueryRecordList.SCHEMA$))`

It works when I use JsonJacksonCodec, but not with AvroJacksonCodec. Am I doing something incorrectly which would be causing this issue?

**Comment by mrniko** [comment]
Can you provide some test case to reproduce it?

**Comment by Sylvain-Royer** [comment]
Unfortunately, I can't seem to reproduce it outside of my codebase.  When I create a test case on the redisson repo, it seems to work correctly. As a note, I'm running my codebase in Java 1.7, but I'm building/running redisson tests in 1.8.

**Comment by Sylvain-Royer** [comment]
From what I can tell with my testing, the value being passed into `AvroExtendedMapper.writeValueAsBytes` is the key in the key/value pair. This is causing an exception when I try to encode the String as my passed in Avro Object. Is it expected behavior for both the key and value to be encoded by the Codec?

**Comment by mrniko** [comment]
> I think I might end up creating a new codec that has one encoder/decoder pair for key and one for values.

This should help you
