### ISSUE TITLE
CommandAsyncService blocks indefinitely [without OutOfMemoryError]

### ISSUE THREAD

**Issue by antonysychov** [redisson/redisson#889]
all application threads are blocked with stack trace
``
```
"thrift-worker-5" #68 prio=5 os_prio=0 tid=0x00007f575c85f000 nid=0x6e69 waiting on condition [0x00007f5754a9c000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e356d560> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:148)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:134)
	at org.redisson.RedissonBatch.execute(RedissonBatch.java:253)
```

redisson version 3.4.2
cluster configuration 

```
d61dd782a6545ad61e1443b081cc940b8b2bf4bb XXX:6382 slave 1b5e1e32fc5fcbb741dc8f17528e178cc43f72af 0 1495639973317 18 connected
df0f58cba6088e5f90dc7606603535ebd7b35d7d XXX:6381 slave be530716595b868ec75bba96377c2876822432fa 0 1495639973820 19 connected
be530716595b868ec75bba96377c2876822432fa XXX:6381 master - 0 1495639973819 19 connected 6070-10069
5765a883861af184e6807dc11cb9fd1c4c9a9748 XXX:6379 myself,master - 0 0 16 connected 12070-16383
17c6e10f6c25c97e390c36849514c0b268ca97e7 XXX:6380 slave 3c649506252fd43ef1c59ebbf2413d7cef9f36a7 0 1495639972817 20 connected
bad3c26e74a9dbfee472cfcef177bee87fd56d4c XXX:6379 slave 5765a883861af184e6807dc11cb9fd1c4c9a9748 0 1495639973017 16 connected
3c649506252fd43ef1c59ebbf2413d7cef9f36a7 XXX:6380 master - 0 1495639974422 20 connected 0-2069 10070-12069
1b5e1e32fc5fcbb741dc8f17528e178cc43f72af XXX:6382 master - 0 1495639974321 18 connected 2070-6069
```

**Comment by mrniko** [comment]
Could you describe a way how to reproduce?

**Comment by mrniko** [comment]
Anyway it can't be blocked indefinitely because of timeout setting for each Redis call
