### ISSUE TITLE
JaxsonCodec and abstract classes.

### ISSUE THREAD

**Issue by sheldon-sminq** [redisson/redisson#893]
We are storing objects that is an abstract class.

```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = Queue.class, name = "Queue"),
})
public abstract class BaseQueue {
```
The Jaxson codec fails while de-serializing the object, how to i set subType can you help me out with an example?

**Comment by sheldon-sminq** [comment]
The current exception i get

```
io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: a11c3335762a07c7 [dw-36 - PUT /v1/appointment/create]
! com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@class' that is to contain type id  (for class java.lang.Object)
!  at [Source: io.netty.buffer.ByteBufInputStream@71e3fe5e; line: 1, column: 6789]
! at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
! at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1061)
! at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:147)
! at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
! at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
! at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
! at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
! at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
! at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
! at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:82)
! at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:283)
! at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
! at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
! at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
! at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
! at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
```

**Comment by sheldon-sminq** [comment]
We currently shifted to a combination of SnappyCode with StringCodec, we do the JSON serialization/de-serizlization on our side.
