### ISSUE TITLE
JCache: NOAUTH Authentication required error after slave crash and restart

### ISSUE THREAD

**Issue by Rincewind99** [redisson/redisson#895]
I'm testing Redisson JCache with following configuration:

```
---
replicatedServersConfig:
  clientName: "bsfapp.localdomain"
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 64
  password: "123456"
  readMode: "MASTER_SLAVE"
  subscriptionMode: "SLAVE"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  nodeAddresses: ["redis://bsfapp.localdomain:6379", "redis://bsfapp2.localdomain:6379"]
  scanInterval: 2000
  database: 0
  slaveSubscriptionConnectionPoolSize: 50
  slaveSubscriptionConnectionMinimumIdleSize: 1
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.FstCodec> {}
codecProvider: !<org.redisson.codec.DefaultCodecProvider> {}
resolverProvider: !<org.redisson.liveobject.provider.DefaultResolverProvider> {}
redissonReferenceEnabled: true
useLinuxNativeEpoll: false

```

After crashing the slave (DEBUG SEGFAULT) the client reconnects but doesn't authenticate. I see endless errors like this:

```
ERROR  [11:36:28.961] [redisson-netty-1-2] o.r.c.ReplicatedConnectionManager -  NOAUTH Authentication required.. channel: [id: 0xdc3558ca, L:/192.168.56.132:36320 - R:bsfapp2.localdomain/192.168.56.134:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@7325eb72[Not completed], command=(INFO REPLICATION), params=[], codec=null] 
org.redisson.client.RedisException: NOAUTH Authentication required.. channel: [id: 0xdc3558ca, L:/192.168.56.132:36320 - R:bsfapp2.localdomain/192.168.56.134:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@7325eb72[Not completed], command=(INFO REPLICATION), params=[], codec=null]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:267)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
```

Is this a bug or wrong configuration?

**Comment by Rincewind99** [comment]
Seems like every server restart, regardless if master or slave triggers this error. Configuring with MasterSlaveServersConfig is working fine.

**Comment by jackygurui** [comment]
Can you try this again with the master branch please?

**Comment by Rincewind99** [comment]
No problems with master branch. I can restart master and slave servers without errors.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/842
