### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by pengfei-xu** [redisson/redisson#900]
Caused by: java.lang.StackOverflowError
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)
        at org.redisson.misc.URLBuilder$1.createURLStreamHandler(URLBuilder.java:78)

**Comment by domainname** [comment]
Hi @pengfei-xu, I encountered this issue in Redisson 3.2.4. Any idea? Will upgrading it to a newer version solve the problem?
