### ISSUE TITLE
Exception when removing entry from a map cache

### ISSUE THREAD

**Issue by stodge** [redisson/redisson#909]
I'm sure I'm missing something obvious here but I'm getting an exception when I remove an entry from the map cache, using the KryoNet encoder. I can put an entry into the map cache but I can't remove from it.

```
[redisson-netty-6-14] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 45, length: -516868041 (expected: range(0, 193))
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: index: 45, length: -516868041 (expected: range(0, 193))
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1353)
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.slice(AbstractUnpooledSlicedByteBuf.java:230)
	at io.netty.buffer.AbstractByteBuf.readSlice(AbstractByteBuf.java:836)
	at org.redisson.codec.MapCacheEventCodec.decode(MapCacheEventCodec.java:101)
	at org.redisson.codec.MapCacheEventCodec.access$100(MapCacheEventCodec.java:35)
	at org.redisson.codec.MapCacheEventCodec$1.decode(MapCacheEventCodec.java:47)
	at org.redisson.client.protocol.pubsub.PubSubMessageDecoder.decode(PubSubMessageDecoder.java:38)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:283)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:313)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:302)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	... 24 more
```

Any suggestions would be appreciated, thanks.

**Comment by mrniko** [comment]
Which OS do you use both for Redis and Redisson client?

**Comment by stodge** [comment]
The Redis server is Centos 6.9 and the client is Windows 10.

**Comment by mrniko** [comment]
Bug related only to current master branch version. Because I run Redis and Redisson on windows during tests running this line is the cause of your issue https://github.com/redisson/redisson/blob/bd76707828398ccfdc07535c53f8824f25707b6d/redisson/src/main/java/org/redisson/codec/MapCacheEventCodec.java#L96 You run client only on windows os

**Comment by stodge** [comment]
Ah I see thanks. Is this something that can/will be fixed?

**Comment by mrniko** [comment]
I have no idea how to fix yet.

> I'll see if I can install Redis on my Windows PC to prototype using Redisson.

Good idea :)
