### ISSUE TITLE
Can redisson use IBM JDK?

### ISSUE THREAD

**Issue by Madhu147** [redisson/redisson#913]
This is the error which i was receiving while with Oracle JDK this was working fine

Caused by: java.lang.NoSuchMethodError: io/netty/util/internal/PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater; (loaded from file:/app/jws-3.1/tomcat8/webapps/livpvnasci01.r1-core.r1.aig.netisoAbhishekOHTechStackJun6ReferenceDataService/WEB-INF/lib/netty-common-4.1.8.Final.jar by WebappClassLoader

        at io.netty.channel.ChannelOutboundBuffer.<clinit>(ChannelOutboundBuffer.java:92) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.<init>(AbstractChannel.java:421) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.<init>(AbstractNioChannel.java:218) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.<init>(AbstractNioByteChannel.java:72) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe.<init>(NioSocketChannel.java:458) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe.<init>(NioSocketChannel.java:458) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.newUnsafe(NioSocketChannel.java:455) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.newUnsafe(NioSocketChannel.java:50) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:80) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:54) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:98) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:88) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:81) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:74) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[na:na]

**Comment by mrniko** [comment]
Can't say, because I didn't run Redisson on IBM JDK.
