### ISSUE TITLE
configuration java.lang.IllegalArgumentException with 2.9.3

### ISSUE THREAD

**Issue by huayicheng2015** [redisson/redisson#917]
Version:**2.9.3**

```Java
                        Observable.just(1)
                        .map(new Func1<Integer, RedissonClient>() {
                            @Override
                            public RedissonClient call(Integer integer) {
                                Config config = new Config();
                                SingleServerConfig singleServerConfig = config.useSingleServer();
//                ReplicatedServersConfig singleServerConfig = config.useReplicatedServers();
                                String address = redisResult.getHost().concat(":").concat(redisResult.getPort());
                                singleServerConfig.setAddress(address);
                                singleServerConfig.setSubscriptionConnectionMinimumIdleSize(Constant.SUBSCRIPTION_CONNECTION_MINIMUM_IDLE_SIZE);
                                singleServerConfig.setSubscriptionConnectionPoolSize(Constant.SUBSCRIPTION_CONNECTION_POOL_SIZE);
                                singleServerConfig.setConnectionMinimumIdleSize(Constant.CONNECTION_MINIMUM_IDLE_SIZE);
                                singleServerConfig.setTimeout(Constant.TIME_OUT);
                                singleServerConfig.setRetryAttempts(Constant.RETRY_ATTEMPTS);
                                singleServerConfig.setRetryInterval(Constant.RETRY_INTERVAL);
//                singleServerConfig.setScanInterval(Constant.SCAN_INTERVAL);
                                singleServerConfig.setReconnectionTimeout(Constant.RECONNECTION_TIME_OUT);
                                singleServerConfig.setFailedAttempts(Constant.FAILED_ATTEMPT);
                                singleServerConfig.setPassword(redisResult.getPassword());
                                singleServerConfig.setSubscriptionsPerConnection(Constant.SUBSCRIPTIONS_PER_CONNECTION);
                                redisson = Redisson.create(config);
                                return redisson;
                            }
                        })
                        .compose(RxUtils.<RedissonClient>applyNewThreadSchedulers()).subscribe(
                        new Action1<RedissonClient>() {
                            @Override
                            public void call(RedissonClient redissonClient) {
                                Toast.makeText(RedisActivity.this, redissonClient.toString(), Toast.LENGTH_LONG).show();
                            }
                        },
                        new Action1<Throwable>() {
                            @Override
                            public void call(Throwable throwable) {
                                Log.e("RedisActivity", "configuration", throwable);
                            }
                        }
                );
```

I got the error message as followed when the code to the ```singleServerConfig.setAddress(address);```.

```
E/RedisActivity: configuration
                                                                 java.lang.IllegalArgumentException: Illegal character in scheme at index 0: [s4.*********.com]:????
                                                                     at java.net.URI.create(URI.java:733)
                                                                     at org.redisson.misc.URIBuilder.create(URIBuilder.java:37)
                                                                     at org.redisson.config.SingleServerConfig.setAddress(SingleServerConfig.java:129)
                                                                     at com.++++++.redisson.redis.RedisActivity$2$3.call(RedisActivity.java:102)
                                                                     at com.++++++.redisson.redis.RedisActivity$2$3.call(RedisActivity.java:95)
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                                                                     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
                                                                     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                                                                     at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
                                                                     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
                                                                     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10142)
                                                                     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                                                                     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10142)
                                                                     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                  Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: 1
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
                                                                     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) 
                                                                     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80) 
                                                                     at rx.Subscriber.setProducer(Subscriber.java:209) 
                                                                     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76) 
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) 
                                                                     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) 
                                                                     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) 
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10142) 
                                                                     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
                                                                     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
                                                                     at rx.Observable.unsafeSubscribe(Observable.java:10142) 
                                                                     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) 
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
```

But I promiss that ```address== s4.*********.com:????``` in ```String address = redisResult.getHost().concat(":").concat(redisResult.getPort());```   
Fortunately, there is no error with 2.9.2.

**Comment by mrniko** [comment]
With the new Redisson version you should define url including schema:

singleServerConfig.setAddress("redis://" + address);
