### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Redis server response timeout (6000 ms) occured for command

### ISSUE THREAD

**Issue by sdzzj** [redisson/redisson#934]
**异常信息：**
`org.redisson.client.RedisTimeoutException: Redis server response timeout (6000 ms) occured for command: (HGETALL) with params: [*****] channel: [id: 0x8891cdc5, L:/192.168.2.90:36476 - R:/192.168.2.36:6580]
        at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:646)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:745)`

**版本信息：**
redisson版本：3.4.3
redis 版本：3.2.8

**配置参数：**
`<bean id="StringCodec" class="org.redisson.client.codec.StringCodec" />
<redisson:client id="redissonClient" threads="0" netty-threads="0" codec-ref="StringCodec" use-linux-native-epoll="false">
	<redisson:cluster-servers
		client-name="m-redission"
		master-connection-pool-size="120" 
		slave-connection-pool-size="120"
		timeout="6000"
	>
		<redisson:node-address value="redis://${env.redis.cluster.node01}" />
		<redisson:node-address value="redis://${env.redis.cluster.node02}" />
		<redisson:node-address value="redis://${env.redis.cluster.node03}" />
		<redisson:node-address value="redis://${env.redis.cluster.node04}" />
		<redisson:node-address value="redis://${env.redis.cluster.node05}" />
		<redisson:node-address value="redis://${env.redis.cluster.node06}" />
	</redisson:cluster-servers>
</redisson:client>`

**服务器情况：**
       集群模式，三主三从

这个问题怎么解决？？？

**Comment by jackygurui** [comment]
map.readAllEntrySet()是通过HGETALL实现的，在元素很多的情况下这个命令是很费时的，而且阻塞服务端，你可以考虑用map.entrySet().iterator()来遍历。如果非要采用map.readAllEntrySet()的话，需要自己调整超时相关的参数。

**Comment by sdzzj** [comment]
这里的timeout设置6000 感觉不小了？（设置多少合适，有什么经验么？），field元素大概45个左右，这个数量应该不算大？

再一个就是，不单单是HGETALL，其他命令，例如GET、ZCAED偶尔也有类似异常。

**Comment by sdzzj** [comment]
org.redisson.client.RedisTimeoutException: Redis server response timeout (6000 ms) occured for command: (ZCARD) with params: [*****] channel: [id: 0x2682691a, L:/192.168.2.90:57987 - R:/192.168.2.237:6580]
        at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:646)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:745)

**Comment by sdzzj** [comment]
org.redisson.client.RedisTimeoutException: Redis server response timeout (6000 ms) occured for command: (EVAL) with params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, ****key****, history_visitor, ["3269261","3708635","3169232","3511565"]] channel: [id: 0xe133bc07, L:/192.168.2.90:52368 - R:/192.168.2.231:6580]
        at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:646)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jackygurui** [comment]
并发量大的情况下现有连接的列队满了造成的，需要调整retryAttempts和retryInterval这两个参数。

**Comment by jikuanyu** [comment]
[zzent]2019-05-06 13:39:02,271 ERROR Exception occured. Channel: [id: 0x9b5fd7b2, L:/192.168.144.77:62141 - R:192.168.119.10/192.168.119.10:9001] | CommandsQueue.exceptionCaught(153)
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[zzent]2019-05-06 13:39:32,337 ERROR Exception occured. Channel: [id: 0x1ac48504, L:/192.168.144.77:62156 - R:192.168.119.10/192.168.119.10:9001] | CommandsQueue.exceptionCaught(153)
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":30000,
      "retryAttempts":3,
      "retryInterval":15000,
      "reconnectionTimeout":30000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://192.168.119.10:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":11
    },
   "threads":16,
   "nettyThreads":32,
   "codec":{
      "class":"org.redisson.codec.FstCodec"
   },
   "transportMode":"NIO"
}

**Comment by jackygurui** [comment]
@jikuanyu 请依照模板开一个新的帖子。
