### ISSUE TITLE
No Such Method Error while upgrading from Redisson 2.2.4 to 2.9.3

### ISSUE THREAD

**Issue by Himanshu4** [redisson/redisson#938]
Caused by: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:55) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:98) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:88) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:81) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:74) ~[fg-api-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_101]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_101]
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:39)

**Comment by mrniko** [comment]
please check netty version in your classpath it should be 4.1.x

**Comment by Himanshu4** [comment]
Fixed that. There were two different netty versions on the classpath. Removing the old version solved the issue. Thanks.
