### ISSUE TITLE
Redisson 3.4.3. Wildfly. Sentinel. Netty exception : "Too many open files"

### ISSUE THREAD

**Issue by MelaninForbes** [redisson/redisson#957]
Hello! Could you please explain what's going on?

Using Redisson 3.4.3 in Java EE with Wildfly 10.1.0.Final on Linux in production. 
JRE 1.8.
This is how I configure it (may be not the excelent solution, but anyway...): 

```
@Singleton
@Startup
public class RedisClientBean{

private static RedissonClient client;

public RedissonClient getClient(){
    return client;
}

@PostConstruct
public void init(){
    Config config = new Config();
    try{
      config.useSentinelServers()
                .setMasterConnectionPoolSize(200)
                .setSlaveConnectionPoolSize(200)
                .setConnectTimeout(15000)
                .setReconnectionTimeout(3000)
                .setRetryAttempts(20)
                .setFailedAttempts(20)
                .setRetryInterval(3000)
                .setClientName("MyRedissonClient")
                .setMasterName("mymaster")
                .addSentinelAddress(.........);
      client = Redisson.create(config); 
    } catch (Exception e){
         throw new RuntimeException("Unable to init Redis connection : "+e.toString(), e);
    }
}

@PreDestroy
public void kill(){
    if(client != null){
        client.shutdown();
    }
}

}
```
And all the Stateless beans use this static RedissonClient instance to use API's business.

After some time (about several hours) I started to face to this stack trace (even if no invocations of Redisson API were done) :
```
23:04:32,009 ERROR [stderr] (redisson-3-257) Exception in thread "redisson-3-257" java.lang.IllegalStateException: failed to create a child event loop
23:04:32,009 ERROR [stderr] (redisson-3-257) Exception in thread "redisson-3-268" 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at org.redisson.client.RedisClientConfig.<init>(RedisClientConfig.java:42)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at org.redisson.connection.MasterSlaveConnectionManager.createRedisConfig(MasterSlaveConnectionManager.java:363)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:358)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at org.redisson.connection.SentinelConnectionManager.registerSentinel(SentinelConnectionManager.java:158)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at org.redisson.connection.SentinelConnectionManager.onSentinelAdded(SentinelConnectionManager.java:220)
23:04:32,009 ERROR [stderr] (redisson-3-257) 	at org.redisson.connection.SentinelConnectionManager$1$1.onMessage(SentinelConnectionManager.java:179)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:81)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at org.redisson.client.handler.CommandDecoder$1.run(CommandDecoder.java:366)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at java.lang.Thread.run(Thread.java:745)
23:04:32,010 ERROR [stderr] (redisson-3-257) Caused by: io.netty.channel.ChannelException: failed to open a new selector
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	... 19 more
23:04:32,010** ERROR [stderr] (redisson-3-257) Caused by: java.io.IOException: Too many open files
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at sun.nio.ch.IOUtil.makePipe(Native Method)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
23:04:32,010 ERROR [stderr] (redisson-3-257) 	... 23 more
23:04:32,010 ERROR [stderr] (redisson-3-268) java.lang.IllegalStateException: failed to create a child event loop
23:04:32,010 ERROR [stderr] (redisson-3-268) 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
23:04:32,010 ERROR [stderr] (redisson-3-268) 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
23:04:32,010 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
23:04:32,010 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
23:04:32,010 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
23:04:32,010 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
23:04:32,010 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.client.RedisClientConfig.<init>(RedisClientConfig.java:42)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.connection.MasterSlaveConnectionManager.createRedisConfig(MasterSlaveConnectionManager.java:363)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java:358)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.connection.SentinelConnectionManager.registerSentinel(SentinelConnectionManager.java:158)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.connection.SentinelConnectionManager.onSentinelAdded(SentinelConnectionManager.java:220)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.connection.SentinelConnectionManager$1$1.onMessage(SentinelConnectionManager.java:179)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:81)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at org.redisson.client.handler.CommandDecoder$1.run(CommandDecoder.java:366)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at java.lang.Thread.run(Thread.java:745)
23:04:32,011 ERROR [stderr] (redisson-3-268) Caused by: io.netty.channel.ChannelException: failed to open a new selector
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at 

io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
23:04:32,011 ERROR [stderr] (redisson-3-268) 	... 19 more
23:04:32,011 ERROR [stderr] (redisson-3-268) Caused by: java.io.IOException: Too many open files
23:04:32,011 ERROR [stderr] (redisson-3-268) 	at sun.nio.ch.IOUtil.makePipe(Native Method)
23:04:32,012 ERROR [stderr] (redisson-3-268) 	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65)
23:04:32,012 ERROR [stderr] (redisson-3-268) 	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
23:04:32,012 ERROR [stderr] (redisson-3-268) 	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
23:04:32,012 ERROR [stderr] (redisson-3-268) 	... 23 more
```
FDs examination with **lsof -p WILDFLY_PID | wc -l**  shows that count of opened FDs increases each minute.

Using **lsof -p WILDFLY_PID** we can see lots of rows like these :

```
java    11317 wildfly  427r     FIFO               0,10      0t0 1658137609 pipe
java    11317 wildfly  428w     FIFO               0,10      0t0 1658137609 pipe
java    11317 wildfly  429u  a_inode               0,11        0       8156 [eventpoll]
java    11317 wildfly  430r     FIFO               0,10      0t0 1658126709 pipe
java    11317 wildfly  431w     FIFO               0,10      0t0 1658126709 pipe
java    11317 wildfly  432u  a_inode               0,11        0       8156 [eventpoll]
java    11317 wildfly  433r     FIFO               0,10      0t0 1658126710 pipe
java    11317 wildfly  434w     FIFO               0,10      0t0 1658126710 pipe
java    11317 wildfly  435u  a_inode               0,11        0       8156 [eventpoll]
java    11317 wildfly  436r     FIFO               0,10      0t0 1658126711 pipe
java    11317 wildfly  437w     FIFO               0,10      0t0 1658126711 pipe
java    11317 wildfly  438u  a_inode               0,11        0       8156 [eventpoll]
java    11317 wildfly  439r     FIFO               0,10      0t0 1658126712 pipe
java    11317 wildfly  440w     FIFO               0,10      0t0 1658126712 pipe
java    11317 wildfly  441u  a_inode               0,11        0       8156 [eventpoll]
java    11317 wildfly  442r     FIFO               0,10      0t0 1658126713 pipe
java    11317 wildfly  443w     FIFO               0,10      0t0 1658126713 pipe
java    11317 wildfly  444u  a_inode               0,11        0       8156 [eventpoll]
java    11317 wildfly  445r     FIFO               0,10      0t0 1658126714 pipe
```

**ulimit -a** gives me **nofiles = 64000** soft and hard, and it is said to be good for production environment. 
How to deal with it?
(Fortunatelly the problem had some not excellent solution : I switched to **single server** configuration, and that worked for me, but how about API's sentinel configuration?)

By the way since Redisson uses netty, how to (or should I at all) correctly deal with **EventLoopGroup**, mentioned in this theme with almost the same issue ? : [https://github.com/netty/netty/issues/639](url)

As far as I understood from that article, EventLoopGroup should be shared between clients. 
But EventLoopGroup is not mentioned in Redisson documentation at all (Am I wrong?)

**Comment by mrniko** [comment]
Hi,

Sure it's important to less EventLoopGroup instances as you can.

> But EventLoopGroup is not mentioned in Redisson documentation at all (Am I wrong?)

Redisson allows to specify it through [Config.eventLoopGroup](https://github.com/redisson/redisson/wiki/2.-Configuration#eventloopgroup) parameter.
https://github.com/redisson/redisson/wiki/2.-Configuration#eventloopgroup

**Comment by MelaninForbes** [comment]
Hi. 
Thanks for the reply, I'll check it out later, 'cause we decided to use single server mode in couple with haproxy.
Nevertheless EventLoopGroup approach (code example) while using sentinel configuration is worth mentioning in Wiki.
