### ISSUE TITLE
how to set comparator when using priority queue

### ISSUE THREAD

**Issue by ouchengeng** [redisson/redisson#960]
Hi, I'm new to redisson. And I'm learning using priority queue with customized comparator. My code works well for the first time, but fails the second. Seems it cannot load the comparator class.
Here's my code.
`	public static void test() {
		Config config = new Config();
		config.setUseLinuxNativeEpoll(false);
		config.useSingleServer().setAddress("redis://0.0.0.0:6379");
		RedissonClient redisson = Redisson.create(config);
		RPriorityQueue<Integer> queue = redisson.getPriorityQueue("Queue2");
		queue.trySetComparator(new MyComparator());
		queue.add(1);
		queue.add(2);
	}
`
`
class MyComparator implements Comparator<Integer> {

		@Override
		public int compare(Integer o1, Integer o2) {
			// TODO Auto-generated method stub
			return o1 - o2;
		}
		
}`

The exception:
`Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalAccessException: Class org.redisson.RedissonPriorityQueue can not access a member of class MyComparator with modifiers ""
	at org.redisson.RedissonPriorityQueue.loadComparator(RedissonPriorityQueue.java:134)
	at org.redisson.RedissonPriorityQueue.<init>(RedissonPriorityQueue.java:102)
	at org.redisson.Redisson.getPriorityQueue(Redisson.java:617)
Caused by: java.lang.IllegalAccessException: Class org.redisson.RedissonPriorityQueue can not access a member of class MyComparator with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at org.redisson.RedissonPriorityQueue.loadComparator(RedissonPriorityQueue.java:129)
`

So anybody can tell me how to write customized comparator for priority queue.
Thanks so much !

**Comment by mrniko** [comment]
Comparator class should be `public static`
