### ISSUE TITLE
reactor/fn/Supplier : Unsupported major.minor version 51.0 (unable to load class reactor.fn.Supplier)

### ISSUE THREAD

**Issue by cbc356326350** [redisson/redisson#969]
When i use redisson 2.9.4 , i find this error in logs

```
java.lang.UnsupportedClassVersionError: reactor/fn/Supplier : Unsupported major.minor version 51.0 (unable to load class reactor.fn.Supplier)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2948)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1208)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1688)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
	at org.redisson.RedissonBatch.<init>(RedissonBatch.java:68)
	at org.redisson.Redisson.createBatch(Redisson.java:571)
```

**Comment by mrniko** [comment]
Fixed
