### ISSUE TITLE
Exception in thread "redisson-netty-17-12" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy

### ISSUE THREAD

**Issue by fsindustry** [redisson/redisson#975]
I use redisson with springboot，throw the following Exception when starting:

Exception in thread "redisson-netty-17-12" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
    at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
    at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
    at ch.qos.logback.classic.Logger.warn(Logger.java:692)
    at io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:861)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
please add logback lib into your classpath
